### ISSUE TITLE
Comparator Tab / Light Table / Inspector

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#1474]
Originally reported on Google Code with ID 1490

```
I found this feature request in the forum (http://rawtherapee.com/forum/viewtopic.php?f=2&t=2991&p=22116&hilit=collections#p22116),
so parking it here for tracking.

It would be very helpful to have an image comparator tab in RT.
UI may be similar to that of the Editor in the single tab mode when B/A is turned on.
Comparator should support the following functions:
- allow to load 2 (or more) images
- allow synchronous scrolling and zooming of the loaded images.
- allow rating/color labeling loaded images

Additionally, one option (could be simpler to implement) would be to hide away the
toolbox and history; another option - to allow user to keep the toolbox & history,
thus allowing to apply changes to the selected images that are loaded into comparator.

Essentially comparator is a blend of the file browser (one can view multiple images,
rate, multi-edit) and editor's B/A synchronous zooming & scrolling.

Additional important aspect, difference from the file browser implementation: I think
comparator should loaded from a file list,
generated based on user's selection. Implementation of the file list support will eventually
be helpful for collections (discussed earlier).

Implementation of the comparator would likely be easier when imaging pipelines in RT
are straightened out and unified.

```

Reported by `michaelezra000` on 2012-07-14 11:05:24

**Comment by Beep6581** [comment]
It would be really great if the Inspector could:
- Zoom-to-fit,
- Show images zoomed-to-fit fullscreen, allowing the user to open the next/previous image and to rate or delete the current image.

**Comment by agriggio** [comment]
I was considering changing the inspector to open full screen (with optional zoom to fit) when pressing 'z' in the file browser, inspired by darktable. I wasn't planning to do rating and navigation though. any interest?

**Comment by heckflosse** [comment]
@agriggio absolutely!

**Comment by rfranke** [comment]
This thread hasn't been active for a while. I'd like to take it up as I'm really missing a fullscreen preview for selecting photos in the file browser. Additionally, I find it crucial to see photos with the full monitor resolution to overcome the mushy look under macOS, see #5591. 
First investigations look promising. The 'z' key is already used for some filter feature though (filter all edited photos? -- it's not documented at http://rawpedia.rawtherapee.com/Keyboard_Shortcuts).
