### ISSUE TITLE
Preview image distorted when zoom to 33% or 50% using a lens correction profile in combination with 'Auto fill'

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#1791]
Originally reported on Google Code with ID 1807
```
When using a lens correction profile, the preview image at 50% zoom is broken. With
some Canon profiles, it not zoom to 50%, but to maximum depth. Other profiles (like
the Pentax for the Amsterdam photo sample) produces a extremly distortion at 50%.

You can download a sample image with the lense profile at http://www.terminal.io/tmp/4623/example.zip

Steps to reproduce:

- Open the photo
- zoom to 50%
- load the lens correction profile

```

Reported by `cytrinox` on 2013-03-26 20:29:29

**Comment by Beep6581** [comment]
Options:
1- Don't show the LCP's effect in preview at all,
2- Keep the buggy behavior as is,
3- Automatically disable Auto-fill from 33% upwards (either just from the preview or completely)
4- Automatically disable Auto-fill when enabling LCP
5- Fix the code so LCP works well with Auto-fill at all zoom levels.


1, 2 and 3 are unacceptable and from the discussion it seems 5 is not to be expected. This leaves us with 4. Any objections?

**Comment by Beep6581** [comment]
Let's implement point 4 - Automatically disable Auto-fill when enabling LCP. The fact of Auto-fill being disabled should be reflected in history so that the user gets some feedback that this was done.

Starting point:
```
diff --git a/rtgui/lensprofile.cc b/rtgui/lensprofile.cc
index a7a6344..0362dc1 100644
--- a/rtgui/lensprofile.cc
+++ b/rtgui/lensprofile.cc
@@ -167,6 +167,7 @@ void LensProfilePanel::onUseDistChanged()
     useDistChanged = true;
 
     if (listener) {
+        listener->panelChanged (EvTransAutoFill, M("GENERAL_DISABLED"));
         listener->panelChanged (EvLCPUseDist, ckbUseDist->get_active() ? M("GENERAL_ENABLED") : M("GENERAL_DISABLED"));
     }
 }
```
It sends a message to the history panel, but doesn't actually disable Auto-fill yet.

**Comment by Beep6581** [comment]
The commit above, in branch lcpautofill, disables Auto-Fill when loading an LCP file in non-batch mode and when enabling LCP Distortion Correction in non-batch mode. In both cases you get notified about this via the History panel.

It does not disable Auto-Fill when you load a PP3 which has both enabled, because the idea is that by the time you create such a PP3 you are well aware of the issue and if you have both enabled then you did that knowingly.

**Comment by Beep6581** [comment]
Pull request opened:
https://github.com/Beep6581/RawTherapee/pull/3318

**Comment by Floessie** [comment]
Fixed by @Beep6581 and me in  8b5cf38.

**Comment by Beep6581** [comment]
There is a bug where if you close a photo with Auto-Fill enabled, regardless whether an LCP is used or not, and you restart RawTherapee (crucial, cannot reproduce this without restarting RT), then the photo will load with Auto-Fill disabled if you re-open it in the Editor tab.

**Comment by Beep6581** [comment]
Ah there already is an issue for the bug.
