### ISSUE TITLE
Wrong White Level for Canon 550d

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#1906]
Originally reported on Google Code with ID 1922
```
I open this issue to have a dedicated one for Canon 550D white point.

It is not the usual case where the WL is wrong for some ISOs, it is wrong higher for
every ISO (by 1.2 for 100-160-200-400-... and by 1.05 for 200-400-800...). So a correction
is necessary eitherway. 

It has already reported as wrong 
http://rawtherapee.com/forum/viewtopic.php?f=1&t=4457#p33109
http://code.google.com/p/rawtherapee/issues/detail?id=1037#c9
http://code.google.com/p/rawtherapee/issues/detail?id=1037#c10

ourmark (Mark Anderson) measured white levels at various ISOs

ISO     decimal   hex

100     13584   0x3510
200     15304   0x3bc8
400     15304   0x3bc8
800     15304   0x3bc8
1600   15305   0x3bc9
3200   15307   0x3bcb
6400   15311   0x3bcf
12800 15319   0x3bd7

On the above I have to add that the lowest White Level I've found for ISOs 200-400-800...
is at 15278 (Imaging resource ISO12800, blue channel http://216.18.212.226/PRODS/T2I/FULLRES/T2IhSLI12800_NR0.CR2)
and there is a possibility that when using in-camera long exposure denoise (by black
frame) or hi ISO NR the white point is even lower at around 15200. 

Adobe sets 
WL at 12876 for ISO 100 (and maybe ISO 160-320-...). I think it's too low for ISO100
but maybe OK for 160-320.. I cannot find any samples at "intermediate" ISOs .. 

WL at 15000 for ISO 200-400-800... a bit conservative but on the safe side with only
1/20 stops highlights lost.

I think a WL at 15200 (0x3b60) or 15000 (0x3a98) is OK for a generally correct single
value (ISos 200-400.. and 125-250-500..) and the exception will be ISOs 100-160-320-640
.. which will need a 1.14 linear correction.
Or maybe use 13500 (0x34bc) to be correct at the base ISO and somehow mention that
we can use 0.85 linear correction to save some highlights when we are at ISOs 125-200-250-400-500-...

In any case for a full characterization and in order to start building a database for
issue http://code.google.com/p/rawtherapee/issues/detail?id=1752 we need samples with
burned areas 

At all ISOs 100-125-160-200-250-320.... shot with and without long exposure or hiISO
NR, shot at midle apperture settings (f/5.6) and at wide apertures (Canon digitally
amplifies raw values when apperture is wider than f/2.8).
```

Reported by `iliasgiarimis` on 2013-07-06 18:47:04

**Comment by Beep6581** [comment]
@iliasg can we close?

**Comment by iliasg** [comment]
For 550D yes, as it's covered by camconst.json, just wait a bit to check if we are OK with the alternate names 550D appears (T2i, Kiss X4) ...

**Comment by iliasg** [comment]
No "Canon EOS Rebel T2i" is not recognized to be in camconst.json so for the moment we have to change 
`"make_model": "Canon EOS 550D", `
with
`"make_model": [ "Canon EOS 550D", "Canon EOS Rebel T2i", "Canon EOS Kiss X4" ],`

This brings up another desired feature for camconst.json i.e. to recognize by "CanonModelID" tag (if it exists) instead of "Model" tag .. I think Dcraw works this way ;).  

@heckflosse  .. I can start to fill all such cases (alternate model names) if the above request is expected to take long .. what do you think ?.

**Comment by iliasg** [comment]
@heckflosse I was wrong .. RT uses the camconst.json data even if it reports (on console) that it doesn't ("no constants exist in camconst.json for Canon EOS T2i") .. so we only need to correct the report ;) 
.. but now I think that it's good for the users if we include the alternate names anyway. Additionally this is needed when a new model is not supported by the merged Dcraw version. 
.. so I will procceed with filling this info in the next days  (I am away from home with limited time / resources).
@Beep6581 I think we can close this issue ..

**Comment by heckflosse** [comment]
@iliasg Ilias, the solution to include alternate names is the most readable for users of rt. So I'm completely with you to add alternate names to camconst.json and not using cryptic codes (as in dcraw).

**Comment by Beep6581** [comment]
Including alternate names is good, at least for me :) Because it means I can more easily grep the file for whichever model I'm looking for.

I will close this issue as the 550D support is done, and we handle the alternate names in #3298.
