### ISSUE TITLE
The "clipshadow indicator" seems not to work as expected

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#1926]
Originally reported on Google Code with ID 1942

```
Hi,
I put all relevant files in http://filebin.net/9cqi31lyuw
When I load the raw file and hit ">" some parts of the picture are highlighted even
if I do not see why, 
They do not look that dark (the timber frame for example).
May be I do not know how to set up that feature?
Best regards
```

Reported by `dgaudry@condorcet93.fr` on 2013-08-06 15:50:05

**Comment by midluk** [comment]
Also noticed this an I find it quite annoying.
I have an image with a really bright yellow that is marked as clipped shadow because the blue channel is near zero. I can't think of a good use case for this information. In my opinion the clipped shadow indication should always be based on the luminance and the maximum (instead of the minimum) of the individual channels.

**Comment by midluk** [comment]
I have now implemented this for me locally, if you would accept such a change, I can publish the patch.

**Comment by heckflosse** [comment]
@midluk We really appreciate getting patches/pull requests. But we will decide whether to accept them after reviews, not before ;-)

**Comment by Beep6581** [comment]
The way RT currently works, enabling the clipped shadows indicator shows you areas where any channel is clipped when in "preview all channels" mode, i.e. standard preview. If you additionally enabled previewing of say the green channel, then you will see only areas where the green channel is clipped. If you only want to see areas where all channels are clipped, you enable preview of the luminosity channel. That's neat and powerful.

The proposed patch changes the behavior in "preview all channels" mode by showing only areas where all channels are clipped (below the threshold), while still allowing the user to preview the individual R, G, B and L channels. I'd say that's an improvement.

**Comment by midluk** [comment]
I had some more thoughts about the situation and it came to my mind that seeing ANY channel clipping might be useful when adjusting the black slider in exposure tool. Does the black slider work on individual channels or on luminance (no hard clipping should occur then)?
