### ISSUE TITLE
Change tmp location in RT

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#1989]
Originally reported on Google Code with ID 2005
```
My machine has /tmp cached to RAM.  Whenever, RT exports images to gimp, the huge 16bit
TIFF file is loaded twice in memory (once in /tmp and once by gimp).  It would be super
nice if we could change the path of RT temporary export directory.


Archlinux-64bit.

```

Reported by `ayr035` on 2013-10-15 03:52:58

**Comment by Beep6581** [comment]
Status?

**Comment by Hombre57** [comment]
I have to use /tmp for my pp3 patch, so I'm using the TMP environment variable. I forgot about this issue, but the simplest way to handle this issue (in a developer point of view) is to create 2envenvironment variable, e.g. RTTMP_SMALL and RTTMP_BIG. If they doesn't exists, we fall back to TMP.

I hope to be ready for the next w.e. (in 7 days).

**Comment by Beep6581** [comment]
I think it would also solve the OP's needs if RT simply used /tmp/rawtherapee-temp/ with no version number in the name so that there is nothing to predict, then he could simply make that folder a symlink to anywhere else. But it's your choice and I leave it in your hands :)

**Comment by Hombre57** [comment]
To be more portable, environment variable are easier to create on Windows than symlink I guess, so I'll chose that. And you know what ? This temp directory will have a RawTherapee/Big and /Small subdirectories, so both solutions will be available ;)
