### ISSUE TITLE
Ideas for a default profile to produce predictable "camera-like" output

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#2055]
Originally reported on Google Code with ID 2071

```
Autolevels are today mainly used to make the first open of an image to look good (it's
used in the default profile). I'd prefer if first open should would just look similar
to a standard in-camera jpeg, ie just a tonecurve to brighten and compress highlights,
and that's it.

I've attached how such a tonecurve looks. Not sure if it can be achieved with the Exposure
box sliders. Try open a file, select the neutral profile (make sure highlight recovery
is also at 0 if you don't have bleeding edge when this is fixed), and then apply this
type of curve -- you'll see how very similar it becomes to the camera's JPEG output.

I think autolevels should not be included in any of the bundled profiles, and maybe
not even be saved into the .pp3 when enabled. Instead just seen as a settings "assistant",
you press once and get some values as a starting point for more advanced processing.
I could be convinced otherwise though, but I certainly don't think it's good to have
in the Default profile.

Why do I want this? Because ideally I'd like that you could dump all your raw photos
from a shoot on RT and do nothing and get predictable output. Autolevels is not good
to have in such a situation, it will try to correct an underexposed image, expand contrast
in low contrast conditions etc. A fixed curve (or corresponding) will give you something
that looks like normal "unprocessed" camera output.

It's also what basically all other raw converters do, default profile is something
stable similar to default camera jpegs. A few converters do have an "autolevels" function
(Lightroom has it for example), but it's not something that gets enabled per default,
as the results generally require further tuning by a human operator.

What do you think?
```

Reported by `torger@ludd.ltu.se` on 2013-11-20 19:25:54

**Comment by Beep6581** [comment]
Currently some DCPs have a curve and some don't, and so opening a photo results in:
* a flat image if your default raw PP3 has auto-levels disabled and the DCP lacks a curve,
* a nice image if your default raw PP3 has auto-levels disabled and the DCP has a curve,
* an nice image if your default raw PP3 has auto-levels enabled and the DCP lacks a curve,
* an over-exposed image if your default raw PP3 has auto-levels enabled and the DCP has a curve.

There are several ways of handling this, I will list them in order of my preference:
1. Use @agriggio's new histogram-matching feature by default, so that the raw file always looks very similar to the out-of-camera JPEG. The downside is that this feature does not exist yet, and we don't know what weaknesses it will have if and when it does exist, for example will it handle low-key shots, or shots of the moon, will it take Auto Levels and the DCP Tone Curve into account?
2. Use a custom Exposure Tone Curve, with Auto Levels disabled and DCP Tone Curve disabled. The curve is editable, and it's clear to the user what's happening. The result would always be predictable. The only downside is that the tone curve would be a one-size-fits-all. Despite this, we know that it is possible to have a tone curve which works well with most cameras, because that's what the DCP tone curve does. I attached the DCP curve, and if we choose this option then I'm suggesting that we use it as Tone Curve 1 in "Film-Like" mode: 
[DCP tone curve.rtc.txt](https://github.com/Beep6581/RawTherapee/files/1628580/DCP.tone.curve.rtc.txt)
3. Have RawTherapee use Neutral by default for both raw and non-raw photos. This would enforce the idea that RawTherapee shows you the "real raw data" and the user is responsible for developing it, and it would avoid a bucket-full of problems. The only downside is that new users would not be wow'd by a nice image, though as you can see by the four points above that's not always currently the case either. The result would always be predictable.
4. Use Auto Levels in the default PP3 with the DCP tone curve disabled. The downside is that AL has a lot of issues, some of which will probably never get fixed. The result would not be predictable.
5. Use DCP Tone Curve by default with Auto Levels disabled. The result would be predictable only among raw files coming from the same camera, and not predictable when opening photos from various cameras.

One thing I am sure of is that our current "Default*" profiles need to change due their unpredictable results and not taking the DCP Tone Curve into account, and it would be nice to do this for 5.4.

**Comment by agriggio** [comment]
@Beep6581 I can try working on integrating histogram matching, but realistically I'm not sure I can do it before 5.4 (unless you want to delay 5.4 even further...).
Among the options above, I'd go for 2. If you want something more sophisticated, we could bundle profiles with "typical" tone curves for various camera brands (these could be generated by an enhanced version of my histogram matching script that takes the median of a series of shots for example), and then use dynamic profiles by default to activate the proper tone curve for the given camera maker (falling back to a generic one). This would also serve as an example of dynamic profile rules for new users...
Or do you think this is just too complicated and not worth it?

**Comment by heckflosse** [comment]
@agriggio +1 for the histogram matching, but also for doing that for 5.5!

**Comment by Beep6581** [comment]
@agriggio as @heckflosse wrote - would be cool at some point to have this, but not necessarily for 5.4.
If RT will have this feature in the future (even if it won't but especially if it will), then no point spending time on making median-average curves - we can't realistically do that for more than a few camera models anyway, I assume models from the same maker are not consistent so we would need to deal with "sets", and there are better ways of spending the time it would take...

**Comment by agriggio** [comment]
I was thinking about generic camera *brands*, not individual models. And it wouldn't even need to be accurate, just in the ballpark. We could even use fake names to make this clear (say, "Nikonian", "Canonical", "Sonyc"... :stuck_out_tongue_winking_eye: ) I'm partially kidding, but I thought it could be feasible. Anyway, not a big deal, as I wrote option 2 would still be better than the current default IMHO.

**Comment by Beep6581** [comment]
I'm guessing here, but I don't think it's likely that my 12 year old Pentax K10D's curve would look like a Pentax K-1's curve, ditto for other brands. I looked at all of your histogram-matched PP3s from the forum and they weren't that different from each other, so I think given that we're already accepting variation between the OOC-JPEG and the suggested brand-median result, we can cut a lot of work out by taking it one step further and thinking of our DCP curve (which I'm suggesting to ship as an editable Exposure Tone Curve 1 instead) as a median of all the brand-median curves ;)

I'm not opposing the idea, I just don't think it's time well spent and not future-proof if RT is to have the histogram-matching feature some day.

Having said that, it occurred to me that, for curiosity's sake, we could run your python script directly on the RPU server which already has a collection of unique raw files per model (20GB, though ideally we would need many raw files per model). This is the folder structure:
http://raw.pixls.us/data/
@agriggio if you could edit your script so that it can make those median curves by make, @andabata was willing to run it directly on the server for us.

**Comment by agriggio** [comment]
let's go with the simple solution

**Comment by agriggio** [comment]
Now that we have histogram matching, how about this for a default pp3?

```text
[Version]
AppVersion=5.4
Version=330

[Exposure]
Auto=false
Clip=0.02
CurveMode=Perceptual
CurveMode2=Perceptual
Curve=0;
Curve2=0;
HistogramMatching=true

[Sharpening]
Enabled=true
Method=usm
Radius=0.5
Amount=200
Threshold=20;80;2000;1200;
OnlyEdges=false
EdgedetectionRadius=1.9
EdgeTolerance=1800
HalocontrolEnabled=false
HalocontrolAmount=85
DeconvRadius=0.75
DeconvAmount=75
DeconvDamping=20
DeconvIterations=30

[White Balance]
Setting=Camera
Equal=1
TemperatureBias=0

[Color Management]
InputProfile=(cameraICC)
ToneCurve=false
ApplyLookTable=false
ApplyBaselineExposureOffset=true
ApplyHueSatMap=true
BlendCMSMatrix=false
DCPIlluminant=0
WorkingProfile=ProPhoto
OutputProfile=RT_sRGB
OutputProfileIntent=Relative
OutputBPC=true
Gammafree=default
Freegamma=false
GammaValue=2.2200000000000002
GammaSlope=4.5

[LensProfile]
LcMode=lfauto
LCPFile=
UseDistortion=true
UseVignette=true
UseCA=false

[RAW]
CA=true

[RAW Bayer]
Method=amaze

[RAW X-Trans]
Method=3-pass (best)
```

**Comment by Beep6581** [comment]
@agriggio I was thinking of something very similar. I'm not sure what to do with the DCP look table - I think it should be enabled by default since we're using a tone curve in FIlm-Like mode by default. @atorger what do you think?

**Comment by Floessie** [comment]
Apart from the DCP look table, what about re-enabling HLR via default profile? While it was almost always active in the past due to #4249, nowadays it's always disabled.

**Comment by Beep6581** [comment]
I propose to delete our current `Default*` PP3s, to bundle all 6 of the following profiles, and to set either "`Auto-Matched Curve - ISO Low`" or "`Standard Film Curve - ISO Low`" as the default for raw files:
https://filebin.net/is4tqh4qcqrrmf3v

Thoughts, and stuff:
1. I think naming a profile "Default" discourages users from changing it. Users should adapt the default profile to their taste. As such, none of these profiles have the word "default" in their name.
2. There are two sets of 3 profiles. The difference between each set is that one uses the new histogram matching feature, while the other uses an editable Exposure > Tone Curve 1 in the same shape as that which we include in our DCP profiles.
3. We know that users like the curve in the DCP profiles. The curve shape comes from DCamProf/ACR.
4. We also know that the histogram matching feature works well.
5. Of all the input profiles we ship, relatively few contain a DCP curve. As such, it is not possible to provide a consistent experience to our users if we rely on DCP curves. Instead, the "Standard Film Curve" profiles use the exact same curve, but placed in Exposure > Tone Curve 1 in Film Simulation mode (same as used when activating the DCP Tone Curve). This makes it immediately clear that a curve is being used, and users are free to modify its shape.
6. The DCP Look Table option is enabled by default, though it only affects those few camera models whose DCP profiles we ship. The DCP Tone Curve option is disabled by default.
7. All these profiles contain only those keys and sections which are actually used. This gives the user flexibility:
    * The user can just apply the profile to a new photo and get a good look right out of the box.
    * If the user already tweaked a photo, e.g. set the white balance and enabled resizing, and now wants to apply one of these profiles without destroying their previous settings, they can do so by setting the [processing profile fill mode](http://rawpedia.rawtherapee.com/The_Image_Editor_Tab#Processing_Profile_Selector) to "preserve" and applying these profiles.
    * If the user already tweaked a photo but wants to have everything reset when applying one of these profiles, they can set processing profile fill mode to "fill" before applying.
8. I will document their use in RawPedia.

Which profile do we set as the default for raw photos?
While I personally prefer a linear curve, it's clear from user comments that they generally would like something like looks like their out-of-camera image. As such, I think we should set `Auto-Matched Curve - ISO Low.pp3` as the default. We have a few weeks of testing until a final release - we can always revert to `Standard Film Curve - ISO Low.pp3` if histogram matching turns out to be unreliable (it hasn't failed a single time in my experience yet).

**Comment by agriggio** [comment]
I agree with everything. Just one note: I saw that the `Standard Film Curve` profiles have highlight compression set to `90`, is that intentional?

**Comment by Beep6581** [comment]
Yes, it prevents ugly highlight-clipping transition zone discoloration. Have you found it to be a problem?

**Comment by agriggio** [comment]
> Have you found it to be a problem?

I haven't tested this profile specifically, but in my normal use of RT I have never found a "one size fits all" value for highlight compression -- it seems to me that this is very image-specific. But maybe I'm wrong.

**Comment by Beep6581** [comment]
> I have never found a "one size fits all" value

Agreed. With the changes in the last year, HLC is less aggressive and seems to do no harm at values <100. The default profile is nothing more than a way for a new RT user to get a decent-looking starting point. If you don't mind, I would keep HLC=90 for now - we can always remove it before the release. If it does more harm than good - please report!

**Comment by Beep6581** [comment]
P.S. in c2e7d924a171a36da68ac5ca482c0d52e5a60641 the commit message says,
> False color suppression steps set to 2 - this affects both X-Trans and Bayer raw files.

I made a mistake - the `CcSteps` I changed affects only the X-Trans section, but the Bayer section already had that key set to `2`, so both are `2`.

**Comment by Beep6581** [comment]
I processed concert photos using the new PP3s. I'm generally very happy with them.

--edit
I split off what I wrote here into a new issue #4341

**Comment by Beep6581** [comment]
Points 3, 4 and 5 all have O=63.529. Perhaps it would solve the issue if there was a condition which would prevent adding a new point if that point would have an output value equal to the previous point.
