### ISSUE TITLE
Auto Luminance button BW and Dynamic curves for RGBproc

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#2086]
Originally reported on Google Code with ID 2102
```
Here is a patch that adds functionality to Rgbproc.

1) Auto button for mode "Luminance equalizer" (Black and white)
2) dynamic histogram for curves"before" and "after" (Black and White)
3) dynamic histogram for curves "Tonecurves" (Exposure)

I made this proposal issue2096  :)
```

Reported by `jdesmis` on 2013-12-04 07:25:12

<hr>
 * *Attachment: [issue2102-1.patch](https://storage.googleapis.com/google-code-attachments/rawtherapee/issue-2102/comment-0/issue2102-1.patch)*

**Comment by Beep6581** [comment]
@Desmis has this been solved and committed, can we close?

**Comment by Desmis** [comment]
@Beep6581 

I think we can close :)
