### ISSUE TITLE
Are pure colors shown and inverted correctly?

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#2133]
Originally reported on Google Code with ID 2149

```
Open the attached image, apply (Neutral).

White should be all clipped, but RT shows L=99, or R=100 G=100 B=99.6. See the other
colors too.

When inverting the attached image using either Tone Curve 1 or RGB curves, white does
not turn black, etc. http://i.imgur.com/C8Yp3Y2.png (mouse cursor was over the bottom-left
square)

Tried with Monitor Color Profile set to my own ICC, also tried with sRGB or nothing
(deleted the entry in the options file).

I also see issue 2141 with the blue square turning black.

Related forum: http://rawtherapee.com/forum/viewtopic.php?f=1&t=5210
```

Reported by `entertheyoni` on 2013-12-20 21:51:30

<hr>
- _Attachment: testchart1.png<br>![testchart1.png](https://storage.googleapis.com/google-code-attachments/rawtherapee/issue-2149/comment-0/testchart1.png)_

**Comment by Beep6581** [comment]
White still is not 100% R=G=B.
Currently the output profile histogram shows R=G=B 99.6% for the white patch, and the working profile histogram shows R=99.6%, G=100%, B=99.6%.

**Comment by Beep6581** [comment]
I cannot reproduce this in `5.4-672-g`7aeef817e using 
* http://rawtherapee.com/shared/test_images/8_bit_chroma_subsampling.png
* http://rawtherapee.com/shared/test_images/8_bit_integer_gamma.png (R=G=B=50.2% for the gray area is correct)

@Thanatomanic as you referenced this, can you reproduce? If not, then let's close this and go with your issue.

**Comment by Thanatomanic** [comment]
@Beep6581 The colors are correct now, except for my own issue with the cyan, which also shows up here. Go ahead and close this issue.
