### ISSUE TITLE
Lightness sliders

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#2160]
Originally reported on Google Code with ID 2176

```
RT useability would greatly improve if it had separate edge-aware  Lightness sliders
for Shadows and Highlights
```

Reported by `michaelezra000` on 2014-01-02 17:45:53

**Comment by Thanatomanic** [comment]
Going through some old issues. I believe this is no longer useful since the new Shadows / Highlight tool in 5.4 (?) or some version since then.
