### ISSUE TITLE
History columns have no names

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#2199]
Originally reported on Google Code with ID 2215

```
History columns have no names, yet are visible. This looks weird, broken.
http://i.imgur.com/zsGibZE.png
```

Reported by `entertheyoni` on 2014-01-22 12:53:16

**Comment by Beep6581** [comment]
In gtk3, the columns are fixed at 50%, the user cannot resize them. Any objections against removing the column headers?

**Comment by Hombre57** [comment]
No objections it seems, closing.
