### ISSUE TITLE
XMP & IPTC metadata missing or corrupt

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#2307]
Originally reported on Google Code with ID 2323

```
I set the following as a title for one of my PEFs in digiKam:
Pentax 50mm f/1.7 SMC-M at f/1.7, focus 0.45m
I wrote this metadata to the raw file.

In RawTherapee, I saved four versions: one with the "Copy IPTC/XMP unchanged to output
file (when tagging with other program)" enabled, another with that option disabled,
and both JPG and TIFF.

I opened the original PEF and these saved files in Gwenview, Geeqie, digiKam, exiftool,
exiv2 and RT. Results follow:
Gwenview:
Pentax 50mm f1.7 SMC-M 01.pef raw files not supported by digiKam
disabled.jpg Pentax 50mm f/1.7 SMC-M at f/22, focus ?
disabled.tif Pentax 50mm f/1.7 SMC-M at f/22, focus ?
enabled.jpg missing
enabled.tif Pentax 50mm f/1.7 SMC-M at f/1.7, focus 0.45m

Geeqie:
Pentax 50mm f1.7 SMC-M 01.pef Pentax 50mm f/1.7 SMC-M at f/1.7, focus 0.45m
disabled.jpg Pentax 50mm f/1.7 SMC-M at f/22, focus ?
disabled.tif Pentax 50mm f/1.7 SMC-M at f/22, focus ?
enabled.jpg missing
enabled.tif Pentax 50mm f/1.7 SMC-M at f/1.7, focus 0.45m

digiKam:
Pentax 50mm f1.7 SMC-M 01.pef
  IPTC tab: >>> IIM Application 2 <<< Object Name : Pentax 50mm f/1.7 SMC-M at f/1.7,
focus 0.45m
   XMP tab: >>> Dublin Core <<< Title : Pentax 50mm f/1.7 SMC-M at f/1.7, focus 0.45m
disabled.jpg
  IPTC tab: Object Name : Pentax 50mm f/1.7 SMC-M at f/22, focus ?
   XMP tab: empty
disabled.tif
  IPTC tab: Object Name : Pentax 50mm f/1.7 SMC-M at f/22, focus ?
   XMP tab: empty
enabled.jpg
  IPTC tab: empty
   XMP tab: empty
enabled.tif
  IPTC tab: Object Name : Pentax 50mm f/1.7 SMC-M at f/1.7, focus 0.45m
   XMP tab: Title : Pentax 50mm f/1.7 SMC-M at f/1.7, focus 0.45m

exiftool (exiftool -G -s -a -m -u -args <image> | grep 'SMC-M at'):
Pentax 50mm f1.7 SMC-M 01.pef
  -XMP:Title=Pentax 50mm f/1.7 SMC-M at f/1.7, focus 0.45m
  -IPTC:ObjectName=Pentax 50mm f/1.7 SMC-M at f/1.7, focus 0.45m
disabled.jpg
  -IPTC:ObjectName=Pentax 50mm f/1.7 SMC-M at f/22, focus ?
disabled.tif
  -IPTC:ObjectName=Pentax 50mm f/1.7 SMC-M at f/22, focus ?
enabled.jpg
  -XMP:Title=Pentax 50mm f/1.7 SMC-M at f/1.7, focus 0.45m
  -IPTC:ObjectName=Pentax 50mm f/1.7 SMC-M at f/1.7, focus 0.45m
enabled.tif
  -XMP:Title=Pentax 50mm f/1.7 SMC-M at f/1.7, focus 0.45m
  -IPTC:ObjectName=Pentax 50mm f/1.7 SMC-M at f/1.7, focus 0.45m

exiv2 (exiv2 -pa <image> | grep 'SMC-M at'):
Pentax 50mm f1.7 SMC-M 01.pef
  Iptc.Application2.ObjectName                 String     45  Pentax 50mm f/1.7 SMC-M
at f/1.7, focus 0.45m
  Xmp.dc.title                                 LangAlt     1  lang="x-default" Pentax
50mm f/1.7 SMC-M at f/1.7, focus 0.45m
disabled.jpg
  Iptc.Application2.ObjectName                 String     40  Pentax 50mm f/1.7 SMC-M
at f/22, focus ?
disabled.tif
  Iptc.Application2.ObjectName                 String     40  Pentax 50mm f/1.7 SMC-M
at f/22, focus ?
enabled.jpg
  Warning: Ignoring IPTC information encoded in the Exif data.
  Warning: Ignoring XMP information encoded in the Exif data.
enabled.tif
  Iptc.Application2.ObjectName                 String     45  Pentax 50mm f/1.7 SMC-M
at f/1.7, focus 0.45m
  Xmp.dc.title                                 LangAlt     1  lang="x-default" Pentax
50mm f/1.7 SMC-M at f/1.7, focus 0.45m

RawTherapee:
Pentax 50mm f1.7 SMC-M 01.pef IPTC tab, Title: Pentax 50mm f/1.7 SMC-M at f/22, focus
?
disabled.jpg IPTC tab, Title: Pentax 50mm f/1.7 SMC-M at f/22, focus ?
disabled.tif IPTC tab, Title: Pentax 50mm f/1.7 SMC-M at f/22, focus ?
enabled.jpg missing
enabled.tif Pentax 50mm f/1.7 SMC-M at f/1.7, focus 0.45m

Raw file: http://rawtherapee.com/shared/test_images/pentax_50mm_f1.7_smc-m_01.pef
JPG/TIFF saved files: http://filebin.net/6zrtafqm9l
```

Reported by `entertheyoni` on 2014-04-01 19:59:56

**Comment by asp** [comment]
Over at exiv2 we have an open issue on this topic: http://dev.exiv2.org/issues/1081

It appears that the XMP data has gotten dumped into Exif.Image.XMLPacket

**Comment by clanmills** [comment]
I'd like to support what Alan has said about this.  The Adobe Spec for embedding XMP in JPEGs is quite explicit that XMP and IPTC data must be encoded as an APP1/APP13 segment.  The Exif metadata (formatted as TIFF in an APP1/Exif segment) should not use tags such as XMLPacket.  http://www.adobe.com/content/dam/Adobe/en/devnet/xmp/pdfs/XMPSpecificationPart3.pdf

I will be happy to help RawTherapee to analyse and remedy this issue.  Perhaps the team should consider adopting libexiv2 for metadata handling as it is used by Gimp/DigiKam/gThumb and other open source image handling applications.

If you adopt libexiv2, I will add an API to repair this "on the fly".  This would enable you to retain your existing code and, with a single call, will repair your JPEG to conform with Adobe's Spec.  If you decide not to include libexiv2, I will be happy to contribute a standalone 'C' function to RawTherapee with the same purpose and result.

The current situation at the Exiv2 project concerning this is to close issue 1081 because we do not have a bug in our handling of this.  I've opened a new feature request to fix the JPEG and you may wish to add to our discussion:  http://dev.exiv2.org/issues/1154

**Comment by asp** [comment]
I am not a coder, I just dug into the XMP implementation in exiv2 a bit, so this may be totally wrong, but:

It looks like RawTherapee is putting all XMP properties and values into ApplicationNotes (Exif.Image.XMLPacket in exiv2 speak).

https://github.com/Beep6581/RawTherapee/blob/master/rtexif/rtexif.cc#L474

**Comment by asp** [comment]
We are considering a workaround for this RT bug in exiv2. Comments and/or patches are most welcome!

[exiv2 Feature #1154: Read XMP and IPTC data from Exif Data in JPEGs](http://dev.exiv2.org/issues/1154)

**Comment by Beep6581** [comment]
I wanted to write something so that you know that we have seen this and that we're not ignoring you. Thing is, the people currently active specialize in things other than metadata, so it's unfortunately quite likely that nothing will happen here. We really could use some help.

**Comment by clanmills** [comment]
I’ll involve myself with this later in the year.  I hope to get exiv2 v0.26 finished in June and have a break and vacation in July.  So mid-August I’ll get involved.  The easy way to deal with this is for Exiv2 to accept your metadata.  The harder way is for me to fix RT and at the moment, I’ve no idea how much effort that will take.

Robin
http://clanmills.com

**Comment by Beep6581** [comment]
Closing as duplicate of #3801 - Adopt libexiv2 or ExifTool for metadata handling.
