### ISSUE TITLE
Segfault opening dir in File Browser containing refresh-white.png

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#2337]
Originally reported on Google Code with ID 2353
```
Segfault when opening attached refresh-white.png
Stack backtrace: http://bpaste.net/show/KyqST3F05ZyhOzEFiiKG/

I replaced the file with a crash-free version, but it would be nice if RT didn't crash
on it in the first place. The segfault version of that PNG is attached here.

The version that segfaults is 8-bit indexed, Base type: GrayscaleAlpha
```

Reported by `entertheyoni` on 2014-04-22 09:20:00

<hr>
 * *Attachment: refresh-white-segfault.png<br>![refresh-white-segfault.png](https://storage.googleapis.com/google-code-attachments/rawtherapee/issue-2353/comment-0/refresh-white-segfault.png)*

**Comment by heckflosse** [comment]
This bug was fixed some time ago. 8-bit indexed png files are ignored now.
