### ISSUE TITLE
Better sorting of padded numbers and fractions in File Browser

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#2467]
Originally reported on Google Code with ID 2484

```
Padded number sorting could be improved:
http://i.imgur.com/ZNmKFBv.png
```

Reported by `entertheyoni` on 2014-08-28 07:06:04

**Comment by Beep6581** [comment]
The file sort order is still human-unfriendly:
![screenshot_20180516_114827](https://user-images.githubusercontent.com/5844619/40109974-1841d854-58ff-11e8-885b-2b5475ac0466.png)

Expected:
```text
GX9whiteISO200.RW2
GX9whiteISO400.RW2
GX9whiteISO800.RW2
GX9whiteISO1600.RW2
GX9whiteISO3200.RW2
GX9whiteISO6400.RW2
GX9whiteISO12800.RW2
GX9whiteISO25600.RW2
```

**Comment by Floessie** [comment]
@Beep6581 I already have an idea how to solve that...

**Comment by Beep6581** [comment]
Maybe this helps, `sort` from `coreutils` has a `--human-numeric-sort` option:
https://github.com/coreutils/coreutils/blob/master/src/sort.c

**Comment by Floessie** [comment]
@Beep6581 Thanks for the pointer, although I saw it too late. I did it my way. :notes: :wink:

**Comment by Beep6581** [comment]
@Floessie great :)
Note that `case '.'` will fail on locales which use the comma as a decimal separator, and dragons beware for locales which use `.` as a thousands separator (i.e. 0 or more `.` are valid).

**Comment by Beep6581** [comment]
Note that my note could be rubbish, since I didn't read the whole patch ;)

**Comment by Floessie** [comment]
@Beep6581 
> Note that case '.' will fail on locales which use the comma as a decimal separator, and dragons beware for locales which use . as a thousands separator (i.e. 0 or more . are valid).

Yes, the code is "locale-unaware", but it's about filenames, so this shouldn't be a problem for the f-numbers you mentioned in 2014. The thousands separator per se shouldn't be a problem, but more than one `.` is treated as such and not condensed to one. Improvements welcome...

**Comment by Floessie** [comment]
> The thousands separator per se shouldn't be a problem, but more than one `.` is treated as such and not condensed to one.

Thinking a night about it, I stand corrected: It would reverse the order.

**Comment by Floessie** [comment]
@Beep6581 Maybe it's sufficient to just pad numbers and ignore the fraction (just like I did with negative numbers). Everything else smells like over-engineering for a problem, that's not existent. `f2.8` would still come before `f22`.

Opinion?

**Comment by Beep6581** [comment]
Having 800 before 1600 is the main thing, and everything else is just icing on the cake.

**Comment by Floessie** [comment]
@Beep6581 
> Having 800 before 1600 is the main thing, and everything else is just icing on the cake.

Okay, I'll reduce the whole thing further tonight.

**Comment by Floessie** [comment]
@Beep6581 Now you can give it a try.

**Comment by Beep6581** [comment]
@Floessie apologies, PR #4559 went completely off my radar!

Test image set:
```text
002.pef
01.pef
021.pef
08.pef
11.pef
1.pef
21.pef
2.pef
3.pef
foo_2018-01-01_bar.pef
foo_2018-08-08_bar.pef
foo_2018-11-11_bar.pef
foo_2018-12-01_bar.pef
foo_2018-12-12_bar.pef
foo_2018-12-23_bar.pef
fooISO100bar.pef
fooISO1600bar.pef
fooISO6400bar.pef
fooISO800bar.pef
```

```text
$ locale
LANG=en_SE.UTF-8
LC_CTYPE="en_SE.UTF-8"
LC_NUMERIC=C
LC_TIME="en_SE.UTF-8"
LC_COLLATE="en_SE.UTF-8"
LC_MONETARY="en_SE.UTF-8"
LC_MESSAGES="en_SE.UTF-8"
LC_PAPER="en_SE.UTF-8"
LC_NAME="en_SE.UTF-8"
LC_ADDRESS="en_SE.UTF-8"
LC_TELEPHONE="en_SE.UTF-8"
LC_MEASUREMENT="en_SE.UTF-8"
LC_IDENTIFICATION="en_SE.UTF-8"
LC_ALL=
```
![screenshot_20180612_103439](https://user-images.githubusercontent.com/5844619/41279240-3c4c0f7a-6e2c-11e8-863d-f0837d6eb9e6.png)

Super, +1 for merge!

**Comment by Floessie** [comment]
@Beep6581 
> apologies, PR #4559 went completely off my radar!

No problem. I'm completely busy ATM as well. :sweat_smile:

I'll merge...

Best,
Flössie

**Comment by heckflosse** [comment]
@Floessie Can we close this?

**Comment by Floessie** [comment]
@heckflosse Ingo, thanks for the pointer. I guess, we can close this (and I'll do so right now). The padding could be made a bit more robust by ~~prepending~~ appending the original number of digits. But as long as noone has a problem with the implementation as-is I see no need to change it.

Flössie
