### ISSUE TITLE
Lensfun support

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#2543]
Originally reported on Google Code with ID 2560

```
Issue opened to get a new start. I'll merge the old Lensfun Issue into this one.

I started work on Lensfun support in rt. The first patch is only a mockup to test whether
it can be accessed in RT. DrSlony already tested on Linux. Hombre and I tested on Win64
(thanks for your help with cmake, Hombre). But we also need tests on Win32 and Mac.

I can only describe the procedure for Win64 builds (I'm on drive H: in example):

1. clone the Lensfun repo with 'git clone http://git.code.sf.net/p/lensfun/code h:\lensfun-code'
   or use a gui (Git Gui for example) to clone

2. change to the source directory

   h:
   cd \lensfun-code
   md cmake_build
   cd cmake_build
   cmake -G "MinGW Makefiles" -D CMAKE_BUILD_TYPE=Release -D LENSFUN_INSTALL_PREFIX=%MINGW_BASEPATH%\
-D BUILD_TESTS=OFF -D BUILD_STATIC=ON ..
   C:/MinGW64/bin/mingw32-make.exe -j8 install

   set the CMAKE_BUILD_TYPE parameter according to what you want to get ( Release /
Debug / RelWithDebInfo ) before

3. apply the attached patch to rt

4. build rt

5. start rt in console

It should output 'HomeDataDir: ...' in console if it can be accessed.

That's all for the moment. When we have a clean build process for all OS I'll continue
work.

Ingo
```

Reported by `heckflosse@i-weyrich.de` on 2014-11-06 19:06:39

<hr>
- _Attachment: [rt_lensfun_00.patch](https://storage.googleapis.com/google-code-attachments/rawtherapee/issue-2560/comment-0/rt_lensfun_00.patch)_

**Comment by Beep6581** [comment]
https://gist.github.com/anonymous/622ebd946014a6f8277e

**Comment by seebk** [comment]
I just wanted to drop a note that current Lensfun development HEAD has added support for the Adobe ACM lens model. Maybe this simplifies migration from LCP profiles to Lensfun in RT.

**Comment by Beep6581** [comment]
What's ACM?

**Comment by seebk** [comment]
ACM is the Adobe Camera Model. This means that Lensfun can directly 
apply correction using the parameters from LCP profiles. However, it 
cannot open and parse LCP files directly. But there is a small Python 
script to convert LCP to valid Lensfun XML data.

**Comment by indikaPathi** [comment]
Is anyone currently working on this issue?

**Comment by da-phil** [comment]
This is a feature I'd be also interested in, it would help RT to get access to a big (open source) lens correction database.

**Comment by perspectival** [comment]
I'm also very interested in this feature. It really is a hassle to track down Adobe lcp lens profiles. One of the major use cases for using RawTherapee is to provide users with a standalone alternative to Lightroom ;-) Thanks for all your hard work on RawTherapee, and I hope lensfun can be integrated.

**Comment by Vittel** [comment]
Is anyone working on RawTherapy at all? (Also lensfun would be fun!)

**Comment by Beep6581** [comment]
@Vittel https://github.com/Beep6581/RawTherapee/pulse

**Comment by Vittel** [comment]
Hey, yea, i realized that now :) The website appeared to be somwhow out of date, but indeed there is alot of activity. 
Would love to see the documentation for some more recent information about how to create lens profiles from ... anything. The adobe lcp-s are making everything worse... (your documentation is down; see latest issue:))

**Comment by Beep6581** [comment]
Handled by #3826
