### ISSUE TITLE
rawtherapee freezes on batch processing

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#2569]
Originally reported on Google Code with ID 2586
```
I can't process my files either raw or jpeg pictures.
A run through gdb, pressing Ctrl+C, gives the following

Program received signal SIGINT, Interrupt.
pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
185	62:	movl	(%rsp), %edi


```

Reported by `domenico.ferrari` on 2014-11-20 18:13:52

**Comment by adamreichold** [comment]
I think this can be closed, as the original issue (trying to export into a read-only folder) is also handled by the file-saving-error code from issue #2241 (which seems to work as intended when testing the current master).

**Comment by heckflosse** [comment]
Adam, thanks a lot for reviewing the issue :)
