### ISSUE TITLE
Special handling of chromaticity=-100 no longer needed

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#2574]
Originally reported on Google Code with ID 2591

```
When the Chromaticity slider in the L*a*b* Adjustments tool is at -100, RT is set to
work in "old color toning" mode where you can color-tone the image using the a* and
b* curves. When you move the slider to -99, the images pops into black-and-white tones.
This behavior is intentional, it comes from the days before RT had the Black-and-White
and Color Toning tools. Now that it has those tools, this behavior is no longer necessary.
Moreover, it is unintuitive and almost impossible to figure out if you trigger it without
knowing about it.

Options:
1- Leave it as-as.
Cons: unintuitive, unnecessary.
Pros: PP3 compatibility preserved.

2- Remove this behavior.
Cons: PP3s which used chroma=-100 with bent a* and b* curves will need to enable the
Black-and-White tool to get the same effect.
Pros: no unintuitive and unnecessary behavior.

3- Remove this behavior, but if loading PPVERSION <=321 then keep it.
Cons: nothing.
Pros: PP3 compatibility preserved, etc.
```

Reported by `entertheyoni` on 2014-12-02 13:39:11

**Comment by Beep6581** [comment]
@Desmis is this something you could look into? If we agree to remove this behavior, it would be good to do that now before releasing RT5 so that RT5 PP3s stay consistent.

**Comment by Desmis** [comment]
@Beep6581 
I pushed a chaage in branch "bwtoningold"

If ppversion < 314  and if user select chroma= -100, then the system enable "black and white"
if ppversion > 314 old bwtoning is desabled

:)

**Comment by Beep6581** [comment]
@Desmis I tested and found no problems, :+1: for merging https://github.com/Beep6581/RawTherapee/tree/bwtoningold

**Comment by Beep6581** [comment]
@Desmis looks like you already merged the branch "bwtoningold", so you can delete it from https://github.com/Beep6581/RawTherapee/branches

**Comment by Beep6581** [comment]
Fixed long time ago - closing.

P.S. Currently (`5.5-118-g`0f1f12d29) the `a*` and `b*` curves tone the image regardless of the chromaticity slider's value - the image is toned even if `chromaticity=-100`.
