### ISSUE TITLE
segfault opening an image - pipette?

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#2580]
Originally reported on Google Code with ID 2597
```
Using a debug build, I had some image open and then I opened either the same one from
the File Browser or a different one. I got this backtrace:
http://dpaste.com/22EX66S
I may have had a pipette active while opening a new image.
The PP3 is attached, the image was a HDR DNG, not this one but otherwise identical
to it: http://rawtherapee.com/shared/test_images/hdrmerge_045.dng
```

Reported by `entertheyoni` on 2014-12-04 14:13:42

<hr>
 * *Attachment: [2596segfault.pp3](https://storage.googleapis.com/google-code-attachments/rawtherapee/issue-2597/comment-0/2596segfault.pp3)*

**Comment by adamreichold** [comment]
Could not reproduce using the provided DNG and PP3 using a Linux x86-64 debug build of 5758f4d9ad04f42f041dc291e1d27d2d55f84d62.

**Comment by Beep6581** [comment]
Can't reproduce anymore either, link expired, closing.
