### ISSUE TITLE
The Color Toning tool needs some love when viewed from the File Browser

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#2659]
Originally reported on Google Code with ID 2676
```
http://i.imgur.com/enTxEHL.png
```

Reported by `entertheyoni` on 2015-02-18 20:25:53

**Comment by adamreichold** [comment]
The [branch](https://github.com/adamreichold/RawTherapee/tree/remove-unused-colortoning-labels) removes the two unused labels visible in the screenshot. They were always hidden outside of batch mode which is probably why they were overlooked.

**Comment by Beep6581** [comment]
Thank you, fixed in commit 7ef35abb57ebd3654fc9e7b3b383821a7152eb87
