### ISSUE TITLE
Auto Exposure does not allways use the parameters it shows in gui

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#2708]
Originally reported on Google Code with ID 2726

```
1) Open the dng file from http://filebin.net/f9jue0c9a5
2) Apply default profile and zoom to snow (200%). Should look as bad as hdr1.png from
above link.
3) press the neutral button and the auto exposure button, now artifacts are gone. Should
look like hdr2.png
4) Now zoom to 50% and back to 200%. Artifacts are there again

Ingo
```

Reported by `heckflosse@i-weyrich.de` on 2015-03-26 21:27:06

**Comment by Beep6581** [comment]
I can still reproduce this in master, 4.2.971 5e11f6bb833681a305c2a00946923f547a914ca9.

**Comment by heckflosse** [comment]
Yes, same here

**Comment by Beep6581** [comment]
I can still reproduce the steps in the [first](#issue-100405658) and [fourth](#issuecomment-130064944) comments using `5.3-346-g`a2bf6081.

**Comment by Beep6581** [comment]
Maybe related to #2627

**Comment by Thanatomanic** [comment]
I cannot reproduce this anymore using `5.4.455`

**Comment by Beep6581** [comment]
Confirmed, I cannot reproduce neither the first nor the fourth bug anymore.
