### ISSUE TITLE
Add camconst support for foveon files

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#2711]
Originally reported on Google Code with ID 2729

```
This patch adds camconst support for foveon files.
Ilias, could you add the camconst entries for the foveon cams please?

Ingo
```

Reported by `heckflosse@i-weyrich.de` on 2015-03-30 17:13:41

<hr>
- _Attachment: [camconst_foveon.patch](https://storage.googleapis.com/google-code-attachments/rawtherapee/issue-2729/comment-0/camconst_foveon.patch)_

**Comment by Beep6581** [comment]
exiftool shows the SD1's make and model as:

```
-EXIF:Make=SIGMA
-EXIF:Model=SIGMA SD1
```

RawTherapee shows "Exif data not available" in the (i)nfo panel, and "Unknown" for make and model in the File Browser > Filter

**Comment by Beep6581** [comment]
We still need to add entries to `camconst.json` for Foven models using safe white (and black?) levels, and to rename the shipped profiles from e.g. `sd1_merrill_cloudy8140-CROP-WP10.icm` to something more consistent with the other names which RawTherapee should be able to load automatically (once reading Exif of Foveon models is implemented).

**Comment by morosakubek** [comment]
Hi,
Still all Merril's cameras shows that "Exif data not available", so as i think rawtherapee can't properly read the file.

**Comment by Beep6581** [comment]
camconst.json now supports Foveon files, closing.

Adding specific raw formats to camconst.json should be handled in separate issues.
