### ISSUE TITLE
New OS X 10.7/8/9 and 10.10 development builds

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#2713]
Originally reported on Google Code with ID 2731
```
Hello

Could someone please make available 64-bit builds of the latest development code for
testing?

As I understand it, builds for OS X 10.7 should also work on 10.8 and 10.9 and these
platforms support 32-bit and 64-bit, while 10.10 requires its own build and is 64-bit
only, so we would need three builds in total.
```

Reported by `entertheyoni` on 2015-04-03 14:00:49

**Comment by mglorencin** [comment]
Would it be possible for someone to build the latest build. I really tried to set my enviroment to make the build my self but had a constant issue with some dependencies so I gave up after a few days of trying :( 

anyway I would appreciate a newer dev build for testing

**Comment by Beep6581** [comment]
Closing, will upload new build as soon as someone makes one.
