### ISSUE TITLE
MonkeysOnWheels: Segfault when opening or applying PP3 with deleted non-existant Exif

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#2722]
Originally reported on Google Code with ID 2740
```
Applying a PP3 or opening an image with an associated PP3 which deletes a tag which
does not exist in the image segfaults RawTherapee.

For example open amsterdam.pef and open segfault_copyright.pp3 and segfault because
it has no copyright Exif tag, but do the same with blue_horse.nef and no segfault because
that nef has "EXIF:Copyright=Michael Ezra".

Apply segfault_monkeys.pp3 to any image and segfault, unless you happen to have an
Exif tag called MonkeysOnWheels.
```

Reported by `entertheyoni` on 2015-04-14 18:37:33

<hr>
 * *Attachment: [segfault_copyright.pp3](https://storage.googleapis.com/google-code-attachments/rawtherapee/issue-2740/comment-0/segfault_copyright.pp3)*
 * *Attachment: [segfault_monkeys.pp3](https://storage.googleapis.com/google-code-attachments/rawtherapee/issue-2740/comment-0/segfault_monkeys.pp3)*

**Comment by adamreichold** [comment]
The [branch](https://github.com/adamreichold/RawTherapee/tree/fix-edit-tag) should fix the access to an invalid iterator in `ExifPanel::editTag`.

**Comment by Beep6581** [comment]
Fix confirmed in gtk3 branch.

**Comment by Beep6581** [comment]
Merged into master, thank you.
Commit 4273fa300047e31a9e06b0c7736f1071f9a8fe37
