### ISSUE TITLE
Ctrl + Shift behavior is not good

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#2727]
Originally reported on Google Code with ID 2745
```
In Windows Explorer and many more programs Ctrl+Shift allows selecting separated ranges
of files. It does not in RT.

RT 4.2.147
```

Reported by `pinhuer` on 2015-04-19 21:36:49

**Comment by adamreichold** [comment]
The [branch](https://github.com/adamreichold/RawTherapee/tree/fix-range-selection) tries to simplify the thumbnail browser selection implementation, fixing the above mentioned bug and adding the shift-and-control range selection behaviour to select several additional ranges.

I think there are still some counter-intuitive cases with the shift-and-control feature, but I guess they can only be resolved by tracking the last-range-selection-started in addition to the last-clicked entry which IMHO is too much complexity considering the benefit.

**Comment by heckflosse** [comment]
Branch seems to work fine
:+1: to merge

Ingo

**Comment by Beep6581** [comment]
Merged.
