### ISSUE TITLE
JPEG output is suboptimal

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#2735]
Originally reported on Google Code with ID 2753

```
Well, in fact, it really sucks!

Take a look at the dark areas of the background on the center of the image, and compare
it with IrfanView's output. All image were saved with a slider set to "90%" for quite
good image quality. The IrfanView version has been saved first to Tiff/8 bits by RT,
then converted by IrfanView with 90% quality too.

What can we see:
1. all images out of RT has strong posterization.
2. the IrfanView version is the smallest one, even compared to the "Best compression"
version of RT's one, and for the same compression ratio.

Tagged as critical.

Output files:
-------------
http://www.rawtherapee.com/shared/test_images/BlackCat%20output/BlackCat-A.Best%20quality.jpg
http://www.rawtherapee.com/shared/test_images/BlackCat%20output/BlackCat-B.Eqilibrated.jpg
http://www.rawtherapee.com/shared/test_images/BlackCat%20output/BlackCat-C.Best%20compression.jpg
http://www.rawtherapee.com/shared/test_images/BlackCat%20output/BlackCat-IrfanViewV4.32.jpg

Test image:
-----------
http://www.rawtherapee.com/shared/test_images/BlackCat.DNG
http://www.rawtherapee.com/shared/test_images/BlackCat.DNG.pp3

```

Reported by `natureh.510` on 2015-04-26 11:43:40

**Comment by Hombre57** [comment]
Made some test again with a different colorimeter driver (Argyl CMS instead of DataColor one), set all settings to identical values (97% quality for jpeg) and then get identical result. I don't know what was involved in my initial experience, but I'm closing the issue, non relevant.

**Comment by iliasg** [comment]
@Hombre57 @Beep6581  
> I don't know what was involved in my initial experience, 

Whith recent RT there is a significant improvement regarding posterization for 8-bit exports .. I bet it comes from better rounding in place of an ungly truncation before .. https://github.com/Beep6581/RawTherapee/pull/3432/files

**Comment by Hombre57** [comment]
So there really was an issue ? Glad that it is solved, thanks !

**Comment by iliasg** [comment]
@Hombre57 @Beep6581 

There is still a difference between tiff-8bit vs jpeg-8bit exports .. tiffs are less posterized ;)

If a developer could take a look in Libjpeg or call libjpeg guys .. to investigate if low precision maths are involved there .. maybe jpeg posterization can become even less with some easy tweeks ..

From RT's part we can use non standard gamma curves which give more codes at the darks 
An easy solution for less posterization is to use the "free gamma" option and define there
gamma = 2.40 - Slope = 15.0 (max) and it would be better if we had more headroom for the slope ..
Or use a linear-log curve ..  https://github.com/Beep6581/RawTherapee/issues/3333#issuecomment-224711875
