### ISSUE TITLE
Fitting cropped image to windowed should fit only cropped area

### ISSUE THREAD

**Issue by neilpho** [Beep6581/RawTherapee#2858]
If I press "f" to fit the image into the window then it would be more useful if just the cropped area filled the window instead of the whole (masked off) image.

**Comment by Beep6581** [comment]
Alt+f

**Comment by neilpho** [comment]
I think "f" should fit the visible, useful area to the screen. Alt-f could then be used for the whole (invisible) image. I think it is a better experience for the user that way.
