### ISSUE TITLE
Fix CMake-3 warnings

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#2861]
CMake, specifically cmake-3.2.2, shows a whole bunch of warnings during compilation, we should address them.

**Comment by innir** [comment]
I only see one warning (repeated several times): 
`Policy CMP0046 is not set`

I think the line causing this is not even needed so I just removed it and also removed a cmake_policy statement that was not used.

**Comment by Beep6581** [comment]
Fix confirmed.

**Comment by innir** [comment]
Could you merge the pull request? I don't have the permissions.

**Comment by Beep6581** [comment]
Hombre have you merged it?

**Comment by innir** [comment]
I think so, as I included it in my pr #2865 by chance

**Comment by Beep6581** [comment]
Ok, let's close. I do confirm that the changes are in master.
