### ISSUE TITLE
An output profile crashes RT 4.2.2.2

### ISSUE THREAD

**Issue by xpatUSA** [Beep6581/RawTherapee#2863]
I am trying out display-class profiles with CLUTs so that I can truly save a file with Perceptual Rendering Intent. So far I have only found one and it crashes RT during the 'save as' operation.

I have put the profile up here:

http://kronometric.org/phot/xfer/ppRGB-sRGB.icm

Would like to know why it crashes RT.

Thanks,
Ted.

**Comment by Beep6581** [comment]
1- What is "4.2.2.2"? There is no such RT version. Please report bugs only if you can reproduce them in the latest version.

2- What is that profile? What is it for, where did you get it?

3- Where did you try to set it? As input? Output? Monitor?

http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports

**Comment by xpatUSA** [comment]
On 8/13/15, Beep6581 <notifications@github.com> wrote:
> 1- What is "4.2.2.2"? There is no such RT version.


>Please report bugs only if you can reproduce them in the latest version.
>
> 2- What is that profile? What is it for, where did you get it?

Doesn't matter

>
> 3- Where did you try to set it? As input? Output? Monitor?

output
>
> http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports
>
your response is quite unfriendly. I am not an idiot and please forget
that I asked the question.

**Comment by heckflosse** [comment]
xpatUSA, I don't think that the answer was hostile.The link http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports was not made for idiots, but to help us to get as much informations as possible. Idiots wouldn't be able to give the informations we asked for in that link.

So, If you want to help us to solve your Issue, please give us more informations. If not, we'll forget.

Ingo

**Comment by heckflosse** [comment]
xpatUSA, I tried your profile. It works fine when I save to jpeg or compressed tiff. When saving to uncompressed tiff I can reproduce the crash.
Telling us what you did would have saved some of my time to try out... 

Ingo

**Comment by xpatUSA** [comment]
Ingo,
 I am sorry that you wasted time on this issue. I had already closed the issue and did not expect further responses. Please take no further action. I will try to close this issue again.
regards.

**Comment by heckflosse** [comment]
If it crashes I'll fix it :-) Issue reopened

**Comment by xpatUSA** [comment]
OK, I'll be glad to help. I'm using Windows 7 on a Dell Inspiron with
a Core i5 processor and 6GB RAM. I dowloaded the 64bit version of RT,
here's the 'about this build' data:

Branch: default
Version: 4.2.222
Changeset: cb035234398c
Compiler: gcc 4.9.2
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V2.22.0
Build type: Release
Build flags: -m64 -mwin32 -mthreads -msse -msse2 -mtune=generic
-fopenmp -Werror=unknown-pragmas -mwindows -DNDEBUG -O3
-Wno-aggressive-loop-optimizations
Link flags: -mwin32 -mthreads -static-libgcc  -mtune=generic -mwindows -s -O3
OpenMP support: ON
MMAP support: ON

Like yourself, I find it works when saving as JPEG but not uncompressed TIFF.

I think I must have assumed JPEG was unsuccessful and that seems not
to be the case. So, my main interest is for JPEG and this issue
becomes less important for me.

Thank you for your patience.

Ted

**Comment by heckflosse** [comment]
Hi Ted,
thank your for providing the informations. I already solved the problem in https://github.com/Beep6581/RawTherapee/pull/2867

Ingo

**Comment by xpatUSA** [comment]
Thanks for the information, Ingo.

Ted

**Comment by heckflosse** [comment]
Fixed in bb33cc6ffe7e96f08011ecb183957aa0f5ce7e58
