### ISSUE TITLE
Sony Lens recognize issue

### ISSUE THREAD

**Issue by gianlucapirro69** [Beep6581/RawTherapee#2868]
The last windows version (4.2.276) doesn't recognize Sony 16-35 f4 FE OSS

![2015-08-15_234938](https://cloud.githubusercontent.com/assets/13813800/9291014/d88d8708-43a8-11e5-9dec-7edb9f827458.jpg)

**Comment by Beep6581** [comment]
Hi, please provide a sample raw file http://filebin.net/

**Comment by gianlucapirro69** [comment]
Ok. The file .arw is here

http://filebin.net/r0k8uq18g9

**Comment by Beep6581** [comment]
Merged into issue 2879

**Comment by gianlucapirro69** [comment]
The issue is in the last version too

**Comment by heckflosse** [comment]
Works fine here. Can you clear the cache please and test again?

Ingo

**Comment by Beep6581** [comment]
And please give the hash of the version you used, "the last version" doesn't mean anything.

**Comment by gianlucapirro69** [comment]
I use 4.2.312 for WIN x64. I re-installed again but it doesn't recognize Sony 16-35 FE

**Comment by Beep6581** [comment]
No, re-installing won't help. You need to clear the cache. Either right-click on a selection of photos > "Cache" > "Clear from cache - full", or (easier) delete the "data" folder from the cache folder http://rawpedia.rawtherapee.com/File_Paths

"4.2.312" means nothing to us, we need you to either open AboutThisBuild.txt or go to Preferences > About > Version and copy the changeset, e.g.
Changeset: 11d382d998231bfc5ec7dffdf46763fa5fcf31f3

**Comment by gianlucapirro69** [comment]
61de76748502   I cleared cache...same issue

**Comment by Beep6581** [comment]
Git says that is an unknown revision, but 4.2.312 sounds quite old. Wait for a newer build and test then.

**Comment by gianlucapirro69** [comment]
I download from http://rawtherapee.com/downloads 4.2.312 is the last version

**Comment by gianlucapirro69** [comment]
ok. Now it's ok with last release
