### ISSUE TITLE
Unknown git option: -C 

### ISSUE THREAD

**Issue by mbajor** [Beep6581/RawTherapee#2871]
I'm trying to build packages from github sources. I have error for some Linux distros (CentOS 7, Debian 7, Fedora 20, Scientific Linux 7, Univention 4.0, openSUSE 13.1)
```
...
[281s] -- git command found: /bin/git
[281s] Unknown option: -C
[281s] usage: git [--version] [--help] [-c name=value]
[281s]            [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
...
```

Build results: https://build.opensuse.org/package/show/home:rawtherapee/rawtherapee

**Comment by Beep6581** [comment]
Hey

Where do we find a full log?
You can come to IRC if you like, I'll be there in 40 minutes.

**Comment by mbajor** [comment]
> Where do we find a full log?
@Beep6581 Go to https://build.opensuse.org/package/show/home:rawtherapee/rawtherapee and click "failed" red message.

**Comment by innir** [comment]
You need at least git version 1.8.5 for this option - I thought it's save to assume this.
I'll check for other options tonight.

**Comment by Beep6581** [comment]
Fixed and committed AFAIK
