### ISSUE TITLE
pictures in queue shown even if cut because shown in bottom row

### ISSUE THREAD

**Issue by gaudry-daniel** [Beep6581/RawTherapee#2876]
Hi
I am used to have a look at my pictures in the queue to decide which ones I am not ready to process. Unfortunately, the ones in the bottom row are cut (the bottom 1/3). Is it advisable not to put them on screen if there is not enough room for them?
Best regards
Daniel GAUDRY

**Comment by Beep6581** [comment]
Hey, please show a screenshot of the problem.

**Comment by gaudry-daniel** [comment]
Hi
Here is the screen showing the cut images on the bottom row. It may be better not to show them
Best regards


![zzz](https://cloud.githubusercontent.com/assets/13891713/9416365/8713001e-4845-11e5-897d-7a584aafa772.png)

**Comment by gaudry-daniel** [comment]
Done
Best regards

Daniel Gaudry
9 Avenue Calmels
92270 Bois Colombes
France
+33664195009

**Comment by Beep6581** [comment]
But this is not a bug, just scroll down.
