### ISSUE TITLE
latest OS X 10.10 development build … 4.2.312 or higher?

### ISSUE THREAD

**Issue by mglorencin** [Beep6581/RawTherapee#2878]
Would it be possible for someone to build the latest OSX build. I really tried to set my enviroment to make the build my self but have a constant issue with some dependencies so I gave up after a few days of trying :( 

anyway I would appreciate a newer dev build for testing, didn't know how to post about it here as this really is not an issue but if you I reply in older topic where we had this kind of thread, post just doesn't show up as this is not an issue, it's more an request … then again it's a dev build and latest OSX 4.2.270 build gives me crashes as I already reported here https://github.com/Beep6581/RawTherapee/issues/2713 … and would like to test if latest build has that crash issue solved

**Comment by Beep6581** [comment]
Closing, will upload new build as soon as someone makes one.

**Comment by mglorencin** [comment]
thank you :+1:
