### ISSUE TITLE
Update lens IDs from exiftool-10.00

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#2879]
I wrote `tools/generateLensList` which is a Bash4 script to make updating the lens IDs in `rtexif/*` easy. Consequently, I updated `canonattribs.cc olympusattribs.cc pentaxattribs.cc sonyminoltaattribs.cc` with lenses from exiftool-10.00.

Compare https://github.com/Beep6581/RawTherapee/compare/master...lensfix

There are two things to look out for:

1- RawTherapee has its own lens-matching logic. You will notice sometimes more than one lens goes by the same ID. RawTherapee throws some bones, casts a spell from rtexif/rtexif.h std::string guess() and hopefully comes up with the right lens. How well this works I don't know, nor do I know whether the voodoo, designed for the exiftool lens lists all those years ago, still works well for this updated list. Specifically you will see things like: 
```
-        choices.insert(p_t(8, "Canon EF 100-300mm f/5.6"));
+        choices.insert(p_t(8, "Canon EF 100-300mm f/5.6 or Sigma or Tokina Lens"));
```
I chose to keep the "or blabla" text until many have tested it and given responses. If the "or blabla" is not needed because RT's voodoo works, then I can easily remove it.

2- I think this only pertains to Sony/Minolta: I also included what the scary now-deleted comments perhaps referred to as '"categories' header" types', 
```
+        choices.insert(p_t(129, "Tamron Lens (129)"));
+        choices.insert(p_t(129, "Tamron 200-400mm F5.6 LD"));
+        choices.insert(p_t(129, "Tamron 70-300mm F4-5.6 LD"));
```
The reason I didn't remove the first line is because though it's easy to do I'm not sure how future-proof my script would be and I don't know yet whether removing it is really necessary. If it is, that can be easily done.

I will update nikonattribs.cc once it is revealed to me how to do that.
For now, **please test!**

**Comment by Beep6581** [comment]
generateLensList updated to handle Nikon lenses, nikonattribs.cc updated too.

**Comment by Beep6581** [comment]
There is inconsistency in exiftool's style of writing the focal length in lens names:
- Canon uses f/# except for one entry which uses F/# (Tamron 18-200mm F/3.5-6.3 Di III VC)
- Nikon uses half f/# half F# and two F/#
- Sony/Minolta always use F#
- Pentax always uses F#

exiftool doesn't consider this a problem or a bug and doesn't intend on changing it.

I updated the script and .cc files to use "f/" aperture notation.
Please test.

**Comment by heckflosse** [comment]
DrSlony, what's the status of this issue?

**Comment by Beep6581** [comment]
Well nobody complained or gave feedback, so I assume it's all working well, and therefore no need to keep the issue open.
