### ISSUE TITLE
pulling the latest source code

### ISSUE THREAD

**Issue by gaudry-daniel** [Beep6581/RawTherapee#2880]
Hi
I stil use the pull request as :

 hg pull                                                                                                                                                                                            
pulling from https://code.google.com/p/rawtherapee/                                                                                                                                                           
searching for changes                                                                                                                                                                                         
no changes found                                        

It looks as it is still using google!
What should I modify to use the new github or is it still ok?
best regards
Daniel gaudry

**Comment by Beep6581** [comment]
Hey

Explained on the front page:
https://github.com/Beep6581/RawTherapee

Please don't open issues for personal support - use IRC or the forum for that.
http://rawtherapee.com/blog/contact

**Comment by gaudry-daniel** [comment]
Hi
thanks, I did open on the forum, however the forum on how to compute rt in
linux is not yet updated and stil recomends google. As i do not know who is
in charge of that very well written text, uo may be able to contact and
suggest the required chqnges
best regards
Daniel Gaudry

Daniel Gaudry
9 Avenue Calmels
92270 Bois Colombes
France
+33664195009
