### ISSUE TITLE
Crash exporting to JPG

### ISSUE THREAD

**Issue by JPauly** [Beep6581/RawTherapee#2888]
When trying to convert this picture with the setting privided in the PP3 File RT crashes (http://filebin.net/pojnpn9owv). Ends with window error message, that program has crashed and I will be informed, when solution is available (picture provided with RT in background). Tried on different RT versions, first on 4.0xxx, then stable version 4.2 and now on 4.2.312, always same effect. Using Window 8.1Pro (all windows patches installed), Intel I5-4570 with 12GB.
Picture was taken on a waterhole in Namibia with sodium vapor lamps (my guess), so it needed a lot of color modifications... With other pictures and other setting no crash problem, only with these settings also on other picutures....
Error or UTS problem?

**Comment by heckflosse** [comment]
Crash confirmed on Win7/64

**Comment by heckflosse** [comment]
The crash is caused by the R curve you used in RGB curves.
How did you create that curve?

**Comment by heckflosse** [comment]
Got it. Crashes when two points of curve are at position x=0

**Comment by Beep6581** [comment]
Crash confirmed, fix confirmed.

**Comment by JPauly** [comment]
Yes, I set both to zero as the lighting was very special. Perfect!
