### ISSUE TITLE
New DCP Profile for Canon PowerShot G7 X

### ISSUE THREAD

**Issue by stefan-i** [Beep6581/RawTherapee#2890]
I created a DCP profile for the Canon PowerShot G7 X for inclusion in RT.
it was created with an X-Rite CC24 shot and the corresponding X-Rite software.

Measurements with Colorchartcheck.exe: 

New DCP (Reference: Babel values)
                      Min    Avg    Max
DeltaE2000    0,46    1,77    4,27

New DCP (Reference: X-Rite values)
                      Min    Avg    Max
DeltaE2000    0,19    2,25    4,87

Camera Standard  (Reference: Babel values)
                       Min    Avg    Max
DeltaE2000    0,49    1,95    4,57

Camera Standard  (Reference: X-Rite values)
                      Min    Avg    Max
DeltaE2000    0,16    2,15    4,67

I tried the CC24 shot in four different locations and with exposure bracketing, this is the best result I could achieve. On balance it seems to offer a slight improvement over the current camera standard matrix profile.

DCP and DNG Raw can be found here:
http://filebin.net/rw0tg2tmso

**Comment by stefan-i** [comment]
Can anyone please add this to RT?

**Comment by Beep6581** [comment]
Added Canon PowerShot G7 X dual-illuminant DCP made using DCamProf 0.9.11

**Comment by stefan-i** [comment]
Sorry, I don't understand - how can this possibly now have become a *dual-illuminant* DCP? 
Do you think the DCPs made with DCamProf are in general preferable to X-Rite?

**Comment by Beep6581** [comment]
I used photos sent by someone a month ago.
Hard to say which is better in this case, as the test photos sent were not taken under real tungsten illumination (I hope the tungsten photo of the CC24 chart was, but I'm not sure either, so if you could take one under real tungsten illumination that would be great).

X-Rite doesn't let you tweak anything, while DCamProf does and Anders, the developer, is also a RT developer.

**Comment by stefan-i** [comment]
Ah, you mean this commit? https://github.com/Beep6581/RawTherapee/commit/fb6ffa6aa88f8cf41c471891ace428abf4a98662 
This seems to be a misunderstanding, the profiles there are not for the Powershot G7 X (a compact camera) but, amongst others, an EOS X7 (a DSLR).
If you want I can shoot and upload a CC24 under real Tungsten, but from what I've seen of DCamProf it does not seem to be a programme I'd be able to use, as superior as it might be :)

**Comment by Beep6581** [comment]
No, the commit is still local on my machine, haven't pushed it yet.
Yes, please take one. Make sure it's a real tungsten bulb, use a tripod, don't open the aperture more than f/8, stand at least 2m away from the light source and make sure the light source is directly behind you or at least 2m above the target so that the illumination is even, perpendicular. ISO100. Make sure there are no colored walls or reflective surfaces nearby. Let the shot fill 1/3rd of the frame in the center, as bright as possible with no clipping.
Please open a new issue once the files are ready.

**Comment by stefan-i** [comment]
OK, the files are uploaded, continued here: https://github.com/Beep6581/RawTherapee/issues/2919
