### ISSUE TITLE
DrSlony needs a new keaboard

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#2891]
DrSlony's keyboards space key is wonky. To allow us to understand what he writes, he has to get a new one. I'll donate 5€. Anyone else wants to chime in?

Ingo

**Comment by Hombre57** [comment]
I can donate 5€ too, but how ?

**Comment by heckflosse** [comment]
DrSlony can tell us. But could be difficult without spaces ;-)

**Comment by mkyral** [comment]
He can use paste for missing Spaces ;-)
Or on Linux (and probably on windows too), just remap some unused key (like Caps lock) to Space.

**Comment by Beep6581** [comment]
Sometimes I'mclose to remapping myforehead to space...

**Comment by heckflosse** [comment]
I suggested him to use alt-32 on windows. But all these suggestions are just workarounds for getting a new keyboard. For that reason I created the Issue (kind of crowdfunding). We're already at 10€ after 17 minutes.

**Comment by Beep6581** [comment]
http://goo.gl/EuxCKU

**Comment by michaelezra** [comment]
I am in:) I had a new spare keyboard for old Asus M3Np laptop somewhere.. but that won't work.
DrSlony - was that a black coffee or a tea that spilled into the space?:)

**Comment by Beep6581** [comment]
Thank you for this, it means much more to me than the price of the keyboard :)

Michael it was 6 years worth of things. I cleaned the keyboard thoroughly some weeks ago but didn't notice that the rubber nipple from the space key (and F8 key) came off at some point. So then I re-purposed them from two of the never-used numpad keys, but to work they need more motivation than a mule going uphill, making legible writing slow and painful :)

**Comment by Beep6581** [comment]
I'veneverdone this before, hope it works!
https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=AWV33QKZJBWWL

**Comment by michaelezra** [comment]
done:)

**Comment by heckflosse** [comment]
done

**Comment by Beep6581** [comment]
Thank you Michael and Ingo!

**Comment by Hombre57** [comment]
I have a sleeping PayPal account, I wanted to donate just now, but I have to validate my credit card first, it may take 1 day or so. Is there another mean to donate, or will you wait ?

**Comment by Beep6581** [comment]
Shipping from China will take a week or two, so a day makes little difference. Thank you Hombre :)

**Comment by Beep6581** [comment]
http://i.imgur.com/H7RzclD.png
Fixed pending confirmation...

Thank you everyone!

**Comment by Beep6581** [comment]
Hombre thank you! :)

**Comment by Beep6581** [comment]
Fix confirmed ::))
Thank you everyone!
