### ISSUE TITLE
Wavelets: size tool panel jumps

### ISSUE THREAD

**Issue by paulmatthijsse** [Beep6581/RawTherapee#2893]
Open a raw, go to the wavelet tab, under toning click on the Opacity red-green button and the tool panel gets wider and is partly invisible. If this doesn't happen, click on the Edit nodes button on the right of the graph. The blue-yellow button does not always show this problem. 
Same when you click under Edge sharpness on the Local contrast button (or the Edit nodes button) and under Final Touchup on the Final local contrast button (ditto). 
v4.2.346

**Comment by Beep6581** [comment]
Duplicate of issue #2531

**Comment by paulmatthijsse** [comment]
Excusez, didn't see that one.
