### ISSUE TITLE
Wavelets: contrast and chroma interfere

### ISSUE THREAD

**Issue by paulmatthijsse** [Beep6581/RawTherapee#2894]
Open a raw, go to the wavelets tab (and activate the tool), click several times in the Contrast entry on the Contrast+ button until the finest level is for example 198. Deselect the Chrome entry (where all levels are at their default values of 0) and the image gets very ugly, as if the contrast values are doubled or more. 
v4.2.346

**Comment by Beep6581** [comment]
Confirmed.
This may have something to do with the Contrast > Apply To combobox no longer working. It used to work and make a big difference, now there is no difference between "Shadows/Highlights" and "Whole luminance range".

**Comment by paulmatthijsse** [comment]
Contrast - Apply To combo still works here. Click on the Contrast+ button until the first level is at 350 and toggle between the Apply To's. There's certainly a big difference!
Also dragging the left slider combo of the Highlight Luminance range to the left, changes the effect. Same for the Shadow part. A agree that this effect is less outspoken than it used to be. Perhaps better so.

**Comment by Desmis** [comment]
I commit and push a change (master) I think solved the problem :)
56eb18e4df

**Comment by paulmatthijsse** [comment]
Merci Jacques, you solved this little (but quite annoying) problem indeed.

**Comment by Beep6581** [comment]
Fix confirmed.

The Apply To bug is also not-reproducible, probably fixed when we updated refreshmap.
