### ISSUE TITLE
Deutsch locale finished

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#2896]
Translation of the german locale is finished. Remove the file extension .png before using it.
One unclear tooltip isn't translated. I have to wait for the correction in the English language file.
If you find wrong, bad or funny translations, please let me know.

![deutsch](https://cloud.githubusercontent.com/assets/13800920/9689792/a4a6cd56-5338-11e5-8056-321de82f7731.png)

**Comment by Beep6581** [comment]
Thank you.

**Comment by heckflosse** [comment]
TooWaBoo, thanks you very much for this work!

**Comment by heckflosse** [comment]
https://github.com/Beep6581/RawTherapee/commit/a7db8f001ce1bccb93bc31d64f0165db5527da5a

**Comment by TooWaBoo** [comment]
my pleasure

cu TooWaBoo
