### ISSUE TITLE
Warning notification popup when tool keys fail to apply

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#2899]
When applying a PP3 or opening an image with a PP3 already applied which uses an external DCP, LCP, etc. and this file is not found, RawTherapee should show a visible helpful warning. A popup could be too annoying, but at least hijacking the progress bar would help.

**Comment by Hombre57** [comment]
@Beep6581 Possible solution : Add a red triangle icon (the warning sign) on top toolbar on which the tooltip would give the error message, plus ("click to dismiss the message(s)"). That button would then act as a message accumulator.

**Comment by agriggio** [comment]
@Hombre57 I was thinking along similar lines (except that  I was considering putting the icon on the bottom, next to the progress bar... but that was just a thought).
It's definitely doable but might be a bit tedious as it requires several (small) changes

**Comment by Beep6581** [comment]
@Hombre57 maybe a GtkInfoBar?
https://developer.gnome.org/gtk3/stable/GtkInfoBar.html

**Comment by Hombre57** [comment]
@Beep6581 I don't know how it's visually displayed (as an icon or only a temporary notification popup ?), but yes, that should do it.

**Comment by Beep6581** [comment]
Another example, when you open the TIFF+PP3 supplied in #4310, the output profile is set to "No ICM; sRGB Output". RawTherapee gives me no hint that the PP3 actually is supposed to use `OutputProfile=AdobeRGB1998`, and that the `AdobeRGB1998.icc` file cannot be found.

**Comment by Beep6581** [comment]
Duplicate of #4261
