### ISSUE TITLE
crash on saving

### ISSUE THREAD

**Issue by chimera15** [Beep6581/RawTherapee#2904]
The newest windows x64 release I reached a point where with my settings it crashed every time I tried to save anything..not sure how to report that besides here. 4.2.1 is working ok, still crashes every once in a while but am able to save at least.

**Comment by heckflosse** [comment]
http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports

**Comment by chimera15** [comment]
Well I don't have the debug version, so what more information would be helpful?

**Comment by Beep6581** [comment]
So you need to find which, and upload the raw+pp3 file. Didn't the article make that clear?
Someone here will provide a debug build.

**Comment by sguyader** [comment]
Here's an RT 4.2.350 Debug build for 64-bit Windows, I hope this helps:
https://drive.google.com/open?id=0B_AvPFlUj8t5NkVYRFlCWW9FTTA
