### ISSUE TITLE
Microsoft Visual C++ Runtime Error - there is no way to open the RT

### ISSUE THREAD

**Issue by Rychu08** [Beep6581/RawTherapee#2909]
Every time I'm trying to run RT I have this notification: 

![bez tytulu](https://cloud.githubusercontent.com/assets/14318881/9915666/9b398d10-5cb8-11e5-82b6-4ffdb9bcd35e.jpg)

My RT: 
Branch: master
Version: 4.2.346
Changeset: 98c12219089d9c171aa3d5269733cafb54467073
Compiler: gcc 4.9.2
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V2.22.0
Build type: Release
Build flags: -m64 -mwin32 -mthreads -msse -msse2 -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -mwindows -DNDEBUG -O3 -Wno-aggressive-loop-optimizations
Link flags: -mwin32 -mthreads -static-libgcc  -mtune=generic -mwindows -s -O3
OpenMP support: ON
MMAP support: ON

What's more - yesterday I was able to run the programme as usual, today this came up. 
Does anyone have an idea what could be the reason? I've already tried uninstalling MS Visual Redistributable Packages then installing it again, as well as with the latest version of RT. I used CCleaner as well to clean the logs and stuff. 
Is there any way to run the RT again, or it will be dead for ever? :|
Thanks in advance

**Comment by Beep6581** [comment]
http://rawpedia.rawtherapee.com/How_to_fix_crashes_on_startup
