### ISSUE TITLE
Gtk3 history panel expands horizontally when it should remain constant

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#2910]
The History panel has two columns. In the Gtk2 branch, when long text appears in both columns, the left column "wins" and expands, squeezing the right column's text so much that some of it is hidden. Horizontal scrollbars are set to never appear.
In the Gtk3 branch when long text appears, it is never hidden, instead the container table expands horizontally to the left. Since it is set to never have horizontal scrollbars, the whole History table gets hidden behind the left edge of the RT window http://i.imgur.com/qMGH9vz.jpg

Workaround: I'll set the horizontal scrollbar policy to automatic for the time being until the squeeze-and-hide behavior is re-implemented (if we want it?).

@Hombre57 what are your thoughts about the old behavior?

**Comment by Hombre57** [comment]
I've worked on this issue for 5 days now, only to get that damn thing working, and it's still not satisfactory, but I'll push a fix tonight to have 2 columns equally sized (automatically) with automatic tooltip, so we can still read any line completly through them. Identation is not ideal for multi-line parameter values, but still better than nothing.

I'm having difficulties to tell Gtk not to expand e.g. progress bars whenever the text gets longer. I either miss something, or Gtk3 doesn't offer a correct API to handle such situation.

The patch also fix the curve's background, that was not displayed so far.

**Comment by Hombre57** [comment]
And one more notice: I'm working on other (major) changes, but will push to Gtk3 only. I don't have the time to handle two branches.

**Comment by Beep6581** [comment]
Works great!
I pushed a fix:
https://github.com/Beep6581/RawTherapee/commit/303e69b5fbd3a56677ac265b56f9b8fcaee777f3

One more improvement would be to prevent the left panel from shrinking into the left RT window edge when a user makes it too narrow. It shouldn't let the user resize it any narrower than the point at which the contents no longer fit horizontally.
OK http://i.imgur.com/uVpbunG.png
Still OK http://i.imgur.com/l929TCZ.png
Not OK http://i.imgur.com/2nTVHVx.png

**Comment by Beep6581** [comment]
Just pushed a fix for that:
https://github.com/Beep6581/RawTherapee/commit/c026c8bcf0bdf5d7ab1a5d06e48406cd94bbedc1

**Comment by Hombre57** [comment]
Thanks for the fix! I don't really understand what happened when I pulled yesterday, maybe my local Gtk3 branch was not up to date, but it's not easy to understand what's going on with revision with Git.

It's great that you found how to lock the minimal width of the paned, I would not have found it myself.

**Comment by Beep6581** [comment]
I'm happy that you're not shouting at me for touching it :D
