### ISSUE TITLE
Gtk3 theme

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#2911]
I cleaned up old themes and pushed a new theme to the Gtk3 branch which is to be the one and only theme. It is currently called cookiedough.css and is loaded when you enable slim mode.

Why it is as it is:
* Our brain is quick to adapt to what it perceives to be the neutral gray color, therefore if a theme uses any color hinting in large surfaces then our idea of what neutral gray looks like will adapt to that and we will end up misadjusting the white balance or hues of our photos, therefore the theme should use absolutely no hue in any large-surface areas.
* Small things like icons and buttons can use color, they won't affect your idea of what neutral gray looks like.
* The theme should not waste any screen space. This theme is as slim as possible while still looking decent.

When slim mode is disabled, rtcommon.css is used. Once ready, rtcommon.css will be deleted and cookiedough.css will be renamed to rtcommon.css. The reason I haven't done this yet is that the UI in many places uses hard-coded tests for slim mode in the C++ files and then changes border widths, padding etc. accordingly - I suppose we must remove all of these from the .cc files.

**Comment by Hombre57** [comment]
Yes, we should remove almost all of these, but not all, i.e. some parameters like column/row spacing can't be handled through css, or I didn't find a way to do it.

Since I prefer having a nice looking GUI over only a "decent" one, I'm against removing the slim mode. I'd put all colors related thing in rtcommon.css as well as the non slim dimensions, ans still keep the slim.css file with overriding values.

**Comment by Beep6581** [comment]
My theme *is* nice looking, its great looking, it's not just "decent" :P

Haven't committed yet, turns out RT runs a lot of obsolete tests regarding themes and iconsets, and the safety fallbacks will cause segfaults if they are ever used. Random example from rtimage.cc:120 - there is no "Default.iconset"
```
        if (!safe_file_test(configFilename, Glib::FILE_TEST_EXISTS) || !keyFile.load_from_file (configFilename)) {
            // ...otherwise fallback to the iconset set in default.iconset
            configFilename = Glib::build_filename(argv0, Glib::build_filename("themes", "Default.iconset"));
```

**Comment by Beep6581** [comment]
Committed https://github.com/Beep6581/RawTherapee/commit/ce95798fcd419890c0af6b637751064b489f9ee5

The cleanups will be invasive and will need to be done separately.

**Comment by Beep6581** [comment]
Off-topic but I can't find the original, @Hombre57 you asked for the Snapshots panel to not resize below a minimal height -> done 93982b84ec9a5c3d2a10b400cfc76bdfa932bc74

**Comment by Beep6581** [comment]
Commit a9aa5308b5bb3c155ecaf6ab4adea2034186b589
* Introduces a new default theme designed to look elegant, not waste any screen space, and not distract the photographer or alter his/her color fidelity.
* Removes all Gtk+ 2 themes and their images.
* Removes slim mode. The new theme is elegantly slim. If someone wishes it slimmer or fatter they are to do so using CSS the way Gtk3 is designed for.
* Two horrible RT logo icons replaced with a crisp new one in four sizes.

![scrot_2015-11-17 024559](https://cloud.githubusercontent.com/assets/5844619/11200600/ae2cd0b8-8cd7-11e5-8e23-84b00c6edf3d.png)

Done.

**Comment by Hombre57** [comment]
Could you provide a screenshot of the file browser as well, and a screenshot of the Noise Reduction tool unfolded + a Tone Curve unfolded ? I see significant difference between my Windows build and the screenshot above. E.g. : the background of the histogram is light gray instead of black, and I don't see the thin frame around the NoteBooks.

I'm also not found of the light grey frame around the NoteBook's tab icons... neither having them separate from the tab content, but that's a matter of taste, and I'll certainly include a second theme named 'legacy' ;)

**Comment by Beep6581** [comment]
As with designing a website, good use of CSS requires good use of HTML. Designing the CSS theme for RT brought up inconsistencies in the way that the UI code is structured - frames here, myexpanders there, checkboxes elsewhere.

I don't care about the border round the notebook tabs. Feel free to change that. Also feel free to justify the Editor's progress bar to the left. I'd rather we spend our combined time on one theme than having two slightly differing ones with half the man-hours put into each.

Keep in mind that Gtk+ 3 is still undergoing many changes and improvements, e.g. the file window bookmarks panel on the left that had to be hacked with C++ in 3.16 should be user-controllable in 3.18 or 3.20, etc.

A growing number of users complain about the "1:1" icon saying it's not visible enough. I must agree, either we want something to be seen, or we don't show it, so I am inclined on removing that icon's partial transparency. What do you think about it?

**Comment by Beep6581** [comment]
![scrot_2015-12-01 170347](https://cloud.githubusercontent.com/assets/5844619/11506523/2d456c7e-9850-11e5-9a30-d70ba2b3b3bd.png)
![scrot_2015-12-01 170425](https://cloud.githubusercontent.com/assets/5844619/11506524/2d49e506-9850-11e5-9340-b20d28c47717.png)
![scrot_2015-12-01 170807](https://cloud.githubusercontent.com/assets/5844619/11506526/2d4c5200-9850-11e5-9043-a1be2e4992b0.png)
![scrot_2015-12-01 170832](https://cloud.githubusercontent.com/assets/5844619/11506527/2d4c7758-9850-11e5-9c2d-0ec1d9d10a41.png)
![scrot_2015-12-01 170858](https://cloud.githubusercontent.com/assets/5844619/11506525/2d4a64fe-9850-11e5-89aa-413d917ac12a.png)
![scrot_2015-12-01 171129](https://cloud.githubusercontent.com/assets/5844619/11506528/2d532120-9850-11e5-9da8-b5b8a86cb259.png)

**Comment by Hombre57** [comment]
> I don't care about the border round the notebook tabs.

I don't understand this sentence. All that I say is that I find quite disturbing to not see how the GUI is structured, like in the File Browser where you see buttons on the right, + buttons displayed vertically, + some kind of content, but without visible relation between them all (a notebook inside a notebook panel). Could you find a way to restore the notebook structure ?

In the Preferences window, we don't see the Frame's area through a different color like before, is it part of your new design ?

> A growing number of users complain about the "1:1" icon saying it's not visible enough. I must agree, either we want something to be seen, or we don't show it, so I am inclined on removing that icon's partial transparency. What do you think about it?

Go ahead.

**Comment by Beep6581** [comment]
> I'm also not found of the light grey frame around the NoteBook's tab icons

> I don't care about the border round the notebook tabs.
I meant that the way they are now is not special to me, feel free to change them as you like. If you mean something like this then I agree it would look more clear: http://www.usabilityfirst.com/wp-content/uploads/2009/12/tabs-c02ca91c.jpg

> Could you find a way to restore the notebook structure ?
"Restore" means they were there to begin with, and that's not the case. This is what RT-gtk3 with Adwaita and no custom theme looks like:
![scrot_2015-12-02 153830](https://cloud.githubusercontent.com/assets/5844619/11533579/c0eb579e-990a-11e5-830f-fd3516558a4c.png)

> In the Preferences window, we don't see the Frame's area through a different color like before
This does it:
```
.prefNotebook GtkFrame {
    background-color: #3B3B3B;
    border: 1px solid #505050;
    border-radius: 4px;
}
```
Pushed in commit 169f4d7.

`.prefNotebook .frame {` won't work as expected. Instead of targetting individual (sub)frames, it affects the whole notebook as the notebook uses a frame.

Would be nice if someone took the time to go through all the UI code and applied a relevant class to every "structural element", because currently finding the right selector to target the right element is... not fun.
