### ISSUE TITLE
New DCP Camera Profiles (Canon Powershot G7 X, Pentax K-5 II)

### ISSUE THREAD

**Issue by stefan-i** [Beep6581/RawTherapee#2919]
Continued from: https://github.com/Beep6581/RawTherapee/issues/2890 
As suggested there I have taken an additional CC24 shot under real tungsten (traditional 75 Watt Philips bulb :))
I tried to follow all your other suggestions (Tripod, f/8, lowest native ISO, brightest exposure without clipping...), I hope the quality is OK

While at it I took the same Tungsten CC24 shot also with my other camera, a Pentax K-5 II. Currently there is only a single illuminant DCP created with X-Rite software in RT, maybe it's worth it to update this as well with a dual illuminant profile?

All DNG Raw files (Daylight and Tungsten for both Canon G7 X and Pentax K-5 II) can be found here: http://filebin.net/v9b8qg8e22

**Comment by Beep6581** [comment]
Great!

**Comment by Beep6581** [comment]
Added.

I usually "relax" the DCP profiles a bit, but in the Pentax K-5 II's case I didn't because relaxing caused a significant difference in the red patch between the tungsten and daylight shots.

**Comment by stefan-i** [comment]
Thanks!

**Comment by stefan-i** [comment]
One question: Is the embedded tone curve "film like" or "perceptual"?

**Comment by Beep6581** [comment]
It's Adobe's standard film curve.
