### ISSUE TITLE
Amaze Demosaicing Tile Size Optimization.

### ISSUE THREAD

**Issue by TimZaman** [Beep6581/RawTherapee#2920]
Hi.

Browsing through the code i found the tile size in amaze demosaicing to be quite small. 
The tiles are used to cut up the work in tiles of this certain size. I found that when the size of the tiles are set small (160) and the image is large (80 megapixel), the speed improvement of making the tile of size 512 increases the speed by 20%. If i set it at 1024, it only increases by 10%.
If i use a 40 megapixel file, and set the tile size to 512 it increases the speed by 10%.

I would suggest increasing the tile size at least 2x, but maybe someone else first confirm such preliminary findings, or someone can elaborate why the value of 160 was chosen.

https://github.com/Beep6581/RawTherapee/blob/master/rtengine/amaze_demosaic_RT.cc#L51-L52

**Comment by heckflosse** [comment]
@TimZaman maybe this is of interest for you: https://github.com/Beep6581/RawTherapee/issues/1819#issuecomment-129995754

**Comment by TimZaman** [comment]
Ah that's spot on. I wonder what other parameters are of importance,
like image size or maybe even image saliency.
Anyone up for trying this again?

**Comment by heckflosse** [comment]
I'm not against to make a new try to speedup Amaze. The last time I took a look at Amaze it ended with the assumption (only in my brain) that a further speedup of about 25% could be possible (without changing tile size)

**Comment by TimZaman** [comment]
I was planning on looking into porting it to opencl or cuda, probably the
former. Been on my list for ages. Duo to the complexity i have some trouble
slicing and chunking down the process though.

**Comment by heckflosse** [comment]
@TimZaman I know about the complexity of Amaze code. I made all the optimizations (including SSE) for it.

**Comment by heckflosse** [comment]
@TimZaman 
The tile size should be chosen to fit 'almost' all tile buffers into L2 cpu cache for each core. At the time I made the opts for amaze that was the case. Don't know if that's still the case for newer cpus. Maybe we find a better way to (dynamically) adjust tile size (determine size of L2 cache and adjust tile size).
