### ISSUE TITLE
<Save as> to current directory instead of last used directory

### ISSUE THREAD

**Issue by paulmatthijsse** [Beep6581/RawTherapee#2924]
I often use the Save as... button to save my files with a specific name, like DSC_xxxx.tonecurve+waves+ciecam, so that I can see quickly afterwards which tools I have used. 

When I click that button for the first time during a session, it always opens with a dialog that shows the last used directory when I did a Save as (eg. somemap/lastyear), instead of suggesting the directory which my current to-be-saved photo is in (eg thismap/thisyear). 

Is this changeable? I would appreciate that.

I don't think this is related to issue #2905

**Comment by Hombre57** [comment]
Browsing to the edited image's directory is just one click away, i.e. there's an entry for that in the Favorite Locations panel in the save dialog.

**Comment by paulmatthijsse** [comment]
Hey, why didn't you say that before? ;-)
You're right and until now completely overseen by me.
Thanks! 

Topic can be closed.
