### ISSUE TITLE
attempt to allocate widget with width -1164904012 and height 173

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#2925]
In the gtk3 branch, if I open amsterdam.pef from the Editor (SETM/VT, Hide Vertical Scrollbar disabled) then I get this non-fatal error in the console:
`(rawtherapee:4849): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width -1164904012 and height 173`

Two useful tools in debugging this are:
`GTK_DEBUG=geometry gdb rt-gtk3/rawtherapee`
and
`G_DEBUG=fatal-warnings grb rt-gtk3/rawtherapee`
You can combine them:
`GTK_DEBUG=geometry G_DEBUG=fatal-warnings gdb rt-gtk3/rawtherapee`
but that will involve pressing "_c_ontinue" many times before RT fully loads.

Regardless, this is what happens:
```
gtk_widget_set_clip:                      gtkmm__GtkVBox 0 0 1268 973
gtk_widget_size_allocate:                 gtkmm__GtkPaned 0 0 1268 188
gtk_widget_size_allocate:                   gtkmm__GtkVBox 0 0 1268 188
gtk_widget_size_allocate:                     gtkmm__GtkHBox 0 0 1268 188
gtk_widget_size_allocate:                       gtkmm__GtkVBox 0 0 1268 188
gtk_widget_size_allocate:                         gtkmm__GtkHBox 0 0 1268 173
gtk_widget_size_allocate:                           gtkmm__GtkFrame 0 0 1268 173
gtk_widget_size_allocate:                             gtkmm__GtkDrawingArea 3 3 1262 167
gtk_widget_size_allocate:                           gtkmm__GtkVScrollbar 582453244 0 -1164904012 173
```

**Comment by Beep6581** [comment]
Still valid though I think the reported crash was a separate issue, now not reproducible.

**Comment by adamreichold** [comment]
Could also not reproduce using 8ae520e794579a8d3da36909a36859abbd55ac26 and Gtkmm 3.18.0.

**Comment by Beep6581** [comment]
I am "still" on 3.16.7.

**Comment by Hombre57** [comment]
Any news on this ?

**Comment by Beep6581** [comment]
I upgraded yesterday 3.18.7. Will report back if I still see this.
