### ISSUE TITLE
Version 4.2 cannot be built because of erroneous code

### ISSUE THREAD

**Issue by magicgoose** [Beep6581/RawTherapee#2927]
…/RawTherapee-4.2/rtengine/dcraw.cc:8728:11: error: '(anonymous union at
          …/RawTherapee-4.2/rtengine/dcraw.cc:8728:11)' cannot be defined in a type specifier
        if (((union { uint32_t x; uint8_t c; }){1}).c) {
              ^
    …/RawTherapee-4.2/rtengine/dcraw.cc:8728:48: error: member reference base type 'void' is not a structure or union
        if (((union { uint32_t x; uint8_t c; }){1}).c) {
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~

I tried building it with the command given in README: `mkdir build && cd build && \
cmake -DCMAKE_BUILD_TYPE="release" -DPROC_TARGET_NUMBER="2" -DBUILD_BUNDLE="ON" -DBINDIR="." -DDATADIR="." -DCACHE_NAME_SUFFIX=4 .. && \
make -j8 install && \
mv release ~/rawtherapee` and this is the result (or lack thereof) I got.

What can be changed to make it work?

BTW, I'm using OS X 10.10.

**Comment by Beep6581** [comment]
Hey
Try building the latest code, not 4.2 (instructions here at the bottom https://github.com/Beep6581/RawTherapee ), and let us know what version of the compiler you're using.

**Comment by magicgoose** [comment]
Latest code fails even earlier:

    -- Could NOT find OpenMP (missing:  OpenMP_C_FLAGS OpenMP_CXX_FLAGS)
    CMake Error at /usr/local/Cellar/cmake/3.3.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
      Could NOT find MACINTEGRATION (missing: MACINTEGRATION_LIBRARY
      MACINTEGRATION_INCLUDE_DIR)
    Call Stack (most recent call first):
      /usr/local/Cellar/cmake/3.3.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
      cmake/modules/FindMacIntegration.cmake:27 (find_package_handle_standard_args)
      rtgui/CMakeLists.txt:38 (find_package)


    -- Configuring incomplete, errors occurred!

> let us know what version of the compiler you're using

I guess, it's the following?

    $ gcc --version
    Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
    Apple LLVM version 7.0.0 (clang-700.0.72)
    Target: x86_64-apple-darwin14.5.0
    Thread model: posix

**Comment by Beep6581** [comment]
Read the OS X section here https://github.com/Beep6581/RawTherapee/blob/master/COMPILE.txt
and maybe try the script here https://github.com/Beep6581/RawTherapee/blob/master/rtdata/osx/macosx_bundle.sh

**Comment by Beep6581** [comment]
Stale.
