### ISSUE TITLE
Color propagation highlight reconstruction causes crash on some files

### ISSUE THREAD

**Issue by pi99y** [Beep6581/RawTherapee#2928]
* System:
Win 8.1 64bit
8GB ram (Did extensive memory tests to ensure memory modules are OK)
Intel i5-4200U 1.6Ghz

* RT versions tested on: 
"offically posted" version 4.2.363 from the "download page"
and also "RawTherapee_WinVista_64_4.2.366" (master branch) posted on forums by sguyader

* Files tested on:
Fuji X-Pro1 RAF
**Just some files are effected** (at first I thought it's the combination of high ISO and blown highlights, but I found some files with those parameters that process OK)

Example of file that causes crashes: http://www.megafileupload.com/5f1i/will_crash.zip (**this file is not an isolated case!**)
Example of a file that will not cause a crash: http://www.megafileupload.com/5f1j/will_not_crash.zip

* Recreate:
Apply the "(neutral)" profile to the photo and choose "Highlight reconstruction", method: "Color propagation". Note that "Color propagation" seems to cause the problems, it processes fine with "blend" mode for example. Put file to queue and start processing. It crashes every time after a few seconds. File output options don't seem to effect the outcome.

**Comment by pi99y** [comment]
* Recreated on:
Win 7 64bit
8GB ram
Intel Core 2 Quad Q9650 3 GHz

* RT version: "official" 4.2.363 64bit

On this machine it crashes as soon as I select the "Color Propagation" mode (using the test file provided above).

**Comment by heckflosse** [comment]
Crash confirmed.
