### ISSUE TITLE
Speedup for Highlight Reconstruction method 'Colour propagation'

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#2929]
I created a new branch https://github.com/Beep6581/RawTherapee/tree/hilite_recon

Processing time for D800 file on my machine reduced from 2891 ms to 1597 ms.
There maybe small differences in output (only visible when using enhanced absolute difference).

Edit: Peak memory usage of 'Colour propagation' is also reduced by width \* height \* 4 bytes

Ingo

**Comment by heckflosse** [comment]
With https://github.com/Beep6581/RawTherapee/commit/d6521adc3524b2461b83f269b90f407133cf40f6 I added a choice between two versions of 'Colour propagation'. The new one currently is 'TP_HLREC_COLORL'. I didn't add a language entry because I hope we can stay with one method after testing.
There is only a small difference between both methods.
The 'old' method uses the max values of the current image to determine whether pixels are clipped or not. That leads to the following:
1) For underexposed images, where no pixel is clipped, it determines pixels as clipped and tries to correct them.
2) For some images, where the max value exceeds the value 65535 by a certain degree, we get pinkish highlights

The 'new' method always uses the allowed max values not the max values in the image
This leads to the following:
1) For underexposed images, where no pixel is clipped, no pixels are corrected. For this case I also implemented an early break to reduce processing time.
2) For some images, where the max value exceeds the value 65535 by a certain degree, we don't get this pinkish highlights.

Here you can find some examples: http://filebin.net/85260lmwlb

Ingo

**Comment by heckflosse** [comment]
I detected that there is a bug in my latest commit. When you zoom in to 100% a demosaic happens but no color propagation. So after zooming in to 100% just disable/enable HR before you compare both methods.
The bug doesn't happen all the time but I don't want to spend time on it because it will be solved automatically when we go back to one cp method, whatever that will be

**Comment by iliasg** [comment]
Hello Ingo. Thanks for this patch :) it was RT's weakest part for my system as it's memory consumption didnot permite me to use it for >28 Mp files.

I will test as soon as I will be able to compile in the new enviroment (.. take me by the hand ..) :)

**Comment by heckflosse** [comment]
Hi Ilias, glad to see you here :) Unfortunately I can't help you setting up a Win32 environment but I guess Sebastien can do.
About the memory consumption: I reduced it by 4 * width * height bytes. There's another 4 * width * height bytes reduction possible but it will be a bit slower then.

Ingo

**Comment by heckflosse** [comment]
@iliasg : I had another look at the code. It is possible to reduce peak memory usage of Colour Propagation by another 4 * width * height bytes, so in sum this would be a reduction of 12 * width * height bytes compared to master branch. But this will increase processing time a bit (though it will be still much faster than master branch)

Ingo

**Comment by michaelezra** [comment]
Hi Ingo, could this be done only for 32 bit systems (to allow better systems enjoy the higher speed:) ) ?

**Comment by heckflosse** [comment]
Hi Michael, of course :-) And I'll do it only if it's really needed. I just wanted to let you know that it's possible ;-)

**Comment by heckflosse** [comment]
@iliasg, @michaelezra : It just turned out that the reduction of peak memory usage also leads to a small speedup. I'll test a bit more to be sure there's no bug. If there's no bug we have a win-win and I'll push the change :-)

Ingo

**Comment by mks9900** [comment]
Hi Ingo, just tested the new branch and found this when using the new TP_HLREC compared to colour propagation:
https://johanthor.smugmug.com/Other/RawTherapee/i-4WkW5fJ
vs
https://johanthor.smugmug.com/Other/RawTherapee/i-wMRNcZ9

See the stripes and strange colour in the detail window? Neutral profile, wb-corrected and auto exposure in both images. Don't know if it's related to the bug you mentioned in comment three above...?
If you would like the raw image, please let me know. :-)

BR,
Johan

**Comment by heckflosse** [comment]
Johan, it looks related to the bug I mentioned above, but without the raw file I can not be sure. So, yes, please provide the raw file.
And thanks for testing :-)

Ingo

**Comment by mks9900** [comment]
Ingo, I've sent you a link to the raw files! :-)

**Comment by iliasg** [comment]
Another link with a file where the new algo makes negligible difference .. both work well recovering the burned sky, but a small magenta coloration remains at the top of the trees on both reconstructors !!.
https://www.dropbox.com/s/30r1m8g2nbfiylg/IMGP8368.DNG?dl=0

The raw white level is at 16382 for all channels .. normally it is an easy (safe) situation .. why the coloration is there ??.

I remember an issue at gc about the scaling (scale_mul) of DNG's where it looks like the black levels used at the scaling are different than the prototypes  
https://code.google.com/p/rawtherapee/issues/detail?id=2381 
could this be the reason ??.

**Comment by heckflosse** [comment]
Short update.
I could reproduce Johan's issue and will post a solution for it (though it's mainly caused by wrong white levels). Johan is working on measuring white levels for his cam meanwhile I guess ;-)

@iliasg I also found the reason and a solution for your issue but I have to work a bit more on it to get to a really usable solution.

Ingo

**Comment by heckflosse** [comment]
@iliasg Here's a short description to explain your Issue:

Colour Propagation basically works by filling clipped areas from the surrounding unclipped area.
So now, what is an unclipped area? In the current implementation all the pixels which are between 0.25 * maxval and 0.95 * maxval form this unclipped area and are used to fill the clipped area. 0.25 is quite low which means that to fill the clipped area dark pixels are also used. I tried with a value of 0.7 instead of 0.25 meaning that only pixels in the surrounding area between 0.7 * maxval and 0.95 * maxval are used to fill the clipped areas. This let the pinkish artifacts at the top of the trees disappear.
You can try yourself (search for threshpct in hilite_recon.cc and try different values). Maybe this parameter should also be adjustable in gui

Ingo

**Comment by iliasg** [comment]
Ιngo, I will try .. but I need to clarify some things.

In TP_HLREC, Is This maxval same as the raw white level ? Or is it a value after WB scaling ?
Does the algo compare with neighbouring pixels at the same color or calculates the clipped green from the nearby unclipped red/blue ? 
0.25*white_level is not dark .. it's only 2 stops from clipping i.e. brighter than midtone (0.18*)

BTW
- TP_HLREC gives worse result in 3 of 4 files I have tryed so far  
- are we shure that scale_mul is correct for DNG files ?. (gc issue2381)
- Which is Johans model ?
- The accidental double pass color propagation in GC-issue2464 was very efficient .. I vote to use is as option :)

**Comment by sguyader** [comment]
I also tested the new method, and results were also slightly worse than the
original one. Testes on a couple of Fuji xtrans files.

**Comment by heckflosse** [comment]
@iliasg In TP_HLREC the maxval is always 65535. In 'original' Color Propagation maxval is the value of the brightest pixel independent on white level (sounds wrong, doesn't it?).
The algorithm works on demosaiced RGB data so naturally it works on all channels.
I agree that 0.25 * whitelevel is not dark but it's relative dark compared to clipped pixels.
Johan uses a Nikon D3s (white level set to 16383 by dcraw). After setting white level to 16060 (measured with the rawtherapee method described in camconst.json) it looks fine for his ISO 3200 shot.
As I wrote above I'll post a solution for the cases that maxval (brightest pixel) is less than 65535. This is a fallback to 'old' Colour Propagation' for the cases that white level is too large (where the new version fails currently). 

But the old version completely fails for this cases (probaly white level too low?)
 http://www.photographyblog.com/reviews/canon_eos_750d_review/sample_images/ left third from bottom
http://www.photographyblog.com/reviews/canon_eos_5ds_r_review/sample_images/ left 5th from bottom

I'll take a look th GC-issue2464 now.

Ingo

**Comment by heckflosse** [comment]
@sguyader, Sebastien, I agree that when white level is too large the result of the new method can be worse than old method. Solving that Issue is quite easy and I'll do that with next push. I made the new method for cams (mostly Canon) where white level (from dcraw or camconst.json) is to small (or whatever causes the really heavy pinkish highlights with the files I mentioned in above post).

Ingo

**Comment by heckflosse** [comment]
@iliasg @sguyader @michaelezra @mks9900 
i would like to commit and merge into master the speedup (including the reduction of memory usage, up to this commit https://github.com/Beep6581/RawTherapee/commit/8d5cb1708965aed1f93aefb0b9ee13320bd74e8b) before we continue solving all the highlight issues. The optimizations don't have visual impact on result. Any objections?

Ingo

**Comment by iliasg** [comment]
No objection by me :)

**Comment by sguyader** [comment]
Go ahead Ingo

**Comment by heckflosse** [comment]
Ok, speedup and reduced memory usage pushed to master branch. I let hilite_recon branch unchanged, so we can continue now :-)

Ingo

**Comment by heckflosse** [comment]
I deleted and recreated hilite_recon branch and added a new modification.
What changed with new modification:

In a first step it checks if all 3 channels are clipped. If less than 3 channels are clipped the output will be the same as before modification.
If all 3 channels are clipped it checks whether the clipping amount is the same for all 3 channels.
If the amount is the same for all 3 channels (which is often the case for e.g. Pentax and Nikon files) the output will be the same as before modification.
If all 3 channels are clipped and there is a variance in clipping amount between the channels (often the case for Canon EOS files) a per channel correction factor gets calculated.
Additionally in this case also the clipping amount is checked against the hard coded clipping percentage (hardcoded says values between 0.95 * maxval and 1.0 * maxval are clipped). So if the largest of the channel corrected clipping amounts is larger than the hard coded one (< 0.95) the correction factor will be corrected again.
This works quite good (though not perfect) for all the canon EOS files I tested which had a strong pinkish highlight issue before when using Colour Propagation.

So let's test again :-)

Ingo

**Comment by pi99y** [comment]
I just tested "RawTherapee4.2.375" compiled by @sguyader (from his Google drive) and I'm getting crashes that look like previously fixed #2928 issue. Can you please check if the fix for that is included here? Thank you!

**Comment by heckflosse** [comment]
@pi99y Do you get the crashes with the same file as in #2928? If it's a different file it may be a different bug and I need that file to reproduce the bug. Fix for #2928 is included in 'master' branch, but I don't think it's in other branches (except hilite_recon branch). Are you testing 'Retinex' or 'local lab' branch perhaps?

Ingo

**Comment by sguyader** [comment]
I think RawTherapee4.2.375 is the most up-to-date, I compiled it today
after I git pulled today, so the fix #2928 is included.

Sebastien

**Comment by pi99y** [comment]
Same file yes and it also should be the "master" branch. 
It's the "RawTherapee_WinVista_64_20151011.zip" from
https://drive.google.com/folderview?id=0B_AvPFlUj8t5SUdodURGOFdOems&usp=sharing#list

Please try to recreate it yourself (with the previous raw file) since I probably won't have time to do an extensive test/bug report for another 17 hours or so... (but I'll do it later if you won't be able to recreate the bug)

Thanks.

**Comment by Beep6581** [comment]
sguyander, pi99y, for future reference: "4.2.375" means absolutely nothing, it's important that you provide the branch and the changeset hash from AboutThisBuild.txt, e.g. gtk3 3695063b248a40f112612842aa92bb31316d8a4a
and of course the raw file to test on.

**Comment by heckflosse** [comment]
@pi99y Works fine here with your file. It's in my color propagation test suite since you uploaded it and I tried every modification also with your will_crash.raf.

Ingo

**Comment by sguyader** [comment]
Yeah you're right, I'll do that in the future.

**Comment by heckflosse** [comment]
I found a bug in Colour Propagation (all branches, a really old bug)

It's in the following lines:

https://github.com/Beep6581/RawTherapee/blob/hilite_recon/rtengine/hilite_recon.cc#L1026
https://github.com/Beep6581/RawTherapee/blob/hilite_recon/rtengine/hilite_recon.cc#L1027
https://github.com/Beep6581/RawTherapee/blob/hilite_recon/rtengine/hilite_recon.cc#L1028

if you open an image with Colour Propagation enabled the content of variables hlmax[0], hlmax[1] and hlmax[2] is always zero. But when you disable/enable Highlite reconstruction the variables are filled with the clip values after white balance. When you process an image in queue they also contain zero.
Colour Propagation operates on RGB data before white balance so either of the two choices seems clearly wrong. And even more wrong seems that it's not consistent...
I'll take a closer look tomorrow.

Ingo

**Comment by pi99y** [comment]
I had a hard time reproducing my bug today. While I did manage to do it (a few times) it seems it has something to do with opening the film simulation menu WHILE the HL reconstruction is still being calculated. The recreation process is a bit unclear (it doesn't happen allways or even most of the times) so this is probably something unrelated to color propagation issue... Sorry for the confusion.

**Comment by heckflosse** [comment]
With 9061b25 I pushed a fix for the inconsistency mentioned two posts above.
Also included a small bug fix.

**Comment by heckflosse** [comment]
I would like to merge (or let DrSlony merge) a0dabf8 into master.

* I detected no case where the result is worse than master.
* With Canon files the result is often better than master
* It's a tiny bit faster than master for images with large burned areas.
* It's not yet perfect but a good base to continue work.

Any objections?

Ingo

**Comment by iliasg** [comment]
Ι didn't try the last change /a0dabf8...
but with yesterday's 9061b25 the result are as described .. a little better on some files, no worse result on any file detected
