### ISSUE TITLE
Deutsch locale - Update Retinex translation

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#2941]
<b>Deutsch</b> locale update based on <b>RT 4.2.450</b>
http://filebin.net/rw7noop0zm
Changed "Neutral" button under exposure to "Reset" -> Zurücksetzen.
Added key "TP_RETINEX_FREEGAMMA"
Updated key "SAVEDLG_SUBSAMP_TOOLTIP"
Updated key "TP_RETINEX_VARIANCE_TOOLTIP"

If you'll find wrong, bad or funny translations, please let me know.

cu TooWaBoo

**Comment by Beep6581** [comment]
Thank you. Please use http://filebin.net/ in the future as fooling GitHub into treating a text file as a binary file can lead to trouble.

**Comment by heckflosse** [comment]
@TooWaBoo Ich habe mir die Datei gerade mal angeschaut. Ein paar Sachen sollten noch geändert werden. Details folgen morgen.

Vielen Dank, Ingo

**Comment by TooWaBoo** [comment]
@Beep6581
Ok, I'll do it next time

@Ingo
Ich hoffe,dass ich nicht zu viel Mist übersetzt habe. :-)

cu TooWaBoo

**Comment by TooWaBoo** [comment]
Added Deutsch locale based on RT 4.2.450 to the first post.

@heckflosse 
Hallo Ingo, mir fehlen noch die Infos der Änderungen.

cu TooWaBoo

**Comment by heckflosse** [comment]
Sorry, ich war etwas beschäftigt. Werde versuchen das heute zu erledigen.

Ingo

**Comment by Beep6581** [comment]
The Deutsch file has many "\n" newlines in history messages which don't exist in the original "default" file. I understand this may be because German words are long and horizontal space in the History panel is very limited. Please confirm that you are aware of the extra newlines and that you have done so intentionally.

**Comment by TooWaBoo** [comment]
@Beep6581 
Yes, I'm aware of the "\n" newlines. I want to keep the width of the history panel as small as possible.

**Comment by heckflosse** [comment]
ein kleiner Korrekturvorschlag:

statt

+TP_RETINEX_VARIANCE_TOOLTIP;Niedrige Werte erhöhen den lokalen Kontrast und Sättigung, können aber zu Artefakte führen.

besser

+TP_RETINEX_VARIANCE_TOOLTIP;Niedrige Werte erhöhen lokalen Kontrast und Sättigung, können aber zu Artefakten führen.

oder

+TP_RETINEX_VARIANCE_TOOLTIP;Niedrige Werte erhöhen den lokalen Kontrast und die Sättigung, können aber zu Artefakten führen.


Ansonsten ist mit nichts ins Auge gesprungen. Falls doch, kann immer noch nachgebessert werden ;-)

Vielen Dank und nochmals Entschuldigung für die Verspätung beim Durchsehen

Ingo

**Comment by TooWaBoo** [comment]
Finished :-)
Link is updated in the first post.

cu TooWaBoo

**Comment by Beep6581** [comment]
Dankeschon, committed.
