### ISSUE TITLE
Hide JPG files when RAW is present

### ISSUE THREAD

**Issue by neilpho** [Beep6581/RawTherapee#2942]
In the manner of Lightroom it would be good if JPG versions of RAW files were hidden. A badge on the RAW thumbnail would indicate the presence of a matching JPG.

This would help those of us who shoot RAW+JPG.

**Comment by sguyader** [comment]
Can't you simply use the Filter tab, enable Metadata filtering and filter based on "File type"?

**Comment by neilpho** [comment]
I can't because not all images are in RAW+JPG, some are JPG only. Even within a single session.

Lightroom defaults to this behaviour for good reason.

**Comment by neilpho** [comment]
Lightroom treats JPGs as sidecar files, which really they are, when there is a raw version.

**Comment by adamreichold** [comment]
Hello, I just opened pull request #2970 which tries to implement such functionality using the existing filter mechanism. Maybe you could give it a try whether the implementation seem useful w.r.t. this issue?

**Comment by adamreichold** [comment]
@neilpho Since PR #2970 was merged, I think this can be closed?

**Comment by Beep6581** [comment]
Yes, done in https://github.com/Beep6581/RawTherapee/pull/2970
