### ISSUE TITLE
Lens distorsion correction

### ISSUE THREAD

**Issue by falket** [Beep6581/RawTherapee#2944]
Hello everyone,

 i would like to fix distorsion for some of my shots and i have found out that (whilst hoping for a lensfun solution) lcp correction often leads to unexpected results (read makes distorsion even worser).

I have tried with a Sigma 10 20mm 4-5.6 mounted on a Pentax K20, here are the original raw files, the pp3, the lcp profile from dng converter (can i upload it? If not i'll delete the maybe copyrighted file) and the results are simply wrong (look at the window at the top right):

https://goo.gl/lvRpQV

Branch: master
Version: 4.2.448
Changeset: 26d182dabc6f133c27bffa3aac3f91b7ae55d578
Compiler: cc 4.8.4
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V2.24.4
Build type: release
Build flags:  -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG
Link flags:   -march=native
OpenMP support: ON
MMAP support: ON

This happens also for example with the sigma 17 70 2.8 4.

**Comment by sguyader** [comment]
I'm not sure, but maybe the lens profiles you use were made using camera
with a diffrent crop factor?
I tried creating a basic LCP profile myself for my Samyang 12mm, and it
does a proper job for distortion in RT. So I don't think it's a bug in RT.

**Comment by falket** [comment]
Thank you for the idea. But the lcp contains a value crop factor 1.5, and Pentax for now has only aps digital cameras.

Here is the beginning of the lcp.

<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Adobe XMP Core 5.3-c007 1.136881, 2010/06/10-18:11:35        ">
 <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about=""
    xmlns:photoshop="http://ns.adobe.com/photoshop/1.0/"
    xmlns:stCamera="http://ns.adobe.com/photoshop/1.0/camera-profile">
   <photoshop:CameraProfiles>
    <rdf:Seq>
     <rdf:li>
      <rdf:Description
       stCamera:Author="Adobe (www.adobe.com)"
       stCamera:Make="PENTAX"
       stCamera:CameraRawProfile="True"
       stCamera:Lens="Sigma Lens"
       stCamera:CameraPrettyName="PENTAX"
       stCamera:LensPrettyName="SIGMA 10-20mm F4-5.6 EX DC / HSM"
       stCamera:ProfileName="Adobe (SIGMA 10-20mm F4-5.6 EX DC / HSM, PENTAX)"
       stCamera:SensorFormatFactor="1.5"
       stCamera:FocalLength="10"

**Comment by Beep6581** [comment]
Hello

The person who implemented LCP support in RawTherapee wrote that some LCPs are just bad, full of bad control points, though they still work with Adobe software as Adobe uses proprietary and undocumented error-filtering code.

Until lensfun support arrives, your best bet is to create the LCP yourself. The procedure is easy and well-documented.

There is nothing to be done in this issue.
