### ISSUE TITLE
LAB curves do not reset when new file is opened

### ISSUE THREAD

**Issue by mbaz** [Beep6581/RawTherapee#2945]
I'm using RT version 4.2.1 on windows 7.

I edit a photo and modify its LAB curves. When I load a new picture (using the Neutral profile) the curves do not reset.

**Comment by Beep6581** [comment]
When a new image is loaded the curves are whatever they are set to in the PP3. If you now change the curve type to a different type, one what was used previously in that RT session, they will use the old curve shape. It's an aid.

**Comment by mbaz** [comment]
Thanks for the reply. It may be just my workflow, but I find that I seldom
want to apply the same curves to two pictures. So, I need to manually reset
the curves almost every time I load a new picture.
