### ISSUE TITLE
LAB curves not reset when going back in history

### ISSUE THREAD

**Issue by mbaz** [Beep6581/RawTherapee#2946]
I'm using RT 4.2.1 on Windows 7. I edit a picture, including modifying its LAB curves, and then click back on its history, going back to an early change (before the LAB curves were modified). When I look at the LAB curves, they still have the modified values, i.e. they were not reset.

**Comment by Beep6581** [comment]
Cannot reproduce. What are the steps to reproduce? Which curve specifically?

**Comment by mbaz** [comment]
Open a file to edit. Do some changes -- white balance, noise suppression, etc. Now, select the Exposure tab and LAB Adjustments. Set (for example) CC to parametric, and incrase the "Saturated" slider to 50. Now, on the history panel on the left, click on "Photo loaded". Set the CC curve to parametric again; the Saturated slider will be set to 50.

This is probably related to #2945, and is the intended behavior. I still find this disconcerting, though, since to me, going back in history means undoing all changes. This is also inconsistent, since most sliders are reset, but not all.

If this is indeed the intended behavior, then please feel free to close the bug.

**Comment by Beep6581** [comment]
Going back in history in your example works flawlessly, the curve got set to what it was. Since at that point in history the parametric curve was not set to anything, RT lets you use your last-used setting as a starting point if you now switch to the parametric curve. You will find this comes in useful when working on series of shots.

**Comment by mbaz** [comment]
Thanks for explaining the rationale behind this behavior.
