### ISSUE TITLE
Filmstrip's height is a bit too short making vertical scrollbars appear

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#2948]
The Filmstrip's automatically calculated height is just a bit too short, making the vertical scrollbar always appear.

**Comment by Hombre57** [comment]
There's a hack for that in the code, just search for "Hack" in the cc files, you should easily find it.

**Comment by Beep6581** [comment]
Fixed in a9aa5308b5bb3c155ecaf6ab4adea2034186b589

**Comment by Beep6581** [comment]
Properly worked around in #2983
