### ISSUE TITLE
Segmentation fault during RGB curves: parametric mode

### ISSUE THREAD

**Issue by innir** [Beep6581/RawTherapee#2950]
Hi,

I got a bug report in Debian:
> Dear Maintainer,
> 
> I am a complete beginner with rawtherapee and was trying out some functions.
> I stumbled upon this Segfault which is easily reproducible:
> 
> Here is how it occurs:
>   * load an image (any format will do, in my case NEF or JPG, different sizes)
>   * choose "Color" tab
>   * select "parametric" for any color in "RGB Curves"
>   * change e.g. "Highlights" ("Darks") to a value >0 (<0), close to the maximum (minimum)
>   * move rightmost (leftmost) slider in horizontal color bar to the right (left)
>   * a kink develops in the curve
>   * -> Segfault
> 
> Even though nobody might ever do this for their photos, the program should not crash.
> 
> It happens for any image, so the existence of a pp3 file does not matter.
> 
> Regards,
> Tobias

See also: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=801540

Best,
Philip

**Comment by heckflosse** [comment]
I fixed this bug some time ago. https://github.com/Beep6581/RawTherapee/issues/2923 and https://github.com/Beep6581/RawTherapee/issues/2888
