### ISSUE TITLE
SEGV in rtengine::HaldCLUT::correct()

### ISSUE THREAD

**Issue by innir** [Beep6581/RawTherapee#2951]
Hi,

another report - I'm not sure if it's still reproducible, I tried a little and was not able to:

> Dear Maintainer,
> 
> Film simulation is a great tool to instantly get your
> colors right. That's why I'm experimenting a lot with
> it. Unfortunately there seems to be a problem:
> - Entering a directory with RAWs using film simulation
>   in their pp3s, or
> - changing the simulated film in before-after view, or
> - going from editor back to file list
> sometimes crashes the application. In that case, it will
> often crash again, as soon as the thumbnail for the
> affected image becomes visible or the image itself
> is double-clicked.
> 
> Program received signal SIGSEGV, Segmentation fault.
> [Switching to Thread 0x7fff99ffb700 (LWP 1673)]
> 0x0000555555c427b4 in rtengine::HaldCLUT::correct(rtengine::Imagefloat&, int, float, float, float, float&, float&, float&) ()
> (gdb) bt
> #0  0x0000555555c427b4 in rtengine::HaldCLUT::correct(rtengine::Imagefloat&, int, float, float, float, float&, float&, float&) ()
> #1  0x0000555555ad923c in ?? ()
> #2  0x00007ffff363f716 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
> #3  0x00007ffff32070a4 in start_thread (arg=0x7fff99ffb700) at pthread_create.c:309
> #4  0x00007ffff2f3bcbd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
> 
> Program received signal SIGSEGV, Segmentation fault.
> [Switching to Thread 0x7fffc67fc700 (LWP 1779)]
> 0x0000555555c427b4 in rtengine::HaldCLUT::correct(rtengine::Imagefloat&, int, float, float, float, float&, float&, float&) ()
> (gdb) bt
> #0  0x0000555555c427b4 in rtengine::HaldCLUT::correct(rtengine::Imagefloat&, int, float, float, float, float&, float&, float&) ()
> #1  0x0000555555ad923c in ?? ()
> #2  0x00007ffff363b7df in GOMP_parallel () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
> #3  0x0000555555ac93e4 in rtengine::ImProcFunctions::rgbProc(rtengine::Imagefloat*, rtengine::LabImage*, rtengine::EditBuffer*, LUT<float>&, LUT<float>&, LUT<float>&, rtengine::SHMap*, int, LUT<float>&, LUT<float>&, LUT<float>&, float, float, rtengine::ColorGradientCurve const&, rtengine::OpacityCurve const&, bool, LUT<float>&, LUT<float>&, rtengine::ToneCurve const&, rtengine::ToneCurve const&, rtengine::ToneCurve const&, rtengine::ToneCurve const&, double&, double&, double&, float&, float&, float&, double, int, int) ()
> #4  0x0000555555ba27dc in rtengine::Thumbnail::processImage(rtengine::procparams::ProcParams const&, int, rtengine::TypeInterpolation, std::string, double, double, float, float, float, float, std::string, double&) ()
> #5  0x00005555559ce7f6 in Thumbnail::processThumbImage(rtengine::procparams::ProcParams const&, int, double&) ()
> #6  0x000055555586db80 in ThumbImageUpdater::Impl::processNextJob() ()
> #7  0x00007ffff6d4bb02 in ?? () from /usr/lib/x86_64-linux-gnu/libglibmm-2.4.so.1
> #8  0x00007ffff6fdd2b8 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
> #9  0x00007ffff6fdc925 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
> #10 0x00007ffff32070a4 in start_thread (arg=0x7fffc67fc700) at pthread_create.c:309
> #11 0x00007ffff2f3bcbd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
> 
> It might be also related to cropping, as it only
> started to happen after a crop was applied.
> 
> I already removed the whole cache, but that made
> it effectivly crash more often.
> 
> I hope this has already been fixed upstream, so
> it won't take to long to find the culprit.
> 
> Best,
> Björn

See: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=769028

Best,
Philip

**Comment by Beep6581** [comment]
Hey
Please see http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports
and supply:
- the raw file + PP3 + HALD CLUT (or its name, if its shipped in the RawTherapee Film Simulation Collection,
- the AboutThisBuild contents
- details of your system and RAM
- a stack backtrace using a debug build, not a release type build,
- anything else stated there.

**Comment by innir** [comment]
I guess it's a duplicate of #2558. So it's already fixed.
