### ISSUE TITLE
Metadata settings ignored in batch queue processing

### ISSUE THREAD

**Issue by softwarelimits** [Beep6581/RawTherapee#2955]
I add some metadata modifications to the profile, but the generated pictures do not contain any of these modifications. I tried several things, no matter how I try, the metadata of the original pictures is always copied unmodified to the resulting jpg images. 

```
[Exif]
Exif.DateTimeDigitized=#delete
Exif.ExifVersion=#delete
Exif.ExposureBiasValue=#delete
Exif.ExposureProgram=#delete
Exif.ExposureTime=#delete
Exif.FileSource=#delete
Exif.Flash=#delete
Exif.FNumber=#delete
Exif.FocalLength=#delete
Exif.ISOSpeedRatings=#delete
Exif.MaxApertureValue=#delete
Exif.MeteringMode=#delete
Make=#delete
Model=#delete

[IPTC]
Author=;
AuthorsPosition=;
Caption=;
CaptionWriter=;
Category=;
City=;
Copyright=Free for non-commercial use.;
Country=;
Credit=;
DateCreated=;
Headline=;
Instructions=;
Province=;
Source=some source;
Title=;
TransReference=;
```

**Comment by Beep6581** [comment]
http://rawpedia.rawtherapee.com/Preferences#Metadata

**Comment by softwarelimits** [comment]
Bingo! Thank you very much for the quick reply! 
OK, but then it is at least a GUI issue - shouldn't the meta-data tab be unselectable if the preferences do not allow editing of metadata - or at least show some warning? Is there any situation when editing metadata without actually applying the changes to the resulting picture makes sense?

```
if (prefs.metadatacopy == "on") {
  display.warning("changes will not be applied if you do not change preferences!")
} 
```

**Comment by Beep6581** [comment]
That's a good idea.
@Hombre57 any contraindications?

**Comment by Beep6581** [comment]
Handled by #3647
