### ISSUE TITLE
FR: Please add multiple size options for resizing to multiple image sizes in batch queue

### ISSUE THREAD

**Issue by softwarelimits** [Beep6581/RawTherapee#2956]
Feature Request: 
It would be a great enhancement to be able to specify multiple image sizes for the resize process - currently the resize tool seems to be limited to only one resize process for each batch export process. 
It is a very common usecase that a user would like to generate multiple different resulting image sizes for several media types (print, web large, web small) - but also would like to use RT for the resizing and not any other tool, e.g. to use the post resize sharpening. Currently for every image size one has to apply another profile, what results in redundant processing operations for each and every image size. 
This could be solved by being able to add multiple output sizes to the resize tool. 
Thanks for your attention!

**Comment by Beep6581** [comment]
Each size would require its own post-resize sharpening setting. RT's toolchain isn't flexible like that.

All you need to do is to select all files in the File Browser, change the resize parameters and ctrl+b to add the selection to the queue. * Change resize parameters again, ctrl+b. Repeat.

* To avoid running full processing on each image which takes time, you could now select the saved images instead, assuming you first downscaled to a large size and now want to downscale further.
