### ISSUE TITLE
Sometimes scrollbar height in Gtk3 slim modes gets thicker

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#2957]
Sometimes scrollbar height in Gtk3 slim modes gets thicker. Fixit.

**Comment by Hombre57** [comment]
FYI, in order to solve some bugs, I've updated my Gtk3 install to 3.18. RT is now broken here, so I'll make a halt on that branch, and see if I want to cope with Gtk again some day soon.

**Comment by Beep6581** [comment]
I don't remember what this bug is about, closing.
