### ISSUE TITLE
EOS 5DS R not recognized

### ISSUE THREAD

**Issue by sjprg** [Beep6581/RawTherapee#2961]
Canon 5DS R not recognized

**Comment by iliasg** [comment]
Do you use a recent RT version ?.

**Comment by Beep6581** [comment]
sjprg upload a sample raw file and AboutThisBuild.txt contents
http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports

**Comment by sjprg** [comment]
I am using the latest trial download from RT website.

**Comment by sjprg** [comment]
File is too large to attach even zipped

**Comment by heckflosse** [comment]
Upload to http://filebin.net/ and post the link here

**Comment by fliker09** [comment]
https://filebin.net/wnm27io0x01z9w3c/5DS.zip
http://i.imgur.com/dTvHeTm.png

Branch: default
Version: 4.2.0
Changeset: c81d9026d25c
Compiler: x86_64-linux-gnu-gcc 5.2.1
Processor: undefined
System: Linux
Bit depth: 64 bits
Gtkmm: V2.24.4
Build type: Release
Build flags: -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -std=c++11 -D_FORTIFY_SOURCE=2   -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG
Link flags:  -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed
OpenMP support: ON
MMAP support: ON

If more details needed - just ask!

**Comment by Beep6581** [comment]
Works fine in the [latest development version](http://rawtherapee.com/downloads).
https://i.imgur.com/tXjSV7y.png

**Comment by fliker09** [comment]
Great! Is it possible to get latest version (which it is by the number, btw?) without compiling? May be some PPA?

**Comment by Beep6581** [comment]
Yes, see our downloads page.
I don't know which version by number that is, around 1000.

**Comment by fliker09** [comment]
I don't see anything for Linux here :\
http://i.imgur.com/p2s2JeG.png

**Comment by Beep6581** [comment]
Click Platforms > Ubuntu.
