### ISSUE TITLE
Retinex versus Tone-mapping - newretinex branch

### ISSUE THREAD

**Issue by Desmis** [Beep6581/RawTherapee#2969]
I am trying to develop an algorithm (personnel) to allow Retinex simulate a "tone-mapping effect"
I will post a change probably tomorrow...
:)

**Comment by heckflosse** [comment]
Jacques, I'm working on making retinex usable for non raw images (tiff,jpg). This requires some code movements between different source files. I hope it will not conflict too much with your changes. Should I wait with my changes until you posted your changes and then make them based on your changes?

Ingo

**Comment by Desmis** [comment]
Salut Ingo

I'll post my change tomorrow. I have introduced an iteration loop in "ipretinex.cc", and various adjustments to ipretinex...and of cource GUI....
No changes to Rawimagesource.cc.
I think your proposition is good (wait and change after).

Thank you :)

Jacques

**Comment by heckflosse** [comment]
Ok :)

**Comment by Desmis** [comment]
Ingo

I just push the change..I call the new branch "retinexadd" to 'allow' other things that Tone-mapping

Amicalement
Jacques

**Comment by Beep6581** [comment]
Cool, can't wait to test! :)

**Comment by heckflosse** [comment]
Jacques, I'll need some more time for non-raw retinex. So please don't hesitate to push new changes. I'll push my changes this week (don't know exactly when).

Ingo

**Comment by Desmis** [comment]
Ingo, OK:)

I just push a change with;
* fixed segfault when using Iterations and Hue equalizer
* add a slider for Gradient strength

Nota : 
* all gradient are empirical and we can change range...
* we can also do differently, do not play directly with iterations (actually when "iteration" increase all gradient are in the same way (more or less)) but alternative...Before we must test the current solution

:)

**Comment by Desmis** [comment]
I have update "Rawpedia" (always in french) to 'explain'  "Retinex versus Tone-mapping" :)

**Comment by Beep6581** [comment]
Interesting results can be had with this addition, let's keep it.

Jacques what do you think about renaming:
* Gain to Contrast
* Offset to Brightness
* Neighboring pixels to Radius
Easier to understand?

**Comment by Desmis** [comment]
DrSlony
We can rename as we want, although the 3 "old" names seem more in line.

Ok for "Gain" and "Contrast"
Ok for "offset" and "Brightness"
But for "Neighboring pixels", "Sigma" seems closer to me.

Do you want, I update...?

**Comment by Beep6581** [comment]
I understand they are more inline with the research behind Retinex, but for users (photographers) I think "sigma" means... not much?

**Comment by Desmis** [comment]
then OK to "radius"...but the value is not radius, as indeed sigma !

So I update ?? Very easy to do :)

**Comment by Desmis** [comment]
But if one is in the semantics, it would be reviewing many names in RT, eg :
* Unsharp mask, Deconvolution, damping, edge stopping, variance, etc. which I think are at least as abstruse as offset or Gain...:)

**Comment by Desmis** [comment]
I just push these changes, and also a small modification to "gaussian gradient"

**Comment by Desmis** [comment]
Just another change, to take into account "Highlight method" for "Gaussian gradient"

I update Rawpedia !

**Comment by Desmis** [comment]
Ingo

Can I push a change ...tomorrow morning, or must I wait ?

**Comment by heckflosse** [comment]
Jacques, no problem. I wait.

**Comment by Desmis** [comment]
I just push a change with a "Mask method" (I took the idea with Russell Cottrell plugin).
You can used 3 functions
* a single "diagonal contrast curve"...very fast but be aware to artifacts
* a Gaussian mask, fast...
* a wavelet mask (I took and change the Emil's code!) ...slow or very very slow (about 10 or 30 seconds)

Ingo, now you can :)

**Comment by Desmis** [comment]
I think it is easy to reduce by 50% the time wavelet, but now I await the TIFF / JPG change Ingo

I'll update Rawpedia !

**Comment by heckflosse** [comment]
Jacques, I'll need a bit to code a good solution for TIFF/JPG retinex. But it's no problem if you change the functions 'retinex', 'retinexpreparebuffers', 'retinexpreparecurves' and 'MSR' meanwhile. So just go on :+1: It's mostly copy&paste to include modified versions of the functions into my changes.

Ingo

**Comment by Desmis** [comment]
Ingo
Thank you :)

I just push a change with:
* numerous bug fixed
* acceleration of sharp mask (wavelet)
* add a combobox for "preview" with 3 choices : 
** standard = normal display
** Mask : display the mask generate by Retinex on which you can act
** Transmission : display an image of "Transmission Map file" before action on Contrast (gain) and Brightness (offset). Attention it is not the real datas, but they are "shift" to make visible

**Comment by Desmis** [comment]
I have updated  Rawpedia (always in french)...
For me both "Mask method" + Preview transmission" is a major advance for Retinex!

**Comment by Beep6581** [comment]
I haven't tried today's changes out yet, but this sounds like a similar addition to the Wavelet tool, so I wanted to say that it would be good if one could not just preview but also save the mask image (for use in GIMP/PS/etc), and in that case it should not be called "Preview" (the similar option in Wavelet was also initially called "Preview" though it influenced the saved image) but "Process".

**Comment by Desmis** [comment]
No problem, it's only a semantic problem...When you send to TIFF/JPEG "mask" or "Transmission" are saved :)

**Comment by Desmis** [comment]
It should be noted that export the image "Transmission" is possible, but in my opinion of no use ...

Some remarks of semantics (again):
* I really do not think change "Gain" for "Contrast" is a good thing in some cases the slider increases the contrast in others not. It can be called "Gain", "amplification", "multiplier", etc. Its real function : multiply "transmission map" values! 

* Offset vs Brightness or Lightness is acceptable
* We can rename "Variance" by "Contrast", because I think it corresponds substantially to the result .Even if in addition to the contrast  this slider add  relief effects "Tone-mapping" type.

**Comment by Desmis** [comment]
Ingo
Can I push a change without it bothering you ?
The files concerned are "retinex.cc (GUI)" and MSR function in "ipretinex.cc"
Thank you :)

**Comment by heckflosse** [comment]
Jacques, of course.

**Comment by Desmis** [comment]
I just push a chnage ==> I have add;
1) an auto mode to Process "Transmission"...I don't think it's better or worst than the other, but different..
2) always in Process a "Unshap mask"...you can generate images with high or very high radius Unsharp mask, with some settings of retinex ...
:)

**Comment by Desmis** [comment]
Hello all
I am working on "wavelet" to establish an "unsharp mask" from the process "Above the level" and Background = Residual.
 My initial tests show that it works very well and should be able to imagine many combinations...and perhaps a "Wavelet retinex"!!
Before continuing development includes a section on the GUI, I would like to know if:
1) I included these new features in "retinexadd" ?
2) or I open a new branch ?

:)

**Comment by Beep6581** [comment]
@Desmis @he

**Comment by Beep6581** [comment]
@Desmis I get a lot of this in the console:
```
.................................................................................
.................................................................................
.................................................................................
```
Could you clean up the printfs in ipretinex.cc if you don't need them?
```
471:                    printf("..");
568:            printf(".\n");
```

**Comment by Beep6581** [comment]
Thank you for these additions. The Retinex tool is now very configurable, but also very hard to understand. Some of this difficulty can be removed by making the interface more clear:

1. There is now a "Process (Preview)" combobox at the end of the Retinex tool, and it affects the whole Retinex tool, hiding most of the Retinex tool's widgets when preview is anything but "standard". The position of this combobox is semantically misleading. I think it should be moved into the very top of the Settings expander

2. There is also a new "Mask" section, it pops out five sliders and a curve when mask method is anything but "None". Again it would be more clear to the user if this whole Mask section was at least inside a frame if not a MyExpander. Otherwise we need to append "Mask " to every mask adjuster label, e.g. from "Highlights" to "Mask highlights", from "Highlights tonal width" to "Mask highlights tonal width", etc. I think a frame or MyExpander is cleaner.

3. The tooltip for "Mask method" says "Use the mask generated by the Gaussian function above". Which function above is the gaussian function specifically?

4. Many of the tooltips lacked dots at the end of sentences and before \n.

5. Please review the following tooltips, as they refer to adjusters which have been renamed and I don't know which ones these are:
TP_RETINEX_GRAD_TOOLTIP
TP_RETINEX_GRADS_TOOLTIP
TP_RETINEX_SCALES_TOOLTIP

Please remember to run `git pull` before making changes, as I committed some fixes in https://github.com/Beep6581/RawTherapee/commit/d146809651e2a676e816ef0aeb3a52f4532727b7

**Comment by Desmis** [comment]
I have create a new branch : "newretinex" with the changes above
Now you can try Retinex :)

I try to delete "retinexadd"
git branch -dr origin/retinexad
git says me : 
$ git branch -dr origin/retinexadd
Branche de suivi origin/retinexadd supprimée (précédemment edd88be).

But if I look to GitHub...retinexadd is always here :)

**Comment by Beep6581** [comment]
Great, I will test in the evening.

To delete the branch: `git branch -D retinexadd`
To clean up your list of branches: `git fetch origin --prune`
or you can go to https://github.com/Beep6581/RawTherapee/pull/3055 and click on the [Delete branch] button below the last comment.

By the way, there is a little "bell" icon for notifications in the top-right corner of every GitHub page !(http://i.imgur.com/vyl4zk8.png). If you click it you will see all places on GitHub where someone wrote your name with a @ before it, e.g. @Desmis, and all issues which you are watching where there has been activity. Checking it every time you visit GitHub is the easiest way of keeping track of discussions which are relevant to you.

**Comment by Desmis** [comment]
Hello DrSlony
I have ben away some days...
Thank you very much for your help, now I master a little GIT :)
In the doc I saw for delete a branch  : git branch -Dr retinexadd ! is the "r" necessary ?

Thank you again :)

**Comment by Beep6581** [comment]
I'm not entirely sure, but I think that if you `git branch -D retinexadd` and then clean up using `git fetch origin --prune`, then the -r is unnecessary. Maybe you don't have to do --prune if you used -r while deleting? I don't know yet :)

**Comment by Beep6581** [comment]
@Desmis partial-paste in this branch is broken. Open a photo, apply some profile, enable retinex and set for example strength to 100. Copy the profile with the "processing profile fill mode" button pressed 
![profile-filled](https://cloud.githubusercontent.com/assets/5844619/12374309/cd991fca-bc97-11e5-9888-4e09523ed6c3.png) Now apply the Neutral profile, which resets everything, set the "processing profile fill mode" off ![profile-partial](https://cloud.githubusercontent.com/assets/5844619/12374315/e7d8bcce-bc97-11e5-8eb3-47df89b0040b.png) and partial-paste just the Retinex tool. Result: everything gets pasted, not just Retinex.

**Comment by Desmis** [comment]
@Beep6581 
Hello DrSlony
I did a full review after your comment above
1) solved
2) solved
3) solved
4)5)6) for me everything works as it should...but Retinex tool is very versatile and depends on many parameters. So according to images action on masks will be more or less pronounced
7) solved
:)
I'll look to your image !

I have update Rawpedia Retinex in french, essentially change the texts to meet different locations changes

@heckflosse 
Ingo, 2 months ago you planned changes, what is it?
I sent you a message on your home address in the last few days
:)

**Comment by Beep6581** [comment]
4, 5, 6) Yes, should first study the documentation you wrote on RawPedia.
The rest - great :)

**Comment by Desmis** [comment]
I simplify GUI interface of Retinex : Process (logical), Mask method (suppress 'curve only'...it is the same functionnality with Sliders "Gaussian mask" to zero

**Comment by Desmis** [comment]
If you  have proposition to improve ? :)

**Comment by gaaned92** [comment]
In order to try newretinex, I am building a win32 build. I suggest you rebase if possible the branch at least to avoid a lot of warnings. Thanks.

**Comment by Desmis** [comment]
Qu'est-ce que tu entends par "rebase if possible the branch"...?  :)

**Comment by gaaned92** [comment]
Newretinex est très en retard sur la branche master. Ce serait bien de la remettre à niveau. 
Quelqu'un peut-il aider à remettre la branche newretinex au niveau de la branche master?

Can somebody help to put the retinex branch at master branch level?

**Comment by gaaned92** [comment]
WIN 32 relwithdebinfo build available here :https://drive.google.com/open?id=0B2q9OrgyDEfPOEZmVlBzLWlnSWc

**Comment by Desmis** [comment]
Merci @gaaned92  pour ce lien :)

Je tiens à préciser (in french..ce qui correspond pour les anglophones à la même difficulté que l'anglais pour moi):
1) les opérations "merge" sont pour moi stressante...Pour mémoire ce qui a valu que la précédente branche Retinex ait été fusionnée...tient plus de l'obstination à arriver à quelque  chose et au hasard, qu'à une volonté de "fusionner malgré tout"...de plus je n'ai aucune formation "informatique" (sinon un peu de FORTRAN IV, avec cartes perforées en 1970!)
2) je ne suis pas à l'aise avec ces manipulations, qui sont - c'est un euphémisme de le dire - mal exprimées dans tous les tutoriels...j'en veux pour témoignage de l'effacement d'une branche. On me dit pour effacer  la branche "reinexadd" sur le serveur: "git branch -D retinexadd."..cela ne fonctionne pas, après recherches sur le net :"git push origin --delete retinexadd", qui fonctionne
3) lorsque je propose d'importantes nouveautés en termes d'algorithmes. Je propose toujours une première version très rustique où j'ai "arrangé a minima" le GUI pour que cela fonctionne (il est évident que l'interface GUI suivra lorsque l'algo sera au point et approuvé). On me demande tout, tout se suite, c'est particulièrement contraignant, car fixer le GUI...fixe d'une certaine manière l'algorithme. Bref je suis en train de le faire pour "newwavelet", mais là encore, les choix de regroupement (qu'est-ce qui est dans quoi ?) sont purement arbitraires :)

Merci de m'avoir lu!
Jacques

**Comment by Beep6581** [comment]
I merged master into newretinex and fixed some merge conflicts. Builds fine.

**Comment by Beep6581** [comment]
I tested it for half an hour, no crashes and no issue. It is a useful addition, +1 for merge.

Here are several versions of the same photo just to demonstrate:
http://filebin.net/htxc3yofny

**Comment by Desmis** [comment]
Thank you DrSlony
If no opposition, could you merge for me :)

**Comment by Beep6581** [comment]
Sure, I'll just first wait for an "ok" from Ingo or Adam.

**Comment by Desmis** [comment]
No problem :)

**Comment by Beep6581** [comment]
Done, merged into master.
You can delete the branch using the "Delete branch" button here:
https://github.com/Beep6581/RawTherapee/pull/3111
You can also close this issue - we can address any bugs in a new one.

**Comment by Desmis** [comment]
DrSlony
Thank you very much...with this button it's easy to delete :)

**Comment by Beep6581** [comment]
You're welcome.
So I'll close this issue then.

**Comment by Beep6581** [comment]
P.S. I just merged master into gtk3, so gtk3 now has the latest Retinex tool.

**Comment by Desmis** [comment]
Thank you. I'll test :)

**Comment by Desmis** [comment]
I found a forgotten in viewMethod (standard)
I also used Astylert for Retinex.cc
I just pushed the change to branch gtk3
:)
