### ISSUE TITLE
Adding keywords and supl categories does not work

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#2978]
Gtk3 branch, META -> IPTC panel, when you add keywords or supplemental categories, they are added to the combobox, but not to the scrolledwindow beneath
http://i.imgur.com/yNcQ5xX.png

Probably related, when I click on the empty scrolledwindow this appears in the console:
```(rawtherapee:9312): Gtk-CRITICAL **: file /var/tmp/portage/x11-libs/gtk+-3.16.7/work/gtk+-3.16.7/gtk/a11y/gtktreeviewaccessible.c: line 295 (get_visible_column): should not be reached```

**Comment by adamreichold** [comment]
The [branch](https://github.com/adamreichold/RawTherapee/tree/fix-iptc-list-views) should fix this as I think this is only a typo, i.e. calling `remove_all_columns` instead of `clear_items` which is why no columns are visible in the two list views.

**Comment by Beep6581** [comment]
Fix confirmed, will merge tomorrow if no objections.

**Comment by Beep6581** [comment]
Thank you, merged.
