### ISSUE TITLE
Target the Filmstrip/File Browser frame directly with CSS

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#2983]
The FileBrowser area, whether viewed in the File Browser tab or as the FilmStrip in an Editor tab, contains a frame. The frame's padding causes bugs #2948 and #2949.

![filebrowserframe](https://cloud.githubusercontent.com/assets/5844619/11318643/6d312622-905b-11e5-96c1-6ae9676fa018.jpg)

Commit d8ad81c85c62adc4ecfefefb72699614d5d0067a removes the padding which works around these bugs. However I'm not entirely happy with how its done, because I would prefer to find this frame in our code and give it a class, but I can't find it! So I did the next-best thing and gave the containing element a class "`.filebrowser`" and used the CSS selector "`.filebrowser GtkFrame`" to target it. This is perfectly valid use of CSS however it would be better if we could add_class directly to this frame. Some Gtk+ elements use "internal" structures and we would use only the containing element, which might be the case here and if that is so then this issue can be closed as there is no better solution. However I will leave this issue open for a few weeks because maybe @Hombre57 or someone else has more luck finding this specific frame.

**Comment by Hombre57** [comment]
It's line 36 of rtgui/thumbbrowserbase.cc.

**Comment by Beep6581** [comment]
Thank you
