### ISSUE TITLE
Blue image after processing

### ISSUE THREAD

**Issue by gaudry-daniel** [Beep6581/RawTherapee#2984]
Hi,
The image (link below) from RT is blue what can I do?
May be my setting are wrong ??
I give the raw, jpg and setting file
Best regards
 http://filebin.net/5w2kutjtby

**Comment by Beep6581** [comment]
You need to change the bit depth in the metadata from "12" to "14", until we implement a solution on our end. The method of doing so is explained here:
http://rawtherapee.com/forum/viewtopic.php?p=44209#p44209
