### ISSUE TITLE
Parameters synchronization

### ISSUE THREAD

**Issue by kaolpr** [Beep6581/RawTherapee#2985]
Would it be possible to implement a synchronization of photo development parameters between photos (feature present in LR)? It would greatly speed up development of series of photos taken in similar conditions.

**Comment by Beep6581** [comment]
Copy the profile from one photo, paste it to many others:
http://rawpedia.rawtherapee.com/The_File_Browser_Tab

**Comment by mks9900** [comment]
DrSlony and kaolpr: I've used Lightroom on and off for a long time, and the feature I think kaolpr thinks of (please correct me) is a feature I my self miss: There's a button simply called "Previous" in LR that when pressed, applies the previous image's settings to the current image. Quite handy if you forgot to press Ctrl+C on the first image, meaning you don't have to spend time to go back and forth (F3/F4) to do so. :-)

**Comment by Beep6581** [comment]
But you don't need F3/F4, just copy it from the Filmstrip http://rawpedia.rawtherapee.com/The_Image_Editor_Tab#The_Filmstrip
I'm not against a "copy from previous image" shortcut if that is indeed what kaolpr is asking for (though I don't believe it is, as I've seen the sync feature in LR and that is not the same thing, and the "previous" feature is a separate thing), but considering RT lets you edit in METM and SETM (LR only has SETM) and this proposed feature would require one of us to figure out what is intuitive to users, e.g. in METM is "the previous image" the last-viewed tab or is the the last-worked-on one? Is there even a right answer? And if not, why implement an unintuitive feature? Considering this dilemma, and considering the solutions in my previous post, I don't think this is needed.
