### ISSUE TITLE
Nederlands translation

### ISSUE THREAD

**Issue by wtermeer** [Beep6581/RawTherapee#2986]
Update of the Dutch language file.
https://www.dropbox.com/s/5k6nr5wdiybdd9x/Nederlands?dl=0

**Comment by Beep6581** [comment]
Thank you!

P.S. You will noticed I replaced "#14 2015-11-23 updated to rt4.2.something by wim ter meer" with "#14 2015-11-23 update by wim ter meer", please skip the version number in the future.
