### ISSUE TITLE
New DCP Camera Profiles made with DCamProf

### ISSUE THREAD

**Issue by stefan-i** [Beep6581/RawTherapee#2989]
Hi,
to my surprise I actually managed to learn how to use DCamProf (I followed "the easy way" method here: http://www.ludd.ltu.se/~torger/photography/camera-profiling.html#the_easy_way) and have updated the profiles of all cameras I own(ed).   

The following DCPs are included:
Canon PowerShot S110 (single illuminant daylight)
Pentax K-5 (single illuminant daylight)
Pentax K-5 II (dual illuminant daylight/tungsten)
Canon PowerShot G7 X (dual illuminant daylight/tungsten)

The K-5 II and G7 X profiles are based on the same CC24 shots as from this earlier issue (https://github.com/Beep6581/RawTherapee/issues/2919) but I think it's worth to update them as the latest DCamProf versions since then have included some important bugfixes for clipping and heavily saturated colors. In addition, the new glare matching feature has improved especially the tungsten profiles (much lower Delta E values).
Download here: http://filebin.net/kijgwu4dgc

**Comment by Beep6581** [comment]
Hey
Could you make the source raw files available?

**Comment by stefan-i** [comment]
No problem, I added them to the filebin link above.
One small correction: The Pentax K-5 II Daylight shot is different from the one used in issue 2919. I noticed that the daylight and tungsten images were shot with a different lens, so I used another daylight image that was shot with the same lens (Pentax DA*55/1.4) as the tungsten one for better consistency.

**Comment by Beep6581** [comment]
Thank you. May we add them to our (publicly available) collection of color target shots?

@il

**Comment by stefan-i** [comment]
Sure, you may add them to the color target collection (good idea, by the way!)

**Comment by stefan-i** [comment]
Even if it's not easy for a beginner to understand, I think DCamProf is worth the effort to learn and gives outstanding results. The "killer feature" IMO is the embedded tone curve with the neutral tone reproduction operator. The curve usually gives a very good starting point (mostly close to the embedded JPG), and if one then sets exposure compensation, black point and maybe highlight compression and does the rest of the adjustments (contrast, lightness, saturation) within the CIECAM module one has great and clean colors from start to finish. Nice!

By the way, the "Perceptual" curve mode within RT (which I understand is supposed to be similar to the neutral tone operator) still seems to suffer from some artifacts (especially with dark blue colors), whereas the embedded curve in the DCamProf DCPs now seems to work perfectly in these cases.

**Comment by stefan-i** [comment]
Any news on this? Are the profiles OK to be included?

**Comment by iliasg** [comment]
Hi Stefan, I forgot to make any evaluation job on these, I will do it tonight ..

**Comment by Beep6581** [comment]
iliasG I would like to recreate these DCPs, and more, using the latest version of dcamprof, but I have quite a lot of work to do before I get to that. I could try doing that tonight or tomorrow.

**Comment by iliasg** [comment]
I have some difficult days now for valuable work also, best hope is during weekend, mainly in evaluating-measuring.
BTW I cannot experiment with dcamprof as there is no win32 bit build available ..

**Comment by stefan-i** [comment]
Nothing seems to be happening here? 

Anyway, I created one more dual illuminant profile for the Pentax K-3. I uploaded it together with the Raw CC24 shots here:
http://filebin.net/0eppncjsvc
I also added the other files from above to this new link. 
Please use this new link and not the one in the first post because I noticed I made an error with the Canon S110 and Pentax K-5 profiles above - I uploaded older versions of profiles made with DCamProf 0.10.2 instead of the latest 0.10.4. The files here are now all made with DCamProf 0.10.4.

For quality control purposes, these are the average and median DeltaE values of the profiles as measured by DCamProf:

**Canon PowerShot G7 X**
Daylight: average 1.58, median 1.30
Tungsten: average 1.88, median 2.23

**Canon PowerShot S110 **
Daylight: average 2.38, median 2.09

**Pentax K-3**
Daylight: average 1.83, median 1.59
Tungsten: average 1.88, median 1.77

**Pentax K-5** 
Daylight: average 1.63 , median 1.52

**Pentax K-5 II **
Daylight: average 1.49, median 1.33
Tungsten: average 1.81, median 1.97

**Comment by Beep6581** [comment]
Just so you know, I am working on this ;)

**Comment by stefan-i** [comment]
OK, great, no worries :)
If the weather is right at the week-end (a big if at the moment...) I can probably supply another profile for the Fuji X100T next week.

**Comment by stefan-i** [comment]
The weather turned out fine and sunny so I could take a nice daylight shot in a suitable location yesterday. Daylight and tungsten CC24 shots and dual illuminant profile for the Fujifilm X100T can thus be found here:
http://filebin.net/iqg07ofgtm

DeltaE statistics:
Daylight: average 1.81,  median 1.56 
Tungsten: average 1.85, median 2.03

For reference, these are the command lines used to create these and the other profiles above with DCamProf:

Daylight:
dcamprof make-profile -g cc24-layout.json -i D50 -C cc24.ti3 my-profile.json 

Tungsten:
dcamprof make-profile -g cc24-layout.json -i StdA cc24.ti3 my-profile.json

**Comment by stefan-i** [comment]
One usage note: I noticed that the file "Pentax K-3.dcp" needs to be renamed to "Ricoh Pentax K-3.dcp" for the auto-detection in RT to find the profile for the K-3. Apparently Pentax changed the naming convention compared to earlier DSLRs.

**Comment by Beep6581** [comment]
Yes, RawTherapee finds the correct DCP based on the name of the DCP file which must match the name of the camera model as reported in the "i" info dialog. As such, I name the raw files accordingly.
http://rawtherapee.com/shared/test_images/colortarget/

**Comment by stefan-i** [comment]
You seem to have forgotten the profile for the Fuji X100T?

**Comment by Beep6581** [comment]
Oops, I'll add it shortly.

**Comment by stefan-i** [comment]
Thanks. I noticed in your logs that you seem to be getting noticeably worse DeltaE values than I did with the same CC24 shots. I wonder what is going on here? Could you post the command line you used, I couldn't find this in the log file?

**Comment by Beep6581** [comment]
The lowest DE are not always the best.
https://discuss.pixls.us/t/easily-generate-dcp-profiles-using-dcamprof-and-this-bash-script/897

**Comment by sguyader** [comment]
Some time ago, @iliasg made a dcp profile for the Fujifilm X-T1. Where can I find it? Is it the best profile for this camera to use with RawTherapee?

**Comment by iliasg** [comment]
@sguyader Seb, https://drive.google.com/file/d/0B0NqktTgc54sdGFCRWwwc3ZPcEk/view?usp=sharing
But I think it is not a good profile, very saturated colors in general and the usual problem of oversaturated blues which is common for profiles built by x-rite's passport utility.

**Comment by Beep6581** [comment]
Added
https://github.com/Beep6581/RawTherapee/commit/98dd99103d8ab164185b8ad74bd8d17234cf4fe3

**Comment by ben-richardson** [comment]
@Beep6581 You mentioned a "(publicly available) collection of color target shots" above. Is that still available?

**Comment by Beep6581** [comment]
@ben-richardson Yes, http://rawtherapee.com/shared/test_images/colortarget/
