### ISSUE TITLE
Some issues with GUI translation in "default"

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#2992]
<b>TP_WAVELET_CONTEDIT;'After' contrast curve</b>  points to <b>HISTORY_MSG_367;W - ES - Local contrast curve</b> -> History message text is wrong.
__________

Demosaik method Bayer- and X-Trans-Matrix are using two History messages together, depending on the selected entry. <b>HISTORY_MSG_98;Demosaicing method</b> and <b>HISTORY_MSG_167;Demosaicing method</b>. I guess it’s mixed up and one History message should be for Bayer and the other one for X-Trans.
__________

Bayer- and X-Trans-Matrix <b>TP_RAW_FALSECOLOR;False color suppression steps</b> are using the same History message <b>HISTORY_MSG_115;False color suppression</b>. To make the History message unique, they should point to two different History messages.
__________

The key <b>MAIN_BUTTON_SENDTOEDITOR</b> is still missing.
See: http://rawtherapee.com/forum/viewtopic.php?f=4&t=6215#p43389
__________

cu TooWaBoo

**Comment by Beep6581** [comment]
1- @de

**Comment by TooWaBoo** [comment]
Thanks for your fast replay.
3- You can use both methods with the same photo, but one of them has no effect. If users playing arround with the tools, the History message doesn't show a unique setting. But it's not a big deal.
