### ISSUE TITLE
Opening an image in SETM doesn't work

### ISSUE THREAD

**Issue by Hombre57** [Beep6581/RawTherapee#2997]
In RT4.2.534, double clicking on a thumbnail in the File Browser tab does not send the file to the Editor immediately. You can wait any longer you want, it only start when switching to the Editor tab.

**Comment by adamreichold** [comment]
Is this on the `master` or `gtk3` branch? My current guess is `gtk3` since `master` reports version 4.2.503 here and the function seems to work.

**Comment by adamreichold** [comment]
I think some constant redrawing might be happening in the `gtk3` brach which blocks or at least slows down background processing. Does applying the one-liner from issue #2990 change this apparent behaviour for you? For me it does at least change the perceived behaviour from 'it takes forever' to 'it takes a bit'.

**Comment by Hombre57** [comment]
Yes, the one line change in issue #2990 does solve the problem. Thanks !
