### ISSUE TITLE
Lenses are not recognized on Panasonic cameras

### ISSUE THREAD

**Issue by iliasg** [Beep6581/RawTherapee#2998]
Lenses are not recognized on Panasonic cameras. I tried with new and old Panasonic models with new and old (4.2.0) RT versions.
I cannot find any Panasonic lens data in xxx.. atribs.cc files. Although I found Panasonic lens data in Olympusattribs.cc 
Is RT supposed to read the lens info for Panasonic bodies from exif ?.

**Comment by Beep6581** [comment]
"I found Panasonic lens data in Olympusattribs.cc"
Do you mean the Lumix entries? exiftool has no "Panasonic" camera category, and it has the Lumix lenses in the "Olympus" category.

If you have xmlstarlet and exiftool installed:
```
xmlstarlet sel -T -t -m "taginfo/table/tag[@name='LensType']/values/key" -v "concat(@id,'   ',val)" -n < <(exiftool -listx -Olympus:all) | sed -r -e 's/   / = /' -e 's| F([0-9]+)| f/\1|g'
```

**Comment by iliasg** [comment]
OK .. but RT fails with Panasonic bodies while it's fine with Olympus bodies ..

**Comment by ghtma** [comment]
Unfortunately this issue is still open and not assigned. Any chance to get it fixed in the near future?

**Comment by Beep6581** [comment]
@ghtma can you upload some sample raw files? Use http://filebin.net/

**Comment by ghtma** [comment]
@Beep6581 
I have uploaded [three files](https://filebin.net/lle2xzp6r5r5wzns), one for each lens I own. The blue text in the image is the "LensType" read with ExifTool.

**Comment by ghtma** [comment]
Thanks for fixing the bug. Is a nightly build available to test it?

**Comment by Beep6581** [comment]
@ghtma you need a build from 2017-04-18 or newer. There are none yet, but when one is made it will appear here: https://discuss.pixls.us/t/download-rawtherapee-development-builds/2924
That's assuming you use Windows - you didn't state which OS you use.
