### ISSUE TITLE
Deutsch language update based on RT4.2.507

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#3002]
http://filebin.net/j5kirzvi6b

cu TooWaBoo

**Comment by Beep6581** [comment]
Thank you, committed.
Please set your text editor to use LF line endings, not CR+LF.

**Comment by TooWaBoo** [comment]
I had this before, but the "default" file uses CR+LF (0d 0a). So I changed it vom LF to CR+LF.

cu TooWaBoo

**Comment by Beep6581** [comment]
It doesn't - it uses LF, and I convert your translations to LF every time :)
I wanted to say that I love your bold and double-line solution to dealing with long words! I will implement that for default at some point.

**Comment by TooWaBoo** [comment]
Thanks :-)
