### ISSUE TITLE
Converting std::auto_ptr to std::unique_ptr

### ISSUE THREAD

**Issue by Hombre57** [Beep6581/RawTherapee#3010]
std::auto_ptr are deprecated now, this pull request convert them to std::unique_ptr

See the new branch, based on the gtk3 branch but could be applied to master as well.

**Comment by adamreichold** [comment]
I definitely agree to this very useful change as the deprecation warnings are pretty annoying and the semantics of `std::auto_ptr` a quite problematic. However, `std::unique_ptr` is a C++11 feature which means that if we want to use it, we have to mandate C++11 and should change the build system accordingly.

Therefore I would suggest doing that only on the `gtk3` branch and also fixing a minimum GCC version we are targeting (also best checked using CMake). As discussed before, my personal suggestions would be C++11 and GCC 4.8 or even better C++14 and GCC 5 which is more future proof and will become GCC's default anyway.

P.S.: You can specify the target branch when creating a pull request, e.g. create PR to merge `gtk3-converting-to-unique-ptr` into `gtk3` as well, e.g. using [this page](https://github.com/Beep6581/RawTherapee/compare/gtk3...gtk3-converting-to-unique-ptr).

**Comment by adamreichold** [comment]
Also if you we would go for C++14, we should also add usage of `std::make_unique` where we use `std::unique_ptr`.

**Comment by Hombre57** [comment]
Adam, I think I'm definitely not the one to make such change related to C++ standards. I thought that the fix for the std::auto_ptr would be straightforward, but that's not the case (for me), so I'll let you or anyone fluent with this kind of thing do.

I agree with raising the requirement to gcc5 for the gtk3 branch though.

And thanks for the pull request tip ;)

**Comment by Hombre57** [comment]
Btw, because we don't know each other yet, I'm only a self-trained developer, that's not my daily job, so I help but do what I can, and will let Gtk and/or C++ specialist do in 99% of the case :), and will take care of any suggestion/advice/comment.

**Comment by adamreichold** [comment]
@Hombre57 I took your branch and added the discussed build system changes in PR #3011. Let's see what Ingo's opinion is on what C++/GCC versions are appropriate for the `gtk3` branch...

**Comment by Beep6581** [comment]
I would appreciate if you could use C++11 and GCC-4.9 for a few months as GCC5 is still not an option for some.

**Comment by adamreichold** [comment]
@Beep6581 Since @heckflosse preferred the same combination (C++11 and GCC 4.9), PR #3011 was rebased yesterday to use that instead of C++14 and GCC 5.0. In any case, making good and judicious use of the new features is probably more important than fixing the compiler version, but with the PR, we can begin working on such improvements.

**Comment by adamreichold** [comment]
@Beep6581 This will among other things be cleaned-up by pull request #3040 which beings to make use of C++11 language features to improve code maintainability.

**Comment by adamreichold** [comment]
Closed after merge #3040.

**Comment by Beep6581** [comment]
Hey @adamreichold, just for your information I upgraded to GCC-5.3.0, so that is what I do my testing on.

**Comment by adamreichold** [comment]
@Beep6581 Nice to know we are using the same compiler version then. ;-) Should hopefully yield faster builds and better build diagnostics. I am currently thinking about how I can run a copy of GCC 4.9 on my Arch box as to make sure not to break Ingo's builds, but the C++ ABI of my system is obviously the new one which GCC 4.9 does not support. Probably need to go with a VM or container or something... (I think OpenSUSE stuck to 4.9 with Leap 42.1, so this sounds like a nice candidate.)

**Comment by heckflosse** [comment]
@adamreichold Don't worry about my builds. As soon as I completed my work on some speedup Issues I'll upgrade to new Win64 gcc whatever version. For me the only problem is that we say to support gcc 4.9.x but we don't support it.

Ingo

**Comment by adamreichold** [comment]
@heckflosse Why do you say that we do not support GCC 4.9? #3072 is definitely an error on my part even though I am not yet sure why it builds here. (The include hierarchy is really messy which is why I am thinking of running GCC 4.9 to catch that stuff locally.) The problem with #3070 seems to be that the packages are built using GCC 4.8 everywhere, even though GCC 4.9 (and newer) is available on those distributions.
