### ISSUE TITLE
Windows version

### ISSUE THREAD

**Issue by ivanzanolla** [Beep6581/RawTherapee#3021]
Hi, I have been using RawTherapee for more years but the Windows Version is very older than Linux Version.

Could you compile also RawTherapee with latest featurest? Thanks

**Comment by sguyader** [comment]
Hello,
I make windows build regularly, you can download them on my google Drive:
https://drive.google.com/folder/d/0B_AvPFlUj8t5SUdodURGOFdOems/edit
Sebastien

**Comment by ivanzanolla** [comment]
Wow thank you very much. Why these versions aren't put in the official site?

Could me explain how to compile myself a version?

Thank's :)

**Comment by sguyader** [comment]
I don't have the rights to upload my builds to the main site, but if you
look carefully at the right place (http://rawtherapee.com/downloads) you'll
see fairly recent builds for Windows made by Michaelezra and DrSlony (I
actually don't know why my builds never find their way to the main site,
but it's not a problem).
Regarding compilation instructions, you'll have a number of things to set
up before, and I don't have the time right now to write these instructions
for you. You can find some instructions in the COMPILE.TXT file placed in
the RT install forlder, which can give you the first steps already.

-Sebastien

**Comment by Beep6581** [comment]
sguyander I do occasionally put your builds on the site, at least those that Michael hasn't already made. We appreciate you making them.

**Comment by sguyader** [comment]
Oh OK, sorry I only saw those made by Michael!
