### ISSUE TITLE
Segfault in Denoise Auto Multizone mode when smoothing set to max in preferences

### ISSUE THREAD

**Issue by FM33** [Beep6581/RawTherapee#3022]
Hello,

When I process files with auto multizone denoising, I encounter frequent crash (every 2-3 pictures in queue) and get a different result against the preview.

Branch: master
Version: 4.2.514
Changeset: 09062a95076bb3c2b3c63fb053047df5780be226
Compiler: cc 4.8.4
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V2.24.4
Build type: release
Build flags:  -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG
Link flags:   -march=native
OpenMP support: ON
MMAP support: ON

![render difference](https://cloud.githubusercontent.com/assets/6499232/11808057/5049da88-a31e-11e5-9739-b5deabb34be8.png)
[Crash while processing.txt](https://github.com/Beep6581/RawTherapee/files/62300/Crash.while.processing.txt)

**Comment by FM33** [comment]
PEF & PP3 available here (unable to upload on github) : 
https://webcloud.zaclys.com/index.php/s/lmM4zOyvsEyownV

**Comment by Beep6581** [comment]
Please provide a stack backtrace:
http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports

The preview not matching the output is normal for this mode:
http://rawpedia.rawtherapee.com/Noise_Reduction#Auto_multi-zones

**Comment by FM33** [comment]
[bt full.txt](https://github.com/Beep6581/RawTherapee/files/63815/bt.full.txt)

**Comment by heckflosse** [comment]
The crash is in Shadows/Highlights /Sharp mask, not in Denoise

**Comment by heckflosse** [comment]
@FM33 : can you please post a screenshot of this part of preferences : http://filebin.net/7fd4vkca4c/options.png

**Comment by FM33** [comment]
![perfprefs](https://cloud.githubusercontent.com/assets/6499232/11842281/0fb546a2-a403-11e5-8884-97ed0f411e25.png)

**Comment by heckflosse** [comment]
@FM33 : Thanks. Now I can reproduce the crash

**Comment by heckflosse** [comment]
Though the crash occurred later in pipeline, the reason for the crash was an access to uninitialized variables in denoise processing. I'll push a fix in a few minutes.
