### ISSUE TITLE
Retinex shows wrong colors when changing "Working Profile"

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#3026]
To reproduce this bug, do the following steps:
1. Open an image and apply Neutral profile
2. Switch Retinex on
3. Change "Working Profile" from ProPhoto to sRGB
-> Image shows wrong colors

Switching Retinex off and on corrects the colors.

cu TooWaBoo

**Comment by Beep6581** [comment]
Confirmed in gtk3 branch merged with renderingintent branch.

**Comment by Hombre57** [comment]
Is it specifically in this branch ?

**Comment by Beep6581** [comment]
No, that's just the branch I had lying around at the time :) Confirmed also in branch add-monitor-profile-and-softproofing

**Comment by Beep6581** [comment]
Still valid in master.
Beep @Desmis

**Comment by Beep6581** [comment]
@Desmis have you seen this issue?

**Comment by Desmis** [comment]
I think it is solved :)

**Comment by Beep6581** [comment]
Yes, I confirm it is fixed.
