### ISSUE TITLE
Corrupted mRAW from Canon 7D

### ISSUE THREAD

**Issue by tymmej** [Beep6581/RawTherapee#3030]
RawTherapee: Branch: master
Version: 4.2.521
Changeset: 1650333b2a911e21c2e59bdf889005bff872bf9e
Compiler: clang-mp-3 3.7.0
Processor: generic x86
System: Apple
Bit depth: 64 bits
Gtkmm: V2.24.4
Build type: Release
Build flags: -w -I/opt/local/include/libomp -L/opt/local/lib/libomp -fopenmp=libomp -mtune=generic -Werror=unused-label   -Werror=unknown-pragmas -O3 -DNDEBUG
Link flags:  -mtune=generic
OpenMP support: ON
MMAP support: ON
(http://rawtherapee.com/releases_head/mac/RawTherapee_OSX_10.11_64_4.2.521.zip)
OS: Mac OS 10.11

Description: When using mRAW format on Canon 7D photo has two parts with different brightness. This doesn't happen on normal RAW. Image looks normal in camera and using other (Affinity Photo) software. Divide between two parts of image is always in the same place.
Files: mRAW from Canon 7D, JPEG on default profile, pp3 file. http://filebin.net/034exmnrgi

**Comment by tymmej** [comment]
The problem was lens profile for Canon 15-85 lens. After disabling vignette it works fine.

I'm not sure if it's problem with lens profile or handling of lens profile in RawTherapee.

**Comment by Beep6581** [comment]
LCP implementation can behave strange at some zoom levels.
On a side-note, good to see that the OS X 10.11 build runs fine!
