### ISSUE TITLE
Inscape not found when rebuilding the icons

### ISSUE THREAD

**Issue by Hombre57** [Beep6581/RawTherapee#3031]
The path in tools/source_icons/script/svg2png.bash is wrong if Inkscape/64 is installed.

Is it possible to modify this script to use an environment variable (e.g. INKSCAPE_EXE) that sets where to find the executable (including the executable's filename) ? Moreover with a Windows path format ?

If yes, the caller script should stop if this variable doesn't exist.

**Comment by Beep6581** [comment]
I don't know as I don't use Windows, but just go ahead and change line 52. It's not like anybody else uses it other than us, and I'm covered by line 54 :)

**Comment by Hombre57** [comment]
Ok, I'll push it to master when done.
