### ISSUE TITLE
LTO linking fails - undefined reference

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3034]
@adamreichold when I try to compile PR #3028 using -DWITH_LTO="ON", regardless whether I do or don't use -DCMAKE_CXX_FLAGS="-std=c++11", I get this failure:
https://dpaste.de/kivj/raw
GCC-4.9.3

**Comment by adamreichold** [comment]
I think errors like
````
/usr/bin/ar: CMakeFiles/rtexif.dir/rtexif.cc.o: plugin needed to handle lto object
````
indicate a problem with the linker plug-ins on the build machine. It might go away after you update gcc and binutils, but you can also try symlinking `lto_plugin.so` into `bfd_plugins` or using `CMAKE_AR` and `CMAKE_RANLIB` to use `gcc-ar` and `gcc-ranlib` as described in the following links:
https://forums.gentoo.org/viewtopic-t-993248.html?sid=cf65184661ef5e26fafda56ca1f738b7
https://bugs.archlinux.org/task/43367
https://cmake.org/Bug/view.php?id=15547

**Comment by Beep6581** [comment]
Thank you Adam. They mention in one of the bug reports GCC-5.1 made a gcc-ar symlink which should prevent this. I'll close this issue and try LTO again once I upgrade to GCC-5.3.
