### ISSUE TITLE
Windows XP 32 bits and multilangmgr.cc

### ISSUE THREAD

**Issue by sguyader** [Beep6581/RawTherapee#3041]
A user sent me a message regrading the error he encounters when trying my win32 builds on his Windows XP 32 bits machine. when trying to launch the program, he gets the following error message:

http://imgur.com/zhC5Ryx

I tried the patch by @adamreichold (issue #3028) but compilation failed with this error message (in fact instead of using the patch, I modified manually the multilangmgr.cc file accordingly, I hope I didn't introduce a mistake, otherwise if someone can tell me the commands to patch the file it would be great):

	C:/Rawtherapee-sources/rtrepo/rtgui/multilangmgr.cc: In member function 'Glib::ustring MultiLangMgr::getOSUserLanguage()':
	C:/Rawtherapee-sources/rtrepo/rtgui/multilangmgr.cc:151:14: error: expected primary-expression before 'langID'
	 +       LCID langID = GetUserDefaultLCID();
				  ^
	C:/Rawtherapee-sources/rtrepo/rtgui/multilangmgr.cc:154:27: error: 'langID' was not declared in this scope
			 if (GetLocaleInfo(langID, LOCALE_SNAME, langRFC, 64) != 0 && lstrlen(langRFC) >= 2) {
							   ^
	rtgui/CMakeFiles/rth.dir/build.make:2022 : la recette pour la cible « rtgui/CMakeFiles/rth.dir/multilangmgr.cc.obj » a échouée
	make[2]: *** [rtgui/CMakeFiles/rth.dir/multilangmgr.cc.obj] Erreur 1
	make[2]: *** Attente des tâches non terminées....
	CMakeFiles/Makefile2:235 : la recette pour la cible « rtgui/CMakeFiles/rth.dir/all » a échouée
	make[1]: *** [rtgui/CMakeFiles/rth.dir/all] Erreur 2
	Makefile:127 : la recette pour la cible « all » a échouée
	make: *** [all] Erreur 2

**Comment by Beep6581** [comment]
@sguyader I think you made a mistake, there shouldn't be a "+" in that compilation failure.
1. Go to `C:/Rawtherapee-sources` and write `git reset --hard HEAD` to undo your changes.
2. Download this file and save it to `C:/Rawtherapee-sources/adam.patch` http://filebin.net/0vm1mkvpag/adam.patch
3. Go to `C:/Rawtherapee-sources` and run `git apply adam.patch`
Then try compiling again.

**Comment by sguyader** [comment]
Now I'm feeling stupid... I didn't see any extra "+"... @Beep6581 I followed your steps, and it compiled fine. I updated my google drive with patched Win32 builds, let's see how it works for XP 32 used.

**Comment by adamreichold** [comment]
@sguyader Did you test whether using the system language in the RT preferences actually does what it is supposed using this patch? I think @gaaned92 reported that it does compile, he also said, that it does _not_ work...

**Comment by sguyader** [comment]
On my Win7 64 bits machine, language selection works with your patch. I usually use Rawtherapee in English, and I can switch from English to French, and "System language" does also switch to French.
I don't know if it works on other versions of Windows.

**Comment by iliasg** [comment]
Seb, your last build (4.2.539) works fine with or without -mstackrealign on my winvista32. The one with no -mstackrealign is around 1.5% faster on LMMSE demosaic with 6 step enhancement.
As expected the "System Language" works fine switching from english (or any selected) to system (greek).

May I ask why are these dublicates in build flags  ?
[AboutThisBuild.txt](https://github.com/Beep6581/RawTherapee/files/72476/AboutThisBuild.txt)

**Comment by adamreichold** [comment]
Does this mean I should commit the `GetUserDefaultLocaleName` patch to master?

**Comment by sguyader** [comment]
@adamreichold your patch works for selecting languages, as reported by a user (Brian Beezley) on his Win XP 32 bits machine.
@iliasg yes my google drive is open to everyone, they have access to Win64, Win32 and Win32-mstackrealign versions (including Debug version). Some flags are duplicated probably because I lost my .cmake config files and I probably messed in the new one (also I use "-DPROC_TARGET_NUMBER=1" which probably adds some flags on its own). I'll try to clean this up.

**Comment by Beep6581** [comment]
@adamreichold notice that in @iliasg's paste of @sguyader's build flags, there is "-std=gnu++0x". That shouldn't be there, right?

**Comment by adamreichold** [comment]
@Beep6581 I don't think it matters and it definitely should not have any impact of whether RT runs on Windows XP or not. (Which is also what my testing using VM confirmed.)

**Comment by sguyader** [comment]
Should I remove this flag for the win32 builds ?

**Comment by adamreichold** [comment]
@sguyader You can remove it from all builds after PR #3028 is merged. We will always set it internally then.

**Comment by gaaned92** [comment]
@adamreichold 
How I tested the langage patch:
- verify that local langage is set to FR : bottom righte langage toolbar on my XP conf
- open RT 
- deselect 'use system langage', set manually langage to english in preference, close RT and restart
- langage is english
- select 'use system langage' , close and restart
- langage should be french but it is still english

generally the last manually selected langage is kept on my system
If it works on other systems, I think patch could be commited, as it is always possible on XP to manually select langage.

**Comment by adamreichold** [comment]
Ok, so I did some digging and the code I provided should indeed only work on Vista and later as well. But I think I found the necessary steps to support the older versions as well and created the branch [`get-os-user-language-on-xp`](https://github.com/adamreichold/RawTherapee/tree/get-os-user-language-on-xp). Could you test again using this branch? Thank you!

**Comment by sguyader** [comment]
@adamreichold your branch compiles fine and on my Win7 64 bits, and the selection of the correct system language (French for me) works too.

**Comment by gaaned92** [comment]
@adamreichold  : branch compiles fine on WXP and now the selection of system language works.

**Comment by adamreichold** [comment]
@Beep6581 With the recent successful tests by @sguyader and @gaaned92 I am reasonably confident that this works on the various Windows versions we aim to support. Should I commit the last revision to master then?

**Comment by Beep6581** [comment]
Yes please.

**Comment by adamreichold** [comment]
Fixed by commit 31eef891185da3e832918d09f5b77a95bd66abe5.
