### ISSUE TITLE
g_get_home_dir_utf8 entry point not found in libglib-2.0-0.dll [gtk3 branch]

### ISSUE THREAD

**Issue by sguyader** [Beep6581/RawTherapee#3042]
I'm trying to make Gtk3 builds in MSYS2, all is fine until I try to launch RT, I get the error message written in title.
Any idea?

**Comment by adamreichold** [comment]
This sounds like you build RT with a different version of `glib` then is used to run it. Does it work when you run it from the MSYS2 prompt (where the environment is suitably set up)? Do you have any version of `glib` installed system-wide?

**Comment by sguyader** [comment]
It runs fine from MSYS2 prompt indeed. I don't think I have a glib dll installed system-wide (checked my PATH). Can I have a list of the dll's I should copy in the RT folder for Gtk3?

**Comment by adamreichold** [comment]
Well the list thing is complicated and will probably take some time to create, but you can't go wrong with just copying all DLL from `/mingw32/bin` resp. `/mingw64/bin`... (To crate such a list, I would copy the executable somewhere on a pristine VM and then need to iteratively copy DLL until there are no more dependency errors. There is also surely Windows tooling to do this, but I have very little experience with Windows development.)

**Comment by sguyader** [comment]
I did iterative run RT / copy the called dll, until I stumbled on this
error.

**Comment by adamreichold** [comment]
I guess that does mean that there is some version of `glib` on your path which was then loaded as an indirect dependency. What happens when you also copy `libglib-2.0-0.dll` from the MinGW folders?

**Comment by Beep6581** [comment]
@sguyader is this resolved?

**Comment by sguyader** [comment]
I don't know if it's solved, I have this problem compiling in the mingw64
environment (new issue opened)

**Comment by gaaned92** [comment]
@sguyader  to list all required dependencies, you can use dependency walker see www.dependencywalker.com.
When testing completness, you can change the name of all gtkmm, mingw, msys install dir  that are in PATH. Dont forget GIMP as it can be in PATH.

**Comment by sguyader** [comment]
Ok, I looked further, and indeed I found another libglib dll installed where I didn't excpect it (a program called Ggobi that I used only as a dependency for another program). So now launching RT passes this step, but I face another error message: 
(rawtherapee.exe:8460): GLib-GIO-ERROR **: No GSettings schemas are installed on the system.

**Comment by adamreichold** [comment]
Closing as requested by initial reporter.
