### ISSUE TITLE
gdkconfig.h: No such file or directory

### ISSUE THREAD

**Issue by sguyader** [Beep6581/RawTherapee#3044]
Now I use MSYS2 to compile RT for Windows. Since yesterday, I'm facing a new problem when trying to compile 64 bits binaries, I get the fowing error:

	In file included from C:/msys64/mingw64/include/gtk-2.0/gdk/gdkscreen.h:32:0,
					 from C:/msys64/mingw64/include/gtk-2.0/gdk/gdkapplaunchcontext.h:31,
					 from C:/msys64/mingw64/include/gtk-2.0/gdk/gdk.h:32,
					 from C:/msys64/mingw64/include/gdkmm-2.4/gdkmm/region.h:48,
					 from C:/msys64/mingw64/include/gdkmm-2.4/gdkmm/screen.h:32,
					 from C:/msys64/mingw64/include/gdkmm-2.4/gdkmm.h:27,
					 from C:/msys64/mingw64/include/gtkmm-2.4/gtkmm.h:89,
					 from C:/Rawtherapee-sources/rtrepo/rtgui/options.h:22,
					 from C:/Rawtherapee-sources/rtrepo/rtgui/cacheimagedata.h:23,
					 from C:/Rawtherapee-sources/rtrepo/rtexif/rtexif.cc:28:
	C:/msys64/mingw64/include/gtk-2.0/gdk/gdktypes.h:55:23: fatal error: gdkconfig.h: No such file or directory
	compilation terminated.
	rtexif/CMakeFiles/rtexif.dir/build.make:62 : la recette pour la cible « rtexif/CMakeFiles/rtexif.dir/rtexif.cc.obj » a échouée
	make[2]: *** [rtexif/CMakeFiles/rtexif.dir/rtexif.cc.obj] Erreur 1

gdkconfig.h is indeed missing from the mingw64 environment, but it is also missing in mingw32 though I do not get this error compiling 32 bits binary.
I thought it could be something I messed in my dependencies after trying to build the gtk3 branch, but I reinstalled them, I also did a fresh clone of the repository, and I still get this error.

**Comment by gaaned92** [comment]
@sguyader : I cannot really help but  in mingw32 I find gdktypes.h in E:\msys32\mingw32\lib\gtk-2.0\include and not in E:\msys32\mingw32\include\gtk-2.0\gdk , but it works!

**Comment by sguyader** [comment]
In fact gdktypes.h is there, but it looks for gdkconfig.h which is not there. I don't have this problem compiling un 32 bits environments, only the 64 bits one.

**Comment by sguyader** [comment]
@gaaned92 I think you wanted to say gdkconfig.h instead of gdktypes.h, because it is the former which is found in /mingw32/lib/gtk2.0/include.
In fact I copied this one and put it in /mingw64/lib/gtk2.0/include, and now c I can compile again in 64 bits.
Maybe did I accidentally delete it?

**Comment by adamreichold** [comment]
I have checked the package contents, i.e.
````
$ pacman -Ql mingw-w64-x86_64-gtk2 | grep gdkconfig
mingw-w64-x86_64-gtk2 /mingw64/lib/gtk-2.0/include/gdkconfig.h
````
So the header should be part of the package and your installation might have been corrupted. I'd suggest reinstalling a fresh MSYS2 environment. Do you mind if I close this then?

**Comment by sguyader** [comment]
OK you can close now.

**Comment by Beep6581** [comment]
Invalid
