### ISSUE TITLE
SSE4.1 version of Shadow Highlights Sharp mask. Try to activate SSE version of SH for 32 bit builds

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#3049]
In branch https://github.com/Beep6581/RawTherapee/tree/shmap_speedup I made a SSE4.1 version of vectorized LUT access. The only place where vectorized LUT access is used currently is in Shadow Highlights Sharp Mask. On my system the SSE4.1 version speeds up SH Sharp Mask from 1324 ms to 1160 ms for the usual D800 NEF.
Because we're now on gcc >= 4.9 I also enabled some stuff which was restricted to 64bit builds in past, for 32 bit builds. If that doesn't crash on 32bit builds, it should give a good speedup for SH Sharp mask with those builds.
If it doesn't work on 32bit builds I can easily restrict it to 64bit builds again.

Ingo

**Comment by heckflosse** [comment]
I forgot to mention that for generic builds the SSE4.1 opts will have no effect. At the moment they are only for native builds when your cpu supports SSE4.1

**Comment by gaaned92** [comment]
@Ingo  I tried the branch with following parameters 
Branch: shmap_speedup
Version: 4.2.541
Changeset: bc24d984158f5714de4d76b18ad8afe01223d915
Compiler: gcc 5.2.0
Processor: undefined
System: Windows
Bit depth: 32 bits
Gtkmm: V2.24.4
Build type: release
Build flags:  -m32  -mthreads -mstackrealign -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -std=gnu++0x -mwindows -DNDEBUG -msse2 -mfpmath=sse -O3
Link flags: -m32 -mthreads  -static-libgcc -Wl,--large-address-aware,--verbose  -march=native -mwindows -s -O3
OpenMP support: ON
MMAP support: ON

OS : WXP SP3
HW : Intel pentium 4 Prescott,  instructions : MMX, SSE, SSE2, SSE3, EM64T

The release build crashes on start.
With same build parameters, master branch runs ok
Ask If you need some other trial.
André

**Comment by heckflosse** [comment]
André, thanks a lot for testing this. Can you test starting RT in an empty folder too?
I hoped that using gcc 5.x would solve some issues with code generation on WIN32 systems...

Ingo

**Comment by Beep6581** [comment]
I tested neutral + shadows/highlights sharp mask:
http://filebin.net/csugo26cwx/sh_sm.pp3

Used the "benchmarkRT" script in /tools/ which saves the same image five times and takes an average.
Unpatched: 3.757s
Patched: 3.431s
i7 820QM @ 1.73GHz

**Comment by heckflosse** [comment]
@Beep6581 Thanks for testing. That's the speedup I expected at your system (with SSE4.1, but without FMA support). It's no big speedup, but IMHO we shouldn't stay supporting only SSE2 in future.

Ingo

**Comment by gaaned92** [comment]
@Ingo :  sorry, it crashes when opening a non empty directory
Don't know if it is useful : instruction at "0x008657b2" uses "0xffffffff"

**Comment by heckflosse** [comment]
André, thanks for your test. I'll try to detect the reason for the crash!

**Comment by heckflosse** [comment]
I made some changes and pushed to master branch. Speedup is only for native x64 builds.

Ingo
