### ISSUE TITLE
Impossible to compile with MSYS2 and Windows 8 64 bits

### ISSUE THREAD

**Issue by Desmis** [Beep6581/RawTherapee#3050]
I will speak in French, because my English is very bad ... and I do not want any.

J'ai été absent depuis le 20 décembre jusque hier (30 décembre après midi). J'ai pu voir les mises au point du nouvel environnement de compilation MSYS2 avec les mails reçus sur mon Smartphone, notamment les échanges  entre Sébastien Guyader et Ganned92, Adamreichod, DrSlony.
Je dois rappeler que je ne suis pas du tout informaticien, et que toute cette procédure est un peu (beaucoup) du Chinois!!

Lorsque je suis rentré hier, j'ai essayé d'appliquer à le lettre, les recommandations de Rawpedia (windows).
1) j'ai téléchargé : Msys-x86-64-20150916.exe
2) j'ai suivi les instructions repris en (1) pour MSYS2. A noter que au point 6 "Close MSYS2, run it again from Start menu and update the rest with"...il n'apparaît rien sur mon bureau, ni dans le menu de démarrage. Pour relancer MSYS2, j'ai  actionné l'invite de commande puis lancé "msys2_shell.bat"

3) j'ai ensuite lancé : "Mingw64_shell.bat"
4) puis toutes les commandes reprises dans Rawpedia
5) tout à l'air de bien se passer, même si il y a beaucoup de messages et qu'il est quasi impossible de repérer si il y a un dysfonctionnement
6) lorsqu'on arrive à "Install required libairies", il y a un message anormal : après la phase 2/33..."aucun schéma trouvé, aucune action effectuée"
7) puis on passe à "Download and build libiptcdata" : tout à l'air de fonctionner sinon un message de type : "iptce/po/makefile.in" seems to ignore
8) j'ai modifié Makefile avec "nano", puis "make"  et "make install"; dans msys64/home/jacques/ un dossier est créé avec" libiptcdat-1.0.4"
9) puis je passe à Clearlook, qui se passe sans problème sinon des messages d'alerte "warning" relatifs au link des fichiers lgdi32, lmon32, lshell32, lole32
10) le clone de RT se passe sans problème, puis "cd rawtherapee", puis "mkdir build" et "cd build"
11) puis "cmake -G "MSYS Makefiles"...etc.
12) tout commence bien, mais arrivé à "libiptcdata", j'obtiens 
-- Checking for module 'libiptcdata'
--   Package 'libiptcdata' not found
CMake Error at C:/msys64/mingw64/share/cmake-3.4/Modules/FindPkgConfig.cmake:365 (message):
  A required package was not found
Call Stack (most recent call first):
  C:/msys64/mingw64/share/cmake-3.4/Modules/FindPkgConfig.cmake:527 (_pkg_check_modules_internal)
  CMakeLists.txt:243 (pkg_check_modules)

J'ai essayé diverses parades : 
1) j'ai désinstallé et réinstallé MSYS2 2 fois: même problème...mais que c'est long de tout réinstaller!
2) en copiant "libiptcdata.pc" (à partir de home/jacques/libiptcdata-1.0.4/libiptcdat) dans msys64/mingw64/lib/pkconfig, on passe l'étape "cmake" de "libiptcdata"
3) mais ensuite lorsque je fais "make -j8", les fichiers suivants sont manquants : pthread.h, sched.h, stdint.h (pour libiptcdata). J'ai copié ces fichiers de l'environnement MINGW64 précédent
4) mais lorsque j'arrive au terme pour élaborer Rawtherapee.exe, j'ai un message qui m'indique qu'il manque "iptcdata"

J'ai examiné les variables d'environnement, aucune référence à Msys64 n'y figure : est-ce normal ? Rien n'est changé par rapport aux "SET" et "PATH" dans l'environnement MINGW

J'ai passé beaucoup de temps, plus de 8 heures à essayer, désinstaller, réinstaller, MSYS2 en suivant ligne par ligne tout ce qui est écrit (pour être sur des saisies je fais des copier/coller depuis Rawpedia jusque Msys64/Mingw64)

Est-ce que j'ai oublié quelque chose, est-ce que je ne fais pas certaines choses qui ne sont pas écrites ?
Est-ce que on peut m'aider ?

Bien sûr je peux essayer de traduire tout cela en anglishe...mais je doute de l'efficacité !

**Comment by Desmis** [comment]
Autre point troublant:
Lors du Cmake, certaines références se font avec l'ancien environnement MINGW, par exemple:
*-- Found PkgConfig: C:/gtkmm64/bin/pkg-config.exe (found version "0.23")
*  Found EXPAT: C:/MinGW64/lib/libexpat.dll.a (found version "2.1.0") alors que "Expat" a été installé par MSYS2!

**Comment by Hombre57** [comment]
Je pense que ton problème viens du fait que ton ancien environnement est toujours installé et utilisable car présent dans le PATH et dans la variable d'environnement PKG-CONFIG, à vérifier. J'espère en tout cas que l'installation de MSYS2 s'est bien passé si des varaibles existaient déjà et pointant au mauvais endroit. Il faut aussi respecter les conditions pour le chemain d'installation de MSYS2, à savoir pas d'espace ni de caractère spéciaux dans le chemin.

Si tu ne veux pas désinstaller ton ancien environnement, supprime en les références dans le PATH et supprimes les variables relatives à GTKMM. Tu devrais aussi recompiler libiptcdata et clearlooks dans ces nouvelles conditions, et avant cela, supprimer les fichiers pthread.h, sched.h, stdint.h importé (ils devraient être là).

Pour ma part, je n'ai pas réussi à compiler clearlooks, donc si ces nouvelles conditions te le permettent toujours, je suis preneur de la méthode (il ne trouve pas XML::Parser, je crois que je serais bon pour une réinstalle de MSYS2 :-( ).

Mais peut-être que @sguyader et @gaaned92 pourrons t'en dire plus

**Comment by Hombre57** [comment]
Et en quelle version de Windows es-tu ?

**Comment by Desmis** [comment]
Salut Hombre
Donc tu penses que ces problèmes viennent de l'ancien environnement ! Mais si je le supprime...est-ce que je peux encore compiler sous cet ancien environnement, en ayant "effacé" les PATH  ??

En tous cas, le moins que l'on puisse dire c'est que c'est diablement plus complexe qu'avant ! Il faut vraiment aimer Rawtherapee....(on est très très loin des compilateurs de Microsoft que j'utilisais pour Dcraw !!)

Je suis sous Windows8 

Merci  :)

**Comment by Hombre57** [comment]
Ben non, tu ne pourras plus, mais le nouveau te permet de compiler pour Gtk2 et Gtk3.

Je sais que ça  à l'air plus complexe, mais les mise à jour seront largement plus simple, et on peut compiler indiférement pour gtk2 et Gtk3, ce qui est un gros progrès sous Windows ! On passe d'une version de gcc à l'autre sans problème majeur (hormis bug inhérant à chaque nouvelles version, bien sûr).

Je fais moi-même un réinstalle complète sous Win7, on verra si je m'en sort aussi :)  ATTENTION à bien prendre en compte cette info sur la première ligne de la page Rawpedia / Compil windows : "Then run the following commands using either **MinGW-w64 Win32 Shell** or **MinGW-w64 Win64 Shell** depending on whether you want to build a **32-bit** or a **64-bit** version"

**Comment by Hombre57** [comment]
De plus, il faut désinstaller cmake, puisque cmake est fourni par MSYS2.

Pour le PATH, il faudra le compléter toi-même en y rajoutant `C:\msys64\mingw64\bin` selon ton dossier d'installation.

**Comment by Desmis** [comment]
Merci, j'ai bien vu tout cela...je vais réfléchir à comment sauvegarder l'environnement pour pouvoir le reconstituer...
Néanmoins il y a des trucs bizarres : 
1) pourquoi aucune variable d'environnement de de MSYS2 ?
2) pourquoi rien n'apparaît dans le "Start menu" et oblige au fichier *.bat
3) pourquoi les 3 fichiers *.h sont absents ? (pthread.h, sched.h, stdint.h)
4) pourquoi libiptcdata est-elle correctement installée et pas reconnue ?

Je veux bien encore "réinstaller MSYS2"...cela prend en gros 2 bonnes heures (avec Clealook et libiptcdat), mais je veux être à peu près sûr de mon coup !)

Mais - détail - je veux bien faire tout cela, mais nulle part il est dit dans Rawpedia de faire cela...désinstaller l'ancienne config, cmake,..., "bricoler" PATH, etc.

:)

**Comment by Hombre57** [comment]
1- MSYS2 a son propre PATH, qui inclus `/mingw64/bin`. L'ajouter au PATH de Windows ne servira qu'à se servir d'outil tel que cmake depuis une console Windows. Je vais demander à ce qu'il soit ajouter à RawPedia, de même que la variable PKG_CONFIG. Cela n'est pas fait automatiquement car on est censé n'utiliser que la console MSYS2 pour compiler, dans laquelle ces variables existent.
2- Je ne sais pas. Sous Win7, il y a bien une entrée dans le menu Windows
Ligne de commande pour MSYS2 Shell :
`C:\Windows\System32\cmd.exe /A /Q /K C:\msys64\msys2_shell.bat`
Ligne de commande pour MinGW-w64 Win64 Shell :
`C:\Windows\System32\cmd.exe /A /Q /K C:\msys64\mingw64_shell.bat`
3- sans doute à cause de la confusion avec ton environnement existant. Je n'ai pas eu ce problème à l'instant.
4- Il y a une erreur dans RawPedia pour la compilation de libiptcdata : il faut utiliser un préfix différent pour une version 32 et 64 bits. Dans notre cas (64 bits), il faut utiliser `--prefix=/mingw64`

Mon environnement de dev est terminé, j'ai enfin réussi à compiler clearlooks. Pas d'erreur à l'étape cmake, la compilation fonctionne, RT fonctionne.

**Comment by Desmis** [comment]
bon je verrais cela l'an prochain :)
Bonne année 2016 à tous !

**Comment by Hombre57** [comment]
Petite correction : RT se lance sans planter, mais ne trouve pas clearlooks! Il a pourtant bien été compilé, mais aucune dll n'a été produite (que de .a).

Bonne année 2016 Jacques

**Comment by sguyader** [comment]
@Hombre57, j'ai eu le même souci pour clearlooks, la compilation ne produit aucune dll sous mingw64, par contre ça a fonctionné sous mingw32. Du coup pour une build en 64 bits, j'utilise les anciennes dll 64 bits et ça fonctionne.
@Desmis, si d'ici 2016 tu n'y arrives pas, j'essaierai de t'aider. Mais pas avant samedi.

Bon réveillon à tous!
Happy new year's eve everybody!

**Comment by Desmis** [comment]
Bonjour à tous en cette nouvelle année 2016...Happy new year :)

L'année commence bien!
J'ai supprimé toutes les variables d'environnement de l'ancienne installation (MinGW), désinstallé MSYS2...nettoyé tout...
Puis installation de Msys2 avec libiptcdata en 64 bits

Tout se compile correctement...J'ai maintenant : 
* une version "debug" avec GTK2...que j'ai copiée dans un autre dossier, tout fonctionne correctement sauf ClearLook, mais cela ne me gêne pas trop.
* une version "release" avec GTK3, qui fonctionne correctement

Mais, dois-je comprendre qu'on ne peut installer qu'un seul "clone"...j'avais pris l'habitude dans installer 4, pour pouvoir "jongler" entre les diverses modifications. En fait cela n'est a priori pas gênant...et évite de se creuser inutilement les méninges.

Merci à tous :)

**Comment by Desmis** [comment]
Bonjour à tous !
je pensais que tout allait bien...mais...mais !

En fait, après avoir compilé sans problème, j'ai voulu générer Rawtherapee.exe à partir d'une autre branche que "master'...et là rien ne va plus...on peut même dire que plus rien ne va !!

Par exemple pour la branche "waveletsharp" (j'ai essayé avec une autre branche "retinexadd" et il y a la même difficulté!)

J'ai essayé:
a) à partir du même clone ou b)
b) en effaçant dans msys64/home/jacques   le dossier Rawtherapee
à partir de là b) j'ai rechargé un clone : 
$ git clone http://github.com/Beep6581/RawTherapee.git
puis
$ cd RawTherapee
puis 
$ git checkout waveletsharp
puis
$ mkdir build
puis 
$ cd build
puis Cmake
$ cmake -G "MSYS Makefiles" -DCMAKE_BUILD_TYPE="release" -DPROC_TARGET_NUMBER="2" -DBUILD_BUNDLE="ON" -DCMAKE_INSTALL_PREFIX="." -DBINDIR="." -DDATADIR="." -DCACHE_NAME_SUFFIX=4 ..

Jusque là tout se passe bien...mais après:
$ make -j8
Tout commence bien avec rtexif, et d'un seul coup...un nombre impressionnant de messages d'erreurs de compilation qui  défile à une vitesse qui en rend la lecture impossible...

Donc, même après effacement du dossier home\jacques\Rawtherapee...impossible de construire quoi que ce soit...si la branche n'est pas "master" ou "gtk3"

Sauf si bien sûr j'ai raté quelque chose où si il y a une manipulation à faire où si ce point a été évoqué dans d'autres "issues" ??  :)

**Comment by Hombre57** [comment]
Oui il y a des choses qui ont été faite pour que RT se compile avec gcc 5 utilisant l'ABI C++11 en standard. Ces branches n'ont sans doutes pas intégré ces changement qui ont été poussé vers master depuis quelques jours seulement. Avant de les compiler, vois si tu peux "merger" master dans ces branches (**et pas l'inverse**).

Pour info, tu peux très bien avoir autant de clone que tu veux, chacun étant calé [checkout] sur la tête [HEAD] que tu veux (dur dur de parler fransösich). La commande suivante présente dans Rawpedia :
```
   $ git clone http://github.com/Beep6581/RawTherapee.git
   $ cd RawTherapee
```
peut se transformer en :
```
   $ git clone http://github.com/Beep6581/RawTherapee.git RT-1
   $ cd RT-1
```
... sous entendu que le clone s'installera dans le dossier RT-1, et que si tu veux faire des opération Git sur ce clone, il faudra d'abord faire un `cd` pour être dans RT-1. Pour que le clonage initial se fasse, ce dossier doit être vide. La doc ne dit pas si ce dossier doit préexister où si Git le créera (mais je pense qu'il le créera).

Sur ce, re-Bonne Année 2016 ;)

**Comment by Hombre57** [comment]
PS:  je n'ai pas testé si la syntaxe du chemin de destination RT-1 est bonne, parfois linux est étrange : il faut écrire `./RT-1` pour signifier qu'on veut un sous-dossier à partir du `cd` courant. Mais dans un premier temps, essaie `RT-1` tout simplement.

**Comment by Desmis** [comment]
je veux bien essayer de merger "waveletsharp" avec master, mais comment fait-on ? sans faire de conn..ies ? :)

**Comment by Desmis** [comment]
ou plutôt l'inverse, mais cela ne change rien à la question !

**Comment by Hombre57** [comment]
En ligne de commande, je ne tenterais même pas (je ne sais pas), mais je peux le faire pour toi sous Eclipse si tu veux ; quels branches sont à mettre à jour ?

**Comment by Desmis** [comment]
Alors allons-y : 
* il y en a 3 : 
** waveletsharp
** retinexadd
** gammadif
Mais ce serait bien que quelqu'un me dise, comment faire en ligne de commande...cela ne doit pas être compliqué, mais pour éviter les emme...es :)

Merci par avance

**Comment by Desmis** [comment]
Pour plusieurs clones, j'ai essayé une autre solution qui marche (a priori...et à vérifier dans le temps).

Je copie l'ensemble du dossier "Rawtherapee" qui est dans "home\jacques", vers un dossier que j'ai créé auparavant par exemple G:\RTD...et cela à l'air de fonctionner :)

**Comment by Hombre57** [comment]
Je ne vois pas à quoi tu fais référence.

**Comment by Desmis** [comment]
Je ne sais pas si on parle de la même chose ?
1) oui je suis d'accord pour que tu "merges" MASTER dans "Waveletsharp", "retinexadd", "gammadif", 3 branches actuelles non "à jour"

2) par ce que j'évoque en
"Pour plusieurs clones, j'ai essayé une autre solution qui marche (a priori...et à vérifier dans le temps).

Je copie l'ensemble du dossier "Rawtherapee" qui est dans "home\jacques", vers un dossier que j'ai créé auparavant par exemple G:\RTD...et cela à l'air de fonctionner :)"

C'est la possibilité, simple de mon point de vue, de créer plusieurs dossiers (clones?) de RT en copiant "home\jacques\Rawtherapee" dans un autre dossier (vide) de mon choix. Chacun de ces dossiers est reconnu par Git :)

**Comment by sguyader** [comment]
Jacques, pour avoir plusieurs versions en répertoires distincts en
parallèle, il suffit de créer tes répertoires,par exemple
/home/jacques/rawtherapee/branche1, /home/jacques/rawtherapee/branche2,
/home/jacques/rawtherapee/branche3... Pour compiler branche1, tu fais cd
/home/jacques/rawtherapee/branche1 puis quand tu lances la configuration
cmake tu précises que les sources sont dans ../ (j'avais trouvé la commande
dans le script BuildRT).

**Comment by Desmis** [comment]
Hombre
Tout à l'air de fonctionner correctement...je viens de compiler la branche "waveletsharp"...et je vais (pas tout de suite) faire les autres....pour pouvoir reprendre ce que j'étais en train de faire avant ce "big-bang" pour RT.

Sébastien
Merci, je vais regarder ce qui me convient le mieux, pour dupliquer/mettre à jour plusieurs branches

Merci à vous deux...et encore bonne année...Dans 2 mois maintenant je vais me retrouver à la Guadeloupe pour passer 15 jours de vacances :)

**Comment by sguyader** [comment]
Merci Jacques pour tes voeux, bonne année à tous aussi.
Voici un exemple de script que je suis en train de tester pour lancer les compilations automatiques et produire des builds "à la pelle" sous MSYS2:

```
#!/bin/bash

cd /c/Rawtherapee-sources/rtrepo

git checkout master
git pull

cd build64

cmake -G "MSYS Makefiles" -C ../my.win64.cmake -DCMAKE_BUILD_TYPE="release" -DPROC_TARGET_NUMBER="1" -DBUILD_BUNDLE="ON" -DCMAKE_INSTALL_PREFIX="." -DBINDIR="." -DDATADIR="." -DCACHE_NAME_SUFFIX="" ..

read -p "Press [Enter] key to start backup..."

make -j4 install
```

J'ai donc mes sources installées sous `C:\Rawtherapee-sources\rtrepo`, et dans ce répertoire j'y ai créé plusieurs sous-répertoires pour mes différentes builds (`build64` est le répertoire destiné à la branche master compilée en 64 bits, j'ai aussi `build32`, `build32mstack`...). Je crois que le `..` à la fin de la commande `cmake` indique d'aller les chercher les sources dans le répertoire de niveau supérieur.

**Comment by Beep6581** [comment]
It would probably be faster and easier for Jacques to download TeamViewer QuickSupport and have someone connect to him and delete his old toolchain and install the new one for him.
https://www.teamviewer.com/en/download/windows.aspx

**Comment by Hombre57** [comment]
@sguyader @adamreichold (if you're around)

I've statically linked libclearlooks, the linking process went fine, but when starting RT, I get this error (in French) :
`(rawtherapee.exe:5960): Gtk-WARNING **: '/mingw64/lib/gtk-2.0/2.10.0/engines\': Le module spécifié est introuvable.`
which mean `the specified module can't be found`.

I don't know what "module" mean exactly. Everything is in place in mingw64 except that the dll has not been created, only the static lib. I've copied the etc/gtk2.0 and lib/gtk2.0 folders into the base install folder, but it keeps referring to the mingw path.

Do you have an idea of what's going on ? I've build libclearlooks myself through a mingw/64 console.

**Comment by Hombre57** [comment]
NB: I had to copy the `libclearlooks.a` and `libclearlooks.la` into `/mingw64/lib` to make the linking process successful. I've also added `-lclearlooks` on line 237 of the main CMakeLists.txt. (just to be complete)

**Comment by sguyader** [comment]
As I said earlier, Clearlooks doesn't compile currently in mingw64 (no DLL
is produced), although it compiles fine in mingw32. The easiest way I found
for my builds is to simply copy the dll's from the 'old' gtkmm2 64 bits
installer. It works fine like that.

**Comment by Hombre57** [comment]
I know, but I'd like to avoid that. If no-one can find a solution (the lib has been built and linked to RT after all), I'll go your way.

**Comment by adamreichold** [comment]
@Hombre57 I am not sure if it is possible to statically link a theme engine into Gtk+ or directly into an application using it, at least I have never heard of it and find nothing on the web immediately. The problem is probably caused by Gtk+ trying to set the theme at run time by loading the dynamic library even if the theme engine is statically linked. (More specifically, just linking the engine via `-lclearlooks` is not enough, since Gtk+'s theme engine loader has to be told about that and look for the symbols already present in the binary instead of loading a shared library. Also these symbols have to anchored in the binary somehow, just linking a static library which is used nowhere (since themes are not referenced at compile time) should change nothing w.r.t. to the symbols available at run time. I am therefore quite sceptical this works. (I know how this is done for Qt and it is quite complicated there with a lot of limitations.))

@sguyader Can you explain why `clearlooks` does not build on 64-bit Windows? (I did fix the missing prefix in the RawPedia article.)

**Comment by Desmis** [comment]
Je viens juste de terminer le changement de configurations du : 1) au passage de MinGW à MSY2 et 2) au diverses évolutions de RT pendant mon absence durant les fêtes de fin d'année.
Ces 2 points rendant impossible (si ils n'étaient pas résolus !) toute évolution des développements en cours.
J'obtiens maintenant, grâce  à votre aide, un environnement de travail "acceptable"...notamment pour mener à bien plusieurs développements en cours. Je pense d'ailleurs qu'il est possible si personne ne s'y oppose d'en "merge(r)" un  (retinexadd).

Merci encore
Jacques :)

**Comment by Hombre57** [comment]
@adamreichold @sguyader I've built RT again without -lclearlooks. I can run it with the old libclearlooks.dll copied next to rawtherapee.exe, but still the same error :
```
(rawtherapee.exe:2932): Gtk-WARNING **: '/mingw64/lib/gtk-2.0/2.10.0/engines\': Le module spécifié est introuvable.
```
RT doesn't seem to understand where to find the modules...

**Comment by sguyader** [comment]
Maybe you forgot to copy modules/libgail.dll (I'm not at home right now,
i'm not sure about the correct path).
Le 3 janv. 2016 10:07, "Jean-Christophe" <notifications@github.com> a
écrit :

**Comment by Hombre57** [comment]
No, I forgot to say that I've copied the `lib` and `etc` folder with gtk related modules and libs into RT's base install dir (recreating the folder tree).

**Comment by sguyader** [comment]
Finally I was able to compile the Clearlooks engine in MingW64. I actually found a more recent source tarball of [gtk engines 2.21](http://ftp.iitm.ac.in/archlinux/other/gtk-engines/) from Archlinux, and this one does produce the `libclearlooks.dll` file. Anf it works with Rawtherapee.

**Comment by adamreichold** [comment]
@sguyader I tried to update the RawPedia article. Can you confirm the that this aligns with what you discovered? Thanks.

More generally speaking, what is still to be done w.r.t. to this issue after the Clearlooks problem is resolved? Can this be closed?

**Comment by sguyader** [comment]
@adamreichold I think it's all good. If someone else can test on their system and confirm, then we can close this issue.

**Comment by Hombre57** [comment]
Yeah ! It's works nice on Win7/64 ! Merci Sébastien :)

**Comment by Desmis** [comment]
I just tried on Win8 - 64, it works nice.
Merci Sébastien
