### ISSUE TITLE
Create a Windows packaging script

### ISSUE THREAD

**Issue by adamreichold** [Beep6581/RawTherapee#3060]
While building RawTherapee becomes much simpler using MSYS2, it still does not change the amount of work needed to create a redistribution installation bundle. We should create a script (probably shipped within the source code repository) to create such installation bundles by copying exactly the necessary files out of the MSYS2 environment, so that the result will have the smallest possible size.

**Comment by sguyader** [comment]
For gtk3 builds, it looks like the `hicolor` theme is in fact not needed in the RT bundle. I'm now trying to narrow down the list of needed Adwaita icons.

**Comment by Beep6581** [comment]
There is a old InnoSetup script:
https://github.com/Beep6581/RawTherapee/tree/master/rtdata/win

I suggest deleting `rtdata/win/`, creating `tools/innosetup/` and putting an updated `WindowsInnoSetup.iss.in` in there.

**Comment by Beep6581** [comment]
Ah I misunderstood the intention of this issue - it is to write a shell script to copy only the needed files before making an installer using InnoSetup or other.

**Comment by sguyader** [comment]
But speaking of InnoSetup, its script will need to be adapted because there are differences between gtk2 and gtk3 bundles. I have to modify the current script to produce gtk3 bundles.

**Comment by sguyader** [comment]
Here's a listing the files which should to be copied into the **Gtk3** RT bundles, after removing the unneeded files:
```
	\share\glib-2.0\schemas
	\share\glib-2.0\schemas\gschemas.compiled
	
	\share\icons\Adwaita\icon-theme.cache
	\share\icons\Adwaita\index.theme
	\share\icons\Adwaita\16x16\actions\document-save-symbolic.symbolic.png
	\share\icons\Adwaita\16x16\actions\edit-clear-symbolic.symbolic.png
	\share\icons\Adwaita\16x16\actions\edit-undo-symbolic.symbolic.png
	\share\icons\Adwaita\16x16\actions\find-location-symbolic.symbolic.png
	\share\icons\Adwaita\16x16\actions\list-add-symbolic.symbolic.png
	\share\icons\Adwaita\16x16\actions\list-remove-symbolic.symbolic.png
	\share\icons\Adwaita\16x16\actions\media-playback-pause-symbolic.symbolic.png
	\share\icons\Adwaita\16x16\actions\media-record-symbolic.symbolic.png
	\share\icons\Adwaita\16x16\actions\pan-down-symbolic.symbolic.png
	\share\icons\Adwaita\16x16\actions\pan-end-symbolic-rtl.symbolic.png
	\share\icons\Adwaita\16x16\actions\pan-end-symbolic.symbolic.png
	\share\icons\Adwaita\16x16\actions\pan-start-symbolic-rtl.symbolic.png
	\share\icons\Adwaita\16x16\actions\pan-start-symbolic.symbolic.png
	\share\icons\Adwaita\16x16\actions\pan-up-symbolic.symbolic.png
	\share\icons\Adwaita\16x16\actions\view-list-symbolic.symbolic.png
	\share\icons\Adwaita\16x16\actions\window-close-symbolic.symbolic.png
	\share\icons\Adwaita\16x16\actions\window-maximize-symbolic.symbolic.png
	\share\icons\Adwaita\16x16\actions\window-minimize-symbolic.symbolic.png
	\share\icons\Adwaita\16x16\actions\window-restore-symbolic.symbolic.png
	\share\icons\Adwaita\16x16\devices\drive-harddisk-symbolic.symbolic.png
	\share\icons\Adwaita\16x16\places\folder-documents.png
	\share\icons\Adwaita\16x16\places\folder-download.png
	\share\icons\Adwaita\16x16\places\folder-music.png
	\share\icons\Adwaita\16x16\places\folder-pictures.png
	\share\icons\Adwaita\16x16\places\folder-publicshare.png
	\share\icons\Adwaita\16x16\places\folder-remote.png
	\share\icons\Adwaita\16x16\places\folder-templates.png
	\share\icons\Adwaita\16x16\places\folder-videos.png
	\share\icons\Adwaita\16x16\places\folder.png
	\share\icons\Adwaita\16x16\places\network-server.png
	\share\icons\Adwaita\16x16\places\network-workgroup.png
	\share\icons\Adwaita\16x16\places\user-bookmarks.png
	\share\icons\Adwaita\16x16\places\user-desktop.png
	\share\icons\Adwaita\16x16\places\user-home.png
	\share\icons\Adwaita\16x16\places\user-trash.png
	\share\icons\Adwaita\16x16\status\dialog-information-symbolic.symbolic.png
	
	\share\icons\hicolor\icon-theme.cache
	\share\icons\hicolor\index.theme
	\share\icons\hicolor\16x16\apps\gtk3-demo-symbolic.symbolic.png
	\share\icons\hicolor\16x16\apps\gtk3-demo.png
	\share\icons\hicolor\16x16\apps\gtk3-widget-factory-symbolic.symbolic.png
	\share\icons\hicolor\16x16\apps\gtk3-widget-factory.png
	\share\icons\hicolor\16x16\apps\inkscape.png
	\share\icons\hicolor\16x16\mimetypes\djvu.png
```
Although no `hicolor` icon seem to be actually used by RT, the program complains when it is not there.
Some of the Adwaita icons are not needed by RT itself, but are needed by the Gtk inspector, but even with those included, now the icon set is very light (less than 150 kB on the disk).

**Comment by sguyader** [comment]
Because the WindowsInnoSetup.iss file needs currently to be adapted for the build type (Release/Debug) and branch (master/Gtk3) when making Windows packages, I wanted to try to do it automatically from bash script.
Two things must be modified either in the setup file itself or in its configuration file (WindowsInnoSetup.iss.in):

1. To make a package from Gtk3 branch:

line 108 change from `Source: "{#MyBuildBasePath}\lib\*"; DestDir: "{app}\lib\"; Flags: ignoreversion recursesubdirs createallsubdirs` to Source: "{#MyBuildBasePath}\lib\*"; DestDir: "{app}\lib\"; Flags: ignoreversion recursesubdirs createallsubdirs`.

I was able to use `sed -i 's/lib/share/g' ~/rtrepo-gtk3/tools/win/InnoSetup/WindowsInnoSetup.iss.in`
 for this. It's okay because "lib" doesn't occur anywhere else, otherwise I wonder if the backslashes would cause any trouble.

2. To include gdb.exe in a Debug package:

line 120, I would add `Source: "{#MyBuildBasePath}\gdb.exe"; DestDir: "{app}"; Flags: ignoreversion` but in this case my very weak knowledge in scripting made me fail. I tried to follow some examples found on the web, with sed or with gawk, but both failed, probably because the line to be added contains some characters that have a particular signification to the issued command (for example gawk complained about the curly brace and the sharp sign).

@Beep6581, I'm sure you can find an elegant solution.

**Comment by Beep6581** [comment]
I changed the formatting a bit to make it more readable, with each line of code on its own line. I hope you don't mind. But in point 1, the "to" line is the same as the original line. Was the substitution of all occurrences of `lib` to `share` the only change?

**Comment by sguyader** [comment]
@Beep6581 I give you my permanent authorization to make my posts more readable!
I edited the "to" in point 1, it is indeed the only change needed to make Gtk3 packages.
But of course, to make a Gtk3 Debug build, points 1 and 2 need to considered.

**Comment by Beep6581** [comment]
1.
It seems safe to just replace `{app}\lib\` with `{app}\share\`:
`sed -i 's/{app}\\lib\\/{app}\\share\\/' tools/win/InnoSetup/WindowsInnoSetup.iss.in`
But you can make it more safe by only performing the replacement on lines which match
`Source: "{#MyBuildBasePath}\lib\*";`
using:
`sed -i '/Source\: "{#MyBuildBasePath}\\lib\\\*";/s/{app}\\lib\\/{app}\\share\\/' tools/win/InnoSetup/WindowsInnoSetup.iss.in`
It looks like spaghetti but its quite simple:
- It applies the replacement only on lines which match the string I pasted above, and as there is only one line containing that, its safer than just relying on "lib" alone,
- I escaped three characters: : \ *

Note that in your "to" example, you replaced only the second instance of `lib` with `share`, not the first, while your code example uses `/g` which would replace both. Which one was the typo?

2.
Several options here, we could simply append text after line 119:
`sed -i '119 a\Source: "{#MyBuildBasePath}\\gdb.exe"; DestDir: "{app}"; Flags: ignoreversion' tools/win/InnoSetup/WindowsInnoSetup.iss.in`
I escaped the backslash before `gdb.exe`, nothing else.
but that's not safe IMHO, line numbers are not to be relied on. A better solution is that I just added that line in commit 3f85ee00e998cc9f3d53e7f16fcdb94303e62f60 and all you have to do now is to remove the leading `;` to use it, using:
`sed -i '/\\gdb.exe/s/^;//' tools/win/InnoSetup/WindowsInnoSetup.iss.in`
It matches all lines which contain `\gdb.exe`, which currently is only one line, and replaces the semicolon with nothing only if the line begins with a semicolon.

**Comment by gaaned92** [comment]
@sguyader to solve the innosetup issue, i use the skipifsourcedoesnotexist flag for lib share and gdb.exe. 
Then, it remains to write a script that copy these directories and file in install dir based on aboutthisbuid.txt information.(build type and gtkmm version). This script should also copy all dependencies from mingw/bin

**Comment by sguyader** [comment]
@Beep6581 thanks I'll try that for next builds.
@gaaned92 for now, I have separate scripts for each type of build. I'll try to make a unified script some day, maybe.

**Comment by Beep6581** [comment]
@sguyader remember to take into account that my response to point 1 was made to match your example replacement whereas your example sed command would not do the same thing...

If you want to replace only `{app}\lib\` with `{app}\share\`, use:
`sed -i '/Source\: "{#MyBuildBasePath}\\lib\\\*";/s/{app}\\lib\\/{app}\\share\\/' tools/win/InnoSetup/WindowsInnoSetup.iss.in`

But if you want to replace both instances of `lib` with `share`, use:
`sed -i '/Source\: "{#MyBuildBasePath}\\lib\\\*";/s/lib/share/g' tools/win/InnoSetup/WindowsInnoSetup.iss.in`

**Comment by Beep6581** [comment]
By the way, does this issue need to stay open? Is WindowsInnoSetup.iss.in not enough to fulfill the requirement from the original post?

**Comment by adamreichold** [comment]
@Beep6581 When I reported this after the discussions on the RawPedia article for building on Windows, I was not even aware of the InnoSetup manifest. So if this manifest is able to take over after running `make install`, then I agree that this issue can be closed. Even though it would probably be prudent to change the deployment section of the RawPedia on how to use the InnoSetup manifest instead listing files to copy.

**Comment by Beep6581** [comment]
Then we leave it open until a Windows user can complete the documentation and verify that it's all straightforward.

**Comment by sguyader** [comment]
@Beep6581 I'm not in front of my computer right now, but I think there is only one instance of `lib`in the file.
In my opinion you can close the issue.

**Comment by Beep6581** [comment]
@sguyader it has two instances, both on the same line. Please see your post again:
https://github.com/Beep6581/RawTherapee/issues/3060#issuecomment-187799196
I pointed the issue out here, hopefully its more readable: http://paste2.org/wIBXGzZH

**Comment by sguyader** [comment]
Ah yes, two instances of `lib` in one line. And yes both instances need to be changed `share`.

**Comment by Beep6581** [comment]
Ok, then remember to use my second example, not the first one. This one:
`sed -i '/Source\: "{#MyBuildBasePath}\\lib\\\*";/s/lib/share/g' tools/win/InnoSetup/WindowsInnoSetup.iss.in`
