### ISSUE TITLE
Build fails using mingw64 gcc 4.9.2

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#3067]
Building from a fresh clone fails on my system because of:

rtgui\cachemanager.cc:303:9: error: 'unique_ptr' is not a member of 'std'

Ingo

**Comment by adamreichold** [comment]
Sorry about that, it seems to indirectly included with later versions of `libstdc++`. At least this means I had some limited success with disentangling the header interdependencies. :-\

**Comment by heckflosse** [comment]
@adamreichold Thanks for fixing this, but now it fails with this error:
http://pastebin.com/xFuDDPvu

**Comment by adamreichold** [comment]
@heckflosse Which version `glibmm` are you using? (The three argument version of `Glib::build_filename` should be present since version 2.28.)

**Comment by heckflosse** [comment]
@adamreichold 2.4

**Comment by heckflosse** [comment]
@adamreichold Look at the third argument please: cachemanager.cc:260:78: error: no matching function for call to 'build_filename(const Glib::ustring&, const Glib::ustring&, std::string)'
maybe that's the cause for the error?

**Comment by adamreichold** [comment]
@heckflosse Any chance you can update that? After all, `glibmm` 2.4.8 was released on 2005-06-09 and 2.46.3 is current.

**Comment by adamreichold** [comment]
I do not think the third arguments type is the problem as
* There is no three argument version in the candidate list,
* `std::string` should be implicitly convertible to `Glib::ustring` and
* I should see that error here as well.

But you should be able to test that hypothesis by explicitly casting `*iterator` to `Glib::ustring`. (Sorry, that I can't test this as it does build here.)

**Comment by heckflosse** [comment]
@adamreichold I'll wait for your answer to my last comment before I'll have a look whether I can update ;-)

**Comment by heckflosse** [comment]
I'll test that now

**Comment by adamreichold** [comment]
(Maybe not my place to do so, but I would suggest updating in any case. A ten year old library probably has its share of known bugs and security issues.)

**Comment by heckflosse** [comment]
@adamreichold I'll try to update later. Currently I'm working on four different speedups and don't want to change my system until they are completed. I'll let the Issue open until I updated.

Ingo
