### ISSUE TITLE
Improving the Gtk3 GUI cosmetics

### ISSUE THREAD

**Issue by sguyader** [Beep6581/RawTherapee#3069]
I don't know if I'm expressing myself correctly, but in the Gtk3 build (from today's merge), the label text of the the ouutput profile drop down menu flows out to the right and becomes mixed with the navigate to previous/next image and Synchronize file browser icons:
![Imgur](http://i.imgur.com/PeZsaYF.jpg)

Maybe should I open a separate issue (then let me know), but I also think some extra space between the progress bar, the Preferences button and the Fullscreen button would improve the look:
![Imgur](http://i.imgur.com/4HnMjlg.jpg)

**Comment by Beep6581** [comment]
This will change in the near future when the new additions are moved into a new tab, issue #3054.
Closing.
