### ISSUE TITLE
Problem with constantly refreshing preview occuring randomly [Gtk3]

### ISSUE THREAD

**Issue by sguyader** [Beep6581/RawTherapee#3071]
When I run the latest Gtk3 build and open an image, if the window is large (big screen) everything is okay, but if I reduce the window size (for example to fit a smaller laptop screen panel), then sometimes the preview strats to get updated constantly, though it is quite random (sometimes it refreshes the preview once, sometimes a couple times before settling down, sometimes it's constant until I do something like activating/disactivating a filter). If I increase the Window size, the the constant refreshing stops.
During such a refreshing loop, all the 4 threads are used almost at 100%, even if I switch to the File browser, meaning that the preview refreshing is still occuring in the background.
Also, notice that at smaller window size, the image preview is not centered, it's just as if there's a non-shrinkable space at the left of the preview.
I made 2 screencasts to show you the problem (better than with my words, and you'll see the messages in the console):
[screencast 1, small screen panel](https://drive.google.com/file/d/0B_AvPFlUj8t5SGdMWE43SEUwbW8/view?usp=sharing)
[screencast 2, large screen panel](https://drive.google.com/file/d/0B_AvPFlUj8t5V2YtMmt4NEJRd0k/view?usp=sharing)

I don't get such a problem with the latest builds from master branch.

**Comment by Beep6581** [comment]
Looks like issue #2531 but for the preview area.

**Comment by sguyader** [comment]
I don't know if it the same, unless I don't understand the problem in issue #2531.

1. I don't see any scrollbar appearing in the preview are, which is not unexpected, I think, because for example in the first screencast you can see that the preview is zoomed out and is smaller than the preview area (I would expect scrollbars to appear only when the zoom level makes the preview image larger than the preview area).

2. It looks like it's not just the preview area that is concerned, because even the toolbar on top right of the filmstrip is affected (see the Hand and Crop selection tools icons jumping around)

3. There still is this odd behaviour of the preview image not centered at smaller window size.

**Comment by Beep6581** [comment]
My guess is that the progress bar's changing width causes that.

**Comment by TooWaBoo** [comment]
I realized this issue too, but only when the history panel is open.

**Comment by Hombre57** [comment]
> My guess is that the progress bar's changing width causes that.

I second that : if the progressbar change it's size due to a change of the text in a situation where the bottom toolbar run out of space yield this problem.

I'm working on a patch that stabilize the progressbar size and that will be included in the patch that rework the bottom toolbar appearance.

**Comment by Hombre57** [comment]
See issue #3081 and PR #3080. It should fix this issue.

**Comment by Hombre57** [comment]
Do you confirm the "constantly refreshing preview" is fixed ? If yes, please close this issue.

**Comment by Hombre57** [comment]
No answer. With the comment provided in the PR, I'll assume that it has been fixed. Closing.
