### ISSUE TITLE
Build failure on ARCH (gcc  5.3.0) and openSUSE Thumbleweed (gcc 5.2.1)

### ISSUE THREAD

**Issue by mbajor** [Beep6581/RawTherapee#3074]
Error code
```
[  627s] /home/abuild/rpmbuild/BUILD/rawtherapee-4.2.594/rtgui/batchqueue.cc: In member function 'bool BatchQueue::saveBatchQueue()':
[  627s] /home/abuild/rpmbuild/BUILD/rawtherapee-4.2.594/rtgui/batchqueue.cc:227:25: error: variable 'std::ofstream file' has initializer but incomplete type
[  627s]      std::ofstream file (fileName, std::ios::trunc);
[  627s]                          ^
[  627s] /home/abuild/rpmbuild/BUILD/rawtherapee-4.2.594/rtgui/batchqueue.cc: In member function 'bool BatchQueue::loadBatchQueue()':
[  627s] /home/abuild/rpmbuild/BUILD/rawtherapee-4.2.594/rtgui/batchqueue.cc:267:33: error: variable 'std::ifstream file' has initializer but incomplete type
[  627s]      std::ifstream file (fileName);
```
And [full log](https://build.opensuse.org/build/home:rawtherapee/openSUSE_Tumbleweed/x86_64/rawtherapee/_log)

Edit: Not only Arch and openSUSE failed, but all.

**Comment by adamreichold** [comment]
I am sorry about this error which I don't see on my Arch box also running GCC 5.3. The process of disentangling the header interdependencies to speed up build times often means that shadowed and indirectly included headers get removed it seems to depend on various libraries versions which headers the depend on themselves. Again, I am sorry to have broken the build.
