### ISSUE TITLE
Speedup for dcraw decoders

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#3078]
Last days I tried to speed up the dcraw decoders a bit. There are fast ones (like sony arw2 decoder) where no speedup is needed, normal ones (like Nikon NEF decoder) and really slow ones (like decoder for CR2 files of newer Canon cams).

I got a good speedup for the really slow decoder (decoding time reduced by 33 %), a medium speedup for Nikon (decoding time reduced by 21%) and a small speedup for other files (Pentax PEF 12%, older Canon models 8%) and no speedup for Sony arw2 files.

The critical part of my changes are the changes to dcraw.cc. Each change to dcraw.cc possibly means a bit more work when a new dcraw version is released (which is not so often). But I think we should not stay with current dcraw speed only because it's easier update to a new dcraw version. 
I also would like to astyle the dcraw.cc code...

What do other devs think about that?

Ingo

**Comment by heckflosse** [comment]
I want to add some numbers:

Master branch at my system:

Sony arw2: 142 Mpix/second decoding time
Nikon NEF: 47 Mpix/second decoding time
Pentax PEF: 47 Mpix/second decoding time
newer Canon CR2 files: 28 Mpix/second decoding time

optimized code:

Sony arw2: 142 Mpix/second decoding time
Nikon NEF: 60 Mpix/second decoding time
Pentax PEF: 53 Mpix/second decoding time
newer Canon CR2 files: 43 Mpix/second decoding time

**Comment by adamreichold** [comment]
Wouldn't it be possible to upstream the speed improvements into dcraw itself? We do not have to effectively fork it and even more people would benefit from this. If we are going to look into more substantial modifications to the dcraw code base, why not align with one of the library projects that try to fix this, e.g. [LibRaw](http://www.libraw.org/) or indirectly via [libkdcraw](https://projects.kde.org/projects/kde/kdegraphics/libs/libkdcraw)?

(I think `astyle` is not too useful for code we do not maintain. It code be done automatically after patching, but it sounds like it only adds complications for little benefit.)

**Comment by heckflosse** [comment]
@adamreichold I would prefer that too, but I heard that Dave is a bit stubborn. I also I don't want to astyle dcraw.c, but dcraw.cc, which is the file generated by dcraw.patch from dcraw.c and which is used in rt. Yes, libraw and rawspeed are also options, but I don't know whether it's easier to stay with patched dcraw or to switch to libraw/rawspeed in our current code base. 

Ingo

**Comment by heckflosse** [comment]
@adamreichold I want to explain how updating dcraw in RT currently works, so you get a better understanding of the procedure:
When Dave releases a new dcraw version, I diff it to the old one and check (and partly apply) the changes he made to dcraw.c code to our dcraw.cc code. Then I make a new dcraw.patch file which is able to generate the dcraw.cc from the dcraw.c code. Because applying the changes to dcraw.cc is done manually IMHO it's no problem if dcraw.cc is formated by astyle (original dcraw.c code is almost unreadable so is current dcraw.cc code currently)

The 'partly apply' above is because sometimes Dave includes changes Anders made for new cams in dcraw.cc into his dcraw.c code.

Ingo

**Comment by adamreichold** [comment]
@heckflosse I understand that astyle would be applied after patching, what I mean with complications is that it will become harder to look at some code in `dcraw.cc` and relate that to its origins in `dcraw.c` which will be necessary as long as we semi-automatically patch `dcraw.c` into `dcraw.cc`.

The only other option I see (next to the status quo together with upstreaming the speed improvements or reusing one of the library projects based on dcraw), would be to discard the idea that we will merge changes from dcraw in a tool-based way and fully import the dcraw code and only integrate changes manually from that time on. We could then restyle, refactor and integrate the functionality into the RT code base as we see fit. Of course, the question stays how large the change sets of dcraw typically are and if it is more expensive to continuously adjust the patch file or to review the dcraw diff and manually integrate the changes into refactored RT code paths.

**Comment by adamreichold** [comment]
@heckflosse What is not fully clear to me in the current description: Why keep that patch file in the process if you apply the changes manually to `dcraw.cc` anyway? Why not just stop after applying the latest upstream changes by hand?

**Comment by heckflosse** [comment]
@adamreichold : First I answer to your last comment: dcraw updates are rare (one per year) and in between there are changes like this one https://github.com/Beep6581/RawTherapee/commit/bc80ef946b5ba55ada5536b149e0aea6ecba2064 which need to be reflected by a dcraw.patch file for dcraw updates in case Dave doesn't include them into his code.

**Comment by adamreichold** [comment]
@heckflosse Sorry, but I still don't get it: If just never had a `dcraw.c` and `dcraw.patch` in the repository, that commit would just touch `dcraw.cc` and be much smaller for it. For what do we actually use the `dcraw.patch` file if we only manually touch `dcraw.cc` and create the patch from diffing `dcraw.c` against `dcraw.cc` after that? The reason to have the patch would be to create `dcraw.cc` from `dcraw.c` AFAIU but that is exactly what we are not doing? Why do we need to reflect changes in the patch file if we never apply it to anything?

**Comment by heckflosse** [comment]
Adam, in fact I missed a part in my explanation. Maybe it gets more clear by looking at rtengine/dcraw.patch.README. 

Ingo

**Comment by heckflosse** [comment]
If our dcraw.patch file applies to new dcraw.c there's nothing to do. Only in case that it doesn't apply we have to manually solve the rejections.

**Comment by adamreichold** [comment]
@heckflosse The README sounds very different from your explanation: In README I use the old patch against the updated `dcraw.c` to semi-automatically import it into RT, only resolving the rejects and hoping that the diff algorithm will take care of trivial things like plain insertions. If I understood your explanation correctly, you started with diffing the old against the new `dcraw.c` to manually apply these changes manually to `dcraw.cc`. If we can always do that because the upstream changes are small, then there would be no need to keep the patch around.

So how often does just apply the patch to an updated upstream work? How complicated is it to resolve the rejects in the patch instead of applying the change set manually?

**Comment by heckflosse** [comment]
@adamreichold  Difference between theory and practice. Readme tells you about the ideal solution. But practice is almost ever to apply the changes manually by looking at the diff. You're right that in this case the dcraw.patch file makes less sense.

**Comment by heckflosse** [comment]
And, applying the changes manually is often easier than resolving the rejects because it happens that Dave makes changes for the changes we made to dcraw code (e.g. Anders makes changes for some cames and Dave includes this changes but modifies them before inclusion)

**Comment by adamreichold** [comment]
If that is the case, my vote is for either going with one of the libraries or detaching from upstream dcraw, refactoring the code as we see fit and always manually importing updates to the dcraw code base.

**Comment by heckflosse** [comment]
@adamreichold : I agree with you! Currently refactoring the code and manually importing updates to the dcraw codebase seems easier for me than to go the libraw way. But maybe you can try to update to current https://www.cybercom.net/~dcoffin/dcraw/dcraw.c, which is not yet included into RT. Maybe you find a better solution. In past (last two years) I was the only one who made the updates, so maybe I'm a bit blind (I really would appreciate if you could also take a look at the procedure and share your thoughts!!!).

Ingo

**Comment by heckflosse** [comment]
I just pushed a new branch 'dcraw_decode_speedup'
I tested using 6 files (Olympus E-M5, Pentax K10D, Canon Powershot G5 X, Nikon D800, Canon EOS 300D, Canon EOS 5DS). I always measured the decoding time 7 times and took the median.

Before patch:
Olympus E-M5: 508 ms
Pentax K10D: 215 ms
Canon Powershot G5 X: 512 ms
Nikon D800: 748 ms
Canon EOS 300D: 187 ms
Canon EOS 5DS: 1767 ms

I made several commits.

First one was inlining getbithuff_t::operator():

Olympus E-M5: 492 ms
Pentax K10D: 221 ms
Canon Powershot G5 X: 517 ms
Nikon D800: 712 ms
Canon EOS 300D: 178 ms
Canon EOS 5DS: 1811 ms

As you can see there's a speedup for some files but also a slowdown for other ones.

I inlined ljpeg_diff in the second commit:

Pentax K10D: 200 ms
Canon Powershot G5 X: 480 ms
Canon EOS 5DS: 1753 ms

The next commit was for Nikon only. Original dcraw code clamped the raw values by checking them against >=0 and <0x3fff. Checking against >= 0 is nonsense for unsigned values and checking against <0x3fff can be done by a fast bitwise and operation. That's what I did:

Nikon D800: 688 ms

with the next commit I made two functions from one (operator) because the original one had a lot of stuff inside which was not needed for all files. I also added some compiler hints. This commit only affected Olympus and Nikon files:

Olympus E-M5: 468 ms
Nikon D800: 611 ms

with the next commit I used the faster function also for Pentax and Sony arw files:

Pentax K10D: 195 ms

The last commits includes some more compiler hints and an optimized version of lossless_jpeg_load_raw()
This is mainly for the Canon EOS 5DS file

Canon EOS 5DS: 1186 ms

So now we have:

Olympus E-M5: 508 ms => 463 ms
Pentax K10D: 215 ms => 195 ms
Canon Powershot G5 X: 512 ms => 480 ms
Nikon D800: 748 ms => 602 ms
Canon EOS 300D: 187 ms => 178 ms
Canon EOS 5DS: 1767 ms => 1186 ms

**Comment by Beep6581** [comment]
Quick test using a PEF and CR2, I measured the total processing time so it's hard to see the difference for PEF, but for CR2 the total processing time went down by half a second from 6.7s to 6.2s. The outputs before/after the patch are identical.

**Comment by adamreichold** [comment]
@heckflosse Since you pushed a patch, does that we will go with detaching from upstream dcraw? Shouldn't we wait for more developer opinions on this? In any case, a pull request would probably be helpful for code review.

**Comment by heckflosse** [comment]
@adamreichold I pushed to a new branch, not to master. My intention was to show what's possible and then wait for opinions of other developers. Of course I could also make a PR from my fork but what difference does that make for code review?

**Comment by iliasg** [comment]
Ingo, is huffman paralelization in your intention ? https://code.google.com/p/rawtherapee/issues/detail?id=1964#c16

Some Canon (5ds) cr2s are organized in slices .. this could help paralelization no ?

**Comment by heckflosse** [comment]
Ilias, yes, https://code.google.com/p/rawtherapee/issues/detail?id=1964#c16 is still on my screen :)
But it requires some work on rtengine/myfile.* first. Currently I'm looking at rawspeed code to see how well it is optimized. Maybe we can use it in rt... But I suspect switching from our dcraw patch method to rawspeed/libraw is a lot of work as currently our engine has a lot of dependencies to dcraw code.

For the Canon (5ds) cr2s it should be possible to vectorize some parts of the code (or write code which gets vectorized by compiler for this parts)

**Comment by adamreichold** [comment]
@heckflosse I was just thinking about using GitHub's inline commit comments to discuss this. But if you don't intend to merge until a consensus is found, it can probably also wait until then.

**Comment by heckflosse** [comment]
@adamreichold I made a PR for the branch. That doesn't mean that I want to merge it, but to discus it.

**Comment by Hombre57** [comment]
Just for reference, I won't discuss the technical aspect of the speedup, I'll trust @heckflosse and @adamreichold for that.

I don't mind detaching from official dcraw, we have comparing tools to find out the changes to integrate in our version anyway, so if you think it's easier to detach then I'm fine too.

**Comment by gaaned92** [comment]
@heckflosse one other consideration to migrate to libraw/rawspeed is to be able to build the last version (now 0.18) and not wait to others to make it. I tried in W32 with no success. Did you succeded and if yes, can you share the process.
André

**Comment by mightymax** [comment]
@heckflosse we rely heavily on the speed of RawTherapee's raw conversion, especially for Canon CR2 files. I am not a developer who can help you on this, but maybe my company can contribute by sponsoring payed hours for development?

**Comment by heckflosse** [comment]
I created a [branch](https://github.com/Beep6581/RawTherapee/tree/cr2_decode_speedup) with optimizations for decode of cr2 files.

**Comment by heckflosse** [comment]
Closed because of da9e760
