### ISSUE TITLE
GTK3 version compiling problem on Ubuntu 15.10

### ISSUE THREAD

**Issue by dnw3039** [Beep6581/RawTherapee#3079]
I have no problem compiling the master or newretinex branches.
I get the following error messages when I attempt to compile the GTK3 branch:

                                                                                          
/sdb2/home/dnw/repo-rt/rtengine/../rtgui/guiutils.h:38:114: error: ‘Align’ in namespace ‘Gtk’ does not name a type
 perties(Gtk::Widget *widget, bool hExpand, bool vExpand, enum Gtk::Align hAlign, enum Gtk::Align vAlig
                                                                                            ^
/sdb2/home/dnw/repo-rt/rtengine/../rtgui/guiutils.h:423:10: error: ‘Grid’ in namespace ‘Gtk’ does not name a type
     Gtk::Grid *box;
          ^
rtengine/CMakeFiles/rtengine.dir/build.make:54: recipe for target 'rtengine/CMakeFiles/rtengine.dir/safegtk.cc.o' failed
make[2]: *** [rtengine/CMakeFiles/rtengine.dir/safegtk.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
rtengine/CMakeFiles/rtengine.dir/build.make:146: recipe for target 'rtengine/CMakeFiles/rtengine.dir/diagonalcurves.cc.o' failed
make[2]: *** [rtengine/CMakeFiles/rtengine.dir/diagonalcurves.cc.o] Error 1
rtengine/CMakeFiles/rtengine.dir/build.make:123: recipe for target 'rtengine/CMakeFiles/rtengine.dir/flatcurves.cc.o' failed
make[2]: *** [rtengine/CMakeFiles/rtengine.dir/flatcurves.cc.o] Error 1
rtengine/CMakeFiles/rtengine.dir/build.make:100: recipe for target 'rtengine/CMakeFiles/rtengine.dir/curves.cc.o' failed
make[2]: *** [rtengine/CMakeFiles/rtengine.dir/curves.cc.o] Error 1
CMakeFiles/Makefile2:161: recipe for target 'rtengine/CMakeFiles/rtengine.dir/all' failed
make[1]: *** [rtengine/CMakeFiles/rtengine.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2

The full console output from the compile job  is in the attached file:
[log.txt](https://github.com/Beep6581/RawTherapee/files/83845/log.txt)

**Comment by adamreichold** [comment]
I get similar errors if I switch between Gtk+ 2 and 3 based branches without removing all build artefacts, could that be your problem as well? Could you try making a clean build of the `gtk3` branch? I'd recommend separate out of tree builds for Gtk+ 2 and 3 based builds.

**Comment by dnw3039** [comment]
Thanks I will try that

**Comment by Beep6581** [comment]
Yes, you must delete the build folder, and perhaps also run `make clean` and then `./clean` (Linux/OS X) or `clean.bat` (Windows).

**Comment by dnw3039** [comment]
Thanks,

Thanks it now compiles. The result is very elegant, thanks for the working you have put into this.
