### ISSUE TITLE
Reworked Editor's bottom toolbar

### ISSUE THREAD

**Issue by Hombre57** [Beep6581/RawTherapee#3081]
PR #3080 does fix the bottom toolbar of the Editor panel (Gtk3).

I had to use the preferred function to fix the progress bar's width (it is constant now and should avoid the refresh loop), and tried to do the same for the profile MyCombobox[-Text] instead of using set_size_request, hoping that it will clip the text to the widget's size, but it does not. The 2 methods does not seem to interact correctly (using preferred width instead of set_size_request did fixed the progressbar size bug).

The changes to MyCombobox is then useless, but should I really remove it and go back to set_size_request (I wouldn't do that). FYI, Gtk::Widget has no set_preferred_width function, that's why I had to create a subclass of Gtk::ProgressBar.

**Comment by Beep6581** [comment]
The solution works well. I found only one issue, but I'm not even sure it's worth reporting, worth spending time one. I'll describe it regardless: when the left panel is hidden everything works correctly, when you make the RT window very small and press "f" the preview gets shrunk and centered.
![scrot_2016-01-10 024726](https://cloud.githubusercontent.com/assets/5844619/12219452/6b915516-b744-11e5-9099-b3af5d06a9bc.png)

If I show the left panel and press "f", the preview does not shrink down enough width-wise and does not get centered:
![scrot_2016-01-10 024814](https://cloud.githubusercontent.com/assets/5844619/12219459/a965ecf8-b744-11e5-97a0-dd673db87636.png)
![scrot_2016-01-10 024919](https://cloud.githubusercontent.com/assets/5844619/12219462/c3f605ee-b744-11e5-9b47-6b789b5c6577.png)

or of I hide the right panel and press "f":
![scrot_2016-01-10 025030](https://cloud.githubusercontent.com/assets/5844619/12219464/d19b7076-b744-11e5-8358-252b323fb022.png)

**Comment by adamreichold** [comment]
> The changes to MyCombobox is then useless, but should I really remove it and go back to set_size_request (I wouldn't do that). FYI, Gtk::Widget has no set_preferred_width function, that's why I had to create a subclass of Gtk::ProgressBar.

If we do not intend to use it, I would strongly suggest removing it. The smaller a code base and its individual modules the better. (Also compile times and run time performance will benefit from discipline in that regard.)

**Comment by sguyader** [comment]
I confirm the fix is working. I also observe the same behaviour as @Beep6581, i.e. the preview not centered when shrinked (I mentioned this already in the second part of report in issue #3071).
Is it possible to commit this fix quickly?

**Comment by Hombre57** [comment]
PR #3080 committed and merged to branch gtk3. I'd suggest to close this issue and open a new one for the centering problem.

**Comment by Beep6581** [comment]
Thank you @Hombre57!
