### ISSUE TITLE
Crash when showing File Browser tab

### ISSUE THREAD

**Issue by NextTherapist** [Beep6581/RawTherapee#3084]
This is what I initially meant in https://github.com/Beep6581/RawTherapee/issues/3064

When having this pp3 file

[9783928_w720h480q75v60346_hex_si_dart2.jpg.out.pp3.txt](https://github.com/Beep6581/RawTherapee/files/86131/9783928_w720h480q75v60346_hex_si_dart2.jpg.out.pp3.txt)

 in the folder or applying it to a specific jpg file, I get this crash:

[new-crash2.txt](https://github.com/Beep6581/RawTherapee/files/86128/new-crash2.txt)
[new-crash.txt](https://github.com/Beep6581/RawTherapee/files/86129/new-crash.txt)

This one has no Retinex enabled...

**Comment by Beep6581** [comment]
Cannot reproduce here when applying that PP3 to PEF, PNG and JPG files and viewing them in the File Browser and Editor.

What is the "previews tab"?
Did it really crash? "Program received signal SIGINT, Interrupt." That means it was stopped manually, so did it crash or did it freeze? If it froze, how long did you wait before pressing ctrl+c?

**Comment by NextTherapist** [comment]
It happens with this image:

![9783928_w720h480q75v60346_hex_si_dart2](https://cloud.githubusercontent.com/assets/16581692/12242075/2a5c0dee-b897-11e5-8e23-83ea812cdd46.jpg)

It froze... when running in gdb, all my crashes froze.

**Comment by adamreichold** [comment]
@Beep6581 The current implementation of `threadutils` will send SIGINT in release builds upon failure to conform to strict locking. Maybe this is the reason? Reproducing this with a debug build would certainly help.

**Comment by NextTherapist** [comment]
It is happening again at the moment. How long shall I wait before ctrl+c?

**Comment by NextTherapist** [comment]
I wanted to say "File Browser tab".
This time I waited, and closed an image, and switched to another folder in the File Browser:

[new-crash3.txt](https://github.com/Beep6581/RawTherapee/files/86169/new-crash3.txt)

**Comment by NextTherapist** [comment]
Was it replicable on your system?
Please let me know when you need the image file again.

**Comment by NextTherapist** [comment]
My system ist Windows 7 64bit and it happened with the newest version of the stable branch: 
RT 4.2.539 for Windows Vista/7/8/10 64-bit (Branch: master), 2015-12-26 04:34 (with crashes)
and with 
debug version RT 4.2.642 for Windows Vista/7/8/10 64-bit (Branch: gtk3), 2016-01-08 09:29 (with error lines)

**Comment by NextTherapist** [comment]
Still happens with RT 4.2.797 and this image file: 
[https://cloud.githubusercontent.com/assets/16581692/12242075/2a5c0dee-b897-11e5-8e23-83ea812cdd46.jpg](url)

**Comment by heckflosse** [comment]
@NextTherapist I get a 404 for your link

**Comment by NextTherapist** [comment]
@heckflosse 
Why does gitup set a (url) behind the link? Sorry, should work now:
[https://cloud.githubusercontent.com/assets/16581692/12242075/2a5c0dee-b897-11e5-8e23-83ea812cdd46.jpg]

**Comment by NextTherapist** [comment]
Thank you! :-)

**Comment by heckflosse** [comment]
Can not reproduce in current master build. Didn't try with 4.2.797

**Comment by NextTherapist** [comment]
Did you apply the pp3 file from the first post? It happens after some restarts, when scrolling along the thumbnails in the filemanager tab. Difficult to reproduce, but it _always _happens at some unpredictable point of time with this image and pp3 and _never _without...

**Comment by heckflosse** [comment]
Ok, I'll try again

**Comment by heckflosse** [comment]
@NextTherapist Crash confirmed. Looking...

**Comment by heckflosse** [comment]
@NextTherapist The crash is caused by CIECAM02 being enabled. If you set Enabled=false in [Color appearance] section of the pp3 file it opens fine but as soon as ciecam02 is enabled in preview it crashes. Still searching for the culprit....

**Comment by NextTherapist** [comment]
@heckflosse I am really glad to read that. I thought I was somehow dumb :-D

**Comment by heckflosse** [comment]
@NextTherapist Thanks for reporting this bug and being so persistent to get it fixed :+1:

**Comment by NextTherapist** [comment]
@heckflosse Thank you _very _much!!

> when using ciecam02 on files without exif data

You must get that idea!

From which version on will I get this fix in master branch?

**Comment by heckflosse** [comment]
@NextTherapist The fix is already in master branch. I don't know the version of the next 'official' windows build because I don't make them.

**Comment by Beep6581** [comment]
@NextTherapist the fix is present in branch `master` from version 4.2-836, or from `gtk3` about 4.2-977 (I haven't merged `master` into `gtk3` yet, will probably do that later today).

**Comment by NextTherapist** [comment]
@Beep6581 Thank you!
