### ISSUE TITLE
Display Problems with several GTK-Themes

### ISSUE THREAD

**Issue by naanoo** [Beep6581/RawTherapee#3100]
You seem to try to override the system's gtk theme. But not all the properties are set.

That causes some problems with several themes.

See:
https://github.com/horst3180/arc-theme/issues/376

Warm regards,

Sebastian

**Comment by horst3180** [comment]
More specifically the inbuilt themes need to set `GtkTreeView::even_row_color` and `GtkTreeView::odd_row_color` similar to [this](https://github.com/horst3180/arc-theme/blob/4d092abce315926a33442d20f27e0f82f4939ae3/common/gtk-2.0/main.rc#L63).

**Comment by Beep6581** [comment]
Can you reproduce it on a recent version? Which version? (number + hash) Which version of Gtk3 does it use?

**Comment by naanoo** [comment]
I use the RAWtherapee and GTK versions supplied by Ubuntu 15.10 by default.

*RAWTherapee:*
Version: 4.2.0
Changeset: c81d9026d25c

*GTK:*
Version: 3.14.5-1+deb8u1 0

**Comment by Beep6581** [comment]
That's very old and unsupported. Probably already fixed. Closing. Please only open bug reports if you have reproduced the problem with the latest code.
http://rawtherapee.com/downloads
http://rawpedia.rawtherapee.com/Linux

**Comment by horst3180** [comment]
No, it's not fixed.
I can reproduce this with the latest version from `master` (https://github.com/Beep6581/RawTherapee/commit/5ff270bf51d16a13147f1849fff0936ce528530f). I think only the GTK2 version is affected by this bug.
I managed to fix it by patching the inbuilt themes like I described above. I can send you a pull request.

**Comment by Beep6581** [comment]
Please send a PR if it fixes master.

**Comment by Beep6581** [comment]
Fixed by @horst3180 
https://github.com/Beep6581/RawTherapee/commit/94725dedae4c210f5d15eda980f4e01a9eeb817a
