### ISSUE TITLE
Gtk3 GUI touchup

### ISSUE THREAD

**Issue by Hombre57** [Beep6581/RawTherapee#3103]
This issue will handle talks around the Gtk3 GUI. I've added a gtk3-gui-touchup-and-bugfix branch with some enhancement (from my pov) and bugfix. See commit https://github.com/Beep6581/RawTherapee/commit/93d01f3a82ce6ba1ef5388b94ae7f0a2cf3b6bae for details

I'd also like to restore the default Adwaita NoteBook style if you don't mind.

**Comment by Hombre57** [comment]
Reminder : making the 1:1 icon less transparent.

**Comment by Beep6581** [comment]
Good changes @Hombre57

I only have one request:
![scrot_2016-01-17 172413](https://cloud.githubusercontent.com/assets/5844619/12378483/59f70cc8-bd3f-11e5-8171-f47a7a9816b1.png)
![scrot_2016-01-17 172427](https://cloud.githubusercontent.com/assets/5844619/12378484/59f9378c-bd3f-11e5-867e-8cdfbb9448be.png)
The histogram lines (obviously broken before) are now hard to see in the fixed version, could you make them lighter?

**Comment by Hombre57** [comment]
> The histogram lines (obviously broken before) are now hard to see in the fixed version, could you make them lighter?

Done.

> Reminder : making the 1:1 icon less transparent.

Done

**Comment by Beep6581** [comment]
Thanks!

**Comment by iliasg** [comment]
In edit-tool panel, a dashed horizontal line is visible between the rolled and stable areas.
![rt-gtk3-tool_panel](https://cloud.githubusercontent.com/assets/15012599/12396111/5da4a25c-be0e-11e5-8ab8-aa032dd8adaf.png)

The bottom line is almost always visible. The top one is invisible at first opening the edit mode but becomes visible after a few rolls up-down.
Edit .. looks like a dashed line becomes visible in various instaces. I just saw a vertical left one at 
![rt-gtk3-aboutl_panel](https://cloud.githubusercontent.com/assets/15012599/12396304/6249b454-be0f-11e5-9f6a-4131afcc2846.png)
 

Win Vista_32bit 
Branch: gtk3
Version: 4.2.672
Changeset: aa212e58422d4a66e05bcfd20545e317f9a35912
Compiler: gcc 5.3.0
Processor: undefined
System: Windows
Bit depth: 32 bits
Gtkmm: V3.18.0
Build type: release
Build flags:  -m32  -mthreads -mstackrealign -std=gnu++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -mwindows -DNDEBUG -msse2 -mfpmath=sse -O3
Link flags: -m32 -mthreads  -static-libgcc -Wl,--large-address-aware,--verbose  -march=native -mwindows -s -O3
OpenMP support: ON
MMAP support: ON

**Comment by iliasg** [comment]
Request ..
Please make a slim version. The current theme eats too much vertical space, the circular sliders are huge in height (I think an oval or rectangular shape with less height will be much better)

**Comment by Beep6581** [comment]
The dashed line means there is stuff hidden there. It's a feature of Gtk3, it's useful, please leave it.

This **is** the slim version. Padding is at a minimal. The only thing left to slim-down is making the slider knobs smaller. I had no luck doing that.

**Comment by Hombre57** [comment]
@Beep6581 Shall I try ? How small should it be ?

**Comment by iliasg** [comment]
I am fine with the dashed lines when if they are an indication of hidden stuff. 
But in my installation they work inconsistently .. I mean that they do not appear just after I scroll a bit away from top or bottom nor they disappear just after I am at the top/bottom .. there is a delay i.e. it appears after I somehow trigger a refresh of my display (change the RT window say minimization then restore).

**Comment by Beep6581** [comment]
@Hombre57 try as small as makes sense before the 'reset' icon make the difference insignificant.

**Comment by Hombre57** [comment]
@iliasg Not sure that RT is the culprit here.

To reduce the size of the slider's knob, add this on line 43 of RawTherapee.css :
```
GtkScale {
	-GtkScale-slider-length: 16;
	-GtkRange-slider-width: 16;
	-GtkRange-trough-border: 4;
}
```

But you'll notice that it has no effect at ll on the size of the slider, so is it really worth it to reduce the knob's size ?

Hint if you want to experiment : if you want to increase the size of the knob by 2 px, you'll have to increase `-GtkScale-slider-length`and `-GtkRange-slider-width` by 2 and decrease `-GtkRange-trough-border` by 1 to keep the through line identical. Don't ask me why :unamused:

**Comment by Beep6581** [comment]
Ah maybe that was the problem. Answer to your question - no point then.

**Comment by iliasg** [comment]
@Hombre57 Thanks, I cannot built RT in the new environment yet to try the modifications
Strange that the current GTK3 gui is the slimmest possible !! Fact is that the GTK2 slim is around 20% slimmer.

**Comment by gaaned92** [comment]
@iliasg  you can find a 32bit build of Gui touchup branch in https://drive.google.com/open?id=0B2q9OrgyDEfPOEZmVlBzLWlnSWc

**Comment by Beep6581** [comment]
@iliasg no, the Gtk+ 2 theme's slimness depends on the gtkrc file, the hard-coded C++ padding and spacing, and the gtk2-engine, which in gtk2 is user-selectable. It could take twice as much space as the Gtk3 version if you used an eye-candy engine. In Gtk3 there is one hard-coded engine. You can adjust most things with CSS, some you can't.

**Comment by iliasg** [comment]
@gaaned92 @Hombre57 
the last build works almost fine except that it crashes when click on tick boxes (enable/disable the dcb enhancement, enable/disable autoCA, sharp mask in shadows/highlights etc)
Win_vista_32bit
Branch: gtk3-gui-touchup-and-bugfix
Version: 4.2.675
Changeset: 3b7ef934ce5f6ac725ee2d8e1258238f211115cc
Compiler: gcc 5.3.0
Processor: undefined
System: Windows
Bit depth: 32 bits
Gtkmm: V3.18.0
Build type: release
Build flags:  -m32  -mthreads  -std=gnu++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -mwindows -DNDEBUG -msse2 -mfpmath=sse -O3
Link flags: -m32 -mthreads  -static-libgcc -Wl,--large-address-aware,--verbose  -march=native -mwindows -s -O3
OpenMP support: ON
MMAP support: ON

**Comment by Beep6581** [comment]
Following discussions at https://discuss.pixls.us/t/new-windows-builds/615/19 I understand that debug builds should now include gdb.exe, so could you get a stack backtrace? Instructions here http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports

**Comment by gaaned92** [comment]
@iliasg  debug build available at same place

**Comment by iliasg** [comment]
Debug build does not crash. Is there any reason to try (my first) backtrace ?

Branch: gtk3-gui-touchup-and-bugfix
Version: 4.2.675
Changeset: 3b7ef934ce5f6ac725ee2d8e1258238f211115cc
Compiler: gcc 5.3.0
Processor: undefined
System: Windows
Bit depth: 32 bits
Gtkmm: V3.18.0
Build type: debug
Build flags:  -m32  -mthreads  -std=gnu++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -O1 -g2
Link flags: -m32 -mthreads  -static-libgcc -Wl,--large-address-aware,--verbose  -march=native -O1
OpenMP support: ON
MMAP support: ON

**Comment by Hombre57** [comment]
@iliasg Is it crashing specifically with this branch ? I'm asking because I'd like to merge it to the gtk3 branch (and leave it open for more tuning).

If not, could you open a new issue for that ?

**Comment by iliasg** [comment]
@Hombre57 I first detected the crash with this branch, but Ι have the same crash with the latest version of GTK3 branch https://discuss.pixls.us/t/new-windows-builds/615/51?u=ilias_giarimis which is solved by using -mstackrealign flag 

A previous version of GTK3 branch was fine without -mstackrealign (and 2% faster)
Branch: gtk3
Version: 4.2.672
Changeset: aa212e58422d4a66e05bcfd20545e317f9a35912

I think you are free to merge as the speed penalty is small, and I am not able to help with tests for the moment ..

**Comment by Beep6581** [comment]
+1 for merge

**Comment by Beep6581** [comment]
What is the status of the https://github.com/Beep6581/RawTherapee/tree/gtk3-gui-touchup-and-bugfix branch?

**Comment by Hombre57** [comment]
I'm trying to make more changes. I've removed set_border_width from the code but the css replacement (margin, padding) doesn't work! It would be nice if you could look at it, but I don't want to commit this WIP, so i'll post a patch later today.

**Comment by Hombre57** [comment]
Here is the patch. The problem is the padding and margin values set in the css file but not used by Gtk3. When exploring the GUI with the Inspector, it shows that the class is correctly referenced ...but it has no effect.

Eg : line 207, 217, 221 and so on...

[Gtk3-GUI adjustment.patch.txt](https://github.com/Beep6581/RawTherapee/files/120777/Gtk3-GUI.adjustment.patch.txt)

**Comment by Beep6581** [comment]
@Hombre57 I will take a look. Please bump me in a few days if I still haven't.

**Comment by Hombre57** [comment]
Bump ? :)

**Comment by Beep6581** [comment]
Sorry, I haven't forgotten, just had no time yet.

**Comment by Beep6581** [comment]
Hey, I have this at the top of my TODO list now. I checked out `gtk3-gui-touchup-and-bugfix` but the patch doesn't apply. Please advise what to do to.

**Comment by Hombre57** [comment]
Patch applied fine here. Anyway, I've create a Gtk3-GUI-Touchup branch.

**Comment by Beep6581** [comment]
For reference:
In Gtk+ 3.18(.7) to use Gtk+ Inspector you need to do either of these:
`GTK_DEBUG=interactive ./rawtherapee`
`gsettings set org.gtk.Settings.Debug enable-inspector-keybinding true`
Only then will Ctrl+Shift+d or Ctrl+Shift+i work.

Padding is generally handled in Gtk+, margin is generally not handled in 3.18.7 yet. "The situation is improved in 3.20"

**Comment by Beep6581** [comment]
Padding inside a frame works, but I couldn't get it to work inside MyExpander. One option would be to either put MyExpander inside a frame, or a frame around each MyExpander. The frame could be made invisible, but be there for the padding.

There are now three Gtk3 branches aside from the main `gtk3` one:
* Gtk3-GUI-Touchup
* gtk3-gui-touchup-and-bugfix
* gtk3-profile-panel-utf8-chars

**Comment by Hombre57** [comment]
My problem is to set padding around frames, not inside.

So what do you suggest ? Should I put that branch aside waiting for a generally available Gtk3 3.20 ? Or merging and have this too compact (to my eyes) to avoid managing yet another left over branch ?

**Comment by Hombre57** [comment]
- `Gtk3-GUI-Touchup`  -> test branch because you couldn't apply the patch, and I didn't want to commit to `gtk3-gui-touchup-and-bugfix` yet
- `gtk3-gui-touchup-and-bugfix`  -> main GUI touchup branch
- `gtk3-profile-panel-utf8-chars`  ->  already merged, so branch deleted

**Comment by michaelezra** [comment]
Hombre, I just tried 4.2.699 build with GTK3 and happily report that curves work with my Wacom tablet!
I mean !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Hombre57** [comment]
That doesn't surprise me, they revamped the device handling classes for Gtk3. So I'm happy for you :). Can I close issue #438 ?

**Comment by michaelezra** [comment]
yes! thank thank you!:)!!!!

**Comment by michaelezra** [comment]
I wonder if it is possible to add scroll using dragging? e.g. if one is using a wacom pen, to drag the panel up/down in order to scroll through it.

**Comment by Hombre57** [comment]
Open a new issue and I'll look at it.

**Comment by michaelezra** [comment]
thanks!

**Comment by heckflosse** [comment]
@michaelezra Does that mean you managed to make builds using msys2 environment?

**Comment by michaelezra** [comment]
Hi Ingo, unfortunately no. I could not find the time to redo it all.. started 2 businesses recently  (timelessme.com and photovertex.com, preparing for the ArtExpo in April - btw if anyone would like to attend I can provide tickets for free). I hope to sort various things out and be active in the project again.

**Comment by heckflosse** [comment]
Hi Michael, glad to see you back in the project at least a bit. If you need assistance to build rt using msys2, please cry loud :-) We need more tests and making your own native build of rt would also speed up your rt processing a bit ;-)

Ingo

**Comment by Hombre57** [comment]
I didn't recall that `gtk3-gui-touchup-and-bugfix` has already been merger to Gtk3 branch and no commit has been done after. So I've deleted that branch.

**Comment by Beep6581** [comment]
> So what do you suggest ? Should I put that branch aside waiting for a generally available Gtk3 3.20 ? Or merging and have this too compact (to my eyes) to avoid managing yet another left over branch ?

I have two usability difficulties with `Gtk3-GUI-Touchup`:
1. The tool enable/disable button is hard to hit. Normal priority.
2. The curve bottom-left/top-right points are almost impossible to grab. High priority, as it makes using them very difficult.

I spoke with Gtk+ devs and showed them the problem, and it seems to be simply that the padding/margin support we need is not there in 3.18 yet. 

As I see it, there are four options:
1. Merge as-is. Not desirable due to "enable" button and curve point difficulties.
2. Abandon branch. Not desirable.
3. Wait for Gtk+ 3.20. Not reasonable.
4. Implement workaround or redo hard-coded margins for "enable" button and curve box.

Waiting for 3.20 is not a solution because it hasn't even been released yet and it will be a year before it gets into mainstream distros, and even then it would be harsh of us to say 3.20 is the minimum required version. I don't think maintaining a branch for a year is an acceptable solution either. What do you think of my idea of using an invisible frame to work around the problem? Otherwise we need to re-introduce hard-coded margins for the MyExpander containers and for the curve box containers.

**Comment by Hombre57** [comment]
Yes, option 4 is the best one. I'll try to do it tomorrow.

**Comment by Hombre57** [comment]
Patch committed to the GUI-touchup branch. Don't ask me to shrink all margins to have a more compact UI, it's already very compact. If you want something more compact, think about providing a smaller icon set, or wait for Gtk v3.20.

**Comment by Beep6581** [comment]
Hombre great work, both issues are fixed and I'm happy to see that the code is cleaner and makes better use of CSS.

**Comment by Beep6581** [comment]
In `master` when you click on the empty space on an adjuster's bar, to the left or to the right of the knob, the value of the slider is increased or decreased by a set amount, in RT typically 2 or 10. In `gtk3` when you do that, instead of being increased or decreased by some amount, the knob jumps straight to that spot. Do you think we could have the old behavior back? Should I open a new issue?

**Comment by sguyader** [comment]
I also prefer the older way, it's generally faster for increasing/decreasing values by a set amount which is larger than unit amount, and it allowed to be less precise with where you click.

**Comment by Hombre57** [comment]
@sguyader  Désolé mais je n'ai aps compris ce que tu veut dire, pourrais-tu me réexpliquer en français ?

**Comment by sguyader** [comment]
Désolé, je voulias dire que je préfère aussi comment ça marchait avec Gtk+2 : on peut cliquer approximativement d'un côté ou de l'autre du slider pour faire augmenter/diminuer par incréments, c'est plsu rapide que de chercher à cliquer précisément sur le petit bouton +/- et cliquer de multiples fois car chaque clic augmente/descend la valeur d'une seul unité. J'espère que je suis un peu plus clair ?

**Comment by Hombre57** [comment]
C'est très clair, oui.

I'm looking at this.

**Comment by Hombre57** [comment]
I looks like the new implementation of Gtk::HScale has transferred the *increment move* on the right mouse button. However it only move the slider by an unknown amount instead. The increment is however correctly set in rtgui/adjuster.cc, line 335, with the same value as the spin button, 5 lines above.

Btw, scrolling or CTRL+scrolling over the spin button have the same effect then clicking on the slider's range.

So I guess that it's in the hands of the Gtk3 team, I don't see any workaround here and don't intend to spend time on it.


Soooo....    can I merge the GUI-Touchup branch, and should I delete it ?

**Comment by Beep6581** [comment]
:+1:
