### ISSUE TITLE
'Cancel job' in Queue does not work when using context menu

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#3104]
Add a job to the queue. Switch to queue. Right click and select 'Cancel job'. Doesn't work in master branch. Worked some time ago. Using keyboard 'del' or clicking on 'x' still works.

Ingo

**Comment by adamreichold** [comment]
Sorry about that, the problem was part of the C++11 example code, i.e. I made an error when replacing separate calls to `sigc::mem_fn` and `sigc::bind` by `std::bind`.

**Comment by heckflosse** [comment]
Thanks for fixing it :+1:
