### ISSUE TITLE
Crash when displays a folder with files uses HaldCLUT

### ISSUE THREAD

**Issue by morosakubek** [Beep6581/RawTherapee#3105]
Dear Developers,
Rawtherapee crash when displays a folder with files uses HaldCLUT (NEF and CR2 files). When you clean the folder '.cache' (Manjaro Linux) starts normally. After restarting the program hangs when loading thumbnails.

gdb output:
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffbf7fe700 (LWP 19576)]
0x0000000000a6468c in rtengine::HaldCLUT::correct(rtengine::Imagefloat&, int, float, float, float, float&, float&, float&)
    ()

Sorry for my English.

**Comment by adamreichold** [comment]
@morosakubek Thank you for reporting this. Can you also add the output of `bt full` from `gdb` as well? Also the about-this-build information is necessary and an example image with the corresponding PP3 file would be helpful. Some more hints and advice on how to analyze such issues can be found [here](http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports).

**Comment by morosakubek** [comment]
(gdb) bt full
#0  0x0000000000a646fd in rtengine::HaldCLUT::correct(rtengine::Imagefloat&, int, float, float, float, float&, float&, float&) ()
No symbol table info available.
#1  0x0000000000889536 in ?? ()
No symbol table info available.
#2  0x00007ffff337dc4f in GOMP_parallel (fn=0x887db0, data=0x7fffbf7fc220, num_threads=1, flags=0)
    at /build/gcc-multilib/src/gcc-5.3.0/libgomp/parallel.c:168
No locals.
#3  0x0000000000894a2a in rtengine::ImProcFunctions::rgbProc(rtengine::Imagefloat*, rtengine::LabImage*, rtengine::EditBuffer*, LUT<float>&, LUT<float>&, LUT<float>&, rtengine::SHMap*, int, LUT<float>&, LUT<float>&, LUT<float>&, float, float, rtengine::ColorGradientCurve const&, rtengine::OpacityCurve const&, bool, LUT<float>&, LUT<float>&, rtengine::ToneCurve const&, rtengine::ToneCurve const&, rtengine::ToneCurve const&, rtengine::ToneCurve const&, double&, double&, double&, float&, float&, float&, double, int, int, rtengine::DCPProfile*) ()
No symbol table info available.
#4  0x0000000000991da9 in rtengine::Thumbnail::processImage(rtengine::procparams::ProcParams const&, int, rtengine::TypeInterpolation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, double, double, float, float, float, float, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, double&) ()
No symbol table info available.
#5  0x000000000074f5bc in Thumbnail::processThumbImage(rtengine::procparams::ProcParams const&, int, double&) ()
No symbol table info available.
#6  0x00000000005c5b97 in ThumbImageUpdater::Impl::processNextJob() ()
No symbol table info available.
#7  0x00007ffff6d31ca2 in ?? () from /usr/lib/libglibmm-2.4.so.1
No symbol table info available.
#8  0x00007ffff6fc40ae in ?? () from /usr/lib/libglib-2.0.so.0
No symbol table info available.
#9  0x00007ffff6fc3715 in ?? () from /usr/lib/libglib-2.0.so.0
No symbol table info available.
#10 0x00007ffff2f464a4 in start_thread () from /usr/lib/libpthread.so.0
No symbol table info available.
#11 0x00007ffff2c8413d in clone () from /usr/lib/libc.so.6
No symbol table info available.

**Comment by Beep6581** [comment]
@morosakubek what about the AboutThisBuild.txt file, the version, etc. etc. ? Please see the link again. If you compiled your own build, make sure you're using a '**debug**' build for the stack-backtrace, not a 'release' one.

**Comment by Floessie** [comment]
DrSlony,

This is actually an old bug in the official 4.2 release, see Issue https://github.com/Beep6581/RawTherapee/issues/2558. Nevertheless it's still present in most if not all Linux distributions due to the lack of a more recent official release. So it's very likely this bug will surface every now and then.

Best,
Flössie

**Comment by Beep6581** [comment]
Ok, then due to lack of reply and old version, closing as already-fixed.
