### ISSUE TITLE
#include inside comments

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#3108]
Touching one of the following files forces make to rebuild rawimagesource.cc because make doesn't check that the #include is inside a comment.
If the comment is like //#include "foo" cmake works correct.

fast_demo.cc
amaze_demosaic_RT.cc
CA_correct_RT.cc
cfa_linedn_RT.cc
green_equil_RT.cc
hilite_recon.cc
expo_before_b.cc

Fixed with e5b1abd

**Comment by Beep6581** [comment]
Confirmed in cmake-3.3.1.
