### ISSUE TITLE
Annoyoing output in console when closing RT

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#3113]
When I close RT:

$ cat AboutThisBuild.txt
Branch: amaze_speedup
Version: 4.2.615
Changeset: e5b1abdc3b508bd8f0766693c26d49ce2783ec4d
Compiler: gcc 5.3.0
Processor: undefined
System: Windows
Bit depth: 64 bits
Gtkmm: V2.24.4
Build type: Release
Build flags:  -std=gnu++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON

I always see this on console:

(rawtherapee.exe:6776): GLib-GObject-WARNING **: instance of invalid non-instantiatable type '(null)'

(rawtherapee.exe:6776): GLib-GObject-CRITICAL **: g_signal_handlers_disconnect_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(rawtherapee.exe:6776): GLib-GObject-WARNING **: instance of invalid non-instantiatable type '(null)'

(rawtherapee.exe:6776): GLib-GObject-CRITICAL **: g_signal_handlers_disconnect_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(rawtherapee.exe:6776): GLib-GObject-WARNING **: instance of invalid non-instantiatable type '(null)'

(rawtherapee.exe:6776): GLib-GObject-CRITICAL **: g_signal_handlers_disconnect_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(rawtherapee.exe:6776): GLib-GObject-WARNING **: instance of invalid non-instantiatable type '(null)'

(rawtherapee.exe:6776): GLib-GObject-CRITICAL **: g_signal_handlers_disconnect_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(rawtherapee.exe:6776): GLib-GObject-WARNING **: instance of invalid non-instantiatable type '(null)'

(rawtherapee.exe:6776): GLib-GObject-CRITICAL **: g_signal_handlers_disconnect_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

Ingo

**Comment by Beep6581** [comment]
I too get those when closing RT in both `master` and `gtk3` branches.
```$ ./rt_master/rawtherapee 
(rawtherapee:23430): GLib-GObject-WARNING **: The property GtkWindow:allow-shrink is deprecated and shouldn't be used anymore. It will be removed in a future version.
/home/drslony/test_images/amsterdam_lossy_dng14_linear.dng: You must link dcraw with libjpeg!!
/home/drslony/test_images/amsterdam_lossy_dng14.dng: You must link dcraw with libjpeg!!
/home/drslony/test_images/amsterdam_lossy_dng14_linear.dng: You must link dcraw with libjpeg!!
/home/drslony/test_images/amsterdam_lossy_dng14.dng: You must link dcraw with libjpeg!!
/home/drslony/test_images/schwarzenbergovo_jesusland.png uses an unsupported feature: <palette-indexed colors|interlacing>. Skipping.
embedded profile is not an RGB profile, using sRGB as input profile
embedded profile is not an RGB profile, using sRGB as input profile

(rawtherapee:23430): GLib-GObject-WARNING **: instance of invalid non-instantiatable type '(null)'

(rawtherapee:23430): GLib-GObject-CRITICAL **: g_signal_handlers_disconnect_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(rawtherapee:23430): GLib-GObject-WARNING **: instance of invalid non-instantiatable type '(null)'

(rawtherapee:23430): GLib-GObject-CRITICAL **: g_signal_handlers_disconnect_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(rawtherapee:23430): GLib-GObject-WARNING **: instance of invalid non-instantiatable type '(null)'

(rawtherapee:23430): GLib-GObject-CRITICAL **: g_signal_handlers_disconnect_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(rawtherapee:23430): GLib-GObject-WARNING **: instance of invalid non-instantiatable type '(null)'

(rawtherapee:23430): GLib-GObject-CRITICAL **: g_signal_handlers_disconnect_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(rawtherapee:23430): GLib-GObject-WARNING **: instance of invalid non-instantiatable type '(null)'

(rawtherapee:23430): GLib-GObject-CRITICAL **: g_signal_handlers_disconnect_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed


$ ./rt_gtk3/rawtherapee 

(rawtherapee:23621): GLib-GObject-WARNING **: The property GtkSettings:gtk-button-images is deprecated and shouldn't be used anymore. It will be removed in a future version.
/home/drslony/test_images/amsterdam_lossy_dng14_linear.dng: You must link dcraw with libjpeg!!
/home/drslony/test_images/amsterdam_lossy_dng14.dng: You must link dcraw with libjpeg!!
/home/drslony/test_images/amsterdam_lossy_dng14_linear.dng: You must link dcraw with libjpeg!!
/home/drslony/test_images/amsterdam_lossy_dng14.dng: You must link dcraw with libjpeg!!
/home/drslony/test_images/schwarzenbergovo_jesusland.png uses an unsupported feature: <palette-indexed colors|interlacing>. Skipping.
embedded profile is not an RGB profile, using sRGB as input profile
embedded profile is not an RGB profile, using sRGB as input profile

(rawtherapee:23621): GLib-GObject-WARNING **: instance with invalid (NULL) class pointer

(rawtherapee:23621): GLib-GObject-CRITICAL **: g_signal_handlers_disconnect_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(rawtherapee:23621): GLib-GObject-WARNING **: instance with invalid (NULL) class pointer

(rawtherapee:23621): GLib-GObject-CRITICAL **: g_signal_handlers_disconnect_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
```

**Comment by heckflosse** [comment]
I tried to bisect:
7d28c2531c73f87775231959fd916684d59ae1df is fine
b5a7037e4f7c9cf7dcdfe68cde02662262f08d5d shows the warnings, but I guess the bug is in
cc266431646867831f8797689bfd7f1628eebdd4 (which I can't build here)
@adamreichold can you have a look?

Ingo

**Comment by adamreichold** [comment]
@heckflosse I will look into it, but I don't know how soon I'll be able to do that, hopefully on the weekend. A little too much on my plate at the moment...

**Comment by adamreichold** [comment]
@heckflosse The culprit actually seems to be de8c7df0906b0e7a3463b3fad656bbda804bebb9, but I have yet to determine what exactly causes this. At least removing the implementation of `bindCurrentFolder` (binding a lambda to a signal) or removing the binding of a `std::bind` functors in the batch queue which were my first candidates did not resolve the warnings here. Will continue checking the changes...

**Comment by adamreichold** [comment]
@heckflosse Seems to have been an issue with the destruction order in the batch queue. Opened pull request #3120 to fix it.

**Comment by Beep6581** [comment]
I confirm the PR fixes it.

**Comment by heckflosse** [comment]
I also confirm the fix. Thank you :+1:
