### ISSUE TITLE
Amaze demosaic

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#3114]
I did a code review of Amaze which includes a lot of small speedups (you know, even small speedups sum up) and also cleans the code a bit (less code, better readability, at least for me ;-)

The first part, which I will push in a new branch tomorrow, speeds up Amaze processing time of a D800 NEF on my machine from 601 ms to 517 ms, which is about 14% (not so much). That's the part which doesn't introduce before/after differences (only a few pixels are different because I changed one calculation from 3(a^2+b^2+c^2) - (a+b+c)^2 to (a-b)^2 + (a-c)^2 + (b-c)^2 which is mathematically equivalent, bot not numerically in float space).

However, the difference can only be noticed by amplifying, not by eyeball

I would like to get a review for this part before I make further changes which will introduce before/after differences (I commented the planned changes in the first commit, search for 'TODO_INGO') when I pushed the first commit.

Ingo

**Comment by heckflosse** [comment]
Branch pushed: https://github.com/Beep6581/RawTherapee/commit/2017a0e59223878913f5c1e04ab97c29c4c02d7c

**Comment by Desmis** [comment]
Hello Ingo
I tested new branch "amaze"

No visible differences, in TIF.
Very very very very small differences with layers differences in Photoshop CS 

And about 10% to 20% speed-up

As always good job :)

**Comment by Beep6581** [comment]
I did a comparison before/after patch, no issues whatsoever.

**Comment by heckflosse** [comment]
With ee665d6  I cleaned the code and made some changes to nyquist part of Amaze.
Original implementation of this part had loop dependencies which let to differences in output when changing tile size of Amaze. I removed these dependencies. Now there are no differences when changing tile size, but of course there are differences to output of last commit.
I also changed one summation in nyquist code: https://github.com/Beep6581/RawTherapee/blob/amaze_speedup/rtengine/amaze_demosaic_RT.cc#L913 because the comment didn't fit to the code and the comment sounds logical.

Please test, Ingo

**Comment by Desmis** [comment]
Ingo

I tested your new changes, with "nyquist code" on "FileRGGB_sg.dng" and on others habitual files
The results are a "little better", but on a normal photo, I think no visible differences

No differences in spped-up 

:)

**Comment by iliasg** [comment]
Useful would be tests on http://filebin.net/vjdg287lng/2015-12-04_karin_library_13_01-05.dng to see if there is any improvement regarding https://github.com/Beep6581/RawTherapee/issues/2490#issuecomment-172653631 or find a solution (Amaze is worse than other demosaickers there.
(I cannot compile RT yet ..)

**Comment by heckflosse** [comment]
@iliasg I tested with the hdr dng you linked. There is no improvement regarding https://github.com/Beep6581/RawTherapee/issues/2490#issuecomment-172653631
I would prefer to check first whether the artifacts are a result of the merging process.

Ingo

**Comment by Desmis** [comment]
Ingo

I completed my test
1) with noisy image (D800) : there are small differences, but I can 't say what image is better !
2) with a D4 50 ISO : small differences in colored area -with colored variations - no visible differences - small differences in Layers differences...eg, With Photoshop CS in 16 bits : 
first image : L=18302 a=2043 b=6479   second: L=18532 a=2065 b=7946  (it is the maximum difference I found)

Globaly with test on  "FileRGGB_sg.dng", I think results are better, and speed-up about 15%

:)

**Comment by michaelezra** [comment]
Ingo, thanks for another speedup, I am trying to test it. 
This may belong to another issue... I was trying to recompile RT/master branch as usual, but am getting this error:

Building CXX object rtgui/CMakeFiles/rth.dir/epd.cc.obj
In file included from c:/gtkmm64/include/cairo/cairo-ft.h:50:0,
                 from c:/gtkmm64/include/cairomm-1.0/cairomm/fontoptions.h:26,
                 from c:/gtkmm64/include/gdkmm-2.4/gdkmm/screen.h:35,
                 from c:/gtkmm64/include/gdkmm-2.4/gdkmm.h:27,
                 from c:/gtkmm64/include/gtkmm-2.4/gtkmm.h:89,
                 from C:\Users\Michael\workspace\git\RawTherapee\rtgui\shadowshighlights.h:22,
                 from C:\Users\Michael\workspace\git\RawTherapee\rtgui\shadowshighlights.cc:19:
c:/gtkmm64/include/fontconfig/fontconfig.h:115:30: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
 #define FC_CACHE_SUFFIX      ".cache-"FC_CACHE_VERSION
                              ^
c:/gtkmm64/include/fontconfig/fontconfig.h:116:31: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
 #define FC_DIR_CACHE_FILE     "fonts.cache-"FC_CACHE_VERSION

**Comment by heckflosse** [comment]
Michael, I guess you have to switch to the new tool chain using msys2. Adam explained it very good:http://50.87.144.65/~rt/w/index.php?title=Windows

I followed the instructions step by step and it worked fine here. With the exception that in RT directory structure there should be no blank e.g. c:\users\michael ezra\rt\... does not work

Ingo

**Comment by michaelezra** [comment]
Thanks, Ingo... wow seems I would need to create the entire environment from scratch. What was a reason for that?

**Comment by heckflosse** [comment]
IIRC the main reason was to be able to build new gtk3 branch on windows

**Comment by Desmis** [comment]
Hello Michael
You must suppress (delete) , all your Windows environment variables :)

**Comment by Hombre57** [comment]
Hello Ingo,

Some bad news : RT is crashing with a specific file. Since the BT shows that it crash in rtengine::RawImageSource::amaze_demosaic_RT () of the current master (as of now), I'm posting here (or should I open a new issue ?)

DNG file, pp3 file, AboutThisBuild.txt and BT are here : http://filebin.net/cgxvt7o6gu

**Comment by heckflosse** [comment]
Hi Hombre,
I'll take a look

**Comment by heckflosse** [comment]
Works fine in release build here. I'll try debug build now

**Comment by heckflosse** [comment]
Bug confirmed in debug build

**Comment by heckflosse** [comment]
Crashes with all files in debug build. Release build works fine....

**Comment by Hombre57** [comment]
Possible, I only tested with one file O:)

**Comment by heckflosse** [comment]
Fixed with 78d2d65e2a29e8e1b52aaf42b52e8a22f6a9513c

**Comment by Hombre57** [comment]
I confirm the fix, thank you Ingo !

**Comment by heckflosse** [comment]
Hombre, thanks. But I still don't know why it didn't crash with Release build...
