### ISSUE TITLE
Runtime error when converting edit

### ISSUE THREAD

**Issue by jemholdsworth** [Beep6581/RawTherapee#3115]
![image](https://cloud.githubusercontent.com/assets/16862242/12535431/32c80328-c27b-11e5-8401-6905fd4250a6.png)

Have a problem for saving raw files. the save button on top left only saves .nef 
the convert button at the bottom left gives me the error seen in the attached screenshot. Can someone suggest a fix for this?
Potentially I would like to save in raw format for prints and jpeg for online media. Any help would be greatly appreciated.. Thanks.

**Comment by Beep6581** [comment]
http://rawpedia.rawtherapee.com/Saving
http://rawpedia.rawtherapee.com/The_Floating_Point_Engine
http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports

**Comment by Beep6581** [comment]
Stale.
