### ISSUE TITLE
Ugly tooltip in RT with GTK3.14

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#3116]
The tooltips in RT have an ugly shadow. Searching the web for an solution to fix it in the stylesheet, I've found this.
https://github.com/mate-desktop/marco/issues/139

I hope this will help to fix it.

cu TooWaBoo

**Comment by Beep6581** [comment]
@TooWaBoo  that's not a stylesheet fix, its a window compositor fix.
Please always upload a screenshot of the problem.

@Hombre57 I guess such things are handled by Gtk+ and will be resolved with a Gtk+ upgrade. I'll close if you agree.

**Comment by TooWaBoo** [comment]
I can't take a screenshot of tooltips. When I push a button or do a mouse click, the tooltip is gone.

**Comment by Beep6581** [comment]
You can create a new screenshot from GIMP and set a timer, e.g. "take a screenshot of the whole window in 5 seconds".

**Comment by TooWaBoo** [comment]
Here it is.
![unbenannt](https://cloud.githubusercontent.com/assets/13800920/12537583/bd10b4fc-c2c2-11e5-99b9-6ff69429052b.png)

**Comment by Hombre57** [comment]
@Beep6581 I agree that the fix has to be in the Window compositor. I hope someone already reported the bug. We should close this issue but someone else will certainly open a new one some day... :)

**Comment by TooWaBoo** [comment]
This can be fixed by adding this to the css-file.
```
.tooltip {
	padding: 0;
}
```

**Comment by Hombre57** [comment]
Fix confirmed. Will be committed with patch from issue #3103.
