### ISSUE TITLE
RT crashes when saving a TIF file (RT WinVista_64_4.2.622)

### ISSUE THREAD

**Issue by dngimage** [Beep6581/RawTherapee#3117]
RT crashes when saving TIF files. It doesn't happen all the time but many times.
I'm using RawTherapee_WinVista_64_4.2.622-g55fc921.
I also tried RawTherapee_WinVista_64_4.2.674-g676a444_gtk3.zip and I get the same problem.

All builds found here:
https://drive.google.com/folderview?id=0B_AvPFlUj8t5SUdodURGOFdOems&usp=drive_web#list

**Comment by Beep6581** [comment]
We need a stack backtrace, sample raw and PP3, steps to reproduce, etc.
All debug builds should include gdb.exe.
http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports

**Comment by dngimage** [comment]
Using RawTherapee_WinVista_64_4.2.699-g3c016c4_gtk3.zip.
The problem is gone!

Thanks guys!

The only thing now is that there is a delay when you exit RT, but no crashes :)
