### ISSUE TITLE
Fix slow parsing of CLUT directory #2

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3121]
@adamreichold a user in the forum stated that the error message popup when scanning the Hald CLUT tree takes too long was unclear - I committed a more verbose explanation for the popup which he confirmed as being clear. However there is one more problem.

After dismissing the popup, the user must still wait many minutes before being able to actually change the Hald CLUT folder which RT is currently using. I see two solutions:

1. This is the preferred solution if possible. Dismissing the popup should also immediately abort scanning the Hald CLUT folder and the `ClutsDirectory=` key in the `options` file should be reset to empty.

2. If stopping the scan is not possible, then I think its still better if dismissing the popup resets the `ClutsDirectory=` key in the `options` file to nothing and then forcefully closes RT.

**Comment by adamreichold** [comment]
@Beep6581 Implementation of the first approach should be straight forward, yet I see one problem with that: What if the user does have a huge CLUT folder or a moderately-sized one on slow storage? Hence I'd suggest we implement the warning as question to either continue (but only asking once) or abort immediately.

**Comment by adamreichold** [comment]
@Beep6581 Pull request #3124 does the (optional) cancellation part of the above. I am not sure it is a good thing to permanently change an options entry from outside the preferences dialog and this will be quite hard to maintain in the future IMHO and hence I would suggest leaving that part out. What do you think?

**Comment by Beep6581** [comment]
Your solution is good.
