### ISSUE TITLE
Some cache Issues

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#3122]
When there are a lot of files in cache the time to close rt increases (e.g. 2 seconds for 2567 files in cache). I could reduce it by changing
auto enumerator = dir->enumerate_children ();
to 
auto enumerator = dir->enumerate_children ("standard::*");
in cachemanager.cc line 354

Now it's much faster, but cache size limitation doesn't work, but that's not caused by 1) I guess because without the modification it doesn't work either. I set the Cache limit to 2000 files but there are still 2567 files in cache after starting and closing rt.

Any ideas?

Ingo

$ cat AboutThisBuild.txt
Branch: master
Version: 4.2.631
Changeset: 91f240d057bf88f5bbe4d81695e942703d37d0ad
Compiler: gcc 5.3.0
Processor: undefined
System: Windows
Bit depth: 64 bits
Gtkmm: V2.24.4
Build type: Release
Build flags:  -std=gnu++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON

**Comment by adamreichold** [comment]
It definitely did not work before the recent rewrite and I did test it on Linux after that. I did add some error reporting to `CacheManager::deleteFiles`, does it print any messages to the console?

**Comment by heckflosse** [comment]
I'll have a look.

**Comment by adamreichold** [comment]
I found where I messed up: `fname` already contains the MD5 part which needs to be stripped of before we can determine the names of all the cache entries.

**Comment by heckflosse** [comment]
ok, "standard::*" is not enough, but "standard::*,time::*" should be enough and is still a lot faster.
Though it doesn't solve the bug... Looking...

**Comment by heckflosse** [comment]
Ok, can you add the "standard::*,time::*" thing too, please?

**Comment by heckflosse** [comment]
Damned, the '*' got removed in last comment:
```
    "standard::*,time::*"
```

**Comment by adamreichold** [comment]
Can you give pull request #3122 a try?

**Comment by heckflosse** [comment]
I'll try in an hour. Have to get some chinese food now :)

**Comment by heckflosse** [comment]
@adamreichold It works as expected and closes fast now :+1:
