### ISSUE TITLE
coverity scan 2016-01-31

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3127]
https://scan.coverity.com/projects/rawtherapee
https://scan.coverity.com/projects/rawtherapee/view_defects

**Comment by Desmis** [comment]
i push a change on a new branch "coverty_scan_one" for
* iplab2rgb.cc
* retinex.cc
* ipwavelet.cc
* partialpasted.cc

**Comment by Beep6581** [comment]
I opened a pull request https://github.com/Beep6581/RawTherapee/pull/3138
Could someone please review it?

**Comment by adamreichold** [comment]
@Beep6581 I had a look at #3138 and the `kH` part is unclear to me, but my other comments are only about maintainability and not correctness.

**Comment by heckflosse** [comment]
If there are no objections, I'll try to fix all coverity issues related to rtengine/rawimagesource.*
@adamreichold , @Desmis : ok?

Ingo

**Comment by Desmis** [comment]
Ingo, No problem :)

**Comment by adamreichold** [comment]
@heckflosse Agreed, but please have a look at #3139 first, so they are no unnecessary merge conflicts. Thank you! (I should probably have a look at asserting some assumed preconditions in the thumbnail browser selection logic...)

**Comment by heckflosse** [comment]
ok

**Comment by heckflosse** [comment]
btw: if there's interest in output of cppcheck for current master branch, I can post a link

**Comment by adamreichold** [comment]
@heckflosse Yes, I think `cppcheck` could be more useful than Coverity at this point, since we could run it locally in a fix-and-then-recheck cycle. What do you think about posting the flags and rule sets you use on a RawPedia page which could anybody could follow and improve over time?

**Comment by Desmis** [comment]
This seems to me a very good idea.
We could generalize and put on rawpedia:
* good practices. for example, even if it appears to be a double with Git, write the most common practices - those used in 95% of cases: push, merge, delete, etc. (what works and I wrote in a text editor !)
* bad pratices to avoid : we learn more with error

This is an important step towards collective learning
:)

**Comment by heckflosse** [comment]
@adamreichold @Desmis About posting cppcheck flags and rules on RawPedia: I currently use the cppcheck gui. Should I post settings for gui (e.g. screenshots of my settings) or are you using cppcheck on command line (in that case screenshots wouldn't be useful)?
I also like Jacques' idea about 'avoid bad practises' and 'how to push, merge' etc.
Ingo

**Comment by adamreichold** [comment]
@heckflosse If that is what you use, a screenshot certainly seems like a good start. We can always add scripting later on. Browsing the results is certainly easier using the CppCheck GUI.

@heckflosse @Desmis Concerning the best and bad practices. Do you think linking specific articles (like a coding guideline) and documentation would suffice or should we explicitly write our own RT-specific documentation? (For example, the [CppCore guidelines](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md) are a nice high-level coding guide IMHO.)

**Comment by Beep6581** [comment]
This is a good idea and I am for it, but remember that you can also use https://github.com/Beep6581/RawTherapee/wiki

**Comment by Desmis** [comment]
@adamreichold 

I think, both:)

"CppCore guidelines" seems to be a very good article (that I must read!).

But I think - not specialy to write code C++, but for usual pratice with Git (merge, PR, push, etc.) to have :

For good practices :  a) synthesis in a line of the command which will be used in 95% of cases; b) a link as you say with specific articles

For (all) "bad" pratice it is probably more complex,  is key to feedback (bad practices, errors are source of learning), and is something complex (when I was in business I took care of feedback on security and organizational problems). We can begin by stating the problem (in fact the story) and the solutions implemented at different levels: 1) the practice at operational level (what we should do and not, with command, code,...); 2) the organization of the project (documentation, cooperation, rules,...); 3) the aims and objectives (affect the future of the project, its organization, its structure, its goals...)

**Comment by Beep6581** [comment]
New scan #3558
