### ISSUE TITLE
PP3 in cache should match image file checksum regardless of its location

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3134]
If you set RT to store processing profiles only in the cache, apply a PP3 to some raw file, then move the raw file to a different folder, RT doesn't find the PP3. It seems to me that it should, as moving a file generally does not change its MD5. Is there a good reason RT doesn't match the file when its moved?

Related question:
https://discuss.pixls.us/t/rt-disabling-pp3/801/11?u=Tina_Turner

**Comment by patdavid** [comment]
How does this work? Does RT have to calculate an md5 hash for every file in a directory every time it's accessed? Might slow things down...

What about a per-directory hash to track changes on a directory basis too?

**Comment by Hombre57** [comment]
The MD5 is computed from the full path only IIRC. This is required to handle 2 images with same file name nut in different filder, which is a pissible situation. Moving files through RT's file panel will handle everything correctly (well, it should), but do that through your OS and the pp3 file is orphan.

**Comment by Beep6581** [comment]
The MD5 is a hash of the full path, and not a hash of the file itself?

**Comment by heckflosse** [comment]
@Beep6581 yes, iirc. For the reason Hombre wrote about

**Comment by Hombre57** [comment]
What could be done is enhancing the File Browser to be able to create/delete/move folders, as well as drag'n'dropping thumbnails onto Folder to move them. This will make everything more user friendly and usable. Should be a new issue, and no, I'm not candidate to code it (other things to do).

**Comment by Beep6581** [comment]
The "solution": additionally hashing the whole image files, storing both the full path hash and the file content hash in the cache, and making assumptions about what to do when encountering a file (in the File Browser or Editor) which has a matching content hash but no matching path hash in the cache.
The "solution" would be slow and messy and barely useful, so I'll close this.
