### ISSUE TITLE
New preview canvas

### ISSUE THREAD

**Issue by Hombre57** [Beep6581/RawTherapee#3136]
As already discussed more than a year ago in issue #2538, I finally managed to updated the Canvas mechanism so that we can have free space around borders and manipulate widgets in this free space. See the [NewPreviewCanvas](https://github.com/Beep6581/RawTherapee/tree/NewPreviewCanvas) branch.

It also solve issue #2578.

**Comment by Hombre57** [comment]
I know that being able to pan the image that much away from border my be disturbing and useless, but this is for good reasons : if you want to use airbrush on borders or move object beyond the image space, this is required.

If you're okay, I'd like to commit this asap so I could concentrate on thinking about local adjustments.

While you're testing this, I'll try to finish the Gtk3 GUI touch-up.

**Comment by Beep6581** [comment]
@Hombre57 compiled and tested, works great! Merging for more testing sounds fine.

**Comment by adamreichold** [comment]
@Hombre57 I'll open a pull request, so that we can have a better overview over comments that inside the branch or commit views...

**Comment by Hombre57** [comment]
I'd like to commit rather soon, possibly by the end of the week (on saturday) if no one complain.

**Comment by adamreichold** [comment]
@Hombre57 I am not yet through with the review, but I also do not think that my lack of progress or rather bad time management should prevent these improvements from being merged. So a +1 from me...

**Comment by Hombre57** [comment]
Thanks @adamreichold . PR merged into master and branch deleted. Closing this issue as well.
