### ISSUE TITLE
Canon EOS 6D camconst/DCP

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3144]
Shots required for adding camconst.json/DCP support for Canon EOS 6D:
http://filebin.net/87o14i5q7m
Password: calumetphoto
Link expires: 2016-02-29
From: https://discuss.pixls.us/t/beginner-questions-and-observations-profiles-setup-etc/726/9

@iliasg would you like to take this or should I do it?

**Comment by iliasg** [comment]
If a Dcamprof for win32 was available I would like to take this .. but there isn't :(
Regarding the Black/White levels I think we are already at a very good shape but I will take a farther step investigating how the LENR changes things.

**Comment by Beep6581** [comment]
I will make the DCP. It's specifically the black/white level checking which I meant in my question, as you know the things to look out for better than I do.

**Comment by gaaned92** [comment]
@iliasg 
The desired win32 dcamprof build is [here](https://drive.google.com/open?id=0B2q9OrgyDEfPOEZmVlBzLWlnSWc).
I just tested the help function. I hope I included all dependencies.

**Comment by iliasg** [comment]
thanks .. now I have to make myself familiar with Dcamprof ..
as about black/white levels I think we are 99% fine with no change in camconst.

**Comment by RawConvert** [comment]
From: https://discuss.pixls.us/t/beginner-questions-and-observations-profiles-setup-etc/726/9
To add to the previous files, here are more colour chart exposures for profile making:
http://filebin.net/y4bj1y6rhr
These are 6D sunshine and overcast pics.
Andrew

**Comment by Beep6581** [comment]
@RawConvert can you also provide a tungsten shot?

If you're wondering how to take good tungsten shots - I took a shot last year in the basement, because the walls are white and there are real tungsten bulbs there. I took another shot this year in a white tiled bathroom. I was surprised to find that DCPs made from each lead to identical results. I take this as confirmation that either environment was good. Just make sure you're at least 2 meters away from the bulb and that the chart is more or less perpendicular to the light source, so that the illumination of the chart is relatively even and glare free.

**Comment by RawConvert** [comment]
hi,  I sent a load of files a few weeks ago, the link is amongst the posts, hopefully someone downloaded, it might have expired now.  There was a tungsten shot in there (and a daylight bulb too).
Andrew

**Comment by Beep6581** [comment]
Ah you're the same person :) Yes I have it, no problem.

**Comment by RawConvert** [comment]
phew!

**Comment by Beep6581** [comment]
@RawConvert the old daylight shots require a 0.89 tint adjustment which is an indicator that something is probably wrong with the light. I'll delete them. The old tungsten shot has temperature values that look correct - can you confirm that the lightbulb was clear, untinted tungsten? http://images.wisegeek.com/light-bulbs.jpg

In the future please remember to position the brown patch in the top-left, with the neutral patches at the bottom. I can correct this in RT or in ArgyllCMS but less work and possibly better to not have to do that. Also position the chart so that it doesn't need perspective correction.

I used the overcast shot as the DE were far better than from the other one.
[Canon EOS 6D.dcp.txt](https://github.com/Beep6581/RawTherapee/files/160601/Canon.EOS.6D.dcp.txt)
DCP committed.

As @iliasg is happy with the current black/white levels, I'll close.

**Comment by RawConvert** [comment]
hi Morgan,  thanks for this.
 
I’m not sure what you mean by “old daylight” shots, I think the only daylight ones were the ones yesterday.  Do you mean 2742, 2743?  These were a “daylight” fluorescent bulb.  This might account for the tint?  Did you see the text file I enclosed with the main bunch?
 
The tungsten was indeed a clear plain bulb.
 
Lastly, I don’t understand “I used the overcast shot as the DE were far better than from the other one.”.  I’ve only sent one overcast shot surely, no.2954.
 
Hoping the above makes sense,
Andrew

**Comment by Beep6581** [comment]
Old daylight shots = the ones from the now-expired link from 25 days ago which you provided in https://discuss.pixls.us/t/beginner-questions-and-observations-profiles-setup-etc/726/9
The delta E values from the overcast shot were better than those from the various daylight shots (old and new).

**Comment by RawConvert** [comment]
Hi,  I was wondering if the 6D colour profiles / parameter files have been done from the test shots I sent in recently.  If so, how can I get them please?  Thanks,  Andrew

**Comment by Beep6581** [comment]
They are included in all builds since March 6.

**Comment by RawConvert** [comment]
Ok well can you help me find them please.  I’ve installed the latest win XP RT (dev, 4.2.745) but there’s no 6D file in the dcpprofiles folder, see attached.
Similarly I’ve installed the latest dev Ubuntu version and can’t see a 6D profile there either.

**Comment by Beep6581** [comment]
That build is not recent enough.
If you want the file, get it from the git repo: https://github.com/Beep6581/RawTherapee/tree/master/rtdata/dcpprofiles

Two things:

1. In the future, when referring to a version, please provide the commit hash instead of "4.2.745", as the latter doesn't tell us anything.
2. Also, I suggest not replying or writing things here using email, because there is a lot of "spam" included in the post, and because things like attachments do not work. Use https://github.com/Beep6581/RawTherapee/issues

**Comment by iliasg** [comment]
After examining LENR shots I found that we have to slightly alter the strategy about white levels for Canon Dslrs (a bit less conservative at low ISOs but a bit more at high ISOs). 
The subtraction with LENR set to On spreads the single clipping point and this spread depends on (per ISO) read noise. The more is the noise the more the clipping spreads .. 
I thing there is no need to update now as the difference is small 
I will include the above (more detailed per ISO WL for 6D + directions how to measure/calculate) in the upcoming (this week) camconst.json update (which will also include many new models )
