### ISSUE TITLE
Unable to send image to external editor [windows]

### ISSUE THREAD

**Issue by sguyader** [Beep6581/RawTherapee#3148]
As initially reported [here](https://discuss.pixls.us/t/cannot-opeh-gimp-from-rt/843), when trying to export the current image to external editor, a window pops up saying "Cannot start editor", though the path to the editor is set correctly. The initial poster found this using RT 4.2.699 Gtk3, and I reproduce it in many different builds including the old 4.2.372 Local Lab.
It happens on Windows 7 and 10, 64 bits (I can't try 32-bits builds currently).

Screenshot:
[imgur](http://imgur.com/u90LD5J)

I'm not sure it is really a rawtherapee problem, I don't see any suspect message in debug console.

**Comment by Hombre57** [comment]
Do you have gspawn-win64-helper.exe (or the 32 bits counterpart) installed next to rawtherapee.exe ?

**Comment by Beep6581** [comment]
https://github.com/Beep6581/RawTherapee/blob/master/rtgui/editorpanel.cc#L1743
Which version of GIMP do you have installed?
What is the full path to `gimp-win-remote.exe` and to `gimp-2.*.exe`?
Have you tried deleting or renaming the options file?

**Comment by sguyader** [comment]
@Hombre57, yes I have the executables at the correct place, I even tried some from older installations.

@Beep6581, I tried with the current Gimp version downloaded today from the official Gimp website (2.8.16 I think). The original poster tried and had the problem with both 2.8 and 2.9.
The path to Gimp binary was the default one (C:\Program Files\gimp\bin). And I checked the options file to be sure it had the correct path recorded, though I didn't try to delete it. Will try later.

**Comment by sguyader** [comment]
Deleting the options file doesn't do better.

**Comment by dngimage** [comment]
Mine works fine. I am using RawTherapee4.2.730 on Win-64-bit/Win7 and GIMP 2.8.14.

**Comment by Beep6581** [comment]
dngimage could you try with 2.8.16 from the official GIMP website?

**Comment by dngimage** [comment]
@Beep6581 ,

Using now gimp-2.8.16-setup.exe for Windows, found here:

https://www.gimp.org/downloads/

And it still works.

![preferences](https://cloud.githubusercontent.com/assets/16865949/13096120/61f15956-d4dc-11e5-9848-a11ca5dfb1b5.jpg)

**Comment by sguyader** [comment]
Now I'm feeling really stupid... I did set the path to "...\Gimp 2\bin" instead of just "...\Gimp 2". So there's no bug at all, it works, sorry for that.
In fact, in the [Rawpedia article](http://50.87.144.65/~rt/w/index.php?title=Edit_Current_Image_in_External_Editor) the way to correctly set the path is not specified, maybe it should be clearly stated.

**Comment by Beep6581** [comment]
I don't use Windows - please provide an example of the correct path, then I'll add it to RawPedia.

**Comment by sguyader** [comment]
In fact it seems to depend on the Gimp build, and on the type of Windows build (32 or 64 bits). For the current official builds, the path is the root of the Gimp install folder, **not** the binary folder (\bin) within the install folder.

**Comment by Beep6581** [comment]
Ok, is that for 32-bit or 64-bit then? Please give a full path example, using GIMP's default installation folder.
Everyone reading this, please chime in.

**Comment by sguyader** [comment]
For 32 bits : C:\Program Files (x86)\GIMP 2
For 64 bits : C:\Program Files\GIMP 2

Apparently, Partha's Gimp builds install into "Gimp-2.8" instead of "GIMP 2".

**Comment by sguyader** [comment]
Oh I forgot, the first path above (the one with x86) is for 64 bits Windows. For 32 bits Windowsill there will be only the second path.

**Comment by Beep6581** [comment]
Closing due to lack of followups.
