### ISSUE TITLE
Rw2 file lense distortion

### ISSUE THREAD

**Issue by BennyNielsen** [Beep6581/RawTherapee#3150]
Hi RawTherapee

I run the 4.2.447 on a Windows 10.
I have a Panasonic DMC-FZ1000 camera.
When I load my Rw2 files into RawTherapee it looks like the lense distortion is wrong.
To my knowledge the information about lense distiortion is a part of the Rw2 file.
I have uploaded som files to dropbox.
https://www.dropbox.com/sh/iq98jf8wanzavy0/AADQ89Ji2kfbL2jZP-A3H9N-a?dl=0

Rw2 file from the camera.
Jpg _Camera_Save from the camera.
jpg _RT_Save is the Rw2 file converted by RawTherapee
jpg _SP_Save is the Rw2 file converted by SilkyPix(software with the camera) 

I hope you can help me.

Thanks for a great program
Benny Nielsen

**Comment by Beep6581** [comment]
Hey

Dropbox doesn't seem to work for me, I click "Download" and nothing happens. Please use http://filebin.net/

Raw files contain lens distortion, this is normal. You can optionally fix it using one of three methods:
* Manually,
* Using an LCP,
* Or potentially using "Auto distortion correction" if the JPEG embedded in the raw file has been corrected.

http://rawpedia.rawtherapee.com/Lens/Geometry

**Comment by BennyNielsen** [comment]
I have now uploaded the files to http://filebin.net/8u4lqnwtns

**Comment by BennyNielsen** [comment]
Where do I find an LCP file for my camera?

**Comment by BennyNielsen** [comment]
I am very disappointed in Beep6581.
He just closes my issue, without taking me seriously.
I am trying to help you make RawTherapee usable for Panasonc users.
The answer is just Issue closed :(

**Comment by Beep6581** [comment]
Cloning issues = spam, and the answer is that there is no bug here.
