### ISSUE TITLE
Before|After lock doesn't always keep the locked version

### ISSUE THREAD

**Issue by BennyNielsen** [Beep6581/RawTherapee#3151]
Hi RawTherapee

I run the 4.2.447 on a Windows 10.

I open a new picture in RT.
I press the Before/after.
I press the lock (it closes)
I change the temperature
I toggle the Before/after, off/on. It looks fine.
I change the temperature
I toggle the Before/after, off/on. It looks fine.
I change the nuance
I toggle the Before/after, off/on. The before picture now shows the previous picture and not the picture that I locked.
 
Thanks for a great program
Benny Nielsen

**Comment by Beep6581** [comment]
Confirmed in gtk3 branch when I used the Tint slider.

**Comment by Hombre57** [comment]
The locked Before view is the one that is displayed when you enter in Before/After mode, i.e. it is reset each time you enter this mode (it has always worked like this).

**Comment by Beep6581** [comment]
Ah I was thrown off by the fact that the steps to reproduce include changing *the same* slider twice, which updates the same history entry, while B|A looks at separate history entries.
I confirm that it actually works fine.

**Comment by BennyNielsen** [comment]
Ok, it did not work as I expected.
How do I get the function that I need?
I want to compare the original to the current picture during my work.
Thanks

**Comment by Hombre57** [comment]
This feature doesn't exist yet in a user friendly manner, so there should be a feature request asking for making the locked before image persistent between successive toggling of the B/A mode. It may be low priority though.

**Comment by BennyNielsen** [comment]
Ok, Thank you :)
