### ISSUE TITLE
32bit Windows XP Raw Therapee "master" crashes while processing jobs with "resize" on.

### ISSUE THREAD

**Issue by wariag** [Beep6581/RawTherapee#3152]
Hi,

I have succesfully compiled master revision 4.2.674, (hurrah ;)) with` -DCMAKE_C_FLAGS="-mstackrealign" -DCMAKE_CXX_FLAGS="-mstackrealign"`, it seems top run OK on my machine except mantioned "resize" option on.

This bug seems to be present in recent revisions; the last one (the last one tested by me) that does not crash is 4.2.507.

**Comment by heckflosse** [comment]
@wariag can you please upload the pp3 which causes the crash to filebin.net and post the link here?

**Comment by heckflosse** [comment]
@wariag Please post the Changeset from Preferences/About/Version too

**Comment by wariag** [comment]
Branch: master
Version: 4.2.674
Changeset: a7fbe52f50a8613b3cfabfddc8f9e45087f42e3c
Compiler: gcc 5.3.0
Processor: undefined
System: Windows
Bit depth: 32 bits
Gtkmm: V2.24.4
Build type: release
Build flags: -mstackrealign -std=gnu++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON

About pp3, the crash is reproductible whatever version made .pp3 file, `[Resize]
Enabled=true` = crash, `[Resize]
Enabled=false` = no crash.

[http://filebin.net/upload/a2q5t337eq](url)

**Comment by heckflosse** [comment]
@wariag thanks for the pp3 and the version info. I though it might have been caused by post-resize sharpening, but that's not the case because it's disabled. Can you make a debug build and post a [backtrace](http://50.87.144.65/~rt/w/index.php?title=How_to_write_useful_bug_reports#When_RawTherapee_crashes_-_An_introduction_to_stack_backtraces) of the crash?

**Comment by wariag** [comment]
Hi,
 
I'm compiling debug version right now.
Stay tuned ;)
 
 
 
 
W dniu 2016-02-15 15:26:30 użytkownik Ingo Weyrich <notifications@github.com> napisał:
@wariag thanks for the pp3 and the version info. I though it might have been caused by post-resize sharpening, but that's not the case because it's disabled. Can you make a debug build and post a backtrace of the crash?

**Comment by wariag** [comment]
Hi,

I'm sure that I'm doing it wrong, but 
the first pancake is always spoiled ;)

`Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 3848.0x3520]
0x00a4b171 in _mm_load_ps (__P=0xb910e68)
    at D:/msys32/mingw32/lib/gcc/i686-w64-mingw32/5.3.0/include/xmmintrin.h:928
928       return (__m128) *(__v4sf *)__P;
(gdb) bt full
#0  0x00a4b171 in _mm_load_ps (__P=0xb910e68)
    at D:/msys32/mingw32/lib/gcc/i686-w64-mingw32/5.3.0/include/xmmintrin.h:928
No locals.
#1  rtengine::boxabsblur<float, float> (src=0xf650040, dst=0xb90ce68, radx=3,
    rady=3, W=64, H=64, temp=0xb910e68)
    at D:/msys32/home/user/RawTherapee/rtengine/boxblur.h:1050
        col = 0
        onev = {1, 1, 1, 1}
        lenp1v = {-1552.65393, -1330.22327, 1.59867232e-035, -1012.89612}
        rlenv = {-5738.01074, -1326.11426, -1640.5741, 3215.69556}
        leninitv = {4, 4, 4, 4}
        tempv = {4.16997217e-033, 8.96831017e-044, 7.17464814e-043,
          5.57996444e+021}
        lenv = {4, 4, 4, 4}
        lenm1v = {1102.78589, -3735.92896, -1021.10779, 341.562286}
#2  0x00867f7c in rtengine::ImProcFunctions::RGBtile_denoise (this=0xb91ed90,
    fLblox=0xf650040, hblproc=0, noisevar_Ldetail=3.6e+009, nbrwt=0xb90ce68,
    blurbuffer=0xb910e68)
    at D:/msys32/home/user/RawTherapee/rtengine/FTblockDN.cc:2079
        blkstart = 0
        tempv = {5.56634426e-032, 1.1253642e-029, 5.62366136e-032,
          7.88424452e+033}
        noisevar_Ldetailv = {2.66246708e-043, 5.58823755e+021,
---Type <return> to continue, or q <return> to quit---`

**Comment by heckflosse** [comment]
@wariag Thanks for the backtrace. Fix follows soon.
