### ISSUE TITLE
cmake/modules/FindMacIntegration.cmake needs to be updated for the gtk3 branch?

### ISSUE THREAD

**Issue by ion12** [Beep6581/RawTherapee#3153]
On OS X "cmake" command fails for me with gtk3 branch unless "gtkmacintegration-gtk3" is added or replaces "gtkmacintegration-gtk2" in "cmake/modules/FindMacIntegration.cmake".
Tested with OS X 10.11.3

**Comment by Beep6581** [comment]
Thank you, fixed.
