### ISSUE TITLE
Use custom default processing profile 

### ISSUE THREAD

**Issue by TheChymera** [Beep6581/RawTherapee#3157]
I would like to make RawTherapee automatically add some IPTC info to any file I create with it. I have created a small processing profile to this avail:

```
[IPTC]
Author=Horea Christian;
AuthorsPosition=;
Caption=;
CaptionWriter=;
Category=;
City=;
Copyright=;
Country=;
Credit=Horea Christian (chymera.eu);
DateCreated=;
Headline=;
Instructions=;
Province=;
Source=;
Title=;
TransReference=;
```

And saved it to  `~/.cache/RawTherapee/profiles/chr.pp3`. 

I think the best way to have RT add this by default is to set it as my default processing profile - right?

Sadly, under the prefernces menu, I can only select one of the bundled profiles as my default. Any ideas what I can do about this?

**Comment by Beep6581** [comment]
It's `~/.config/RawTherapee/profiles/` not `~/.cache/RawTherapee/profiles/`.

**Comment by TheChymera** [comment]
Thanks, moving the profiles to the other directory worked.
