### ISSUE TITLE
Obsolete "project version" code in macosx_bundle.sh

### ISSUE THREAD

**Issue by ion12** [Beep6581/RawTherapee#3162]
This is only cosmetics, but in RawTherapee/rtdata/osx/macosx_bundle.sh, on lines 32-35, update project version code still references Mercurial, which results in DMG bundle not including version number.

```
if test -x $(which hg) -a -d "${PROJECT_SOURCE_DIR}/.hg"; then
  PROJECT_VERSION=$(hg -R "${PROJECT_SOURCE_DIR}" parents --template "{latesttag}.{latesttagdistance}")
fi
```

I tried using instead

```
if [ -d "${PROJECT_SOURCE_DIR}/.git" ]; then
  GIT_VERSION=$(git describe --tags --always)
  PROJECT_VERSION=$(echo ${GIT_VERSION%-*} | tr '-' '.')
fi
```

and it worked.

don't want to cause any breaks, don't know if "git describe --tags --always" always returns the same pattern that will conform to $(echo ${GIT_VERSION%-*} | tr '-' '.') being correct
maybe someone can confirm, or come up with a more elegant solution. 

Or just remove the obsolete Mercurial reference if it's too much hassle ;)

It's bash so nothing OS X specific.

**Comment by Beep6581** [comment]
@ion12 I updated the OS X scripts and moved them from `rtdata/osx` to `tools/osx`
According to https://goo.gl/eWDQv6 the `CFBundleVersion` and `CFBundleShortVersionString` must consist of "three period-separated integers", and further text implies there should be nothing more. Now this is bad because in git we need the hash and/or the branch, so I would prefer to have the version in the form of `4.2-677-g904467b_master` and not just `4.2.677`. My changes make it stick to Apple's requirements. Please confirm that it works.

Once you confirm that it works, I am curious whether it will still work if we use the full version string which includes the branch and hash. To test this, edit `tools/osx/macosx_bundle.sh`, uncomment line 37 and comment line 40, then retry building it. If it still builds with our nonconforming version string, I think we should use that, so let me know and I'll make the change once it's confirmed that it works.

**Comment by ion12** [comment]
First of all ran into a few things:

rt_build/RawTherapee/rtdata/CMakeLists.txt -> line 106:
`list (APPEND MACOSX_BUNDLE_COMMAND sh "${PROJECT_SOURCE_DIR}/rtdata/osx/macosx_bundle.sh")`
still refers to /rtdata/osx/ and not /tools/osx/

rt_build/RawTherapee/tools/osx/macosx_bundle.sh -> line 157:
`PROJECT_SOURCE_DATA_DIR="${PROJECT_SOURCE_DIR}"/rtdata/osx`
still refers to /rtdata/osx/ and not /tools/osx/

rt_build/RawTherapee/tools/osx/macosx_bundle.sh -> line  167:
`s|@shortVersion@|$(echo ${PROJECT_VERSION}|`
missing closing right parenthesis 
but I think since it's no longer piped into 'cut', no need to wrap `${PROJECT_VERSION}` into `$(echo )` anyway?

Hacked it myself just to be able to test - builds compiled with either lines 37 and 40 both seem to run fine.
Won't know if there are any end-user-undetectable ill-effects for line 37 not respecting Apple standards though.

There are 2 places where PROJECT_VERSION is used, once in lines 166-169, to generate the bundle version short string in "Info.plist" that is part of the .app bundle. 
I assume that is the string that has to adhere to the Apple standards you mentioned.
(at least officially - the test build that doesn't still works...)

The second instance, in line 191, just generates the DMG file name. I can't claim any expert knowledge on this, but just from common sense - A DMG is just a disk image, I can't think of why it's naming convention should make any difference to the .app it contains.

Perhaps you can keep both 37 and 40, but use 37 as a different variable that would only be used for DMG naming but not for Info.plist , so at least the DMG has a more descriptive name.

**Comment by Beep6581** [comment]
Thank you for the feedback, all implemented. I also re-formatted that macosx_bundle.sh file, the old formatting made it hard to read.
053905838231ee0c0bba8a885b1173a6471b70fb
9f29f49f0196ae3bec1dd54971a9d6f221372e36

**Comment by ion12** [comment]
So should the .zip files I upload also keep the same name as the new DMG naming with the full git project version?
Right now all the downloads on rawtherapee.com go by the short 4.x.xxx naming.
`RawTherapee_OSX_10.11_64_4.2-685-g80dacdd_master.dmg`
It's quite long and messy for a file name when I actually see it on the finder, maybe not such a good idea after all and it's enough to have the info in the `AboutThisBuild.txt` file? sorry...

**Comment by Beep6581** [comment]
> So should the .zip files I upload also keep the same name as the new DMG naming with the full git project version?
Yes please. I don't think the filename length is relevant to users, but it leads to less hassle for us.

OK to close?

**Comment by ion12** [comment]
Sure. RawPedia instructions still refer to short version naming, and it would be nice if Windows and Mac would be in sync with new naming scheme.

For what it's worth, I do think that the stable release versions should still use the short version string, to clearly denote they are **not** development builds... 
but that could edited manually for those rare occasions if it makes things simple.
Thanks for all the effort :)

**Comment by Beep6581** [comment]
Actually we need only version + branch, we don't need the hash to be part of it. I'll do that tomorrow. Maybe we think of something more in the meanwhile...
