### ISSUE TITLE
Detail window centres to whole image instead of centre of preview

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#3163]
With new preview canvas patch :
Open image
Zoom to 50%
move image to left as much as possible
open detail window
detail windows opens fine but shows the center of the whole image, which is out of view

Before preview canvas patch it always showed the center of current preview area

**Comment by Hombre57** [comment]
I didn't knew that it had to be centered to the current display. Should be pretty easy to fix (I'm looking into it...), but if the image's border is in the center of the main preview, so will it be for the detail window.

**Comment by Hombre57** [comment]
Fixed in commit 0b32f12.

**Comment by heckflosse** [comment]
@Hombre57 
Fix confirmed. Thank you very much :)

**Comment by heckflosse** [comment]
@Hombre57 
If you add 'fixes #1234' to the commit message, the commit will close Issue 1234 automatically when the fix is pushed :)

**Comment by Hombre57** [comment]
Good to know, thanks
