### ISSUE TITLE
PNG image appears totally black in the Editor

### ISSUE THREAD

**Issue by Hombre57** [Beep6581/RawTherapee#3171]
It's strange no-one reported that yet, so it may be related to my own repos, but just in case, have you tried to load a png image (8bits, totally standard) in the Editor ?

**Comment by heckflosse** [comment]
@Hombre57 I tried with master branch. Can't confirm, but I didn't check if it's 8bits...

**Comment by Beep6581** [comment]
Tested using
http://rawtherapee.com/shared/test_images/8_bit_chroma_subsampling.png
http://rawtherapee.com/shared/test_images/8_bit_integer_gamma.png

Works fine in `master` and `gtk3`. 
`-- Found PNG: /usr/lib64/libpng.so (found version "1.6.19+apng")`

**Comment by Hombre57** [comment]
libpng found here too, but it doesn't work, even with those 2 files.

```
-- Found PNG: D:/Jean-Christophe/Developpement/Toolchain/msys64/mingw64/lib/libpng.dll.a (found version "1.6.20")
```

**Comment by Hombre57** [comment]
I had to delete the cached CMakeFiles (even though I've re-cmaked the project), but it is working now.

**Comment by Beep6581** [comment]
Strange! Good to keep that in mind. I delete the cache files (`rm -rf build && make clean`) when I change major branches (e.g. from `master` to `gtk3`) but haven't needed to do so when changing from less change-ful branches.
