### ISSUE TITLE
RT_Win64_Gtk3_Release_4.2.787 always starts maximized

### ISSUE THREAD

**Issue by dngimage** [Beep6581/RawTherapee#3173]
Running RawTherapee_WinVista_64_Gtk3_Release_4.2.787:
1. Run RT and resize or set RT's window position.
2. Exit RT.
3. Run RT again, now RT forgets its window size\position, and always starts maximized.

**Comment by sguyader** [comment]
Confirmed, in Gtk3 builds only. It's not new, as it happens also in v. 4.2.764.

**Comment by Beep6581** [comment]
Tried both GTK2 and GTK3, both work fine here in Linux using [awesome](https://en.wikipedia.org/wiki/Awesome_(window_manager)), both remember their window size and position when restarting.

**Comment by Beep6581** [comment]
GTK2:
Version: 4.2.801
Changeset: a79e4bc24bb7854b34939edd731c8f5e4ec6fb1f

GTK3
Version: 4.2.927
Changeset: 098603c6477cc0f6d79d26ac932d270124be047b

**Comment by Hombre57** [comment]
Fixed in gtk3-bugfix branch. Closing.

**Comment by heckflosse** [comment]
@Hombre57 @Floessie Thanks for fixing that :+1:
