### ISSUE TITLE
Filename changes to "." in Save window

### ISSUE THREAD

**Issue by dngimage** [Beep6581/RawTherapee#3174]
I can't reproduce this all the time but sometimes when working on an image and I click on the save current image icon to open the Save dialog window, in the entry that says "Name:" the file name is gone. I have to re-type in the empty space the file name in order to save. If I close the image and go back to the browser, then re-open the image the bug is gone when saving. It is as if something internally is affecting or corrupting the file name before the Save Dialog Window opens and you just get nothing where the file name should be. The only way to save after that is to re-type the file name. As I said it is hard to reproduce but it happens.

**Comment by Beep6581** [comment]
If you Ctrl+s to save and delete the filename, then cancel saving, the next time you open that window the filename will be just ".". I would prefer that if one hits cancel, then none of the changes are remembered, so if you delete the filename and hit cancel, the next time you run ctrl+s for the same image it will show the full filename again.

**Comment by sguyader** [comment]
It also happens with the master/gtk2 build 4.2.696.

**Comment by Beep6581** [comment]
Still valid.

**Comment by Beep6581** [comment]
Commit e4f24fff fixed the problem if you leave a filename intact and hit the escape key or the cancel button, but if you delete the filename and then click the cancel button, the filename is lost and the "." dot appears the next time you ctrl+s.

**Comment by Floessie** [comment]
Like so?

```patch
diff --git a/rtgui/saveasdlg.cc b/rtgui/saveasdlg.cc
index 1818d748a..7067e8ed1 100644
--- a/rtgui/saveasdlg.cc
+++ b/rtgui/saveasdlg.cc
@@ -280,8 +280,6 @@ void SaveAsDialog::okPressed ()
 
 void SaveAsDialog::cancelPressed ()
 {
-
-    fname = fchooser->get_filename();
     response (Gtk::RESPONSE_CANCEL);
 }
 
@@ -297,7 +295,7 @@ void SaveAsDialog::formatChanged (Glib::ustring f)
     }
 }
 
-void SaveAsDialog::setInitialFileName (Glib::ustring fname)
+void SaveAsDialog::setInitialFileName (const Glib::ustring& fname)
 {
     this->fname = fname;
     fchooser->set_current_name(fname);
diff --git a/rtgui/saveasdlg.h b/rtgui/saveasdlg.h
index 9b06471e8..073be23f4 100644
--- a/rtgui/saveasdlg.h
+++ b/rtgui/saveasdlg.h
@@ -57,7 +57,7 @@ public:
     bool            getToTailOfQueue   ();
     int             getSaveMethodNum   ();
 
-    void  setInitialFileName (Glib::ustring iname);
+    void  setInitialFileName (const Glib::ustring& iname);
     void  setImagePath (const Glib::ustring& imagePath);
 
     void okPressed ();
```

**Comment by Beep6581** [comment]
@Floessie we found yesterday in IRC that removing this one line fixed it:
https://github.com/Beep6581/RawTherapee/blob/e4f24fff9c0bb48c260d23c4fa435a7f1970d817/rtgui/saveasdlg.cc#L284
Which fix would you recommend?

**Comment by Floessie** [comment]
😁

**Comment by Floessie** [comment]
I was grinning, because those solutions are the same. You can choose either, but mine also fixes a heavy call-by-value in the interface.

**Comment by Beep6581** [comment]
Missed that - I only half payed attention while replying from work... that's my excuse ;]
