### ISSUE TITLE
Speedup and Cleanup for raw ca correction

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#3178]
I pushed a new branch [cacorrect](https://github.com/Beep6581/RawTherapee/tree/cacorrect) to clean and speed up raw ca correction code.
I started this because I wanted to refresh understanding the code with the goal to make an xtrans version of ca-correction. But during that procedure I found a loop which got my attention.
I placed two stopwatches in code, one for the whole auto ca correction and another one for the loop:
I measured with a D800 NEF

before patch 'Median loop' : 177 ms
before patch 'CA_correct_RT' : 633 ms

after patch 'Median loop' : 4 ms
after patch 'CA_correct_RT' : 424 ms

Ingo

**Comment by iliasg** [comment]
Ingo, !!
I detected two cases where raw ca mibehaves .. 
- tiles visible (different coloration)  after strong exposure correction (say +4 stops) when we apply raw ca on underexposed shots
- coloration (redish) of black text on Imaging resource still life samples
Is it OK to post details here or it's better to open a new issue ?

**Comment by heckflosse** [comment]
Ilias, if the cases where raw ca misbehaves are not related to this Issue I would prefer opening a new Issue

**Comment by heckflosse** [comment]
I pushed further speedups and cleanups to [cacorrect](https://github.com/Beep6581/RawTherapee/tree/cacorrect). I also included a new slider which allows to control the strength (aggressiveness) of auto ca correction. The default value of 6 behaves exactly as the original version. Lower values are less aggressive.
Example:
open amsterdam.pef
zoom to the car with number plate XP-SL-89 (bottom right) without auto-ca-correction and then with auto-ca-correction and look at the left rear light
its height shrinks when activating auto ca correction
Move strength slider to 2.0 avoids shrinking the rear light but ca at wheel rims is still removed.

This new slider is currently a prototype to allow testing more easy. For that reason I didn't make a tool tip, didn't include it in partial paste and so on.

Ingo

**Comment by heckflosse** [comment]
I forgot to mention the current timings for the patch: 
last patch: 424 ms, this patch: 366 ms

**Comment by heckflosse** [comment]
I also forgot to mention that memory usage of ca correction is reduced by c * 65536 bytes where c is number of cores.

**Comment by heckflosse** [comment]
Once again I pushed further speedups and cleanups to cacorrect.
Processing time now is about 316 ms at my system for a D800 NEF, which is double speed compared to master branch.

**Comment by heckflosse** [comment]
I merged the speedup (without auto ca strength adjuster) into master and reactivated the new adjuster in cacorrect branch.

**Comment by Beep6581** [comment]
Fixed long ago.
