### ISSUE TITLE
Scroll by draggin within the Tool panel

### ISSUE THREAD

**Issue by michaelezra** [Beep6581/RawTherapee#3179]
I wonder if it is possible to add scroll using dragging? e.g. if one is using a wacom pen, to drag the toolpanel panel up/down in order to scroll through it. 

Its just once you start using the pen, you never go back to mouse:)

**Comment by Hombre57** [comment]
There's an integrated feature for scrolling ScrolledWindow, unfortunately they've reserved this possibility to touch screen only ( https://developer.gnome.org/gtkmm/stable/classGtk_1_1ScrolledWindow.html#a88132d21cc8378c793889b9fa20ac1ca ).

Still it should be possible to add this feature, but there without inertial handling (i.e. it won't allow you to *throw* the ScrolledWindow).

**Comment by michaelezra** [comment]
Hombre, Thanks for looking into it. I enabled the scroll bars and they are so elegant in GTK-3 that it is sufficient:) I will close this issue.

**Comment by Hombre57** [comment]
Nice to hear. I'm closing, yes.
