### ISSUE TITLE
'Empty trash' does not work in master branch

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#3181]
To reproduce:
Move an image to trash
Show contents of trash (Ctrl-t)
click 'Empty trash' and confirm
Image seems to be deleted.
Restart rt => image is back again

Works fine in gtk3 branch

**Comment by adamreichold** [comment]
@heckflosse Since it does not affect `gtk3`, I guess this fallout from the SafeGtk changes? Will hopefully be able to fix this tomorrow...

**Comment by adamreichold** [comment]
@heckflosse Had some spare time left after all. ;-) It was fallout as expected and it was the Root Of All Evil(tm), i.e. premature optimization
````
diff --git a/rtgui/filecatalog.cc b/rtgui/filecatalog.cc
index 236dbae..47adae7 100644
--- a/rtgui/filecatalog.cc
+++ b/rtgui/filecatalog.cc
@@ -935,7 +935,7 @@ void FileCatalog::deleteRequested  (std::vector<FileBrowserEntry*> tbe, bool inc
 
     if (msd.run() == Gtk::RESPONSE_YES) {
         for (unsigned int i = 0; i < tbe.size(); i++) {
-            const auto& fname = tbe[i]->filename;
+            const auto fname = tbe[i]->filename;
             // remove from browser
             delete fileBrowser->delEntry (fname);
             // remove from cache
````
as trying not to copy `filename` resulting in using a cleared file name later in the code... :-\

**Comment by heckflosse** [comment]
Thanks for fixing it :)
