### ISSUE TITLE
Preview image jumps around on canvas while zooming

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3182]
If you zoom all the way in and out with the mouse scroll-wheel while the cursor is over the canvas, not over the image, the image will start jumping about the canvas at some point. The zoom % shown is also incorrect, which is probably the cause of the image jumping around. For example the preview image's size stopped shrinking at 6% as I zoomed out but the % kept shrinking all the way down to 1%.

Screencast from someone in the forum:
http://filebin.net/owe0qd81iq
https://discuss.pixls.us/t/gtk3-4-2-787-zoom-center-problem/935/8?u=diego_maradonna

**Comment by Hombre57** [comment]
Should be fixed by commit f36565c. If so, please close this issue.

**Comment by Beep6581** [comment]
The fix mostly works, but there is still a centering oddity:
If the image fits-to-window at 25% and I hold the cursor outside the image over the canvas in the top-right corner and zoom out with the mouse scrollwheel, the image shrinks "towards" the cursor at 20%, 16% and 14%. Then at 12% is starts shrinking away from the cursor towards the center. Now that I think about it, maybe the "virtual canvas" size limit was reached and that is why it appears to shrink towards the center?

What do you think about making the image zoom in or out not centered around the cursor but around the middle of the canvas when the cursor is not over the image?
I imagine it would work well for zooming out, but not for zooming it, because the moment you zoom in to a point where the image appears under the cursor it would start zooming centered around the cursor and not around the screen center, which is not what you want when pushing the mouse scrollwheel up a few clicks. But just a thought.

**Comment by Hombre57** [comment]
That's how the new preview works : it zoom in/out centered on the mouse location, but to avoid having unlimited panning, I've introduced an "anchor" in the mechanism, which is a point which is located at the center of the preview area. If you zoom out to 10% or 5% and then pan the image, you'll notice that the center of the preview area is limiting the panning.

Please don't ask me to enable more panning while zoomed out, it was already quite difficult for me to put this in place.

> What do you think about making the image zoom in or out not centered around the cursor but around the middle of the canvas when the cursor is not over the image?

I think it would be counter intuitive, for the reason you explained :point_up:

**Comment by Beep6581** [comment]
Then :+1: for closing.
