### ISSUE TITLE
Use gtk3 as the new default branch

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3184]
This issue is to decide when to branch the `master` branch off into `gtk2`, and to merge the `gtk3` branch into `master`. We could do it as soon as every active developer gives an "ok". Current active developers: @adamreichold, @heckflosse, @Hombre57, @Desmis, @atorger. Does everyone agree? I will notify the package maintainers once we all agree

**Comment by heckflosse** [comment]
As soon as I merged my open branches, I'll give my ok.
I want to complete these before:
branch 'cacorrect'
branch 'cbdlbw'
branch 'retinexgain'

Ingo

**Comment by Desmis** [comment]
No problem, I'll look that in approximately 3 weeks :)

**Comment by adamreichold** [comment]
I agree to do this.

**Comment by Hombre57** [comment]
I agree too.

Since we have 3 weeks left, I'll have time to commit my patches.

**Comment by atorger** [comment]
Agree! Great work with GTK3!

**Comment by heckflosse** [comment]
branch 'cbdlbw' is pushed to master
branch 'cacorrect' has some merge conflicts, which should be solvable
I'll try to complete branch 'retinexgain' next days.
When that is done, I'm ok to swap master and gtk3

Ingo

**Comment by Hombre57** [comment]
@heckflosse  With or without the watermarking feature ? I can strip it out and make it a separate tool myself if you don't have time for this.

**Comment by heckflosse** [comment]
@Hombre57 I meant 'retinexgain', not 'newwavelet'. But maybe it's better to strip out watermarking from 'newwavelet' and then I make the modifications to 'newwavelet' because iirc 'newwavelet' contains 'retinexgain'. If it does not contain 'retinexgain' I will include it after you stripped out watermarking.

**Comment by Beep6581** [comment]
Making "gtk3" the new main branch would simplify things and let me go for walks in the forest again instead of merging. If we do that, I would rename "master" to "gtk2". But I just merge, I don't code, so please vote whether you feel the time is right to start committing directly to "gtk3".

**Comment by Hombre57** [comment]
As of now, I'm ok to let gtk3 be the new master, but I'll wait @heckflosse 's position to give a final vote.

**Comment by heckflosse** [comment]
I'm not against being gtk3 the new master. But we should merge all the open branches before and also ask @Desmis, @Floessie and @iliasg

**Comment by Desmis** [comment]
No problem for me :)

**Comment by Floessie** [comment]
If the plan still is to branch `master` off into `gtk2` and then `gtk3` into `master`, I'd say: Go for it!

**Comment by Beep6581** [comment]
@Floessie `master` will be branched off into `gtk2`, but I would just leave `gtk3` as-is. git has no need for having a branch called "master", there's only a human factor. Renaming branches could cause confusion down the road, when trying to do things like `git show commit:rtgui/foo.cc` or `git diff branchA..branchB` I think it's not something that would make life easier.

**Comment by Floessie** [comment]
@Beep6581 I didn't mean to rename `gtk3` to `master`, but to merge it into `master` once `master` is branched off into `gtk2`. The human factor is not to be sneezed at. :wink:

**Comment by Desmis** [comment]
@Beep6581 @Floessie @heckflosse @Hombre57 
I just push a branch "newwaveletgtk3"
The conversion work was huge, I spent over 15 hours (or more). And I do not see how we could go faster.
Indeed, many changes have been made - which I do not question. For example :
* FTblockdn.cc
* Wavelet.cc and .h
* ...
In this cases, sspecially for wavelet, git merge was of no help, it was necessary to rewrite everything manually.

For information, before commit, I made a patch: about 2000 K° (the size of wavelet.cc is x 2)

I saved this work because I do not want to lose it. It compiles, but nevertheless at launch the system crash. Obviouly I can't test !
I'll still check why. Probably at the GUI level?
But if I can not, I'll ask for help.

Thank you :)

**Comment by Desmis** [comment]
I have found the bug (ss)...Some sliders were missing in declaration...In fact there are
* 66 sliders
* 12 thresholdadjuster 
* 15 curves
* 23 methods
*  16 expanders

Of course, probably to do some others improvments (history msg...)
And also, test to see if all works well :)
 jacques

**Comment by Desmis** [comment]
@Beep6581 
Another question, which as nothing to do with "newwavelet" !
To find the bug, I tried :  
* Debug version
* with gdb
gdb is installed in mingw64/bin
It start, and after stop. wihout action, but he says to me  "ImportError : No module named libstdcxx.v6.printers"
"Error while executing Python code"
???
Thank you
Jacques

**Comment by gaaned92** [comment]
@Desmis You should use the 64 or 32 gdb.exe available [here](http://www.equation.com/servlet/equation.cmd?fa=gdb) as noted in [compiling/windows](http://rawpedia.rawtherapee.com/Windows).
it is much easier to use.

**Comment by gaaned92** [comment]
@Beep6581 Perhaps you will take the decision not to update and maintain GTK2 branch further.
In this case it will be necessary to advise XP users (if there are still some) that XP is no longer supported.
We will have  to change WinXP_32 in WinVista_32 in the build names.

**Comment by Beep6581** [comment]
@Desmis I'm happy you rescued the work - I enjoyed that branch the last time I tried it, though even then it needed some bugfixing and cleanups.
I can't help with Windows problems unfortunately.

**Comment by Beep6581** [comment]
@gaaned92 that's not a problem.

**Comment by Beep6581** [comment]
> I'm not against being gtk3 the new master. But we should merge all the open branches before

Branches with GTK3 support:
- newwavelet/newwaveletgtk3
- locallab/locallabgtk3
- pixelshift/pixelshift_gtk3

Branches for master:
- spot-removal-tool
- var-tracking
- denoise_uniform
- colourtoning
- SaveStrategy
- gammadif
- xmp

Of the branches for master, only denoise_uniform and possibly colourtoning are ones we will want to merge before switching. I don't know what var-tracking is about - @Floessie is it for deletion? As far as I know, the remaining branches are either incomplete or very outdated thereby not playing a role in this decision.

So the plan is to make the switch when these two branches are merged. Anyone opposed?

**Comment by Floessie** [comment]
@Beep6581 `var-tracking` was merged with 56dbfe1e5f6a066c6d09da36479c5e75832df694. I'll delete it. Meanwhile I created `imdim_cleanup` for `master`.

**Comment by Desmis** [comment]
@gaaned92 

Thank you, it work :)

**Comment by Hombre57** [comment]
I'll port spot-removal-tool to the Gtk3 branch on my side, and perhaps SaveStrategy in the future.

I'll test again the 2 branch you want to commit this w.e. and will answer your poll by Sunday.

**Comment by Beep6581** [comment]
The new default branch is called `dev` and uses GTK3. The branch which uses GTK2 is called `gtk2` and is no longer supported. Refer to #3660 for more info.
