### ISSUE TITLE
Missing labels in CA removal tool

### ISSUE THREAD

**Issue by da-phil** [Beep6581/RawTherapee#3190]
In commit 51de80b558c73db9b79fb76f0f9caff337e0326a the following labels have been removed and are therefore missing in the GUI now:
- `TP_CACORRECTION_BLUE`
- `TP_CACORRECTION_LABEL`
- `TP_CACORRECTION_RED`

**Comment by heckflosse** [comment]
Oh, that was me. Looking

**Comment by heckflosse** [comment]
@da-phil Thanks for reporting this bug so quickly :+1:
