### ISSUE TITLE
Curves become to big when edit by number is activated

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#3193]
Curves become to big when edit by number is activated.
This happens, if more than two entry fields are showen.
I suggest to use 2 lines for the entry fields.

![unbenannt](https://cloud.githubusercontent.com/assets/13800920/13542489/6bfea27a-e263-11e5-8f6b-124ba19b1ddd.png)

btw: The buttons have a different height.

**Comment by Hombre57** [comment]
Some users prefer having a wide tool panel for having big curve editor, and then prefer having a single line coordinate editor.

What if the spin buttons were flowing automatically ?

**Comment by TooWaBoo** [comment]
Flowing automatically sounds good. +1

**Comment by Hombre57** [comment]
Fixed in the new flowing-curve-edit-axis branch. I'd like to commit tomorrow if no objections.

**Comment by Beep6581** [comment]
Builds and looks good!
Would it be possible to make the spinboxes float left, so that there is no big gap between each label and its respective spinbox?
http://i.imgur.com/zzlFJv7.png

**Comment by Hombre57** [comment]
Which one do you prefer ?

N°1:
![solution1](https://cloud.githubusercontent.com/assets/13788115/13731729/8cd06524-e970-11e5-9b35-15bff2cdaf25.png)

N°2:
![solution2](https://cloud.githubusercontent.com/assets/13788115/13731730/8e8ed5b2-e970-11e5-9e01-f36022cf9f7f.png)

**Comment by Hombre57** [comment]
I vote for N°2.

**Comment by heckflosse** [comment]
N°2 for me

**Comment by michaelezra** [comment]
N2

**Comment by Hombre57** [comment]
Solution 2 committed, merging to gtk3 now and closing this issue.

**Comment by Beep6581** [comment]
N°2, thank you :]
