### ISSUE TITLE
Double-clicking on a folder should expand it in the treeview if it contains subfolders

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3198]
The treeview, at least in `gtk3` in Linux, has two active parts: the triangle, and the folder name with the folder icon.

The triangle only supports single-click events and it expands the folder if it contains subfolders. That's good. Could someone verify that it's working correctly in Windows? I ask because of https://discuss.pixls.us/t/need-some-help/963/7

The folder label and icon on the other hand support the double-click event, which loads the folder and shows the thumbnails in the file browser. What it should also do is the same as single-clicking on the triangle does - it should expand the folder in the treeview to show the subfolders (if the folder contains any). Currently I double-click on a folder to show the thumbs, but if the folder contains subfolders then there is no indication of that unless I then click on the triangle.

To demonstrate:
I double-clicked on this folder http://i.imgur.com/ikvG8aW.png
It loaded the thumbnails of the photos from that folder, but does it contain subfolders? Who knows? One must then click on the triangle to find out http://i.imgur.com/3pVZ3Eg.png

This bug or shortcoming is in `gtk3`, I haven't checked `master`.

**Comment by gaaned92** [comment]
In master, double click on folder doesn't expand it. You must click on triangle.

**Comment by Beep6581** [comment]
So double-click on the folder should also fire the same event as clicking on the triangle does, in both Gtk+ 2 and 3.

**Comment by Beep6581** [comment]
This is a test, ignore this.

**Comment by Beep6581** [comment]
Over the last months there has been a recurring packaging problem with the file browser arrows missing. If this feature was implemented (I tried and gave up, don't understand GTK+ signals yet) missing arrows would be less of a problem. I'm also using that as an excuse to bump the issue :)

**Comment by gaaned92** [comment]
@Beep6581  if the folder contains raw images and subfolders,  presently double click permits to display the raw.
If now it expands the folder, how we can display the raw files?

**Comment by Beep6581** [comment]
Still valid.
