### ISSUE TITLE
New OS X 10.10 and 10.11 builds needed

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3201]
Hey @ion12 and @helmi03 ! I was waiting for a moment when we finish merging many of the branches, and this happened the other day. Could I ask you to make new builds? Of course there are more merges coming, but now is a great time to make new builds, and then again in a month when we switch the default branch to `gtk3`.

**Comment by ion12** [comment]
release:
https://drive.google.com/open?id=0B8oSq7opQwfFSjBNNE9pWlZlVVk
debug:
https://drive.google.com/open?id=0B8oSq7opQwfFZ3BIbWRzVzBCMDg

Not sure what you decided for the DMG naming convention in the end but for now you can just rename the .zip file, it won't affect the .app itself

**Comment by Beep6581** [comment]
Thanks! I'll upload tomorrow, too tired now.

**Comment by Beep6581** [comment]
Uploaded.
