### ISSUE TITLE
Tool names not aligned evenly

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3203]
All boxes containing tool names and their enable/disable buttons or expander icons in Detail and Wavelet are aligned the same way, with consistent spacing between each other and indentation from the left.
All tools in Exposure, Color, Transform and Raw are aligned the same relative to each other but different to Detail and Wavelet, except for Tone Mapping and Preprocessing which are both nudged to the right.
http://i.imgur.com/1YfI8Gh.png

**Comment by Hombre57** [comment]
Fixed in commit 7f0a96e. Closing.

**Comment by Beep6581** [comment]
Fix confirmed.
