### ISSUE TITLE
Preferences - Color Management - standard monitor profile disappears

### ISSUE THREAD

**Issue by VolkerLerch** [Beep6581/RawTherapee#3204]
Raw Therapee Version 4.2.745
German language
Opensuse leap 4.2

In preferences --> color management, I choose my ICC profile directory (which is in my case /home/my_user_dir/.local/.../icc ).
I then select my own standard monitor profile. After selection, it is being displayed in the preferences mask.
![color_management](https://cloud.githubusercontent.com/assets/17731554/13616442/46a014ea-e57a-11e5-9571-a96fa37f5c1f.png)

I close the window by pressing 'ok'. No error message is displayed.

Next time when I open this window, the standard monitor profile is not provided any more. Instead, it shows 'no color profile'.

Also on the main window, I cannot select the color profile either.
All other pre-defined color profiles 'RT_*' are selectable.

**Comment by reggybe** [comment]
Doesn't happen with openSUSE 13.2, same RT version. Can you take a look in your options file in .config/RawTherapee under Color Management if it is written there?
