### ISSUE TITLE
Resize crop area borders need wider

### ISSUE THREAD

**Issue by IC7K** [Beep6581/RawTherapee#3205]
need wider area in 2-3 of current width, where cursor have "resizing" type, because difficult to catch borders for resize with mouse

more info here [https://discuss.pixls.us/t/resize-crop-borders-need-more-wider-how-to/987/13](url)

thanks all!

**Comment by Hombre57** [comment]
This is a minor change, so if you're okay with the new detection area (doubled), I'd like to commit tomorrow.

**Comment by heckflosse** [comment]
I'm ok with the change though would have chosen 8 instead of 12. But :+1: for commit

**Comment by Hombre57** [comment]
Changing from 6 to 8 would not make a big change. Why not using 9, which is the mean of 6 and 12 ?

**Comment by heckflosse** [comment]
@Hombre57 : +1 for 9

**Comment by Hombre57** [comment]
Branch enlarged-crop-borders rebased with the new width of 9px and merged into master. Closing this issue and deleting branch.
