### ISSUE TITLE
Paste button is missing in curves

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#3207]
Paste button is missing in curves when "Custom" is selected.
Buttons have different height.

![unbenannt](https://cloud.githubusercontent.com/assets/13800920/13684705/372ad1fa-e70d-11e5-8f23-e8189c763486.jpg)

**Comment by Hombre57** [comment]
Fixed in commit e0d1004. Closing.

**Comment by Beep6581** [comment]
Missing button fix confirmed.
The icon containers still vary in size though http://i.imgur.com/vrWB8qs.png

**Comment by Beep6581** [comment]
+1 for separation between the icon groups, I found that helpful.
