### ISSUE TITLE
Not working on Linux Mint 17.3

### ISSUE THREAD

**Issue by a-r-taylor** [Beep6581/RawTherapee#3210]
Hi,

Installed the Ubuntu version of Rawtherapee using the PPA. It installed without issue, but when I run the program, it appears on screen for a fraction of a second before quitting. There are no error messages that show.

Still a Linux newb so all help is appreciated.

Cheers.

**Comment by Beep6581** [comment]
Hey

If you run into a problem, you need to provide specifics: what version of Ubuntu, what PPA, what version of RawTherapee, etc.
http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports

**Comment by a-r-taylor** [comment]
Hey,

Thanks for the response.

OS: Linux Mint 17.3 XFCE 64bit
PPA: ppa:dhor/myway -- as per the website
Version: 4.2-4dhor~trusty -- according to Software Manager

As mentioned, it does not stay on screen long enough for any information. 

Thanks.

**Comment by Beep6581** [comment]
Ok, first try installing the "unstable" version or whatever it's called there, perhaps "rawtherapee-unstable". If that crashes too, try to install the "debug" version, then follow the link I sent to get a stack backtrace. It sounds complicated but I assure you the instructions are clear and easy to follow, I just can't give the exact package name you must install as I don't use Ubuntu or anything similar.

**Comment by Beep6581** [comment]
Stale, lacks info, closing.
