### ISSUE TITLE
Histogram is wrong when "No ICM: sRGB Output" is selected

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#3213]
RT 4.2.849 Gtk3, Win 10 x64
1. Open an image and apply "Neutral"
2. Check in Preferences, if "Use working profile for main histogram and navigator" is **unchecked**.
3. Switch "Output Profile" between "RT_sRGB" and  "No ICM: sRGB Output".

Histograms "No ICM: sRGB Output" should look close to "RT_sRGB", but it doesn't.

![unbenannt](https://cloud.githubusercontent.com/assets/13800920/13727457/96bad2f4-e8f3-11e5-80cc-d0d8d7103602.png)

**Comment by mmmtok** [comment]
Hi, 

I have just created #3283.  I think it can be the fix for this also.
