### ISSUE TITLE
RT 4.2.1 for Windows Installation Failed 

### ISSUE THREAD

**Issue by DigitalReload** [Beep6581/RawTherapee#3216]
installed RT 4.2.1 for Windows Vista/7/8/10 64-bit (Branch: default), 2014-10-25 05:51 ( most recent stable )

Failed to start from installer and failed to start from menu.

I get a windows message rawtherapee has stopped working.
A problem caused the program to stop working correctly. Windows will close the program and notify you if a solution is available.

I am using Avast antivirus (paid version) I disconnected avast for 10 mins for the install.

Help is appreciated

**Comment by Beep6581** [comment]
4.2.1 is old and unsupported.
Get the latest development version:
http://rawtherapee.com/downloads

Follow this guide if you run into any issues:
http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports
http://rawpedia.rawtherapee.com/How_to_fix_crashes_on_startup

**Comment by DigitalReload** [comment]
Many Thanks.

 

Installed and working.

 

I am a Lightroom user with some Photoshop experience. I am attracted to deconvolution sharpen & focus solutions.

 

I am pleased to discover RT and look forward to the technique and opportunities offered.

 

Regards Edward
