### ISSUE TITLE
Windows license text in setup - wrong encoding

### ISSUE THREAD

**Issue by Krzysiu** [Beep6581/RawTherapee#3218]
Hello! It's very minor, yet still I'm letting you know. The setup of build 4.2.849 (maybe other as well, I wasn't looking at this earlier) on Win7 64 have UTF-8 license text, yet encoding is wrong, so it starts with "Copyright Â©2004-2012 GĂˇbor HorvĂˇth".

**Comment by sguyader** [comment]
Yes it happens in older builds too.

**Comment by Beep6581** [comment]
Please let me know if it's fixed.

**Comment by sguyader** [comment]
Yes it's fixed. I noticed that the field in the "Version" tab is empty.
