### ISSUE TITLE
Neutral doesn't reset Tint slider

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3219]
I got the files from https://discuss.pixls.us/t/white-balance-offset-for-ir-work/1045/5
Using latest `gtk3`, I opened it in the Editor tab, applied Neutral, and the tint slider did not reset, it remained at 5.000.
This is a small bug but with major consequences, could someone take a look? Else I'll try to take it tomorrow.

**Comment by heckflosse** [comment]
@Beep6581 I don't think it's a bug. Set Tint to 1000 and apply Neutral => tint is set to 5000

**Comment by Beep6581** [comment]
The tint was calculated as the default/neutral value for that image? I see that's what happens with other images.

**Comment by Beep6581** [comment]
Closing this, see #3221
