### ISSUE TITLE
Multiple bugs with White Balance Temp and Tint sliders

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3221]
Create several copies of the same image, `amsterdam.pef` in my example. Apply Neutral to all of them.
1. If you look at one of them from the File Browser, the White Balance Temp and Tint starts off in the "Camera" position showing e.g. `6504` `1.000`. Open that photo in the Editor, you get `6112` `1.168`. Check it in the File Browser, it still shows `6504` `1.000`.
2. Apply Auto White Balance to one of them from the File Browser, it shows `5772` `0.936`. Open it in the Editor, you see `6504` `1.000`.
3. Go to the next image, it should be in the "Camera" method position, showing `6112` `1.168`, because you applied Neutral in the beginning. Apply Auto from the Editor, now you see `5640` `0.859`. Reload the same image from the File Browser or Filmstrip, now the Editor shows Auto `6504` `1.000` BUT that's not what the preview uses. The image in the preview is in fact using `5641` `0.859`. Change either temp or tint and go back in history, now the temp and tint sliders will show `5641` `0.859`.
4. I'm not sure whether applying Neutral behaves correctly regarding the Temp and Tint sliders.

I would call this above-average priority because it means the White Balance tool is broken when not used from the Editor, and of all the tools in RawTherapee White Balance is one of the most likely tools to be used from outside the Editor.

**Comment by heckflosse** [comment]
Fixed with #3689
