### ISSUE TITLE
Crash when clicking on the hand tool butten

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#3222]
RT 4.2.849, Win 10 x64
Crash when clicking on the hand tool butten in the file browser tab.

![unbenannt](https://cloud.githubusercontent.com/assets/13800920/13797981/f35024d6-eb11-11e5-87bf-ff56e221d704.PNG)

1. Quit RT, if it's running.
2. Run RT
3. Click on the hand tool button
--> Crash

**Comment by heckflosse** [comment]
Works fine here. Maybe related to gtk3...

**Comment by heckflosse** [comment]
Confirm crash in gtk3 branch (4.2.879)

**Comment by Beep6581** [comment]
Cannot reproduce in Linux
Commit 570bd07
Gtk+ 3.18.7

**Comment by dngimage** [comment]
I confirm the crash running RawTherapee_WinVista_64_4.2.849-gtk3.

**Comment by heckflosse** [comment]
Here is a [bt full](http://pastebin.com/RGZ5WgcF)

**Comment by heckflosse** [comment]
Don't know why it doesn't crash in master branch, but I'll fix it there too
