### ISSUE TITLE
Performance issue with gtk3 branch

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#3223]
Start time of gtk3 branch is much longer then start time of master (gtk2) branch.
That's not a big problem, because usually one starts rt and processes a lot of pictures.
But when I open a file in METM, using gtk3 branch needs about 650 ms more (on my 4Ghz machine) than master (gtk2) branch. And it needs that additional time for each file I open when I'm in METM mode. 650 ms is more than the amaze demosaic time of an 36 Mp NEF on my machine. Why the hell do I speed up image processing when new gtk3 gui eats all of the improvements?

Ingo

**Comment by heckflosse** [comment]
I found one reason for the slowdown when opening editor in metm using gtk3 branch. It's the Gtk::FileChooserButton. Each incarcation of it adds about 50 ms to the time needed to open an editor tab. We have four of them (flatfield, darkframe, colour management and lens profile) which sum up to 200 ms. The only way to work around this is to use the same mechanism as in CurveEditorSubGroup::inputFile where the FileChooserDialog is created on demand and not a priori.

**Comment by michaelezra** [comment]
Ingo, thanks for such scrutinizing work! It is worth it making this change:)

**Comment by heckflosse** [comment]
@michaelezra Michael, for SETM it's absolutely no issue because rt only needs a bit more time to start, but in METM I find the delay quite annoying (opening an editor in METM using gtk3 needs about 650 ms more than doing the same using gtk2)

**Comment by Hombre57** [comment]
I don't know if it's wise to change the FileChooserButton. Perhaps that the slow down is cause by the famous "network:" warning, that will hopefully be solved some day soon ?

If you still prefer to replace them by a custom made FileChoserButton, it won't have the same nice appearance.

**Comment by heckflosse** [comment]
The FileChooserButton already was slow in gtk2 and with gtk3 it got even slower.
I use SETM where that's not an Issue because only time to start rt is affected. If it's not an Issue for users of METM or Dual-Monitor where it slows down every time you open a file, we can close the Issue.

**Comment by Beep6581** [comment]
I asked whether the Gtk+ devs were aware of the problem, whether anyone was working on it and whether any solutions exist:
```
23:16:25   ~Company | i'm not aware of any such work
23:17:18    baedert | I don't see why a patch creating the dialog on click shouldn't be accepted
23:17:41   ~Company | baedert: because the dialog is used to forward all the filechooser interface to
23:17:58    baedert | I now see why a patch creating the dialog on click shouldn't be accepted
23:18:36   ~Company | i totally understand the problem, and I'm all for people fixing it
23:19:23    baedert | otoh writing your own filechooserbutton that does what you want shouldn't be too hard
23:20:13   ~Company | and from the pov of the gtk project developers, it's probably not very high on the list of priorities
23:20:32   ~Company | so what i'm saying is "if you want it fixed, you'll have to do it yourself"
23:21:00   ~Company | yeah, writing your own button is probably a good idea if you create many of them
23:21:27   ~Company | (also, i really really dislike the filechooser interfaces behavior anyway
```

**Comment by Hombre57** [comment]
Hmmm... I'd say it's low on our TODO list too, but that's something you should ask to users.

I've tried Gtk3 in Release build and METM, and it's darn fast ! (Core i7 with plenty of ram but old-school HD).

Again, maybe that it won't take much longer than with Gtk2 if the "netwok:" problem is fixed (just guessing).

Since it affect performance, I'll give the last word to Ingo.

**Comment by heckflosse** [comment]
@Hombre57 I agree about low priority but it's still slow on my Win7/64 with 32GB RAM and a combination of SSD and RAID-0 HD. It has nothing common with speed of mass storage. The point is, that the GtkFileChooserButton creates a FileChooserDialog in background which is only used when you press the button. Currently we have 4 of this buttons (FF, DF, ICM and LCP) and pressing one of them in gui is a rare case in workflow I guess.

**Comment by Hombre57** [comment]
I'll create a custom widget then, but shall I do it in master or Gtk3 ?

**Comment by heckflosse** [comment]
Gtk3

**Comment by Hombre57** [comment]
I've tried to do that patch, but it's beyond my skill (and frankly, that should be assigned to the Gtk dev team...). So I'll let someone else do it, sorry.

**Comment by heckflosse** [comment]
With current dev and latest gtk+ this issue is no longer valid => closing
