### ISSUE TITLE
RT won't read width of toolpanel on startup (Gtk3)

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#3226]
When starting RT bei doubleclicking on an image in the file system, the toolpanel is always set to its minimum width.
It looks like RT is not reading the corresponding setting in the option file.

The history panel works fine.

**Comment by Hombre57** [comment]
Fixed in Gtk3 in commit 644526d, though it affect master as well, but I'm privileging Gtk3 now.

**Comment by heckflosse** [comment]
I pushed the fix to master branch too.

**Comment by Hombre57** [comment]
@Beep6581 @heckflosse Does pushing to both branch cause merge problem ?

**Comment by heckflosse** [comment]
@Hombre57 According to DrSlone it does not

**Comment by heckflosse** [comment]
@Hombre57 : As long as gtk3 is not the new master branch we should fix bugs in master and merge them (the fixes, not the bugs) into gtk3 branch IMHO

**Comment by Hombre57** [comment]
Ok

**Comment by Beep6581** [comment]
I expected pushing the same code to both branches to cause a problem, but commits 644526d1668da833f53811a77de1c7175492693e and 0c786ee1bce8cd2e18d8e6316fb0f04aea3b6d9c caused no problem when merging, so I hope it's safe to do the same here. But until we officially switch to `gtk3` please commit to `master` unless the code is specific to gtk3.
