### ISSUE TITLE
Design gtk3

### ISSUE THREAD

**Issue by Cylo0n** [Beep6581/RawTherapee#3232]
Curve Diagrams are way to big. For example Tone Curves in Exposure section. 
It makes the workflow confusing because of scrolling around in this section.

**Comment by TooWaBoo** [comment]
Can you provide a screenshot please.
To big can be everything. :-)

**Comment by Cylo0n** [comment]
Of Course ;-)

![rawtherapee git](https://cloud.githubusercontent.com/assets/17475103/14060916/9ff7d180-f372-11e5-921e-d523ce9f0408.jpg)

**Comment by TooWaBoo** [comment]
Why have you set the toolpanel so big?
If you reduce the width of the toolpanel the curve diagram becomes smaller.

**Comment by Cylo0n** [comment]
Because i don't want to scroll in Tool Tabs above.

**Comment by Hombre57** [comment]
Curves are square shaped and will remain as is. You can hide curves once you're fine with their edition. Having a large curve area is something I appreciate, to make precise adjustments.

What could be done is to make the curve auto-expanding feature optional (if not already the case).

**Comment by Cylo0n** [comment]
That would be fine. :-)

**Comment by Beep6581** [comment]
@Hombre57 close?

**Comment by Hombre57** [comment]
No time to "make the curve auto-expanding feature optional (if not already the case)". I'll let you decide to close this issue or not.
