### ISSUE TITLE
Consistently crashing when doing distortion correction

### ISSUE THREAD

**Issue by mbaz** [Beep6581/RawTherapee#3233]
RT 4.2.880, 64 bits, on windows 7, official binary.

When editing a JPG file and clicking on the "distortion correction" button, RT consistently crashes.

**Comment by Beep6581** [comment]
@mbaz 
http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports

**Comment by mbaz** [comment]
**Raw Therapee version:**

Branch: gtk3
Version: 4.2.880
Changeset: 4979c0c83604cc489534b39f04bca9199d2ed6c9
Compiler: gcc 5.3.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.18.0
Build type: release
Build flags: -m64 -mwin32 -mthreads -std=gnu++11 -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -msse -msse2 -mwindows -fopenmp -Wno-aggressive-loop-optimizations -DNDEBUG -O3
Link flags: -m64 -mwin32 -mthreads -static-libgcc -mtune=generic -mwindows -s -O3
OpenMP support: ON
MMAP support: ON

**Downloded from:**

http://rawtherapee.com/releases_head/windows/RawTherapee_WinVista_64_Gtk3_Release_4.2.880.zip

**System:**

64-bit Windows 7 Enterprise SP1, intel Core i5-3320M @ 2.6 GHz, 8 GB RAM.

**Steps to reproduce:**

1. Download this JPG file: http://filebin.net/qa8kp2a0qu/IMG_4438.JPG
2. Open RT and open the file.
3. Select the Transform tab, scroll down to Lens/Geometry module, and click the button under "Distortion Correction".
4. RT crashes.

**Other notes**

I have JPGs from a Canon S90 P&S, a Nikon D80, and an Olympus E-PL5. It seems like only files from the S90 cause a crash.

I will try to download a debug version of RT and post a backtrace, but it make take a few days.

**Comment by Beep6581** [comment]
Reproduced in Linux, will provide backtrace later.
Segfaults with "Floating point exception".

**Comment by heckflosse** [comment]
Auto distortion correction works only with raw files. We should gray out the button for tiff, jpeg and png

**Comment by Beep6581** [comment]
Crash not reproducible.

The button is not grayed out for non-raw files yet.
