### ISSUE TITLE
Adding more PENTAX camera to camconst.json

### ISSUE THREAD

**Issue by Hombre57** [Beep6581/RawTherapee#3235]
Here is a file that shows strong purple highlights (ToyBot.PEF) : http://filebin.net/ao1lb7g7sv . It's an old file and that I didn't opened for a while. Just load it and apply Neutral profile.

Setting Raw White Point to 1.01 suppress the purple HL completely.

**Comment by sguyader** [comment]
It happens to me sometimes that highlights turn magenta when trying to reconstruction them with color propagation, or when usinh retinex. Is the raw white point correction a generally good way to correct these magenta highlights?

**Comment by Hombre57** [comment]
D'ont think so, but in the case of this issue, it's probably related to the camconst file for the Pentax K-x body.

I see that PENTAX has only 2 bodies in camconst, partially supported. I'll try to get help on this. I have a K-3 and can have access to K-r (IIRC), so I'll provide the shots.

**Comment by Hombre57** [comment]
Switching this issue to the real problem, which is a lack of Pentax bodies in camconst. This issue will host the progress of collecting values for bodies of this brand. I'll try to collect data by posting a request in a Pentax community forum.

**Comment by iliasg** [comment]
Same issue as https://github.com/Beep6581/RawTherapee/issues/2972
It is again a 4094 WL against the nominal of 4095 
camconst.json item for K-x which will be in the upcoming update. WL set to 4080 for safety in case of larger deviations from nominal (LENR). 

    { // Quality B, per ISO info missing
        "make_model": "PENTAX K-x",
        "dcraw_matrix": [ 8843,-2837,-625,-5025,12644,2668,-411,1234,7410 ], // adobe dcp d65
        "ranges": { "white": 4080 } // nominal at ISO200 4094
    }, 

Waiting for overexposured samples with long exposure noise reduction ON .. it's the worst case as LENR subtracts a black frame and the spead of values at BF (noise) propagates up to the highlights.

**Comment by iliasg** [comment]
Pentax K-x item is included in updated camconst.json https://raw.githubusercontent.com/Beep6581/RawTherapee/d0cef55aada8e51321d44982a2a8ca258eaa6139/rtengine/camconst.json
K-x highlight issue is fixed.
