### ISSUE TITLE
New camera profile for Nikon D7200

### ISSUE THREAD

**Issue by stefan-i** [Beep6581/RawTherapee#3236]
Hi,

I shot my X-Rite Colorchecker 24 with a Nikon D7200 and 85/1.8G lens for both daylight and tungsten illumination. 
The Raw files and dual illuminant profile created with DCamProf 0.10.4 are uploaded here: http://filebin.net/3ukb5naed0

**Comment by Beep6581** [comment]
[Nikon D7200.dcp.txt](https://github.com/Beep6581/RawTherapee/files/232733/Nikon.D7200.dcp.txt)
