### ISSUE TITLE
Intermittent crashes when deleting an image

### ISSUE THREAD

**Issue by MogadonSnowflake** [Beep6581/RawTherapee#3237]
RT 4.2.905 Windows 64 bit running on Windows 8.1. 

In Filmstrip mode, right-click on image and select either _File Operations - Delete_ or _File Operations - Delete with output from queue_.

RT will crash ~50% of the time when using these deletions methods with the Windows message "This program has stopped working..."

**Comment by Beep6581** [comment]
Please get the "Debug" build and provide a stack backtrace.
http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports

**Comment by MogadonSnowflake** [comment]
RT 4.2.905 for Windows Vista/7/8/10 64-bit - debug
Uploaded by DrSlony on 2016-04-01 09:14
Branch: gtk3
Downloaded from: http://rawtherapee.com/downloads

In Filmstrip mode, left-click on the gear cogs to add the image to the queue, right-click on the gear cogs and select _File Operations - Delete_.

Screenshot: 
<a href="http://photobucket.com/" target="_blank"><img src="http://i574.photobucket.com/albums/ss189/sgb32/RTDeleteBug_zpsnfnmiazi.jpg" border="0" alt=" photo RTDeleteBug_zpsnfnmiazi.jpg"/></a>

Stack backtrace attached.

Regards

Steve
[log.txt](https://github.com/Beep6581/RawTherapee/files/200214/log.txt)
