### ISSUE TITLE
DCP profile for the Fujifilm X-T1

### ISSUE THREAD

**Issue by sguyader** [Beep6581/RawTherapee#3243]
Hi,
Yesterday I received my new X-Rite Colorchecker Passport, and went outside to shoot the target for profiling. Following the instructions on Rawpedia, I shot the target under the sun (there was a very slight overcast), putting a black cloth around the target to avoid any potential reflections from the surroundings.
I then used DCamProf 0.10.4 to generate a dcp profile, using the following commands:

``scanin -v -dipn daylight.tif /usr/share/argyllcms/ref/ColorChecker.cht /home/sguyader/Téléchargements/dcamprof-0.10.4/data-examples/cc24_ref.cie /home/sguyader/Téléchargements/dcamprof-0.10.4/daylight-diag.tif``

``./dcamprof make-profile -i D50 -C daylight.ti3 daylight.json``

``./dcamprof make-dcp -t acr -n "Fujifilm X-T1" daylight.json "Fujifilm X-T1 daylight DCamProf.dcp"``

Notice I used the ``-t acr`` to include an ACR tone curve into the profile.

Here's the link to download the raw file and the different generated files for review and diagnosis: http://filebin.net/94oml57m7n

Comparing this profile with the one recently included in RT, I think both are quite close when the Tone curve is disabled. However, the tone curve included in my profile seem to have less contrast and is less prone to clipping, which may be preferable (but correct me if I'm wrong).

If I can improve the anything in the shooting conditions, please let me know. I'll also try to find a tunsgten bulb to add this lighting condition to the profile.

**Comment by Beep6581** [comment]
Hey

Could you include a tungsten shot too? Using a real and not tinted tungsten bulb.

**Comment by sguyader** [comment]
Hi, yes I'm planning to do it. I found a regular tungsten bulb, and I'll
try to make some shots soon.

**Comment by Beep6581** [comment]
I found that my basement and bathroom (both with white walls) produced identical tungsten DCPs.

**Comment by sguyader** [comment]
Hi @Beep6581 I made a tungsten shot last night, with a regular tungsten bulb, in a bedroom with white walls.
Here are all the files for you to check: http://filebin.net/r8qyc8jozj

Let me know if I can improve something in the shooting conditions.

**Comment by Beep6581** [comment]
Great! Flooded with work today, I'll check it in tonight or within the next few days.

**Comment by Beep6581** [comment]
[Fujifilm X-T1.dcp.txt](https://github.com/Beep6581/RawTherapee/files/232727/Fujifilm.X-T1.dcp.txt)

**Comment by sguyader** [comment]
@Beep6581, thanks! Did you check the profile I had made? Was it not good enough?

**Comment by Beep6581** [comment]
It ended up being visually identical.
