### ISSUE TITLE
Fit crop to screen doesn't work as expected anymore

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#3249]
To reproduce:
Open image
apply crop
pan the preview so that only part of the crop is visible
Alt-f to 'Fit crop to screen'
Expected behaviour (tested with old version 4.2.487) : Crop is zoomed to fit into preview area and is centered to preview area
Behaviour in master branch: Crop is zoomed to fit into preview area (correct) but is not centered to preview area (wrong)

@Hombre57 May that be related to your pan changes sometime ago ?

Ingo

**Comment by Hombre57** [comment]
Certainly. I'll look at it tomorrow, if I can downgrade to Gtk3.18.0 :-/

**Comment by Hombre57** [comment]
Fixed in commit 3ac59ad.
