### ISSUE TITLE
GTK3 Graphs not refreshing 

### ISSUE THREAD

**Issue by Tilo15** [Beep6581/RawTherapee#3250]
Hello,
The histograms and custom curve graphs aren't refreshing properly in the GTK3 version of RawTherapee. The new information gets drawn over the old information making it impossible to actually use the curves and histogram as shown in the attached image.
![screenshot from 2016-04-10 21-50-17](https://cloud.githubusercontent.com/assets/11801324/14409417/e7b81bba-ff66-11e5-8dcc-df8c39627cd7.png)

Thanks,
Tilo15

EDIT:
Thought I should add some more information,
I am using RawTherapee on Fedora 23 with Gnome shell 3.18.2
rawtherapee-gtk was installed using RawTherapee's repo, not Fedora's

**Comment by Hombre57** [comment]
Could you select a theme in Preferences ? Does it help ? Do you have similar issue with Cage Control curve ?

**Comment by Hombre57** [comment]
Discussion continues in #3251.
