### ISSUE TITLE
Speedup for Flat-Field correction

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#3253]
Issue opened to get an Issue number. I'll post first speedups tomorrow or after the weekend

**Comment by heckflosse** [comment]
I analyzed the flat-field processing. There are some things I can speed up:
1.) this [condition](https://github.com/Beep6581/RawTherapee/blob/master/rtengine/rawimagesource.cc#L2993) always evalueates for the first case, which means we can remove it. 
2.) When using flat-field correction, usually in one rt session the same flat-field will be used for more than one file. That could lead to the following optimization: currently when using ff [this loop](https://github.com/Beep6581/RawTherapee/blob/master/rtengine/rawimagesource.cc#L2954) will be executed for each apply of the same ff to different shots. This can easily be moved to the flat-field store, meaning it would only be applied once per rt session and flat-field file.
3.) There are two loops [this one ](https://github.com/Beep6581/RawTherapee/blob/master/rtengine/rawimagesource.cc#L2650) and [this one](https://github.com/Beep6581/RawTherapee/blob/master/rtengine/rawimagesource.cc#L2704) which can be optimized by about factor 2

Ingo

**Comment by heckflosse** [comment]
I created [a new branch](https://github.com/Beep6581/RawTherapee/commits/flatfield_speedup) with the optimizations mentioned above and some more too....

**Comment by heckflosse** [comment]
Speedup is about 35% for ff type area without auto-clip-control, 25% for ff type area with auto-clip-control and double speed for ff type hor+vert.

Ingo

**Comment by heckflosse** [comment]
I want to add some words to what I changed:

1. there was a loop in ff processing which was executed each time a ff was applied to a raw file even if the result of this loop was the same each time. I moved that processing into the ff store causing it to be applied only once per session and ff
2. I optimized code using SSE and some other techniques
3. I optimized L1 cache usage

**Comment by michaelezra** [comment]
Ingo, thank you!

**Comment by heckflosse** [comment]
@michaelezra Hi Micheal, may I ask which ff blur type you use and why? Just for curiosity.

Ingo

**Comment by michaelezra** [comment]
Hi Ingo, I am only using the blur type 'Average' . The other types were created for correction of sensor nonuniformities for either vertical or horizontal readouts or both. As I recall, this was inspired by some of the earlier Canon sensor issues.
