### ISSUE TITLE
Panasonic DMC-FZ1000 lens distortion correction

### ISSUE THREAD

**Issue by HJarausch** [Beep6581/RawTherapee#3254]
Hi,
I'd like to use Rawtherapee but I can't since the support for my Panasonic Lumix DMC-FZ1000 is disappointing. For photographs at short focal lengths the lens correction is suboptimal.
E.g., Darktable does a better job but isn't perfect, as well.

Before dismissing Rawtherapee altogether I'd like to patch it to use the lens parameters which are embedded in the raw file - as does Lightroom.

I don't fear C(++) programming but I'd need some help where to start.
Furthermore, I'd like to use a wide angle converter which requires even different parameters which I do not know, yet.

Many thanks for any help,
Helmut

**Comment by Beep6581** [comment]
Hey

It will be difficult for anyone to point you where to start as you haven't clearly described where the problem lies, haven't described what you tried and haven't provided a sample raw file.

I would say start here:
http://rawpedia.rawtherapee.com/Lens/Geometry#Lens_Correction_Profile
http://rawpedia.rawtherapee.com/Lens/Geometry#Distortion_Correction
http://rawpedia.rawtherapee.com/How_to_get_LCP_and_DCP_profiles
http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports

**Comment by benuri** [comment]
I think that Helmut would like to get the built-in lens profile embedded into the RAW files.
As far as I understand, this is not something the RT does for any camera, except the ability to fit a lens correction function from the JPEG preview embedded in the RAW file.

The problem of finding out the lens correction parameters embedded into the RAW by the camera, is not specific to RT, and requires some reverse-engineering of the file format.

EXIFTool, DNG SDK and DNG Converter are very good tools to start with if you do want to find which fields in the RAW files affect the lens correction and how to interpret them.

**Comment by HJarausch** [comment]
Thanks!
Unfortunately this is no Lens Correction Profile from Adobe since Adobe does extract this information from the raw file as I'd like to do with RT.
The embedded lens correction parameters have been digged out by Raphaël Rigo - see
https://syscall.eu/#pana
Since more and more modern cameras - at least bridge cameras - are using this technique, it would be worth while to add this feature to RT.
I haven't looked at the code, yet, but I assume it first reads the EXIF info to determine the model of the camera.
Then it looks up its own lens correction parameters in its internal database.
At this point one could check if this camera does embed these parameters in the raw file and at which positions. Then one could extract these parameters and apply the corresponding lens corrections.

I've just hoped somebody who knows the source well could tell me starting point where such a modification could be applied. I'd first do it for FZ1000, but later on one could think about some external format of an xml based 'database' which contains the information about the embedded parameters.

**Comment by Beep6581** [comment]
Now I understand. This is a request for direct support of the a, b and c distortion coefficients.

> Unfortunately this is no Lens Correction Profile from Adobe since Adobe does extract this information from the raw file as I'd like to do with RT.

Adobe does not extract LCPs from raw files. Adobe creates their own LCPs. The links I pasted explain where to get LCPs and how to make your own. What https://syscall.eu/#pana describes has nothing to do with Adobe's LCP. He does extract the a, b and c distortion parameters, which are universally used for distortion correction, and so are used in LCPs too, but they are not an LCP, so let's not confuse things.

That article is from 2011. The solution most beneficial to everyone would be if extraction of those parameters was supported by exiv2 or exiftool. I checked three random RW2 raws from imaging-resource using exiftool-10.14 and it had no trouble extracting this:
```
exiftool -G -s -a -m -u -args YP1240041.RW2 | grep -ia distortion
-PanasonicRaw:DistortionParam02=0.011627197265625
-PanasonicRaw:DistortionParam04=0.315673828125
-PanasonicRaw:DistortionScale=1
-PanasonicRaw:DistortionCorrection=On
-PanasonicRaw:DistortionParam08=0.0587158203125
-PanasonicRaw:DistortionParam09=0.010986328125
-PanasonicRaw:DistortionParam11=-0.186798095703125
-PanasonicRaw:DistortionN=3288
```

RawTherapee does not currently allow the user to enter the a, b and c distortion coefficients, but I suppose it uses them internally as LCP files use them. It would be nice if there was support for entering them.

**Comment by HJarausch** [comment]
On 04/20/2016 07:29:23 PM, Beep6581 wrote:
> Now I understand. This is a request for direct support of the a, b  
> and c distortion coefficients.

>> Unfortunately this is no Lens Correction Profile from Adobe since  
>> Adobe does extract this information from the raw file as I'd like to  
>> do with RT.

> Adobe does not extract LCPs from raw files. Adobe creates their own  
> LCPs. The links I pasted explain where to get LCPs and how to make  
> your own.

Unfortunately, this doesn't work. Adobe doesn't have an LCP for the  
FZ1000. I've tried to get one myself and I have asked others.
So, Adobe must extract any information for processing the RAW file from  
the RAW file itself.

Thanks,
Helmut

**Comment by Beep6581** [comment]
The posts above include information on how to create your own LCPs and how to extract the a, b and c distortion coefficients from DMC-FZ1000 raws using exiftool for which the source code is readily available.
RT's distortion correction is handled for example here:
https://github.com/Beep6581/RawTherapee/blob/master/rtengine/iptransform.cc#L718

I'll close this issue, feel free to open a new one if you start working on a patch.

**Comment by greenoid** [comment]
An existing Adobe Lens Profile (LCP), or a hand crafted LCP, or the integrated distortion parameter from the panasonic raw file would not help in RawTherapee at the moment because:
- when LCP is converted in Lensfun format, it would have to use the model "acm". This is only understood by Lensfun version 2 xml format. RawTherapee does include Lensfun in version 3.2.0 which does not support version 2 files. This is output by RawTherapee with every new start on the console as a warning.
- Panasonic embedded distortion correction parameters adhere to the Adobe Lens Correction Model or an internal Panasonic lens correction profile but definitely not the hugin lens distortion correction profile as I have learned by trying.
[deleted, thanks @heckflosse]
- so the only solution today are handcrafted hugin parameters from lensfun, which dont't exist for many models yet.

**Comment by heckflosse** [comment]
> RawTherapee uses RawSpeed to read the raw files

That's wrong
