### ISSUE TITLE
Incorrect focal length for Pentax K100D Super

### ISSUE THREAD

**Issue by geoderix** [Beep6581/RawTherapee#3255]
For all files (both .pef and .jpeg) from Pentax K100D Super Rawtherapee shows incorrect value for the focal length. More precisely, for all images Rawtherapee shows the focal length 250 mm.
This bug does not give the possibility to use .lcp profile for lens correction.
Other programs (FastStone, XnViewMP etc) show the correct focal length.
I found the bug in the RT 4.2.781 for Windows XP and in RT 4.2.905 for Windows Vista/7/8/10 64-bit.
Sample files from Pentax K100D Super (.pef and .jpag) can be downloaded from here: http://filebin.net/la42em8f3l
Thank you.

**Comment by Beep6581** [comment]
Confirmed.

**Comment by Beep6581** [comment]
Merged into #3654
