### ISSUE TITLE
stack-buffer-overflow when using AddressSanitizer

### ISSUE THREAD

**Issue by Floessie** [Beep6581/RawTherapee#3259]
Hi,

when compiling RT with `-fsanitize=address` it fails early:

	==5957==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffc16d04068 at pc 0x7f37e800d8d8 bp 0x7ffc16d03ba0 sp 0x7ffc16d03350
	READ of size 440 at 0x7ffc16d04068 thread T0
		#0 0x7f37e800d8d7 in __asan_memmove (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x888d7)
		#1 0xc45a2d in int* std::__copy_move<false, true, std::random_access_iterator_tag>::__copy_m<int>(int const*, int const*, int*) (/home/bah/src/rawtherapee/build/release/rawtherapee+0xc45a2d)
		#2 0xc4551d in int* std::__copy_move_a<false, int*, int*>(int*, int*, int*) (/home/bah/src/rawtherapee/build/release/rawtherapee+0xc4551d)
		#3 0xc450fa in int* std::__copy_move_a2<false, int*, int*>(int*, int*, int*) (/home/bah/src/rawtherapee/build/release/rawtherapee+0xc450fa)
		#4 0xc44a6c in int* std::copy<int*, int*>(int*, int*, int*) (/home/bah/src/rawtherapee/build/release/rawtherapee+0xc44a6c)
		#5 0xc4554a in int* std::__uninitialized_copy<true>::__uninit_copy<int*, int*>(int*, int*, int*) (/home/bah/src/rawtherapee/build/release/rawtherapee+0xc4554a)
		#6 0xc45132 in int* std::uninitialized_copy<int*, int*>(int*, int*, int*) (/home/bah/src/rawtherapee/build/release/rawtherapee+0xc45132)
		#7 0xc44aa2 in int* std::__uninitialized_copy_a<int*, int*, int>(int*, int*, int*, std::allocator<int>&) (/home/bah/src/rawtherapee/build/release/rawtherapee+0xc44aa2)
		#8 0xc44f6b in void std::vector<int, std::allocator<int> >::_M_range_initialize<int*>(int*, int*, std::forward_iterator_tag) (/home/bah/src/rawtherapee/build/release/rawtherapee+0xc44f6b)
		#9 0xc4485c in void std::vector<int, std::allocator<int> >::_M_initialize_dispatch<int*>(int*, int*, std::__false_type) (/home/bah/src/rawtherapee/build/release/rawtherapee+0xc4485c)
		#10 0xc43a4f in std::vector<int, std::allocator<int> >::vector<int*, void>(int*, int*, std::allocator<int> const&) (/home/bah/src/rawtherapee/build/release/rawtherapee+0xc43a4f)
		#11 0xc14b81 in Options::setDefaults() (/home/bah/src/rawtherapee/build/release/rawtherapee+0xc14b81)
		#12 0xc0e94a in Options::Options() (/home/bah/src/rawtherapee/build/release/rawtherapee+0xc0e94a)
		#13 0xc3d5d0 in __static_initialization_and_destruction_0(int, int) (/home/bah/src/rawtherapee/build/release/rawtherapee+0xc3d5d0)
		#14 0xc3d668 in _GLOBAL__sub_I__ZN7Options5rtdirE (/home/bah/src/rawtherapee/build/release/rawtherapee+0xc3d668)
		#15 0x15a10ac in __libc_csu_init (/home/bah/src/rawtherapee/build/release/rawtherapee+0x15a10ac)
		#16 0x7f37e141259e in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2059e)
		#17 0x76b898 in _start (/home/bah/src/rawtherapee/build/release/rawtherapee+0x76b898)

	Address 0x7ffc16d04068 is located in stack of thread T0 at offset 456 in frame
		#0 0xc11c05 in Options::setDefaults() (/home/bah/src/rawtherapee/build/release/rawtherapee+0xc11c05)

	  This frame has 1 object(s):
		[32, 456) 'babehav' <== Memory access at offset 456 overflows this variable
	HINT: this may be a false positive if your program uses some custom stack unwind mechanism or swapcontext
		  (longjmp and C++ exceptions *are* supported)
	SUMMARY: AddressSanitizer: stack-buffer-overflow ??:0 __asan_memmove
	Shadow bytes around the buggy address:
	  0x100002d987b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	  0x100002d987c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	  0x100002d987d0: 00 00 00 00 f1 f1 f1 f1 00 00 00 00 00 00 00 00
	  0x100002d987e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	  0x100002d987f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	=>0x100002d98800: 00 00 00 00 00 00 00 00 00 00 00 00 00[f4]f4 f4
	  0x100002d98810: f3 f3 f3 f3 00 00 00 00 00 00 00 00 00 00 00 00
	  0x100002d98820: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	  0x100002d98830: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	  0x100002d98840: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	  0x100002d98850: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	Shadow byte legend (one shadow byte represents 8 application bytes):
	  Addressable:           00
	  Partially addressable: 01 02 03 04 05 06 07 
	  Heap left redzone:       fa
	  Heap right redzone:      fb
	  Freed heap region:       fd
	  Stack left redzone:      f1
	  Stack mid redzone:       f2
	  Stack right redzone:     f3
	  Stack partial redzone:   f4
	  Stack after return:      f5
	  Stack use after scope:   f8
	  Global redzone:          f9
	  Global init order:       f6
	  Poisoned by user:        f7
	  Container overflow:      fc
	  Array cookie:            ac
	  Intra object redzone:    bb
	  ASan internal:           fe
	==5957==ABORTING

Best,
Flössie

**Comment by Beep6581** [comment]
Fix confirmed, everything seems to work fine.

For info, I merged your commit using:
```
git checkout gtk3
git pull
git cherry-pick 296919eb2b872e644185bf29ad7af059d3e89099
```
Then compile.
