### ISSUE TITLE
Monitor profile name swaps over buttons

### ISSUE THREAD

**Issue by NextTherapist** [Beep6581/RawTherapee#3263]
This is a screenshot of RawTherapee_WinVista_64_Gtk3_Release_4.2.927 

![rawtherapee-monitor-profile-name-swapping](https://cloud.githubusercontent.com/assets/16581692/14748270/0bca13fe-08b9-11e6-8c0e-d7ad8a15d604.png)

The buttons under the name of the profile are not visible anymore.

**Comment by Beep6581** [comment]
Duplicate of #3186
