### ISSUE TITLE
Blue Curve with Luminosity Mode do nothing (Color Tab - RGB Curves)

### ISSUE THREAD

**Issue by geoderix** [Beep6581/RawTherapee#3265]
The Blue Curve from Color Tab - RGB Curves with Luminocity Mode enabled do nothing.
I found the bug in the RT 4.2.781 for Windows XP and in RT 4.2.905 for Windows Vista/7/8/10 64-bit.
Thank you!

**Comment by Beep6581** [comment]
Explained by @Desmis 
https://discuss.pixls.us/t/conversion-to-black-white-something-not-right/868/6
Solution: Don't use ProPhoto working space.

**Comment by geoderix** [comment]
Ok.
I switched Working Profile to sRGB. When I change Red or Green curve with Luminocity Mode I see changes. But when I change Blue curve with Luminocity Mode I almost do not see the changes. They are too small. Are you sure that the reason is the color space width of ProPhoto?
Thank You.
