### ISSUE TITLE
Fuji X-Pro 2 dcp submitted for review and integration

### ISSUE THREAD

**Issue by CharlesRT2** [Beep6581/RawTherapee#3269]
I photographed two Color Checkers - a large old MacGregor and a small paper Passport - with a Fuji X-Pro 2 in direct mid-day sunlight using a Fuji 18-55 lens at f/5.6. I made two .dcp files with Passport, which give slightly different results.

I have uploaded the RAF and dcp files for review at http://filebin.net/95d7whei5n .
Someone can integrate the dcp files into RT or make better dcp files from the RAFs.

**Comment by sguyader** [comment]
Thanks Charles, it will be helpful and maybe attract more photographers to
RT.

**Comment by Beep6581** [comment]
@CharlesRT2 thank you, but please provide the raw photos themselves, not DCPs made from them. By providing them, you agree to release them into the public domain, so there will be no problems with licencing.

**Comment by CharlesRT2** [comment]
@Beep6581 I uploaded the two raw files again. They are now at https://filebin.net/k8qll45qxpwgcz82  , and yes, they are in the public domain.

**Comment by Beep6581** [comment]
That Macbeth chart is in bad shape, the ColorChecker Classic is of unknown age, the shadow indicates the chart may have been photographed at an angle likely to cause glare (luckily it's matte), and I don't know whether `ColorChecker.cht` from ArgyllCMS and `cc24_ref.cie` from DCamProf are compatible with either.

DCPs and log files:
https://filebin.net/azjk8akj6vjo289e

@iliasg do you have a preference?

**Comment by CharlesRT2** [comment]
If you want me to photograph one or both charts again, let me know.

**Comment by iliasg** [comment]
@Beep6581 By Dcamprof DE results classic is better
I would like to crossmeasure against Dpreview/Imaging_resource cc24 shots .. but I lost my infrastructure for de2000 measures in a mid_summer crash :(
But these are single illuminant dcps ..no ? .. I think there is no reason to use as RT defaults these profiles at least until we have again  solved the single illuminant issue.

**Comment by Beep6581** [comment]
@iliasg correct, single.

**Comment by Beep6581** [comment]
@CharlesRT2 could you re-shoot the ColorChecker Classic (or Passport if you have a Passport) following these requirements http://rawpedia.rawtherapee.com/How_to_create_DCP_color_profiles#Shooting_the_color_chart and specifically:
- Shoot in both daylight and tungsten light (real tungsten lightbulb, not easy to find anymore :P ),
- Have the chart fill about 1/3rd of the frame. Your previous ColorChecker shot was good in this regard, while the Macbeth (where did you get the name MacGregor from? There is no such thing AFAIK) was too large.
- Stand in such a way that the sun isn't directly behind you, as this can cause glare.
- Stand in an empty parking lot or somewhere far away from high walls, overhead trees and other things which could bounce colored light.

**Comment by CharlesRT2** [comment]
It is overcast today. Is that acceptable, or do I wait for a sunny day?

(Sorry about Macbeth/MacGregor. We English lords could never keep those Scottish clans straight.)

**Comment by CharlesRT2** [comment]
Okay, second try. Took a sunlight shot early-midafternoon and a shot under a General Electric Soft White 60W tungsten(?) bulb. The files are at
https://filebin.net/2khssq4uh9ov8owk

**Comment by Beep6581** [comment]
@CharlesRT2 the tungsten shot is underexposed by almost 2 steps, its at ISO1600, out of focus and has motion blur. The daylight shot is at ISO200 at f/5.6.
Please read http://rawpedia.rawtherapee.com/How_to_create_DCP_color_profiles#Shooting_the_color_chart and the comments in this issue again. The shots need to be at the lowest real ISO (typically ISO100), well exposed without clipping, sharp, f/8, etc.

**Comment by Beep6581** [comment]
@CharlesRT2 the daylight shot is not clipped at all.

In a moment I will commit a DCP for RT5 because it's not bad, and better than without one, but it would be good if you could still provide us with a better tungsten shot, as described above.

**Comment by CharlesRT2** [comment]
@Beep6581 Here is a shot under a 60-watt GE soft light. [https://filebin.net/vpncnfl2qttmt5hc]

Shot at the base ISO of the Fuji X-Pro 2, ISO 200.

**Comment by CharlesRT2** [comment]
@Beep6581 Here is another light bulb shot with, I believe, less camera shake.
https://filebin.net/zji0tcwu8y3oc93v

**Comment by Beep6581** [comment]
@CharlesRT2 thank you, new raw file (D2CF3626.RAF) added, DCP updated.
