### ISSUE TITLE
Use last directory in "move"

### ISSUE THREAD

**Issue by Krzysiu** [Beep6581/RawTherapee#3270]
Let's say I have opened `c:\foo\photo.jpg` and I want to move it to other directory. I'm clicking on "move" and save dialog shows me directory `c:\foo`. I'm moving it to `e:\bar`, move was successful. I'm choosing another file, from the same directory and after clicking on "move" I'm again in `c:\foo`, not the last used for moving directory - `e:\bar`. I think it's the matter of taste, but for me displaying last used dir would be better. I don't know about other users, but I have "unsorted" directory and "sorted", so I'm moving photos to "sorted" and I need to do it with every move. 

My env: Windows 7 64 bit, RT 4.2.915 64 bit, Gtk3

**Comment by Krzysiu** [comment]
I still think it would be cool, but now I realized there's "recent" in the left panel, so it's not so needed anymore. I'm not closing it yet, because maybe you'd think such change is still fine.

**Comment by Beep6581** [comment]
Closing because nobody will do this, unless you submit a patch.
