### ISSUE TITLE
Branch rec2020 - Add Rec2020 to working profiles

### ISSUE THREAD

**Issue by Desmis** [Beep6581/RawTherapee#3274]
I create a new branch with
- a new profile "Rec2020" for "working profiles"
  :)

**Comment by Beep6581** [comment]
Compiles and runs fine in Linux/GCC-5.3.0.

I noticed that it makes clipped whites turn light-gray.

**Comment by Desmis** [comment]
I think there was a bug in matrix calculation.
I push a change  with "good" matrix :)

**Comment by Beep6581** [comment]
White-turns-gray problem fixed. I think we can merge?

For documentation:
* http://rawpedia.rawtherapee.com/Color_Management
What gamma and slope does it have?
* http://rawpedia.rawtherapee.com/Color_Management_addon/fr
If you update this, I can try google-translating it into English.

**Comment by Desmis** [comment]
I just merge rec2020 in master

**Comment by Desmis** [comment]
I have updated Rawpedia in frenh and in english :)

**Comment by Beep6581** [comment]
I merged `master` into `gtk3`, and astyle'd both. Strangely, astyle made no differnece in `master`, but it did in `gtk3`.

Compiles and runs fine as far as I can tell.

**Comment by Desmis** [comment]
I also from time to time, I meet formatting problems when I import from previous commits.
I think we do not all use the same version of "astyle". I always use the "astylert" (.bat) that is in the "git"

**Comment by sguyader** [comment]
@Beep6581 since you just merged Master into Gtk3, I'll make new builds for
Windows 64 bits today. So please wait for these and don't upload
yesterday's builds.

**Comment by Beep6581** [comment]
@Desmis I use version 2.05.1. Yes, we should always use `astyle --options=rawtherapee.astylerc`
I think the issue can be closed.

@sguyader great!
