### ISSUE TITLE
Speedup for thumbnail processing

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#3275]
I created the new branch [rgbcurvesspeedup](https://github.com/Beep6581/RawTherapee/commits/rgbcurvesspeedup). The intention for this branch was to speedup creation of rgb curves (that's the reason for the name of the branch), but then I detected some possibilities to speedup a lot of parts of curve generation and some other parts too. These speedups are mainly noticeable in thumbnail processing, less noticeable in preview processing and even less noticeable in full processing.
Processing of thumbnails with default profile is about 2 times faster with this changes on my machine and with my small thumb size. When switching folders containing cached thumbs that's noticeable by eye, but I also let one StopWatch in code in case someone wants to measure before/after.
@Floessie Can you review the changes to rtengine/LUT.h please? The 'compressTo' methods should be valid only for `LUT<unsigned int>` and makeIdentity and makeConstant should be valid only for `LUT<float>`
Code is not completely beautified and cleaned yet.

Ingo

**Comment by Floessie** [comment]
@heckflosse I've checked the new branch out and will have a look at it later. Do you prefer exactly `unsigned int` or any unsigned integral type? And if exactly `unsigned int` wouldn't `std::uint32_t` be even more exact?

Flössie

**Comment by heckflosse** [comment]
@Floessie I updated my post from above, because formating killed some relevant information. I'll go for the more exact data types.

**Comment by Floessie** [comment]
[Here](https://gist.github.com/Floessie/b849ceb55b700d761bb2317b28038177) is my take on your problem. Don't know if it's the most compact one, but it's certainly readable. :)

**Comment by heckflosse** [comment]
@Floessie Great! I'll try that immediately. Thank you :+1:

**Comment by Floessie** [comment]
@heckflosse You're welcome! :) As a test, I changed one `std::uint32_t` to `std::uint8_t` and it failed as expected.

**Comment by heckflosse** [comment]
@Floessie Yeah, works fine here too. I'll push the changes soon.

**Comment by heckflosse** [comment]
I pushed a lot of small improvements to [rgbcurvesspeedup branch](https://github.com/Beep6581/RawTherapee/commits/rgbcurvesspeedup). Though these are very small improvements, processing time for a thumb with default profile is reduced from ~40 ms to ~10 ms at my system.

**Comment by Floessie** [comment]
@heckflosse [Here](https://gist.github.com/Floessie/9ae10f897011bfb2558daddc9acef534) is a little patch with some minor C++11 improvements.

**Comment by heckflosse** [comment]
@Floessie Thank you very much for the review and the patch! Highly appreciated :+1:

**Comment by heckflosse** [comment]
@Floessie I added your patch to branch

**Comment by Floessie** [comment]
@heckflosse *Review* is carrying things too far. I just had a quick look at your diffs and those `delete`s struck me. I only checked if my patch compiles, but nothing more. So take it with a grain of salt.

**Comment by heckflosse** [comment]
I pushed some further improvements to [rgbcurvesspeedup branch](https://github.com/Beep6581/RawTherapee/tree/rgbcurvesspeedup)

**Comment by heckflosse** [comment]
I made further improvements to [rgbcurvesspedup branch](https://github.com/Beep6581/RawTherapee/commits/rgbcurvesspeedup) and merged into master branch to get more tests. Issue stays open

Ingo
