### ISSUE TITLE
RT v. 4.2.967 for Windows 64-bit crashes upon launch

### ISSUE THREAD

**Issue by CharlesRT2** [Beep6581/RawTherapee#3277]
The debug window closes, so I screen-captured only part of it:
    terminate called after throwing an instance of 'std::out_of_range'
        what():  basic_string: __pos (which is 18446744073709551615)

Here are the Problem Details:
  Problem Event Name:   APPCRASH
  Application Name: rawtherapee.exe
  Application Version:  0.0.0.0
  Application Timestamp:    5728a02c
  Fault Module Name:    libstdc++-6.dll
  Fault Module Version: 0.0.0.0
  Fault Module Timestamp:   00000000
  Exception Code:   40000015
  Exception Offset: 00000000000223ca
  OS Version:   6.1.7601.2.1.0.768.3
  Locale ID:    1033
  Additional Information 1: a33a
  Additional Information 2: a33a3cb2d5e6baaa3e33c978a1f1f5d9
  Additional Information 3: de06
  Additional Information 4: de06691953e72a23732ac60da6a10b54

**Comment by Beep6581** [comment]
Hello @CharlesRT2 
Unfortunately that information is not useful. Please follow this and open a new issue with the required files and info.
http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports

**Comment by CharlesRT2** [comment]
Thank you. Fortunately, before I plunged into pulling together a bug report, I noticed the adjacent RawPedia section about crashes on startup, and one of its suggestions revealed the problem. The folder to start in had a .pp3 file for Classic Chrome film simulation on the Fuji XT1 that S. Guyader had made available. When I removed file from the folder, the newly installed build of RT launched without problem.

**Comment by Beep6581** [comment]
> The folder to start in had a .pp3 file for Classic Chrome film simulation on the Fuji XT1 that S. Guyader had made available. When I removed file from the folder, the newly installed build of RT launched without problem.

It is very important that you reproduce this crash and supply the raw+PP3+Hald CLUT to us.

**Comment by CharlesRT2** [comment]
There is no raw to supply: RT crashed before presenting its opening screen. Also, the same thing happened when I had a different single raw file in the folder.

The HALDCLUT is the 358 MB collection that S. Guyader offered. It is dated 7/16/2014. The .pp3 is also one he supplied, which I attach here, as a .txt file of course (I gave it a filename and do not have the original filename).

[FujiXT1_Classic_Chrome_Guyader.txt](https://github.com/Beep6581/RawTherapee/files/252627/FujiXT1_Classic_Chrome_Guyader.txt)

**Comment by sguyader** [comment]
@CharlesRT2 I didn't offer any HaldCLUT collection, I juste pointed to the collection downloadable on Rawpedia.

**Comment by Beep6581** [comment]
This is hopefully a duplicate of issue #3154, which is now fixed.
