### ISSUE TITLE
RT 4.2.974 Win 7 invoke HaldCLUT crash - backtrace

### ISSUE THREAD

**Issue by ClaesGitHub** [Beep6581/RawTherapee#3278]
I hope I managed to follow all instructions, this is the first gdb/RT I've ever made.
Win 7, 64-bit, 12 gig RAM.
Backtrace:
[logRT.txt](https://github.com/Beep6581/RawTherapee/files/252127/logRT.txt)
When Backtrace stopped (see last line in log file), gdb crashed!

**Comment by pi99y** [comment]
Also see #3154
