### ISSUE TITLE
Histogram of working space does not show "gray" for gray regions

### ISSUE THREAD

**Issue by mmmtok** [Beep6581/RawTherapee#3283]
I think histograms for whole gray points should show almost the same values of R, G and B.
When it comes to the one for output color space, it's OK but working space histogram is not.

[Versions]
I see this with
	RT 4.2.753
	OSX 10.11.4
but I believe it is platform independent.

[Reproduction procedure]
1. Open Preferences and check "Use working profile for main histogram and navigator"
2. Open the whole gray image.
3. Apply "Neutral"
4. Do "Spot WB" at somewhere in the image to make the image real gray.
5. Observe the histogram.
6. To see expected histograms, uncheck "Use working..." in Preference and change output profile.

[Candidate fix]
I think there is an obvious bug in rtengine/iplab2rgb.cc.  The following changes fixed it in my own build.
```
--- iplab2rgb.cc.orig   2016-05-13 14:55:35.000000000 +0900
+++ iplab2rgb.cc        2016-05-13 15:17:23.000000000 +0900
@@ -202,7 +202,7 @@
         }
     } else {

-        const auto rgb_xyz = iccStore->workingSpaceMatrix (profile);
+        const auto xyz_rgb = iccStore->workingSpaceInverseMatrix (profile);

 #ifdef _OPENMP
         #pragma omp parallel for schedule(dynamic,16) if (multiThread)
@@ -227,7 +227,7 @@
                 float z_ = 65535.0 * Color::f2xyz(fz) * Color::D50z;
                 float y_ = (LL > Color::epskap) ? 65535.0 * fy * fy * fy : 65535.0 * LL / Color::kappa;

-                Color::xyz2rgb(x_, y_, z_, R, G, B, rgb_xyz);
+                Color::xyz2rgb(x_, y_, z_, R, G, B, xyz_rgb);

                 image->data[ix++] = (int)Color::gamma2curve[CLIP(R)] >> 8;
                 image->data[ix++] = (int)Color::gamma2curve[CLIP(G)] >> 8;
```
[Misc]
It may also solve another problem reported in #3213, though I have not tested.

**Comment by heckflosse** [comment]
@mmmtok Thanks a lot for providing this patch! Works fine here. @Desmis Jacques, can you also take a look please?

**Comment by Desmis** [comment]
@mmmtok  @heckflosse 
Yes, I confirm, we must use "workingSpaceInverseMatrix", instead of  "workingSpaceMatrix"...
:)
