### ISSUE TITLE
Ubuntu 16.04 libgtkmm-2.4.so.1: cannot open shared object file

### ISSUE THREAD

**Issue by Jau-Al** [Beep6581/RawTherapee#3285]
Hello,

I installed rawtherapee under Ubuntu 16.04. It won't open.

`rawtherapee: error while loading shared libraries: libgtkmm-2.4.so.1: cannot open shared object file: No such file or directory`

I checked :
```
~$ apt-cache policy libgtkmm-2.4-1v5 
libgtkmm-2.4-1v5:
  Installé : 1:2.24.4-2
  Candidat : 1:2.24.4-2
 Table de version :
 *** 1:2.24.4-2 500
        500 http://fr.archive.ubuntu.com/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
```

Compatibility problem ?

**Comment by ClaesGitHub** [comment]
Hi! Do you compile RT, pulling the source code from GitHub?
If so, check your dependencies for Ubuntu 16.04 (use the gtk3 branch):

> sudo apt-get update
> sudo apt-get install build-essential cmake curl git libbz2-dev libcanberra-gtk3-dev libexiv2-dev libexpat-dev libfftw3-dev libglibmm-2.4-dev libgtk-3-dev libgtkmm-3.0-dev libiptcdata0-dev libjpeg8-dev liblcms2-dev libpng12-dev libsigc++-2.0-dev libtiff5-dev zlib1g-dev

**Comment by Jau-Al** [comment]
No, It's from the repository. I tried the PPA two (unstable version). It was exactly the same.

**Comment by ClaesGitHub** [comment]
I can check a little later today.
If you feel like compiling RT all by yourself, follow these instructions:
http://50.87.144.65/~rt/w/index.php?title=Linux

**Comment by aserebryakov** [comment]
Just tried on my Ubuntu 16.04 x64. No issue with running.

> Branch: default
Version: 4.2.0
Changeset: c81d9026d25c
Compiler: x86_64-linux-gnu-gcc 5.2.1
Processor: undefined
System: Linux
Bit depth: 64 bits
Gtkmm: V2.24.4
Build type: Release
Build flags: -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -std=c++11 -D_FORTIFY_SOURCE=2   -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG
Link flags:  -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed
OpenMP support: ON
MMAP support: ON

**Comment by ClaesGitHub** [comment]
@aserebryakov Please do not use RT 4.2.0. It is very, very old.
@Jau-Al I have just checked of a naked Ubuntu 16.04 x64 machine
```
sudo add-apt-repository ppa:dhor/myway
sudo apt-get update
sudo apt-get install rawtherapee-unstable
```
works just fine.
If you need more assistance, I believe it is better to user the RT forum at 
https://discuss.pixls.us/

**Comment by Jau-Al** [comment]
srysrysry ! In fact, rawtherapee wasn't the culprit lol.
I used synaptic to reinstall all gtk libs and unity. Now everything is fine ! 
Thank you everyone ;-)
And again sorry, I should have begun with this !

P.S : Maybe a snap version could be a good idea  ? Looks like it's nice for dependencies ^^. (just an idea)

**Comment by heckflosse** [comment]
Ok, the Issue seems to be solved => Close!
