### ISSUE TITLE
failed compile in lastest upgrade

### ISSUE THREAD

**Issue by gaudry-daniel** [Beep6581/RawTherapee#3286]
Hi
I tried the update and got the following output:
Can you help??
best regards

Building CXX object rtengine/CMakeFiles/rtengine.dir/clutstore.cc.o
/home/daniel/RawTherapee/rtengine/imageio.cc: In static member function ‘static int rtengine::ImageIO::getPNGSampleFormat(Glib::ustring, rtengine::IIOSampleFormat&, rtengine::IIOSampleArrangement&)’:
/home/daniel/RawTherapee/rtengine/imageio.cc:218:31: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
     fread (header, 1, 8, file);
                               ^
/home/daniel/RawTherapee/rtengine/imageio.cc: In member function ‘int rtengine::ImageIO::loadPNG(Glib::ustring)’:
/home/daniel/RawTherapee/rtengine/imageio.cc:297:31: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
     fread (header, 1, 8, file);
                               ^
/home/daniel/RawTherapee/rtengine/imageio.cc: In member function ‘int rtengine::ImageIO::saveTIFF(Glib::ustring, int, bool)’:
/home/daniel/RawTherapee/rtengine/imageio.cc:1317:68: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
                     write (TIFFFileno (out), buffer + 8, exif_size);
                                                                    ^
/home/daniel/RawTherapee/rtengine/clutstore.cc: In function ‘vfloat2 {anonymous}::getClutValues(const AlignedBuffer<short unsigned int>&, size_t)’:
/home/daniel/RawTherapee/rtengine/clutstore.cc:98:26: error: ‘m_mask’ was not declared in this scope
     v_low = vandm(v_low, m_mask);
                          ^
/home/daniel/RawTherapee/rtengine/clutstore.cc:102:25: error: ‘lowval’ was not declared in this scope
         _mm_cvtepi32_ps(lowval),
                         ^
/home/daniel/RawTherapee/rtengine/clutstore.cc:103:25: error: ‘highval’ was not declared in this scope
         _mm_cvtepi32_ps(highval)
                         ^
/home/daniel/RawTherapee/rtengine/clutstore.cc:104:5: error: could not convert ‘{<expression error>, <expression error>}’ from ‘<brace-enclosed initializer list>’ to ‘vfloat2’
     };
     ^
make[2]: *** [rtengine/CMakeFiles/rtengine.dir/clutstore.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [rtengine/CMakeFiles/rtengine.dir/all] Error 2
make: *** [all] Error 2

**Comment by heckflosse** [comment]
@gaudry-daniel Thanks for reporting. Fixed in e8d90698cfe2bfb5c5a05ffe4d7b4cf113829c8f
