### ISSUE TITLE
Premature end of JPEG file. Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by asktoby** [Beep6581/RawTherapee#3296]
I am able to repeatedly crash RawTherapee 4.2.0 on Fedora.

Steps to reproduce:
Open Rawtherapee from Command Line
Use File browser left panel to navigate to and double click on photo folder
Double click on photo from the thumbnail browser
Click "Put current image to processing que" in bottom left
Go to processing queue
Click "Start processing"
Rawtherapee crashes so:

Premature end of JPEG file
Segmentation fault (core dumped)

If I reopen rawtherapee the file is still in the queue, and can then be saved.

**Comment by Beep6581** [comment]
http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports
