### ISSUE TITLE
Camconst.json, 2016 updates 

### ISSUE THREAD

**Issue by iliasg** [Beep6581/RawTherapee#3298]
Here https://drive.google.com/file/d/0B0NqktTgc54sZTRsbE9IUlhzeUE/view?usp=sharing
is an updated camconst.json supporting many new models (not all recent models ..) and correcting some data for older models.
Please test for any issues ..

As a new Dcraw with almost all recent models supported is available (Dcraw 9.27 - Rev. 1.477 Date: 2016/05/10 21:30:43) http://www.cybercom.net/~dcoffin/dcraw/dcraw.c
 and as usually some things change (Sony BL read from exif etc) we will need an updated camconst.json after RT adapts to the latest DCraw.

**Comment by Beep6581** [comment]
@iliasg ok with you if I commit this camcont.json update so @sguyader and @gaaned92 can include it in their builds for more testing?

**Comment by heckflosse** [comment]
@iliasg Ilias, I'll start the dcraw part now

**Comment by Beep6581** [comment]
As I have to leave for a few hours and I suppose sguyader and gaaned will want to build in the meanwhile, I committed it to both branches, with some minor comment changes.

**Comment by iliasg** [comment]
@Beep6581 thanks for commiting to gain some testers, although I think it's faster and more efficient if we just make the new camconst.json public at RT forum .. should I post a message there ?.

@heckflosse Ingo thanks, after merging the new Dcraw please give a little thought if it's efficient to have one more Black Level constant  in camconst.json i.e "abs_black" (absolute BL i.e.one that ovewrites any BL detected or hardcoded by Dcraw) in addition to the current "black" which is relative (added upon the detected by Dcraw). 
We have 1-2 issues open with Nikon some (not all) files from D810 and D5300 (?) (may be more ..) with wrong detected BL which we could correct with an "absolute black" setting in camconst.json

**Comment by heckflosse** [comment]
@iliasg It would need a lot of changes to camconst code to add an "abs_black" property because of the way it's designed. "white" has index 0 and "black" has index 1 and a lot of code depends on that mapping currently.
An easy solution would be to treat all black levels > 65535 as absolute black level (after subtracting 65535 of course). That would be a one line change. What do you think?

**Comment by Beep6581** [comment]
@heckflosse if the many changes required to implement abs_black are similar or follow a pattern, maybe I could help by scripting?

**Comment by iliasg** [comment]
@heckflosse Ingo, I do not have a clear mind at the moment .. :(
I could deal with this >65535 norm but what about normal users ?. Will just updating the manual be enough ?.  
I don't understand why it is so complex !! the only difference between the current camconst "black" and the "abs_black" will be the elimination of any input coming from Dcraw. I mean that now Dcraw feeds camconst with a "detected black" and then the final "black level" is detected_black + camconst black  .. just change the code so that black_level = abs_black .. or I took the order inversely ? 
Anyway .. the >65535 norm is better than nothing .. almost fine I'd say .. go for it 
The issue which could be solved with absolute black is https://github.com/Beep6581/RawTherapee/issues/2814 you can find at the last post a link for such a file .. is the new Dcraw still at fault ? (I am on a 32bit environment so I cannot test myself .. waiting a build from @gaaned92)

**Comment by heckflosse** [comment]
@iliasg @Beep6581 It's not complex. It's just that implementing "abs_black" is not a one liner, which also means it needs more tests than the one liner ;-)

**Comment by iliasg** [comment]
camconst.json update https://drive.google.com/file/d/0B0NqktTgc54sVXhiS180SFRqbm8/view?usp=sharing to keep in track with latest Dcraw 9.27 merge

- Updated manual/comments .. absolute black (WL>65535) from recent Dcrawupdate branch included.
- Reorder of items, trying to achieve Brand-category(high/mid/low)-model structure 
- Fuji x-pro1 added,  
- added alternate names of Canon models

**Comment by heckflosse** [comment]
@iliasg Thank you! Pushed to master branch d57eec1

**Comment by iliasg** [comment]
Small update ..
https://drive.google.com/file/d/0B0NqktTgc54sQmdYVE5JZ0NlVlU/view?usp=sharing
Added
Canon G7X II (same data as G7X)
Fuji X-T2 (same data as X-pro2), 
Panasonic GX80/85/GX7II (separated from G7 due to different color matrix (DNG9.6)
Sony RX10III (same data as RX10II)

**Comment by Beep6581** [comment]
Thank you @iliasg, committed.

This RAF opens fine:
http://www.imaging-resource.com/PRODS/fuji-x-t2/Y-beta-DSCF0375.RAF.HTM
49MB
` -EXIF:CompressedBitsPerPixel=2.5`
`-RAF:XTransLayout=BGGRGG RGGBGG GBRGRB RGGBGG BGGRGG GRBGBR`

This one does not:
http://www.imaging-resource.com/PRODS/fuji-x-t2/XT2hSLI00100NR0.RAF.HTM
28MB
`-EXIF:CompressedBitsPerPixel=2.5`
`-RAF:XTransLayout=GRBGBR BGGRGG RGGBGG GBRGRB RGGBGG BGGRGG`

**Comment by iliasg** [comment]
@Beep6581 the 28MB file is compressed .. waiting for Libraw's code to be ported in RT ;)

**Comment by iliasg** [comment]
Updated with DNG 9.7 data and fillup some constants for 5DIV
Updated Canon 5DIV data, quality B, only Long Exposure data missing but safely guessed
New models .. Nikon D3400, Panasonic G80/G81/G85
https://drive.google.com/file/d/0B0NqktTgc54sNHNVNkxCRHpiX2c/view?usp=sharing

**Comment by Beep6581** [comment]
@iliasg committed. I had to fix a typo on line 513, there was an extra comma:
```
-                { "iso": [ 320, 640, 1250, 2500, ], "levels": 13300 }, // G1,G2 F4.0-13422-F2.8-13562-13616
+                { "iso": [ 320, 640, 1250, 2500 ], "levels": 13300 }, // G1,G2 F4.0-13422-F2.8-13562-13616

```

**Comment by iliasg** [comment]
Ooohh the usual typo error , thanks for correcting and committing.

**Comment by iliasg** [comment]
camconst.json update includes
Pentax K-70 (reported in https://discuss.pixls.us/t/support-for-pef-dng-from-pentax-k-70-and-pixel-shift-resolution/2560). 
adobe_coeff setting needed in Dcraw.cc for activating camconst.json WLs for Pentax's DNGs

Preliminary support for
Panasonic LX10/15
XiaoYI M1 (this one exports DNG files and needs to set "adobe_coeff" in Dcraw.cc to activate the correct WL)
https://drive.google.com/file/d/0B0NqktTgc54scnMwZEZSaVcwM2M/view?usp=sharing

**Comment by Beep6581** [comment]
I re-formatted the whole file and rewrote some parts.
Notable changes:

- The file had a mix of tab and space characters. Now tab characters are no longer used.
- Indentation is always 4 space characters wide.
- Closing braces appear on the same column as the first non-indenation character of the line with opening braces.

Please check that your text editor respects the formatting already in the file so that when you indent using the [tab] key, the editor will use 4 spaces.

Top is after, bottom is before:
https://i.imgur.com/SvqluEm.png

**Comment by heckflosse** [comment]
@iliasg 

> XiaoYI M1 (this one exports DNG files and needs to set "adobe_coeff" in Dcraw.cc to activate the correct WL)

That's an easy modification. But I would like to test it. Do you have a link to a DNG from that camera?

**Comment by iliasg** [comment]
Ingo, sure .. choose from Dpreview gallery
https://www.dpreview.com/samples/0522898516/yi-m1-sample-gallery
We need the same for Pentax k-70's DNGs (because the WL reported is not absolute as used by RT but decreased by BL ..
http://www.imaging-resource.com/PRODS/pentax-k70/pentax-k70A7.HTM

**Comment by heckflosse** [comment]
@iliasg In first step I will simply call adobe_coeff especially because we want to release rt5 soon.
Then we should open a new issue to collect all the useful camconst enhancements which are now spread over several issues and make a concept.
pr with changes for k-70 and XiaoYI M1 follows soon.

**Comment by heckflosse** [comment]
@iliasg [new pr](https://github.com/Beep6581/RawTherapee/pull/3490)

**Comment by iliasg** [comment]
Updated camconst.json includes
Pentax K-1 https://github.com/Beep6581/RawTherapee/issues/3489
Olympus E-M1MarkII (preliminary support .. color data guessed )
Canon G7 X moved to the correct model_group to comply with 14bit files ..

**Comment by heckflosse** [comment]
@iliasg It seems you used a version of camconst.json which was made before [the changes, @Beep6581  made](https://github.com/Beep6581/RawTherapee/commit/d2526e0f942848ac8f91b3d0f2e8d3d31ab3f78d)

I'll just pick the changes you made for the 3 cams you mentioned above if you don't mind.
Please pull again after my push to be sure your next changes are made on current master branch ;)

Ingo

**Comment by heckflosse** [comment]
@iliasg I pushed to master branch

**Comment by iliasg** [comment]
Thanks, sorry for the mess :(

**Comment by heckflosse** [comment]
@iliasg no problem. Did you see [low light pixelshift](https://discuss.pixls.us/t/support-for-pef-dng-from-pentax-k-70-and-pixel-shift-resolution/2560/62) ?

**Comment by iliasg** [comment]
- Updates for 
Canon 80D .. filled most WL and aperture scaling missing data
Olympus E-M1MarkII .. correct color matrix
Panasonic LX100 .. more detailed WL data
Pentax K70 .. color matrix from DNG_v9.8, frame correction

- New models
Canon EOS M5
Fujifilm X-A3
Nikon D5600
Olympus E-PL8
Panasonic FZ2000/FZ2500/FZH1
Panasonic LX9/LX10/LX15
Sony A99II
Sony a6500
[camconst-dng9.8.zip](https://github.com/Beep6581/RawTherapee/files/673344/camconst-dng9.8.zip)

**Comment by Beep6581** [comment]
camconst.json from camconst-dng9.8.zip committed with minor changes. @iliasg please [get camconst.json from git](https://github.com/Beep6581/RawTherapee/blob/master/rtengine/camconst.json) before making future changes.

**Comment by iliasg** [comment]
OK, thanks
