### ISSUE TITLE
TP_RETINEX_GAINTRANSMISSION_TOOLTIP

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3299]
@Desmis hello, I'm revising some labels and this one is unclear to me:

`TP_RETINEX_GAINTRANSMISSION_TOOLTIP;Amplify or reduce transmission map to achieve luminance.\nAbscissa: transmission -min from 0, mean, and values (max).\nOrdinate: gain.`

Could you please explain the "Abscissa: transmission -min from 0, mean, and values (max)." part?

**Comment by Desmis** [comment]
@Beep6581 

Hello
It is the same 'explanation" than for "Transmission" and "Transmission map curve".
For this last the label is : "transmission from negative values (min), mean, and positives values (max)"

To say in another word. The abscissa represents a Gaussian function of "transmission"...Transmission varies from negatives (often about -10 to -50 values to positives values about +10 to +50. The abscissa represents in the middle==>mean, middle * 1.33 ==> mean + sigma, middle * 0.66 ==> mean - sigma, 0 ==> min, 1 ==> max...
But difficult for me to explain in my bad english
:)
Jacques

**Comment by ClaesGitHub** [comment]
@Beep6581 
Would it be easier to understand for ordinary users if you wrote _x-axis_ and _y-axis_ instead? Or perhaps _horizontal axis_ and _vertical axis_?
