### ISSUE TITLE
Queue tab "Save to folder" shortcuts don't update PathFolder in options file

### ISSUE THREAD

**Issue by NextTherapist** [Beep6581/RawTherapee#3301]
RT Master 4.2.797, Windows 7 64bit

I targetted the queue output to a subfolder of Desktop. After processing the queue and finally removing the subfolder, I started the next queue processing: to Desktop without a subfolder.

RT _produces_ the same subfolder again and saves the new output to the subfolder

**Comment by Beep6581** [comment]
Cannot reproduce.

> I started the next queue processing: to Desktop without a subfolder.

How exactly did you do that? Did you click the "Save to folder" button again and point RT to the Desktop folder?

**Comment by NextTherapist** [comment]
@Beep6581 
The "Save to folder" button was preselected and proposed "None". I chose "Desktop" and started processing. Then RT created the subfolder again and saved the file in it.

**Comment by Beep6581** [comment]
> How **exactly** did you do that?

How did you choose "Desktop", in the main area or in the side panel? Did you enter the Desktop folder? Did you single-click it or double-click it? Did you use the "OK" button? Details.

**Comment by NextTherapist** [comment]
![rt-queue-desktop](https://cloud.githubusercontent.com/assets/16581692/15465935/573384d4-20d7-11e6-8e0f-def83f6cad41.png)

This is what I see when I restart RT after saving the queue output to a subfolder and then deleting the subfolder.
I put an image into the queue, change to the queue tab and see the attached dialogue.
(I do not need to select "Save to folder" here, it's preselected)
I click on the field that shows "None" behind "Save to folder" and it switches to my windows user name, without showing me alternatives.
I click there again and now I get alternatives. As a second, directly after my user name, I get "Desktop". 
I select "Desktop" from the list and then click on "Start processing".
Then I get a new subfolder with the output image.

**Comment by Beep6581** [comment]
Thank you, reproduced in Linux.

To reproduce, one must use the shortcut destinations in the first two sections of the drop-down. In Linux/Gtk3, the drop-down has three sections. The first two contain mount points, "favorite" destinations, "Desktop" and "File System", and the last section contains just "Other...".
"Other..." works well, but the shortcuts before it don't.

**Comment by Beep6581** [comment]
I tried several of the choices in the drop-down, none of them updated the `PathFolder=` key in the options file, only "Other..." did.

**Comment by NextTherapist** [comment]
Still exists in 4.2.1000.

**Comment by Beep6581** [comment]
Still valid in 5.1-rc1.

**Comment by Beep6581** [comment]
And no longer valid in 5.1 :)
