### ISSUE TITLE
Samsung NX1 SRW fails to open properly

### ISSUE THREAD

**Issue by Michael-GH** [Beep6581/RawTherapee#3308]
Build: 4.2.862 & 4.2.1005 W10 x64

Opening a Samsung NX1 SRW raw file results in only a partial strip of image shown. Build 808 does not have this issue. Happens with all SRW files I have, used to be fine.
According to [pixls comment](https://discuss.pixls.us/t/samsung-nx1-raw/1467/9?u=michael), this appears to be due to a [new line introduced to NX1 section of camconst.json](https://github.com/Beep6581/RawTherapee/blob/master/rtengine/camconst.json#L1689).

Sample SRW file can be found here: http://filebin.net/o5l5raugil

**Comment by heckflosse** [comment]
@Michael-GH Thanks for reporting. Fixed with d0cef55aada8e51321d44982a2a8ca258eaa6139

Ingo
