### ISSUE TITLE
Segfault adjusting false color suppression steps

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3312]
I can reproduce a segfault if I open the image from https://github.com/Beep6581/RawTherapee/issues/3311 , apply neutral and adjust the X-Trans False color suppression steps (3-pass demosaicing selected), but only if I run a release build normally. If I run it from GDB, or if I run a debug build from GDB, no crash.

I just grab the False color suppression steps knob and drag it left and right without releasing. Zoomed to fit (25%). For example this time it segfaulted the 28th time I dragged it from left to right and back again.

Tested now with amsterdam.pef using the Bayer False color suppression steps slider, same procedure, same crash. Also can't reproduce in debug or through GDB.

Tested the same procedure with the Exposure slider, but no crash.

```
Branch: gtk3
Version: 4.2.1013
Changeset: 7040b6e5b1fdd596c58fb201ccbcd5ad1f3b7a3e
Compiler: cc 5.3.0
Processor: Intel(R)\ Core(TM)\ i7\ CPU\ Q\ 820\ @\ 1.73GHz
System: Linux
Bit depth: 64 bits
Gtkmm: V3.18.0
Build type: release
Build flags: -std=c++11 -Wno-deprecated-declarations -Wno-unused-result -std=gnu++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON
```

**Comment by heckflosse** [comment]
I take that

**Comment by heckflosse** [comment]
Hmmm, false colour correction is [skipped](https://github.com/Beep6581/RawTherapee/blob/master/rtengine/rawimagesource.cc#L881) at 25% zoom
Must be something else...

**Comment by Beep6581** [comment]
Yes, the preview did not change at all, but playing with that slider caused a reproducible segfault.
How is that slider handled differently to the Exposure slider?
I will report back if I reproduce it with other sliders, hopefully that will give a clue.

**Comment by Beep6581** [comment]
I tried with most other sliders in the Raw tab. I could not reproduce the crash with any of them except for the FCSS sliders - both of them! amsterdam.pef was crashed by twiddling with the X-Trans FCSS slider.

**Comment by heckflosse** [comment]
@Beep6581 I cannot reproduce here. Can you test with [lines 882 to 891 of rawimagesource.cc](https://github.com/Beep6581/RawTherapee/blob/master/rtengine/rawimagesource.cc#L882) commented out?
