### ISSUE TITLE
Panasonic DMC-ZS100

### ISSUE THREAD

**Issue by chpower** [Beep6581/RawTherapee#3315]
Hello I just started using RawTherapee and I can't get my raw photos to look right but my jpg files look fine. Could you check the files I have sent to Github for my Panasonic DMC-ZS100. I followed the instructions for "Adding Support for New Raw Formats.
http://filebin.net/l6hrnr0l4p 

Thank You so much for the great software!
Chris Power

**Comment by iliasg** [comment]
@chpower Chris, Thanks for the samples. RT already has support for ZS100 .. what do you exactly mean by "don't look right" ?.
I only see a problem at your last sample with vignette at an extended area at the right corners !!.

**Comment by Beep6581** [comment]
Chris by not looking right do you mean they just look different?
http://rawpedia.rawtherapee.com/The_Image_Editor_Tab#Eek.21_My_Raw_Photo_Looks_Different_than_the_Camera_JPEG

**Comment by chpower** [comment]
Hello, My raw  images look purple, it seems no mater what adjustments I make I can't stop my images from looking purple. Is it just that I am not familiar with the software? Is this the way they should look with no processing?
I will take a look at the instructions you have sent.

Thank you

**Comment by Beep6581** [comment]
Chris,

> Have you tried opening your raw file in the latest development version?

**Comment by chpower** [comment]
Hi, I converted my raw files to DNG and everything worked. My version is 4.0.12.0 (Ubuntu Linux) would you still suggest installing the latest development version?
What would be the latest version for Linux?

Thank you

**Comment by heckflosse** [comment]
@chpower Can you please post the content of the AboutThisBuild.txt in your rt folder?

**Comment by Beep6581** [comment]
Chris, 4.0.12 is severely, gravely, painfully old. We are about to release RT5.

http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports
> Make sure you use the latest version of RawTherapee as it's likely that a bug in an old version has been fixed in the latest one.

Ubuntu ships latest development versions, they are (misleadingly) called "rawtherapee-unstable", see our Download page. Get the latest one. If you get that and help test, you help make RT5 more stable.

There's no bug here, other than possible improvement for camconst.json. @iliasg the issue is yours.

**Comment by chpower** [comment]
Hi, I installed the latest rawtherapee-unstable from the website and my raw files now look fine. I will send a bug report if I encounter any.
Thank you for all the help.
Chris
