### ISSUE TITLE
Potentially redundant processing - dcrop

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3320]
In `dcrop.cc`, insert this printf:
```
void crop::update (int todo)
{
    mymutex::mylock croplock(cropmutex);
    printf("dcrop update\n");
```

For the first image you open in SETM you get three "dcrop update" lines in the console, while for all subsequent images you get two lines.

**Comment by heckflosse** [comment]
I tried again.
For first image I always get three "dcrop update" lines.
For subsequent images I get two "dcrop update" lines when image size and orientation is the same as current image and three "dcrop update" lines when image size or orientation is different.
