### ISSUE TITLE
SUSE packaging failed

### ISSUE THREAD

**Issue by mbajor** [Beep6581/RawTherapee#3328]
I can't build packages for some SUSE distros. Validator returns error:
`[  894s] I: Program returns random data in a function
[  894s] E: rawtherapee no-return-in-nonvoid-function /home/abuild/rpmbuild/BUILD/rawtherapee-4.2.900/rtgui/lensgeom.cc:143`

**Comment by Floessie** [comment]
I'll take this one now.

**Comment by Floessie** [comment]
@mbajor Should work now. Already merged to master. Please report back here, if this fix wasn't sufficient for the SUSE build to succeed.
