### ISSUE TITLE
Speedup for dcp processing

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#3331]
I created this Issue to make some speedups for processing of raw files when dcp is used.
I already made an (unpublished) about 35% to 40% speedup (without using SSE) but as discussed in another Issue @Floessie and I think, more can be done. So this will get another speedup fun session for @Floessie and me :) I'm really curious about the final result!
First patch follows when fix for #3304 is commited

**Comment by heckflosse** [comment]
I'll create a new branch with the first speedups this evening

**Comment by Floessie** [comment]
Great, looking forward to it. :+1:

I won't have time on the weekend, but will join you occasionally next week.

**Comment by heckflosse** [comment]
@Floessie, ok, I'll make a bunch of commits to keep the overview.

**Comment by heckflosse** [comment]
Ok, let's begin.
Testfile is amsterdam.pef with [this pp3](https://filebin.net/0kthdpnfsyqbrd0c)

I created [this new branch](https://github.com/Beep6581/RawTherapee/tree/dcp_speedup)
I inserted two StopWatches into code.
First change is a first step to speedup the part of dcp which is executed in rgbproc function.
Processing time for rgbproc before second commit was 805 ms, after commit it is 263 ms.
I got no differences in output by this changes.

Next speedup follows soon.

Ingo

**Comment by heckflosse** [comment]
I pushed the next speedup. This time for function DCPProfile::apply()
Processing time before commit was 143 ms. Now it's 74 ms.

Next small speedup follows soon.

Ingo

**Comment by heckflosse** [comment]
I pushed another small speedup. Processing time for rgbproc was 263 ms before, is 243 ms now.

Enough for today,

Ingo

**Comment by heckflosse** [comment]
I pushed some changes. Only cleanup, no additional speedup this time.

**Comment by heckflosse** [comment]
Fixed with ea9dfc9
