### ISSUE TITLE
Rawtherapee forgets checked Autofill-option

### ISSUE THREAD

**Issue by derastronaut** [Beep6581/RawTherapee#3332]
When I reopen a raw file in which I had set the checkbox for Autofill (transform > lens corrections), that checkbox isn't marked anymore.

I'm using the Rawtherapee-PPA by Dariusz Duma (https://launchpad.net/~dhor/+archive/ubuntu/myway/). Last Update was this morning.

This is what the about-button in Rawtherapee under version displays:
Branch: master
Version: 
Changeset: daily
Compiler: x86_64-linux-gnu-gcc 5.3.1
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V2.24.4
Build type: Release
Build flags: -std=c++11 -O3 -std=gnu++11  -Werror=unused-label -fopenmp -Werror=unknown-pragmas
Link flags:   
OpenMP support: ON
MMAP support: ON

**Comment by da-phil** [comment]
I can confirm, I was wondering about that too just an hour ago.
"Autofill" is neither a default option for unprocessed files nor is it checked for already edited files where it was turned on before.

**Comment by heckflosse** [comment]
Confirmed.

**Comment by derastronaut** [comment]
> "Autofill" is neither a default option for unprocessed files nor is it checked for already edited files where it was turned on before.

Sorry for my bad English. I know that this is no default option and of course I meant that I already had set this checkbox during my first edit. Then I closed the raw-file and when I open that file again, the checkbox isn't marked anymore.

**Comment by da-phil** [comment]
It's fine, I just confirmed what you already said ;)
"Autofill" was supposed to be a default option before, you didn't say anything wrong.

**Comment by derastronaut** [comment]
Ok, thanks :)

**Comment by Floessie** [comment]
Isn't that, what #3318 (#1791) was about?

**Comment by heckflosse** [comment]
@Floessie Not for files with already existing profiles with autofill enabled. Just for the case when user newly selects a lcp when autofill was enabled. At least as far as I understood ;-)

**Comment by Floessie** [comment]
@heckflosse So seemingly @Beep6581 overdid a bit. ;)

**Comment by heckflosse** [comment]
;)

**Comment by Beep6581** [comment]
This explains how the logic is supposed to work:

**Comment by Beep6581** [comment]
Bug: If you close a photo with Auto-Fill enabled, regardless whether an LCP is used or not, and you restart RawTherapee, then the photo will load with Auto-Fill disabled if you re-open it in the Editor tab. Cannot reproduce this from the File Browser and cannot reproduce this without restarting RT.

**Comment by derastronaut** [comment]
I've noticed that when I open a new raw-file, RawTherapee automatic adds the entry "(Objektivkorrekturen) Auto-Füllen" (German for Auto-Fill) to the history.

The same happens to edited files.

In the settings I have set that all raw-files will be load in natural-style.

**Comment by Beep6581** [comment]
onUseDistChanged() is fired when opening a file, even when it does not use LCP.
