### ISSUE TITLE
Gray-out perceptual and saturation color conversion for matrix color profiles

### ISSUE THREAD

**Issue by geoderix** [Beep6581/RawTherapee#3335]
As I understand matrix color profiles can't use the perceptual and saturation color conversion intents. But I can choose perceptual and saturation color conversion in RawTherapee and, of course, nothing happens. It misleads those who do not know the subtleties of color space conversion.
Is there any way restrict selection and gray-out perceptual and saturation color conversion for matrix color profiles?
Thank you!

**Comment by Beep6581** [comment]
This is handled by issue #3054
