### ISSUE TITLE
Monitor ICC profile filename text overflows its dropdown box (GTK3, Win7) - UI issue

### ISSUE THREAD

**Issue by dKatara** [Beep6581/RawTherapee#3337]
#### Version info
Running it on Win7 SP1 64bit
Downloaded the release from this exact link: http://www.rawtherapee.com/shared/builds/windows/RawTherapee_WinVista_64_Gtk3_Release_4.2.1005.zip
Version info from the About window:
```
Branch: gtk3
Version: 4.2.1005
Changeset: 20fc105cf8494b58fcf55538f00d12707f5cd70d
Compiler: gcc 5.3.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.18.0
Build type: release
Build flags: -m64 -mwin32 -mthreads -std=gnu++11 -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -msse -msse2 -mwindows -fopenmp -Wno-aggressive-loop-optimizations -DNDEBUG -O3
Link flags: -m64 -mwin32 -mthreads -static-libgcc -mtune=generic -mwindows -s -O3
OpenMP support: ON
MMAP support: ON
```

#### Screenshots
![](http://i.imgur.com/8p7emPO.png)
![](http://i.imgur.com/oY2itSM.png)

#### How to reproduce
Go to Preferences, Color Management tab and load a monitor profile whose filename is long enough to overflow the dropdown box.

#### Bug location
I would assume the problem is in `EditorPanel::MonitorProfileSelector`, around this line: https://github.com/Beep6581/RawTherapee/blob/master/rtgui/editorpanel.cc#L76

Every time you select a different profile, it should set the size of the box enough to fit the text in, or it should truncate the text and add `...` to it.

Unfortunately, I am not familiar with GTK3, so I can't fix this myself.

Cheers,
David.

**Comment by TooWaBoo** [comment]
This is an already known Gtk3 bug.
https://github.com/Beep6581/RawTherapee/issues/3186

cu TooWaBoo

**Comment by Beep6581** [comment]
Thank you for reporting, known issue.
