### ISSUE TITLE
New builds for Windows and macOS

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3339]
@sguyader @gaaned92 @ion12 @helmi03 we just merged master into gtk3. The code now includes important fixes to DCP which was partially broken and went unnoticed for the past month. It would be great if you could make new builds.

**Comment by mglorencin** [comment]
it would really be great if someone could 👍

**Comment by ion12** [comment]
Unfortunately my mac is dead. Second machine in less than two years :(
This time though I discovered that Apple has admitted to a known hardware fault with the gpu on some models and mine is on the list, I hope they will fix it. 
Will try and upload a new build as soon as I can.

**Comment by gaaned92** [comment]
If you are a windows user, you can go [here](https://discuss.pixls.us/t/new-windows-builds/615) starting by the end. You will find 32 and 64 bit builds.

**Comment by Beep6581** [comment]
The latest Windows builds are now on the main site.

**Comment by helmi03** [comment]
https://drive.google.com/folderview?id=0B81lBx1OzJMselN2TTJTUmlJWGs
for branch master. I tried to compile for branch gtk3, but when open from /Application, rt not responding.

**Comment by Beep6581** [comment]
@helmi03 thanks!

I'm a bit worried about this:
```
Processor: i386
Build flags: -march=native
```

What does `gcc -march=native -E -v - </dev/null 2>&1 | grep cc1` show if you run it?

`-march=native` will compile a build which will run only on your type of CPU, so if someone with a different type of CPU downloads the build, it won't run.

Use `-DPROC_TARGET_NUMBER="1"` for a generic build.
See https://github.com/Beep6581/RawTherapee/blob/master/ProcessorTargets.cmake

If you use `-mtune` instead of -march`, then the build will be optimized for the given CPU type, but it will also run on other CPU types. So you could use `-mtune=native` to produce a build optimized for your CPU but which will still run on other CPU types, or replace "native" with whatever architecture you want to target, e.g. `-mtune=corei7`.

**Comment by helmi03** [comment]
I recompiled with -DPROC_TARGET_NUMBER="1" and replaced the files with new build in https://drive.google.com/folderview?id=0B81lBx1OzJMselN2TTJTUmlJWGs

**Comment by Beep6581** [comment]
That looks good, thanks! I'll upload tomorrow.

**Comment by Beep6581** [comment]
Could you compile a new build?
If using GTK+ >=3.20 then use the `gtk3-bugfix` branch,

**Comment by Beep6581** [comment]
@helmi03 do you have a forum account? http://discuss.pixls.us/ 
If so, what is your username?

**Comment by ion12** [comment]
latest gtk2 master built on 10.11 - if it's still useful:

https://filebin.net/krl24lbhii5576xr

I tried the gtk3-bugfix branch again, and again it compiles fine but then app fails to start with same errors I had in the past.
Am I correct that the partha build for gtk3 is not done using macports?
You asked for gdb backtrace and I don't really know how to do that and rawpedia is down, but I'll be happy to do it if someone can explain

**Comment by helmi03** [comment]
gtk3-bugfix for osx 10.12 (4.2.1447, clang-mp-3 3.9.0)

https://filebin.net/kdlrguptt56syza0

Minor changes to rtengine/dcraw.cc (since I got error.txt, maybe clang-3.9 osx specific).
Changes to /tools/osx/macosx_bundle.sh for gtk3 build (see build-gtk3.diff)

**Comment by Floessie** [comment]
@Beep6581 The ambiguity of `std::abs()` is a C++ problem, so I don't think this fix should go upstream. Strictly speaking, the `std::fabs()` solution by @helmi03 isn't equivalent to Dave Coffin's implementation: The problem stems from feeding `std::abs()` with an `unsigned`, IMHO.

@helmi03 Could you try this patch?

```patch
diff --git a/rtengine/dcraw.cc b/rtengine/dcraw.cc
index dcfe66ee..a004a6f1 100644
--- a/rtengine/dcraw.cc
+++ b/rtengine/dcraw.cc
@@ -2011,7 +2011,7 @@ void CLASS hasselblad_correct()
                                             {bhu-1,0},{bhu-1,bwu/2},{bhu-1,bwu-1}};
             for (col = 0; col < bw; col++) {
                 for (i = 0; i < 9; i++) {
-                    ushort dist = (ushort)sqrt(abs(corners[i][0] - row) * abs(corners[i][0] - row) + abs(corners[i][1] - col) * abs(corners[i][1] - col));
+                    ushort dist = (ushort)sqrt(abs((int)(corners[i][0] - row)) * abs((int)(corners[i][0] - row)) + abs((int)(corners[i][1] - col)) * abs((int)(corners[i][1] - col)));
                     ushort weight = dist > maxdist ? 0 : maxdist - dist;
                     corners_weight[9*(row*bw+col)+i] = weight;
                 }
```

Changing it to `std::fabs()` as @helmi03 did won't hurt (@heckflosse correct me, if I'm wrong), because `std::sqrt()` converts to a `double` nevertheless.

Best
Flössie

**Comment by helmi03** [comment]
I successfully compile with patch from @Floessie .

Added new file RawTherapee_OSX_10.12_64_4.2-1447_gtk3-bugfix-patch2.zip at

https://filebin.net/kdlrguptt56syza0

**Comment by Partha1b** [comment]
@Beep6581 Yes, I will look into the macosx bundle and provide patches. I don't use it at the moment.

**Comment by Partha1b** [comment]
@Beep6581 Also, would you please post my build to your system? I might have erroneously send it to you by PM as opposed to post to pixel.us. 

Note that my builds will work with all version Mac from 10.9 on to the latest beta.

**Comment by Beep6581** [comment]
@Partha1b done https://discuss.pixls.us/t/new-nightly-rawtherapee-builds-windows-macos-linux-appimage-other/2924/1
You should be able to edit that with new links.

**Comment by ion12** [comment]
I can confirm that the patch for macosx_bundle in the diff helmi03 put up fixes my issues with the app not starting and I can now build/bundle gtk3 branch correctly as well.

btw is there any further need for gtk2 builds moving forward?

**Comment by Beep6581** [comment]
@ion12 no need for GTK2 builds. For now please use the `gtk3-bugfix` branch until further notice (until Hombre57 merges it into `gtk3`).

**Comment by mandree** [comment]
changing abs() -> std::fabs() on FreeBSD seems to have done the trick, however I haven't run-time tested the conversion for lack of raw material.
