### ISSUE TITLE
Compiling rawtherapee master branch on Debian jessie

### ISSUE THREAD

**Issue by hajakely** [Beep6581/RawTherapee#3340]
Hi everyone!
First I want to thank you all for Rawtherapee. I have been using it since the first time I heard about it in 2012. Until recentely I was using the stable version, unfortunately, the debian jessie repository is quite out dated, so couple of weeks ago I was testing the spot-removal-tool branch. It was working nicely except that the spot removal tool was not working yet (at least for me though). In addition, it was not able to edit jpeg file with it, something that I did before and it worked with the stable version.
So today, I decided to compile the master branch instead. Unfortunately I encounter an error. Everything was working nicely until in the middle of the 'make' command. Here is the error:
```
[ 35%] Building CXX object rtengine/CMakeFiles/rtengine.dir/klt/convolve.cc.o
rtengine/CMakeFiles/rtengine.dir/build.make:1503: recipe for target 'rtengine/CMakeFiles/rtengine.dir/dcp.cc.o' failed
make[2]: *** [rtengine/CMakeFiles/rtengine.dir/dcp.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:161: recipe for target 'rtengine/CMakeFiles/rtengine.dir/all' failed
make[1]: *** [rtengine/CMakeFiles/rtengine.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2
```

I decided to compile the 'newwavelet' branch and that one worked without error.
My operating system is Debian Jessie and I am using the Gnome desktop environment

Thanks in advance and keep up this great work!
Best regards,

Haja

**Comment by Beep6581** [comment]
Hi @hajakely 

Delete the `build` folder, check out `master`, and try again. If it fails again, paste the full log, you can use a pastebin like http://paste2.org/
You should manually delete the `build` folder when switching branches, CMake doens't always pick this up automatically and sometimes that causes build failures.

Which GCC are you using?

**Comment by hajakely** [comment]
Thanks for the quick reply,

I deleted the build folder before I compiled.
I have gcc 4.9.2-2 and 4.9.2-10 installed
The full log when I compiled the master branch is on http://paste2.org/Vw4bWUFA
I just compiled the 'newwavelet' branch and it worked without problem.

**Comment by Beep6581** [comment]
Compiles fine here in GCC-5.3.0, @Floessie do you know how to get this to compile in 4.9?

**Comment by heckflosse** [comment]
I confirm the issue when build on my Sabayon notebook using gcc 4.9.3

**Comment by Floessie** [comment]
@Beep6581 Ah, the fallout. ;) 

@heckflosse Either this way, or change `constexpr Matrix xyz_srgb` to `const Matrix xyz_srgb`, though I would also prefer your solution. But now `iccmatrices.h` looks a bit odd. Maybe we should convert them all to `constexpr`? Shall I? Funny enough, GCC 5 doesn't complain...

@Beep6581 How can I merge a branch here without creating a PR first? Didn't find a corresponding button.

**Comment by Beep6581** [comment]
@Floessie I don't think you can do that via GitHub, you'd have to use command-line.

**Comment by hajakely** [comment]
Thanks everybody for your help!

Cheers;
