### ISSUE TITLE
Compile error in dcp.cc RT version 4.2.1060

### ISSUE THREAD

**Issue by chris-gurgiolo** [Beep6581/RawTherapee#3341]
Hi

The latest rawtherapee version 4.2.1060 fails when trying to compile dcp.cc. There are multiple errors reported concerning the variable xyz_sRGB.  One major clue seems to be an error stating that the variable cannot be declared constexpr.  I am not familiar with c++ but I did go and change the variable declaration from constexpr to const and the routine compile and rawtherapee did successfully compile.  Maybe that what not the thing to do but it worked.

chris

**Comment by Beep6581** [comment]
Hey @chris-gurgiolo 

Please try again now, pull first.

**Comment by chris-gurgiolo** [comment]
Thanks!  That did the trick.  Funny the failed compile was don
immediately followng pull this morning.
       chris
On Sat, 2016-06-11 at 07:57 -0700, Beep6581 wrote:
> Hey @chris-gurgiolo
> Please try again now, pull first.
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
-- 
Chris Gurgiolo
Bitterroot Basic Research Inc.
837 Westside Road
Hamilton, MT 59840-9369

Phone: (406)363-6163
E-Mail: chris@gurgiolo.com

**Comment by Beep6581** [comment]
@chris-gurgiolo FYI, when you post here via email, all your personal information is publicly visible. I deleted it, but keep this in mind. You can post here without using email by going to https://github.com/Beep6581/RawTherapee/issues

Closing.
