### ISSUE TITLE
Trying to use Badpixel filter text file with x-trans sensor

### ISSUE THREAD

**Issue by DavidX81** [Beep6581/RawTherapee#3344]
Hi my name is David.
I love RawTherapee and I thank you very very very much for working on this great free software - it is gorgeous! :-)

I use RawTherapee version 4.3.1005 currently (latest "non-stable"?).
I use Fujifilm X-T1, latest firmware.
I have a (actually more but let's concentrate on one) deadpixel, visible in my pictures/RAW more or less pronounced (depending on surrounding pixels).

I read raw pedia help, and forum / github discussions already, but I found nothing that helped me eventually.
I have placed the "Fujifilm X-T1.badpixels" file in the dark-frame directory and verfified (with verbose=true) that RawTherapee finds it.

I tried with numbers in file offset of +0, +4 and +7 (related to what I read about in various threads found on the net) - nothing helped.
Also I tested putting the offset (tested with all three) in the first row of the ".badpixels" file - didn't help either.
Result in 100% always looks the same, bad pixel doesn't disappear.

No Hotpixel, no Deadpickel preprocessing checkbox checked in GUI
By the way, hotpixel and Deadpickel preprocessing checkbox doesn't help at all (even with changing Treshold).
The only thing that helps a little (pixel and surroundings turn grey but keep visible) is, at Demosaicing ("3-pass") moving "False colout suppression steps" to 1.

Hotpixel native pos 3771 2880.
See Badpixel_DM-Fast.jpg - 100% view, cut.  X-Trans Demosaic: "fast" (so that it can be seen naturally, due it changes with more step optimizing like with 3-pass).
See Badpixel_DM-None.jpg - 100% view, cut.  X-Trans Demosaic: "none".
Original image attached also. The RAW file is in the zip.

Has this feature still bugs (maybe just with X-trans) - or am I doing something wrong?

BTW: My .badpixels file "Fujifilm X-T1.badpixels" looks like this:
`3775 2884`

[FXTB8354.zip](https://github.com/Beep6581/RawTherapee/files/310847/FXTB8354.zip)

![fxtb8354_](https://cloud.githubusercontent.com/assets/19891334/15992383/e90ad5a8-30ca-11e6-9e93-6a3e3248457a.jpg)

![badpixel_dm-fast](https://cloud.githubusercontent.com/assets/19891334/15992342/def7a970-30c9-11e6-8d5a-65ecaa3793e2.jpg)

![badpixel_dm-none](https://cloud.githubusercontent.com/assets/19891334/15992341/d8ed6614-30c9-11e6-9862-bbc9ff345573.jpg)

**Comment by DavidX81** [comment]
Added info about .badpixels file, which I forgot.

**Comment by heckflosse** [comment]
`7`
`3771 2880`

works fine with your file.

**Comment by DavidX81** [comment]
Indeed - thank you very much for your help - I must have missed that particular kind of possible combinations during my tests!

You made me happy, even more than I am with RawTherapee already! :-)

P.S.: So the offset=7 for x-trans ... I think it's not documented so well in rawpedia (http://50.87.144.65/~rt/w/index.php?title=Dark_Frame#Bad_Pixels) and should be reworked?

**Comment by heckflosse** [comment]
I updated [the documentation](http://50.87.144.65/~rt/w/index.php?title=Dark_Frame#Bad_Pixels)

**Comment by DavidX81** [comment]
Great, thanks! ;-)

**Comment by heckflosse** [comment]
You're welcome!
