### ISSUE TITLE
Rework median defines

### ISSUE THREAD

**Issue by Floessie** [Beep6581/RawTherapee#3346]
In #3342 I proposed a cleaner solution for the median define in `rtengine/ffmanager.cc`. @heckflosse was quick to point to the other occurrences scattered across RT. An `rgrep '#define.*med[0-9]'` on current master reveals this:
```
rtengine/dirpyrLab_denoise.cc:#define med3(a,b,c) (a<b ? (b<c ? b : (a<c ? c : a)) : (a<c ? a : (b<c ? c : b)))
rtengine/dirpyrLab_denoise.cc:#define med3x3(a0,a1,a2,a3,a4,a5,a6,a7,a8,median) { \
rtengine/ipwavelet.cc:#define med3(a0,a1,a2,a3,a4,a5,a6,a7,a8,median) { \
rtengine/ipwavelet.cc:#define med2(a0,a1,a2,a3,a4,median) { \
rtengine/ipretinex.cc:#define med3(a0,a1,a2,a3,a4,a5,a6,a7,a8,median) { \
rtengine/improcfun.h:#define med3(a0,a1,a2,a3,a4,a5,a6,a7,a8,median) { \
rtengine/rawimagesource.cc:#define med3x3(a0,a1,a2,a3,a4,a5,a6,a7,a8,median) { \
rtengine/rawimagesource.cc:#define med5(a0,a1,a2,a3,a4,median) { \
rtengine/FTblockDN.cc:#define med2(a0,a1,a2,a3,a4,median) { \
rtengine/FTblockDN.cc:#define med5(a0,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18,a19,a20,a21,a22,a23,a24,median) { \
```

The naming should be changed to correspond to the number of inputs, so `med2` becomes `med4` and `med5` becomes `med25` for example.

Furthermore, at least `med25` could benefit from [`std::nth_element()`](http://en.cppreference.com/w/cpp/algorithm/nth_element).

I'm thinking about providing templates like the one in #3342 and additionally (a) version(s) that take(s) a `std::array<T, N>`.

**Comment by heckflosse** [comment]
@Floessie There is also at least one highly optimized med9 implementation for vfloat (vectorized). It is in [demosaic_algos.cc](https://github.com/Beep6581/RawTherapee/blob/master/rtengine/demosaic_algos.cc#L1767). Maybe there is another one somewhere else.
Also keep in mind that there is a med3 in rt_math.h although it's not named med3. It's 
```inline const _Tp ULIM(const _Tp& a, const _Tp& b, const _Tp& c)``` whic in fact is med3.
There's also a vectorized med3 implementation [here](https://github.com/Beep6581/RawTherapee/blob/master/rtengine/sleefsseavx.c#L1337)

**Comment by Floessie** [comment]
@heckflosse I've begun the revision of the median implementations by extending `rtengine/median.h`. It's far from being finished. I'm thinking about forwarding `median<...>()` to those special implementations like `median5()`, then one could always use `median()` and get the best implementation. What do you think?

[This function](https://github.com/Beep6581/RawTherapee/blob/master/rtengine/FTblockDN.cc#L121) doesn't always return a value, but I think it'll be obsolete when switching to `median()`.

**Comment by heckflosse** [comment]
@Floessie Because median often is performed in the innermost loop, we have to use the best implementation everywhere to not get slowdowns somewhere. But don't worry: I'll test all the places where we use median, for speed (before/after your modifications) ;-)

Thanks for this work!

Ingo

**Comment by Floessie** [comment]
@heckflosse Thank you, Ingo. That's very kind of you. I see the places in code, but it takes a lot of time for me, to identify the right knobs to trigger the code paths. So I'm very glad, that you'll take care of that and can provide me with the right test instructions in case of regressions. I hope, most places will benefit from the new implementation. `fq_sort2()` (mentioned above) for example does a quicksort, whereas `std::nth_element()` is based on a quickselect. The new `median5()` (for types other than `vfloat`) uses only 6 comparisons instead of the original 7. And I've found an interesting paper on minimal comparisons for medians up to 9 elements. Maybe I can make use of it. If not, I'll take the already present algorithms (especially yours for `vfloat` medians). :)

**Comment by Floessie** [comment]
@heckflosse Discussing this with a coworker gave me some new ideas, and I've also found a bug in yesterday's commit. So please hold on with your tests, it's still too early. I'll give you the green light within a few days.

**Comment by heckflosse** [comment]
@Floessie About the median5: The shortest I got is this (used the old ugly macro coding for simplicity):

```
PIX_SORT(p[0],p[1]) ;
PIX_SORT(p[3],p[4]) ;
p[3] = max(p[0],p[3]);
p[1] = min(p[1],p[4]);
PIX_SORT(p[1],p[2]) ;
p[2] = min(p[2],p[3]);
median=max(p[1],p[2]) ;
```

**Comment by Floessie** [comment]
@heckflosse The median5 is okay. `median(std::array<>)` was wrong, because I had a bug in my testbed. Should be fixed now. I renamed all variants to `median` because the compiler will pick the best fitting implementation automatically. :)

Now I have a headache due to median7... Enough for today.

**Comment by heckflosse** [comment]
'headache due to median7' :)

**Comment by Floessie** [comment]
@heckflosse How much are we addicted to optimization? I ask, because median9 seems important, and I could make a version using only [14](http://www.cs.hut.fi/~cessu/selection/) comparisons at most, current implementation takes 19 fixed. median7 had 41 functions to inline, median9 will have 64. So much for my headache. ;)

Making that version will take some time, and it will be lengthy. Do you think, it's worth the effort, or is the quickselect in `std::nth_element()` sufficient?

**Comment by heckflosse** [comment]
@Floessie I have to check the current speed first before I can answer your question. Btw: It is possible to make scalar versions without comparisons using SSE min and max functions and n + 1 sse registers with only first element of each register filled ;-) But that probably would be overkill.
If you want to test the speed of median9 before/after for example you can place a StopWatch in rtengine\FTblockDN.cc line 211 and enable Noise reduction with Median type 3x3

**Comment by Floessie** [comment]
@heckflosse ... much like your [MEDIAN7](https://github.com/Beep6581/RawTherapee/blob/master/rtengine/median.h#L62), I guess? Interesting, indeed. Thanks for the benchmark pointer. I'll definitely try that. As for the median9: I'll try to uncrust my AWK knowledge to automate the inlining a bit.

**Comment by heckflosse** [comment]
@Floessie yes, like the MEDIAN7. You can optimize each of the networksort kind medians this way. Start at last 'compare and swap', eliminate them, go up to next one and so on.

**Comment by heckflosse** [comment]
@Floessie Here's an untested example for median5 which describes the optimization process in meta language:

```
#define PIX_SORT(a,b,temp) {temp = min(a,b);b = max(a,b); a = temp;)


// original version, 13 instructions
PIX_SORT(p[0],p[1],median);  // three instructions
PIX_SORT(p[3],p[4],median);  // three instructions
p[3] = max(p[0],p[3]);       // one instruction
p[1] = min(p[1],p[4]);       // one instruction
PIX_SORT(p[1],p[2],median);  // three instructions
p[2] = min(p[2],p[3]);       // one instruction
median = max(p[1],p[2]);     // one instruction

// first elimination, 12 instructions
PIX_SORT(p[0],p[1],median);  // three instructions
PIX_SORT(p[3],p[4],median);  // three instructions
p[3] = max(p[0],p[3]);       // one instruction
p[1] = min(p[1],p[4]);       // one instruction
median = min(p[1],p[2]);     // one instruction
p[2] = max(p[1]),p[2]);      // one instruction
p[2] = min(p[2],p[3]);       // one instruction
median = max(median,p[2]);   // one instruction

// second elimination, 11 instructions
PIX_SORT(p[0],p[1],median);  // three instructions
median = min(p[3],p[4]);     // one instruction
p[4] = max(p[3],p[4]);       // one instruction
p[3] = max(p[0],median);     // one instruction
p[1] = min(p[1],p[4]);       // one instruction
median = min(p[1],p[2]);     // one instruction
p[2] = max(p[1]),p[2]);      // one instruction
p[2] = min(p[2],p[3]);       // one instruction
median = max(median,p[2]);   // one instruction
```

**Comment by Floessie** [comment]
@heckflosse I've created a little [benchmark](https://gist.github.com/Floessie/a7d57203883569c69f1963b2a41922d7) for the various benchmark implementations I have now. As you've probably expected (and I should have), the branchless SSE version is always the fastest. The 14-compares-version is only faster for integers at `-O0`. Here are the results (in µs on my Skylake with GCC 5.4.0):

Impl | `-O0` | `-O1` | `-O2` | `-O3` | 
----|-----|-----|-----|-----
median | 1676 | 286 | 297 | 271
median7 | 823 | 81 | 57 | 60
median7mm | 751 | 33 | 30 | 30
median7sse | 635 | 32 | 30 | 30

As you already said, the SSE version seems to be overkill.

I think I've understood how to convert those `PIX_SORT` to min/max: Just inline the macro and eliminate independent stores bottom to top. I've just not yet understood how to construct the sorting network in the first place, so I'll take the macros for granted.

**Comment by heckflosse** [comment]
@Floessie I guess the sorting networks are from [this paper](http://ndevilla.free.fr/median/median.pdf)

**Comment by Floessie** [comment]
@heckflosse Yes, I already found them [here](http://ndevilla.free.fr/median/median/src/optmed.c) (btw. from 1998 - when we were young...). Yesterday I took `opt_med7`, expanded the macro with a regex and pruned it. My version now has 21 min/max, whereas yours has only 20. I must have missed one opportunity, but I fail to figure out where. Can you help me?

```c++
template<typename T>
inline T median(T a, T b, T c, T d, T e, T f, T g)
{
    T tmp = std::min(a, f);
    f = std::max(a, f);
    a = tmp;
    tmp = std::min(a, d);
    d = std::max(a, d);
    a = tmp;
    tmp = std::min(b, g);
    g = std::max(b, g);
    b = tmp;
    tmp = std::min(c, e);
    e = std::max(c, e);
    c = tmp;
    b = std::max(a, b);
    tmp = std::min(d, f);
    f = std::max(d, f);
    d = tmp;
    tmp = std::min(c, g);
    g = std::max(c, g);
    d = std::max(tmp, d);
    d = std::min(d, g);
    tmp = std::min(e, f);
    f = std::max(e, f);
    e = std::max(b, tmp);
    tmp = std::min(b, tmp);
    d = std::max(tmp, d);
    return std::min(d, e);
}
```

Thanks,
Flössie

**Comment by heckflosse** [comment]
@Floessie Sure:
```
f = std::max(e, f);
```
can be removed

**Comment by Floessie** [comment]
@heckflosse Oh, I must have been blind! In my only defense: It was Friday night. :) Thanks a lot!

**Comment by heckflosse** [comment]
@Floessie :)

**Comment by heckflosse** [comment]
@Floessie : `from 1998 - when we were young`. Maybe you :) I already had a 3 in first place at that date :)

**Comment by Floessie** [comment]
@heckflosse Well, wouldn't call that old from today's point of view. :)

**Comment by Floessie** [comment]
@heckflosse Now, I think, it's time to test, Ingo. I pruned `median25` to the best I could come up with and tested the result by hammering it 12+h on four cores with randomly shuffled sequences. That's not a full coverage, but I didn't want you to get much older while waiting for my 25! permutations to finish. ;) With my random tests I'm quite confident, as they failed during the process when I made an error.

I've killed the macros I could find, but still I know, there are some more places you mentioned before. Apart from that, there might also be places to vectorize, but this I'll leave to you. The medians are in place. If you find an implementation for `MIDDLE4OF6` (etc. in `rtengine/median.h`) using only a minimal number of temporaries, I'd convert it/them to templates, too.

Now I'm looking forward to your benchmarks.

Best,
Flössie

**Comment by heckflosse** [comment]
@Floessie I'll try to find some free time before weekend to test and benchmark. Too many things on hold currently :(

**Comment by heckflosse** [comment]
@Floessie iirc I already optimized MIDDLE4OF6 to the max... But it's a while ago, maybe I'm wrong...

**Comment by Floessie** [comment]
@heckflosse No problem, so I can convert the other places in the meantime. And take `MIDDLE4OF6` as is. :)

Do I have to protect the `vfloat` variants with `#ifdef __SSE2__` or something?

**Comment by heckflosse** [comment]
@Floessie 'yes' to both questions

**Comment by heckflosse** [comment]
@Floessie I measured performance using your latest commits.
I used a D800 file and measured the following:

- Amaze Demosaic : no difference in speed :+1: 
- lmmse Demosaic : no difference in speed: :+1:
- Denoise median 25 part: more than 3x speed :+1: :+1: :+1: 
- Denoise median 49 part : processing time increased by 7% :-1: 
- Denoise median 81 part: processing time increased by 4% :-1: 

It seems there is some room for improvements. I didn't check for differences in output yet and also didn't measure the other occurrences of median calculation. To be continued...

Thanks for this great work (especially the median 25 :)

Ingo

**Comment by Floessie** [comment]
@heckflosse Ingo, thanks a lot for testing. The 49 and 81 part version now relies on `std::nth_element()` which per se should be as fast as `fq_sort2()`. I suspect the [array initialization](https://github.com/Beep6581/RawTherapee/commit/d82956bbe5df9cba8366f00660c8ac356e1e9a89?diff=unified#diff-230d9b623490c3e055ae81276bf45dd2R237) (which I deliberately added) must have pessimized the result. Can you give me a pointer as to where I should optimally add the `BENCHFUN`?

Thanks again for taking your time to test! :+1:

**Comment by heckflosse** [comment]
@Floessie [this line](https://github.com/Beep6581/RawTherapee/blob/median-rework/rtengine/PF_correct_RT.cc#L1437)
```
tmbb[i][j] = median(srbb[ip][jp], srbb[ip][j], srbb[ip][jn], srbb[i][jp], srbb[i][j], srbb[i][jn], srbb[in][jp], srbb[in][j], srbb[in][jn], tmbb[i][j]);
```
looks buggy.

**Comment by Floessie** [comment]
@heckflosse Yes, obviously I forgot to remove the destination element from the parameter list. Will be fixed...

**Comment by heckflosse** [comment]
@Floessie [here](https://gist.github.com/heckflosse/223895b12722a6a6b637b00c91eb726b) is a fast median13. Code needs to be cleaned. It's about 5x speed of current implementation. The base for it I found [here](http://pages.ripco.net/~jgamble/nw.html). I don't know whether it's optimal but 5x speed should be worth using it :)

**Comment by heckflosse** [comment]
@Floessie I added `BENCHFUN` [here](https://github.com/Beep6581/RawTherapee/blob/median-rework/rtengine/FTblockDN.cc#L100)

**Comment by Floessie** [comment]
@heckflosse Ingo, thanks for the `BENCHFUN` pointer and median13. I'm curious as to where the median13 is needed.

While I'm unfamiliar with Perl, I managed to install [this](https://github.com/hoytech/Algorithm-Networksort-Chooser) program in a VM and was able to obtain a 49 and 81 version. They are lengthy but branchless and might be faster than `std::nth_element()`. I'll give them a try. :)

About the patch: YES, please! :+1: Or just commit on the branch, that's easier.

Thanks
Flössie

**Comment by heckflosse** [comment]
@Floessie median13 is MED_5X5SOFT in rtengine\FTblockDN.cc
I'll try to make a patch. Have to clean the code first after making test code....

**Comment by heckflosse** [comment]
@Floessie [here](https://gist.github.com/heckflosse/3b7c06d09c07337ca4d1f6b97c5c07f7) is a patch

**Comment by Floessie** [comment]
@heckflosse Great, Ingo! And not that hard to comprehend. I'll take care of the cleanup and integrate it. Also `MIDDLE4OF6` is still on my agenda.

How about AVX? Shouldn't that be 8x faster?

**Comment by heckflosse** [comment]
@Floessie Yes, AVX should be faster. But on my AMD FX8350 it's slower when all cores are used because AMD FX8350 has only 1 AVX unit per 2 cores. That does not mean that we should not use it. I simply can not test it reasonably.

**Comment by Floessie** [comment]
@heckflosse Ingo, I just pushed 5cbff43. This gives some nice speedup on my machine for 7x7 and 9x9. Now if you vectorize it, it's going to fly. :)

At first I had a nice solution for the `PIX_SORT` macro for compaction:

```c++
template<typename T>
inline T median(std::array<T, 81> array)
{
    using size_type = typename std::array<T, 81>::size_type;

    T tmp;

    const auto sort = [&array, &tmp](size_type a, size_type b) noexcept {
        tmp = std::min(array[a], array[b]);
        array[b] = std::max(array[a], array[b]);
        array[a] = tmp;
    };

    sort(0, 64);
    sort(1, 65);
    sort(2, 66);
    ...
```

But it turned out to be unstable: Sometimes the compiler would inline it, sometimes not. Now it's fully unrolled again, yielding stable results.

About my AVX question: In your SSE optimization to 5x5 strong you have a fixed stepping of 4. I remember us talking about a vector size constant during our HaldCLUT session, which could be applied here.

Could you take a look at the new `middle4of6()`? Is the interface okay and doesn't it regress?

I've removed the array initialization for 7x7 and 9x9, although it made no difference with the previous implementation. Maybe another compiler version benefits from leaving it out.

HTH
Flössie

**Comment by Floessie** [comment]
@heckflosse Vectorized it myself. Now it flies! :) Please countercheck.

Thanks
Flössie

**Comment by heckflosse** [comment]
@Floessie Some first results:

Vectorized median gave an improvement for >= median25. For < median25 the processing time was almost the same when I compared vectorized to scalar version. Perhaps compiler is able to create good vectorized code up to a number of registers which is below the max. number of sse registers (16 in case of compiling for x86/64). Maybe it's the limited memory bandwidth of my system... Don't know
Nevertheless: The vectorized median >= 25 are really fast now (As you saied, they fly) :+1:

**Comment by heckflosse** [comment]
@Floessie After looking at the amount of work you did (especially for median49 and median81) I really have to take my hat off to you :+1:

**Comment by Floessie** [comment]
@heckflosse Ingo, thanks for testing!

> Vectorized median gave an improvement for >= median25. For < median25 the processing time was almost the same when I compared vectorized to scalar version. Perhaps compiler is able to create good vectorized code up to a number of registers which is below the max. number of sse registers (16 in case of compiling for x86/64).

Same here: At most 1ms faster for the smaller medians. Linking this observation to the register count sounds quite plausible. Now the question: Shall I keep it that way, or remove the SSE code for the smaller medians?

> After looking at the amount of work you did (especially for median49 and median81) I really have to take my hat off to you

Thanks! :) You pushed me on the right track with sorting/selection networks.

For SSE builds we could now remove the "slow" label from the selection. ;)

I'm still pondering over AVX: I think, I'll give it a try and use `VECTLENSP` for the loops. Just out of curiosity...

**Comment by heckflosse** [comment]
@Floessie I would remove the SSE code for the smaller medians to give the compiler a chance to generate even faster code on cpus with AVX512 for example.

About the 'slow' label: We should remove it for all builds because if a build does not use SSE everything is slow anyway and (more important) we can not #ifdef __SSE2__ in language files.

**Comment by Floessie** [comment]
Completed with PR #3377.
