### ISSUE TITLE
Long display profile name overflows selection box bounds in editor tab

### ISSUE THREAD

**Issue by zaltysz** [Beep6581/RawTherapee#3347]
I have a few display profiles with long file names. If I choose one of them to be active in Rawtherapee, its name overflows the bounds of selection box with text "spilling" on other UI elements in editor tab. 
![display_profile_overflow](https://cloud.githubusercontent.com/assets/19934545/16051904/5edfb7e4-326a-11e6-8081-e6dbb99afbb2.png)

Rawtherapee 4.2.1005 x64 on Windows 10.

**Comment by Beep6581** [comment]
Thanks for reporting, this is handled by #3186
