### ISSUE TITLE
OnePlus One (smartphone) DNG file support

### ISSUE THREAD

**Issue by alpharhino** [Beep6581/RawTherapee#3349]
For some reason that I can't seem to find, RawTherapee crashes when I load [this image](https://drive.google.com/open?id=0B5COm6bm6U8WQTd4amxkNkE0eFE) taken on my OnePlus One. Other software seems to have no problem, but RawTherapee shows the photo as black, and then crashes when I double click to open it.  Other DNG's of shorter time open fine, so I am unsure of the problem.
PC Specs: Intel 6700HQ Win10 16GB RAM
Photo Info: ISO 100 Shutter Speed 99s
RawTherapee Version: 4.2.1005

**Comment by NextTherapist** [comment]
Your file seems to be non-standard in some way. I squeezed it through the Adobe DNG Converter and got this file, which opens without a problem: [DNG7.1](https://filebin.net/5rbqscm6guusahk9)

**Comment by alpharhino** [comment]
That's very odd. It works now with the file you posted, but the shutter speed shows up as way off (1/13s). This seems to happen with one specific app and I have no idea why.  The image renders perfectly fine in google drive and snapseed, so I'm not sure what the problem is.

**Comment by iliasg** [comment]
@alpharhino google drive and snapseed do not decode DNGs they just extract and display the embedded in DNG jpeg preview.
Darktable uses libraw as a decoding engine which looks like has better support for DNGs.
Can you report about what WB temp/tint Darktable reports .. and the quality of color ? 

Latest Dcraw 9.27 (RT's decoding engine) also fails on this file, renders it as Black. If anyone can pass the message to Dave Coffin please do (my e-mails are rejected).

There is one more problem with this file. It uses an unusual color profile with no colormatrix1,2 and this is a multiple problem for RT which relies on colormatrix2 for WB calculations and color correction, so 
- RT's WB gets crazy ..
- Color correction fails giving wrong colors even on the modified by DNG converter file. @atorger  had in plan to implement full dcp support for DNG files making full use of the embedded_in_DNG dcp profile .. hopefully he will find the time to do it. 

In the meanwhile we can 
- export the embedded dcp with dcptool http://dcptool.sourceforge.net/Usage.html and use it as custom profile 
- On the converted by AdobeDNG converter, change the colormatrix2 values from 1 0 0 0 1 0 0 0 1 to something like 2.33 -0.89 -0.34 -0.13 1.021 0.034 -0.089 0.414 0.89 (guesswork ..;) ) to overcome WB difficulties

Too much trouble for a very small user base ..

**Comment by alpharhino** [comment]
Is there an easy way to make the DCP into a custom profile? I'm somewhat new to how color profiles work so I want to make sure I'm not missing anything.

**Comment by iliasg** [comment]
In order to have a normal WB behavior, you have to change the colormatrix2 value to the one suggested .. use exiftool for this.

If you already have the extracted dcp 
- name it same as the camera model RT recognizes and then it will be auto selected ..
- or select it by hand as custom

**Comment by alpharhino** [comment]
Got it fixed! [Here](https://drive.google.com/open?id=0B5COm6bm6U8WdkVmWllrYTVKOTA) is a comparison of the photo with and without the color profile (and a few other tweaks). Thanks for all your help

**Comment by Beep6581** [comment]
@alpharhino now that you've been helped, for the benefit of everyone else, you could document step by step what needs to be done to correctly read that raw file. See [here](https://guides.github.com/features/mastering-markdown/) to learn how to write numbered lists.

**Comment by heckflosse** [comment]
Can we close this issue?

**Comment by iliasg** [comment]
Yes .. close it.
The links of the problematic file expired .. I found some samples of the same smartphone (I think ..) which have no problem !! https://www.dropbox.com/sh/30pje0h85il030b/AAAvdPlNpgms-MXPhsHVfFlra?dl=0
So I think the problematic file was a special case (bad firmware ?) which should be corrected by now ..

Lets just keep in mind that it would be usefull to 
- have the option to set priorities in camconst.json so that we can use the camconst color matrix instead of the embedded in DNG as is now 
- Full support of in_DNG embedded profiles
