### ISSUE TITLE
What do we do with the branch "locallab"

### ISSUE THREAD

**Issue by Desmis** [Beep6581/RawTherapee#3351]
All is in the title...
- Is there locallab evolve as proposed by DrSlony ? (in forum)
  or :
- hope do we can create more (than one) local controls
  or : 
- the two ?
  :)

**Comment by heckflosse** [comment]
@Desmis Jacques, sorry, I had not much time to look at how to implement more than one locallab last weeks. Maybe I have a bit more free time next week.

Ingo

**Comment by Desmis** [comment]
@heckflosse 
I think, to verify..., I found a fairly simple way to have, for an image, multiple instances of "Locallab" (3..5.. or more)

It needs (it's holidays...) some weeks to do that work. But I'm pretty confident (I hope) :)

**Comment by heckflosse** [comment]
@Desmis Hello Jacques,
I'm sorry that I didn't find much time to look at the locallab last weeks. I'm curious about the solution you found.
I'm also off to holidays soon for 3 weeks (first week without internet access).

Ingo

**Comment by Desmis** [comment]
@heckflosse 
Ingo
The solution is apparently simple and essentially concerns Rtengine

First I add a slider or a combobox or other control to choose the control point you want to activated (1..2 ..3....6..or more)

In dcrop.cc and Improccoordinator.cc and also simpleprocess.cc; I create a "small database"  (this term is excessive but reflects the principle) type "pp", (ed "mpp" for multiple pp3)  with for each control the value of each "pp3 locallab".
Then, I create a loop ("for" or "while") and for the current control, I exchange the value mpp with pp3.

When I run the loop each "control" is executed with its own "pp3 locallab", and obviously the database is update with good values

All that remains to be done. First step I will try to do a simplified version to see if it works and then we'll see to perfect

Jacques

**Comment by Beep6581** [comment]
Merge into #3421
