### ISSUE TITLE
RT eats all memory (Gtk3)

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#3353]
**RT 4.2.1074 x64 Gtk3, WIN 10 x64, 8GB Ram**
I've developed 53 RAW images in batch processing. After processing of 49 images I've got a Windows message that I run out of memory and I have to quit RT. Virtual memory was set to automatic and the size was set to 1,8 GB. I've increased the virtual memory to 8GB, started the bach processing of the 53 images again and checked the memory usage in the task manger. The memory usage was constantly growing up. I never had any problems about memory in the past and I don't know if this is an RT- or Windows issue.
**Start:**
![start](https://cloud.githubusercontent.com/assets/13800920/16174460/0c0ee6f0-35c3-11e6-805e-c4cfafd0aaaf.png)
**End:**
![end](https://cloud.githubusercontent.com/assets/13800920/16174466/2bc4a4ee-35c3-11e6-9d06-04b276fd0021.png)

**Comment by heckflosse** [comment]
@TooWaBoo is that gtk3 specific or also on gtk2 (master branch)?

**Comment by TooWaBoo** [comment]
@heckflosse 
I've tried it only in Gtk3. I don't have Gtk2 version on my PC

**Comment by heckflosse** [comment]
@TooWaBoo To verify your issue I just started queue processing of more than 200 raw files (default profile) using master (gtk2), Works fine (no increase of used memory)

**Comment by FM33** [comment]
I have the same issue with GTK3 version in Ubuntu 16.04 amd64, 8GB RAM.
While I'm working on photos and then adding them to queue, memory usage of RT process keeps growing. I have to restart RT regularly to clear memory and avoid swapping that is *extremely* slow and performance breaking. Once restarted, the queue is restored, but there is no excessive memory usage.
I usually quit RT when it takes 4-5 GB RAM. After restart it's 200 MB even though queue is still populated.
The growing occurs the most when editing / using history.

There was no issue with GTK2 version under Ubuntu 14.04. Issue began after upgrade, when I started over with GTK3 version.

**Comment by FM33** [comment]
4.2.1152

**Comment by Beep6581** [comment]
@FM33 can you find which processing profile this happens with (i.e. apply the same PP3 to all photos and process them to see whether it happens), and then upload it? If you cannot attach it directly, upload it using http://filebin.net/

**Comment by FM33** [comment]
For me, the growing is not while processing but while editing.

**Comment by TooWaBoo** [comment]
This issuee can be closed 'cause it's fixed by "Contrast by Detail Levels"
