### ISSUE TITLE
ORF Images Distorted 

### ISSUE THREAD

**Issue by naisanza** [Beep6581/RawTherapee#3354]
I don't know what's causing this with a default, vanilla config of RawTherapee

Opened with RawTherapee:

![distorted](https://cloud.githubusercontent.com/assets/1614425/16174815/0f15d63a-35a3-11e6-9d84-a6a6e3a15ac4.jpg)

Opened with Olympus Viewer 3:

![olympus_viewer3](https://cloud.githubusercontent.com/assets/1614425/16174816/1554ecfc-35a3-11e6-8ebe-fdfdaf3cb34c.jpg)

**Comment by TooWaBoo** [comment]
You have to assign a lens correction profile.
Read this:
http://50.87.144.65/~rt/w/index.php?title=Lens/Geometry
...and this:
http://50.87.144.65/~rt/w/index.php?title=How_to_get_LCP_and_DCP_profiles

**Comment by Beep6581** [comment]
@naisanza http://rawpedia.rawtherapee.com/The_Image_Editor_Tab#Eek.21_My_Raw_Photo_Looks_Different_than_the_Camera_JPEG

**Comment by naisanza** [comment]
@TooWaBoo @Beep6581 Thanks guys!

For how important this step is, I'm surprised the program even let me edit the pictures without having a message that says my lens/camera profile isn't found

@TooWaBoo Google Translate to the rescue

@Beep6581 That's a great article! Somehow I didn't find it when I was looking for "image distortion problems." I just started shooting in RAW yesterday
