### ISSUE TITLE
Sony Raw from RX1r II cannot be opened anymore

### ISSUE THREAD

**Issue by marco46** [Beep6581/RawTherapee#3358]
Actually it can be opened but it shows garbage. And in the shell you get the error message:  Unexpected end of file.
It is happening with all files which can be opened by an quite recent version. I will try to bisect the change set if I can find time.

**Comment by heckflosse** [comment]
@marco46 Please upload a problematic file to filebin.net and post the link

**Comment by heckflosse** [comment]
@marco46 I just tried with an RX1r II arw from [here](http://www.photographyblog.com/reviews/sony_cybershot_dsc_rx1r_ii_review/sample_images/) using rt master branch. Worked fine.

**Comment by marco46** [comment]
[example](https://filebin.net/u60avgebblatjvyt)

**Comment by marco46** [comment]
I uploaded a screen shot too.

**Comment by heckflosse** [comment]
@marco46 Issue confirmed. I'll take this

**Comment by heckflosse** [comment]
I bisected. Culprit is 18243db5bafb63595fd561c89a7b7676483ef843
I'll investigate tomorrow...

**Comment by marco46** [comment]
`+  } else if (!strcmp(make,"Sony") && raw_width == 8000) {
+    width -= 32;
+    if (!strncmp(model,"DSC",3)) {
+      tiff_bps = 14;
+      load_raw = &CLASS unpacked_load_raw;
+      black = 512;
+    }`

Does it mean it is always using the uncompressed algorithm for loading?

**Comment by heckflosse** [comment]
@marco46 without looking into details I would say: yes.
But I have to check whether the bug is in dcraw code or in the patch I made for the dcraw update

**Comment by heckflosse** [comment]
It seems the bug is in dcraw code.
Though that doesn't mean I can't fix it. Maybe tomorrow evening...

**Comment by heckflosse** [comment]
@marco46 Thanks for reporting the bug and for the pointer :+1:

**Comment by marco46** [comment]
@heckflosse Thank you for the fast response!

**Comment by heckflosse** [comment]
@marco46 I don't know why this was changed in dcraw code. But I tested the old version and it opens compressed and uncompressed Sony Raw from RX1r II fine whereas the current version does only open uncompressed Sony Raw from RX1r II. I will push a fix soon.
