### ISSUE TITLE
Build failure on Fedora 24

### ISSUE THREAD

**Issue by mbajor** [Beep6581/RawTherapee#3359]
I have a problem with building packages for Fedora 24 - **x86 with -msse2 flag**.

x86_64 and x86 without -msse2 flag build with success

logs:
https://build.opensuse.org/public/build/home:rawtherapee/Fedora_24/i586/rawtherapee/_log
https://build.opensuse.org/public/build/home:rawtherapee/Fedora_24/i586/rawtherapee-gtk3/_log

**Comment by heckflosse** [comment]
@mbajor 
```
[  239s] /home/abuild/rpmbuild/BUILD/rawtherapee-gtk3-4.2.1074/rtengine/rawimage.cc:82:6: internal compiler error: Segmentation fault
[  239s]  void RawImage::get_colorsCoeff( float *pre_mul_, float *scale_mul_, float *cblack_, bool forceAutoWB)
[  239s]       ^~~~~~~~
[  239s] Please submit a full bug report,
[  239s] with preprocessed source if appropriate.
[  239s] See <http://bugzilla.redhat.com/bugzilla> for instructions.
```

looks like a bug in Gnu 6.1.1

**Comment by mbajor** [comment]
@heckflosse Interesting...
Arch and openSUSE Tumbleweed have gcc in the same version and there is no problem with build packages for them.

**Comment by heckflosse** [comment]
@mbajor Marcin, I don't know how to solve an `internal compiler error: Segmentation fault`.
Can you please report this upstream as you have the full logs?

**Comment by mbajor** [comment]
@heckflosse Confirmed bug in gcc
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=77621

**Comment by Floessie** [comment]
If that isn't a good start to the week: RT triggered (its first?) ICE! :tada: Thanks to @mbajor for actually forwarding this problem to the GCC bugzilla. :+1:

**Comment by Floessie** [comment]
... And fixed on GCC trunk r240302. :+1:

**Comment by Beep6581** [comment]
Yay!

There were some other "internal compiler error" bugs reported in the past years though.
