### ISSUE TITLE
Fix Denoise - Median tooltip

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3360]
Fix Denoise - Median tooltip for #3300

**Comment by Beep6581** [comment]
Median 9x9 - remove "slow".

**Comment by heckflosse** [comment]
Done for 'default' language file.

**Comment by Floessie** [comment]
@Beep6581 I'll care about the rest. Will push directly to master.

**Comment by Beep6581** [comment]
@Floessie I pulled before you wrote that comment and had to effectively overwrite your changes, sorry about that.
