### ISSUE TITLE
Speedup for raw preprocessing

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#3362]
I created a [new branch](https://github.com/Beep6581/RawTherapee/commits/preprocess_speedup) with some speedups for raw preprocessing. I measured in queue using the usual D800 file and neutral profile.

Before: 148 ms
After:     83 ms

Edit: Additionally to the speedup the memory consumption of BadPixels bitmap is reduced by factor 8 if bad pixels have to be processed and to zero if bad pixels don't have to be processed.

**Comment by Beep6581** [comment]
Compiles and runs fine.
Haven't timed unpatched. With patch, enabling hot pixel filter takes ("preprocess took") ~70ms, disabling ~20ms.
No difference in output between patched and unpatched.

**Comment by heckflosse** [comment]
8cbdd31
