### ISSUE TITLE
Quick adding same image to queue several times and then deleting the middle entry from queue leads to wrong queue content

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#3363]
To reproduce:

Add the same image 8 times to queue by pressing add to queue button 8 times as fast as you can.
Go to queue tab and remove 4th entry.
Close rt
Start rt
Queue should have 7 entries now, but has less than 7

**Comment by Beep6581** [comment]
Bug confirmed.

**Comment by Floessie** [comment]
@heckflosse What about Windows (not that I care much about it)? Shouldn't you better use `mytime.h`?

**Comment by heckflosse** [comment]
@Floessie I tested on Windows. Works fine because we use msys2

**Comment by Floessie** [comment]
@heckflosse Ah, okay. Sorry for the noise.

**Comment by Beep6581** [comment]
Fix confirmed.
