### ISSUE TITLE
Exif lost when saving compressed tiff from raw on windows builds

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#3370]
To reproduce:

open a raw file
save to compressed tiff
open the tiff

there's only the exif header line but no content

works fine on Linux

Uncompressed tiff works fine too (because we don't use libtiff to save uncompressed tiff)

Can a windows user please confirm this?

**Comment by gaaned92** [comment]
For compressed tiff, exiftool complains "bad format(63379)for ExifIFD entry 0".
OK for uncompressed tiff

**Comment by heckflosse** [comment]
@gaaned92 Thanks for confirming the bug

**Comment by heckflosse** [comment]
@Beep6581 @Floessie Can you test this on Linux please?

**Comment by heckflosse** [comment]
@Floessie Thanks for testing :+1:

**Comment by Beep6581** [comment]
Compiles and works fine, except for one thing. I saved amsterdam.pef as a 16-bit TIFF compressed and uncompressed.

Uncompressed:
```
-MakerNotes:SRHalfPressTime=1.80 s
-MakerNotes:SRFocalLength=106 mm
```

Compressed:
```
-MakerNotes:SRHalfPressTime=0.08 s
-MakerNotes:SRFocalLength=26 mm
```

**Comment by Beep6581** [comment]
I deleted the cache folder and saved two uncompressed files and two compressed ones. Both compressed ones match, both uncompressed ones match, and both types differ between each other as above.

**Comment by Beep6581** [comment]
Reproduced the bug in 2710bcd so its not caused by this patch.

**Comment by heckflosse** [comment]
@Beep6581 Maybe you found the reason for [this comment](https://github.com/heckflosse/RawTherapee/blob/master/rtengine/imageio.cc#L1296)
