### ISSUE TITLE
Canon EOS-1D mkII raw files are rendered as flat black

### ISSUE THREAD

**Issue by henrym11106** [Beep6581/RawTherapee#3373]
I'm using the dhor/myway/ubuntu xenial repo and the issue appeared around two weeks ago in the development release. I also just compiled from Git with the same results.
the stable 4.2-4 ubuntu release is fine.

I've tried every image processing setting without luck. raw white and black points do nothing, color profiles, exposure adjustments, new and old processing profiles, etc. 

the working preview and exported image is completely black. the metadata is correct, though.

unedited raw files have normal thumbnail previews. newly opened files get black thumbnails. images exported pre-bug reflect the exported image for a few seconds before blacking out on their own.

so far only canon 1d mkII .cr2 files are affected.

**Comment by Floessie** [comment]
@henrym11106 Thanks for reporting this issue. Could you please provide us with a sample CR2 file, optimally through [filebin.net](http://filebin.net/)?
