### ISSUE TITLE
Enhancement request: Manual input of focus distance for LCP 

### ISSUE THREAD

**Issue by zaltysz** [Beep6581/RawTherapee#3374]
As I understand, CA correction using LCP works only when image contains focus distance in EXIF. Lots of cameras do not add required tag, so images taken with them can't be CA corrected (using information in LCP) despite having full LCPs (made by using either other cameras, which add focus distance information, or made from images to which focus distance was added manually).

I propose an input box with spinner to be showed in "Lens correction profile" part of GUI for manually entering focus distance when image lacks Focus distance information in EXIF.

**Comment by Beep6581** [comment]
While this is a feature I could implement, its one almost nobody else would use which makes me not keen on spending time doing it. More importantly, RawTherapee is getting lensfun support. Lensfun is a library for correcting lens-related issues. Once that's in place, this won't be a problem for you. As such, I'm closing this.
