### ISSUE TITLE
Enable whole area of magnification windows for moving

### ISSUE THREAD

**Issue by da-phil** [Beep6581/RawTherapee#3378]
I guess that applies to all RT versions so far, I'm currently using the latest version (4.2.969) from master branch.

When you add a magnification window to a picture, only the rectangular border region can be used for dragging it around, sometimes this is quite cumbersome to precisely click on the border of the window. 
Wouldn't it make sense to enable the whole area of the rectangle for dragging around?
I can't imagine a scenario where strongly overlapping rectangles would make it difficult to distinguish between them for moving action.

**Comment by heckflosse** [comment]
@da-phil I you mean [this](https://filebin.net/nd3zno7tlnubp7zs/detailwindow.png) then it's easy to [fix](https://filebin.net/nd3zno7tlnubp7zs/detailwindowmove.patch)

Ingo

**Comment by Beep6581** [comment]
+1 for making it possible to move the red area by clicking inside it. Not +1 if you mean the detail window in the top-right corner of the canvas.

**Comment by da-phil** [comment]
jup, I mean the detail or magnification windows you can add to the workspace. if it's that simple, can you please include this patch @heckflosse? :P

**Comment by heckflosse** [comment]
@da-phil Yes, should be no problem :) I'll do that tomorrow
