### ISSUE TITLE
Wrong thumbnail orientation and unintended "crop" (in the top panel of the editor)

### ISSUE THREAD

**Issue by pi99y** [Beep6581/RawTherapee#3384]
Hi,
I've noticed this for some time now (maybe for like a year) that **sometimes** (I'm not quite sure how to recreate, but it **might have something to do with applying or copy/pasting profiles**) the thumbnails of the top panel in the editor view are displayed in the wrong orientation, while the image remains in a opposite orientation - resulting in a cut/cropped image that does not represent the actual image or it's crop (see attached screenshot).
Notice that it also brakes the thumbnails layout - no space between the broken thumbnail and the next to its right.

It goes away if you re-launch RT or maybe even if you just switch directories - so it might be thumbnail cache related.

I've been using the various (I try to stay up to date) "master" branch builds (Win 64bit) all this time and I'm on Win 8.1.

![rt-orientation_](https://cloud.githubusercontent.com/assets/10639257/16870380/7aa0c930-4a81-11e6-8c8f-71a4572a70c1.jpg)

**Comment by Floessie** [comment]
@heckflosse I remember having provided a patch for this in another issue. The problem was a missing lock in a trivial function. I can't find the issue right now, but I talked about the "Monitor" pattern there. Perhaps you can find the issue and the patch. Thanks.

**Comment by Floessie** [comment]
@Beep6581 It's in #3304. Don't know, if it ever got included in master.

**Comment by Beep6581** [comment]
Hey, I was away on holiday and am back now.
#3304 and its bugfix branch fix-dcp-race-and-store were merged, but you spoke of some additional speedups which appear not to have been done yet. @Floessie your `lock(mutex);` fix is not in master. Should it be added? If so, I can test if you prepare a patch or branch.

**Comment by Floessie** [comment]
@Beep6581 Hej! I'm still on holiday, so I can't currently provide you with a patch other than the one in #3304. And yes, the `MyMutex::MyLock lock(mutex);` line should suffice. You can of course try it, it did fix the problem for me.

A few days ago I introduced RT to a friend who uses Windows. This bug here appeared immediately as well as #3387 (or something similar). :(

Hej så länge!
Flössie

**Comment by Beep6581** [comment]
Ah, if it's that simple then I'll try it and commit it with @heckflosse's blessings!
Enjoy your holiday :)

**Comment by Beep6581** [comment]
@Floessie hey, sorry for the off-topic: I sent you a message on [discuss](http://discuss.pixls.us/) some weeks ago regarding coverity, could you check your discuss inbox? Click on your profile picture icon in the top-right corner, and then click on the mail icon.

**Comment by Floessie** [comment]
@Beep6581 Sorry, must have missed your message. I'm currently unable to receive from my Gmail account with my elderly Claws Mail. I've got to upgrade my server (long due) first, there will be al lot of messages waiting... The Gmail web frontend is unavailable to me from this WiFi access, cause it's VPNed to another country and Google won't let me in from there without SMS confirmation. That's more than I can bear in the security vs. anonymity arena. ;) I'll come back to your offer (read it in the meantime) as soon as I can mail you directly again. Thanks.

**Comment by pi99y** [comment]
Hi, while I haven't seen the bug lately and have considered it fixed I saw it again today. (Maybe it appears only for certain cases now?  Like here for the last photo? = guessing)

![again](https://cloud.githubusercontent.com/assets/10639257/20441764/29453e56-adc6-11e6-861b-bc75bebf1967.jpg)



This was on a latest Ubuntu "daily/dev" build from http://ppa.launchpad.net/dhor/myway/ubuntu
I don't know why the version number is absent from the "About" menu in Ubuntu builds - so I can't report the version number:

```
Branch: master
Version: 
Changeset: daily
Compiler: x86_64-linux-gnu-gcc 5.4.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V2.24.4
Build type: Release
Build flags: -std=c++11 -O3 -std=gnu++11  -Werror=unused-label -fopenmp -Werror=unknown-pragmas
Link flags:   
OpenMP support: ON
MMAP support: ON
```
