### ISSUE TITLE
Add in "About" information about OpenCL enable/disable

### ISSUE THREAD

**Issue by ezombie** [Beep6581/RawTherapee#3385]
Branch: master
Version: 4.2.995
Changeset: 57e95a35c23fb748f9fd8bf9ecdecf7fa1b4fec6
Compiler: cc 6.1.1
Processor: phenomX4
System: Linux
Bit depth: 64 bits
Gtkmm: V2.24.4
Build type: release
Build flags:  -Wno-unused-result -Wno-aggressive-loop-optimizations -std=gnu++11 -march=amdfam10 -Werror=unused-label -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG
Link flags:  -march=amdfam10
OpenMP support: ON
MMAP support: ON

OpenCL support: ON/OFF

**Comment by Beep6581** [comment]
RawTherapee does not support OpenCL, so "OpenCL support: OFF".
