### ISSUE TITLE
Wavelet subtools should be disabled by default

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3386]
Currently all Wavelet sub-tools are enabled by default. They should be disabled by default.

**Comment by lvreclp** [comment]
Hello. I would like to help developing RawTherapee. Could I take this enhancement request to handle?

**Comment by Beep6581** [comment]
Hey @lvreclp , sure!

**Comment by heckflosse** [comment]
@lvreclp You're still alive?

**Comment by Beep6581** [comment]
Ok to merge?

**Comment by heckflosse** [comment]
Ok

**Comment by Beep6581** [comment]
Done.
