### ISSUE TITLE
did you forget make tags or releases ? 

### ISSUE THREAD

**Issue by sergiomb2** [Beep6581/RawTherapee#3388]
tag 4.2

@Beep6581 Beep6581 tagged this on 24 Oct 2014 · **995 commits** to master since this tag

**Comment by sergiomb2** [comment]
Hello , I'm sorry, I was flagged by github ,  I see in  https://build.opensuse.org/package/show/home:rawtherapee/rawtherapee, rawtherapee-4.2.1002.tar.bz2   I deduce that is commit 1002 after last release 4.2 . 
As package maintainer of Fedora I emphasize:  If you do a tag, we (distros) could package the same thing and test the same thing and start work on that , is just group some commits, no more than that.

**Comment by Beep6581** [comment]
We're quite aware of that. A new version will be tagged when its ready. It's not ready yet.
