### ISSUE TITLE
Memory leak in preview rendering of "Contrast by Detail Levels"

### ISSUE THREAD

**Issue by midluk** [Beep6581/RawTherapee#3389]
I recently tried to edit some photos with the "Contrast by Detail Levels" tool enabled.
After some (50-100) photos, I noticed some significant memory usage (>12GiB).
When zooming in and out in any photo repeatedly, I can quickly produce a significant rise in memory usage.
When I disable the "Contrast by Detail Levels" tool, I don't see a significant rise in memory usage.
So there seems to be a memory leak in the preview rendering of the "Contrast by Detail Levels" tool.
I have not noticed increased memory usage during export, even with a few hundred photos.

I have attached the pp3 (renamed to txt) for one of the photos to quickly reproduce.
[IMG_8967.CR2.txt](https://github.com/Beep6581/RawTherapee/files/381050/IMG_8967.CR2.txt)

This is self-compiled from git master on Fedora 24 x86_64.
> Branch: master
> Version: 4.2.995
> Changeset: 57e95a35c23fb748f9fd8bf9ecdecf7fa1b4fec6
> Compiler: cc 6.1.1
> Processor: x86_64
> System: Linux
> Bit depth: 64 bits
> Gtkmm: V2.24.4
> Build type: Release
> Build flags:  -std=gnu++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-> pragmas -O3 -DNDEBUG
> Link flags:  -march=native
> OpenMP support: ON
> MMAP support: ON

**Comment by TooWaBoo** [comment]
I still have reported a memory leak here: https://github.com/Beep6581/RawTherapee/issues/3353

I can confirm, that disabling "Contrast by Detail" will solve it. So ther is a bug in the "Contrast by Detail" tool.

**Comment by midluk** [comment]
Might indeed be a duplicate of #3353, even though I'm using the gtk2 version (assuming that this is still the default).
I exported about 200 images yesterday with Contrast by Detail Levels activated and RES memory usage stayed below 2GiB. Might still be some memory leak somewhere, but the total leaked memory seems to be less than the usual fluctuations that can be seen during image processing.
In top, VIRT memory usage climed to 40GiB, though. On a 32 bit system this would have run out of address space quite fast. Does RT memory map the input images and does not unmap them again?
