### ISSUE TITLE
Segfault after using haldclut

### ISSUE THREAD

**Issue by meownoid** [Beep6581/RawTherapee#3391]
After using haldclut (Color -> Kodak -> Porta 160 2) on the one of the images I've keep getting segfaults on every action (double-clicking on image, clicking on File browser tab, right-clicking on image). After restart I can do what I want, but only once. Then I get segfault again.
Core dump: https://yadi.sk/d/ffbzL5amtntvy

**Comment by Beep6581** [comment]
http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports

**Comment by meownoid** [comment]
https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by Beep6581** [comment]
Thanks! :)
