### ISSUE TITLE
 RT crashes using RAF from Fuji XE2-S

### ISSUE THREAD

**Issue by Franckel** [Beep6581/RawTherapee#3393]
Hi all,

I use RT v 4.2.0 installed on Linux Mint 17.2 Cinnamon and have an issue with RAF from my Fuji XE-2S : Each time I open RAF, RT close immediately after a brief opening.
I also own a Fuji XT-1 and have no issue with it.
If I open a folder containing RAF from both gears, RT remain opened, I can treat RAF from XT-1, but if I double-click on a RAF from XE2-S, RT close and cannot be opened anymore until I open another folder.

I spent a lot of time googling for same issue without finding a solution.

Am I alone with this issue ?

Thanks in advance.

Franck

**Comment by heckflosse** [comment]
@Franckel 4.2.0 is really old. Can you upload one file to filebin.net and post the link here to allow us to check whether the problem still exists in master branch?

Ingo

**Comment by Franckel** [comment]
Hi Ingo, 
Thanks for your quick reply.
4.2.0 is the version available in the repository for my Linux Mint. Don't know how to upgrade neither where to look for the latest version.
Whatever, what I don't understand that I don't have the issue with my XT-1 latest firmware.
Here is the link for one of the file causing the issue : https://filebin.net/401a8j3fmzhfqmil
Thanks for your help.
Regards,
Franckel

**Comment by heckflosse** [comment]
@Franckel Your file opens fine in latest rt version. I'm developing on windows, not on linux, but if you read this http://50.87.144.65/~rt/w/index.php?title=Linux and follow the insrtuctions, you will be able to build rt based on latest sources!

**Comment by Franckel** [comment]
Thanks ingo, I'll give it a try.
However, I tried an upgrade and my Linux version replied me that 4.2.0 was the latest version available.
Maybe it's my Linux that is too old ;-) and doesn't support newer version of RT.
I will try tomorrow as it's late in the evening here in France.
Thanks again.

**Comment by heckflosse** [comment]
@Franckel Don't hesitate to ask for help if you have problems building rt on linux!

**Comment by Franckel** [comment]
OK, many thanks :-)
Help much appreciated.

Nice shot !!! ;-) (bud bad weather...) :-))

**Comment by Franckel** [comment]
Hi all,
Just FYI, I tried to run the unstable version of RT. Unfortunatly, the problem remains the same.

**Comment by heckflosse** [comment]
@Franckel Did you try the latest development build too? As we don't build packages for Linux ourself we don't know which version the latest 'unstable' version for your OS is (especially because for whatever reason the version is not included in the 'unstable' builds by the package maintainer).
Easiest way is to compile latest version by following the instructions I linked above.

Ingo

**Comment by Franckel** [comment]
@heckflosse Yes, I did. The unstable and the fresh one.
I'm downloading the latest version of my OS (Linux Mint 18) and will try in live session.
As I never compile nor built a program, I want to have and take my time to do it.
I believe it will be a very interesting experience ;-)
Will keep you informed.
Thanks again :-)

**Comment by heckflosse** [comment]
@Franckel I had a look at https://launchpad.net/rawtherapee-unstable
The latest unstable version for Ubuntu is from January 2016 :(

Ingo

**Comment by heckflosse** [comment]
@Franckel Update: I confirm that the latest 'official' unstable version crashes with your raw but the current development version opens it fine on the same OS.

**Comment by Franckel** [comment]
@heckflosse Thanks a lot for your time spending to my problem.
In my repositories, I have 3 different versions available for my actual OS : 1 labelled 'stable', 1 labelled 'unstable' and 1 labelled 'fresh'. The last 2 ones are in development.
But, I tried the 3 and have the issue.
So, I'm now sure that my OS is too old for the very latest version of RT.
I'm just creating the live usb stick for Linux Mint 18 and will try the live session and will come back to inform you.

**Comment by heckflosse** [comment]
@Franckel Ok, I'll wait :+1:

**Comment by Franckel** [comment]
@heckflosse OK, I confirm that my Linux Mint 17.2 is too old.
I tried with Linux Mint 18 and surprisingly, the RT version was the same : 4.2.0 and didn't work.
I installed the unstable version (last modified two days ago) and it was OK.
Effectively, the last unstable version for ubuntu 14.04 is dated on January 2016.
So the conclusion is : I have to update my OS or use a live session or dual boot on the latest one.
I will try to compile the latest version as advised by you.

Thank you so much Ingo for the time you spent on my problem. Very much appreciated. :-)

**Comment by heckflosse** [comment]
@Franckel You're welcome! Compiling rt on your machine is the best solution for several reasons:

1.) You don't have to rely on package builders
2.) You'll be up to date with latest bug fixes
3.) Compiling rt on your machine does not restrict to SSE2 (as the packaged build does) but optimizes for SSE4.1 and FMA if your CPU supports that features. On my CPU, the speed performance difference between packaged build (SSE2) and native build (SSE2, SSE3, SSE4, FMA) is about 10%.

Ingo
