### ISSUE TITLE
I cannot save an edited file.

### ISSUE THREAD

**Issue by drshortcutify** [Beep6581/RawTherapee#3394]
Hello there,

I use a brand new macbook running OS X (El Capitan 10.11.4, processor 1.2 GHz Intel Core m5) and I just downloaded RT 4.2.349 from http://rawtherapee.com/downloads (4.2.876). 

Without having touched any setting, I just tried to get myself familiar with the interface. So I opened a RAW image, applied some basic edits (like exposure) and tried to save it both by clicking on the save button in the bottom right and through command+s. I then chose the folder where I wanted the file to be saved, and every time I get a 'no entry' road sign with the path to the folder. Once or twice I got an 'error saving file' message. After that more often than not RT freezes.

I contacted Apple and went through all the permissions on the machine and they told me that I have the right permissions as administrator and that the issue may come from RT. 

Please help! I really want to use your software! Thank you so much in advance! Regards. RZ.

Branch: master
Version: 4.2.349
Changeset: a7db8f001ce1bccb93bc31d64f0165db5527da5a
Compiler: clang 3.5.0
Processor: generic x86
System: Apple
Bit depth: 64 bits
Gtkmm: V2.24.4
Build type: Release
Build flags: -I/opt/local/include/libomp -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG
Link flags:  -mtune=generic
OpenMP support: ON
MMAP support: ON

**Comment by Beep6581** [comment]
Hey

Where are you trying to save to?
When you're in the Editor tab, press Ctrl+s so that the "Save" window pops up, select a folder, make sure "Save immediately" is ticked. Take a screenshot and show us here. Then click OK. What happens? Take another screenshot if there's an error message.

**Comment by drshortcutify** [comment]
Thanks for your answer. I try to save in my pictures folder on my hard disk. I have attached two screenshots, one of the save page and one of the error message that I receive immediately after having pressed ok.

<img width="1280" alt="screenshot 2016-08-17 14 52 03" src="https://cloud.githubusercontent.com/assets/21059628/17736962/715576da-6482-11e6-9e73-3c20eb91640a.png">
<img width="1280" alt="screenshot 2016-08-17 14 52 11" src="https://cloud.githubusercontent.com/assets/21059628/17736961/70f2ab7c-6482-11e6-8d46-a697c05fd19f.png">

**Comment by drshortcutify** [comment]
Err... I have a hard time understanding why but now everything seems to be working like a charm. I can't explain it.

**Comment by Beep6581** [comment]
Are you logged in as the "TheRez" user? Was anything removable or network mounted?
