### ISSUE TITLE
unrelated bulk changes cause saturation setting to double its value

### ISSUE THREAD

**Issue by spodzone** [Beep6581/RawTherapee#3395]
**Background**:
I have version
rawtherapee 1:4.2+448.g26d182d-3
from arch linux.

**Sample files** (Olympus Pen-F and a custom profile):
http://misc.sty.nu/P8135296.ORF.pp3 and http://misc.sty.nu/P8135296.ORF 

**Method**:
From the File Browser pane, duplicate this ORF file a couple of times. Check in the Exposure tab and the saturation should be 36 (looks reasonable to me - make a mental note of the shade of yellow it gives). 
Now select all 3 images and in the Transform tab, enable Resize (with this profile, it should enable scaling with a factor 1.33). 

**Result**: 
All 3 images turn a lurid shade of thicker sludgy yellow as the saturation doubles to 72.

It does seem to require multiple images selected to happen, and obviously saturation needs to be nonzero to start with.

**Comment by heckflosse** [comment]
Issue confirmed

**Comment by spodzone** [comment]
Looks good to me. Many thanks!

**Comment by heckflosse** [comment]
@spodzone You're welcome!
