### ISSUE TITLE
Ciecam02: Wrong transition curve

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#3398]
I found a possibly wrong curve in [color.cc function skinredfloat()](https://github.com/Beep6581/RawTherapee/blob/master/rtengine/color.cc#L1785) which is used in ciecam02 Algorithm 'Lightness + Chroma (JC)'.

If you plot this [curve](https://filebin.net/p3cwkquvz6xnh5ju/ciecamcurve.png) you'll see a break at J = 22.
For simplicity the plot only shows range 16 <= J <= 70.
Changing the calculation from

`dred = 4.1666f * J - 26.6f;`

to

`dred = 2.5f * J;`

would result in a [continuous function](https://filebin.net/p3cwkquvz6xnh5ju/ciecamcurve2.png).

@Desmis Jacques, what do you think?

Ingo

**Comment by Desmis** [comment]
@heckflosse 

Hello Ingo.

I am still in "holiday" with my grandchildren. So little time to devote to RT.
But as always you're right. There is a bug in the calculation of the transition and the answer is that you propose: dred = 2.5f * J ;

Jacques
