### ISSUE TITLE
New OS X builds

### ISSUE THREAD

**Issue by ion12** [Beep6581/RawTherapee#3399]
@Beep6581 

Finally got my work machine back in operation, new build for OS X, done in 10.11.6

https://filebin.net/p63v8x2dyspir1u0

Can also confirm that the new edit in Gimp command line is working correctly.

I can compile the gtk3 branch without errors but when I try to start it it crashes immediately
[BUG-build_gtk3.txt](https://github.com/Beep6581/RawTherapee/files/428804/BUG-build_gtk3.txt)

Looking at the sources, it seems that are a few places where gtk2 is hardcoded in
`/tools/osx/macosx_bundle.sh`
Not sure if I'm reading it right, but perhaps that could be an issue?

Unfortunately I have zero time to work on this before the end of the month, but if anyone can figure out what to change and wants me to just try and recompile a patch that should be fine.
Otherwise I can try and be more active in figuring it out next month

**Comment by Beep6581** [comment]
Great, and great! I will upload soon...

As for your crash:
1. Please try compiling a debug build and [show a stack backtrace from GDB](http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports#When_RawTherapee_crashes_-_An_introduction_to_stack_backtraces). This Apple-style stack backtrace makes my head spin.
2. Which version of gtk+ and gtkmm are you using? All I see in the log is "3.0.1", and that can't be correct, it would be too old. For reference, I'm using gtk+ 3.18.9 and gtkmm 3.18.1.
I can take a look at the `macosx_bundle.sh` script over the week, maybe I get lucky, but I'd first like to know points 1 and 2.

**Comment by ion12** [comment]
@Beep6581 
Will get back to you with GDB backtrace and gtk+ & gtkmm versions at the beginning of next month.
Unfortunately I really can't follow up anything at the moment as I have a stressful deadline early next week :)

**Comment by Beep6581** [comment]
No problem. Please report that in a new bug report issue, I'll close this one as the builds have already been uploaded.
