### ISSUE TITLE
Update to Serbian translation

### ISSUE THREAD

**Issue by gpopac** [Beep6581/RawTherapee#3402]
Hello RT team,

I updated Serbian translation for RawTherapee some time ago. Could you commit this to the project? Not everything is translated to meet the last changes in the main branch, but I will not have the time for this soon.

[Serbian (Cyrilic Characters).txt](https://github.com/Beep6581/RawTherapee/files/433776/Serbian.Cyrilic.Characters.txt)
[Serbian (Latin Characters).txt](https://github.com/Beep6581/RawTherapee/files/433777/Serbian.Latin.Characters.txt)

**Comment by Beep6581** [comment]
Thank you, updating.
