### ISSUE TITLE
Speedups for black&white conversions

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#3405]
I started a [new branch](https://github.com/Beep6581/RawTherapee/commits/bwspeedups) with some speedups for b&w conversions. Further speedups and cleanups will follow before I create a PR

Ingo

**Comment by heckflosse** [comment]
One result from above patch:

b&w Luminance Equalizer with Green Gamma correction set to 10 measured with usual D800 file:
before: 2536 ms
after:    1448 ms

**Comment by heckflosse** [comment]
I added a commit to the branch. Processing time for the example from above is now 1191 ms.

**Comment by Hombre57** [comment]
Less than half the initial time, quite impressive as usual ! Works fine here.

**Comment by Hombre57** [comment]
Just tested it in Release mode, i.e. with optimizations but w/o timers.

**Comment by heckflosse** [comment]
Fixed with eb3c661
