### ISSUE TITLE
Artifacts in blue highlights 

### ISSUE THREAD

**Issue by romandocent** [Beep6581/RawTherapee#3408]
I have troubles in work with highlights caused by blue, mostly LED lights. 
I use Nikon D600 and there is no native icm or dcp included in RT like for D700 or other cameras, so I forced to use "Camera Standard" default option in Color Management. I found dcp for D600 somewhere in internet, but it doesn't fit in most cases. RT 4.2.1152 under Ubuntu 16.04. Watch please screenshots of this bug (100% crops of problem areas).

Here was blue lights on the bridge. 
This is what camera jpeg does:
[http://img-fotki.yandex.ru/get/52325/17692153.45/0_cf4c5_fe61bde4_orig]
This is "default", amaze demosaic settings of RT:
[http://img-fotki.yandex.ru/get/31690/17692153.45/0_cf4c7_84bc1662_orig]
This is "default iso high" with white balance taken from gray asphalt:
[http://img-fotki.yandex.ru/get/118251/17692153.45/0_cf4c8_8e3dd301_orig]
This one processed with handmade nikon d600 dcp found in internet (almost ok in highlights, but other colors are incorrect):
[http://img-fotki.yandex.ru/get/93451/17692153.45/0_cf4c6_8d4a754d_orig])

Next one example. 
Camera jpeg (highlights are ok on my opinion):
[http://img-fotki.yandex.ru/get/62935/17692153.45/0_cf4d1_d4f30316_orig]
"default"+amaze demosaic in RT (worse!):
[https://img-fotki.yandex.ru/get/62935/17692153.45/0_cf4d0_65a39a6_orig]
Processed with Immse with enhancement steps 6 and false color steps 5 (much better, but still no good in comparison camera jpeg): 
[http://img-fotki.yandex.ru/get/59115/17692153.45/0_cf4cf_e35e0d_orig]

Next example.
Camera jpeg (watch blue led-light lines):
[http://img-fotki.yandex.ru/get/31690/17692153.45/0_cf4ce_61e86b28_orig]
"default"+amaze (worse!):
[http://img-fotki.yandex.ru/get/53638/17692153.45/0_cf4cd_26db720b_orig]
"default"+immse (better but...):
[http://img-fotki.yandex.ru/get/45082/17692153.45/0_cf4cc_7ff25f55_orig]

Last one.
Camera jpeg (ok):
[http://img-fotki.yandex.ru/get/109793/17692153.45/0_cf4cb_f29771f2_orig]
default+amaze (uh!):
[http://img-fotki.yandex.ru/get/118251/17692153.45/0_cf4ca_aab63a59_orig] 
immse and other process but still worse:
[http://img-fotki.yandex.ru/get/96333/17692153.45/0_cf4c9_db3a017d_orig]

What to do with it. Tried almost everything, but RT fails with this blue leds ((.
I can send you links to .nef by mail.

**Comment by TooWaBoo** [comment]
Here's another thread about those artifacts: https://github.com/Beep6581/RawTherapee/issues/2897
It belongs to the dcp profile.

**Comment by heckflosse** [comment]
Is that Issue still valid and reprocucible?. If not, I'll close it soon!

Ingo

**Comment by TooWaBoo** [comment]
Yes, it's still valid.

**Comment by romandocent** [comment]
The solution, that I found at this moment. Use Nikon D600 dcp that I've got from Adobe DNG Converter or Adobe Camera RAW installation. With this dcp profile colors and tones get close to native Nikon profile. But one more thing: in "Color management" tab, where you use custom dcp profile, the "tone curve", "baseline exposure" and "Look table" options must be checked ("base table" switched on by default for me). It is necessary step, otherwise colors may be wrong as in my examples above. 
Why don't add these missed dcp profiles to the RawTherapee installation? Are they proprietary? This one works fine for me.

**Comment by Beep6581** [comment]
@romandocent please upload the raw file(s), not the JPEG(s).

> Why don't add these missed dcp profiles to the RawTherapee installation? Are they proprietary?
Yes.

**Comment by Beep6581** [comment]
Any reason to keep this open?

**Comment by TooWaBoo** [comment]
I think this can be closed.
