### ISSUE TITLE
Crop not used while saving

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3411]
I'm using current `master` merged into `softproof`. When I open a DNG image, apply neutral, apply a crop, then save, the saved image either is completely uncropped, or the crop is of the wrong area.

Reproduce using:
http://rawtherapee.com/shared/test_images/eizo_vs_laptop.hdr.dng
https://i.imgur.com/MM20xZX.jpg
http://rawtherapee.com/shared/test_images/tracteur.dng
https://i.imgur.com/9bCTNVv.jpg

**Comment by Beep6581** [comment]
Works correctly in `gtk3`. I don't currently have a clean `master` or a clean `softproofing` build to test.

**Comment by Hombre57** [comment]
Fixed in commit a69c631.
