### ISSUE TITLE
TIF orientation tag error message

### ISSUE THREAD

**Issue by multinaturalist** [Beep6581/RawTherapee#3412]
PROBLEM:

RT produces 2 error messages when accessing a TIF image created by **Thumbs Plus** (http://www.cerious.com). Initially, RT issues these errors when making thumbnails for each such TIF image in a selected folder, and subsequently any time I double-click on one of the TIF images to edit it in RT.  Thumbnails are made correctly, and I can still edit the image, but RT produces the 2 error messages whenever accessing a TIF image created by Thumbs Plus.

Other image editing software (Gimp, Corel PhotoPaint X6) do not have any problem with TIF images created by ThumbsPlus. I contacted Thumbs Plus (Cerious.com) who told me their encoding for TIF files is done correctly and has been tested with many image editing programs. I only experience this "orientation tag" error with RT. (RT reports an invalid value of "0" for the orientation tag.)

These RT errors occur regardless of TIF compression level used, with **one exception**. RT does not produce error messages when I save TIF files in Thumbs Plus with **"skim low-order bits"** selected. However. If I resave the skimmed TIF file in ThumbsPlus with "skim low-order bits" unchecked, RT again produces the error messages.

**Links** to error message Screenshot & an original TIF image which triggers the error message:

[Screenshot_001.png](https://filebin.net/xl77e2rzkp1bv1fv/Screenshot_001.png)

[DSC_1546.tif](https://filebin.net/xl77e2rzkp1bv1fv/DSC_1546.tif)  -  (2.3MB)

MY SOFTWARE:

RawTherapee Version Information:

    Branch: gtk3
    Version: 4.2.1148
    Changeset: 2bfb0acdd7ea202bb716e84585802d1875e41da4
    Compiler: gcc 5.3.0
    Processor: generic x86
    System: Windows
    Bit depth: 64 bits
    Gtkmm: V3.18.0
    Build type: release
    Build flags: -m64 -mwin32 -mthreads -std=gnu++11 -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -msse -msse2 -mwindows -fopenmp -Wno-aggressive-loop-optimizations -DNDEBUG -O3
    Link flags: -m64 -mwin32 -mthreads -static-libgcc -mtune=generic -mwindows -s -O3
    OpenMP support: ON
    MMAP support: ON

Downloaded from:  http://rawtherapee.com/releases_head/windows/RawTherapee_WinVista_64_Gtk3_Debug_4.2.1148.zip

System Information:

    Toshiba Satellite C655 laptop
    Intel Pentium P6100 @2.0 GHz, 64-bit
    8 GB Ram
    Windows 10 Home OS

I am using Thumbs Plus v10.4010 (http://www.cerious.com).

**Comment by Beep6581** [comment]
Hello

Thank you for a well-written report. The only thing missing is a sample image, but in this case it looks like we don't need one.

> I contacted Thumbs Plus (Cerious.com) who told me their encoding for TIF files is done correctly

I wonder what they based that claim on, since "0" is an invalid value, as RawTherapee correctly reports:
http://www.awaresystems.be/imaging/tiff/tifftags/orientation.html

**Comment by multinaturalist** [comment]
Thank you. I fixed the links to the error screenshot & sample image.

I will pass that information along to Thumbs Plus. Could they be leaving the field "blank," or unset?

**Comment by Beep6581** [comment]
They should consult the TIFF specification to find out.

You need not worry about it - the tag warning is just a warning, nothing fatal.
