### ISSUE TITLE
Cannot scroll toolbox with mousewheel when HideTPVScrollbar=true

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3413]
In `gtk3` using gtk+-3.18.9, when the vertical scrollbar is hidden, one cannot scroll the toolbox with the mousewheel. Perhaps we should disable that option in gtk3, since the vertical scrollbar auto-hides and so is never in the way.

**Comment by TooWaBoo** [comment]
I can scroll with the mousewheel when the scrollbar is hidden in Windows 10 RT 4.2.1174 GTK3.
Maybe it's only a Linux issue

**Comment by Beep6581** [comment]
Which Gtk3 version do you use?

**Comment by TooWaBoo** [comment]
Branch: gtk3
Version: 4.2.1174
Changeset: a6179ef9697c8d042e686c3a70d5da0243b7cc5f
Compiler: gcc 5.3.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
**Gtkmm: V3.18.0**
Build type: release
Build flags: -m64 -mwin32 -mthreads -std=gnu++11 -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -msse -msse2 -mwindows -fopenmp -Wno-aggressive-loop-optimizations -DNDEBUG -O3
Link flags: -m64 -mwin32 -mthreads -static-libgcc -mtune=generic -mwindows -s -O3
OpenMP support: ON
MMAP support: ON

**Comment by Beep6581** [comment]
I found that with the vertical scrollbar set to hidden using Gtk+-3.18.9, scrolling with the mouse scrollwheel only happens if the cursor is over a combobox, for example the highlight reconstruction method combobox. When it's not over the combobox, I cannot scroll down.

Strangely, if I did scroll the toolbox down by hovering the cursor over a combobox, scrolling down, moving it over the combobox again, scrolling down, and now I move it away from the combobox and scroll down one click, the toolbox scrolls up one click!

**Comment by TooWaBoo** [comment]
With GTK+ 3.18.0 no problems at all.

**Comment by heckflosse** [comment]
I also tried using Win7 gtk3 3.18.0. No Problems here

**Comment by Beep6581** [comment]
Summary: gtk+-3.18.9 and possibly other versions seem to have a bug regarding the mousewheel and scrollbar. Regardless, in Gtk3 the vertical scrollbar auto-disappears. Is there any use keeping the option?

**Comment by Beep6581** [comment]
Still the case using GTK+ 3.22.19 in Linux, but works fine in Windows.

**Comment by Beep6581** [comment]
I opened a PR:
https://github.com/Beep6581/RawTherapee/pull/4218

**Comment by Beep6581** [comment]
Now the option is only forced when using Linux and GTK+ >=3.19, as it was reported that scrolling worked in Linux using GTK+ <=3.18.

**Comment by Beep6581** [comment]
Closing as worked-around.
