### ISSUE TITLE
Wrong signing of rawtherapee-gtk3-1_4.2.1174-1-x86_64.pkg.tar.xz

### ISSUE THREAD

**Issue by Chawoosh** [Beep6581/RawTherapee#3414]
Yesterday Arch refuse download the new version of RT. After downloading file of RT and .sig I see that signing is wrong. Update was successful only after deleting .sig file.

**Comment by Beep6581** [comment]
@Chawoosh as stated here https://discuss.pixls.us/t/wrong-signing-of-rawtherapee-gtk3-1-4-2-1174-1-x86-64-pkg-tar-xz/2173/2?u=morgan_hardwood please report the problem in the correct place. We have nothing to do with those packages, they are run by other people.
