### ISSUE TITLE
Crash while saving a jpg photo

### ISSUE THREAD

**Issue by stelariusinfinitek** [Beep6581/RawTherapee#3416]
This happened to me before. I changed the Preview Demosaic Method to fast because someone said this could be a fix but I don't think it matters that much. If you need any more details, just ask please. RawTherapee is something I like very much because the results are beautiful. 

**OS** : Arch Linux
**DE** : Xfce4 (if it matters)
**RawTherapee** : 4.2.448 (from official repositories)
### Version :

**Branch**: makepkg
**Version**: 4.2.448
**Changeset**: 26d182dabc6f133c27bffa3aac3f91b7ae55d578
**Compiler**: cc 6.1.1
**Processor**: x86_64
**System**: Linux
**Bit depth**: 64 bits
**Gtkmm**: V2.24.4
**Build type**: Release
**Build flags**: -std=c++11  -Werror=unused-label -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG
**Link flags**:  -Wl,-O1,--sort-common,--as-needed,-z,relro
**OpenMP support**: ON
**MMAP support**: ON
### The log :

```
Process 972 (rawtherapee) of user 1000 dumped core.

Stack trace of thread 972:
#0  0x00000383d55fecc0 _int_malloc (libc.so.6)
#1  0x00000383d5600d44 malloc (libc.so.6)
#2  0x00000383d9782538 g_realloc (libglib-2.0.so.0)
#3  0x00000383d9750419 n/a (libglib-2.0.so.0)
#4  0x00000383d9750798 g_array_append_vals (libglib-2.0.so.0)
#5  0x00000383d3ae21b0 g_file_attribute_matcher_new (libgio-2.0.so.0)
#6  0x00000383d3b84397 n/a (libgio-2.0.so.0)
#7  0x00000383d7c36cbf _ZN3Gio4File18enumerate_childrenERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_18FileQueryInfoFlagsE (libgiomm-2.4.so.1)
#8  0x0000000000827b8f _Z20safe_build_file_listRN4Glib6RefPtrIN3Gio4FileEEERSt6vectorINS_7ustringESaIS6_EERKS6_PKS8_ (rawtherapee)
#9  0x000000000067fc97 _ZN11FileCatalog11getFileListEv (rawtherapee)
#10 0x0000000000680cd0 _ZN11FileCatalog16reparseDirectoryEv (rawtherapee)
#11 0x000000000068109a _ZN11FileCatalog14on_dir_changedERKN4Glib6RefPtrIN3Gio4FileEEES6_NS2_16FileMonitorEventEb (rawtherapee)
#12 0x00000383d7c4316d n/a (libgiomm-2.4.so.1)
#13 0x00000383d4eea1c8 ffi_call_unix64 (libffi.so.6)
#14 0x00000383d4ee9c2a ffi_call (libffi.so.6)
#15 0x00000383d9a52c9a g_cclosure_marshal_generic_va (libgobject-2.0.so.0)
#16 0x00000383d9a521b4 n/a (libgobject-2.0.so.0)
#17 0x00000383d9a6c8ed g_signal_emit_valist (libgobject-2.0.so.0)
#18 0x00000383d9a6cfdf g_signal_emit (libgobject-2.0.so.0)
#19 0x00000383d3b88d09 n/a (libgio-2.0.so.0)
#20 0x00000383d977ce67 g_main_context_dispatch (libglib-2.0.so.0)
#21 0x00000383d977d0d0 n/a (libglib-2.0.so.0)
#22 0x00000383d977d3f2 g_main_loop_run (libglib-2.0.so.0)
#23 0x00000383d8d9a347 gtk_main (libgtk-x11-2.0.so.0)
#24 0x00000383d861c16f _ZN3Gtk4Main3runERNS_6WindowE (libgtkmm-2.4.so.1)
#25 0x00000000004eec5d main (rawtherapee)
#26 0x00000383d55a6291 __libc_start_main (libc.so.6)
#27 0x0000000000500b3a _start (rawtherapee)

Stack trace of thread 973:
#0  0x00000383d566548d poll (libc.so.6)
#1  0x00000383d977d066 n/a (libglib-2.0.so.0)
#2  0x00000383d977d17c g_main_context_iteration (libglib-2.0.so.0)
#3  0x00000383d977d1c1 n/a (libglib-2.0.so.0)
#4  0x00000383d97a3345 n/a (libglib-2.0.so.0)
#5  0x00000383d592b454 start_thread (libpthread.so.0)
#6  0x00000383d566e7df __clone (libc.so.6)

Stack trace of thread 974:
#0  0x00000383d566548d poll (libc.so.6)
#1  0x00000383d977d066 n/a (libglib-2.0.so.0)
#2  0x00000383d977d3f2 g_main_loop_run (libglib-2.0.so.0)
#3  0x00000383d3b6f7c6 n/a (libgio-2.0.so.0)
#4  0x00000383d97a3345 n/a (libglib-2.0.so.0)
#5  0x00000383d592b454 start_thread (libpthread.so.0)
#6  0x00000383d566e7df __clone (libc.so.6)

Stack trace of thread 1441:
#0  0x00000383d56612cd open (libc.so.6)
#1  0x00000383d55f92e3 _IO_file_open (libc.so.6)
#2  0x00000383d55f9483 _IO_file_fopen@@GLIBC_2.2.5 (libc.so.6)
#3  0x00000383d55ed604 __fopen_internal (libc.so.6)
#4  0x000000000087ef52 _ZN8rtengine7ImageIO8saveJPEGEN4Glib7ustringEii (rawtherapee)
#5  0x00000000006dad3c _ZN8rtengine7Image1610saveAsJPEGEN4Glib7ustringEii (rawtherapee)
#6  0x000000000057ab22 _ZN4sigc8internal10slot_call0INS_12bind_functorILin1ENS_18bound_mem_functor3IiN8rtengine8IImage16EN4Glib7ustringEiiEES7_iiNS_3nilES9_S9_S9_EEiE7call_itEPNS0_8slot_repE (rawtherapee)
#7  0x000000000057b50b _ZN17ProgressConnectorIiE13workingThreadEv (rawtherapee)
#8  0x00000383d9502a4d n/a (libglibmm-2.4.so.1)
#9  0x00000383d97a3345 n/a (libglib-2.0.so.0)
#10 0x00000383d592b454 start_thread (libpthread.so.0)
#11 0x00000383d566e7df __clone (libc.so.6)
```

**Comment by heckflosse** [comment]
@stelariusinfinitek Can you try latest dev version supplied by Marcin Bajor for Arch please. I don't know which version it is but it could be > 4.2.1000.
Have a look [here](http://rawtherapee.com/downloads) and select 'Arch Linux', '64-bit', 'Development version'

Ingo

**Comment by stelariusinfinitek** [comment]
Thank you. :) I didn't know about the repository. I will test it. The thing is that the crash doesn't happen all the time, just sometimes. I don't really know what to say without knowing the cause.

**Comment by stelariusinfinitek** [comment]
I worked a bit with the development version but the interface is not pleasant, too many spaces and big buttons (Gtk3 version; the system theme helps a big, some problems like big buttons at the top remain). I'll try to ignore the bug until is it fixed.

**Comment by heckflosse** [comment]
@stelariusinfinitek gtk2 version should almost look the same as 4.2.448 where you reported the bug for

**Comment by stelariusinfinitek** [comment]
I don't know how to install it, my package manager picks the one from community repository because it has the same name.

**Comment by heckflosse** [comment]
@stelariusinfinitek Maybe @Beep6581 can help you. I can't because I'm mainly on Windows

**Comment by Beep6581** [comment]
@stelariusinfinitek you have two options:
* http://rawtherapee.com/downloads select the "Arch Linux" platform and follow the instructions for AUR
* Compile manually http://rawpedia.rawtherapee.com/Linux

**Comment by stelariusinfinitek** [comment]
@Beep6581 , thank you.  

Is this a known bug? This happened to me since I discovered RawTherapee.

**Comment by Beep6581** [comment]
@stelariusinfinitek currently it's known only to you ;) Can you still reproduce it in the latest git master head?

**Comment by stelariusinfinitek** [comment]
@Beep6581 Hey :) I'm on Windows right now but I'll install Linux in a hour. Does that mean I have to compile RawTherapee? Because I have a 1,8 Ghz Dual-Core CPU.

**Comment by Floessie** [comment]
> Does that mean I have to compile RawTherapee? Because I have a 1,8 Ghz Dual-Core CPU.

Yes. But if you start right now, you can report back tomorrow. :grin:

**Comment by stelariusinfinitek** [comment]
@Floessie Well... it's not worth it. :) I'll use it as it is.

**Comment by Floessie** [comment]
@stelariusinfinitek Hey, don't give up so easy. I support Ingo's assumption, that you have an OOM problem. If you like, send a RAW and PP3 to [filebin.net](https://filebin.net/) and post the link here with steps for reproduction and the amount of free memory you have before starting RT. I could then adjust my VM to have about the same amount of free memory and try to reproduce your crash under Linux.

**Comment by Beep6581** [comment]
@stelariusinfinitek its best to report using the latest version, so if your Linux distro does not ship a daily build then compile it yourself. Compilation on your CPU should only takes 10 minutes, and it's quite simple. Use the master branch. And as @Floessie wrote, it's important that you supply the files in question and steps to reproduce.
