### ISSUE TITLE
Wrong IPTC tagging for german Umlaute

### ISSUE THREAD

**Issue by NextTherapist** [Beep6581/RawTherapee#3417]
RT 4.2.1000 Master writes something else instead of german Umlaute when filling in IPTC fields and exporting to JPG.

Instead of "ö" I get "ÃƒÂ¶", instead of "ü" I get "ÃƒÂ¼" and instead of "ä" I get ÃƒÂ¤".
And instead of "ß" I get "ÃƒÅ¸".

I get this wrong text in Irfanview, XNView, Photoshop CS2 - and even in Rawtherapee itself :-(

**Comment by Beep6581** [comment]
Duplicate #1314
