### ISSUE TITLE
Speedups for denoise

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#3418]
I prepared a new branch to address some small performance issues in denoise.

- When using `Automatic global` mode the calculation of the 3 `Chrominance values` was called too often. It was called for each detail window and also when panning around. Now it's only called once (independent on the number of detail windows) and it's also called only for the first 1:1 view, which means it's not called again when panning around.

- In denoise itself 2 gammacurves are created, each of them took about 10 ms. Another gammacurve is created in the denoise info code (which calculates the 3 `Chrominance values`) and also took 10 ms. I reduced the processing time to create each of this curves to 0.4 ms.

Example: Panning around in 1:1 view of amsterdam.pef with Denoise Automatic global and Denoise median set to off took 90 ms (denoise info) + 189 ms (denoise) . Now it takes 0 ms (denoise info) + 170 ms (denoise)

I'll push the new branch soon.

Ingo

**Comment by heckflosse** [comment]
I just pushed [denoise branch](https://github.com/Beep6581/RawTherapee/tree/denoise)

**Comment by Floessie** [comment]
@heckflosse Impressive as always. :+1: Not that I understand the math, but there is a minor style glitch [here](https://github.com/Beep6581/RawTherapee/compare/denoise#diff-986675e22da438b842194e9a6cf102c6R329): This should be a good old `struct` if it has no methods/functions other than a ctor and/or dtor. And I don't know if all lower case is common for classes in RT...

**Comment by heckflosse** [comment]
@Floessie In my first version that class, struct also had a pointer to a LUT. For that reason I used a class to destroy the LUT in destructor. But then I detected that I don't need that pointer, removed it and forgot to change it from class to struct. I'll change that with before I merge the branch as well as the lower case thing. :)

**Comment by heckflosse** [comment]
I forgot to mention: Though I optimized the math behind the generation of the gamma curves and also changed the calculation from double to single precision, I had no difference in output testing with 2 files and 4 denoise methods.

**Comment by heckflosse** [comment]
I made some changes: https://github.com/Beep6581/RawTherapee/commit/ef83e6b591a211afe8d4471c6933b3953ae2fd4e

**Comment by heckflosse** [comment]
@Floessie `Not that I understand the math`: I can explain it if you're interested :)

Ingo

**Comment by Floessie** [comment]
@heckflosse Yes, please, if your time permits. Maybe I'm (still) able to grok it. ;)

As to the `struct`: I saw that you elegantly solved the initialization with C++11. Still I think a ctor and/or dtor is perfectly fine for a `struct`. It's all about its data members. If there are accessors, it should be a class and hide its data in `private:`.

**Comment by heckflosse** [comment]
@Floessie here you go :)
[gamcurve_opt.txt](https://github.com/Beep6581/RawTherapee/files/461514/gamcurve_opt.txt)

**Comment by Floessie** [comment]
@heckflosse Ingo, thanks for sharing an insight into your brain. ;)

It's always interesting how much you gain if you stay in the single precision realm.

Those sleef functions are scary. They must have been conceived by some long bearded Unix veteran or even earlier by a clean-shaven mathematician at Los Alamos.

Now I understand `iv` in `gammanf2lut()`. `iv` always makes me always think of "initialization vector", maybe that's why it seemed cryptic to me at first glance.

> log(a/b) = log(a) - log(b)

Ah, long forgotten school math. They never told us why we had to learn it. Now everthing makes sense at long last.

Wow, nice write-up. Thanks a lot!

**Comment by heckflosse** [comment]
@Floessie 

> It's always interesting how much you gain if you stay in the single precision realm.

Using single precision float only didn't lead to the difference between 10.114 ms and 2.728 ms. It was using sleef functions which gave that big step. iirc the simple change from double to float resulted in a small 10% speedup.

> Those sleef functions are scary. They must have been conceived by some long bearded Unix veteran or even earlier by a clean-shaven mathematician at Los Alamos.

https://plus.google.com/+NaokiShibata/posts

> Now I understand  iv  in  gammanf2lut() 

Yes, `iv` is simply the float version of the loop index `i` ;)

> Ah, long forgotten school math. They never told us why we had to learn it.

I confirm that!

Ingo

**Comment by Floessie** [comment]
@heckflosse 

> https://plus.google.com/+NaokiShibata/posts

So, wouldn't it be just fair to mention him as source in `sleef.c`?

**Comment by heckflosse** [comment]
> So, wouldn't it be just fair to mention him as source in sleef.c ?

Done :)

**Comment by da-phil** [comment]
wow, that speedup really is noticeable! I've to process a lot of high ISO shots in the next couple of days and really like that deno(i)sing is working so fast now ;)
good work ingo! :+1:

**Comment by heckflosse** [comment]
@da-phil Thanks for testing and reporting :+1:
