### ISSUE TITLE
automatic distorsion correction improvement

### ISSUE THREAD

**Issue by esby** [Beep6581/RawTherapee#3419]
I don't know if this was suggested, maybe I am missing something.

We can enable or disable distorsion correction which is fine.

But it seems we cannot run automatic distorsion automatically, one needs to click the 'auto distorsion correction' to have it run. In terms of UI, this is a waste of time, since you probably wants to use it when it is activated.

**Comment by heckflosse** [comment]
@esby I started work on this Issue long time ago, but it got stale for whatever reason... For reference: https://github.com/Beep6581/RawTherapee/issues/2235
