### ISSUE TITLE
Pink / Violet Hilights artefacts with Panasonic GH4 raws 

### ISSUE THREAD

**Issue by esby** [Beep6581/RawTherapee#3420]
When shooting against daylight ('à contrejour') with my Panasonic GH4 camera , violet / pink artefacts can appear sometimes. (A 45mm olympus was mounted on it).

Here's an example of raw file showing the issue: https://filebin.net/h0d20opghd95xk99/Shooting_Alice_Genderbend_-_Parc_de_Cimiez_-_Nice_-_2016-08-23-_P1540728.RW2

The result looks like that: https://www.flickr.com/gp/styeb/6St703 

This issue is also present in shoots 'a contrejour', with Pink / Violet taint in burnt part, like a chromatic aberration (I am not specialist, but It makes me think to it).

**Comment by iliasg** [comment]
Τhis is not RawTherapee's issue .. same happens with ACR/LR

It's an GH4 (and other m4/3 models) issue, sometimes getting worse in cooperation with specific lenses ..
