### ISSUE TITLE
FocusDistanceUpper and Lower in Canon RAW CR2 is displayed as 0.0

### ISSUE THREAD

**Issue by cm7695** [Beep6581/RawTherapee#3422]
If I open a CR2 Raw File from my Canon 5d Mark ii (contains in MakerNotes in Subfolder CanonShotInfo focus distance, and also defined in canonattribs.cc lines 1847 1848
 )  FocusDistanceUpper and Lower are displayed as 0.0 in the Meta Data Tab.
Used Version is the git version from today.

**Comment by cm7695** [comment]
Found the Problem:
FocusDistanceUpper and Lower are found in CanonFileInfo not in ShotInfo
Remove line
 1847   {0, AC_WRITE, 0, 0, 19, AUTO, "FocusDistanceUpper", &caFocusDistanceInterpreter},
1848    {0, AC_WRITE, 0, 0, 20, AUTO, "FocusDistanceLower", &caFocusDistanceInterpreter},

and add to canonFileInfoAttrib the lines 
 {0, AC_WRITE, 0, 0, 0x0014, SSHORT, "FocusDistanceUpper", &caFocusDistanceInterpreter},
 {0, AC_WRITE, 0, 0, 0x0015, SSHORT, "FocusDistanceLower", &caFocusDistanceInterpreter},

Specifications from http://www.exiv2.org/tags-canon.html

**Comment by Floessie** [comment]
Great! Thanks for finding this out and also providing a fix.

@Beep6581 Okay for you, if I fix it this way? I'd streamline it by using `AUTO` and `20`/`21`.

**Comment by Beep6581** [comment]
Thank you @cm7695 !

@Floessie I can't comment whether that is the right thing to do, but if it fixes the problem then go ahead!

I did update all of those `/rtexif/` files based on exiftool-10.20 a few months ago. I'm not sure if I updated that function as well, I don't have the repo here so I can't run `git blame rtexif/canonattribs.cc` to find out. Could you run that and see if you can find which commit touched that line last? It would be good to know so that we can report it upstream if it came from exiftool and if it hasn't changed upstream. Otherwise I can investigate tomorrow night.

**Comment by Beep6581** [comment]
Ha, I just found out that GitHub also supports `git blame`, so that function did not come from my update based on exiftool.
https://github.com/Beep6581/RawTherapee/blame/master/rtexif/canonattribs.cc#L1847

**Comment by Floessie** [comment]
@cm7695 Please try the newest master and report back, if this issue can be closed. Thanks!

**Comment by cm7695** [comment]
Yes, it works; this issue can be closed. 
I think the problem is, that in exiftool in canon.pm in lines 2503 and 2514 these Tags are listed as FocusDistanceUpper and lower in ShotInfo; in FileInfo in lines 6258 and 6268. It's probably camera specific.
I think line 1850 is wrong:
{0, AC_WRITE, 0, 0, 24, AUTO, "MeasuredEV2", &caMeasuredEVInterpreter},

Isn't it 23 for MeasuredEV2? (Exiftool, canon.pm line 2564)

**Comment by Floessie** [comment]
@cm7695 

> Isn't it 23 for MeasuredEV2? (Exiftool, canon.pm line 2564)

I guess so, also according to [exiv2.org](http://www.exiv2.org/tags-canon.html). Good catch. Have you also checked the other canon tags, or shall I?

**Comment by cm7695** [comment]
@Floessie I looked only at a few tags. Tomorrow I will check the whole file. But I think it is better you double-check my results afterwards. I give a feedback tomorrow or overmorrow.

**Comment by Floessie** [comment]
@cm7695 Fine, let's proceed that way. Thanks for your efforts!

**Comment by cm7695** [comment]
So, checked. 23 for measuredEV2.
Canon Serial Number is displayed wrong. In exiftool they say remove leading 0xff...
My image size output is probably wrong. dcraw gives a raw crop [158 51 5634 3753]. But maximum possible export size is only 5626x3745, 8 pixel removed in width and hight. My knowledge about demosaicing  is nearly zero, but if I use dcraw from command-line I get the full 5634x3753.
That's all I found.

**Comment by Floessie** [comment]
@cm7695 

> Canon Serial Number is displayed wrong. In exiftool they say remove leading 0xff...

Can you provide me with an sample CR2 (via filebin.net)? My Canon files show the same number in exiftool, exiv2, and RT.

> My knowledge about demosaicing is nearly zero, but if I use dcraw from command-line I get the full 5634x3753.

Mine too. @Beep6581: Could you have a look? @cm7695 will hopefully provide us with a sample file.

Best
Flössie

**Comment by heckflosse** [comment]
> My image size output is probably wrong. dcraw gives a raw crop [158 51 5634 3753]. But maximum
> possible export size is only 5626x3745, 8 pixel removed in width and hight. My knowledge about 
> demosaicing is nearly zero, but if I use dcraw from command-line I get the full 5634x3753

The pixels at the borders of the image can't be interpolated correctly by demosaicer because they lack pixels at least on on side. To give consistent demosaic results also at the borders, rt simply crops away 4 pixels from each border after demosaic for bayer sensors (for x-trans sensors it crops 7 pixels iirc).

Ingo

**Comment by cm7695** [comment]
Ok, that make sense.
To SerialNumber Problem:
Exiftool displays: Serial Number                   : 3731820040
exiv2 -pv displays: 0x000c Canon        SerialNumber                Long        1  3731820040
exiv2 -pt displays: Exif.Canon.SerialNumber                      Long        1  de6f03592

Only the results from exiftool and exiv2 -pt are correct.

RT displays: 18446744073146404360

Herer is a sample: https://filebin.net/fz4zyu9en3gee997/20150901_0001.CR2

**Comment by Beep6581** [comment]
> Only the results from exiftool and exiv2 -pt are correct.

Did you mean only exiftool and exiv2 -pv are correct?

`DE6F03592` seems to begin correctly with `DE6F` and then has the strange `03592`. Well `3592` dec is `0x0E08`, and `0xDE6F0E08` gives the correct dec `3731820040`.

> RT displays: 18446744073146404360

`18446744073146404360` is `0x0xFFFFFFFFDE6F0E08`. Chop off the first 4 bytes and fixed.

`de6f03592` looks wrong, why would they intentionally mix hex and decimal? Should I report a bug at http://dev.exiv2.org/projects/exiv2/issues for -pt?

**Comment by Floessie** [comment]
@Beep6581 

> `18446744073146404360` is `0xFFFFFFFFDE6F0E08`. Chop off the first 4 bytes and fixed.

Looks like a wrong sign extension, as `0xDE6F0E08` should have been treated unsigned but wasn't. I'll have a look. Thanks for your investigation.

**Comment by Floessie** [comment]
@Beep6581 Yep, it's [here](https://github.com/Beep6581/RawTherapee/blob/master/rtexif/rtexif.cc#L1560). That shouldn't be casted to `long`, which is 64b on LP64 systems (Windows is LLP64, so the error won't occur there). In fact, there is even no reason to do so. The line should simply read:

```
sprintf (b, "%u", toInt(4 * i + ofs));
```

The `SLONG` is also wrong, but it won't show.

HTH
Flössie

**Comment by cm7695** [comment]
@Beep6581 I don't know why it doesn't display the correct serial number with the -pt option. In Manual they say: interpretet. 
So I would expect 0xDE6F0E08 with the -pv option (plain values) and 3731820040 with the -pt option. But not a mix of both. I didn't found a reason to write the serial number as de6f03592.
@Floessie Your line fixes the problem.

**Comment by Floessie** [comment]
@cm7695 Fine, I'll push a fix tonight.

**Comment by Beep6581** [comment]
EOS 5D Mark III http://rawtherapee.com/shared/test_images/greenscreen.cr2
FocusDistanceUpper and FocusDistanceUpper were 0 in a gtk3-branch build from a few weeks ago, and are correct in the `fix-canon-exif` branch. The serial number was displayed correctly before and after the patch.
LensSerialNumber is displayed as `0000012bf9` in both before and after. Exiv2 and ExifTool display it like that as well.

EOS 5D Mark II https://filebin.net/fz4zyu9en3gee997/20150901_0001.CR2
FocusDistanceUpper and FocusDistanceUpper were 0 in the gtk3-branch build, and the serial number was wrong. All are correct in the `fix-canon-exif` branch.

Shall we close?

**Comment by cm7695** [comment]
Yes, you can close.

**Comment by Floessie** [comment]
@Beep6581 Thanks a lot for testing. I'll  merge...
