### ISSUE TITLE
A combination of settings in Wavelet's Edge Sharpnes tool crashes RawTherapee

### ISSUE THREAD

**Issue by MJacal** [Beep6581/RawTherapee#3425]
Tested versions:

Windows 7: 4.2.1148 gtk3
Windows 7 and 10: 4.2.1012 master
Ubuntu Studio 16.04 VM: ppa:dhor/myway rawtherapee-unstable: 4.3+git20160910-375~ubuntu16.04.1

Steps:

- Open any raw photo in editor (I have tried cr2, nef, rw2 and dng). Selecting Neutral, Default or any other profile makes no difference.
- Activate Wavelet Levels and Edge Sharpness.
- In Edge Sharpness, set Strength to any value, bigger than 0.
- Drag Detail slider to the lowest value, -50.

RawTherapee crashes every time. 

(Windows: "rawtherapee.exe has stopped working", Ubuntu: "The application RawTherapee has closed unexpectedly".)

Attached log.txt file, created by Windows 4.2.1012 master, debug version.

[log.txt](https://github.com/Beep6581/RawTherapee/files/466151/log.txt)

**Comment by heckflosse** [comment]
Crash confirmed

**Comment by Desmis** [comment]
@heckflosse 

Hello Ingo

This bug is "well known" (for me).
It is due in certain case: radius < 20 and first level = reduced and brings artifacts.

The solution you propose seems good (abs), but why not just limited to cases "reduced"

Jacques

**Comment by heckflosse** [comment]
@Desmis 

Hello Jacques

you're right :)

Ingo
