### ISSUE TITLE
 Incorrect Hue values - RT 4.2.1038, Xubuntu 

### ISSUE THREAD

**Issue by LZL1** [Beep6581/RawTherapee#3428]
RT shows incorrect Hue (HSV) for different working profiles (color spaces),
e.g. the same point:
Hue ~ 18 sRGB
Hue ~ 22 Adobe RBG
Hue ~ 28 Wide Gamut
Hue ~ 31 ProPhoto

Lab values for this point are a~11, b~13.

I use Xubuntu 16.04.1.

Branch: master
Version: 4.2.1038
Changeset: a7dc063f35580ff7430d8954f620b6666ce03d1b
Compiler: cc 5.4.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V2.24.4
Build type: release
Build flags: -std=gnu++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG
Link flags: -march=native
OpenMP support: ON
MMAP support: ON

**Comment by heckflosse** [comment]
[Please take a look](https://discuss.pixls.us/t/incorrect-hue-values-rt-4-2-1038-xubuntu/2240/11)

**Comment by LZL1** [comment]
It can be closed.
To avoid this it is necessary to uncheck "Use working profile for main histogram and Navigator"
Thanks to Ingo.
