### ISSUE TITLE
Version 

### ISSUE THREAD

**Issue by sarak3098** [Beep6581/RawTherapee#3433]
Hi there 

Iknow previously I sent a request syggestions about which version to download as I had issues but my dell computer is windows vista and should I download this version http://rawtherapee.com/releases_head/windows/RawTherapee_WinVista_64_Gtk3_Release_4.2.1148.zip

Regards 

Sar

**Comment by Floessie** [comment]
Hi Sar,

as you have a 32 bit Vista, the version you refer to is **not** the right one. In the meantime ganeed92 over at pixls.us was kind enough to provide new Windows builds. Please have a look [there](https://discuss.pixls.us/t/new-windows-builds/615/281).

Best
Flössie

**Comment by Beep6581** [comment]
@sarak3098 please do not open issues on GitHub for personal support. User support is at https://discuss.pixls.us/c/software/rawtherapee
