### ISSUE TITLE
Lock ratio should be disabled by default, or remember the last selection

### ISSUE THREAD

**Issue by groovenectar** [Beep6581/RawTherapee#3439]
I can't be the only one who crops most photos and generally prefers a freeform crop ratio. Designed to be a one-after-another workflow, I think that would be worth either remembering the last selection, or even disabling by default? How does anyone feel about having it disabled by default if the former option is not feasible? Any argument for enabling it each time?

**Comment by Beep6581** [comment]
"Lock ratio" was intentionally [enabled](https://github.com/Beep6581/RawTherapee/blob/master/rtengine/procparams.cc#L1152) by default. If you don't like that, create a new default PP3 for yourself
http://rawpedia.rawtherapee.com/Creating_processing_profiles_for_general_use

**Comment by groovenectar** [comment]
Thanks for the info about default profiles. That solves it. Maybe at some point one of us will get around to updating the boolean if it seems like a good idea to enough people :)

**Comment by sboukortt** [comment]
I agree: I don’t see any particular reason why the original aspect ratio should dictate that of the result. In fact, not all of my cameras even have the same aspect ratio to begin with.

The default was indeed changed in cb5e99ef, but what was the rationale behind the change? The commit message is not particularly explicit about it.
