### ISSUE TITLE
 gcc 6.2.1 build failure

### ISSUE THREAD

**Issue by mbajor** [Beep6581/RawTherapee#3440]
I can't build packages (from master branch, gtk3 builds fine) for some distributions with gcc 6.2.1 (with and without msse2)
e.g. openSUSE Tumbleweed, openSUSE Factory PowerPC (ppc64, ppc64le)

There is no problem with build for openSUSE Factory PowerPC(ppc) and Arch. Both have gcc 6.2.1.

```
[  317s] /home/abuild/rpmbuild/BUILD/rawtherapee-4.2.1071/rtgui/dirbrowser.cc:62:64: error: no match for 'operator<<' (operand types are 'std::basic_ostream<char>' and 'const Glib::RefPtr<Gio::File>')
[  317s]              std::cerr << "Failed to list subdirectories of \"" << dir << "\": " << exception.what () << std::endl;
```

```
[  461s] /home/abuild/rpmbuild/BUILD/rawtherapee-4.2.1071/rtgui/dirbrowser.cc:62:23: error: cannot bind 'std::basic_ostream<char>' lvalue to 'std::basic_ostream<char>&&'
[  461s]              std::cerr << "Failed to list subdirectories of \"" << dir << "\": " << exception.what () << std::endl;
```

[Sample log file
](https://build.opensuse.org/public/build/home:rawtherapee/openSUSE_Tumbleweed/i586/rawtherapee/_log)

**Comment by Hombre57** [comment]
I'm at work so I can't commit a patch right now, but I've fixed that in the lockable-color-picker branch by replacing `dir` by `dir->get_basename()` where the error occur.

**Comment by Floessie** [comment]
@mbajor As it doesn't seem GCC related, do the gtkmm versions differ between those builds that work and those that don't?

**Comment by mbajor** [comment]
@Floessie There are more differences
e.g.
[openSUSE Factory PowerPC ppc (build success)
](http://pastebin.com/J3qJL7dJ) + [full log](https://build.opensuse.org/public/build/home:rawtherapee/openSUSE_Factory_PowerPC/ppc/rawtherapee/_log)

[openSUSE Factory PowerPC ppc64 (build failed)
](http://pastebin.com/nx5pL5F1) + [full log](https://build.opensuse.org/public/build/home:rawtherapee/openSUSE_Factory_PowerPC/ppc64/rawtherapee/_log)

 |openSUSE Factory PowerPC ppc (build success) | openSUSE Factory PowerPC ppc64 (build failed)
------------ |------------ | -------------
gtk+-2.0|2.24.29|2.24.31
glibmm-2.4|2.44.0|2.50.0
gtkmm-2.4|2.24.4|2.24.5
giomm-2.4|2.44.0|2.50.0
sigc++-2.0|2.4.1|2.10.0
lcms2|2.7|2.8
libpng|1.6.21|1.6.25

**Comment by Floessie** [comment]
@mbajor Thanks, Marcin! I suspect glibmm-2.4 2.50.0 has that subtle change provoking this issue.

@Hombre57 I'm currently upgrading my distribution and will try a GTK3 build then. If I succeed, I can take care of this one. Okay for you, or do you already have a patch in your queue?

**Comment by Floessie** [comment]
@mbajor @Hombre57 I can reproduce the problem on master with an up-to-date Debian Stretch. I'll prepare a fix according to Jean-Christophe's work-around.

**Comment by Floessie** [comment]
@mbajor I've merged the fix to master. Please report back, if it fixes your problems, too. :smiley:

**Comment by mbajor** [comment]
@Floessie Fix confirmed. Thanks ! :)
