### ISSUE TITLE
Canon 750D red tint

### ISSUE THREAD

**Issue by Sarkanyolo** [Beep6581/RawTherapee#3441]
Dear Developers,

Every time I open a RAW file that has been made by my Canon 750D, the picture has huge red tint that is very hard to correct.
Strange thing is, that it looks perfect as a preview, the red tint appears when I want to develop it.
I also tried with sample RAW images that [I found here](http://www.photographyblog.com/previews/canon_eos_750d_photos/), and the result is the same.

I'm using the latest RAW Therapee, fresh install.

**Comment by Beep6581** [comment]
@Sarkanyolo "latest" is very vague, please provide proper details and upload your Canon 750D raw file using https://filebin.net/
See http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports

**Comment by Sarkanyolo** [comment]
Dear Beep6581,

The version is 4.2.1 x64 on Windows 7 x64.
Any RAW file on the linked page creates the same red tinted image.
For your example I uploaded one of them to here: [https://filebin.net/gcmdxu46w7ka2fxj](https://filebin.net/gcmdxu46w7ka2fxj)

**Comment by iliasg** [comment]
@Sarkanyolo Please use the latest release version .. https://filebin.net/y0hivouboulbzadn

**Comment by Sarkanyolo** [comment]
@iliasg The issue is fixed in the version 4.2.1234.
When you plan to officially release these changes?

**Comment by Beep6581** [comment]
Thank you @Sarkanyolo 

We are releasing a new "stable" version shortly - see #3300
