### ISSUE TITLE
Deutsch locale update based on RT 4.2.1234

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#3442]
New Update 30. Sep.2016 19:43
deleted
New Update 30. Sep.2016 22:48
[Deutsch.txt](https://github.com/Beep6581/RawTherapee/files/503788/Deutsch.txt)

**Comment by Floessie** [comment]
@TooWaBoo :+1: There is at least one inconsistency with "Film Simulation" vs. "Filmsimulation" (preferred) and "der Pixel" vs. "das Pixel" (preferred).

**Comment by TooWaBoo** [comment]
@Floessie 
Thanks

Changed **"Film Simulation"** to **"Filmsimulation"**, but in this context **"Anteil der Pixel, die sich bei..."**, **"der Pixel"** is correct .

**Comment by Floessie** [comment]
@TooWaBoo Sorry, my crusty school german. I meant the inflected form in `TP_WAVELET_NPTYPE_TOOLTIP`.

**Comment by TooWaBoo** [comment]
Found it, changed it and replaced the file. 
Thanks

PS: Your German is better than mine. :-)

**Comment by Beep6581** [comment]
May I merge?

**Comment by TooWaBoo** [comment]
@Beep6581 
Yes

**Comment by heckflosse** [comment]
@Beep6581 Yes
