### ISSUE TITLE
RA: Building placement / overlap (Service Depot / Missile Silo)

### ISSUE THREAD

**Issue by pi99y** [Beep6581/RawTherapee#3449]
Current bleed.
(without "build everywhere")

![ora_build_overlap](https://cloud.githubusercontent.com/assets/10639257/19160653/f7dd3784-8bf0-11e6-9542-227cce17d9f2.jpg)

**Comment by Beep6581** [comment]
@pi99y you're into OpenRA too? :)
https://github.com/OpenRA/OpenRA/issues/
