### ISSUE TITLE
Extremely slow in Windows when floppy drive enabled

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3450]
RawTherapee can be extremely slow to load and run in Windows 10 if there is a floppy drive enabled in the BIOS. Both Gtk2 and Gtk3.
https://discuss.pixls.us/t/new-windows-builds/615/344?u=morgan_hardwood

**Comment by heckflosse** [comment]
One solution would be to exclude Drive A: and B: from scanning. But iirc, when A: and/or B: are disabled in Bios one can use these drive letters also for other drives (usb sticks and so on). So disabling scan of A: and B: may lead to new issues...

**Comment by iliasg** [comment]
@Beep6581 I think this issue only happens on windows 10.

@heckflosse Ingo, what if just abort scanning of an empty drive.  As I understand it, windows shoud give the info if drive A is empty/loaded, it just happens that win10 does not (?? !!) or handles it in a different address ..

**Comment by heckflosse** [comment]
@iliasg The problem is, whatever I change, I can not test it as I'm on Win7

**Comment by Beep6581** [comment]
Microsoft lets people download Windows 10 virtual machines. I tried it before and it worked fine. You can download an ISO from here:
https://www.microsoft.com/en-us/software-download/windows10ISO
I'm getting one right now...

**Comment by heckflosse** [comment]
I won't try Windows 10. Never change a running system...

**Comment by heckflosse** [comment]
I guess we can close this

**Comment by Beep6581** [comment]
@heckflosse is the issue fixed?

**Comment by heckflosse** [comment]
@Beep6581 I don't know. I could never reproduce it and it was not reported again for quite a while.

**Comment by Beep6581** [comment]
Yes, I haven't seen it mentioned in a long time, so closing.
