### ISSUE TITLE
Merged master-b8eb349 into gtk3

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3453]
With Ingo's help I managed to merge `master` into `gtk3`. The work was made difficult by the numerous additions to code which differs between the two branches, combined with cleanups.
Lesson learned - merge more often!

https://github.com/Beep6581/RawTherapee/tree/gtk3-merge-master-b8eb349

@Hombre57 could you take a look if everything seems OK?
Of course everyone else is welcome (and encouraged) to check, but please don't fix any non-merge bugs, as this is a merge-only commit!

**Comment by heckflosse** [comment]
@Beep6581 Cppchecked, didn't detect any new important issues :+1:

**Comment by Hombre57** [comment]
@Beep6581 Walked through the rtgui folder, looks good for me too. I rediscovered the `ConnectionBlocker` class btw, and will make a new patch once this branch is merged to gtk3. Good job @Beep6581 :+1:

**Comment by Beep6581** [comment]
Thanks! :)

**Comment by Beep6581** [comment]
Actually it's too early in the morning to merge... I'll have a coffee first, just in case. :)

**Comment by Beep6581** [comment]
Done.
