### ISSUE TITLE
Crash when click "toggle before/after view" button

### ISSUE THREAD

**Issue by RuralHunter** [Beep6581/RawTherapee#3454]
OS: Ubuntu 16.04
The daily build crashes for any image when I click the "toggle before/after view" button. This works fine with the official stable version 4.20. My daily build version was install from rawtherapee-unstable of APT-Sources: http://ppa.launchpad.net/dhor/myway/ubuntu xenial/main amd64 Packages
Version info:
Branch: master
Version: 
Changeset: daily
Compiler: x86_64-linux-gnu-gcc 5.4.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V2.24.4
Build type: Release
Build flags: -std=c++11 -O3 -std=gnu++11  -Werror=unused-label -fopenmp -Werror=unknown-pragmas
Link flags:   
OpenMP support: ON
MMAP support: ON

**Comment by Floessie** [comment]
Reproduced it on current master. Looking...

**Comment by Floessie** [comment]
Fix:
```patch
diff --git a/rtgui/cropwindow.cc b/rtgui/cropwindow.cc
index f7d7c30..b0132f9 100644
--- a/rtgui/cropwindow.cc
+++ b/rtgui/cropwindow.cc
@@ -2535,8 +2535,11 @@ void CropWindow::setCropGUIListener       (CropGUIListener* cgl)
 void CropWindow::setPointerMotionListener (PointerMotionListener* pml)
 {
     pmlistener = pml;
-    pml->signal_cycle_rgb().connect( sigc::mem_fun(*this, &CropWindow::cycleRGB) );
-    pml->signal_cycle_hsv().connect( sigc::mem_fun(*this, &CropWindow::cycleHSV) );
+
+    if (pml) {
+		pml->signal_cycle_rgb().connect( sigc::mem_fun(*this, &CropWindow::cycleRGB) );
+		pml->signal_cycle_hsv().connect( sigc::mem_fun(*this, &CropWindow::cycleHSV) );
+    }
 }
 
 PointerMotionListener* CropWindow::getPointerMotionListener ()
```

Best
Flössie

**Comment by Beep6581** [comment]
@Floessie bug and fix confirmed.

**Comment by Floessie** [comment]
@Beep6581 Thanks. Feel free to commit the fix yourself. :smile:

**Comment by RuralHunter** [comment]
Thanks for the quick fix!
