### ISSUE TITLE
Can not import default raw settings

### ISSUE THREAD

**Issue by 243750496** [Beep6581/RawTherapee#3457]
i want to load default settings as the improted raw image, but after i double click the image it will auto set some adjustment to it , how to be original? and buy the way what's the difference of right side of welcome page that also have some configuration can set and do to images(or single) and the advance edit mode withch showup after double clicked the image 
![screenshot 2016-10-13 20 12 09](https://cloud.githubusercontent.com/assets/6311930/19348674/ae956146-9181-11e6-9911-15801ff6d195.png)
![screenshot 2016-10-13 20 12 35](https://cloud.githubusercontent.com/assets/6311930/19348673/ae94af62-9181-11e6-8b1d-716b83fcadda.png)

**Comment by Beep6581** [comment]
Please read the [documentation](http://rawpedia.rawtherapee.com/) first, specifically [this](http://rawpedia.rawtherapee.com/The_Image_Editor_Tab#Eek.21_My_Raw_Photo_Looks_Different_than_the_Camera_JPEG), [this](http://rawpedia.rawtherapee.com/Sidecar_Files_-_Processing_Profiles) and [this](http://rawpedia.rawtherapee.com/Creating_processing_profiles_for_general_use), and use our [forum](https://discuss.pixls.us/c/software/rawtherapee) for user support, not GitHub.
