### ISSUE TITLE
Wavelet (below or equal, all directions) Preview in combination with Contrast adjustment

### ISSUE THREAD

**Issue by pi99y** [Beep6581/RawTherapee#3459]
EDIT:
OK I just realised that the first screenshot is a bad example since I changed the contrast of above levels too. But the question and animated GIF example remains - Should such a drastic contrast change result in no visible change?
---

This seems strange:
* adjust the weavlet contrast drastically
* set weavlet process to "below or equal" and "all directions"
there is no visible change if the contrast setting are on or off.

Now leave the contrast settings the same, just change the process to "all levels all directions" or even the current level directions to something other than "all directions", the change is clearly visible:

![rt_wq](https://cloud.githubusercontent.com/assets/10639257/19368924/c2e9be3c-91a2-11e6-81aa-b1be99895c00.jpg)

Animated GIF to see there really is no change: (and it's not because GIF is limited to 256 colors)

![rt_wq](https://cloud.githubusercontent.com/assets/10639257/19369019/3ec8f676-91a3-11e6-87c9-b7f401ee3b5a.gif)

Is this correct behaviour? Seems strange to me.

My setup: (Fuji x-trans raw file (X-pro 1), Win 8.1 64bit, Branch: master, Version: 4.2.1122, Changeset: 29d5329f3f8d212186260ac7775ec46317d61f29)

**Comment by heckflosse** [comment]
@pi99y If there's no detail for the levels below or equal 4 you won't see a difference when viewing `Below or equal the level`, `Level 4`

**Comment by pi99y** [comment]
If there were no details wouldnt be the preview blank gray? The person is visible due to details in those first 4 levels, no?

**Comment by heckflosse** [comment]
@pi99y Unfortunately your screen shot hides the setting of `Apply to` at the bottom. Enabling `Contrast` uses that setting, while disabling `Contrast` ignores it (as it is in `Contrast` section)

**Comment by heckflosse** [comment]
@pi99y Wouldn't it be better to discuss this in [rt forum](https://discuss.pixls.us/c/software/rawtherapee) ?

**Comment by heckflosse** [comment]
@pi99y `Should such a drastic contrast change result in no visible change?` Not if you apply it to 'Shadows/Highlights' only.

**Comment by pi99y** [comment]
Ha, I totally missed the "Apply to" section.
Indeed, swhitching it to "whole range" it now behaves as I expected. 
Sorry for the alarm. Other weavlet settings like Chroma and Denoise worked on the same "preview" so it looked like a bug to me. But yeah, I missed the "Apply to" section.

Thanks @heckflosse for the explanation.

I'll try asking in IRC next time beforehand (since I dislike registering yet for another service like forums).
