### ISSUE TITLE
Olympus OMD E10 MK2 pink raw

### ISSUE THREAD

**Issue by frspp** [Beep6581/RawTherapee#3471]
If overexposed, RT shows & exports in pink.
Raw: https://filebin.net/5db68swymrvkitjk
RT: latest downloaded from http://rawtherapee.com on OSX 10.11.

Branch: master
Version: 4.2.876
Changeset: ba534817502c7f02930efb567c6dd6f74cfe995a
Compiler: clang-mp-3 3.7.1
Processor: generic x86
System: Apple
Bit depth: 64 bits
Gtkmm: V2.24.4
Build type: Release
Build flags: -w -std=gnu++11 -mtune=generic -Werror=unused-label -fopenmp=libomp -Werror=unknown-pragmas -O3 -DNDEBUG
Link flags:  -mtune=generic
OpenMP support: ON
MMAP support: ON

**Comment by heckflosse** [comment]
@frspp Works fine here using latest rt version. Please download [this file](https://github.com/Beep6581/RawTherapee/blob/master/rtengine/camconst.json), copy it over the existing one on your system and try again. Don't know where that is on OSX though.

**Comment by heckflosse** [comment]
Reopened this issue because there's still an issue with that file...

**Comment by heckflosse** [comment]
@iliasg Can you have a look? I have to dial in 1.01 raw white point to avoid pink highlights

**Comment by frspp** [comment]
Ye, I also tried with camconst.json you linked to, didn't help.

**Comment by heckflosse** [comment]
@frspp Can you change line 1413 of camconst.json to
`        "make_model": [ "OLYMPUS E-M10", "OLYMPUS E-M10 Mark II", "OLYMPUS E-M10MarkII" ],`
and try again?

I tried and that works fine here

**Comment by frspp** [comment]
Yes, works here too. Thanks!

**Comment by Beep6581** [comment]
Now it's my turn to re-open ;)

**Comment by frspp** [comment]
haha ok :D I made fork for myself and made a pull request, this is proper way to do it?

**Comment by heckflosse** [comment]
:+1:

**Comment by heckflosse** [comment]
Merged into master branch

**Comment by heckflosse** [comment]
@frspp Thanks for your help :+1:
