### ISSUE TITLE
CbDL badly interacts with Graduated and Vignetting Filter if CbDL is set to 'before Black-and-White'

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3473]
https://filebin.net/0k6p7aduvsvb3iu0/imgur-2016_10_20-12_12_05.png
https://filebin.net/0k6p7aduvsvb3iu0/cbdl_vignetting.pp3

It seems that having CbDL enabled while dragging the Graduated Filter widget makes the preview go crazy. The more I drag the widget, the worse the preview becomes.
Using gtk3-testing branch, haven't tried master yet.

**Comment by Beep6581** [comment]
Update: Every time I turn on the Vignetting Filter or the Graduated Filter the preview gets worse. So if I turn it on and off and on and off and repeat, it gets very bad.

**Comment by heckflosse** [comment]
I'll have a look

**Comment by heckflosse** [comment]
Confirmed, when CbDL is set to 'before Black-and-White'.
Works fine when CbDL is set to 'after Black-and-White'.
