### ISSUE TITLE
Incorrect exposure correction

### ISSUE THREAD

**Issue by nmalykh** [Beep6581/RawTherapee#3476]
RawTherapee 4.2.1171
Exposure correction reset previous rotation.

**Comment by heckflosse** [comment]
@nmalykh [How to write useful bug reports](http://50.87.144.65/~rt/w/index.php?title=How_to_write_useful_bug_reports)

**Comment by heckflosse** [comment]
@nmalykh Now I understood what you mean. Bug confirmed.

**Comment by heckflosse** [comment]
@nmalykh Thanks for reporting the bug :+1:
