### ISSUE TITLE
Gtk+ >=3.20 Slider knob bottom half does not register click

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3479]
If I hover the mouse cursor over the bottom half of the slider's knob, it does not register a click event, so I can't drag the slider.  In fact the active area doesn't go all the way up to the top either, it seems to catch the event in the area from the middle of the knob half way to the top. Nothing for the bottom.
![knob](https://cloud.githubusercontent.com/assets/5844619/19628767/47f061b6-9965-11e6-86b4-2e7495febac2.jpg)

Maybe related to this. When I click the knob in Gtk Inspector, it shows this:
![imgur-2016_10_23-20 54 25](https://cloud.githubusercontent.com/assets/5844619/19628765/440eae9a-9965-11e6-8513-003c476af9de.jpg)

**Comment by Hombre57** [comment]
Solved in commit c1a6abb. Could you confirm ?

**Comment by Beep6581** [comment]
Confirmed, thank you!
