### ISSUE TITLE
Crop-guide is wrong when panning image out of preview in Fit-To-Screen mode

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#3480]
Apply a crop. Select 'Rule of thirds'. Switch to 'Fit to Screen' using 'f'-key.
Then pan the preview to move 50% of the crop out of the preview.
=> Crop-guide is wrong

**Comment by Hombre57** [comment]
Works fine now in master.

**Comment by heckflosse** [comment]
@Hombre57 Fix confirmed. Thank you :+1:
