### ISSUE TITLE
Gtk+ >=3.20 Whole window goes black

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3482]
Using Gtk+ 3.20.9
Reproducible: Not reliably.

Sometimes when I start RT and open a photo, the whole RT window turns black. The contents are there, because if I hover the mouse over the right place I get a visible tooltip over the blackness. Un-maximizing the window draws everything. If I maximize it, things stay good. When that happens, if I toggle the filmstrip, the window always (?) goes black again, and when I toggle the filmstrip again it fixes itself.

If the RT window does not go black when I open an image after loading RT, then toggling the filmstrip does not trigger the problem.

**Comment by heckflosse** [comment]
Sounds like an uninitialized variable

**Comment by Floessie** [comment]
Seen it, too. My debug build spits out the following:
```
(rawtherapee:815): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width -1192119356 and height 203
```

**Comment by Floessie** [comment]
Maybe the hints in #2925 help with debugging.

**Comment by Floessie** [comment]
Here is the tail of all those messages:
```
Gtk-Message: gtk_widget_size_allocate:                 gtkmm__GtkPaned 0 0 939 256, baseline -1
Gtk-Message: gtk_widget_size_allocate:                   gtkmm__GtkVBox 0 0 939 256, baseline -1
Gtk-Message: gtk_widget_size_allocate:                     gtkmm__GtkHBox 20 20 899 216, baseline -1
Gtk-Message: gtk_widget_size_allocate:                       gtkmm__GtkVBox 21 21 897 214, baseline -1
Gtk-Message: gtk_widget_size_allocate:                         gtkmm__GtkHBox 22 22 895 205, baseline -1
Gtk-Message: gtk_widget_size_allocate:                           gtkmm__GtkDrawingArea 23 23 893 203, baseline -1
Gtk-Message: gtk_widget_size_allocate:                           gtkmm__GtkVScrollbar 83458482 23 -166947900 203, baseline -1

(rawtherapee:10300): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width -166947900 and height 203
```

Tested with 7124681, not yet seen on current `gtk3-bugfix`.

HTH
Flössie

**Comment by Beep6581** [comment]
Tried with `GTK_DEBUG=geometry G_DEBUG=fatal-warnings`, could not reproduce the `attempt to allocate widget with width -verylongnumber and height smallnumber` problem on `gtk3-bugfix` either.

**Comment by Floessie** [comment]
Me neither. I can't see the bug nor the message on `gtk3-bugfix`, only on 7124681.

**Comment by Hombre57** [comment]
Is the black screen still occurring with actual gtk3-bugfix branch ? If not (for both problems), I think this issue should be closed.

**Comment by Beep6581** [comment]
Hasn't occurred yet using commit 965cadb52ead7fcedf90585cab2fd7f470c85f36

**Comment by Floessie** [comment]
I switched my repo from `master` to 965cadb, deleted my `build` directory, ran `cmake` and `make install` again. The *all black* issue is gone.

But there are other issues popping up. Have I done something wrong when switching branches? There is no CSS warning when starting.

- When maximizing (not full screen) the window title bar is gone. When restoring (via WM, XFCE in my case) it only appears again after I resize the window.
- The fonts are rather big and there is only minimal space between the tab titles.
- In file browser mode the hand tool icon overlaps with those icons on the left (on a small window).
- In SETM/VT the vertical progress bar on the left fills top to bottom.

Those are only the most obvious things. I must have done something wrong when reinstalling. Any hint?

**Comment by Beep6581** [comment]
@Floessie let's close this issue and take up your points in #3446 or in separate issues.
