### ISSUE TITLE
Gtk+ >=3.20 Comboboxes must not let content overflow

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3483]
Comboboxes in Gtk+ >=3.20 have different defaults than they had previously. All comboboxes in RT must be made to not allow text overflow.
The Processing Profiles selector is one such combobox which must be fixed, as it currently expands to the left to accommodate for the longest item it contains, which means if one of the PP3s has a long name it looks like this:
![imgur-2016_10_24-14 57 04](https://cloud.githubusercontent.com/assets/5844619/19646528/1b8f317a-99fa-11e6-99b4-f3869a6b01b7.png)

**Comment by Beep6581** [comment]
@Hombre57 could we include this one for RT5 release?

**Comment by Hombre57** [comment]
Yes.

**Comment by Hombre57** [comment]
The content does not overflow anymore, but the content of the combobox doesn't "ellipsize".

**Comment by Beep6581** [comment]
@Hombre57 unfortunately the committed code does not work well. In gtk3-bugfix 2fcc5b75c83c6f7ebe9f3347046fc2e5e4b46a36 the right panel's minimum width is now huge, as it depends on the length of the longest entry in the Processing Profile combo.
I cannot shrink the right panel anymore: https://i.imgur.com/dB6xkyK.jpg
On a lower resolution screen there would be no room left for the preview.

**Comment by Hombre57** [comment]
That's what I meant by "the combobox doesn't ellipsize". I'm working on that, but we may need to get in touch with the Gtk dev team on their IRC. What is the best hours to do that (UTC) ?

**Comment by Beep6581** [comment]
I saw most activity around afternoon-evenings Euro-time, though some are from outside of Europe so you might get lucky at any time. Best if you leave your IRC client up 24 hours and repeat the question every few hours.

**Comment by Beep6581** [comment]
Fix confirmed.
