### ISSUE TITLE
Additions to preferences: default grid, default aspect ratio, lock ratio on/off

### ISSUE THREAD

**Issue by frspp** [Beep6581/RawTherapee#3484]
My wishlist
1. Add to preferences/somewhere: option to choose default grid when cropping (for me it's no grid)
2. Add to preferences/somewhere: option to choose default aspect ratio and lock ratio on/off state when cropping

And this one may even be a bug?
3. Cropping works very nicely in Adobe Camera Raw. Once you choose cropping tool, you see also areas outside of crop. When tool is changed/crop is accepted (with enter), it only shows cropped area. I see Rawtherapee also work the same with Black and White editor backgrounds, but not with grey. Possible to also have  grey bg working the same way?

**Comment by Beep6581** [comment]
One item per issue please.

- 1 and 2 are handled by making your own default processing profile. http://rawpedia.rawtherapee.com/
Related:

  * #2255 Crop guide: migrate to toolbar
  * #1192 Crop panel redesign

- 3 is handled by Preferences > Default Theme > Crop mask color/transparency.

Closing.

**Comment by frspp** [comment]
ah yes, thanks for info

**Comment by frspp** [comment]
3: I tried this few times, but doesn't work. It always defaults to "Guide type: Rule of thirds" even when other settings (exposure, sharpening) are read from my default profile.
