### ISSUE TITLE
Compile support for system libraries

### ISSUE THREAD

**Issue by mattiaverga** [Beep6581/RawTherapee#3492]
I'm packaging Rawtherapee for Fedora and distribution guidelines requires to use libraries already present in the system, if possible.
It is possible to compile Rawtherapee using the klt library already present as standalone package in Fedora, instead of using the bundled version?
Thanks.

**Comment by sharkcz** [comment]
see pull request #3573

**Comment by Beep6581** [comment]
Seems to have been implemented in RawTherapee 5.2.
