### ISSUE TITLE
Gtk+ >=3.20 #ThresholdSelector

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3496]
Commit 965cadb52ead7fcedf90585cab2fd7f470c85f36 affected the ThresholdSelector
Now the CbDL Skin Hue ThresholdSelector does not show the gradient background in the right place:
https://i.imgur.com/tgn0M4k.png

Further, if I apply styling using CSS, it appears that the ThresholdSelector in Sharpening is constructed differently to the one in CbDL - the background behaves differently, please see:
![imgur-2016_11_02-09 31 36](https://cloud.githubusercontent.com/assets/5844619/19921634/21c341b2-a0df-11e6-8736-1ef76e669552.png)

The CSS:
```
#ThresholdSelector {
  background-image: -gtk-gradient (linear,
                                   left top, right top,
                                   color-stop(0, #ff0000),
                                   color-stop(0.5, #00ff00),
                                   color-stop(1, #0000ff));
}
```

**Comment by Hombre57** [comment]
Adding a gradient background in ThresholdSelector have to be done in the code, not the CSS.

**Comment by Beep6581** [comment]
What sort of element are the four "knobs" in a ThresholdSelector?

**Comment by Hombre57** [comment]
They are all handled hand rendered by the ThresholdSelector object, which inherits the `drawingarea` and `trough` class (see line 145 of thresholdselector.cc).

I've looked for hours to see how to set style to subparts of a custom widget, but didn't found anything. I guess that I have to create a `Knob` widget to have a dedicated style. If you find something on this, I'm interested. Actually, the knobs and the trough are rendered using the `drawingarea` class I suppose.

**Comment by Beep6581** [comment]
The Skin Hue threshold selector in CbDL still has no background gradient:
https://i.imgur.com/cuOnztL.png

**Comment by Beep6581** [comment]
Fix confirmed.
