### ISSUE TITLE
Gtk+ >=3.20 SETM - Vertical tabs inconsistent icons

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3498]
The main notebook tabs are inconsistent in SETM - Vertical: Queue and File Browser have their icons on the top, while Editor has its on the bottom:
https://i.imgur.com/ar9zO33.png

Non-vertical is fine.

This was a regression introduced in commit 6438645b2142488347dc82b2f1bd46123aa5ff9a, the previous commit didn't have it.

**Comment by Hombre57** [comment]
I'll update the vertical tabs to have icons below the labels.

**Comment by Beep6581** [comment]
Fix confirmed.
