### ISSUE TITLE
Navigator/LockableColorPicker does not show correct RGB/HSV for output profile

### ISSUE THREAD

**Issue by mmmtok** [Beep6581/RawTherapee#3506]
Problem found in version 4.2.1184.

Reproduction procedure:
1. Set preference to see histogram as output profile.
2. Set some output profile
3. See RGB/HSV values in navigator or lockable color picker
4. Set another output profile
5. See RGB/HSV values
6. Compare values from step 3 and step 5.  All seem to be sRGB values.

Candidate fix:
```
diff --git a/rtengine/iplab2rgb.cc b/rtengine/iplab2rgb.cc
index 6b04bb8..c6e5c3d 100644
--- a/rtengine/iplab2rgb.cc
+++ b/rtengine/iplab2rgb.cc
@@ -144,8 +144,6 @@ Image8* ImProcFunctions::lab2rgb (LabImage* lab, int cx, int cy, int cw, int ch,
 
     Image8* image = new Image8 (cw, ch);
     Glib::ustring profile;
-    cmsHPROFILE oprof = iccStore->getProfile (profile);
-
     bool standard_gamma;
 
     if(settings->HistogramWorking) {
@@ -159,6 +157,8 @@ Image8* ImProcFunctions::lab2rgb (LabImage* lab, int cx, int cy, int cw, int ch,
         standard_gamma = false;
     }
 
+    cmsHPROFILE oprof = iccStore->getProfile (profile);
+
     if (oprof) {
         cmsHPROFILE oprofG = oprof;
```

**Comment by Beep6581** [comment]
With "Use working profile for ..." enabled, the LCP matches the values in the Navigator.
They both change when I change the working profile, and don't change when I change the output profile.

With "Use working profile for ..." disabled, the LCP matches the values in the Navigator.
They change slightly when I change the working profile:
- https://i.imgur.com/p7AMPwW.jpg
- https://i.imgur.com/VfjzspT.jpg
They change when I change the output profile to/from Rec. 2020 and only for that profile:
- RT_sRGB https://i.imgur.com/3CHaB9t.jpg
- RT_Large_g10 https://i.imgur.com/Kujx0Ov.jpg
- Rec. 2020 https://i.imgur.com/FopSm9n.jpg
- Swapped Red and Green https://i.imgur.com/REzJsMi.jpg

**Comment by Beep6581** [comment]
@Hombre57 can this be closed?
