### ISSUE TITLE
Remote processing?

### ISSUE THREAD

**Issue by ror6ax** [Beep6581/RawTherapee#3509]
Hi, I'm wondering if there is any interest in doing something of a render-farm style remote processing capability. Currently, most of my laptops(admittedly old ones) are crashing once processing queue gets more than one image.

This functionality is something I like very much about RT, and I believe many would agree that spinning an amazon instance worker for couple of hours is cheaper than buying a top class equipment for raw conversion only.

I'm no C++ programmer, I'd need someone to provide an interface for the core functionality of the converter, but the actual deployment, setting up, and connectivity - that I can handle.

Thanks,
Greg

**Comment by Hombre57** [comment]
@ror6ax What do you mean by _interface to the core functionality_ ? I guess that you want RT to be started as a service ? That's not planed and I don't think any devs knows how to do that. I'd however like to provide a rawtherapee-cli.exe version where the GUI wouldn't be included in the binary. I don't know how much time it could require though.

**Comment by ror6ax** [comment]
I meant some api I can talk to from the webserver. CLI would do, but ideally I'd prefer a socket for this.

**Comment by Beep6581** [comment]
CLI now exists.
