### ISSUE TITLE
Change license of rtdata/rt_splash_5.svg to CC BY-SA 3.0 please

### ISSUE THREAD

**Issue by innir** [Beep6581/RawTherapee#3511]
Hi,

currently rtdata/rt_splash_5.svg is licensed under [CC BY-NC-SA 3.0](http://creativecommons.org/licenses/by-nc-sa/3.0/) which is a problem for many Linux distributions as only modifications for non commercial uses are allowed.This makes it non-free in the Debian sense. Could the license be change to [CC BY-SA 3.0](http://creativecommons.org/licenses/by-sa/3.0/)?

Best,
Philip

**Comment by Beep6581** [comment]
Good catch!
