### ISSUE TITLE
Idea for the handling of monochrome non-raw files

### ISSUE THREAD

**Issue by jtappin** [Beep6581/RawTherapee#3515]
While the handling of raw files from monochrome cameras has been discussed and looks (as far as I can tell) to be handled (#2001 and #2409), handling of single-channel non-raw files is unavailable.

This is something of an issue for those of us using RT for processing scans from B&W film, as making 3-channel 16-bit tiff files uses serious amounts of disk space (a quality scan of a 35mm negative is likely to be more than 20Mp -- or 120Mb uncompressed, maybe 80 compressed), and there's no mosaicing to reduce space hence the sizes are typically about 3+ times those of comparable camera raw files.

I'm aware that handling single channel throughout the path is probably not practical as it would involve major internal changes, but I would suggest that it might be possible to read single channel files and use them to populate the 3 channels with identical values (and it would be nice if the "Black and White" option in the colours tab were automatically enabled in this case).

**Comment by Floessie** [comment]
This scheme is already used for [grayscale PNGs](https://github.com/Beep6581/RawTherapee/blob/master/rtengine/imageio.cc#L350), so as a workaround you could use PNGs. IMHO JPEGs and TIFFs should be handled consistently. I'll take a look when I find some spare time after Christmas.

**Comment by Floessie** [comment]
Okay, here is a preliminary patch. JPEG was super simple, TIFF a bit more work. Please have a look:

```patch
diff --git a/rtengine/imageio.cc b/rtengine/imageio.cc
index f869a0f..4afedd2 100644
--- a/rtengine/imageio.cc
+++ b/rtengine/imageio.cc
@@ -556,11 +556,13 @@ int ImageIO::loadJPEG (Glib::ustring fname)
         jpeg_read_header(&cinfo, TRUE);
 
         //if JPEG is CMYK, then abort reading
-        if (cinfo.jpeg_color_space == JCS_CMYK || cinfo.jpeg_color_space == JCS_YCCK || cinfo.jpeg_color_space == JCS_GRAYSCALE) {
+        if (cinfo.jpeg_color_space == JCS_CMYK || cinfo.jpeg_color_space == JCS_YCCK) {
             jpeg_destroy_decompress(&cinfo);
             return IMIO_READERROR;
         }
 
+        cinfo.out_color_space = JCS_RGB;
+
         deleteLoadedProfileData();
         loadedProfileDataJpg = true;
         bool hasprofile = read_icc_profile (&cinfo, (JOCTET**)&loadedProfileData, (unsigned int*)&loadedProfileLength);
@@ -677,8 +679,8 @@ int ImageIO::getTIFFSampleFormat (Glib::ustring fname, IIOSampleFormat &sFormat,
 
     TIFFClose(in);
 
-    if (photometric == PHOTOMETRIC_RGB) {
-        if ((samplesperpixel == 3 || samplesperpixel == 4) && sampleformat == SAMPLEFORMAT_UINT) {
+    if (photometric == PHOTOMETRIC_RGB || photometric == PHOTOMETRIC_MINISBLACK) {
+        if ((samplesperpixel == 1 || samplesperpixel == 3 || samplesperpixel == 4) && sampleformat == SAMPLEFORMAT_UINT) {
             if (bitspersample == 8) {
                 sFormat = IIOSF_UNSIGNED_CHAR;
                 return IMIO_SUCCESS;
@@ -820,7 +822,7 @@ int ImageIO::loadTIFF (Glib::ustring fname)
     allocate (width, height);
 
     float minValue[3] = {0.f, 0.f, 0.f}, maxValue[3] = {0.f, 0.f, 0.f};
-    unsigned char* linebuffer = new unsigned char[TIFFScanlineSize(in)];
+    unsigned char* linebuffer = new unsigned char[TIFFScanlineSize(in) * (samplesperpixel == 1 ? 3 : 1)];
 
     for (int row = 0; row < height; row++) {
         if (TIFFReadScanline(in, linebuffer, row, 0) < 0) {
@@ -829,10 +831,18 @@ int ImageIO::loadTIFF (Glib::ustring fname)
             return IMIO_READERROR;
         }
 
-        if (samplesperpixel > 3)
+        if (samplesperpixel > 3) {
             for (int i = 0; i < width; i++) {
                 memcpy (linebuffer + i * 3 * bitspersample / 8, linebuffer + i * samplesperpixel * bitspersample / 8, 3 * bitspersample / 8);
             }
+        }
+        else if (samplesperpixel == 1) {
+            for (int i = width; i >= 0; --i) {
+                memcpy(linebuffer + i * 3 * bitspersample / 8 + 2, linebuffer + i * bitspersample / 8, bitspersample / 8);
+                memcpy(linebuffer + i * 3 * bitspersample / 8 + 1, linebuffer + i * bitspersample / 8, bitspersample / 8);
+                memcpy(linebuffer + i * 3 * bitspersample / 8 + 0, linebuffer + i * bitspersample / 8, bitspersample / 8);
+            }
+        }
 
         if (sampleFormat & (IIOSF_LOGLUV24 | IIOSF_LOGLUV32 | IIOSF_FLOAT)) {
             setScanline (row, linebuffer, bitspersample, minValue, maxValue);
```

HTH
Flössie

**Comment by jtappin** [comment]
Impressive turnaround :-)

**Comment by jtappin** [comment]
Unfortunately it doesn't seem to quite work. I tried with a couple of 16-bit 1-channel tiffs. One (the larger) was opened, but with corrupted colours:
![rt_gs_tiff](https://cloud.githubusercontent.com/assets/658624/20679850/79679372-b594-11e6-8186-ce7ef42f43d9.jpeg)
A smaller version of the same image crashed RT with an double free error:
```
$ rawtherapee IMG_0004a.tif 
RawTherapee, version 4.2.1200
*** Error in rawtherapee double free or corruption (!prev): 0x0000000003e60580 ***
```
And a long traceback (I have saved it but I doubt it's much use).

**Comment by heckflosse** [comment]
`for (int i = width; i >= 0; --i) {`
shouldn't that be 
`for (int i = width - 1; i >= 0; --i) {`

**Comment by Floessie** [comment]
@heckflosse Of course, you are right. :+1: 

@jtappin 
> Impressive turnaround :-)

:slightly_smiling_face: But only expect it to land in RT 5.1, not 5.0.

Could you provide me with one of your failing files via [filebin.net](https://filebin.net/)?

**Comment by Floessie** [comment]
Got it! I'll push a branch soon...

**Comment by Floessie** [comment]
I created a branch [`grey-imageio`](https://github.com/Beep6581/RawTherapee/compare/grey-imageio).

Best
Flössie

**Comment by jtappin** [comment]
They are at:
filebin.net/2ioxiuup9vkv8y4x
The small one IMG_0004a.tif caused the crash, the bad colours were from IMG_0002a.tif.
FWIW both files were converted from RGB files with gimp 2.9.4 as I couldn't find any original greyscale scans.

**Comment by Floessie** [comment]
@jtappin Tested your images with the `grey-imageio` branch: They look okay to me now.

**Comment by jtappin** [comment]
@Floessie I can confirm that it works for me now -- I guess the indexing offset was the killer.

**Comment by jtappin** [comment]
I do however still see the corrupted colours in the file browser for IMG_0002a.tif (exaclty the same pattern as in the screenshot I provided earlier), though it is opened correctly when I select it.

**Comment by Floessie** [comment]
@jtappin 
> I guess the indexing offset was the killer.

Exactly! I was missing the fact, that I was in byte realm and only had an 8b TIFF tested. :tired_face: 

> I do however still see the corrupted colours in the file browser for IMG_0002a.tif (exaclty the same pattern as in the screenshot I provided earlier), though it is opened correctly when I select it.

That's because the old version of the thumbnail got cached. If you clear your cache or copy/move the file to have a new name, you'll see it corrected.

HTH
Flössie

**Comment by jtappin** [comment]
Thanks, clearing the cache did the trick.

Being able to use greyscale TIFFs should save a bit over 3Gb per film!

**Comment by Beep6581** [comment]
This is good! Is this safe to go into 5.0, or 5.1? I ask because I'm wondering how to update the docs.

**Comment by Floessie** [comment]
@Beep6581 

Pros:
- Straightforward, reviewable change
- Consistency with PNGs
- Feature request pops up regularly

Cons:
- Not reviewed by @heckflosse :wink: 
- Only `PHOTOMETRIC_MINISBLACK`-TIFFs supported (but this is the norm) and no evaluation of `minValue` and `maxValue` (as with color TIFFs)
- A bit late in the game

I abstain from voting and leave it up to you to decide.

**Comment by heckflosse** [comment]
@Floessie I will review it now

**Comment by heckflosse** [comment]
@Floessie @Beep6581 Builds and works fine. No objections from me.
@Floessie Is there a reason you memcpy from width-1 to 0 instead of 0 to width-1?

**Comment by Floessie** [comment]
@heckflosse 
> Is there a reason you memcpy from width-1 to 0 instead of 0 to width-1?

`linebuffer` is source and destination, and I don't want to destroy the data in the first third of the buffer when progressing forward.

**Comment by heckflosse** [comment]
@Floessie I see now. Thanks for explanation :+1:

**Comment by Floessie** [comment]
Likewise, thanks for reviewing! :+1: 

PS: I know that iterating backward isn't that cache friendly, but doing so was simpler.

**Comment by Beep6581** [comment]
Tested with PNG and TIFF, 8-bit and 16-bit integer (floating-point TIFFs don't show up in the file browser), works fine! +1 for merge now.

**Comment by Floessie** [comment]
@Beep6581 
> (floating-point TIFFs don't show up in the file browser)

[Some](https://www.cheshireeng.com/HDReye/files/HDReyeSampleWhiteBalanced.tif) did and still do. There's a variety of subformats, and RT only supports the plain ones.

Shall I merge, or will you?

**Comment by Beep6581** [comment]
I tried the floating-point ones from GIMP-git only.

You're welcome to merge into master.

**Comment by heckflosse** [comment]
@Floessie Thanks a lot :+1:

**Comment by jtappin** [comment]
Thank you all.

**Comment by Floessie** [comment]
Not for that trifle... :blush:
