### ISSUE TITLE
build fails when using libcairo 1.15

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#3517]
Reported by @mbajor on irc

[  241s] /home/abuild/rpmbuild/BUILD/rawtherapee-4.2.1197/rtengine/../rtgui/guiutils.h:440:16: error: cannot convert 'Cairo::RefPtr<Cairo::ImageSurface>' to 'bool' in return
[  241s]          return surface;

using libcairo 1.14 it builds

**Comment by heckflosse** [comment]
Related:
https://bugzilla.gnome.org/show_bug.cgi?id=626858#c4
https://git.gnome.org/browse/glibmm/commit/?id=aee3a6fa6a37e1178b43437966b4225a34f9c6e2

**Comment by heckflosse** [comment]
@mbajor Can you test this patch please?

```
diff --git a/rtgui/guiutils.h b/rtgui/guiutils.h
index 38f5297..b8e058e 100644
--- a/rtgui/guiutils.h
+++ b/rtgui/guiutils.h
@@ -437,7 +437,7 @@ public:
     // you have to check if the surface is created thanks to surfaceCreated before starting to draw on it
     bool surfaceCreated()
     {
-        return surface;
+        return static_cast<bool>(surface);
     }
     Cairo::RefPtr<Cairo::ImageSurface> getSurface()
     {

```

**Comment by mbajor** [comment]
@heckflosse Fix confirmed. Thanks ! :)

**Comment by heckflosse** [comment]
@Beep6581 @Floessie @Hombre57 
Any objections to commit this in master branch?

**Comment by Hombre57** [comment]
No objection on committing.

Just for my personal information: isn't `bool(surface)` the same than `static_cast<bool>(surface);` ?

**Comment by Floessie** [comment]
@heckflosse Absolutely no objections. I would have solved it exactly the same way.

@Hombre57 
> Just for my personal information: isn't bool(surface) the same than static_cast<bool>(surface); ?

No. A C-style cast is equivalent to `reinterpret_cast<>`, which has no restrictions at all. For a `static_cast<>` the types have to be convertible. But you are right: In this place a c'tor-like C-style cast would have also done, although a C++-style cast should be prefered as it's more meaningful.

Best
Flössie
