### ISSUE TITLE
TooWaBlue-GTK3-20_ / Gtk+3.20 ready / & Deutsch locale

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#3518]
TooWaBlue for Gtk+3.20 is ready. I've add the font "Arial" to the theme. This font is available on every Windows OS. The default font is so ugly. If the font doesn't exists, this entry is ignored and the default font is used.
[TooWaBlue-GTK3-20_.txt](https://github.com/Beep6581/RawTherapee/files/625190/TooWaBlue-GTK3-20_.txt)

Deutsch locale based on RT 4.2.1408
[Deutsch.txt](https://github.com/Beep6581/RawTherapee/files/625192/Deutsch.txt)

Screenshot
![unbenannt](https://cloud.githubusercontent.com/assets/13800920/20802258/d04ada92-b7eb-11e6-8d1b-89b3732c5b5e.png)

**Comment by gaaned92** [comment]
For those who use gtk3-bugfix build and want to test before inclusion in the git source:
- copy in <RTinstallDir>/themes
- change the file type .txt to .css
- choose default theme Toowablue in preferences
