### ISSUE TITLE
Suggestion: Change how external Editor is called on Windows

### ISSUE THREAD

**Issue by Partha1b** [Beep6581/RawTherapee#3522]
I suggest that we use a Windows specific API to access external editor in that OS. This has the flexibility of being supported by Microsoft and moreover, does not require any additional steps to compile on Windows. 

The API I am thinking of is ShellExecute (https://msdn.microsoft.com/en-us/library/bb762153(VS.85).aspx). I am happy to provide the code and test it. 

This will not change the end User experience and will not require any additional learning curve.

Thanks,
Partha

**Comment by heckflosse** [comment]
@Partha1b 

> I am happy to provide the code and test it.

I will be happy if you provide the code and can test it too. :+1:

**Comment by Partha1b** [comment]
Thanks for your support. :)

Anyway seriously, I have a issue. I tested my code and it works fine for my
GIMP builds on Windows. So, that's good. However, before GIMP starts for
me, I get the dialogbox claiming "Cannot start editor\n Please set the
correct path in Preference". Any suggestions on why I am triggering this?

Also, any volunteers for testing the build? :)

Thanks,
Partha

**Comment by heckflosse** [comment]
> Also, any volunteers for testing the build? :)

Sure, tell me where I can find the source. Then I will build and test it.

**Comment by Partha1b** [comment]
Thanks for the offer. As you know I'm only modifying 1 file at the moment.

Should I upload that file somewhere or do you prefer that I create a
tarball with the code?

Note that my git pull is current as of today.

**Comment by heckflosse** [comment]
@Partha1b Just that file should be enough to test. Upload it to filebin.net please.

**Comment by Partha1b** [comment]
I've never used filebin.net before. Hope this works. I think I need to give
you this URL? https://filebin.net/d65mu2yc3xsqz1mf

**Comment by heckflosse** [comment]
Thanks for the file. Already downloaded. Building now...

**Comment by heckflosse** [comment]
I tested. Currently it does not work because I don't have `gimp-win-remote` installed

**Comment by heckflosse** [comment]
@Partha1b 
```
If the function succeeds, it returns a value greater than 32.
If the function fails, it returns an error value that indicates the cause of the failure.
The return value is cast as an HINSTANCE for backward compatibility with 16-bit Windows applications.
It is not a true HINSTANCE, however.
It can be cast only to an int and compared to either 32 or the following error codes below.
```

**Comment by heckflosse** [comment]
@Partha1b [This one](https://filebin.net/hqifb7htz55jfzub) works fine here

**Comment by Partha1b** [comment]
I don't know what this gimp-win-remote is. Do we need this part of the code?

**Comment by Partha1b** [comment]
Well, I am still getting can't start editor and then it starts it.
Remember, I am using my own build and so have to pass a command line to RT.
I'll keep looking.

**Comment by heckflosse** [comment]
@Partha1b 

> Well, I am still getting can't start editor and then it starts it.
Remember, I am using my own build and so have to pass a command line to RT.

You forgot to return a value (true/false) in the Win32 part of openInCustomEditor

**Comment by heckflosse** [comment]
@Partha1b [This](https://filebin.net/osjbzasqvc8ld2a2) should work

**Comment by heckflosse** [comment]
@Floessie Could you have a look at the solution one post above? I bet there's a better solution than casting to (uintptr_t)

**Comment by Partha1b** [comment]
Thanks. I'll check it out. Perhaps there is a better solution.

I've never seen gimp-win-remote mentioned before I saw this in RT. So, I
doubt that anyone is using it.

**Comment by heckflosse** [comment]
@Partha1b 

> Could you have a look at the solution one post above?
>> Thanks. I'll check it out. Perhaps there is a better solution.

That question was for @Floessie :)

My point is about checking return code of ShellExecute for being > 32. Anything <= 32 is an error.
The `gimp-win-remote` not found bug is just a side-effect of not checking the return code of ShellExecute correctly.

**Comment by Floessie** [comment]
@heckflosse Well, the doc says it "can be cast only to an int", and I think it is cleanest to follow that rule. As `HINSTANCE` is basically a `void*`, we need the most brutal cast:

    if (reinterpret_cast<int>(success) > 32) {

I hope, that answers your question.

@Partha1b It looks like the indentation got messed up. We use four spaces everywhere.

Best
Flössie

**Comment by Partha1b** [comment]
OK, this one works now.  https://filebin.net/6t14uwk4uxtv1l5i

Should we also have a case for success <= 32?

@heckflossie, I don't know why the indentation is messed up. My np++ is set
to insert 4 spaces for tables.

Thanks,
Partha

**Comment by Floessie** [comment]
@Partha1b Not really an issue, my editors sometimes mess it up, too. Sometimes something happens with the whitespace when pasting. I just wanted to mention, that there is something wrong with the indentation.

:+1: for merging Ingo and me into \@heckflossie at first.:laughing:

**Comment by Partha1b** [comment]
Yeah, Sorry about that. 😋 I hit send before I could correct it and then
went to github to do that.

**Comment by Partha1b** [comment]
Hate to bring this one up again, @Floessie . Any idea what we need to do to get this incorporated into the code? Thanks!

**Comment by Floessie** [comment]
@Partha1b I'm on Linux and cannot test.

@heckflosse How do we proceed with it?

**Comment by heckflosse** [comment]
@Partha1b @Floessie I'll test the patch in the evening

**Comment by Partha1b** [comment]
@heckflosse Was your testing successful?

**Comment by heckflosse** [comment]
@Partha1b Sorry for late answer :( Yes, it was successful. But it should be cleaned a bit (removing commented lines and so on). Shall I do that?

**Comment by Partha1b** [comment]
@heckflosse Thanks! Yes, please clean it as my formatting got messed up last time around.

**Comment by heckflosse** [comment]
@Partha1b Ok, will do that

**Comment by Partha1b** [comment]
@heckflosse  don't mean to be annoying, 🙂 can we close this issue soon? Thanks!

**Comment by heckflosse** [comment]
@Partha1b Sorry, you're right by doing that. Had too much on hold :(
Just cleaned your patch a bit and tested on Win64 (works fine there). Need at least a test on Linux and OSX before I can push it to master.
[Here's the cleaned patch](https://gist.github.com/heckflosse/f4d3fe2bfa384192260c126f106b0c39) (mainly cosmetic changes)

**Comment by Beep6581** [comment]
GCC-4.9.3
```
[ 72%] Building CXX object rtgui/CMakeFiles/rth.dir/previewloader.cc.o
/home/morgan/programs/code-rawtherapee/rtgui/extprog.cc: In static member function ‘static bool ExtProgStore::openInGimp(const Glib::ustring&)’:
/home/morgan/programs/code-rawtherapee/rtgui/extprog.cc:269:9: error: ‘sucess’ was not declared in this scope
     if (sucess) {
         ^
```

**Comment by Partha1b** [comment]
Thanks Ingo for pushing this through. I don't expect this will have any
impact on Linux/OSX.

**Comment by Partha1b** [comment]
Sorry Beep6581, which platform is this? It compiled fine for me on Windows
10 with gcc-6.2.0.

**Comment by Beep6581** [comment]
@Partha1b Sabayon.

**Comment by heckflosse** [comment]
@Partha1b Looks like a typo `sucess` vs. `success`

**Comment by Beep6581** [comment]
Compiled fine when I correct the typo, and "Other command line" and "GIMP" work fine.

**Comment by heckflosse** [comment]
@Beep6581 :+1: for push with the corrected typo

**Comment by Partha1b** [comment]
As Tony the tiger says, "Grrrrrreat!!" :)
