### ISSUE TITLE
Processing stops after process of each image in a certain type of dng files

### ISSUE THREAD

**Issue by meokbodizi** [Beep6581/RawTherapee#3523]
It produces message like

> Invalid byte sequence in conversion input

[https://goo.gl/photos/y4iosK4EhHhFqh4eA](https://goo.gl/photos/y4iosK4EhHhFqh4eA)

These dng files from Microsoft Lumia 950 XL

It does not happen when i handle CR2 raw images from EOS M

Here are sample dng files of Lumia 950 XL
[https://drive.google.com/file/d/0B6Q9Z2vj0OxUbUdBRDJGMmpqTUU/view?usp=sharing](https://drive.google.com/file/d/0B6Q9Z2vj0OxUbUdBRDJGMmpqTUU/view?usp=sharing)
[https://drive.google.com/file/d/0B6Q9Z2vj0OxUWS1WSWNtdjR6dDA/view?usp=sharing](https://drive.google.com/file/d/0B6Q9Z2vj0OxUWS1WSWNtdjR6dDA/view?usp=sharing)
[https://drive.google.com/file/d/0B6Q9Z2vj0OxUV0ZTSTJwYXdsNkk/view?usp=sharing](https://drive.google.com/file/d/0B6Q9Z2vj0OxUV0ZTSTJwYXdsNkk/view?usp=sharing)

I also hope you add dcp profiles of Lumia 950 XL
[https://drive.google.com/file/d/0B6Q9Z2vj0OxUVDM1NGxGaTRtNWM/view?usp=sharing](https://drive.google.com/file/d/0B6Q9Z2vj0OxUVDM1NGxGaTRtNWM/view?usp=sharing)
[https://drive.google.com/file/d/0B6Q9Z2vj0OxUWFNydVNFcXpra1U/view?usp=sharing](https://drive.google.com/file/d/0B6Q9Z2vj0OxUWFNydVNFcXpra1U/view?usp=sharing)
[https://drive.google.com/file/d/0B6Q9Z2vj0OxUYjVwMFVlMGtaTDQ/view?usp=sharing](https://drive.google.com/file/d/0B6Q9Z2vj0OxUYjVwMFVlMGtaTDQ/view?usp=sharing)
[https://drive.google.com/file/d/0B6Q9Z2vj0OxUeHQ4N0oyVktTcVE/view?usp=sharing](https://drive.google.com/file/d/0B6Q9Z2vj0OxUeHQ4N0oyVktTcVE/view?usp=sharing)
[https://drive.google.com/file/d/0B6Q9Z2vj0OxUUk51cHNxWFRBNjg/view?usp=sharing](https://drive.google.com/file/d/0B6Q9Z2vj0OxUUk51cHNxWFRBNjg/view?usp=sharing)
[https://drive.google.com/file/d/0B6Q9Z2vj0OxUYzVhNlBlMTBBUm8/view?usp=sharing](https://drive.google.com/file/d/0B6Q9Z2vj0OxUYzVhNlBlMTBBUm8/view?usp=sharing)

**Comment by Beep6581** [comment]
@meokbodizi all of the links are broken.

Where are the DCP files from? If you made them, please upload photos of the color target instead.

**Comment by meokbodizi** [comment]
@Beep6581 
You can find those dcp files from original post.

[original post](https://drive.google.com/file/d/0B6Q9Z2vj0OxUbUdBRDJGMmpqTUU/view?usp=sharing)
[one drive 1](https://onedrive.live.com/?authkey=%21AGDUe0wNAxN2zvY&id=D115526C14F8B24B%21148&cid=D115526C14F8B24B)
[one drive 2](https://onedrive.live.com/?authkey=%21AHrD40AkNc2Z2Uo&id=72316AA2942F0A8A%21119749&cid=72316AA2942F0A8A)

I fixed links.

**Comment by heckflosse** [comment]
![invalid_byte_sequence](https://cloud.githubusercontent.com/assets/13733487/20927461/0376802c-bbc2-11e6-8c30-69ff86965ffc.png)

**Comment by heckflosse** [comment]
Steps to reproduce:
Create a folder named `资料`
Save a raw file into that folder.
Add file to queue.
Start queue

**Comment by Beep6581** [comment]
@meokbodizi 
1. Where are the DCP files from, did you make them yourself?
2. If you made them yourself, please upload the raw photos of the color target.

**Comment by Beep6581** [comment]
Crash reproduced in Gentoo, same segfault message.

**Comment by heckflosse** [comment]
It's always reproducible when I add 2 images to queue and then start queue

**Comment by heckflosse** [comment]
The exception is from [here](https://github.com/Beep6581/RawTherapee/blob/master/rtgui/batchqueue.cc#L242). But I don't know how to fix it.
@Floessie Do you have an idea?

**Comment by Floessie** [comment]
@heckflosse I only had a quick look, as I've no time ATM. One thing I'd try, was turning the `<<` cascade into distinct calls like `file << x; file << y;` and try again. Could be, there are `std::string`s involved, and they don't mix well with `Glib::ustring`s on `operator <<()`.

**Comment by heckflosse** [comment]
This is a strange issue... 
On my Win7/64 I can reproduce the issue and [this patch](https://filebin.net/fjrv9j8db0ls1s7w) fixes it.
On @Beep6581 Linux it segfaults with and without patch.
On my Linux I can not reproduce it at all. Works fine there with and without patch.

**Comment by meokbodizi** [comment]
@Beep6581 Sorry, the link was wrong address. Here is the [original post](http://forums.windowscentral.com/microsoft-lumia-950-xl/425279-950xl-dual-sim-dng-camera-profile-fix-skintone-sky-issue.html) where these dcp profiles come.
@heckflosse I am using Win7/64bit. Just moved sample files to another path that is full of english and i do not get the same error message. For clearance, I get error message while processing CR2 raw files on the path having korean words.

**Comment by heckflosse** [comment]
@meokbodizi Thanks for testing and confirming that it works fine without 'korean' words. So you have at least a workaround until we fixed this 'korean/chinese/japanese/whatever else' bug :) My patch already fixes that on my windows system, but we have to check other OS too.

**Comment by Floessie** [comment]
@heckflosse Nice patch, but isn't `entry->outFileName` affected as well (though I didn't have a closer look). In @Beep6581's case, is it really a SEGV or an exception like on Windows?

**Comment by heckflosse** [comment]
@Floessie You're right about `entry->outFileName`. In my tests it was always empty but now I found the case when it is not empty.

**Comment by Floessie** [comment]
@heckflosse I was thinking a bit about your patch: Could it be, that you fixed the crash by catching the exception, and wouldn't the following code be sufficient then for `fname_to_utf8()`?

```c++
try {
    return Glib::filename_to_utf8(fname);
} catch (Glib::Error&) {
    return Glib::convert_with_fallback(fname, "UTF-8", "ISO-8859-1", "?");
}
```

**Comment by heckflosse** [comment]
@Floessie I will check that and also post a new patch which also handles `entry->outFileName`

**Comment by Beep6581** [comment]
Is this for inclusion in 5.0?

**Comment by Beep6581** [comment]
@heckflosse @Floessie do we tag this 5.6?

**Comment by heckflosse** [comment]
Isn't that already fixed? At least for Windows:
https://github.com/Beep6581/RawTherapee/blob/dev/rtgui/batchqueue.cc#L263

**Comment by Floessie** [comment]
@Beep6581 I also remember that this was fixed.

**Comment by Beep6581** [comment]
Fantastic.
