### ISSUE TITLE
Gtk+ >=3.20 PartialPaste -> stretching separator

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#3524]
Looks like the middle column has a fixed width and that's why the separator is stretching.

![unbenannt](https://cloud.githubusercontent.com/assets/13800920/20907718/30c8bdaa-bb50-11e6-9919-1bdba58c9f33.png)

**Comment by Hombre57** [comment]
Should be fixed in gtk3-bugfix branch. Closing ?

**Comment by Beep6581** [comment]
Looks fine here using GTK+ 3.22.3 https://i.imgur.com/Gm1Kn0i.png

**Comment by TooWaBoo** [comment]
Can be closed. Looks fine here too.
