### ISSUE TITLE
Improvement Preferences

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#3526]
The "Image Processing" tab waste a lot of space. Here is my suggestion.

![unbenannt3](https://cloud.githubusercontent.com/assets/13800920/20909808/24c810e2-bb5e-11e6-9c80-3d6a83335d44.png)

**Comment by heckflosse** [comment]
@TooWaBoo :+1:
May I suggest an improvement?

![rt_pref_image_processing](https://cloud.githubusercontent.com/assets/13733487/20910160/178f4f92-bb60-11e6-889d-c7b012b3e111.png)

**Comment by Floessie** [comment]
A :+1: to @TooWaBoo from me, too.

@heckflosse Though I like the idea of saving space, moving checkboxes to the right might steal awareness from them. IMHO it's better to have them in just one column.

Just my 2¢
Flössie

**Comment by Hombre57** [comment]
@Beep6581 You assigned yourself to this issue. Are you coding it or should I do ?

**Comment by Hombre57** [comment]
@Beep6581 @heckflosse @TooWaBoo 

Sorry but since this issue is stalled from dec '16, I did it and committed it to dev in commit 3d4ff41. I hope you don't mind.

Close if ok for you.

**Comment by Beep6581** [comment]
What's there to mind ;)
