### ISSUE TITLE
Improvement: Spinner instead of Progressbar

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#3527]
The progressbar tells me only that RT is working. Most of the time it jumps to the middle, stays awhile and it's finished, but it takes a lot of space.
On the internet, I've found a css-Spinner and adaptet it to RT. Here's a screenshot. I've hijacked some buttons. :-)

![unbenannt](https://cloud.githubusercontent.com/assets/13800920/20921651/6ed13b40-bba5-11e6-9e90-7941f1999c56.png)

It's easy to control them via css. You can change the color, size, size of the dots and speed without any external resource. Control from the application can be done by simply assigning and removing classes to/from the spinner object.

Here is a test theme. The yellow spinner disapears when hovering, the red one starts spinning and the green one runs always. You need **Gtk+3.20**. Rename the extension .txt to .css.
[TooWaBlue-Spinner-GTK3-20_.txt](https://github.com/Beep6581/RawTherapee/files/633651/TooWaBlue-Spinner-GTK3-20_.txt)

# What do you think?

**Comment by Beep6581** [comment]
There is a dedicated GTK3 spinner: https://developer.gnome.org/gtk3/unstable/GtkSpinner.html

The decision here is whether the progress bar should get fixed. I would prefer if it did, but issues have been open for years with no progress, so if it won't get fixed, then +1 for spinner, though I think it would be better to use the GTK3 spinner instead of a massive CSS blob.

See #808

**Comment by TooWaBoo** [comment]
Ohps, I forgot the Gtk spinner. If it does the job and looks nice, why not. :-)
Both spinners are save to use. As far as I can see, the css-Spinner has more flexibility.
The one which has the least processor load should be the first choice.

**Comment by TooWaBoo** [comment]
Made some performace tests. The css-Spinner increases pocessing time by around 20% and the CPU load is also 20% higher. That's a lot.
I hope, the Gtk-Spinner is better.

**Comment by heckflosse** [comment]
> Made some performace tests. The css-Spinner increases pocessing time by around 20% and the CPU load is also 20% higher. That's a lot.

Yes, that's too much. I didn't spend weeks and months to speed up rt to get it eaten up by a gui element...
Hopefully the Gtk-Spinner is better.

**Comment by TooWaBoo** [comment]
@heckflosse 
What are 20%, when you can get such a nice spinner. hahahaha

**Comment by RawConvert** [comment]
Better than a hungry spinner, how about simply extending the literals which can appear where "HL Reconstruction" shows, so the user has a feel for what processing is taking place.  E.g. add Noise Reduction, Sharpening, Wavelets and any other big hitters.  I think this is more useful than a spinner.
