### ISSUE TITLE
Issue with noise reduction in editor

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#3528]
Steps to reproduce:

Open a noisy image in editor and apply 'Default ISO Medium' profile.
Zoom to 100 %. Most of chroma noise is removed, good!
Now go to exposure tab and press reset button, most of chroma noise is removed, good!
Now press auto levels button, chroma noise is visible again, bad!
Now zoom out to 50% and again zoom in to 100%, chroma noise is removed.

There's something wrong in editor...

**Comment by meokbodizi** [comment]
@heckflosse 
In my case, good till reset button.
But same issue occur after applying auto level again.
And noise disappears by dragging image with mouse left click on image even without re-zooming.

**Comment by heckflosse** [comment]
@meokbodizi 
I updated my post because you're right that it's good until pressing auto level button.
As it's also good not only be re-zooming but also by dragging it's not a critical issue but still one we should solve.

**Comment by Lawrence37** [comment]
Cannot reproduce in `dev`. Closing this as it's an old issue. Feel free to reopen if the problem still exists.
