### ISSUE TITLE
Remove annoying tooltips

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3537]
Tooltips are good when they tell us things we don't know or may need to be reminded about without having to read a whole document on RawPedia. But they're not good when they get in the way and when they say something of no real value.

There is issue #2221 for a general cleanup, but that turned out to be a lot of work and I never finished the patch. This issue is to quickly clean up the most intrusive ones.

**Comment by TooWaBoo** [comment]
For my own setup, I've add this in the stylesheet of a duplicated theme:

> tooltip {background-color: transparent; border: none;}
> tooltip label {color: transparent;}

This is setting the whole tooltip to transparent and when I need them, I can switch between the two themes.

If you can inject this by the application itself, mybe it's an easy way to do it.

**Comment by Beep6581** [comment]
The `.off` class or an option in Preferences to disable tooltips is a good idea, but remember that some tooltips play more than a didactic role, e.g. the tooltip for Sharpening's threshold adjuster widget shows control point values which cannot be found elsewhere. I think removing unnecessary tooltips in this issue and moving the useful ones off the active widgets in issue 2221 will make finding ways of hiding them less important.

**Comment by heckflosse** [comment]
:+1: to remove annoying tooltips

**Comment by Beep6581** [comment]
Merged.
