### ISSUE TITLE
CbDL no preview when changing exposure

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3539]
Enable CbDL and set high values https://i.imgur.com/T28bI4C.jpg , then change the Exposure slider https://i.imgur.com/GnM1Z8Y.jpg . The CbDL effect is gone from the preview. If you now hop in history back before you enabled CbDL https://i.imgur.com/NA4Ltfj.jpg and forward to the end again, the CbDL effect pops back https://i.imgur.com/1bjjKfS.jpg

**Comment by heckflosse** [comment]
It also pops back if you change zoom ratio or pan.

**Comment by heckflosse** [comment]
Works fine if it CbDL is set to `after Black-and-White'.

I take a look
