### ISSUE TITLE
Lingering artifacts in equalizer graphs

### ISSUE THREAD

**Issue by kulga** [Beep6581/RawTherapee#3541]
I was unable to quickly locate a identical issue.

About:
```
Branch: gtk3
Version: 4.2.1383
Changeset: 5ecd50b1cda1d0ff0f93aee5bddf5ee2197ccffe
Compiler: cc 5.4.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.18.0
Build type: debug
Build flags: -std=c++11 -Wno-deprecated-declarations -Wno-unused-result -std=gnu++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -g
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON
```

System Info (also included graphics since this may be related for this bug)
```
Linux Mint 18 Cinnamon
CPU Quad core Intel Xeon E3-1285L v4 (-HT-MCP-) cache: 6144 KB speed: ~3.2MHz
Ram: 32169MB
Graphics:  Card: NVIDIA GM107 [GeForce GTX 750 Ti]
           Display Server: X.Org 1.18.3 drivers: nvidia (unloaded: fbdev,vesa,nouveau)
           Resolution: 1920x1080@60.00hz
           GLX Renderer: GeForce GTX 750 Ti/PCIe/SSE2 GLX Version: 4.5.0 NVIDIA 367.57
```
Download location: github latest development build
CLI info:
```
TODO: make #tabClose as smalla s possible through css
```
Steps to reproduce: 

* Go to any "Equalizer" graph and move the mouse around, artifacts will linger until RT is completely closed

![](https://i.imgur.com/v6lyDun.gif)

**Comment by Floessie** [comment]
@kulga Current GTK3 development happens on [`gtk3-bugfix`](https://github.com/Beep6581/RawTherapee/tree/gtk3-bugfix). Please try that branch and see, if your problem is already gone.

Best
Flössie

**Comment by kulga** [comment]
@Floessie Apologies, I was not aware of `gtk3-bugfix`
This issue does not occur in that branch.

Thank you!

**Comment by Beep6581** [comment]
@kulga thanks for a great bug report, I wish all were like this ;)

**Comment by Floessie** [comment]
@kulga Thanks for reporting back, and for the impressive report as well! :smiley:
