### ISSUE TITLE
Add on/off for White Balance

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3542]
Feature request to add support for turning the White Balance tool on/off, for after RT5.0.

- Off would mean that the white balance multipliers are set to 1 1 1.
- WB picker should be disabled when turning WB off.
- Bump PP3 version.
- If PP3 version lower than x, assume WB is on.

Let me know if you have any thoughts or suggestions.

**Comment by heckflosse** [comment]
> WB picker should be disabled when turning WB off.

WB picker should enable WB when WB is picked and WB is off.
That would be consistent with the behaviour of the crop tool

**Comment by Floessie** [comment]
@Beep6581 Maybe a bit off-topic: Is there any plan for having an "Invert" button early in the pipeline, so that one could deal a bit better with negatives?

**Comment by Beep6581** [comment]
@Floessie there was some talk and WIP, nothing came of it.
I documented the options here:
http://rawpedia.rawtherapee.com/Negative

**Comment by agriggio** [comment]
Started working on this. See the `colortab-tools-onoff` branch. Could someone please test and tell me if this is what you wanted?
**Note**: as agreed on IRC in this branch I'll also add on/off buttons for the other tools in the color tab that do not have them (except for output color profile, for which it doesn't make sense)

**Comment by agriggio** [comment]
added also for the other tools now. If somebody can test, maybe we can merge this before 5.4?

**Comment by Beep6581** [comment]
Good!

No problems found with raw files.

Not sure what happens under the hood when WB is disabled for non-raw files. I would imagine they should stay the same, because WB off = multipliers = 1 = colors as-are?
https://i.imgur.com/W9YyeJn.png

**Comment by agriggio** [comment]
> Not sure what happens under the hood when WB is disabled for non-raw files. I would imagine they should stay the same, because WB off = multipliers = 1 = colors as-are?

@Beep6581 I agree. I'll fix that.

BTW, should I also add an on/off switch for Exposure and L\*a\*b\* adjustments?

**Comment by agriggio** [comment]
> I'll fix that.

Done

**Comment by Beep6581** [comment]
@agriggio I know users would like that, and I would personally like that too!

**Comment by Hombre57** [comment]
@Floessie 
> Maybe a bit off-topic: Is there any plan for having an "Invert" button early in the pipeline, so that one could deal a bit better with negatives?

Wouldn't a checkbox "Image is a Negative" in the WB tool be simpler ? It would let `RawImageSource` and `StdImageSource` update the values before computing the WB ?

**Comment by Hombre57** [comment]
@Floessie ...later on another chekbox could tell if image is an infrared capture. Don't know what to do with this information though.

**Comment by Beep6581** [comment]
Reopened as it needs to be documented.

**Comment by Beep6581** [comment]
Documented.
