### ISSUE TITLE
Locallab branch - add local CBDL and others improvments

### ISSUE THREAD

**Issue by Desmis** [Beep6581/RawTherapee#3546]
I just push a change to locallab branch

I add, "Contrast By Details Levels" to Locallab.
I also modified some default values

You must delete *.mip files

Jacques
:)

**Comment by Desmis** [comment]
I push another change, concerning Blur and Noise.
I have add "scope" in order to better delimited action, I add also "luminance only".

I realized some optimizations to reduce processing time and memory.

You must delete *.mip files

I have not planned any further changes (except bug).
I realized a help in Rawpedia (in [French)](http://50.87.144.65/~rt/w/index.php?title=Local_Lab_controls/fr)

:)

**Comment by Desmis** [comment]
I add local Tone-Mapping, in a new change!

Now there is no need to delete * .mip files

    If the update is made from files generated by the version c65ba61, all settings are maintained.

    If the update is made from files generated before the version c65ba61, settings are not maintained, but no crash.

I will be absent from tomorrow evening, until early January

Happy holidays to everyone :slight_smile:

**Comment by Beep6581** [comment]
Happy holidays @Desmis !

**Comment by Desmis** [comment]
@Beep6581 

Thank you :)

**Comment by Desmis** [comment]
2 new changes 
1) add Button reset for current control point
2) Fixed crash for "inverse" - Blur and Sharpening
:)

**Comment by Desmis** [comment]
I add "curves" to locallab.
Currently this only applies to the Retinex curve, which was previously global.

The system is a bit complex, but it works and moreover I think (except may be for the new module "curve" ... to check) that the set is more robust.

I'll explain in Rawpedia (when I could access the login again. Because now I can no longer access (except in read mode : I write to Pat David !).

Probably, I'll add a curve type  L=f(L), in the next days :)

**Comment by Desmis** [comment]
I have update Rawpedia (in french)
http://rawpedia.rawtherapee.com/Local_Lab_controls/fr

**Comment by Desmis** [comment]
I push a change.
I update GUI with expanders !

**Comment by Desmis** [comment]
I push a change with a new curve C=f(C) in branch locallabgtk3
No problem ! I have merge  locallab to gtk3 on january 21 jan.

@Beep6581 
Now I want to merge with branch gtk3 and Git said me 
Nikon 750.dcp is suppressed in gtk3 and modified in HEAD (traduction from french)
(I had not this message 2 days ago)

What must I do ? which command ?
Thank you !

**Comment by Beep6581** [comment]
@Desmis I'm in a meeting right now, I will get back to you in an hour!

**Comment by Beep6581** [comment]
See https://github.com/Beep6581/RawTherapee/issues/3615#issuecomment-273916382

The file `rtdata/dcpprofiles/Nikon D750.dcp` was deleted, there is a new file `rtdata/dcpprofiles/NIKON D750.dcp` (notice the capitalized name). If you are merging `gtk3` into `locallabgtk3` you can safely delete the not-capitalized one, so to fix the problem:
`git rm "rtdata/dcpprofiles/Nikon D750.dcp"`
Then finish the merge:
`git commit`

If you like I can do it for you.

Now I want to touch on something unrelated, possibly a problem:
> I push a change with a new curve C=f(C) in branch locallabgtk3

Why add a new feature to the gtk3 branch but not to the gtk2 branch? Currently `master` is still our main branch, so all new features should go into `master` (in your case `locallab`) and the only thing which should go into `gtk3` (in your case `locallabgtk3`) are merges with master and gtk3-related fixes, otherwise we could end up with a mess.

**Comment by Desmis** [comment]
@Beep6581 
1 - git rm "rtdata/dcpprofiles/Nikon D750.dcp"
2 - commit
And system is bizarre he ask me with a geeen script "veuillez saisir le massage de validation pour vos modifications..."
What must I do

3. I think, but excuse my very bad comprehension of english that gtk3 wil be the futur master branch
And now i will go backward !

**Comment by Desmis** [comment]
Now my system is hang !

**Comment by Desmis** [comment]
Here the message, what must I do, for me  It's all but clear :)

jacques@pc-bureau MINGW64 ~
$ cd /g/code/rt3gtk3

jacques@pc-bureau MINGW64 /g/code/rt3gtk3
$ git status
Sur la branche locallabgtk3
Votre branche est à jour avec 'origin/locallabgtk3'.
Modifications qui seront validées :
  (utilisez "git reset HEAD <fichier>..." pour désindexer)

        supprimé :        rtdata/dcpprofiles/Nikon D750.dcp

Modifications qui ne seront pas validées :
  (utilisez "git add/rm <fichier>..." pour mettre à jour ce qui sera validé)
  (utilisez "git checkout -- <fichier>..." pour annuler les modifications dans la copie de travail)

        supprimé :        rtdata/dcpprofiles/NIKON D750.dcp

**Comment by Desmis** [comment]
@Beep6581 
After manipulations a little random, I managed to commit and push !
Now how can I go backwarg without errors ?

**Comment by Desmis** [comment]
All in manual !

**Comment by Beep6581** [comment]
@Desmis hey,
> Now how can I go backwarg without errors ?

What do you mean by backwards?

> All in manual !

Does that mean everything is now ok?

**Comment by Desmis** [comment]
All is ok.
But rt objectives are now dark for me.
I thought since many mounths that the objectif was gtk3 ?? !!
Jacques


Envoyé depuis un mobile Samsung

-------- Message d'origine --------
De : Beep6581 <notifications@github.com> 
Date : 23/01/2017  20:46  (GMT+01:00) 
A : Beep6581/RawTherapee <RawTherapee@noreply.github.com> 
Cc : Desmis <jdesmis@gmail.com>,Mention <mention@noreply.github.com> 
Objet : Re: [Beep6581/RawTherapee] Locallab branch - add local CBDL and others improvments (#3546) 
 
@Desmis hey,

Now how can I go backwarg without errors ?

What do you mean by backwards?

All in manual !

Does that mean everything is now ok?

**Comment by Beep6581** [comment]
@Desmis I bumped https://github.com/Beep6581/RawTherapee/issues/3184#issuecomment-274614943

**Comment by Beep6581** [comment]
I will close this now as most of the discussion has happened in the forum https://discuss.pixls.us/t/local-lab-build/1430

All locallab issues:
#3546
#3421
#3351 
#3292 
#2538

Merged into #3421
