### ISSUE TITLE
Add space between toolpanel and vertical scrollbar

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3548]
For #3300 RT5

There is no gap between the toolpanel and the vertical scrollbar which appears when needed. That means when I try to click on the reset icon the vertical scrollbar suddenly appears over it and I can't. We need to add a gap in the default theme.

**Comment by Beep6581** [comment]
One solution is to add a gap between the MyExpander and the right edge https://i.imgur.com/aMwlMa3.jpg
```
#MyExpander {
	margin-right: 8px;
}
```

Another solution is to add a gap inside the tool frame https://i.imgur.com/HDTkFHN.jpg
```
#ExpanderBox box {
	padding-right: 8px;
}
```

**Comment by Hombre57** [comment]
This should be added when the vertical scrollbar is shown only, so we have to set that in another class.
