### ISSUE TITLE
Update: TooWaBlue v2.22 / Gtk+ 3.20

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#3551]
Requires RT version 4.2.1445 or higher
Change .txt to .css
[TooWaBlue-GTK3-20_.txt](https://github.com/Beep6581/RawTherapee/files/667936/TooWaBlue-GTK3-20_.txt)
[TooWaBlue-Dark-GTK3-20_.txt](https://github.com/Beep6581/RawTherapee/files/667937/TooWaBlue-Dark-GTK3-20_.txt)

**Comment by TooWaBoo** [comment]
Replaced version 2.20 with 2.21
Realized, that hidding titlebar in fullscreen is already done by the window itselfs.

**Comment by Beep6581** [comment]
Both themes look good and no errors.

Line 1607 has:
```css
headerbar label {
(...)
    font-size: 12px;
```

As discussed before, you can prevent breaking things for users by using `%` or `em` instead of `px`.

**Comment by TooWaBoo** [comment]
Checked the file I've uploaded and local and and did'nt found a font style.

**Comment by TooWaBoo** [comment]
You've checked the old theme file in the Gtk3 bugfix branche. The update is free of any font styles.

**Comment by Beep6581** [comment]
Confirmed, nothing in 2.21. 

I'm using GTK+ 3.22.3:
```
(rawtherapee:29629): Gtk-WARNING **: Theme parsing error: TooWaBlue-GTK3-20_.css:1097:15: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'

(rawtherapee:29629): Gtk-WARNING **: Theme parsing error: TooWaBlue-GTK3-20_.css:1106:15: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'

(rawtherapee:29629): Gtk-WARNING **: Theme parsing error: TooWaBlue-GTK3-20_.css:1570:15: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'

(rawtherapee:29629): Gtk-WARNING **: Theme parsing error: TooWaBlue-Dark-GTK3-20_.css:1097:15: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'

(rawtherapee:29629): Gtk-WARNING **: Theme parsing error: TooWaBlue-Dark-GTK3-20_.css:1106:15: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'

(rawtherapee:29629): Gtk-WARNING **: Theme parsing error: TooWaBlue-Dark-GTK3-20_.css:1570:15: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'

```

**Comment by TooWaBoo** [comment]
Looks like **icon-shadow** is not compatible with Gtk. Changing this next time into **-gtk-icon-shadow**.

**Comment by TooWaBoo** [comment]
All changes are done, Should be load without warnings.
Replaced  files with version 2.22

**Comment by Beep6581** [comment]
Confirmed, and pushed.

I included some whitespace and line ending fixes for consistency, please download the files from the repo before working further on them:
https://github.com/Beep6581/RawTherapee/blob/gtk3-bugfix/rtdata/themes/TooWaBlue-GTK3-20_.css
https://github.com/Beep6581/RawTherapee/blob/gtk3-bugfix/rtdata/themes/TooWaBlue-Dark-GTK3-20_.css
Click on "raw".

Speaking of line endings, both files use CRLF while the rest of RawTherapee's codebase uses LF (with the exception of Windows-only files like `clean.bat`). It's a 1 second fix, I can do it if anyone wants.
