### ISSUE TITLE
gtk3-bugfix - double-click does not reveal subfolders

### ISSUE THREAD

**Issue by Partha1b** [Beep6581/RawTherapee#3552]
@Hombre57, @Beep6581 
I cannot drill down into subfolders anymore. If I have Folder/subfolder1/subfolder2, I can only see Folder and then have to restart the App to see subfolder1 and restart to see subfolder2 etc.

I noticed that in gtk2 version, a down arrow needed to be clicked to reveal subfolders. I clicked just to the left of a folder and it did reveal the subfolders.  So, need a ">" or similar icon as gtk2.

**Comment by Beep6581** [comment]
@Partha1b this is what the file browser should look like in `gtk3-bugfix`:
![imgur-2016_12_21-17 49 57](https://cloud.githubusercontent.com/assets/5844619/21397954/f5225128-c7a5-11e6-9bcd-affe452bf8be.png)

If you don't see those arrows, maybe you're missing the icon? What did the bisect reveal?

Please paste your AboutThisBuild.txt

**Comment by gaaned92** [comment]
Windows10 comparison of master branch 4.2.1203 and gtk-bugfix 4.2.1445
I get exactly the same behavior .
 The "left arrow" is apparent on the two builds and permits to unfold the subfolders(it becomes then a down arrow). So you are surely missing the icon.
 in GTK2  Aspect changes when you pass over it (from empty to full). 

In GTK2 and GTK3, double clicking on subfolder permits to display the photos in the file browser window.

**Comment by Beep6581** [comment]
Related: https://github.com/Beep6581/RawTherapee/issues/2661

**Comment by Partha1b** [comment]
@Beep6581 Yes, the icons are missing. I also get this at startup:

```
(rawtherapee:30962): Gtk-WARNING **: Could not find the icon 'user-home-symbolic-ltr'. The 'hicolor' theme
was not found either, perhaps you need to install it.
You can get a copy from:
        http://icon-theme.freedesktop.org/releases
```
which does not make sense to me. 

Here is my AboutThisBuild.txt:
```
Branch: gtk3-bugfix
Version: 4.2.1445
Changeset: c6c5610333b9fbbda32fd46932fa8cdb3813532e
Compiler: cc 8.0.0.8000042
Processor: generic x86
System: Apple
Bit depth: 64 bits
Gtkmm: V3.20.1
Build type: RelWithDebInfo
Build flags: -stdlib=libc++ -std=c++14 -O3 -mmacosx-version-min=10.9 -std=gnu++11 -mtune=generic -Werror=unused-label -O2 -g -DNDEBUG
Link flags: -headerpad_max_install_names -mtune=generic
OpenMP support: ON
MMAP support: ON
```

**Comment by Partha1b** [comment]
@gaaned92 On the Mac, I don't get a good file-browser or thumbnail window with the gtk3 build as I do using the gtk2 build.

**Comment by gaaned92** [comment]
@Partha1b  I think you did not copy the /share subdir. The share.zip is uploaded  in [my W64 RT drive](https://drive.google.com/open?id=0B2q9OrgyDEfPS2FpdDAtMVI1RG8)
Copy the /share subfolder in the installed build. hope this solve the issue.
I am now generally pleased with the gtk3 GUI which is very close to gtk2 GUI. An inconvenience remains as you cannot reduce width of left and right panel in editor window.
Great job from Hombre and also Toowaboo.

**Comment by Partha1b** [comment]
@gaaned92 No, that's not it. Of course I have the share folder.

**Comment by Beep6581** [comment]
@Partha1b a screenshot would be helpful.

**Comment by gaaned92** [comment]
@Partha1b :  
If I suppress adwaita and hicolor iconsets I get the same messages as above and the arrow left to dir name disappears.
So, I really think you miss adwaita and hicolor. You should also have other anomalies due to missing icones (as -/+ at the right of sliders..) inside GUI.

Structure of /share inside gtk3 builds

```
 share   ---/glib2/schemas/gschemas.compiled
         ---/icons  ---/adwaita  
                    ---/hicolor                       
```    
Only a few icon sizes are usefull.

**Comment by Partha1b** [comment]
@Beep6581 , Here is the screenshot that I think you are asking for?
![image](https://cloud.githubusercontent.com/assets/16463793/21409461/60dea70c-c7a8-11e6-9c7b-10d6294ee698.png)

@gaaned92 
Mac Apps work a little differently from Windows. 

Is rawtherapee looking for adwaita and hicolor icon sets from gnome-themes-standard-3.22.2?

**Comment by Beep6581** [comment]
This is 99% a packaging issue, not a RawTherapee issue. The screenshot shows that you are missing non-RT icons:
- `list-add-symbolic.symbolic.png`
- `list-remove-symbolic.symbolic.png`
- `pan-down-symbolic.symbolic.png`
- `pan-end-symbolic.symbolic.png` or `pan-start-symbolic-rtl.symbolic.png`
- Possibly others

My folder structure, to give you a hint:
```
/usr/share/glib-2.0/schemas/gschemas.compiled
/usr/share/icons/Adwaita/16x16/actions/
/usr/share/icons/Adwaita/32x32/actions/
(...)
```
But of course you must set somewhere that Adwaita is to be used. @gaaned92 you mentioned not long ago which file it is which sets the theme, I even replied, could you remind me where that was?

I don't think you need to bundle "hicolor", that is only a fallback theme if your main theme is missing icons. Are we using any icons missing from Adwaita?

**Comment by Partha1b** [comment]
@Beep6581 Yes, I know it's a packaging issue. :) 

Since Mac apps are userland apps, the schemas and icons etc. are packaged with the app. I am now studying the code to see how "Adwaita" is called within RT.

**Comment by gaaned92** [comment]
@Beep6581 yes hicolor seems not to be needed as there is no icon inside it (for my builds) .
 I don't remember to have mentioned the name of file where adwaita is set. Surely @Hombre57 knows that.

**Comment by Beep6581** [comment]
Found it: /etc/gtk-3.0/settings.ini
```
[Settings]
gtk-theme-name = Adwaita
gtk-icon-theme-name = Adwaita
gtk-cursor-theme-name = Adwaita
```

**Comment by gaaned92** [comment]
On my system in C:\Users\Andre\AppData\Local\settings.ini
```
[Settings]
gtk-theme-name = Adwaita
gtk-icon-theme-name = gnome
gtk-cursor-theme-name = Adwaita
```
But... how and when this file is installed? When I suppress it, it doesn't seem to change anything in RT. gtk3-bugfix

**Comment by Partha1b** [comment]
It's not needed in general. If you wish to change your iconset from the
default "Adwaita" (which is the gtk default) you can use the settings.ini
file to specify your theme/iconset/fonts.

**Comment by Partha1b** [comment]
OK, I think I have figured this out. I have set XDG_DATA_HOME and all is well. Well mostly. 
![image](https://cloud.githubusercontent.com/assets/16463793/21435421/d2b39faa-c847-11e6-8dba-cf58e1b1d00a.png)
Couple of issues with what you see on the screen but not a deal breaker. Also, one icon I am missing is called missing-image.

**Comment by Beep6581** [comment]
@Partha1b @Benitoite can we close this?

**Comment by Beep6581** [comment]
Issue was resolved, closing.
