### ISSUE TITLE
Suggestion for IPTC panel

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#3554]
Solves the min. width issue of the entry field and no need to resize the panel.

![unbenannt](https://cloud.githubusercontent.com/assets/13800920/21445927/3e3dbd3c-c8c0-11e6-8fd9-2f1503216a9a.png)

**Comment by Hombre57** [comment]
@TooWaBoo @Beep6581 I'd like to merge asap (as well as printer-profile branch which is complete) to merge into gtk3.

**Comment by Beep6581** [comment]
Tested, looks good! Fine with me to merge.

**Comment by TooWaBoo** [comment]
This can be closed
