### ISSUE TITLE
Ubuntu 16:10 internal compiler error compiling rawtherapee gtk branch Version: 4.2.1443

### ISSUE THREAD

**Issue by dnw3039** [Beep6581/RawTherapee#3557]
I am using Ubuntu 16:10. I got a internal compiler error compiling the gtk branch.  Version: 4.2.1443

/usr/lib/gcc/x86_64-linux-gnu/6/include/smmintrin.h:102:3: internal compiler error: Segmentation fault
   return (__m128d) __builtin_ia32_roundpd ((__v2df)__V, __M);
   ^~~~~~

I resolved the problem by upgrading GCC using this advice: **application2000/how-to-install-latest-gcc-on-ubuntu-lts.txt** https://gist.github.com/application2000/73fd6f4bf1be6600a2cf9f56315a2d91

I thought I should log this as others might have the problem. This is similar to **Build failure on Fedora 24** issue:https://github.com/Beep6581/RawTherapee/issues/3359

**Comment by Beep6581** [comment]
@dnw3039 which version of GCC did this happen with, which branch did you try to compile (there is no "gtk" branch) and which commit?

**Comment by dnw3039** [comment]
I used the gtk3 branch. I do not have a record but I think it was the commit was 88c2520380c5e58ef713c76d342c266f7565a5fc . The compiler was the standard for Ubuntu 16:10, which I believe is gcc-4:6.1.1. It is now gcc-6 6.2.0.
