### ISSUE TITLE
RawTherapee crashed after opening linear DNG from Sigma SD H Quattro camera in editor

### ISSUE THREAD

**Issue by diethardsteiner** [Beep6581/RawTherapee#3559]
version: 4.2.1234-2.20161105gitb766110.fc25
The particular linear DNG I tried to open in RawTherapee was taken by the Sigma SD H Quattro camera and can be downloaded from [here](https://www.dropbox.com/s/ho8ddpsacavxa93/SDQH1383.DNG?dl=0).
In RawTherapee I can see the thumbnail pic in the browser, but once double clicking on it, RawTherapee crashes. Please fix. The same picture can be opened with UFRaw without problems.

**Comment by heckflosse** [comment]
Crash confirmed.

**Comment by heckflosse** [comment]
@diethardsteiner Though ufraw opened the file without crash, it did not open it correctly. Here's what I get using ufraw:
![sigmadng_ufraw](https://cloud.githubusercontent.com/assets/13733487/21567302/8a4b9ca8-ceab-11e6-8c18-c8d88b0752f1.png)

using dcraw.exe to convert to tiff:
![sigmadng_dcraw](https://cloud.githubusercontent.com/assets/13733487/21567318/a4740ed0-ceab-11e6-815a-b0d227835472.png)


and after patch using rt:
![sigmadng_rt](https://cloud.githubusercontent.com/assets/13733487/21567335/c3234e40-ceab-11e6-8bfa-bff15bb2ea6f.png)

**Comment by iliasg** [comment]
@heckflosse Ingo, fine !!

BTW dcraw by default auto scales raws .. if we want to disable Dcraw's auto scaling to take comparable with RT's  neutral we have to use the -W (capital W) switch.

**Comment by heckflosse** [comment]
@iliasg Yes, I know. I was referring to the wrong crop by showing the screen shots. But I still think there is something wrong with this sigma dng file...
@Floessie Could you have a look at the rtthumbnail.cc part of my patch please? Though I managed to avoid the crash when building the thumb, I didn't manage to show the correct crop in thumb and gave up after some tries. Maybe you have an idea.

**Comment by diethardsteiner** [comment]
Excellent, thanks a lot! I'll test over the weekend.

**Comment by diethardsteiner** [comment]
For the very first time I tried to compile RawTherapee on the latest Fedora version. I did follow the instructions on the wiki:

[Docu](http://rawpedia.rawtherapee.com/Linux#Fedora)

Install dependencies:

```
sudo dnf install bzip2-devel cmake exiv2-devel expat-devel fftw-devel gcc-c++ glib2-devel glibmm24-devel gtk3-devel gtkmm30-devel lcms2-devel libcanberra-devel libiptcdata-devel libjpeg-turbo-devel libpng-devel libsigc++20-devel libtiff-devel zlib-devel
```

How many threads does your CPU support:

```
grep -c processor /proc/cpuinfo
```

Then replace the number in "-j8" below with this number.

```
git clone https://github.com/Beep6581/RawTherapee 
cd RawTherapee
rm -rf build; make clean; ./clean
mkdir build && cd build
cmake -DCMAKE_CXX_FLAGS="-std=c++11 -Wno-deprecated-declarations -Wno-unused-result" \
      -DWITH_LTO="OFF" \
      -DCMAKE_BUILD_TYPE="release" \
      -DPROC_TARGET_NUMBER="2" \
      -DBUILD_BUNDLE="ON" \
      -DBINDIR="." \
      -DDATADIR="." \
      -DCACHE_NAME_SUFFIX="4" ..
```

Here I get following error:

```
-- Checking for module 'glibmm-2.4>=2.16'
--   Found glibmm-2.4, version 2.50.0
-- Checking for module 'gtkmm-2.4>=2.22'
--   
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:424 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPkgConfig.cmake:597 (_pkg_check_modules_internal)
  CMakeLists.txt:232 (pkg_check_modules)
```

The` gtkmm30-devel.x86_64` package is installed though on my system. Do you have any ideas why it is failing?

**Comment by heckflosse** [comment]
@diethardsteiner You tried to build master branch using the dependencies for gtk3 branch. master branch needs gtk2. Unfortunately I can not tell you the dependencies for master branch on Fedora :(

**Comment by diethardsteiner** [comment]
Excellent, thanks a lot, this worked! But RawTherapee is still crashing ... is this because the bug fix is only available in the master but not the gtk3 branch?

**Comment by heckflosse** [comment]
@diethardsteiner 

> is this because the bug fix is only available in the master but not the gtk3 branch?

exactly. I guess it will be available in gtk3 branch soon but I don't know when.

**Comment by diethardsteiner** [comment]
@heckflosse Thanks a lot for letting me know! I'll recompile once the gtk3 branch has the bug fixes in.

**Comment by Beep6581** [comment]
@diethardsteiner the `gtk3` branch now has the fix!

**Comment by diethardsteiner** [comment]
@Beep6581 Awesome, thanks a lot!

**Comment by diethardsteiner** [comment]
Works excellently! I had to set the processing profile to neutral, otherwise the pics looked overexposed. Since I haven't used RawTherapee before, I will familiarise myself with the program a bit more over the coming weeks and then provide more feedback if required. So far my impressions are very good! Thanks a lot for all your hard work.

**Comment by diethardsteiner** [comment]
I did a comparison between what I see in UFRaw and RawTherapee: The picture in RawTherapee looks less sharp when viewed at 100%. Is this related to the auto-scaling problem you mentioned further up?

**Comment by Beep6581** [comment]
@diethardsteiner these are a good starting point:
http://rawpedia.rawtherapee.com/The_Image_Editor_Tab#Eek.21_My_Raw_Photo_Looks_Different_than_the_Camera_JPEG
http://rawpedia.rawtherapee.com/Getting_Started

**Comment by diethardsteiner** [comment]
Ok, thanks, I'll read through it.

**Comment by heckflosse** [comment]
@diethardsteiner 

> Is this related to the auto-scaling problem you mentioned further up?

No, the scaling referred to exposure, not to sharpening

**Comment by diethardsteiner** [comment]
So I read through the article. I guess the main message you wanted to highlight is that raw converters do apply some settings automatically. I've only started using using UFRaw as well as RawTherapee, so I can only share my simple observations here. I am not trying to say that the way UFRaw displays the linear DNG is correct. It seems to be in line with what I can see in Capture One from a sharpness level at 100%. 

Two more observations: 

- If I take a look at the picture in UFRaw at 100% and try to get everything in RawTherapee to roughly the same size/proportions, I end up with a 50% zoom level in RawTherapee.
- UFRaw shows an image size of 6216x4168, whereas RawTherapee shows an image size of 5988x4004.

**Comment by heckflosse** [comment]
@diethardsteiner 
> UFRaw shows an image size of 6216x4168, whereas RawTherapee shows an image size of 5988x4004
UFRaw has the borders top and left

**Comment by diethardsteiner** [comment]
@heckflosse: Ok, I see what you mean, I didn't imagine that they would include this in the image size. 
Regarding the first point I mentioned: What about the difference in zoom level? Can you please explain this?

**Comment by heckflosse** [comment]
@diethardsteiner No, I can not explain that because it looks same in ufraw and rt at 100% zoom here:

![ufraw100](https://cloud.githubusercontent.com/assets/13733487/21581331/7496cc3c-d02e-11e6-9cdc-e05ce1517f97.png)
![rt100](https://cloud.githubusercontent.com/assets/13733487/21581333/8bf5f1d2-d02e-11e6-8c27-cccf04067fb2.png)

**Comment by diethardsteiner** [comment]
@heckflosse: Thanks! Here is a screenshot from my laptop: I have a Dell XPS with a 13.3” QHD+ (3200 x 1800) display.
![screenshot from 2017-01-01 13-33-35](https://cloud.githubusercontent.com/assets/1726057/21581357/48252fb0-d027-11e6-8968-1edc6f4ea263.png)

**Comment by heckflosse** [comment]
@diethardsteiner Can you please show a screen shot from rt at 100% view using [this file](http://www.rawtherapee.com/shared/test_images/amsterdam.pef)?

**Comment by diethardsteiner** [comment]
@heckflosse Here you go:
![screenshot from 2017-01-01 14-05-45](https://cloud.githubusercontent.com/assets/1726057/21581494/a1656e7e-d02b-11e6-9ca8-0d94a9a7db42.png)
![screenshot from 2017-01-01 14-06-12](https://cloud.githubusercontent.com/assets/1726057/21581495/a16b6766-d02b-11e6-937e-5b48f51cfe06.png)
![screenshot from 2017-01-01 14-06-42](https://cloud.githubusercontent.com/assets/1726057/21581496/a16c4e10-d02b-11e6-900c-bb6fba73ad10.png)

**Comment by heckflosse** [comment]
@diethardsteiner Thanks, looks like rt is upscaled on your display while ufraw is not. That's the reason it looks less sharp in rt. But I have no clue why rt is upscaled or why ufraw is not upscaled.

**Comment by diethardsteiner** [comment]
@heckflosse ok, thanks for letting me know. I'll try to find out.

**Comment by Beep6581** [comment]
What I think is happening is that RawTherapee does not support HiDPI mode yet, it does not declare itself as HiDPI-capable, so the operating system scales everything - icons, text and preview. Perhaps UFRaw does, and so only the icons and text are scaled, while the preview is rendered 1:1. #3547

**Comment by diethardsteiner** [comment]
@Beep6581: Thanks for letting me know. After some searching my conclusion was that this is app dependent. Then I also found the issue you mentioned. I do really hope support for HiDPI displays is coming soon as I am seriously considering using RawTherapee as my main raw converter. But this issue is a major blocker.

**Comment by Beep6581** [comment]
@diethardsteiner then start RawTherapee like this:
`GDK_SCALE=1 GDK_DPI_SCALE=2 ./rawtherapee`
or to disable scaling entirely:
`GDK_SCALE=1 GDK_DPI_SCALE=1 ./rawtherapee`

**Comment by diethardsteiner** [comment]
@Beep6581 Thanks for pointing this out. This influences everything apart from the picture scaling. Icons, menu, etc are all actually fine (ok, thumbnails are half of the size, but I can live with that). However, the picture at 100% is still scaled. This is the most problematic issue.

**Comment by Beep6581** [comment]
Please show three full-screen screenshots, running RawTherapee using each of the modes above.

**Comment by diethardsteiner** [comment]
default:
![screenshot from 2017-01-01 17-11-46 - default](https://cloud.githubusercontent.com/assets/1726057/21582181/b7f20eb2-d045-11e6-80c8-b9c642f887e1.png)

`GDK_SCALE=1 GDK_DPI_SCALE=2 ./rawtherapee`

![screenshot from 2017-01-01 17-12-34 - gdk_scale-1-gdk_dpi_scale-2](https://cloud.githubusercontent.com/assets/1726057/21582182/c2d62c0a-d045-11e6-9b98-eb120ab52587.png)

`GDK_SCALE=1 GDK_DPI_SCALE=1 ./rawtherapee`: This seems to be exactly the same as the default settings.
![screenshot from 2017-01-01 17-13-21 - gdk_scale-1-gdk_dpi_scale-1](https://cloud.githubusercontent.com/assets/1726057/21582183/d2da347a-d045-11e6-9867-23b8c3618010.png)
