### ISSUE TITLE
TooWaBlue 2.26 update Gtk+3

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#3562]
[TooWaBlue-GTK3-20_.txt](https://github.com/Beep6581/RawTherapee/files/677810/TooWaBlue-GTK3-20_.txt)
[TooWaBlue-Dark-GTK3-20_.txt](https://github.com/Beep6581/RawTherapee/files/677812/TooWaBlue-Dark-GTK3-20_.txt)

**Comment by Beep6581** [comment]
@TooWaBoo I'd like to convert CRLF to LF to conform with the rest of the code, OK with you?

**Comment by TooWaBoo** [comment]
Shure, thanks

**Comment by Beep6581** [comment]
Done, please download those file from git before making new edits.
