### ISSUE TITLE
Copy metadata to saved reference image for profiling

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3567]
Would be nice downstream if RT copied metadata to the saved image when using "Save reference image for profiling". Currently metadata is stripped.

**Comment by Hombre57** [comment]
@Beep6581 Done in commit 91e494a7098e760d2422003011e8311d7032bba5, in Tunneling mode. Could we close ?

**Comment by agriggio** [comment]
:+1: for closing, thanks!

**Comment by Beep6581** [comment]
Fix confirmed, thanks @Hombre57
