### ISSUE TITLE
RAW image is distorting with negative colors

### ISSUE THREAD

**Issue by itzsomnath** [Beep6581/RawTherapee#3568]
Hi, Once opening a RAW file (taken in Canon 80D) in RawTherapee_WinVista_64_4.2.1 version. the image is distorting with negative colors.  Please check the screenshot and check the google drive link for the original image.  

https://drive.google.com/file/d/0B3oKYtuzoNVWTzJDX3NkNWs0Yms/view?usp=sharing

My system configuration is as follow.
Windows 10 Pro 64 bit.
Intel Core i7- 6650 U CPU @2.20 GHz, 16GB RAM, Intel Iris graphics 540

![issue_rawtherapy](https://cloud.githubusercontent.com/assets/8308302/21577552/d1664bf2-cf2c-11e6-98ce-cd71149a8fef.JPG)

**Comment by iliasg** [comment]
4.2.1 is ancient ..
Try the latest .. https://discuss.pixls.us/t/download-rawtherapee-builds-windows-macos-linux-appimage-other/2924

**Comment by itzsomnath** [comment]
It has multiple zip files to download. few are debug versions. Which one is usable and stable copy?

**Comment by heckflosse** [comment]
@itzsomnath I would go for release_gtk3 or release_master

**Comment by Beep6581** [comment]
Canon EOS 80D works fine in the latest RT https://i.imgur.com/T3Cowcu.jpg

**Comment by itzsomnath** [comment]
@Beep6581  which version are you referring ? can you please provide the download link?
I need for windows 10.

**Comment by heckflosse** [comment]
@itzsomnath [here you go](https://discuss.pixls.us/t/download-rawtherapee-builds-windows-macos-linux-appimage-other/2924). Download the release_gtk3 or release_master build

**Comment by itzsomnath** [comment]
Appreciate your help. I installed 'RawTherapee_WinVista_64_release_gtk3_4.2.1464'. Now color issue is fine. But for RAW images  'auto level' is making the image fade/dull. Earlier 'auto level' used to improve the image quickly at a shot. currently Its making the image fade/dull. 

I found 'auto level' is working fine for JPG image but not for RAW

**Comment by heckflosse** [comment]
@itzsomnath Please upload an example raw file to filebin.net and post the link here.

**Comment by itzsomnath** [comment]
filebin.net is restricted in my network. 
I have uploaded in google drive. please check the following link

https://drive.google.com/file/d/0B3oKYtuzoNVWTzJDX3NkNWs0Yms/view?usp=sharing

**Comment by heckflosse** [comment]
@itzsomnath I need a raw file, not a screen shot

**Comment by itzsomnath** [comment]
Please check below link.

https://drive.google.com/file/d/0B3oKYtuzoNVWOWRCRlNVTWlLLXc/view?usp=sharing

**Comment by heckflosse** [comment]
@itzsomnath Here's what I get using auto levels. Do you get the same?
![rt_al](https://cloud.githubusercontent.com/assets/13733487/21581633/908cc32c-d03a-11e6-983b-53c2464e425b.png)

**Comment by itzsomnath** [comment]
@heckflosse yes.
