### ISSUE TITLE
Some buttons need labels

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3571]
Some buttons need labels (the icon can be completely discarded if needed):

- Save reference image for profiling
- Distortion auto-correction (the label could be shortened to "Auto-correct" if needed)
- Probably Auto-crop and the draw rotation line buttons too.

Why - because users can't find them, and we can't clearly refer to them without having to circle them in screenshots, as I did [here](https://discuss.pixls.us/t/canon-g7x-mk-ii-built-in-lens-profile-rawtherapee/2956/2?u=morgan_hardwood) and the user still [said](https://discuss.pixls.us/t/canon-g7x-mk-ii-built-in-lens-profile-rawtherapee/2956/9?u=morgan_hardwood) that the button does not exist.

**Comment by Hombre57** [comment]
Could you test the `buttons-without-label` branch ? I've removed the associated icons, this is the Gtk3 standard. Ok to commit ?

**Comment by Beep6581** [comment]
@Hombre57 looks much better now! But big warning, something happened to all the translation files in this branch, they have corrupt encoding! I will fix it.

**Comment by Beep6581** [comment]
Actually since the problem is already committed, fixing it would mean reverting those changes which would make an unnecessarily messy log, plenty of this kind of stuff:
![0ivtbc8](https://cloud.githubusercontent.com/assets/5844619/21608235/9002924c-d1bb-11e6-9734-6df112d83c06.png)

If you don't mind, I will apply your changes from `rtgui/distortion.cc` and `rtgui/icmpanel.cc` to `gtk3` and update the language files accordingly, that would be the cleanest solution. Are you ok with that?

**Comment by Beep6581** [comment]
@Floessie this is why I didn't want unnecessary non-ASCII stuff in the code files, because of corruption which may go unnoticed.

@Hombre57 which editor did you edit those language files in? Please check that it is UTF8-compliant.

**Comment by Hombre57** [comment]
I'm using Notepad++ to edit language files and it works fine. In the present case, I've saved the changes in patch and apllied it back too with Eclipse. Thoug the integrated editor handle UTF-8 correctly, it doesn't seem to be the case of the 'apply patch' tool.

I'd prefer that you open another branch based on master and apply the change correctly and delete my branch.

**Comment by Hombre57** [comment]
Btw, backporting patch does work fine if the surrounding code is the same, but in our case the code base has diverged strongly, so we should avoid call for trouble by doing this ;)

**Comment by Floessie** [comment]
@Beep6581
> this is why I didn't want unnecessary non-ASCII stuff in the code files, because of corruption which may go unnoticed.

Ah yes, and those corrupted comments will erode to real code each time you save it and start eating our RAWs by secretly killing the eighth bit in every byte to make it ALL ASCII so that in the end we won't even have a photo of an accent or umlaut anymore which will be the end of the world except for the US... :scream: 

All I can say: Shit happens. :grin: But hey, you are free to convert the language files to pure ASCII. I'm just not sure if they are still readable by the intended readers.

**Comment by Floessie** [comment]
@Beep6581 All joking aside: Isn't that something, travis could take care of? Isn't `recode` able to check for pure UTF-8?

**Comment by Beep6581** [comment]
@Floessie I heard it was non-ASCII characters which allowed Donald Trump to become president...

> Isn't that something, travis could take care of? Isn't recode able to check for pure UTF-8?

TravisCI currently only runs on master. It could be made to run on other branches once GTK3 deps are taken care of, but there are other problems. Don't know about `recode` being used for checking, but `file` can check character encodings, though it can't do that reliably - if a file has been corrupted and subsequently saved using UTF-8, it will be identified as valid UTF-8, even though the contents are still corrupted. Further, most of our files use the US-ASCII charset, not UTF-8.

New branch [buttons-without-label-2](https://github.com/Beep6581/RawTherapee/tree/buttons-without-label-2) created, old branch deleted, PR #3580 opened.

**Comment by Floessie** [comment]
@Beep6581 
> I heard it was non-ASCII characters which allowed Donald Trump to become president...

... and only 140 of them. ;)

> Don't know about recode being used for checking, but file can check character encodings, though it can't do that reliably - if a file has been corrupted and subsequently saved using UTF-8, it will be identified as valid UTF-8, even though the contents are still corrupted.

Right, that's impossible to cope with. I found a tool named `isutf8` in the `moreutils` package. But it won't help in that case either.

> Further, most of our files use the US-ASCII charset, not UTF-8.

Well, technically that's a subset of UTF-8, so that shouldn't be a problem.
