### ISSUE TITLE
Keep rotate mode after use (like white balance)

### ISSUE THREAD

**Issue by Krzysiu** [Beep6581/RawTherapee#3574]
This is proposal of enchantment. I'm talking about that toolbar which is just above the photo - crop, rotate, white balance, before/after view. I'll use following abbreviations: WB - white balance; RM - rotate [mode]; WBP - white balance probing; HT - hand tool mode. 

Crop, rotate, white balance and color probing - after cropping and rotating RT is going back to hand tool mode. White balance and color probing is permanently active and you need to turn it off by right click or pressing HT icon. While after crop, it goes back to HT, you can still change it, by dragging borders of selection or moving whole selection, so I'd say it's not a problem. And it means that rotate is inconsistent with the rest.

There are many solutions to this problem and they would not only improve RM but also WBP.

1. Click on the button - one time mode. Click on the button while holding CTRL - permanent mode. It would apply to WBP and RM. 
2. I think it's the best. Three state button (https://developer.gnome.org/gtk3/stable/GtkToggleButton.html#gtk-toggle-button-set-inconsistent). You click for the first time on the button - one time mode (inconsistent state). After second click it enters perm mode (normal button state). Second click - perm mode. Third - one time etc. For now clicking again on already selected mode button does nothing.
3. Buttons stays the same, but you can hold CTRL when rotating/WB probing and as long as CTRL is pressed, it doesn't go back to HT mode. When it's released, RT switches to HT mode.
4. It could work same as new color probing tool. It's in perm mode always and right mouse button goes back to HT mode. After selecting rotate mode pressing right click before rotating also goes back to HT.

There's also case of crop button. After selecting crop, it goes back to HT, but you can still change/move crop borders, so I think it could stay as it's now.

**Comment by Beep6581** [comment]
My opinion is that I've never had issues with the way these tools work, and I don't see a need for making "straighten" stick - you press "s", draw the line along an edge, and that's it, it's fixed, so why keep it sticky?

Cropping is different: you don't crop along an edge, you make the crop and then adjust and re-adjust until you find the perfect fit.

**Comment by Krzysiu** [comment]
OK, but why then white balance is sticky?

**Comment by Beep6581** [comment]
No interest, closing.
