### ISSUE TITLE
RT crashes when saving directly in all formats and through queue -can't save my work on 32bit Windows with 3 GB RAM

### ISSUE THREAD

**Issue by tsbgr79** [Beep6581/RawTherapee#3577]
If you are filing a bug report, please first read the guide How to Write Useful Bug Reports:
http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports
You must provide the required information in order for your bug report to be valid.
Delete this text before posting.

**Comment by tsbgr79** [comment]
Hi and happy New Year!

RT crashes every time I hit the save button or saving multiple or individual files through the queue function.

I can't save my work in any format and when the program crashes after a direct save attempt I lose all the changes after restarting it. The changes stay saved after saving and crashing through queue.

Thanks in advance for your help!

**Comment by TooWaBoo** [comment]
Did you read your first post and followed the instruction? :-)
RT version? OS? Where do you save the files?

**Comment by tsbgr79** [comment]
Ok, I just wanted to _emphasize_ the fact that I can't save the brilliant images I work on ;)

Version 4.2.1074, Windows 7 and I am saving the files in a file sub-directory located on my Desktop. 

I tried to save in different locations including an external USB mass storage device with no success.

**Comment by TooWaBoo** [comment]
Are you on a 32 or 64bit system?

**Comment by Beep6581** [comment]
@tsbgr79 scroll up, click on the "How_to_write_useful_bug_reports" link and read it please.

**Comment by tsbgr79** [comment]
TooWaBoo yes, 32-bit version confirmed.

Beep6581: 

Version 4.2.1074, Windows 7, Quad Core 2.40GHz Intel, 3Gigs of RAM, debug version downloaded from here: http://rawtherapee.com/downloads 

Steps: I work with NEF - Nikon files and after applying the changes RT crashes 4 seconds after clicking the Save button or the Start processing button in the Queue menu

No particular file or process, it happens all the time, no pp3 files to share

This is all the info that I am able to share, I hope it helps :)

**Comment by TooWaBoo** [comment]
@tsbgr79 
This should help:
http://rawtherapee.com/blog/maximizing-memory-efficiency

**Comment by tsbgr79** [comment]
Thanks TooWaBoo, I will try these recommendations and I will let you know of the results asap.

**Comment by gaaned92** [comment]
@tsbgr79  some more info : what is the camera model and pixel size of photos?
If you want some help, the best is to go on [PIXLS.Rawtherapee](https://discuss.pixls.us/c/software/rawtherapee)

As already said you surely run out of memory. This is not a bug but a limitation of 32bits systems that is identified in rawtherapee documentation.
1- As indicated in the link provided by toowaboo, you **must**  use the 3GB flag (see also [here](http://avatechsupport.blogspot.fr/2008/03/how-to-set-3gb-startup-switch-in.html))
2- It may not be sufficient depending on the size of your NEF. What is your camera? the size of your images in pixels?
3- try a more recent version of RT : download a release master build [here](https://discuss.pixls.us/t/download-rawtherapee-builds-windows-macos-linux-appimage-other/2924)
4-Close **all** applications. then open RT and edit one NEF, apply neutral profile, put it in queue,  close your NEF photo in editorpanel(the pp3 is then saved) and start queue. If it crashes, either your NEF is corrupted or you have not enough memory.

**Comment by heckflosse** [comment]
@tsbgr79 If your machine is low on RAM:

1.) Don't use `Save as` to save you files.
2.) Add them to the queue but don't start the queue with an image open in editor.
3.) Close rt and start rt, then start the queue. This way no image is opened in editor when you start the queue.
4.) If that's still not enough, select an empty folder in file browser before you start the queue. That will free some memory you may need to process your files.

**Comment by tsbgr79** [comment]
So I tried all the practical tips you've suggested with no result, RT still crashes while saving.

The link to newer versions that gaaned92 posted contains only XP versions and I run Win7.

Also, the 3GB flag procedure link doesn't cover Win7 (there is no Edit button, the menus are different) and I couldn't do that.

I am also not able to do the 4-Gig tuning, sorry but I am not confident enough to change those values, if you can help me with idiot-proof step by step instructions on how to do it I guess I will cross my fingers and give it a try.

Again, thank you all for your help, I liked RT from the beginning but I didn't expect the saving problem to be that difficult to resolve...

**Comment by gaaned92** [comment]
@tsbgr79 
1- the name of Windows 32 bits builds contains XP(the same as you already downloaded). It doesn't matter. install and use it on Vista.
2- 3GB flag : go to the [link](http://avatechsupport.blogspot.fr/2008/03/how-to-set-3gb-startup-switch-in.html) already given in  my point 1 of my above post. Follow the procedure for vista. Without the flag, you will have little if no chance to be able to process NEF file from recent Nikon camera.
It is the same thing as 4gig tuning.
3- what is the model of your camera, pixel size? beyond 20 Megapixel, it wil be very difficult even impossible to process the NEF on a 32 bit machine.

When you test, process only one image and follow heckflosse procedure step by step.
You must not use save command.
Note : when you "save" it is there that processing tasks occurs. Read rawpedia to understand how it works.
So it is not a "saving problem" but a "processing problem".

**Comment by tsbgr79** [comment]
1- I installed the latest version but every time I open RT a black dialog window pops up first, then command prompts scrolling down in it for about 3 seconds and then the program appears but with coarse graphics and in low res.

2- I followed the procedure, after writing the prompt I got a non acceptance message, restarted anyway, problem still unsolved.

3- I have a Nikon D3300 and yes, it has a 24mp+ sensor so the NEF files are about 10Mb...

**Comment by iliasg** [comment]
Solution:
Windows Vista, Windows 7, or Windows 8
- To enable the 3GB switch:
    Right-click on the Command Prompt icon in the Accessories program group of the Start menu. Click **Run as Administrator**.
    At the command prompt, enter:
    bcdedit /set IncreaseUserVa 3072
    Restart the computer.
- To disable the 3GB switch:
    Right-click on the Command Prompt icon in the Accessories program group of the Start menu. Click **Run as Administrator**.
    At the command prompt, enter:
    bcdedit /deletevalue IncreaseUserVa
    Restart the computer.

Are you sure you have not forgotten to "run as administrator" ?

**Comment by heckflosse** [comment]
@tsbgr79 

> 3- I have a Nikon D3300 and yes, it has a 24mp+ sensor so the NEF files are about 10Mb...

The size of your input file (10MB...) does not matter.
When you save your 24mp file rt needs a lot of memory on top of the already used memory.

**Comment by tsbgr79** [comment]
@iliasg So I tried it again this morning and I was successful. I immediately tried to open the latest RT version 4.2.1477 that I downloaded yesterday and I got the same black dialog window but with no prompts and the program never opened BUT...
...then I clicked on RT version 4.2.1074, it opened normally, I heavily edited a random 25mp pic and BOOM, successful direct save button saving! It took about 10 seconds but it worked :)

Then it crashed again when I tried to save another heavily edited pic from the queue so I decided to go for a real test after restarting it, 5 heavily edited pics successfully saved through the queue function, worked like a charm and the program was responsive throughout the process!

So problem solved for me I guess, my old horse seems to be barely coping after the 3GB switch :)

I really appreciate your help and the time you spent to help me, thank you all again and happy new year!

**Comment by gaaned92** [comment]
@tsbgr79 
If you carefully read [this topic](https://discuss.pixls.us/t/download-rawtherapee-builds-windows-macos-linux-appimage-other/2924), you will observe that under the windows 32 bit builds you find those lines:
```
gtk3 4.2.1477 (2017-01-04)
locallab 4.2.1273 (2016-12-20)
pixelshift 4.2.1267 (2016-12-20)
master 4.2.1232 (2017-01-04)
```
in each line you find the branch name (e.g. gtk3) and a version number (e.g. 4.2.1.1477)
If you want to specify a version you have to give the two parts (e.g. master 4.2.1232).  For this version, you will find in general two builds : a release build that is fast and adebug build much slower for debug purpose.

As I wrote in above post you coud try a newer master build. 
3- try a more recent version of RT : download a **release master** build [here](https://drive.google.com/drive/folders/0B2q9OrgyDEfPOEZmVlBzLWlnSWc)

So what you should download is following file:
RawTherapee_WinXP_32_release_master_4.2.1232.zip
Reading the name, we find that it is: 

- a 32 bit windows Build
- a **release** build (fast and using minimum memory)
- for **master** branch (the only you should use unless you want to test new features)
- version number 4.2.1232 (change with updates, here it is the last version for branch master)

Instead I notice you downloaded a **gtk3** build ( you name it RT version 1477). gtk3 is not ,at this time, the branch to use on 32bits windows for beginner. When you are familiar with RT, you can test it on your PC.

I hope those explanations will help you.
And also don't forget to read [rawpedia](http://rawpedia.rawtherapee.com/Main_Page) from beginning to end. It is not that long

**Comment by tsbgr79** [comment]
@gaaned92 Don't get this wrong but you should start thinking that when you are interacting with obviously less computer literate persons, like me for instance, you should withhold useless information like "when you "save" it is there that processing tasks occurs. So it is not a "saving problem" but a "processing problem" and "the size of your input file (10MB...) does not matter. When you save your 24mp file rt needs a lot of memory on top of the already used memory". Ok, we obviously not know so much about computers and RT in particular like you do but we are not retards and there is absolutely no need to make us look like that. I don't need or want to be a RT expert so stop telling me to carefully read all about it all the time. I click save, RT crashes and it seems like a saving problem to me but no, the computer genius says it's actually a processing problem, usefulness of information 0, show off value 100. Also, I accept being told to adhere to posting rules and to provide complete information about the problem but then I provide extra information about file sizing and the computer genius again says something fancy and totally useless to highlight how clueless I am. And it goes on and on, you posted a random download page and of course I downloaded the wrong version, what a shame, and now you are providing me with additional information about how to pick the right one, wow I guess you couldn't imagine how someone could be that dense! Finally, when someone says "thank you", you should reply to him politely at least once during the conversation, common courtesy never hurt anyone.

**Comment by heckflosse** [comment]
@tsbgr79 

> "the size of your input file (10MB...) does not matter. When you save your 24mp file rt needs a lot of memory on top of the already used memory"

I wrote that part, not @gaaned92

**Comment by tsbgr79** [comment]
@heckflosse Yeah, my bad, I still believe that it's a quite useless piece of information.

I really hope that you will consider my comments without getting the wrong idea, I am not saying that you did any of the above intentionally :)

**Comment by heckflosse** [comment]
@tsbgr79 My bad, as you mentioned the file size my initial thought was 'file size does not matter'. For that reason (and only for that reason!) I wrote that comment. I really thought to give useful information. Maybe I should have given more information (for example the amount of memory rt needs to process 24 Mp files using neutral profile). I just calculated and I'm sure I forgot something: To save a full size 24 Mp file RT needs at least 768.000.000 byte of RAM on top of the already opened RT.

And also happy new year of course :)

**Comment by gaaned92** [comment]
Ok, I did not wanted to be rude but only tried to help giving detailed explanation.  My bad to try to provide so much useless information.
Enjoy Rawtherapee

**Comment by heckflosse** [comment]
@tsbgr79 Maybe you can imagine that neither @gaaned92, nor @iliasg, nor @Beep6581n nor I indented to be rude? We just wanted to support your issue by giving more useful information!

Ingo

**Comment by tsbgr79** [comment]
It's cool, just think of yourselves as guitar teachers from time to time, playing songs is super easy if you can hit every freaking not every freaking time but some people can hardly pluck a string ;)

**Comment by heckflosse** [comment]
People building guitars rarely are good guitar teachers I guess ;)

**Comment by tsbgr79** [comment]
Computer people certainly can't see the forest for the trees most of the times.

**Comment by Beep6581** [comment]
Support for 32-bit platforms ended with 5.0-r1.
