### ISSUE TITLE
Wrong tooltip in IPTC panel

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#3579]
Field "Author" and "Credit" share the same tooltip. The tooltip is wrong for field "Author".
![unbenannt](https://cloud.githubusercontent.com/assets/13800920/21637440/2c1f5f92-d267-11e6-989c-f802b23590f8.png)

**Comment by Beep6581** [comment]
Fixed in commit d654a7a21bd503d4333d821c9bb85d6f0833abcd
The currently missing string will be added in #3581
