### ISSUE TITLE
Update IPTC labels and tooltips to IPTC Core 1.2

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3581]
Update the IPTC labels and tooltips to IPTC Core 1.2 from 2014-06-18.
https://www.iptc.org/std/photometadata/specification/IPTC-PhotoMetadata

Blocked on PR #3580

**Comment by Beep6581** [comment]
Handled in branch [iptc12](https://github.com/Beep6581/RawTherapee/tree/iptc12)

**Comment by Beep6581** [comment]
Updated string in commit 14361da5.

**Comment by Beep6581** [comment]
Grrreat... I started adding missing tags, but found that libiptcdata is stuck at version 1.0.4 from 2009.

**Comment by Beep6581** [comment]
As libiptcdata is dead from 2009 and I can't add new properties, I want to merge this as-is. Created PR #3582

**Comment by Beep6581** [comment]
libexiv2 can read/write IPTC, if RawTherapee used it we could finally drop the rtexif stuff. But that's post-5.0.

**Comment by Hombre57** [comment]
could you deleted branch iptc12 ?

**Comment by Beep6581** [comment]
Done.
