### ISSUE TITLE
Deutsch locale update

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#3584]
Update Soft-Proofing and IPTC
[Deutsch.txt](https://github.com/Beep6581/RawTherapee/files/686160/Deutsch.txt)

btw: The language files are not synchroniced and don't contain the "Soft-Proofing" keys in the "Untranslated Keys" section.

**Comment by Beep6581** [comment]
The IPTC section is not ready for translation, there are pull requests pending.
I will merge your translation, but the IPTC section may get nuked in the process and will need to be updated once the PRs are merged.
