### ISSUE TITLE
Why install options file in /usr/share/ ?

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3586]
When users install RawTherapee in Linux, at least in Ubuntu using the highlyexplosive PPA, [rtdata/options/options.lin](https://github.com/Beep6581/RawTherapee/blob/master/rtdata/options/options.lin) gets installed as /usr/share/rawtherapee/options
Why? There is no need for that file. Only ~/.config/RawTherapee*/options is needed. Seems like a cmake or packaging error to me.

**Comment by Beep6581** [comment]
I don't know about Windows and macOS @sguyader @Partha1b but I don't believe Linux needs this:
https://github.com/Beep6581/RawTherapee/blob/master/rtdata/CMakeLists.txt#L88

**Comment by innir** [comment]
@Beep6581 I didn't look into the code, where is~/.config/RawTherapee*/options sourced from? ~/.config/RawTherapee*/options is not created at install time but at first launch of RT for each user.
I wouldn't touch this code now it works as it is. I'd suggest to work on this after RT 5 - keep in mind, the last chance to get RT 5 into Debian Stretch is within the next ten days and if anything goes wrong with tis code we might and up with no RT in Stretch at all

**Comment by gaaned92** [comment]
In windows, the  options.win (renamed options) is installed near by the RT exe.  it is said that it is the global option file.
If I suppress it and also the "local"  user/.../rawtherapee/options, then, when I start rawtherapee, the "parsed extension" pane is empty in the GUI and also in newly created local options file.

**Comment by Beep6581** [comment]
Confirmed! Defaults are indeed taken from it when I self-compile in Linux too. Closing as invalid.

**Comment by Floessie** [comment]
>  I'd suggest to work on this after RT 5 - keep in mind, the last chance to get RT 5 into Debian Stretch is within the next ten days and if anything goes wrong with tis code we might and up with no RT in Stretch at all

:no_mouth:
