### ISSUE TITLE
Different look between Previews in Editor mode for files from camera with foveon sensor. Windows 10

### ISSUE THREAD

**Issue by meokbodizi** [Beep6581/RawTherapee#3587]
[Screenshot](https://goo.gl/photos/m23saVdDwaz4xQB46)

Also there is problem to read X3F format image created by Sigma SD14.

Histogram covers too wide range than real one. And Exif data not available.

[Here](https://drive.google.com/open?id=0B6Q9Z2vj0OxUSjhVd2hZa3dqZzg) is the X3F raw file.

**Comment by heckflosse** [comment]
@meokbodizi rt has only very basic support for foveon files unfortunately :(

**Comment by meokbodizi** [comment]
@heckflosse Thats sad :(
