### ISSUE TITLE
DCP batch settings broken

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3590]
Color Management > DCP settings are broken in batch mode.

1. Go to Preferences > Batch Processing and make sure it's all on Set mode.
2. Open a photo in the Editor tab and deselect all DCP checkboxes.
3. Click on it in the File Browser. Enable all DCP checkboxes. Click on some other raw and back on this one. DCP checkboxes are still unselected.

I noticed this when I tried to deselect "tone curve" and "look table" for all photos in our test_images/colortarget/ folder.

Tested in dc55eae4 (master current head).

5.0 blocker #3300

**Comment by Hombre57** [comment]
This bug will be fixed on Saturday.

**Comment by heckflosse** [comment]
@Hombre57 :+1:

**Comment by Hombre57** [comment]
Fixed in PR #3608

**Comment by Beep6581** [comment]
Thank you for the fix! Confirmed to work well.

**Comment by Beep6581** [comment]
Closing the issue as the PR has been merged and the branch deleted.
