### ISSUE TITLE
Preview area overflows over UI

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3591]
View the screenshot at 1:1 and look at the toolbox or the left panel https://i.imgur.com/92APmyR.png

```
Branch: master
Version: 4.2.1234
Changeset: dc55eae4164f93d04f281f5b8f54036f184f8b39
Compiler: cc 4.9.3
Processor: Intel(R)\ Core(TM)\ m3-6Y30\ CPU\ @\ 0.90GHz
System: Linux
Bit depth: 64 bits
Gtkmm: V2.24.5
Build type: relwithdebinfo
Build flags: -std=c++11 -Wno-deprecated-declarations -Wno-unused-result -std=gnu++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -O2 -g -DNDEBUG
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON
```

**Comment by Beep6581** [comment]
Seems to be a bizarre monitor thing. I'm using an IPS display.

The dotted grid appears in the area I marked in gold here: https://i.imgur.com/kxYNS0Q.png
I see it in RT and in both the screenshots. I see it when I open the screenshots in GIMP, and the grid stays static when I pan the screenshots. I only see it at 1:1. If I zoom in or enlarge the image 400% using nearest neighbor, the dotted grid disappears.

As a monitor thing, this can most likely be closed, but I'm curious who else can see it. @heckflosse confirmed that he saw something similar in the pixelshift branch, though he can't see it in my screenshot.

**Comment by heckflosse** [comment]
That's not an rt issue. Closing!
