### ISSUE TITLE
Labels for wide GTK3 buttons

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3594]
Buttons in the master branch have both icons and labels (if the system-wide GTK2 settings are set to show them), while in the GTK3 branch some wide buttons still don't have labels.
GTK2 https://i.imgur.com/OfIlfIQ.jpg
GTK3 https://i.imgur.com/D2w0OOy.png https://i.imgur.com/Fu13VVc.jpg

- White balance pipette
- Select Crop
- Auto-Crop
- Select Straight Line

**Comment by Beep6581** [comment]
I left the white balance picker as-is, as the icon is well known even in other programs and looks better than a text label.

https://i.imgur.com/YMuqUIc.jpg

**Comment by heckflosse** [comment]
:+1:

**Comment by Beep6581** [comment]
Merged.
