### ISSUE TITLE
Crash on reading floating point demosaiced DNG files

### ISSUE THREAD

**Issue by jaspervdg** [Beep6581/RawTherapee#3600]
The DNG that can be downloaded [here](https://www.dropbox.com/s/0ixamhnvcmvc4lr/DSC05032-HDR.dng?dl=0) causes RawTherapee to crash (4.2.1375, 4.2.1492, as well as what's in git; on Windows). When running a (debug) build on the commandline it spews errors complaining that "DNG Deflate: Failed uncompressing tile [so and so], with error -5.". It looks like this error corresponds to Z_BUF_ERROR, indicating that somehow the buffer is too small to contain the uncompressed data (line 9802 in dcraw.cc), but I have no idea why that might be.

The DNG was generated using Lightroom's HDR Merge tool, and it looks like pretty much any DNG generated that way suffices to crash RT. However, DNG files generated by "Export to DNG" seem fine, for example...

**Comment by heckflosse** [comment]
Crash confirmed. I will have a look to avoid the crash but float dng files with subtiles are currently not supported in rt. Though rt should not crash for these files but ignore them. That's what I will try to do now.

Ingo

**Comment by jaspervdg** [comment]
Thanks for explaining the issue. It would certainly be a welcome improvement if RT did not crash upon encountering these files.

**Comment by heckflosse** [comment]
@jaspervdg I was wrong about the reason for the crash. The file does not have sub tiles. But it's a demosaiced floating point dng file. This is currently not supported in rt. I'm already testing a fix to skip such files.

**Comment by heckflosse** [comment]
Suggested fix:

```
diff --git a/rtengine/dcraw.cc b/rtengine/dcraw.cc
index dcfe66e..063c472 100644
--- a/rtengine/dcraw.cc
+++ b/rtengine/dcraw.cc
@@ -8753,7 +8753,7 @@ void CLASS identify()
       case 0:
       case 1:     load_raw = &CLASS   packed_dng_load_raw;  break;
       case 7:     load_raw = &CLASS lossless_dng_load_raw;  break;
-      case 8:     load_raw = &CLASS  deflate_dng_load_raw;  break;
+      case 8:     if(tiff_samples == 1) load_raw = &CLASS  deflate_dng_load_raw;  break;
       case 34892: load_raw = &CLASS    lossy_dng_load_raw;  break;
       default:    load_raw = 0;
     }

```

**Comment by Beep6581** [comment]
Fix confirmed, and HDRMerge DNGs are still shown and read correctly.

**Comment by heckflosse** [comment]
Reopened because the patch had side effects. Looking again now.

**Comment by heckflosse** [comment]
I had to revert the last patch because it broke some stuff.
This one should be much better. It only changes code in the function which is calles for deflate compressed dng file, which also can only handle deflate compressed float dng undemosaiced files.
Means it can't break other stuff!
I added some console output too.

```
diff --git a/rtengine/dcraw.cc b/rtengine/dcraw.cc
index dcfe66e..4daf451 100644
--- a/rtengine/dcraw.cc
+++ b/rtengine/dcraw.cc
@@ -9727,10 +9727,28 @@ static void copyFloatDataToInt(float * src, ushort * dst, size_t size, float max
 }
 
 void CLASS deflate_dng_load_raw() {
+    float_raw_image = new float[raw_width * raw_height];
+
+#ifdef _OPENMP
+#pragma omp parallel for
+#endif
+    for (size_t i = 0; i < raw_width * raw_height; ++i)
+      float_raw_image[i] = 0.0f;
+
+  if(tiff_samples != 1) {
+    fprintf(stderr, "deflate_dng_load_raw %s: demosaiced float dng files are not supported\n",ifname);
+    return;
+  }
+
   struct tiff_ifd * ifd = &tiff_ifd[0];
   while (ifd < &tiff_ifd[tiff_nifds] && ifd->offset != data_offset) ++ifd;
   if (ifd == &tiff_ifd[tiff_nifds]) {
-    fprintf(stderr, "DNG Deflate: Raw image not found???\n");
+    fprintf(stderr, "deflate_dng_load_raw %s: Raw image not found???\n",ifname);
+    return;
+  }
+
+  if (ifd->sample_format != 3) {  // no floating point data
+    fprintf(stderr, "deflate_dng_load_raw %s: Only float format is supported for deflate compressed dng files\n",ifname);
     return;
   }
 
@@ -9742,16 +9760,6 @@ void CLASS deflate_dng_load_raw() {
 	default: predFactor = 0; break;
   }
 
-  if (ifd->sample_format == 3) {  // Floating point data
-    float_raw_image = new float[raw_width * raw_height];
-
-#ifdef _OPENMP
-#pragma omp parallel for
-#endif
-    for (size_t i = 0; i < raw_width * raw_height; ++i)
-      float_raw_image[i] = 0.0f;
-  }
-
   // NOTE: This reader is based on the official DNG SDK from Adobe.
   // It assumes tiles without subtiles, but the standard does not say that
   // subtiles or strips couldn't be used.

```

**Comment by iliasg** [comment]
@heckflosse @jaspervdg 
I think this should be reported to dcoffin .. https://www.cybercom.net/~dcoffin/dcraw/

**Comment by heckflosse** [comment]
@iliasg that's not in official dcraw. It's in the code Javier wrote for hdrmerged files

**Comment by jaspervdg** [comment]
@heckflosse Ah, that makes (some sort of) sense, I guess Lightroom demosaics the files while doing the HDR merge. Note that (in case anyone else runs into this issue) a workaround seems to be to use "Export to DNG" on the merged file in Lightroom. (Not sure why this works, but it does.) I look forward to trying your (new) patch.

**Comment by Beep6581** [comment]
New patch works as advertised, ARWs and HDRMerge'd HDRs work fine.
