### ISSUE TITLE
Crash on open JPEG file with corrupted metadata (include) +gdb log

### ISSUE THREAD

**Issue by dimmaq** [Beep6581/RawTherapee#3602]
Hello/
Crash open image [DSC_1004.zip](https://github.com/Beep6581/RawTherapee/files/693415/DSC_1004.zip)

Test on win10x64 RawTherapee_WinVista_64_Gtk3_Release_4.2.1375 download from http://rawtherapee.com/downloads
 ubuntu 16.10x64  ver4.2.0 and unstable ver  from rep ppa:dhor/myway

GDB log
[log.txt](https://github.com/Beep6581/RawTherapee/files/693474/log.txt)
Branch: gtk3
Version: 4.2.1492
Changeset: 4c20b1f4af1928d80467833b9f93cbb0ea26ca71
Compiler: gcc 6.2.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.22.0
Build type: debug
Build flags:  -m64 -mwin32 -mthreads -std=gnu++11 -Werror=unused-label -Werror=unknown-pragmas -Wno-aggressive-loop-optimizations -std=gnu++11 -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -O1 -g2
Link flags: -m64 -mthreads  -static-libgcc   -mtune=generic -O1
OpenMP support: ON
MMAP support: ON

**Comment by heckflosse** [comment]
Crash confirmed.

**Comment by Beep6581** [comment]
Confirmed in Linux, the JPEG has corrupt metadata.

**Comment by Floessie** [comment]
@heckflosse Didn't have a closer look, yet, but if `t->getCount()` is smaller than 8, fancy things will happen...

**Comment by heckflosse** [comment]
@Floessie :+1: t-getCount was 6...

**Comment by Floessie** [comment]
@heckflosse My debug build has just finished. I came to the same conclusion, but you were faster:

```
(gdb) f 2
#2  0x00005555561fd2f8 in rtexif::UserCommentInterpreter::toString[abi:cxx11](rtexif::Tag*) (this=0x5555567466c8 <rtexif::userCommentInterpreter>, t=0x7fffac0047b0)
    at /home/user/src/rawtherapee/rtexif/stdattribs.cc:451
451	            strncpy (buffer, (char*)t->getValue() + 8, t->getCount() - 8);
(gdb) p t->count 
$1 = 6
```

Best
Flössie
