### ISSUE TITLE
Build on Linux broken due DCP profile filename typo

### ISSUE THREAD

**Issue by virosh** [Beep6581/RawTherapee#3603]
Hello!

I tried to build RT few minutes ago and surprisingly it failed.
The issue was with one of the DCP profiles - Sony ILCE-6000.dcp. When the make script tries to copy the profile to the build directory it fails due to the fact that the filename is **SONY** ILCE-6000.dcp.
The workaround is to rename the file and run the BuildRT without forcing an update.
Below you will find information regarding the build and the exact error:

> Branch: master
> Version: 4.2.1253
> Changeset: cef9b7fe2b35730314f0b066086f63ea4c171df7
> Compiler: cc 6.2.1
> Processor: x86_64
> System: Linux
> Bit depth: 64 bits
> Gtkmm: V2.24.5
> Build type: release
> Build flags: -std=c++11 -Wno-deprecated-declarations -Wno-unused-result -std=gnu++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG
> Link flags:  -march=native
> OpenMP support: ON
> MMAP support: ON

```
CMake Error at rtdata/cmake_install.cmake:220 (file):
  file INSTALL cannot find
  "/home/virosh/dev/rawtherapee/rtdata/dcpprofiles/Sony ILCE-6000.dcp".
Call Stack (most recent call first):
  cmake_install.cmake:80 (include)


Makefile:105: recipe for target 'install' failed
make: *** [install] Error 1
```

**Comment by heckflosse** [comment]
@virosh Thanks for reporting :+1:

**Comment by Beep6581** [comment]
Colortarget photos and the DCP profiles generated from them are to be named exactly the same way RawTherapee identifies them. This is the case here; other profiles will be updated before RT5 release.
