### ISSUE TITLE
Update TooWaBlue Gtk+3.22 Version 2.31

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#3604]
Minor fixes,
External images of radio- and checkbuttons are no longer needed.
[TooWaBlue-GTK3-20_.txt](https://github.com/Beep6581/RawTherapee/files/699382/TooWaBlue-GTK3-20_.txt)
[TooWaBlue-Dark-GTK3-20_.txt](https://github.com/Beep6581/RawTherapee/files/699383/TooWaBlue-Dark-GTK3-20_.txt)

**Comment by Beep6581** [comment]
Can you submit a patch/PR which removes the buttons and updates the files?

**Comment by TooWaBoo** [comment]
@Beep6581 
I don't understand what you mean. The theme uses now the Adwaida checkbox and radiobutton with a modified frame. All is done by css.
