### ISSUE TITLE
Looking for Theme Testers

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#3605]
I've created a test TooWaBlue theme to address the issue of different DPI settings.
The layout grows with the font size. I don't know if it solves the issue, so I need some testers who can test different DPI settings and post some screenshots.

[TooWaBlue-GTK3-20_.txt](https://github.com/Beep6581/RawTherapee/files/718899/TooWaBlue-GTK3-20_.txt)
[TooWaBlue-Dark-GTK3-20_.txt](https://github.com/Beep6581/RawTherapee/files/718900/TooWaBlue-Dark-GTK3-20_.txt)

1. Download TooWaBlue-GTK3-20_.txt
2. Rename the file extension .txt into .css
3. Move it into the theme folder
4. Run RT, open Preferences and select "TooWaBlue"
5. Click OK and restart RT

**Comment by Hombre57** [comment]
@TooWaBoo Keep in mind that we (i.e. @Beep6581) will generate several icon size in a near future to each high-DPI support, I don't want you to make useless fine tuning (but it's up to you of course).

Also there are lots of in source functions to control spacing. You can look for `set_column_spacing`, `set_row_spacing` (gtk3 functions) and `set_border_width`, `set_spacing`. I don't have enough time to replace everything and will probably only do it once the Gtk2 branch has been dropped, but you can still ask me to delete the ones that are annoying you.

**Comment by TooWaBoo** [comment]
@Hombre57 
Thanks for the info, but 99% are finished now. :-) I've updated the test file to **version 2**.
The sized images are no problem, as long as they are smaller or equal as the button itself.
Right now I can live with the hardcoded sizing. We can talk about this when you are working on it.

At the moment I'm intersted how the theme looks like on high DPI settings and on a Macintosh (different font rendering). I'll hope there are some poeple out there, who can do some tests.

**Comment by Beep6581** [comment]
@TooWaBoo you can test for yourself using the environment variables `GDK_DPI_SCALE` and `GDK_SCALE`.

**Comment by TooWaBoo** [comment]
@Beep6581 

Testing on my systemis is easy. I'm setting different DPI values, or changeing the font size.
What I want to know is, how it looks like on other systems and/or OS. eg. the font size value on OS X is not the same like in Windows.

btw. Where can I find those environment variables in Windows?

**Comment by TooWaBoo** [comment]
Test theme update to version 6 in the first post.

**Comment by Beep6581** [comment]
> btw. Where can I find those environment variables in Windows?

https://www.nextofwindows.com/how-to-addedit-environment-variables-in-windows-7

In Linux they can be used from the same command which launches the executable, so it's quite likely the same thing will work in Windows:
`GDK_SCALE=2 GDK_DPI_SCALE=1 C:\rt\rawtherapee.exe`

**Comment by TooWaBoo** [comment]
@Beep6581 
> Expect RT to look broken on 1920x1080 regardless of theme.

This has nothing to do with the theme itselfs. If your DPI setting is set to 200% the system is scaling up all images except the tumbnails. This happens with the RT theme too.

**Comment by Beep6581** [comment]
I know, that's why I wrote "regardless of theme".

**Comment by TooWaBoo** [comment]
You can also set a DPI in the theme by doing this:
```
* {
    ‑gtk‑dpi: 120; /* 120dpi*/
}
```

**Comment by Beep6581** [comment]
That's the equivalent of using `GDK_SCALE=1 GDK_DPI_SCALE=2` (replace "2" with whatever), i.e. only text is scaled, but real HiDPI requires `GDK_SCALE=2` which scales all elements, not just text.

**Comment by TooWaBoo** [comment]
TWB test update to version 7 in the first post.
Checkbox, radio button and scrollbar resizing added.

@Hombre57 
I can't resize the filmstrip scrollbar. I guess there are some things hardcoded. Could this be the reason of the scrollbar stuck issue? Maybe a floating scrollbar will fix it.

**Comment by Hombre57** [comment]
@TooWaBoo No, there isn't any hardcoded styling for those scrollbars. It's part of "the mysteries of the Gtk scrollbar" for me.

**Comment by TooWaBoo** [comment]
TWB test update to version 10 in the first post.

Resizing of the filmstrip scrollbar works now. Minor fixes.
This is the final test. Everything which could be done by the theme file has been done.

**Comment by Beep6581** [comment]
@TooWaBoo advertise this in the forum for more feedback. Let me know when it's ready for commit.

**Comment by TooWaBoo** [comment]
TWB test update to version 11 in the first post.

Resizing of the scrollbar rewritten.
Add a workaround for the scrollbar stuck bug. The filmstrip height is now calculated correct. There is a small issue with the workaround. The correct length of the filmstrip/file browser scrollbar is wrong and will be corrected after hovering the scrollbar the first time.

@Hombre57 
Let me know when you need help to add the workaround to the RT theme.

@Beep6581 
I will advertice the theme in the forum today.

**Comment by TooWaBoo** [comment]
@Beep6581 
Final update TooWaBlue version 2.40 in the first post. Ready for commit

**Comment by Beep6581** [comment]
@TooWaBoo so you would like this to overwrite the existing TWB theme files, correct?

**Comment by TooWaBoo** [comment]
@Beep6581 
Yes, or is there any reason to keep the non DPI version?

**Comment by Beep6581** [comment]
@TooWaBoo not that I know of. As long as someone with a real HiDPI screen confirmed no issues. And the non-`em` version will always be in git history, if we need it.

**Comment by TooWaBoo** [comment]
Then we should replace the px-version.

**Comment by Beep6581** [comment]
TODO #3300

**Comment by Hombre57** [comment]
@TooWaBoo What do you want me to do exactly ? How does your workaround works and what should be done in the code ?

**Comment by TooWaBoo** [comment]
@Hombre57 
Add this to your css.
```
/* Scrollbar stuck workaround */
scrollbar:not(.overlay-indicator).horizontal:hover slider {
    min-width: calc(2em - 0.0001px);
}
scrollbar:not(.overlay-indicator).vertical:hover slider {
    min-height: calc(2em - 0.0001px);
}

```
Every time, when you hovering the scrollbar it triggers a refresh, which makes the scrollbar usable.

**Comment by TooWaBoo** [comment]
@Hombre57 
I thought too complicated for the _Scrollbar stuck workaround_. :-)
This will do the same simpler:

```
/* Scrollbar stuck workaround */
scrollbar:not(.overlay-indicator):hover {
    min-width: 1px;
}
```

**Comment by Hombre57** [comment]
@TooWaBoo I tried hard to fix the scrollbar bug in the code, but I give up. However your change in CSS just above doesn't work either when pasted in rawtherapee's main theme.

**Comment by TooWaBoo** [comment]
Did you test the TooWaBlue theme too?
I've modified the RT theme and it works with RT 4.2.1527 on Win 10 x64.
[RawTherapee-GTK3-20_.txt](https://github.com/Beep6581/RawTherapee/files/722087/RawTherapee-GTK3-20_.txt)

**Comment by Hombre57** [comment]
@TooWaBoo Your patch work as you described, I forgot the "hover" step. Not a full fix but better than nothing. @Beep6581 have committed this patch, and should commit your theme before tagging too.

**Comment by Beep6581** [comment]
@TooWaBoo are you around?
I will change this:
  `Version 2.40 - requires RT 4.2.1445 or higher`
to a more user-friendly this:
    `Version 2.40 - requires RT 5.0`
Let me know ASAP if you don't want that. Sorry for the short notice.

**Comment by TooWaBoo** [comment]
@Beep6581 

That's OK.
