### ISSUE TITLE
Cannot compile GTK3

### ISSUE THREAD

**Issue by Desmis** [Beep6581/RawTherapee#3610]
Hello

After many days, for Localllab, I try again GTK3, the last time it was a few weeks ago.

And I cannot compile, with error message "Align' is not an enumerator-name", etc.

I saw,there is a new version of MSYS2. I am with "msys2-x86_64_20150916" and the current is "msys2-x86_64_20161025"...

What must I do ? What precautions ?

Thank you :)

**Comment by Beep6581** [comment]
Hey @Desmis 
These instructions are up to date: http://rawpedia.rawtherapee.com/Windows
Make sure you either delete or rename the "build" folder when switching branches.
If you still have a problem, please paste the full log.

**Comment by Desmis** [comment]
@Beep6581 
https://filebin.net/jxxgqroj85819zt8

I completely reinstalled MSYS2, because no choice to update Msy2 ??

Previously, but I did not delete it I had a folder "msys64". I called the new "msys64new".
The installation was quite long, but no problem.

I created a Clone in:
C: / msys64new / home / jacques / R_T1

Then I chose the branch gtk3

The compilation went smoothly:
But at the execution I have a crash that I along with the link 
_ZN4Glib17signalProxyNormal13connect_impl_EbON4sigc9slot_baseEB  ==> not found
Can you help me ?

Thank you
Jacques

**Comment by Beep6581** [comment]
@Desmis maybe @heckflosse can help you as he helped someone with the same problem here: https://discuss.pixls.us/t/help-in-developing-rawtherapee-as-developer/1610/6?u=morgan_hardwood

**Comment by Desmis** [comment]
@Beep6581 
@heckflosse 

I used the other "Old" Installation "Msys2", and all works well : compilation - execution

Perhaps a conflict between the 2, but if I delete the first...I will have nothing !!

I look at "environment variables", but I don't see anything no normal ??

I wait from Ingo

Thank you
Jacques

**Comment by heckflosse** [comment]
@Desmis 
Hello Jacques, I never had that `_ZN4Glib17signalProxyNormal13connect_impl_EbON4sigc9slot_baseEB ==> not found` bug.
For building gtk2 and gtk3 branches I use two build folders `build2` and `build3`.

> but if I delete the first...I will have nothing

why not keep the first as it seems to work now?

Ingo

**Comment by Desmis** [comment]
@heckflosse 
OK, its what I do...I have 4 or 5 clone, and I choose between...

But with the first I cannot compile gtk3 !

Jacques

**Comment by heckflosse** [comment]
@Desmis I meant 1 clone, but 2 build folders inside the clone folder. One for gtk2 and one for gtk3 based branches

**Comment by Desmis** [comment]
@Beep6581 @heckflosse 
I repeat new installations, twice...
To have maximum chances, I create a new Msys2 : mingw64n in an other drive D:
I look at all messages, the only I saw is in:
"pacman -S tar gzip nano make diffutils intltool git " where "avertissements "are done for impossibility to recupare info files SVN in usr/share/ma/man3/git::SVN for 7 files : Ra.3pm.gz, etc.

Otherwise, alla seems to work.

But when I click on Rawtherapee.exe , always the same message..._ZN4Glib17signalProxyNormal13connect_impl_EbON4sigc9slot_baseEB ==> not found

I saw in the doc of MSYS2, the possibility of updating package, instead of installation !
Perhaps there are conflicts...and perhaps, it is necessary to all uninstall ?

**Comment by Desmis** [comment]
I try to update my old Msys2 with the process in MSYS2 doc : pacman -Syuu

But I have very very numerous errors....
Now, new MSYS2 and old MSYS2 does not woks !!!

I think, all desinstall...with which tools ? and reinstall after.... or change my computer ?
In any case, I can not do anything for RT

:)

**Comment by Desmis** [comment]
@Beep6581 @heckflosse 
It seems to work :)
I am careful, because there was still at the start a crash with the message:

(rawtherapee.exe:35412): GLib-GObject-←[1;33mWARNING←[0m **: instance of invalid non-instantiatable type '<invalid>'

(rawtherapee.exe:35412): GLib-GObject-←[1;35mCRITICAL←[0m **: g_signal_handlers_destroy: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

If I restart RT everything seems to work ... to check!

That's what I did:
1) To locate all programs found on the Internet that involve "_Z4 ..." (libgiomm-2.4-1.dll) : imagemagig, etc. and uninstall them
2) uninstall with "Ccleane"r and "IobitUninstaller", all MSYS2, old git, old msys, old TDMGCC, old cmake, etc.
3) clean register
4) Make inactive the antivirus "avast", which controls during the installation the files * .exe - important

5) install MSYS2 version 20161025.
6) and follow the instructions of Rawpedia

to be continued :)
jacques

**Comment by Desmis** [comment]
I install 2 clones 
1) for gtk2
2) for gtk3
All seems to work :)


I think Rawpedia must be updated.... At least in my case, we cannot install another MSYS2...That leads to crash, and big difficulties ! The best for me, is to uninstall old version, and then reinstall. Its take about 1h30, but it's sure !

**Comment by Beep6581** [comment]
@Desmis happy to hear you sorted the problem out!

> I think Rawpedia must be updated...

I'm happy to help with that, but I don't see what to update...
http://rawpedia.rawtherapee.com/Windows
The article doesn't mention having two MSYS2 installations, it only says:

> Begin by installing and updating MSYS2 using the instructions from the MSYS2 website.
