### ISSUE TITLE
 D65 Color Target Shots for Nikon D7000

### ISSUE THREAD

**Issue by dnw3039** [Beep6581/RawTherapee#3612]
Colour target shots for Nikon D7000 

https://filebin.net/i1dhccis98x2un7g/_DSC8221.NEF

https://filebin.net/i1dhccis98x2un7g/_DSC8227.dng

regards

David

**Comment by Beep6581** [comment]
@dnw3039 thank you, but please shoot the target smaller so that it fills less of the frame (1/3rd), like this https://i.imgur.com/7ptIcsP.jpg
shoot it in direct sunlight, use a faster shutter speed so that there is no motion blur, and shoot about 2EV brighter because your shot it 2EV underexposed. We also need a tungsten shot.

Instruction updated, see http://rawpedia.rawtherapee.com/How_to_create_DCP_color_profiles#Shooting_the_color_chart

**Comment by Beep6581** [comment]
@dnw3039 Friday is the last day for inclusion in RT5, though if you can't make it by then we will just include it in 5.1.

**Comment by dnw3039** [comment]
I have tried to get the best exposure, but I don't think they are are right as I can not produce a good DCP from them. Anyhow here are my attempts.

It is very hard to find a tungsten globe now in Australia, imports have been banned for the last 15 years. I found an old 150w spotlight in the attic.

https://filebin.net/x6soot8erd7u52cr/tungsten.NEF
https://filebin.net/x6soot8erd7u52cr/daylight.NEF

**Comment by dnw3039** [comment]
Hi,

When you have finished the work for RT v5. Could you advise me on how to get a good profile image. 
I don't think I have ever had a better result than -  "  25.00% of the patches was removed due to being nearby the whitepoint.  Largest chromaticity group contains 2 patches. Patch count reduced from
  24 to 17.'

This was taken in my garden about midday in full sunlight, - there are large tress around - could they cause this problem ?

I have taken dozen of photo's at different exposes and prevented over-exposure.

This is the make-profile result for the daylight picture https://filebin.net/x6soot8erd7u52cr/tungsten.NEF

 dnw@Capulet:/test/dcam$ ./dcamprof make-profile -i D50 -C daylight.ti3 daylight.json
Reading target...
Generating values for the calibration illuminant D50...
Re-generating target reference XYZ values for illuminant D50...
Camera G on darkest patch(es) is 6.5% lighter compared to observer Y.
  Y dynamic range is 4.84 stops, G dynamic range is 4.75 stops, difference
  0.09 stops. A small difference is normal, while a large indicates that there
  is glare.
Warning: auto-selected neutral patch (D02) is not the lightest, as the
  lightest patch is considerably off-white. That is if you later use the target
  for white balancing you should use the indicated patch instead of the
  lightest.
The most neutral patch (D02) differs 1.22 DE from actual neutral,
  transforming target reference XYZ values to match, using CAT02.
Automatic LUT relaxation weights assigned.
Making camera profile...
Finding a camera raw RGB to CIE XYZ matrix for calibration illuminant D50...
Whitest patch in target (D02) differs DE 1.22 from calibration illuminant,
  close enough to calculate whitepoint preservation.
Inverting to get ColorMatrix:
  {
    "ColorMatrix1": [
      [  0.665857, -0.150254, -0.044773 ],
      [ -0.439617,  1.174878,  0.300944 ],
      [ -0.081713,  0.196972,  0.737997 ]
    ]
  }
Matrix patch match average DE 1.41, DE LCh 0.84 0.49 0.80
                    median DE 1.42, DE LCh 0.86 0.45 0.65
                       p90 DE 2.53, DE LCh 1.85 1.12 1.79
                       max DE 3.89, DE LCh 2.28 1.53 3.41
ColorMatrix optimal white balance for target: 0.455136,1,0.727666 (m2.19715,1,1.37426)
Finding a camera raw RGB to CIE XYZ matrix for connection space illuminant D50...
  {
    "LUTMatrix1": [
      [  0.700741,  0.122284,  0.141193 ],
      [  0.328470,  0.631572,  0.039958 ],
      [  0.000943,  0.013064,  0.811195 ]
    ]
  }
LUTMatrix optimal white balance for target: 0.451957,1,0.724216 (m2.2126,1,1.3808)
Matrix patch match average DE 4.92, DE LCh 1.98 3.59 3.09
                    median DE 5.21, DE LCh 1.66 3.06 3.24
                       p90 DE 9.08, DE LCh 4.46 7.34 6.86
                       max DE 10.59, DE LCh 5.33 8.25 10.03
Finding a camera raw RGB to CIE XYZ matrix for connection space illuminant D50...
  Y row limit set to -0.2.
Applying white-balance to get ForwardMatrix:
  {
    "ForwardMatrix1": [
      [  0.730343,  0.139228,  0.094648 ],
      [  0.300349,  0.844006, -0.144355 ],
      [  0.040480, -0.333251,  1.117973 ]
    ]
  }
ForwardMatrix optimal white balance for target: 0.451957,1,0.724216 (m2.2126,1,1.3808)
Matrix patch match average DE 1.70, DE LCh 0.98 0.86 0.78
                    median DE 1.68, DE LCh 1.11 0.79 0.42
                       p90 DE 3.05, DE LCh 1.92 1.67 1.97
                       max DE 3.68, DE LCh 2.80 2.37 3.06
Making 2.5D chromaticity-addressed lookup table for XYZ correction...
4.17% of the patches was put in a chromaticity group due to nearby neighbor.
  25.00% of the patches was removed due to being nearby the whitepoint.
  Largest chromaticity group contains 2 patches. Patch count reduced from
  24 to 17. Note that patch matching cannot reach 100% when chromaticity
  groups are formed, as the LUT matches the average within a group.
Lightness axis is disabled. Since lightness affects chroma, the LUT chroma
  control points are recalculated to better match the uncorrected lightness.
  A residual error of up to about 0.2 DE is expected.
Relaxing LUT stretch with up to 3.93 DE. Iterating over 17 patches...
  Lightness correction is disabled.
.Average DE for the 17 tested patches increased to 1.90 after LUT relax.
  64.71% could do without LUT correction.
Native LUT patch match average DE 1.65, DE LCh 0.93 1.06 0.59
                        median DE 1.51, DE LCh 1.01 0.96 0.55
                           p90 DE 3.01, DE LCh 1.88 2.36 1.31
                           max DE 3.34, DE LCh 2.22 3.18 1.37
5 worst patches for Overall DE:
  C04 RGB 0.330 0.515 0.133 XYZref 0.663 0.666 0.082 XYZcam 0.630 0.638 0.116 sRGB #FECE20 #F9CB48 DE 3.34 DE LCh -0.95 -3.18 +0.36 (light vivid yellow)
  B06 RGB 0.258 0.314 0.079 XYZref 0.537 0.477 0.066 XYZcam 0.476 0.432 0.073 sRGB #F7A62B #E8A137 DE 3.08 DE LCh -2.22 -2.05 +0.60 (light strong orange)
  B05 RGB 0.172 0.420 0.128 XYZref 0.390 0.485 0.099 XYZcam 0.357 0.441 0.107 sRGB #AFC245 #A8B94F DE 3.01 DE LCh -2.13 -2.05 +0.55 (light strong yellow-green)
  C01 RGB 0.029 0.102 0.163 XYZref 0.077 0.064 0.235 XYZcam 0.084 0.074 0.220 sRGB #00499A #184B94 DE 2.46 DE LCh +1.88 -2.36 -1.37 (dark purple-blue)
  C03 RGB 0.132 0.076 0.042 XYZref 0.242 0.140 0.042 XYZcam 0.230 0.144 0.051 sRGB #C0333A #B74041 DE 2.44 DE LCh +0.53 -2.37 +0.11 (strong red)
5 worst patches for Lightness DE:
  B06 RGB 0.258 0.314 0.079 XYZref 0.537 0.477 0.066 XYZcam 0.476 0.432 0.073 sRGB #F7A62B #E8A137 DE 3.08 DE LCh -2.22 -2.05 +0.60 (light strong orange)
  B05 RGB 0.172 0.420 0.128 XYZref 0.390 0.485 0.099 XYZcam 0.357 0.441 0.107 sRGB #AFC245 #A8B94F DE 3.01 DE LCh -2.13 -2.05 +0.55 (light strong yellow-green)
  C01 RGB 0.029 0.102 0.163 XYZref 0.077 0.064 0.235 XYZcam 0.084 0.074 0.220 sRGB #00499A #184B94 DE 2.46 DE LCh +1.88 -2.36 -1.37 (dark purple-blue)
  C02 RGB 0.067 0.250 0.099 XYZref 0.165 0.252 0.086 XYZcam 0.161 0.237 0.085 sRGB #51994E #57934F DE 2.22 DE LCh -1.44 -1.55 -0.67 (yellow-green)
  B01 RGB 0.233 0.202 0.059 XYZref 0.445 0.342 0.053 XYZcam 0.416 0.321 0.059 sRGB #EE802F #E67D38 DE 2.31 DE LCh -1.39 -1.36 -1.25 (strong orange)
5 worst patches for Chroma DE:
  C04 RGB 0.330 0.515 0.133 XYZref 0.663 0.666 0.082 XYZcam 0.630 0.638 0.116 sRGB #FECE20 #F9CB48 DE 3.34 DE LCh -0.95 -3.18 +0.36 (light vivid yellow)
  C03 RGB 0.132 0.076 0.042 XYZref 0.242 0.140 0.042 XYZcam 0.230 0.144 0.051 sRGB #C0333A #B74041 DE 2.44 DE LCh +0.53 -2.37 +0.11 (strong red)
  C01 RGB 0.029 0.102 0.163 XYZref 0.077 0.064 0.235 XYZcam 0.084 0.074 0.220 sRGB #00499A #184B94 DE 2.46 DE LCh +1.88 -2.36 -1.37 (dark purple-blue)
  B05 RGB 0.172 0.420 0.128 XYZref 0.390 0.485 0.099 XYZcam 0.357 0.441 0.107 sRGB #AFC245 #A8B94F DE 3.01 DE LCh -2.13 -2.05 +0.55 (light strong yellow-green)
  B06 RGB 0.258 0.314 0.079 XYZref 0.537 0.477 0.066 XYZcam 0.476 0.432 0.073 sRGB #F7A62B #E8A137 DE 3.08 DE LCh -2.22 -2.05 +0.60 (light strong orange)
5 worst patches for Hue DE:
  C01 RGB 0.029 0.102 0.163 XYZref 0.077 0.064 0.235 XYZcam 0.084 0.074 0.220 sRGB #00499A #184B94 DE 2.46 DE LCh +1.88 -2.36 -1.37 (dark purple-blue)
  C06 RGB 0.054 0.269 0.271 XYZref 0.149 0.209 0.332 XYZcam 0.155 0.210 0.334 sRGB #009BBA #0097B7 DE 1.57 DE LCh +0.10 -0.77 +1.35 (blue)
  A02 RGB 0.221 0.306 0.190 XYZref 0.434 0.387 0.214 XYZcam 0.418 0.367 0.205 sRGB #D29987 #D09484 DE 1.79 DE LCh -1.14 +0.42 -1.31 (red)
  B01 RGB 0.233 0.202 0.059 XYZref 0.445 0.342 0.053 XYZcam 0.416 0.321 0.059 sRGB #EE802F #E67D38 DE 2.31 DE LCh -1.39 -1.36 -1.25 (strong orange)
  A01 RGB 0.066 0.093 0.054 XYZref 0.130 0.113 0.057 XYZcam 0.125 0.112 0.056 sRGB #7C5547 #795546 DE 1.54 DE LCh -0.25 -0.96 +1.18 (dark brown)
5 best patches for Overall DE:
  D02 RGB 0.291 0.645 0.467 XYZref 0.622 0.645 0.532 XYZcam 0.622 0.645 0.532 sRGB #D2D2D2 #D2D2D2 DE 0.00 DE LCh +0.00 +0.00 +0.00 (gray 80%)
  D05 RGB 0.045 0.100 0.073 XYZref 0.094 0.098 0.083 XYZcam 0.096 0.099 0.084 sRGB #575859 #585859 DE 0.36 DE LCh +0.20 +0.05 +0.29 (gray 40%)
  D06 RGB 0.016 0.035 0.026 XYZref 0.034 0.035 0.030 XYZcam 0.034 0.035 0.030 sRGB #343435 #343436 DE 0.69 DE LCh -0.00 +0.69 -0.01 (gray 20%)
  B02 RGB 0.053 0.170 0.235 XYZref 0.136 0.125 0.320 XYZcam 0.140 0.131 0.311 sRGB #3262AE #3765AC DE 1.07 DE LCh +0.86 -1.08 -1.00 (purple-blue)
  A05 RGB 0.114 0.263 0.273 XYZref 0.268 0.255 0.365 XYZcam 0.256 0.244 0.344 sRGB #8286B6 #8084B1 DE 1.15 DE LCh -1.01 -0.46 +0.16 (purple-blue)
Writing output to "daylight.json"...
Complete!


regards

David Wilson

**Comment by Beep6581** [comment]
@dnw3039 the daylight shot is underexposed by 1.3EV. Could be improved but not a big problem. The tungsten shot is unevenly lit - that leads to massive delta-E and is a showstopper. The shots must be re-taken.

**Comment by Beep6581** [comment]
@dnw3039 will you supply a new shot?

**Comment by dnw3039** [comment]
Here are the best three tungsten shots. I have not been able to find a 100 watt globe. These are taken with a 150 watt tungsten flood light. This is the best I can do. 
 
I have not been able to take a single picture after many at different exposures of my colorpassport target where dcamprof does not produce a message like "Patch count reduced from  24 to 15. " or 24 -17. Or complain of too much glare. 

The link https://filebin.net/0v4fyigw6becofx6

I hope my efforts are of some assistance.

regards

David

**Comment by Beep6581** [comment]
@dnw3039 all of the images suffer from glare and uneven lighting due to the short distance and acute angle between the light source and the target, and the brightest one has motion blur. They are not usable.
http://rawpedia.rawtherapee.com/How_to_create_DCP_color_profiles#Shooting_the_color_target

**Comment by Beep6581** [comment]
No progress, closing.
