### ISSUE TITLE
failed install Fujifilm X-E2.dcp 

### ISSUE THREAD

**Issue by ezombie** [Beep6581/RawTherapee#3614]
-- Up-to-date: /home/test/rawtherapee/build/release/./dcpprofiles/Fujifilm X-E2.dcp
CMake Error at rtdata/cmake_install.cmake:220 (file):
  file INSTALL cannot find
  "/home/test/rawtherapee/rtdata/dcpprofiles/Fujifilm X-T1.dcp".
Call Stack (most recent call first):
  cmake_install.cmake:80 (include)

Makefile:61: recipe for target 'install' failed
make: *** [install] Error 1

real	0m4.155s
user	0m3.209s
sys	0m0.862s

Error during make, exiting.

**Comment by heckflosse** [comment]
@ezombie Some dcp files have been renamed. Please run cmake again before running make. That should solve the issue.
