### ISSUE TITLE
Tungsten Color Target Shots for Nikon D750

### ISSUE THREAD

**Issue by paperdigits** [Beep6581/RawTherapee#3618]
Here are color target shots for the Nikon D750. I've uploaded many, since I'm not sure which one is good and which one isn't. Some are directly lit by the bulb, while others are bounced off a white wall. 

https://filebin.net/cdm83p07f02jck0s

I release these files under the Creative Commons Zero license.

**Comment by Beep6581** [comment]
As discussed on IRC, due to underexposure and glare and uneven lighting these shots are not usable.
https://i.imgur.com/uEGxJLS.png
