### ISSUE TITLE
RT5 tarball: ReleaseInfo.cmake in wrong directory

### ISSUE THREAD

**Issue by innir** [Beep6581/RawTherapee#3622]
Hi,

in the RT5-gtk3 tarball the ReleaseInfo.cmake is located in rawtherapee-5.0-gtk3/ReleaseInfo.cmake but it should be in the root directory of the tarball. It's a bug in the script tools/generateSourceTarball (I can fix it later this week)

Could you please fix the tarball?

Thanks,
Philip

**Comment by innir** [comment]
BTW: Thanks for all your hard work- this is really a wonderful release you created!
And thanks for (hopefully) making it possible to enter Debian stretch!

**Comment by Beep6581** [comment]
Thank you for the report, we will fix the tarball and the script today.

**Comment by Beep6581** [comment]
The source tarballs are fixed.

**Comment by innir** [comment]
Thanks for the quick fix.

**Comment by Beep6581** [comment]
@Desmis @Floessie @heckflosse @Hombre57 @innir et al.

According to the manual, git tags shouldn't be checked out. I adapted the explanation to our case:

> You can’t really check out a tag in Git, since they can’t be moved around. If you want to put a version of your repository in your working directory that looks like a specific tag, you can create a new branch at a specific tag with `git checkout -b [branchname] [tagname]`:
```
$ git checkout -b master-5.0 5.0-gtk2
Switched to a new branch 'master-5.0'
```
> Of course if you do this and do a commit, your `master-5.0` branch will be slightly different than your `5.0-gtk2` tag since it will move forward with your new changes, so do be careful.

Assumptions:
- People will be making and using two types of builds: releases and nightly builds.
- Releases will always be tagged.
- Nightly builds will always have the latest tag and a hash.
- Builds could come from various branches - master, locallab, pixelshift, ...

About versions:
- The core git information we need is the commit hash someone is using. Using that we know everything.
- We also create a numeric version for other uses:
  - We show a version in AboutThisBuild.
  - We use an APPVERSION for PP3 file headers, example `4.2.1234` or `5.0`.
  - We show a version in the window title.
  - Any other places?

These numeric versions can be totally wrong and misleading! e.g. both `gtk3` and `locallab` can have version 4.2.1234, but each would be very different! So using that version in PP3s or in CSS themes is prone to fail.

As numeric versions are incapable of being accurate, it would be best if we stopped using them. We could use the tag instead when being vague is enough, and the commit hash when we need details. I believe we can always find the latest tag. Would that not be enough?

I don't yet know how to handle builds from other branches. i.e. should Ingo tag `pixelshift`, should Jacques tag `locallab`? If so, what should the tag look like? If a build was made using a commit from branch x and we would like to know this without examining the commit hash, using the branch name would be handy. But if you `git checkout <tag>` (which according to the manual is not correct) then you cannot easily find out which branch you're on, and I don't want to write a bash script which uses flaky regex to do that, which could fail if someone is using a different git version. So either we keep using branch names and get tags the way the manual says, or we drop branch names and use tags more often, or other?

**Comment by Beep6581** [comment]
Update: the wording in the manual is incorrect according to the git guys, so we can checkout a tag, nothing wrong with that, it will just be detached. There is still, however, no clean way to get the branch from a tag.

I'm thinking that it would be best if we stopped using unreliable numeric versions, but that would also be a big change which I bet nobody is eager to do, so we keep using branches and fix the generateReleaseInfo script to support git branches to verbosely fail if it cannot get the required info.
