### ISSUE TITLE
Blackmagic URSA 4K raw support

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3625]
Request from the [forum](https://discuss.pixls.us/t/cinemadng-raw-compatibility/3135) to add support for the Blackmagic URSA 4K DNG.
DNG: https://pixls-discuss.s3.amazonaws.com/original/2X/1/1b94dc4c32ca73036ea8f34dec97e7a04ce0fc8d.dng

**Comment by iliasg** [comment]
I think it's better to use 
`if (!strncmp(make,"Blackmagic", 10) tiff_bps = 16`

**Comment by heckflosse** [comment]
@iliasg I will try that :+1:

**Comment by heckflosse** [comment]
Should work now: 6a4f2cf
Ok to close?

**Comment by Thanatomanic** [comment]
Decodes fine, white levels may still be off, but that's a different issue. Closing.
