### ISSUE TITLE
Colour-target shots from Olympus e-m1 mark2

### ISSUE THREAD

**Issue by harshula** [Beep6581/RawTherapee#3630]
I've followed the instructions on:
http://rawpedia.rawtherapee.com/How_to_create_DCP_color_profiles#Shooting_the_color_target

and uploaded to:
https://filebin.net/nsvj1soupg77aono

the following files:
olympus-em1m2-daylight-P1250014.ORF
olympus-em1m2-tungsten-P1250026.ORF

They are licensed under CC0 license (https://creativecommons.org/about/cc0)

Please let me know if there are any problems with the images and you need me to retake them.

**Comment by Beep6581** [comment]
Tungsten was taken at f/2.8, that could be improved - don't go below f/5.6 (f/2.8 could be fine, of course it depends on the lens, but f/5.6 should be a safe minimum). If you happen to have time to re-shoot the tungsten shot before I add them in a few days, you could also push the exposure +0.8EV https://i.imgur.com/KoFYiBN.png

**Comment by iliasg** [comment]
Well Olympus is the quilty for this underexposure .. because of the overrated manufacturer ISO ..
A correction of 2/3 stops is fine ( log2(1.60) = 2/3)
![e-m1ii-tung](https://cloud.githubusercontent.com/assets/15012599/22315470/7e3a43c8-e36f-11e6-9ac0-34897c79ba46.png)
Although something strange happens here .. while the neutral grey patch is fine (51.8 vs the reference 50.9) the dark and white patches are low (18.8 vs 20.8 and 92.7 vs 96.5) .. 
This usually comes from lens vignette. But also there is a small probability to come from light fall off due to small distance of a point light source to the taget ..

**Comment by harshula** [comment]
@iliasg I was holding the light source about one meter away. Perhaps I need to use a tripod with a longer exposure and move the light source further away?

**Comment by iliasg** [comment]
1m is not that close and I suppose your lamp is not exactly a point source so less than 1% light falloff is expected (supposing the cc24 is 20cm long). But as I see your lens also has negligible vignette at f2.8 !! so it's something else .. mabe glare .. try with the target at an angle  ?.
In anyway a bigger distance from the lamp will help a bit, aperture at f4.0-f5.6 will also help .. so we need a tripod ;)

**Comment by Beep6581** [comment]
@iliasg good catch!

**Comment by harshula** [comment]
Take 2 ... changed the light bulb to a weaker one and used a tripod:
https://filebin.net/6je0zglh13zpck3g

**Comment by harshula** [comment]
@iliasg & @Beep6581: Is the second tungsten image above suitable?

**Comment by iliasg** [comment]
It is better .. a bit better exposure and a bit better homogenuity ..
![em1m2-tungsten2](https://cloud.githubusercontent.com/assets/15012599/22369939/8087e10c-e497-11e6-9c76-49d18fb8ef27.png)

**Comment by harshula** [comment]
Take 3 (tungsten)
* 75 watt light bulb ~2.4m distance from the colour chart
* https://filebin.net/c6n5tp1g0d3hyaom

* olympus-em1m2-tungsten-2-P1260046.ORF & olympus-em1m2-tungsten-3-P1280054.ORF are licensed under CC0 license (https://creativecommons.org/about/cc0)

@iliasg & @Beep6581: Will this one suffice?

**Comment by iliasg** [comment]
Looks better than before ..
![em1m2-tungsten3](https://cloud.githubusercontent.com/assets/15012599/22467645/1dfd21ca-e7ce-11e6-8b8a-29c0863aaa1a.png)
