### ISSUE TITLE
Colour-target shots from Panasonic GX85

### ISSUE THREAD

**Issue by harshula** [Beep6581/RawTherapee#3631]
I've followed the instructions on:
http://rawpedia.rawtherapee.com/How_to_create_DCP_color_profiles#Shooting_the_color_target

and uploaded to:
https://filebin.net/gfzt2dwrcibzw6qv

the following files:
panasonic-gx85-daylight-P1100383.RW2
panasonic-gx85-tungsten-P1100393.RW2

They are licensed under CC0 license (https://creativecommons.org/about/cc0)

I noticed that the white colour swatch under tungsten has a clipped red channel. Let me know if you need me to retake it.

**Comment by Beep6581** [comment]
@harshula thank you for the shots, I eyeballed them and they look fine. I'll add some in some days, I need a break.

**Comment by iliasg** [comment]
Same as with E-M1M2 we have a light fall off 
The exposure would be better at +1/3 stops 
![gx85-tung](https://cloud.githubusercontent.com/assets/15012599/22316107/83e75366-e373-11e6-92f7-ec00424704ed.png)

**Comment by harshula** [comment]
@iliasg I was holding the light source about one meter away. Perhaps I need to use a tripod with a longer exposure and move the light source further away?

**Comment by harshula** [comment]
Take 2 ... changed the light bulb to a weaker one and used a tripod:
https://filebin.net/1ck5u0af2tclfp28

**Comment by harshula** [comment]
@iliasg & @Beep6581: Is the second tungsten image above suitable?

**Comment by iliasg** [comment]
It is better and worse .. you made the perfect exposure but the fall off for the bright patch is more than tungsten-1
![gx85-tungsten2](https://cloud.githubusercontent.com/assets/15012599/22368963/e50d86d2-e491-11e6-834a-48a1c36fc410.png)

**Comment by harshula** [comment]
@iliasg The first light bulb I used was much stronger but, excluding the centre, it has a dimpled pattern on the glass. Is it plausible that tungsten-1 contains hot spots due to the dimples and not that tungsten-2 has worse fall-off? Can the daylight image be used as a cross-reference?

**Comment by iliasg** [comment]
Hmm .. maybe .. ideally we need a flat field to be able to compensate ..
For the moment measures on the background area show different lighting between the GX85 vs E-M1M2 shots !!
![gx85-tungsten2-ff](https://cloud.githubusercontent.com/assets/15012599/22375075/4d08dac4-e4b1-11e6-9520-5b7d03c84b3a.png)
![em1m2-tungsten2-ff](https://cloud.githubusercontent.com/assets/15012599/22375076/4d146678-e4b1-11e6-8c48-e121b160947c.png)

**Comment by harshula** [comment]
@iliasg The colour chart was at different distances from the light source for the E-M1M2 (~1.9m) and GX85 (~1.7m).

**Comment by harshula** [comment]
Take 3 (tungsten)
* 75 watt light bulb ~2.4m distance from the colour chart
* https://filebin.net/c1kq8w77qg15xcj0

* panasonic-gx85-tungsten-2-P1100401.RW2 & panasonic-gx85-tungsten-3-P1100411.RW2 are licensed under CC0 license (https://creativecommons.org/about/cc0)

@iliasg & @Beep6581: Will this one suffice?

**Comment by iliasg** [comment]
Looks better than before .. reference values are (left to right)
Babel avg of 30 samples -> 96.53-81.21-66.48-50.83-35.85-20.81
X-rite reference -> 96.54-81.26-66.77-50.87-35.66-20.46
I think it's OK ..
![gx85-tungsten3](https://cloud.githubusercontent.com/assets/15012599/22468528/3decf0ca-e7d1-11e6-97fa-0e28d2c95521.png)
