### ISSUE TITLE
Inconsistent gui when Wavelet Residual Image Compression strength is not zero

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#3634]
To reproduce:
apply this pp3 to amsterdam.pef
[tmvav.pp3.zip](https://github.com/Beep6581/RawTherapee/files/732193/tmvav.pp3.zip)

Now two adjusters in Tonemapping tool are disabled
![wavtm00](https://cloud.githubusercontent.com/assets/13733487/22330543/0a23ab3e-e3c7-11e6-8c0c-ed3aa555700e.png)

because Wavelet is enabled and `Wavelet Residual Image Compression strength` is not zero though `Residual image` is disabled.
![wavtm01](https://cloud.githubusercontent.com/assets/13733487/22330624/7a32a8e4-e3c7-11e6-8354-2b2f307f3056.png)

Now disable Wavelet tool and look at tonemapping tool.
![wavtm00](https://cloud.githubusercontent.com/assets/13733487/22330692/cc9c58e6-e3c7-11e6-96a9-ae1cbe8225c9.png)
Adjusters are still disabled.

Now reload the image and look at tonemapping tool
![wavtm02](https://cloud.githubusercontent.com/assets/13733487/22330761/1d2e8cac-e3c8-11e6-8cc3-f4e083c991a8.png)
Strength adjuster is enabled.

Now again enable Wavelet tool but set `Wavelet Residual Image Compression strength` to zero
![wavtm03](https://cloud.githubusercontent.com/assets/13733487/22330828/764f4baa-e3c8-11e6-8229-11db8997451f.png)

Look at tonemapping tool
![wavtm04](https://cloud.githubusercontent.com/assets/13733487/22330926/f0fdef32-e3c8-11e6-9b51-40a4478d7b3a.png)
Strength and gamma adjuster are disabled

Reload the image and look at tonemapping tool
![wavtm05](https://cloud.githubusercontent.com/assets/13733487/22330975/2d02f3ce-e3c9-11e6-9266-7002c55e9c0c.png)
Now Strength and gamma adjuster are enabled.

I don't understand that

**Comment by Beep6581** [comment]
Reproduced.

**Comment by Lawrence37** [comment]
Tone Mapping Strength and Gamma are always active in `dev`, so closing this issue.
