### ISSUE TITLE
Large fonts in RT 5 after second start with GTK 3.20

### ISSUE THREAD

**Issue by mc6312** [Beep6581/RawTherapee#3637]
Running on Ubuntu 16.10, GTK 3.20.
First run (~/.config/RawTherapee/options file is missing) - GUI fonts has normal size.
Second run - GUI fonts are large.
Running on Fedora 25, GTK 3.22 - font size always normal.

I found this code in rtgui/preferences.cc, line 2236:

#if GTK_MAJOR_VERSION == 3 && GTK_MINOR_VERSION < 20

May be instead of "<" should be "<="?

**Comment by Stiouxk** [comment]
Thanks, I was also having this problem (Ubuntu 16.10, GTK 3.20). After changing this, and also a similar line in rtgui/main.cc, around line 342, my font sizes are now normal.
