### ISSUE TITLE
DEBUG message "... installation is broken" RT5 Gtk3.22

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#3638]
Getting these errors when I run RT5 debug Gtk3.22 but RT is running without any problems.
```

(rawtherapee.exe:3616): GdkPixbuf-[1;33mWARNING[0m **: Cannot open pixbuf loader module file 'C:\Program Files\RawTherapee 5.0 DEBUG\lib\gdk-pixbuf-2.0\2.10.0\loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > C:\Program Files\RawTherapee 5.0 DEBUG\lib\gdk-pixbuf-2.0\2.10.0\loaders.cache
to make things work again for the time being.

(rawtherapee.exe:3616): Gtk-[1;33mWARNING[0m **: Could not load a pixbuf from /org/gtk/libgtk/theme/Adwaita/assets/check-symbolic.svg.
This may indicate that pixbuf loaders or the mime database could not be found.
```

```
Branch: gtk3
Version: 5.0
Changeset: 7fe7c4f60f85b47bc1d24b2cfece43444028e3a6
Compiler: gcc 6.3.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.22.0
Build type: debug
Build flags:  -m64 -mwin32 -mthreads -std=gnu++11 -Werror=unused-label -Werror=unknown-pragmas -Wno-aggressive-loop-optimizations -std=gnu++11 -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -O1 -g2
Link flags: -m64 -mthreads  -static-libgcc   -mtune=generic -O1
OpenMP support: ON
MMAP support: ON
```

**Comment by Beep6581** [comment]
Self-compiled?

**Comment by TooWaBoo** [comment]
No, downloaded from @Gaaned92: https://drive.google.com/drive/folders/0B2q9OrgyDEfPS2FpdDAtMVI1RG8

**Comment by Beep6581** [comment]
@TooWaBoo does that only happen with debug, or also release?
Can anyone else reproduce?

@gaaned92 if that happens in release, would be great if this could be fixed for `5.0-r1-gtk3`.

**Comment by TooWaBoo** [comment]
I can't test if this happens with the release version too. Debug and release run fine. Prior version 5 (Gtk3.22 Nightly builds), I only got the last error message with the debug version.

**Comment by TooWaBoo** [comment]
@gaaned92
I've tried your build "RawTherapee_gtk3_5.0-gtk3-27-g50114c1a_WinVista_64.zip" from your Google drive.
The path to the pixbuf-loader is wrong:
```
it's:
lib\2.10.0\...

should be:
lib\gdk-pixbuf-2.0\2.10.0\...
```

**Comment by gaaned92** [comment]
@Beep6581 I made a post on this subject not long ago, as I get the message in verbose mode. Nobody seemed worried. Sorry, I cannot find it.
@TooWaBoo  Thank you for the notice. I correct and rebuild.

**Comment by gaaned92** [comment]
With path correction, the first warning `...Cannot open pixbuf loader module file... ` disappears.
But two  warnings remain:

```
(rawtherapee.exe:16884): Gdk-[1;33mWARNING[0m **: Failed to load cursor theme Adwaita
```
In the RT builds I make, cursors are located in ".../ share/icons/Adwaita/cursors" .

and
```
(rawtherapee.exe:16884): Gtk-[1;33mWARNING[0m **: Could not load a pixbuf from /org/gtk/libgtk/theme/Adwaita/assets/check-symbolic.svg.
This may indicate that pixbuf loaders or the mime database could not be found.
```
@Hombre57 is already  aware of this warning.

But these two warnings seem innocuous and  as @TooWaBoo  said, Rawtherapee runs without problem.

**Comment by TooWaBoo** [comment]
@Beep6581 , @Hombre57 , @gaaned92 , @Partha1b

After copying the dll below to RT, RT is runnung without any error message **and** it shows the missing arrows
on @partha's RT portable. Looks like the pixbuf-loader can not run without these dlls.
```
libcroco-0.6-3.dll
librsvg-2-2.dll
libxml2-2.dll
```

**Comment by Beep6581** [comment]
@TooWaBoo great, I hope this fix makes its way into the 5.0-r1 builds @gaaned92 @sguyader @Partha1b

Would be great if the Windows installers included both a `rawtherapee.exe` and a `rawtherapee-debug.exe` with `gdb.exe`. We need a 32-bit GTK2 installer for Windows XP and a 64-bit GTK3 installer for WinVista.

**Comment by Partha1b** [comment]
@Beep6581 , @TooWaBoo Yes, it will make to my build

**Comment by Beep6581** [comment]
@gaaned92 I see two identically named builds in https://drive.google.com/drive/folders/0B2q9OrgyDEfPS2FpdDAtMVI1RG8
"RawTherapee_5.0-r1-gtk3_WinVista_64.zip"
One is 20MB and the other 40MB. Does the 40MB one contain release+debug? If not, could you please @ping me when a r+d WinVista 64-bit GTK3 one is available?

Could you also please @ping me when a 32-bit Windows XP GTK2 build is ready?

**Comment by gaaned92** [comment]
@Beep6581  , @TooWaBoo  Ok, already included. 
GTK2 and GTK3 W64 builds with included debug uploaded
for 32 bits GTK2 and GTK3 uploaded within half hour.
edit : uploaded
Note: There are still a lot of windows 32 bit users (vista and above) that can use GTK3 builds.

**Comment by Beep6581** [comment]
@gaaned92 could you please point me to the following as I can't tell by the filename which ones have release+debug+gdb:
- GTK2 32-bit WinXP
- GTK3 64-bit WinVista

**Comment by gaaned92** [comment]
@Beep6581  Sorry to be unclear. From now, all new builds will contain in the exe installer:

- rawtherapee.exe launched by default,
-  gdb.exe 
- and rawtherapee_debug.exe

These are:

- RawTherapee_5.0-r1-gtk2_WinVista_64.zip
- RawTherapee_5.0-r1-gtk3_WinVista_64.zip
- RawTherapee_5.0-r1-gtk2_WinXP_32.zip
- RawTherapee_5.0-r1-gtk3_WinXP_32.zip


@TooWaBoo  only one warning remains
`Gdk-[1;33mWARNING[0m **: Failed to load cursor theme Adwaita`
I am curious to know how you found the 3 missing dll
André

**Comment by TooWaBoo** [comment]
@gaaned92 
I don't get the cursor error and I did a clean install of your installation file.

> I am curious to know how you found the 3 missing dll

Yesterday, I've tried to compile RT myself. At the step, where to copy the dll, I've copied all and recognized, that the error messages are gone. Then I've removed the dlls one by one until the errors appear again.

**Comment by Beep6581** [comment]
Thank you, builds uploaded. I verified that the Windows XP builds includes a debug file, but I could not verify the 64-bit one. In fact someone on IRC said that it didn't have a debug exe. Could someone please verify that "RT 5.0-r1-gtk3" available from http://rawtherapee.com/downloads/ includes a debug exe?

**Comment by Beep6581** [comment]
As for this issue, please update http://rawpedia.rawtherapee.com/Windows or tell me what to add, if anything.

**Comment by TooWaBoo** [comment]
@Beep6581 
This is the list of DLLs, which is installed by @gaaned92 for WIN x64 Gtk3.22

```
libatk-1.0-0.dll
libatkmm-1.6-1.dll
libsz-1.dll
libcairo-2.dll
libcairo-gobject-2.dll
libcairomm-1.0-1.dll
libcroco-0.6-3.dll
libepoxy-0.dll
libexpat-1.dll
libfﬁ-6.dll
libfftw3f-3.dll
libfontconﬁg-1.dll
libfreetype-6.dll
libgcc_s_seh-1.dll
libgdk_pixbuf-2.0-0.dll
libgdk-3-0.dll
libgdkmm-3.0-1.dll
libgio-2.0-0.dll
libgiomm-2.4-1.dll
libglib-2.0-0.dll
libglibmm-2.4-1.dll
libgmodule-2.0-0.dll
libgobject-2.0-0.dll
libgomp-1.dll
libgraphite2.dll
libgtk-3-0.dll
libgtkmm-3.0-1.dll
libharfbuzz-0.dll
libiconv-2.dll
libintl-8.dll
libjpeg-8.dll
liblcms2-2.dll
liblzma-5.dll
libpango-1.0-0.dll
libpangocairo-1.0-0.dll
libpangoft2-1.0-0.dll
libpangomm-1.4-1.dll
libpangowin32-1.0-0.dll
libpcre-1.dll
libpixman-1-0.dll
libpng16-16.dll
librsvg-2-2.dll
libsigc-2.0-0.dll
libstdc++-6.dll
libtiff-5.dll
libwinpthread-1.dll
libxml2-2.dll
zlib1.dll
```

**Comment by TooWaBoo** [comment]
> @Beep6581 
> In fact someone on IRC said that it didn't have a debug exe.

It contains a rawtherapee_debug.exe

**Comment by Beep6581** [comment]
@TooWaBoo thank you, RawPedia updated. And thank you for the confirmation that it includes _debug.exe.

Can we close this issue?

**Comment by TooWaBoo** [comment]
> Can we close this issue?

I think so.

**Comment by TooWaBoo** [comment]
@Beep6581 The following line has to be add to the compiling instruction too.

```
<prefix>\lib\gdk-pixbuf-2.0 -> .\lib\gdk-pixbuf-2.0
```

> The following files also need to be copied: 
> ```
> <prefix>\bin\gspawn-<win32|win64>-helper.exe -> .
> <prefix>\bin\gspawn-<win32|win64>-helper-console.exe -> .
> 
> <prefix>\lib\gtk-2.0\include -> .
> <prefix>\lib\gtk-2.0\modules -> .
> <prefix>\lib\gtk-2.0\2.10.0\engines -> .
> 
> <prefix>\share\glib-2.0\schemas\gschemas.compiled -> .\share\glib-2.0\schemas
> ```

btw: I didn't find anything from `<prefix>\lib\gtk-2.0\...` in the current installation from @gaaned92 
I don't know, if they are needed or not.

**Comment by Partha1b** [comment]
@TooWaBoo where is gspawn used in the code? I don't think it's used anymore.

As for gtk-2.0/2.10.0 modules or gtk-3.0/3,0.0, you only need them if you use them.

**Comment by TooWaBoo** [comment]
@Partha1b 

> @TooWaBoo where is gspawn used in the code? I don't think it's used anymore.

I'm not sure, but I think they are needed for a DEBUG version.

**Comment by Partha1b** [comment]
@TooWaBoo gspawn is used to spawn an external program in a given environment. 

So for Linux and Apple we use GLib::spawn_command_line to run an external command. On Windows we're using ShellExecute. So, the helper files are not needed anymore. 

Someone correct me here if I am wrong here.

**Comment by TooWaBoo** [comment]
@Partha1b 

I've tested it and removed the ...helper.exe. It's not needed for DEBUG, but it's needed for e.g. to launch an external program for the custom processing profile builder.

I'm using this Addon for RT: https://github.com/marcapelini/RTProfileSelector/releases
btw: This should be advertised in the forum, it's really helpfull.

**Comment by Partha1b** [comment]
@TooWaBoo Ahh OK. So, this is a third-part addon? Should the helper files not be included with that plugin?

**Comment by TooWaBoo** [comment]
@Partha1b 

I don't think so. This is the way how RT launches these external programs. It has nothing todo with the addon itself - I guess.

**Comment by Beep6581** [comment]
@TooWaBoo I added the line, http://rawpedia.rawtherapee.com/Windows#Copy_RawTherapee_and_required_DLLs
