### ISSUE TITLE
Allow the use of relative paths for film simulation CLUTs

### ISSUE THREAD

**Issue by agriggio** [Beep6581/RawTherapee#3639]
Currently RawTherapee stores the full path to film simulation CLUTs in the generated pp3 sidecars.
This patch adds support for using paths relative to the user's HaldCLUT directory, making sharing pp3 files easier.
[relative-clut.patch.txt](https://github.com/Beep6581/RawTherapee/files/735930/relative-clut.patch.txt)

**Comment by Floessie** [comment]
@Beep6581 Would you mind to test Alberto's patch? I'd push it afterwards.

**Comment by heckflosse** [comment]
@Floessie I will also test the patch today

**Comment by Floessie** [comment]
@heckflosse Thanks! Much appreciated, Ingo! :+1:

**Comment by heckflosse** [comment]
@agriggio @Floessie 
I just tested the patch on Win7/64. It works when you select a clut which is in top clut folder but not when you select a clut which is in one of the subfolders (`Black-and-White/Agfa` for example).

**Comment by agriggio** [comment]
Thanks for the review. I'll fix it and resubmit then. (I have to admit, I only use top-level cluts so I never tested with subfolders... :-/)

**Comment by agriggio** [comment]
[relative-clut.patch.txt](https://github.com/Beep6581/RawTherapee/files/774557/relative-clut.patch.txt)
New version of the patch. It should work also with subfolders now

**Comment by heckflosse** [comment]
@agriggio New patch works fine. Thank you! :+1: for push @Floessie

**Comment by Floessie** [comment]
Pushed to `dev`.
