### ISSUE TITLE
NIKON COOLPIX B700 raw file support

### ISSUE THREAD

**Issue by rpittaro** [Beep6581/RawTherapee#3640]
Bug Report

RawTherapee  Version 5.0-GTK3
Intel XEON CPU E3-1230 3.3GHz
Windows 10 64 bit
Downloaded from http://rawtherapee.com/downloads
RT 5.0 for Windows Vista/7/8/10 64-bit – fast
RawTherapee won’t demosaic an NRW file from a Nikon  B700   properly regardless of the type of demosaicing  selected. The image looks as expected when demosaicing is set to “none”. I’m fairly sure the software is installed properly because it works fine with test NRW files I downloaded from the web (files are from other types of Nikon cameras . I don’t believe there is anything wrong with the files because ViewNX-I and NX-D.

![2017-01-28](https://cloud.githubusercontent.com/assets/25400318/22395786/f58fec3c-e4fc-11e6-8a1e-2ab57387e969.png)

**Comment by Beep6581** [comment]
@rpittaro please upload that raw file for us using http://filebin.net/

**Comment by rpittaro** [comment]
Here is a sample file from a Nikon B700 that does't Demosaic properly
filebin.net/64ja3ohfy2ivwrar

**Comment by Beep6581** [comment]
The NIKON COOLPIX B700 is not supported by dcraw yet. RawTherapee will support it once dcraw supports it.

**Comment by rpittaro** [comment]
Thanks for your prompt response
Rick
