### ISSUE TITLE
Mistyped labels in preferences (English)

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#3644]
![unbenannt](https://cloud.githubusercontent.com/assets/13800920/22418880/32aa4a4c-e6db-11e6-87ca-03d06783bf24.png)

**Comment by Floessie** [comment]
@TooWaBoo For what reason ever, there is a [strict refusal](https://github.com/Beep6581/RawTherapee/pull/3430) to change "copypasta" to something sensible. Maybe because some veterans feel sentimental about that old pun. :grin:

**Comment by TooWaBoo** [comment]
@Floessie 

I've found this yesterday when I made pasta. A friend was visiting me and ask me if he can have some pasta too. I said: "Sure, I've an application which can copy pasta." So I run RT, clicked on the copypasta button, but no pasta came out of the printer. I've moved the buttons from left to right, but still no luck. This should be fixed and I suggest to add a copybeer button to the curves. 😁

**Comment by Floessie** [comment]
@TooWaBoo 
> and I suggest to add also a copybeer button to the curves.

**That** would be really helpful! Perhaps you could turn it into a dropdown, so that we can also select "copywhiskey", "copychampagne", and "copywine". I know, *you* can do it with some crazy CSS. :+1:

**Comment by heckflosse** [comment]
:+1: for "copywhiskey" and so on if they work.

**Comment by TooWaBoo** [comment]
@heckflosse 

> ... if they work.

That's your job.  ![3eaef0526bbb8f4d4bc01429a9548521](https://cloud.githubusercontent.com/assets/13800920/22440311/30fc5336-e733-11e6-953f-30b671c74846.png)

**Comment by Beep6581** [comment]
Neither of those are typos. Proper nouns such as the name of a frame are capitalized, and copypasta is delicious.
