### ISSUE TITLE
IPTC metadata is not written to the output files of any format

### ISSUE THREAD

**Issue by geoderix** [Beep6581/RawTherapee#3645]
IPTC metadata is not written to the output files of any format (jpeg, tiff or png, 8-bit or 16 bit). All fields of IPTC are empty in the output file.

RT 5.0 for Windows Vista/7/8/10 64-bit - fast, gtk3, from http://rawtherapee.com/downloads.

Any input files (raw, jpeg, tiff or png, 8-bit or 16 bit).

**Comment by Beep6581** [comment]
Disable "Preferences > Image Processing > Metadata > Copy Exif/IPTC/XMP unchanged to the output file".

**Comment by geoderix** [comment]
It is difficult to find so disguised settings. Thank you.

**Comment by Beep6581** [comment]
I agree - see #3647.
