### ISSUE TITLE
Release RawTherapee 5.0-r1

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3649]
I would like to release 5.0-r1, tagged `5.0-r1-gtk2` and `5.0-r1-gtk3` within the next two days.
It will be a revision - nothing new, just fixes some compilation and versioning issues and a missing theme.

https://github.com/Beep6581/RawTherapee/pull/3635 makes changes which could require a few weeks of testing, so I think it's better if that goes into 5.1.

To be done is to re-instate TooWaBlue v1.94 for GTK+ <=3.18.
https://discuss.pixls.us/t/rawtherapee-5-released-congrats-to-the-team/3133/47?u=morgan_hardwood
Hopefully just a revert+rename of https://github.com/Beep6581/RawTherapee/commit/9f811772a96b905541b0f051cd15e8564e7285fc

If you have anything else to add into this revision, speak now.

@gaaned92 @sguyader @Partha1b please test `master` if you're building for XP and `gtk3` if you're not, check that AboutThisBuild.txt has correct info.

**Comment by Partha1b** [comment]
@Beep6581 Is it ready for testing/building now?

**Comment by Floessie** [comment]
@Beep6581 
> #3635 makes changes which could require a few weeks of testing, so I think it's better if that goes into 5.1.

Definitely! I'm still ambivalent if the change is worth the impact it has. When I've ported it over to a new `development` derived branch we can test and discuss it further in #3635.

**Comment by Beep6581** [comment]
@Partha1b yes it is. I will ask for a new build when 5.0-r1 is tagged, so don't spend time polishing this - it's just to test.

@Floessie glad to hear that.

**Comment by Beep6581** [comment]
@TooWaBoo's missing TooWaBlue theme for <=GTK+ 3.18 is fixed.

**Comment by TooWaBoo** [comment]
@Beep6581 
Please update https://github.com/Beep6581/RawTherapee/issues/3651 in the Gtk3 branch too.

**Comment by Beep6581** [comment]
@TooWaBoo thanks, committed.
