### ISSUE TITLE
Fails to build with gcc 7

### ISSUE THREAD

**Issue by innir** [Beep6581/RawTherapee#3652]
Hi,

this is nothing with high priority at the moment but as I got a bug report, I'll forward it to you:

> The package fails to build in a test rebuild on at least amd64 with
gcc-7/g++-7, but succeeds to build with gcc-6/g++-6. The
severity of this report may be raised before the buster release.
There is no need to fix this issue in time for the stretch release.

> The full build log can be found at:
http://people.debian.org/~doko/logs/gcc7-20170126/rawtherapee_5.0-1_unstable_gcc7.log
The last lines of the build log are at the end of this report.

>To build with GCC 7, either set CC=gcc-7 CXX=g++-7 explicitly,
or install the gcc, g++, gfortran, ... packages from experimental.

>  apt-get -t=experimental install g++ 

> Common build failures are new warnings resulting in build failures with
-Werror turned on, or new/dropped symbols in Debian symbols files.
For other C/C++ related build failures see the porting guide at
http://gcc.gnu.org/gcc-7/porting_to.html

The corresponding bug in Debian is: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=853637

Best,
Philip

**Comment by Floessie** [comment]
... The ever recurring `abs()` problem.

@Partha1b @heckflosse I had the impression that was fixed, because it also appeared on macOS with Clang. Does anyone remember, where the patch (and discussion) got lost? I'm getting old...

**Comment by Floessie** [comment]
Got it: It's in [#3339](https://github.com/Beep6581/RawTherapee/issues/3339#issuecomment-268975964).

@Beep6581 If @heckflosse is okay with the patch, it should go into `5.0-r1`.

**Comment by Beep6581** [comment]
@Floessie fine with me. Could you commit (into master)?

**Comment by Floessie** [comment]
@Beep6581 I'll do so tonight. I'll also update `dcraw.patch`.

**Comment by Beep6581** [comment]
@Floessie have a word with @heckflosse about that - I think the latest agreement was to only update the patch when a new dcraw comes around.

**Comment by heckflosse** [comment]
@Floessie @Beep6581 Yes, only new dcraw.patch when a new dcraw comes around.

**Comment by Floessie** [comment]
Even better. :smile:

**Comment by Floessie** [comment]
Should be fixed now. Maybe there are other places which fail with GCC 7, but I can only take care of them when I've got an GCC 7 installation at hand.

@innir Philip, thanks for forwarding from the BTS!
