### ISSUE TITLE
Incorrect determination of the focal length for Pentax cameras

### ISSUE THREAD

**Issue by geoderix** [Beep6581/RawTherapee#3654]
For many PENTAX cameras (I do not know about the cameras of other manufacturers) RawTherapee often incorrectly determines the focal length:

I had a camera PENTAX K100D Super. With lens smc PENTAX-DA 18-55mm F3.5-5.6 AL, regardless of the real focal RawTherapee always shows the focal length of 250 mm (for jpeg or pef):
https://filebin.net/waeow8wdkd1ui8do
https://filebin.net/ftj5fk8iprdqj66s

For PENTAX K100D Super +  smc PENTAX-DA 40mm F2.8 Limited RawTherapee always determines 16,25 mm focal lenght:
https://filebin.net/a6g0f7t2tw0v8u63

For PENTAX K100D Super + smc PENTAX-FA 50mm F1.4 RawTherapee always determines 60 mm focal lenght:
https://filebin.net/u1jdzovum5zhml0h

For other PENTAX cameras (images taken from www.photographyblog.com):

PENTAX 645Z	+  smc PENTAX-D FA 645 55mm F2.8 AL [IF] SDM AW for dng determines 17,50 mm focal lenght:
https://filebin.net/abawxuor69qu830h

PENTAX K200D + smc PENTAX-DA 18-55mm F3.5-5.6 AL II RawTherapee  determines 620 mm focal lenght:
https://filebin.net/0zr2behffb5qgi35

If you have time and desire the list goes on.

The values in EXIF "Focal Length", "SR Focal Length", "Focal Length In 35mm Format "  fields for all of the above files are correct. I do not know how to read and write the code, so I can only guess where RawTherapee taking focal length.

RT 5.0 for Windows Vista/7/8/10 64-bit - fast, gtk3, from http://rawtherapee.com/downloads.

P.S. If you take the pef file (RawTherapee shows the correct focal length - 35 mm) and with the default settings save it in jpeg, then, the focal length of the jpeg file miraculously changed to 6.25 mm (RawTherapee opinion):
source pef: https://filebin.net/c4vik7aivqt8xbqj
destination jpeg: https://filebin.net/hd26vwl28utcp0fd

Thank you for attention!

**Comment by Beep6581** [comment]
@geoderix thank you for the report and sample files. I will take a look when updating our lens database for RawTherapee 5.1.

**Comment by Beep6581** [comment]
@geoderix any chance you could upload the raw files again into one filebin?

**Comment by Beep6581** [comment]
Reproduced using http://img.photographyblog.com/reviews/pentax_645z/sample_images/pentax_645z_26.dng
```
-TIFF-IFD0-ExifIFD:FocalLength=55.0 mm                                                                                                                                                                                                                                         
-TIFF-IFD0-MakerNotes:FocalLength=55.0 mm 
-Composite:FocalLength35efl=55.0 mm (35 mm equivalent: 43.0 mm)
```
RT shows 20.00mm

**Comment by heckflosse** [comment]
@Beep6581 Link gives 403

**Comment by geoderix** [comment]
If someone seriously intends to fix this bug and you confirm it, I'll try to repeat the links. Otherwise, I'm sorry to waste time on useless work.

By the way, why would you recommend filebin.net if the bugs do not fix for years, and the files there are deleted after three months? Personal interest?

**Comment by Beep6581** [comment]
Ah, then you will need to look for that image from this page:
http://www.photographyblog.com/reviews/pentax_645z_review/sample_images/
Mirror: https://filebin.net/gt5zfqlhr1gqgtff

**Comment by heckflosse** [comment]
@geoderix 

> If someone seriously intends to fix this bug and you confirm it, I'll try to repeat the links.

I started work on this!

**Comment by geoderix** [comment]
Really? Confirm that this is not a joke and I will tense up.

**Comment by heckflosse** [comment]
Confirmed. I'm already trying to fix the case for the 645z file linked above.

**Comment by geoderix** [comment]
Ok!

**Comment by heckflosse** [comment]
And @Hombre57 is also working at it :)

**Comment by Hombre57** [comment]
I have a K100D PEF file here and the focal length is correct. I'll test a K100D Super raw image now ( http://www.imaging-resource.com/PRODS/K100DS/K100DShSLI0400.PEF.HTM ).

The 645Z have unknown LensData informations, and @heckflosse have found a way to get the focal length from the Exif section, not from the MakeNotes.

**Comment by geoderix** [comment]
[Here](https://gofile.io/?c=qvfGLK) is the 7z archive with the files with incorrect determined focal lenght in Rawtherapee for Penta[ K100D Super, K200D, 645z and files with  miraculously changed focal length when converting from raw to jpeg. Attention! File size is 1,3 Gb. Expired date - 31/12/2017.

**Comment by heckflosse** [comment]
@geoderix Thanks! Already started download.

**Comment by heckflosse** [comment]
@geoderix We fixed the issues with K100D Super, K200D and 645Z files.

I tried to reproduce the issue with the jpeg files but could not reproduce it.
I converted the k70 and the ks2 file to jpeg using rt and the jpegs show the same focal length as the raws

**Comment by geoderix** [comment]
Thank you! Thank you! Thank you!
Have you tried already on the bugfixed version? I use stable 5.0-r1-gtk (win64).
Just converted pentax_ks2_03.pef (18 mm) and get jpg with 130 mm focal lenght (according to Rawtherapee).
https://filebin.net/b8f3hapg98pxa7y1

**Comment by heckflosse** [comment]
@geoderix For the jpeg problem I only tried with the fixed version and I can confirm that pentax_ks2_03.pef (18 mm) has also 18 mm in the freshly generated jpeg.

**Comment by geoderix** [comment]
It's just fine. Where can I get the fixed version?

**Comment by heckflosse** [comment]
@geoderix If you're on windows you have to wait some days for a new build. I don't make builds, I only code and make builds for my machine. I'll inform you here as soon as I know a new build is available.

**Comment by geoderix** [comment]
Ok! Thank you! I'm happy!

**Comment by heckflosse** [comment]
@geoderix Before I forget to mention it: When a new build is available you have to 'Clear all' in Preferences/File Browser once, because the focal length information for the thumbs is also stored in the cache files. If you don't, you will still see the wrong focal length for thumbs you opened with previous version of rt.

**Comment by heckflosse** [comment]
Issue stays open until a new Windows build is available and @geoderix confirmed the fixes.

**Comment by geoderix** [comment]
I looked in https://discuss.pixls.us/t/download-rawtherapee-development-builds/2924 and I went to https://drive.google.com/drive/folders/0B2q9OrgyDEfPOEZmVlBzLWlnSWc. There I see RawTherapee_dev_5.0-r1-gtk3-446-g931db7ab_WinXP_32.zip added 17.04.2017 at 11:14. I downloaded it and saw changelog:

`Fix wrong focal length for Pentax K200D, as reported in #3654`

`commit 34be802c928802cdee77347a3f89c64ff8c2b253`
`Author: heckflosse <heckflosse67@gmx.de>`
`Date:   Sun Apr 16 23:04:32 2017 +0200`

   `Fix wrong focal length for Pentax 645Z and Pentax K100D Super, as reported in #3654`

`commit 2c9c3b2a7f876648d45b6cd55528380885c38c37`
`Author: Morgan Hardwood <bugs@londonlight.org>`
`Date:   Sun Apr 16 18:52:26 2017 +0200`

Ok! I uninstalled RawTherapee 5.0-r1 and installed RawTherapee_dev_5.0-r1-gtk3-446-g931db7ab_WinXP_32 on my old office laptop with Windows XP SP3.

**Comment by Beep6581** [comment]
@geoderix what are you saying? Do you confirm it's fixed?

**Comment by geoderix** [comment]
I could not start RawTherapee_dev_5.0-r1-gtk3-446-g931db7ab_WinXP_32 on Windows XP SP3 - I got a message: ""This application failed to start because dwmapi.dll was not found. Re-installing the application may fix this problem." 

Ok. I uninstall and install  RawTherapee_dev_5.0-r1-gtk3-446-g931db7ab_WinXP_32. And no effect - I got a message: ""This application failed to start because dwmapi.dll was not found. Re-installing the application may fix this problem." 

I understand that RawTherapee_dev_5.0-r1-gtk3-446-g931db7ab_WinXP_32 is defective build? How to report this to the compiler (Edmond Gautier)?

Later at evenining I will try RawTherapee_dev_5.0-r1-gtk3-446-g931db7ab_WinVista_64. Maybe it will work.

Sorry for the torn post and randomly pressed keys to close-open the bug.

Bug fixes have not been verified yet.

**Comment by Beep6581** [comment]
@geoderix the build is made by @gaaned92 , hopefully he sees this.

**Comment by geoderix** [comment]
It would be nice :)

**Comment by gaaned92** [comment]
@geoderix The new versions of Rawtherapee are based on GTK3 (instead of GTK2 for legacy versions).
Unfortunately, GTK3 requires on Windows systems the Display Window Manager (DWM) that was implemented by MS on Vista and above. So the missing DWMAPI.dll warning on XP and there is nothing to do.
 @Beep6581 In update info.cmake line 95, I think that from now, as gtk3 is the only gui tool, "WinXP" should be replaced by "WinVista" to avoid to confuse the last XP users.

**Comment by heckflosse** [comment]
@gaaned92 

> In update info.cmake line 95, I think that from now, as gtk3 is the only gui tool, "WinXP" should be replaced by "WinVista" to avoid to confuse the last XP users.

Agreed. Will change that in a few minutes.

**Comment by heckflosse** [comment]
@gaaned92 Pushed.

**Comment by geoderix** [comment]
@gaaned92 
 
```
The new versions of Rawtherapee are based on GTK3 (instead of GTK2 for legacy versions).
Unfortunately, GTK3 requires on Windows systems the Display Window Manager (DWM) that was implemented by MS on Vista and above. So the missing DWMAPI.dll warning on XP and there is nothing to do.
```

It is bad news. Such news looks even worse because such things need to be warned in advance. If you, of course, have any respect for users. But, it seems, this is not so, unfortunately.

**Comment by geoderix** [comment]
I installed the version of RawTherapee_dev_5.0-r1-gtk3-446-g931db7ab_WinVista_64. For Pentax K100D, K200D, 645Z the focal length is determined correctly. After converting to jpeg - also correct, except for 18.12 mm -> 18 mm. Adobe profiles (.lсp) for correction of distortion and vignetting work (hurray!).
Thank you.
But the files converted in the previous version (without the bugs fixed) continue to show strange values: 6.25 mm instead of 18 mm and 35 mm See links. https://filebin.net/0r1lwv6ympal3gus
I'm confused - should I close or not close the bug in this situation?

**Comment by heckflosse** [comment]
@geoderix 
That was not the decision of @gaaned92. Blaming him for that is absolutely wrong.
At some point we (the rt team) decided to not support gtk2 anymore and use only gtk3 for now.
Unfortunately that means WindowsXP users can't use the gtk3 builds. But MS support for XP was stopped 3 years ago already. @gaaned92 made RT builds for XP up to end of last year which is more than 2 years longer as MS supported XP!

If I would be @gaaned92 I would expect an apology from you about being blamed not to have any respect for users!

Ingo

**Comment by heckflosse** [comment]
@geoderix 
About the files converted with previous versions of RT: We can't fix the wrong exif data in this files posthumous in rt:(

Though you can fix the wrong data in the jpegs using exiftool or exiv2 if it's important. But others know more about usage of this tools than I do.

Ingo

Edit:

> should I close or not close the bug in this situation

As we can't fix the wrong exif in files which are saved in previous rt versions, it should be safe to close the issue. Thanks for testing the Win64 build and giving feedback :+1:

**Comment by geoderix** [comment]
I am sorry!
I meant no offense. I wrote something that is visible from the user's side. If you make such a decision, then you should not report it after it happened and with such intonation. People used the program, wrote bugs, and made plans. Maybe they should have warned them in advance? And not the way @gaaned92 did it. Nothing personal.
Excuse me.

**Comment by geoderix** [comment]
@heckflosse 
Nothing can be done - I close the bug.
Thank you.

**Comment by gaaned92** [comment]
@geoderix should you had made the effort to read the readme.rtf, you had solved the XP warning by yourself. I don't have any intonation, it is only facts. 
And don't be rude when you post.

**Comment by geoderix** [comment]
@gaaned92 
I also stated only the facts. I downloaded the version for Windows XP, it does not work. After that, you remembered that it was not for Windows XP and called me the last user of Windows XP. Why do you call me rude?
Best regards!

**Comment by heckflosse** [comment]
@geoderix 

With all respect, this one was rude:

> If you, of course, have any respect for users. But, it seems, this is not so, unfortunately.

**Comment by patdavid** [comment]
@geoderix 

> It is bad news. Such news looks even worse because such things need to be warned in advance. If you, of course, have any respect for users. But, it seems, this is not so, unfortunately.

You were warned in advance over _three years ago_ when your outdated OS stopped being supported.

Your intimation that the devs of this Free Software project didn't care about users was uncalled for.

**Comment by geoderix** [comment]
@heckflosse 

`With all respect, this one was rude:`

 `  If you, of course, have any respect for users. But, it seems, this is not so, unfortunately.`

With all respect, but this is what the ordinary user looks like.

**Comment by geoderix** [comment]
@patdavid
`You were warned in advance over three years ago when your outdated OS stopped by being supported.`

And I was warned again with release RawTherapee  RT 5.0-r1-gtk2 for Windows XP or newer 32-bit at 2017-02-04 11:00. Correct reasoning?

**Comment by heckflosse** [comment]
@geoderix So you say the ordinary user (whatever that means) thinks the rt developers have no respect for users?

Ingo

**Comment by geoderix** [comment]
@heckflosse 

I described the situation with @gaaned92  through the eyes of a ordinary user. I did not talk about all the developers. Did I say something wrong?

**Comment by Beep6581** [comment]
@geoderix please halt this discussion immediately and make sure your future comments are polite, constructive and friendly. If they are not, I will block you. I will not ask again.

**Comment by heckflosse** [comment]
@geoderix Let's calm down (that includes me as well). Maybe that's just a misunderstanding. I hope so :)

@gaaned92 wrote:
```
The new versions of Rawtherapee are based on GTK3 (instead of GTK2 for legacy versions).
 Unfortunately, GTK3 requires on Windows systems the Display Window Manager (DWM) that was implemented by MS on Vista and above. So the missing DWMAPI.dll warning on XP and there is nothing to do.
```

That's a perfectly neutral statement which describes the facts. We can't do anything to get gtk3 gui working on WindowsXP and @gaaned92 (who provided RT Windows XP builds in past and still provides the Win64 builds and Win32 builds for WinVista upwards) also can't do anything to provide RT gtk3 Windows XP builds. 

Then you wrote:

```
If you, of course, have any respect for users. But, it seems, this is not so, unfortunately.
```

I would have been offended by this comment.

**Comment by heckflosse** [comment]
I unlocked the conversation to give @geoderix the opportunity to answer my post.

**Comment by geoderix** [comment]
@heckflosse 
 `That's a perfectly neutral statement which describes the facts. We can't do anything to get gtk3 gui working on WindowsXP and @gaaned92 (who provided RT Windows XP builds in past and still provides the Win64 builds and Win32 builds for WinVista upwards) also can't do anything to provide RT gtk3 Windows XP builds.`

Yes, without context this is perfectly neutral statement.
With context this is a disparaging and arrogant to the users phrase.
It's funny that you had to зush back the janitor so that I could answer.
