### ISSUE TITLE
Switch between RGB curves in the RGB curves tab does not work

### ISSUE THREAD

**Issue by ghost** [Beep6581/RawTherapee#3657]
Hi,
using the RGB curves in the colour management tab I realized that it is not possible to go back e.g. to the R curve, once G and B curves have been changed. I.e. I cannot iterate changes in the curves without resetting my changes, which in turn resets my adjustments just made.

Hermann-Josef

RT version :
Branch: gtk3
Version: 5.0
Changeset: 7fe7c4f60f85b47bc1d24b2cfece43444028e3a6
Compiler: gcc 5.3.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.18.0
Build type: release
Build flags: -m64 -mwin32 -mthreads -std=gnu++11 -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -msse -msse2 -mwindows -fopenmp -Wno-aggressive-loop-optimizations -DNDEBUG -O3
Link flags: -m64 -mwin32 -mthreads -static-libgcc -mtune=generic -mwindows -s -O3
OpenMP support: ON
MMAP support: ON

Windows10 Pro, 24 GByte memory, processor Intel I7

**Comment by TooWaBoo** [comment]
I'm on Windows 10 Home x64 and I can't reproduce this behaviour.
Testet with RT5 Gtk3.18 and RT5 Gtk3.22

**Comment by Beep6581** [comment]
Each curve gets its own entry in the linear history. Can you describe the problem better?

**Comment by ghost** [comment]
Hi,
in the RGB curves tab (Color management tab) I select the R channel and custom, change the curve and then go to G, do the same, and then with the B channel.

Now I want to iterate the changes and want to switch back to the R channel but I cannot. I get stuck with the B channel. The only way out is to reset the changes.

Maybe this is my fault, since I was choosing "custom" again. I just realized, I have to hit the curve icon. Then I can switch between the channels.

Also I realized, when checking this again: If I open another image, the changes in the RGB curves are still there. Is that on purpose? I would have thought that with a new image the settings are reset.

Hermann-Josef

**Comment by heckflosse** [comment]
> Also I realized, when checking this again: If I open another image, the changes in the RGB curves are still there. Is that on purpose? I would have thought that with a new image the settings are reset.

It is on purpose that the changes in RGB curves are still there but are not active until you change the curve type because the curve type for a new image is set to linear. This allows you to easily apply the same curve to a new image by changing curve type from linear to custom.
