### ISSUE TITLE
Exif tag UserComment

### ISSUE THREAD

**Issue by herb52** [Beep6581/RawTherapee#3658]
Hello,

I started to work with RawTherapee 5.0-gtk3 64-bit on a Windows 7 64-bit system. (I never worked with older versions of RawTherapee.) Congratulations to this version.

I assigned the 2 tags Exif:UserComment and also Exif:ImageDescription to a *.orf image and stored the output as *.jpg file. Both tags contained Ascii characters and also some chinese characters.

In order to check the written metadata, I also assigned the identical tags with Exiftool 10.41 and have seen the following:
- ImageDescription has been written in identical form by Exiftool and by RawTherapee.
  Tag-values encoded in UTF8.
- UserComment has been stored differently:
  Exiftool wrote: UNICODE followed by tag-value encoded in UCS2
  RawTherapee wrote: ASCII followed by tag-value encoded in UTF8

The MWG 2.0 specification says:
UTF-8 is only recommended for string-type tags, not for tags like UserComment which specify an encoding.  The MWG spec says: "Exif tags such as UserComment that have an encoding prefix SHOULD be written as ASCII if all bytes fit in the 7-bit range 0..127, and MUST be written in some other encoding if any byte is outside the 7-bit range".

So for me RawTherapee is wrong according to the specification.

Best regards
Herb

**Comment by Beep6581** [comment]
See #4372
