### ISSUE TITLE
Nikon D300 shots for DCP

### ISSUE THREAD

**Issue by Kakupakat** [Beep6581/RawTherapee#3661]
https://filebin.net/b6qloe6minx8tud5

**Comment by Beep6581** [comment]
@Kakupakat as with #3662, all StdA shots are overexposed. Could you upload a new set?

**Comment by Kakupakat** [comment]
The new set: https://filebin.net/tfwhozcn3vn5jujd

**Comment by Beep6581** [comment]
@Kakupakat thank you, DCP added.
