### ISSUE TITLE
RT5 crash at start

### ISSUE THREAD

**Issue by srgmro** [Beep6581/RawTherapee#3666]
RT5 get from PPA Dariuz.
Version: 5.0-r1-gtk3
Branch: releases
Commit: 50114c1a
Commit date: 2017-02-01
Compiler: x86_64-linux-gnu-gcc 5.4.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.18.0
Build type: Release
Build flags: -O3 -std=gnu++11  -Werror=unused-label -fopenmp -Werror=unknown-pragmas
Link flags:  -Wl,-Bsymbolic-functions -Wl,-z,relro
OpenMP support: ON
MMAP support: ON

Running on Kubuntu 16.4; i7 2600 12Gio Ram
I am unable to compile a debug version.
So you will find herre the result from a console at start, when there is a crash :
```
serge@serge-pc:~$ rawtherapee
* Error in `rawtherapee': realloc(): invalid pointer: 0x00007fd1ad015d00 *
```
Backtrace:
==========
```
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7fd1a91787e5]
/lib/x86_64-linux-gnu/libc.so.6(realloc+0x348)[0x7fd1a9184e58]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_realloc+0x28)[0x7fd1ad4ea7d8]
/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x16d209)[0x7fd1ac85a209]
/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x16d43a)[0x7fd1ac85a43a]
/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x16c22d)[0x7fd1ac85922d]
/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1fd3ed)[0x7fd1ac8ea3ed]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_type_create_instance+0x1b7)[0x7fd1ad7df317]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x1531b)[0x7fd1ad7c131b]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_object_newv+0x1f2)[0x7fd1ad7c2d22]
/usr/lib/x86_64-linux-gnu/libglibmm-2.4.so.1(_ZN4Glib6ObjectC2ERKNS_15ConstructParamsE+0x10d)[0x7fd1ad27853d]
/usr/lib/x86_64-linux-gnu/libgtkmm-3.0.so.1(_ZN3Gtk6ObjectC2ERKN4Glib15ConstructParamsE+0x16)[0x7fd1ac0a3966]
/usr/lib/x86_64-linux-gnu/libgtkmm-3.0.so.1(_ZN3Gtk6WidgetC2ERKN4Glib15ConstructParamsE+0x22)[0x7fd1ac07f502]
/usr/lib/x86_64-linux-gnu/libgtkmm-3.0.so.1(_ZN3Gtk4MiscC2ERKN4Glib15ConstructParamsE+0x15)[0x7fd1ac01b195]
/usr/lib/x86_64-linux-gnu/libgtkmm-3.0.so.1(_ZN3Gtk5LabelC1ERKN4Glib7ustringEb+0xb6)[0x7fd1ac00a7e6]
rawtherapee(_ZN11FileCatalog19_refreshProgressBarEv+0x295)[0x6a5115]
rawtherapee(_ZN11FileCatalog12previewReadyEiP16FileBrowserEntry+0x302)[0x6a7e52]
rawtherapee(_ZN13PreviewLoader4Impl14processNextJobEv+0x237)[0x6c4147]
/usr/lib/x86_64-linux-gnu/libglibmm-2.4.so.1(+0x595c2)[0x7fd1ad27b5c2]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x7154e)[0x7fd1ad50c54e]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x70bb5)[0x7fd1ad50bbb5]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba)[0x7fd1a94d16ba]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7fd1a920782d]
```
That's all I am able to do. For me this backtrace is always the same I obtained when RT5 crashes.
Sorry 
SM

**Comment by Beep6581** [comment]
@srgmro please install GDB and run RawTherapee from it to get a better stack backtrace as explained here http://rawpedia.pixls.us/index.php/How_to_write_useful_bug_reports#When_RawTherapee_crashes_-_An_introduction_to_stack_backtraces

Try to find whether a specific file is causing the crash as explained here http://rawpedia.rawtherapee.com/How_to_fix_crashes_on_startup

**Comment by srgmro** [comment]
@Beep6581 You were right, the problem arise from two folders having numerous raw files and pp3. A new one never trigger the crash. The only strange behaviour arises from using the unstable version of RT which never exhibit that crash with the usual folders. So I consider the problem as solved. thanks very much for your help and suggestions.
SM

**Comment by Beep6581** [comment]
@srgmro the bug can only get fixed if you upload the guilty file.

**Comment by srgmro** [comment]
OK, I am looking carefully to the folder and loading in it step by step raw images (for the moment from sony ). The first things which looks strange for me is that I have some raw image in triplicate, that i nevre have before. 
Ex : DSC01635.ARW and DSC01635_1.ARW DSC01635_2.ARW with time of creation of 13:28 for the first one and 15:28 for the two others. This behaviour is systematic each time my raw file are in triplicate.
Let me know if there is something new in the default configuration of RT5.
SM

**Comment by srgmro** [comment]
Looking further on folders of canon raw files (.CR2) I never observer files in triplicate.
SM

**Comment by srgmro** [comment]
I consider that these triplicates can only arise from loading of raw files from the camera.
So I focus on looking on faulty files, but that will not be so easy. The crash is not highly reproducible.

**Comment by srgmro** [comment]
The method to detect the guilty file.
I chose to start from the folder which contains the suspected file. (around  1000 raw files).
At each step I divided  into two equal halves the folder, and checked which of the two is always responsible for the crash. Then the crashing folder was divided once more and so on...
Following this process which was followed at each step of a complete reboot of the system (in this way I get the more reproducible crash), I reached two equal folder containing 15 an 16 raw files. 
At this step neither of the two exhibit the expected crash. I stopped my investigation there.
Sorry but I can't go further.

**Comment by Beep6581** [comment]
@srgmro thank you for the effort. Are you willing to either [compile your own debug build](http://rawpedia.rawtherapee.com/Linux)  or [contact Dariusz](http://rawtherapee.com/downloads) to help you get one, to get us a proper stack backtrace? If not, we have nothing to go by and will have to close this issue.
