### ISSUE TITLE
Demosaic artefacts

### ISSUE THREAD

**Issue by Eneen** [Beep6581/RawTherapee#3667]
Hi,

I'm in the middle of mimicking Canon DPP look. I've came across demosaic artefacts when strong contrast and chromatic aberration is involved. I tried several available algorithms but none is better then original one. Please take a look. I can provide CR2 and jpegs but need to know where to upload big files to make them available.

DPP gives soft nice looking picture without any artefacts:
![_mg_6842_dpp_crop](https://cloud.githubusercontent.com/assets/25537418/22607505/7e7f6562-ea58-11e6-9aef-d18321c2e4e5.JPG)

RT with amaze gives >blue< halo around bright edges:
![_mg_6842_rt_amaze_crop](https://cloud.githubusercontent.com/assets/25537418/22607516/88d3a85c-ea58-11e6-85e3-2d8ea176e27a.JPG)

RT with igv gives almost same look as DPP but blue halo is still visible and there are visible jagged edges around small objects:
![_mg_6842_rt_igv_crop](https://cloud.githubusercontent.com/assets/25537418/22607526/95623d36-ea58-11e6-9705-6940c0b3dea0.JPG)

All are set to max reduction level (5 I guess).

**Comment by heckflosse** [comment]
@Eneen As you opened the Issue you could read this:

```
If you are filing a bug report, please first read the guide How to Write Useful Bug Reports:
http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports
You must provide the required information in order for your bug report to be valid.
Delete this text before posting.
```

Unfortunately you only followed the last sentence :(

**Comment by Eneen** [comment]
Oh, I'm very sorry, haven't found that page before. Here is all info:
RT version 5.0-gtk3-27-g50114c1a from here:
https://drive.google.com/drive/folders/0B2q9OrgyDEfPS2FpdDAtMVI1RG8
System info: Windows 10, Intel Core i7 4770, 16GB RAM
Link to files: http://filebin.ca/3B9yaTMQOHxu/rawtherapee_dem_artef.7z
To replicate just open provided CR2 file and change between demosaicing modes. I've attached pp3. I hopefully disabled all possible corrections to show exact problem. As I've written before, there is no option in DPP to disable chromatic aberration correction, but when moving picture around it displays original picture before correction kicks in and there is no blue halo visible. I was able to grab screenshot:
![_mg_6842_dpp_crop_screen](https://cloud.githubusercontent.com/assets/25537418/22609110/313ae3dc-ea60-11e6-8f28-625e98408e9e.JPG)

**Comment by heckflosse** [comment]
@Eneen Thanks for uploading the file and providing information about the rt version you use.
What you see there is the correct output of the demosaicers. It's CA and maybe also some fringe which you can correct in RT as well.

PLease try the following pp3 files.
One is with CA correction, the other one with CA correction + Defringe



[_MG_6842_pp3.zip](https://github.com/Beep6581/RawTherapee/files/751619/_MG_6842_pp3.zip)

**Comment by Eneen** [comment]
Indeed, that fixed it, great! And it seems, that DPP uses CA correction that's invisible to user. Good to know. Also result from RT is sharper.

**Comment by Beep6581** [comment]
@Eneen read this, it covers that most editors do things behind your back without your knowing: http://rawpedia.rawtherapee.com/The_Image_Editor_Tab#Eek.21_My_Raw_Photo_Looks_Different_than_the_Camera_JPEG

Also see this http://rawpedia.rawtherapee.com/Getting_Started

No issue here, closing.
