### ISSUE TITLE
Adwaita : Windows cursors missing

### ISSUE THREAD

**Issue by gaaned92** [Beep6581/RawTherapee#3670]
I don't know if they are used by Rawtherapee GTK3 as it seems without impact.
It generates a warning either in verbose mode or in debug builds.

As described [https://bugzilla.gnome.org/show_bug.cgi?id=774671](https://bugzilla.gnome.org/show_bug.cgi?id=774671), the adwaita windows cursors are missing in the MSYS2 installation.
I hope that the adwaita update will find its way to MSYS2

**Comment by Beep6581** [comment]
Is there anything that we should do about it?

**Comment by gaaned92** [comment]
@Hombre57 could you answer?

**Comment by gaaned92** [comment]
I found here [https://git.gnome.org/browse/adwaita-icon-theme/](https://git.gnome.org/browse/adwaita-icon-theme/) the adwaita icon theme 3.23.91.
the "adwaita-icon-theme-3.23.91\Adwaita\cursors\"  folder contains effectively .cur windows cursors.
When copying this folder in Rawtherapee the warning disappear.
My next builds will include those windows cursors.
So I think we have to wait for a MSYS2 update.

**Comment by gaaned92** [comment]
@Beep6581 perhaps we can close this as I think there is nothing to do in Rawtherapee
