### ISSUE TITLE
DNG files from HdrMerge are decoded incorrectly when zlib 1.2.11 is used

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#3674]
Suggested fix until we have a better solution:

```
diff --git a/rtengine/dcraw.cc b/rtengine/dcraw.cc
index a3bd3e5..8623d26 100644
--- a/rtengine/dcraw.cc
+++ b/rtengine/dcraw.cc
@@ -9791,20 +9791,22 @@ void CLASS deflate_dng_load_raw() {
     }
     uLongf dstLen = tile_width * tile_length * 4;
 
-#ifdef _OPENMP
+#if defined(_OPENMP) && ZLIB_VER_REVISION == 8
 #pragma omp parallel
 #endif
 {
     Bytef * cBuffer = new Bytef[maxCompressed];
     Bytef * uBuffer = new Bytef[dstLen];
 
-#ifdef _OPENMP
+#if defined(_OPENMP) && ZLIB_VER_REVISION == 8
 #pragma omp for collapse(2) nowait
 #endif
     for (size_t y = 0; y < raw_height; y += tile_length) {
       for (size_t x = 0; x < raw_width; x += tile_width) {
 		size_t t = (y / tile_length) * tilesWide + (x / tile_width);
+#if defined(_OPENMP) && ZLIB_VER_REVISION == 8
 #pragma omp critical
+#endif
 {
         fseek(ifp, tileOffsets[t], SEEK_SET);
         fread(cBuffer, 1, tileBytes[t], ifp);

```

@Beep6581 Can you test the patch please?

**Comment by Beep6581** [comment]
Thank you! I will test when I get back home.

**Comment by Beep6581** [comment]
Fix confirmed!

**Comment by TooWaBoo** [comment]
Funny things happen...
https://discuss.pixls.us/t/no-disk-in-drive-fixed/3287

**Comment by Floessie** [comment]
@TooWaBoo André's (gaaneed92) first patch ever is a striking success. Give him the credits for (and in) #3544. :smile:

**Comment by TooWaBoo** [comment]
@Floessie 

Ahh, so I was on the wrong way.
@gaaned92
Many thanks for that. Sorry, that I didn't find this issue before.

**Comment by heckflosse** [comment]
Reopened because [floatdngomp](https://github.com/Beep6581/RawTherapee/tree/floatdngomp) branch fixes this issue finally.

I tested using [eizo_vs_laptop.hdr.dng](http://rawtherapee.com/shared/test_images/eizo_vs_laptop.hdr.dng). File was loaded from SSD

before: 195 ms
after: 75 ms

**Comment by Beep6581** [comment]
I'm using zlib-1.2.11. I recompiled HDRMerge and compiled floatdngomp, confirmed that both use `libz.so.1.2.11`, saved a new DNG and processed it successfully in RT.
