### ISSUE TITLE
gtk3 warning: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

### ISSUE THREAD

**Issue by gaaned92** [Beep6581/RawTherapee#3675]
build : 5.0.gtk3
Windows10
When starting rawtherapee, this message appears 6 times.

**Comment by TooWaBoo** [comment]
This happens only with the RT theme. I doesn't happen with TooWaBlue, maybe 'cause I'm setting the size of the scrollbar in the theme.

**Comment by gaaned92** [comment]
Is it possible to do that in rawtherapee theme?

**Comment by TooWaBoo** [comment]
Yes, it's possible. But when you set a size of an object, you have to size everything.

I've adapted the styles for the RT theme. You can use them by copypasta :-)
ping @Beep6581, @Hombre57 
```
scrollbar {
    margin: 0;
    padding: 0;
}
scrollbar slider {
    padding: 0;
    margin: 0;
    border-color: transparent;
    border-style: solid;
    border-radius: 12px;
}

scrollbar:not(.overlay-indicator).horizontal slider,
scrollbar.horizontal.hovering slider {
    min-height: 6px;
    min-width: 24px;
    border-width: 3px;
}
scrollbar:not(.overlay-indicator).horizontal.fine-tune slider,
scrollbar.horizontal.hovering.fine-tune slider {
    min-height: 4px;
    border-width: 4px;
    margin: 0 -1px;
}
scrollbar.horizontal.overlay-indicator:not(.hovering) slider {
    min-width: 24px;
    min-height: 3px;
    border-width: 1px;
    border-radius: 3px;
    margin: 0 2px;
}

scrollbar:not(.overlay-indicator).vertical slider,
scrollbar.vertical.hovering slider {
    min-height: 24px;
    min-width: 6px;
    border-width: 3px;
}
scrollbar:not(.overlay-indicator).vertical.fine-tune slider,
scrollbar.vertical.hovering.fine-tune slider {
    min-width: 4px;
    border-width: 4px;
    margin: -1px 0;
}
scrollbar.vertical.overlay-indicator:not(.hovering) slider {
    min-width: 3px;
    min-height: 24px;
    border-width: 1px;
    border-radius: 6px;
    margin: 2px 0;
}
```

**Comment by Hombre57** [comment]
For Gtk3.20 I guess ?

One should add that we shouldn't have to set the size of this object, it's a Gtk bug.

**Comment by TooWaBoo** [comment]
@Hombre57 

It's for Gtk3.20

I have to size this object, 'cause of the DPI thing. :-)

**Comment by Hombre57** [comment]
Which is not the case for the main theme. Yet it seem to be mandatory.

**Comment by TooWaBoo** [comment]
It's up to you to add it to the theme. I don't think there is a problem if you don't do it

**Comment by Hombre57** [comment]
I'll try your patch tomorrow (working on something else actually), but was only saying that your patch above is a workaround of a Gtk bug, or do I miss something ?

**Comment by TooWaBoo** [comment]
No, you don't miss anything.
