### ISSUE TITLE
Operation over NFS extremely slow

### ISSUE THREAD

**Issue by ff2000** [Beep6581/RawTherapee#3676]
I am on Gentoo Linux, currently use the gtk3 branch.
```
Version: 5.0-r1-gtk3
Branch: gtk3
Commit: 50114c1
Commit date: 2017-02-01
Compiler: clang 3.9.0
Processor: Intel(R)\ Core(TM)\ i3-2350M\ CPU\ @\ 2.30GHz
System: Linux
Bit depth: 64 bits
Gtkmm: V3.22.0
Build type: Release
Build flags:  -std=gnu++11  -Werror=unused-label -fopenmp=libomp -Werror=unknown-pragmas -O3 -DNDEBUG
Link flags:   
OpenMP support: ON
MMAP support: ON
```
But I had this issue also with gtk2.
Both my laptop and the NFS server run kernel 4.9.6, nfsv4.1 support is enabled.

The biggest issue is generation of thumbs. I have a 10MP Olympus E-520 and shoot RAW+jpeg. A raw is about 10MB, jpeg about 5MB. RT reads 4 files at a time (which IMO makes sense for a DUAL core + Hyper Threading CPU) and then pauses for roughly 30 seconds. It literally pauses as the network and CPU monitors show ZERO load. As long as thumbs are loading opening an image is also blocked - I see the "amaze" and "demosaic" steps freeze in the middle of operation. It seems as if a global lock is involved and a shared thread pool with NUM CPUS threads is used for every file operation.

I also tried Geeqie as an image viewer. thumb generation and general operation is really fast. The network monitor shows constant load while geeqie operates on the NFS mount.

So I think there seems to be some sort of bug in RawTherapee, at least for my system. If you need some more information please just ask!

**Comment by Beep6581** [comment]
Possibly a duplicate of #1807

**Comment by ff2000** [comment]
Yes could be a duplicate, though I see 2 differences: #1807 and #622 are specifically about Windows NAS. And those reports only mention an initial delay of 15-20 resp. 30 sec, after that all thumbs get loaded. For me I get 30 sec. timeout after every 4 images for new (uncached by RT) folders which means 100/4*30 = 750sec for reading a folder with 100 images...
For folders with already existing thumbs in RT-cache I get (much) more than just 4 images per iteration, but still a timeout of 30sec between them.
Also #622 is already closed as fixed. Of course I don't know if that's enough to keep this issue open ;)

**Comment by heckflosse** [comment]
@ff2000 Can you try this patch? It measures the time for read and write of the cache files. Maybe we find the culprit.

Edit: Before you try the patch I should ask whether your rt cache is on NFS too

```
diff --git a/rtengine/rtthumbnail.cc b/rtengine/rtthumbnail.cc
index 14f9f91..bed9981 100644
--- a/rtengine/rtthumbnail.cc
+++ b/rtengine/rtthumbnail.cc
@@ -37,7 +37,7 @@
 #include "../rtgui/ppversion.h"
 #include "improccoordinator.h"
 #include <locale.h>
-//#define BENCHMARK
+#define BENCHMARK
 #include "StopWatch.h"
 
 
@@ -841,7 +841,6 @@ IImage8* Thumbnail::quickProcessImage (const procparams::ProcParams& params, int
 IImage8* Thumbnail::processImage (const procparams::ProcParams& params, int rheight, TypeInterpolation interp, std::string camName,
                                   double focalLen, double focalLen35mm, float focusDist, float shutter, float fnumber, float iso, std::string expcomp_, double& myscale)
 {
-    BENCHFUN
 
     // check if the WB's equalizer value has changed
     if (wbEqual < (params.wb.equal - 5e-4) || wbEqual > (params.wb.equal + 5e-4)) {
@@ -1635,7 +1634,7 @@ unsigned char* Thumbnail::getGrayscaleHistEQ (int trim_width)
 
 bool Thumbnail::writeImage (const Glib::ustring& fname, int format)
 {
-
+BENCHFUN
     if (!thumbImg) {
         return false;
     }
@@ -1673,7 +1672,7 @@ bool Thumbnail::writeImage (const Glib::ustring& fname, int format)
 
 bool Thumbnail::readImage (const Glib::ustring& fname)
 {
-
+BENCHFUN
     if (thumbImg) {
         delete thumbImg;
         thumbImg = nullptr;
@@ -1726,6 +1725,7 @@ bool Thumbnail::readImage (const Glib::ustring& fname)
 
 bool Thumbnail::readData  (const Glib::ustring& fname)
 {
+    BENCHFUN
     setlocale(LC_NUMERIC, "C"); // to set decimal point to "."
     Glib::KeyFile keyFile;
 
@@ -1822,6 +1822,7 @@ bool Thumbnail::readData  (const Glib::ustring& fname)
 
 bool Thumbnail::writeData  (const Glib::ustring& fname)
 {
+BENCHFUN
     MyMutex::MyLock thmbLock(thumbMutex);
 
     Glib::ustring keyData;
@@ -1885,7 +1886,7 @@ bool Thumbnail::writeData  (const Glib::ustring& fname)
 
 bool Thumbnail::readEmbProfile  (const Glib::ustring& fname)
 {
-
+BENCHFUN
     FILE* f = g_fopen (fname.c_str (), "rb");
 
     if (!f) {
@@ -1908,7 +1909,7 @@ bool Thumbnail::readEmbProfile  (const Glib::ustring& fname)
 
 bool Thumbnail::writeEmbProfile (const Glib::ustring& fname)
 {
-
+BENCHFUN
     if (embProfileData) {
         FILE* f = g_fopen(fname.c_str (), "wb");
 
@@ -1924,7 +1925,7 @@ bool Thumbnail::writeEmbProfile (const Glib::ustring& fname)
 
 bool Thumbnail::readAEHistogram  (const Glib::ustring& fname)
 {
-
+BENCHFUN
     FILE* f = g_fopen (fname.c_str (), "rb");
 
     if (!f) {
@@ -1941,7 +1942,7 @@ bool Thumbnail::readAEHistogram  (const Glib::ustring& fname)
 
 bool Thumbnail::writeAEHistogram (const Glib::ustring& fname)
 {
-
+BENCHFUN
     if (aeHistogram) {
         FILE* f = g_fopen (fname.c_str (), "wb");
 

```

**Comment by heckflosse** [comment]
@ff2000 Can you try a build without mmap?
Insert this in the cmake command line:
```
-DWITH_MYFILE_MMAP="OFF"
```

**Comment by ff2000** [comment]
Building with MMAP=OFF did not help.
RT-cache is on the local disc, so not on NFS. Applied patch and I fear the bad function was not yet captured:
```
readData took 0 ms
readImage took 0 ms
readAEHistogram took 0 ms
readEmbProfile took 0 ms
writeImage took 0 ms
writeAEHistogram took 0 ms
writeEmbProfile took 0 ms
writeData took 0 ms
readData took 0 ms
readImage took 0 ms
readAEHistogram took 0 ms
readEmbProfile took 0 ms
CacheImageData::load / Error code 4 while reading values from "/home/franz/.cache/RawTherapee/data/_9305451.JPG.69ee0ed7830a6aab98e50db17763e94a.txt":
Datei oder Verzeichnis nicht gefunden
writeImage took 0 ms
writeAEHistogram took 0 ms
writeEmbProfile took 0 ms
writeData took 0 ms
writeImage took 0 ms
readData took 0 ms
writeImage took 0 ms
writeAEHistogram took 0 ms
readImage took 0 ms
writeEmbProfile took 0 ms
writeAEHistogram took 0 ms
writeEmbProfile took 0 ms
writeData took 0 ms
writeData took 0 ms
readAEHistogram took 0 ms
readEmbProfile took 0 ms
CacheImageData::load / Error code 4 while reading values from "/home/franz/.cache/RawTherapee/data/_9305452 - _9305458.jpg.f63032ab19f5b40d9c7f522051945add.txt":
Datei oder Verzeichnis nicht gefunden
CacheImageData::load / Error code 4 while reading values from "/home/franz/.cache/RawTherapee/data/_9305452 - _9305458_v2.jpg.708ce95e1809b69a13a4f535bf64a08e.txt":
Datei oder Verzeichnis nicht gefunden
CacheImageData::load / Error code 4 while reading values from "/home/franz/.cache/RawTherapee/data/_9305452.JPG.616c0a21885de6425fec86f6446557cc.txt":
Datei oder Verzeichnis nicht gefunden
readData took 0 ms
readImage took 0 ms
readAEHistogram took 0 ms
readEmbProfile took 0 ms
readData took 0 ms
readImage took 1 ms
readAEHistogram took 0 ms
readEmbProfile took 0 ms
writeImage took 0 ms
writeAEHistogram took 0 ms
writeEmbProfile took 0 ms
writeData took 0 ms
readData took 0 ms
readImage took 0 ms
readAEHistogram took 0 ms
readEmbProfile took 0 ms
CacheImageData::load / Error code 4 while reading values from "/home/franz/.cache/RawTherapee/data/_9305453.JPG.7ca8e6caef8cdb5e06f0439fbc5183ef.txt":
Datei oder Verzeichnis nicht gefunden
```
Those errors come with every image not yet in the cache, so I thought it should not be fatal... I also get them with local files and there the speed is OK.

**Comment by heckflosse** [comment]
@ff2000 thanks for testing. Maybe googling for 'nfs 30 sec delay' can help...

**Comment by ff2000** [comment]
I tried debugging with valgrind, took ages and unfortunately valgrind segfaulted after exiting RT :( The collected data can be read but seems it doesn't contain any hint (at least to me). Will look at it again later this week(end), when I find the time.

**Comment by heckflosse** [comment]
@ff2000 I guess valgrinding won't help in that case. But maybe I'm wrong...

**Comment by ff2000** [comment]
@heckflosse I hope callgrind can guide me at least to find the "hot spots".

**Comment by heckflosse** [comment]
@ff2000 I hope that too :+1:

**Comment by Floessie** [comment]
@ff2000 Maybe try `strace` first...

**Comment by heckflosse** [comment]
@ff2000 I added an [Issue in forum](https://discuss.pixls.us/t/operation-over-nfs-extremely-slow/3297). Maybe anyone there has hints...

**Comment by paperdigits** [comment]
@ff2000 Can you share your `/etc/exports` file with us?

**Comment by Floessie** [comment]
@ff2000 I have a NFS here (v3 with TCP). I copied 4G of RAWs there, restarted the client PC, fired up RT `dev` and pointed it to the NFS folder: A short hiccup after the first 8 thumbs (number of cores), the rest came pretty instantaneously. I must admit, I tuned my NFS not for security but maximum throughput.

Server: `/home #.#.#.#/16(rw,async,no_subtree_check)`
Client: `#####:/home /mnt/##### nfs _netdev,tcp,nfsvers=3,intr 0 0`

HTH,
Flössie

**Comment by heckflosse** [comment]
@ff2000 Any news on this issue?

**Comment by harshula** [comment]
@Floessie @heckflosse @ff2000 When debugging NFS performance issues, if there are reads/writes involved, start by collecting nfsiostat output. e.g. nfsiostat 5 /nfsmountpoint >> nfsiostat.txt . Once you have the output, then have a look at the RTT and EXE latencies to determine if the delays are on the NFS Client or NFS Server.
If you are familiar with wireshark, you can collect a tcpdump at the same time. e.g. tcpdump -n -s 300 -i INTERFACE -w OUTFILE host NFS-SERVER-IP . Make sure you use -s to ensure you don't capture all the data and create unnecessarily large files. Then you can generate a summary of latency for each RPC operation to determine if the latency is on the client or server. If you suspect a NFS client problem, then strace can be useful. Make sure to use -T -tt -f -v.
Good luck!

**Comment by ff2000** [comment]
@harshula thx for the info.
I played a lot with export and mount options the weekend and could not get any further. I noticed however that while RT is thumbnailing a DIR geeqie also shows the lockups as RT - which is somewhat weird... I also tried darktable which behaves even worse. I will investigate more.

**Comment by harshula** [comment]
@ff2000 No probs. Go back to the defaults for the time being. First step is to isolate the problem to either the NFS Client of NFS Server. That can be done using nfsiostat and/or tcpdump.

**Comment by ff2000** [comment]
This is what nfsiostat gave me:
```
192.168.1.70:/media mounted on /home/media/desktop:

           ops/s       rpc bklog
           0.000           0.000

read:              ops/s            kB/s           kB/op         retrans    avg RTT (ms)    avg exe (ms)
                   0.000           0.000           0.000        0 (0.0%)           0.000 0.000
write:             ops/s            kB/s           kB/op         retrans    avg RTT (ms)    avg exe (ms)
                   0.000           0.000           0.000        0 (0.0%)           0.000 0.000

192.168.1.70:/media mounted on /home/media/desktop:

           ops/s       rpc bklog
           0.000           0.000

read:              ops/s            kB/s           kB/op         retrans    avg RTT (ms)    avg exe (ms)
                   0.000           0.000           0.000        0 (0.0%)           0.000 0.000
write:             ops/s            kB/s           kB/op         retrans    avg RTT (ms)    avg exe (ms)
                   0.000           0.000           0.000        0 (0.0%)           0.000 0.000

192.168.1.70:/media mounted on /home/media/desktop:

           ops/s       rpc bklog
           0.000           0.000

read:              ops/s            kB/s           kB/op         retrans    avg RTT (ms)    avg exe (ms)
                   0.000           0.000           0.000        0 (0.0%)           0.000 0.000
write:             ops/s            kB/s           kB/op         retrans    avg RTT (ms)    avg exe (ms)
                   0.000           0.000           0.000        0 (0.0%)           0.000 0.000

192.168.1.70:/media mounted on /home/media/desktop:

           ops/s       rpc bklog
           0.000           0.000

read:              ops/s            kB/s           kB/op         retrans    avg RTT (ms)    avg exe (ms)
                   0.000           0.000           0.000        0 (0.0%)           0.000 0.000
write:             ops/s            kB/s           kB/op         retrans    avg RTT (ms)    avg exe (ms)
                   0.000           0.000           0.000        0 (0.0%)           0.000 0.000

192.168.1.70:/media mounted on /home/media/desktop:

           ops/s       rpc bklog
          12.800           0.000

read:              ops/s            kB/s           kB/op         retrans    avg RTT (ms)    avg exe (ms)
                   5.800        5645.762         973.407        0 (0.0%)         921.586         922.069
write:             ops/s            kB/s           kB/op         retrans    avg RTT (ms)    avg exe (ms)
                   0.000           0.000           0.000        0 (0.0%)           0.000 0.000
```
So essentially no traffic for 30 seconds. (This pattern repeats)

I also did a tcpdump and it shows the same hole with no packages being transferred for 30 seconds. I will have to dive into wireshark to get those stats. Will take some time as I never used wireshark to this extent.

BTW.: If you think further posts (as it's mostly about debugging) shouldn't go here I can post on the forum and (hopefully) come back with the solution.

**Comment by Floessie** [comment]
@ff2000 Hm, 30s? Sound a bit like a resolver timeout. Had those problems once with avahi/mDNS. Just a wild guess...

**Comment by ff2000** [comment]
This is a direct Ethernet connection, all wired, no services involved, static IP. For both Server and Client. So I hope I can rule that out...

**Comment by paperdigits** [comment]
I'd say make sure all your DNS stuff is working well in /etc/resolvconf, static IP or not, network stack may still ping your DNS. Also make sure portmapper is functioning properly.

**Comment by Floessie** [comment]
Yep, and to make sure, use `strace` or something similar as suggested. :)

**Comment by harshula** [comment]
@ff2000 I hope you captured the nfsiostat output to a text file for the entire duration of the problem. If so please upload it somewhere, so I can download it and have a look. filebin.net seems to be preferred by Rawtherapee devs. It's not a good idea to make any conclusions from a single sample, however, an RTT ~1 second is quite bad. That's about two orders of magnitude worse than I normally see. RTT is the time outside the NFS Client. So network latency plus NFS Server latency.

**Comment by harshula** [comment]
@ff2000 How is the NFS performance investigation going?

**Comment by ff2000** [comment]
Unfortunately I have not yet found a solution. I spent some hours without success. I now went ahead and mounted via sshfs which seems to work just fine. No hangs so far.
I will close this issue for now. When I find the time and the source of the problem I will post it here. Thx for all your help nevertheless!

**Comment by valpackett** [comment]
Hi. I've had a similar issue. Not the same though — no pauses, but also thumbnail related:

With NFSv4 between two FreeBSD boxes, both RawTherapee and Darktable slowed down to a crawl in file browser mode, with a full CPU load. (A beefy Ryzen 7 rig not being able to scroll a list of fscking photo thumbnails looks *so ridiculous*…)

`-DWITH_MYFILE_MMAP="OFF"` completely solved the problem for me! Thanks a lot @heckflosse :)

**Comment by valpackett** [comment]
Would be nice if RawTherapee automatically turned off mmap for network filesystems…

**Comment by heckflosse** [comment]
@myfreeweb Thanks for feedback! Currently we are in the process to release 5.4, which means it's too late now for changing this. Maybe for 5.5. I will set it on my todo list now. Issue should not be closed.
