### ISSUE TITLE
Windows 10 Photo Viewer doesn't show metadata

### ISSUE THREAD

**Issue by shreedhar2015** [Beep6581/RawTherapee#3680]
I am using a 64 bit Win 10 computer and the latest RT 5.0-r1-gtk3 build. I have enabled writing of metadata in the preferences. However, the exported tiff file does not contain any metadata. The same file exported as a JPG contains all the information.  What should be done to rectify this behaviour?

**Comment by Beep6581** [comment]
> If you are filing a bug report, please first read the guide How to Write Useful Bug Reports:
http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports
You must provide the required information in order for your bug report to be valid.

@shreedhar2015 as I already requested in the forum, please provide all of the information listed in the guide. In addition to the sample TIFF and raw file, include your [options](http://rawpedia.rawtherapee.com/File_Paths) file.

**Comment by shreedhar2015** [comment]
Sorry for the incomplete bug report. Here is my second attempt:

**About RT:**
Version: 5.0-r1-gtk3
Branch: 5.0-r1-gtk3
Commit: 50114c1
Commit date: 2017-02-01
Compiler: gcc 5.3.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.18.0
Build type: release
Build flags: -m64 -mwin32 -mthreads -std=gnu++11 -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -msse -msse2 -mwindows -fopenmp -Wno-aggressive-loop-optimizations -DNDEBUG -O3
Link flags: -m64 -mwin32 -mthreads -static-libgcc -mtune=generic -mwindows -s -O3
OpenMP support: ON
MMAP support: ON

Operating System: Win 10 Home single language 64bit
processor: Intel i5 4200U 1.6GHZ, 4GB RAM
Machine: Sony Vaio Flip 13 Laptop.

I have changed the extension of the options file to txt for me to be able to upload it:
[options.txt](https://github.com/Beep6581/RawTherapee/files/767392/options.txt)

Links to the sample tiff, pp3 and raw files:
https://drive.google.com/open?id=0B8W40PqaFFmyZ3diNkVuRTdTS1U
https://drive.google.com/open?id=0B8W40PqaFFmyeUM3M2ZGTFlWd28
https://drive.google.com/open?id=0B8W40PqaFFmyc2FhZGNKVUlkbHM

Screenshot of the problem:
![screenshot 26](https://cloud.githubusercontent.com/assets/15703860/22838024/26c97a7e-efe9-11e6-8241-c04eb32ffb4e.png)

**Comment by Beep6581** [comment]
Thanks for the missing info.

All the metadata is intact in your TIFF file: https://paste.pound-python.org/show/jyxzKeHsCjDo2fH9veNy/

**Comment by shreedhar2015** [comment]
Wow, what a fast reply! Thanks a lot ! 

But then, why is it that photo viewer is not able to read it? 
The same programme does read the metadata from other files.

**Comment by Beep6581** [comment]
Most likely because there is an unknown or broken tag in the metadata and Windows 10 Photo Viewer completely aborts reading the metadata instead of skipping those tags.
Coincidentally,
![df92un6](https://cloud.githubusercontent.com/assets/5844619/22838807/05a97bea-efc7-11e6-8b98-38150484152f.png)

**Comment by Beep6581** [comment]
I saved four TIFF versions of your raw: 8-bit, 16-bit, each compressed and uncompressed. All exhibit the "Unknown field with tag" message:
```
/tmp $ identify -verbose /tmp/_MG_2544_u_8.tif 2>&1 | tail -n 6
  Version: ImageMagick 6.9.6-6 Q16 x86_64 2017-01-17 http://www.imagemagick.org
identify: Unknown field with tag 34866 (0x8832) encountered. `TIFFReadCustomDirectory' @ warning/tiff.c/TIFFWarnings/910.
identify: Unknown field with tag 42033 (0xa431) encountered. `TIFFReadCustomDirectory' @ warning/tiff.c/TIFFWarnings/910.
identify: Unknown field with tag 42034 (0xa432) encountered. `TIFFReadCustomDirectory' @ warning/tiff.c/TIFFWarnings/910.
identify: Unknown field with tag 42036 (0xa434) encountered. `TIFFReadCustomDirectory' @ warning/tiff.c/TIFFWarnings/910.
identify: Unknown field with tag 42037 (0xa435) encountered. `TIFFReadCustomDirectory' @ warning/tiff.c/TIFFWarnings/910.
/tmp $ identify -verbose /tmp/_MG_2544_c_8.tif 2>&1 | tail -n 6
  Version: ImageMagick 6.9.6-6 Q16 x86_64 2017-01-17 http://www.imagemagick.org
identify: Unknown field with tag 34866 (0x8832) encountered. `TIFFReadCustomDirectory' @ warning/tiff.c/TIFFWarnings/910.
identify: Unknown field with tag 42033 (0xa431) encountered. `TIFFReadCustomDirectory' @ warning/tiff.c/TIFFWarnings/910.
identify: Unknown field with tag 42034 (0xa432) encountered. `TIFFReadCustomDirectory' @ warning/tiff.c/TIFFWarnings/910.
identify: Unknown field with tag 42036 (0xa434) encountered. `TIFFReadCustomDirectory' @ warning/tiff.c/TIFFWarnings/910.
identify: Unknown field with tag 42037 (0xa435) encountered. `TIFFReadCustomDirectory' @ warning/tiff.c/TIFFWarnings/910.
/tmp $ identify -verbose /tmp/_MG_2544_u_16.tif 2>&1 | tail -n 6
  Version: ImageMagick 6.9.6-6 Q16 x86_64 2017-01-17 http://www.imagemagick.org
identify: Unknown field with tag 34866 (0x8832) encountered. `TIFFReadCustomDirectory' @ warning/tiff.c/TIFFWarnings/910.
identify: Unknown field with tag 42033 (0xa431) encountered. `TIFFReadCustomDirectory' @ warning/tiff.c/TIFFWarnings/910.
identify: Unknown field with tag 42034 (0xa432) encountered. `TIFFReadCustomDirectory' @ warning/tiff.c/TIFFWarnings/910.
identify: Unknown field with tag 42036 (0xa434) encountered. `TIFFReadCustomDirectory' @ warning/tiff.c/TIFFWarnings/910.
identify: Unknown field with tag 42037 (0xa435) encountered. `TIFFReadCustomDirectory' @ warning/tiff.c/TIFFWarnings/910.
/tmp $ identify -verbose /tmp/_MG_2544_c_16.tif 2>&1 | tail -n 6
  Version: ImageMagick 6.9.6-6 Q16 x86_64 2017-01-17 http://www.imagemagick.org
identify: Unknown field with tag 34866 (0x8832) encountered. `TIFFReadCustomDirectory' @ warning/tiff.c/TIFFWarnings/910.
identify: Unknown field with tag 42033 (0xa431) encountered. `TIFFReadCustomDirectory' @ warning/tiff.c/TIFFWarnings/910.
identify: Unknown field with tag 42034 (0xa432) encountered. `TIFFReadCustomDirectory' @ warning/tiff.c/TIFFWarnings/910.
identify: Unknown field with tag 42036 (0xa434) encountered. `TIFFReadCustomDirectory' @ warning/tiff.c/TIFFWarnings/910.
identify: Unknown field with tag 42037 (0xa435) encountered. `TIFFReadCustomDirectory' @ warning/tiff.c/TIFFWarnings/910.
```

Quote from ImageMagick's forum,
> The TIFF specification defines a number of well-known tags. Other proprietary tags are permitted but ignored.

**Comment by shreedhar2015** [comment]
I am sorry to ask: But what does this unknown tag mean? Is it a RT issue or a Win 10 issue? If it is a Win 10 issue in your opinion, I will close the issue here !!!

**Comment by Beep6581** [comment]
@shreedhar2015 I edited my post with a possible answer to your question just as you were writing it :)

**Comment by shreedhar2015** [comment]
@Beep6581 I think you are saying that it is a Win 10 issue. I will thus close the bug report. Thanks a lot. 

I guess, I will have to figure out myself how to get rid of this problem.

**Comment by Beep6581** [comment]
These unknown tags are:
```
0x8832 Recommended Exposure Index      : 200
0xa431 Serial Number                   : 302021000038
0xa432 Lens Info                       : 28-105mm f/0
0xa434 Lens Model                      : EF28-105mm f/3.5-4.5 USM
0xa435 Lens Serial Number              : 0000000000
```
