### ISSUE TITLE
Long launch and unresponsive 

### ISSUE THREAD

**Issue by PsychoMan44** [Beep6581/RawTherapee#3682]
RawTherapee version 5.0-r1-gtk3
Version: 5.0-r1-gtk3
Branch: 5.0-r1-gtk3
Commit: 50114c1
Commit date: 2017-02-01
Compiler: gcc 5.3.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.18.0
Build type: release
Build flags: -m64 -mwin32 -mthreads -std=gnu++11 -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -msse -msse2 -mwindows -fopenmp -Wno-aggressive-loop-optimizations -DNDEBUG -O3
Link flags: -m64 -mwin32 -mthreads -static-libgcc -mtune=generic -mwindows -s -O3
OpenMP support: ON
MMAP support: ON

Fresh install of Windows 10 Home 64 bit.
Intel i5 750@2.67GHz
RAM 4GB

RawThreapee launches for 2-3 minutes. Looks like nothing is happening at all. Process is created immediately but takes almost no CPU resources and slowly fills memory (from about 25MB to 140MB once its up).
After it launches it's still very slow. Opening preferences window takes at least a minute. Even activating the window (after it was minimized) takes couple of seconds.
Opening and editing photos works fine. But again, as soon as want to open save dialogue it takes at least a couple of seconds.

When started in debug mode, console is empty for full loading time and fills with couple instances of below once its up:
(rawtherapee-debug.exe:7176): Gtk-WARNING **: Failed to fetch network locations: Error opening directory 'C:\Aplikacje\Media\RawTherapee\network:': No such file or directory

I have created empty directory with this name, but it did not change anything.

**Comment by Beep6581** [comment]
@PsychoMan44 try the advice from #3450

**Comment by PsychoMan44** [comment]
Yup. Disabling A drive in BIOS solved the issue.
Thanks!
