### ISSUE TITLE
Windows cursor & Filechooser language pack, Enhancement

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#3684]
@gaaned92, @sguyader Perhaps you are interested in this pack
DOWNLOAD: https://filebin.net/87rwe7kekbod8gk6

Gtk uses the system cursor on Windows. Some of them don't look nice. I made a mini cursor pack to replace those ugly cursors.
The double arrows are used for the vertical/horizontal crop area and has now the same style as the diagonal cursor. The fat plus in curves is replaced by a crosshair. The left/right arrow replaces the cursor for the control points in equalizer curves. Copy the folder cursors to `share\icons\Adwaita\`

btw: Don't trust the thumbnails in Windows explorer. It often shows the wrong cursor.
![unbenannt](https://cloud.githubusercontent.com/assets/13800920/22853777/1598ff88-f05f-11e6-904e-01ed6b860489.png)

I've found a filechooser language pack in my MSYS2 installation. It contains the locale for the filechooser, context menu and messages. Copy the folder locale to `share\`
![unbenannt2](https://cloud.githubusercontent.com/assets/13800920/22853809/c171b07a-f05f-11e6-9638-f84fbfe6bb2c.PNG)

**Comment by gaaned92** [comment]
@TooWaBoo Thanks for cursors and langage pack. I include them in my builds.
Perhaps you noticed that there is a bug in the adwaita cursors folder as it contains no windows cursors (.cur files).
There  is an adwaita update correcting this bug (available on github) but it is not yet integrated in MSYS2.

**Comment by TooWaBoo** [comment]
@gaaned92 

> Perhaps you noticed that there is a bug in the adwaita cursors folder...

Yes, I know, but only these 5 cursors can be replaced in RT. All other cursors are either images or it uses the Windows cursors.
