### ISSUE TITLE
Thumbnail in queue distorted (gtk3)

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#3685]
Tested on Win7/64 using current dev code and gkt+ 3.18

To reproduce:

Open amsterdam.pef
Send to queue using the queue button at bottom
Go to queue

![thumbdistorted](https://cloud.githubusercontent.com/assets/13733487/22863513/a86b0ce2-f141-11e6-9cb6-4f476aa04267.png)

Works fine in gtk2. After restart of rt thumb is also fine again.

**Comment by gaaned92** [comment]
Cannot reproduce on W10, gtk3.22.7, branch dev 5.0-r1-gtk3-6-gf9bd9956

**Comment by heckflosse** [comment]
@gaaned92 Thanks for testing. Maybe it's an issue with gtk3.18

**Comment by gaaned92** [comment]
Tested also with 5.0-r1-gtk3-15-g82f4978c : ok

**Comment by Beep6581** [comment]
Cannot reproduce using any recent build, GTK+ 3.22.5.
But this problem has appeared sporadically over the years, long before GTK3.

**Comment by agriggio** [comment]
I still see this from time to time. Haven't been able to identify the exact reason yet

**Comment by heckflosse** [comment]
I can reproduce it 100% this way:

Start rt with empty queue
open amsterdam.pef
press add to queue button in editor
switch to queue

**Comment by agriggio** [comment]
thanks Ingo, this helps. I'll try to take a look

**Comment by Beep6581** [comment]
I still cannot reproduce. Maybe it's related to the window and panel sizes or to the information included in the thumbnail (image name, date, focal length, font size for this info, etc.)?

**Comment by heckflosse** [comment]
Maybe it also helps to know how it's not reproducible:

Start rt with empty queue
Switch to queue
Switch to file browser
open amsterdam.pef
press add to queue button in editor
switch to queue

**Comment by agriggio** [comment]
@heckflosse Ingo, it seems I spoke too soon (again :-) 
I can't reproduce here with your instructions. Can you be a bit more detailed? What processing profile are you using? Does it happen if you set it to neutral? What layout do you use for RT? Maybe you can attach screenshots of all the steps?

**Comment by heckflosse** [comment]
@agriggio Alberto, here are some screenshots. I copied amsterdam.pef to a new folder and applied neutral profile. Then closed and started rt with an empty queue:

![dt_01](https://cloud.githubusercontent.com/assets/13733487/25775383/4892caf4-32a4-11e7-9406-a732d23839d2.png)

Opened amsterdam.pef from file browser:

![dt_02](https://cloud.githubusercontent.com/assets/13733487/25775392/80cee376-32a4-11e7-925d-2d760278b8c7.png)

Pressed the add to queue button at bottom and switched to queue:

![dt_03](https://cloud.githubusercontent.com/assets/13733487/25775400/b52f1e9c-32a4-11e7-84e7-672a137df104.png)

**Comment by agriggio** [comment]
thanks, I'll try again later

**Comment by agriggio** [comment]
still no luck... :-/ I'll try other ways of reproducing, but there's a high chance this is not going to be fixed for 5.1

**Comment by heckflosse** [comment]
@agriggio Alberto, I see no problem not fixing that for 5.1 because imho it's only a temporary problem (e.g. after restart of rt queue shows a correct thumb and it also has no influence on final output). And I really appreciate your efforts to solve that issue :+1:

**Comment by heckflosse** [comment]
@agriggio Alberto, when I force refreshThumbnailImage() as in this hack it works fine:

```
diff --git a/rtgui/thumbbrowserentrybase.cc b/rtgui/thumbbrowserentrybase.cc
index 6fa8eac..31afc06 100644
--- a/rtgui/thumbbrowserentrybase.cc
+++ b/rtgui/thumbbrowserentrybase.cc
@@ -416,7 +416,7 @@ void ThumbBrowserEntryBase::resize (int h)
         width = bsw + 2 * sideMargin + 2 * borderWidth;
     }
 
-    if ( preh != old_preh || width != old_width ) {
+    if ( true || preh != old_preh || width != old_width ) {
         delete [] preview;
         preview = nullptr;
         refreshThumbnailImage ();

```

**Comment by Beep6581** [comment]
@heckflosse could you upload your options file?
Can you reproduce it in Sabayon?

**Comment by heckflosse** [comment]
As I'm on gtk+ 3.22 now, I can't reproduce the issue anymore => closing.
