### ISSUE TITLE
Feature suggestion: Lens correction enhacement

### ISSUE THREAD

**Issue by Eneen** [Beep6581/RawTherapee#3688]
Hi,

I've got idea to enhance current lens correction system. Current one is very similar to CameraRaw system: automatic correction + manual 1 parameter correction and it is designed to rather "have good profile" then manual correction.
Idea is to bring parameters from LCP to RT UI under "Advanced Lens correction" tickbox, so all loaded parameters from profile are visible or can just be entered into empty value-boxes or set by sliders.
1. Expose all distortion parameters to UI to provide perfect manual correction when there is need to (currently I think only hugin is able to do this):
- additionally correct automatic correction due to lack of correction for specific shooting distance inside profile
- for new or unknown lenses like when working with jpeg files
- manual defishing without profile
2. Expose shooting distance, aperture value and sensor size parameters to UI for:
- older camera bodies with no shooting distance info
- jpeg files without exif (it's really great that RT works with jpegs too!)
3. Expose all chromatic aberration parameters similar to distortion one.
4. Maybe ability to save LCP as replacement for tool from adobe.

Best regs.

**Comment by Beep6581** [comment]
Handled by #3826
