### ISSUE TITLE
White Balance shows wrong values when opening a file whichs wb method is 'Auto'

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#3690]
To reproduce:
Open amsterdam.pef
Set Auto WB
rt shows the calculated values for Temperature and Tint, fine
![awb00](https://cloud.githubusercontent.com/assets/13733487/22939583/6f6fa1a6-f2df-11e6-9fee-9506157d9999.png)
reopen amsterdam.pef
rt shows the hard coded default values for Temperature and Tint...
![awb01](https://cloud.githubusercontent.com/assets/13733487/22939658/b43eba74-f2df-11e6-89d4-22fc50d07cf0.png)

I will try to fix that.

**Comment by Beep6581** [comment]
See #3221.

**Comment by heckflosse** [comment]
@Beep6581 I hope I can fix it soon :)
