### ISSUE TITLE
Co,flict between PS CC2017 and RT5 ?

### ISSUE THREAD

**Issue by baobob35** [Beep6581/RawTherapee#3695]
Dell studio in WIN 7 Pro Adobe CC2017 RT 5 last release
Unable to open PS 2017 after having run RT CC opens, Bridge opens
Restarting the computer solves the problem
Bob

**Comment by Beep6581** [comment]
@baobob35 could you edit your post and describe the problem more clearly?

**Comment by Beep6581** [comment]
We don't fix PS2017 bugs.
