### ISSUE TITLE
Critical update TooWaBlue v2.44, Gtk3 Bugfix

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#3696]
Bugfix: see forum https://discuss.pixls.us/t/solved-critical-bug-in-toowablue-theme/3328
[TooWaBlue-GTK3-20_.txt](https://github.com/Beep6581/RawTherapee/files/776822/TooWaBlue-GTK3-20_.txt)
[TooWaBlue-Dark-GTK3-20_.txt](https://github.com/Beep6581/RawTherapee/files/776823/TooWaBlue-Dark-GTK3-20_.txt)

Rename .txt to .css

**Comment by TooWaBoo** [comment]
ping @Beep6581

**Comment by Beep6581** [comment]
@TooWaBoo thank you, committed.

It would be less error-prone and easier for both of us if you could submit pull requests instead:
https://help.github.com/articles/fork-a-repo/
https://help.github.com/articles/creating-a-pull-request-from-a-fork/
