### ISSUE TITLE
Make sure Windows installer runs "release" exe by default

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3699]
Re: https://www.dpreview.com/forums/post/59134142

@gaaned92 @sguyader please make sure that the Windows installer creates a shortcut which points to `rawtherapee.exe` and that if the user ticks the option to automatically run RawTherapee after installation has finished then it runs this release `rawtherapee.exe`, not `rawtherapee-debug.exe`.

https://github.com/Beep6581/RawTherapee/blob/dev/tools/win/InnoSetup/WindowsInnoSetup.iss.in#L126
I don't know what `#StringChange` is there for, maybe try removing it as per
http://www.jrsoftware.org/ishelp/topic_runsection.htm

Please confirm when you have seen this.

**Comment by sguyader** [comment]
I was wondering this because a user at dpreview reported that it ran the debug exe the first time he launched the program. But I checked the last installer I made (from the Dev branch) and by default it launched the correct release exe.

**Comment by Beep6581** [comment]
It's dpreview - PEBKAC not excluded ;)

**Comment by sguyader** [comment]
I don't know what PEBKAC is. Anyways, the user reported slowness in RT run right after installation, somebody asked if he was running the debug executable, and after loading the release executable, RT was running fast.
By the way, I do read and sometimes write on Dpreview 😊

**Comment by heckflosse** [comment]
@sguyader I was the 'somebody' :)

**Comment by heckflosse** [comment]
@sguyader PEBKAC: „Problem exists between keyboard and chair“

**Comment by gaaned92** [comment]
I already verified that the installer launches by default the release exe. Cannot launch the debug unless you manually modify shortcuts. edit or you launch it manually

**Comment by Beep6581** [comment]
So both installers are verified to use the "release" exe, and the innosetup script seems correct... must be PEBKAC.

Thank you for your attention. Closing.

**Comment by sguyader** [comment]
Why was this issue open at first?

**Comment by heckflosse** [comment]
@sguyader Sébastien, because a user reported that debug.exe was started during installation process:
https://www.dpreview.com/forums/post/59134142
And we thought there might have been a bug in installer.

**Comment by heckflosse** [comment]
@sguyader Sébastien, read ogni backwards ;-)

**Comment by sguyader** [comment]
@heckflosse OK! I thought you had another nickname at Dpreview. So we're talking about the same user. The only one apparently...
