### ISSUE TITLE
Grey-out tools which do not work for certain files

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#3704]
Some tools in rt only work on raw files, some only on bayer raw files, some only on bayer and xtrans  raw files, some (soon) only on multi-frame raw files and so on...

This issue is to discuss how to improve the gui for this cases.

For tiff, jpeg and png files we could simply disable the raw-tab

For raw files the situation is a bit more complex as there are several types of files and not all tools work for each type. Here is a short summary of the tools in raw-tab.

`+` means the tool works, 
`-` means the tool does not work and it's not possible to make it work
`?` means the tool does not work and I don't know whether it's possible to make it working
`p` means the tool does not work and I think it's possible to make it working (in theory at least)

```
                           bayer  xtrans  demosaiced raw

raw ca correction            +      p          -
flat field                   +      +          p
dark frame                   +      +          +
raw white point              +      +          +
raw black point              +      +          ?
False Colour suppression     +      +          p
line noise filter            +      ?          ?
green equilibration          +      ?          ?
hot/dead pixel filter        +      +          p
```

**Comment by reggybe** [comment]
For tiff, jpeg and png files we could simply disable the raw-tab: **+1**
For the others: a change in some of those sliders (raw ca correction, flat field, false colour suppression, hot/dead pixel filter)  should invoke the whole toolchain of demosaicing from the beginning. The already done edits in the other tabs should be saved previously in a temporary pp3-file (or the clipboard) that is reloaded after the demosaicing and then deleted. This will of course take some time, but not that much.

**Comment by heckflosse** [comment]
@reggybe 

> For the others: a change in some of those sliders (raw ca correction, flat field, false colour suppression, hot/dead pixel filter) should invoke the whole toolchain of demosaicing from the beginning.

It already does!

**Comment by Beep6581** [comment]
@heckflosse is there a difference between "demosaiced raw" and the missing "non-raw"?

**Comment by heckflosse** [comment]
@Beep6581 'Demosaiced' raw files (or better 3-channel raw files) are lossy dng, Canon mraw, Canon sraw and Foveon.
non-raw files are tiff, jpeg and png. For the non-raw files we could simply grey-out the raw tab

**Comment by Beep6581** [comment]
Is there a functional difference between "3-channel raw files" and plain TIFFs? Do "3-channel raw files" have the same white levels as raw, are they white-balanced, etc?

**Comment by heckflosse** [comment]
Forgot to close the issue as I [commited](https://github.com/Beep6581/RawTherapee/commit/52e8668aee35e028b009e3e0f97be9bf116f4a15) the changes
