### ISSUE TITLE
Thumbnails fail when switching directory after queue processing

### ISSUE THREAD

**Issue by reggybe** [Beep6581/RawTherapee#3705]
After processing a queue with several files, and then switching to another directory with imagefiles for editing, the thumbnails are not drawn on the screen. The info about how many files there are in the directory is OK. So I have to quit RT and restart it. This happens with all directories. The image files are on a external hard drive. 

Info:
Version: 5.0-r1-gtk3
Branch: releases
Commit: 50114c1a
Commit date: 2017-02-01
Compiler: gcc-5 5.3.1
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.20.1
Build type: release
Build flags: -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -std=gnu++11  -Werror=unused-label -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG
Link flags:   
OpenMP support: ON
MMAP support: ON

Version from openSuSe for Leap 42.2
Desktop HP Compaq 8200 Elite Pro, Intel Core i5 pro 3300Mhz, 8GB RAM

Reggybe

**Comment by heckflosse** [comment]
@reggybe 

> The info about how many files there are in the directory is OK

Does it show 0/n or n? Can you post a screenshot?

**Comment by reggybe** [comment]
Thanks for the tip. Found the solution. I used a starrating filter, but didn't deactivate it after the processing. The issue can be closed.

BTW: thanks for all the speedups and fixes youdid already.

**Comment by heckflosse** [comment]
Thanks for the feedback :+1: 
Though my tip was a bit hidden ;-)
