### ISSUE TITLE
Speedup for lcp vignetting correction

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#3707]
I just created a [new branch](https://github.com/Beep6581/RawTherapee/tree/lcpvignette_speedup) to speedup lcp vignetting correction.

I tested with a D800 file

Before changes: 76 ms
after changes using non SSE2 code: 34 ms
after changes using SSE2 code: 19 ms

I detected no differences in output.

Ingo

**Comment by heckflosse** [comment]
I made some additional measures because my 8-core amd really is restricted by speed of ram:

I tested without use of omp:

processing time with new code on 1 core is 62 ms compared to old code on 8 cores which was 76 ms.
That clearly shows:

1. the memory in my machine is too slow to scale with the 8 cores
2. using SSE2 code can lead to big improvements
3. The processing time of 19ms on 8 cores is almost the max speed I can get on that machine

**Comment by heckflosse** [comment]
One additional note: 
You may ask why I made this speedup because 76 ms already was fast.:
When processing pentax pixelshift files each of the 4 frames has to go through lcp vignetting correction in case a lcp profile with vignetting  correction is selected. That multiplies the processing time for this step by factor 4

**Comment by heckflosse** [comment]
I pushed some further changes:

I tested with 2 files (a lossy DNG 20 MP file and a D800 file) on 1 core and on 8 cores:

Measured in dev:
```
lossy dng 1 core      300 ms
lossy dng 8 cores      74 ms
D800 1 core           448 ms
D800 8 cores           76 ms
```
Measured with new code:
```
lossy dng 1 core      107 ms
lossy dng 8 cores      32 ms
D800 1 core            32 ms
D800 8 cores           18 ms
```

**Comment by Floessie** [comment]
@heckflosse May I do some cleanups (not speedups) here?

**Comment by heckflosse** [comment]
@Floessie absolutely :+1:

**Comment by Floessie** [comment]
@heckflosse 99309aa4ace072af51ce74614153c805ad13db9d has a little cleanup. There could be much more, perhaps in the next days. As for speed, I only changed `param0Sqr` to `float` and used float constants where applicable (everywhere, in fact).

**Comment by heckflosse** [comment]
@Floessie Thanks a lot for the cleanup!
About param0Sqr: It's calculated only once per file. For that reason I explicitly set it to double precision.

**Comment by Beep6581** [comment]
Hey guys, small hint: if your first commit in a new branch contains only the inclusion of timers and nothing more, it would make it easier for people like me to get you a before/after time!

**Comment by heckflosse** [comment]
@Beep6581 Agreed. I will do that for the next speedup!

**Comment by heckflosse** [comment]
@Floessie I pushed again :)

**Comment by heckflosse** [comment]
Arghh, I'm not happy with the current astlye. Maybe I will revert my last commit :(
