### ISSUE TITLE
Problem with commit - Extra fields

### ISSUE THREAD

**Issue by salvadhor** [Beep6581/RawTherapee#3709]
Hi,

Since commit dfdcacfa52c63149811b679ed156cefdb9a3408a Launchpad has problem to get source code from github:

```
  File "/srv/importd.launchpad.net/production/launchpad-rev-18326/bzrplugins/git/mapping.py", line 334, in import_commit
    raise UnknownCommitExtra(commit, [item[0] for item in commit.extra])
bzrlib.plugins.git.errors.UnknownCommitExtra: Unknown extra fields in <Commit dfdcacfa52c63149811b679ed156cefdb9a3408a>: ['HG:rename-source'].
Import failed:
Traceback (most recent call last):
```

It's obviously exception in code of LP, but is it possible to fix this on Github side? Message 'Unknown extra fields' means, that we have something extra there. 

best regards,

**Comment by Beep6581** [comment]
Hey @salvadhor 
Report to https://bugs.launchpad.net/bzr-git/+bugs maybe they know of a solution.
Related: https://bugs.launchpad.net/bzr-git/+bug/1372149
