### ISSUE TITLE
locallab Gtk3 wrong #ExpanderboxID

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#3714]
@Desmis 

Found a bug in the gui. The expander for local lab is using a wrong ID.

Curently the ID is set to **#ExpanderBox** but should be **#Expanderbox2**.
Comparing with the Wavelet expander there should be set a level which assigns the correct expander ID.
It looks OK in the RawTherapee theme, 'cause every border is set but in the TooWaBlue theme the ID **#Expanderbox** is handled totally different.

```
snip wavelet.cc
    expsettings->add(*settingsVBox);
    expsettings->setLevel(2);
    pack_start (*expsettings);

    expcontrast->add(*levBox);
    expcontrast->setLevel(2);
    pack_start (*expcontrast);

    expchroma->add(*chBox);
    expchroma->setLevel(2);
    pack_start (*expchroma);

    exptoning->add(*tonBox);
    exptoning->setLevel(2);
    pack_start (*exptoning);

    expnoise->add(*noiseBox);
    expnoise->setLevel(2);
    pack_start (*expnoise);

    expedge->add(*edgBox);
    expedge->setLevel(2);
    pack_start (*expedge);

    expgamut->add(*conBox);
    expgamut->setLevel(2);
    pack_start (*expgamut);

    expresid->add(*resBox);
    expresid->setLevel(2);
    pack_start(*expresid);

    expfinal->add(*finalBox);
    expfinal->setLevel(2);
    pack_start(*expfinal);
```

The expander ID is set in guiutils.cc
```
snip guiutils.cc
void ExpanderBox::setLevel(int level)
{
    if (level <= 1) {
        set_name("ExpanderBox");
    } else if (level == 2) {
        set_name("ExpanderBox2");
    } else if (level >= 3) {
        set_name("ExpanderBox3");
    }
}
```

**Comment by Desmis** [comment]
I just push a change with for each expander
expxxx->setLevel (2);

:)

**Comment by TooWaBoo** [comment]
Thanks, looks much nicer now (95%). But I've found some hardcoded styling which should be removed. :-)
Delete all lines which contains **...->set_border_width...** and **...->set_spacing...**
After doing this the look will be identical to Wavelet.

![unbenannt](https://cloud.githubusercontent.com/assets/13800920/23303031/f3dee0e6-fa91-11e6-90b7-aba67cbc3bb4.PNG)

**Comment by Beep6581** [comment]
Looks good!

**Comment by TooWaBoo** [comment]
btw: Local LAB is a mix of functions from Exposure, Detail  and Color like the Wavelet. Wouldn't it be better to move Local LAB to the Wavelet tab?

**Comment by Desmis** [comment]
If locallab was originally set to this place, it is because the "locallab" module uses L*a*b* functions (such as Lab adjustements, Tone mapping, CBDL, etc.). ..but not directly "wavelet").

I find that this module, now, given its "volume", to facilitate access, should have an independent place, like "exposure", or "details", or "color", or "wavelet" ...
It's a simple code shift ...

But it is necessary to:
1) that everyone agrees on this change of location
2) that a decision is made by the group, on what one does of "locallab"

But, reminder, I leave on vacation tomorrow morning for the Caribbean, for a fortnight. This does not prevent debate
:)

**Comment by TooWaBoo** [comment]
Puh, this was fast but you missed one line.

```
    pack_start (*expsettings);

-->    colorVBox->set_spacing (2);
//   colorVBox->set_border_width (4);
```
I wish you a nice vacation. :-)

**Comment by Desmis** [comment]
Done :)
Thank you

**Comment by TooWaBoo** [comment]
Everything is fixed now. I close this issue. Found another issue but i will open a new issue for that.
