### ISSUE TITLE
History message conflict between AWB bias and Local LAB

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#3716]
Local L*A*B* and AWB bias are sharing the same message ID in the branch locallab-dev, file: default.
HISTORY_MSG_444;Local L*a*b*
HISTORY_MSG_444;WB - Temp bias

**Comment by Desmis** [comment]
Done :)

**Comment by TooWaBoo** [comment]
You are fast as hell. :-)
I close this issue
