### ISSUE TITLE
5.0-r1-gtk2 on win7sp1 32 -- what():  std::bad_alloc

### ISSUE THREAD

**Issue by master-nemo** [Beep6581/RawTherapee#3718]
Hi,

use RawTherapee 5.0-r1-gtk2
get "this application has requested the runtime to terminate it in an unusual way. " when start exporting 

my system:
windows 7 sp1 32bit

what I tried to do:
reinstall all VCredists for all versions
reinstall RawTherapee 5.0-r1-gtk2, 
trying dev versions 
RawTherapee 5.0-r1-gtk2 5.0-r1-gtk2
RawTherapee 5.0-r1-gtk3 5.0-r1-gtk3

nothing helps (

here is what `rawtherapee_debug.exe` says:
```
E:\Program Files\RawTherapee\5.0-r1-gtk2>rawtherapee_debug.exe
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```

PS: About memory. somewhere I read what similar error with bad_alloc might be raised at low memory situation: so no: 8Gb memory installed and at least 5+Gb is free when it crashes.

**Comment by TooWaBoo** [comment]
>  8Gb memory installed and at least 5+Gb is free when it crushes.

...but you are on a 32bit system. One application can't use your whole memory. Even if you install 100GB it won't help.
Look at here https://github.com/Beep6581/RawTherapee/issues/3577 there you'll find some usefull hints.

**Comment by heckflosse** [comment]
Independent on the amount of memory in your machine the following is still true for 32bit windows:
https://msdn.microsoft.com/en-us/library/bb613473(VS.85).aspx

**Comment by master-nemo** [comment]
Thanks. I already have done 4-Gigabyte Tuning years ago and live with it without problems.
![2017-02-26_17-56-59](https://cloud.githubusercontent.com/assets/1632320/23340777/32ae1780-fc4d-11e6-85a5-51cd4d9f6a62.png)
![rep](https://cloud.githubusercontent.com/assets/1632320/23340783/454d54f0-fc4d-11e6-9259-8d5d04e617c8.jpg)

BTW: I also tried to export with small target size (900px at long side UPD: and 200 too): and get same error

**Comment by heckflosse** [comment]
It seems it crashes at 2 GB which could mean that the 4GB-Tuning is not active. Can you check that please?
Without that, each program can not use more than 2 GB on your system

**Comment by heckflosse** [comment]
@master-nemo I just tried processing a D800 (36 Mp) file using the 32bit version of rt (exactly the one you used) on my 64bit Windows 7. Worked fine.

**Comment by Beep6581** [comment]
> I also tried to export with small target size (900px at long side UPD: and 200 too): and get same error

@master-nemo output image size is completely irrelevant to the amount of required memory (in fact enabling resizing could require more memory). It's the input image size and the tools you use which matter.

> trying dev versions
RawTherapee 5.0-r1-gtk2 5.0-r1-gtk2
RawTherapee 5.0-r1-gtk3 5.0-r1-gtk3

Those are not dev versions. Get dev builds from https://discuss.pixls.us/t/download-rawtherapee-development-builds/2924

P.S. It's "crash" not "crush".

**Comment by master-nemo** [comment]
thanks for answers. 

@heckflosse
> It seems it crashes at 2 GB 

![2017-02-26_18-22-40](https://cloud.githubusercontent.com/assets/1632320/23343146/dc759c3c-fc77-11e6-99a8-df569797e117.png)
and system can use more 
![2017-02-26_22-57-57](https://cloud.githubusercontent.com/assets/1632320/23343165/142a429a-fc78-11e6-9670-63f22dcbd464.png)

But thanks for idea: i'll check if 1 process can use >2GB.

@Beep6581, I agree to you about memory to processing RAW itself. But when I used LR on system with low memory then exporting small versions helps: same size (~24MP) export failed, but ~2048 worked. So I just tried this at RT. 
And thanks for grammar correction (and sorry for any future mistakes).

PS: thanks again for answers. I'll check your ideas

**Comment by heckflosse** [comment]
@master-nemo 

> But when I used LR on system with low memory then exporting small versions helps: same size (~24MP) export failed, but ~2048 worked. So I just tried this at RT.

When you export an image in rt all processing before resize, which is the second last step before export, is done at full size of image! Only `post-resize-sharpening` is between `resize` and `save`

**Comment by master-nemo** [comment]
Thansk all for answers: indeed `increaseuserva` option was lost on last reinstall. sorry for bothering you for nothing.

**Comment by heckflosse** [comment]
@master-nemo Thanks for the feedback :+1: Greatly appreciated!
Can we close the issue?

**Comment by master-nemo** [comment]
@heckflosse, I think it would be right (to close issue)
thanks again
