### ISSUE TITLE
Support Exif and XMP rating tag

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3728]
RawTherapee could speak with other contemporary software regarding photo ratings if it used the `xmp:Rating` tag.

The XMP specification part 1 (April 2012) has this to say about `xmp:Rating`:
> A user-assigned rating for this file. The value shall be -1 or in the range [0..5], where -1 indicates “rejected” and 0 indicates “unrated”. If xmp:Rating is not present, a value of 0 should be assumed. NOTE Anticipated usage is for a typical “star rating” UI, with the addition of a notion of rejection.

Depends on #463.

**Comment by Beep6581** [comment]
RawTherapee stores color labels and ranks in the `.pp3` files. It would be nice if it could read this info from Exif and XMP tags if an entry in the PP3 does not exist.

**Comment by Beep6581** [comment]
See https://discuss.pixls.us/t/get-the-ranking-file-property-into-rawtherapee/5253

**Comment by lewicki-pk** [comment]
Hi.

What is the status of this issue?

I'm using RawTherapee with DigiKam (second one for exporting, viewing, filtering and rating) and this feature is for me essential to complete my workflow.

**Comment by Beep6581** [comment]
Closing as handled by #4403
