### ISSUE TITLE
Shadows & highlights tool causing black patches (with white edges) in dark areas when Sharp mask is disabled and large radius is used

### ISSUE THREAD

**Issue by Blizzara** [Beep6581/RawTherapee#3730]
Hi,

Using the shadows & highlights tool causes these weird patches on images with high contrasts and dark areas. The issue is visible only in the final jpg (or png, didn't try tiff) output, not on the preview. See images below for an example, files (.CR2 included) also available [here](https://avo.kapsi.fi/IMG_1510.zip). Toggling S&H on/off should toggle the bug also.

![S&H ON](https://cloud.githubusercontent.com/assets/1384385/23592355/3ab04bc2-0208-11e7-8571-70d6d04671be.jpg)
![S&H OFF](https://cloud.githubusercontent.com/assets/1384385/23592356/3d5e5878-0208-11e7-9d4f-1039d31202e5.jpg)

Version: 5.0-r1-gtk3
Branch: releases
Commit: 50114c1a
Commit date: 2017-02-01
Compiler: x86_64-linux-gnu-gcc 5.4.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.18.0
Build type: Release
Build flags: -O3 -std=gnu++11  -Werror=unused-label -fopenmp -Werror=unknown-pragmas
Link flags:  -Wl,-Bsymbolic-functions -Wl,-z,relro
OpenMP support: ON
MMAP support: ON

Thanks,
-Arttu

**Comment by heckflosse** [comment]
Issue confirmed!

**Comment by heckflosse** [comment]
@Blizzara It's clearly an Issue with using large gauss sigma (radius). Should be solvable. I will take a deeper look tomorrow!

**Comment by Blizzara** [comment]
ff5919b seems to fix the problem - I tested four previously buggy images, and could not reproduce the artifacts anymore. Thanks for a very quick fix!
-Arttu

**Comment by heckflosse** [comment]
@Blizzara Thanks for testing and feedback :+1:

**Comment by Beep6581** [comment]
Reproduced in raw from first comment and in one of my concert shots, and confirmed that ff5919be4abbcdd4d1d29125bb2b8f424c880af1 fixes it.

**Comment by heckflosse** [comment]
@Beep6581 Thanks for testing :+1:

**Comment by Beep6581** [comment]
Thanks for patching :+1: :+1:
