### ISSUE TITLE
Mimetype issues with panasonic RW2

### ISSUE THREAD

**Issue by ff2000** [Beep6581/RawTherapee#3732]
Dolphin didn't want to open the raws from my brand new Panasonic G81. Tracked it down to different naming of the rw2 mimtypes.
freedesktops shared-mime-info specifies it as "image/x-panasonic-raw2":
https://cgit.freedesktop.org/xdg/shared-mime-info/tree/freedesktop.org.xml.in#n4659
while Rawtherapee specifies "image/x-panasonic-rw2":
https://github.com/Beep6581/RawTherapee/blob/dev/rtdata/icons/rawtherapee.desktop.in#L16

Is this an error in RawTherapee or shared-mime-info?

**Comment by heckflosse** [comment]
Exiv2 also specifies `image/x-panasonic-rw2`
http://dev.exiv2.org/projects/exiv2/wiki/Supported_image_formats

**Comment by ff2000** [comment]
Thx, so this is an issue in shared-mime-info. Will create an issue there ASAP.

**Comment by ff2000** [comment]
Fixed in shared-mime-info:
https://bugs.freedesktop.org/show_bug.cgi?id=100078

**Comment by Floessie** [comment]
@ff2000 Great! Especially that you found the exiv2 link! :+1:
