### ISSUE TITLE
RawTherapee theme window decoration issue

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#3733]
The client side decoration of the RawTherapee theme has an issue by displaying on a dark background.
The titlebar has the same color as the background. I've made some changes to the theme (copied from the TooWaBoo theme). If you like them, you can take it. :-)
I also centered the labels of the OK, Cancel ... buttons.

[RawTherapee-mod-GTK3-20_.txt](https://github.com/Beep6581/RawTherapee/files/821441/RawTherapee-mod-GTK3-20_.txt)

Original theme
![unbenannt2](https://cloud.githubusercontent.com/assets/13800920/23613564/4190f824-0280-11e7-957f-a967f4d003c7.PNG)

Modified theme
![unbenannt](https://cloud.githubusercontent.com/assets/13800920/23614376/00f9c018-0283-11e7-997b-c5b25646bfaa.PNG)

These are the changes I did.

**Start at line 53**
```
/*** Window decoration *********************************************************/
@define-color winHeaderbar rgb(50,50,50);

:not(.popup):not(tooltip) > decoration {
    background-color: #484848;
    background-image: none;
    border-radius: 5px 5px 0 0;
    border: none;
    padding: 0;
    box-shadow: 0 3px 9px 1px rgba(0, 0, 0, 0.5), 0 0 0 1px #242424;
    margin: 10px;
}
headerbar {
    background-color: shade(@winHeaderbar,1.12);
    box-shadow: inset 0 1px rgba(200,200,200,.13);
    background-image: linear-gradient(shade(@winHeaderbar,1.14), shade(@winHeaderbar,.86));
    border-bottom: 1px solid #242424;
    border-radius: 5px 5px 0 0;
    min-height: 26px;
    padding: 1px 5px 0;
    margin: 0 0 1px 0;
}

/* Window state */
.maximized > headerbar {
    border-radius: 0;
}
/**/

/*** End Window decoration *****************************************************/
```

**Start at line 205**
```
/* Save, Cancel, OK ... buttons */
.dialog-action-area button {
    min-height: 24px;
    margin-top: 6px;
}
/**/
```

**Comment by Beep6581** [comment]
Thank you @TooWaBoo . Looks fine in Linux, merged.
