### ISSUE TITLE
Documentation of dynamic processing profiles

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3736]
Hello @agriggio 

Thank you very much for the new feature!
Now that the code is committed, documentation needs to be written for it. Could you sign up for a RawPedia account, then let me know so that I can give you edit permissions? Alternatively you could describe it here and I will help get it up onto RawPedia, though it would be easier if we did it there straight away.

**Comment by agriggio** [comment]
@Beep6581 I just signed up (username `agriggio`). I need to wait for the account to be created I suppose, right?

**Comment by Beep6581** [comment]
Correct.
Your account is now created and you have edit permissions. Let me know if you need help.

**Comment by agriggio** [comment]
Thanks. It might take a couple of days before I will write it though - I hope it's not a problem

**Comment by Beep6581** [comment]
Not at all! It came to mind when I wanted to write about it on G+ but didn't know what to write, and am busy with some other things at the moment so I won't have time to learn it. Could you ~summarize~ advertize here in a short paragraph what it lets the user do?

**Comment by agriggio** [comment]
For now, would this (almost) copy-paste from pixls.us do? (slightly edited now)

The idea of the "Dynamic" profile builder is to allow you to define some rules
(based on the EXIF metadata of the picture, like camera name, ISO, etc.) for
automatically applying a sequence of (partial) processing profiles the first
time you edit a picture with RT.

There is a new mode, "(Dynamic)", to the "Default Processing Profile" option
(in the "Image Processing" tab of the preferences dialog), which activates the
functionality.

Then, you need to define your custom rules. This is done again via the
preferences dialog, under the new tab "Dynamic Profile Rules". Here's a
screenshot:

![rt-custom](https://cloud.githubusercontent.com/assets/11982086/23634384/38d8c00a-02ca-11e7-9d41-1a5cce92a05f.png)


Each rule lets you define the conditions for application (e.g. a given camera
model and/or lens, shutter speed, and so on) of the selected processing
profile.  When you edit a picture for the first time, the list of rules is
scanned, and all the profiles that match are combined (in the order given, so
later rules can override earlier ones) to build the initial .pp3 file.

**Comment by Beep6581** [comment]
@agriggio great, here is the post: https://plus.google.com/+rawtherapee/posts/7u9a8uAmYV3
Do you use g+? If so, I could tag you in the post.

**Comment by agriggio** [comment]
I just subscribed, but I'm not really into social networks to be honest... :-)

**Comment by agriggio** [comment]
I've created a bare-bones page, see
http://rawpedia.rawtherapee.com/Dynamic_processing_profiles
Feel free to edit for content, style and formatting :-)
(or if you want me to elaborate on something, just ask and I'll see what I can do)

**Comment by TooWaBoo** [comment]
@agriggio 

What theme are you using in your sreenshot? It doesn't look like the RawTherapee nor a TooWaBlue theme.

**Comment by agriggio** [comment]
@TooWaBoo I'm using the default. What makes you think it is not the case? I might have changed the font (I don't remember), but if so only through the preferences dialog. I didn't touch any CSS

**Comment by TooWaBoo** [comment]
>  What makes you think it is not the case?

Sorry, my fault. It's a long time that I saw the Gtk3.**18** theme. It looks totally different to Gtk3.20 version.

**Comment by agriggio** [comment]
@TooWaBoo no problem :-)
BTW, I've expanded the documentation a little bit. Feedback is welcome!

**Comment by agriggio** [comment]
can we close this? the docs are in rawpedia
