### ISSUE TITLE
Improve handling of checkButtons in code

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#3739]
This is a request to get help from @Floessie,  @Hombre57 and also from @agriggio 

Let me explain:

When a checkbutton is used in gui (and there currently are a lot of checkbuttons for pixelshift code) we always have a connector.

For example in `rtgui/rawcacorrection.h` we have
`Gtk::CheckButton* caAutocorrect;`
and
`sigc::connection caacsconn;`

And in `rtgui/rawcacorrection.cc` we have
`caacsconn = caAutocorrect->signal_toggled().connect ( sigc::mem_fun(*this, &RAWCACorr::caCorrectionChanged), true);`

In my local pixelshift code I already made a class `myCheckButton` in `guiutils.h` and I want to implement the functionality mentioned above in that class to get rid of that amount of sigc::connection declarations (as I mentioned, pixelshift has more than one checkButton).

What would be the best way to do that?

Ingo

**Comment by Hombre57** [comment]
`rtgui/adjuster.h` define a class that handle all aspect of the sliders. So I'd rather create dedicated `rtgui/checkbox.h|cc` files to do the same with checkboxs, because it will have to handle the GUI for the Batch Tool Panel too.

If it doesn't answer your question, could you explain better ?

**Comment by heckflosse** [comment]
@Hombre57 Let me expain it better :)

Currently I made this to get rid of the bools which are needed to handle checkButtons correctly:
guiutils.h:
```
/**
 * @brief subclass of Gtk::CheckButton in order to handle the last active state
 */
class MyCheckButton : public Gtk::CheckButton
{

    bool lastActive;
public:
    using CheckButton::CheckButton;
    void setLastActive() {lastActive = get_active();};
    void setLastActive(bool active) {lastActive = active;};
    bool getLastActive() {return lastActive;};
};
```

And then in e.g. rawcacorrection.cc instead of
```
    lastCA  = pp->raw.ca_autocorrect;
.
.
.
.

        } else if (lastCA) {
            caAutocorrect->set_inconsistent (true);
        }

        lastCA = caAutocorrect->get_active ();
```

I can use 
```
caAutocorrect->setLastActive(pp->raw.ca_autocorrect);
.
.
.
.
.
        } else if (caAutocorrect->getLastActive()) {
            caAutocorrect->set_inconsistent (true);
        }

        caAutocorrect->setLastActive();
    }

```
This way I don't have to declare a boolean for each checkButton, which simplifies the code.

Now I want to do similar with the signal connectors for the checkButtons

**Comment by Floessie** [comment]
@heckflosse Am I right, that your real question is about passing the action function to `signal_toggled.connect()`? I'd suggest to call a [`std::function`](http://en.cppreference.com/w/cpp/utility/functional/function) via a `sigc::mem_fun` proxy. Maybe the proxy could be omitted [if the return type is `void`](http://stackoverflow.com/questions/13805883/use-lambda-in-connection-with-sigc-library), but more research is needed to come up with a possible solution.

**Comment by agriggio** [comment]
thanks for involving me :-) I'll have a look at the code and think about it. To be honest, though, the dynamic profile GUI was my first "serious" thing with GTK, so I doubt I can be of much help... I'm definitely interested in the conversation however!

**Comment by Hombre57** [comment]
@heckflosse Have you pushed these changes in a branch ?

**Comment by heckflosse** [comment]
@Hombre57 I pushed to pixelshift branch. As discussed on irc, here are my changes related to avoid sigc::connection objects and the booleans to handle state of checkButtons in gui header files to simplify gui code

https://github.com/Beep6581/RawTherapee/blob/pixelshift/rtgui/guiutils.h#L266

And for example: 

https://github.com/Beep6581/RawTherapee/blob/pixelshift/rtgui/bayerprocess.cc#L319

**Comment by Hombre57** [comment]
I've done some work on this but I'll need some advice soon. I should to be able to push something by Saturday.

**Comment by Hombre57** [comment]
I've finished my patch. May I push it to psgtk3 or should I open a PR ?

**Comment by heckflosse** [comment]
@Hombre57 feel free to push to psgtk3

**Comment by Hombre57** [comment]
Pushed to psgtk3.

I'd like to make the parent `Gtk::CheckButton` class private (to avoid mixing up uses of the child and parent class), but it doesn't build because of the constructor. If you want to have a look, it's on line 46 of `rtgui/checkbox.h`.

If you manage make it private, you should enable the commented out methods at the end of this files (and in the *.cc file). Otherwise, this can be deleted.

**Another note :** in a general manner, widgets should always be visible in Batch editing, that's why I've surrounded the `show` and `hide` methods by `if (!batchMode)`

**Comment by heckflosse** [comment]
@Hombre57 Maybe @Floessie can help on making it private?

**Comment by Floessie** [comment]
@Hombre57 @heckflosse Not even [I]( https://github.com/Beep6581/RawTherapee/issues/3048#issuecomment-250542150) can do this. :grin:

 `private` inheritance means, everything is private, even the knowledge about base classes. There's a good answer to this on [stackoverflow](http://stackoverflow.com/a/9661959).

But what about the copyright notice in `checkbox.*`? The file wasn't written by Gabor in 2010...

Best,
Flössie

**Comment by Hombre57** [comment]
@Floessie There's no clear copyright policy on any of RT files. The last thing I heard was keep the Gabor copyright 2008-2010 and avoid any other copyright, despite some did included one. I don't even know what I should have stated if I had to.

**Comment by Hombre57** [comment]
> @Hombre57 @heckflosse Not even I can do this.

Haha, good one ! 🤣

**Comment by agriggio** [comment]
@Hombre57 when I added a couple of new files for the dynamic profiles features, I put a copyright like this:

```
 *  Copyright (c) 2017 Alberto Griggio
```

because I assumed that the policy was to indicate the original author of the file. However, feel free to change it if you think it is wrong!

**Comment by Hombre57** [comment]
@agriggio Nope, I'll change mine (and for other files too). Thanks for the hint. However I'd like to have a comment from @Beep6581 first.

**Comment by Floessie** [comment]
... who is still in Uganda until the weekend.

> Nope, I'll change mine (and for other files too).

:+1:

**Comment by Hombre57** [comment]
I've committed a patch to update de copyright note of the 2 new files. I'll change others after discussion with Emperor of this repository (i.e. @Beep6581)

**Comment by heckflosse** [comment]
@Hombre57 :+1: for adding your copyright to your code! I did the same for pixelshift code a while ago.

**Comment by Beep6581** [comment]
Files written by Gabor need to retain his name in the GPL header - the copyright owner grants the permissions as stated in the licence (GPL) to others. Files not written by him need to indicate who the original copyright holder is. It cannot be him, as he cannot claim authorship over code he did not write. So if writing a new file then copy the licence header and replace the copyright notice with your name, date and contact address (email). When editing someone else's file you can but don't have to add (not replace) your name to the copyright list, or even to the function in question.

> I'll change others after discussion with Emperor of this repository

<falls of chair> :rofl:

**Comment by Hombre57** [comment]
@Beep6581 Understood.

Can we close ?

**Comment by heckflosse** [comment]
@Hombre57 Yes, we can. And thanks for the new checkBox class :+1:
