### ISSUE TITLE
Bad artifacts (white pixels) with the attached pp3 and ARW

### ISSUE THREAD

**Issue by agriggio** [Beep6581/RawTherapee#3742]
RAW file from here:
https://pixls-discuss.s3.amazonaws.com/original/2X/f/fe651efcce1684b4f1d8f3cda2d65d821752f24d.ARW

PP3 in attach (adjust the path to the "FUJI Provia 100 Generic" film simulation, and take the lens correction profile from Adobe DNG converter). The result is in the attached jpg.

Bisect says the culprit is 6e7712831a5e146aa694165cc488a3b7230c669f

![dsc03922-4](https://cloud.githubusercontent.com/assets/11982086/23713598/bd557afa-0426-11e7-973b-2b9936f2385e.jpg)
[bad.pp3.txt](https://github.com/Beep6581/RawTherapee/files/828285/bad.pp3.txt)

**Comment by Floessie** [comment]
@agriggio Alberto, as you are already at it, could you bisect it further?

1. Replace all new `constexpr` with `inline` again.
2. Make those functions depending on `min/max()` use `std::min/max()`.
3. Change `min/max()` to the [older](https://github.com/Beep6581/RawTherapee/commit/6e7712831a5e146aa694165cc488a3b7230c669f#diff-557116a6e0a898ee051eb7356bded351L58) recursive form.

You should find the real problem along the way. :+1:

**Comment by heckflosse** [comment]
I guess the real cuprit is [here](https://github.com/Beep6581/RawTherapee/blob/dev/rtengine/curves.h#L998). For dark parts we get a division by zero.

**Comment by Floessie** [comment]
That would also be a good place for the new `constexpr max()`. :wink:

**Comment by heckflosse** [comment]
Using std::min and std::max in `LIM()` function fixes it...

**Comment by Floessie** [comment]
@heckflosse That's strange. It's basically the [default](http://en.cppreference.com/w/cpp/algorithm/min) implementation without the braces. Precedence issue (although I'm pretty sure those braces are not needed)?

**Comment by Floessie** [comment]
My GCC 6.3 libstdc++ has this:
```c++
  template<typename _Tp>
    _GLIBCXX14_CONSTEXPR
    inline const _Tp&
    min(const _Tp& __a, const _Tp& __b)
    {
      // concept requirements
      __glibcxx_function_requires(_LessThanComparableConcept<_Tp>)
      //return __b < __a ? __b : __a;
      if (__b < __a)
	return __b;
      return __a;
    }
```

**Comment by Floessie** [comment]
@heckflosse Does this fix it?

```patch
diff --git a/rtengine/rt_math.h b/rtengine/rt_math.h
index e1c01a94..a49d8962 100644
--- a/rtengine/rt_math.h
+++ b/rtengine/rt_math.h
@@ -42,7 +42,7 @@ constexpr const T& min(const T& a)
 template<typename T>
 constexpr const T& min(const T& a, const T& b)
 {
-    return a < b ? a : b;
+    return (b < a) ? b : a;
 }
 
 template<typename T, typename... ARGS>
@@ -60,7 +60,7 @@ constexpr const T& max(const T& a)
 template<typename T>
 constexpr const T& max(const T& a, const T& b)
 {
-    return a < b ? b : a;
+    return (a < b) ? b : a;
 }
 
 template<typename T, typename... ARGS>
```

**Comment by heckflosse** [comment]
@Floessie 0.0 / 0.0 returns a nan.

if a is nan then
`return b < a ? b : a` should return a
while
`return a < b ? a : b` should return b

or vice versa?

**Comment by heckflosse** [comment]
@Floessie building...

**Comment by heckflosse** [comment]
@Floessie yes, that fixes it

**Comment by Floessie** [comment]
@heckflosse Are those braces needed? I guess not...

I'll commit after your answer.

**Comment by heckflosse** [comment]
@agriggio @Floessie 

maybe we should also test and probably apply this patch?

```
diff --git a/rtengine/curves.h b/rtengine/curves.h
index 3487720..0970060 100644
--- a/rtengine/curves.h
+++ b/rtengine/curves.h
@@ -995,6 +995,7 @@ inline void LuminanceToneCurve::Apply(float &r, float &g, float &b) const
 
     float currLuminance = r * 0.2126729f + g * 0.7151521f + b * 0.0721750f;
     float newLuminance = lutToneCurve[currLuminance];
+    currLuminance = currLuminance == 0.f ? 0.00001f : currLuminance;
     float coef = newLuminance / currLuminance;
     r = LIM<float>(r * coef, 0.f, 65535.f);
     g = LIM<float>(g * coef, 0.f, 65535.f);

```

**Comment by heckflosse** [comment]
@Floessie braces are not needed

**Comment by Floessie** [comment]
> or vice versa?

Don't know by heart. Maybe I'll do some research tomorrow.

Okay, I'll commit both now!

**Comment by heckflosse** [comment]
:+1:

**Comment by Floessie** [comment]
@agriggio Please test and close.

**Comment by agriggio** [comment]
works now, so closing

**Comment by Beep6581** [comment]
Bug confirmed and fix confirmed.
