### ISSUE TITLE
Add on/off for every tool

### ISSUE THREAD

**Issue by X-Raym** [Beep6581/RawTherapee#3745]
Hi !

Some groups of settings have a toggle on/off button.

But some haven't like the Exposure table.

[https://monosnap.com/file/nY2STTSz8nkUPWBsE6rtIHFVprAnzq.png](https://monosnap.com/file/nY2STTSz8nkUPWBsE6rtIHFVprAnzq.png)

It would be nice to have it for every groups of parameter to quickly toggle before / after of several parameters.

Thanks for listening !

**Comment by Thanatomanic** [comment]
I don't think this is an actual issue. It pertains only to the Exposure tab, which is such an elemental tool (and it can be easily reset if necessary, and brought back from the history).

**Comment by Beep6581** [comment]
Yes, most tools now have an on/off switch, and there's no need for this issue to linger.

**Comment by X-Raym** [comment]
@Thanatomanic it was not about reset but about quick A/B comparison.
