### ISSUE TITLE
Pressing Shift hover sliders make them flick

### ISSUE THREAD

**Issue by X-Raym** [Beep6581/RawTherapee#3747]
Hi !

We can press <kbd>Shift</kbd> hover a slider to adjust value. Cool !

But on Windows 10 x64,

- it highlights the last touched slider (even if the mouse isn't hover it)
- it makes the slider flick very quickly

![screenshot](http://i.imgur.com/6c5EXfM.gif)

Thanks !

**Comment by heckflosse** [comment]
@X-Raym 

I really tried to answer you, but that animated gif above was so disturbing...
I know that often pictures are more informative than text, but clearly not in this case!
Please describe the issue in clear words!

Ingo

**Comment by TooWaBoo** [comment]
@X-Raym 

Which RT version are you using? (Preferences -> About -> Version)


I couldn't reproduce this behaviour.

This is my version

```
Version: 5.0-r1-gtk3-124-gb84e570f
Branch: dev
Commit: b84e570f
Commit date: 2017-03-09
Compiler: gcc 6.3.0
Processor: undefined
System: Windows
Bit depth: 64 bits
Gtkmm: V3.22.0
Build type: release
Build flags: -mwin32 -m64 -mthreads -msse2 -std=c++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -mwindows -Wno-aggressive-loop-optimizations -DNDEBUG -O3
Link flags: -m64 -mthreads -static-libgcc -march=native -mwindows -s -O3
OpenMP support: ON
MMAP support: ON
```

**Comment by heckflosse** [comment]
@X-Raym After understanding your issue I can confirm it on Win7/64 gtk3.18

As soon as I hold the shift-key the last active slider flickers (in gtk3 builds)

Edit: It's not the last active slider which flickers but the last changed slider.

**Comment by TooWaBoo** [comment]
It flickers, 'cause the Shift key switches the slider between normal and fine tune mode. Holding the Shift key switches between these modes very fast. So it's not a bug?

There are two different functions on the same key.

**Comment by heckflosse** [comment]
@TooWaBoo I don't know if that's a bug :(

@X-Raym Hint for further issues: Developers and testers (especially developers) act like machine. Means, speaking prosa is suboptimal. You have have to give clear instructions about how to reproduce an issue to not waste their spare time :)

**Comment by X-Raym** [comment]
@heckflosse 
Hi !
Sorry if my report wasn't clear enough, I made dev too so I know how frustrating bad reports can be. I was in a hurry cause it is already 03:30am here... ^^

Here are my infos:
```Version: 5.0-r1-gtk3  
Branch: 5.0-r1-gtk3  
Commit: 50114c1  
Commit date: 2017-02-01  
Compiler: gcc 5.3.0  
Processor: generic x86  
System: Windows
Bit depth: 64 bits
Gtkmm: V3.18.0
Build type: release
Build flags: -m64 -mwin32 -mthreads -std=gnu++11 -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -msse -msse2 -mwindows -fopenmp -Wno-aggressive-loop-optimizations -DNDEBUG -O3
Link flags: -m64 -mwin32 -mthreads -static-libgcc -mtune=generic -mwindows -s -O3
OpenMP support: ON
MMAP support: ON
```

As you can reproduce now... is there anything else you miss ?

**Comment by X-Raym** [comment]
@TooWaBoo 
Maybe it is not a bug but it certainly looks weird.
Having two actions on the same button swtiching from one to ther other at somewhere arround 25hz is a bit unexpected ^^

Also, I am not sure to see any difference for mousewheel between the normal and fine tune mode.

Not that if you press <kbd>SHIFT</kbd> then <kbd>ALT</kbd>, the flickering stops.

**Comment by TooWaBoo** [comment]
@X-Raym 

I'm not sure, but I think this is a GTK and not a RT bug. In Gtk3.22 the Shift key doesn't toggle between normal and fine tune mode.

**Comment by X-Raym** [comment]
@TooWaBoo
Do you want me to test with another build of RT ?

**Comment by TooWaBoo** [comment]
There is no need to test with another build, but if you want to try the latest **dev**elopement version (Gtk3.22), you can download it from here: https://drive.google.com/drive/folders/0B2q9OrgyDEfPS2FpdDAtMVI1RG8

**Comment by X-Raym** [comment]
@TooWaBoo 
I confirm, the *5.0-r1-gtk3-124-gb84e570f* version doesn't seem to have this problem. Cool !

I close the issue then (we can still reopen later if needed).

Thanks you for your support :)

**Comment by Beep6581** [comment]
I can't make sense of the text in the first post, but the fact that the slider can change height is not a bug. GTK3 lets you put the slider into "normal" or "fine" adjustment mode using Shfit, and the height change if your indicator of that. If that has changed, if that no longer works, then that is the bug.

**Comment by Beep6581** [comment]
I confirm that there is a bug: current dev does not give any feedback as to the slider's state. It used to work before. The slider should go thick when it's in fine adjustment mode.

Issue #3751 opened.

**Comment by TooWaBoo** [comment]
> GTK3 lets you put the slider into "normal" or "fine" adjustment mode using Shfit

Gtk3.18 does, Gtk3.22 doesn't. To switch into fine tune mode you have to click on the slider and hold it for 2 sec. without moving. The behaviour in Gtk3.18 (Shift toggles between the two modes) doesn't make sence, 'cause it has no effect when you move the sliders with the keys and when you use the mouse you have to click and this switches the fine tune mode off.

> The slider should go thick when it's in fine adjustment mode.

In Gtk3.18. the height of the slider in fine tune mode was automatically set. In Gtk.3.22 you have to explicitly define it in css. Checkout the TooWaBlue theme (Line 618).

**Comment by TooWaBoo** [comment]
@Beep6581 

If you want, I can add it to the RT theme.

**Comment by Beep6581** [comment]
@TooWaBoo the feature works the same in 3.22.9 as it did in 3.18 and probably in 3.16 too. Click-hold or shift-click the knob to trigger it. The user gets feedback in the form of the slider height changing.

> doesn't make sence, 'cause it has no effect when you move the sliders with the keys and when you use the mouse you have to click and this switches the fine tune mode off.

I'm not sure what you mean, but the feature does make sense and is usable in RawTherapee. Maybe it's broken in Windows?

I just confirmed that the feature works correctly and is usable in RT when using GTK+3.22.9/Linux and not using our custom CSS themes.

The purpose of issue #3751 is to get it working correctly again using our themes.

**Comment by TooWaBoo** [comment]
> I just confirmed that the feature works correctly and is usable in RT when using GTK+3.22.9 and not using our custom CSS themes.

Confirmed, works in Windows too.

It looks like setting the dimensions in the theme is overwriting the fine tune functionality. That's why you have to define the fine tune state in the css too.

Insert this at line 246 in the RT theme to get back the feedback for the fine tune mode in Gtk>3.20

```
scale.fine-tune trough {
    margin: 5px;
    padding: 1px;
}
scale.fine-tune trough highlight {
    margin: -2px;
}
```

**Comment by TooWaBoo** [comment]
> ...Click-hold or shift-click the knob to trigger it...

In Gtk3.18 the fine tune mode toggles on/off without clicking anything just by holding the Shift key like rapid fire in a game and this makes no sense.

**Comment by Beep6581** [comment]
@TooWaBoo that must be specific to Windows, as it works fine in GTK+ 3.18 in Linux. The slider should change modes only on the shift press event - holding shift should not make it cycle modes.

Could you delete all RT CSS files and see whether it works correctly using GTK+ 3.22 in Windows?

**Comment by TooWaBoo** [comment]
> Could you delete all RT CSS files and see whether it works correctly using GTK+ 3.22 in Windows?

I already did and it works fine with Gtk3.22
