### ISSUE TITLE
Slider mode no longer gives visual feedback

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3751]
GTK3 lets you put the slider into "normal" or "fine" adjustment mode using Shfit, and the height change if your indicator of that. Current dev does not give any feedback as to the slider's state. It used to work before. The slider should go thick when it's in fine adjustment mode.

**Comment by TooWaBoo** [comment]
Insert this at line 246 in the RT theme to get back the feedback for the fine tune mode in Gtk>3.20

```
scale.fine-tune trough {
    margin: 5px;
    padding: 1px;
}
scale.fine-tune trough highlight {
    margin: -2px;
}

```

**Comment by gaaned92** [comment]
@
Windows10 gtk3.22.9 : slider goes thick

**Comment by TooWaBoo** [comment]
@gaaned92 

Where did you get Gtk3.22.**9** for Windows?
Did you test with the RT or the TWB theme?

**Comment by gaaned92** [comment]
@TooWaBoo 
I just made an update of MSYS2 : pacman -Syu


```
-- Found PkgConfig: C:/msys64/mingw64/bin/pkg-config.exe (found version "0.29.1")
-- Checking for module 'gtk+-3.0>=3.16'
--   Found gtk+-3.0, version 3.22.9
-- Checking for module 'glib-2.0>=2.44'
--   Found glib-2.0, version 2.50.3
-- Checking for module 'glibmm-2.4>=2.44'
--   Found glibmm-2.4, version 2.50.0
-- Checking for module 'gtkmm-3.0>=3.16'
--   Found gtkmm-3.0, version 3.22.0
```
I tested  with the RT theme only. I dont know where to insert correction in TWB theme

**Comment by TooWaBoo** [comment]
> ...where to insert correction...

Have you done the test with the modification above?
The TWB theme doesn't have this issue, 'cause I'm sizing everything.

` Found gtk+-3.0, version 3.22.9`
I get the same message, but "AboutThisBuild" shows Gtk3.22.0

**Comment by gaaned92** [comment]
For the TWB you are right.

AboutThisBuild shows the gtkmm-3 version and not the gtk+-3 version.  gtkmm version is the last line of the pasted message above.
Perhaps AboutthisBuild should be modified as gtk+ version is more informative.
From Gnome: "gtkmm is the C++ API for GTK+, with bindings for other GNOME libraries too". This API seems to be stable.

**Comment by TooWaBoo** [comment]
Ahh, thanks, now I get it.

**Comment by gaaned92** [comment]
@TooWaBoo 
Will this fix be included in Beep6581/RawTherapee ?

**Comment by TooWaBoo** [comment]
Will be done soon.
https://github.com/Beep6581/RawTherapee/pull/3757
