### ISSUE TITLE
Browse all files in folder and subfolders recursively

### ISSUE THREAD

**Issue by ronanM** [Beep6581/RawTherapee#3756]
Add the possibility to view all files of a dir tree (recursively). Like in `XnViewMP`, `Lightroom`, etc.

**Comment by X-Raym** [comment]
+1 for this feature, would be very handy !

**Comment by rogerwalt** [comment]
+1 👍 😎

**Comment by lorthirk** [comment]
+1 :smile:

**Comment by vladshut** [comment]
+1

**Comment by josephaaroncampbell** [comment]
+1. Yes please add this. would be incredibly helpful.

**Comment by andrzejdus** [comment]
+1

**Comment by Cmonsta6** [comment]
Would appreciate this

**Comment by Shurshev** [comment]
+1

**Comment by Oxize** [comment]
Has this be implemented or not? I cant find it. Would be so usefull. I have an Canon directoryh, and below that are all my dates. With lightroom you could only add the directory Canon, and it added all photo's in the subdirs (dates with photos)

**Comment by Lawrence37** [comment]
Yes, this issue was closed as completed by #6769. Recursive browsing is available in the development version and will appear in the 5.11 release.

**Comment by Oxize** [comment]
Any ETA for 5.11?
