### ISSUE TITLE
Suggestion to save some vertical space in rt queue tab

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#3758]
![queue](https://cloud.githubusercontent.com/assets/13733487/23838658/34d116c4-0798-11e7-898a-9bc4208f04bb.png)

**Comment by TooWaBoo** [comment]
In Gtk3.22 it looks like this:
![unbenannt](https://cloud.githubusercontent.com/assets/13800920/23841503/12d7915e-07ae-11e7-92e8-f9336935966e.PNG)

I will ckeck if I can add the frame in Gtk3.18.

**Comment by TooWaBoo** [comment]
In Gtk3.18 I can't set space between frames and the thumbnail area. I guess, that's why I didn't add the frames. Gtk3.18 lacks a lot of css features.
![q](https://cloud.githubusercontent.com/assets/13800920/23843649/b1ebe2d6-07bd-11e7-8791-f76a8f39a082.PNG)

So, what shall we do? :-)

**Comment by heckflosse** [comment]
Looks good on gtk > 3.18. I was confused by the double `file format`. Now it makes sense. I close the issue
