### ISSUE TITLE
Wavelet Gtk3.18 GUI issue

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#3759]
There is a GUI issue (look at the frame) in the Wavlet tool only for the "Wavelet Settings" expander in **Gtk3.18**, but in **Gtk3.22** it looks OK.

RT theme
![unbenannt](https://cloud.githubusercontent.com/assets/13800920/23854096/1a5b74bc-07f0-11e7-88a9-e8719d277237.PNG)

TWB theme
![unbenannt2](https://cloud.githubusercontent.com/assets/13800920/23854108/28973dae-07f0-11e7-9eed-57aed57f193d.PNG)

**Comment by Hombre57** [comment]
@TooWaBoo Should be solved with commit 3660ed5. Could you test ?

**Comment by TooWaBoo** [comment]
I can only compile Gtk3.22 and the test was successful.
@heckflosse or @agriggio are still on Gtk3.18, perhaps they can test it.

**Comment by Hombre57** [comment]
Tested with my virtual machine, and works fine with Gtk3.18. Closing.

**Comment by heckflosse** [comment]
@Hombre57 :+1:
