### ISSUE TITLE
Remove "Profile fill mode" 

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#3761]
I'm thinking about the "Profile fill mode" button. For me, it doesn't make sense. I didn't find any usefull scenario where I would use this feature and I suggest to remove it.

![1816c33792d8f2f0af08f677bb0341cae7849d65](https://cloud.githubusercontent.com/assets/13800920/23953359/a410cf18-0994-11e7-892b-73138e9b6a2f.PNG)

A discussion is also done here:
https://discuss.pixls.us/t/loading-this-pp3-file-changes-setting-it-should-not-change/3485/5

**Comment by agriggio** [comment]
Any opinions on this? I actually use the feature so I'd vote for it to stay...

**Comment by TooWaBoo** [comment]
You can close it if this feature makes sense for you.

**Comment by Beep6581** [comment]
It's a useful feature with no other way of getting the same result. Usability could be improved, but I'll open a new issue for that at some point.
