### ISSUE TITLE
Region shown in detail window magically moves to centre of preview when using - button to zoom out the detail window

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#3764]
To reproduce:

Open an image in editor
Open a new detail window and place the area it shows outside the centre of the preview, like this:
![detail00](https://cloud.githubusercontent.com/assets/13733487/24005456/598ac3e2-0a69-11e7-8171-976abdd6d86b.png)
Then click the - button top of the detail window.
Now the area the detail window shows is centre of preview...
![detail01](https://cloud.githubusercontent.com/assets/13733487/24005514/845e2cee-0a69-11e7-8fde-f15703379783.png)

**Comment by heckflosse** [comment]
@agriggio Can we close this? Seems to be fixed in dev.

**Comment by agriggio** [comment]
yes I think so

**Comment by heckflosse** [comment]
Ok
