### ISSUE TITLE
Incorrect zooming with lens correction profiles

### ISSUE THREAD

**Issue by agriggio** [Beep6581/RawTherapee#3765]
It seems lens correction profiles interact badly with zooming. Using an image
with an active lens profile makes RT compute wrong zooms when the level is >=
33%: basically the image becomes huge (see screenshot).

* zoom at 25%
![zoom-25](https://cloud.githubusercontent.com/assets/11982086/24021791/fa296180-0aa2-11e7-8788-4f169793f8a9.png)

* zoom at 33%
![zoom-33](https://cloud.githubusercontent.com/assets/11982086/24021795/016669ca-0aa3-11e7-9b34-172769071418.png)

**Comment by heckflosse** [comment]
@agriggio Yes, that's caused by auto-fill. There already is a very old issue about that somewhere

**Comment by agriggio** [comment]
Ok. I tried to search but didn't see anything "obviously" related...

**Comment by heckflosse** [comment]
@agriggio #3400 for example

**Comment by agriggio** [comment]
@heckflosse ah, I was searching for open issues. this is so annoying I'd like to fix it. any suggestions on where to start?

**Comment by heckflosse** [comment]
@agriggio Maybe [start here](https://github.com/Beep6581/RawTherapee/blob/dev/rtengine/iptransform.cc#L1067) ?

**Comment by agriggio** [comment]
@heckflosse :+1: I'll see what I can do

**Comment by agriggio** [comment]
@heckflosse this seems to work for me. Can you give it a try? (It seems that
LCP distortion correction should be applied to the full-size image to be
accurate)

```
diff --git a/rtengine/iptransform.cc b/rtengine/iptransform.cc
--- a/rtengine/iptransform.cc
+++ b/rtengine/iptransform.cc
@@ -948,7 +948,7 @@
     double hpteta  = fabs(hpalpha - rtengine::RT_PI / 2) < 3e-4 ? 0.0 : acos ((hpdeg > 0 ? 1.0 : -1.0) * sqrt((-oH * oH * tan(hpalpha) * tan(hpalpha) + (hpdeg > 0 ? 1.0 : -1.0) * oH * tan(hpalpha) * sqrt(16 * maxRadius * maxRadius + oH * oH * tan(hpalpha) * tan(hpalpha))) / (maxRadius * maxRadius * 8)));
     double hpcospt = (hpdeg >= 0 ? 1.0 : -1.0) * cos (hpteta), hptanpt = tan (hpteta);
 
-    double ascale = params->commonTrans.autofill ? getTransformAutoFill (oW, oH, pLCPMap) : 1.0;
+    double ascale = params->commonTrans.autofill ? getTransformAutoFill (fW, fH, pLCPMap) : 1.0;
 
     bool darkening = (params->vignetting.amount <= 0.0);
 

```

**Comment by heckflosse** [comment]
I tried with [amsterdam.pef](http://www.rawtherapee.com/shared/test_images/amsterdam.pef)
using this lcp
![lcp1](https://cloud.githubusercontent.com/assets/13733487/24047398/d6ecfc80-0b25-11e7-99a4-cd1dad206315.png)

Result:
![lcp2](https://cloud.githubusercontent.com/assets/13733487/24047408/dffde4c4-0b25-11e7-8da4-aebc3359a7a1.png)

**Comment by agriggio** [comment]
@heckflosse ok, I was too quick :smile: 
I'll try harder...

**Comment by agriggio** [comment]
@heckflosse this one should work better. It is still not perfect (e.g. if you
move the image on the screen, you get some weird results) but it's better than
before. I must admit I still don't understand what is happening exactly, it
seems that at certain zoom levels the computation of scale factor for the auto
adjust simply goes crazy. I suspect there is some sort of round-off error that
makes the binary search algorithm always fail. I'll try to investigate more,
but perhaps you can test this in the meantime?

```
diff --git a/rtengine/improcfun.h b/rtengine/improcfun.h
--- a/rtengine/improcfun.h
+++ b/rtengine/improcfun.h
@@ -54,7 +54,7 @@
 
     void calcVignettingParams(int oW, int oH, const VignettingParams& vignetting, double &w2, double &h2, double& maxRadius, double &v, double &b, double &mul);
 
-    void transformPreview       (Imagefloat* original, Imagefloat* transformed, int cx, int cy, int sx, int sy, int oW, int oH, int fW, int fH, const LCPMapper *pLCPMap);
+    void transformPreview       (Imagefloat* original, Imagefloat* transformed, int cx, int cy, int sx, int sy, int oW, int oH, int fW, int fH, const LCPMapper *pLCPMap, double ascale);
     void transformLuminanceOnly (Imagefloat* original, Imagefloat* transformed, int cx, int cy, int oW, int oH, int fW, int fH);
     void transformHighQuality   (Imagefloat* original, Imagefloat* transformed, int cx, int cy, int sx, int sy, int oW, int oH, int fW, int fH, const LCPMapper *pLCPMap, bool fullImage);
 
diff --git a/rtengine/iptransform.cc b/rtengine/iptransform.cc
--- a/rtengine/iptransform.cc
+++ b/rtengine/iptransform.cc
@@ -303,10 +303,27 @@
 
     if (!(needsCA() || needsDistortion() || needsRotation() || needsPerspective() || needsLCP()) && (needsVignetting() || needsPCVignetting() || needsGradient())) {
         transformLuminanceOnly (original, transformed, cx, cy, oW, oH, fW, fH);
-    } else if (!needsCA() && scale != 1) {
-        transformPreview (original, transformed, cx, cy, sx, sy, oW, oH, fW, fH, pLCPMap);
     } else {
-        transformHighQuality (original, transformed, cx, cy, sx, sy, oW, oH, fW, fH, pLCPMap, fullImage);
+        if (!needsCA() && scale != 1) {
+            double ascale = 1.0;
+            if (params->commonTrans.autofill) {
+                if (pLCPMap) {
+                    LCPProfile *pLCPProf =
+                        lcpStore->getProfile(params->lensProf.lcpFile);
+                    LCPMapper alcp(pLCPProf, focalLen, focalLen35mm,
+                                   focusDist, 0, false,
+                                   params->lensProf.useDist,
+                                   fW, fH, params->coarse, rawRotationDeg);
+                    ascale = getTransformAutoFill (fW, fH, &alcp);
+                } else {
+                    ascale = getTransformAutoFill (oW, oH, nullptr);
+                }
+            }
+            
+            transformPreview (original, transformed, cx, cy, sx, sy, oW, oH, fW, fH, pLCPMap, ascale);
+        } else {
+            transformHighQuality (original, transformed, cx, cy, sx, sy, oW, oH, fW, fH, pLCPMap, fullImage);
+        }
     }
 
     if (pLCPMap) {
@@ -907,7 +924,7 @@
 }
 
 // Transform WITH scaling, WITHOUT CA, simple (and fast) interpolation. Used for preview
-void ImProcFunctions::transformPreview (Imagefloat* original, Imagefloat* transformed, int cx, int cy, int sx, int sy, int oW, int oH, int fW, int fH, const LCPMapper *pLCPMap)
+void ImProcFunctions::transformPreview (Imagefloat* original, Imagefloat* transformed, int cx, int cy, int sx, int sy, int oW, int oH, int fW, int fH, const LCPMapper *pLCPMap, double ascale)
 {
 
     double w2 = (double) oW  / 2.0 - 0.5;
@@ -948,7 +965,7 @@
     double hpteta  = fabs(hpalpha - rtengine::RT_PI / 2) < 3e-4 ? 0.0 : acos ((hpdeg > 0 ? 1.0 : -1.0) * sqrt((-oH * oH * tan(hpalpha) * tan(hpalpha) + (hpdeg > 0 ? 1.0 : -1.0) * oH * tan(hpalpha) * sqrt(16 * maxRadius * maxRadius + oH * oH * tan(hpalpha) * tan(hpalpha))) / (maxRadius * maxRadius * 8)));
     double hpcospt = (hpdeg >= 0 ? 1.0 : -1.0) * cos (hpteta), hptanpt = tan (hpteta);
 
-    double ascale = params->commonTrans.autofill ? getTransformAutoFill (oW, oH, pLCPMap) : 1.0;
+//    double ascale = params->commonTrans.autofill ? getTransformAutoFill (oW, oH, pLCPMap) : 1.0;
 
     bool darkening = (params->vignetting.amount <= 0.0);
 

```

**Comment by heckflosse** [comment]
@agriggio Alberto, I really appreciate that you try to solve this issue :+1: I also spent a lot of hours trying to find a solution long time ago, but I failed :( Hopefully we'll find a solution. I will help wherever I can.
I'll try your patch tomorrow and report.

**Comment by agriggio** [comment]
@heckflosse here's a better attempt. This goes much closer than before to a proper solution. For me (still limited testing though) `transformPreview` works now. `transformHighQuality` has still some issues, but haven't figured out why yet.
[better-fix.patch.txt](https://github.com/Beep6581/RawTherapee/files/852293/better-fix.patch.txt)

**Comment by agriggio** [comment]
@heckflosse I believe I might have a solution. From my testing here, it seems to work. It's in the branch `issue3765-candidate-fix` of my fork.
There's one thing open, a TODO in `dcrop.cc`, which I'm happy to discuss. Other than that, I think I understand why the code was wrong and why the fix should work... there might still be some glitches but overall we should be on the right track.

**Comment by heckflosse** [comment]
@agriggio I will build and test now. What's that TODO you want to discuss?

**Comment by agriggio** [comment]
I'm not at the PC now, but I had to add a hardcoded factor to adjust the
crop when LCP distortion is enabled. ideally, the corrective factor should
be computed, and not estimated with a magic compile-time constant...

Il 18 Mar 2017 6:21 PM, "Ingo Weyrich" <notifications@github.com> ha
scritto:

**Comment by heckflosse** [comment]
@agriggio 
I tested you branch and found no issues :+1: 

> but I had to add a hardcoded factor

Can you point me to the line of code?

**Comment by agriggio** [comment]
@heckflosse [here you go](https://github.com/agriggio/RawTherapee/blob/issue3765-candidate-fix/rtengine/dcrop.cc#L1147)

**Comment by heckflosse** [comment]
@agriggio Thanks! Maybe @Beep6581 can test that. Iirc he has shots made with an ultrawide samyang lens and also has lcp files for this!

**Comment by agriggio** [comment]
@heckflosse a 15% distortion seems really huge to me for a "normal" lens. However, I have no idea about fisheye -- never used one :stuck_out_tongue: 
I'd appreciate if someone more knowledgeable can have a look and/or test, indeed!

**Comment by Beep6581** [comment]
Tested with Samyang 8mm + @TooWaBoo's LCPs and the zoom level works fine here.

**Comment by agriggio** [comment]
Great. I'll write a better commit message and push then
