### ISSUE TITLE
ThresholdAdjuster has no background gradient

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3769]
Using GTK+ 3.22.9 some ThresholdAdjuster, specifically the Color Toning ones, have no background gradient. CbDL works fine. This is not a CSS problem.

**Comment by Hombre57** [comment]
I'm taking that one.

**Comment by agriggio** [comment]
I pushed a tentative fix. Please test

**Comment by heckflosse** [comment]
@agriggio Works fine here on win7/64 :+1:

**Comment by Hombre57** [comment]
@agriggio I feel a bit bit ashamed about this issue. I'm the initial coder of that class, looked for 2h where that bug could be, but had no clue of the existence of `Surface::flush()` and `Surface::mark_dirty()`. How did you get to this ?

Thanks for the clean fix ! 👍

**Comment by agriggio** [comment]
@Hombre57 don't worry, nothing to feel ashamed! I just did the usual, tracked it down with gdb, then read the code, then read the docs, and a bit of luck ;-)

**Comment by waxhead** [comment]
Just built dev and ran RT quickly to confirm, and there it is, gradient colours showing in the split toning tool.

Many thanks for fixing it.

**Comment by Beep6581** [comment]
Fix confirmed, thank you!
