### ISSUE TITLE
File Open window double-click changes sort order

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3770]
1. Open the "Load a profile from file" dialog (reproducible using any dialog).
2. Left-click on a PP3 file.
3. Left-click any of the headers to change sort order, e.g. "Name" or "Size" or "Modified".
4. Double-click the PP3 file. Instead of opening the file, it behaves as if I clicked the header again, changing the sort order.

The dotted-line box which indicates which widget has focus remains on the header when I double-click on a file - perhaps that's a clue.

**Comment by Hombre57** [comment]
Those widgets are 100% handled by Gtk itself. I don't think we can do anything on this and would suggest to close this issue.

**Comment by Beep6581** [comment]
Fine with me.

**Comment by Beep6581** [comment]
P.S. GTK+ 3.22.9

**Comment by heckflosse** [comment]
P.S. was the same on GTK+ 3.18
