### ISSUE TITLE
CMake policy boolean issue CMP0012

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3771]
Report from Gentoo regarding CMake warnings generated by ebuild:

```
CMake Warning (dev) at /usr/share/cmake/Modules/FindOpenMP.cmake:179 (if):
  if given arguments:

    "TRUE"

  An argument named "TRUE" appears in a conditional statement.  Policy
  CMP0012 is not set: if() recognizes numbers and boolean constants.  Run
  "cmake --help-policy CMP0012" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindOpenMP.cmake:224 (_OPENMP_GET_SPEC_DATE)
  CMakeLists.txt:298 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.
```

and

```
/usr/share/cmake/Modules/FindOpenMP.cmake:266 (_OPENMP_GET_SPEC_DATE)
```

> CMP0012
if() recognizes numbers and boolean constants.
In CMake versions 2.6.4 and lower the if() command implicitly
dereferenced arguments corresponding to variables, even those named
like numbers or boolean constants, except for 0 and 1.  Numbers and
boolean constants such as true, false, yes, no, on, off, y, n,
notfound, ignore (all case insensitive) were recognized in some cases
but not all.  For example, the code "if(TRUE)" might have evaluated as
false.  Numbers such as 2 were recognized only in boolean expressions
like "if(NOT 2)" (leading to false) but not as a single-argument like
"if(2)" (also leading to false).  Later versions of CMake prefer to
treat numbers and boolean constants literally, so they should not be
used as variable names.
The OLD behavior for this policy is to implicitly dereference
variables named like numbers and boolean constants.  The NEW behavior
for this policy is to recognize numbers and boolean constants without
dereferencing variables with such names.
This policy was introduced in CMake version 2.8.0.  CMake version
3.6.3 warns when the policy is not set and uses OLD behavior.  Use
the cmake_policy command to set it to OLD or NEW explicitly.
.. note::
  The "OLD" behavior of a policy is
  "deprecated by definition"
  and may be removed in a future version of CMake.

**Comment by Floessie** [comment]
@Beep6581 I see this, too, for some time now. As the module is in `/usr/share/cmake/Modules/`, there is IMHO nothing we can do about it. Obviously, the `FindOpenMP.cmake` module shipped with cmake 3.7 isn't fully compatible with cmake 3.7. :wink:

**Comment by Beep6581** [comment]
Quote by Francesco Riosa:

```
This would be better fixed upstream adding:
if(POLICY CMP0012)
  cmake_policy(SET CMP0012 NEW)
endif()
```

**Comment by Beep6581** [comment]
@Floessie of course at the dead of night it flew right past me that this is not RT related :stuck_out_tongue:
But worth checking that our CMake file is behaving well - I'm still on CMake-3.6.
