### ISSUE TITLE
Locale files are not in sync with default

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#3776]
I wanted to make the German translation and have determined that the file is not synchronized with the latest version of the default file.

**Comment by Beep6581** [comment]
Here you go: https://filebin.net/o3luob5b11jwemns
From 5.0-r1-gtk3-291-gba7adbce but synced with default. I don't want to commit a sync of all other files until some merges are out of the way.

**Comment by TooWaBoo** [comment]
Ok, Thanks. I close it.
