### ISSUE TITLE
Distorted preview when image is flipped and a lcp-file is set

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#3778]
Distorted preview when image is flipped **and a lcp-file is set.**
The distortion change when you zoom in or out.

![unbenannt](https://cloud.githubusercontent.com/assets/13800920/24326823/c36de91a-11b7-11e7-92e2-35850e151e7c.PNG)

**Comment by agriggio** [comment]
I'll take a look ASAP

**Comment by agriggio** [comment]
working on a fix, if my tests are ok will commit later today

**Comment by agriggio** [comment]
I've just pushed a tentative fix. From my tests here it seems to work, but I'd appreciate some further stressing of it...

**Comment by TooWaBoo** [comment]
Tested. Works fine.

Good job. 👍

**Comment by agriggio** [comment]
Thanks. Closing then!
