### ISSUE TITLE
No way to change directory and folder...

### ISSUE THREAD

**Issue by artphotodude** [Beep6581/RawTherapee#3779]
Am trying to use Version 4.2, but I am having to literally manually type the path to each directory.  The File Browser tab does absolutely nothing when clicked on.  

While I am guessing there is a work-around, I must say, this is kinda' a deal breaker for any software to be unable to located files through the GUI.

Installed in Linux Mint Mate 17.3 (64-bit)

**Comment by heckflosse** [comment]
I would say it's a deal breaker to use old version 4.2 when 5.0 is already released and 5.1 is around the corner ;-)

**Comment by TooWaBoo** [comment]
Is this button on or off?
![unbenannt](https://cloud.githubusercontent.com/assets/13800920/24330557/cbc9275a-1220-11e7-8fbe-9e046818ee56.PNG)
