### ISSUE TITLE
Add DCI-P3 output color profile

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3782]
Here is a DCI-P3 color profile candidate for inclusion in RT as an output (and working?) profile:
https://filebin.net/aml2ssh7us2yt58e/DCI-P3.icc
I generated it using displaycal-synthprofile
@Desmis could you take a look?

**Comment by Desmis** [comment]
This profile is "between", AdobeRGB and BetaRGB.
 *Always smaller  than BetaRGB

* In comparison with AdobeRGB : bigger for red, and smaller for green

**Comment by Beep6581** [comment]
@Desmis thank you for taking a look, but my intention in asking was whether the profile looks and behaves correctly. I don't know how to properly test it.

**Comment by Beep6581** [comment]
@Desmis should we add this or not?

**Comment by Desmis** [comment]
@Beep6581 
I think you can :)

**Comment by Beep6581** [comment]
Done. 5fc2b1e1

I added ACES, and two variants of DCI-P3:
- DCI-P3 Theater (white point `x=0.314` `y=0.351)`
- DCI-P3 D65 (white point `x=0.3127` `y=0.329)`
