### ISSUE TITLE
Add ACES color profile

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3783]
Here is an ACES color profile candidate for inclusion in RT as an output (and working?) profile:
https://filebin.net/aml2ssh7us2yt58e/ACES.icc
I generated it using displaycal-synthprofile
@Desmis could you take a look?

**Comment by Desmis** [comment]
This profile is Huge, largely greater than Prophoto, for all colors (especially for red and blue), and all luminance
For what use ? All these color are not visible for an human.
Probably this profile will leads to artifacts, or bizarre behavior, but why not ?

Jacques

**Comment by Beep6581** [comment]
> For what use ?

It's not for me to decide what someone uses it for. I just want to know whether this specific profile which I generated has any defects or whether it's fine to include.

**Comment by Desmis** [comment]
I repeat : for what use ?
For me, it is a bad idea. From my point of view, already Prophoto is too
big,  with color out of human vision... and already leads to malfunction
for some tools, but here we are out, out, out...The only use I see, is by
comparison to see the limitation of a sensor camera. Not for photo usage :)

For me the best "big" profile is WidegamutRGB

Jacques

**Comment by Beep6581** [comment]
I am not concerned with reasons for using ACES (Analyzing sensors is one possible use, compatibility with other software where ACES is a standard is another). My concern is whether this profile is generated correctly and can be used with RT. 

Duplicate of #2083

**Comment by EmberLightVFX** [comment]
1+ to be able to develope the image to ACES AP0/AP1!
I work with VFX and one big hazzle is to convert raw image to ACES that is the industry standard in VFX. Currently the only software I know that can do this is Affinity Photo. Being able to do this in RawTherapee would be awesome!

ACES AP0 is a storage-colorspace. It's bigger than anything you could ever need, including every perceivable color so in the future when new standards arrive your media will be able to be converted to it with ease.
AP1 (ACEScg mostly) is a working colorspace. So to work within the colorspace more than just debayering the image, AP1 is the go-to colorspace.
