### ISSUE TITLE
Wrong entry in PartialPaste

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#3786]
There is a wrong entry in Partial Paste.
I guess "CA auto-correction strength" is used only in a test environment.

![unbenannt](https://cloud.githubusercontent.com/assets/13800920/24393092/0e086afa-1397-11e7-8a82-d56656a65051.PNG)

```
Version: 5.0-r1-gtk3-304-g209ea353
Branch: dev
Commit: 209ea353
Commit date: 2017-03-28
```

**Comment by Beep6581** [comment]
Please describe very briefly what #3786 is in the commit message to make git log messages easier to follow, e.g.
"Fixes uninitialized variables found by valgrind; removes CA Strength from partial paste dlg #3786".

It would save me some time figuring that out when I write the changelog in a few weeks ;)
