### ISSUE TITLE
Sporadic crashes when starting rt

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#3787]
Since some days (don't know exactly, maybe since two weeks) I get sporadic crashes when I start RT. It's not reproducible but I get at least one crash a day on Win7/64 and on Sabayon/64.

Am I the only one who experiences this?

Ingo

**Comment by agriggio** [comment]
confirmed, but I've seen this for much longer, not just a few days. I
thought it could be gtk3 because I don't remember it when I was on gtk2.
but it's very sporadic and I didn't have the time to (try to) nail it down

**Comment by Beep6581** [comment]
@heckflosse I had some sporadic crashes too in the last few weeks, though I haven't been using RT regularly enough to say whether this is new or how new. Same as @agriggio about not trying to nail it down.

**Comment by heckflosse** [comment]
@agriggio I also never got this startup crash using gtk2 builds.

**Comment by heckflosse** [comment]
Though it's a sporadic crash I would like to treat this as a critical bug.
Do you agree?

**Comment by Floessie** [comment]
> Do you agree?

Yep.

**Comment by agriggio** [comment]
agreed

**Comment by Desmis** [comment]
I agree, with gtk3, more sporadic crash than with gtk2

**Comment by heckflosse** [comment]
Locally I applied this patch:
```
diff --git a/rtgui/main.cc b/rtgui/main.cc
index 155d9f3..88dc4ea 100644
--- a/rtgui/main.cc
+++ b/rtgui/main.cc
@@ -119,11 +119,11 @@ int main(int argc, char **argv)
 {
     setlocale(LC_ALL, "");
     setlocale(LC_NUMERIC, "C"); // to set decimal point to "."
-    gtk_init (&argc, &argv);  // use the "--g-fatal-warnings" command line flag to make warnings fatal

     Glib::init();  // called by Gtk::Main, but this may be important for thread handling, so we call it ourselves now
     gdk_threads_set_lock_functions(G_CALLBACK(myGdkLockEnter), (G_CALLBACK(myGdkLockLeave)));
     gdk_threads_init();
+    gtk_init (&argc, &argv);  // use the "--g-fatal-warnings" command line flag to make warnings fatal
     Gio::init ();

     //mainThread = Glib::Threads::Thread::self();

```

because of [`This call must be made before any use of the main loop from GTK+; to be safe, call it before gtk_init().`](https://developer.gnome.org/gdk3/stable/gdk3-Threads.html#gdk-threads-init).

I also tried to remove the deprecated stuff but failed.

I'll work with above patch now for some days just for curiosity.

**Comment by ff2000** [comment]
Thx @heckflosse - the patch solved the startup crashes for me. It was nearly impossible for me to get into the folders from recent photo trips (which have way too many photos... new camera... xD). I now was able to open three such folders in a row without a crash.
BTW. I had two crashes while editing a photo, likely due to changing a parameter while RT was still busy working on the last change (it first froze completely, then crashed with a "double free or corruption"). Made me think there was something wrong with threading. As I am currently going through loads of photos I can give the patch a good test. "Fingers crossed".

**Comment by agriggio** [comment]
:+1: for merging this. even if it doesn't catch all the cases, it's still
better than `dev`
