### ISSUE TITLE
Compiling with -Wall shows a large amount of warnings which should be fixed

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#3790]
I want to try to make rt a bit more `-Wall`-clean.
I will start with compilation units in rtengine
Checked means it's clean. Unchecked means it's not clean or not tested yet.

- [x] colortemp.cc
- [x] curves.cc
- [x] flatcurves.cc
- [x] diagonalcurves.cc
- [x] dcraw.cc (fixed some warnings and disabled the remaining ones)
- [x] iccstore.cc
- [x] color.cc
- [x] dfmanager.cc
- [x] ffmanager.cc
- [x] gauss.cc
- [x] rawimage.cc
- [x] image8.cc
- [x] image16.cc
- [x] imagefloat.cc
- [x] imagedata.cc
- [x] imageio.cc
- [x] improcfun.cc
- [x] init.cc
- [x] dcrop.cc (Ingo)
- [x] loadinitial.cc
- [x] procparams.cc
- [x] rawimagesource.cc (Ingo)
- [x] demosaic_algos.cc (Ingo)
- [x] shmap.cc (Ingo)
- [x] simpleprocess.cc (Ingo)
- [x] refreshmap.cc
- [x] fast_demo.cc (Ingo)
- [x] amaze_demosaic_RT.cc (Ingo)
- [x] CA_correct_RT.cc (Ingo)
- [x] cfa_linedn_RT.cc (Ingo)
- [x] green_equil_RT.cc (Ingo)
- [x] hilite_recon.cc (Ingo)
- [x] expo_before_b.cc
- [x] stdimagesource.cc (nothing)
- [x] myfile.cc (Ingo)
- [x] iccjpeg.cc (nothing)
- [x] improccoordinator.cc (Ingo)
- [x] pipettebuffer.cc (Flössie)
- [x] coord.cc (Flössie)
- [x] processingjob.cc (Flössie)
- [x] rtthumbnail.cc (Flössie)
- [x] utils.cc (jacq)
- [x] labimage.cc (jacq)
- [x] slicer.cc (jacq)
- [x] cieimage.cc (jacq)
- [x] iplab2rgb.cc (jacq)
- [x] ipsharpen.cc (jacq)
- [x] iptransform.cc (jacq)
- [x] ipresize.cc (jacq)
- [X] ipvibrance.cc (jacq)
- [x] icons.cc (jacq)
- [x] imagedimensions.cc (jacq)
- [x] jpeg_ijg/jpeg_memsrc.cc
- [x] jdatasrc.cc (jacq)
- [x] iimage.cc (jacq)
- [x] EdgePreservingDecomposition.cc (jacq)
- [x] cplx_wavelet_dec.cc (jacq)
- [x] FTblockDN.cc (jacq)
- [x] PF_correct_RT.cc (jacq)
- [x] previewimage.cc (jacq)
- [x] ipwavelet.cc (jacq)
- [x] dirpyr_equalizer.cc
- [x] calc_distort.cc
- [x] lcp.cc
- [x] dcp.cc
- [x] ipretinex.cc
- [x] cJSON.c
- [x] camconst.cc
- [x] klt/convolve.cc
- [x] klt/error.cc
- [x] klt/klt.cc
- [x] klt/klt_util.cc
- [x] klt/pnmio.cc
- [x] klt/pyramid.cc
- [x] klt/selectGoodFeatures.cc
- [x] klt/storeFeatures.cc
- [x] klt/trackFeatures.cc
- [x] klt/writeFeatures.cc
- [x] clutstore.cc
- [x] ciecam02.cc (Ingo)
- [x] pixelshift.cc

**Comment by Floessie** [comment]
@heckflosse I don't see a branch, yet. I could join you from time to time.

**Comment by heckflosse** [comment]
@Floessie I will create a branch now after committing fixes for the compilation units at top of the list.
Maybe we should agree about the procedure to avoid double work. Kind of I start from top and you start from bottom until we meet (or vice versa)

**Comment by heckflosse** [comment]
@Floessie I created the new branch `wallfix` ;-)

**Comment by Floessie** [comment]
> Kind of I start from top and you start from bottom until we meet

:+1:

**Comment by Desmis** [comment]
Can I help, even Ingo start from top, and Floessie start from bottom :)

**Comment by Floessie** [comment]
@Desmis Maybe you could pick the ones you like to work on now from the end of the list and put your name on it. Then I'll do the same later for the ones that I'm going to clean.

**Comment by Desmis** [comment]
@Floessie 
Ok, but how to do, I am a not at all a specialist for compilation  :
a)  for compilation directives with windows , which files in cmake ?
b) for only have warning for one specific file
c) etc.
Thank you 
Jacques

**Comment by heckflosse** [comment]
@Desmis 
For temporary usage of compiler switches I always cheat by modifying `CMakeCache.txt` in build folder.
HowTo:
1. Open `CMakeCache.txt`
2. Search for `PROC_TARGET_2_FLAGS:STRING=-march=native`
3. Add ` - Wall` to that line and save
4. `make`, but ignore all the warnings because it makes a full build now
5. open a source file from the list above (for example `ipwavelet.cc`) and add space in first line, delete that space and save
6. `make`, now you get only the warnings related to that file and the included files.

**Comment by Desmis** [comment]
Ingo

OK, thank you, I'll try soon :)

**Comment by Desmis** [comment]
Ok, thats works :)
I just change ipvibrance.cc in the middle of the list 
jacques

**Comment by heckflosse** [comment]
@Desmis 
Jacques, please do not reformat the code during this cleanup. It makes it impossible to see what you fixed.

**Comment by Desmis** [comment]
Ok :)

**Comment by Floessie** [comment]
BTW: What's the matter of adding spaces between function name and the opening parenthesis? Haven't seen it very often, but there must be some reasoning to it.

PS: I'll join you on the weekend.

**Comment by heckflosse** [comment]
@Desmis 
Jacques, I will take improcfun.cc now :)

**Comment by Desmis** [comment]
@heckflosse 
How do we do, for commit and push...
I am afraid of probable conflicts, but maybe there are no risks ?

**Comment by heckflosse** [comment]
@Desmis 
One solution could be to use wallfix_desmis, wallfix_flossie and wallfix_ingo branches

Edit: Btw. I just pushed

**Comment by heckflosse** [comment]
@Floessie @Desmis 
I will work now on wallfix_ingo branch to avoid conflicts.
I always make one commit per compilation unit

**Comment by heckflosse** [comment]
@Floessie @Desmis 
Scratch my lost post. I have to think about that first

**Comment by Beep6581** [comment]
I don't know how messy this will get, but if you are able to confine the changes to individual files then working in the same branch and committing/pulling every time you're done with a single file would be easy and it would make this easier for others to checkout and test.

**Comment by Desmis** [comment]
I create wall_jacq and push changes for
FTblockdn.cc Edgeprervingdecomposition.cc previewimage.cc  with changes
and Pfcorrect.cc iimage.cc jdatsrc.cc imagedimensions.cc icons.cc utils.cc  - no nead changes

Now I make a pause,To be sure we work well together :)

**Comment by heckflosse** [comment]
@Desmis 
I will take rawimagesource.cc, demosaic_algos.cc and fast_demo.cc now
@Beep6581 
I made a commit for each single compilation unit and from now on I will also make a push for each commit

**Comment by Floessie** [comment]
@heckflosse I marked my initial three and will push to your branch.

**Comment by heckflosse** [comment]
@Floessie Oups, saw this too late. I hope my commit from now will not conflict.

**Comment by Floessie** [comment]
@heckflosse Sure it will, but I'll revert mine. :smile:

**Comment by heckflosse** [comment]
@Floessie @Desmis I will take improccoordinator.cc, simpleprocess.cc and dcrop.cc now

**Comment by Floessie** [comment]
@heckflosse How comes, there are files you listed that don't trigger here?

**Comment by heckflosse** [comment]
@Floessie You mean in my commits? In first post I just listed all compilation units of rtengine

**Comment by Floessie** [comment]
@heckflosse No, I mean, I compile them with `-Wall`, but don't get a warning...

**Comment by Floessie** [comment]
@heckflosse 
> In first post I just listed all compilation units of rtengine

Ah, that is why.

**Comment by Floessie** [comment]
@heckflosse Sorry, no time left tonight. I was working on `rtthumbnail.cc`: If we have a height or width, or a file size, shall we turn that into an unsigned or just cast the place with the comparison to signed?

**Comment by heckflosse** [comment]
@Floessie @Desmis It's really great to see the progress of this task. I expected that to take much longer. Now I think we can at least make rtengine compilation units `-Wall`-clean very soon (except dcraw.cc maybe...)

**Comment by heckflosse** [comment]
@Floessie I use unsigned when there is no subtraction. When there is a subtraction I use signed because I'm too lazy to search for possible side effects.

**Comment by heckflosse** [comment]
@Floessie Can I push some changes or do you have something on hold?

**Comment by heckflosse** [comment]
@Floessie I pushed my changes
@Desmis I also merged your changes into wallfix branch

**Comment by agriggio** [comment]
sorry to jump in this late, but if you need help let me know! also, if you
care usually clang is much more pedantic than GCC with -Wall

**Comment by heckflosse** [comment]
@agriggio the rtengine part is almost done now (at least for -Wall). But helping out for rtgui compilation units and also checking using more pedantic clang would be great :+1:

**Comment by heckflosse** [comment]
I also just started a cppcheck run...

**Comment by agriggio** [comment]
OK, I'll see what I can do

**Comment by heckflosse** [comment]
@agriggio Great :+1:

**Comment by heckflosse** [comment]
@Floessie @Desmis @agriggio @Beep6581 
Shall I open a new checklist for rtgui or add it to this issue?

**Comment by Desmis** [comment]
@heckflosse 
Ingo
I prefer a new checklist :)

**Comment by Desmis** [comment]
@heckflosse 
I have begun rtgui

No problem with : wavelet.cc, vibrance.cc
One small change to whitebalance.cc

**Comment by Desmis** [comment]
One change to colortoning.cc

No problem with retinex.cc blackwhite.cc  colorappearance.cc

**Comment by Desmis** [comment]
No problem with :
dirpyrdenoise.cc dirpyrequalizer.cc labcurve.cc rawexposure.cc tonecurve.cc
sharpening.cc sharpenedge.cc rawcacorrection.cc prsharpening.cc icmpanel.cc

**Comment by heckflosse** [comment]
Here's the checklist for rtgui:

- [x] editwindow.cc
- [x] batchtoolpanelcoord.cc
- [x] paramsedited.cc
- [x] cropwindow.cc
- [x] previewhandler.cc
- [x] previewwindow.cc
- [x] navigator.cc
- [x] indclippedpanel.cc
- [x] previewmodepanel.cc
- [x] filterpanel.cc
- [x] exportpanel.cc
- [x] cursormanager.cc
- [x] rtwindow.cc
- [x] renamedlg.cc
- [x] recentbrowser.cc
- [x] placesbrowser.cc
- [x] filepanel.cc
- [x] editorpanel.cc
- [x] batchqueuepanel.cc
- [x] checkbox.cc
- [x] ilabel.cc
- [x] thumbbrowserbase.cc
- [x] adjuster.cc
- [x] filebrowserentry.cc
- [x] filebrowser.cc
- [x] filethumbnailbuttonset.cc
- [x] cachemanager.cc
- [x] cacheimagedata.cc
- [x] shcselector.cc
- [x] perspective.cc
- [x] thresholdselector.cc
- [x] thresholdadjuster.cc
- [x] clipboard.cc
- [x] thumbimageupdater.cc
- [x] bqentryupdater.cc
- [x] lensgeom.cc
- [x] coloredbar.cc
- [x] edit.cc
- [x] coordinateadjuster.cc
- [x] coarsepanel.cc
- [x] cacorrection.cc
- [x] chmixer.cc
- [x] blackwhite.cc
- [x] resize.cc
- [x] icmpanel.cc
- [x] crop.cc
- [x] shadowshighlights.cc
- [x] impulsedenoise.cc
- [x] dirpyrdenoise.cc
- [x] epd.cc
- [x] exifpanel.cc
- [x] toolpanel.cc
- [x] lensprofile.cc
- [x] lockablecolorpicker.cc
- [x] sharpening.cc
- [x] vibrance.cc
- [x] rgbcurves.cc
- [x] colortoning.cc
- [x] whitebalance.cc
- [x] vignetting.cc
- [x] gradient.cc
- [x] pcvignette.cc
- [x] rotate.cc
- [x] distortion.cc
- [x] crophandler.cc
- [x] dirbrowser.cc
- [x] curveeditor.cc
- [x] curveeditorgroup.cc
- [x] diagonalcurveeditorsubgroup.cc (Ingo)
- [x] flatcurveeditorsubgroup.cc
- [x] filecatalog.cc
- [x] extprog.cc
- [x] previewloader.cc
- [x] rtimage.cc
- [x] inspector.cc
- [x] histogrampanel.cc
- [x] history.cc
- [x] imagearea.cc
- [x] imageareapanel.cc
- [x] iptcpanel.cc
- [x] labcurve.cc
- [x] main.cc (disabled -Wdeprecated-declarations)
- [x] multilangmgr.cc
- [x] mycurve.cc
- [x] myflatcurve.cc
- [x] mydiagonalcurve.cc
- [x] options.cc
- [x] retinex.cc
- [x] preferences.cc
- [x] profilepanel.cc
- [x] saveasdlg.cc
- [x] saveformatpanel.cc
- [x] soundman.cc
- [x] splash.cc
- [x] thumbnail.cc
- [x] tonecurve.cc
- [x] toolbar.cc
- [x] pathutils.cc
- [x] guiutils.cc
- [x] threadutils.cc
- [x] zoompanel.cc
- [x] toolpanelcoord.cc
- [x] thumbbrowserentrybase.cc
- [x] batchqueueentry.cc
- [x] batchqueue.cc
- [x] lwbutton.cc
- [x] lwbuttonset.cc
- [x] batchqueuebuttonset.cc
- [x] browserfilter.cc
- [x] exiffiltersettings.cc
- [x] profilestore.cc
- [x] partialpastedlg.cc
- [x] sensorbayer.cc
- [x] sensorxtrans.cc
- [x] preprocess.cc
- [x] bayerpreprocess.cc
- [x] bayerprocess.cc
- [x] bayerrawexposure.cc
- [x] xtransprocess.cc
- [x] xtransrawexposure.cc
- [x] darkframe.cc
- [x] flatfield.cc
- [x] rawcacorrection.cc
- [x] rawexposure.cc
- [x] wavelet.cc
- [x] dirpyrequalizer.cc
- [x] hsvequalizer.cc
- [x] defringe.cc
- [x] popupcommon.cc
- [x] popupbutton.cc
- [x] popuptogglebutton.cc
- [x] sharpenedge.cc
- [x] sharpenmicro.cc
- [x] colorappearance.cc
- [x] filmsimulation.cc
- [x] prsharpening.cc
- [x] dynamicprofile.cc
- [x] dynamicprofilepanel.cc

**Comment by agriggio** [comment]
Can I give a shot to the files in  `rtengine`? Clang still gives me some meaningful warnings (I silenced the less useful ones). Also, what about `rtexif`? And why is `rgengine/fujicompressed.cc` not listed?

**Comment by heckflosse** [comment]
@agriggio Sure you can give it a shot :+1: 
rtengine/fujicompressed.cc is not listed because currently it's not an own compilation unit.
But I agree that we should fix warnings in this one too!
rtexif also needs to be checked but I wanted to have an own checklist for it too when rtgui is completed

**Comment by agriggio** [comment]
rtexif is almost clean already, there's only one warning - I can fix that.

**Comment by agriggio** [comment]
I'm also working on `rtgui` -- I'm basically done. I'm leaving the deprecation warnings about `gdk_threads*` in `main.cc`

**Comment by agriggio** [comment]
it seems I was wrong about `rtexif`. Clang gives no warning now, but gcc shows many places in which the return values of `fread`, `read`, `fwrite` and `write` are ignored. How should we fix those though? The easy solution is to cast explicitly to `void`, should we do that or should we try to handle the possible failures?

**Comment by agriggio** [comment]
rtgui should be clean now (except for the GDK threads stuff)

**Comment by heckflosse** [comment]
@agriggio @Desmis great :+1:

**Comment by heckflosse** [comment]
@agriggio @Floessie 
Do you understand this warning?
```
H:/rt5master/rtengine/myfile.h:74:20: warning: assuming signed overflow does not occur when assuming that (X - c) > X is always false [-Wstrict-overflow]
     if (f->pos < 0 || f->pos > f->size) {
                    ^
```

**Comment by agriggio** [comment]
my interpretation: since overflow for signed is undefined behaviour (this
is what the standard says), GCC will assume that overflow does not occur
and optimize a comparison (x - c) > x by rewriting to false. how it applies
in that context is still a bit of a mystery :-)

**Comment by agriggio** [comment]
we have to look at the context for the above if to understand why GCC is optimizing it away

**Comment by heckflosse** [comment]
I begin to understand it. Here is one context:
```
  fseek (ifp, -(int)sizeof tail, SEEK_END);
```

**Comment by heckflosse** [comment]
I just pushed my changes and also a windows specific change (in `extprog.cc`) When this task is almost completed we should ask one of the Mac builders for a -Wall run to catch also Mac-specific warnings.

**Comment by heckflosse** [comment]
I fixed another one in rawimage.cc and one in dirbrowser.cc and also made a debug build.
Debug build also compiles fine :)

@agriggio I didn't get the warnings about unused return values you mentioned. What am I doing wrong?

**Comment by agriggio** [comment]
@heckflosse are you on Windows? the warnings are triggered by a particular
annotation on the function prototype. I suspect the annotation is specific
to glibc

**Comment by heckflosse** [comment]
@agriggio Yes, I'm on windows.

**Comment by heckflosse** [comment]
I pushed fixes for myfile.h and fujicompressed.cc

**Comment by Floessie** [comment]
Here's my minor contribution:
[rtthumbnail.patch.txt](https://github.com/Beep6581/RawTherapee/files/889321/rtthumbnail.patch.txt)

Sorry, but my weekend was unexpectedly busy, and so will be the next two weeks. But you all did a fantastic job! :+1:

**Comment by heckflosse** [comment]
@Floessie I included your patch.

I also fixed some warnings in dcraw.cc and disabled the remaining ones in dcraw.cc and main.cc
There's one windows specific warning left
```
In file included from H:/rt5master/rtengine/dcraw.cc:79:0:
C:/msys64/mingw64/x86_64-w64-mingw32/include/winsock2.h:15:2: warning: #warning Please include winsock2.h before windows.h [-Wcpp]
 #warning Please include winsock2.h before windows.h
  ^
```
but I can ignore that ;-)

Finally I added `-Wall` to `CMAKE_CXX_FLAGS`

@agriggio @Desmis @Floessie Thanks a lot for the fantastic teamwork :+1:

**Comment by Beep6581** [comment]
I merged `dev` into `thewall` and compiled using GCC 4.9.3. Results here: https://filebin.net/jzhbtxpi2d8xab93/rt_log.html

**Comment by heckflosse** [comment]
@Beep6581 Ah, yes. This are the warnings @agriggio mentioned above which I don't get on windows.

**Comment by heckflosse** [comment]
@Beep6581 I don't get this one:
```
/home/morgan/programs/code-rawtherapee/rtgui/thumbbrowserbase.cc: In member function ‘virtual bool ThumbBrowserBase::Internal::on_button_press_event(GdkEventButton*)’:
/home/morgan/programs/code-rawtherapee/rtgui/thumbbrowserbase.cc:777:5: warning: ‘void gdk_window_process_updates(GdkWindow*, gboolean)’ is deprecated (declared at /usr/include/gtk-3.0/gdk/gdkwindow.h:1060) [-Wdeprecated-declarations]
    gdk_window_process_updates (window->gobj(), true);
    ^
/home/morgan/programs/code-rawtherapee/rtgui/thumbbrowserbase.cc:777:53: warning: ‘void gdk_window_process_updates(GdkWindow*, gboolean)’ is deprecated (declared at /usr/include/gtk-3.0/gdk/gdkwindow.h:1060) [-Wdeprecated-declarations]
    gdk_window_process_updates (window->gobj(), true);
```
Maybe because I'm on gtk 3.18? I'll build on Sabayon now

Edit: It's because I use 3.18
```
gdk_window_process_updates has been deprecated since version 3.22 and should not be used in newly-written code.
```

**Comment by heckflosse** [comment]
@Beep6581 
```/home/morgan/programs/code-rawtherapee/rtengine/helpersse2.h: In function ‘void gaussianBlur(float**, float**, int, int, double, float*, eGaussType, float**)’:
/home/morgan/programs/code-rawtherapee/rtengine/helpersse2.h:37:38: warning: ‘Tv1’ may be used uninitialized in this function [-Wmaybe-uninitialized]
#define STVFU(x,y) _mm_storeu_ps(&x,y)
                                     ^
/home/morgan/programs/code-rawtherapee/rtengine/gauss.cc:235:12: note: ‘Tv1’ was declared here
    vfloat Tv1, Tm1v1, Tp1v1;
```
Is not reported by gcc 5.3.0. I checked the code and it is indeed a false positive. I can fix it nevertheless.

**Comment by Beep6581** [comment]
4.9 seems to be still supported: https://gcc.gnu.org/develop.html

**Comment by gaaned92** [comment]
I compiled wallfix branch with following parameters
```
Version: 5.0-r1-gtk3-374-g602162a3
Branch: wallfix
Commit: 602162a3
Commit date: 2017-04-03
Compiler: gcc 6.3.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.22.0
Build type: release
Build flags:  -m64 -mwin32 -mthreads  -Werror=unused-label -Werror=unknown-pragmas -Wno-aggressive-loop-optimizations -std=c++11 -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -mwindows -DNDEBUG -msse2 -O3
Link flags: -m64 -mthreads  -static-libgcc   -mtune=generic -mwindows -s -O3
OpenMP support: ON
MMAP support: ON

```
gtk3.22.10

I get following warnings

[https://filebin.net/cawwtufd2pdt5foz/logfile.html](https://filebin.net/cawwtufd2pdt5foz/logfile.html)

**Comment by heckflosse** [comment]
@gaaned92 Thanks for reporting :+1: I will fix them now.

**Comment by heckflosse** [comment]
@Beep6581 @gaaned92 
I just pushed some fixes for the warnings you reported.
As I didn't get these warnings using gcc 5.3 I need your tests again :)

**Comment by Beep6581** [comment]
It builds without warnings using GCC 4.9.3, and the build works well. Identical output to dev branch if S/H is turned off.

**Comment by heckflosse** [comment]
Also builds without warnings on my Sabayon system now :)

**Comment by gaaned92** [comment]
two warnings here see [https://filebin.net/n7phivbsq6fn3mau/logfile1.html](https://filebin.net/n7phivbsq6fn3mau/logfile1.html)

**Comment by agriggio** [comment]
A couple of further warnings that I'm seeing here (gcc 6.2.0):

```
[75/231] Building CXX object rtengine/CMakeFiles/rtengine.dir/gauss.cc.o
../rtengine/gauss.cc: In function ‘void {anonymous}::gaussVertical(T**, T**, int, int, double) [with T = float]’:
../rtengine/gauss.cc:906:24: warning: assuming signed overflow does not occur when assuming that (X - c) > X is always false [-Wstrict-overflow]
 template<class T> void gaussVertical (T** src, T** dst, const int W, const int H, const double sigma)
                        ^~~~~~~~~~~~~
../rtengine/gauss.cc:906:24: warning: assuming signed overflow does not occur when assuming that (X - c) > X is always false [-Wstrict-overflow]
../rtengine/gauss.cc:906:24: warning: assuming signed overflow does not occur when assuming that (X - c) > X is always false [-Wstrict-overflow]
[91/231] Building CXX object rtengine/...Files/rtengine.dir/rawimagesource.cc.o
../rtengine/rawimagesource.cc: In member function ‘virtual void rtengine::RawImageSource::retinexPrepareBuffers(rtengine::procparams::ColorManagementParams, rtengine::procparams::RetinexParams, multi_array2D<float, 4ul>&, LUTu&)’:
../rtengine/rawimagesource.cc:2211:17: warning: ‘retinexgamtab’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         #pragma omp parallel for
```

**Comment by heckflosse** [comment]
I pushed a fix for another two warnings.
@agriggio I don't know how to fix the warning in `gaussVertical`
@gaaned92 I think I can not fix this note:
```
Y:/RTSOURCE/rawtherapee/rtgui/placesbrowser.cc:323:0: note: -Wmisleading-indentation is disabled from this point onwards, since column-tracking was disabled due to the size of the code/headers
```

**Comment by agriggio** [comment]
@heckflosse this "fixes" it here:

```
diff --git a/rtengine/gauss.cc b/rtengine/gauss.cc
--- a/rtengine/gauss.cc
+++ b/rtengine/gauss.cc
@@ -921,7 +921,7 @@
     #pragma omp for nowait
 #endif
 
-    for (int i = 0; i < W - numcols + 1; i += numcols) {
+    for (unsigned i = 0; i < unsigned(W - numcols + 1); i += numcols) {
         for (int k = 0; k < numcols; k++) {
             temp2[0][k] = B * src[0][i + k] + b1 * src[0][i + k] + b2 * src[0][i + k] + b3 * src[0][i + k];
             temp2[1][k] = B * src[1][i + k] + b1 * temp2[0][k] + b2 * src[0][i + k] + b3 * src[0][i + k];
```

**Comment by agriggio** [comment]
Actually, this is probably better (if it can happen that `W+1 < numcols`):

```
diff --git a/rtengine/gauss.cc b/rtengine/gauss.cc
--- a/rtengine/gauss.cc
+++ b/rtengine/gauss.cc
@@ -921,7 +921,7 @@
     #pragma omp for nowait
 #endif
 
-    for (int i = 0; i < W - numcols + 1; i += numcols) {
+    for (unsigned i = 0; i < unsigned(std::max(0, W - numcols + 1)); i += numcols) {
         for (int k = 0; k < numcols; k++) {
             temp2[0][k] = B * src[0][i + k] + b1 * src[0][i + k] + b2 * src[0][i + k] + b3 * src[0][i + k];
             temp2[1][k] = B * src[1][i + k] + b1 * temp2[0][k] + b2 * src[0][i + k] + b3 * src[0][i + k];
```

**Comment by heckflosse** [comment]
@agriggio 
Let's hope that always W >= numcols -1 ;-)

**Comment by heckflosse** [comment]
@agriggio you've been faster :+1:

**Comment by heckflosse** [comment]
@agriggio I pushed your fix for gauss.cc
