### ISSUE TITLE
PNG files cause crash

### ISSUE THREAD

**Issue by teplit** [Beep6581/RawTherapee#3794]
The attached PNG files cause reproducible crash on three different Windows systems.

Steps to reproduce the problem:
1. Place the PNG files in an empty folder
2. Configure RawTherapee to parse PNG files
3. Open the folder from the first step with RawTherapee

RawTherapee versions: 5.0-r1-gtk3 (64 and 32 bit)
Screenshot of the error message: ![rawtherapee crash](https://cloud.githubusercontent.com/assets/5978882/24576991/5b5ff19e-16ce-11e7-9807-44efdeac5fe1.png)

The problematic PNG files:
[gradient45](https://cloud.githubusercontent.com/assets/5978882/24576934/4afecd6c-16cd-11e7-929b-b48317bcb591.png)
[gradient46](https://cloud.githubusercontent.com/assets/5978882/24576935/4b027c46-16cd-11e7-9007-1d1092fe80d4.png)

**Comment by Beep6581** [comment]
Reproduced in Linux.

**Comment by heckflosse** [comment]
It crashes at thumbnail generation because rt tries to generate a thumbnail according to the thumb height set in preferences (and maybe zoom factor of thumb too). In my test it tries to generate a thumbnail of size 80640 x 84 (width x height). 
Even If that would work correctly it would explode the filebrowser afterwards.
@Beep6581 @Hombre57 @Desmis @Floessie @agriggio : We have to decide how to handle this kind of images (for example skip them based on certain conditions or whatever)

**Comment by agriggio** [comment]
would make sense to crop thumbnails that have a too big w:h ratio (say e.g >= 10:1) and of course signal this to the user in some way? what do you
think?

**Comment by heckflosse** [comment]
@agriggio Currently I'm not sure about a good solution.

**Comment by TooWaBoo** [comment]
A "Bounding Box" like in the "Resize" tool would be the best solution.

**Comment by Hombre57** [comment]
Yes, a customable bounding box large enough to display panoramas without going into extreme width.

**Comment by Beep6581** [comment]
There is already a discussion about File Browser thumbnail improvements with ideas and mockups over at issue #1239.

**Comment by Beep6581** [comment]
Still valid.

**Comment by agriggio** [comment]
If we want a hotfix, we can simply reject images that have too unbalanced aspect ratios. It's not a proper solution but it's better than crashing I'd say. In that case, something like this should do:

```diff
diff --git a/rtengine/rtthumbnail.cc b/rtengine/rtthumbnail.cc
--- a/rtengine/rtthumbnail.cc
+++ b/rtengine/rtthumbnail.cc
@@ -150,6 +150,10 @@
 
     ImageIO* img = imgSrc.getImageIO();
 
+    if (std::max(img->getWidth(), img->getHeight()) / std::min(img->getWidth(), img->getHeight()) > 10) {
+        return nullptr;
+    }
+    
     Thumbnail* tpp = new Thumbnail ();
 
     unsigned char* data;
```

**Comment by Beep6581** [comment]
Yes please.

**Comment by brussell1** [comment]
(I've opened the now closed ticket "RawTherapee 5.4 doesn't detect images with certain dimensions")

So the "solution" is to reject images with certain resolutions instead of fixing this bug? Really?
I hope thats not the final decision in this case...

I've been editing 3dLUTs with such resolutions like 1024x32 and it worked flawlessly until RT5.4.

**Comment by agriggio** [comment]
> So the "solution" is to reject images with certain resolutions instead of fixing this bug? Really?

Did you read the comments above? Nobody wrote that this is a solution, merely a hotfix to avoid crashes. In fact, the issue is still open. Nobody had time to find a proper solution unfortunately, but we are happy to accept patches :-)

**Comment by brussell1** [comment]
Why not go for your first suggestion: cropping the thumbnails? Imo that would be a far more reasonable hotfix than to just drop support for certain image resolutions alltogether.

**Comment by heckflosse** [comment]
@brussell1 I just tested rt on your file (with the restriction removed, so I could open it) and got crashes while zooming in and out using the mouse wheel. So it's not only cropping the thumbnails to solve this. We have to dig a bit deeper to solve it in general.

**Comment by brussell1** [comment]
Is there any motivation to fix this issue?

**Comment by Hombre57** [comment]
@brussell1 I'll have a look next week.

**Comment by brussell1** [comment]
So may I ask, 4 months and 2 releases later, that you fix this please? 
If it's not that easy, can you at least add a checkbox to the settings like "allow experimental support for unusual aspect ratios" or sth.?
I'm still stuck with RT5.2 for my needs.
