### ISSUE TITLE
Crash when switching between raw and tif

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#3797]
To reproduce

1. copy both images from [here](https://filebin.net/qf4hfomif5husmze) into a new folder
2. open folder in rt
3. open IMGP0569.dng
4. open imgp0569.tiff
5. repeat step 3. and 4. until it crashes

I already tried using idle_harder branch. There it also crashes.
I tried to get a backtrace in Debug mode but get only
```
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```
I also got this in console sometimes:
```
(rawtherapee.exe:5124): Gtk-CRITICAL **: _gtk_css_image_compute: assertion 'parent_style == NULL || GTK_IS_CSS_STYLE (parent_style)' failed
```

**Comment by Beep6581** [comment]
Reproduced using (neutral) for both and using F3/F4 to switch.

**Comment by Beep6581** [comment]
[log1.txt](https://github.com/Beep6581/RawTherapee/files/889615/log1.txt)
[log2.txt](https://github.com/Beep6581/RawTherapee/files/889614/log2.txt)
[log3.txt](https://github.com/Beep6581/RawTherapee/files/889616/log3.txt)

**Comment by Floessie** [comment]
```patch
diff --git a/rtgui/toolpanelcoord.cc b/rtgui/toolpanelcoord.cc
index cacbee99..7920b7a9 100644
--- a/rtgui/toolpanelcoord.cc
+++ b/rtgui/toolpanelcoord.cc
@@ -311,6 +311,7 @@ ToolPanelCoordinator::~ToolPanelCoordinator ()
 
 void ToolPanelCoordinator::imageTypeChanged(bool isRaw, bool isBayer, bool isXtrans)
 {
+    GThreadLock lock;
 
     if(isRaw) {
         rawPanelSW->set_sensitive(true);
```

**Comment by heckflosse** [comment]
@Floessie Fix confirmed. Thank you :+1: 
I shouldn't make changes to gui code ...
Will you commit it?

**Comment by Floessie** [comment]
:smile: 

> Will you commit it?

No, I'm behind a firewall atm. Feel free to push.

**Comment by Beep6581** [comment]
Fix confirmed.
