### ISSUE TITLE
Olympus TG-4 wrong distortion in raw

### ISSUE THREAD

**Issue by ertyz** [Beep6581/RawTherapee#3803]
I've got problems with distortion in raw on my Olympus TG-4 camera. Only Adobe (Photoshop/Lightroom) and brand Olympus Viewer software can show me correct result.

There is the samples:
That is Olympus jpeg (correct): http://pasteboard.co/Cn6bL8XF.jpg
That is Adobe version (correct): http://pasteboard.co/CoLK1K1t.jpg
That is RawTherapee 5.0 (incorrect): http://pasteboard.co/CE4J3IEe.jpg

Also, dcraw (XnView 2.39), libraw 18.2, CyberLink PhotoDirector 8, CaptureOne 10 all got same problem with curved horizon

original raw: https://goo.gl/vgP6cV
all samples: https://goo.gl/Z7rQzI

camera firmware 2.0
RawTherapee_5.0-r1-gtk3_WinVista_64, Windows 10 x64
And I've got a lot of samples like this if you need...

**Comment by Beep6581** [comment]
@ertyz http://rawpedia.rawtherapee.com/Lens/Geometry#Lens_Correction_Profile
