### ISSUE TITLE
Fujifilm GFX 50S raw crop offset 

### ISSUE THREAD

**Issue by vadimcro** [Beep6581/RawTherapee#3806]
RAF files imported from GFX-50s get a "shift" left, resulting in cropped left-side of the image and added black frame that carries no information to the right of the file. same JPEG file imports fine. At first the previdw shows the full image, but in the editor the RAF gets shifted and cropped. It happends upon load,
before any editing is applied.

![rt](https://cloud.githubusercontent.com/assets/26960145/24747097/9d78536e-1abb-11e7-9b22-39136cb58f16.jpg)

**Comment by Beep6581** [comment]
@vadimcro please upload a sample raw file using https://filebin.net/

**Comment by vadimcro** [comment]
Here you go...
https://filebin.net/tx8n4grxn99ri0xz/VGFX0131.RAF

**Comment by heckflosse** [comment]
https://github.com/Beep6581/RawTherapee/commit/3bf98847f25e3a7e3fcbf27487fcd5bfd006bfbb

**Comment by Beep6581** [comment]
I confirm with your file and with one from http://www.imaging-resource.com/PRODS/fuji-gfx/fuji-gfxA7.HTM that it works fine in the latest dev.

**Comment by vadimcro** [comment]
Thanks for pointing out the issue with JSON file.
It fixed the issue.
Json file that comes with downloadable stable Branch: 5.0-r1-gtk3 for 64bit win system did not contain
the lines of GFX-50s. Could you please check and tend that the JSON file would be updated in the stable compiled release?
Thanks a lot!

**Comment by Beep6581** [comment]
@vadimcro 5.0-r1 has been released and will not be changed. The added support for the Fujifilm GFX 50S is available in dev builds and will be part of RawTherapee-5.1.

**Comment by vadimcro** [comment]
Thanks for the info!
Eager for future releases!
Great Software with enormous potential!

**Comment by heckflosse** [comment]
@vadimcro fyi: 5.1 will also open compressed files from GFX 50S
