### ISSUE TITLE
Support DJI X5S Raw files from SSD

### ISSUE THREAD

**Issue by TheGrumpster** [Beep6581/RawTherapee#3811]
This is an odd bug/feature-request. RT info here:
```
Version: 5.0-r1-gtk3
Branch: 5.0-r1-gtk3
Commit: 50114c1
Commit date: 2017-02-01
Compiler: gcc 5.3.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.18.0
Build type: release
Build flags: -m64 -mwin32 -mthreads -std=gnu++11 -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -msse -msse2 -mwindows -fopenmp -Wno-aggressive-loop-optimizations -DNDEBUG -O3
Link flags: -m64 -mwin32 -mthreads -static-libgcc -mtune=generic -mwindows -s -O3
OpenMP support: ON
MMAP support: ON
```
The issue is that RT seems unable to deal with the raw .dng files from the X5S (FC6520) camera when the images are stored to the SSD instead of the SD Card. I have no idea why there should be any difference, and it may very well be a DJI bug and not an RT bug, but I am not knowledgeable enough myself to figure this out.

I do know that RT works perfectly with raw .dng files from the SD card. However, raw .dng files recorded to the SSD come up as a pixelated mess of white and magenta, as if it is unable to understand the image format. I also note that RT does not know the camera or lens on the SSD files, but does know this on the SD card files.

Adobe Capture Raw IS able to process raw .dng files properly regardless of whether they are from the SSD or SD card. So ACR somehow knows how to parse these correctly even though RT apparently does not.

Some background here for those wondering. The X5S is a micro-4/3 camera for the Inspire 2 drone, and the drone can record data (raw .dng files in this case) to either a micro-SD card, or to a proprietary SSD card (that allows vastly more images to be stored and is used primarily for video, but also can hold stills).

I've uploaded a sample of a file (20MB) from the SSD here:
https://grumpysworld.com/bnsf_4062_intermodal_20170408_ottawa_ks.dng

One thing that strikes me as very odd is that this .dng is about half the size of one from the SD card, so something fishy is going on. It most likely is a DJI bug (they are notorious at writing terrible software), but I'm hoping someone who understands .dng files can figure this out. Also, as I noted, ACR seems to produce a decent image from this file with no problem, so that too is a mystery.

Thanks for your help!

**Comment by Beep6581** [comment]
Confirmed that dev does not open it. @TheGrumpster could you upload the same photo saved to SD?

**Comment by TheGrumpster** [comment]
I sincerely wish I could because I know this would be tremendously helpful. Alas, the Inspire 2 (to the best of my knowledge) does NOT allow you to capture stills to both the SSD and micro-SD simultaneously. That said, if you want a "normal" raw .dng (40MB) from the X5S, you can have this one:
https://blog.grumpysworld.com/wp-content/uploads/2017/04/bnsf_7567_oilload_20170218_forestcity_mo.dng

I got to thinking about this and I'm really wondering if DJI isn't pulling a fast one here. The Inspire 2 is primarily an aerial video platform, but I use it for stills. The X5S is a micro-4/3 camera with a 20MP sensor and the SD-card raws are about 40MB. The SSD card raws are only 20MB. So what occurred to me is that maybe when you shoot to the SSD, the camera is actually recording video and just grabbing frames to write. How else could the .dng be half the size?

But what's weird is that ACR doesn't seem to care. I actually got a pretty decent image out of the 20MB conversion and I don't see any compression artifacts that lead me to think we've lost image data, but clearly we have somewhere.

FYI, the reason to shoot stills on the SSD is because you get unlimited burst capacity. So on the image of my first post, I shot about 160 frames and just picked the one I liked best. With the micro-SD, you can't shoot bursts like that. Once again, this makes me VERY suspicious that this is some sort of hokey video trickery that DJI is doing and not telling anyone about.

Really appreciate the help because I don't understand the raw digital formats very well. Old school film geezer here.

**Comment by sandymc** [comment]
A brief look at the DNGs indicates a rather strange situation. Both DNGs claim to be JPEG compressed, but actually, the 40MB one isn't really compressed - the compression is effectively not there. That's technically legal by JPEG compression standards, but strange.  The 20MB file is actually genuinely JPEG compressed, which is why it's smaller. But both files are technically legal. Adobe software reads them, as does e.g., AccuRaw.

**Comment by TheGrumpster** [comment]
Very interesting, but quite scary. Shouldn't a raw be raw? If I wanted jpeg, I'd shoot jpeg. One thing that did occur to me (keep in mind, I have no clue what I'm talking about here) is that the X5S shoots a variety of video formats and one of these is Prores422, which to my understanding is in YUV color space instead of RGB, and down-samples the 2 chroma channels to 2 bits each, while keeping the luminance channel at 4 bits.
A friend pointed out that the raw formats are different between SD card and SSD for the X5S, and he claimed the difference was bit depth, which again makes we wonder about this 422 scheme. It would be nice to have SD and SSD files for the same scene so we could torture them and figure out what is really going on. Then again, if you are adept at snooping in dng files, you can probably figure it out that way too.

Also, rather OT, but interesting, DJI appears to have radically changed the profile information contained in the SD-card dng files during a firmware update last month. I know this because all my shots prior to that (including the sample I provided above) come up a bit over-saturated and quite magenta in many converters, whereas the newer dng files come up very flat and slightly blue.

**Comment by heckflosse** [comment]
@TheGrumpster 

> Very interesting, but quite scary. Shouldn't a raw be raw? If I wanted jpeg, I'd shoot jpeg.

Even some canon camerase use `lossless` jpeg compression to save space for raw files.
Don't confuse that with lossy jpeg compression or jpeg files.

**Comment by heckflosse** [comment]
RT reports
```
bnsf_4062_intermodal_20170408_ottawa_ks.dng: Corrupt data near 0x5bb4
```

I will investigate but can't promise anything...

**Comment by Beep6581** [comment]
@TheGrumpster the 21MB file (4062) is not a JPEG. It is a 12-bit raw file (possibly encoded using JPEG compression if you trust the metadata `-TIFF-IFD0:Compression=JPEG` - anyone know how to verify this?), while the 41MB file (7567) is a 16-bit uncompressed raw file.

**Comment by Beep6581** [comment]
Converting the 12-bit raw (4062) to DNG using Adobe DNG Converter results in a DNG which RT reads fine.

**Comment by Beep6581** [comment]
Copying metadata from 7567 or from the Adobe DNG Converted DNG file to 4062 didn't help either, though the corrupt address changed.

**Comment by Beep6581** [comment]
There seems to be nothing we can do about this. Maybe a dcraw update will improve the situation, regardless of whether the file really is corrupt or not. You could submit the file to Dave Coffin http://www.cybercom.net/~dcoffin/dcraw/
If you want to process these files in RT, the workaround for now is to use Adobe DNG Converter.
