### ISSUE TITLE
Cppcheck 1.78 run

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#3812]
I ran current dev branch through cppcheck 1.78 and created [cppcheck3](https://github.com/Beep6581/RawTherapee/commits/cppcheck3) branch which fixes a lot (but not all) of the issues reported by cppcheck.

Ingo

**Comment by Floessie** [comment]
@heckflosse :+1: Didn't see any real bugs in the diff, mostly too broad scopes. Nice use of `const`! :smile: 

If you come across statements like `int var = (int)(...)`, ditch the cast. There was one such place in the diff, but I could not comment there.

**Comment by Beep6581** [comment]
I merged `cppcheck3` into `osxbuild2` and get this warning:
```
/home/morgan/programs/code-rawtherapee/rtengine/PF_correct_RT.cc: In member function ‘void rtengine::ImProcFunctions::BadpixelsLab(rtengine::LabImage*, rtengine::LabImage*, double, int, int, float, float, float, float, float, float)’:
/home/morgan/programs/code-rawtherapee/rtengine/PF_correct_RT.cc:1448:16: warning: unused variable ‘shfabsv’ [-Wunused-variable]
         __m128 shfabsv, shmedv;
                ^
```

**Comment by heckflosse** [comment]
@Beep6581 Fixed.

**Comment by heckflosse** [comment]
@Floessie Thanks for your review :+1: I didn't try to fix real bugs. I just worked through the log with the intention to fix as many cppcheck issues as possible. I will continue that task now.
`int var = (int)(...)` yes that's nonsense

**Comment by heckflosse** [comment]
I merged the current state of the branch into dev to get more tests and will continue now with further cleanups
