### ISSUE TITLE
RawTherapee opens hdr dng images creted by Lightroom as black images

### ISSUE THREAD

**Issue by vilmantasr** [Beep6581/RawTherapee#3820]
RawTherapee (5.0-r1-gtk3-419-g3ff25193, from https://drive.google.com/drive/folders/0B2q9OrgyDEfPS2FpdDAtMVI1RG8, OS Windows 10) displays black image after opening HDR dng (3 images) created with Ligtroom CC 2015 (newest version), camera: Pentax K-5II.

HDR DNG:
https://www.dropbox.com/s/7pk69hyrh4ulldo/IMGP2883-HDR.dng?dl=0

![2017-04-12 12_58_45-rawtherapee 5 0-r1-gtk3-419-g3ff25193 - c__users_vilmantasr_pictures_2017_2017-0](https://cloud.githubusercontent.com/assets/8343756/24952552/7fcd3f04-1f80-11e7-808f-8d274eb700f8.png)

**Comment by heckflosse** [comment]
@vilmantasr 
Demosaiced float dng files are not supported currently.
