### ISSUE TITLE
Automatically detected monitor profile is not selected by default

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3821]
I set the monitor default color profile to Foo, then enable "Use operating system's main monitor color profile" and open an image, the monitor profile selected by default under the preview is still Foo. Even if I change it to "System default (from GDK)" and restart RT, it still defaults to Foo. Since the Preferences options is called "monitor default color profile", "System default (from GDK)" should be on by default regardless of what is selected in the disabled combo.

Issue first reported here: https://github.com/Beep6581/RawTherapee/pull/3810#issuecomment-292746555

**Comment by agriggio** [comment]
should work now
