### ISSUE TITLE
GCC diagnostic issue on macOS/Clang

### ISSUE THREAD

**Issue by ion12** [Beep6581/RawTherapee#3825]
Trying to build dev branch pulled earlier today on Mac OS X 10.11 / Clang 3.9.1
Getting build-blocking error:

```
RawTherapee/rtengine/dcraw.cc:5:32: error: unknown warning group '-Wunused-but-set-variable', ignored
      [-Werror,-Wunknown-pragmas]
#pragma GCC diagnostic ignored "-Wunused-but-set-variable"
```
`-Werror=unknown-pragmas` is enforced by OPENMP_FOUND, the only way I could build was by uncommenting 
`#pragma GCC diagnostic ignored "-Wunused-but-set-variable"` 
altogether, or moving it temporarily into the 
`#if (__GNUC__ == 6)` 
block

ping @heckflosse

**Comment by heckflosse** [comment]
@ion12 
which `__GNUC__` version does correspond to your clang version?

**Comment by agriggio** [comment]
you can try with -Qunused-arguments for clang

**Comment by ion12** [comment]
as far as I can tell from clang 3.9.1 src:
```
    // Currently claim to be compatible with GCC 4.2.1-5621, but only if we're
    // not compiling for MSVC compatibility
    Builder.defineMacro("__GNUC_MINOR__", "2");
    Builder.defineMacro("__GNUC_PATCHLEVEL__", "1");
    Builder.defineMacro("__GNUC__", "4");
    Builder.defineMacro("__GXX_ABI_VERSION", "1002");
```
not sure if this is the correct info you are after...

**Comment by ion12** [comment]
also this might be useful?
https://stackoverflow.com/questions/6557042/how-to-disable-a-particular-unknown-pragma-warning-gcc-and-or-clang

> It seems correct to me to hide any #pragma from a compiler which is not expected to understand it in the way that you intend, given that the whole point of #pragma is to provide a mechanism for invoking implementation-defined behaviour in the compiler.
(If you do end up doing this, note that Clang defines \_\_clang__, but both GCC and Clang define \_\_GNUC__.)

Sorry I can't be more help, this is way beyond my knowledge ;)

**Comment by heckflosse** [comment]
@ion12 can you try this patch please?

```
diff --git a/rtengine/dcraw.cc b/rtengine/dcraw.cc
index eca3733..3307416 100644
--- a/rtengine/dcraw.cc
+++ b/rtengine/dcraw.cc
@@ -2,7 +2,6 @@
 #pragma GCC diagnostic push
 #pragma GCC diagnostic ignored "-Warray-bounds"
 #pragma GCC diagnostic ignored "-Wsign-compare"
-#pragma GCC diagnostic ignored "-Wunused-but-set-variable"
 #pragma GCC diagnostic ignored "-Wparentheses"
 #if (__GNUC__ == 6)
 #pragma GCC diagnostic ignored "-Wmisleading-indentation"
@@ -1855,13 +1854,12 @@ void CLASS parse_hasselblad_gain()
       not be seen as clipped).
     */
 
-    ushort raw_h;
     int offset;
     off_t base;
 
     base = ftell(ifp);
     fseek(ifp, 2 * 23, SEEK_CUR);
-    raw_h = get2();
+    get2();
     fseek(ifp, 48, SEEK_CUR);
     offset = get4();
     hbd.levels = offset ? base + offset : 0;
@@ -6700,7 +6698,7 @@ void CLASS parse_sinar_ia()
 
 void CLASS parse_phase_one (int base)
 {
-  unsigned entries, tag, type, len, data, save, i, c;
+  unsigned entries, tag, len, data, save, i, c;
   float romm_cam[3][3];
   char *cp;
 
@@ -6713,7 +6711,7 @@ void CLASS parse_phase_one (int base)
   get4();
   while (entries--) {
     tag  = get4();
-    type = get4();
+    get4();
     len  = get4();
     data = get4();
     save = ftell(ifp);

```

**Comment by ion12** [comment]
@heckflosse I will try the patch first thing tomorrow morning!

**Comment by ion12** [comment]
@heckflosse patch confirmed working

**Comment by heckflosse** [comment]
@ion12 Thanks for testing the patch :+1:
