### ISSUE TITLE
PP3 created alongside input file when should be in cache

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3834]
Summary: A dead PP3 file is written next to the input image if you open it before assigning a profile to it when Preferences is set to write PP3 files to the cache only.

1. Set RawTherapee to:
```
SaveParamsWithFile=false
SaveParamsToCache=true
LoadParamsFromLocation=1
```
2. Put two raw files in a folder. Delete the cache and any PP3 files inside this folder:
`rm -rvf ~/.cache/RawTherapee/ && rm ~/downloads/temp/*.pp3`
3. Run RawTherapee. Don't do anything.
4. Check for PP3 files in the cache and the folder:
`find ~/.cache/RawTherapee/ -iname "*.pp3" && ls -l ~/downloads/temp/*.pp3`
Nothing found yet, good.
5. Apply Neutral to the first photo from the File Browser, then check for PP3 files:
```
find ~/.cache/RawTherapee/ -iname "*.pp3" && ls -l ~/downloads/temp/*.pp3
/home/morgan/.cache/RawTherapee/profiles/1.pef.dc2756834c5f375cb3a1f0d7b792d675.pp3
ls: cannot access '/home/morgan/downloads/temp/*.pp3': No such file or directory
```
Good so far.
6. Open the first photo and hit ctrl+s to save, then check for PP3. Same result as above, good so far.
7. Open the second photo. It had no PP3 assigned from the File Browser. Check for PP3 files:
```
find ~/.cache/RawTherapee/ -iname "*.pp3" && ls -l ~/downloads/temp/*.pp3
/home/morgan/.cache/RawTherapee/profiles/1.pef.dc2756834c5f375cb3a1f0d7b792d675.pp3
-rw-r--r-- 1 morgan morgan 10761 Apr 18 13:37 /home/morgan/downloads/temp/2.pef.pp3
```
Bug, 2.pef.pp3 should not be there.
8. Set exposure compensation to some easily identifiable value, e.g. 1.23. Hit Ctrl+Shift+s to manually write the PP3 to the correct location. Check for PP3 files:
```
find ~/.cache/RawTherapee/ -iname "*.pp3" && ls -l ~/downloads/temp/*.pp3
/home/morgan/.cache/RawTherapee/profiles/2.pef.eafd31aa98a4dab567c88444e0cf18e5.pp3
/home/morgan/.cache/RawTherapee/profiles/1.pef.dc2756834c5f375cb3a1f0d7b792d675.pp3
-rw-r--r-- 1 morgan morgan 10761 Apr 18 13:37 /home/morgan/downloads/temp/2.pef.pp3
```
The file in the cache has `Compensation=1.23` while the file next to the input image has `Compensation=0`. Good, the new file was written to the cache only.
9. This step doesn't show any new aspect of the bug, it just shows that the problem is reproducible multiple times in a single RT session. Open the last raw file. It too had no PP3 assigned from the File Browser, and as with the second file a new PP3 is incorrectly created next to the input image.
```
find ~/.cache/RawTherapee/ -iname "*.pp3" && ls -l ~/downloads/temp/*.pp3
/home/morgan/.cache/RawTherapee/profiles/2.pef.eafd31aa98a4dab567c88444e0cf18e5.pp3
/home/morgan/.cache/RawTherapee/profiles/1.pef.dc2756834c5f375cb3a1f0d7b792d675.pp3
-rw-r--r-- 1 morgan morgan 10761 Apr 18 13:37 /home/morgan/downloads/temp/2.pef.pp3
-rw-r--r-- 1 morgan morgan 10761 Apr 18 13:42 /home/morgan/downloads/temp/3.pef.pp3
```

**Comment by Beep6581** [comment]
Seems to happen here:
https://github.com/Beep6581/RawTherapee/blob/dev/rtengine/procparams.cc#L3581

**Comment by agriggio** [comment]
@Beep6581 I just pushed a fix on `dev`, can you please test?

> Seems to happen here

It was actually a regression introduced by me when I restructured the thumbnail contextual menu to add a "reset to default" operation -- sorry about that :-/

**Comment by Beep6581** [comment]
Fix confirmed @agriggio, thank you.

**Comment by heckflosse** [comment]
@agriggio I also confirm the fix :+1:
