### ISSUE TITLE
Raw CA chromatic aberration correction produces color casts

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3836]
Raw CA correction causes color casts when working with very dark images which require a high positive exposure compensation, as is usually the case with HDR DNGs. Using 01-04.dng if I enable raw CA correction (auto or manual), a color cast appears and it is strong enough to make using that feature not possible when accurate colors are needed.

Increasing exposure before raw CA correction takes places works around the problem:
```diff
diff --git a/rtengine/CA_correct_RT.cc b/rtengine/CA_correct_RT.cc
index e1493ae4..fcb09872 100644
--- a/rtengine/CA_correct_RT.cc
+++ b/rtengine/CA_correct_RT.cc
@@ -165,6 +165,10 @@ void RawImageSource::CA_correct_RT(const bool autoCA, const double cared, const
 
     constexpr float eps = 1e-5f, eps2 = 1e-10f; //tolerance to avoid dividing by zero
 
+    for(int i = 0; i< height; ++i)
+        for(int j = 0; j< width; ++j)
+            rawData[i][j] *= 4.f;
+
     #pragma omp parallel
     {
         int progresscounter = 0;
@@ -1009,6 +1013,9 @@ void RawImageSource::CA_correct_RT(const bool autoCA, const double cared, const
     free(Gtmp);
     free(blockwt);
     free(RawDataTmp);
+    for(int i = 0; i< height; ++i)
+        for(int j = 0; j< width; ++j)
+            rawData[i][j] *= 0.25f;
 
     if(plistener) {
         plistener->setProgress(1.0);
```

http://rawtherapee.com/public_html/shared/test_images/2015-12-04_karin_library_04_01-04.dng

Raw CA correction off:
![2015-12-04_karin_library_10_01-05_1_rawautoca_off](https://cloud.githubusercontent.com/assets/5844619/25200432/95bba994-254e-11e7-83fb-1da57cfb968f.jpg)

Raw CA correction on:
![2015-12-04_karin_library_10_01-05_2_rawautoca_on](https://cloud.githubusercontent.com/assets/5844619/25200431/95b92fde-254e-11e7-9001-1e3d8e11bbc8.jpg)

Raw CA correction on with patch:
![2015-12-04_karin_library_10_01-05_3_rawautoca_on_patched](https://cloud.githubusercontent.com/assets/5844619/25200430/95b91bd4-254e-11e7-8a86-82c4a3aa81e7.jpg)

**Comment by heckflosse** [comment]
I think I found the real culprit:

```
diff --git a/rtengine/CA_correct_RT.cc b/rtengine/CA_correct_RT.cc
index e1493ae..aea20d8 100644
--- a/rtengine/CA_correct_RT.cc
+++ b/rtengine/CA_correct_RT.cc
@@ -967,7 +967,7 @@ void RawImageSource::CA_correct_RT(const bool autoCA, const double cared, const
                         int c = FC(rr + top, left + border + (FC(rr + top, 2) & 1));
 
                         for (int row = rr + top, cc = border + (FC(rr, 2) & 1), indx = (row * width + cc + left) >> 1; cc < cc1 - border; cc += 2, indx++) {
-                            RawDataTmp[indx] = 65535.0f * rgb[c][(rr) * ts + cc] + 0.5f;
+                            RawDataTmp[indx] = 65535.0f * rgb[c][(rr) * ts + cc];
                         }
                     }
 

```

Edit: Short explanation to the patch:
The impact of adding 0.5 to red and blue channel (but not to green channel) increases for darker images and introduces the colour cast. It also means the output of raw ca correction is not the same as the input to ca correction for the part of the image where no ca has to be corrected.
Removing the addition of 0.5 solved the colour cast in my tests.

**Comment by Beep6581** [comment]
Tested using 3 images, I confirm that the fix worked very well!
https://filebin.net/iwd6sef5wiiep7ez

**Comment by Beep6581** [comment]
Thank you!

**Comment by heckflosse** [comment]
:)
