### ISSUE TITLE
ThresholdSelector does not react unless Modifier is pressed

### ISSUE THREAD

**Issue by ff2000** [Beep6581/RawTherapee#3838]
I have a weird issue with ThresholdSelector (e.g. Sharpening Threshold): I can't move a cursor and its secondary by simply clicking and moving. Moving one cursor by holding down SHIFT works. I pressed CTRL and I hit thresholdselector.cc:548 - dX *=0.05; (high precision movement?) - works.
Now I had the ingenious idea to press ALT - and that seems to work just fine now, both the selected cursor and its secondary move.

Now for the even weirder part: this only shows up on my laptop but not on my dads desktop. He is running kde (X11, not Wayland), I am running awesome wm. Both are linux (Gentoo, updated in parallel), X stack is identical. I tried QTile as an alternative X wm with no success. BUT Wayland seems to work, both Enlightenment and sway let me work the selector as intended. I even migrated my laptop to libinput (as that's what wayland compositors use - I was still on evdev, my dad's desktop still is) with no success. GTK on both systems is 3.22.11, but AFAIR this dates back to at least 3.20.x.

Any ideas? This could very well be a configuration issue. But a really weird one because I never experienced something like that before. Could this have something to do with focus as an additional key_press (SHIFT, CTRL, ALT) is required?

**Comment by Beep6581** [comment]
@ff2000 quick note that the alt key in KDE by default puts you into window moving mode. Maybe that's the difference?

**Comment by ff2000** [comment]
Just a short question before I dive deeper into this: do you say that I actually HAVE to press ALT to move two connected cursors separately? Because I couldn't find anything in the RawTherapee sources (and the Tooltip is silent about that, too). And that kwin translates Alt+click into just a click would be... weird.

**Comment by Beep6581** [comment]
@ff2000 using USM Sharpening's Threshold selector as an example, I can click-and-drag near the left end to move both the top and bottom left nodes, and near the right end to move both the top and bottom right nodes.

Use Shift to move a single node.

Do you still have an issue using at least 5.3 though preferably the latest `dev`, and using no less than GTK+ 3.22.0?

**Comment by Thanatomanic** [comment]
@ff2000 Old issue, but are you still able to reproduce this?

**Comment by ff2000** [comment]
@Thanatomanic thx for digging this out. I migrated to kde in the meantime. Fired up awesome and I had no issues. Awesome wasn't updated. Don't know what caused this all in the first place. I'm on gtk+-3.24.1 now.
