### ISSUE TITLE
Noise reduction preview is not applied over 50% zoom level 

### ISSUE THREAD

**Issue by mpavlase** [Beep6581/RawTherapee#3839]
Hi,
I've noticed, that noise reduction doesn't work when working with RAW images - only in Editor, after batch processing to produce JPG the result is fine.

Version:
5.0.5.0-gtk3, Fedora 25 (64bit)

How to reproduce it:
* open .CR2 picture in Editor tab
* leave Noise reduction off (disabled) from Detail tab
* zoom to 100% level
* turn on Noise reduction from Detail tab
* zoom to 50% level or smaller (33% i.e.)

Screenshots:
https://filebin.ca/3K8nVflcrJlE/50_off.png
https://filebin.ca/3K8oCRkOGYNw/50_on.png
https://filebin.ca/3K8nvaRPwfJs/100_off.png
https://filebin.ca/3K8nwps59bmO/100_on.png

Sample RAW file+profile:
https://filebin.ca/3K8jp83zc9pL/IMG_2673.CR2.pp3
https://filebin.ca/3K8jm0UKawXC/IMG_2673.CR2

Thanks!

**Comment by Beep6581** [comment]
http://rawpedia.rawtherapee.com/Noise_Reduction
