### ISSUE TITLE
RT built from GIT on Linux/Slackware hangs on startup.

### ISSUE THREAD

**Issue by Richard092345** [Beep6581/RawTherapee#3846]
[Solved]

I think I have solved the problem by updating the compile script to the latest version of rawtherapee.SlackBuild.

I have experienced systematic crashes from my git based builds of RT during the last months. The crashes occured when I opened a directory with a lot of raw files. 

I found out that I don't get that problem if I compile RT from file "rawtherapee-5.0.r1.gtk2.tar.xz" which is available from  SlackBuild.  The same directories that bug my git based build open nicely here.

Sorry for the false alarm.

**Comment by Beep6581** [comment]
@Richard092345 in the future please follow http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports
