### ISSUE TITLE
Curve tool in LAB panel does not always correctly expand

### ISSUE THREAD

**Issue by casta** [Beep6581/RawTherapee#3851]
Hi,

I have a weird GUI issue with the curve in the LAB panel. It usually happen at first time when opening a picture, and then it seems ok until I restart rawtherapee. Nothing critical but…
It may be due to my PP3 default profile [1], that enables the L* parametric curve but with all values set to 0 (I do that for convenience so that the curve is already expanded, since I use it quite frequently): ```LCurve=2;0.25;0.5;0.75;0;0;0;0;```

Basically, the usual steps to reproduce:
1. cold start rawtherapee
2. open a raw with my default profile [1]
3. scroll down to the LAB panel, the sliders under the already opened L* parametric curve are partially hidden.
4. scroll up/down the adjustment tools a few time, or switch the focus to some other window and switch back, the hidden sliders magically appears, and starting from now, the issue should have vanished until the next rawtherapee restart.

I have made a small screencast [2] showing the issue (could not do a screenshot since switching the focus make the issue disappear ;)). Look carefully at the right bottom of the screen.
Maybe something in the GUI structure not initialized at cold start ?

Thanks !!!

[1] https://www.xwing.info/dl/rawtherapee/PersoX100s.pp3
[2] https://www.xwing.info/dl/rawtherapee/rawtherapee.mp4

Version: 5.0-r1-gtk3-474-gd8e0207b
Branch: dev
Commit: d8e0207b
Commit date: 2017-04-28
Compiler: x86_64-pc-linux-gnu-gcc 5.4.0
Processor: Intel(R)\ Core(TM)\ i5-4690\ CPU\ @\ 3.50GHz
System: Linux
Bit depth: 64 bits
Gtkmm: V3.22.0
Build type: Gentoo
Build flags: -march=native -O3 -mtune=native -pipe -std=c++11  -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations
Link flags: -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -Wl,--sort-common
OpenMP support: yes
MMAP support: ON

**Comment by TooWaBoo** [comment]
This is a known bug in Gtk3.20 and there's no fix yet. If you hover some buttons with the mouse within this frame will correct the display. There are also some other curve tools affected eg. Retinex.

**Comment by casta** [comment]
Ok I did not catch this, looks indeed the same as #3525
