### ISSUE TITLE
5.1 locallab_dev build for Mac OSX

### ISSUE THREAD

**Issue by Benitoite** [Beep6581/RawTherapee#3856]
Just wanted to share this locallab_dev Mac OSX build, as I thought this would be a nice tool to have in one's toolbox.

https://filebin.net/rpwgtfra4z85d48y/RawTherapee_OSX_10.9_64_5.1-231-gd204369f.zip

```
Version: 5.1-231-gd204369f
Branch: locallab_dev
Commit: d204369f
Commit date: 2017-07-06
Compiler: clang-mp-3 3.9.1
Processor: generic x86
System: Apple
Bit depth: 64 bits
Gtkmm: V3.16.0
Build type: release
Build flags: -arch x86_64 -O3 -mmacosx-version-min=10.9 -std=c++11 -mtune=generic -Werror=unused-label -mmacosx-version-min=10.9 -flto -fopenmp=libomp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -O3 -DNDEBUG
Link flags: -arch x86_64 -mmacosx-version-min=10.9 -mtune=generic -headerpad_max_install_names -flto
OpenMP support: ON
MMAP support: ON
```

**Comment by Beep6581** [comment]
Screenshot:
![8b1abf048502697c4d69047accab1e1af2243b38](https://cloud.githubusercontent.com/assets/5844619/25672954/ffd0d308-3035-11e7-94f9-c91accf73553.jpg)

**Comment by ion12** [comment]
@Benitoite Thanks for sharing! 👍

**Comment by Benitoite** [comment]
@ion12 no prob, now up to Version: 5.1-231-gd204369f
