### ISSUE TITLE
What is RT-cli???

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#3859]
After compiling RT from the repository I got  an extra file called "rawtherapee-cli.exe"
What is it for?

Version: 5.0-r1-gtk3-483-gedfea689
Branch: dev
Commit: edfea689
Commit date: 2017-05-03
Compiler: gcc 6.3.0
Processor: undefined
System: Windows
Bit depth: 64 bits
Gtkmm: V3.22.0
Build type: release
Build flags: -mwin32 -m64 -mthreads -msse2 -std=c++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -mwindows -Wno-aggressive-loop-optimizations -DNDEBUG -O3
Link flags: -m64 -mthreads -static-libgcc -march=native -mwindows -s -O3
OpenMP support: ON
MMAP support: ON

**Comment by agriggio** [comment]
see #3691

**Comment by Hombre57** [comment]
@TooWaBoo I'll update RawPedia about rawtherapee-cli.
