### ISSUE TITLE
Curve pipette misbehaving when using new zoom levels

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3861]
1. Download http://rawtherapee.com/shared/test_images/colortarget/NIKON%20D600%20daylight.nef
2. Open, apply neutral.
3. Custom curve, enable pipette
4. Zoom to fit
5. Hover over the bottom gray row of patches. You should see the curve position indicator (vertical line) stay static as you move your cursor over a single patch, and the position of the indicator should coincide with the value of the patch. Instead what I see is the indicator move about wildly as I move the pipette over a single patch. e.g. hovering the pipette over the brightest patch (bottom-left) and moving the pipette from the center of the patch to the lower-right edge I see the indicator move from the dark tones of the histogram all the way to the light tones.

It works correctly when I zoom using the standard zoom factors - 16%, 20%, 25%, 33%, 50%, 100%, 200%, etc.
It does not work when using the new zoom levels, e.g. 18%.
![screenshot_20170504_143538](https://cloud.githubusercontent.com/assets/5844619/25703925/daa5ffca-30d7-11e7-8edb-390fa0396d2c.png)
![screenshot_20170504_143558](https://cloud.githubusercontent.com/assets/5844619/25703926/daa892f8-30d7-11e7-88d3-37f1016879af.png)
![screenshot_20170504_143813](https://cloud.githubusercontent.com/assets/5844619/25703923/da7f93e4-30d7-11e7-8fa4-bd22113080c1.png)

**Comment by heckflosse** [comment]
Confirmed

**Comment by agriggio** [comment]
investigating...

**Comment by agriggio** [comment]
I just pushed a fix, please confirm (reopening in the meantime)

**Comment by heckflosse** [comment]
Fix confirmed. Thank you :+1:

**Comment by Beep6581** [comment]
Fix confirmed, thank you.
