### ISSUE TITLE
Default language is the system one

### ISSUE THREAD

**Issue by 10110111** [Beep6581/RawTherapee#3864]
I've compiled RT 5.0-r1-gtk2 cloned from this git repo (`gtk2` branch) on my BLFS, and started it successfully. But I was surprized to see that its GUI doesn't speak the system language, which I have set to US English via `LANG` environment variable. Instead it talks to me in Russian, which is only present in `LC_CTYPE`. Here's what `locale` says:
```
$ locale
LANG=en_US
LC_CTYPE=ru_RU.UTF-8
LC_NUMERIC="en_US"
LC_TIME=en_GB.UTF-8
LC_COLLATE="en_US"
LC_MONETARY="en_US"
LC_MESSAGES="en_US"
LC_PAPER="en_US"
LC_NAME="en_US"
LC_ADDRESS="en_US"
LC_TELEPHONE="en_US"
LC_MEASUREMENT="en_US"
LC_IDENTIFICATION="en_US"
LC_ALL=
```
`LC_CTYPE` isn't supposed to be the system language, it's `LANG` which is.
I've checked Preferences→General→Use system language or, in fact, Настройки→Основные настройки→Использовать язык ОС, which it is by default, is checked. I had to uncheck it and explicitly select US English in the combobox to the right of the checkbox.

**Comment by agriggio** [comment]
confirmed. I think your analysis is correct.

**Comment by agriggio** [comment]
just pushed a candidate fix, please test -- though I believe it should be ok

**Comment by 10110111** [comment]
Cherry-picked it to `gtk2` branch, and it works OK here.
