### ISSUE TITLE
WB is causing strange artifacts in darker areas of the picture

### ISSUE THREAD

**Issue by praemdonck** [Beep6581/RawTherapee#3865]
I'm processing raw images of film negatives. I followed instructions from http://rawpedia.rawtherapee.com/Negative.

In general I'm getting good results, the more I overexpose the picture of the negative, the better the colours, however when I overexpose too much I'm getting artifacts in the darker areas of the picture. Changing the White balance sliders has an impact on the artifacts

Image Showing problem. Raw was overexposed by 3 stops (Most of the picture looks fine except darker area):
 

Processed JPG: https://www.dropbox.com/s/xm0vdhsf9ql1lii/DSC_3957.jpg?dl=0
NEF: https://www.dropbox.com/s/cw0thk78htmfhca/DSC_3957.NEF?dl=0
pp3: https://www.dropbox.com/s/1u2ww4ytrc8fihp/DSC_3957.NEF.pp3?dl=0
dcp file: https://www.dropbox.com/s/qrxuef95wfr7euv/Nikon_D7200_Negative_Base_Profile.dcp?dl=0

Same image overexposed by 2 stops, not showing the problem:
Processed JPG: https://www.dropbox.com/s/rashrxo04aie1fx/DSC_3956.jpg?dl=0
NEF: https://www.dropbox.com/s/g8as780vc9bp1pj/DSC_3956.NEF?dl=0
pp3: https://www.dropbox.com/s/u24fgcbd1etxs59/DSC_3956.NEF.pp3?dl=0
dcp file: same as for the previous picture.

To reproduce 
open .NEF
apply custom dcp file in color management
select Use DCP tones curve
set WB to auto

RawTherapee details (installed from ubuntu repository):

Branch: default
Version: 4.2.0
Changeset: c81d9026d25c
Compiler: x86_64-linux-gnu-gcc 5.2.1
Processor: undefined
System: Linux
Bit depth: 64 bits
Gtkmm: V2.24.4
Build type: Release
Build flags: -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -std=c++11 -D_FORTIFY_SOURCE=2   -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG
Link flags:  -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed
OpenMP support: ON
MMAP support: ON

Linux (Mint) Version:
Linux  4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

    *-cpu
          description: CPU
          product: Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
          vendor: Intel Corp.
          physical id: 46
          bus info: cpu@0
          version: Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
          slot: SOCKET 1150
          size: 3495MHz
          capacity: 4300MHz
          width: 64 bits
          clock: 100MHz

Memory: 8 Gb

Pablo

**Comment by Beep6581** [comment]
@praemdonck upgrade to RT5 as 4.2 is very old and unsupported. The artifacts are still reproducible in RT5 though.

To reproduce, download https://filebin.net/y9v1etj6ecrot9lt and open the raw file, apply neutral, select the negative DCP and enable the DCP curve. Improving the white balance (Auto) amplifies the problem.

Workaround: fix the exposure compensation, or set highlight compression to 100.
![imgur-2017_05_08-13 49 15](https://cloud.githubusercontent.com/assets/5844619/25803014/5318f6fe-33f5-11e7-97f2-dd9595ea0770.png)
![imgur-2017_05_08-13 50 23](https://cloud.githubusercontent.com/assets/5844619/25803013/53182ddc-33f5-11e7-8e04-05bcbcb2bdf8.png)

**Comment by praemdonck** [comment]
@Beep6581 Thanks for your response. Adjusting the exposure on RT 5 does the trick, (this is not the case with RT 4.2).

Just an observation: on RT 4.2 the image gets brighter when moving exposure compensation to the right, while on RT 5 it works in the opposite direction

**Comment by Beep6581** [comment]
@praemdonck IIRC it was because the DCP curve was moved before the Exposure tool in the engine pipeline after 4.2.
