### ISSUE TITLE
Microcontrast

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#3867]
Because Microcontrast tool works quite good for pixel shift files I started to optimize it.
While doing this I found a possible bug. Have a look at [this loop](https://github.com/Beep6581/RawTherapee/blob/dev/rtengine/ipsharpen.cc#L709):

```
            n = 0;

            for(row = j - k; row <= j + k; row++) {
                for(col = i - k, offset2 = row * width + col; col <= i + k; col++, offset2++) {
                    if (((v < LM[offset2]) && (signs[n] > 0)) || ((v > LM[offset2]) && (signs[n] < 0))) {
                        temp = v * 0.75f + LM[offset2] * 0.25f; // 0.75 0.25
                    }

                    n++;
                }
            }
```

It's obvious that the last iteration of the loop which fulfills the condition:
`if (((v < LM[offset2]) && (signs[n] > 0)) || ((v > LM[offset2]) && (signs[n] < 0)))`
wins.

If that's correct behaviour, then an easy way to optimize this loop is to process it backwards and step out on the first time the condition is fulfilled.

But in my opinion this is not the intended behaviour of this loop because the result of the loop would depend on whether it's processed forwards or backwards.

What do you think? Bug or not?

@Desmis Jaques, can you give me some insights?

Ingo

**Comment by Desmis** [comment]
@heckflosse 

Ingo
I am not at home and it is difficult for me to test. But, I was inspired by the work of Manuel LLorens with his agreement, it was in 2010 or 2011 , I think (before that date we were in a project hosted in Spain where other developers like Emil Martinec, Guillermo Luijk, ...).

I added features, but the code base with the loop is the same ... the one found on the site of M.LLorens at the time, and had been the subject of numerous tests by Internet users .
Maybe there is a bug, but if by deleting or modifying the code, the result is substantially identical, do not hesitate to optimize.

Thank you and have a good day.

Jacques

**Comment by heckflosse** [comment]
I created a [microcontrast](https://github.com/Beep6581/RawTherapee/tree/microcontrast) branch with a lot of optimizations.

With old code microcontrast processing time at default settings for a 36 MP file at my system is ~3200 ms, with new code it's ~880 ms.
There can be very small differences in output caused by optimized calculations and a solved data race.

Ingo

**Comment by heckflosse** [comment]
I [eliminated one loop](https://github.com/Beep6581/RawTherapee/commit/9a1dd0109b6abbda91d4505cfdd23f5617d0af38). Microcontrast processing time at default settings  for a 36 MP file at my system now is ~590 ms

**Comment by heckflosse** [comment]
With c856894  processing time now is ~490 ms

**Comment by Desmis** [comment]
@heckflosse 

Ingo

I come back from my family !
I just test new branch "microcontrast"

* processing time divided by 4
* no differences (or very very very small)

Very good job :)

Jacques

**Comment by heckflosse** [comment]
@Desmis Jacques, thanks for testing :+1: 
I will clean the code a bit before I push.

Ingo
