### ISSUE TITLE
deutsch translation of Pixel Shift controls

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#3872]
@TooWaBoo I just saw that you used '(Sensor-Matrix)\nFarbinterpolation\n' for 'Pixel Shift (PS)' in 'deutsch' translation file. What's the reason for that?

Ingo

**Comment by TooWaBoo** [comment]
It follows the rules I've used everywhere.
Tool Name -> Subtool Name(1) ... Subtool Name(n) -> Parameter Name

eg.
![unbenannt](https://cloud.githubusercontent.com/assets/13800920/26033380/59e108a4-38ab-11e7-9d71-328c8c86e93d.PNG)

**Comment by heckflosse** [comment]
ah, ok. I was just curious
