### ISSUE TITLE
raw_crop from user camconst.json file ignored if system camconst has entry

### ISSUE THREAD

**Issue by luisfl** [Beep6581/RawTherapee#3873]
Fedora 23 fully updated.
RawTherapee, version 5.0-r1-gtk3-502-gabd11da0

I cannot make the user's **camconst.json** file work. I am trying to only apply a crop over the system **camconst.json** file. So, I created a **camconst.json** file in ~/.config/RawTherapee5-dev with the following content:

{"camera_constants": [
    {
        "make_model": "OLYMPUS E-M1",
        "dcraw_matrix": [ 7687,-1984,-606,-4327,11928,2721,-1381,2339,6452 ],
        "raw_crop": [ 1200, 1200, 1352, 1088 ],
        "ranges": { "white": 4080 }
    }
]}

This is the content of the system **camconst.json** file with the "raw_crop" line added. Then, I do:

**rawtherapee-cli -q -d -Y -js3 -j95 -o 1.jpg -c rawfile**

Yet, the raw file is processed but not cropped. If I change the "raw_crop" line adding garbage, like

**"raw_crop": [ 120xxxxxxxx0, 1200, 1352, 1088 ],**

rawtherapee complains:

**JSON parse error in file "/home/gato/.config/RawTherapee5-dev/camconst.json" near '_crop":[12sssssss00,1200,1352,1088],"ranges":{"white":4080}}]}'**

So rawtherapee processes the file. If I change the system **camconst.json** adding the "raw_crop" line, file is cropped as it should.

It looks like the system **camconst.json** file is read after the user's file, overriding it.

**Comment by heckflosse** [comment]
@luisfl Thanks for reporting. I also read the related discussion on dpreview.com. I'll have a look tomorrow :)

Edit: As it's already past midnight, 'tomorrow' means 'today, after I got some sleep' ;-)

**Comment by Beep6581** [comment]
According to my tests, its only `raw_crop` which is ignored in my user file, but `ranges` and `dcraw_matrix` from my user file correctly override the system one.

Interestingly, if the system `camconst.json` has an entry for my camera, _even if that entry has no `raw_crop`property_, then the `raw_crop` from my user `camconst.json` is ignored.

**Comment by luisfl** [comment]
My camera does not have raw_crop in the system file either. But if I remove my camera from the system file, the user file is executed properly.

**Comment by sguyader** [comment]
Indeed I see the same here, the custom white level in my user camconst file is taken into account, but not the raw_crop.

**Comment by luisfl** [comment]
Great! I'll test it when the updated RPM package be available in 
http://download.opensuse.org/repositories/home:/rawtherapee/Fedora_23/x86_64/
Thanks!

**Comment by Beep6581** [comment]
Hi @sguyader , did you get my emails 4 and 1 day ago?
Would you have time to make a Windows build if we release 5.1 tomorrow?

**Comment by sguyader** [comment]
Hi Morgan,
Ok I'll try to make a new build. As I said in the past, it's become quite a
pain for me to make Windows build as I do it in a Virtualbox machine which
gets only part of my already low system resources. Which is is why I always
wait to see if someone else can make a build quickly.
I didn't update my MSYS2 install, so it will be a GTK 3.18 build​.
Sébastien

**Comment by luisfl** [comment]
Confirmed: working in stable 5.1.

**Comment by heckflosse** [comment]
@luisfl Thanks for testing and confirming :+1:

**Comment by luisfl** [comment]
@heckflosse  Thanks to all of you for your great work. Immensely appreciated.
