### ISSUE TITLE
Library module does not load any RAW files or JPG files

### ISSUE THREAD

**Issue by jaijujacob** [Beep6581/RawTherapee#3878]
Hi,

I updated RawTherapee 5.1 today. When I open any folder with RAW(CR2) files or JPGs, nothing gets loaded. I updated from 4.2. Seems like some minor conf issue.

Please suggest what need to be done. I am unable to open any images in RawTherapee now

If you are filing a bug report, please first read the guide How to Write Useful Bug Reports:
http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports
You must provide the required information in order for your bug report to be valid.
Delete this text before posting.

**Comment by agriggio** [comment]
Hi @jaijujacob 
can you please make sure that the relevant file extensions are checked in "Preferences -> File Browser"? (see screenshot)
![shot](https://cloud.githubusercontent.com/assets/11982086/26141100/78a39a32-3ada-11e7-9878-97fe7debdaba.jpg)

Also, try to clear the cache completely ("Clear all" button in the same screenshot)

**Comment by Beep6581** [comment]
If you're updating from 4.2 then its best if you delete the [options](http://rawpedia.rawtherapee.com/File_Paths) file while RT is not running.

**Comment by jaijujacob** [comment]
Thanks a lot! I removed options and restarted RawTherapee. Everything works great (y)
