### ISSUE TITLE
Cant open files with spaces in name for edit in external editor: Affinity Photo

### ISSUE THREAD

**Issue by giggedy** [Beep6581/RawTherapee#3883]
Version: RawTherapee 5.0-r1-gtk3
OS: MS Windows 10 Pro Build 15063
CPU: Intel i7 4790K @4Ghz
Memory: 16GB
Downloaded http://rawtherapee.com/releases_head/windows/RawTherapee_5.1_WinVista_64.zip

Cant open files with spaces in name for edit in external editor: Affinity Photo.
Filenames without spaces works.
The problem persists in 5.1. Had to revert to 5.0 because of another problem I will report.

Preferences\External editor: "C:\Program Files\Affinity\Affinity Photo\photo.exe"
Open a .NEF-file with spaces in name. In this case "NEF with spaces in name.NEF"
Use shortcut Ctrl-e to edit in Affinity Photo

Attached screenshots:

![rt-affinityopenerror-1](https://cloud.githubusercontent.com/assets/28889539/26345856/7fda8d6e-3fa4-11e7-83d7-4fb3128457b4.jpg)
![rt-affinityopenerror-2](https://cloud.githubusercontent.com/assets/28889539/26345857/7fdbec22-3fa4-11e7-9c89-db42b6789f20.jpg)
![rt-affinityopenerror-3](https://cloud.githubusercontent.com/assets/28889539/26345860/7fe5b4a0-3fa4-11e7-8fdc-a63999d7308b.jpg)
![rt-affinityopenerror-4](https://cloud.githubusercontent.com/assets/28889539/26345858/7fdee580-3fa4-11e7-9088-209d5ee98991.jpg)
![rt-affinityopenerror-5](https://cloud.githubusercontent.com/assets/28889539/26345861/802b71fc-3fa4-11e7-8614-3f80087c4151.jpg)
![rt-execpath](https://cloud.githubusercontent.com/assets/28889539/26345859/7fdee4b8-3fa4-11e7-88d8-8ed0dc884f08.jpg)

**Comment by Beep6581** [comment]
And if you remove the quotes?

**Comment by gaaned92** [comment]
confirmed on W10 with Rawtherapee 5.1
Send a photo with blank in name to xnviewMP ==> file not found

**Comment by giggedy** [comment]
The behaviour is the same, with or without quotes.
This works with Photoshop, and as a workaround I can copy Affinitys photo.exe to photoshop.exe and in "Preferences\External Editor" select "Affinity Photo" as directory in "Adobe Photoshop installation directory" and check the checkbox for Adobe. If that made any sense.

**Comment by Beep6581** [comment]
Try this patch:
```diff
diff --git a/rtgui/extprog.cc b/rtgui/extprog.cc
index bdbbb85b..7b82461c 100644
--- a/rtgui/extprog.cc
+++ b/rtgui/extprog.cc
@@ -324,7 +324,7 @@ bool ExtProgStore::openInCustomEditor (const Glib::ustring& fileName)
 #if defined WIN32
 
     const auto cmdLine = Glib::ustring("\"") + options.customEditorProg + Glib::ustring("\"");
-    auto success = ShellExecute( NULL, "open", cmdLine.c_str(), fileName.c_str(), NULL, SW_SHOWNORMAL );
+    auto success = ShellExecute( NULL, "open", cmdLine.c_str(), Glib::ustring("\"") + fileName.c_str() + Glib::ustring("\""), NULL, SW_SHOWNORMAL );
     return (uintptr_t)success > 32;
 
 #elif defined __APPLE__
```

**Comment by giggedy** [comment]
OK, that was fast.
It will take me some time to set up an environment to compile it and I can't do it right now.

**Comment by giggedy** [comment]
Ah, OK.
METM then.

**Comment by Floessie** [comment]
@Beep6581 You can also quote it like this (a bit shorter):
```c++
auto success = ShellExecute( NULL, "open", cmdLine.c_str(), ('"' + fileName + '"').c_str(), NULL, SW_SHOWNORMAL );
```

**Comment by gaaned92** [comment]
@Beep6581 first patch (with  Glib::ustring("\"")...) doesn't compile on W10.

Second compiles and build. The quoted name is transmitted and xnviewmp opens. So OK

@giggedy  You can find here [https://drive.google.com/open?id=0B2q9OrgyDEfPS2FpdDAtMVI1RG8](urhttps://drive.google.com/open?id=0B2q9OrgyDEfPS2FpdDAtMVI1RG8)
the patched build RawTherapee_dev_5.1-18-patched_WinVista_64.zip
