### ISSUE TITLE
On Windows, previously opened raw files can't be moved or deleted until RawTherapee is closed

### ISSUE THREAD

**Issue by giggedy** [Beep6581/RawTherapee#3884]
Previously opened NEF-file can't be moved or deleted until RawTherapee is closed.

Version: 5.1
OS: MS Windows 10 Pro Build 15063
CPU: Intel i7 4790K @4Ghz
Memory: 16GB
Downloaded http://rawtherapee.com/releases_head/windows/RawTherapee_5.1_WinVista_64.zip

Open .NEF-file in RawTherapee 5.1.
Close .NEF-file.
The .NEF-file can't be moved or deleted until RawTherapee is closed.

![rt-wontclosefile](https://cloud.githubusercontent.com/assets/28889539/26349756/1a39bcfc-3fb1-11e7-9026-5ca79183a207.jpg)

**Comment by Beep6581** [comment]
Please don't crop screenshots.

Are you working in METM or SETM?

Cannot reproduce in Linux.

**Comment by giggedy** [comment]
Oh, sorry about the crop.
Not sure what METM or SETM means so I guess no is the right answer :)

**Comment by Beep6581** [comment]
They're editor tab modes:
http://rawpedia.rawtherapee.com/The_Image_Editor_Tab#Editor_Tab_Modes
See Preferences > General > Layout, the default is SETM,VT

**Comment by giggedy** [comment]
Ah, OK.
METM then.

**Comment by heckflosse** [comment]
Bug confirmed on win7/64. Also for SETM and CR2 files. Works fine with jpgs.

**Comment by heckflosse** [comment]
I take this one though I'm not sure if I will find the culprit.

**Comment by heckflosse** [comment]
When building without MMAP support it works fine. That will make it easier to find the culprit.

**Comment by heckflosse** [comment]
I feel the need to discuss why mmap is still used for loading raw files.

@Floessie @agriggio Any thoughts from you?

**Comment by Floessie** [comment]
@heckflosse Ingo, I'm sure you wouldn't ask, if you had not benchmarked it. :smile: Theoretically mmapping should be faster. Have you checked the return value of `UnmapViewOfFile()`? The rest looks sane to me, although I'm not familiar with the Win API.

**Comment by heckflosse** [comment]
The file was opened twice but closed only once.
This fixes it:

```diff
diff --git a/rtengine/rawimage.cc b/rtengine/rawimage.cc
index d8dc7eb1..7b6ee878 100644
--- a/rtengine/rawimage.cc
+++ b/rtengine/rawimage.cc
@@ -39,6 +39,7 @@ RawImage::~RawImage()
 {
     if(ifp) {
         fclose(ifp);
+        ifp = nullptr;
     }
 
     if( image ) {
@@ -410,7 +411,11 @@ int RawImage::loadRaw (bool loadData, unsigned int imageNum, bool closeFile, Pro
     verbose = settings->verbose;
     oprof = nullptr;
 
-    ifp = gfopen (ifname);  // Maps to either file map or direct fopen
+    if(!ifp) {
+        ifp = gfopen (ifname);  // Maps to either file map or direct fopen
+    } else  {
+        fseek (ifp, 0, SEEK_SET);
+    }
 
     if (!ifp) {
         return 3;

```

**Comment by heckflosse** [comment]
I would appreciate if someone could test the patch on Linux before I push it :)

**Comment by Beep6581** [comment]
I compiled in Linux using the patch and opened `1.pef` and then switched to `2.pef`. I deleted both files and associated PP3 files while RawTherapee was running and `2.pef` was still open in the Editor. This is the same behavior as before the patch. I then switched to `3.pef` and closed RT. No problems.
