### ISSUE TITLE
rawtherapee-cli (5.1) crashing with -t option

### ISSUE THREAD

**Issue by albfe** [Beep6581/RawTherapee#3891]
when specifying the -t option, rawtherapee-cli crashes with the following message:
awtherapee-cli -o /tmp/ -t -c xxx.cr2 
RawTherapee, version 5.1, command line
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::at: __n (which is 2) >= this->size() (which is 2)

Also adding the -b8 option does not change the result. It works fine with -tz

**Comment by heckflosse** [comment]
Bug confirmed.
