### ISSUE TITLE
Canon EOS 77D support

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3893]
Waiting for raw files from https://discuss.pixls.us/t/canon-77d-raw-support-colour-problems/4300

```json
    { // Quality X
        "make_model": "Canon EOS 77D",
        "dcraw_matrix": [ 7377,-0742,-0998,-4235,11981,2549,-0673,1918,5538 ] // Adobe DNG Converter 9.10.1
    },
```

Ping @iliasg

**Comment by kubman** [comment]
Files are here: <a href="http://www.smnd.sk/kubman/77D_raw.7z">http://www.smnd.sk/kubman/77D_raw.7z </a>

**Comment by Beep6581** [comment]
Support for the Canon EOS 77D was added in the most recent `camconst.json` update, commit 10822f5c2ece7f3d99ea9ff91bea3b240d910152.
