### ISSUE TITLE
"Save to folder" fails on some special characters

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3900]
From https://discuss.pixls.us/t/3-problems-with-new-rt-5-1-output-config/4313

When the Windows 10 user tries to set the output directory to `D:\Obróbka\Out` in the Queue tab, RT fails with "Invalid byte sequence in conversion input".
![cf99cbc503e80f2f092a81e57b6ba9a7aba9b059](https://cloud.githubusercontent.com/assets/5844619/26598530/d2109f20-4575-11e7-8461-3da44045b57d.jpg)

Steps to reproduce:
> Click "Save to folder"
Menu list
Find my folder (with "ó" in path)
Click "Select folder"
In this field is "None"
I repeat this procedure and result is: 
![3e384ff598992b789880a34dd1183c9f7d7bebd4](https://cloud.githubusercontent.com/assets/5844619/26600329/f901f952-457b-11e7-8415-c7c0032ccbba.jpg)

**Comment by heckflosse** [comment]
Fixed some time ago. Don't remember the commit
