### ISSUE TITLE
New fast mac 5.1 build using clang-mp-3 3.9.1

### ISSUE THREAD

**Issue by Benitoite** [Beep6581/RawTherapee#3903]
This _should_ work for OS X 10.9+ Tested on 10.11 and 10.12.
This build addresses the couple of mac issues https://github.com/Beep6581/RawTherapee/issues/3899 Cairo Font Crash https://github.com/Beep6581/RawTherapee/issues/3882 Renaming App Problem
Known issue: intermittent crash on exit after editing images. 

https://filebin.net/fpn3joegylydvr3x/RawTherapee_OSX_10.9_64_5.1.zip
```
Version: 5.1
Branch: 5.1
Commit: f23d70fd
Commit date: 2017-05-15
Compiler: clang-mp-3 3.9.1
Processor: generic x86
System: Apple
Bit depth: 64 bits
Gtkmm: V3.16.0
Build type: release
Build flags: -arch x86_64 -O3 -std=c++11 -mtune=generic -Werror=unused-label -mmacosx-version-min=10.9 -flto -fopenmp=libomp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -O3 -DNDEBUG
Link flags:  -mtune=generic -headerpad_max_install_names -flto
OpenMP support: ON
MMAP support: ON
```

**Comment by Beep6581** [comment]
@Benitoite thank you for making builds! Consider advertising your build in the forum to get more exposure.
