### ISSUE TITLE
Display release notes only if new major version

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3905]
Every time I test a new build the Release Notes window pops up and seeing it so often gets annoying. All I know about C++ is how to spell it, but to my great surprise this patch in branch [lessrelnotes](https://github.com/Beep6581/RawTherapee/compare/lessrelnotes) seems to work. Could someone take a look?

**Comment by heckflosse** [comment]
Builds and works fine on win7/64

**Comment by Beep6581** [comment]
The code's not shit? :smile:

**Comment by heckflosse** [comment]
Don't ask me about regex :)

**Comment by Beep6581** [comment]
Merged.
