### ISSUE TITLE
"Reset to default" vs. "Custom profile builder" workflow blocking issues

### ISSUE THREAD

**Issue by raceviper13** [Beep6581/RawTherapee#3906]
I am struggling with a change to RawTherapee 5.1.

[My problem is...]
Execution of the custom profile builder has substantially changed.  "Reset to default" (no longer called "Custom profile builder") now passes a pre-filled PP3 to my custom profile builder on opening an unedited file.  Additionally, I have been informed that there is no longer an ability ask RT to run the custom profile builder on an edited image.  Currently with 5.1, my workflow is absolutely blocked.

[What I am requesting...]
I am asking that we re-activate the "Custom profile builder" item in the menu.  The "Reset to default" can remain for those who requested it.  Additionally, I need a means to provide an essentially empty PP3 to my custom profile builder when opening an unedited file.

[Why I am requesting this...]
Workflow explanation:  (This is a problem to me due to the following).  Using a previous versions of RT...

1. Opening an unedited image, my profile builder would edit a PP3 which was essentially blank, then configure it per many parameters.
2. Opening a pre-edited image, my profile builder edit a PP3 which was already complete, then configure it depending what is already in the PP3.

The key is my custom profile builder would retrieve seven (7) key values in the existing PP3.  It would not  change those values when editing the PP3.

However, there are many other keys that are changed regardless if they already exist.  Therefore I could run the custom profile builder at any time and not worry if careful edits that I perform during my workflow are lost.

```
Version: 5.1
Branch: 5.1
Commit: f23d70fd
Commit date: 2017-05-15
Compiler: gcc 6.3.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.22.0
Build type: release
Build flags: -m64 -mwin32 -mthreads -Werror=unused-label -Werror=unknown-pragmas -Wno-aggressive-loop-optimizations -std=c++11 -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -mwindows -DNDEBUG -msse2 -O3
Link flags: -m64 -mthreads -static-libgcc -mtune=generic -mwindows -s -O3
OpenMP support: ON
MMAP support: ON
```

**Comment by agriggio** [comment]
Here's a patch that restores (more or less) the old behaviour of the custom profile builder. This is still invoked by calling "Reset to default", I didn't add a dedicated menu item for it. What it does:

1. the first time you open an unedited image, the custom profile builder is
   invoked without generating any pp3 file before

2. if you use "Reset to Default" and you have a custom profile builder set,
   the current pp3 is not actually reset, but the only thing that happens is
   that the custom profile builder is rerun (and so it is free to modify
   in-place the current pp3).

Please test and let me know if this is ok for you, thanks.

```diff
diff --git a/rtgui/thumbnail.cc b/rtgui/thumbnail.cc
--- a/rtgui/thumbnail.cc
+++ b/rtgui/thumbnail.cc
@@ -218,35 +218,36 @@
     const CacheImageData* cfs = getCacheImageData();
     Glib::ustring defaultPparamsPath = options.findProfilePath(defProf);
     const bool create = (!hasProcParams() || force);
+    const bool run_cpb = !options.CPBPath.empty() && !defaultPparamsPath.empty() && cfs && cfs->exifValid && create;
 
     const Glib::ustring outFName =
         (options.paramsLoadLocation == PLL_Input && options.saveParamsFile) ?
         fname + paramFileExtension :
         getCacheFileName("profiles", paramFileExtension);
 
-    if (defProf == DEFPROFILE_DYNAMIC && create && cfs && cfs->exifValid) {
-        rtengine::ImageMetaData* imageMetaData;
-        if (getType() == FT_Raw) {
-            rtengine::RawMetaDataLocation metaData = rtengine::Thumbnail::loadMetaDataFromRaw(fname);
-            imageMetaData = rtengine::ImageMetaData::fromFile (fname, &metaData);
-        } else {
-            imageMetaData = rtengine::ImageMetaData::fromFile (fname, nullptr);
+    if (!run_cpb) {
+        if (defProf == DEFPROFILE_DYNAMIC && create && cfs && cfs->exifValid) {
+            rtengine::ImageMetaData* imageMetaData;
+            if (getType() == FT_Raw) {
+                rtengine::RawMetaDataLocation metaData = rtengine::Thumbnail::loadMetaDataFromRaw(fname);
+                imageMetaData = rtengine::ImageMetaData::fromFile (fname, &metaData);
+            } else {
+                imageMetaData = rtengine::ImageMetaData::fromFile (fname, nullptr);
+            }
+            PartialProfile *pp = ProfileStore::getInstance()->loadDynamicProfile(imageMetaData);
+            int err = pp->pparams->save(outFName);
+            pp->deleteInstance();
+            delete pp;
+            if (!err) {
+                loadProcParams();
+            }
+        } else if (create && defProf != DEFPROFILE_DYNAMIC) {
+            const PartialProfile *p = ProfileStore::getInstance()->getProfile(defProf);
+            if (p && !p->pparams->save(outFName)) {
+                loadProcParams();
+            }
         }
-        PartialProfile *pp = ProfileStore::getInstance()->loadDynamicProfile(imageMetaData);
-        int err = pp->pparams->save(outFName);
-        pp->deleteInstance();
-        delete pp;
-        if (!err) {
-            loadProcParams();
-        }
-    } else if (create && defProf != DEFPROFILE_DYNAMIC) {
-        const PartialProfile *p = ProfileStore::getInstance()->getProfile(defProf);
-        if (p && !p->pparams->save(outFName)) {
-            loadProcParams();
-        }
-    }
-    
-    if (!options.CPBPath.empty() && !defaultPparamsPath.empty() && create && cfs && cfs->exifValid) {
+    } else {
         // First generate the communication file, with general values and EXIF metadata
         rtengine::ImageMetaData* imageMetaData;
 
```

**Comment by raceviper13** [comment]
Unfortunately I am unable to test this patch as I do not have the time to learn how to compile a build or apply a patch.  I appreciate the work to add it, but cannot test.

Is there something I can do to help someone else test?

**Comment by gaaned92** [comment]
@raceviper13
If you want to test, RawTherapee_dev_5.1-38-#3906_WinVista_64.zip uploaded at [https://drive.google.com/open?id=0B2q9OrgyDEfPS2FpdDAtMVI1RG8](https://drive.google.com/open?id=0B2q9OrgyDEfPS2FpdDAtMVI1RG8)

**Comment by raceviper13** [comment]
This worked very well.  I hope that those who are using the new functionality will not be affected.  This is a great solution for my workflow.

Thanks!!!!

**Comment by gaaned92** [comment]
@agriggio  did you commit this fix ?

**Comment by agriggio** [comment]
@gaaned92 not yet. If there are no objections, I can do it later today
