### ISSUE TITLE
New image browser menu item "Reset to default" is misleading

### ISSUE THREAD

**Issue by raceviper13** [Beep6581/RawTherapee#3907]
If we are going to keep it around as is, we may want to rename "Reset to default".  That term implies to me that we are resetting the image to how RT likes to apply settings for all newly edited images without any customization.

Maybe "Apply user defaults" instead.

**Comment by Beep6581** [comment]
The term used must relate to Preferences > Image Processing > Default Processing Profile, i.e. the word "Default" is key here. "User" seems completely unnecessary and even misleading.
"Reset to default" and "Apply default" seem equally fine to me, the former having the benefit of being already translated.
