### ISSUE TITLE
Large memory leak when switching folder in file browser

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#3908]
When switching folders in file browser, there is a large memory leak.

To reproduce:
1. create two folders with about 200 files
2. switch between this folders a lot of times
=> at my system the memory usage of rt increases by about 20 MB per switch

I can reproduce it with current dev build of rt and also with 5.0 build on Win7/64
@Beep6581 can reproduce it also on Linux

**Comment by agriggio** [comment]
From my quick analysis, this happens when you switch dirs while some of the thumbnails are still loading. @heckflosse, can you confirm this? If so, that's because the current code is not very clear about who owns some of the pointers (especially of `FileBrowserEntry` objects) that are passed around during the loading of dirs. This is one of the leaks (there might be others):

- `FileCatalog::previewReady` gets called by `PreviewLoader::Impl::processNextJob`.

- if we have not switched folders in the meantime (i.e. after the preview loader object was created), then `FileCatalog::previewReady` will call `FileBrowser::addEntry`, which in turn will delete the input `FileBrowserEntry` (indirectly, within a idle handler)

- however, if we have switched folders in the meantime, then `FileCatalog::previewReady` will simply do nothing, meaning it will just return *without deleting* the entry.


You can try this quick'n'dirty patch and see whether it solves the leak (**warning:** untested):


```diff
diff --git a/rtgui/filecatalog.cc b/rtgui/filecatalog.cc
--- a/rtgui/filecatalog.cc
+++ b/rtgui/filecatalog.cc
@@ -720,6 +720,7 @@
 {
 
     if ( dir_id != selectedDirectoryId ) {
+        delete fdn;
         return;
     }
 
```


The proper solution, though, would be to refactor the code and be clear on the ownership of the pointers. Using a smart pointer (e.g. `std::shared_ptr`) would be advisable if possible.

**Comment by Beep6581** [comment]
I noticed while reproducing this in a debug build (dev, unpatched) under GDB that all cores are maxed-out for well over a minute after all the thumbnails have loaded, after the tab label switches from showing 100% to showing the actual number.

**Comment by heckflosse** [comment]
@agriggio Thanks for the patch.
As I always waited until cpu load was at 0 before I switched folders, it does not fix the leak. But as it fixes another possible leak, we should commit it nevertheless.
Also (with and without your patch) I get a crash after switching folders about 30 times.
@Beep6581 got that crash on Linux too.

Alberto, could you make a run with one or more of this options enabled : #3167 ?
I would do that, but on Windows the sanitizers are not supported and my Linux is a Sabayon which only supports gcc 4.9.3 :(

**Comment by agriggio** [comment]
ok, I'll test as soon as I can

**Comment by heckflosse** [comment]
@agriggio Alberto, thank you :+1:

**Comment by heckflosse** [comment]
@agriggio Alberto, I just saw that the AddressSanitizer is supported in gcc >= 4.8
Means I can test it on my Sabayon. Already compiling...

**Comment by agriggio** [comment]
@heckflosse Ingo, I'm already taking a look... there are several leaks that I'm trying to fix, I'll follow up asap

**Comment by heckflosse** [comment]
@agriggio Alberto, this patch fixes the leak:

```
diff --git a/rtgui/thumbbrowserentrybase.cc b/rtgui/thumbbrowserentrybase.cc
index 6fa8eac5..378e8d63 100644
--- a/rtgui/thumbbrowserentrybase.cc
+++ b/rtgui/thumbbrowserentrybase.cc
@@ -56,20 +56,12 @@ void ThumbBrowserEntryBase::updateBackBuffer ()
 
     Gtk::Widget* w = parent->getDrawingArea ();
 
-    Glib::RefPtr<Gdk::Window> win = w->get_window();
-
-    if (!win)
-        // Nothing to draw on, so we return
-    {
-        return;
-    }
-
     if (backBuffer && (backBuffer->getWidth() != exp_width || backBuffer->getHeight() != exp_height )) {
         // deleting the existing BackBuffer
         backBuffer.reset();
     }
     if (!backBuffer) {
-        backBuffer = Glib::RefPtr<BackBuffer> ( new BackBuffer (exp_width, exp_height, win) );
+        backBuffer = Glib::RefPtr<BackBuffer> ( new BackBuffer (exp_width, exp_height, Cairo::FORMAT_RGB24) );
     }
 
     // If thumbnail is hidden by a filter, drawing to it will crash

```

I need a review of the patch because I'm not really knowing what I'm doing...
But it fixes it \o/

@Desmis Jacques, that also fixes the 2 windows gdi handles per thumb leak in file browser (but not the gdi handles leak in metm)

**Comment by heckflosse** [comment]
I included the patch from last post into branch 'valgrind_fixes'. With SETM it's much more stable now.
I tried switching between folders with 3072 files a lot of times and got no crash \o/

But using SETM showed another small windows gdi handles leak. When hovering over thumbs in SETM filmstrip each popup of thumb image informations leaks 2 windows gdi handles

**Comment by heckflosse** [comment]
@Hombre57 Your help and expertise for this stuff would be very very welcome!!!

**Comment by agriggio** [comment]
@heckflosse Ingo, great! I'll try to take a look later today.

**Comment by Desmis** [comment]
@heckflosse 

Hello Ingo

My question.... how do you find that ??

I think all our problems come from GTK3 (and Cairo ?? ) but I am not surprised by your skills, but why "Cairo::FORMAT_RGB24" ...

Jacques

**Comment by heckflosse** [comment]
@Desmis Jacques, I looked for changes made for gtk3 branch and detected this backbuffer stuff.
Then I simply tried. I used FORMAT_RGB24 because it was used [here](https://github.com/Beep6581/RawTherapee/blob/dev/rtgui/guiutils.cc#L1336) too

**Comment by Desmis** [comment]
@heckflosse 

Thank you :)

**Comment by Hombre57** [comment]
@heckflosse @agriggio What about reference count [when doing this](https://github.com/Beep6581/RawTherapee/blob/dev/rtgui/guiutils.cc#L1340) ?

**Comment by Hombre57** [comment]
@heckflosse You patch is correct. Please delete `BackBuffer::BackBuffer(int width, int height, Glib::RefPtr<Gdk::Window> referenceWindow)` from guiutils.cc as it's not used anymore and broken (`cast_static` is not what I've guessed...)

**Comment by agriggio** [comment]
I'm not familiar with Cairo. I'll check the docs

Il 25 Giu 2017 2:40 PM, "Jean-Christophe" <notifications@github.com> ha
scritto:

**Comment by heckflosse** [comment]
@Hombre57 I deleted `BackBuffer::BackBuffer(int width, int height, Glib::RefPtr<Gdk::Window> referenceWindow)`, pushed and merged valgrind_fixes into dev.
