### ISSUE TITLE
Link on rawtherapee.com is pointing to google code (not GitHub)

### ISSUE THREAD

**Issue by socomajor** [Beep6581/RawTherapee#3914]
Hi all,
This is no bug, but I didn't know any other way to tell this to the devs : 
The link to the source on the features page is broken on : http://rawtherapee.com/blog/features 
(actually not broken but pointing to the old google code hosting).

It might be good to update this. I don't know Raw Therapee yet but I almost gave up when I saw the last commit on google code was from 2015. Happily I found the GitHub repo and am know about to install. 

See ya !

**Comment by Beep6581** [comment]
Thank you @socomajor , fixed.
