### ISSUE TITLE
File deletion does not work properly in RT 5.1

### ISSUE THREAD

**Issue by icom962** [Beep6581/RawTherapee#3918]
When deleting files with RT 5.1 only the .pp3 file get deleted, and the original .nef remains available, although not shown in RT file browser. However, the files are still there and also show up in RT next time it is started. When then again marking the files for deletion (having no .pp3 companions), deletion finally works.
It's the first time I'm experiencing something similar.

I'm using the version 5.1 for Win Vista/7/8/10 64 bit fast from RT download page on Win10 64 bit

_(Version: 5.1. Branch: 5.1, Commit: f23d70fd, Commit date: 2017-05-15, Compiler: gcc 6.3.0, Processor: generic x86, System: Windows, Bit depth: 64 bits, Gtkmm: V3.22.0, Build type: release
Build flags:  -m64 -mwin32 -mthreads  -Werror=unused-label -Werror=unknown-pragmas -Wno-aggressive-loop-optimizations -std=c++11 -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -mwindows -DNDEBUG -msse2 -O3
Link flags: -m64 -mthreads  -static-libgcc   -mtune=generic -mwindows -s -O3
OpenMP support: ON, MMAP support: ON)_

**Comment by heckflosse** [comment]
I tried this:

1. Opened a folder with 3 files (all having pp3 files)
2. Clicked the 'Move to trash' icon for one file
3. Ctrl-t to show content of trash
4. Clicked the trash icon to permanently delete the trash content

Worked fine here (Win7/64): Looked in explorer: File is deleted.

**Comment by icom962** [comment]
Ok, tried the same with 3 files - with the same result, i.e. everything seems to be ok "now suddenly".
Then did another test with about 50 files, since actually I'm working with 50-200 fiels per folder - also worked. Maybe clearing of cache had helped? I'll continue watching this for the next days.

**Comment by icom962** [comment]
Did it again now: I had one folder with 97 .nef files, thereof I marked 23 for deletion. Deleting with the trash icon again only deleted the .pp3, not the .nef. When closing RT and opening again, the files show up again, however, without the green check mark. So again I marked them for deletion - and then it worked.

Made the same experience with a second folder and about 50 files.
What might give a hint: after having clicked the trash icon such deleting the .pp3, I tried to delete one of the remaining .nefs directly in the win explorer: it told me: "_file in use: file cannot be deleted because it's open in RT_" (free translation from a german windows 10).

Any ideas?

**Comment by Beep6581** [comment]
"Deleting with the trash icon" is probably where you're going wrong. The trash icon does not delete files, it marks them as being trash and hides them from view.
You're looking for right-click > File operations > Delete.

**Comment by heckflosse** [comment]
@icom962 Maybe that's this issue https://github.com/Beep6581/RawTherapee/commit/e242afedd67bb826f1b40ae40c50ca947c8b4e57, which is fixed in dev build but not in f23d70fdb2414d529148d04a5ef96facd1c790fe

**Comment by Beep6581** [comment]
I just documented deleting and the trash bin:
http://rawpedia.rawtherapee.com/The_File_Browser_Tab#Deleting_Files

**Comment by icom962** [comment]
@Beep6581 - I think I'm not doing this wrong - what I meant is the trash icon shown to the left of the trash contents ("_permanently delete ..._") - it has been working ever since and only now in RT 5.1. showed the behavior described above.

@heckflosse  - the issue you pointed out seems to be what I'm experiencing - so probably I should try with a dev build.

**Comment by Kolli96** [comment]
Same problem here. Does not delete RAW files. In the old version played well but this not.

System is Windows 10 64-bit and RT 5.1 64-bit version.

**Comment by Beep6581** [comment]
@Vike95 @icom962 could you try the latest dev build from @gaaned92 or @sguyader ?

**Comment by heckflosse** [comment]
@Vike95 See 3 posts above your post.

**Comment by Kolli96** [comment]
Where I can download latest dev version on Windows 10 64-bit?

**Comment by heckflosse** [comment]
@Vike95 You can find nightly builds [here](https://drive.google.com/drive/folders/0B2q9OrgyDEfPS2FpdDAtMVI1RG8)

**Comment by Beep6581** [comment]
@Vike95 as @heckflosse wrote, and get the build that starts with "RawTherapee_dev_5.1-", the newest one at the time of writing is `RawTherapee_dev_5.1-141-gded8c66f_WinVista_64.zip` from July 13.

**Comment by Kolli96** [comment]
This RawTherapee_dev_5.1-141-gded8c66f_WinVista_64.zip version does not start in Windows 10 64-bit. 
Process rawtherapee.exe start but shuts down after a few seconds. 

I delete normal version+ any folders and I Install this dev version administrator account and antivirus program does not prevent this program. No any errors.

**Comment by heckflosse** [comment]
@Vike95 Works fine here on Win7/64
@TooWaBoo does it work on your Windows 10?

**Comment by TooWaBoo** [comment]
I'm on version: 5.1-143-g0e011623. Works fine here

```
Version: 5.1-143-g0e011623
Branch: dev
Commit: 0e011623
Commit date: 2017-07-14
Compiler: gcc 7.1.0
Processor: undefined
System: Windows
Bit depth: 64 bits
Gtkmm: V3.22.0
Build type: release
Build flags: -mwin32 -m64 -mthreads -msse2 -std=c++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -mwindows -Wno-aggressive-loop-optimizations -DNDEBUG -O3
Link flags: -m64 -mthreads -static-libgcc -march=native -mwindows -s -O3
OpenMP support: ON
MMAP support: ON
```

**Comment by Kolli96** [comment]
I re-installed RawTherapee_dev_5.1-141-gded8c66f_WinVista_64.zip and now it works good! It also deletes selected NEF (RAW) files on hard drive.

**Comment by heckflosse** [comment]
@Vike95 @icom962 Can we close the issue?

**Comment by Kolli96** [comment]
> @Vike95 @icom962 Can we close the issue?> 

Yeah on my behalf if this is officially corrected and will include a future non-dev version.

**Comment by heckflosse** [comment]
@Vike95 Thanks for confirmation!
