### ISSUE TITLE
Crash when opening several files in editor

### ISSUE THREAD

**Issue by Desmis** [Beep6581/RawTherapee#3920]
First, excuse my bad english :)

1) when I developed "localrgb", I found often after open 3 or 4 or 5 files in editor, a crash with RT
I attribute this to my work, and I try to prevent memory leaks...But I found nothing (Which does not mean that everything is fine !)

2) after that, I tried with "locallab_dev", same crash

3) after that, I compiled a new "dev", and same crash

My config: 
```
Version: 5.1-46-g04988e52
Branch: dev
Commit: 04988e52
Commit date: 2017-06-11
Compiler: gcc 6.3.0
Processor: undefined
System: Windows
Bit depth: 64 bits
Gtkmm: V3.22.0
Build type: release
Build flags:  -std=c++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -O3 -DNDEBUG
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON
```
And also, I work with 2 screens 
with "Multiple Editors Tabs in Own Window Mode"

Perhaps, this crash is the "same" that we speak in #3908 or #3901 
:)

Jacques

**Comment by heckflosse** [comment]
@Desmis Jacques, I also think it's related to #3908 and #3901 
I'm still working on that stuff

**Comment by Desmis** [comment]
@heckflosse 

Ingo

Thank you :)

**Comment by Desmis** [comment]
A complement : there are very few files in each folder, between 15 and 40
And also, I have seen furtively, a GUI message, relative to the size of image or screen...but  it disappeared :)

jacques

I'll be away for a week !

**Comment by Desmis** [comment]
I have now another message, the system is stopped ang I can read
* Rawtherapee.exe:7924 - Gtk-warning ** : drawing failure for widdget 'gtkmm__GtkNotebook' out of memory,
and gtkmm__GtkHPaned : out of memory
and  gtkmm__GtkWindow : out of memory

or the same and : _create_dc_and_bitmap : descripteur non valide

**Comment by heckflosse** [comment]
@Desmis Jacques, that looks similar to the bugs I'm currently searching

**Comment by heckflosse** [comment]
@Desmis Jacques, can we close?

**Comment by Desmis** [comment]
Yes, it is the same problem :)
