### ISSUE TITLE
 5.1-56-ga6cf24b Crashes when pasting nothing.

### ISSUE THREAD

**Issue by waxhead** [Beep6581/RawTherapee#3922]
I noticed RT crashing a while back, like last week, but couldn't work out what triggered the crash, but I knew it was around copying and pasting edits from one image to another.  Subsequent attempts to replicate the crash failed.

Tonight I did it again, but figured the issue was partly due to me missing the C in the CRTL-C operation and then hitting CRTL-V to paste nothing.

From the Browser windows open an image to the Editor window, click on it in the film strip hit CRTL-V, without CRTL-C.  This should work.  An alternative approach is to click on an image that has nothing down to it and CRTL-C CRTL-V that on your working image.

I've compiled a debug version of the latest from dev tonight and captured the debug log, attached.  Info from about:

Version: 5.1-56-ga6cf24b
Branch: dev
Commit: a6cf24b
Commit date: 2017-06-12
Compiler: cc 5.4.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.18.0
Build type: debug
Build flags:  -std=c++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -g
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON

[rt-crash-crtl-v-no-crtl-c.txt](https://github.com/Beep6581/RawTherapee/files/1071517/rt-crash-crtl-v-no-crtl-c.txt)

**Comment by heckflosse** [comment]
@waxhead Thanks for the report. I tried to reproduce it on Win7/64 and on Linux with exactly the same rt version you used. Could not reproduce it :( There must be something missing.

**Comment by waxhead** [comment]
@heckflosse I was just about to go to bed.  

OK, so I opened up the non debug version of RT and I had to do it a couple of times to get it to actually crash.

I repeatedly did CRTL-V nothing, but then I copy and pasted from an image that has no changes against it, and it crashed.

I loaded up RT again, and this time I stayed in the file browser and did a CRTL-C and CRTL-V from one image to another, did a second CRTL-V and it crashed.

Sometimes I get a core dumped other times I get a lot of output on the console.

This is on linux too.

**Comment by heckflosse** [comment]
@waxhead 
Ok, I will try harder

**Comment by waxhead** [comment]
I'm attaching the console output from the dev build, not the debug build.

[console-output.txt](https://github.com/Beep6581/RawTherapee/files/1071596/console-output.txt)

**Comment by waxhead** [comment]
OK I can do this more reliably now.

Copy CRTL-C from an image.  CRTL-V to another image, CRTL-V again, Crash.

**Comment by heckflosse** [comment]
Bug confirmed

**Comment by waxhead** [comment]
From a usability point of view I was editing a couple of images and I copies the settings from my first image, pasted to a second one, didn't like the result and undid it.  Opened a different image and just wanted to apply the setting again, second CRTL-V crashed RT.  So it might appear that it's any additional CRTL-V after a the first one, even on different images.

This is what was in the console:

pete@kanga~/rt $ ./rawtherapee

(rawtherapee:18881): glibmm-ERROR **: 
unhandled exception (type std::exception) in signal handler:
what: vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)

Trace/breakpoint trap (core dumped)

Probably not that helpful...
