### ISSUE TITLE
Why can an image become highly posterized on saving?

### ISSUE THREAD

**Issue by 10110111** [Beep6581/RawTherapee#3927]
Using RT version 5.0-r1-gtk2-1-g348eb20 (as `git describe` says), I'm trying to export an image, which in RT looks like this (screenshot of RT):
![screenshot - 140617 - 23 01 12](https://user-images.githubusercontent.com/6376882/27152130-ea25937e-515d-11e7-989e-fc60531e3ea3.jpg)
But whatever output format I select, I get the following result (screenshot of resulting file opened in GIMP):
![screenshot - 140617 - 23 03 30](https://user-images.githubusercontent.com/6376882/27152182-17fe2d6a-515e-11e7-819c-74ccafff3955.png)
Similar image appears when I select anything except "None" in a combobox at the bottom of the window (e.g. _Rec2020_).
This happens with all CR2 images I have. What could be a reason for such result?

**Comment by heckflosse** [comment]
Can you try a newer version of rt (e.g. 5.1)?

**Comment by 10110111** [comment]
I'm not sure. My `gtk2` branch is "Already up-to-date." says `git pull`. Does 5.1 require GTK3?

**Comment by heckflosse** [comment]
Yes, 5.1 requires gtk3. What os are you using?

**Comment by 10110111** [comment]
BLFS. I guess I'll have to build GTK3.

**Comment by 10110111** [comment]
OK, just had to update LCMS from 2.3 to 2.8 (as 5.1 requires at least 2.6), and it works in `gtk2` branch now without rebuild to 5.1. Thanks.
