### ISSUE TITLE
Crash on startup in dev branch after crashes caused by CRTL-V bug.

### ISSUE THREAD

**Issue by waxhead** [Beep6581/RawTherapee#3928]
Hi,

After having the crashes the other night and now fixed, the latest git pull sees RT crashing when I open the folder I was working in when the other crashes started.

I have followed the steps on what to do when RT crashes on start up detailed in Rawpedia http://rawpedia.rawtherapee.com/How_to_fix_crashes_on_startup

So this seems like I have another problem that RT isn't handling, possibly due to a corrupt PP3 file.  I've compiled a debug version of RT and this is the git log:

The latest version I have is:
pete@kanga~/repo-rt $ git log -1
commit db18b7ad71e61c096aa9d17685620011a8ce781e
Author: heckflosse <heckflosse67@gmx.de>
Date:   Wed Jun 14 22:13:49 2017 +0200

    Fix some coverity issues

Crash gdb output attached.  I'm keeping the folder as is in case you want more info or can tell me what file is casuing the problem  :)

[crash.txt](https://github.com/Beep6581/RawTherapee/files/1077149/crash.txt)

**Comment by heckflosse** [comment]
@waxhead Ctrl-v bug corrupted pp3 files. I had that here too. You have to find the corrupted one and delete it.

**Comment by waxhead** [comment]
@heckflosse Hey Ingo, is it worth trying to protect against crashing on a corrupt file and some how have RT mark the files a unreadable? One thought would be to put .unreadable at the end of the file and RT wouldn't read it again and the user would be able to later find it.

Seems a bit harsh for the whole application to crash out like that, but I understand if coding in checks at each point would be onerous.

**Comment by Floessie** [comment]
@waxhead @heckflosse Simply ignoring corrupted input would be a welcome first step. Sanitizing input from untrusted sources (even ignoring it) should be the norm. A second step would be a means to let the user know, and Peter's suggestion is appealing.

@waxhead Please provide us with your corrupted PP3, so we can learn how to ignore it. :smile: 

Best,
Flössie

**Comment by heckflosse** [comment]
@waxhead I agree rt shouldn't crash by corrupt pp3 files!
In my case the crash was caused by a pp3 having this empty keys:
```
[HSV Equalizer]
HCurve=
SCurve=
VCurve=
```
I will fix that case now.

**Comment by heckflosse** [comment]
@waxhead @Floessie #3929

**Comment by waxhead** [comment]
@Floessie Oh No, I think I deleted them all!  I did have them moved out the way, but clearly I'm a little too tired and not thinking straight.

I have some other pp3 files that might be broken as well, will have to test them one by one..

**Comment by waxhead** [comment]
All good, I have 4 files that crash RT.  However they may all have a similar issue as I only copy and pasted nothing to trigger the bug for these ones I think!

I can provide a zip file with images included but it's 57 meg, too big for uploading here.



[bad-pp3.zip](https://github.com/Beep6581/RawTherapee/files/1077426/bad-pp3.zip)

**Comment by heckflosse** [comment]
Hmm, none of the 4 files crashes RT here.

**Comment by Beep6581** [comment]
@waxhead can you reproduce the crashes if you delete the cache and run the latest dev build? If so, please describe how, step by step starting with downloading your zip.
