### ISSUE TITLE
Crash when pp3 file contains empty key for a curve

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#3929]
When a pp3 file contains an empty key for a curve, RT crashes.
Example:
```
[HSV Equalizer]
HCurve=
SCurve=
VCurve=
```

**Comment by waxhead** [comment]
Some PP3's from my side.

[bad-pp3.zip](https://github.com/Beep6581/RawTherapee/files/1077427/bad-pp3.zip)
