### ISSUE TITLE
Installer: Add "Browser with RawTherapee" option to context menu

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3933]
From https://discuss.pixls.us/t/windows-context-menu-open-directory-with-rawtherapee/4442
Untested. A Windows user should take over.

```diff
diff --git a/tools/win/InnoSetup/WindowsInnoSetup.iss.in b/tools/win/InnoSetup/WindowsInnoSetup.iss.in
index 55305d5f..4862e808 100644
--- a/tools/win/InnoSetup/WindowsInnoSetup.iss.in
+++ b/tools/win/InnoSetup/WindowsInnoSetup.iss.in
@@ -89,6 +89,7 @@ Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{
 ;Name: "desktopicon\common"; Description: "For all users"; GroupDescription: "Additional icons:"; Flags: exclusive
 ;Name: "desktopicon\user"; Description: "For the current user only"; GroupDescription: "Additional icons:"; Flags: exclusive unchecked
 Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked; OnlyBelowVersion: 0,6.1
+Name: regBrowseFolder; Description: "Add ""Browse with RawTherapee"" option to context menu when right-clicking on a folder."; GroupDescription: File extensions:
 
 [Files]
 Source: "{#MyBuildBasePath}\rawtherapee*.exe"; DestDir: "{app}"; Flags: ignoreversion
@@ -125,3 +126,6 @@ Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\{#MyAppName} {#MyA
 [Run]
 Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
 
+[Registry]
+Root: HKCU; Subkey: "SOFTWARE\Classes\Directory\shell\Browse with RawTherapee"; ValueType: string; ValueData: "Browse with RawTherapee"; Flags: uninsdeletekey; Tasks: regBrowseFolder
+Root: HKCU; Subkey: "SOFTWARE\Classes\Directory\shell\Browse with RawTherapee\command"; ValueType: string; ValueData: "{app}\{#MyAppExeName} -w ""%1"""; Flags: uninsdeletekey; Tasks: regBrowseFolder
```

Things to test:
- Whether the option is selectable by the user during installation, should be selected by default,
- Whether the feature works after installation if RT is installed to a folder with spaces in its name,
- Whether it works when right-clicking folders with spaces in their names.

**Comment by gaaned92** [comment]
@Beep6581 feature ok
1- ok
2- ok
3-ok
Thanks to you and James

**Comment by heckflosse** [comment]
@gaaned92 Shall I include that into my next commit?

**Comment by gaaned92** [comment]
@heckflosse I think you can but  it would be safer if somebody else build and test on windows

**Comment by heckflosse** [comment]
@gaaned92 Ok! I compile on windows but never make builds. So you're right that it will be better if another windows builder will test!

**Comment by gaaned92** [comment]
@heckflosse  I believed it was commited. It will be commited in 5.4. Nevertheless, I included thatin my 5.3 build.

**Comment by Beep6581** [comment]
Status?

**Comment by agriggio** [comment]
Shouldn't there be also an "Open with RawTherapee" entry available for picture files?
Also, wouldn't be better to use the "-R" flag when invoking RT?

**Comment by Beep6581** [comment]
Now that `-R` exists, definitely.

P.S. This has still not been committed, and I will not commit it as I don't use Windows and can't test. Would be nice if a Windows dev took over.

**Comment by heckflosse** [comment]
👍 for using -R

**Comment by Beep6581** [comment]
Any Windows user willing to test (+ finish?) + merge this, or are we not including it for 5.4?
It would be a pity if it wasn't included since the patch is already there, it just needs to be tested again.
Ping @gaaned92 @sguyader @Hombre57

**Comment by agriggio** [comment]
I'll try on my vm

**Comment by gaaned92** [comment]
- The patch  is included in all my W64 builds since 5.3 and I use it from time to time. It works ok .
So  I agree to commit it.

- Shouldn't there be also an "Open with RawTherapee" entry available for picture files?
For me it's less interesting because when I use Rawtherapee in GUI mode, I always want to process a set of images in a directory.

**Comment by agriggio** [comment]
> Shouldn't there be also an "Open with RawTherapee" entry available for picture files?

Yes, definitely.

> For me it's less interesting because when I use Rawtherapee in GUI mode, I always want to process a et of images in a directory.

I use it quite often (from geeqie on linux) together with the "remote" mode of RT, which will open the selected image in the editor of an already-running instance of RT. I think this is what "open with RawTherapee" should do on windows too.
@gaaned92 would you be able to produce a patch for this as well?

**Comment by gaaned92** [comment]
Two ways to add "open with RawTherapee":
- only to files with parsed extension; feasible but complex. Don't know exactly yet how to do.

- brutal force to all files

```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\*\shell\Open With Rawtherapee]

[HKEY_CLASSES_ROOT\*\shell\Open With Rawtherapee\command]
@="\"D:\\RAWTHERAPEE\\5.3-549-gc04150be3\\rawtherapee.exe\" -R \"%1\""

```

Now it remains to transform that in Innosetup command

**Comment by Beep6581** [comment]
If needed, you can find a list of supported mime-types here:
https://github.com/Beep6581/RawTherapee/blob/34bd19f4bfb25ec52df785e55feabca9dd817124/rtdata/icons/mime-types

**Comment by gaaned92** [comment]
@Beep6581 To add the menu to only the processed types is not so simple and I don't know yet how to do manually.
 The hereunder diff permits to add the "open with rawtherapee" context menu to all files.
If a file is not of a type processed by RT, only the editor is open.


```diff
diff --git a/tools/win/InnoSetup/WindowsInnoSetup.iss.in b/tools/win/InnoSetup/WindowsInnoSetup.iss.in
index 55305d5f0..c1560fa81 100644
--- a/tools/win/InnoSetup/WindowsInnoSetup.iss.in
+++ b/tools/win/InnoSetup/WindowsInnoSetup.iss.in
@@ -89,7 +89,8 @@ Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{
 ;Name: "desktopicon\common"; Description: "For all users"; GroupDescription: "Additional icons:"; Flags: exclusive
 ;Name: "desktopicon\user"; Description: "For the current user only"; GroupDescription: "Additional icons:"; Flags: exclusive unchecked
 Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked; OnlyBelowVersion: 0,6.1
-
+Name: regBrowseFolder; Description: "Add ""Browse with RawTherapee"" option to context menu when right-clicking on a folder."; GroupDescription: File extensions:
+Name: openFile; Description: "Add ""Open with RawTherapee"" option to context menu when right-clicking on a file."; GroupDescription: File extensions:
 [Files]
 Source: "{#MyBuildBasePath}\rawtherapee*.exe"; DestDir: "{app}"; Flags: ignoreversion
 Source: "{#MyBuildBasePath}\camconst.json"; DestDir: "{app}"; Flags: ignoreversion
@@ -125,3 +126,8 @@ Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\{#MyAppName} {#MyA
 [Run]
 Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
 
+[Registry]
+Root: HKCU; Subkey: "SOFTWARE\Classes\Directory\shell\Browse with RawTherapee"; ValueType: string; ValueData: "Browse with RawTherapee"; Flags: uninsdeletekey; Tasks: regBrowseFolder
+Root: HKCU; Subkey: "SOFTWARE\Classes\Directory\shell\Browse with RawTherapee\command"; ValueType: string; ValueData: "{app}\{#MyAppExeName} -w ""%1"""; Flags: uninsdeletekey; Tasks: regBrowseFolder
+Root: HKCR; Subkey: "*\shell\Open with RawTherapee"; ValueType: string; ValueData: "Open with RawTherapee"; Flags: uninsdeletekey; Tasks: openFile
+Root: HKCR; Subkey: "*\shell\Open with RawTherapee\command"; ValueType: string; ValueData: "{app}\{#MyAppExeName} -R ""%1"""; Flags: uninsdeletekey; Tasks: openFile

```

**Comment by Beep6581** [comment]
@gaaned92 why `*\`? I don't see mention of that anywhere in the docs.

**Comment by Beep6581** [comment]
Made consistency changes and created PR https://github.com/Beep6581/RawTherapee/pull/4346
Please test branch `win-contextmenu`

**Comment by gaaned92** [comment]
Please test

> RawTherapee_win-contextmenu_5.3-550-gdb456825a_WinVista_64.zip

uploaded at
https://keybase.pub/gaaned92/RTW64NightlyBuilds/
