### ISSUE TITLE
Easy to print quick checklist for "Shooting the color target"

### ISSUE THREAD

**Issue by rogerxxxx** [Beep6581/RawTherapee#3934]
Attached below are the beginnings of a quick checklist users can use as a quick guide when in the field performing "Shooting the color target" (As designated at: http://rawpedia.rawtherapee.com/How_to_create_DCP_color_profiles#Shooting_the_color_target)

Some of the problems I had when using the "Shooting the color target" guide, I didn't have something in the field to easily read or follow through while being blinded by mid-day sun and while trying to stabilize the target during intermittent winds.  I also mistook the whiter patch for the mid-gray exposure patch, but thankfully bracketing saved my butt here, allowing time to realize the mistake later.  (A very common mistake apparently, as indicated with the forums!)  Although (since I'm a guy), I thought I was able to memorize most of the many details from the "Shooting the color target" guide page, I did finally forget to use the camera's most detailed aperture.

The below checklist is in text and easily printed, and is a step by step guide for following in the field.  I would probably also add numbers for each step, but figure other eyes-on can probably provide a better finished checklist.  (Albeit, most people just publish what I submit and stick my name on it, so I'm held explicitly liable or blamed.)

So although i found "Shooting_the_color_target" to be a good guide, it was written with the likely intent to provide the general information required for attaining the good test images or as a follow-up afterwards, but not easily read or utilized while in the field.  (eg. Lots of details or confusing terminology not needed while in the field!)

--- Begin Snip ---
Best to avoid camera preset scene modes, and set the camera for manual or aperture priority mode.  Acquire images/exposures from areas not having any structures, shadows or walls; or areas/walls containing bright colors possibly promoting color casts upon the color calibration target.

Only compose the image (or exposure) for the 24 color patches, or the right side of the X-Rite ColorChecker Passport.

Position the X-Rite ColorChecker card with brown square patch in the upper left position.

Avoid exposing with reflections of the light source, by positioning camera in between the light source and the color card, as the picture diagram states, giving priority to ensuring the color card is perpendicular to the lens.

Make sure the color card is perpendicular to the camera sensor.

Make sure only one third of the entire image captured contains the color card.

Camera settings using Manual Mode will likely be:
Sunlight: f1/2000s(?), f/8.0, ISO 100
Tungsten/Incandescent: 1/4-1/5s, f/8.0, ISO 800

Use your camera lens's best aperture, likely 2.5-3.0 stops over the lowest aperture.  (eg. For cameras with f/2.8 as the lowest possible aperture, use f/5.6-f/8; lowest f/3.5, use f/8-f/11; ...)  Also use the base ISO, likely ISO 100.

Using spot metering, zoom into the 18% gray patch (or the third gray patch from the right, right of the black patch) on the bottom row within the 24 color patch card and set or lock the auto-exposure to this 18% gray patch.  This patch is also called middle gray.  (FYI: The second color patch from the left is a white balance patch, matching the larger white balance card on the rear of the 24 color patch card.)  A more simplified method, use bracketing to take three exposures; -1, 0, +1 exposures, and choose the image containing center-most histogram values.

Recompose or refocus onto the 24 color patches while exposure is set or bracketing is activated, ensuring the color card remains perpendicular and horizontal/vertical according to your camera's frames guides.

Take a focused image/exposure on the center of the 24 color patch card.

Check the histogram of the image/exposure taken using the camera's display, and check for the image being under or over exposed, rather than relying on your camera's light meter or auto-exposure.  (Need the image histogram clearly centered; and for my Nikon, this was clearly evident or displayed within the histogram when using the 24 color patch card under tungsten lighting.)

Compensate for under or over exposure.  Again, compose/recompose the image/exposure by using the auto-exposure on the 18% gray patch again, this time compensating using shutter speed for any under or over exposure or again using readjusted bracketing.  Repeat the previous steps until a centered histogram is acquired.  For incandescent/tungsten, if the exposure is too dark for an adequate shutter speed, add more commonly used 60w tungsten light bulbs.  (There are 150w and brighter tungsten bulbs, but the color temperature sways with these less commonly used bulb wattages.)

Acquire and submit one image for sunlight and one for incandescent/tungsten.

--- End of Snip ---

**Comment by Beep6581** [comment]
Updated: http://rawpedia.rawtherapee.com/How_to_create_DCP_color_profiles#Shooting_the_color_target
