### ISSUE TITLE
Joint-optimizing processing

### ISSUE THREAD

**Issue by cmrdt** [Beep6581/RawTherapee#3938]
instead of separate serial pipeline  (which might accumulate errors)

e.g similar to below  &papers it mentions
[Deep Joint Demosaicking and Denoising](https://groups.csail.mit.edu/graphics/demosaicnet/data/demosaic.pdf)     [webpage](https://groups.csail.mit.edu/graphics/demosaicnet/)   [slides](https://groups.csail.mit.edu/graphics/demosaicnet/data/demosaicnet_slides.pdf)   [cod](https://github.com/mgharbi/demosaicnet)[e](https://www.dropbox.com/s/lk2oh935g7v4gof/flexisp_demosaicking_demo.zip)

also for some processing is it done in wrong color space 
- sRGB (not recommended, common, gamma)
- linear Rec709 RGB (better)
- RAW camera data (has black-level)
- linearized,camera-RGB-Primaries (physically based, maybe for sensor noise-modeling, white-balance; maybe even earlier for hot/dead-pixels filtering)
- linear tri-stimulus LMS color spaces
- CIE​CAM02[-](http://www.springer.com/cda/content/document/cda_downloaddocument/9781441961891-c1.pdf?SGWID=0-0-45-1337202-p173968189)(UCS) CIE​CAM[1](http://files.cie.co.at/900_CIE%20Division%208%202016%20Minutes.pdf)[6](http://www.ingentaconnect.com/content/ist/ei/2016/00002016/00000020/art00016)[-(UCS)](http://onlinelibrary.wiley.com/doi/10.1002/col.22131/abstract;jsessionid=038B1550B054173DB283225A7208DDF7.f02t03) LAB &ot[h](http://reality.cs.ucl.ac.uk/projects/xlrcam/kim09xlrcam.html)[ers](https://www.osapublishing.org/viewmedia.cfm?uri=oe-25-13-15131) (perceptual post-process; gamut caveats- [not](http://sccg.sk/~sikudova/publications/cga_gamut.pdf) there yet)

**Comment by heckflosse** [comment]
@cmrdt Can you please rephrase your comment in clear sentences?

**Comment by heckflosse** [comment]
@cmrdt the paper is really interesting :+1:
