### ISSUE TITLE
Raw Therapee only opens JPG files

### ISSUE THREAD

**Issue by rcstaats** [Beep6581/RawTherapee#3939]
I'm running the newest Windows version of Therapee on a Win 7 system.

When I open the file browser, it only shows JPG files even though there are other image types, e.g., raw, png, tif, in the same directory.  

The file type associations are set up correctly in the preferences, and the meta option is not checked.  However ... there are two listings in the picture type box, jpg and JPG.  While the box is not checked, I'm thinking that might have something to do with it.  No amount of effort has been able to clear those two entries out of the selection criteria box.

**Comment by heckflosse** [comment]
@rcstaats Please show screenshots

**Comment by heckflosse** [comment]
@rcstaats Especially a screenshot of the 'picture type box', whatever that is...
