### ISSUE TITLE
RT crashes when switching folders

### ISSUE THREAD

**Issue by ghost** [Beep6581/RawTherapee#3940]
I get crashes when I switch folders in RT; I was merely randomly switching between folders and I didn't have to do it for a long time. :-)

Backtrace from debug build is here:
[backtrace](https://pastebin.com/cqiY79cw)

Version: 5.1-83-g41d3179f
Branch: dev
Commit: 41d3179f
Commit date: 2017-06-21
Compiler: cc 6.3.0
Processor: Intel(R)\ Core(TM)\ i7-2600K\ CPU\ @\ 3.40GHz
System: Linux
Bit depth: 64 bits
Gtkmm: V3.22.0
Build type: debug
Build flags:  -std=c++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -g
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON

Thanks in advance!

**Comment by heckflosse** [comment]
@mks9900 Can you try to build from [this branch](https://github.com/Beep6581/RawTherapee/tree/valgrind_fixes)? This should fix it.

**Comment by ghost** [comment]
Ingo; perfect! Much more stable now after your fixes!
Thanks!

**Comment by heckflosse** [comment]
@mks9900 Thanks for reporting and testing :+1: 
Fixed with e4c75c4
