### ISSUE TITLE
Monitor and printer ICC color profiles missing

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3941]
Tested after deleting the options file to enforce defaults.

Preferences > Color Management, the Monitor and Printer comboboxes both show "None". "Directory containing color profiles" is correctly set to `ICCDirectory=/usr/share/color/icc`

Editor > Color tab > Color Management, Output Profile shows only "No ICM: sRGB Output", no other options. `~/rt/iccprofiles/output/` contains the usual RT_* ICC files.

"Critical" because RT cannot be used well when color management is not working.

**Comment by Beep6581** [comment]
Fix confirmed, thanks Ingo!

**Comment by heckflosse** [comment]
I had to fix it because I broke it ;-)
