### ISSUE TITLE
deconvolution: spatially-varying , other psf's

### ISSUE THREAD

**Issue by cmrdt** [Beep6581/RawTherapee#3942]
esp since for
- certain camera/lenses
- near the center vs edges, 
- also focus-state
- scene dependency

see 
- [Computational Imaging Through Simple Lenses](http://www.cs.ubc.ca/labs/imager/tr/2013/SimpleLensImaging/) [or](https://github.com/Y-Vladimir/SmartDeblur) 
 - [Image Enhancement using Calibrated Lens Simulations](http://people.csail.mit.edu/yichangshih/lensEnhancement/lensEccv.pdf) [web](http://people.csail.mit.edu:80/yichangshih/lensEnhancement/)
 - [Total Variation Approach - Customizing Imagery to Improve Visual Acuity](https://www.cs.purdue.edu/homes/igarciad/p/2015_TOG/2015_TOG_VisualAcuity.pdf) [web](https://www.cs.purdue.edu/homes/igarciad/p/2015_TOG/2015_TOG.html)

**Comment by Thanatomanic** [comment]
While the research is surely interesting, without a proper request or need for implementation in RT there is no need to keep this issue open.
