### ISSUE TITLE
Sync gimp-plugin with GIMP repo and add a version test when 5.2 is out.

### ISSUE THREAD

**Issue by Jehan** [Beep6581/RawTherapee#3943]
Hi!

We pushed your plugin in GIMP. Thanks for this. :-)
What would be nice now is to:

1/ Contribute any future changes (after having synced to our code because we already did a few fix: https://git.gnome.org/browse/gimp/log/plug-ins/file-rawtherapee) directly to us because we don't want to ship an outdated plugin.

2/ When you release the version 5.2, contribute a patch to test for RawTherapee version.

Cf. https://bugzilla.gnome.org/show_bug.cgi?id=784228
Thanks again! :-)

**Comment by agriggio** [comment]
Noted, thanks!

**Comment by agriggio** [comment]
Hi @Jehan, I just updated the GIMP plugin code in the RT repo (`tools/gimp-plugin`) to check for version >= 5.2.
Will you take care of porting to GIMP or should I submit a patch?

Thanks!

**Comment by Jehan** [comment]
It's ok, I just pushed your commit with your authorship: https://git.gnome.org/browse/gimp/commit/?id=38be044bbaa4e6fb9a3601eae59ee311ecf36e4c

It would be awesome if you could add the MacOS support. As Mitch was saying on the bug report on our side, even by just copy-pasting the Darktable plugin code, and just testing that it doesn't break the Linux code. At least the code will be there and people on MacOS can test (then if it doesn't work or break the MacOS build, we'll get bug reports. That's still going forward).

**Comment by agriggio** [comment]
ok, if copy/paste without test on the Mac is fine, I'll try to do that

**Comment by Jehan** [comment]
Maybe I can just give it a try if you want. Then we can just close the bug reports. :-)

**Comment by agriggio** [comment]
Sorry, I'm traveling these days and I didn't have time to work on this. If you want to go then by all means please do it :smile: 
BTW, I just noticed that my latest commit is obviously wrong. The test:

```
&& rtmajor >= 5 && rtminor >= 2
```

should actually be

```
&& ((rtmajor == 5 && rtminor >= 2) || rtmajor >= 6)
```

Sorry about that -- I did not think long enough :stuck_out_tongue:

**Comment by Jehan** [comment]
All done (your version check fix as well). You can check our changes. You'll notice also some changes because we factorized a bit so that both file-darktable and file-rawtherapee plug-ins now share file-formats.h.

I guess we can just close the bug report on your side as well (we'll just wait for people complaining if it doesn't work properly since I don't have a MacOS as well! ;p).

**Comment by agriggio** [comment]
> You'll notice also some changes because we factorized a bit so that both file-darktable and file-rawtherapee plug-ins now share file-formats.h.

I didn't look at the code yet, but if you want to share `file-formats.h` between the two plugins you should be aware that there are subtle differences between the two. Specifically, the one of Darktable IIRC registers some TIFF files to be handled by the plug-in. This is fine for DT, but was causing some endless loops for the RT one in case of errors. I guess that is because the DT plug-in was producing OpenEXR files to be imported by GIMP, whereas RT is generating TIFFs. As a result, in some cases (on error, but I don't remember the details, sorry) it happened that GIMP was calling the RT plugin, which was generating a TIFF, which when sent back to GIMP was causing it to call the RT plugin again, in an endless loop...

I am sorry that the above description is a bit fuzzy, but I just thought I should raise the flag. That's why I used a custom `file-formats.h` though.

**Comment by Jehan** [comment]
Hi,

Yeah we already noticed that darktable's file-formats.h was listing tiff and we removed it. GIMP handles tiff just fine.
We didn't know about the issue you raise though, but that's a good additional reason. And don't worry, the explanation was clear. ;)

**Comment by Benitoite** [comment]
Here is the error I'm getting when trying to build the plugin on macOS:

```
gimptool-2.0 --build file-rawtherapee.c
/opt/local/libexec/llvm-3.9/bin/clang -arch x86_64 -O3 -mmacosx-version-min=10.9 -I/opt/local/include -D_REENTRANT -I/opt/local/include/gimp-2.0 -I/opt/local/include/gegl-0.3 -I/opt/local/include/json-glib-1.0 -I/opt/local/include/gio-unix-2.0/ -I/opt/local/include/babl-0.1 -I/opt/local/include/gtk-2.0 -I/opt/local/lib/gtk-2.0/include -I/opt/local/include/pango-1.0 -I/opt/local/include/harfbuzz -I/opt/local/include -I/opt/local/include/pango-1.0 -I/opt/local/include/cairo -I/opt/local/include/atk-1.0 -I/opt/local/include/cairo -I/opt/local/include/pixman-1 -I/opt/local/include -I/opt/local/include/freetype2 -I/opt/local/include -I/opt/local/include/freetype2 -I/opt/local/include/libpng16 -I/opt/local/include/gdk-pixbuf-2.0 -I/opt/local/include/libpng16 -I/opt/local/include/glib-2.0 -I/opt/local/lib/glib-2.0/include -I/opt/local/include -o 'file-rawtherapee' file-rawtherapee.c -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib -L/opt/local/lib -lgimpui-2.0 -lgimpwidgets-2.0 -lgimpmodule-2.0 -lgimp-2.0 -lgimpmath-2.0 -lgimpconfig-2.0 -lgimpcolor-2.0 -lgimpbase-2.0 -lgegl-0.3 -lgegl-npd-0.3 -lm -lgmodule-2.0 -ljson-glib-1.0 -lgio-2.0 -lbabl-0.1 -lgtk-quartz-2.0 -lgdk-quartz-2.0 -framework Cocoa -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lintl -Wl,-framework -Wl,CoreFoundation 
file-rawtherapee.c:23:10: fatal error: 'config.h' file not found
#include "config.h"
```
Could it be looking for` ~/repo-rt/build/rtgui/config.h` or perhaps `~/gimp/config.h`

**Comment by Beep6581** [comment]
Same problem here.

**Comment by Jehan** [comment]
This is the config.h which is generated by the `configure` script of GIMP (found at root folder of the build directory). This plugin will be included in GIMP itself, so there is no need to build it separately with gimptool.

This being said, if you really want to build it like this, I don't think we actually use any of the values from config.h. This is just good practice to always include it in every file. So you can probably just comment out/delete the line and it should compile.

**Comment by agriggio** [comment]
as @jehan said, those errors are expected. if you want to self-comp Ile, just comment out the include and also the header file for i18n (I don't remember the name right now). you will also need to define the translation macros (`M_` IIRC) to be no-ops. I'll try to post a patch here tomorrow

**Comment by Beep6581** [comment]
@Jehan @agriggio what will my grandmother need to do in Linux and Windows to open raw files in RawTherapee 5.2 from GIMP 2.9.6? I ask so that I can update http://rawpedia.rawtherapee.com/GIMP_Plugin

**Comment by agriggio** [comment]
I think (s)he would need to:

1. have RT  >= 5.2 in `$PATH`
2. select the RT importer from the raw import section of the preferences in GIMP.

that should be enough

**Comment by Jehan** [comment]
Hopefully nothing. If the right version of RawTherapee is installed and if the detection code works well (it does on Linux, for MacOS and Windows, that's untested, I think; we welcome patch anyway if you have any bug on any platform), GIMP will simply open the file in RawTherapee without you having to do anything. Then exiting RT will import the result into GIMP.
Same for darktable.

If neither RawTherapee nor darktable are installed, one will get an error message on opening a raw file. This message will list both programs and their minimum version as well as the URL to get them.

If both RawTherapee and darktable are installed, not sure which one gets priority (probably random from which one gets registered first, or last, or whatever), but one can configure the preferred raw software in GIMP preferences.

**Comment by Beep6581** [comment]
Great, I'll update the docs.

**Comment by Beep6581** [comment]
@agriggio ok to close?

**Comment by agriggio** [comment]
yes
