### ISSUE TITLE
Hide "Send to Queue" button and deactivate shortcut when in no-file-browser mode

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3945]
Hide "Send to Queue" button and deactivate shortcut when in no-file-browser mode, as clicking it crashes RT.

**Comment by agriggio** [comment]
looks like a regression, as I remember this was not happening...

**Comment by heckflosse** [comment]
@agriggio Alberto, will you fix it or shall I do?

**Comment by agriggio** [comment]
I think I broke it, so I'll fix it!
