### ISSUE TITLE
rawtherapee-cli thinks /dev/null is a file

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3948]
```
~/rt/rawtherapee-cli -o /dev/null -c ~/photos/test_images/amsterdam.pef
RawTherapee, version 5.1-118-gaae77945, command line
Processing: /home/morgan/photos/test_images/amsterdam.pef
Error saving to: /dev/null.jpg
```

If I use `/dev/null/` I get `Error saving to: /dev/null/.jpg`

Works fine for `/tmp` and `~/photos`

**Comment by Hombre57** [comment]
Could you test this patch ?

```patch
diff --git a/rtgui/main-cli.cc b/rtgui/main-cli.cc
index d262d5f..11d83f3 100644
--- a/rtgui/main-cli.cc
+++ b/rtgui/main-cli.cc
@@ -294,6 +294,7 @@
     Glib::ustring outputPath = "";
     std::vector<rtengine::procparams::PartialProfile*> processingParams;
     bool outputDirectory = false;
+    bool noExtension = false;
     bool overwriteFiles = false;
     bool sideProcParams = false;
     bool copyParamsFile = false;
@@ -324,7 +325,11 @@
 #if ECLIPSE_ARGS
                     outputPath = outputPath.substr(1, outputPath.length()-2);
 #endif
-                    if( Glib::file_test (outputPath, Glib::FILE_TEST_IS_DIR)) {
+                    if(outputPath.substr(0,9) == "/dev/null") {
+                        outputPath.assign("/dev/null");  // removing any useless chars or filename
+                        outputDirectory = false;
+                        noExtension = true;
+                    } else if(Glib::file_test (outputPath, Glib::FILE_TEST_IS_DIR)) {
                         outputDirectory = true;
                     }
                 }
@@ -696,9 +701,13 @@
             Glib::ustring::size_type ext = s.find_last_of('.');
             outputFile = Glib::build_filename(outputPath, s.substr(0, ext) + "." + outputType);
         } else {
-            Glib::ustring s = outputPath;
-            Glib::ustring::size_type ext = s.find_last_of('.');
-            outputFile =  s.substr(0, ext) + "." + outputType;
+            if (noExtension) {
+                outputFile = outputPath;
+            } else {
+                Glib::ustring s = outputPath;
+                Glib::ustring::size_type ext = s.find_last_of('.');
+                outputFile = s.substr(0, ext) + "." + outputType;
+            }
         }
 
         if( inputFile == outputFile) {
```

**Comment by Beep6581** [comment]
```
$ ./build/release/rawtherapee-cli -o /dev/null -c ~/photos/test_images/amsterdam.pef
RawTherapee, version 5.1-139-g14f5d523, command line
Processing: /home/morgan/photos/test_images/amsterdam.pef
/dev/null already exists: use -Y option to overwrite. This image has been skipped.
$ ./build/release/rawtherapee-cli -o /dev/null -Y -c ~/photos/test_images/amsterdam.pef
RawTherapee, version 5.1-139-g14f5d523, command line
Processing: /home/morgan/photos/test_images/amsterdam.pef
$ echo $?
0
```
Success! Good night :)

**Comment by Floessie** [comment]
@Hombre57 Wouldn't it be cleaner to make use of [`Gio::FileInfo::get_file_type()`](https://developer.gnome.org/glibmm/stable/classGio_1_1FileInfo.html#abf62545b515bef26ead386be87750edb). Testing for `FILE_TYPE_SPECIAL` would also enable `/dev/stdout` or named pipes. This could also set `-Y` implicitly.

Just my 2¢,
Flössie

**Comment by Hombre57** [comment]
@Floessie Because I'm not used to _exceptions_. That will be the case if `outputPath` does not exist when using [Gio::File::query_info](https://developer.gnome.org/glibmm/stable/classGio_1_1File.html#adb25ffdbe571d33e89c9503fe9a20dcd), which is what will happen most of the case. Also how will you handle symlinks (would the target exist or not) ? In short, it's too high level for me. I'll let you and @Beep6581 decide what's the best thing to do : commit or make that cleaner.

**Comment by Floessie** [comment]
@Hombre57 
> That will be the case if outputPath does not exist when using Gio::File::query_info, which is what will happen most of the case. Also how will you handle symlinks (would the target exist or not) ?

I see, there are some cornercases. Maybe it's not worth the effort then.

> I'll let you and @Beep6581 decide what's the best thing to do : commit or make that cleaner.

"or" isn't "xor". 😉 @Beep6581 should take your patch as is, and maybe someone sometime comes up with a better solution.

Best,
Flössie

**Comment by Hombre57** [comment]
Patch committed in rev ded8c66.

**Comment by Hombre57** [comment]
I probably forget a _name dropping_  ... @Beep6581 :)

**Comment by Beep6581** [comment]
Yes, thank you! Confirmed it works well in dev now.
