### ISSUE TITLE
Getting a lot of compiler warnings

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#3949]
After updating to the latest MSYS I got a lot of compiler warnings.

[Compiler Warnings.txt](https://github.com/Beep6581/RawTherapee/files/1118383/Compiler.Warnings.txt)

```
Version: 5.1-119-g3fb5c7d3
Branch: dev
Commit: 3fb5c7d3
Commit date: 2017-07-03
Compiler: gcc 7.1.0
Processor: undefined
System: Windows
Bit depth: 64 bits
Gtkmm: V3.22.0
Build type: release
Build flags: -mwin32 -m64 -mthreads -msse2 -std=c++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -mwindows -Wno-aggressive-loop-optimizations -DNDEBUG -O3
Link flags: -m64 -mthreads -static-libgcc -march=native -mwindows -s -O3
OpenMP support: ON
MMAP support: ON
```

**Comment by heckflosse** [comment]
@WooWaBoo

At the moment to get rid of this annoying warnings you can add this line

`#pragma GCC diagnostic ignored "-Wdeprecated"`

at top of

`C:/msys64/mingw64/include/glibmm-2.4/glibmm/variant.h`

**Comment by TooWaBoo** [comment]
Thanks, I don't care about the warnings. It compiles successfully. It's only an info for you.

**Comment by heckflosse** [comment]
@TooWaBoo I don't think it's only an info for devs. This massive amount of warnings 'hides' other warnings which may be important.
MSYS should fix that...

**Comment by TooWaBoo** [comment]
I'll give feedback if they have fixed it.

**Comment by Floessie** [comment]
JFYI: This has been [fixed](https://github.com/GNOME/glibmm/commit/a4de5823f43b415359a05710b77f3de9e3d6448d) in glibmm in April.

**Comment by TooWaBoo** [comment]
New update of MSYS available but the bug still exists.

**Comment by Beep6581** [comment]
Report it to MSYS.

**Comment by mingwandroid** [comment]
Why would msys2 be interested in fixing your compiler warnings? It seems a deprecated feature is being used by either your code or your dependencies' code or your C++ std flag is wrong.

In what way should msys2 fix any of that?

**Comment by heckflosse** [comment]
@mingwandroid
If you read the post 3 above your post you will see that is not a bug in our code and is already fixed in glibmm. But it seems in the glibmm used by msys it is not yet fixed.

**Comment by TooWaBoo** [comment]
New update of msys2 has fixed this issue.
