### ISSUE TITLE
Gimp plugin file_rawtherapee.exe missing entry point

### ISSUE THREAD

**Issue by gaaned92** [Beep6581/RawTherapee#3950]
@agriggio 
In order to build the plugin on windows10, I built the last unstable gimp2.9.5 see [https://wiki.gimp.org/wiki/Hacking:Building/Windows](https://wiki.gimp.org/wiki/Hacking:Building/Windows) to get the missing files.
I put the plugin in my user  gimp2.9.5-cce  plugin dir. (built by Partha)
When I launch gimp I get the  error message:

>    ![capture-3](https://user-images.githubusercontent.com/13785581/27786616-261d9e66-5fe2-11e7-99ad-8a9fb9c154e5.jpg)

**Comment by agriggio** [comment]
Hi @gaaned92,
looks like the version of gimp you are using doesn't include the `gimp_register_file_handler_raw` function. I think it got introduced relatively recently (see e.g. https://discuss.pixls.us/t/gimp-and-specifying-raw-importers).
You can try commenting out the relevant line in `file-rawtherapee.c` and see if that helps

**Comment by agriggio** [comment]
Oh BTW, the RT gimp plugin is now part of gimp itself, so it should be shipped by default in future versions. See #3943

**Comment by gaaned92** [comment]
OK I close the thread
