### ISSUE TITLE
Wrong export of jpg for PhotoShop CS6

### ISSUE THREAD

**Issue by hupchen** [Beep6581/RawTherapee#3952]
Dear all,

there is a problem with the export of jpg from RAWTherapee. If I export I file as JPG, I cannot open the jpeg in PhotoShop CS6. 

I see an error about the jpeg header.

Best regards
Blandyna

**Comment by Beep6581** [comment]
@hupchen Hi, please see http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports
