### ISSUE TITLE
How do we handle cropped raw images?

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3960]
For cameras which produce more than one size of raw image, how do we handle the `raw_crop` parameter in `camconst.json` so that both the full raw image and the cropped ones render correctly?

Ping @iliasg @heckflosse 

e.g. the Sony ILCE-7S has a cropped mode when attaching an APS-C lens which requires:
`        "raw_crop": [ 0, 0, 2792, 1872 ],`
but currently we have this and as a result these APS-C raws have a corrupt bar on the right:
`        "raw_crop": [ 0, 0, 4254, 2848 ],`

![imgur-2017_07_08-17 11 03](https://user-images.githubusercontent.com/5844619/27986540-721799f8-6400-11e7-801a-8bdbb75ec96a.png)

https://filebin.net/37o7sazg4h62k6fy/DSC03529.ARW

**Comment by iliasg** [comment]
This (multiple frame sizes per camera in camconst.json) is something I 've asked a lot of times lately ..

For the moment we can only do it in dcraw.cc defining raw crops according to the full raw size ..
and if we are lucky** we can also use the alternative way of defining raw crops  "raw_crop": [ 0, 0, -32, 0 ],
** By lucky I mean 
- to have FF and APS-C crops with the same number of "garbage columns or lines" at same side of the "full raw frame" 
- the above does not get meshed by the Dcraw.cc way of defining raw crops ..

**Comment by Beep6581** [comment]
@iliasg thank you for the reply. Was the closing intentional? i.e. Do we not want to keep this open to find a better solution which doesn't require getting lucky?

**Comment by iliasg** [comment]
Ohh I closed the issue accidentally :(

**Comment by heckflosse** [comment]
@iliasg I will push a branch this weekend which allows to define a raw crop in pp3 file as a variation of the standard raw crop (from dcraw or camconst.json). Still no gui for that. But the raw engine will use the settings from pp3 file then in case the raw crop in pp3 file is enabled.
FF and DF will also be adopted to the raw crop in pp3 in the new branch.
