### ISSUE TITLE
Multi Monitor - maximizing not correctly

### ISSUE THREAD

**Issue by Luncher91** [Beep6581/RawTherapee#3962]
Version: 5.1
Setting: MultiTab on multiple monitors if available
OS: Windows

I have a three Monitor setup (2x 1920x1080 and 1x 1920x1200). The primary display is the large one.
Maximizing the secondary window on the primary screen does not result in a maximized window. There is some space around the window. So it is centralized but not maximized.

I hope someone can fix that for the next release.

**Comment by heckflosse** [comment]
@Luncher91 Would you mind to report this in #3957 (MEOW = Multiple Editors Own Window)?
I'm currently trying to collect and fix the related issues there.

**Comment by Luncher91** [comment]
Sure!

**Comment by heckflosse** [comment]
Thank you!
