### ISSUE TITLE
Input styling looks bad

### ISSUE THREAD

**Issue by simontheflutist** [Beep6581/RawTherapee#3964]
I'm using RawTherapee 5.1 (can't find futher version info; I know that apt is updating RT on schedule) on Ubuntu 16.04 64-bit, on a Dell Precision with a Core i7.

On my system it looks like this:

![image](https://user-images.githubusercontent.com/13023178/28046465-a8df9a28-6598-11e7-9d92-3d2479e93b65.png)

The expected appearance is like this:

![image](https://user-images.githubusercontent.com/13023178/28046590-8f15c940-6599-11e7-9cbe-16cfcdb2b18a.png)

Font sizes are more balanced and consistent, and as a whole this is much more visually appealing.

Let me know if I can provide any other debug information.

**Comment by Beep6581** [comment]
http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports
We need your build details from Preferences > About > Version, your system's GTK+ version, etc.
Try deleting your options file while RT is not running: `rm -rv ~/.config/RawTherapee*`

**Comment by simontheflutist** [comment]
Build details here:

![image](https://user-images.githubusercontent.com/13023178/28104793-9eb45ddc-6691-11e7-937c-af2061f1de1a.png)

[GTK+ details](https://stackoverflow.com/a/126193/3040627):

```
ii  libgtk-3-0:amd64             3.18.9-1ubuntu3.3         amd64        GTK+ graphical user interface library
ii  libgtk-3-bin                 3.18.9-1ubuntu3.3         amd64        programs for the GTK+ graphical user interface library
ii  libgtk-3-common              3.18.9-1ubuntu3.3         all          common files for the GTK+ graphical user interface library
ii  libgtk2-appindicator-perl    0.15-1build3              amd64        Perl bindings for libappindicator
ii  libgtk2-imageview-perl       0.05-2build2              amd64        Perl bindings for the GtkImageView image viewer widget
ii  libgtk2-perl                 2:1.2498-1                amd64        Perl interface to the 2.x series of the Gimp Toolkit library
ii  libgtk2-unique-perl          0.05-2ubuntu1             amd64        module for single instance applications
ii  libgtk2.0-0:amd64            2.24.30-1ubuntu1          amd64        GTK+ graphical user interface library
ii  libgtk2.0-bin                2.24.30-1ubuntu1          amd64        programs for the GTK+ graphical user interface library
ii  libgtk2.0-cil                2.12.10-6                 amd64        CLI binding for the GTK+ toolkit 2.12
ii  libgtk2.0-common             2.24.30-1ubuntu1          all          common files for the GTK+ graphical user interface library
```

**Comment by simontheflutist** [comment]
Nothing changes after I delete config files.

**Comment by Beep6581** [comment]
What does `xdpyinfo | grep -A2 screen` say?
How did you install RawTherapee, from which repository?

**Comment by TooWaBoo** [comment]
Looks like you are using a highres monitor. Can try the TooWaBlue theme and upload a screenshot, please?

**Comment by simontheflutist** [comment]
I think this looks a bit better, but if I recall correctly, fonts and colors are still not quite right. (With TooWaBlue)

What makes TooWaBlue different?

![image](https://user-images.githubusercontent.com/13023178/28241754-541b91b2-694f-11e7-9b67-27289b0f64f7.png)

**Comment by TooWaBoo** [comment]
@simontheflutist 

I guess you are using GTK lower than 3.20. I've no experience on Linux but if it's possible to update to GTK3.20 or higher, the TooWaBlue theme is highres compatible.

**Comment by Beep6581** [comment]
@simontheflutist https://github.com/Beep6581/RawTherapee/issues/3964#issuecomment-314799541

**Comment by simontheflutist** [comment]
stdout of `xdpyinfo | grep -A2 screen`:

```
default screen number:    0
number of screens:    1

screen #0:
  dimensions:    3840x2160 pixels (1016x572 millimeters)
  resolution:    96x96 dots per inch
```

I believe this is where my RawTherapee is coming from:

`deb http://ppa.launchpad.net/dhor/myway/ubuntu xenial main`

**Comment by Beep6581** [comment]
@simontheflutist thank you, I contacted Dariusz Duma, the repo maintainer, so that hopefully the missing info problem in the About window can be fixed.

@TooWaBoo is right that your Gtk+ is quite old, better if you used 3.22, however why don't you change the font size manually from the Preferences panel in RawTherapee?

**Comment by Beep6581** [comment]
P.S. Looks like the missing info problem in `AboutThisBuild.txt` was solved, based on this:
https://launchpad.net/~dhor/+archive/ubuntu/myway/+packages?field.name_filter=rawtherapee&field.status_filter=published&field.series_filter=
