### ISSUE TITLE
Crash after quitting RT in Mac OSX 10.11.3

### ISSUE THREAD

**Issue by kapiliitr** [Beep6581/RawTherapee#3971]
I am using RawTherapee versions 5.1 and 5.1.134 on Mac OSX El Capitan 10.11.3. Both versions crash after I close RT either by clicking the 'x' or by quitting from the main menu. Attached is a log I got from the crash report.

[crash-close.txt](https://github.com/Beep6581/RawTherapee/files/1150453/crash-close.txt)

**Comment by Benitoite** [comment]
Yes, I believe we all (macOS people) get that crash.  Seems related to libomp.  Reference: https://github.com/Beep6581/RawTherapee/issues/3882#issuecomment-304055545

**Comment by Benitoite** [comment]
For the record I tried macports libomp-devel but get the same crash.

**Comment by Benitoite** [comment]
Now I've tried building libiomp5 from https://www.openmprtl.org/sites/default/files/libomp_20160808_oss.tgz
with some success… 

@kapiliitr can you test this new build which integrates this library for the crash on exit: [old link removed]

**Comment by kapiliitr** [comment]
@Benitoite Raw therapee didn't even start for me. Attached is the error message and logs.
<img width="421" alt="screen shot 2017-07-16 at 4 25 27 pm" src="https://user-images.githubusercontent.com/1621360/28252214-938424a0-6a43-11e7-869c-8467b2901e57.png">
[openfail.txt](https://github.com/Beep6581/RawTherapee/files/1151407/openfail.txt)

**Comment by Benitoite** [comment]
Thanks for the report @kapiliitr !
I see macosx_bundle.sh is not copying the library into the app Frameworks dir.  However it is setting the correct install_name in rawtherapee-bin and rawtherapee-cli. I wonder why the script is not completely installing the library.

**Comment by Benitoite** [comment]
@kapiliitr Here's a new one to try.  https://filebin.net/n79w2kos0xtbsug7/RawTherapee_OSX_10.9_64_5.1-162-g26077cd0.zip

I added a manual copy command to macosx_bundle.sh.  Seems to open fine on my macOS 10.11 clean machine.

**Comment by kapiliitr** [comment]
That works. I can confirm that my changes were saved and RT did not throw a crash error on closing from either the 'x' sign or from the menu. Thanks :)

**Comment by Benitoite** [comment]
No prob @kapiliitr !
