### ISSUE TITLE
Bug in Newwavelet

### ISSUE THREAD

**Issue by Desmis** [Beep6581/RawTherapee#3974]
Hello

Yesterday, I tried to merge "newwaveletgtk3" with "dev".
Many changes due to 20 days without merge....but no probem...compile fine !
But when I try to execute RT, crash at beginning.

I think, I say "quel con tu t'es planté"...I retry twice and always the same problem.

I tried many many things...and I don't say all what I tried...during 2 days...
Finally, I merge with  "5f97800".... after in most cases always crash!

With "expanders" like in 5f97800,
1) when I click to shut a windows, crash
2) when I click on preferences", crash

I have look, relook, re re re look at my (old) code (more than one year), and found some bugs, in wavelet.cc, procparams and paramsedited. 
I controled pp3 and compare with sliders, checkbox, etc.  all seems to be good now.

But always crash as 1) and 2)

If I deleted in "expanders" "Gtk::manage", and in "exp***->add (*xxx, false)", suppres "false". In this case, no crash when 1), but always when 2)

I create a new branch (to preserve work in newwaveletgtk3), "waveletnew", with commit at "5f97800"

Perhaps, there is always bugs in my old code, or perhaps it is others things :)

jacques

**Comment by heckflosse** [comment]
@Desmis Jacques, can you tell me what to do to reproduce.

Shall I merge dev into newwavelet and test?
I'm sure to find the culprit, but I need to know how to test

**Comment by Desmis** [comment]
@heckflosse 
Ingo
The actually "waveletnew" is the less instable solution, with "evolution for expanders"

1) if I run "newwaveletgtk3", the system run normaly. I don't say there are no bug...(this branch has not been really tested during 1 year), but strictly "informatic", it runs fine

2) waveletnew, is the same, but  
a) with code clean (wavelet.cc, procparams, paramsedited...) : order in declaration,  supprees unused functions, etc.; 
b) merge with 5f97800
c) I suppressed functions added  - "GTK manage" for expanders and "false", for "add" (ex: expsettings->add(*settingsBox, false);)
In this case, RT start, we can close editors whithout crash, but if we click on "Preferences"==> crash
d) if I don't suppress c), I cannot close editors whithout crash

3) if you merge "waveletnew" wit "dev", all compile fine, but when starting RT, immediatly crash

Is it clear ?

Thank you :)

Jacques

**Comment by heckflosse** [comment]
@Desmis

Jacques,

I merged dev into waveletnew. RT starts fine here. I fixed the crash when opening `Preferences`
Can I push to waveletnew?

Ingo

**Comment by Desmis** [comment]
No problem :)

**Comment by heckflosse** [comment]
Pushed

**Comment by Desmis** [comment]
@heckflosse 

Ingo
I just "pull" waveletnew. It's compile and run fine :)

Thank you very much :)

Jacques

**Comment by heckflosse** [comment]
@Desmis

Jacques, de rien :)

**Comment by Beep6581** [comment]
I merged `dev` into `waveletnew`.

**Comment by Desmis** [comment]
@Beep6581 
thank you :)
