### ISSUE TITLE
Always show verbose warning when failure writing options file

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3975]
When RT fails writing the options file, the user should always get a verbose popup warning, not only a printf in the console when running in verbose mode as is now.

**Comment by Beep6581** [comment]
PR https://github.com/Beep6581/RawTherapee/pull/3976 shows a popup when RT fails to write the options file. It also shows a warning in the console:
> Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

Ideally it should use the `writeFailed()` function, but I don't know how to get the parent. Ingo points out that the same warning is generated when emptying the trash.

I would like to commit this ASAP so that we can find and fix some issues on macOS, but it would be nice if someone knew how to get that parent parameter.

**Comment by heckflosse** [comment]
go for merge from me

**Comment by Beep6581** [comment]
Merged into dev, but could be done better - see https://github.com/Beep6581/RawTherapee/pull/3976#discussion_r128290755
