### ISSUE TITLE
macOS RawTherapee 5.2 release build

### ISSUE THREAD

**Issue by Benitoite** [Beep6581/RawTherapee#3981]
Here is a build for MacOS 10.9 and up of the 5.2 release code.

https://filebin.net/qtcqeiljc248y4fu/RawTherapee_OSX_10.9_64_5.2.zip

Version: 5.2
Branch: 5.2
Commit: 78e921cb
Commit date: 2017-07-23
Compiler: clang-mp-3 3.9.1
Processor: generic x86
System: Apple
Bit depth: 64 bits
Gtkmm: V3.16.0
Build type: release
Build flags: -arch x86_64 -O3 -mmacosx-version-min=10.9 -std=c++11 -mtune=generic -Werror=unused-label -mmacosx-version-min=10.9 -flto -fopenmp=libomp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -O3 -DNDEBUG
Link flags: -arch x86_64 -mmacosx-version-min=10.9 -mtune=generic -headerpad_max_install_names -flto
OpenMP support: ON
MMAP support: ON
![52ss](https://user-images.githubusercontent.com/17919239/28504334-1ccbd54c-6fca-11e7-835d-6515029acdb2.jpg)
💈[Richard E. Barber](https://plus.google.com/116843283001218189721)

**Comment by Beep6581** [comment]
Thank you, uploaded.
