### ISSUE TITLE
Update description of -w

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3983]
In light of commit bc3d82a17a2f03c9b5ff007570a6c08b60666573, the description of `-w` should be updated (by a Windows user, not by me):
http://rawpedia.rawtherapee.com/Command-Line_Options

**Comment by Hombre57** [comment]
@Beep6581 Fixed. I'll let you check for syntax correctness and close.

**Comment by Beep6581** [comment]
Thank you @Hombre57 

> If you pass parameters to the RawTherapee executable it spawns a console window

1. Does that refer to `rawtherapee.exe`, `rawtherapee-cli.exe` or both?
2. Would the `-R` parameter cause a console window to spawn, or is it only filenames and folders as parameters which do that?

**Comment by Hombre57** [comment]
@Beep6581

1. Yes, this behavior is only set for `rawtherapee.exe`.
2. For `rawtherapee.exe`, a console window is spawn whenever :
    - a supplementary option is provided and :
       - options.rtSettings.verbose = true
       - or the file to open doesn't exist or is a directory, unless started in _remote_ mode (`-R`)

   For `rawtherapee-cli.exe`, a console is spawn whenever :
    - a supplementary option is provided and :
        - options.rtSettings.verbose = true
        - or the file to open doesn't exist or is a directory

**Comment by Beep6581** [comment]
Thank you for the clarification.
