### ISSUE TITLE
[macOS] sudo make macosx_bundle did not install runtime path in rawtherapee-cli

### ISSUE THREAD

**Issue by Benitoite** [Beep6581/RawTherapee#3985]
I noticed after building Version: 5.2-12-gb4899f24 the rpath gets set for -bin but not for -cli.  Library install names are correctly set, but I have to add a command to `macosx_bundle.sh`:

`install_name_tool -add_rpath @loader_path/../Frameworks /Users/tune/repo-rt/build/RawTherapee.app/Contents/MacOS/rawtherapee-cli`

**Comment by Beep6581** [comment]
Is this patch a fix for [this problem](https://github.com/Beep6581/RawTherapee/issues/3984#issuecomment-317652145)?

Where do I add that? Can you provide a patch/diff or pull request?

**Comment by Beep6581** [comment]
Is this it?

```diff
diff --git a/tools/osx/macosx_bundle.sh b/tools/osx/macosx_bundle.sh
index c819fae7..40cfe195 100644
--- a/tools/osx/macosx_bundle.sh
+++ b/tools/osx/macosx_bundle.sh
@@ -169,6 +169,7 @@ done
 
 msg "Registering @loader_path into the executable:"
 echo "   install_name_tool -add_rpath @loader_path/../Frameworks '${EXECUTABLE}'" | bash -v
+echo "   install_name_tool -add_rpath @loader_path/../Frameworks '${EXECUTABLE}-cli'" | bash -v
 
 msg "Installing required application bundle files:"
 PROJECT_SOURCE_DATA_DIR="${PROJECT_SOURCE_DIR}/tools/osx"
```

Note that there are several other places where `${EXECUTABLE}` is used with no `-cli` version. Someone should check them out to make sure `-cli` versions are not needed.

**Comment by Benitoite** [comment]
@Beep6581 No, this is unrelated. MacOS is quite the moving target...

That is the right spot, and your patch works.
