### ISSUE TITLE
Cameras' support 2017 - camconst.json and dcraw.cc updates

### ISSUE THREAD

**Issue by iliasg** [Beep6581/RawTherapee#3988]
Well, .. late to the party (RT5.2) but I hope not too late ;)

Updated camconst.json including support for many new cameras:

* Canon EOS 200D (EOS Rebel SL2, EOS Kiss X8)
* Canon EOS 6D Mark II
* Canon EOS 77D (Canon EOS 9000D)
* Canon EOS 800D (Canon EOS Rebel T7i, Canon EOS Kiss X9i)
* Canon EOS M6
* Canon PowerShot G9 X Mark II
* Fujifilm GFX 50S (updated color matrix)
* Fujifilm X-T20
* Fujifilm X100F
* Nikon D7500
* Nikon D80 (changed White Level)
* Olympus Tough TG-5
* Panasonic Lumix DC-GH5
* Pentax KP (completed)
* Sony α9 (Sony ILCE-9)

[camconst.zip](https://github.com/Beep6581/RawTherapee/files/1178013/camconst.zip)

**Comment by Beep6581** [comment]
@iliasg I re-wrote the list in your post for easier future reference and fixed a typo (D200 -> 200D), hope you don't mind that.

Tested and committed.

**Comment by Beep6581** [comment]
https://plus.google.com/b/106783532637761598368/+rawtherapee/posts/gBzRNWUrj5f

**Comment by agriggio** [comment]
wouldn't be more effective to have a 'hotfix' release (e.g. 5.2.1)?

**Comment by Beep6581** [comment]
At some point, once more changes accumulate. For now replacing one text file by a small percentage of users is enough.

**Comment by iliasg** [comment]
@agriggio @heckflosse 
- For the moment, to turn RT at not using the DNG WhiteLevels and color matrix, we need to add 
`|| !strncmp(model, "KP",2)` in https://github.com/Beep6581/RawTherapee/blob/dev/rtengine/dcraw.cc#L9513 . I will need to investigate a bit more to decide if it's better to make a generic change for Pentax models instead of doing this per_model ..

- I Added Fuji X-A10 in the below attached camconst.json .. but we need some changes in dcraw.cc to accomodate this one because dcraw reads false "raw_width" = 2222 "raw_height" = 35 .. probably because Fuji changed the way these values are reported. The correct values are  4912x3278
![fuji-x-a10-exif](https://user-images.githubusercontent.com/15012599/28713993-07db3546-739a-11e7-80d5-0ee1347f844c.png)
I think if we insert at around https://github.com/Beep6581/RawTherapee/blob/dev/rtengine/dcraw.cc#L9020 
```
if (!strncmp(model,"X-A10",5)) {
raw_width = 4912;
raw_height = 3278;
```
will do the job
Raw samples .. http://www.photographyblog.com/reviews/fujifilm_x_a10_review/sample_images/

I am not able to build RT at the moment .. I will be active again after monday ..

[camconst-fujiX-A10.zip](https://github.com/Beep6581/RawTherapee/files/1182727/camconst-fujiX-A10.zip)

**Comment by Taminaluna** [comment]
Hello,
I want to work on the raw files of my Canon77d with Rawtherapee. I added the camconst.json to .config/RawTherapee/profiles directory, but the colors differ quite a lot from the jpg. Is there anything else I have to change? I only chose Bearbeitungsprofile/Meine Profile/Canon EOS77d.
Thanks a lot for answering my request.
Barbara

**Comment by Beep6581** [comment]
@Taminaluna `camconst.json` does not go into `~/.config/RawTherapee/profiles/camconst.json`, move it to `~/.config/RawTherapee/camconst.json`

**Comment by Taminaluna** [comment]
Now it works :-), thank you very much!!! 
Best regards, Barbara

**Comment by iliasg** [comment]
camconst.json update attached
Includes support for 
Fujifilm X-A10 (modification of dcraw.cc is still needed)
Nikon D850, 
Olympus E-M10 Mark III,
Panasonic FZ80-81-82-83, TZ90-91-92-93-ZS70 
Sony RX10IV, 
Color matrix for Olympus E-M1II changed to final instead of beta
some small corrections here and there ..
[camconst26092017.zip](https://github.com/Beep6581/RawTherapee/files/1331017/camconst26092017.zip)

**Comment by Beep6581** [comment]
I would like to merge this ASAP to increase the chance of it getting tested before the release, but "Fujifilm X-A10 (modification of dcraw.cc is still needed)" - @heckflosse dcraw is not my territory, could you take it?

**Comment by heckflosse** [comment]
@Beep6581 I will push the dcraw.cc changes to dev asap

**Comment by Beep6581** [comment]
Thank you,
dcraw changes committed in ab07f62d, camconst changes committed in 172cbc1c.

Please open a new issue when there are new updates.
