### ISSUE TITLE
5.2 Widgets sizes have changed

### ISSUE THREAD

**Issue by listlfa** [Beep6581/RawTherapee#3997]
Some widgets are sized differently in 5.2 compared to previous versions.
Sample images for 5.2 and 5.1 below.

Complete version information -- 
Version: 5.2
Branch: release-5.2
Commit: 78e921cb
Commit date: 2017-07-23
Compiler: gcc 6.3.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.22.0
Build type: release
Build flags: -mwin32 -m64 -mthreads -msse2 -std=c++11 -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -mwindows -Wno-aggressive-loop-optimizations -DNDEBUG -O3
Link flags: -m64 -mthreads -static-libgcc -mtune=generic -mwindows -s -O3
OpenMP support: ON
MMAP support: ON

System information --
PS C:\Users\a> systeminfo

Host Name: -------------------
OS Name: Microsoft Windows 7 Ultimate
OS Version: 6.1.7601 Service Pack 1 Build 7601
OS Manufacturer: Microsoft Corporation
OS Configuration: Standalone Workstation
OS Build Type: Multiprocessor Free
Registered Owner: a
Registered Organization:
Product ID: --------------------------------
Original Install Date: 31/07/2014, 7:21:37 PM
System Boot Time: 24/04/2017, 8:23:48 PM
System Manufacturer: System manufacturer
System Model: System Product Name
System Type: x64-based PC
Processor(s): 1 Processor(s) Installed.
[01]: Intel64 Family 6 Model 42 Stepping 7 GenuineIntel ~3301 Mhz
BIOS Version: American Megatrends Inc. 3603, 9/11/2012
Windows Directory: C:\Windows
System Directory: C:\Windows\system32
Boot Device: \Device\HarddiskVolume4
System Locale: en-au;English (Australia)
Input Locale: en-us;English (United States)
Time Zone: (UTC+08:00) Perth
Total Physical Memory: 8,159 MB
Available Physical Memory: 4,766 MB
Virtual Memory: Max Size: 12,253 MB
Virtual Memory: Available: 8,383 MB
Virtual Memory: In Use: 3,870 MB
Page File Location(s): F:\pagefile.sys
Domain: WORKGROUP
Logon Server: \-----------------

Download --
http://rawtherapee.com/releases_head/windows/RawTherapee_5.2_WinVista_64.zip

Exact Steps--
1.Open RawTherapee

Samples--
Now, 5.2
https://imgur.com/a/XV5fb

https://imgur.com/a/LfkUr

Previously, 5.1
https://imgur.com/a/uhYre

https://imgur.com/a/IOFBF

**Comment by Beep6581** [comment]
Your 5.2 screenshots look like they're not using the RT theme at all. This means that it's likely that you have other issues in your settings which you may not have noticed yet. As such, I recommend you close RawTherapee, delete your [options file](http://rawpedia.rawtherapee.com/File_Paths#Config), and run it again. Should look fine now.

**Comment by listlfa** [comment]
I deleted the "options" file, starting 5,2 created a new "options" file. Now 5.2 looks normal and 5.1 looks wrong, same as 5.2 used too.  I'm a happy camper now and I'll leave it up to the dev team on if they want to keep this Issue open as a real bug.

Thank you :)
