### ISSUE TITLE
Canon 80D mRaw deinterlacing is broken

### ISSUE THREAD

**Issue by ants** [Beep6581/RawTherapee#4001]
80D mRaw format images show up as offset slices. Looks like slice height gets misinterpreted.

Version: 5.2
Branch: releases
Commit: 78e921cb

Example of problem: https://drive.google.com/open?id=0B_GMYhSIxbfMXy01c25pZnBCT00
Source file: https://drive.google.com/open?id=0B_GMYhSIxbfMWFplMzRDdU52cWc

**Comment by Benitoite** [comment]
Note that 80D mRaw has issues with tiling: https://discuss.pixls.us/t/canon-eos-80d-mraw-support-exhibit-tiling-issues/4190/2?u=hiram

**Comment by Beep6581** [comment]
See: https://github.com/Beep6581/RawTherapee/issues/3533#issuecomment-267024043

**Comment by ants** [comment]
Thanks. I will use darktable to get at the images I accidentally took with the mRaw mode.
