### ISSUE TITLE
RW2 files

### ISSUE THREAD

**Issue by ghost** [Beep6581/RawTherapee#4003]
I have just discovered RawTherapee and honestly I'm impressed. I've been working with Capture One so far. But I've already seen that RawTherapee offers much more editing tools.
Recently I bought the Lumix DC-TZ90 which has the same RW2 files as the DMX-FZ72. So I thought there would be no problem at all loading TZ90 files into Capture One. The files are not recognized by Capture One. RawTherapee can edit them, but they appear very much without saturation and it can be difficult to get them to appear right.
You can compare three screenshots, one with RW2 files (DMC-FZ72) with the same value for all previews, and two RW2 files (DC-TZ90) with different looks in preview above (as loaded in RawTherapee) and in the editing box. When selected in the editing box the saturation of the review changed to bleached out.
What I would like to know is, is there a way to change the settings in RawTherapee so that these RW2 - TZ90 files appear without the loss of saturation? If not, I seriously assume there is something wrong with this later RW2 version of Panasonic. Capture One can load the older RW2 but not the new one. What I did was convert the troublesome RW2 to dng, and then they could be imported into Capture One.
![clips_3980](https://user-images.githubusercontent.com/30772419/29003231-29cf8dbc-7ab3-11e7-8ca1-d43bc9e52260.jpg)
![clips_3978](https://user-images.githubusercontent.com/30772419/29003233-2dc528a0-7ab3-11e7-90ab-ac02c690f414.jpg)
![clips_3979](https://user-images.githubusercontent.com/30772419/29003235-312b76f2-7ab3-11e7-9131-3937d9deefec.jpg)
Thanks for your help.

**Comment by Beep6581** [comment]
The thumbnail with the green tick shows you what the image generated from the raw data using the current tool settings looks like. The thumbnail without the tick means the image has not been opened yet, so it shows you the embedded JPEG preview created by your camera.

http://rawpedia.rawtherapee.com/Getting_Started#Edit_your_first_image
http://rawpedia.rawtherapee.com/The_Image_Editor_Tab#Eek.21_My_Raw_Photo_Looks_Different_than_the_Camera_JPEG

**Comment by ghost** [comment]
Thanks for your reply.
Though I am still baffled by the apparant difference between the two types of RW2 files that Panasonic seems to use. There is no problem with the FZ72 camera, and there is a huge problem with the TZ90, because the latter one requires a hell of a lot of editing to get to look like the jpg preview.
I am going to study the manual first.

Another issue, what do you most photographers using RawTherapee do to catalogue their photos in a way that they are easily accessible by RawTherapee?

Thanks and regards,
Hetty

**Comment by Beep6581** [comment]
The Panasonic Lumix DC-TZ90 is brand new and not yet supported. You can help getting it supported by uploading a sample raw file using https://filebin.net/ and pasting the link in a new issue.

**Comment by ghost** [comment]
Yes, I understand now that each camera has a different kind of RAW format that needs to be loaded in a special way. I’ve managed to apply the generic processing profile punch 2 to this camera’s files. It works fine.
I’l send you some original files.
Thanks,

Hetty

**Comment by ghost** [comment]
I suppose this must be the link:
                                         dw5ws19dqvgl50ni <https://filebin.net/dw5ws19dqvgl50ni>

https://filebin.net/dw5ws19dqvgl50ni <https://filebin.net/dw5ws19dqvgl50ni>

Succes.

**Comment by Beep6581** [comment]
Thanks @hettyme 
In order for us and the [libre community](https://raw.pixls.us/) to use these raw files please confirm the following:
*  You declare that you own full rights to these files and you hereby release them under the [CC0](https://creativecommons.org/share-your-work/public-domain/cc0/) licence into the public domain.
* The files are manually copied from card/camera, without using any software like Nikon Transfer, and haven't been modified in any way.

**Comment by hettyme** [comment]
On 6 Aug 2017, at 19:32, Beep6581 <notifications@github.com> wrote:

Thanks @hettyme <https://github.com/hettyme>
In order for us and the libre community <https://raw.pixls.us/> to use them please confirm the following:

You declare that you own full rights to these files and you hereby release them under the CC0 <https://creativecommons.org/share-your-work/public-domain/cc0/> licence into the public domain.
The files are manually copied from card/camera, without using any software like Nikon Transfer, and haven't been modified in any way.

**Comment by ghost** [comment]
These are indeed the original RAW files (which my mac can’t read) taken straight from the camera DC-TZ90 without any editing and of which I own full rights.
Both files can be used under the CC0 licence, which I assume does not infringe in any way upon my own rights to use the files in any way I deem fit.
Herewith end the legalistic formalities.

Success with the making of an RW2 profile for this camera. Strange though that the older RW2 format is recognized by Capture One and my mac and not this new type of RW2.

**Comment by ghost** [comment]
I have two more files which indicate that somethings else needs tweaking in this RW2 version, the spherical correction. See photos. One is a clip from the file as it was rendered after conversion to dng (in Adobe dng converter) and the other is a clip of the file as it now shows in RawTherapee. Something needs adjusting there.
![clips_3981](https://user-images.githubusercontent.com/30772419/29006122-e6a8639c-7ae9-11e7-8fd7-1404f15af1d6.jpg)
![clips_3982](https://user-images.githubusercontent.com/30772419/29006125-ec33e5f2-7ae9-11e7-80f1-18def4e2ae53.jpg)
I hope this helps.

**Comment by ghost** [comment]
And this is how it looks in Silkypix, apparently the only app capable of correctly rendering the raw files. 
![clips_3983](https://user-images.githubusercontent.com/30772419/29006193-556bc926-7aeb-11e7-80c5-d336ace8c3c5.jpg)

**Comment by Beep6581** [comment]
Regarding the dark edges, see the last paragraph of the Lens Correction Profile section here:
http://rawpedia.rawtherapee.com/Lens/Geometry#Lens_Correction_Profile

Thank you for the raw sample. I opened issue #4004 - please take a look. Some more samples are needed, explained there.

**Comment by ghost** [comment]
OK, I’ll study the support pages and see what is needed.

**Comment by ghost** [comment]
I have uploaded several files. The photos were made with the object on a level table and the camera levelled.
ISO 200 P1040122
400 P...123
800 P...124
1000 P... 125
1250 P...132
1600 P...133
Tonight I'll shoot the 1800 and 3200 ISO.
Ratio 4:3 P1040139
3:2 P...140
16:9 P...141
1:1 P...142
The files can be found here.
https://filebin.net/j35i2sexf90zacr2
All under the CC0 licence.
I hope this helps. Success.
