### ISSUE TITLE
Pentax K-1 DCP profile broken ?

### ISSUE THREAD

**Issue by Hombre57** [Beep6581/RawTherapee#4006]
Here is the error message I get when browsing a folder with Penx K-1 files : 
```
DCP '/home/jc/rawtherapee/dcpprofiles/RICOH PENTAX K-1.dcp'
is missing 'ColorMatrix1'. Skipped.
```
If this profile can't be used, we should remove it from the bundled DCP profiles. Could one confirm that it's broken... and why ? @iliasg ?

**Comment by iliasg** [comment]
@Hombre57 
Inspecting the profile with exiftool shows no problem .. colormatrix1/2 , forwardmatrix1/2 and lookuptables exist, and the dcp works fine  with RT5.0.111 (It's hard for me to test with newer builds because it takes 15mins to start :( )

**Comment by Floessie** [comment]
@Hombre57 I downloaded a Pentax K-1 DNG and the DCP automatched without that error message.

```
$ md5sum src/rawtherapee/build/release/dcpprofiles/RICOH\ PENTAX\ K-1.dcp 
6d358374424fb28243da4e67f3002cac  src/rawtherapee/build/release/dcpprofiles/RICOH PENTAX K-1.dcp
```

HTH,
Flössie

**Comment by Beep6581** [comment]
Confirmed that the `RICOH PENTAX K-1.dcp` we ship (I made it) has an MD5 of `6d358374424fb28243da4e67f3002cac` and that it works fine on both normal and pixel-shift K-1 raws.

**Comment by Hombre57** [comment]
Ok, collateral effect of my patch on multi-frame handling. Closing.
