### ISSUE TITLE
Use astyle version 3

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4010]
Hello

We recently seem to have found that astyle version 2.* formats things differently to 3.0 using the same "recipe". As such, we should all update to the latest astyle release (3.0) to make sure things are consistent and diffs are clean.

Please tick the box once you've read this:
- [x] @agriggio 
- [x] @Desmis 
- [x] @Floessie 
- [x] @heckflosse 
- [x] @Hombre57

**Comment by Floessie** [comment]
There's still the problem with `pad-first-paren-out`, as you can see in for example in [f70ba32c9d2767c9941d28b8fe20ccb7cc0aed67](https://github.com/Beep6581/RawTherapee/pull/4033/commits/f70ba32c9d2767c9941d28b8fe20ccb7cc0aed67#diff-8ebdbcfe31960475e589d93d17c99cd2R347):

* `void func(int arg)` --> `void func (int arg)`
* `void func()` --> `void func()`

And it's not only function calls or declarations: astyle prepends every opening parenthesis with content in code with a space, i.e. initializations also. Is that something we want?

**Comment by heckflosse** [comment]
@Floessie 

> Is that something we want?

I dont't like the prepending space

**Comment by agriggio** [comment]
I really dislike that too

**Comment by Beep6581** [comment]
@Floessie did your edited [`rawtherapee.astylerc`](https://github.com/Beep6581/RawTherapee/blob/dev/rawtherapee.astylerc) fix that problem? If not, I can contact the author of astyle for help.

**Comment by Floessie** [comment]
@Beep6581 I guess, you mean [this one](https://github.com/Beep6581/RawTherapee/pull/4009/files/88d0512b4a6241416ed039ac9df26d6ef6947f1c#r132949360). I cannot tell, if it solves more problems than it creates, but yes, that solved this very problem in favor of @heckflosse's, @agriggio's, and my style. 😄 

Quoting myself:
> Seems that astyle isn't prepared for the "space in front of call" case (which is rare, IMHO).

The "which is rare, IMHO" didn't mean it's rare in the RT sources. It meant, it's rare in general (considering FLOSS and books on C++). Before digging into RT, I knew that there are different indentation styles and camelCase vs. _ discussions, but I've never thought, that space in front of call would be a topic. Though I'm open to [LLL](https://en.wikipedia.org/wiki/Lifelong_learning). 😉 

Best,
Flössie

**Comment by agriggio** [comment]
to be fair, I've seen space in front of calls used before, but I don't
remember where. that doesn't mean that I like it though :-)

**Comment by Beep6581** [comment]
So I suggest @agriggio @heckflosse @Hombre57 test your modification out and commit it if it's good.

**Comment by Beep6581** [comment]
Reply from the astyle author (matches @agriggio 's version):

> Removing the option pad-first-paren-out and using unpad-paren
will remove the spaces.
