### ISSUE TITLE
Thumbnail height maximum = 800 pixel

### ISSUE THREAD

**Issue by MarkusSenn** [Beep6581/RawTherapee#4015]
Maximum value for thumbnails in "Preferences/File Browser" is 800 pixel. I would like to use a higher value, as I am working on a large high-res monitor

**Comment by Hombre57** [comment]
We could raise the limit, but you must know that thumbnails consume quite some disk space. Which value would you like ?

**Comment by Beep6581** [comment]
@MarkusSenn are you using HiDPI mode or desktop scaling?

**Comment by MarkusSenn** [comment]
I think, 1200 would do, but prefer a MAX of 1600 or even 2000 regarding the newer high-res monitors

on my main studio machine I use a 27" 2560x1440 monitor in "normal" mode, whereas on my 4K-Laptop computer I have to use HiDPI-mode, otherwise many programs' types are rendered to small to be readable

**Comment by Beep6581** [comment]
RawTherapee's main preview should be scaled when using HiDPI mode, while I believe currently it is not, meaning currently more data must be processed when using HiDPI. It should be the same with thumbnails. I don't personally mind allowing a higher max thumb height but keep in mind that that is probably not the correct solution. See issue #3547

Unless my premise about scaling bitmaps is wrong, but the last time I read about HiDPI support, that was the expected behavior.

**Comment by Hombre57** [comment]
@Beep6581 I don't see the benefit of having HiDPI screen if you have to scale up the main preview. Do you mean displaying a 100% image with 1 img pixel = 2x2 screen pixel ? I can agree though for thumbnails and icons.

**Comment by MarkusSenn** [comment]
For my kind of work only the thumbnail max=800 is concerned - I would like to be able to put in a higher value in order to have a larger thumbnail on my 2560x1440 (or even 4K on my laptop) monitor! I completely agreee with Hombre57 that it would be pointless to use a HiDPI screen AND scale up the main preview. So for me: pleae let RT work with higher values (up to 2000 e.g.) in the "thumbnail max. view".

**Comment by Hombre57** [comment]
I guess you hit "Close and comment", which closed the issue ?

What kind of workflow would require such enormous thumbnails ? 800px is already a comfortable size for thumbnails, even on a 4k monitor. If you want big thumbnails for reviewing images, you should use the Inspector tool instead (though it would show the embedded full size image only), and raise the cache number in "Preferences / Performance" so you can hover more than one image without lag.
