### ISSUE TITLE
IPTC Data not exported

### ISSUE THREAD

**Issue by MarkusSenn** [Beep6581/RawTherapee#4016]
strange behavior observed yesterday!
Portrait oriented picture with IPTC-Data in it should be resized using post-resize sharpening.
Now: when "Transform/Resize/Post-Resize sharpening" is on "RL Deconvolution" ---> IPTC-Data got lost in the process and was NOT exported to new smaller file.
However, when the setting was on "unsharp mask" ----> IPTC-Data were exported.

**Comment by Beep6581** [comment]
Could not reproduce:
```
$ exiftool -G5 -s -a -m -u -args /tmp/amsterdam\ rl.jpg | grep "xxxx"
-JPEG-APP13-Photoshop-IPTC:By-line=xxxx
-JPEG-APP13-Photoshop-IPTC:Caption-Abstract=xxxx
$ exiftool -G5 -s -a -m -u -args /tmp/amsterdam\ usm.jpg | grep "xxxx"
-JPEG-APP13-Photoshop-IPTC:By-line=xxxx
-JPEG-APP13-Photoshop-IPTC:Caption-Abstract=xxxx
```

@MarkusSenn http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports
1. Which version of RawTherapee?
2. Which IPTC fields did you test?
3. Preferences > Image Processing > Metadata, what is the status of the "Copy Exif/IPTC/XMP unchanged to output file" checkbox?
4. How do you know the IPTC data in the saved file is missing?

**Comment by MarkusSenn** [comment]
1)    5.2

2)    "Description", "Description Writer", "Headline"

3)    UNchecked (test with CHECKED did not work)

4)    easy: IPTC Data in original file, but not in new smaller file when it was NOT exported / IPTC Data IN new file when export worked fine.

PS: It took quite some time to find out this rather peculiar bug - post-resize sharpening and IPTC-Data do not have anything in common?

**Comment by Beep6581** [comment]
@MarkusSenn what program did you use to determine that the IPTC data was missing from the saved file? As you can see from my snippet, the data is there - I cannot reproduce. Would be good if you could record a screencast showing how you reproduce the bug.

Just so that we're on the same page, please try using this image to reproduce the problem:
http://rawtherapee.com/shared/test_images/amsterdam.pef
