### ISSUE TITLE
Merge with dev is very very difficult

### ISSUE THREAD

**Issue by Desmis** [Beep6581/RawTherapee#4017]
I have merge "waveletnew" with "dev" with many many difficulties. I think new formatting is culprit ??

Difficulties come from "procparams.cc"

I just tried to merge "newlocallab" (merge with dev 6 days ago), with "dev".. It is quasi impossible to do this work. 
All is mixed "wavelet", "locallab", "etc". many  "}" are missing...

In french "c'est le bordel le plus total... mais pourquoi ?"

I will try tomorrow "manually" and or I will astyle "procparams"

Much time :)

jacques

**Comment by Beep6581** [comment]
Commit 47ed067c styles some files in newlocallab the same as they're styled in dev. Other files in dev haven't changed style-wise. I hope this helps you merge.

**Comment by Desmis** [comment]
@Beep6581 
I just tried with your commit,
* less rubric to merge
* but same problem, all is mixed and some "}" are wrong.

I'll do this operation "manually"

Jacques

**Comment by Desmis** [comment]
I just merge with dev "manually" (for procparams.cc)

I hope no error :)

**Comment by Beep6581** [comment]
@Desmis so are the two branches merged now, or is it only the file `procparams.cc` which is merged so far? If you have more files to merge, please show me an example of two files with the `}` problem, and I'll try to find where the problem came from and fix it.

**Comment by Beep6581** [comment]
Ah I see the merge commit now.

Are there any other issues, or can we close?

**Comment by Desmis** [comment]
@Beep6581 

Yes I merge "newlocallab" in "dev"...Perhaps we can close, but I don't think so.

But the problem remains . Why it is so difficult, or even impossible to merge with the command "git merge dev".
I had no problem before the last "style of procparams".

Now if I want to merge (newwavelet ot newlocallab) all rubrics are mixed...you have "locallab" mixed with others (wavelet, defringes, etc.) and some if (...) are not closed.

Jacques

**Comment by Floessie** [comment]
@Desmis Jacques, I'm just curious: I guess you had merge conflicts. Which merge tool do you use to resolve them?

**Comment by Desmis** [comment]
@Floessie 

To merge conflicts, I don't use any tools unless my skills...

For all files excepts "procparams.cc"
I used : git merge dev -m "merge with dev"

Then I open each file with conflict in Notepad++, I searh "head" and "dev" and compared...no problem in most cases.. I do not use special tool...is ther one ?

For "procparams.cc", I have tried, retried...with "newwavelet"...after many changes, I can compile

But for "newlocallab", I gave up, everything is mixed, some if () are not closed. In French "le bordel le plus total".

So I made the merge manually, comparing "procparams.cc (dev)" and "procparams.cc (newlocallab" before merge, scanning each packet of lines. I open the 2 files in 2 windows with Notepad++.
It took 10 minutes ... considerably less than trying to merge with git.
Jacques

**Comment by Floessie** [comment]
@Desmis 
> It took 10 minutes ... considerably less than trying to merge with git.

Yep, if the changes are too many, I sometimes do that, too. I use [Meld](http://meldmerge.org/) as `git mergetool`. Not that I grasp everything about merging and this tool, but it helps me to have a graphical tool to easily choose from one side or the other.

**Comment by Desmis** [comment]
I don't know if "Meld" is good, but obviously, merge with git, for procparams.cc give a corrupt file !

**Comment by Beep6581** [comment]
@Desmis 
> Why it is so difficult, or even impossible to merge with the command "git merge dev".

The reason is that astyle tries to preserve certain types of whitespace which look like they were made intentionally by the coder, so if the coder makes changes in one branch but not another, astyle won't make things the same. For example see the whitespace before the comma in `WBParams::init()` in `rtengine/procparams.cc` [here](https://github.com/Beep6581/RawTherapee/compare/86f3d326d972c86aa463ab1cc709a9ce82cb2ff1...0fc699c4b732d79ba53cce67b54b7c2fa340eff1), if you look at the way whitespaces were used you will see it was messy, inconsistent and the result of manual formatting from years ago which no longer applies.

In the future when I/we do any such cleanups I/we should remember to do the same to the open branches which modify those files. Which means the fewer open branches the better.

**Comment by Beep6581** [comment]
> I do not use special tool...is ther one ?

[kdiff3](http://kdiff3.sourceforge.net/) is very good, as it's a 3-way tool, while most other tools are only 2-way tools.

On my system, git finds it automatically when I do `git mergetool`

**Comment by Desmis** [comment]
I do not dispute the usefulness of a good formatting, but the file resulting after "git merge" is obviously corrupted. 
You offer me tools, but I tell you that Procparams.cc is corrupt

when you found something as (I have not kept ...)

            if (keyFile.has_key ("Locallab", "Sharradius"))  {
                locallab.sharradius  = keyFile.get_integer ("Locallab", "Sharradius");
				
                toneCurve.hlcompr = keyFile.get_integer ("Exposure", "HighlightCompr");

                if (pedited) {
                    pedited->locallab.sharradius = true;
                }
            }
or

        if (!pedited || pedited->toneCurve.hlcompr) {
            keyFile.set_integer ("Exposure", "HighlightCompr", toneCurve.hlcompr)

        if (!pedited || pedited->toneCurve.hlcomprthresh) {
            keyFile.set_integer ("Exposure", "HighlightComprThreshold", toneCurve.hlcomprthres
            }

**Comment by Beep6581** [comment]
@Desmis I do not argue that the result of an automatic merge can be corrupt if a lot of surrounding whitespace changes. Remember that I maintained the gtk2 and gtk3 branches for a long time. The only way to reduce the risk of merge issues is to make the same formatting changes to all branches (or not at all).

**Comment by Desmis** [comment]
The only way I found to merge is to do by comparing the 2 files (dev and newlocallab). It is the first time!

**Comment by Desmis** [comment]
OK but for me there is always a problem :)

Recall, when I merge "big" or "huge" merge (locallab, wavelet), with about 50 or 100 events...I have huge problem with only "procparams".

**It is not a tool problem...**

**it's not due to different version of Astyle**

**it is not because thers is too much merges**

**Never I have had this problem before.**

And the only way to do. I merge the 2 files by comparing, line by line and add manually all lines dues to "locallab".

but now, it's done :)

**Comment by Beep6581** [comment]
@Desmis I closed the issue because I thought the purpose was to raise awareness and now there was nothing to do here - apologies if that is not the case. Is there anything that still needs to be done in this issue?

**Comment by Desmis** [comment]
I don't know what there to do..but I have had huge problem after changes to procparams....

But you can close :)
