### ISSUE TITLE
Adjuster slider value shows 00

### ISSUE THREAD

**Issue by RawConvert** [Beep6581/RawTherapee#4018]
Various sliders including the main Exposure ones and the Lab ones behave strangely when moved by mouse, by including the value "00" between displaying zero and -1.

Ubuntu 16.10,   Version: 5.2-5-g10822f5,   Branch: dev,   Gtkmm: V3.20.1

![rt-zero-zero-value](https://user-images.githubusercontent.com/16868433/29338398-eda94916-820c-11e7-8ddd-968091e9c192.jpg)

**Comment by Floessie** [comment]
Cannot reproduce on Debian 9.1 with GTK 3.22.11.

**Comment by Beep6581** [comment]
I never noticed this before, but I can reproduce it using L\*a\*b\* Lightness for example:
```
Version: 5.2-41-gda4630ef
Branch: dev
Commit: da4630ef
Commit date: 2017-08-15
Compiler: cc 4.9.3
Processor: Intel(R)\ Core(TM)\ m3-6Y30\ CPU\ @\ 0.90GHz
System: Linux
Bit depth: 64 bits
Gtkmm: V3.22.0
Build type: release
Build flags:  -std=c++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -O3 -DNDEBUG
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON
```

**Comment by Beep6581** [comment]
```diff
diff --git a/rtgui/adjuster.cc b/rtgui/adjuster.cc
index a4f57499..bcdccc26 100644
--- a/rtgui/adjuster.cc
+++ b/rtgui/adjuster.cc
@@ -403,6 +403,7 @@ void Adjuster::spinChanged ()
 
 void Adjuster::sliderChanged ()
 {
+    std::cout << slider->get_value() << std::endl;
 
     if (delayConnection.connected()) {
         delayConnection.disconnect ();

```
`1` - `0.5` show as `1`
`0.5` - `0` show as `0`
`-0.0...1` - `-0.5` show as `00`
`-0.5` - `-1` show as `-1`

**Comment by Hombre57** [comment]
We cannot exclude that it's a change of the `Gtk::SpinButton` behavior. Nothing changed since Gtk2 era and I don't see any method to prevent displaying two zeros. See rgui/adjuster.cc  >  `Adjuster::setLimits`

**Comment by RawConvert** [comment]
Ok!

**Comment by Beep6581** [comment]
This is fixed/worked around by https://github.com/Beep6581/RawTherapee/pull/4823#issuecomment-423511624
