### ISSUE TITLE
RawTherapee 5.2: Fonts much to big on retina display (Mac)

### ISSUE THREAD

**Issue by bnzf** [Beep6581/RawTherapee#4022]
I use RawTherapee_OSX_10.9_64_5.2 on a Macbook Pro 2013 15" Retina under OS 10.9.5.

All the fonts in RawTherapee (in the main window) are about of the double size they should be and make RawTherapee quite  unuseable. I use the default settings and verified in the preferences where the fonts are 12pt. I attached a screenshot.

On my MacPro with an ordinary screen all is fine.

![rt5 2retina](https://user-images.githubusercontent.com/31108283/29425821-e73864c6-8384-11e7-840c-c28c396d5d71.jpg)

**Comment by Benitoite** [comment]
Try the development version which fixes this problem. See https://github.com/Beep6581/RawTherapee/issues/3984
https://filebin.net/obil7s03g68z7l7s/RawTherapee_OSX_10.9_64_5.2-61-g6e03141c.zip

**Comment by bnzf** [comment]
The linked development version does not fix the problem with me.

**Comment by Beep6581** [comment]
@bnzf delete your [options](http://rawpedia.rawtherapee.com/File_Paths#Config) file before running the development version. If the text is still too big, change the font size using the development version from Preferences.

**Comment by bnzf** [comment]
Deleiting the .options has no effect. Also, after deleting and running the development version again nothing new, excetp an empty gtk-3.0 folder, is writtten in .options. And made changes survive deleting .options .... so something must be saved somewhere else.

Setting the font  to Arial regular 12pt  makes it slightly better (letters are now about the Apple Menu size), but still larger as on my MacPro (which has the default none-12pt) setting. To get something similar on the Retina I have to change the size there to 9pt.

**Comment by Beep6581** [comment]
> Also, after deleting and running the development version again nothing new, excetp an empty gtk-3.0 folder, is writtten in .options

I don't understand what you're saying.

> Setting the font to Arial regular 12pt makes it slightly better (letters are now about the Apple Menu size), but still larger as on my MacPro (which has the default none-12pt) setting. To get something similar on the Retina I have to change the size there to 9pt.

So there's no problem?

**Comment by bnzf** [comment]
@Beep6581 
> I don't understand what you're saying.

I quit RawTherapee, delete the .options folder, start RawTherapee again change the font size, quit RawTherapee. Then in the newly generated .options folder there is only an empty gtk-3.0 folder. 
And, the changes of the font size survive deleting (again) the .options folder.
So RawTherapee stores settings somewhere else.

> So there's no problem?

If you consider massive different apperence on two different computers, with the default settings, as "no problem", there is no problem ;-)

**Comment by Benitoite** [comment]
@Beep6581 @bnzf The options file is located within the hidden Library folder in your home directory.
Delete the options file in Terminal or go to it by typing Command-Shift G, then enter:
/Users/username/Library/Application Support/RawTherapee/config
, substituting your username where it says username.

**Comment by Beep6581** [comment]
I'm not a macOS user but I have been involved in trying to get RT usable on macOS, in writing macOS documentation and in macOS user support. There is no `.options` folder that I'm aware of, there is only a file called `options` (no dot) inside the `RawTherapee*` folder which is inside a hidden folder called `config`, i.e. `~/.config/RawTherapee/options`, as the documentation says. If that is not the case, it needs to be updated - ping @Benitoite could you confirm?

I'm not aware of there being a `gtk-3.0` folder in `~/.config/RawTherapee/`

So either the documentation is wrong or you're deleting the wrong file/folder.

I don't consider it a problem if the text on a HiDPI screen has a different size than one on a non-HiDPI screen **and** the text size can be changed by the user **and** the setting survives restarting RawTherapee. Of course it would be best to have things looking perfect out of the box, but that won't happen as none of the RT devs use macOS or have HiDPI screens to test on AFAIK.

**Comment by bnzf** [comment]
@Benitoite 
After deleting the content of /Users/username/Library/Application Support/RawTherapee/ the apearance is fine with the default settings and the development version.
Thank you.

**Comment by Beep6581** [comment]
@Benitoite when does RT use `~/.config` and when does it use `/Users/username/Library/Application Support`, does that depend on whether it's in DMG form or something else?

**Comment by Benitoite** [comment]
@Beep6581 Should be using ~/Library/Application Support/RawTherapee/config anytime the app runs thru it's executable loader, the normal way.
https://github.com/Beep6581/RawTherapee/blob/b8801095395cbbbec53a8a63ee08296b0effd8e9/tools/osx/executable_loader.in#L31

**Comment by Beep6581** [comment]
RawPedia updated.
