### ISSUE TITLE
Curves with a large number of points are not loaded from a profile of the picture (pp3)

### ISSUE THREAD

**Issue by tmmidm** [Beep6581/RawTherapee#4023]
Hello.
System info:
RT version 5.2
Windows 7 64-bit
4G Ram

At application of a tone curve in the Exposure tab with a large number of points (&gt; ~ 100) there is the following problem. The curve is loaded from rtc of the file and applied, and also successfully remains in a profile of the picture (pp3), but after closing of the program the kept profile of the picture cannot be applied (at application nothing occurs). In the panel of viewing of files in the picture the tag that for the file there is a picture profile also off.
I attach the rtc file. It is made of profile dcp through dcptool and a text editor.

It is necessary for reproduction of a problem:
1. To open the photo for editing.
2. On the exposition tab to apply a tone curve from the file (in any place, including Lab curve).
3. To leave editing the picture and to close RawTherapee
4. To start RawTherapee and to look in a tab of viewing of pictures at lack of a mark about existence of a profile for the file.
To open the photo for editing and to try to load a profile from the file.

[70D_Faithfull.rtc.txt](https://github.com/Beep6581/RawTherapee/files/1233384/70D_Faithfull.rtc.txt)

**Comment by Beep6581** [comment]
1024 chars are read for a key's value.
https://github.com/Beep6581/RawTherapee/blob/dev/rtengine/procparams.cc#L3683

**Comment by Beep6581** [comment]
Does it make sense supporting so many points? Where do we draw the line?

**Comment by tmmidm** [comment]
Thanks for information on restriction.
At creation of a curve in the manual mode so large number of points of course isn't required.
RawPedia speaks about an opportunity to use any quantity of points in a curve. And it really works before closing of the program. Points also save in pp3 the file, but the program can't read them again. Because of this pp3 the file becomes unsuitable for application before removal of a curve from him manually.
Such behavior of the program is strange.
Change of a way of preservation of a curve in pp3 the file will be possible a solution. For example to keep data like rtc to the file.
As far as it is important for the general flow of users I don't undertake to estimate.

I wanted to separate only a tone curve from dcp of the file and to have an opportunity to use her in any place where there is import of a curve.

**Comment by agriggio** [comment]
I agree that in principle it should be possible to use an arbitrary number of points. Setting a limit a priori seems unnecessary to me.

However, @tmmidm, for your specific use case, note that you don't need all those points to get a faithful tone curve. In my experience, you can do with less than 10, let's just say 6-7:

- the two extreme points
- the point in which the curve crosses the mid line (i.e. where X=Y)
- a couple of points in between

something like this:

![curve](https://user-images.githubusercontent.com/11982086/29460453-53d216e2-8428-11e7-9c48-9412d199f4ab.jpg)

(The process should be quite easy to automate, BTW).

This has also the advantage of being much easier to edit, if you ever want to tweak the curve for a specific picture.

**Comment by tmmidm** [comment]
agriggio, thank you for advise.

I agree that the quantity of the points which are finding room in the extreme length of parameter are enough and reasonably.
In this regard I close a problem.
