### ISSUE TITLE
A problem with the Auto Motion correction for pixelshift demosaicing?

### ISSUE THREAD

**Issue by bnzf** [Beep6581/RawTherapee#4024]
There may be a problem with the Auto Motion correction for pixelshift demosaicing in parts with no motion. 
As an extreme example take a picture that has no motion I would expect that the Auto Motion correction does not detect motion. However turning Auto Motion correction on makes the picture look more or less like demosaiced with AMaZE.

Take for example the raw file from the Studio scene image, 100 ISO, pixelhift, of the Pentax K1  from: [https://www.dpreview.com/reviews/pentax-k-1/8](https://www.dpreview.com/reviews/pentax-k-1/8)

Here a cropped image demosaiced with pixelshift, Motion correction off. The result is more or less back/white with no color artifacts.
![pixelshift_mcoff](https://user-images.githubusercontent.com/31108283/29471463-651a59c8-8450-11e7-9dfe-655406ae27c8.jpg)

Here a cropped image demosaiced with pixelshift, Motion correction Automatic.
![pixelsift_mcautomatic](https://user-images.githubusercontent.com/31108283/29471507-8a9cbbb4-8450-11e7-94dc-5ae8db31d78d.jpg)

Here a cropped image demosaiced with AMaZE
![amaze](https://user-images.githubusercontent.com/31108283/29471552-ae7302a0-8450-11e7-85b8-6dc908afbad3.jpg)

Also Chromatic Aberration Auto correction produces, to a much lesser extend color artifacts (have a closer look to the center of the Siemens star).
![pixelshift_mcoff_autoca](https://user-images.githubusercontent.com/31108283/29471594-db666356-8450-11e7-8b7c-d6e2af61da26.jpg)

I use a Mac, OS 10.9.5.
This happens as well with RT 5.2, as with the development version RawTherapee_OSX_10.9_64_5.2-61-g6e03141c.

**Comment by heckflosse** [comment]
@bnzf This was one of the pictures I used for my tests when I developed pixelshift for rt. I will take a look.

**Comment by heckflosse** [comment]
@bnzf 

1) As I developed pixelshift for rt I tested with about 100 different pixelshift files. Exactly one of them had absolutely no motion and that wasn't IMGP0505.PEF ;-)

![ps_001](https://user-images.githubusercontent.com/13733487/29479075-77526b60-8470-11e7-9e15-fd69b1061ecb.png)

2) Always have a look at the motion mask

3) For images with no motion you can use 'Motion detection off'

4) for images with almost no motion you should use the custom mode and disable the 'check red/blue for motion'

5) the 'Automatic mode' is for outdoor shots with motion (moving water really needs the red/blue check for example).

6) When using 'Custom mode' also have a look at the 'smooth transitions' adjuster. It smooths the transitions between plain pixelshift combine (regions without motion) and (amaze) demosaic (regions with motion).

7) I have to document all this in rawpedia :(

**Comment by heckflosse** [comment]
@bnzf The raw ca correction is done per frame before the frames are combined. Perhaps this could be improved by using the same ca-shift for all frames (which also would be faster), but currently each frame gets his own correction. Also have a look at the corners of the IMGP505.PEF. There the raw auto ca-correction gives a much better result than without (left is without ca-correction, right is with ca-correction):

![ps_ca](https://user-images.githubusercontent.com/13733487/29480481-ded7fedc-8478-11e7-86a5-2186f1641903.png)

**Comment by bnzf** [comment]
@heckflosse 
Most of IMGP505.PEF source is rigid - there should thus be an constant shift over the whole image (except the feathers etc). Unless air refraction fluctuations come in, but at these short distances I do not believe they have a visible effect. 
However the motion mask is scattered:
![motionmaskg](https://user-images.githubusercontent.com/31108283/29484588-4a377dda-84c2-11e7-8cae-527e0794486c.jpg)

When turning Motion correction off if there a no major movements in the picture, then how the small unavoidable motion due e.g. vibrations is handled?

Concerning the CA:
The sub-pictures are taken with the same lens in the same circumstances, so the performed  CA correction should be the same on all sub-pictures, I think. With a common transformation there should be no negative effect to pixelshift.
Inspecting the sub-pictures individually could be a benefit only for a better estimate of what then should be the common CA correction.

**Comment by heckflosse** [comment]
@bnzf 

If the motion correction (detection) would be perfect there would be no need for `custom` or `off`mode.
RT is on the aggresive side when detecting motion in automatic mode because motion artifacts often are worse than demosaic artifacts. Other software is less aggressive but also does not detect motion as well as rt does and is less configurable.

> When turning Motion correction off if there a no major movements in the picture, then how the small unavoidable motion due e.g. vibrations is handled?

How should a motion correction which is turned off should handle motion? Off is off, means no motion correction, just plain pixelshift combine.

> The sub-pictures are taken with the same lens in the same circumstances, so the performed CA correction should be the same on all sub-pictures, I think

The circumstances are not the same as the sub-pictures are shifted by one pixel which gives different (though small differences) results for auto-ca-correction.

**Comment by bnzf** [comment]
@heckflosse 

> How should a motion correction which is turned off should handle motion? Off is off, means no motion correction, just plain pixelshift combine.

I see. For pictures with no internal movement, I will try to combine manually and see if there is an noticeable additional overall offset, due to camera movement, that could be corrected. 

- Edit: I just realized I refer to an other type of motion and approach to fix it. RT aims to handle moving object in a scene by using, for the area of the object, one of the sub images only. I was thinking about the whole scene moves relatively to the camera (or vice versa) and would like to move the sub images accordingly before combining. Sorry for the confusion.

> The circumstances are not the same as the sub-pictures are shifted by one pixel which gives different (though small differences) results for auto-ca-correction.

Sure, but look at that from an other point of view: We know that the sensor shifted by one pixel, so we can use that. 
The real, physical, distortion at a fixed point after the lens is the same. This very point is pictured in the sub pictures at one pixel offset (if the picture is already motion corrected). So we have four "measurements" (recorded with one pixel offset) we can use to determine the "real thing". And then apply that one correction to the sub images (of cause with the appropriate one pixel offset).
