### ISSUE TITLE
number of pictures corresponding to *-filter

### ISSUE THREAD

**Issue by MarkusSenn** [Beep6581/RawTherapee#4025]
I do not see where (if at all) the number of corresponding pictures to a filter, e.g. 1-5*, is indicated.
Example: I choose a selection by marking pictures with 1* Star (Shift+1) and let the selection be displayed. Now how many pictures are in the collection? Where do I find this number? If not, could it be added?

**Comment by heckflosse** [comment]
In the label of the file browser tab? Showing 1/4 when one of totally four files matches,

**Comment by Beep6581** [comment]
@MarkusSenn please use [the forum](https://discuss.pixls.us/c/software/rawtherapee/) for user support, not this issue tracker.
