### ISSUE TITLE
basic question

### ISSUE THREAD

**Issue by MarkusSenn** [Beep6581/RawTherapee#4026]
Sorry, this is maybe really basic, but I do not manage to find the explanation:
The Processing Profile Button: When is it pressed and when released. I don't get the clue, the symbol is too abstract for me. I see either 5 horizontal lines or  of them. Now which is which.
thanks for clarification!

**Comment by Beep6581** [comment]
@MarkusSenn I guess you're referring to the "Fill mode", see http://rawpedia.rawtherapee.com/The_Image_Editor_Tab#Processing_Profile_Selector
Please use the forum for user support.
https://discuss.pixls.us/c/software/rawtherapee/
