### ISSUE TITLE
Speedup for green equilibration

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#4034]
I created [a new branch](https://github.com/Beep6581/RawTherapee/tree/greenequil_speedup) with a speedup for green equlibration.
Because green equilibration has two parts, I placed two stopwatches in code (`gel part one` and `gel part two`).
I measured using a 100 MP file from a Phase One IQ3 using neutral profile + green equilibration set to 100.
I detected no differences in output.

Before

gel part one: ~120ms
gel part two: ~490ms

After

gel part one: ~80ms
gel part two: ~210ms

**Comment by Desmis** [comment]
@heckflosse 

I just tested with a D700 NEF
Compiled an run fine.

before:
gel part one: ~10ms
gel part two: ~43ms

After
gel part one: ~8ms
gel part two: ~18ms

No differences in output TIF.

Good job :)

**Comment by heckflosse** [comment]
@Desmis Jacques, thanks for testing :)
