### ISSUE TITLE
Use in place tranformations when using only luminance transformations

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#4037]
Currently, when a transformation (Vignette and/or Graduated Filter in exposure tab and/or Vignetting Correction Filter in Transform tab) is enabled, rt uses additional memory size of `width*height*3*4 byte` to do this processing even if it doesn't have to. It has to make a copy of the buffer only if other transformations (like rotation, perspective, distortion... ) are enabled too.

I created a new transform patch which optimizes this part for the case mentioned above.

Example: only Graduated Filter applied, no other transformation, measured with a 100 MP file:

before patch : 816 ms
after patch : 286 ms

Currently the patch is only for export (save as, queue), not for preview

```patch
diff --git a/rtengine/improcfun.h b/rtengine/improcfun.h
index 309e5c02..fd72b94e 100644
--- a/rtengine/improcfun.h
+++ b/rtengine/improcfun.h
@@ -198,6 +198,7 @@ public:
     ImProcFunctions       (const ProcParams* iparams, bool imultiThread = true)
         : monitorTransform (nullptr), lab2outputTransform (nullptr), output2monitorTransform (nullptr), params (iparams), scale (1), multiThread (imultiThread), lumimul{} {}
     ~ImProcFunctions      ();
+    bool needsLuminanceOnly() { return !(needsCA() || needsDistortion() || needsRotation() || needsPerspective() || needsLCP()) && (needsVignetting() || needsPCVignetting() || needsGradient());}
 
     void setScale         (double iscale);
 
diff --git a/rtengine/simpleprocess.cc b/rtengine/simpleprocess.cc
index 14ad333e..8c0941af 100644
--- a/rtengine/simpleprocess.cc
+++ b/rtengine/simpleprocess.cc
@@ -30,7 +30,7 @@
 #include "../rtgui/multilangmgr.h"
 #include "mytime.h"
 #undef THREAD_PRIORITY_NORMAL
-
+#include "StopWatch.h"
 namespace rtengine
 {
 extern const Settings* settings;
@@ -812,13 +812,21 @@ private:
 
         // perform transform (excepted resizing)
         if (ipf.needsTransform()) {
-            Imagefloat* trImg = new Imagefloat (fw, fh);
+            StopWatch Stop1("transform");
+            Imagefloat* trImg = nullptr;
+            if (ipf.needsLuminanceOnly()) {
+                trImg = baseImg;
+            } else {
+                trImg = new Imagefloat (fw, fh);
+            }
             ipf.transform (baseImg, trImg, 0, 0, 0, 0, fw, fh, fw, fh, imgsrc->getMetaData()->getFocalLen(), imgsrc->getMetaData()->getFocalLen35mm(),
                            imgsrc->getMetaData()->getFocusDist(),
                            imgsrc->getMetaData()->getFNumber(),
                            imgsrc->getRotateDegree(), true);
-            delete baseImg;
-            baseImg = trImg;
+            if(trImg != baseImg) {
+                delete baseImg;
+                baseImg = trImg;
+            }
         }
     }
 
```

**Comment by Desmis** [comment]
@heckflosse 
I test with a D700 NEF, with "queue" and only "graduated filter"

Before patch : 95 ms
After patch : 60 ms

No differences in output 
:)

**Comment by heckflosse** [comment]
@Desmis Jacques, thanks for testing. The large difference in my test is caused by the fact, that 'before' patch uses 6 buffers (3 in for rgb and 3 out for rgb) which (on Windows) all are aligned to the same modulo 4096 offset. This collides with the only 4-way-L1-cache of my AMD FX8350 CPU. On Linux and/or with Intel cpu the difference is much smaller (as in your test).

**Comment by Hombre57** [comment]
@heckflosse Nice and clean ! :)  👍 to commit
