### ISSUE TITLE
Can't paste things from 3rd party tools on Windows

### ISSUE THREAD

**Issue by Krzysiu** [Beep6581/RawTherapee#4038]
I've tried dynamic profiles and I noticed that pasting doesn't work well. Here are the steps to reproduce it:

1. Copy something from external application (I used Notepad++)
2. Paste it in e.g. Camera field in new dynamic profile (here it works)
3. Copy another text from external application
4. Thing copied from 1st point will be pasted
5. Paste clipboard content somewhere else in Windows - it will contain content from 3rd point

In short thing I've copied is text (lens name from Notepad), it gets copied to clipboard, but RawTherapee sees only the first content. Copying pasting from RT to RT or external application works well. I've tried also (in the New dynamic profile form):

1. Copy something from RT (e.g. pasted camera field)
2. Paste it in Lens field (works)
3. Copy something from RT again
4. Paste it in some field (works)
5. Copy something from external application
6. Paste it in some field (doesn't work, thing from 3rd point is copied)

PC info:
OS: Windows 7 pro 64 bit

RT info:
Version: 5.2
Branch: release-5.2
Commit: 78e921cb
Commit date: 2017-07-23
Compiler: gcc 6.3.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.22.0
Build type: release
Build flags: -mwin32 -m64 -mthreads -msse2 -std=c++11 -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -mwindows -Wno-aggressive-loop-optimizations -DNDEBUG -O3
Link flags: -m64 -mthreads -static-libgcc -mtune=generic -mwindows -s -O3
OpenMP support: ON
MMAP support: ON

**Comment by Beep6581** [comment]
Lack of followups, not confirmed by anyone else in latest `dev`, likely a Gtk+ thing if a thing at all. Closing.
