### ISSUE TITLE
Dynamic profiles doesn't work in Windows

### ISSUE THREAD

**Issue by Krzysiu** [Beep6581/RawTherapee#4040]
I've tried profiles in different combinations (i.e. different photos, profiles, dynamic profile settings, browser mode, then open or directly open file etc; I restarted RT every attempt, deleted old photo PP3 profile, renamed photo to avoid cache), but it simply fails every time. Some of the things I've tried:

* In camera field (rest default, lens unchecked): `Canon EOS 50D`, `CANON EOS 50D`, `re:.*`, `re:Canon .*`, `re:CANON .*` etc etc.
* In lens field (with camera checked and unchecked): different combinations, like above
* camera and lens unchecked, wide range of numeric values (e.g. 99-1000 for ISO 100 photo)
* exact numeric values (i.e. ISO 100-100 for photo with ISO 100)

I'm giving sample files, but I never got it to work - raw, jpeg, different cameras, different profiles etc etc.
* Photo: http://up.krzysiu.net/J2nanpOY8k/IMG_0022.CR2 (22 MB, please mind I've transfer quota; I release it as LGPL with proper attribution given in IPTC, in case you'd need to share it)
* Profile: https://pastebin.com/raw/uMtTARfW

There are no problems when I use profile as default for all raw files. I understand this report is rather "is just don't work", so I can debug it, if you'd tell me how. I'm not C++ programmer, I don't use compiled code debuggers (except Process Hacker, but that's rather monitor than actual debugger), but I'm not a newbie to PCs, so general instruction would be fine. 

PC info:
OS: Windows 7 pro 64 bit

RT info:
Version: 5.2
Branch: release-5.2
Commit: 78e921c
Commit date: 2017-07-23
Compiler: gcc 6.3.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.22.0
Build type: release
Build flags: -mwin32 -m64 -mthreads -msse2 -std=c++11 -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -mwindows -Wno-aggressive-loop-optimizations -DNDEBUG -O3
Link flags: -m64 -mthreads -static-libgcc -mtune=generic -mwindows -s -O3
OpenMP support: ON
MMAP support: ON

**Comment by agriggio** [comment]
hi,
did you set the default profile to (dynamic) in the image processing tab of the preferences dialog?

**Comment by Krzysiu** [comment]
Can I change my username to `idiot`? Sorry for bothering you and thanks a lot. Now it works!

**Comment by Beep6581** [comment]
Confirmed that this is mentioned in RawPedia, so no changes needed.
