### ISSUE TITLE
Make creating dynamic profiles easier

### ISSUE THREAD

**Issue by Krzysiu** [Beep6581/RawTherapee#4041]
I thought of improvement of creating new dynamic profile. There could be new button (or button in Add [new dynamic profile] form) which could be called "From the photo" (or differently - I just give an idea). Then dialog would show up, allowing select which values we want to fill (like partial profile choice) - one could select camera, lens, ISO etc. After clicking on the "apply", it would just fill out fields in new dynamic profile form with chosen data. As an extra, there could be dropdowns for numeric values where one could select exact value/maximum value/minimum value - i.e. when choosing photo with ISO 800, checking ISO and selecting "minimum value", new dynamic would be created with ISO checked, min val 800, max val 512000; when one would choose default "exact value", it would check ISO and fill min and max to 800.

I thought of that as there are differences in recognition between tools and I didn't find any simple way to copy info as read by RT. For example in http://up.krzysiu.net/J2nanpOY8k/IMG_0022.CR2 RT reports "`Canon EF-S18-135mm f/3.5-5.6 IS`" while ExifTool gives "`Canon EF-S 18-135mm f/3.5-5.6 IS`" (mind the space between EF-S and 18). Even without this differences, it would make creating dynamic profiles faster.

PC info:
OS: Windows 7 pro 64 bit

RT info:
Version: 5.2
Branch: release-5.2
Commit: 78e921c
Commit date: 2017-07-23
Compiler: gcc 6.3.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.22.0
Build type: release
Build flags: -mwin32 -m64 -mthreads -msse2 -std=c++11 -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -mwindows -Wno-aggressive-loop-optimizations -DNDEBUG -O3
Link flags: -m64 -mthreads -static-libgcc -mtune=generic -mwindows -s -O3
OpenMP support: ON
MMAP support: ON

**Comment by Hombre57** [comment]
There is a copy/paste mechanism for the PP3 profile in the File Browser. I haven't investigated yet, but it might be possible to add a **Paste** button in the Dynamic Profile window, which would fill all the fields (at least if information is available) from the last **copied** image (or the first one in case of multi-selection). Then it would be up to the user to complete the rule at will and save.

Given the already opened issues and rather big and structural ones, I'd put this request as low priority.

**Comment by midluk** [comment]
I had the same idea some time ago, but could not find a way to get the info of the current image.

But while I was looking at the code I added a "clone" button which works like the "New" button but fills everything with the values of the currently selected rule instead of the default values. If you are interested in that change I can clean it up (make the button text translatable) and post the patch.

**Comment by agriggio** [comment]
@midluk go for it! :+1: ;-)

**Comment by Beep6581** [comment]
@midluk we can re-open this issue when you post the patch.
