### ISSUE TITLE
Speedup for loading of Phase One files

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#4050]
I created a [new branch](https://github.com/Beep6581/RawTherapee/tree/ph1speedup) with a speedup for loading of Phase One files.
I placed two stopwatches in code, one for `phase_one_load_raw_c()` and one for `phase_one_correct()`.
I tested with a Phase One IQ3 100MP file, which I unfortunately can not share.
I measured on my AMD FX8350 8 core:

```
                                  before        after
phase_one_load_raw_c()           1295 ms       225 ms
phase_one_correct()              1090 ms       380 ms
```

There are no differences in output. There's an [additional speedup](https://github.com/Beep6581/RawTherapee/commit/c16115cdde0b0a63aae75de2a23bc113ad35adae#diff-9967648f0eb70b821877dd6105e978efR1481) possible for `phase_one_correct()`, but that leads to very small differences in output. Though the result should be even more accurate with that additional speedup.

The speedup for `phase_one_load_raw_c()` is only enabled when mmap is used, which usually is the case.

More tests are needed, but I only have two files which, as I already wrote above, I can not share.
Maybe @mightymax is interested and can provide some additional files to test with.

**Comment by Beep6581** [comment]
There are 3 files from 2 models here:
https://raw.pixls.us/

And a bunch of raws from the Phase One XF here:
http://www.imaging-resource.com/PRODS/phase-one-xf-100mp/phase-one-xf-100mpA7.HTM

**Comment by mightymax** [comment]
Let me know if you are still interested in more IIQ files, I can provide them without any restrictions. The speed increasement is great news! How did you test the differences in the two images? Pixel by pixel?

**Comment by Beep6581** [comment]
ImageMagick has a very useful `compare 1.tif 2.tif diff.tif` function for testing for differences between images.

**Comment by heckflosse** [comment]
@mightymax I'm still interested in more IIQ files, especially some with highlights clipped or near clipping. Currently I have files from IQ3, P45+ and P65+
To test for differences I built the absolute difference between before and after and amplified the difference image using an extreme brightness curve. The result was completely black. But I also use the method @Beep6581 mentioned.

@Beep6581 `compare 1.tif 2.tif x:` ;-)

I just detected a bug when images have clipped regions. Fix follows soon. But it will reduce the speedup for `phase_one_correct()` a bit :(

**Comment by heckflosse** [comment]
I pushed a fix for the bug with clipped highlights. With this fix the processing time of `phase_one_correct()` went up to 495 ms

**Comment by heckflosse** [comment]
I just pushed 2 commits. First one gives some additional speed for P45+ and P65+.
Second one gives a bit of the speedup back, I lost with my bugfix mentioned above.


```
                                      before        after

IQ3 phase_one_load_raw_c()           1295 ms       225 ms
IQ3 phase_one_correct()              1090 ms       417 ms

P45+ phase_one_load_raw_c()           530 ms       106 ms
P45+ phase_one_correct()              750 ms       300 ms

P65+ phase_one_load_raw_c()           790 ms       155 ms
P65+ phase_one_correct()             1090 ms       345 ms

```
