### ISSUE TITLE
When I start the queue, no visible change happens

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4058]
I add a few photos to the queue. When I click on the "Start processing" button, nothing visible happens. The progress bar said "0%" before, it still says "0%" when I click start. On a slow laptop, a minute could pass before the first photo is done and the % changes. I think it would be appropriate if something changed when the queue is turned on, e.g. making the progress bar say "Processing..." until the next % change, or maybe you have a better idea?

**Comment by Beep6581** [comment]
The queue tab's icon does change, but I missed that, because my focus is "here" and the tab is "there".

I think it would be good if the "0%" progress bar changed immediately, and if the "start" button became inactive when start is pressed.

**Comment by Beep6581** [comment]
Furthermore, the progress indicator does nothing while the queue is processing. I'm on photo 29/49 and it still stays at 0%.

![imgur-2017_09_04-20 42 46](https://user-images.githubusercontent.com/5844619/30036326-90d775e0-91b2-11e7-9fb9-f6cd35f8db93.png)

![imgur-2017_09_04-20 46 26](https://user-images.githubusercontent.com/5844619/30036327-90d87828-91b2-11e7-9e19-68c98903fdb8.png)

**Comment by heckflosse** [comment]
Queue can run in background. Using the progress bar in queue currently would collide with using the progress bar for showing the decode process when you open an image while the queue is running

**Comment by heckflosse** [comment]
The correct solution imho would be to add a progress bar to the queue tab which is updated once per image.

**Comment by heckflosse** [comment]
@Beep6581 

> and if the "start" button became inactive when start is pressed.

Why do we have two buttons at all. It would be sufficient to have one button which's icon changes from start to stop and vice versa.

**Comment by Beep6581** [comment]
> Queue can run in background. Using the progress bar in queue currently would collide with using the progress bar for showing the decode process when you open an image while the queue is running

I would gladly repurpose that progress bar to show queue progress, and leave demosaicing and decoding to the Editor progbar.

> Why do we have two buttons at all. It would be sufficient to have one button which's icon changes from start to stop and vice versa.

Good point.

**Comment by heckflosse** [comment]
> decoding to the Editor progbar.

when using METM the editor progbar is not visible at decoding

**Comment by Beep6581** [comment]
One solution would be for the progress bar to show one thing when the Queue tab is in focus and another thing when the Editor is in focus. That would also take care of showing the File Browser's progress when the File Browser tab is in focus and a large folder is being opened.

Currently the Editor tab is only shown after decoding completes. If that's not a big problem to change, seems more intuitive to me that the Editor tab should be shown the moment a thumbnail is clicked, and the progress bar in the Editor tab is used to show everything related to that image: decoding, demosaicing, all the tools, etc.

**Comment by Beep6581** [comment]
I want to use a Gtk::Switch to get the desired feedback, partly because it's appropriate, but mostly because it looks cool in a dark theme and when you click it, it animates :D (CSS).

![imgur-2018_01_05-00 19 53](https://user-images.githubusercontent.com/5844619/34588611-3399f04a-f1ae-11e7-94d9-2b28e7a56df4.png)

```diff
diff --git a/rtgui/batchqueuepanel.cc b/rtgui/batchqueuepanel.cc
index fcccdf08..292588c9 100644
--- a/rtgui/batchqueuepanel.cc
+++ b/rtgui/batchqueuepanel.cc
@@ -46,29 +46,23 @@ BatchQueuePanel::BatchQueuePanel (FileCatalog* aFileCatalog) : parent(nullptr)
 
     batchQueue = Gtk::manage( new BatchQueue(aFileCatalog) );
 
-    // construct batch queue panel with the extra "start" and "stop" button
     Gtk::VBox* batchQueueButtonBox = Gtk::manage (new Gtk::VBox);
     batchQueueButtonBox->set_name("BatchQueueButtons");
 
-    start = Gtk::manage (new Gtk::ToggleButton ());
-    stop = Gtk::manage (new Gtk::ToggleButton ());
-    autoStart = Gtk::manage (new Gtk::CheckButton (M("BATCHQUEUE_AUTOSTART")));
-    start->set_tooltip_markup (M("FILEBROWSER_STARTPROCESSINGHINT"));
-    stop->set_tooltip_markup (M("FILEBROWSER_STOPPROCESSINGHINT"));
-    autoStart->set_tooltip_text (M("FILEBROWSER_TOOLTIP_STOPPROCESSING"));
-    start->set_active (false);
-    stop->set_active (true);
-    autoStart->set_active (options.procQueueEnabled);
-
-    start->set_image (*Gtk::manage (new RTImage ("gtk-media-play.png")));
-    start->get_style_context()->add_class("BIG");
-    startConnection = start->signal_toggled().connect (sigc::mem_fun(*this, &BatchQueuePanel::startBatchProc));
-    stop->set_image (*Gtk::manage (new RTImage ("gtk-media-stop.png")));
-    stop->get_style_context()->add_class("BIG");
-    stopConnection = stop->signal_toggled().connect (sigc::mem_fun(*this, &BatchQueuePanel::stopBatchProc));
-    batchQueueButtonBox->pack_start (*start, Gtk::PACK_SHRINK, 4);
-    batchQueueButtonBox->pack_start (*stop, Gtk::PACK_SHRINK, 4);
-    batchQueueButtonBox->pack_start (*autoStart, Gtk::PACK_SHRINK, 4);
+    qLbl = Gtk::manage (new Gtk::Label(M("MAIN_FRAME_BATCHQUEUE")));
+
+    qOnOff = Gtk::manage (new Gtk::Switch());
+    qOnOff->set_active (false);
+    qOnOff->set_tooltip_markup (M("FILEBROWSER_STARTPROCESSINGHINT"));
+    //qOnOffConn = qOnOff->signal_state_set(true).connect (sigc::mem_fun(*this, &BatchQueuePanel::startBatchProc));
+
+    qAutoStart = Gtk::manage (new Gtk::CheckButton (M("BATCHQUEUE_AUTOSTART")));
+    qAutoStart->set_tooltip_text (M("FILEBROWSER_TOOLTIP_STOPPROCESSING"));
+    qAutoStart->set_active (options.procQueueEnabled);
+
+    batchQueueButtonBox->pack_start (*qLbl, Gtk::PACK_SHRINK, 4);
+    batchQueueButtonBox->pack_start (*qOnOff, Gtk::PACK_SHRINK, 4);
+    batchQueueButtonBox->pack_start (*qAutoStart, Gtk::PACK_SHRINK, 4);
 
     // Output directory selection
     fdir = Gtk::manage (new Gtk::Frame (M("PREFERENCES_OUTDIR")));
@@ -216,7 +210,7 @@ void BatchQueuePanel::updateTab (int qsize, int forceOrientation)
         if(!qsize ) {
             grid->attach_next_to(*Gtk::manage (new RTImage ("processing.png")), Gtk::POS_TOP, 1, 1);
             l = Gtk::manage (new Gtk::Label (Glib::ustring(" ") + M("MAIN_FRAME_BATCHQUEUE")) );
-        } else if( start->get_active () ) {
+        } else if (qOnOff->get_active()) {
             grid->attach_next_to(*Gtk::manage (new RTImage ("processing-play.png")), Gtk::POS_TOP, 1, 1);
             l = Gtk::manage (new Gtk::Label (Glib::ustring(" ") + M("MAIN_FRAME_BATCHQUEUE") + " [" + Glib::ustring::format( qsize ) + "]"));
         } else {
@@ -236,7 +230,7 @@ void BatchQueuePanel::updateTab (int qsize, int forceOrientation)
         if (!qsize ) {
             grid->attach_next_to(*Gtk::manage (new RTImage ("processing.png")), Gtk::POS_RIGHT, 1, 1);
             grid->attach_next_to(*Gtk::manage (new Gtk::Label (M("MAIN_FRAME_BATCHQUEUE") )), Gtk::POS_RIGHT, 1, 1);
-        } else if ( start->get_active () ) {
+        } else if (!qOnOff->get_active()) {
             grid->attach_next_to(*Gtk::manage (new RTImage ("processing-play.png")), Gtk::POS_RIGHT, 1, 1);
             grid->attach_next_to(*Gtk::manage (new Gtk::Label (M("MAIN_FRAME_BATCHQUEUE") + " [" + Glib::ustring::format( qsize ) + "]" )), Gtk::POS_RIGHT, 1, 1);
         } else {
@@ -273,14 +267,11 @@ void BatchQueuePanel::queueSizeChanged (int qsize, bool queueEmptied, bool queue
 
 void BatchQueuePanel::startBatchProc ()
 {
-
-    stopConnection.block (true);
-    startConnection.block (true);
-    stop->set_active (false);
-    start->set_active (true);
-    stopConnection.block (false);
-    startConnection.block (false);
-
+/*
+    qOnOffConn.block (true);
+    qOnOff->set_active (true);
+    qOnOffConn.block (false);
+*/
     if (batchQueue->hasJobs()) {
         fdir->set_sensitive (false);
         fformat->set_sensitive (false);
@@ -295,13 +286,11 @@ void BatchQueuePanel::startBatchProc ()
 
 void BatchQueuePanel::stopBatchProc ()
 {
-
-    stopConnection.block (true);
-    startConnection.block (true);
-    stop->set_active (true);
-    start->set_active (false);
-    stopConnection.block (false);
-    startConnection.block (false);
+/*
+    qOnOffConn.block (true);
+    qOnOff->set_active (false);
+    qOnOffConn.block (false);
+*/
     updateTab (batchQueue->getEntries().size());
 }
 
@@ -310,7 +299,7 @@ void BatchQueuePanel::addBatchQueueJobs ( std::vector<BatchQueueEntry*> &entries
 
     batchQueue->addEntries (entries, head);
 
-    if (stop->get_active () && autoStart->get_active ()) {
+    if (!qOnOff->get_active() && qAutoStart->get_active()) {
         startBatchProc ();
     }
 }
@@ -318,7 +307,7 @@ void BatchQueuePanel::addBatchQueueJobs ( std::vector<BatchQueueEntry*> &entries
 bool BatchQueuePanel::canStartNext ()
 {
 
-    if (start->get_active ()) {
+    if (qOnOff->get_active()) {
         return true;
     } else {
         fdir->set_sensitive (true);
@@ -332,7 +321,7 @@ void BatchQueuePanel::saveOptions ()
 
     options.savePathTemplate    = outdirTemplate->get_text();
     options.saveUsePathTemplate = useTemplate->get_active();
-    options.procQueueEnabled    = autoStart->get_active ();
+    options.procQueueEnabled    = qAutoStart->get_active();
 }
 
 void BatchQueuePanel::pathFolderButtonPressed ()
@@ -375,7 +364,7 @@ bool BatchQueuePanel::handleShortcutKey (GdkEventKey* event)
     if (ctrl) {
         switch(event->keyval) {
         case GDK_KEY_s:
-            if (start->get_active()) {
+            if (qOnOff->get_active()) {
                 stopBatchProc();
             } else {
                 startBatchProc();
diff --git a/rtgui/batchqueuepanel.h b/rtgui/batchqueuepanel.h
index a4d6ed24..2b3b1f50 100644
--- a/rtgui/batchqueuepanel.h
+++ b/rtgui/batchqueuepanel.h
@@ -32,13 +32,12 @@ class BatchQueuePanel : public Gtk::VBox,
     public FormatChangeListener
 {
 
+    Gtk::Label* qLbl;
     Gtk::Button* zoomInButton;
     Gtk::Button* zoomOutButton;
-    Gtk::ToggleButton* start;
-    Gtk::ToggleButton* stop;
-    Gtk::CheckButton* autoStart;
-    sigc::connection startConnection;
-    sigc::connection stopConnection;
+    Gtk::Switch* qOnOff;
+    sigc::connection qOnOffConn;
+    Gtk::CheckButton* qAutoStart;
 
     Gtk::Entry* outdirTemplate;
     MyFileChooserButton* outdirFolder;
```

I'm having a hard time understanding the gtkmm documentation to change `stop->signal_toggled` to `qOnOff->signal_state_set`:
* `signal_toggled` https://developer.gnome.org/gtkmm/stable/classGtk_1_1ToggleButton.html#a47df906f7ae7a3e1ef7c08301999598d
* `signal_state_set` https://developer.gnome.org/gtkmm/stable/classGtk_1_1Switch.html#a76b1a913499bcfbe4ba2e37c0d4e6cff

Maybe someone would like to help a brother out? :]

**Comment by heckflosse** [comment]
> Maybe someone would like to help a brother out?

I would like, but my limited knowledge...

**Comment by Beep6581** [comment]
Maybe of help:
http://python-gtk-3-tutorial.readthedocs.io/en/latest/button_widgets.html#switch

**Comment by Floessie** [comment]
@Beep6581 
> I want to use a Gtk::Switch to get the desired feedback, partly because it's appropriate, but mostly because it looks cool in a dark theme and when you click it, it animates :D (CSS).

While it might look cool when used stringently, it might awaken desires when only used in one place. In most UIs you either have checkboxes *or* switches. And if you have switches your UI is "responsive" and "touch-ready".

Just my 2¢.

**Comment by agriggio** [comment]
@Beep6581 what exactly are you having troubles with? You should connect the `signal_state_set` handler to the actions currently associated to pressing the start and stop buttons, and use the `bool` argument to the handler to distinguish between the two cases (I suppose `true` would correspond to start and `false` to stop). Does this make sense?

**Comment by Beep6581** [comment]
> it might awaken desires

I'm hoping that it does :smiley: 

@agriggio it makes sense, but despite trying various things with `x` this line just won't compile:
```c++
qOnOffConn = qOnOff->signal_state_set(x).connect (sigc::mem_fun(*this, &BatchQueuePanel::startBatchProc));
```

**Comment by agriggio** [comment]
@Beep6581, try this:

```c++
qOnOffConn = qOnOff->signal_state_set().connect (sigc::mem_fun(*this, &BatchQueuePanel::startOrStopBatchProc));
```

where `startOrStopBatchProc` is like this:

```c++
void BatchQueuePanel::startOrStopBatchProc(bool value)
{
    if (value) {
        startBatchProc();
    } else {
        stopBatchProc();
    }
}
```

**Comment by Beep6581** [comment]
@agriggio if I add this to `.h`:
```c++
    void startOrStopBatchProc();
```
I get
```text
error: prototype for ‘void BatchQueuePanel::startOrStopBatchProc(bool)’ does not match any in class ‘BatchQueuePanel’
```
and an avalanche of other bizarre (to me) errors.

If instead I add
```c++
    void startOrStopBatchProc(bool value);
```
I get:
```text
In file included from /usr/include/sigc++-2.0/sigc++/signal_base.h:27:0,
                 from /usr/include/sigc++-2.0/sigc++/signal.h:8,
                 from /usr/include/sigc++-2.0/sigc++/sigc++.h:104,
                 from /usr/include/glibmm-2.4/glibmm/thread.h:50,
                 from /usr/include/glibmm-2.4/glibmm.h:89,
                 from /usr/include/gtkmm-3.0/gtkmm.h:87,
                 from /home/morgan/programs/code-rawtherapee/rtgui/batchqueuepanel.h:22,
                 from /home/morgan/programs/code-rawtherapee/rtgui/batchqueuepanel.cc:19:
/usr/include/sigc++-2.0/sigc++/functors/slot.h: In instantiation of ‘static T_return sigc::internal::slot_call1<T_functor, T_return, T_arg1>::call_it(sigc::internal::slot_rep*, sigc::type_trait_take_t<T_arg3>) [with T_functor = sigc::bound_mem_functor1<void, BatchQueuePanel, bool>; T_return = bool; T_arg1 = bool; sigc::type_trait_take_t<T_arg3> = const bool&]’:
/usr/include/sigc++-2.0/sigc++/functors/slot.h:155:37:   required from ‘static void* (* sigc::internal::slot_call1<T_functor, T_return, T_arg1>::address())(void*) [with T_functor = sigc::bound_mem_functor1<void, BatchQueuePanel, bool>; T_return = bool; T_arg1 = bool; sigc::internal::hook = void* (*)(void*)]’
/usr/include/sigc++-2.0/sigc++/functors/slot.h:657:90:   required from ‘sigc::slot1<T_return, T_arg1>::slot1(const T_functor&) [with T_functor = sigc::bound_mem_functor1<void, BatchQueuePanel, bool>; T_return = bool; T_arg1 = bool]’
/usr/include/sigc++-2.0/sigc++/functors/slot.h:1821:26:   required from ‘sigc::slot<T_return, T_arg1, sigc::nil, sigc::nil, sigc::nil, sigc::nil, sigc::nil, sigc::nil>::slot(const T_functor&) [with T_functor = sigc::bound_mem_functor1<void, BatchQueuePanel, bool>; T_return = bool; T_arg1 = bool]’
/home/morgan/programs/code-rawtherapee/rtgui/batchqueuepanel.cc:57:114:   required from here
/usr/include/sigc++-2.0/sigc++/functors/slot.h:148:20: error: void value not ignored as it ought to be
                (a_1);
                    ^
```

**Comment by agriggio** [comment]
can you post the full patch?

**Comment by Beep6581** [comment]
@agriggio https://gist.github.com/ceb2cdf2d0cc56d0a0fdcc7130a351c1

**Comment by agriggio** [comment]
@Beep6581 just change the new function like this:

```c++
bool BatchQueuePanel::startOrStopBatchProc(bool value)
{
    if (value) {
        startBatchProc();
    } else {
        stopBatchProc();
    }
    return false;
}
```
and it should compile. I haven't tested what it does though :-)
FWIW, I think the switch is ugly...

**Comment by Beep6581** [comment]
Patch complete, works IMHO very nicely!

@agriggio I'm hoping this tenacious video will melt your heart and change your mind ;)
https://filebin.net/s1m05js425qrrp12/rt_queue_switch.mp4

Opened PR #4276

**Comment by Floessie** [comment]
The switch isn't localized and looks alien in the UI, IMHO. Functionality is fine, though.

**Comment by Beep6581** [comment]
@Floessie the switch is localized. #4278 was supposed to make the switch use the same language as RT is set to use.

**Comment by Kildor** [comment]
The current behavior and UI is much worse than the previous one. I'm looking to the RawTherapee_dev_5.3-485-g8622efce_WinVista_64
At least it has currently mixed icons play and pause. Now there is red pause icon when queue is active and green play when there are some images in queue but it is stop. RT 5.3-228 has correct icons. Was the changing intended?

PS: I agree with Floessie about alien look of this widget.

**Comment by Beep6581** [comment]
> Now there is red pause icon when queue is active and green play when there are some images in queue but it is stop.

Can you show a screenshot? There are no red or green icons. This is what it looks like, and it's very clear whether queue processing is on or off: https://filebin.net/s1m05js425qrrp12/rt_queue_switch.mp4

**Comment by Kildor** [comment]
Sure.

I've added an image to queue. Look to the green overlay over gears icon at queue tab.
![rt-pause](https://user-images.githubusercontent.com/1320579/35196214-c3b7357e-ff01-11e7-9034-74100979ad56.png)

When I start a queue the overlay is changed to red one.
![rt-play](https://user-images.githubusercontent.com/1320579/35196213-c38ff928-ff01-11e7-9141-703f4f9d3fec.png)

In previous version overlays were red when queue was stopped and green when started.

PS: Also I'm not sure if red and blue colors are correct in widget itself. But may be this is different issue with TooWaBlue theme.

**Comment by Beep6581** [comment]
@Kildor opened issue #4316

**Comment by Kildor** [comment]
@Beep6581 but what's about wrong overlay? Should I open a new issue?
They are correct on your screencast, but not on my screenshots.

**Comment by Floessie** [comment]
@Beep6581 
>@Floessie the switch is localized. #4278 was supposed to make the switch use the same language as RT is set to use.

Yes, I saw it and thought: "Maybe it's not yet part of `histogram-matching`." Now I've updated `dev` and still it shows up in my system language and not "English (US)", that I've set. Strange...

**Comment by Beep6581** [comment]
@Kildor that's why I opened that other issue.

@Floessie best to open a new issue for that, and to see how other widgets which include labels behave.

**Comment by Floessie** [comment]
@Beep6581 Done: #4319
