### ISSUE TITLE
Toolbar menus icon overlap each other

### ISSUE THREAD

**Issue by paulinster** [Beep6581/RawTherapee#4060]
Hi Look like the toolbar in filebrowser as well as in editor is doesn' scale very well within macosx retina display. The icon overlap the path field editor. This make the toolbar almost useless

<img width="1069" alt="screen shot 2017-09-05 at 9 52 08 pm" src="https://user-images.githubusercontent.com/10835813/30091020-1f6d9726-9285-11e7-88fd-877ed1499442.png">
<img width="1599" alt="screen shot 2017-09-05 at 9 51 49 pm" src="https://user-images.githubusercontent.com/10835813/30091021-1f6eb66a-9285-11e7-9fe3-ba03816801a3.png">

Also when going into the preferences/settings menu the screen is so large that I can't view/click ok button. The window can't be resize. 

Operating system: MacOS Sierra 10.12.6
Rawtherapee version:  5.2.61-g6e03141c

**Comment by Beep6581** [comment]
Duplicate #4035
