### ISSUE TITLE
White balance setting not applied on initial load

### ISSUE THREAD

**Issue by dgrasberger** [Beep6581/RawTherapee#4063]
Summary:
When generating thumbnails from RAW (Sony) files RT hasn't seen before, it doesn't apply the settings from default profile, but the RT default "camera" white balance instead.

version info:
Branch: default
Version: 4.2.0
Changeset: c81d9026d25c
Compiler: x86_64-linux-gnu-gcc 5.2.1
Processor: undefined
System: Linux
Bit depth: 64 bits
Gtkmm: V2.24.4
Build type: Release
Build flags: -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -std=c++11 -D_FORTIFY_SOURCE=2   -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG
Link flags:  -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed
OpenMP support: ON
MMAP support: ON

System info:
Xubuntu 16.04.3 LTS
4x Core i5-2400S @ 2.50G
16324MB

Steps:
- Create profile with auto as white balance choice
- Make the profile default for raw photos in RT settings:image processing
- Open an image (sony raw) in editor, everything's as it should be
- Copy some new images from SD card to a new directory
- Go to new directory in RT file browser
- Wait for thumbnails to be generated

Error: Thumbnails are generated with "Camera" white balance method rather than "Auto"

Note: after loading any file in editor, its thumbnail is updated with correct processing.

If you are filing a bug report, please first read the guide How to Write Useful Bug Reports:
http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports
You must provide the required information in order for your bug report to be valid.
Delete this text before posting.

**Comment by heckflosse** [comment]
That's not a bug. When opening a folder with `new` images, RT shows the embedded jpg file as thumbnail without any processing.

**Comment by Beep6581** [comment]
> If you are filing a bug report, please first read the guide How to Write Useful Bug Reports:
http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports

> Make sure you use the latest version of RawTherapee as it's likely that a bug in an old version has been fixed in the latest one.

> Version: 4.2.0

Confirmed that this works correctly in dev.

http://rawpedia.rawtherapee.com/The_File_Browser_Tab
