### ISSUE TITLE
Fedora repo is no longer available

### ISSUE THREAD

**Issue by eduperez** [Beep6581/RawTherapee#4064]
The Fedora repo linked in the "downloads" page (http://download.opensuse.org/repositories/home:rawtherapee/Fedora_26/home:rawtherapee.repo) no longer exists (in fact, all the "home:rawtherapee" folder has vanished).

**Comment by Beep6581** [comment]
Thanks for reporting. It's a problem on OBS side:
https://twitter.com/openSUSE/status/905530011540746250
