### ISSUE TITLE
Move working/output profile histogram choice from preferences to alongside the histogram

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4066]
Even though there is a Color Management tab in Preferences, the choice of which profile the main histogram should reflect - working or output - is in the General tab in Preferences. This issue is a request to move it out of Preferences alongside the other buttons next to the main histogram.

**Comment by okoncevoy** [comment]
Hey. I have forked repository and would like to solve that issue, this could be great starting point in helping RT.

**Comment by okoncevoy** [comment]
And how should this switching looks like? A small icon near clipping icons?

**Comment by Beep6581** [comment]
Initially I wanted it to be alongside the [main histogram](http://rawpedia.rawtherapee.com/The_Image_Editor_Tab#Main_Histogram), but because it does more than it says #4067 I think the best place would be in the top toolbar, maybe next to the "Before/After view" button.
Either somewhere round here
https://github.com/Beep6581/RawTherapee/blob/dev/rtgui/editorpanel.cc#L597
or here
https://github.com/Beep6581/RawTherapee/blob/dev/rtgui/toolbar.cc#L32

I made a patch to split the bottom toolbar and the same was going to be done for the top toolbar in #4035 which @Hombre57 took over, so you may want to ping him.

**Comment by okoncevoy** [comment]
Thank you for the detailed answer. Definitely I  will contact @Hombre57

**Comment by Hombre57** [comment]
@Beep6581 I'm afraid that my try of creating a Gtk::Container to handle this flowing toolbar will remain unfruitful. Feel free to resume your work and commit if it's working fine.

**Comment by Hombre57** [comment]
@lvreclp @Beep6581 Given issue #4067, the best place for this icon should be next to the HL/Shadows clipping indicator icons, separated by a vertical separator.

**Comment by Beep6581** [comment]
@lvreclp I can help you with the icon for the toggle button, will look into that once there's a patch.

**Comment by okoncevoy** [comment]
@Beep6581 Do you have any guide lines to coding style? So I am putting this icon next to SH/HL clipping toggles?

**Comment by Floessie** [comment]
@lvreclp 
> Do you have any guide lines to coding style?

No, we don't. Just adapt to the code surrounding your code and stick to the [OTBS](https://en.wikipedia.org/wiki/Indentation_style#Variant:_1TBS_.28OTBS.29).

Best,
Flössie

**Comment by Beep6581** [comment]
> So I am putting this icon next to SH/HL clipping toggles?

Yes, it will fit there well.

**Comment by okoncevoy** [comment]
Here is a WIP that I did for now. I have one more question. Do I need to update hist on the fly? So when user toggles button, histogram should be updated according to current profile?
[histogram.txt](https://github.com/Beep6581/RawTherapee/files/1491388/histogram.txt)

**Comment by Beep6581** [comment]
That would certainly be good!

**Comment by okoncevoy** [comment]
Well, I almost finished with initial implementation. I still can get how to update histogram on the fly. @Beep6581 can I get icon for this feature and where I must put it?
[patch.txt](https://github.com/Beep6581/RawTherapee/files/1491853/patch.txt)

**Comment by Beep6581** [comment]
@lvreclp I will try to get one for you tomorrow. Till then, any ideas for the icon are welcome.

**Comment by Hombre57** [comment]
@lvreclp I have some comments about your proposed patch, I hope you don't mind some constructive ones :

1. when I said "next to the HL/SH clip butons", I was rather expecting to add then to put it in EditorPanel directly, but this is a detail I was a bit unclear on this
2. you don't need to block the button's connection when reading the state of this button. It is only necessary when changing the toggle on/off state with `set_active`, it will prevent throwing unwanted event.
3. ... and that's why you don't have to block `connHistogramProfile` in `IndicateClippedPanel::buttonToggled`, this button is not set in this function
4. options is updated in numerous place in RT, we only save it when closing RT, even though the change would be lost in case of crash, but that's an uncommon case. So I'd remove the `options.save()` line in `IndicateClippedPanel::toggleHistograProfile` and only keep `options.rtSettings.HistogramWorking = chngHistOutput->get_active();`
5. I don't know if it's a typo, but we're not constrained by memory usage for the code, and would then prefer having clearly understandable parameter and function name (even though some of our dev doesn't stick to this rule). So we should use `toggleHistogramProfile` instead of `toggleHistograProfile` (`m` was missing)
6. in `indclippedpanel.h`, we always set a parameter name, even though the compiler doesn't need it. It helps to understand the purpose of the parameter (somewhat) at first sight w/o looking at the code itself. However ...
7. `sigc::bind` on line 78, 79, 80 is used to add  parameter to the called function, that doesn't need one otherwise. This is necessary because a single event handler is used to handle event from different button, that's why we bind the caller to the event. But `toggleHistogramProfile` is only used to handle toggle event for a single button, so we don't need to bind the object to the event, and the function doesn't need a parameter.
8. line 1004 of `preferences.cc` (before patch) shouldn't be removed, as it remove another checkbox too, but rather updated to :
```c++
    workflowGrid->attach_next_to (*ckbShowFilmStripToolBar, *ckbHistogramPositionLeft, Gtk::POS_RIGHT, 2, 2);
```
9. `ckbHistogramWorking` is not necessary anymore and should be removed from `preferences.h`

See the linked patch (it's yours with my modifications).

As to how to update the preview, I have to dig in the code a little bit.

[HistogramButton2.txt](https://github.com/Beep6581/RawTherapee/files/1492942/HistogramButton2.txt)

**Comment by okoncevoy** [comment]
@Hombre57 
Thanks for the review. I will modify changes according to the comments. 
* 1- I will move it to EditorPanel. Should it be put in imageAreaPanel or directly in EditorPanel as separate item? For now I can see, that there is several places. 
* 2- I have removed those blocks in other implementation. This is a first time for me using GTK at all and for now I am not very comfort in this environment. 
About 4, I have tested for this setting (options.rtSettings.HistogramWorking) but is not persistent. It gets dropped to 0 on restart, might be, that I have left some code somewhere, I will check that. In any case, this leads for this setting not to persist. 
* 5 - Is a typo. 
* 6 - Is a habit from my work and personal projects, where warnings are errors. Try to stick with your guidelines.

**Comment by Beep6581** [comment]
@lvreclp good work. One more comment: it would be best if you worked on this in your own branch. That makes following progress and relating comments to specific lines easier.

**Comment by okoncevoy** [comment]
@Beep6581 Maybe there is some contribution guide, that describes, what is the workflow for working on issue (forking whole repo, branching)?

**Comment by Beep6581** [comment]
@lvreclp only this: https://github.com/Beep6581/RawTherapee/blob/dev/CONTRIBUTING.md

**Comment by okoncevoy** [comment]
How can I push my branch?

**Comment by agriggio** [comment]
Hi @lvreclp,
I think the best way is to fork rawtherapee (in github), push to your fork, and then create a pull request here. Thanks!

**Comment by okoncevoy** [comment]
Thanks @agriggio . I have created branch in my fork and pushed it to origin. But I still miss text for tooltip and an icon. Should I already create pull request so some one could review my code once more or should I wait?

**Comment by Beep6581** [comment]
Changes:
https://github.com/Beep6581/RawTherapee/compare/dev...lvreclp:dev-move-histogram-profile

I can help with the icon within a day or two, too flooded with work atm.

**Comment by okoncevoy** [comment]
Thank you.
Same for work load for me. So drop a message, as soon as there will be an icon.

**Comment by agriggio** [comment]
@lvreclp I think it's a good idea to create the PR already. You can continue working on your branch in the meantime

**Comment by Beep6581** [comment]
I checked out your changes:
```
git remote add lvreclp git@github.com:lvreclp/RawTherapee.git
git fetch lvreclp
git checkout -b lvreclp-move-histogram-profile lvreclp/dev-move-histogram-profile
```

Unfortunately, nothing happens when I click on the button.

Here are my icon suggestions. They are based on [this](https://github.com/Beep6581/RawTherapee/blob/edbe4f3f14ee4dcd21091e9800fdbcb96e38b271/tools/source_icons/scalable/gamut_srgb_prophoto_xy.svg) template showing a CIE XY color gamut of `RT_sRGB.icm` overlaying `RT_Medium_gsRGB.icc`.
https://filebin.net/5knxm58cw2qgkhrd
1. ![gamut-hist-1](https://user-images.githubusercontent.com/5844619/33285268-16271be2-d3b2-11e7-8496-f1f4c94a59d6.png)
2. ![gamut-hist-2](https://user-images.githubusercontent.com/5844619/33285269-168d829c-d3b2-11e7-8b60-27447cd2a207.png)
3. ![gamut-hist-3](https://user-images.githubusercontent.com/5844619/33285270-16b51cd0-d3b2-11e7-97b9-634e5e21a7db.png)

```diff
diff --git a/rtgui/editorpanel.cc b/rtgui/editorpanel.cc
index 855458b9..230dbc87 100644
--- a/rtgui/editorpanel.cc
+++ b/rtgui/editorpanel.cc
@@ -587,6 +587,8 @@ EditorPanel::EditorPanel (FilePanel* filePanel)
 
     // Histogram profile toggle controls
     toggleHistogramProfile = Gtk::manage (new Gtk::ToggleButton ());
+    Gtk::Image* histProfImg = Gtk::manage (new RTImage ("gamut-hist.png"));
+    toggleHistogramProfile->add (*histProfImg);
     toggleHistogramProfile->set_relief (Gtk::RELIEF_NONE);
     toggleHistogramProfile->set_active (options.rtSettings.HistogramWorking);
     toggleHistogramProfile->set_tooltip_markup ( (M ("PREFERENCES_HISTOGRAM_TOOLTIP")));
```

![imgur-2017_11_27-20 30 21](https://user-images.githubusercontent.com/5844619/33285357-5b500e22-d3b2-11e7-9765-f94957faf389.png)
![imgur-2017_11_27-20 31 22](https://user-images.githubusercontent.com/5844619/33285358-5b6caf1e-d3b2-11e7-9fee-211ca2114157.png)
![imgur-2017_11_27-20 31 46](https://user-images.githubusercontent.com/5844619/33285359-5b8de170-d3b2-11e7-98d7-96c95bd06dba.png)

I'll make a commit once we decide.

I vote for 3, 2, 1, in that order.

**Comment by agriggio** [comment]
@Beep6581  I find 3 confusing -- 2 (or 1) are much better IMHO

**Comment by okoncevoy** [comment]
@Beep6581 
I also like first icon much more, as for histogram update on the fly, I am still finding for a better way to do that. I will try to commit it today.

**Comment by Beep6581** [comment]
The first icon says nothing about colorspaces, it could mean anything.

It's best to vote not for one, but for all in the order of preference. If @agriggio voted 2 1 3, @lvreclp  voted 1 2 3 and I voted 3 2 1, then 2 has most votes so far.

**Comment by okoncevoy** [comment]
I still struggle with histogram update, I have found that HistogramPanel class have histogramChanged method, but it takes a lot of LUT's in parameters. Is there any other variant how to update histogram?

**Comment by Hombre57** [comment]
@lvreclp You should not update the historgram, but refresh the preview, which incidentally will update the histogram and navigator as well. When you hover the image, the values of the point under the cursor is shown below the histogram, and depends on the image saved at the end of the `Crop::update` method (from `rtengine/dcrop.cc`) -> see `Image8* finaltrue`, which is saved in `CropHandler::cropimgtrue`.

The softproofing button does update the preview, I think there's something to find in `EditorPanel::ColorManagementToolbar::updateSoftProofParameters` in `rtgui/editorpanel.cc`, look for `processor->beginUpdateParams ()` and `processor->endUpdateParams ()`.

**Comment by okoncevoy** [comment]
I have uploaded a new commit. Now a histogram is updated on the fly, might be that this is not the best method, but it works. Looking forward to hear result of review.

**Comment by Beep6581** [comment]
Here's the commit: https://github.com/lvreclp/RawTherapee/commits/dev-move-histogram-profile

**Comment by okoncevoy** [comment]
Pushed one more commit: https://github.com/lvreclp/RawTherapee/commits/dev-move-histogram-profile clean up for method.

**Comment by Hombre57** [comment]
@lvreclp @Beep6581 The patch works fine and is very acceptable. I'd vote for 2, 1, 3, so is even more the preferred choice. So the only thing to add before merging is that icon.

**Comment by Beep6581** [comment]
I pushed the button and images to branch `origin/histogram-profile` (naming git-fail :P)
@lvreclp feel free to merge that into your branch and open a pull request.

**Comment by Beep6581** [comment]
I pushed the button and images in commit 8c42504f in branch [histogram-profile](https://github.com/Beep6581/RawTherapee/tree/histogram-profile)

@lvreclp do you want to merge it into yours and open a pull request, or should I just merge into `dev`?

**Comment by okoncevoy** [comment]
@Beep6581 
I have merged histogram-profile into my fork, so I will create pull request soon.

**Comment by okoncevoy** [comment]
I just tried to test branch, and after building got this:
`terminate called after throwing an instance of 'Glib::FileError'`

**Comment by Beep6581** [comment]
@lvreclp please show a stack backtrace.

Have you verified that the new PNG images exist in your fork?
```
rtdata/images/Dark/actions/gamut-hist.png
rtdata/images/Light/actions/gamut-hist.png
```

**Comment by okoncevoy** [comment]
Now everything is fine. Forgot to run install, so yeah, RT just couldn't find images.

**Comment by okoncevoy** [comment]
@Beep6581 I have created pull request: https://github.com/Beep6581/RawTherapee/pull/4210

**Comment by Beep6581** [comment]
Needs to be documented - I'll do that when time permits.

**Comment by Hombre57** [comment]
@Beep6581 The patch has been merged, but the docs still has to be updated. Should this be closed ? Should it be marked as done in the [5.4 Milestone](https://github.com/Beep6581/RawTherapee/milestone/4) ?

**Comment by Beep6581** [comment]
@Hombre57 all issues which require documentation changes should stay open until the docs are updated.
Now that 5.4-rc1 is out and we are in feature-freeze, the docs can start being written/updated.

**Comment by Beep6581** [comment]
Time permits.

http://rawpedia.rawtherapee.com/The_Image_Editor_Tab#Main_Histogram
