### ISSUE TITLE
"Use working/output profile for main histogram and navigator" affects more than that

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4067]
The "Use working/output profile for main histogram and navigator" choice affects more than that, for example it also affects the clipped shadow/highlights indicators. What else does it affect?

**Comment by Beep6581** [comment]
Testing the clipping indicators more, I can only see a correlation between the level of grayness shown by the indicator and the actual clipped R G B values shown in the Navigator when "Use working/output profile for main histogram and navigator" is enabled. The level of grayness does not correlate to the values when that option is not ticked!

**Comment by Hombre57** [comment]
@Beep6581 See `tools/color_management.svg`

**Comment by Beep6581** [comment]
http://rawpedia.rawtherapee.com/The_Image_Editor_Tab#Main_Histogram
http://rawpedia.rawtherapee.com/Preferences#Clipping_Indication
