### ISSUE TITLE
Allow assigning rank and label without automatically applying default profile

### ISSUE THREAD

**Issue by eduperez** [Beep6581/RawTherapee#4069]
When I add a color label in the file browser to an unedited file, RT automatically applies the default profile to the image, and the thumbnail is updated accordingly.

I like to use the color labels before I start processing my images, and having a profile applied so soon goes against my workflow. I have seen I can clear the processing profile and the label is not deleted, thus this does not look like a technical issue.

I think assigning a color label should not apply a profile to the image.

**Comment by Hombre57** [comment]
This is a duplicate of #2857.
