### ISSUE TITLE
Histogram in tone curve 1 changes dramatically when modifying crop

### ISSUE THREAD

**Issue by midluk** [Beep6581/RawTherapee#4078]
When the crop of an image is changed (modification of crop region or enabling/disabling crop), the histogram in Tone curve 1 sometimes changes completely.

It seems as if the tone curve (if enabled) from a dcp input profile is not used for the tc1 histogram after a crop change.
If the image has been rotated (without auto fill), the black borders (peak in the histogram at zero) seems to affect histogram scaling during normal operation (likely not intended) but not directly after changing crop.

The histogram does not seem to be restricted to the crop region at all (which might be a separate issue or a design choice).

The histogram changes back to normal when something else changes the histogram (e.g. slider in exposure tool or Shadow/Highlights tool).
The histogram changes back to normal and stays this way when the crop is changed through a navigation in the history.

This is on Linux with 5.2-159-g05b97f5c from dev branch.

**Comment by Beep6581** [comment]
@midluk please test using the latest `dev` and provide sample files and steps to reproduce, then we can re-open this issue.
