### ISSUE TITLE
Searching for up to date version of Lensfun

### ISSUE THREAD

**Issue by gaaned92** [Beep6581/RawTherapee#4081]
@seebk 
System : windows 64
It seems that the version of Lensfun available on MSYS2 is rather old. It uses database version 1 xmp files.
Thus I cloned  Lensfun from sourceforge:
`git clone http://git.code.sf.net/p/lensfun/code lensfun`
and built  without problem the master branch. It comes with a data base version 2 more recent than the MSYS2 one.

MSYS2 Lensfun doesn't work with version 2 DB.

I have some questions:
1- Is the master branch the more up to date version with last corrections and the branch to build?
2- the two versions (MSYS2 and SourceForge) appears in the RT abouthisbuild.txt with the same 0.3.2.0. How the two versions can be distinguished?
3- On github, there is a lot of activity to update data.  Is it better to get the up to date  data base directely from github or to wait they are introduced in the sourceforge master branch? 

 As my knowledge on Lensfun is very limited , perhaps I misunderstood some points. Don't hesitate to correct me.
Thanks in advance for your answers and explanations.

**Comment by Beep6581** [comment]
Well the lensfun GitHub description is "This is NOT the official Lensfun repository but ONLY for the calibration team work!", sounds like it's turbulent and their official repo is stable, but best if you either ask one of the members directly on their GitHub page or at least @ tag them here:
https://github.com/lensfun/lensfun/graphs/contributors

**Comment by heckflosse** [comment]
@gaaned92 

> How the two versions can be distinguished?

I don't know how to distinguish them in AboutThisBuild.txt. but for `rawtherapee -v` we could use something like this:

```patch
$ git diff rtgui/main.cc
diff --git a/rtgui/main.cc b/rtgui/main.cc
index f5e134b5..dd981e6a 100644
--- a/rtgui/main.cc
+++ b/rtgui/main.cc
@@ -139,7 +139,7 @@ int processLineParams ( int argc, char **argv )
 #endif

                 case 'v':
-                    std::cout << "Using lensfun " << LF_VERSION_MAJOR << "." << LF_VERSION_MINOR << "." << LF_VERSION_MICRO << "." << LF_VERSION_BUGFIX << std::endl;
+                    std::cout << "Using lensfun " << LF_VERSION_MAJOR << "." << LF_VERSION_MINOR << "." << LF_VERSION_MICRO << "." << LF_VERSION_BUGFIX << " . Supported Database version <= " << LF_MAX_DATABASE_VERSION << std::endl;
                     return 0;

 #ifndef __APPLE__ // TODO agriggio - there seems to be already some "single instance app" support for OSX in rtwindow. Disabling it here until I understand how to merge the two

```

**Comment by heckflosse** [comment]
@Beep6581 

@gaaned92 wrote he cloned from sourceforge, not from github. Using master branch may be risky though.

Edit, sorry, missed 3- of his post

**Comment by seebk** [comment]
@gaaned92 

The latest release is 0.3.2 and is the recommended version to use. It is tagged with v0.3.2 in the Sourceforge master branch (all releases have an associated tag).

The Github repository is used to organize Torsten Brongers calibration service which is the reason why there is a lot of activity in the database files. These changes are regularly merged back into the Sourceforge master.

You can update a local database with the lensfun-update-data script (http://lensfun.sourceforge.net/manual/lensfun-update-data.html) or manually by downloading a backported database from http://lensfun.sourceforge.net/manual/lensfun-update-data.html

The current Sourceforge master branch received quite a lot of changes in the last year. Hence, I would not recommend to use it for a RT. We hope to release a new stable version with an updated database soon. But as we are a very small team I cannot give any time estimates, yet.

**Comment by gaaned92** [comment]
@seebk Thank you for clarification.
