### ISSUE TITLE
Fix some inconsistencies in Profiled Lens Correction gui

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#4082]
There are at least two inconsistencies in the gui:

1) when I select a lensfun profile AND a lcp profile to test them, the lcp profile is removed when I close the editor while `Auto match...` is enabled. But it's not removed when `LCP File` is enabled when closing the editor.

2) the lcp profile can be removed using the `x`-button behind the lcp file name while the lensfun profile can not be removed.

I would like to keep a selected lcp file and to remove the `x`-button behind the lcp file name because we can use `none` to disable lens correction.

First I thought that's a 10 minutes task, but then I saw the the logic in `lensprofile.cc` is quite complicated.
In gui we have 4 radiobuttons (`None`, `Auto`, `Manual` and `Lcp`). In procparams.h we have two booleans (`useLensfun` and `lfAutoMatch`) and a string (`lcpFile`) to represent the selected radio button.

In current gui code we have a [complicated logic](https://github.com/Beep6581/RawTherapee/blob/dev/rtgui/lensprofile.cc#L167) to set the correct radiobutton when a pp3 is read.

I would like to use an enum (with 4 states, `None`, `Auto`, `Manual`, `Lcp`) to represent the selected radiobutton. That would also allow to easily solve the two inconsistencies I mentioned above.

Any objections?

**Comment by agriggio** [comment]
@heckflosse I agree with your proposal. I implemented the engine part
before the GUI, and I did not refactor it as I should have...

**Comment by heckflosse** [comment]
@agriggio I will create a new branch for this and try to solve the issue at the weekend (maybe already tomorrow). Then we will have enough time to review it before 5.3 is released.

**Comment by heckflosse** [comment]
[New branch](https://github.com/Beep6581/RawTherapee/tree/lenscorrectiongui) created.

It seems to work well here. I added pp3 backwards compatibility for `5.2` but not for `5.2 + lensfun`. Means, you have to clear the processing profiles for files you opened with `5.2 + lensfun`.

As my coding style is not the best, I would appreciate reviews from @agriggio and @Floessie ;-)

Please test. Let me know if creating a pr from the branch will help review.

**Comment by agriggio** [comment]
:+1:, I'll have a look over the weekend

**Comment by agriggio** [comment]
I've added a couple of comments via github. I haven't tested, but it looks good to me! :+1: for merging

**Comment by heckflosse** [comment]
I made the changes suggested by @agriggio and merged.
