### ISSUE TITLE
RT dynamic profile is not used when opening a photo with a cleared profile

### ISSUE THREAD

**Issue by olhof** [Beep6581/RawTherapee#4087]
Default Processing Profile (Dynamic) is not used when opening a raw photo with a profile cleared by the file browsers processing file operation (clear).  The dynamic profile is apparently only applied when the pp3-file does not exist.

PC-info:
Windows 10

RT info:
Version: 5.2
Branch: release-5.2
Commit: 78e921cb
Commit date: 2017-07-23
Compiler: gcc 6.3.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.22.0

**Comment by agriggio** [comment]
that's the expected behaviour

**Comment by heckflosse** [comment]
@olhof 
>Default Processing Profile (Dynamic) is not used when opening a raw photo with a profile cleared by the file browsers processing file operation (clear). The dynamic profile is apparently only applied when the pp3-file does not exist.

Works fine here
1) I deleted the pp3 in windows explorer
2) opened the raw in rt => dynamic profile applied
3) closed the raw
4) in file browser I cleared the processing profile of the raw
5) opened the raw => dynamic profile applied

```
Version: 5.2-173-g14378f39
Branch: dev
Commit: 14378f39
Commit date: 2017-09-16
Compiler: gcc 7.2.0
Processor: undefined
System: Windows
Bit depth: 64 bits
Gtkmm: V3.22.0
Lensfun: V0.3.2.0
Build type: Release
Build flags:  -std=c++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -O3 -DNDEBUG
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON
```

**Comment by agriggio** [comment]
if you have rated the picture, "clear" doesn't delete the pp3. that might be the reason. but again, this is expected behaviour. if you want to reapply, just use "reset to default"

**Comment by olhof** [comment]
Hi' Guys
I misunderstood the meaning of the big green checkmark on the thumbnail. I thought it meant that no profile was present.

If you clear the profile the green checkmark will disappear but a profile does still exist, so when you open the photo in the editor the dynamic profile will not be used. Which profile is then used? It is not the dynamic profile! Can anyone explain this to me?

If you choose “reset to default” in the File Browser then the correct dynamic profile is reflected in the thumbnail and used when you open the photo.
