### ISSUE TITLE
Errors with exiv2-0.26

### ISSUE THREAD

**Issue by StefanGyuzelev** [Beep6581/RawTherapee#4089]
When reading Exif data with libexiv2.so.26.0.0 , the following errors occur:
Error: Offset of directory PentaxDng, entry 0x0200 is out of bounds: Offset = 0x000087b0; truncating the entry
Error: Offset of directory PentaxDng, entry 0x0201 is out of bounds: Offset = 0x000087b8; truncating the entry
Error: Offset of directory PentaxDng, entry 0x0205 is out of bounds: Offset = 0x0000ad36; truncating the entry
Error: Offset of directory PentaxDng, entry 0x0207 is out of bounds: Offset = 0x0000ad5e; truncating the entry
Error: Offset of directory PentaxDng, entry 0x0208 is out of bounds: Offset = 0x0000adde; truncating the entry
Error: Offset of directory PentaxDng, entry 0x0209 is out of bounds: Offset = 0x000087c0; truncating the entry
Error: Offset of directory PentaxDng, entry 0x020a is out of bounds: Offset = 0x00009792; truncating the entry
Error: Offset of directory PentaxDng, entry 0x020b is out of bounds: Offset = 0x00009cd8; truncating the entry
Error: Offset of directory PentaxDng, entry 0x0215 is out of bounds: Offset = 0x0000ae02; truncating the entry
Error: Offset of directory PentaxDng, entry 0x0216 is out of bounds: Offset = 0x0000ae16; truncating the entry
Error: Offset of directory PentaxDng, entry 0x021f is out of bounds: Offset = 0x0000a21e; truncating the entry
Error: Offset of directory PentaxDng, entry 0x0222 is out of bounds: Offset = 0x0000aa1e; truncating the entry
Error: Offset of directory PentaxDng, entry 0x03ff is out of bounds: Offset = 0x0000aa30; truncating the entry

Settings for Metadata in Rawtherapee do not affect this problem.
Almost errors gives Geeqie and if read exif data follows Segmentation fault.

Another example:
exiv2 IMGP2192.jpg
It gives the same errors.

File example:
https://drive.google.com/file/d/0Bwd1yqYI35MoMlp0X3hYVDZERFE/view?usp=sharing

**Comment by Beep6581** [comment]
Should be fixed when #3801 is done.
