### ISSUE TITLE
No Preview for Wavelets and Lack of Changes in German Versions 5.0 to 5.2, Windows 8.1

### ISSUE THREAD

**Issue by jliw** [Beep6581/RawTherapee#4090]
Hello, 
please, have in mind what is written in the headline. After trying out the three versions I now send you screenshots of version 5.2 with same input as Morgan Hardwood did with a working version in https://discuss.pixls.us/t/enhancing-local-vs-global-contrast-rt-wavelets/5073/18 - 19/23.

Version: 5.2
Branch: release-5.2
Commit: 78e921cb
Commit date: 2017-07-23
Compiler: gcc 6.3.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.22.0
Build type: release
Build flags: -mwin32 -m64 -mthreads -msse2 -std=c++11 -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -mwindows -Wno-aggressive-loop-optimizations -DNDEBUG -O3
Link flags: -m64 -mthreads -static-libgcc -mtune=generic -mwindows -s -O3
OpenMP support: ON
MMAP support: ON

Data of my computer:
 
![grafik](https://user-images.githubusercontent.com/32042448/30524445-2d343806-9bf4-11e7-879b-6b7cc26fa6db.png)

Downloaded here:
http://rawtherapee.com/downloads

At first, it  is not possible to change the language of RT – it stays German; even downloading via USA did not help –  I always reach your Website mentioned above…

 -> Wavelets: after loading an arbitrary raw-image and setting and changing to 
![grafik](https://user-images.githubusercontent.com/32042448/30524454-5f40c8f0-9bf4-11e7-8cf3-eab8c5e2eb16.png)
  there is no change.

No change either when settings are put this way: 
![grafik](https://user-images.githubusercontent.com/32042448/30524458-67a86b92-9bf4-11e7-86f4-58aa40455355.png)

  I do know why „preview“ is translated to „Verarbeitung“ what means „processing“.

The first screenshot in my dropbox https://www.dropbox.com/sh/5vdbd2wdy24cspj/AABmRD2Y59NM1n_c00nc1PxOa?dl=0, (not https://imgur.com/a/Bds0j , what a joke) should show the residual image; the second some wavelets on gray – they do not. 

The third does not show sharpened edges as an example for not working of that program part – Verarbeitung to „All levels and directions“.
+: ![grafik](https://user-images.githubusercontent.com/32042448/30524465-8cdcd8c6-9bf4-11e7-8329-077fa54836c0.png)

  
I never did change anything else than shown.

Since I preferred to work with an English version of 5.2 (as I do with m PS CS6) I’d enjoy most if you sent me one. As written above I cannot download it by myself.

Otherwise many German users would like functioning wavelets, I guess.

Thank you in advance
Joerg Linnewedel, Hamburg
liw@gmx.eu

PS. Hope you can see my in-pasted jpgs, I cannot though I followed the instruction below.

**Comment by jliw** [comment]
![grafik](https://user-images.githubusercontent.com/32042448/30524539-ea99bc58-9bf5-11e7-8e1a-7c25b6dba10c.png)

**Comment by heckflosse** [comment]
@jliw Please provide screen shots which don't hurt our eyes...

**Comment by jliw** [comment]
With better jpgs now:
Hello, 
please, have in mind what is written in the headline. After trying out the three versions I now send you screenshots of version 5.2 with same input as Morgan Hardwood did with a working version in https://discuss.pixls.us/t/enhancing-local-vs-global-contrast-rt-wavelets/5073/18 - 19/23.

Version: 5.2
Branch: release-5.2
Commit: 78e921cb
Commit date: 2017-07-23
Compiler: gcc 6.3.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.22.0
Build type: release
Build flags: -mwin32 -m64 -mthreads -msse2 -std=c++11 -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -mwindows -Wno-aggressive-loop-optimizations -DNDEBUG -O3
Link flags: -m64 -mthreads -static-libgcc -mtune=generic -mwindows -s -O3
OpenMP support: ON
MMAP support: ON

Data of my computer:
![grafik](https://user-images.githubusercontent.com/32042448/30524546-4e3a46a6-9bf6-11e7-91ba-61e1f89d99f8.png)

Downloaded here:
http://rawtherapee.com/downloads

At first, it  is not possible to change the language of RT – it stays German; even downloading via USA did not help –  I always reach your Website mentioned above…

-> Wavelets: after loading an arbitrary raw-image and setting and changing to
![grafik](https://user-images.githubusercontent.com/32042448/30524565-af407ae2-9bf6-11e7-819a-49b37954a1cd.png)
there is no change.

No change either when settings are put this way: 
![grafik](https://user-images.githubusercontent.com/32042448/30524576-e60b8120-9bf6-11e7-8cda-2a532e73d25e.png)

I do know why „preview“ is translated to „Verarbeitung“ what means „processing“.

The first screenshot on https://www.dropbox.com/sh/5vdbd2wdy24cspj/AABmRD2Y59NM1n_c00nc1PxOa?dl=0, (not https://imgur.com/a/Bds0j , what a joke) should show the residual image; the second some wavelats on gray – they do not. 

The third does not show sharpened edges as an example for not working of that program part – Verarbeitung to „All levels and directions“.
+: ![grafik](https://user-images.githubusercontent.com/32042448/30524590-21ec6ac4-9bf7-11e7-8a82-5a76df3160eb.png)

I never did change anything else than shown.

Since I preferred to work with an English version of 5.2 (as I do with m PS CS6) I’d enjoy most if you sent me one. As written above I cannot download it by myself.

Otherwise many German users would like functioning wavelets, I guess.

Thank you in advance
Joerg Linnewedel, Hamburg

**Comment by heckflosse** [comment]
![rtlang](https://user-images.githubusercontent.com/13733487/30524638-e7692198-9bf7-11e7-83f8-4cc45bee2d20.png)

**Comment by Beep6581** [comment]
@jliw 

* Your screenshots are not readable. Use full-color PNG or JPG, don't use GIF.
* > At first, it is not possible to change the language of RT – it stays German; even downloading via USA did not help – I always reach your Website mentioned above

    What does "downloading via USA" mean?
    If you mean you want to change RT to English, then you do so via Preferences and restart RT for the change to take effect:
![imgur-2017_09_17-22 27 59](https://user-images.githubusercontent.com/5844619/30524622-b1ab4aea-9bf7-11e7-8a06-002127abdfca.png)

* > Wavelets (...) there is no change

    Did you enable Wavelets? Can't tell from your broken screenshots.
* > I do know why „preview“ is translated to „Verarbeitung“ what means „processing“.

    It's not "preview", it is "Process", so the translation is correct.
    If you want to help keep the translation updated, https://discuss.pixls.us/t/localization-how-to-translate-rawtherapee-and-rawpedia/2594
* > (not https://imgur.com/a/Bds0j , what a joke)

    What's the joke?

**Comment by Beep6581** [comment]
The better screenshots show that the Wavelets tool is not enabled.
http://rawpedia.rawtherapee.com/Getting_Started
http://rawpedia.rawtherapee.com/General_Comments_About_Some_Toolbox_Widgets

Closing, invalid report.

**Comment by Beep6581** [comment]
P.S. The screenshots show a problem in your RawTherapee theme. To fix it, go to Preferences and change the theme to anything else, then restart RT.

**Comment by jliw** [comment]
@Beep6581: Thank  you for the link and for your advice concerning the theme (hope I will find out what this is).
@heckflosse : Could not change the language because in none of the three versions a drop-down menue appeared.

**Comment by heckflosse** [comment]
@jliw 
>Could not change the language because in none of the three versions a drop-down menue appeared.

please post a screenshot

**Comment by jliw** [comment]
@heckflosse:
![grafik](https://user-images.githubusercontent.com/32042448/30524814-002faa64-9bfb-11e7-9c25-57be1ad126d1.png)

No menue dropping down next to "Deutsch".

**Comment by heckflosse** [comment]
@jliw Deaktiviere `Systemsprache verwenden`

**Comment by jliw** [comment]
@heckflosse: Dankeschön, prima Hinweis! Gute Nacht! (Ich zumindest gehe jetzt zu Bett.)

**Comment by jliw** [comment]
@heckflosse and @Beep6581:

Sorry I wasted your time last Sunday. In negligent way I read your introduction and did not notice at least one important point. Since actively regretting I wrote the lines below. To me they seem to be good advice for special beginners in RT. If you agree, you can upload the text on Rawpedia after I will have put the right symbols (small jpgs) where now are „S“s. If you propose corrections or improvements, make them easily visible, please.

Enjoy the weekend and kind regards
Joerg

**Some Tips for Users of Lightroom and Camera Raw**

A. Good features you do not find in LR or ACR: At least RL Deconvolution for sharpening and Wavelets for different purposes. (RL Deconvolution you find in S , sharpening, drop-down menue, http://rawpedia.pixls.us/Sharpening#RL_Deconvolution , RL Deconvolution; for Wavelets see S.)

B. What you should Know before Starting
1. Sometimes you have to switch on (S --> S), sometimes not (S). When there is a S left of the headline, klick on it to activate S. Otherwise no effects will occur.
2. First klicking on a headline with hidden drop-down menue lets it appear, second lets it vanish again. 
   Right-klicking opens and all yet open drop-down menues become hidden.
3. For activating curves S klick on the triangle right of the line. The appearing drop-down menue gives four alternatives: 
S  : no changes; S : ususal custom curve with dots; S: changement with sliders; S: improved curve (nice!) (see http://rawpedia.pixls.us/General_Comments_About_Some_Toolbox_Widgets#Tools, 4.2.2 Tone Curves/ Control Cage)
4. The threshold tool see http://rawpedia.pixls.us/Sharpening#RL_Deconvolution , Threshold.
5. S Before- after – open lock S: On left you see the picture before your last change, always the last step but one. Closed lock: When you click on the open lock symbol, S appears, closed lock. The picture on the left stays at it is, indepently of further changes. (Until you unlock again.) 

I guess this is enough for trying out RT a bit. If not - and to get information about the good features of RT: http://rawpedia.rawtherapee.com/Getting_Started and links from there.

**Comment by Beep6581** [comment]
@jliw your points 1-3 are all already explained in the third paragraph:
http://rawpedia.rawtherapee.com/Getting_Started#Edit_your_first_image
