### ISSUE TITLE
Bug in lens correction gui when using history

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#4098]
I just found a bug in lens correction gui

to reproduce

1) open [this file](https://filebin.net/ylvjzwoxygng2f9p)
2) go to lens correction and select `Auto-matched correction parameters` => vignetting and distortion checkbuttons are sensitive now, good
3) go back in history to `Photo loaded` =>vignetting and distortion checkbuttons are not sensitive now, good
4) go forwards in History to `Lens correction` =>vignetting and distortion checkbuttons are not sensitive now, though they should be

**Comment by TooWaBoo** [comment]
Confirmed

**Comment by heckflosse** [comment]
I take this one

**Comment by heckflosse** [comment]
Found another one

to reproduce

1) open the file from first post
2) select a lcp file
3) set lens correction to none
4) close editor
5) open the file again => vignetting and distortion checkbuttons are sensitive now, though they should not be
