### ISSUE TITLE
Applying Auto white balance to large files in file browser leads to wrong results

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#4108]
To reproduce:

1) download the iiq file from [here](http://www.imaging-resource.com/PRODS/phase-one-xf-100mp/XF100FAR200050.IIQ.HTM)
2) Don't open it in rt editor
3) Apply auto white balance in file browser (batch edit) to the file

result:
![wb_wrong](https://user-images.githubusercontent.com/13733487/30875743-c8c53c6e-a2f4-11e7-8972-c0dc7eb15ee8.png)

4) Apply the attached patch
5) start rt
6) clear processing profile and Clear from Cache - full for the iiq file
7) Apply auto white balance in file browser (batch edit) to the file

result:
![wb_correct](https://user-images.githubusercontent.com/13733487/30875924-3ed68ba6-a2f5-11e7-8fb8-062d9f0850bc.png)

```patch
diff --git a/rtengine/rtthumbnail.cc b/rtengine/rtthumbnail.cc
index 065d4640..ea0fd9f1 100644
--- a/rtengine/rtthumbnail.cc
+++ b/rtengine/rtthumbnail.cc
@@ -714,9 +714,8 @@ Thumbnail* Thumbnail::loadFromRaw (const Glib::ustring& fname, RawMetaDataLocati
     double avg_r = 0;
     double avg_g = 0;
     double avg_b = 0;
-    const float eps = 1e-5; //tolerance to avoid dividing by zero
 
-    float rn = eps, gn = eps, bn = eps;
+    unsigned int rn = 0, gn = 0, bn = 0;
 
     for (int i = 32; i < height - 32; i++) {
         int start, end;
@@ -831,9 +830,9 @@ Thumbnail* Thumbnail::loadFromRaw (const Glib::ustring& fname, RawMetaDataLocati
         }
     }
 
-    double reds = avg_r / rn * tpp->camwbRed;
-    double greens = avg_g / gn * tpp->camwbGreen;
-    double blues = avg_b / bn * tpp->camwbBlue;
+    double reds = avg_r / std::max(rn, 1u) * tpp->camwbRed;
+    double greens = avg_g / std::max(gn, 1u) * tpp->camwbGreen;
+    double blues = avg_b / std::max(bn, 1u) * tpp->camwbBlue;
 
     tpp->redAWBMul   = ri->get_rgb_cam (0, 0) * reds + ri->get_rgb_cam (0, 1) * greens + ri->get_rgb_cam (0, 2) * blues;
     tpp->greenAWBMul = ri->get_rgb_cam (1, 0) * reds + ri->get_rgb_cam (1, 1) * greens + ri->get_rgb_cam (1, 2) * blues;

```

**Comment by Beep6581** [comment]
Works fine here on my normal test files.

**Comment by heckflosse** [comment]
Short explanation about the reason for this bug:

Try this code:

```
float n = 0;
for (int i= 0; i< 100000000; ++i)
  n++
std::cout << n << std::endl;
```

Which output do you expect?

**Comment by Floessie** [comment]
@heckflosse Okay, I take the challenge: To store `100000000` one needs at least 27 bits, but a `float` only has a mantissa of 23 bits, thus `100000000` cannot be exactly represented. 😃

**Comment by agriggio** [comment]
I think it's rather the intermediate computations that lose precision, 100000000 should still fit in a float precisely. but I could be wrong, I'm going by hand and floats are tricky :-)

**Comment by heckflosse** [comment]
The result is `16777216` because `16777216.f == 16777216.f + 1.f` is true

**Comment by Floessie** [comment]
So one should not count higher than 2^mantissa_bits with floating point numbers. Good to know. 👍
