### ISSUE TITLE
Some lenses in the Lensfun combo cause markup warnings

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4111]
Select the very first lens profile: `AEE SD19 & Compatibles`
The console shows:
```
(rawtherapee:2160): Gtk-WARNING **: Failed to set text from markup due to error parsing markup: Error on line 1: Entity did not end with a semicolon; most likely you used an ampersand character without intending to start an entity - escape ampersand as &amp;
```

**Comment by agriggio** [comment]
hmmm, we should probably escape the strings. sorry, I had no idea that markup was active by default...

**Comment by Beep6581** [comment]
@agriggio we're on IRC right now

**Comment by heckflosse** [comment]
hmm, the text is set correctly nevertheless

**Comment by agriggio** [comment]
sorry, I'm away from home (with only a phone) until sunday evening...

**Comment by heckflosse** [comment]
I don't see that as an urgent issue, because the text is set correctly and it's just a warning in console.
So from my side, no need to hurry

**Comment by Beep6581** [comment]
Yeah, enjoy your weekend :]

**Comment by Floessie** [comment]
@Beep6581 @agriggio Markup isn't active in `lensfunCameras`, but in the history panel. Here's a patch:

```patch
diff --git a/rtgui/history.cc b/rtgui/history.cc
index 72c61b67..f16111d6 100644
--- a/rtgui/history.cc
+++ b/rtgui/history.cc
@@ -265,7 +265,7 @@ void History::procParamsChanged (ProcParams* params, ProcEvent ev, Glib::ustring
         Gtk::TreeModel::Row newrow = *(historyModel->append());
         newrow[historyColumns.realText] = eventDescrArray[ev];
         newrow[historyColumns.text] = text;
-        newrow[historyColumns.value] = descr;
+        newrow[historyColumns.value] = g_markup_escape_text(descr.c_str(), -1);
         newrow[historyColumns.chev] = ev;
         newrow[historyColumns.params] = *params;
         newrow[historyColumns.paramsEdited] = paramsEdited ? *paramsEdited : defParamsEdited;
@@ -284,7 +284,7 @@ void History::procParamsChanged (ProcParams* params, ProcEvent ev, Glib::ustring
     else {
         row[historyColumns.realText] = eventDescrArray[ev];
         row[historyColumns.text] = text;
-        row[historyColumns.value] = descr;
+        row[historyColumns.value] = g_markup_escape_text(descr.c_str(), -1);
         row[historyColumns.chev] = ev;
         row[historyColumns.params] = *params;
         row[historyColumns.paramsEdited] = paramsEdited ? *paramsEdited : defParamsEdited;
```

Don't know if it's too late for 5.3, but maybe you should consider including it.

HTH,
Flössie

**Comment by agriggio** [comment]
@Floessie great, thanks! :+1:

**Comment by agriggio** [comment]
go ahead and push for me, I'm away from my laptop...

**Comment by Floessie** [comment]
I'm not at my main machine, either.

@Beep6581 Please test and eventually push. Thanks!

**Comment by Beep6581** [comment]
I'll handle it. Compiling.

**Comment by Beep6581** [comment]
Fix confirmed. Committed into `release-5.3-rc1`, will be merged into dev after the release.

Are you aware that the warning icon is a bit large? I kinda like it though :)
https://i.imgur.com/uIzIpKP.jpg

**Comment by agriggio** [comment]
whoa that's huge :-) definitely not what I see here... I didn't actually specify the precise size, but just the usage intent. I guess it's up to the theme to decide what to use...
