### ISSUE TITLE
Need Windows and macOS builds of RT5.3

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4121]
Urgently need Windows and macOS builds!
@Benitoite @sguyader @gaaned92

**Comment by gaaned92** [comment]
Windows64 installer for 5.3 uploaded at [https://filebin.net/wvqymsj23h7kflvw](https://filebin.net/wvqymsj23h7kflvw)

Do you want a Windows32 Installer?(Vista and above)

**Comment by Beep6581** [comment]
Thank you @gaaned92 ! IIRC we dropped 32-bit support with 5.0, so just the 64-bit build is fine.

**Comment by sguyader** [comment]
I started to make a Windows build, but I left home before it was completed. If @gaaned92's build is fine, then you won't need mine.

**Comment by Beep6581** [comment]
By the way, I announced the release 4 hours ago, and already 517 people have read the announcement, and it's 2AM!

**Comment by Benitoite** [comment]
@Beep6581 Here is a build for MacOS 10.9 and up.
https://filebin.net/jgppw63dgag4p92s/RawTherapee_OSX_10.9_64_5.3.zip

**Comment by Beep6581** [comment]
Thank you!
