### ISSUE TITLE
Colors are off in exported jpeg

### ISSUE THREAD

**Issue by kertase** [Beep6581/RawTherapee#4122]
So I have noticed that colors in jpgs are totally off from what they should be. Exports to tiff and png are totally fine. 
Pictures are a lot less saturated when exported to jpg
Here is a screenshot of the issue:
https://imgur.com/a/QtbaY

Rawtherapee verison info:
```
Branch: releases
Commit: 78e921cb
Commit date: 2017-07-23
Compiler: cc 7.1.1
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.22.1
Build type: Release
Build flags: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -std=c++11  -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -O3 -DNDEBUG
Link flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
OpenMP support: ON
MMAP support: ON
```

**Comment by Beep6581** [comment]
http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports
Try to reproduce in the latest version (5.3) and if you think there is a problem then supply the raw + PP3 + JPG + TIFF + PNG. Double-check your color management settings.

**Comment by kertase** [comment]
Didn’t notice the new version sorry,

Still have the issue:
```
Version: 5.3
Branch: releases
Commit: ec0f7936
Commit date: 2017-09-30
Compiler: cc 7.2.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.22.1
Lensfun: V0.3.2.0
Build type: Release
Build flags: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -std=c++11  -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -O3 -DNDEBUG
Link flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
OpenMP support: ON
MMAP support: ON
```
Here are the test files:
https://filebin.net/0ibgp5qql5shkkyp

**Comment by Beep6581** [comment]
The JPG and PNG are identical, no problem there. The images in your imgur screenshot from the first post show that you're comparing RawTherapee's preview to a JPEG file. It's not clear whether that JPEG file was saved by RawTherapee or was an out-of-camera JPEG. Neither of the images on that screenshot are anything like the JPG, TIFF, PNG or PP3 you just sent, which is already a red flag that the user is doing something wrong. Furthermore, you're comparing two different image viewers - RT and the one on the right. As I wrote in the previous comment, check your color management settings.

**Comment by kertase** [comment]
Sorry for wasting your time seems like the jpgs are displayed wrongly in most apps when the pngs are displayed correctly… Must be something with the color management as you said. 

It seems to be because of the output profile being prophoto and that does not get displayed correctly in most programs for jpgs but it does get displayed correctly for tiff and png.

Thank you for your help.
