### ISSUE TITLE
Sort HALD CLUT directories in film simulation list

### ISSUE THREAD

**Issue by mzuther** [Beep6581/RawTherapee#4123]
Hi!

In the film simulation drop down list, the subdirectories of my HALD CLUT directory seem to be listed in arbitrary order. As I have moved and renamed them to create a logic order, it would be nice if they were sorted alphabetically, instead.

Current contents of drop down list:

* BW - Polaroid
* BW - Agfa
* Color - Polaroid
* Color - Fuji
* BW - Ilford

After the change:

* BW - Agfa
* BW - Ilford
* BW - Polaroid
* Color - Fuji
* Color - Polaroid

I'm running the RawTherapee unstable from the Ubuntu repository (5.2-git20170910-556~ubuntu16.04.1).

Thanks for listening! :)

Martin

**Comment by Beep6581** [comment]
Confirmed.

**Comment by mzuther** [comment]
Thanks! You're fast as ever... :)

**Comment by mzuther** [comment]
I can now confirm the fix. Thanks again!!!
