### ISSUE TITLE
[5.3] Blurry image

### ISSUE THREAD

**Issue by SaturnusDJ** [Beep6581/RawTherapee#4124]
A few hours ago I upgraded from 5.0 R something to 5.3 stable on Win 10 64-bit (Commit: ec0f7936).
I don't using scaling on my computer.

When having an image open to work on, it's blurry now. When I open the same image in any other application it's clearly visible RawTherapee is blurry. Saving the image also proves that the RT preview is blurry, not the source or due to the process.

In 5.0 R1 the image sometimes was way more blurry but a quick zoom in and then zoom out made it sharp again. In 5.3 I can not find anything to fix this.

I am going to downgrade soon and see where this stops.

**Comment by SaturnusDJ** [comment]
Problem disappeared after reinstall (plus installing 5.2, 5.1 and 5.0 in different folders, just saying).

**Comment by SaturnusDJ** [comment]
It's back.

![5 0_5 3](https://user-images.githubusercontent.com/14320018/31057671-1add2a8e-a6e7-11e7-9d43-2520dfaf82de.png)

Top 5.0 R1. Bottom 5.3.

Edit:
Might have found it. The whole photo becomes blurry after enabling Auto-matched correction parameters in Profiled Lens Correction. (Remember, output/export is not blurry. 1:1 not blurry either.)

**Comment by heckflosse** [comment]
@SaturnusDJ Please don't crop screenshots. They lack information which might be useful for us. For example, we can't see which zoom level was used.

**Comment by SaturnusDJ** [comment]
Both are on 25%.

**Comment by Beep6581** [comment]
See point 10 of the Advanced section:
http://rawpedia.rawtherapee.com/Getting_Started#Advanced

**Comment by SaturnusDJ** [comment]
Okay tnx. How about enabling instant render on high performance systems? (Thus an option.)
