### ISSUE TITLE
[5.3] Turn off window snapping + remember window position

### ISSUE THREAD

**Issue by SaturnusDJ** [Beep6581/RawTherapee#4125]
5.3 stable on Win 10 64-bit (Commit: ec0f793).

What I do is let RawTherapee fill my center monitor and then have the right panel with processing tools 'stick out onto my second monitor' so that the preview image takes as much space as it needs on the center monitor.
This window position is not being saved during sessions. When I restart there is space on the left and top of the RT window.

And when trying to use vertical maximization, RT overlaps the Windows taskbar. This window snapping feature was added between 5.0 R1 and 5.3 and I have to admit it work horrible. Suggesting a preference to disable it.

**Comment by TooWaBoo** [comment]
RT5.0 Gtk3.18 has used a nativ window. RT5.3 Gtk3.22 uses a none native window. This can't be changed 'cause it's Gtk related. Similar issues happens with other application which uses a none native window too.
RT doesn't have a window snapping feature, this is system related.

**Comment by SaturnusDJ** [comment]
It's outside the RT scope?

The snapping for sure isn't normal behaviour. Must be gtk then. Vertical snapping should not overlap the Windows taskbar.

**Comment by TooWaBoo** [comment]
The window has a shadow around the border which is also the resize handle part. The window is bigger as it looks like.

**Comment by SaturnusDJ** [comment]
Before:
![before](https://user-images.githubusercontent.com/14320018/31058721-a0654c5c-a6f8-11e7-8c32-538bc00cc77a.png)

After maximizing vertically:
![after](https://user-images.githubusercontent.com/14320018/31058725-a2f9ac42-a6f8-11e7-8eba-83ed1e1140da.png)

This time it drops below the task bar. Horizontal position even changes. Really not how it should be.

**Comment by TooWaBoo** [comment]
I know this behaviour when another application (e.g. Potplayer) with a non native window is running at the same time. It's a Gtk and/or Windows 10 issue.

**Comment by TooWaBoo** [comment]
New update GTK3.22.24 now supports native window in WIN10.

**Comment by Beep6581** [comment]
I added a note about this to the second paragraph http://rawpedia.rawtherapee.com/Windows

@gaaned92 @sguyader we should use this for new releases.

@TooWaBoo do you have a link with the source of that info?

**Comment by TooWaBoo** [comment]
No, I don't. I've updated MSYS and it updates GTK. After compiling I got the native window.

**Comment by Beep6581** [comment]
Duplicate of #4141
