### ISSUE TITLE
Flat field correction error

### ISSUE THREAD

**Issue by tmmidm** [Beep6581/RawTherapee#4132]
Hello.
There was the following problem in Rawtherapee 5.3 at application of correction of the flat field.
The initial picture is taken on DualIso technology by means of Magic Lantern.
After the standard (drag and drop to cr2hdr.exe) transformation of the cr2 file to the dng file by  cr2hdr utility, I open dng the file in Rawtherapee and I apply correction of the flat field.
Absolutely black field of a shot is result of it (all points in RGB = 0 0 0).
Before application of correction of the flat field everything is displayed normally.
If to convert cr2 in dng through cr2hdr with an additional option - compress (Loseless; Adobe DNG Converter is used), correction of the flat field issues strange result (excessively clarified edges of a shot).
If to convert dng file (without - compress) to dng file in Adobe DNG Converter and apply correction of the flat field, then result also strange (excessively clarified edges of a shot).

It is a mistake in Rawtherapee? 
Unfortunately, I cannot check correction of the flat field in other programs (for example Adobe LR).
I attach the link to archive with files.
https://drive.google.com/open?id=0B8RdSX_hjqTXZ2lzTnRyVjRXREk
DualIso_image.CR2 - the initial picture from the camera
FlatField.CR2 - the file for correction of the flat field
cr2hdr_default.DNG - result of standard transformation (drag and drop to cr2hdr.exe)
cr2hdr_Losseless compression with Adobe DNG Converter.DNG - cr2hdr with - compress option

System parameters:
Windows 7 64bit Professional
CPU: Pentium D 2x3.80GHz
RAML 4GB

**Comment by Floessie** [comment]
If I understand the [Flat-Field feature](http://rawpedia.rawtherapee.com/Flat_Field) right, input image and flat-field image must match aperture, focal length, and camera/lens combo, of course. I could imagine, the input format also matters, so the first question coming to my mind is: Have you tried to use a flat-field image taken with dual ISO and converted through `cr2hdr` in the same way you did with your input image?

**Comment by tmmidm** [comment]
Floessie, уеs, I tried to use a flat-field image taken with dual ISO (same settings as input picture) and converted through cr2hdr in the same way. 
Result also strange (excessively clarified edges of a shot). = The same as in situation: Input image converted cr2hdr with --compress and original cr2 file to flat field correction.

**Comment by tmmidm** [comment]
But if I use ce2hdr without --compress and dual Iso flat field dng image without --compress, Rawtherapee works good.
I will close issue.
How can I know what is wrong when dual iso input dng image use original cr2 file to flat field correction? Resolution of two image is the same. If I convert original cr2 flat field image to dng by Adobe converter and use it to flat field correction of dual iso input dng image, I get absolutly black field.

**Comment by Floessie** [comment]
I think the culprit with your input DNG is, that `black[4] = {8195, 8195, 8195, 8195}` [here](https://github.com/Beep6581/RawTherapee/blob/dev/rtengine/rawimagesource.cc#L2829), so that `refcolor[m][n] = {0, 0, ...}`.

**Comment by tmmidm** [comment]
Floessie, thanks for help. I will try to understand your ansver.
