### ISSUE TITLE
Info: GTK+ 3.22.24 now supports native windows in Win10

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#4141]
New update GTK3.22.24 now supports native windows in WIN10.

![unbenannt](https://user-images.githubusercontent.com/13800920/31490463-4b0b3c86-af44-11e7-8214-713896851b5b.PNG)

**Comment by Hombre57** [comment]
@TooWaBoo Do you suggest that we should require this version for Windows ?

**Comment by TooWaBoo** [comment]
@Hombre57 
Yes, I think this solves some issues witch we have with non native windows on WIN10. Everything works fine so far.

**Comment by gaaned92** [comment]
If needed I can rebuild 5.3

**Comment by ghost** [comment]
It works!!!
![screenshot 42](https://user-images.githubusercontent.com/29912986/31564277-e646cdc4-b06a-11e7-8b55-517251d86f06.png)
![screenshot 41](https://user-images.githubusercontent.com/29912986/31564273-e6115d42-b06a-11e7-9a42-d4a709a69541.png)

(It is css for gtk. I like black letters on white background.)

**Comment by TooWaBoo** [comment]
@chaotic-sys 
Looks nice. 👍

**Comment by Hombre57** [comment]
@heckflosse @Beep6581 Do you agree with this patch ? It sets minimum requirement for Gtk 3 to 3.22.24 for windows only :

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 01865fc..490cfa7 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -266,10 +266,15 @@
 
 # Check for libraries:
 find_package(PkgConfig)
+if(WIN32)
+pkg_check_modules (GTK     REQUIRED gtk+-3.0>=3.22.24)
+pkg_check_modules (GTKMM   REQUIRED gtkmm-3.0>=3.22)
+else()
 pkg_check_modules (GTK     REQUIRED gtk+-3.0>=3.16)
+pkg_check_modules (GTKMM   REQUIRED gtkmm-3.0>=3.16)
+endif()
 pkg_check_modules (GLIB2   REQUIRED glib-2.0>=2.44)
 pkg_check_modules (GLIBMM  REQUIRED glibmm-2.4>=2.44)
-pkg_check_modules (GTKMM   REQUIRED gtkmm-3.0>=3.16)
 pkg_check_modules (CAIROMM REQUIRED cairomm-1.0)
 pkg_check_modules (GIO     REQUIRED gio-2.0>=2.44)
 pkg_check_modules (GIOMM   REQUIRED giomm-2.4>=2.44)
```

**Comment by Hombre57** [comment]
@TooWaBoo Could you please test the Fullscreen button ? It doesn't restore to maximized properly when clicking on it again here.

**Comment by Hombre57** [comment]
Hmm... seems to work fine now, with your themes and RawTherapee theme. Don't know what happened.

**Comment by TooWaBoo** [comment]
@Hombre57 
I don't have any issues with the fullscreen button.

**Comment by Beep6581** [comment]
@Hombre57 agreed. I already updated RawPedia based on #4125
http://rawpedia.rawtherapee.com/Windows

**Comment by Hombre57** [comment]
Patch committed. This Gtk version doesn't solve the curve issue from Retinex (beside others)... Closing.
