### ISSUE TITLE
In the program Rawtherapee is not displayed when connecting to a computer via RDP

### ISSUE THREAD

**Issue by tuvalkin** [Beep6581/RawTherapee#4142]
In the program Rawtherapee is not open lists (check boxes) when connected to the computer via RDP. When you use a computer directly through the console, everything works as it should. Interestingly, before this problem was not, and now she appeared in version 5.2 Rawtherapee and Rawtherapee version 5.3. Tested on computers with operating system Windows 7/64 and Windows server 2008 R2. The account has administrator rights.

В работе программы Rawtherapee не открываются списки (флажки) при подключении к компьютеру через RDP. При использовании компьютера напрямую, через консоль, всё работает как надо. Интересно, что раньше этой проблемы не было, а сейчас она появилась как в версии Rawtherapee 5.2, так и в версии Rawtherapee 5.3. Проверял на компьютерах с операционной системой Windows 7/64 и Windows server 2008 R2. Учётная запись имеет права администратора.

**Comment by Benitoite** [comment]
Did you have the screenshot?

**Comment by Beep6581** [comment]
@tuvalkin show screenshots of the problem.

**Comment by Benitoite** [comment]
Today's session on deb902 over Gnome Vinagre/RDP running RT 5.3 on win 10, no probs.
![capture](https://user-images.githubusercontent.com/17919239/31797536-908bd140-b4e3-11e7-82d8-fd4e581bdb88.PNG)
![img_2884-1](https://user-images.githubusercontent.com/17919239/31797569-b950b000-b4e3-11e7-9710-9f3fe6e0a3c0.jpg)

**Comment by tuvalkin** [comment]
If you open the list "Method: Blend", you have it open? The list Method takes place? On the screenshot the list is closed.  In the screenshot I do not see that there is no problem.

Если вы открываете список "Метод", он у вас открывается? Список Метод разворачивается? На скриншоте список закрыт. На скриншоте я не вижу что проблемы нет.

**Comment by Benitoite** [comment]
I didn’t have a problem with the drop down list checkboxes I used, but I can try that particular one later.

**Comment by tuvalkin** [comment]
ОК

**Comment by Benitoite** [comment]
Seems to work ok here using Microsoft Remote Desktop on mac as well as Remmina on Debian 9.2.1 to Win 10.

**Comment by tuvalkin** [comment]
You are using Windows 10 and I am running Windows 7 and Windows server 2008 R2. So that's the reason

**Comment by Benitoite** [comment]
Have you tried other protocols?
