### ISSUE TITLE
RT crushes at Win 7 when I use >Tonal compression menu

### ISSUE THREAD

**Issue by KerimRagimov** [Beep6581/RawTherapee#4147]
Version: 5.0-r1-gtk2
Branch: 5.0-r1-gtk2
Commit: 1077c4ba
Commit date: 2017-02-01
Compiler: gcc 6.3.0
Processor: pentium4
System: Windows
Bit depth: 32 bits
Gtkmm: V2.24.4

When I use '**Tonal complerssion**' settings in Exposition table, -- RT crushes down on the stage of saving the file. Debug version the same. What it could be? Tank you for help

**Comment by Beep6581** [comment]
@KerimRagimov http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports
Update to 5.3, then post the missing info if you can still reproduce.

--edit
Just noticed that you're using the 32-bit build. We dropped support for 32-bit Windows with version 5.0-r1.

**Comment by KerimRagimov** [comment]
okay... thank you
