### ISSUE TITLE
Tiff files are not shown anymore after clearing cache

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#4149]
Today on irc @Hombre57 reported that tiff files are not shown anymore after clearing cache.
I confirm the bug. I bisected. The Issue was introduced with bb874bc

**Comment by heckflosse** [comment]
@Hombre57 I think I found the bug...

**Comment by Hombre57** [comment]
@heckflosse Nice catch, thanks for the fix :+1:

**Comment by heckflosse** [comment]
@Hombre57 De rien.
