### ISSUE TITLE
RT 5.3-70-g1c86c3c + lensfun v0.3.2 unable to pick lens of Sony RX10 and RX100 II automatically

### ISSUE THREAD

**Issue by mandree** [Beep6581/RawTherapee#4161]
I am using RawTherapee 5.3-70-g1c86c3c (dev branch) along with 
lensfun v0.3.2 from Git, commit ef537313ff5a2c977f60f10bd09fd155a85535a7, on Ubuntu 16.04LTS on a 64-bit installation.

RX100-II: Trying to auto-correct the lens with lensfun does not work, it is greyed out. The module does pick the right camera, and displays "SONY DSC-RX100M2", and leaves the lens combo gadget empty.
I can pick "Sony DSC-RX100 II & compatibles" and get a plausible correction.

A sample raw image (which was neither evenly illuminated nor properly flat nor level nor aligned) can be found at [https://filebin.net/3jd2vm6om12zksjx/DSC09637.ARW](https://filebin.net/3jd2vm6om12zksjx/DSC09637.ARW)

The RX10 (EXIF overlay: "SONY DSC-RX10 + Unknown", Camera DSC-RX10, Lens "Sony RX10 & compatibles" needs to be selected manually) is also affected. Raw sample: [https://filebin.net/3jd2vm6om12zksjx/DSC06873.ARW](https://filebin.net/3jd2vm6om12zksjx/DSC06873.ARW)

Hint: looking with exiftool and exiv2, the lens does not appear to have a name in the EXIF data, correspondingly RT displays it as "Unknown"

lensfun-update-data will pull a database with a compact-sony.xml that isn't changed in RX100 matters, the older version I am using is at [https://filebin.net/3jd2vm6om12zksjx/compact-sony.xml](https://filebin.net/3jd2vm6om12zksjx/compact-sony.xml)

**Comment by gaaned92** [comment]
- as the two cameras are fixed lens camera, there is no need to identify the lens. Rawtherapee will display "Unknown": that is normal.

- lensfun has a mecanism to find the corresponding lens. With your two cameras, it fails.
Changing the lens name to "DSC-RX10 & compatibles" and "DSC-RX100M2 & compatibles" permits to have an automatic matching. I open a ticket on lensfun site [http://lensfun.sourceforge.net/](http://lensfun.sourceforge.net/)

- corrections seem effectively approximative. Perhaps you should submit new photos to get better corrections. See how to do on the lensfun site. I cannot help in this matter.

**Comment by gaaned92** [comment]
@agriggio 
The same problem happens for Panasonic fixed lens cameras.
See at [https://sourceforge.net/p/lensfun/bugs/91/](https://sourceforge.net/p/lensfun/bugs/91/) the answer of  Torsten Bronger.
Is the same logic is applied for fixed lenses cameras in Rawtherapee?
Title should be: Rawtherapee unable to pick lens of fixed lens cameras.

**Comment by agriggio** [comment]
@gaaned92 thanks for the heads-up. I was unaware of this "trick" -- either it is not documented, or I simply could not find it in the docs (may very well be the latter).
I'll fix it. 
The logic I was using was taken from UFraw, btw.

> Title should be: Rawtherapee unable to pick lens of fixed lens cameras.

well, in many cases the current logic works...

**Comment by gaaned92** [comment]
> well, in many cases the current logic works

...
It works when lens name is the same as camera name  I think.

> either it is not documented, or I simply could not find it in the docs

I am unable as well to find it.

**Comment by agriggio** [comment]
Here's a patch -- can someone test it please? I tried on the two raws above and it works, but I'd like to get some more coverage for other fixed-lens cameras...

```diff
diff --git a/rtengine/rtlensfun.cc b/rtengine/rtlensfun.cc
--- a/rtengine/rtlensfun.cc
+++ b/rtengine/rtlensfun.cc
@@ -172,6 +172,12 @@
 }
 
 
+bool LFCamera::isFixedLens() const
+{
+    return data_ && data_->Mount && std::islower(data_->Mount[0]);
+}
+
+
 Glib::ustring LFCamera::getDisplayString() const
 {
     if (data_) {
@@ -387,12 +393,7 @@
 {
     LFLens ret;
     if (data_) {
-        Glib::ustring lname = name;
-        bool stdlens = camera && (name.empty() || name.find("Unknown") == 0);
-        if (stdlens) {
-            lname = camera.getModel(); // "Standard"
-        }
-        auto found = data_->FindLenses(camera.data_, nullptr, lname.c_str());
+        auto found = data_->FindLenses(camera.data_, nullptr, name.c_str());
         for (size_t pos = 0; !found && pos < name.size(); ) {
             // try to split the maker from the model of the lens -- we have to
             // guess a bit here, since there are makers with a multi-word name
@@ -411,6 +412,9 @@
                 break;
             }
         }
+        if (!found && camera && camera.isFixedLens()) {
+            found = data_->FindLenses(camera.data_, nullptr, "");
+        }
         if (found) {
             ret.data_ = found[0];
             lf_free(found);
diff --git a/rtengine/rtlensfun.h b/rtengine/rtlensfun.h
--- a/rtengine/rtlensfun.h
+++ b/rtengine/rtlensfun.h
@@ -69,6 +69,7 @@
     Glib::ustring getMake() const;
     Glib::ustring getModel() const;
     float getCropFactor() const;
+    bool isFixedLens() const;
 
     Glib::ustring getDisplayString() const;
 
```

**Comment by Benitoite** [comment]
@agriggio Your patch works perfect for the RX100M2, but for me the RX10 was not recognized in the lensfun section. I'm on mac using the lensfun 3.2.0 sourceforge database.  If I had a more up-to-date database, I suppose it would work as well? RX10 doesn't seem to be in my list under Sony.

**Comment by agriggio** [comment]
@Benitoite it's probably a lensfun thing, I agree. It works here:
**EDIT**: sorry, I had attached the wrong screenshot :-)

![screenshot from 2017-10-30 16 56 55](https://user-images.githubusercontent.com/11982086/32180873-6999e302-bd93-11e7-931f-116b19e4f605.png)

**Comment by gaaned92** [comment]
Works for Sony RX10 and RX100 II and also for panasonic FZ1000.
For W10 test `RawTherapee_dev_5.3-86-ga2a70bff_WinVista_64.zip` uploaded at
[https://drive.google.com/open?id=0B2q9OrgyDEfPS2FpdDAtMVI1RG8](https://drive.google.com/open?id=0B2q9OrgyDEfPS2FpdDAtMVI1RG8)

**Comment by gaaned92** [comment]
@Benitoite 
Sadly all Lensfun versions ( 3.2.0 tagged or last master) appear with 3.2.0 version number. So it is of no use.
To know what DB version you use, the only way is to get the timestamp.
The last timestamp  is 1509280372.
As you build yourself, the best is to clone lensfun from sourceforge, build it (it's straihtforward on Windows, should be easy on Mac) and build RT against it.

**Comment by Benitoite** [comment]
1447322002 is my current timestamp.  I believe I have it as cloned from source forge and checked out tag `v0.3.2`.  I will have to try `master`, if that is working ok for windows...
`master` seemed to work ok but I had to take out -std=c++11

**Comment by gaaned92** [comment]
v0.3.2 tag is quite old. Definitely you should try master.
I don't provide any compile flag, but I get a lot of warnings. Nevertheless it works.
It seems lensfun guys are working hard as there are frequent updates. new timestamp 1509356205

**Comment by mandree** [comment]
Note that newer lensfun versions broke the API deliberately, so may not work with other consumers...

FTR, update "lensfun-update-data" to get an up-to-date camera-and-lens corrections database, and if you do that as root (on your own computer) you'll get it for all users.

My original problem appears solved, thanks to Torsten Bronger and @agriggio.
