### ISSUE TITLE
Something in this directory causes RT to crash

### ISSUE THREAD

**Issue by waxhead** [Beep6581/RawTherapee#4162]
Latest git update today, aboutThisBuild:

RT opens fine, however for this specific directory RT is hanging or crashing. Thought it worth reporting.  This isn't the debug build, however happy to provide one if you need it.

[log.txt](https://github.com/Beep6581/RawTherapee/files/1424698/log.txt)

Version: 5.3-70-g1c86c3c
Branch: dev
Commit: 1c86c3c
Commit date: 2017-10-26
Compiler: cc 5.4.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.18.0
Lensfun: V0.3.2.0
Build type: release
Build flags:  -std=c++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -O3 -DNDEBUG
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON

**Comment by Beep6581** [comment]
Please provide a stack backtrace from a debug build.

**Comment by waxhead** [comment]
OK, I'm going to have to admit that I can't recall the directory, I had a look at the log file and that directory works fine.

Can we leave this one open for a little longer I may be able to find it again and I have the debug version built now.
