### ISSUE TITLE
TIFF files sent directly to Gimp by RawTherapee are without EXIF

### ISSUE THREAD

**Issue by kfiresmith** [Beep6581/RawTherapee#4163]
The only way to preserve EXIF data is to save a TIFF file, then open with Gimp.  When the hand-off is done using the convenience button, the TIFF created and handed to Gimp does not contain any EXIF data.

Test host is running latest version of both programs on 64 bit Fedora 26.

**Comment by heckflosse** [comment]
Please tell us which the latest versions of both programs on 64 bit Fedora are!

**Comment by kfiresmith** [comment]
Sorry @heckflosse  - I should have been more clear, they are the same as the latest stable upstream, thus, Rawtherapee 5.3, Gimp 2.8.22.  Distro-specifically:
rawtherapee-5.3-2.1.x86_64
gimp-2.8.22-2.fc26.x86_64

**Comment by Beep6581** [comment]
Please upload the requested files:
https://discuss.pixls.us/t/preserving-exif-through-the-rawtherapee-gimp-pipeline/5475/7?u=morgan_hardwood

**Comment by kfiresmith** [comment]
Sorry @Beep6581  - I have a really slow connection and the .tif is large - it's been processing for a while now.  Will link when it finishes.

**Comment by Beep6581** [comment]
@kfiresmith you could enable resizing in RT, set the scale to 0.01. Then the TIFF file will be tiny.

**Comment by kfiresmith** [comment]
...and they are done.  Apologies again.  
https://filebin.net/oly30i9oyynahqr8

**Comment by kfiresmith** [comment]
Looks like the .tif file in /tmp *does* contain proper EXIF data.  So now I'm stumped about why the JPEG coming out of GIMP doesn't include EXIF data.

**Comment by Beep6581** [comment]
Thank you. Both the TIFF and the JPEG contain metadata, including Exif and makernotes.

As I quoted in the forum, even GIMP's own developer Mitch wrote that metadata is broken in 2.8. Update to GIMP 2.9.6 if you can.
