### ISSUE TITLE
YI M1 RAW images - white becomes pink

### ISSUE THREAD

**Issue by rav-rav** [Beep6581/RawTherapee#4164]
When I import DNG files from my YI M1 camera, the auto-matched camera profile is applied.
This profile however seems to turn bright white colors into pink. Adjusting highlight compression makes it even worse.

The only fix seems to be to use "no profile" for color management, or is there another way?

Here's an example raw file: https://drive.google.com/open?id=0B6dJjdJMeyFAS0U5TmN0R1hnQkU
And the result: https://drive.google.com/open?id=0B6dJjdJMeyFATE9JMnhXR2NyTmM

**Comment by Beep6581** [comment]
@rav-rav probably the white point is incorrect, but I can't tell because the link contains no file. Go to the Raw tab > Raw white points and increase the value above 1.0 until the clipped magenta regions turn white.

**Comment by rav-rav** [comment]
Oh, the link didn't work as expected, I fixed the initial post.

Thanks, increasing the value by 0.01 to 1.01 suddenly completely fixes the issue. The whole histogram makes a huge jump between 1.0 and 1.01 and everything looks fine.

Somehow however I'd expect the image to look like this from the beginning at 1.0.

**Comment by iliasg** [comment]
@Beep6581 @rav-rav @heckflosse 

> Somehow however I'd expect the image to look like this from the beginning at 1.0.

It would be so if the maker name was same as in the first samples (was beta samples ..) we checked  i.e. "XIAOYI" instead of the current "YI TECHNOLOGY"

The problem is that the DNG tag reports wrong WhiteLevel .We have set a more conservative white level in camconst.json but it's inactive for the new maker name ;)

We have to update the dcraw.cc and camconst.json code to include the new naming ..

https://github.com/Beep6581/RawTherapee/blob/8aa3b75c4643340c5d1acf250d896d12ea59e250/rtengine/dcraw.cc#L9569
 
```
if(!strncmp((make, "XIAOYI", 6) II !strncmp(make, "YI", 2)) && !strncmp(model, "M1",2))
```

(I am not sure if the above syntax is OK .. :( )

https://github.com/Beep6581/RawTherapee/blob/8aa3b75c4643340c5d1acf250d896d12ea59e250/rtengine/camconst.json#L2289

```
        "make_model": [ "XIAOYI M1", "YI TECHNOLOGY M1" ],
```

**Comment by Beep6581** [comment]
Fix confirmed:
```diff
diff --git a/rtengine/camconst.json b/rtengine/camconst.json
index b13dd00f..5a3a18fd 100644
--- a/rtengine/camconst.json
+++ b/rtengine/camconst.json
@@ -2286,7 +2286,7 @@ Camera constants:
     },
 
     { // Quality C, No proper color data, beta samples, frame set to official jpeg,
-        "make_model": "XIAOYI M1",
+        "make_model": [ "XIAOYI M1", "YI TECHNOLOGY M1" ],
         "dcraw_matrix": [ 7158,-1911,-606,-3603,10669,2530,-659,1236,5530 ], // XIAO YI DNG D65
         "raw_crop": [ 4, 3, 5192, 3896 ], // full raw 5200x3902, official jpeg 5184X3888
         "ranges": {
diff --git a/rtengine/dcraw.cc b/rtengine/dcraw.cc
index f59f5b2f..8e027842 100644
--- a/rtengine/dcraw.cc
+++ b/rtengine/dcraw.cc
@@ -9566,7 +9566,7 @@ dng_skip:
     adobe_coeff (make, model);
   if(!strncmp(make, "Leica", 5) && !strncmp(model, "SL",2))
     adobe_coeff (make, model);
-  if(!strncmp(make, "XIAOYI", 6) && !strncmp(model, "M1",2))
+  if((!strncmp(make, "XIAOYI", 6) || !strncmp(make, "YI", 2)) && !strncmp(model, "M1",2))
 	adobe_coeff (make, model);
   if (raw_color) adobe_coeff (make, model);
   if (load_raw == &CLASS kodak_radc_load_raw)
```

@heckflosse IIRC we agreed to only update the dcraw patch when a new version comes out, not after every change, is that correct? If so, is the above ok to commit?

**Comment by heckflosse** [comment]
@Beep6581 That's correct. Ok to commit
