### ISSUE TITLE
HDR Tonemap Fattal crash

### ISSUE THREAD

**Issue by Hombre57** [Beep6581/RawTherapee#4165]
If you open [this file](https://pixls-discuss.s3.amazonaws.com/original/2X/8/870226bc6b73d83438602cfa7f7ca0eab7ed4d23.DNG) , set the neutral profile and activate the Fattal tool, RT will crash.

**Comment by Beep6581** [comment]
RT has a Fattal tool?

**Comment by Hombre57** [comment]
Check IRC logs, and see `hdr_tonemap_fattal` branch

**Comment by agriggio** [comment]
warning: it might put your computer on fire... it's not ready for prime time yet

**Comment by Beep6581** [comment]
!!! :+1: :smile: :beers:

**Comment by agriggio** [comment]
@Hombre57 can you try now? I made a few fixes...

**Comment by Hombre57** [comment]
@agriggio Yes, it works now :+1: .

@Beep6581 Should I close this issue or leave it open for other bugs/suggestion for this new tool ?

**Comment by Beep6581** [comment]
@Hombre57 I'd close it, as it's about some specific crash.
