### ISSUE TITLE
Automatic Chromatic Aberration not present, FUJI XT20 XC 16-50mm

### ISSUE THREAD

**Issue by symbolsim** [Beep6581/RawTherapee#4171]
Hi!

Just started using RawTherapee, amazing open-source program! I was reading about the automatic chromatic aberration correction tool in the wiki, however this tick box is unavailable for my photos (Gujufilm XT20,  XC 16-50mm lens)

DOes anybody know how I can get the automatic chromatic abberation to work for my setup?

Regards

Marcus

If you are filing a bug report, please first read the guide How to Write Useful Bug Reports:
http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports
You must provide the required information in order for your bug report to be valid.
Delete this text before posting.

**Comment by heckflosse** [comment]
@symbolsim The current implementation of automatic raw ca correction only works for bayer sensors, not for xtrans sensors.

**Comment by Barugon** [comment]
Is there any reason that it can't be done for x-trans sensors too?
