### ISSUE TITLE
suspicious code in Median_Denoise

### ISSUE THREAD

**Issue by agriggio** [Beep6581/RawTherapee#4173]
Consider this:

```c++
                case Median::TYPE_7X7: {
#ifdef __SSE2__
                    std::array<vfloat, 49> vpp ALIGNED16;

                    for (; j < width - border - 3; j += 4) {
                        for (int kk = 0, ii = -border; ii <= border; ++ii) {
                            for (int jj = -border; jj <= border; ++jj, ++kk) {
                                vpp[kk] = LVFU(medianIn[i + ii][j + jj]);
                            }
                        }

                        STVFU(medianOut[i][j], median(vpp));
                    }

#endif

                    std::array<float, 49> pp;

                    for (; j < width - border; ++j) {
                        for (int kk = 0, ii = -border; ii <= border; ++ii) {
                            for (int jj = -border; jj <= border; ++jj, ++kk) {
                                pp[kk] = medianIn[i + ii][j + jj];
                            }
                        }

                        medianOut[i][j] = median(pp);
                    }

                    break;
                }
```

Isn't there an `#else` missing? Otherwise aren't we doing the work twice on SSE-enabled hardware? Or am I missing something?
(Ping @heckflosse)

**Comment by heckflosse** [comment]
@agriggio You miss the fact that `j` is initialized outside. This way on SSE-enabled hardware the part inside `ifdef __SSE2__` processes as many pixels as possible `j < width - border - 3` and the second part processes the remaining pixels `j < width - border` (if any).
On non SSE-enabled hardware the second part processes all pixels.

**Comment by agriggio** [comment]
> @agriggio You miss the fact that j is initialized outside.

a-ha! There you go. Thanks for pointing out :+1: 
Now I can submit my patch for doing median filtering with a threshold without doing it on all the pixels (should speed up Fattal a little bit)
