### ISSUE TITLE
Expected Behavior? Fast export ignores resize size

### ISSUE THREAD

**Issue by fishcu** [Beep6581/RawTherapee#4175]
I'm running RT ~~5.1~~ 5.3 on Ubuntu 16.04. Info from "about"->"version":
Version: 5.3
Branch: releases
Commit: ec0f7936
Commit date: 2017-09-30
Compiler: x86_64-linux-gnu-gcc 5.4.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.18.0
Lensfun: V0.2.8.0
Build type: Release
Build flags: -O3 -std=c++11  -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations
Link flags:  -Wl,-Bsymbolic-functions -Wl,-z,relro
OpenMP support: ON
MMAP support: ON

In the queue, I have turned on "Auto-start".

In the editor, when right-clicking an image in the overview above (the "film strip") and choosing "Put to queue", the resulting exported image will respect what I have chosen in the "resize" option.
When right-clicking an image and choosing "Put to queue (fast export)" instead, the resulting image will have a size where the larger side is 900 pixels. This seems to correspond to the default value.

Is this the expected behavior or a bug?
To me it makes more sense to respect the currently chosen size for "resize" -- for example the "crop" setting is applied all the same when choosing regular or "fast" export.

Happy to provide more info if needed.

edit: I have updated to RT 5.3 through the dhor/myway PPA. The same behavior persists.

**Comment by heckflosse** [comment]
![fastexport](https://user-images.githubusercontent.com/13733487/32613692-e35569b6-c56b-11e7-9bb8-a057b85a8cd2.png)
