### ISSUE TITLE
TIFF compression predictor

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4179]
I noticed that RawTherapee does not use a TIFF compression predictor:
https://github.com/Beep6581/RawTherapee/blob/dev/rtengine/imageio.cc#L1365
https://www.awaresystems.be/imaging/tiff/tifftags/predictor.html

Since RawTherapee deals with photographs, it might be a good idea to use a predictor. This issue is to test them out.

**Comment by Hombre57** [comment]
@Beep6581 Are you still in charge of this issue ?

**Comment by Beep6581** [comment]
Completely forgot about this. I'll test it out today/tomorrow.

**Comment by Beep6581** [comment]
```diff
diff --git a/rtengine/imageio.cc b/rtengine/imageio.cc
index ff9c9b55..b9507edd 100644
--- a/rtengine/imageio.cc
+++ b/rtengine/imageio.cc
@@ -29,6 +29,9 @@
 #include "../rtgui/options.h"
 #include "../rtgui/version.h"
 
+#define BENCHMARK
+#include "../rtengine/StopWatch.h"
+
 #ifdef WIN32
 #include <winsock2.h>
 #else
@@ -1196,6 +1199,7 @@ int ImageIO::saveJPEG (Glib::ustring fname, int quality, int subSamp)
 
 int ImageIO::saveTIFF (Glib::ustring fname, int bps, bool uncompressed)
 {
+    BENCHFUNMICRO
     if (getWidth() < 1 || getHeight() < 1) {
         return IMIO_HEADERERROR;
     }

```

Uncompressed:
```bash
$ rm -rvf /tmp/tiff
$ mkdir -p /tmp/tiff/uncompressed
$ ./build/release/rawtherapee-cli -o /tmp/tiff/uncompressed -q -a -p rtdata/profiles/Default.pp3 -b8 -t -c ~/photos/test_images/
```

Compressed:
```text
mkdir /tmp/tiff/predictor_none; ./build/release/rawtherapee-cli -o /tmp/tiff/predictor_none -q -a -p rtdata/profiles/Default.pp3 -b8 -tz -c ~/photos/test_images/predictor/
```

Times of subsequent runs vary by up to ~10%.

Column headers abbreviated so they fit in GitHub:
`Unc` = `uncompressed`
`NONE` = `PREDICTOR_NONE`
`HORIZONTAL` = `PREDICTOR_HORIZONTAL`
`FP` = `PREDICTOR_FLOATINGPOINT`

# 8-bit

`5.3-297-g`c202a612

## saveTIFF Time (ms)

Filename | Unc | NONE | HORIZONTAL
--- | --- | --- | ---
Sony_a7RIII_f8_ISO100_daylight_expcomp0.ARW | 198 | 7163 | 18404
amsterdam.pef | 78 | 1560 | 3774
canon_550d_dual_iso.dng | 132 | 3318 | 11984
fujifilm_x100s_x-trans.raf | 118 | 3094 | 8637
greenscreen.cr2 | 162 | 4968 | 12781
karin_library_1.hdr.dng | 78 | 1915 | 6248
mattia_blue_stars.cr2 | 130 | 3665 | 3939
yellow_poppy.nef | 93 | 2348 | 7985

## Size (MB)

Filename | Unc | NONE | HORIZONTAL
--- | --- | --- | ---
Sony_a7RIII_f8_ISO100_daylight_expcomp0.ARW | 122 | 100 | 67
amsterdam.pef | 30 | 25 | 18
canon_550d_dual_iso.dng | 52 | 36 | 22
fujifilm_x100s_x-trans.raf | 47 | 40 | 25
greenscreen.cr2 | 65 | 42 | 31
karin_library_1.hdr.dng | 30 | 17 | 13
mattia_blue_stars.cr2 | 52 | 45 | 39
yellow_poppy.nef | 35 | 26 | 16

# 16-bit

`5.3-297-g`c202a612

## saveTIFF Time (ms)

Filename | Unc | NONE | HORIZONTAL
--- | --- | --- | ---
Sony_a7RIII_f8_ISO100_daylight_expcomp0.ARW | 147 | 12450 | 16665
amsterdam.pef | 77 | 3037 | 4012
canon_550d_dual_iso.dng | 98 | 5580 | 8023
fujifilm_x100s_x-trans.raf | 89 | 5308 | 6999
greenscreen.cr2 | 123 | 11603 | 14915
karin_library_1.hdr.dng | 40 | 3533 | 4698
mattia_blue_stars.cr2 | 98 | 6757 | 6466
yellow_poppy.nef | 93 | 4571 | 6224

## Size (MB)

Filename | Unc | NONE | HORIZONTAL
--- | --- | --- | ---
Sony_a7RIII_f8_ISO100_daylight_expcomp0.ARW | 243 | 235 | 209
amsterdam.pef | 59 | 56 | 51
canon_550d_dual_iso.dng | 103 | 97 | 82
fujifilm_x100s_x-trans.raf | 93 | 91 | 79
greenscreen.cr2 | 128 | 109 | 98
karin_library_1.hdr.dng | 59 | 56 | 48
mattia_blue_stars.cr2 | 104 | 97 | 96
yellow_poppy.nef | 70 | 67 | 57

# 32-bit

`5.3-212-g`912f9f43 (tiff32float branch)

## saveTIFF Time (ms)

Filename | Unc | NONE | HORIZONTAL | FP
--- | --- | --- | ---| ---
Sony_a7RIII_f8_ISO100_daylight_expcomp0.ARW | 344 | 34642 | 50443 | 27774
amsterdam.pef | 141 | 8303 | 11541 | 7488
canon_550d_dual_iso.dng | 209 | 9691 | 14454 | 9541
fujifilm_x100s_x-trans.raf | 175 | 13855 | 21674 | 11350
greenscreen.cr2 | 248 | 22140 | 34591 | 22273
karin_library_1.hdr.dng | 83 | 8303 | 17859 | 9267
mattia_blue_stars.cr2 | 201 | 15068 | 17595 | 14038
yellow_poppy.nef | 250 | 9990 | 19506 | 10457

## Size (MB)

Filename | Unc | NONE | HORIZONTAL | FP
--- | --- | --- | ---| ---
Sony_a7RIII_f8_ISO100_daylight_expcomp0.ARW | 486 | 358 | 332 | 305
amsterdam.pef | 117 | 85 | 84 | 77
canon_550d_dual_iso.dng | 206 | 54 | 50 | 44
fujifilm_x100s_x-trans.raf | 185 | 141 | 121 | 113
greenscreen.cr2 | 256 | 163 | 154 | 146
karin_library_1.hdr.dng | 117 | 80 | 74 | 68
mattia_blue_stars.cr2 | 207 | 138 | 168 | 155
yellow_poppy.nef | 139 | 96 | 91 | 87

**Comment by Beep6581** [comment]
Conclusions.

The file size difference between `PREDICTOR_NONE` and `PREDICTOR_HORIZONTAL` is significant. The time increase varies between 1-4x. **If someone chooses to use TIFF compression, they are prioritizing file size over time.** As such, I think it's fine to hard-code `PREDICTOR_HORIZONTAL`.

For floating-point files, using `PREDICTOR_FLOATINGPOINT` saves a lot of both time and space. It's almost as fast as `PREDICTOR_NONE` while file sizes are significantly smaller. However, there might be an issue with support for these files. For example RawTherapee currently crashes when trying to load a 32-bit floating-point `PREDICTOR_FLOATINGPOINT` file, but opens the same but `PREDICTOR_HORIZONTAL` files fine. This implies that using `PREDICTOR_FLOATINGPOINT` should be optional, and on by default.

Since RawTherapee should make using `PREDICTOR_FLOATINGPOINT` optional, we might as well make the others optional.
Saving to compressed 8-bit and 16-bit TIFF should enable `PREDICTOR_HORIZONTAL` by default.
Saving to compressed 32-bit TIFF should enable `PREDICTOR_FLOATINGPOINT` by default.

**Comment by Beep6581** [comment]
Revised conclusion:
Due to RawTherapee not supporting saving 32-bit floating-point TIFFs [any time soon](https://github.com/Beep6581/RawTherapee/issues/2357#issuecomment-352204776), I'm in favor of just hard-coding `PREDICTOR_HORIZONTAL`.

**Comment by heckflosse** [comment]
👍 for `PREDICTOR_HORIZONTAL`. If I want to go for speed, I will use uncompressed TIFF

**Comment by Hombre57** [comment]
This issue is related to  #4233, I'll make a patch there that fix the segfault and implement `PREDICTOR_HORIZONTAL` for 8/16 bits compressed images and `PREDICTOR_FLOATINGPOINT` for 32 bits ones.

**Comment by Beep6581** [comment]
`bps == 32 ? PREDICTOR_FLOATINGPOINT : PREDICTOR_HORIZONTAL`

Implemented in https://github.com/Beep6581/RawTherapee/commit/5ea5cfd943d2f77f91f3b7f47e377074e57be629#diff-9cc64a95ee3135fa9f9d133820af996dR1376
