### ISSUE TITLE
Blue gamma correction doesn't work on B&W conversion

### ISSUE THREAD

**Issue by RawConvert** [Beep6581/RawTherapee#4188]
When converting to black and white, the blue slider has no effect.
To reproduce: any raw file (I think); colour tools; Black-and-White; Method=Channel Mixer.
Note the red and green gamma sliders make an obvious difference, whereas the blue one makes no difference.  It is a dead parameter.  It is bereft of life.  It has ceased to be.  Etc.
I think it's been like this for some time.
RT 5.2, dev, GTK3.2, Ubuntu

**Comment by Beep6581** [comment]
@RawConvert the change should be visible if you change the working space to sRGB.

@heckflosse made a patch for the R G B curves so that the blue curve would have a visible effect in ProPhoto space. Maybe it could be done for the B&W tool as well? Curve + gamma sliders, as needed (I don't have RT in front of me at the moment).

**Comment by Beep6581** [comment]
Confirmed that blue gamma correction makes a visible difference in sRGB working space, and probably works fine in ProPhoto too, its just that ProPhoto is too big to see a difference.

**Comment by Desmis** [comment]
This "bug" is a non bug :)
it must be the third time I comment on this topic with always the same answer, which is in Rawpedia

_"One can change the rendering of the tones for each channel (R, G, B) using the gamma sliders. This command roughly simulates the rendering of the paper under the enlarger (hard, normal, soft). Pushing the sliders to the left (negative values) darkens the image and gives more contrast, pushing to the right (positive values) softens the image. Notice: there isn't a bug in the Blue channel: when using Prophoto as working space, the blue channel is less active. Use the sRGB working space to see the effect."_ 

Prophoto is too big and in bleu color, these color are out of an human can see.
The last time, I proposed to replace "Prophoto"by "widegamut"  :)

**Comment by Beep6581** [comment]
@heckflosse would your patch to make the blue RGB curve responsive in ProPhoto space be applicable here?

**Comment by Desmis** [comment]
@Beep6581  @heckflosse 
In fact I repeat it is not a bug, but the bad response is due to Prophoto Matrix
```c++
constexpr double xyz_prophoto[3][3] = {
    {0.7976749,  0.1351917,  0.0313534},
    {0.2880402,  0.7118741,  0.0000857},
    {0.0000000,  0.0000000,  0.8252100}
};
```
The third coefficient in the second line is `0.0000857`, that means no response for gamma in blue channel

If you replace `0.0000857` by `0.05` all works fine below

Now a little modification in `improcfun.cc`
```c++
    +bool blackwhite = params->blackwhite.enabled;

   +const bool isProPhoto = (params->icm.workingProfile == "ProPhoto");
// I have moved these 2 lines from below

    float toxyz[3][3] = {
        {
            static_cast<float> ( wprof[0][0] / Color::D50x),
            static_cast<float> ( wprof[0][1] / Color::D50x),
            static_cast<float> ( wprof[0][2] / Color::D50x)
        }, {
            static_cast<float> ( wprof[1][0]),
            static_cast<float> ( wprof[1][1]),
            static_cast<float> ( wprof[1][2])
        }, {
            static_cast<float> ( wprof[2][0] / Color::D50z),
            static_cast<float> ( wprof[2][1] / Color::D50z),
            static_cast<float> ( wprof[2][2] / Color::D50z)
        }
    };
    
+if(isProPhoto && blackwhite) {//work around to increase action for gamma in black and white
 +toxyz[1][2] = 0.05;//instead of 0.0000857
  +}    
```
and comment the 2 lines 
```
  //bool blackwhite = params->blackwhite.enabled;
   // const bool isProPhoto = (params->icm.workingProfile == "ProPhoto");
```
I don't know how to post a patch in this case

Jacques

**Comment by Desmis** [comment]
Here the patch...with drag and drop the file
[gammaprophoto.txt](https://github.com/Beep6581/RawTherapee/files/2615535/gammaprophoto.txt)

**Comment by Beep6581** [comment]
Confirmed that positive gamma correction values of the blue channel now have an effect in ProPhoto space. Negative values however still have almost no effect.

Unsure what we should do.

**Comment by agriggio** [comment]
> Unsure what we should do.

This is already documented in RawPedia, and it's the expected behaviour. I'd say we should do nothing.
