### ISSUE TITLE
when using SETM thumbs are recomputed when switching between File browser and Editor (Filmstrip) even if SameThumbSize=1 in preferences

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#4194]
To reproduce enable the
```
#define BENCHMARK 
```
in improcfun.cc,
enable `Same thumbnail height between the Filmstrip and the File Browser` in preferences and switch between file browser and editor in SETM mode.
There are a lot of `rgbProc took ...` lines, while there should be none

@Hombre57 Do you have an idea?

**Comment by Hombre57** [comment]
@heckflosse Can't reproduce : when set, `ImProcFunctions::rgbProc` (l. 3076) is not called. Where have you placed your printf ?

**Comment by heckflosse** [comment]
@Hombre57 Ok, here are even simpler instructions to reproduce:

1) make sure, your options file has this:
```
ThumbnailSize=120
ThumbnailSizeTab=120
ThumbnailSizeQueue=160
SameThumbSize=1
MaxPreviewHeight=120
```
and also use SETM
2) create a folder with just one file, apply neutral profile to that file
3) close rt
4) apply this patch
```patch
diff --git a/rtengine/improcfun.cc b/rtengine/improcfun.cc
index ad7e4260..e4667923 100644
--- a/rtengine/improcfun.cc
+++ b/rtengine/improcfun.cc
@@ -39,7 +39,7 @@
 #include "improccoordinator.h"
 #include "clutstore.h"
 #include "ciecam02.h"
-//#define BENCHMARK
+#define BENCHMARK
 #include "StopWatch.h"
 #include "../rtgui/ppversion.h"
 #include "../rtgui/guiutils.h"

```
and build rt

5) Start rt => one `rgbproc took ...` line, which is correct
6) Switch to the empty SETM editor => one `rgbproc took ...` line, which should not be there because there's no need to reprocess the thumb in this case
7) Switch to the FileBrowser => one `rgbproc took ...` line, which should not be there because there's no need to reprocess the thumb in this case

**Comment by Hombre57** [comment]
One more condition is necessary to reproduce : activate the information below thumbs in the file Browser (doesn't matter for Editor panel). If hidden, it works fine. I have to see if the computation of the thumb size is correct. Looks to be a rounding error IMHO.

**Comment by heckflosse** [comment]
@Hombre57 confirmed

**Comment by Hombre57** [comment]
So here you go :)

[ThumbSize-diff.txt](https://github.com/Beep6581/RawTherapee/files/1493442/ThumbSize-diff.txt)
