### ISSUE TITLE
[Feature request] corner/frame crop

### ISSUE THREAD

**Issue by awaysounds** [Beep6581/RawTherapee#4197]
Hello.
I know what rawtherapee build on dcraw code.
And dcraw not use frame with resolution from raw data.
Like it do another convertors.
And rawtherapee do, but with another resolution, slightly larger.

For example:
Camera Fuji x100.
In camera jpeg resolution - 4288x2848 px
In dcraw convertion from raw - 4310x2870 px
In rawtherapee from raw - 4302x2862 px

How can you see there is have some difference.
Some space wase cropped.
And this space contain information.

My question - can you add feature for take off using this "frame" for set resolution of image, and give to us all pixels with useful information (disable cropping)?

**Comment by Beep6581** [comment]
Frame size was explained in #2339

**Comment by awaysounds** [comment]
it's not a solution.
