### ISSUE TITLE
Add "Restart required" to Preferences > Color Management

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4198]
Add "Restart required" to Preferences > Color Management > Directory containing color profiles.

... or maybe this can be enhanced so that a restart is not required?

**Comment by okoncevoy** [comment]
Can I take this issue?

**Comment by heckflosse** [comment]
@lvreclp 👍  from me

**Comment by agriggio** [comment]
sure, go ahead! :+1:

**Comment by okoncevoy** [comment]
Ok, than.

**Comment by okoncevoy** [comment]
And what is the issue? As I can see, the color profiles drop down is updated on directory selection? @Beep6581 Can you tell me what must be done for this issue?

**Comment by agriggio** [comment]
just add a label saying "(restart required)" in the GUI, like what is done for other options (eg themes)

**Comment by okoncevoy** [comment]
@agriggio And what about possibility to use it without restart? Adding a label is the easiest solution

**Comment by Beep6581** [comment]
When I change "Directory containing color profiles", the combobox which lists the monitor profiles, under the main preview in the Editor tab(s), is not updated until I restart RT.

**Comment by okoncevoy** [comment]
Looks like I will add restart required label. Now I can't find sane way to re-init color management panel in editor panel after saving preferences.

**Comment by Hombre57** [comment]
@lvreclp 

> And what about possibility to use it without restart?

Maybe using the content of `Preferences::iccDirChanged` could be copied to `Preferences::workflowUpdate`, so that it updates the `ProfilePanel` ?

**Comment by okoncevoy** [comment]
@Hombre57  Can check that.

**Comment by okoncevoy** [comment]
@Hombre57 
Unfortunately this approach with update calling `Preferences::iccDirChanged ` does nothing. Yes, it updated internal list, but it does not re-initialize `EditorPanel` that is already constructed and initialized. 
I have added missing label: https://github.com/Beep6581/RawTherapee/compare/dev...lvreclp:dev_restart_required_for_colormgmt?expand=1

**Comment by Hombre57** [comment]
It is possible to update the editors (not yet done, that's right), but the label will be fine I guess.

**Comment by okoncevoy** [comment]
Can I create merge request on this?

**Comment by agriggio** [comment]
@lvreclp yes, and thanks!
