### ISSUE TITLE
HDR Tone mapping shifts channels?

### ISSUE THREAD

**Issue by sguyader** [Beep6581/RawTherapee#4200]
I see this weird behaviour when I activate HDR Tone mapping on a raw file (tested on a Fuji and Pentax raws, occurs on both): some channel(s) seem to shift one pixel down and to the right, and this may introduce some what appears as chromatic aberration/fringing.
See the animation below (using one of the "moving boat" raw images), showing the shift and it plays with chromatic aberration:

![untitled2](https://user-images.githubusercontent.com/13856378/33285749-9e224c20-d389-11e7-9f13-0ad57714ba46.gif)

```
-- Git checkout information:
-- 	Commit description:	5.3-226-gedbe4f3f1
-- 	Branch:			dev
-- 	Commit:			edbe4f3f1
-- 	Commit date:		2017-11-27
-- 	Commits since tag:	226
-- 	Commits since branch:	226
-- 	Version (unreliable):	5.3.226
```

**Comment by Beep6581** [comment]
Confirmed in K10D PEF and ILCE-7M2 HDR DNG. It looks like a shadow of the red channel remains.

**Comment by agriggio** [comment]
the tool operates on luminance only, so this is technically impossible -- unless I really remember wrong...
there is some rescaling going on internally, so it might be some off-by-one error, but this should affect all channels, not just one.
I think it's more likely that the tool simply amplifies CA artifacts, that is definitely a possibility...
did you try enabling CA correction (either raw or profiled) and see if it mitigates the problem?

**Comment by heckflosse** [comment]
> seem to shift one pixel down and to the right

That's clearly reproducible.

With raw ca correction enabled I can not confirm the ca issue

**Comment by Beep6581** [comment]
You're right, the color channels stay put while the luminance shifts south-east.
![imgur-2017_11_27-22 13 36](https://user-images.githubusercontent.com/5844619/33289568-49e960e4-d3c0-11e7-9389-d7a9551e7c01.png)
![imgur-2017_11_27-22 13 45](https://user-images.githubusercontent.com/5844619/33289569-4a053184-d3c0-11e7-91c1-1de18b65ce9a.png)
![imgur-2017_11_27-22 13 57](https://user-images.githubusercontent.com/5844619/33289570-4a22c58c-d3c0-11e7-8f21-1bc6ecff707c.png)

**Comment by agriggio** [comment]
@Beep6581 as wrote there might be a rounding error in rescaling. I'll take a look when I find some time

**Comment by sguyader** [comment]
@agriggio it looks like it does mess with profiled CA correction. Regarding raw auto CA I don't know, but the problem is that it is not yet available for xtrans sensors for example.

**Comment by Beep6581** [comment]
Fix confirmed, no side-effects noticed.

**Comment by sguyader** [comment]
Thanks @agriggio!
