### ISSUE TITLE
FUJIFILM DBP for GX680 RAF support

### ISSUE THREAD

**Issue by wtanmdt** [Beep6581/RawTherapee#4204]
I recently received a Fujifilm DBP for GX680 digital back. When I converted the raw file to JPG file, I got strange output as below image. It seems like RawTherapee does not recognize the file.
I have uploaded a RAF raw file and a JPG file both saved by the digital back at:
http://www.weldpass.com/upload/Fujifilm-DBP.zip

Thanks,

Wen

![dscf0001-s](https://user-images.githubusercontent.com/34220266/33530286-f8f4095a-d842-11e7-927c-f24ccaae4831.jpg)

**Comment by agriggio** [comment]
@wtanmdt would it be possible to submit this to http://raw.pixls.us if you haven't done that already? thanks!

**Comment by wtanmdt** [comment]
@agriggio Just submitted. Many thanks for the advice.

**Comment by wtanmdt** [comment]
Here is a picture taken on the color target of X-Rite ColorChecker Passport:
 
http://www.weldpass.com/upload/DSCF0002.RAF

**Comment by Beep6581** [comment]
Hi @wtanmdt 

The above photo was shot on an overcast winter's day on a reflective yellow surface, and it's quite small in the frame.

Please follow these shooting guidelines and release both daylight + tungsten shots into the public domain for inclusion in RT:
http://rawpedia.rawtherapee.com/How_to_create_DCP_color_profiles#Shooting_the_Color_Target

**Comment by wtanmdt** [comment]
Hi @Beep6581 
I just retake the photos as below:

http://www.weldpass.com/upload/Fujifilm-DBP-for-GX680-daylight.RAF
http://www.weldpass.com/upload/Fujifilm-DBP-for-GX680-tungsten.RAF

Thanks.

**Comment by Beep6581** [comment]
Thank you for the shots @wtanmdt , they look good, unfortunately neither RawTherapee nor Adobe DNG Converter can open them yet.

**Comment by wtanmdt** [comment]
I wish it will be supported in future RawTherapee release. 
Many thanks for your work @Beep6581

**Comment by wtanmdt** [comment]
Sorry that I delete the snapshot since I do not have the permission from Alex to publish it before testing.

**Comment by wtanmdt** [comment]
One thing to note: 
The raw converted resolution is 5430 x 3845. 
If I shoot JPG format, the resolution is up to 7648 x 5408.

And the color profile needs improvement since the color target shot was not utilized.

**Comment by Beep6581** [comment]
I tried to find the LibRaw commit which introduces this change, but it's not in the repo:
https://github.com/LibRaw/LibRaw/commits/master

I found [this post](https://www.libraw.org/comment/4059#comment-4059) from Alex from 2015:
> We do not push 'work in progress' code to github, but use own private repo for it. Only big pieces, known to work (in our RawDigger/FastRawViewer) are pushed.

**Comment by wtanmdt** [comment]
@Beep6581 

Alex told me that RawDigger is difficult to support this sensor.

**Comment by wtanmdt** [comment]
@Beep6581 
Just wanted to let you know that LibRaw Release 0.19.0 has supported this RAW file as found in dcraw_common.cpp

**Comment by wheropl** [comment]
@wtanmdt 
could I get a picture of the Fujifilm digital back you're using? and possibly another contact method ~ wanted to ask you some questions about it...

**Comment by heckflosse** [comment]
As this is a very rare camera back (also having non square sensels) I am not willing to spend time on fixing all issues with this camera back in RT. I could provide very basic support, but then Auto-Matched Tonecurve segfaults, which would require further work and analysis. I intend to close the issue as `unsupported` except someone is willing to create a pr to fix the issues

**Comment by wtanmdt** [comment]
@wheropl I am trying to upload the picture, but something goes wrong with this forum and I do not succeed. I will try other ways.

**Comment by wtanmdt** [comment]
![IMGP9624-ss](https://user-images.githubusercontent.com/34220266/67399686-3376a080-f572-11e9-9f58-f0058e7c61df.jpg)
 @wheropl here you are.

**Comment by wheropl** [comment]
@wtanmdt thank you very much -i guess i'll have try to find one up for sale now (or two cuz one of my friends also told me he'd gladly get one if the price was reasonable (in his case compared to newer solutions) )...  i wanted to confirm that it's actually possible to get one / find one out in the wild .. out of curiosity if you can remember how much did you pay for yours?

**Comment by wtanmdt** [comment]
@wheropl I paid more than $4000 to get it. And I used an agent to bid and ship it from Yahoo Auction at Japan. This digital back is very rare.

**Comment by wheropl** [comment]
ok thx - will look out and try to snatch one if it pops up

**Comment by wtanmdt** [comment]
@wheropl FYI, PaintShop Pro 2020 and Affinity Photo are all supporting RAW file of this digital back now.

**Comment by bronekkozka** [comment]
Hi there, I'm interested in talking to you about the fuji digital back, please contact me bronek@kozka.com or instagram :
https://www.instagram.com/kozka/
