### ISSUE TITLE
Noise Reduction median filter in L*a*b* mode seems to have no effect

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4208]
5.3-251-g a5571a43
https://filebin.net/l8nauxczfef02f8d/DSC05525.ARW
https://filebin.net/l8nauxczfef02f8d/DSC05525_median.png.out.pp3

It seems that the median filter has no effect in any of the L\*a\*b\* "median methods".

Apply the PP3, zoom to 100%, turn median off/on.

**Comment by Floessie** [comment]
That's strange, because I just developed an ISO 800 image last night and had to turn "median 3x3 soft" on in L*a*b* mode. Worked as desired...

**Comment by Beep6581** [comment]
@Floessie does turning it off/on have any effect on my raw+PP3?

**Comment by Beep6581** [comment]
Median on:
![dsc05525_median_crop_on](https://user-images.githubusercontent.com/5844619/33649422-37e3898e-da5e-11e7-9d3e-16d33756a9f7.jpg)
Median off:
![dsc05525_median_crop_off](https://user-images.githubusercontent.com/5844619/33649432-3dcb9508-da5e-11e7-8514-5e9ff10c753d.jpg)

**Comment by Beep6581** [comment]
If I lower "Luminance - Detail" at the top of the NR tool from 70 to 0, then median has an effect. I am surprised, because I was always under the impression that median is the last step in the NR chain. I thought so for two reasons:
1. Median is at the end of the NR interface.
2. RawPedia, "Use this filter to remove tiny, sharp-looking artifacts _left-over from noise reduction_."

So is it wrong that median is completely dependent upon the luminance controls, and has it always been like that?

**Comment by agriggio** [comment]
median is still at the end afaik.
could it be that there's too much noise left and you are using a too small radius, so median is hardly noticeable? (I didn't check your pp3, just speculating...)

**Comment by Beep6581** [comment]
@agriggio the median size and strength in my PP3 are at maximum, and median has the expected strong effect when luminance strength and luminance details are at 0, i.e. it depends on them, and does not seem to be discretely after them.

**Comment by agriggio** [comment]
ok. I'll take a look when I can (others feel free to precede me! :-)

**Comment by Desmis** [comment]
Hello
I do not know if this has always been like that, but after a short test, just invert the "median Lab" and "Fourier transform detail" treatments and everything is back to normal.

@agriggio 
I can make a patch if you wish  :)
jacques

**Comment by agriggio** [comment]
@Desmis Jacques sure :+1: for me. I have no time right now...

**Comment by Desmis** [comment]
I just push a change in branch "mediandenoise".  :)

Jacques

**Comment by Beep6581** [comment]
Thank you Jacques. Tested, now it works independently. I think it's better like this.

P.S. There are a lot of unrelated whitespace changes in the commit 3e76d861efb32a5dd9b29df9d7a20f47363e191a. It would be good to leave them out when merging so that the actual code change is visible.

**Comment by Desmis** [comment]
@Beep6581 

Ok, but how does one go back with "astyle", and then it will be good to proceed "astyle"

**Comment by Beep6581** [comment]
@Desmis astyle has no undo feature, but it can be fixed quite easily in git:
```
git checkout mediandenoise
git reset HEAD^                     // undo the commit but keep all changes
git checkout -b mediandenoise_clean // switch to new branch mediandenoise_clean
git checkout -p                     // delete the hunks (parts of code) which we don't want, so press "y" for everything except the code changes
git commit -a                       // commits the cleaned-up code
```

The astyle changes were good, but it's good to keep style changes separate from code changes, in their own commit.

**Comment by Beep6581** [comment]
I actually went ahead and did that and opened a PR. @Desmis you can merge it if the changes are good: #4211
