### ISSUE TITLE
Segfault in noise reduction/highlight reconstruction blend

### ISSUE THREAD

**Issue by ghost** [Beep6581/RawTherapee#4214]
I'm currently batch-editing a couple of older raw-pictures, and I consequently get a segfault when trying to finish the queue. This is what I get if I run a debug build through gdb:
[https://pastebin.com/i0gqT68y](https://pastebin.com/i0gqT68y)

Sorry if I got the subject wrong, but that's what gdb spat out, and the queue finishes fine if I turn "Noise Reduction" completely off.

Version: 5.3-253-g58c9f5a4
Branch: dev
Commit: 58c9f5a4
Commit date: 2017-12-06
Compiler: cc 7.2.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.22.2
Lensfun: V0.3.2.0
Build type: release
Build flags:  -std=c++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -O3 -DNDEBUG -ftree-vectorize
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON

**Comment by heckflosse** [comment]
> a couple of older raw-pictures

with odd width?

**Comment by ghost** [comment]
Sorry Ingo, they are all raw files from Nikon D700. I had to google the dimensions, but no, they are even-numbered :-)

**Comment by heckflosse** [comment]
Do they all crash?
Can you post a pp3 please?

**Comment by ghost** [comment]
Sure! Can you access this one?
[https://www.dropbox.com/sh/6hlvoiqx7aaksqb/AACtNFPYMgNb-ZNERV3OCh3Pa?dl=0](https://www.dropbox.com/sh/6hlvoiqx7aaksqb/AACtNFPYMgNb-ZNERV3OCh3Pa?dl=0)

**Comment by heckflosse** [comment]
yes, but I had to edit your post to access them with a single click ;-)

**Comment by heckflosse** [comment]
Can you try to rule out other tools (i.e. profiled lens vignetting corrections) as the reason?

**Comment by heckflosse** [comment]
@mks9900 Johan, not related to this issue: We ship a `NIKON D700.dcp`. @Beep6581 made it from colorchecker shots he made with my D700 some weeks ago. Maybe worth a try ...

**Comment by ghost** [comment]
Thanks Ingo, but I already thought that profile was selected? I read about your effort and they were greatly appreciated by me :-)
In RT, I chose "Auto-matched camera profile"...
I'll try to get on ruling out other tools now!

**Comment by heckflosse** [comment]
Johan, you're right. The dcp is selected by "Auto-matched..."

**Comment by ghost** [comment]
I can now say for certain it is denoise that causes the crash, but not with every file. I uploaded the troublesome file and pp3 and if I toggle denoise on/off I get crash/no crash repeatedly...
[Dropbox link, done correctly :-)](https://www.dropbox.com/sh/6hlvoiqx7aaksqb/AACtNFPYMgNb-ZNERV3OCh3Pa?dl=0)

**Comment by heckflosse** [comment]
Thanks Johan. I will try to find the culprit

**Comment by heckflosse** [comment]
Johan, though it crashes in denoise, the culprit is not denoise.
Can you confirm that it does not crash when highlight reconstruction is disabled?

**Comment by ghost** [comment]
Yes, I can certainly confirm that! Wow, nice work Ingo! 
However, for me,it seems it only crashes if method=Blend, does it crash there for you too?

**Comment by heckflosse** [comment]
yes

**Comment by Beep6581** [comment]
Simpler test case, apply neutral then this PP3:
https://filebin.net/ethqfut80kndq62j/rt_4214_crash.pp3

-- Edit
Note: the `[Color Management]` section shouldn't be in that PP3 - #4216

**Comment by Beep6581** [comment]
And the stack backtrace:
https://paste2.org/zaVx83Ma

**Comment by agriggio** [comment]
Fixed in d7fb8c9
