### ISSUE TITLE
Partial profile always saves color management > output profile intent

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4216]
`dev` `5.3-253-g`58c9f5a4

Saving a partial PP3 with nothing selected saves this:
```
[Version]
AppVersion=5.3-253-g58c9f5a4
Version=328

[Color Management]
OutputProfileIntent=Relative
```

Also, the "Basic settings" checkbox once clicked always shows in that [-] mode and cannot be changed.

![imgur-2017_12_08-00 07 20](https://user-images.githubusercontent.com/5844619/33743141-da95696a-dbab-11e7-909d-7d4a8b45fbdb.png)

**Comment by Hombre57** [comment]
@Beep6581 Trivial patch, tested successfully here, so closing. I made some code refactoring for simplification too.
