### ISSUE TITLE
Maximum width and height in fast export is capped at 3000

### ISSUE THREAD

**Issue by Timmitry** [Beep6581/RawTherapee#4220]
Hi,
I want to batch process my raw images to jpeg with RawTherapee. As can be seen in the screenshot, I can't set the maximum width or height higher than 3000. However, I don't want my images to be resized at all. Is there any way to set this limit higher, or deactivate resizing completely?
I'm using RawTherapee on Windows 10.
Thanks,
Tim

![rawtherapee](https://user-images.githubusercontent.com/20927653/33804290-2198ebc8-dda2-11e7-8287-e03d15b3f0ca.png)

**Comment by heckflosse** [comment]
@Timmitry Use a newer version. You can download rt 5.3 for windows [here](http://rawtherapee.com/downloads)

**Comment by Beep6581** [comment]
@Timmitry also, not sure you're aware of it, you're using "fast export" which is not the "proper" way of exporting images.
See:
http://rawpedia.rawtherapee.com/Getting_Started
http://rawpedia.rawtherapee.com/The_Batch_Queue

We have yet to write documentation for Fast Export...

**Comment by Timmitry** [comment]
@heckflosse Thanks for the hint to the new version - I'll try it out these days!

@Beep6581 For now, I only wanted to generate JPEGs from my RAWs, and not edit each picture manually. I'm not sure if RT does some optimizing with the fast export, that would be nice, but if not, that's okay too. Thanks for the links, I'll hopefully start learning some basics soon...

**Comment by Timmitry** [comment]
Sorry to bother again - I tried the fast export with a new version of RawTherapee.
If I set maximum width and height to e.g. 10000, it will resize all images to either 10.000 pixels width or height, although the original images are only 5184x3456 pixels... How can I disable the resizing?

**Comment by agriggio** [comment]
@Timmitry sounds like a bug, I'll investigate. but what's the use case for this? (just curious)

**Comment by Timmitry** [comment]
@agriggio I want to convert my RAW images to JPGs, with automatic optimization from RawTherapee (e.g. some pictures are way too dark). It does a good job with that!

For now, I'll solve the problem by setting the max width and height to my cameras pixel width.

**Comment by agriggio** [comment]
@Timmitry there's no need for the "fast export" for that. If you want a bare-bones conversion with no rescaling, just apply the "(Neutral)" profile and use the normal export

**Comment by heckflosse** [comment]
@Timmitry The advantage of `Fast export` is improved processing time for downsized images. If you don't downsize, just `Put to queue` instead of `Put to queue (fast export)`

**Comment by Timmitry** [comment]
Ha, I see, that's what I was searching for... I now applied `Neutral`-profile to all pictures, then enabled `Auto Levels`, and then `Put to queue`. Thank you all for your support!
