### ISSUE TITLE
Multiple source file and frame handling

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4221]
This issue is to discuss how to handle our growing needs of being able to use more than one frame and/or more than one source image to generate one resulting image.

The feature should be simple and cover as wide a variety of use cases as possible.

# Selection

Requirements:
- Open a single raw file with a single frame (1 layer).
- Open a single raw file with a single frame - Sony Pixel Shift (1 layer).
- Open a single raw file with multiple frames - Pixel Shift (>=1 layer).
- Open a single raw file with multiple frames - Canon Dual-ISO, Fuji Super-CCD (2 layers).
- Open several raw files with a single frame each - (HDR) blending, manual ghost removal using local editing, etc. (>=2 layers).
- Open several raw files with a several frames each - e.g. blending using Pixel Shift images (>=2 layers).

RawTherapee needs to show in a user-friendly way which images are being used. I propose a new panel which shows all the files which are available for use in the current Editor tab. This could be done in one of two ways:
1. This panel could be implemented as an alternate Filmstrip mode, lets call it "Layers". The Filmstrip would have a togglebutton to switch between traditional Filmstrip mode and Layers mode. This would probably require less coding as it would re-use the Filmstrip.
2. A better (ideal?) solution would be to have the typical Layers panel we all know from GIMP and that other well known photo program for shop owners. Maybe built from a GTK+ treeview.

The user would select all files which they want to use from the File Browser level or from the Filmstrip level. These files would appear in the Layers panel. This solution would allow the user to either select the images manually, or to have RawTherapee select them automatically based on Exif.

# Metadata

Seeing all source images as layers would enable the user to decide which image the [final metadata](https://github.com/jcelaya/hdrmerge/blob/master/ExifTransfer.cpp) comes from. There could be a thumbnail overlay button or context menu entry for selecting the source image for metadata.

Related: Adopt libexiv2 or ExifTool for metadata handling #3801

# Merging

Merging in the loose sense, includes Enfuse, HDRMerge and manual on-canvas painting for [masking](https://github.com/jcelaya/hdrmerge/blob/master/EditableMask.cpp). All images which are in the layers panel and are not marked as "hidden" get merged.

Images with sizes which do not match get anchored to e.g. the bottom-left corner. This allows for overlaying watermark images.

Layers can be offset x/y. HDRMerge [allows this](https://github.com/jcelaya/hdrmerge/blob/master/ImageStack.cpp#L80) for raw files.

**Comment by Beep6581** [comment]
The user will need to be able to adjust at least some parameters per layer.
Related: Snapshot support/multiple PP3 per image support #2624

**Comment by sguyader** [comment]
That would be a nice tool in RT's arsenal. Would that eventually allow
merging xtrans images for HDR blending/tonemapping?

**Comment by Beep6581** [comment]
Duplicate of #1972
