### ISSUE TITLE
Border artifacts using RCD demosaicing

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4225]
Purple border artifacts using RCD.

Tested using a SONY SLT-A77V raw file from:
https://filebin.net/vko4wznvvaulyz40/DSC00989.ARW
Mirror: https://discuss.pixls.us/t/playraw-presolana-was-salvaging-a-raw/5769/4

Branch: colortab-tools-onoff
`15.3-283-g`11ca61e

![imgur-2017_12_12-08 43 15](https://user-images.githubusercontent.com/5844619/33872772-84aaa838-df18-11e7-8ccd-d587c21d7f02.png)

**Comment by agriggio** [comment]
Here's a patch, can you please test?
```diff
diff --git a/rtengine/demosaic_algos.cc b/rtengine/demosaic_algos.cc
--- a/rtengine/demosaic_algos.cc
+++ b/rtengine/demosaic_algos.cc
@@ -4213,7 +4213,7 @@
         }
     }
 
-    border_interpolate2(width, height, 4);
+    border_interpolate2(width, height, 8);
 
     if (plistener) {
         plistener->setProgress(1);
```

**Comment by Beep6581** [comment]
The artifacts are gone.

There is room for improvement, but that's probably unrelated to this specific issue.

Before:
![1 - rcd before](https://user-images.githubusercontent.com/5844619/33908918-388db6bc-df8a-11e7-8f6b-ebe8f7d6098c.png)

After, RCD:
![2 - rcd after](https://user-images.githubusercontent.com/5844619/33908923-3bffb192-df8a-11e7-8e40-2d381949484e.png)

AMaZE:
![3 - amaze](https://user-images.githubusercontent.com/5844619/33908926-3ed97560-df8a-11e7-9f15-0161e5956cf3.png)

DCB:
![4 - dcb](https://user-images.githubusercontent.com/5844619/33908927-410899b0-df8a-11e7-940a-5eb457a193b8.png)
