### ISSUE TITLE
TP_TM_FATTAL_ALPHA, TP_TM_FATTAL_BETA keys in Preferences/Batch processing

### ISSUE THREAD

**Issue by mkyral** [Beep6581/RawTherapee#4229]
In Preferences / Batch processing window, in section HDR Tone Mapping are keys TP_TM_FATTAL_ALPHA and TP_TM_FATTAL_BETA instead of text.

![obrazek](https://user-images.githubusercontent.com/155542/34004607-a452c2ce-e0f8-11e7-858f-e1662bff1c36.png)

These keys are in code only once. I think keys TP_TM_FATTAL_AMOUNT and TP_TM_FATTAL_THRESHOLD should be used.

```c
rtgui/preferences.cc:    mi->set_value (behavColumns.label, M ("TP_TM_FATTAL_LABEL"));
rtgui/preferences.cc:    appendBehavList (mi, M ("TP_TM_FATTAL_ALPHA"), ADDSET_FATTAL_ALPHA, false);
rtgui/preferences.cc:    appendBehavList (mi, M ("TP_TM_FATTAL_BETA"), ADDSET_FATTAL_BETA, false);
rtgui/fattaltonemap.cc:FattalToneMapping::FattalToneMapping(): FoldableToolPanel(this, "fattal", M("TP_TM_FATTAL_LABEL"), true, true)
rtgui/fattaltonemap.cc:    amount = Gtk::manage(new Adjuster (M("TP_TM_FATTAL_AMOUNT"), 1., 100., 1., 0.0));
rtgui/fattaltonemap.cc:    threshold = Gtk::manage(new Adjuster (M("TP_TM_FATTAL_THRESHOLD"), -100., 100., 1., 0.0));
```

**Comment by heckflosse** [comment]
Thanks for reporting. Bug confirmed

**Comment by heckflosse** [comment]
@agriggio Alberto, can you take this one? I don't remember whether amount corresponds to alpha or beta...

**Comment by agriggio** [comment]
sure!
