### ISSUE TITLE
Loading partial pp3 profiles resets all other parameters

### ISSUE THREAD

**Issue by albfe** [Beep6581/RawTherapee#4234]
In the development versions (from github), when opening a pp3 profile that does not contain all parameters (e.g., it contains only parameters on black and white transformation), all the other parameters are incorrectly reset. Even trying to load the profile with CTRL+load and selecting only the relevant options causes the same problem.

**Comment by TooWaBoo** [comment]
Uncheck this button :-)

![grafik](https://user-images.githubusercontent.com/13800920/34079623-830fe46c-e331-11e7-9bef-07a042eb351e.png)

**Comment by albfe** [comment]
Oops, sorry that I missed this option, it works! :)
