### ISSUE TITLE
Before/After view gives wrong output for before view in localcontrast branch

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#4239]
Screenshot with history should be enough to reproduce

![grafik](https://user-images.githubusercontent.com/13733487/34226442-08415f4a-e5ca-11e7-9435-642f4b523f6a.png)

Edit: To easily reproduce, open an image, apply the attached pp3 file and activate before/after view

[labbug.pp3.txt](https://github.com/Beep6581/RawTherapee/files/1576891/labbug.pp3.txt)

Edit: I labeled `Priority-Critical` because it sometimes even segfaults...

**Comment by heckflosse** [comment]
Please ignore the issue until I found the reason...

**Comment by heckflosse** [comment]
Seems to occur only in localcontrast branch.
To reproduce:

Clear processing profile for a file in file-browser.
Open that file
Enable before/after view.
=> sometimes black, somtimes white, sometimes segfault

**Comment by agriggio** [comment]
I'll take a look, I guess it's related to my procevents/refreshmap restructuring

**Comment by heckflosse** [comment]
@agriggio Thank you 👍

**Comment by agriggio** [comment]
found the problem, working on a fix

**Comment by agriggio** [comment]
@heckflosse Ingo can you test please?

```diff
diff --git a/rtengine/rtengine.h b/rtengine/rtengine.h
--- a/rtengine/rtengine.h
+++ b/rtengine/rtengine.h
@@ -413,6 +413,7 @@
       * The image update starts immediately in the background. If it is ready, the result is passed to a PreviewImageListener
       * and to a DetailedCropListener (if enabled). */
     virtual void        endUpdateParams (ProcEvent change) = 0;
+    void endUpdateParams(ProcEventCode change) { endUpdateParams(ProcEvent(change)); }
     virtual void        endUpdateParams (int changeFlags) = 0;
     // Starts a minimal update
     virtual void        startProcessing (int changeCode) = 0;
```

**Comment by heckflosse** [comment]
@agriggio compiling...

**Comment by heckflosse** [comment]
@agriggio Your patch fixed it \o/
