### ISSUE TITLE
Document the Local Contrast tool

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4243]
The Local Contrast tools needs to be documented:
1. Explain what it does and how it does it.
2. Which colorspace is used.
3. Between which tools it lies in the pipeline.
4. Describe the sliders.

**Comment by agriggio** [comment]
Will do. Also HDR Tone Mapping needs some docs probably.

**Comment by Beep6581** [comment]
I hope to find time for this next week.

I posted about it today:
https://plus.google.com/b/106783532637761598368/+rawtherapee/posts/jL6r2izuHrx
We can re-use those screenshots for RawPedia.
https://filebin.net/k82hy7deaw98e847

**Comment by agriggio** [comment]
@Beep6581 here's a description of what it does and how. The only missing part is the description of the "darkness" and "lightness" sliders, which are essentially just ways of giving more boost to the shadows and highlights in the local contrast mask:
http://www.cambridgeincolour.com/tutorials/local-contrast-enhancement.htm

**Comment by agriggio** [comment]
More info: operates in LAB space (on the L channel), applied right after RGB processing and before other LAB processing.

**Comment by Thanatomanic** [comment]
http://rawpedia.rawtherapee.com/Local_Contrast

I've made a preliminary text and provided an example.
