### ISSUE TITLE
Document the HDR Tone Mapping tool

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4245]
The HDR Tone Mapping tools needs to be documented:
1. Explain what it does and how it does it.
2. Which colorspace is used.
3. Between which tools it lies in the pipeline.
4. Describe the sliders.
5. How to use it.

**Comment by agriggio** [comment]
@Beep6581 here's a description of what it does and how. The only missing part is the description of the "darkness" and "lightness" sliders, which are essentially just ways of giving more boost to the shadows and highlights in the local contrast mask:
http://www.cambridgeincolour.com/tutorials/local-contrast-enhancement.htm

**Comment by agriggio** [comment]
More info: operates in LAB space (on the L channel), applied right after RGB processing and before other LAB processing.

**Comment by agriggio** [comment]
Some info: operates in RGB space, and is applied at the beginning of the pipeline, right after denoising, but before the tone curve controls
