### ISSUE TITLE
Perspective correction not rotated when rotating image

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4251]
https://filebin.net/diadde2v6zitc8pv

Use "rotate left/right" or "flip horizontal/vertical". I noticed that the crop was wrong afterwards. Then I removed the crop and set horizontal perspective correction to 50, rotated, and the correction was not rotated with the image!

**Comment by Beep6581** [comment]
To reproduce:
* Open any image
* Un-check Auto-fill
* Horizontal perspective correction 100
* Rotate or flip.

![imgur-2017_12_24-13 17 38](https://user-images.githubusercontent.com/5844619/34326457-d9be79e2-e8ac-11e7-827e-e35bffe167f2.png)

**Comment by heckflosse** [comment]
For the my old D1x files in portrait orientation (D1x had no orientation sensor) the current behaviour is fine :)

**Comment by agriggio** [comment]
why is this a bug? I'm not sure...

**Comment by heckflosse** [comment]
I agree with @agriggio that it's not a bug. Perspective correction is simply called after rotation.

**Comment by Beep6581** [comment]
Perspective correction should be relative to the image the same way rotation and graduated filters are.

Real life example: I tweaked, cropped and perspective-corrected 36 images of abstract paintings, then found out some of them were not oriented correctly, so I fixed that, and by doing so the crops were now wrong and I had to re-perspective-correct and re-crop all affected images.

If you mean why did I mark this as a bug and not a feature request, it's because it matches the definition of a bug from a usability perspective:
> A software bug is an error, flaw, failure or fault in a computer program or system that causes it to produce an incorrect or unexpected result, or to behave in unintended ways

Feel free to change the label.

**Comment by agriggio** [comment]
@Beep6581 do you expect the GUI to be updated as well? (I mean swapping the values of horizontal and vertical perspective correction when rotating the image).
Also, FWIW the graduated filter currently behaves as the perspective correciton: if the image is rotated, the filter becomes "wrong"

**Comment by heckflosse** [comment]
@Beep6581 I disagree. The perspective correction (horizontal/vertical) should be relative to a horizontal/vertical line, which currently is the case. If you change that by coarse rotation (i.e. 90°) you have to change the perspective correction too.

> that causes it to produce an incorrect or unexpected result, or to behave in unintended ways

In first step we have to get an agreement about the expected result ;-)

Crop is a different story.

**Comment by Beep6581** [comment]
@agriggio the crop tool's values are changed when coarse rotation changes, so it would be nice for these to change as well. But I'm no longer sure what I'm requesting is possible - please read on.

@heckflosse Good point. I agree that there are situations, perhaps even the majority, where perspective correction locked to the viewport and not to the image is a good thing, i.e. perhaps in the majority of cases what I'm suggesting is a bad idea.

Here's an example:
https://filebin.net/ngl721we8x5ndg98/DSC05089.ARW
![imgur-2017_12_29-11 59 59](https://user-images.githubusercontent.com/5844619/34435691-d2cce506-ec8f-11e7-9941-de7b9f04f8e0.png)

Everyone would start off by rotating this image 90° CCW, and then fixing the perspective.
If perspective was locked to the image and not to the viewport, then after the rotation "Horizontal" perspective correction would adjust it vertically, and that would feel wrong.

But what if it's an image where "up" is not clear? As in my example in the first post. It's a real-world example which cost me an hour to fix across all affected photos, because I only found out at the end how they're supposed to be oriented. In that case, locking perspective correction to the image would be good.

So my refined position is that the current behavior - perspective rotation locked to the viewport - is correct in the majority of cases (since the majority of photos are not abstract and clearly have an "up" side), but optionally being able to lock perspective adjustment to the image would be "nice to have".

Locking perspective adjustment to the image regarding coarse rotation should be possible. But is it still possible when using fine rotation? Because if it's not possible, then I scrap this whole idea.

The crop tool is locked to the image only regarding coarse rotation, not fine rotation:
![imgur-2017_12_29-12 09 48](https://user-images.githubusercontent.com/5844619/34435913-5ae49776-ec91-11e7-82d3-352b1411fd75.png)
![imgur-2017_12_29-12 09 58](https://user-images.githubusercontent.com/5844619/34435914-5b0142c2-ec91-11e7-829d-9fa6a1903ea4.png)
![imgur-2017_12_29-12 10 58](https://user-images.githubusercontent.com/5844619/34435915-5b23f4ac-ec91-11e7-9561-27d2282b3630.png)

**Comment by Beep6581** [comment]
Closing for lack of interest.
