### ISSUE TITLE
Possible speedups in rgbProc() using the vectorized LUT access from @gatoatigrado and a modification for LUTs which don't clip

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#4259]
This issue is about possible speedups using the he vectorized LUT access code provided by @gatoatigrado 👍 and a modification of that code for LUTs which don't clip.

In first step, I made the following improvements:

1. used the vectorized LUT access also for Tone Curve 2

2. made some slight mods to the code to use the vectorized LUT access also for another 2 steps in rgbProc which are executed always (independent on pp3 settings)

The speedups are in [this branch](https://github.com/Beep6581/RawTherapee/commits/rgbroc_speedup)

**Comment by agriggio** [comment]
@heckflosse what is needed for merging this?

**Comment by heckflosse** [comment]
@agriggio No objection from me to merge this, though I have further changes on hold for rgbproc()

Edit: I have to add at least one `#ifdef __SSE2__` before merge

**Comment by heckflosse** [comment]
@agriggio I just pushed the changes I had on hold. No objection from my side to merge this now to get more tests

**Comment by heckflosse** [comment]
@agriggio Merged

**Comment by agriggio** [comment]
great, thanks!
