### ISSUE TITLE
Speedup for perceptual tone curve

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#4269]
Compared to other tone curves, perceptual tone curves are really slow.

Example: processing time of rgbproc for a 36MPixel file using neutral profile + Tone curce 1

```
Weighted Standard:  450 ms
Perceptual:        4235 ms
```
I created [a new branch](https://github.com/Beep6581/RawTherapee/tree/perceptual_curve_speedup) to speed up perceptual tone curves. First change leads to a small 4% speedup

```
Perceptual:        4065 ms
```

Further speedups will follow

**Comment by heckflosse** [comment]
Processing time with last commit

```
Perceptual:        3150 ms
```

**Comment by Beep6581** [comment]
Tested 0fcc1987a5bbc301bca50485e08206adf2eff1a4 and found no issues.

**Comment by heckflosse** [comment]
For information: with https://github.com/Beep6581/RawTherapee/commit/24a762c2c23541f581f05e20e0f16b7220d3cddd the processing time is < 3000 ms
