### ISSUE TITLE
Whole hue range curve color bar

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4271]
The "whole hue range" curve color bar starts and ends with red. The second-last color is purple, and because of the extra red row when I look at the bar at normal 100% size it looks like the purple part is larger than it should be. Why is red repeated, and if there is no good reason for that, let's remove it.

1600% zoom:
![imgur-2018_01_01-17 04 49](https://user-images.githubusercontent.com/5844619/34469053-b0bbc28c-ef16-11e7-9b62-30185b2d21b0.png)

**Comment by Hombre57** [comment]
That's an interpolation in the HSL color space. I don't think it really matters.

**Comment by Hombre57** [comment]
Is this any better ? I don't see a real difference IMHO. You can play with the first parameter of `Color::hsv2rgb01` given than valY will goes from 0.0 (top pixel) to 1.0 (bottom pixel).

Then you'll have to make that change in every place that this kind of colorbar appears.

![new-hue-range](https://user-images.githubusercontent.com/13788115/34469534-694fbb82-ef21-11e7-8ae9-ce8d99681a7d.png)

```patch
diff --git a/rtgui/labcurve.cc b/rtgui/labcurve.cc
index 6cbf118..90df169 100644
--- a/rtgui/labcurve.cc
+++ b/rtgui/labcurve.cc
@@ -578,7 +578,7 @@
         float value = (1.f - 0.7f) * float(valX) + 0.7f;
         // whole hue range
         // Y axis / from 0.15 up to 0.75 (arbitrary values; was 0.45 before)
-        Color::hsv2rgb01(float(valY), float(valX), value, R, G, B);
+        Color::hsv2rgb01(float(valY*0.9), float(valX), value, R, G, B);
     } else if (callerId == 6) {  // cc - left bar
 
         float value = (1.f - 0.7f) * float(valX) + 0.7f;
```

**Comment by Beep6581** [comment]
0.8 looks pretty good:
![08](https://user-images.githubusercontent.com/5844619/34469634-e5eb47d6-ef23-11e7-8d3a-96bf7f493b81.png)

What do you think?
