### ISSUE TITLE
Slower loading time linked to lensfun db being loaded entirely in memory

### ISSUE THREAD

**Issue by esby** [Beep6581/RawTherapee#4286]
(edit: there is a bug in my fork, not on the main rt tree)

I think there is some kind of  issue with loading the lensfun db entirely into the associated combobox:

I think It affects RawTherapee 5.3 (from git).

Here, on an intel Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz, it takes 5.4 seconds to load lensfun db into the combobox.

If I trim the xml lensfun db to only the optics I uses (panasonic and olympus), by only keeping 
mil-panasonic.xml and mil-olympus.xml
 this loading time becomes 0.14 seconds.

(Note: On an Amd Phenom II X-6, the loading time is reducted still, but still longer with the whole db.)

So, either:
* the loading issue needs to be fixed. This is probably fixed to the way the Gtk::combobox is filled.
* the loaded items should be limited to the lens encountered by the user and loaded when needed.
* the loaded items should be limited to the lens encountered by the user and loaded from a local database only containing those entry and possibly maintained by an external tool or external process.

Work around: 
1 - remove the xml files from lens db you don't need.
(put them into a subdir for example)
it is located under /usr/share/lensfuns/version_1 on debian 9.
2 - edit the xml files if you know how to perform it.

(Note: DrSlony on IRC told me to contact  @Hombre57  and @agriggio about it )

**Comment by esby** [comment]
bash script to measure the loading time under Debian 9

invoke it a first
#!/bin/bash
new="false"

if [ -f log1.time ] && [ -f log1.txt ]
then
  if [ "$1" = "new" ];
  then
    echo "benchmark was requested again"
    new="true"
  else
    echo "benchmark files are already present, use new as a parameter to regenerated these"
  fi
else
  new="true"
fi

if [ "$new" = "true" ];
then
  echo "executing benchmark tests"
  script --timing=log1.time log1.txt -c ./test_rt1.sh > /dev/null
  script --timing=log2.time log2.txt -c ./test_rt2.sh > /dev/null
fi

function get_time()
{
  startS="$1"
  startMS="$2"

  s=$(($SECONDS - $startS ))
  ms1=$(echo $(date "+%3N") | sed 's/^0*//' ) 
  ms2=$(echo $startMS | sed 's/^0*//' ) 
  ms=$(( 1000 +  "$ms1" - "$ms2" % 1000 ))
  echo $s.$ms
}

if [ "$1" == "1" ];
then
  echo "first benchmark"
  startMS=$(date "+%3N" )
  startS="$SECONDS"
  scriptreplay -t log1.time log1.txt | while read x ; do echo $(get_time "$startS" "$startMS") $x ; done 
fi

if [ "$1" == "2" ];
then
  echo "second benchmark:"
  startMS=$(date "+%3N" )
  startS="$SECONDS"
  scriptreplay -t log2.time log2.txt | while read x ; do echo $(get_time "$startS" "$startMS") $x ; done 
fi

**Comment by agriggio** [comment]
@esby what time are you referring to exactly? Do you mean that if you click on the combo box, it takes ~5 seconds to open the combo? Or are you talking about the startup time of RT? Can you please clarify? Also, which GTK+ version are you using?

**Comment by esby** [comment]
I am talking of the startup time. 

I thought the RT5 version was using gtk3 only ? I am mistaken ?

**Comment by Beep6581** [comment]
On my system, the lensfun DB seems to load instantly (verbose=true), while the combobox is sluggish and takes a second to open. GTK+ 3.22.19.

@esby which version of GTK3 are you using, and which version of lensfun?

**Comment by agriggio** [comment]
> I am talking of the startup time.

So are you sure the time is spent filling the combobox, and not simply parsing the lensfun DB?
Anyway, if it's only startup time, it can be annoying but I wouldn't say it's critical... if on the other hand it takes ~5 seconds to open the combo box every time you use it, then it's another story.

> I thought the RT5 version was using gtk3 only ?

Yes, but still there are different GTK3 versions -- I'm still on 3.18.x

**Comment by agriggio** [comment]
@Beep6581 combo boxes in GTK+3 are known to be slow (if you search the web you'll find other references) and not really suitable to many entries. To fix the performance problem, we would need to roll our own. But my interest is fairly low for this, sorry -- performance is acceptable for me even on my old laptop, so it's just not worth the effort. 
Patches are always welcome of course :-)

**Comment by Beep6581** [comment]
Combobox performance is acceptable for me too. I'd rather time was spent on [other parts](http://3.bp.blogspot.com/-O52PK0gXTP0/T1ZJY-J0lLI/AAAAAAAAAJo/wOUiVJlIMYQ/s1600/Super+Pipeline+2+screen1.jpg) of RawTherapee ;)

**Comment by esby** [comment]
(gtkmm 3.22.0-1 (according to dpkg))

Well I may have made a mistake somewhere, 
I was testing on my ported fork;
I just tested on the main version.

0.1299s loading lens done, on my fork I was getting 1.29s with verbose=false, 3.135s with verbose=true.
I am trying to reduce the initial loading time as much as I can as it affects my usage in single editor mode.
I guess there is something wrong on my fork here.

Note: it also turns out my script to calculate the timings measured was wrong. Nothing is actually wrong...

**Comment by heckflosse** [comment]
@esby Ok to close the issue?

**Comment by esby** [comment]
yes, sorry for raising a non existent issue.

Most of the abnomaly was linked to my method to measure it actually.

**Comment by heckflosse** [comment]
@esby In case you compile rt yourself, have a look at "StopWatch.h" and BENCHFUN to measure processing times. Quite easy to add some StopWatches to the source ;-)
