### ISSUE TITLE
Release notes: RPU

### ISSUE THREAD

**Issue by LebedevRI** [Beep6581/RawTherapee#4296]
As discussed in `#pixls.us`:
It would be super great if RawTherapee could include some text about [RPU](https://raw.pixls.us/) into it's release notes.
We do that for dt already, but i would imagine that the audience overlap is not 100% :)

For dt we do:
```
#### Important note: to make sure that darktable can keep on supporting the raw file format
for your camera, *please* read [this post](https://discuss.pixls.us/t/raw-samples-wanted/5420?u=lebedevri)
on how/what raw samples you can contribute to ensure that we have the *full* raw sample set
for your camera under CC0 license!
```
I guess you will want to reword that :) But it is **really** important to link to the post and not the RPU itself, because it contains some more info/blurb.

**Comment by LebedevRI** [comment]
Just to clarify, if you think linking to the post is bad and linking to the RPU itself is better/less of a problem, then feel free to link to the RPU :) Spreading the word/link of RPU is the important bit here.

**Comment by heckflosse** [comment]
We should not forget this issue when we release 5.4
