### ISSUE TITLE
RawTherapee theme bug when editing node in/out values

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4300]
The RawTherapee theme has a bug: when you edit a node's in/out values, the out part's label turns blue and stays blue until you close RT.
![screenshot_20180113_202629](https://user-images.githubusercontent.com/5844619/34909385-0cb60d80-f8a0-11e7-8aae-63210a541a30.png)

**Comment by Beep6581** [comment]
Clicking on the GtkFlowBoxChild selects it, so I can make the left box blue by clicking on the "I:" label or the area around the spinbutton as the blue color shows. The problem is that this highlighting is distracting and unhelpful.

Something stupid like this works around the problem:
```css
flowboxchild:selected {
    background-color: inherit;
}
```

But the real problem is that the GtkFlowBoxChild shouldn't be able to receive focus.

**Comment by Beep6581** [comment]
I tried this but it didn't work:
```diff
diff --git a/rtgui/coordinateadjuster.cc b/rtgui/coordinateadjuster.cc
index c91ced05..f1222e0b 100644
--- a/rtgui/coordinateadjuster.cc
+++ b/rtgui/coordinateadjuster.cc
@@ -44,6 +44,8 @@ CoordinateAdjuster::AxisAdjuster::AxisAdjuster(CoordinateAdjuster *parent, const
 {
 
     label = Gtk::manage(new Gtk::Label(axis->label));
+    label->set_can_focus(false);
+    label->set_selectable(false);
     spinButton = Gtk::manage(new Gtk::SpinButton());
     spinButton->set_name("AxisAdjuster");
     spinButton->set_digits(axis->decimal);
@@ -126,6 +128,7 @@ void CoordinateAdjuster::createWidgets(const std::vector<Axis> &axis)
         currAdjuster->rangeUpperBound = currAxis->rangeUpperBound;
 
         Gtk::Grid *box = Gtk::manage (new Gtk::Grid());
+        box->set_can_focus(false);
         box->set_orientation(Gtk::ORIENTATION_HORIZONTAL);
         box->set_column_spacing(3);
 
```
@Hombre57 could you maybe take a look?

**Comment by Hombre57** [comment]
@Beep6581 Could you test this ?

```patch
diff --git a/rtgui/coordinateadjuster.cc b/rtgui/coordinateadjuster.cc
index c91ced0..209ef09 100644
--- a/rtgui/coordinateadjuster.cc
+++ b/rtgui/coordinateadjuster.cc
@@ -135,7 +135,11 @@
         box->attach_next_to(*(currAdjuster->spinButton), Gtk::POS_LEFT, 1, 1);
         box->attach_next_to(*(currAdjuster->label), Gtk::POS_LEFT, 1, 1);
 
-        add(*box);
+        Gtk::FlowBoxChild *fbChild = Gtk::manage(new Gtk::FlowBoxChild());
+        fbChild->set_can_focus(false);
+        fbChild->add(*box);
+
+        add(*fbChild);
     }
 }
 
```

**Comment by Hombre57** [comment]
@Beep6581 Committed to dev.

**Comment by Beep6581** [comment]
I can still focus the GtkFlowBoxChild by clicking on it, but it no longer auto-focuses when I use the Tab key.

**Comment by Hombre57** [comment]
@Beep6581 `Selected` and `Focused` are different thing. You can ask Gtk to disable focusing, but can't ask to disable the selection of the `FlowBoxChild`, so your first fix was the good one. Patch committed. Works fine here. I didn't tried to click on the label for my previous patch...

**Comment by Beep6581** [comment]
Thanks @Hombre57, looks good now.
