### ISSUE TITLE
HDR tool (Fattal) produce zoom dependant luminosity

### ISSUE THREAD

**Issue by Hombre57** [Beep6581/RawTherapee#4306]
[This image](https://filebin.net/ftonl97b5n4f2w2b) is using the Fattal tool (pp3 provided as well), but the overall luminosity depend on the zoom rate. Put a ColorPicker at X:4300 Y:1500 (coordinates from the Navigator) and make it as big as possible (Ctrl + Scroll up over the circle while still in ColorPicker mode).

You'll see that the luminosity is very different from e.g. 25% zoom rate over 20% (see below).

![fattal-luminosity-25](https://user-images.githubusercontent.com/13788115/34920500-fb67f488-f973-11e7-973e-4d186b56ad9b.png)  ![fattal-luminosity-20](https://user-images.githubusercontent.com/13788115/34920502-fe74a32e-f973-11e7-9615-fa95ee4e9160.png)

I know that the ColorPicker have fixed size (not depending on zoom rate), but the difference is clearly noticeable.

Added to the 5.4 milestone, since I think it's quite serious.

@agriggio Could you have a look ? I might be related to your recent change.

**Comment by agriggio** [comment]
@Hombre57 confirmed. Unfortunately, it's not very easy to fix with the current pipeline. It is related to my recent changes, but also to nondeterminism due by parallel processing (with openmp). 
This patch mitigates the problem, but it doesn't make it go away completely. Can you still give it a try and see if it is a bit better at least?

```diff
diff --git a/rtengine/tmo_fattal02.cc b/rtengine/tmo_fattal02.cc
--- a/rtengine/tmo_fattal02.cc
+++ b/rtengine/tmo_fattal02.cc
@@ -1125,6 +1125,19 @@
             constexpr float c = 65500.f;
             return rgb->r(y, x) < c && rgb->g(y, x) < c && rgb->b(y, x) < c;
         };
+    const auto biggerY =
+        [](float cur_Y, int cur_x, int cur_y, float prev_Y, int prev_x, int prev_y) -> bool
+        {
+            if (!prev_Y) {
+                return true;
+            }
+            float e = (cur_Y - prev_Y) / max(cur_Y, prev_Y);
+            if (std::abs(e) < 0.05) {
+                return (cur_x < prev_x) || (cur_x == prev_x && cur_y < prev_y);
+            } else {
+                return e >= 0.05;
+            }
+        };
     TMatrix ws = ICCStore::getInstance()->workingSpaceMatrix (params->icm.working);
 
     float max_Y = 0.f;
@@ -1142,7 +1155,7 @@
     for (int y = 0; y < h; y++) {
         for (int x = 0; x < w; x++) {
             Yr (x, y) = std::max (luminance (rgb->r (y, x), rgb->g (y, x), rgb->b (y, x), ws), min_luminance); // clip really black pixels
-            if (Yr(x, y) > max_YThr && unclipped(y, x)) {
+            if (biggerY(Yr(x, y), x, y, max_YThr, max_xThr, max_yThr) && unclipped(y, x)) {
                 max_YThr = Yr(x, y);
                 max_xThr = x;
                 max_yThr = y;
@@ -1152,7 +1165,7 @@
 #ifdef _OPENMP
 #pragma omp critical
 #endif
-    if (max_YThr > max_Y) {
+    if (biggerY(max_YThr, max_xThr, max_yThr, max_Y, max_x, max_y)) {
         max_Y = max_YThr;
         max_x = max_xThr;
         max_y = max_yThr;
```

**Comment by heckflosse** [comment]
@agriggio 

> nondeterminism due by parallel processing (with openmp)

Can you point me to the non deterministic part?

**Comment by agriggio** [comment]
@heckflosse there might be many pixels with the same luminance (`Y`) level, at different coordinates `(x, y)`. So `max_x`  and `max_y` get assigned nondeterministically, depending on whatever thread runs first. At least, that's my interpretation of what's happening... makes sense?

**Comment by heckflosse** [comment]
@agriggio 

> makes sense?

not for me

**Comment by heckflosse** [comment]
@agriggio ah, the calaculations based on max_x and max_y inside and outside the parallel region don't match...

**Comment by agriggio** [comment]
```
if (max_YThr > max_Y) {
   max_Y = max_YThr;
   max_x = max_xThr;
   max_y = max_yThr;
}
```

Suppose thread 1 has `max_YThr = 100`, `max_xThr = 1`, `max_yThr = 2`, and thread 2 has `max_YThr = 100`, `max_xThr = 50`, `max_yThr = 20`.
Without knowing which of the two threads runs first, can you tell me the values of `max_x` and `max_y`?

**Comment by heckflosse** [comment]
No, I can't, but it shouldn't matter when the calculation of const float scale uses the same Luminance calculation as in the loop, which is not the case.

**Comment by agriggio** [comment]
@Hombre57 @heckflosse here's a better patch:

```diff
diff --git a/rtengine/tmo_fattal02.cc b/rtengine/tmo_fattal02.cc
--- a/rtengine/tmo_fattal02.cc
+++ b/rtengine/tmo_fattal02.cc
@@ -1127,37 +1127,37 @@
         };
     TMatrix ws = ICCStore::getInstance()->workingSpaceMatrix (params->icm.working);
 
-    float max_Y = 0.f;
-    int max_x = 0, max_y = 0;
-
 #ifdef _OPENMP
-    #pragma omp parallel if (multiThread)
-#endif
-{
-    float max_YThr = 0.f;
-    int max_xThr = 0, max_yThr = 0;
-#ifdef _OPENMP
-    #pragma omp for schedule(dynamic,16) nowait
+    #pragma omp parallel for if (multiThread)
 #endif
     for (int y = 0; y < h; y++) {
         for (int x = 0; x < w; x++) {
             Yr (x, y) = std::max (luminance (rgb->r (y, x), rgb->g (y, x), rgb->b (y, x), ws), min_luminance); // clip really black pixels
-            if (Yr(x, y) > max_YThr && unclipped(y, x)) {
-                max_YThr = Yr(x, y);
-                max_xThr = x;
-                max_yThr = y;
+        }
+    }
+
+    float max_Y = 0.f;
+    int max_x = 0, max_y = 0;
+
+    const auto biggerY =
+        [](float cur_Y, float prev_Y) -> bool
+        {
+            if (!prev_Y) {
+                return true;
+            }
+            float e = (cur_Y - prev_Y) / max(cur_Y, prev_Y);
+            return e >= 0.05;
+        };
+
+    for (int y = 0; y < h; y++) {
+        for (int x = 0; x < w; x++) {
+            if (biggerY(Yr(x, y), max_Y) && unclipped(y, x)) {
+                max_Y = Yr(x, y);
+                max_x = x;
+                max_y = y;
             }
         }
     }
-#ifdef _OPENMP
-#pragma omp critical
-#endif
-    if (max_YThr > max_Y) {
-        max_Y = max_YThr;
-        max_x = max_xThr;
-        max_y = max_yThr;
-    }
-}
 
     // median filter on the deep shadows, to avoid boosting noise
     // because w2 >= w and h2 >= h, we can use the L buffer as temporary buffer for Median_Denoise()
```

@Hombre57 just to clarify: there will still be fluctuations, this is unavoidable to some extent I'm afraid (too many things change slightly when processing the image at different scales), but they should be much less visible now (I hope :-).

**Comment by Hombre57** [comment]
Hi @agriggio & @heckflosse , thanks for the quite reply.

It's better with your patch, but it can still fluctuate from L=88 to L=80 with the same example. We'll keep this enhancement but I'd like to leave this issue opened for some time.

**Comment by Hombre57** [comment]
@agriggio I think the problem is that after rescaling, the location of `(max_y, max_y)` is polluted by the neighbor data of the unscaled image that could be dark.

Could you recompute max_Y before scaling, but on a wider area around the detected coordinate, and take care of the pixels around. E.g., if scale is 1/10, recompute max_Y based on a square of 10x10 px. That shouldn't increase processing time. I hope it makes sens.

**Comment by agriggio** [comment]
@Hombre57 I'm not sure I understand what you have in mind. can you post some code please?

**Comment by agriggio** [comment]
@Hombre57 just to clarify, fluctuations are expected to happen even if you apply no scaling at all. Fixing this would be much harder. If you try the original fattal in luminance HDR, the output is *very* sensitive to the input image size. I tried to mitigate this as much as possible in RT, but eliminating this completely is beyond my skills (unless we go the brute-force way, of course -- but I don't think we want that...).
Here are a couple of screenshots both with and without scaling:

**with scaling**

![scale-10](https://user-images.githubusercontent.com/11982086/34931032-cd2ebd0a-f9cc-11e7-9df6-e2e4c3d45f62.jpeg)

![scale-20](https://user-images.githubusercontent.com/11982086/34931034-d2526502-f9cc-11e7-8463-6b8a4f1b96ad.jpeg)


**without scaling**

![no-scale-10](https://user-images.githubusercontent.com/11982086/34931038-d79caa4a-f9cc-11e7-88ec-089a42eaf9ac.jpeg)

![no-scale-20](https://user-images.githubusercontent.com/11982086/34931045-dd2eb296-f9cc-11e7-8c25-eac9af65da13.jpeg)

**Comment by Hombre57** [comment]
@agriggio My solution doesn't work. I'll try something else tonight.

**Comment by heckflosse** [comment]
With this patch the exposure with and without hdr tonemapping is in the same ballpark. Also thumb, navigator and preview match much better now. Also almost no dependency on zoom level in my tests.
It does not automatically brighten the result as it did before:

two screenshots:

left is just neutral profile, right is neutral profile + 3 EV
![grafik](https://user-images.githubusercontent.com/13733487/34955677-dab05ffc-fa25-11e7-8680-56acf075e31c.png)

left is neutral profile + 3 EV, right is neutral profile + 3 EV + hdr tone mapping
![grafik](https://user-images.githubusercontent.com/13733487/34955718-fcccf8e8-fa25-11e7-941d-b00cb31f114b.png)

```diff
diff --git a/rtengine/tmo_fattal02.cc b/rtengine/tmo_fattal02.cc
index ba59546c..5120e6d1 100644
--- a/rtengine/tmo_fattal02.cc
+++ b/rtengine/tmo_fattal02.cc
@@ -1120,39 +1120,20 @@ void ImProcFunctions::ToneMapFattal02 (Imagefloat *rgb)
     constexpr float epsilon = 1e-4f;
     constexpr float luminance_noise_floor = 65.535f;
     constexpr float min_luminance = 1.f;
-    const auto unclipped =
-        [rgb](int y, int x) -> bool
-        {
-            constexpr float c = 65500.f;
-            return rgb->r(y, x) < c && rgb->g(y, x) < c && rgb->b(y, x) < c;
-        };

     TMatrix ws = ICCStore::getInstance()->workingSpaceMatrix (params->icm.working);

-    float max_Y = 0.f;
-    int max_x = 0, max_y = 0;
-
-    const auto biggerY =
-        [](float cur_Y, float prev_Y) -> bool
-        {
-            if (!prev_Y) {
-                return true;
-            }
-            float e = (cur_Y - prev_Y) / max(cur_Y, prev_Y);
-            return e >= 0.05;
-        };
-
+#ifdef _OPENMP
+    #pragma omp parallel for
+#endif
     for (int y = 0; y < h; y++) {
         for (int x = 0; x < w; x++) {
             Yr (x, y) = std::max (luminance (rgb->r (y, x), rgb->g (y, x), rgb->b (y, x), ws), min_luminance); // clip really black pixels
-            if (biggerY(Yr(x, y), max_Y) && unclipped(y, x)) {
-                max_Y = Yr(x, y);
-                max_x = x;
-                max_y = y;
-            }
         }
     }

+    float oldMedian;
+    findMinMaxPercentile (Yr.data(), Yr.getRows() * Yr.getCols(), 0.5f, oldMedian, 0.5f, oldMedian, true);
     // median filter on the deep shadows, to avoid boosting noise
     // because w2 >= w and h2 >= h, we can use the L buffer as temporary buffer for Median_Denoise()
     int w2 = find_fast_dim (w) + 1;
@@ -1193,7 +1174,9 @@ void ImProcFunctions::ToneMapFattal02 (Imagefloat *rgb)
     const float hr = float(h2) / float(h);
     const float wr = float(w2) / float(w);

-    const float scale = 65535.f / std::max(L(max_x * wr + 1, max_y * hr + 1), epsilon) * (65535.f / Yr(max_x, max_y));
+    float newMedian;
+    findMinMaxPercentile (L.data(), L.getRows() * L.getCols(), 0.5f, newMedian, 0.5f, newMedian, true);
+    const float scale = oldMedian / newMedian;

 #ifdef _OPENMP
     #pragma omp parallel for schedule(dynamic,16) if(multiThread)

```

**Comment by agriggio** [comment]
nice!

**Comment by heckflosse** [comment]
I would like to discuss removing the following code too (at least if my patch is ok). https://github.com/Beep6581/RawTherapee/blob/dev/rtengine/tmo_fattal02.cc#L652

line 652 to 666 could be removed now imho

**Comment by agriggio** [comment]
@heckflosse no objections from me (I take it that you tested it already) :+1:

**Comment by heckflosse** [comment]
@agriggio I did :)

**Comment by Hombre57** [comment]
@heckflosse I guess that you won't believe if I tell that you did what I wanted to do, but I'd have used the [maxval reduction clause from openmp](https://github.com/Beep6581/RawTherapee/blob/656a92cb8e9d65073a6dce0ca9fa67bb03bc4fd1/rtengine/rt_algo.cc#L67).

**Comment by Hombre57** [comment]
Forget my comment...

**Comment by heckflosse** [comment]
@Hombre57 ?

**Comment by Hombre57** [comment]
I don't understand why you use `findMinMaxPercentile` if you only need to find the max value of the image, but you wrote that function who uses the maxval reduction clause, so you know better.

**Comment by heckflosse** [comment]
@Hombre57 Just for explanation: I used findMinMaxPercentile to find the median of the image

**Comment by Hombre57** [comment]
I can't apply the patch, but your screenshots clearly show that it's much better now. 👍

**Comment by agriggio** [comment]
@Hombre57 @heckflosse I confirm that the patch doesn't apply cleanly on `dev`, but this one should do (I also killed the lines mentioned above by @heckflosse):

```diff
diff --git a/rtengine/tmo_fattal02.cc b/rtengine/tmo_fattal02.cc
--- a/rtengine/tmo_fattal02.cc
+++ b/rtengine/tmo_fattal02.cc
@@ -648,22 +648,6 @@
             }
         }
     }
-
-    // remove percentile of min and max values and renormalize
-    float cut_min = 0.01f * black_point;
-    float cut_max = 1.0f - 0.01f * white_point;
-    assert (cut_min >= 0.0f && (cut_max <= 1.0f) && (cut_min < cut_max));
-    findMinMaxPercentile (L.data(), L.getRows() * L.getCols(), cut_min, minLum, cut_max, maxLum, multithread);
-    float dividor = (maxLum - minLum);
-
-    #pragma omp parallel for if(multithread)
-
-    for (size_t i = 0; i < height; ++i) {
-        for (size_t j = 0; j < width; ++j) {
-            L[i][j] = std::max ((L[i][j] - minLum) / dividor, 0.f);
-            // note, we intentionally do not cut off values > 1.0
-        }
-    }
 }
 
 
@@ -1120,39 +1104,20 @@
     constexpr float epsilon = 1e-4f;
     constexpr float luminance_noise_floor = 65.535f;
     constexpr float min_luminance = 1.f;
-    const auto unclipped =
-        [rgb](int y, int x) -> bool
-        {
-            constexpr float c = 65500.f;
-            return rgb->r(y, x) < c && rgb->g(y, x) < c && rgb->b(y, x) < c;
-        };
 
     TMatrix ws = ICCStore::getInstance()->workingSpaceMatrix (params->icm.working);
 
-    float max_Y = 0.f;
-    int max_x = 0, max_y = 0;
-
-    const auto biggerY =
-        [](float cur_Y, float prev_Y) -> bool
-        {
-            if (!prev_Y) {
-                return true;
-            }
-            float e = (cur_Y - prev_Y) / max(cur_Y, prev_Y);
-            return e >= 0.05;
-        };
-    
+#ifdef _OPENMP
+    #pragma omp parallel for
+#endif
     for (int y = 0; y < h; y++) {
         for (int x = 0; x < w; x++) {
             Yr (x, y) = std::max (luminance (rgb->r (y, x), rgb->g (y, x), rgb->b (y, x), ws), min_luminance); // clip really black pixels
-            if (biggerY(Yr(x, y), max_Y) && unclipped(y, x)) {
-                max_Y = Yr(x, y);
-                max_x = x;
-                max_y = y;
-            }
         }
     }
 
+    float oldMedian;
+    findMinMaxPercentile (Yr.data(), Yr.getRows() * Yr.getCols(), 0.5f, oldMedian, 0.5f, oldMedian, true);
     // median filter on the deep shadows, to avoid boosting noise
     // because w2 >= w and h2 >= h, we can use the L buffer as temporary buffer for Median_Denoise()
     int w2 = find_fast_dim (w) + 1;
@@ -1193,7 +1158,9 @@
     const float hr = float(h2) / float(h);
     const float wr = float(w2) / float(w);
 
-    const float scale = 65535.f / std::max(L(max_x * wr + 1, max_y * hr + 1), epsilon) * (65535.f / Yr(max_x, max_y));
+    float newMedian;
+    findMinMaxPercentile (L.data(), L.getRows() * L.getCols(), 0.5f, newMedian, 0.5f, newMedian, true);
+    const float scale = oldMedian / newMedian;
 
 #ifdef _OPENMP
     #pragma omp parallel for schedule(dynamic,16) if(multiThread)
```

**Comment by Hombre57** [comment]
Works nice @heckflosse 👏 
Closing.

**Comment by heckflosse** [comment]
Though the issue is already closed, nevertheless let me add some thoughts:

1. Hombre was right with his issue
2. Alberto and I in first step have not been sure that the issue can be solved easily.
3. Sometimes the solution is really easy, once found :)

Conclusion: Always report issues and be persistant that they can be solved. Cheers :)

**Comment by casta** [comment]
Nice !!
With last changes, it makes wonders. :clap:
Big thank’s !!
