### ISSUE TITLE
Canon CR2 raw file gets cut and disarranged

### ISSUE THREAD

**Issue by johndelarcalas** [Beep6581/RawTherapee#4311]
Hi! First post. So I just started using RawTherapee on the GUI and not sure if posting it here is proper.

So this is the image before I open it.
![initial image](https://user-images.githubusercontent.com/25147512/35014292-788b17fe-fb29-11e7-84c5-9014fee0cff0.jpg)

Once I open it, it shows me this without me editing the picture.
![distorted image](https://user-images.githubusercontent.com/25147512/35014306-8c50859e-fb29-11e7-8299-a532e9557819.jpg)

Saving the image also produces the same effect. I tried, hoping it was temporary (only viewed at RawTherapee. Has anyone encountered this? If yes and the issue has been fixed/solved, kindly direct me there.

**Comment by heckflosse** [comment]
Looks similar to this one:

![grafik](https://user-images.githubusercontent.com/13733487/35014940-c1bb054a-fb12-11e7-8f9e-adeb034afbd8.png)

Related: https://github.com/Beep6581/RawTherapee/issues/3533

**Comment by Beep6581** [comment]
Closing as duplicate of #3533

@johndelarcalas RawTherapee will most likely not support this raw file format until our raw reading dependency "dcraw" does. Your short-term solution is to shoot raw, not mRaw, or to convert to DNG.

**Comment by johndelarcalas** [comment]
@heckflosse Yeah, exactly the same concern. I was trying to figure out by touching some settings and swimming the net for a solution. Man, I must not be good at researching.

@Beep6581 Okay. I will try to find mRaw settings on my Canon 80D and hopefully it doesn't reduce the quality of the images I take. Thank you!

**Comment by heckflosse** [comment]
@johndelarcalas 

@Beep6581 meant, you are currently using mRaw. Better not to use it

**Comment by johndelarcalas** [comment]
@heckflosse @Beep6581 So I checked my images and was shocked why my images were captured as mRAW when my capture setting was on RAW. I checked the image size and resolution and it was captured at 4500x3000. I guess I'll research on that. Thank you. Closing this issue now.
