### ISSUE TITLE
[5.3-713-g6cdbba2, newlocallab, Linux64] Crashes

### ISSUE THREAD

**Issue by FM33** [Beep6581/RawTherapee#4315]
Hello,

I encounter crashes, specially when clicking on add to queue. It seems random.

Version: 5.3-713-g6cdbba2
Branch: newlocallab
Commit: 6cdbba2
Commit date: 2018-01-21
Compiler: cc 5.3.1
Processor: x86_64
System: Linux (Ubuntu 16.04), 8GB RAM, video intel
Bit depth: 64 bits
Gtkmm: V3.18.0
Lensfun: V0.2.8.0
Build type: debug
Build flags: -std=c++11 -Wno-deprecated-declarations -Wno-unused-result -std=c++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -g
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON

[rt53_btfull.txt](https://github.com/Beep6581/RawTherapee/files/1649970/rt53_btfull.txt)

**Comment by heckflosse** [comment]
I take this one

**Comment by heckflosse** [comment]
@FM33 Can you upload a file and the correspondig pp3 file to filebin.net and post the link here?

**Comment by FM33** [comment]
https://filebin.net/ixckb7t6ee8ac8ee

**Comment by heckflosse** [comment]
@FM33 I could not reproduce using latest `dev` and latest `newlocallab` in release and debug build

**Comment by FM33** [comment]
I had 2 more today (with release), including 1 after barely a few minutes. I update and will see if it's still there.

**Comment by FM33** [comment]
I can confirm that when it's there, it's really random. Yesterday I had 1 in the first 5 minutes, then another one after more than 1 hour. Today, after update to g62d9825 I got none even after several hours, but I can't say yet if it was either luck or it's fixed.
