### ISSUE TITLE
Queue On/Off switch incorrectly colors in TooWa* themes

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4316]
The On/Off switch in the Queue is incorrectly colored when using the TooWa* themes. It should look like this (though not necessarily blue):
https://filebin.net/s1m05js425qrrp12/rt_queue_switch.mp4

Using TooWaGray for example, it currently looks like this:
![screenshot_20180122_011921](https://user-images.githubusercontent.com/5844619/35200661-9e5bb10e-ff12-11e7-891b-6fba57742eb9.png)

@TooWaBoo could you have a look at this?

**Comment by TooWaBoo** [comment]
@Beep6581 
Your link doesn't work.
I did this on purpose. The slider is blue as long as you can switch it on or off. It becomes gray when you can't switch it. The red background stays red (active) as long as the queue is running and it's switched on.

**Comment by agriggio** [comment]
@TooWaBoo I agree with @Beep6581 that red is a bad choice here: it reminds me of a red semaphore, the opposite of something running...

**Comment by TooWaBoo** [comment]
Link works.
The behaviour on Windows is different to Linux. If the queue is empty the switch is totally grayed out and you can't switch it on like in your video.

Example how GTK acts on Windows with the RT theme
Empty queue
![grafik](https://user-images.githubusercontent.com/13800920/35232753-922dc7ca-ff9c-11e7-8359-a4bd74ec144c.png)
2 images in queue / OFF
![grafik](https://user-images.githubusercontent.com/13800920/35232817-c4d4d312-ff9c-11e7-84c3-4d28c9bf63a7.png)
2 images in queue / ON
![grafik](https://user-images.githubusercontent.com/13800920/35232937-10b37fd6-ff9d-11e7-8ed3-17fa17c0ff0f.png)
1 image in queue / ON
![grafik](https://user-images.githubusercontent.com/13800920/35233004-41c50f72-ff9d-11e7-84a1-1a50ef460054.png)

**Comment by TooWaBoo** [comment]
@agriggio 
Which color do you prefere?

**Comment by gaaned92** [comment]
perhaps green=ON and red =OFF should be better but I don't mind. and grey =disabled when nothing in queue.

If you click like a fool on the button, it makes RT crash.

**Comment by agriggio** [comment]
@TooWaBoo why do you need to change the background? I'd say leave it to blue

**Comment by Kildor** [comment]
Red as on is very bad idea. I tried to understood for about 20 minutes why RT doesn't finish processing files in queue. It was just switched off.

Red as off is also not a good idea. May be gray if off and blue if on?

**Comment by TooWaBoo** [comment]
@Kildor
I don't get it. Why did you wait 20 minutes? Doesn't the switch indicate the right state?

**Comment by Kildor** [comment]
@TooWaBoo Red button with 'I' doesn't seems to be the "right state" for me. Especially when status overlay at tab icon is also wrong.
To be honest, I do not understand the logic of this widget at all. Why must I move the button left to run? why does it change color? What the hell, why it is animated??77SEVENSEVEN
I could understand that this is something came from mobile, but my WP-phone has no such widgets. At least sliders are moved to the right to be switched on.

UPD. I've checked it one more time and I did really think that blue rect is background part of widget.
I think this is very good UX: http://img.wpxbox.com/Samsung-Focus-S-Extra-Settings.jpg

**Comment by TooWaBoo** [comment]
@All 
Please test this: 
[TooWaBlue-Test-GTK3-20_.css.txt](https://github.com/Beep6581/RawTherapee/files/1652980/TooWaBlue-Test-GTK3-20_.css.txt)
... and this
[TooWaBlue-Test2-GTK3-20_.css.txt](https://github.com/Beep6581/RawTherapee/files/1653128/TooWaBlue-Test2-GTK3-20_.css.txt)

**Comment by TooWaBoo** [comment]
Another idea is to use one Start / Stop toggle button. Similar to the "Auto" exposure button.

**Comment by Beep6581** [comment]
@TooWaBoo 

> The behaviour on Windows is different to Linux. If the queue is empty the switch is totally grayed out and you can't switch it on like in your video.

The behavior is the same - the video was recorded before the final version of the switch.

> Example how GTK acts on Windows with the RT theme

Looks good.

> Red as off is also not a good idea. May be gray if off and blue if on?

I agree, red is danger - there is no danger here. It's not a "delete" button.

As for the labels, according to https://mail.gnome.org/archives/gtkmm-list/2013-July/msg00035.html :
> /\* Translators: if the "on" state label requires more than three
>   \* glyphs then use MEDIUM VERTICAL BAR (U+2759) as the text for
>   \* the state
>   \*/
>  /\* Translators: if the "off" state label requires more than three
>   \* glyphs then use WHITE CIRCLE (U+25CB) as the text for the state
>   \*/

@Kildor 

> Why must I move the button left to run? why does it change color? What the hell, why it is animated??77SEVENSEVEN

Calm down and realize that all RT buttons change color or icon when activated (some worse than others, generally as a result of not having been updated since the GTK2-GTK3 switch) and that it's clickable like any other RT button.

@TooWaBoo 
> Please test this

Tested both, both work well and look meaningful. Other insensitive widgets in that theme are beveled, e.g. the comboboxes, so `test2` seems most consistent.

**Comment by TooWaBoo** [comment]
Created a pull request.
Issue can be closed

**Comment by Kildor** [comment]
@Beep6581 
> Calm down and realize that all RT buttons change color or icon when activated (some worse than others, generally as a result of not having been updated since the GTK2-GTK3 switch) and that it's clickable like any other RT button.

Beg my pardon. I'm calm, I've just tried to show my emotions when I tried to use new button first time.

@TooWaBoo 
Yes, now it is much better.

Anyway, overlays are still messed up, so I'll create a new issue.

**Comment by TooWaBoo** [comment]
@Kildor 
What is messed up? Can you provide a screenshot, please?

**Comment by Kildor** [comment]
@TooWaBoo
Icons in tabbar. I don't think if it is connected with your themes, so I've filled new issue #4323 with all screenshotes.

**Comment by Beep6581** [comment]
@TooWaBoo can we close?

**Comment by TooWaBoo** [comment]
@Beep6581 
Yes
