### ISSUE TITLE
Unused wavelet parameters in options file

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4318]
The `options` file contains several keys specific to the Wavelet tool in the "General" section:
```
EDdetec=3
EDdetecStr=1.3
EDLow=15
EDLipinfl=0.80000000000000004
EDLipampl=1.1000000000000001
```
The last two are not used at all.

Looks like something used for testing which went unnoticed in the previous release. @Desmis could you take a look? Any need to keep them in the General section, or at all, for 5.4?

**Comment by Desmis** [comment]
@Beep6581 

Done, just commit and push :)

**Comment by Beep6581** [comment]
Thank you @Desmis 
Do we want to keep the remaining 3 keys in the General section, or at all?

**Comment by Desmis** [comment]
I think they are well placed here :)

**Comment by agriggio** [comment]
@Desmis Jacques, could you clarify what are these settings for? Are they supposed to be editable by the user? If so, how? I couldn't find them in the gui...

**Comment by Desmis** [comment]
@agriggio 

All these values are for "edge detection" in ipwavelet to act on "local contrast" and "edge sensitivity"

As nobody ask me about these values since many years. I will "comment" (in case of...) them in options.cc, and put the values by default in ipwavelet.cc

**Comment by agriggio** [comment]
@Desmis we can't you simply remove them from options and have them as constants in the code (With proper comments)? 
More in general, why are we having parameters that affect the behaviour of tools in `options` instead of in `ProcParams`?

**Comment by agriggio** [comment]
@Desmis Jacques:

> I will "comment" (in case of...)

If by that you mean "comment out", then please just delete the lines. We are using git for a reason (well, many, but this is definitely one :-)

Thanks!

**Comment by Desmis** [comment]
Chane done, and push :)

**Comment by heckflosse** [comment]
Can we close?

**Comment by Beep6581** [comment]
Confirmed that those keys are no longer in the `options` file.
