### ISSUE TITLE
Icons of queue tab are messed up

### ISSUE THREAD

**Issue by Kildor** [Beep6581/RawTherapee#4323]
Previous versions of RT showed an icon with red pause overlay for queue tab in tabbar if there were some images in stopped queue (icon processing-pause.png) and icon processing-play.png if batch processing was active. It was logical and understandable.

processing is stopped 
![rt-pause-old](https://user-images.githubusercontent.com/1320579/35259560-2b44cd5e-0039-11e8-82d9-8b890a6fe066.PNG)

Processing is active
![rt-play-old](https://user-images.githubusercontent.com/1320579/35259559-2b1fca36-0039-11e8-8da4-d5cc876e80fa.PNG)

Current RT switches this icons. I've checked with 5.3-520, Windows 10x64

Queue is stopped, green play icon (processing-play.png) is shown
![rt-pause-1](https://user-images.githubusercontent.com/1320579/35259593-53bb217a-0039-11e8-8069-f1e559c7fa22.png)

Queue is active, red pause icon (processing-pause.png) is shown
![rt-play-1](https://user-images.githubusercontent.com/1320579/35259592-53987602-0039-11e8-9d6c-464bce584cc8.png)

Was this change intended?

**Comment by agriggio** [comment]
definitely not intended, and I cannot reproduce here. can you post more details about your RT build?

**Comment by Kildor** [comment]
@agriggio I'd compiled RT by myself (as explained in rawpedia) and downloaded RawTherapee_dev_5.3-517-g8e48df11_WinVista_64.zip from keybase.pub/gaaned92/RTW64NightlyBuilds/ and got the same behaviour on two different computers.

Version: 5.3-517-g8e48df11
Branch: dev
Commit: 8e48df11
Commit date: 2018-01-22
Compiler: gcc 7.2.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.22.0
Lensfun: V0.3.2.0
Build type: release
Build flags:  -m64 -mwin32 -mthreads -Wno-aggressive-loop-optimizations -std=c++11 -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations  -DNDEBUG  -O3
Link flags: -m64 -mthreads  -static-libgcc   -mtune=generic  -s -O3
OpenMP support: ON
MMAP support: ON

**Comment by agriggio** [comment]
Ah! Now I see it. It only happens in "Multiple editor tabs mode". I'll take a look

**Comment by Beep6581** [comment]
My bad, sorry! Thanks for fixing it @agriggio

**Comment by Kildor** [comment]
Thank for fixing! Now it works as intended.
