### ISSUE TITLE
Improve HALD CLUT user interface

### ISSUE THREAD

**Issue by mzuther** [Beep6581/RawTherapee#4325]
Hi!

After you have so nicely responded to my last requests, here's a new one. Just so you do not get bored... :)

I often use the HALD CLUT film simulation. However, as I'm not yet acquainted with the way different films behave, I often change the film type to find one that I like. Sometimes, I reduce down to two or three films and then switch back and force to see which one I like best. This involves quite a bit of mouse work and concentration because of the complex one-line combo box.

My suggestion is to change the combo box so that it only contains directories. Then, add a list box with, say, ten lines (and optional scroll bars) that shows the files in the selected directory. This should significantly reduce the amount of mouse movements needed to change the film type. Also, even more important, because it's now much easier to change the film type, users can concentrate on the effect of the film change -- instead of on the menu --, thus possibly reducing the mouse work even more.

As usual, thanks for considering my ideas!

Martin

**Comment by Beep6581** [comment]
You can try out all HaldCLUTs with no mouse clicks:
1. Click on the combobox (ok, 1 click).
2. Press the up or down arrow on your keyboard to try out all the various HaldCLUTs even if they're in different subfolders.

Easiest way to switch back and forth between two or three HaldCLUTs is to use [snapshots](http://rawpedia.rawtherapee.com/The_Image_Editor_Tab#Snapshots).

**Comment by Floessie** [comment]
I had the same problem Martin has: There are two or more film simulations and I can't decide which is best. To find the best, I used to save multiple versions and compared them in Geeqie. Now I tried snapshots for the first time: Yet another trick learned! Works as desired. 👍

**Comment by Beep6581** [comment]
So:

**Comment by mzuther** [comment]
Thanks, I didn't know about the arrow keys. That's great! I definitely think that's something RawPedia should mention. :)

As a side note, I often check the effect of a film type using batch edit mode, so snapshots are not a solution for me. Thanks for the idea, anyway!

**Comment by Beep6581** [comment]
Documentation updated:
http://rawpedia.rawtherapee.com/Film_Simulation

**Comment by mzuther** [comment]
I say it yet again: thanks! :)

**Comment by Beep6581** [comment]
Thanks for pointing the shortcoming out!
