### ISSUE TITLE
Virus found in Msys2 update - in Gcc.exe

### ISSUE THREAD

**Issue by Desmis** [Beep6581/RawTherapee#4333]
Hello
@TooWaBoo 
I have update Msys2 after message yesterday  TooWaBoo

Just after that, when I lauch Mingw64,  "Avast" find a virus in GCC.exe and automaticly put this file in "quarantaine"

Now, when I lauch Mingw64, I have "unknow compiler"

Virus is "IDP.ARES.generic"

What must I do ?

**Comment by Desmis** [comment]
I found in web how to load gcc

pacman -S mingw-w64-x86_64-gcc
OK it update package, and when I run Mingw64; Avast said virus ==> quarantaine

**Comment by Beep6581** [comment]
@Desmis upload the file to https://www.virustotal.com/ 
That will give you a better idea of whether it's infected or a false-positive.

**Comment by Desmis** [comment]
I have made a new update of gcc.exe and used https://www.virustotal.com /
No virus found, but now,
when I launch
make -j8 install $I have an error message 
make: /C/msys64/mingw64/bin/cmake.exe: Command not found
make: *** [Makefile:252: cmake_check_build_system] Error 127

Probbaly needs to all reinstall ? How to force system ?

**Comment by Desmis** [comment]
When I
pacma -Syu
Systeme says it is good nothing to do

**Comment by Desmis** [comment]
I am trying to reinstall a part of msys2

**Comment by Desmis** [comment]
After reinstallation, and create an exception in Avast, Gcc start.
I hope, It will run fine :)
I hope no virus on my computer

**Comment by Desmis** [comment]
All seems to work fine

Thank you

**Comment by Beep6581** [comment]
Great
