### ISSUE TITLE
PDF Documentation Link broken

### ISSUE THREAD

**Issue by tacman** [Beep6581/RawTherapee#4344]
http://rawpedia.rawtherapee.com/index.php?title=Special:Book&bookcmd=render_article&arttitle=Main+Page&returnto=Main+Page&oldid=3523&writer=rl

There's links to obsolete documentation, could there also be a link to some recent documentation in PDF form?

**Comment by Beep6581** [comment]
Thanks for reporting, though we're already aware of it and it's not fixable.

**Comment by tacman** [comment]
Any chance of a command line script that could be run as a cron job,
instead of on-the-fly generation?

It's the https://www.mediawiki.org/wiki/Extension:PdfBook extension,
right?  Alas, I'm not seeing a CLI option, and while there's lots of
discussion about PDF generation, nothing jumps out as a good solution.

Maybe de-activate that extension, to hide the page and error message?

Tac

**Comment by Beep6581** [comment]
@tacman online PDF generation is not currently possible due to limited server access and the required deps not working. Offline generation is not possible in any sane way as far as I know - working solutions are welcome.
As for the menu items, we will hide them after one more attempt to get this working, one more "huff and puff".

**Comment by patdavid** [comment]
It's likely that this is not going to be easily implementable at the moment.

I am in the process of removing the link for now.  I intend to generate a PDF of any book definitions automatically and then point the link to the appropriate place from there.  Please hold. :)

**Comment by patdavid** [comment]
This is addressed now.
We are now manually printing the page http://rawpedia.rawtherapee.com/RawPedia_Book
and making it available at http://rawpedia.rawtherapee.com/RawPedia.pdf

For details on the wiki, check this talk page: http://rawpedia.rawtherapee.com/Talk:RawPedia_Book

**Comment by heckflosse** [comment]
@patdavid Great and thanks for that 👍 

I found an issue. Have a look at the screen shot on page 14/205. The left part is cut off in pdf. Clicking on the screen shot shows the left part.

**Comment by Beep6581** [comment]
A cunning solution @patdavid !

**Comment by Beep6581** [comment]
After a few hours of tweaking, I think the RawPedia PDF now looks better than it did before!
Thanks again @patdavid
