### ISSUE TITLE
local contrast misplaced?

### ISSUE THREAD

**Issue by agriggio** [Beep6581/RawTherapee#4348]
it just occurred to me: shouldn't the local contrast tool be in detail and not exposure? what do you think?

**Comment by Beep6581** [comment]
I guess it's not that different in principle to unsharp-masking, so yes, agreed.

**Comment by agriggio** [comment]
ok, I'll move it then. can I push to dev directly or would you prefer a branch?

**Comment by Beep6581** [comment]
Let's branch so that I can check first.

**Comment by agriggio** [comment]
pushed branch `local-contrast-in-detail`
