### ISSUE TITLE
Changing the LH equalizer in L*a*b* hangs RT

### ISSUE THREAD

**Issue by agriggio** [Beep6581/RawTherapee#4355]
How to reproduce:

- take any raw file (tested with ARW  and CR2)
- apply neutral
- enable L\*a\*b\* Adjustments
- Click on LH, select Equalizer
- Adjust one of the points

RT hangs, with all cores at 100%.

Seems pretty severe... 

I won't be able to look at this before tonight -- and also I'm not sure about tonight, so another pair of eyes is welcome!

**Comment by agriggio** [comment]
I am bisecting -- it worked fine in 2f1ab34ef1231688e6f0a6e247ccb68510fd16e2

**Comment by Floessie** [comment]
Bug confirmed.

**Comment by Floessie** [comment]
The GUI thread is doing heavy resize operations, four threads are in `ImProcFunctions::chromiLuminanceCurve()` (OMP).

**Comment by Floessie** [comment]
The OMP threads hang in the loop starting at [`rtengine/improcfun.cc:5772`](https://github.com/Beep6581/RawTherapee/blob/fcd7a0ab377ebd07f2b46865c17b7123b987b133/rtengine/improcfun.cc#L5772).

**Comment by agriggio** [comment]
bisected. Apparently it comes from this: 478410fa39e4ca81c8e96a7e2604eb30b97d3838

**Comment by Floessie** [comment]
@heckflosse Found a typo in that commit: It's line [5777](https://github.com/Beep6581/RawTherapee/blob/fcd7a0ab377ebd07f2b46865c17b7123b987b133/rtengine/improcfun.cc#L5777).

**Comment by Floessie** [comment]
Fix:
```patch
diff --git a/rtengine/improcfun.cc b/rtengine/improcfun.cc
index 1a545bdf5..37a3e707f 100644
--- a/rtengine/improcfun.cc
+++ b/rtengine/improcfun.cc
@@ -5774,7 +5774,7 @@ void ImProcFunctions::chromiLuminanceCurve (PipetteBuffer *pipetteBuffer, int pW
                         float aprov1 = Chprov2 * sincosval.y;
                         float bprov1 = Chprov2 * sincosval.x;
 
-                        float fy = (Color::c1By116 * Lprov1 ) + Color::c1By116;
+                        float fy = (Color::c1By116 * Lprov1 ) + Color::c16By116;
                         float fx = (0.002f * aprov1) + fy;
                         float fz = fy - (0.005f * bprov1);
```

**Comment by agriggio** [comment]
@Floessie thanks! Testing...

**Comment by agriggio** [comment]
@Floessie fix confirmed! :+1: :tada: 
Can you please push?

**Comment by Floessie** [comment]
💦 🤘 

I can only push tonight, so please go ahead and push.

Best,
Flössie

**Comment by heckflosse** [comment]
@Floessie @agriggio Thanks for bisecting and fixing 👍
