### ISSUE TITLE
in SETM switching from an image with a crop to another image with different dimensions does not fit to screen

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#4357]
To reproduce

1) use SETM
2) open an image and apply a crop
![grafik](https://user-images.githubusercontent.com/13733487/35735645-cef1be5a-0825-11e8-8d1e-05a132344e89.png)

3) Open an image with different dimensions. Expected result: full preview of next image (zoomed to fit).
Instead I get this:
![grafik](https://user-images.githubusercontent.com/13733487/35735686-e8fe7c52-0825-11e8-854b-d39423286a8e.png)

Without applying a crop in step 2 I get this, which is correct:
![grafik](https://user-images.githubusercontent.com/13733487/35735803-44b69aa2-0826-11e8-9e87-1cba67ea0785.png)

**Comment by agriggio** [comment]
@heckflosse is this checkbox ticked?

![screenshot from 2018-02-02 14 38 16](https://user-images.githubusercontent.com/11982086/35736006-e12a44e2-0826-11e8-81b1-69722f35e355.jpeg)

**Comment by heckflosse** [comment]
@agriggio yes, but I thought that would be only for images with equal dimensions

**Comment by agriggio** [comment]
@heckflosse sorry I don't understand your comment :-)
Can you please elaborate on what you expect in relation with the crop and the value of the checkbox? Thanks!

**Comment by heckflosse** [comment]
@agriggio In past, when switching between an image of size 3000 x 2000 and an image of size 6000 x 4000 zoom and pan was not remembered.

Edit: and when first image has no crop, it is still not remembered, which is good. Only when first image has a crop, I get a wrong zoom factor when the second image has different dimensions.

**Comment by agriggio** [comment]
@heckflosse sorry I still don't understand. When you say "zoom and pan was not remembered", was this regardless of the value of the checkbox? Was this the "right" behaviour, or was it just a limitation? 
Regardless, what is the expected behaviour now, considering the following parameters:

- crop vs no crop
- value of the checkbox
- same size vs diferent size of pictures

? The specs are not clear to me, sorry...

Here, everything seems to work as I would expect:

- I have the above checkbox ticked, and I also have this unticked:
![screenshot from 2018-02-02 15 04 08](https://user-images.githubusercontent.com/11982086/35737001-5939b4d8-082a-11e8-8942-837b6d128674.jpeg)

- I open amsterdam.pef and set a crop. The image is *not* automatically zoomed to fit, as expected (given the value of the checkbox above).

- then I press 'f' and I get zoom to fit

- then I open a raw of an A7RIII, which is larger, and it is correctly zoomed to fit.

So, where are the differences between our setups?

**Comment by heckflosse** [comment]
@agriggio got it. When Auto zoom to fit the crop area is enabled and I switch from amsterdam.pef (which has a crop defined) to an A7RIII raw, the A7RIII raw is shown with the crop fit zoom factor of amsterdam.pef.

**Comment by heckflosse** [comment]
opened amsterdam.pef
![grafik](https://user-images.githubusercontent.com/13733487/35737451-d048e390-082b-11e8-9255-9bd5a6b621e7.png)

then opened a 24 MP arw (though not an A7RIII)
![grafik](https://user-images.githubusercontent.com/13733487/35737475-e5815cec-082b-11e8-92e7-af4bcd3b401b.png)

**Comment by agriggio** [comment]
ok, but I still don't understand:

- whether you have "remember % zoom" enabled or not :-)
- whether you still think this is a bug (I'm not sure either way, tbh)

**Comment by heckflosse** [comment]
remember % zoom is enabled 

I still think this is a bug, because it it shouldn't matter whether first image has a crop defined or not. 
As you can see in my above example I zoomed to fit whole image before I opened the arw and still the arw opened at 52%, which is the zoom to crop fit % of the amsterdam.pef with the crop I defined.
Does this make sense?

**Comment by agriggio** [comment]
Ok, I played with the settings a little bit. *None* of them make any sense to me :disappointed: 
The whole thing feels random: I'm sure there is a logic, but I just cannot see it...
Also, why does this depend on what demosaic method is used in "preferences -> performance and quality"?

**Comment by heckflosse** [comment]
The remember zoom % and pan thing was made to easily compare two images of same subject e.g. for sharpness. Iirc it was restricted to images of same size and orientation. When no crop is defined in first image or `autom. zoom to fit the crop` is disabled it still seems to work this way.

Iirc the dependency on `demosaic as in pp3` was to avoid demosaicing twice (first `fast`, then `as in pp3`) when switching between images and being at >= 100 %.

Maybe @Beep6581 can dig out the old issue

**Comment by heckflosse** [comment]
for reference: #2418

**Comment by Beep6581** [comment]
Yes, keeping the zoom % and pan offset when opening an image of the same size is to make it easy to compare successive shots.
https://github.com/Beep6581/RawTherapee/issues/2418

Demosaic fast/as in PP3 was to prevent fast demosaicing artifacts while still letting users of slower machines revert to a faster demosaicing algo.
https://github.com/Beep6581/RawTherapee/issues/2647

**Comment by agriggio** [comment]
@Beep6581 Ok thanks. To clarify: I understand the need for having demosaic fast (in fact, I always use that), but I don't understand why the behaviour of "remember zoom" has to be influenced by this...

**Comment by heckflosse** [comment]
@agriggio I found the cuplrit. Though I don't know how to fix it.

when the second image is opened the crophandler
https://github.com/Beep6581/RawTherapee/blob/dev/rtgui/cropwindow.cc#L2106
still has the values from first image.
Edit: When opening an image in SETM the crophandler always uses the values from previous opened image, not only for second image, which means, at least it is not random ...

**Comment by heckflosse** [comment]
This patch fixes the issue:

```diff
diff --git a/rtgui/editorpanel.cc b/rtgui/editorpanel.cc
index 9c23053a..8506baf6 100644
--- a/rtgui/editorpanel.cc
+++ b/rtgui/editorpanel.cc
@@ -1068,7 +1068,7 @@ void EditorPanel::open (Thumbnail* tmb, rtengine::InitialImage* isrc)
     // since there was no resize event
     if (iareapanel->imageArea->mainCropWindow) {
         iareapanel->imageArea->mainCropWindow->cropHandler.newImage (ipc, false);
-        iareapanel->imageArea->mainCropWindow->initialImageArrived();
+//        iareapanel->imageArea->mainCropWindow->initialImageArrived();
 
         // In single tab mode, the image is not always updated between switches
         // normal redraw don't work, so this is the hard way
diff --git a/rtgui/imagearea.cc b/rtgui/imagearea.cc
index 4c4f78a3..942e6631 100644
--- a/rtgui/imagearea.cc
+++ b/rtgui/imagearea.cc
@@ -655,6 +655,10 @@ void ImageArea::initialImageArrived (CropWindow* cw)
                 } else {
                     mainCropWindow->zoomFit();
                 }
+            } else {
+                if (options.cropAutoFit && mainCropWindow->cropHandler.cropParams.enabled) {
+                    mainCropWindow->zoomFitCrop();
+                }
             }
 
             fullImageWidth = w;

```

Edit: I just updated the patch.

**Comment by heckflosse** [comment]
@agriggio @Beep6581 please test. I really would like to see this issue fixed for 5.4

**Comment by agriggio** [comment]
tested quickly, no issues found

**Comment by heckflosse** [comment]
@agriggio Does that mean it fixes the random behaviour in your test or that it doesn't introduce new issues?

**Comment by agriggio** [comment]
it fixes the issue you reported. the behaviour *feels* random to me, but that's just because I don't get the logic :-)
I don't use remember zoom because I find it confusing

**Comment by heckflosse** [comment]
@agriggio the logic, when remember zoom is enabled was:

1) switching between images of same dimension (width/height) => keep pan position and zoom factor
2) switching between images of different dimensions (width/height) => zoom to fit

Now when autom. zoom to crop fit is disabled it should still be as I wrote above

But when autom. zoom to crop fit is enabled it should be:

1) switching between images of same dimension (width/height) => keep pan position and zoom factor if new image has no crop, else zoom to crop fit
2) switching between images of different dimension (width/height) => zoom fit to whole image if new image has no crop, else zoom to crop fit

Edit: to be confirmed by @Beep6581

**Comment by agriggio** [comment]
sounds good to me then!

**Comment by heckflosse** [comment]
@agriggio I simpilfied the code and created a pr

**Comment by Beep6581** [comment]
PR works great.

**Comment by heckflosse** [comment]
@Beep6581 Thanks for testing
