### ISSUE TITLE
Build fails on Fedora Testing

### ISSUE THREAD

**Issue by mbajor** [Beep6581/RawTherapee#4362]
Lastest success build: 5.3~git.20180130.544.g4ce9b0f01
Log:
https://build.opensuse.org/public/build/home:rawtherapee/Fedora_Rawhide/x86_64/rawtherapee-unstable/_log

**Comment by Floessie** [comment]
@mbajor Marcin, could you point me to the line where it fails, for I don't see a problem in the log...

**Comment by mbajor** [comment]
@Floessie Hmmmm. This is latest build log. It is build again without errors, so that means it was distribution error.
