### ISSUE TITLE
Corrupted pixels near image's edge when using Amaze demosaicing and specific flat field image

### ISSUE THREAD

**Issue by jannefoo** [Beep6581/RawTherapee#4378]
Corrupted rows of pixels appear in the edge portion of an image when using flat field image that has been processed with Pixelfixer (eg. averaged from several raw files). However, the corruption is not present when viewing the flat field image alone, only when applying the flat field image to regular, untouched DNG file. Amaze is the only demosaicing method that shows the corrupted pixels.

Screenshot: https://i.imgur.com/y6T6Nhz.png
Files for testing: https://filebin.net/250br3gup65dueqo/2018-02-06__Polaris_.zip (link is valid for 2 months)

Tested with RT 5.2 and 5.3.

**Comment by heckflosse** [comment]
@jannefoo Are you sure this is caused by the flat field file and not by the dark frame file `masterdark-dsc_5718.dng` which unfortunately is not in the zip?

**Comment by heckflosse** [comment]
@jannefoo Scratch my comment. The pp3 in the zip was set to igv. Now using amaze I can reproduce

**Comment by heckflosse** [comment]
That's somehow caused by the black stripe at upper border of flat field image

**Comment by heckflosse** [comment]
This patch fixes the issue. It skips correction for areas where the pixel values in flat field image are <= 1.0
Currently it does it only for bayer sensor files. When the patch is reviewed, I'll add the functionality also for xtrans.

```diff
diff --git a/rtengine/rawimagesource.cc b/rtengine/rawimagesource.cc
index 04066d49..48a9f0e3 100644
--- a/rtengine/rawimagesource.cc
+++ b/rtengine/rawimagesource.cc
@@ -2894,6 +2894,7 @@ void RawImageSource::processFlatField(const RAWParams &raw, RawImage *riFlatFile
         c4[1][0] = c[1][0];
         c4[1][1] = c[1][1];
 
+        constexpr float minValue = 1.f; // if the pixel value in the flat field is less or equal this value, no correction will be applied.
 #ifdef __SSE2__
         vfloat refcolorv[2] = {_mm_set_ps(refcolor[0][1], refcolor[0][0], refcolor[0][1], refcolor[0][0]),
                                _mm_set_ps(refcolor[1][1], refcolor[1][0], refcolor[1][1], refcolor[1][0])
@@ -2902,7 +2903,8 @@ void RawImageSource::processFlatField(const RAWParams &raw, RawImage *riFlatFile
                             _mm_set_ps(black[c4[1][1]], black[c4[1][0]], black[c4[1][1]], black[c4[1][0]])
                            };
 
-        vfloat epsv = F2V(1e-5f);
+        vfloat onev = F2V(1.f);
+        vfloat minValuev = F2V(minValue);
 #endif
 #ifdef _OPENMP
         #pragma omp parallel for schedule(dynamic,16)
@@ -2915,7 +2917,9 @@ void RawImageSource::processFlatField(const RAWParams &raw, RawImage *riFlatFile
             vfloat rowRefcolorv = refcolorv[row & 1];
 
             for (; col < W - 3; col += 4) {
-                vfloat vignettecorrv = rowRefcolorv / vmaxf(epsv, LVFU(cfablur[(row) * W + col]) - rowBlackv);
+                vfloat blurv = LVFU(cfablur[(row) * W + col]) - rowBlackv;
+                vfloat vignettecorrv = rowRefcolorv / blurv;
+                vignettecorrv = vself(vmaskf_le(blurv, minValuev), onev, vignettecorrv);
                 vfloat valv = LVFU(rawData[row][col]);
                 valv -= rowBlackv;
                 STVFU(rawData[row][col], valv * vignettecorrv + rowBlackv);
@@ -2924,7 +2928,8 @@ void RawImageSource::processFlatField(const RAWParams &raw, RawImage *riFlatFile
 #endif
 
             for (; col < W; col ++) {
-                float vignettecorr = refcolor[row & 1][col & 1] / max(1e-5f, cfablur[(row) * W + col] - black[c4[row & 1][col & 1]]);
+                float blur = cfablur[(row) * W + col] - black[c4[row & 1][col & 1]];
+                float vignettecorr = blur <= minValue ? 1.f : refcolor[row & 1][col & 1] / blur;
                 rawData[row][col] = (rawData[row][col] - black[c4[row & 1][col & 1]]) * vignettecorr + black[c4[row & 1][col & 1]];
             }
         }

```

**Comment by Floessie** [comment]
The code looks reasonable, though I didn't check the semantics of `vmaskf_le()` (`le` is "less or equal", `f` is `float`, but `mask`?).

👍 from me.

**Comment by heckflosse** [comment]
@Floessie [vmaskf_le(a, b)](https://github.com/Beep6581/RawTherapee/blob/dev/rtengine/helpersse2.h#L317) creates a 128bit mask which then is used in [vself](https://github.com/Beep6581/RawTherapee/blob/dev/rtengine/sleefsseavx.c#L909) to select the correct values.

in newer gcc versions you can even write `a = a <= b ? 1.f : a;` where `a` and `b` are vectors of 4 floats, but clang does not like that.

**Comment by Floessie** [comment]
Now I see. For reference:

https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm_cmple_ps&expand=988

https://software.intel.com/sites/landingpage/IntrinsicsGuide/#expand=436&text=_mm_blendv_ps

Thanks!

**Comment by heckflosse** [comment]
@Floessie the documentation for _mm_blendv_ps is obviously wrong
```
__m128 _mm_blendv_ps (__m128 a, __m128 b, __m128 mask)   <= three arguments
Instruction: blendvps xmm, xmm                           <= two arguments

**Comment by Floessie** [comment]
@heckflosse Not the only thing that is wrong at Intel... 😉

**Comment by heckflosse** [comment]
@Floessie seems I was wrong:
`The register assignment of the implicit mask operand for BLENDVPS is defined to be the architectural register XMM0`

**Comment by heckflosse** [comment]
Just to clarify. This patch will be for after release of 5.4
