### ISSUE TITLE
Float tiff files saved from rt should look the same as int tiff files saved from rt when opened in rt

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#4379]
To reproduce:

1) download [this underexposed NEF](https://filebin.net/kowy715lr027rul1/D700_20140718_4161.NEF) (Jacques, Hombre and DrSlony know the dog)
2) Open the NEF in rt and apply neutral profile
3) save to 16 bit tiff
4) save to 32 bit tiff
5) compare the tiffs, they should look equal, but they don't, because the missing highlights lead to brightening the 32 bit tiff while opening in rt (caused by normalization to min and max values in the tiff)

16 bit tiff opened in rt (same as the raw)
![grafik](https://user-images.githubusercontent.com/13733487/35943226-a443943a-0c58-11e8-849a-2298d2e03cfd.png)

32 bit float tiff opened in rt
![grafik](https://user-images.githubusercontent.com/13733487/35943261-bf96abc8-0c58-11e8-8679-8f27f299fcac.png)

**Comment by heckflosse** [comment]
Here's a possible patch:

```diff
diff --git a/rtengine/imageio.cc b/rtengine/imageio.cc
index 306c9589..ba8b35b4 100644
--- a/rtengine/imageio.cc
+++ b/rtengine/imageio.cc
@@ -835,7 +835,7 @@ int ImageIO::loadTIFF (Glib::ustring fname)
 
     allocate (width, height);
 
-    float minValue[3] = {0.f, 0.f, 0.f}, maxValue[3] = {0.f, 0.f, 0.f};
+    float minValue[3] = {0.f, 0.f, 0.f}, maxValue[3] = {1.f, 1.f, 1.f};
     unsigned char* linebuffer = new unsigned char[TIFFScanlineSize(in) * (samplesperpixel == 1 ? 3 : 1)];
 
     for (int row = 0; row < height; row++) {

```

with this patch, 32 bit tiffs which are in [0;1] range will stay in [0;1] range instead of being normalized from [0;max value of tiff] to [0;1] range.
32 bit tiffs which exceed the [0;1] range will be normalized to [0;1] range but not clipped.

**Comment by Hombre57** [comment]
@heckflosse 

No, because it's only an initialization, they will be computed later. I'm preparing a patch.

**Comment by heckflosse** [comment]
@Hombre57 I tested and it works for what I suggested

Edit: and the initial value of max and min of course has an influence on the resulting value ;-)

**Comment by Hombre57** [comment]
@heckflosse We don't want to normalize at all, as said by Elle.

**Comment by heckflosse** [comment]
@Hombre57 👍 for not normalizing at all. I just wanted to make a minimal invasive patch :)

**Comment by Hombre57** [comment]
Ok, but I'd recommend you to tell what you have in mind.

**Comment by heckflosse** [comment]
I had in mind to keep images which are in [0;1] range in that range instead of normalizing from [min >=0;max<=1] to [0;1] range and to normalize images which exceed the [0;1] range to [0;1] range.

But as I already wrote: 👍 for not normalizing at all

**Comment by Desmis** [comment]
@heckflosse 

Ingo
Felix, how is he?
jacques

**Comment by heckflosse** [comment]
@Desmis

Jacques
Felix and cri-cri are doing well :)

Ingo

**Comment by Hombre57** [comment]
@heckflosse I pushed the fix in `non-scaled-tiff32` branch.

**Comment by heckflosse** [comment]
@Hombre57 👍 from me to merge into release5.4 But let's wait for other opinions too

**Comment by Beep6581** [comment]
I tested `dev` 5.3-614-g786b73b8 vs `non-scaled-tiff32` 5.3-615-gd7f7c06f, compressed and uncompressed 32-bit TIFFs. No issues found. +1 for merge for 5.4.

**Comment by Hombre57** [comment]
@Beep6581 What is the process ? Should I push to `dev` first ? Or to `release5.4` directly ?

**Comment by Beep6581** [comment]
To `dev`, then we merge `dev` into `release5.4` (or cherry-pick if there's a commit we don't want, but currently there isn't).
