### ISSUE TITLE
Curves UI & Wacom Pen

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#438]
Originally reported on Google Code with ID 448
```
Curves UI does not work with wacom pen. The cursor is always large crossed arrows. This
worked better, although not flawlessly before and got broken completely ... hmm about
a month or so ago.

There does not seem to be any issues with using mouse in curves UI.
```

Reported by `michaelezra000` on 2010-12-29 22:34:29

**Comment by Hombre57** [comment]
@michaelezra wrote in issue #3103 :
> Hombre, I just tried 4.2.699 build with GTK3 and happily report that curves work with my Wacom tablet!
I mean !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Closing :)
