### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by Kildor** [Beep6581/RawTherapee#4383]
Here is Russian translation (incomplete) for current dev. I've cleaned up all translated strings (to fix shortcuts and so on). Also I've started to translate new strings, but not sure if I find more time before the release.
I did not sort resulted file.

[Russian.txt](https://github.com/Beep6581/RawTherapee/files/1713104/Russian.txt)

PS: Previous translation was made exactly 4 years ago also by me)

**Comment by Beep6581** [comment]
Thank you @Kildor 
You still have time to update the non-translated strings for 5.4-final.

**Comment by Kildor** [comment]
[Russian.txt](https://github.com/Beep6581/RawTherapee/files/1723677/Russian.txt)
Last bunch of changes I had any changes to done.

**Comment by Beep6581** [comment]
Committed.
Please open a new issue in the future.
