### ISSUE TITLE
Using Wavelet/Residual with contrast set to != 0 crashes on completely black image

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#4399]
To reproduce:

1) open amsterdam.pef
2) apply neutral profile
3) set Exposure compensation to -5
4) set Black in Exposure tool to 32768 => now we have a completely black image
5) enable wavelet
6) enable residual
7) set contrast in residual to 1 => crash

**Comment by heckflosse** [comment]
Fixed with this patch:

```diff
diff --git a/rtengine/ipwavelet.cc b/rtengine/ipwavelet.cc
index ad4a169b..572e8429 100644
--- a/rtengine/ipwavelet.cc
+++ b/rtengine/ipwavelet.cc
@@ -1739,6 +1739,11 @@ void ImProcFunctions::WaveletcontAllL(LabImage * labco, float ** varhue, float *
 
     }
 
+    if(max0 <= 0.0) {
+        // completely black image => nothing to do
+        return;
+    }
+
     //      printf("MAXmax0=%f MINmin0=%f\n",max0,min0);
 
 //tone mapping

```

**Comment by gaaned92** [comment]
Bug corrected. Thank you

**Comment by Desmis** [comment]
@heckflosse 
I just proposed the same modification, but you are faster than me :)

Jacques
