### ISSUE TITLE
RT Crashes on CL LAB curve 

### ISSUE THREAD

**Issue by age1988** [Beep6581/RawTherapee#4402]
Latest pull from Dev:

AboutThisBuild.txt:

Version: 5.3-639-g38cab123f
Branch: dev
Commit: 38cab123f
Commit date: 2018-02-15
Compiler: gcc 7.3.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.22.0
Lensfun: V0.3.2.0
Build type: release
Build flags:  -m64 -mwin32 -mthreads -Wno-aggressive-loop-optimizations -std=c++11 -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations  -DNDEBUG  -O3
Link flags: -m64 -mthreads  -static-libgcc   -mtune=generic  -s -O3
OpenMP support: ON
MMAP support: ON

Reproducing the bug:

1. Neutral profile
2. Click on lab adjustment
3. Set mid point in CL curve
4. Program crashes

[CRW_0501.zip](https://github.com/Beep6581/RawTherapee/files/1731171/CRW_0501.zip)

**Comment by heckflosse** [comment]
@age1988 Crash confirmed. Looking
