### ISSUE TITLE
Using EXIF and XMP Rating tag

### ISSUE THREAD

**Issue by lewicki-pk** [Beep6581/RawTherapee#4403]
Hi,
I would like to implement the feature asked about [here](https://discuss.pixls.us/t/get-the-ranking-file-property-into-rawtherapee/5253) and here: #3728 

My idea is that when the `Rating` tag is available- it should be used, but it should not be overwritten. If a `Rank` parameter exists in pp3 it should have higher priority.

I have already started the implementation and you can see it [here](https://github.com/lewicki-pk/RawTherapee/commit/0384671f1bcc4475e5c5cb13e46da650dff53ca9).

I have decided to add the new field to the `ImageData` class that's called `rating`. It is filled with a value taken from tag Rating.

If tag `Rating` does not exist- it gets created with value `0`.

The methods `getRank()` and `setRank()` has been changed so they get/set the new `rating` variable instead of `rank` from `ProcParams`.

**Result:**<br>
Now when I open any new directory- the Rating values get read from the metadata and is displayed as stars. I can also use star fillters. When I reopen the same directory- the "star" rating does not get read.

**Questions:**<br>
* I would like to fix the issue with no star ranking when I'm reopening the directory. Is there an additional cache that is used here?
* I wonder if I should add a new entry to the `ProcParams` with the rating from metadata or should I reuse the `Rank` that's already there. The latter makes more sense to me, but I'm not sure where and how to do so.

I'm looking forward to the comments and tips.

**Comment by Beep6581** [comment]
Hey @lewicki-pk 

Great to hear that you're volunteering to implement this.

How about this logic regarding rating:
1. Get rating from IPTC [`ImageRating`](https://iptc.org/std/photometadata/specification/IPTC-PhotoMetadata#image-rating) `[0;1]`
2. Overwrite with rating from Exif `0x4746` [`Rating`](http://www.exiv2.org/tags.html)
3. Overwrite with rating from XMP [`Rating`](https://sno.phy.queensu.ca/~phil/exiftool/TagNames/XMP.html#xmp) [-1;5]
4. Overwrite with rating from RT `rank` [0;5]

The saved image will then have all rating tags (IPTC, Exif, XMP) set to whatever the end result of the above was.

This is just a suggestion to start a discussion.

**Comment by lewicki-pk** [comment]
Hey @Beep6581 

Yup, I'll implement it :smile_cat: 

Regarding logic- I've came up with some requirements basing on your comment:

1. Reading.
As you wrote above the reading of an image rating is as follows:
   * IPTC `ImageRating`
   * Exif `Rating`
   * XMP `Rating`
   * RawTherapee `Rank` (in Cache)
   * RawTherapee `Rank` (in pp3 file)

Starting from the top and the new rating from the line below will override the rating from the line above.
If any of them doesn't exist- the step gets omitted (e.g. XMP is missing- the Exif gets read and then RT rank overrides it).

I have listed two RT `rank`s in both cache and pp3 files.<br>
Do you think we need both?

2. Changing the value of the `Rating`

When working with RT we should not change the IPTC, Exif or XMP data of an image file, but use the RT files (again either cache or pp3) for it.

If somebody gets rid of both cache and pp3 file- the Rating of an image will be reconstructed from the metadata.

3. Saving

When exporting an image the new rating will be saved into that file. (Should not apply when the new image does not save any metadata).

The RT Rank (from either cache or pp3- need to clarify) will be taken here and stored in the metadata.
For IPTC of course values from 2 to 5 need to be changed to 1.

What about `-1` value in the `Rank`? Should this be supported? I mean: should this be stored in the RT `Rank`?


Current status:
I have already implemented reading Exif Rating and storing it in cache. Filtering images via "Stars" works and that's basically everything I needed to fulfill my workflow.

As soon as I have time (which should be next week) I will implement the missing parts.

In the meantime- I'm waiting for comments :-)

**Comment by Beep6581** [comment]
Great news :)

> I have listed two RT ranks in both cache and pp3 files. Do you think we need both?

If you mean one which holds the result of the cascading (IPTC, Exif, XMP), and one which holds the value from RT's File Browser (Rank), then the former is probably not needed.

> When working with RT we should not change the IPTC, Exif or XMP data of an image file

Yes, RT should never modify the source image.

> What about -1

I don't know... "rejected" is not the same as "this image sucks, 0". Maybe give it a red color label for now, and we can check what other software do, such as darktable and digiKam.

**Comment by lewicki-pk** [comment]
Hi,
I just wanted to let you know that I'm a bit blocked now (with other work) and the feature is not finished yet.
The basic implementation that allows reading the stars and using them to filter the photos is available [>here<](https://github.com/lewicki-pk/RawTherapee) but it is far from perfect.
I'll work on polishing that up.

**Comment by Beep6581** [comment]
Hi @lewicki-pk , any chance this will be done in the next month?

**Comment by lewicki-pk** [comment]
Hi @Beep6581,
I'm sorry, but I've stopped working on it and started using different software.

I won't be able to finish what I've started.

**Comment by Beep6581** [comment]
Ah, that's a pity.

**Comment by erjiang** [comment]
@lewicki-pk What remains to be done on this feature? Curious to know if it's something I'd be able to finish.

**Comment by lewicki-pk** [comment]
Hi @erjiang,
In the end I haven't done much in the topic, but feel free to check out my
fork. It is more than thousand commits behind current master and there are
only a couple of lines changed but it will at least show you where to start.
The change does not seem that big or difficult so I think you should be
able to handle that.
Good luck.

**Comment by erjiang** [comment]
@lewicki-pk Thanks, your work is a good starting point for me.

I've gotten the code to check EXIF, then XMP, then pp3 for rating and allow user to override the embedded rating via the pp3 rank. But I've run into an issue where there's no way to override the embedded rating with 0.

If image has Rating=5, user can set rank to 1-5, but if user tries to set rank to 0, then the code has no way of knowing whether the 0 came from the pp3 file or is the default 0 from the ProcParams initializer (no pp3 file).

@Beep6581 Any suggestions for distinguishing the two cases? My WIP is at https://github.com/erjiang/RawTherapee/tree/embedded-ratings

**Comment by erjiang** [comment]
I changed the default value of `pparams->rank` to `-1`. rank=-1 means "no pparams from disk", and rank=0 means "rank=0 based on pparams from disk". Feels a bit hacky, so let me know if there's a better way.

**Comment by Hombre57** [comment]
@erjiang What is the meaning of `-1` in the XMP ranking tag ? Is there a special `bool rankSet` tag in XMP's specification ?

**Comment by lewicki-pk** [comment]
As far as I know `-1` can be used for setting "Rejected" image but not all formats support this. XMP does support it.

**Comment by erjiang** [comment]
@Hombre57 There is no "rankSet" tag that I know of. Official definition of `xmp:rating` is:

> A user-assigned rating for this file. The value shall be -1 or in the range [0..5], where -1 indicates “rejected” and 0 indicates “unrated”. If xmp:Rating is not present, a value of 0 should be assumed.

If we want to support xmp:Rating = -1, maybe we can use it to set InTrash == true? That way you can reject images in-camera during your shoot, browse them with RT and filter for InTrash, and then nuke them.

**Comment by Beep6581** [comment]
Implemented in PR #5325
