### ISSUE TITLE
Using CbDL reduce artifacts leads to wrong colours in thumbnail and also for < 100% preview

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#4407]
To reproduce:

Use this [raw ](https://filebin.net/zwf5rgm0jz6ckc1b/DSC08105.ARW) (thanks to @agriggio for permission to use it, @Beep6581 please upload it to shared/test_images) with this pp3
[DSC08105.ARW.pp3.zip](https://github.com/Beep6581/RawTherapee/files/1737861/DSC08105.ARW.pp3.zip)

![grafik](https://user-images.githubusercontent.com/13733487/36392278-bd462438-15aa-11e8-874c-570fa8fa6032.png)

I will include a fix into #4406

**Comment by heckflosse** [comment]
Background to the issue and the solution:

Before 0bed7fb always the same radius was used for the gaussian blur when using `ciecam02 + cbdl reduce artifacts` which.

Now the radius is scaled by the preview zoom factor and for thumbnails the processing is skipped

**Comment by Beep6581** [comment]
@agriggio does this doll have a name?

**Comment by Beep6581** [comment]
Uploaded:
http://rawtherapee.com/shared/test_images/pippi.arw
http://rawtherapee.com/shared/test_images/kitchen.hdr.dng

**Comment by heckflosse** [comment]
@Beep6581 

> does this doll have a name?

That's [Pippi](https://sv.wikipedia.org/wiki/Pippi_L%C3%A5ngstrump)

**Comment by Beep6581** [comment]
Link updated :)

**Comment by agriggio** [comment]
@Beep6581 how come you live in Sweden and don't know about pippi? ;-)

**Comment by Beep6581** [comment]
I'm more into Asterix and Tintin ;)
