### ISSUE TITLE
Hugin HDR TIFF files support 

### ISSUE THREAD

**Issue by madarexxx** [Beep6581/RawTherapee#4410]
RawTherapee doesn't show or open 16-bit channel TIFF files produced by Hugin. I cannot provide TIFF files, because my university thinks that students don't need to upload files from dormitories :(

Steps to reproduce:
1) Get Hugin from repos or http://hugin.sourceforge.net/ . Any reasonable version will be good.
2) Add photo(s) to project
3) Stitch project with output file type: HDR, save as TIFF, no compression
4) Try to open this file with RawTherapee
5) See empty editor mode

Expected work: image is opened and can be developed.

My RawTherapee version info:

```
Version: 5.3
Branch: 5.3
Commit: ec0f7936
Commit date: 2017-09-30
Compiler: gcc 7.2.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.22.0
Lensfun: V0.3.2.0
Build type: release
Build flags:  -m64 -mwin32 -mthreads   -Wno-aggressive-loop-optimizations -std=c++11 -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations  -DNDEBUG  -O3
Link flags: -m64 -mthreads  -static-libgcc   -mtune=generic  -s -O3
OpenMP support: ON
MMAP support: ON
```
My system is Windows 7 Professional x64 SP1 (completely genuine), Intel Core i7 4700MQ, 16 Gb RAM.

Download link for this build of Rt is: http://rawtherapee.com/releases_head/windows/RawTherapee_5.3_WinVista_64.zip

Thanks in advance :) RawTherapee is awesome! 
p.s. Is it possible to make properties syncable between different computers? I want to set up dynamic profile rules, but setting them on all my copies of RT (2 laptops with Linux and Windows) is not comfortable.

**Comment by Hombre57** [comment]
@madarexxx

> p.s. Is it possible to make properties syncable between different computers? I want to set up dynamic profile rules, but setting them on all my copies of RT (2 laptops with Linux and Windows) is not comfortable.

It is possible to put your config folder in a shared folder on the network using the [RT_SETTINGS env variable](http://rawpedia.rawtherapee.com/File_Paths#Custom_config_and_cache_folders), otherwise no sync possible.

**Comment by Beep6581** [comment]
@madarexxx we reproduced the problem on our end, but it seems likely that the source of the problem lies within Hugin. For one, the saved TIFF files use LZW compression even when you select "Compression: None". GIMP doesn't open the image correctly either.

I suggest you report this upstream to Hugin: https://bugs.launchpad.net/hugin

**Comment by Thanatomanic** [comment]
I cannot reproduce this in the latest 5.4 dev. A HDR 32 bits floating-point uncompressed TIFF from Hugin 2018.0.0 loads fine in RT.
