### ISSUE TITLE
shortcuts alt+f/f

### ISSUE THREAD

**Issue by manniclick** [Beep6581/RawTherapee#4417]
The functionality of this shortcuts is reversed.
```
Version: 5.4-rc2
Branch: 5.4-rc2
Commit: 042c49d34
Commit date: 2018-02-26
Compiler: gcc 7.3.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.22.0
Lensfun: V0.3.2.0
Build type: release
Build flags:  -m64 -mwin32 -mthreads -Wno-aggressive-loop-optimizations -std=c++11 -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations  -DNDEBUG  -O3
Link flags: -m64 -mthreads  -static-libgcc   -mtune=generic  -s -O3
OpenMP support: ON
MMAP support: ON
```

**Comment by Beep6581** [comment]
That was an intentional change.
I updated RawPedia now, thanks for reporting.

**Comment by manniclick** [comment]
In that case the text describing the buttons below the editor window must be changed accordingly.

**Comment by Beep6581** [comment]
@manniclick Can you point this text out? Do you mean the tooltip? Which language are you running RT in?

**Comment by heckflosse** [comment]
In default language it seems fine:

![grafik](https://user-images.githubusercontent.com/13733487/36793906-08c9b0d2-1c9f-11e8-85a5-d382d7b946c6.png)

**Comment by Beep6581** [comment]
I see that all of the translations are outdated. Fixing.

**Comment by Beep6581** [comment]
Fixed.
