### ISSUE TITLE
flat field correction not available with monochrome dng files

### ISSUE THREAD

**Issue by jannefoo** [Beep6581/RawTherapee#4418]
sample: https://filebin.net/bkojqc8pxupmg9oz

open the file in rt and check the raw tab, only dark frame subtraction is available and not flat field correction.

file was converted from regular dng to mono-dng with monochrome2dng: https://www.fastrawviewer.com/Monochrome2DNG

**Comment by heckflosse** [comment]
@jannefoo Did you try to process the original raw file (not the generated dng) in rt using demosaic method set to `Mono` ?

**Comment by jannefoo** [comment]
that works, but I see no reason the mono dng should not work too.

**Comment by heckflosse** [comment]
@jannefoo I created [branch flatfield_monochrom](https://github.com/Beep6581/RawTherapee/tree/flatfield_monochrom)
