### ISSUE TITLE
Pixel Shift default profiles do not use histogram matching

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4420]
While our new default processing profile for raw images uses histogram matching by default, the Pixel Shift PP3s do not. @heckflosse should it stay like this for 5.4?

**Comment by heckflosse** [comment]
The Pixel Shift PP3s are very small partial profiles which are made to be applied on top of other profiles.

**Comment by Beep6581** [comment]
Ok.
