### ISSUE TITLE
Missing strings in Settings / Batch processing / Noise Reduction

### ISSUE THREAD

**Issue by mkyral** [Beep6581/RawTherapee#4423]
Hi,
I just updating Czech translation and I've found these missing strings in Settings / Batch processing / Noise Reduction:

![obrazek](https://user-images.githubusercontent.com/155542/36925562-c521c640-1e73-11e8-826f-55b6a12249fb.png)

**Comment by Beep6581** [comment]
Thanks for reporting, I'll take this.
