### ISSUE TITLE
Ugly application's icon

### ISSUE THREAD

**Issue by Hombre57** [Beep6581/RawTherapee#4425]
On Windows 7, the icon displayed in the task bar (and only there) is ugly, very pixelated.

![ugly-app-icon](https://user-images.githubusercontent.com/13788115/36927598-d0227ade-1e7e-11e8-93a3-eeeb283289f4.png)

On the left, a nice icon used for the console window (it's a Debug build), but on the right, the application's icon is pixelated.

It's a low priority issue, but would be nice to have something cleaner.

**Comment by heckflosse** [comment]
Looks good here on my Windows 7

![grafik](https://user-images.githubusercontent.com/13733487/36932983-de4006ba-1ed1-11e8-9d44-824cb860ca59.png)

**Comment by Hombre57** [comment]
@heckflosse You have tiny-micro icons 😃, they will always look good at this size. I think it uses the hi16 version in your case, and an upscaled hi16 one in my case, instead of using hi32. I'll have a look.

**Comment by Beep6581** [comment]
For work, I tested which icon bit depths, compression and alpha work and which don't in Windows XP and upward. In XP you are limited to 8bpp uncompressed icons. As we no longer support XP, it's worth trying higher bit depths and compressions.

You can test these three `ico` files by replacing `/rtdata/icons/RT.ico` with one of them:
https://filebin.net/rticotest

**Comment by Hombre57** [comment]
@Beep6581 @heckflosse  I think I've found the culprit. We must define an icon list for RT's windows with `Gtk::Window::set_default_icon_list`.

Here is a patch that use more icons from `rtdata\images` and solve the problem :

```patch
diff --git a/rtgui/rtwindow.cc b/rtgui/rtwindow.cc
index 860221e..4bf0444 100644
--- a/rtgui/rtwindow.cc
+++ b/rtgui/rtwindow.cc
@@ -93,11 +93,13 @@
     WhiteBalance::init();
     ProfilePanel::init (this);
 
-    Glib::ustring fName = "rt-logo-small.png";
-    Glib::ustring fullPath = rtengine::findIconAbsolutePath (fName);
-
+    std::vector< Glib::RefPtr<Gdk::Pixbuf> > appIcons(4);
+    appIcons[0] = RTImage::createFromFile ("rt-logo-tiny.png");
+    appIcons[1] = RTImage::createFromFile ("rt-logo-small.png");
+    appIcons[2] = RTImage::createFromFile ("rt-logo-medium.png");
+    appIcons[3] = RTImage::createFromFile ("rt-logo-large.png");
     try {
-        set_default_icon_from_file (fullPath);
+        set_default_icon_list(appIcons);
     } catch (Glib::Exception& ex) {
         printf ("%s\n", ex.what().c_str());
     }
```

It would be nice if we could have a 48x48px logo in rtdata/images.

**Comment by Hombre57** [comment]
Just for comparison, here is the result of the patch above :

![app-icon01](https://user-images.githubusercontent.com/13788115/36938624-8481beea-1f24-11e8-968f-9966a628264f.png)

You can see that they are slightly different because icons from the `images` and `icons` folder are different.

On Windows, we may not want to set a particular icon because windows will then use the RT.ico file, which include all icon size. The following patch will still add a list of icon of different size, but for Apple and Linux system only.

```patch
diff --git a/rtgui/rtwindow.cc b/rtgui/rtwindow.cc
index 860221e..ccf7a84 100644
--- a/rtgui/rtwindow.cc
+++ b/rtgui/rtwindow.cc
@@ -93,14 +93,18 @@
     WhiteBalance::init();
     ProfilePanel::init (this);
 
-    Glib::ustring fName = "rt-logo-small.png";
-    Glib::ustring fullPath = rtengine::findIconAbsolutePath (fName);
-
+#ifndef WIN32
+    std::vector< Glib::RefPtr<Gdk::Pixbuf> > appIcons(4);
+    appIcons[0] = RTImage::createFromFile ("rt-logo-tiny.png");
+    appIcons[1] = RTImage::createFromFile ("rt-logo-small.png");
+    appIcons[2] = RTImage::createFromFile ("rt-logo-medium.png");
+    appIcons[3] = RTImage::createFromFile ("rt-logo-large.png");
     try {
-        set_default_icon_from_file (fullPath);
+        set_default_icon_list(appIcons);
     } catch (Glib::Exception& ex) {
         printf ("%s\n", ex.what().c_str());
     }
+#endif
 
 #if defined(__APPLE__)
     {
```

Here is what I get then :

![app-icon02](https://user-images.githubusercontent.com/13788115/36938648-fa14542e-1f24-11e8-831e-cefa62ebed42.png)


Icons are the same.

**Comment by Floessie** [comment]
@Hombre57 Just a small tip: Instead of creating a fixed size `std::vector<>` and setting the items afterwards, you can just do that in an init list:

```c++
const std::vector<Glib::RefPtr<Gdk::Pixbuf>> appIcons = {
    RTImage::createFromFile("rt-logo-tiny.png"),
    RTImage::createFromFile("rt-logo-small.png"),
    RTImage::createFromFile("rt-logo-medium.png"),
    RTImage::createFromFile("rt-logo-large.png")
};
```

Best,
Flössie

**Comment by Hombre57** [comment]
@floessie Thanks for the tip, I'll use that in the commit tonight if no one complains.

**Comment by Hombre57** [comment]
Pushed in commit 478e1c0. Closing.
