### ISSUE TITLE
FR: File browser option for looking into subfolder as well

### ISSUE THREAD

**Issue by X-Raym** [Beep6581/RawTherapee#4434]
Hi,

Maybe I miss a setting or something (v5.3)

but it seems that the the file browser only display files/Images of the current folder, and not of its subfolders.

Did I miss something ?

Else, it would be a nice feature to have.

Thanks !

**Comment by Beep6581** [comment]
Duplicate of #3756

**Comment by X-Raym** [comment]
@Beep6581 oops sorry. I didn't search for "dir tree" keyword.
