### ISSUE TITLE
"Auto matching tone curve" reset highlight compression to 0

### ISSUE THREAD

**Issue by agriggio** [Beep6581/RawTherapee#4437]
As the subject says. I can't commit right now, but this should fix it:

```diff
diff --git a/rtgui/tonecurve.cc b/rtgui/tonecurve.cc
--- a/rtgui/tonecurve.cc
+++ b/rtgui/tonecurve.cc
@@ -943,7 +943,6 @@
     brightness->setValue(0);
     contrast->setValue(0);
     black->setValue(0);
-    hlcompr->setValue(0);
 
     if (!black->getAddMode()) {
         shcompr->set_sensitive(!((int)black->getValue() == 0));
```

**Comment by agriggio** [comment]
@Beep6581 how should I fix this? Push to `dev` and merge into `release5.4`? Or should I cherry-pick?

**Comment by Beep6581** [comment]
@agriggio it doesn't matter yet as there are no changes in `dev` which we don't want in 5.4, so straight to `dev` is fine. I will merge it into `release5.4` later after committing some DCPs.
