### ISSUE TITLE
Possible bug in Color::gamutLchonly

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#4443]
While reviewing the `vibrance` code I found a possible bug in `Color::gamutLchonly`. At least it is a mismatch between comment and [code](https://github.com/Beep6581/RawTherapee/blob/dev/rtengine/color.cc#L2514).

The condition matches if at least one of the colours is clipped, while the comment says it should not match if all colours are clipped (let's ignore the `!isHLEnabled`).

```c
        } else if (!isHLEnabled && (R > ClipLevel || G > ClipLevel || B > ClipLevel)) {

// if "highlight reconstruction" is enabled or the point is completely white (clipped, no color), don't control Gamut
```

Shouldn't it be? :
```c
        } else if (!isHLEnabled && max(R, G, B) > ClipLevel && min(R, G, B) <= ClipLevel) {

// if "highlight reconstruction" is enabled or the point is completely white (clipped, no color), don't control Gamut
```
@Desmis Jacques, is the code wrong or the comment?

**Comment by Desmis** [comment]
@heckflosse 

Ingo 
You are true :)

I think, but I write this code 6 yeras ago ! that the good code is what you propose


else if (!isHLEnabled && max(R, G, B) > ClipLevel && min(R, G, B) <= ClipLevel) {

Jacques

**Comment by heckflosse** [comment]
@Desmis Jacques, thanks for confirmation. I will fix it for 5.5

**Comment by Beep6581** [comment]
Does it affect only the Vibrance tool?
Could you please explain what issues this bug caused from the user's perspective?
i.e. if an image looks different in 5.5 than it did before, what will look different?

**Comment by heckflosse** [comment]
@Beep6581 Hard to explain. The code is used to bring an image in gamut. It's used at some places in RT iirc. The condition in the old code matches the case that all colours are clipped while the comment said it should not match in this case. Jacques and I agreed that it would be correct to change the behavour instead of changing the comment.
