### ISSUE TITLE
dependencies_for_creating_builds folder

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4448]
@gaaned92 @sguyader there is a folder `dependencies_for_creating_builds` on our server, is that still needed?
http://rawtherapee.com/shared/builds/windows/dependencies_for_creating_builds/

**Comment by gaaned92** [comment]
@Beep6581 
I think it is no longer needed. These are old dependencies versions.
I order to have correct dependencies, they have to be copied directly from /mingw64/bin.

**Comment by Beep6581** [comment]
Great, deleted.
