### ISSUE TITLE
GPS and IPTC missing from TIFF files

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4464]
GPS and IPTC info is missing from both compressed and uncompressed TIFF files when using "Copy metadata unchanged". It's there in PNG and JPG files.

The ideal fix would be to adopt Exiv2 #3801

**Comment by Beep6581** [comment]
Sample files:
https://filebin.net/4qvyfigdm0e8pedd

**Comment by ofcgk9** [comment]
**Missing metadata (IPTC) after file save from v. 5.4 all formats**

I have Raw Therapee v. 5.4 installed on a 64 bit Windows 7 SP 1 computer with i5 processor and 8 GB RAM. 

When I open a RAW (NEF) file with RT v. 5.4, I see that the Exif data is present.  I enter IPTC data with separate application and verify that the IPTC data is there using that application.

When I save the file, no IPTC data transfers for any file format, and no Exif data transfers for the png format:

I save an 8 bit jpg (3+ MB) from RT

Exif data present
IPTC data window displayed, no data

I save a 16 bit TIFF (59+ MB) from RT

Exif data present
No IPTC data (IPTC window displayed in Photoshop Elements)

I save a 16 bit png (51+ MB) from RT

No Exif data*
No IPTC data (IPTC window displayed in Photoshop Elements)

Checked with:

IrfanView v. 4.44
Adobe Photoshop Elements 10
FastStone Image Viewer 6.0 (No IPTC data capability)
GIMP 2.10.0

* The following Exif data items are displayed in GIMP 2.10.0 (Image/Metadata/ViewMetadata):  Bits per sample, Image length, Image width, Resolution unit, X Resolution, Y resolution

**Comment by Beep6581** [comment]
@ofcgk9 what metadata copy mode did you use (see the top of the Metadata tab)?
Upload sample output files using https://filebin.net/

**Comment by ofcgk9** [comment]
Sorry, I thought I had included that info with my original post, but obviously not.  In all cases, the Metadata copy mode was "Copy unchanged."

**Comment by agriggio** [comment]
Here is a patch that tries to address at least some of the problems. It should allow to properly pass the original IPTC data (or at least, the IPTC data that is parsed by RT) when "Copy unchanged" is selected also for TIFF output.

```diff
diff --git a/rtengine/imageio.cc b/rtengine/imageio.cc
--- a/rtengine/imageio.cc
+++ b/rtengine/imageio.cc
@@ -95,6 +95,14 @@
         td->keepTag(0x02bc);  // XMP
 
         exifRoot = td;
+
+        if (!iptc) {
+            rtexif::Tag* t = exifRoot->getTag(0x83BB);
+            if (t) {
+                iptc = iptc_data_new_from_data ((unsigned char*)t->getValue (), (unsigned)t->getValueSize ());
+            }
+        }
+            
     }
 }
```

**Comment by ofcgk9** [comment]
Thank you.

How and when does this patch get incorporated into the Windows version of Raw Therapee?

**Comment by Beep6581** [comment]
I opened `madeira.dng` (it has GPS info) in RT `5.5-281-g`aa379308e, set some IPTC tags, set meta mode to "Apply modifications" and saved a JPG. It contains IPTC and GPS info.

![madeira](https://user-images.githubusercontent.com/5844619/55328107-e32bda00-548b-11e9-850f-38dc32999996.jpg)
```
$ exiv2 -pa /tmp/madeira.jpg | egrep -i "iptc_|gps"
Warning: Unsupported date format
Exif.Image.GPSTag                            Long        1  966
Exif.GPSInfo.GPSLatitudeRef                  Ascii       2  North
Exif.GPSInfo.GPSLatitude                     Rational    3  32deg 44.60350'
Exif.GPSInfo.GPSLongitudeRef                 Ascii       2  West
Exif.GPSInfo.GPSLongitude                    Rational    3  16deg 59.33900'
Iptc.Application2.ObjectName                 String     10  iptc_title
Iptc.Application2.SpecialInstructions        String     17  iptc_instructions
Iptc.Application2.DateCreated                String      8  iptc_dat
Iptc.Application2.Byline                     String     12  iptc_creator
Iptc.Application2.City                       String      9  iptc_city
Iptc.Application2.ProvinceState              String     13  iptc_province
Iptc.Application2.CountryName                String     12  iptc_country
Iptc.Application2.TransmissionReference      String     10  iptc_jobid
Iptc.Application2.Headline                   String     13  iptc_headline
Iptc.Application2.Source                     String     11  iptc_source
Iptc.Application2.Copyright                  String     14  iptc_copyright
Iptc.Application2.Caption                    String     16  iptc_description
Iptc.Application2.Writer                     String     23  iptc_description_writer
```
```
$ exiftool -G5 -s -a -m -u -args /tmp/madeira.jpg | egrep -i "iptc_|gps"
-JPEG-APP1-IFD0-GPS:GPSLatitudeRef=North
-JPEG-APP1-IFD0-GPS:GPSLatitude=32 deg 44' 36.21"
-JPEG-APP1-IFD0-GPS:GPSLongitudeRef=West
-JPEG-APP1-IFD0-GPS:GPSLongitude=16 deg 59' 20.34"
-JPEG-APP13-Photoshop-IPTC:ObjectName=iptc_title
-JPEG-APP13-Photoshop-IPTC:SpecialInstructions=iptc_instructions
-JPEG-APP13-Photoshop-IPTC:DateCreated=iptc_dat
-JPEG-APP13-Photoshop-IPTC:By-line=iptc_creator
-JPEG-APP13-Photoshop-IPTC:City=iptc_city
-JPEG-APP13-Photoshop-IPTC:Province-State=iptc_province
-JPEG-APP13-Photoshop-IPTC:Country-PrimaryLocationName=iptc_country
-JPEG-APP13-Photoshop-IPTC:OriginalTransmissionReference=iptc_jobid
-JPEG-APP13-Photoshop-IPTC:Headline=iptc_headline
-JPEG-APP13-Photoshop-IPTC:Source=iptc_source
-JPEG-APP13-Photoshop-IPTC:CopyrightNotice=iptc_copyright
-JPEG-APP13-Photoshop-IPTC:Caption-Abstract=iptc_description
-JPEG-APP13-Photoshop-IPTC:Writer-Editor=iptc_description_writer
-Composite:GPSLatitude=32 deg 44' 36.21" N
-Composite:GPSLongitude=16 deg 59' 20.34" W
-Composite:GPSPosition=32 deg 44' 36.21" N, 16 deg 59' 20.34" W
```

With the patch applied, I opened this JPG and saved one of every supported output format and setting using "copy unchanged" meta mode. The JPG and PNG files had GPS info but no IPTC. All TIFF files lacked both GPS and IPTC.

**Comment by AnotherKiwiEater** [comment]
The issue remains open in v5.8 as IPTC data is not being copied with the "Copy Unchanged" setting.  I have thousands of files that I want to process to address rotation issues, and I can't afford to lose the original IPTC data in updated files.  Since this problem is now over two years old, has anyone investigated or made progress on this in the last year.

**Comment by softwarelifecycle** [comment]
4 years out and not fixed?  This is pretty important info... I am taking hundreds of pics for a photogrammetry project that needs this GPS info... obviously updating each photo with GPS data is not possible... Please, this is an important and reasonable update to make...

**Comment by 10110111** [comment]
My current workaround for this is to run the following command to copy the tags from the original to the output file:
```
exiftool -tagsfromfile SOURCE_FILE -gps:all -wm cg DESTINATION_FILE
```
Note that sometimes exiftool-compatible GPS tags don't exist in a raw file but they do in a JPEG sidecar. This is true for my Samsung Galaxy S8. The phone was able to show the point on the map for both files, so maybe it's just that exiftool can't find the relevant tags.

**Comment by Lawrence37** [comment]
Done in #5889.
