### ISSUE TITLE
RawTherapee 5.4 doesn't detect images with certain dimensions

### ISSUE THREAD

**Issue by brussell1** [Beep6581/RawTherapee#4465]
For example, the FileBrowser doesn't show this image: https://raw.githubusercontent.com/crosire/reshade-shaders/master/Textures/lut.png
So it doesn't detect a 1024x32 image. However, If the y dimension is > 103 it works. 

Same behavior on linux and windows.

Info:
Version: 5.4
Branch: releases
Commit: a5e8eb9c
Commit date: 2018-03-20
Compiler: cc 7.3.1
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.22.2
Lensfun: V0.3.2.0
Build type: Release
Build flags: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -std=c++11  -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -O3 -DNDEBUG -ftree-vectorize
Link flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
OpenMP support: ON
MMAP support: ON

**Comment by Beep6581** [comment]
@brussell1 that was intentional, a hotfix to prevent crashes on very unusual dimensions. Maybe we should relax it a bit. Please comment in #3794 of which this issue is a duplicate.
