### ISSUE TITLE
Skip Auto-matched tone curve if embedded thumb is very small

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#4467]
That's kind of a feature request:

With the raw from [here](https://discuss.pixls.us/t/play-raw-rabbit-and-pigeon/7065) the auto matched tonecurve gives bad results because the embedded jpg is very small. Maybe we should restrict the auto matched tonecurve to a certain minimal size of the embedded preview.

@agriggio Alberto, what's your opinion?

**Comment by agriggio** [comment]
I agree :+1:

**Comment by heckflosse** [comment]
@agriggio Alberto, any suggestions for the minimal size based on your experience?

**Comment by agriggio** [comment]
if you look at the code there is some scaling down of the thumbs, though I don't remember the details right now. I'd say we should forbid upscaling, that's it

**Comment by agriggio** [comment]
@heckflosse how about this?

```diff
diff --git a/rtengine/histmatching.cc b/rtengine/histmatching.cc
--- a/rtengine/histmatching.cc
+++ b/rtengine/histmatching.cc
@@ -227,6 +227,13 @@
             histMatchingCache = outCurve;
             histMatchingParams = cp;
             return;
+        } else if (w * 10 < fw) {
+            if (settings->verbose) {
+                std::cout << "histogram matching: the embedded thumbnail is too small: " << w << "x" << h << std::endl;
+            }
+            histMatchingCache = outCurve;
+            histMatchingParams = cp;
+            return;
         }
         skip = LIM(skip * fh / h, 6, 10); // adjust the skip factor -- the larger the thumbnail, the less we should skip to get a good match
         source.reset(thumb->quickProcessImage(neutral, fh / skip, TI_Nearest));
```

**Comment by heckflosse** [comment]
@agriggio Works fine here. Thank you. :+1:
