### ISSUE TITLE
Icon cleanup

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4469]
Branch https://github.com/Beep6581/RawTherapee/tree/iconcleanup

1. Remove all obsolete icons from `rtdata/images`
2. Redraw all SVG icons using new Inkscape 0.92 format, with consistent template, grid, metadata, etc.
3. Create SVGs for icons which don't currently have an SVG plate.
4. Revise icon tree structure.
5. Write new scripts to make generating PNGs from SVGs clean and easy (Bash4 for now, Python in the future, not in this issue).

**Comment by Beep6581** [comment]
PR #4556 deletes unused icons.

**Comment by Beep6581** [comment]
Problematic files:
```text
identify: iCCP: profile 'Photoshop ICC profile': 0h: PCS illuminant is not D50 `rtdata/images/unrated.png' @ warning/png.c/MagickPNGWarningHandler/1665.
identify: iCCP: profile 'Photoshop ICC profile': 0h: PCS illuminant is not D50 `rtdata/images/ratednot.png' @ warning/png.c/MagickPNGWarningHandler/1665.
identify: iCCP: profile 'Photoshop ICC profile': 0h: PCS illuminant is not D50 `rtdata/images/ratednotg.png' @ warning/png.c/MagickPNGWarningHandler/1665.
identify: iCCP: profile 'Photoshop ICC profile': 0h: PCS illuminant is not D50 `rtdata/images/fullscreen-exit.png' @ warning/png.c/MagickPNGWarningHandler/1665.
identify: iCCP: profile 'Photoshop ICC profile': 0h: PCS illuminant is not D50 `rtdata/images/Light/actions/histChro.png' @ warning/png.c/MagickPNGWarningHandler/1665.
identify: iCCP: profile 'Photoshop ICC profile': 0h: PCS illuminant is not D50 `rtdata/images/Light/actions/histChrog.png' @ warning/png.c/MagickPNGWarningHandler/1665.
identify: iCCP: profile 'Photoshop ICC profile': 0h: PCS illuminant is not D50 `rtdata/images/Dark/actions/histChro.png' @ warning/png.c/MagickPNGWarningHandler/1665.
identify: iCCP: profile 'Photoshop ICC profile': 0h: PCS illuminant is not D50 `rtdata/images/Dark/actions/histChrog.png' @ warning/png.c/MagickPNGWarningHandler/1665.
identify: iCCP: profile 'Photoshop ICC profile': 0h: PCS illuminant is not D50 `rtdata/images/fullscreen.png' @ warning/png.c/MagickPNGWarningHandler/1665.
identify: iCCP: profile 'Photoshop ICC profile': 0h: PCS illuminant is not D50 `rtdata/images/PanelEnding.png' @ warning/png.c/MagickPNGWarningHandler/1665.
```

**Comment by Beep6581** [comment]
The FreeDesktop standard has sections on icon naming and tree structure:
https://standards.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html
https://standards.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html

Having reviewed RawTherapee's icon usage and read the specs, it seems to me that the specs don't apply to us and we cannot follow them. The specs are meant to make it possible to have GTK+ load icons automatically from a theme based on a hierarchy of folders and sizes (first try to load an icon of the preferred size from the preferred theme, if it doesn't exist try a different size, if still nothing try the fallback "hicolor" theme, etc.).

We don't rely on GNOME or KDE automatically loading icons through a cascade of themes. We set icons manually, e.g.:
```text
Gtk::Image* const iblueR   = Gtk::manage (new RTImage ("ajd-wb-temp1.png"));
```

Furthermore, our icons do not conform to the standard sizes (48x48, 32x32, etc.). Here is a list of all the sizes our icons use, sorted and unique:
```text
8x22
10x10
11x11
12x12
13x15
14x20
15x13
16x16
17x9
18x18
19x19
20x20
21x18
22x22
23x16
24x24
25x22
26x18
29x12
32x32
65x28
67x28
128x128
552x346
```
It is not possible to store these in folders by icon size as they don't have standard sizes, so why does our repository folder structure and icon scripts even play the `hicolor` FreeDesktop game?

I intend to reorganize the PNG and SVG folder structure and to write a new, simpler script for automatically generating PNG icons from SVG ones, with support for 2x scaling for HiDPI.

**Comment by Beep6581** [comment]
Part of the effort in this branch involves redesigning every single icon RT uses, both SVG and PNG, examining where and how the current icon's entity is used, and adapting the new one to some size standard.

Designations so far (the unit is pixels, the quantity is the longest dimension):
tiny = 10
small = 16
normal = 24

**Comment by Beep6581** [comment]
Previously, the icons were named to suite the code, which resulted in weird filenames, e.g.
`ajd-wb-green1.png` was actually magenta
`clabel1.png` and `ajd-wb-bluered2.png` were both just red circles, almost identical,
etc.
The new icons have filenames representative of what the file holds. e.g. `circle-red`, `circle-green`, etc.
I made the necessary [code changes](https://github.com/Beep6581/RawTherapee/commit/9cecad02f97dbfa8cb752a88dfc6006ed5122ba7#diff-0766c43d7e7f83c462b4c0430e379619), but there are still 5 places I'd appreciate some help with:
```text
rtgui/filecatalog.cc:204:        iCLabeled[i] = new RTImage (Glib::ustring::compose("%1%2%3", "clabel", i + 1, ".png"));
```
```text
rtgui/filecatalog.cc:205:        igCLabeled[i] = new RTImage (Glib::ustring::compose("%1%2%3", "cglabel", i + 1, ".png"));
```
```text
rtgui/filebrowser.cc:210:            submenuLabel->attach (*Gtk::manage(colorlabel[i] = new MyImageMenuItem (M(Glib::ustring::compose("%1%2", "FILEBROWSER_POPUPCOLORLABEL", i)), i == 0 ? "circle-empty-gray.png" : Glib::ustring::compose("%1%2%3", "clabel", i, ".png"))), 0, 1, p, p + 1);
```
```text
rtgui/filebrowser.cc:218:            pmenu->attach (*Gtk::manage(colorlabel[i] = new MyImageMenuItem (M(Glib::ustring::compose("%1%2", "FILEBROWSER_POPUPCOLORLABEL", i)), i == 0 ? "circle-empty-gray.png" : Glib::ustring::compose("%1%2%3", "clabel", i, ".png"))), 0, 1, p, p + 1);
```
```text
rtgui/filebrowser.cc:455:        pmenuColorLabels->attach (*Gtk::manage(colorlabel_pop[i] = new MyImageMenuItem (M(Glib::ustring::compose("%1%2", "FILEBROWSER_POPUPCOLORLABEL", i)), i == 0 ? "circle-empty-gray.png" : Glib::ustring::compose("%1%2%3", "clabel", i, ".png"))), 0, 1, c, c + 1);
```

For reference, old values vs new:
`clabel0` = `circle-empty-gray`
`clabel1` = `circle-red`
`clabel2` = `circle-yellow`
`clabel3` = `circle-green`
`clabel4` = `circle-blue`
`clabel5` = `circle-purple`

There will most likely not be any c**g**label* icons, as the faded shades can be more efficiently done using CSS.

**Comment by Beep6581** [comment]
After much work, the icon cleanup is complete.

Changes:
1. All unused icons deleted.
2. In fact, all icons deleted. All icons redrawn in SVG using Inkscape-0.92.2. Please do not edit or create SVG files using any version lower than 0.92.2.
3. New script to make generating PNG icons easy:
    ```
    ./tools/generatePngIcons foo*.svg
    ```
    The script automatically compresses icons using [pngquant](https://pngquant.org/) while generating them if pngquant is installed. As a result and as an example, all "dark" theme icons combined now take just 109kB.
4. Currently we ship two themes - "light" and "dark". Adding new icon themes is now easy - it's a matter of adding a name and a color to the script, and including the new icon folder in `rtdata/CMakeLists.txt`.
5. Standardization:
    1. Sizes:
        1. Normal: 24x24px.
        2. Small: 16x16px.
        3. Toggle-narrow: 10x24px.
    2. Style - no effects, no blur. Lines 2px wide or more, depending on needs. Opacity 70%, and 90% for verb/subject elements, e.g. in a "zoom-to-crop" icon the crop part, or in a "folder-open" icon the open side, can both have an opacity 90% to make them stand out a bit more.
    3. Colors - `#2a7fff` gets replaced by the theme's color. All other colors are preserved. 
    4. Naming - all icon names lowercase, elements and hierarchies separated by a hyphen, e.g. `folder-open`, `folder-closed`, or `device-floppy`, `device-hdd`.
6. Icons are now generated at two sizes: their normal size, and double-size for HiDPI support #3547 
7. Some icons were completely redesigned, e.g. the new rendering intent icons now convey info regarding what happens to the color gamut and to the white point, the new undo-all icon is now based on the undo icon.
8. There were previously many duplicate icons because they were named after what they do, not after what they are. Icon names now reflect what the icons show, not what we want them to do. It's not always possible, but mostly. That makes it easier to find a given icon, and makes it possible to re-use it for a different purpose without renaming or duplicating files. For example the red-circle icon used to give a photo a red color-label is now called "circle-red", and can be re-used for the channel-mixer's red slider.

Since our themes were based on icons of various styles, shapes and sizes, things like padding may need to be tweaked for the new icons.

**Comment by Beep6581** [comment]
This is in branch [iconcleanup4](https://github.com/Beep6581/RawTherapee/tree/iconcleanup4)

**Comment by gaaned92** [comment]
In my local repo I dont have the rtdata/icons dir

**Comment by Beep6581** [comment]
@gaaned92 correct, I deleted it. Is there a compilation problem? If so, please verify that you're using branch `iconcleanup4`, that you're on commit 4340ece and that you have started with an empty build folder.

**Comment by gaaned92** [comment]
Sorry,I forgot to indicate that it crashes Windowsinnosetup Line 52

**Comment by Beep6581** [comment]
@gaaned92 thanks for testing, I will fix it tomorrow.

**Comment by Beep6581** [comment]
@gaaned92 should be fixed now.

**Comment by TooWaBoo** [comment]
The Hand tool cursor (when dragging the image) is hard to see. It looks like it uses the same icon like the button.
It would be better to use an icon like this: ![closedhand](https://user-images.githubusercontent.com/13800920/42723809-47188642-8766-11e8-964b-e5bc12ad6792.png)

**Comment by Beep6581** [comment]
I have a 1920x1080 13.3" 166PPI screen, and on it the new theme looks good size-wise. @TooWaBoo [suggested](https://github.com/Beep6581/RawTherapee/pull/4684#issuecomment-404990722) making the toolbox icons smaller, i.e. changing from 24px to 16px. Which icons exactly are you referring to? It will take a few hours to do that, so I would like to get some more opinions before commencing.

**Comment by TooWaBoo** [comment]
![unbenannt](https://user-images.githubusercontent.com/13800920/42726728-6ea8d2d8-8799-11e8-9c4d-2e99b520fdc8.png)
![unbenannt3](https://user-images.githubusercontent.com/13800920/42726729-722c926e-8799-11e8-9679-5278c7e03ff3.png)
![unbenannt8](https://user-images.githubusercontent.com/13800920/42726731-770259e0-8799-11e8-8fae-a8116f7e8e80.png)
![unbenannt4](https://user-images.githubusercontent.com/13800920/42726735-7eb89410-8799-11e8-95dd-d16c1e6ccca8.png)
![unbenannt12](https://user-images.githubusercontent.com/13800920/42726738-9a4b542e-8799-11e8-8fa0-d6930a57710f.PNG)

![unbenannt9](https://user-images.githubusercontent.com/13800920/42726875-445d4308-879c-11e8-8e6c-527f9bcb0d8c.png)
![unbenannt10](https://user-images.githubusercontent.com/13800920/42726877-4aa8e690-879c-11e8-9d47-91d726903c70.png)

The size 16px of the circles is OK but they look to heavy. I suggest to use a size of 12px for the visible part of the image.
![unbenannt2](https://user-images.githubusercontent.com/13800920/42726921-1d5ff344-879d-11e8-8f94-44c401ab4576.png)
![unbenannt5](https://user-images.githubusercontent.com/13800920/42726923-1f5e17e8-879d-11e8-821a-6b4d2a787f76.png)
![unbenannt6](https://user-images.githubusercontent.com/13800920/42726924-20da3a52-879d-11e8-91c1-2329d3bbe6d5.png)
![unbenannt7](https://user-images.githubusercontent.com/13800920/42726926-2253b71e-879d-11e8-87f1-cad31717d807.png)
![unbenannt11](https://user-images.githubusercontent.com/13800920/42726927-26326c18-879d-11e8-8e68-3aa3179d140d.png)

**Comment by TooWaBoo** [comment]
Found the curser hand icon. It's "hand-closed.png" ![hand-closed](https://user-images.githubusercontent.com/13800920/42727366-a875bf10-87a5-11e8-9b38-2c83bdd42dd7.png) (see a couple posts above)

**Comment by TooWaBoo** [comment]
Here an example of a good looking layout in 96dpi.
![42728396-b72aeb84-87b9-11e8-9a07-ddf354da5dd2](https://user-images.githubusercontent.com/13800920/42728501-e4fa5be2-87bb-11e8-83ae-b3c2657d22b7.png)

**Comment by Beep6581** [comment]
The camera icon in dev is 22px high while in `iconcleanup4` its only 2 pixels higher, 24px:
![unbenannt4](https://user-images.githubusercontent.com/13800920/42726735-7eb89410-8799-11e8-95dd-d16c1e6ccca8.png)

The yellow exclamation mark icon is from GTK+ not from RT:
![unbenannt9](https://user-images.githubusercontent.com/13800920/42726875-445d4308-879c-11e8-8e6c-527f9bcb0d8c.png)

**Comment by TooWaBoo** [comment]
Contrast in bright themes too low.
old
![grafik](https://user-images.githubusercontent.com/13800920/42732992-0ea177d6-882b-11e8-99e6-ee141db0f6ef.png)
![grafik](https://user-images.githubusercontent.com/13800920/42734195-2f785e60-8840-11e8-969e-f72b08c8c618.png)

new
![grafik](https://user-images.githubusercontent.com/13800920/42732998-33441044-882b-11e8-9666-ded532ba970e.png)
![grafik](https://user-images.githubusercontent.com/13800920/42734208-4b1b50aa-8840-11e8-87a3-2f70275378a9.png)

**Comment by Beep6581** [comment]
These icons are for a dark theme.

**Comment by TooWaBoo** [comment]
This is from dev. All buttons and comboboxes have the same height. The image height of the curves is **18px**
![grafik](https://user-images.githubusercontent.com/13800920/42734238-eb50f066-8840-11e8-97d3-1bfefd4becf8.png)
The height of the white balance method icon is **22px**. It has the wrong height even in dev. That's why the combobox is to high also in dev.
![grafik](https://user-images.githubusercontent.com/13800920/42734347-8a2eaf2e-8842-11e8-989e-26013db7c967.png)

The toolbox in dev is a mix of different icon height (gave me a headache sometimes). Small Gtk-icons use a size of 16px. That's why I suggest to use 16px for Toolbox icons.

I'm also not happy with the new size of the big buttons. On 96dpi it's to much.
![grafik](https://user-images.githubusercontent.com/13800920/42734493-12e38c52-8845-11e8-91c4-a5ad5feabb2c.png)![grafik](https://user-images.githubusercontent.com/13800920/42734501-46d3153c-8845-11e8-8815-125015300b9d.png)

**Comment by Beep6581** [comment]
Screenshots of 3750b00272838d9aa532fccc069b2c7d2a98e53f:
![screenshot_20180715_154523](https://user-images.githubusercontent.com/5844619/42734567-98dbf1a4-8846-11e8-9b5f-c5487081289a.png)
![screenshot_20180715_154608](https://user-images.githubusercontent.com/5844619/42734568-98fc5f5c-8846-11e8-9f67-7e4eadf60d68.png)
![screenshot_20180715_154704](https://user-images.githubusercontent.com/5844619/42734569-991f3a5e-8846-11e8-9e9a-947e5627865f.png)

**Comment by Beep6581** [comment]
Update to come later this evening, after a visit to the lake.

**Comment by TooWaBoo** [comment]
dev
![dev1](https://user-images.githubusercontent.com/13800920/42734826-933c292c-884a-11e8-95ff-ef63cf0cf2cc.PNG)
![dev2](https://user-images.githubusercontent.com/13800920/42734828-9766b1b6-884a-11e8-859b-b52d82afef5c.PNG)

iconcleanup4 with modified TWB theme
![new1](https://user-images.githubusercontent.com/13800920/42734831-a5648108-884a-11e8-86f5-e830002eb6b5.PNG)
![neu2](https://user-images.githubusercontent.com/13800920/42734833-a99545f0-884a-11e8-90b7-ae098389ae13.PNG)

**Comment by Beep6581** [comment]
Changes in bb6282fa:
- The "light" icon theme is now a little lighter, to increase contrast.
- Toolbox icons are now small.
- Buttons:
  - Buttons without labels which use icons as their only source of info regarding what the button does (e.g. the white-balance pipette button) use normal-sized icons.
  - Labeled buttons which use icons as an auxiliary source of information (e.g. Auto-Crop) now use small icons. Curve type icons are also small even though they have no labels.
- Colored circles are smaller.
- Curve type icons redesigned and small.
- Hand icons (when panning the preview) redesigned to have a clear outline regardless of background color.
- Magnifier icons redesigned to have a thinner magnifier frame and larger inner parts.
- Perspective, distortion and crop icons redesigned.
- Some small icons were missing the `-small` suffix, now renamed.

Compare to https://github.com/Beep6581/RawTherapee/issues/4469#issuecomment-405093377

Screenshots of bb6282fa:
![screenshot_20180716_124408](https://user-images.githubusercontent.com/5844619/42754760-fe8d7de2-88f5-11e8-8e57-0bd2cb77af8f.png)
![screenshot_20180716_123837](https://user-images.githubusercontent.com/5844619/42754685-b104fda2-88f5-11e8-8de4-1c164c04ce09.png)
![screenshot_20180716_123926](https://user-images.githubusercontent.com/5844619/42754686-b12a424c-88f5-11e8-8241-7aceb6b82bd8.png)

**Comment by Beep6581** [comment]
Diskette/save icons updated in 00022a01

Unsaved/saved:
![imgur-2018_07_16-17 49 12](https://user-images.githubusercontent.com/5844619/42768839-d19f0208-8920-11e8-8c40-08fc0304be73.png)

Save:
![screenshot_20180716_174942](https://user-images.githubusercontent.com/5844619/42768840-d1c8310a-8920-11e8-9b75-785f3b1ac71d.png)

**Comment by TooWaBoo** [comment]
@Beep6581 
Looks good now except the size of the WB button and combobox. I prefer the smaller icons.
![unbenannt](https://user-images.githubusercontent.com/13800920/42772909-132eb424-892c-11e8-9251-373b4e8ca49b.PNG)![42772915-1632d4f2-892c-11e8-9947-0542e3146fd9](https://user-images.githubusercontent.com/13800920/42774748-d2de409a-8932-11e8-86ea-9e83609acf44.PNG)

I've also modified the RT-theme to make the height of buttons and comboboxes identical.
![unbenannt3](https://user-images.githubusercontent.com/13800920/42773030-5f9243da-892c-11e8-8187-b295f66cf765.PNG)
You'll find the changes at line 39 and 955.
[RawTherapeeMod-GTK3-20_.css.txt](https://github.com/Beep6581/RawTherapee/files/2198677/RawTherapeeMod-GTK3-20_.css.txt)

**Comment by TooWaBoo** [comment]
The "hand-closed.png" ![hand-closed](https://user-images.githubusercontent.com/13800920/42774149-4cd793b2-8931-11e8-8b3c-1d49981b9e19.png) is not a button icon. It's a cursor like "crosshair.png" ![crosshair](https://user-images.githubusercontent.com/13800920/42774095-29f3bee8-8931-11e8-9c83-02407cc576fa.png) and should look e.g. like this ![closedhand](https://user-images.githubusercontent.com/13800920/42774165-55d71a14-8931-11e8-881a-b551f47b24f6.png)
Drag an image and you know what I mean.

**Comment by Beep6581** [comment]
The trash icons were never representative of what they did or showed (show empty trash vs show full trash vs delete this vs empty trash, etc.). Commit 75d1ed02 fixes that.

**Comment by Beep6581** [comment]
@TooWaBoo `hand-closed` changed to cursor style in commit 591d3aa6.

**Comment by TooWaBoo** [comment]
EXIF: button icon missing.
![grafik](https://user-images.githubusercontent.com/13800920/42778028-12ab56f0-893c-11e8-96eb-1f78ea7ff053.png)

**Comment by TooWaBoo** [comment]
CD-ROM icon missing.
![grafik](https://user-images.githubusercontent.com/13800920/42781884-a2b056dc-8947-11e8-8b76-1412780df85e.png)

**Comment by Beep6581** [comment]
Thanks. The tick which shows that the image was edited was also missing. Both are fixed in the latest commit. I also made the ticks theme-colored since there was no reason to have them green and distracting.

**Comment by Beep6581** [comment]
I will be merging tomorrow.

**Comment by Beep6581** [comment]
Branch merged into `dev`.

**Comment by Beep6581** [comment]
@Desmis @heckflosse @Hombre57 @agriggio @Floessie don't hesitate to let me know if you need help with merging `dev` into any of your branches!

**Comment by Floessie** [comment]
Thanks for the hard and time-consuming work you put into this! :+1:

**Comment by Desmis** [comment]
All these new icons are definitely better than old :)
Very good job 
jacques

**Comment by Beep6581** [comment]
I'm happy to hear that you like them!

**Comment by Hombre57** [comment]
@Beep6581 They are nice, thanks for this hard work !

However could you change the rating stars that are displayed in thumbnails please ? The yellow ones are ok, but the grey ones are too big and too distracting IMHO. So I'd make them half the size (but keep the same canvas size), without borders and lighter (more transparent ?). That way, the number of stars will even more pop out, not only by the color.

e.g. with [star-small.svg.txt](https://github.com/Beep6581/RawTherapee/files/2216190/star-small.svg.txt) (well, you get the idea)

![stars](https://user-images.githubusercontent.com/13788115/43036156-01dd54a4-8cfc-11e8-8dc6-b97eca2ce607.png)

There's also 2 problems in `tools/generatePngIcons` :

   1. on line 91, the `inkscape` install folder is completely lowercase by default in the last version. Could you add a path detection for Windows system to solve this letter case issue ?
   2. on line 23, this test is valid for Linux only and prevent generating on Windows/MSYS. You could check for the Windows' inkscape path here.

I've removed the test from l. 23 and changed the letter case from point 1, and it worked well.

**Comment by Beep6581** [comment]
@Hombre57 I agree that it looks better when the not-rated icons are less focus-grabbing, will do something about that.

> the inkscape install folder is completely lowercase by default in the last version

Is "last version" = 0.92.3? And which Windows?

I could blindly fix it, but now is a good opportunity to refresh my info. As I don't use Windows or MSYS2, could you please check:
1. If you install Inkscape-0.92.3, is it available in `$PATH` in MSYS2?
2. What happens when you type `inkscape` in an MSYS2 console?
3. What is the default installation folder for `Inkscape-0.92.3` in Windows >=7?
4. What is the name of the executable?

**Comment by Hombre57** [comment]
@Beep6581 Forget about point 1 above, I personally created the lowercase `inkscape` folder when installing with the zip archive. When installing with the installer, it creates an `Inkscape` folder.

To answer your questions :

   1. no
   2. _command not found_
   3. `/c/Program Files/Inkscape` for 64 bits version (which is already correct in your script), `/c/Program Files (x86)/Inkscape` for 32 bits version
   4. `inkscape.exe`

**Comment by Beep6581** [comment]
@Hombre57 script updated, could you please test?

**Comment by Hombre57** [comment]
@Beep6581 Works nice, thanks !

**Comment by agriggio** [comment]
Sorry for the late reply. Thanks *a lot* for this, the new icons are really nice, a great improvement! :+1:

**Comment by ghost** [comment]
@Beep6581 Sorry if I cannot remember this moment, are these icons currently in use?

_I even mean, are these icons the only one in use in the GUI?_
