### ISSUE TITLE
Fix bad pixels if DNG opcode FixBadPixelsConstant == 0

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#4471]
In dcraw code there is already a `zero_is_bad` flag, which, if set to 1 (true), means all raw pixels with value 0 are treated as bad pixels.
For Leica and Panasonic cameras this flag is hardcoded in dcraw code to 1 (true). For all other cameras it's always 0 (false).

Here's a patch, which checks the above mentioned DNG opcode and sets `zero_is_bad` if FixBadPixelsConstant == 0. For tests you can use the files from [here](https://discuss.pixls.us/t/play-raw-first-foss-processing/7078)

```diff
diff --git a/rtengine/dcraw.cc b/rtengine/dcraw.cc
index 7d82b68a..1d9f49f6 100644
--- a/rtengine/dcraw.cc
+++ b/rtengine/dcraw.cc
@@ -6386,6 +6386,25 @@ guess_cfa_pc:
 	  ((int *)mask)[i] = getint(type);
 	black = 0;
 	break;
+      case 51008:           /* OpcodeList1 */
+        {
+            unsigned oldOrder = order;
+            order = 0x4d4d; // always big endian per definition in https://www.adobe.com/content/dam/acom/en/products/photoshop/pdfs/dng_spec_1.4.0.0.pdf chapter 7
+            unsigned ntags = get4(); // read the number of opcodes
+            while (ntags--) {
+              unsigned opcode = get4();
+              fseek (ifp, 8, SEEK_CUR); // skip 8 bytes as they don't interest us currently
+              if (opcode == 4) { // FixBadPixelsConstant
+                fseek (ifp, 4, SEEK_CUR); // skip 4 bytes as we know that the opcode 4 takes 4 byte
+                if(get4() == 0) { // if raw 0 values should be treated as bad pixels, set zero_is_bad to true (1). That's the only value currently supported by rt
+                    zero_is_bad = 1;
+                }
+              } else {
+                fseek (ifp, get4(), SEEK_CUR);
+              }
+            }
+            order = oldOrder;
+          break;
+        }
       case 51009:			/* OpcodeList2 */
 	meta_offset = ftell(ifp);
 	break;
diff --git a/rtengine/rawimagesource.cc b/rtengine/rawimagesource.cc
index 081ac366..83b7769f 100644
--- a/rtengine/rawimagesource.cc
+++ b/rtengine/rawimagesource.cc
@@ -1750,7 +1750,8 @@ void RawImageSource::preprocess  (const RAWParams &raw, const LensProfParams &le
 
     int totBP = 0; // Hold count of bad pixels to correct
 
-    if(ri->zeroIsBad()) { // mark all pixels with value zero as bad, has to be called before FF and DF. dcraw sets this flag only for some cameras (mainly Panasonic and Leica)
+    if(ri->zeroIsBad()) { // mark all pixels with value zero as bad, has to be called before FF and DF. 
+                          // dcraw sets this flag only for some cameras (mainly Panasonic and Leica) and when DNG opcode FixBadPixelsConstant == 0
         bitmapBads = new PixelsMap(W, H);
 #ifdef _OPENMP
         #pragma omp parallel for reduction(+:totBP) schedule(dynamic,16)

```

**Comment by Beep6581** [comment]
Tested using the Canon PowerShot A3100 IS raw, the patch works beautifully.
Since this feature is hard-coded, is it still possible to view the dead pixels in RT, i.e. to see the "real raw data"?

**Comment by heckflosse** [comment]
> Since this feature is hard-coded, is it still possible to view the dead pixels in RT, i.e. to see the "real raw data"?

No, it works the same as for Leica and Panasonic cameras, where you also can't view the "real raw data" currently.

**Comment by heckflosse** [comment]
@Beep6581 and other devs: Any objection to commit this fix?

**Comment by heckflosse** [comment]
@Beep6581 About the "real raw data" in case of bad pixels for files which which this patch is for, it's just zero!

**Comment by Beep6581** [comment]
@heckflosse +1 for commit.

Being able to show the "real raw data" is one of RawTherapee's "selling points". We may want to consider adding a "Fix bad pixels while demosaicing" checkbox in the Raw tab at some point.

**Comment by iliasg** [comment]
I cannot remember exactly now .. but I think there is a Canon model (600D CR2 ??) which also needs this zeroisbad pass ..

**Comment by heckflosse** [comment]
@iliasg I checked three Canon 600D files. None of them showed black bad pixels

**Comment by iliasg** [comment]
Ingo I found it .. it's 650D and there are around 2500 bad pixels at each channel which have value = 1
Well .. normally the dead pixel algo will catch them ..

EDIT .. forget it .. I was wrong again .. the bad pixels of 650d are at the unused top optically black area ..
The problematic model is around there (600-700) but I cannot find which now .. Sorry for the noise :(
