### ISSUE TITLE
Request: HTTPS for Website

### ISSUE THREAD

**Issue by Echolon** [Beep6581/RawTherapee#4473]
Hi,

just would like to recommend to HTTPS encrypt the website.

Without any costs: https://letsencrypt.org/

Kind regards

**Comment by Beep6581** [comment]
Noted.

**Comment by Echolon** [comment]
Hi,

I know it's picky but as far as I recognised you closed this issue without switching on HTTPS :cry: 

Cheers

Edit: https://blog.github.com/2018-05-01-github-pages-custom-domains-https/
