### ISSUE TITLE
Instant preview switch between images

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4476]
In the past, when switching from one raw file to another raw file from the same camera, the preview would stay on the first image until the second image was done loading, then it would instantly switch. This was very useful for comparing subtle changes between the images. Then, at some point probably during the 5.3-dev days, this behavior was lost. Now, when I switch from one raw file to another, the preview is cleared as soon as the raw file is decoded, and it stays cleared until the preview pipeline is done with everything.

Using neutral, the preview stays cleared for about 2 seconds on my machine, and using a real PP3 with more tools takes longer.

Could the old behavior be restored? i.e. only update the preview once the new one is ready.

**Comment by Floessie** [comment]
Fixed in #4523.

**Comment by Beep6581** [comment]
Thank you!
