### ISSUE TITLE
Core dump RL convolution followed by Contrast+

### ISSUE THREAD

**Issue by ClaesGitHub** [Beep6581/RawTherapee#4481]
In RT's file browser:
1. Select image (either RAF or TIFF)
2. Apply Neutral
3. Open

Now in RT's Editor:
4. Zoom to 100%
5. Detail tab

6. Activate Sharpening ->  RL Deconvolution
7. Set Damping to 0

8. Activate Contrast by Detail levels
9. Contrast+

This results in SIGSEGV. See debug dump below.

[AboutThisBuild.txt](https://github.com/Beep6581/RawTherapee/files/1868041/AboutThisBuild.txt)
[log.txt](https://github.com/Beep6581/RawTherapee/files/1868039/log.txt)

Just tell me if you need additional information.

Sincerely,
Claes in Lund, Sweden

**Comment by Beep6581** [comment]
Reproduced. I had to click Contrast+ several times, then it crashed.
Using http://rawtherapee.com/shared/test_images/colortarget/FUJIFILM%20X-T1%20daylight.raf

**Comment by Beep6581** [comment]
Reproduced also using `amsterdam.pef`, same procedure.

**Comment by heckflosse** [comment]
Reproducible in dev, but not in pixelshift_fixes, which is 26 commits behind dev.
This at least reduces the number of bisect steps ;-)

**Comment by heckflosse** [comment]
Bisected to https://github.com/Beep6581/RawTherapee/commit/b42a45b4817ca838d0d8490638da9f94f35d9b71

ping @agriggio

**Comment by agriggio** [comment]
I'll look into this once I'm done with #4479 
But please feel free to work on it :-)

**Comment by ClaesGitHub** [comment]
ping @agriggio 

CIao Alberto,

I have a hunch that it is the
_Set Damping to 0_
that is the culprit here, i.e. if
Damping > 0, there is no problem (?).

Cordiali Saluti,
Claes a Lund, Svezia

**Comment by heckflosse** [comment]
@ClaesGitHub Setting the damping to != 0 avoids the crash because it implicitely avoids negative Lab L values before the next processing step. Bisecting clearly shows the responsible commit and RL deconvolution code was not changed with this commit afaik.

**Comment by agriggio** [comment]
yes sorry, it's a side effect of unbounded processing. I knew it would happen sooner rather than later :-)

**Comment by agriggio** [comment]
@ClaesGitHub can you try again with the latest dev? I pushed some changes that might have made this go away -- I just tried and was unable to reproduce

**Comment by ClaesGitHub** [comment]
@agriggio 
Ciao! 
Thank you. I have just checked the latest dev and I can _not_ reproduce the error.
/Claes

**Comment by heckflosse** [comment]
@agriggio Fix confirmed :+1:
