### ISSUE TITLE
Colour-target shots from Sony A7iii

### ISSUE THREAD

**Issue by harshula** [Beep6581/RawTherapee#4482]
The following files:
sony-a7m3-daylight-DSC00117.ARW
sony-a7m3-tungsten-DSC00169.ARW

are uploaded to:
https://filebin.net/srwsy7h7170maiv9

They are licensed under CC0 license (https://creativecommons.org/about/cc0)

tungsten: 75 watt light bulb ~2.4m distance from the colour chart

**Comment by Beep6581** [comment]
Thanks @harshula, the shots look good, but we need to wait for Adobe DNG Converter to support this format first.

**Comment by agriggio** [comment]
FYI, a new version of the DNG converter is out, with A7III support:
https://supportdownloads.adobe.com/detail.jsp?ftpID=6321
