### ISSUE TITLE
Dynamic Processing Profile does not apply

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4484]
Hello

I am new to the Dynamic Processing Profile feature and in order to update the documentation I gave it a try. I wanted to see whether the camera name is case-sensitive, so I created two rules, one for "Pentax K10D" and one for "PENTAX K10D", each applies a different bundled profile. When I right-click on the `amsterdam.pef`'s thumb and select "Processing profile operations > Reset to default", neither of these profiles gets applied.

What am I doing wrong?

http://rawtherapee.com/shared/test_images/amsterdam.pef

```text
[rule 1]
iso_min=0
iso_max=512000
fnumber_min=0
fnumber_max=100
focallen_min=0
focallen_max=10000
shutterspeed_min=0
shutterspeed_max=1000
expcomp_min=-20
expcomp_max=20
camera_enabled=true
camera_value=Pentax K10D
lens_enabled=false
lens_value=
profilepath=${G}/Pop/Pop 4 BW

[rule 2]
iso_min=0
iso_max=512000
fnumber_min=0
fnumber_max=100
focallen_min=0
focallen_max=10000
shutterspeed_min=0
shutterspeed_max=1000
expcomp_min=-20
expcomp_max=20
camera_enabled=true
camera_value=PENTAX K10D
lens_enabled=false
lens_value=
profilepath=${G}/Faded/Faded Purple 2 TM
```

**Comment by agriggio** [comment]
Do you have "(Dynamic)" set as the default profile for raw files?
BTW, the matching is case insensitive

**Comment by Beep6581** [comment]
@agriggio I missed that, thank you.
