### ISSUE TITLE
Lens data in Exif shows incorrect information for manual focus Nikon lenses

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#4485]
When using MF AI/AIS lenses on some Nikon cameras one can dial in the lens data.
While this lens data is shown correctly in info dialog, it's incorrect in Exif Lensdata:

![grafik](https://user-images.githubusercontent.com/13733487/38312736-c80a5ade-3822-11e8-896e-cf83595fb820.png)

**Comment by Beep6581** [comment]
Fantastic pharmacy sliding door artwork idea!
