### ISSUE TITLE
__SSE2__ blocks

### ISSUE THREAD

**Issue by kznsq** [Beep6581/RawTherapee#4486]
Hi!
Why there is a code like this (CA_correction_RT.cc line 387):
```
#ifdef __SSE2__
                            for(; col < min(cc1 + left - 3, width) - 7; col+=8, indx+=8) {
                                STVFU(Gtmp[(row * width + col) >> 1], LC2VFU(rgb[1][indx]));
                            }
#endif
                            for(; col < min(cc1 + left - 3, width); col+=2, indx+=2) {
                                Gtmp[(row * width + col) >> 1] = rgb[1][indx];
                           }
```
If we have defined __SSE2__ when it will execute twice (SIMD and plain C code)?

**Comment by heckflosse** [comment]
@kznsq You missed the fact that col is initialized outside. If SSE2 is defined, the non SSE2 part will process only the remaining pixels

**Comment by kznsq** [comment]
@heckflosse Thanks, now it is clear :)

**Comment by heckflosse** [comment]
@kznsq btw: you are not the first one who was confused by this. But I really like this pattern because it simplifies writing and reading the code (the non SIMD part is just a few lines away for better readability).
