### ISSUE TITLE
Add Canon G7X Mark II (Sample Photos)

### ISSUE THREAD

**Issue by zmnpl** [Beep6581/RawTherapee#4490]
Hi,

I recognized that my G7X Mark II is not yet included so I tried to follow [these instructions](https://rawpedia.rawtherapee.com/Adding_Support_for_New_Raw_Formats) to provide you guys with the shots you need to add it.
This is the filebin link: https://filebin.net/4si5zra3ho3i77c8/g7xmarkii.zip

If you need anything more, I'm happy to help.

Best regards
Simon

**Comment by Thanatomanic** [comment]
The raw can be decoded properly and the distortion can be corrected by using the `Automatic` button in the `Distortion Correction` module. See [here](https://discuss.pixls.us/t/canon-g7x-mk-ii-built-in-lens-profile-rawtherapee/2956).
