### ISSUE TITLE
RT 5.4 segfault with HDR dng file.

### ISSUE THREAD

**Issue by dnw3039** [Beep6581/RawTherapee#4493]
I am getting a segfault using some older HDR.dng files.
To replicate open attached  .dng file click "Auto-Match Tone curve" click Auto-Levels - segfault.

gdb trace produces -
```
Thread 1300 "rawtherapee" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffc5ffb700 (LWP 17692)]
0x00005555559c1213 in rtengine::Color::XYZ2Lab(float, float, float, float&, float&, float&) ()
(gdb) 

```

[_1DW1254-1256.dng.zip](https://github.com/Beep6581/RawTherapee/files/1886031/_1DW1254-1256.dng.zip)

Version: 5.4-141-g426380e8d
Branch: dev
Commit: 426380e8d
Commit date: 2018-04-04
Compiler: cc 7.2.0
Processor: core2
System: Linux
Bit depth: 64 bits
Gtkmm: V3.22.2
Lensfun: V0.3.2.0
Build type: release
Build flags: -std=c++11 -Wno-deprecated-declarations -Wno-unused-result -std=c++11 -march=core2 -Werror=unused-label -flto -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -O3 -DNDEBUG -ftree-vectorize
Link flags:  -march=core2 -flto
OpenMP support: ON
MMAP support: ON

**Comment by heckflosse** [comment]
Works fine here on Win7/64

**Comment by Benitoite** [comment]
And no crash on macOS... maybe you have an associated `.pp3`?

**Comment by dnw3039** [comment]
Sorry no .pp3 it crashes before creating the .pp3 file.

**Comment by dnw3039** [comment]
I will compile a debug version and try again for a better error trace.

**Comment by dnw3039** [comment]
I compiled a debug version and a release version of the current dev branch and their was no problem with the HDR files. So it looks like a a transitory problem with either commit 426380e or my system.
