### ISSUE TITLE
When opening an image after starting RT, wavelet tool always is expanded

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#4494]
To reproduce:

1) Start RT
2) Open an image
3) Go to Advanced tab
4) Collapse Wavelet Levels
5) Open preferences dialog
6) Click the button 'Save tools collpased/expanded state now'.
7) Close RT
8) Start RT
9) Open an image
10) Go to Advanced tab

=> Wavelet tool is expanded though it should be collapsed

Fixed with this patch

```diff
diff --git a/rtgui/toolpanelcoord.cc b/rtgui/toolpanelcoord.cc
index de8e2891..2899625f 100644
--- a/rtgui/toolpanelcoord.cc
+++ b/rtgui/toolpanelcoord.cc
@@ -578,7 +578,6 @@ void ToolPanelCoordinator::updateToolState()
         }
 
         wavelet->updateToolState (temp);
-        wavelet->setExpanded (true);
         retinex->updateToolState (temp);
     }
 }

```

**Comment by Beep6581** [comment]
I requested that the Wavelet tool be automatically expanded (only the main tool, not the sub-tools) back when it was in its own tab. The reason was so that you can instantly see whether any sub-tools are enabled without having to expand it every time.

**Comment by heckflosse** [comment]
@Beep6581 

> back when it was in its own tab.

Now, that's not in it's own tab anymore, do you agree with my fix (to be consistent with other tools)?

**Comment by Beep6581** [comment]
@heckflosse yes.
