### ISSUE TITLE
Processing Profiles dropdown unnecessarily scrolls

### ISSUE THREAD

**Issue by tribut** [Beep6581/RawTherapee#4495]
When I open the Processing Profiles dropdown menu, the initial state is "scrolled down" for some reason like this:

![screenshot from 2018-04-08 14-40-45](https://user-images.githubusercontent.com/719105/38467589-4079a3b0-3b3b-11e8-9ffe-37641392ebe4.png)

I need to hover above the "up" arrow for a short while before I can use the menu:

![screenshot from 2018-04-08 14-44-42](https://user-images.githubusercontent.com/719105/38467611-ab7343d8-3b3b-11e8-84c0-77ec4061dd00.png)

I'm currently on Ubuntu 17.10 using the AppImage (`RawTherapee-git-5.4-20180322_1639.glibc2.17-x86_64.AppImage`), but I've had this problem with the distribution package (version `5.2-1` from universe) as well.

**Comment by heckflosse** [comment]
Works fine here, but I have a similar issue when selecting a Lens in `Profiled Lens Correction`.

![grafik](https://user-images.githubusercontent.com/13733487/38467878-75db03f2-3b3e-11e8-83d0-0c332956b5e9.png)

**Comment by Beep6581** [comment]
FWIW, I read about something similar in a discussion in a GTK+ bug report, and the GTK+ devs wrote that such behavior was by design.

**Comment by tribut** [comment]
Starting on the currently active item maybe - but surely not starting with an empty(!) list as in the first screenshot which one has to scroll up from?
But if that is indeed the case, maybe RawTherapee should use a different type of widget here. It is quite annoying to use.

**Comment by Floessie** [comment]
@Beep6581 
> FWIW, I read about something similar in a discussion in a GTK+ bug report, and the GTK+ devs wrote that such behavior was by design.

For anyone interested, it's [bug 129463](https://bugzilla.gnome.org/show_bug.cgi?id=129463).

**Comment by tribut** [comment]
Thanks for the link. It seems that the behavior is indeed expected. The cursor is supposed to point to "(Custom)" when the button is clicked. But because that is the last item and I work with RawTherapee maximized, the menu is shown expanded downwards with no item actually visible.

Sorry for the noise, closing as upstream bug. I'll go upvote #3043 now :grin:
