### ISSUE TITLE
Linear DNG (demosaiced) image white-points too bright

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4496]
-- edit: skip to https://github.com/Beep6581/RawTherapee/issues/4496#issuecomment-379892123 for the cause of the problem.

This applies to FUJIFILM X100S converted to DNG. Specifically, tested using Adobe DNG Converter 10.3 and converted to linear DNG. The DCP's look table is completely broken when applied to the DNG, but works fine for the RAF.

http://rawtherapee.com/shared/test_images/colortarget/FUJIFILM%20X100S%20daylight.raf
http://rawtherapee.com/shared/test_images/colortarget/FUJIFILM%20X100S%20tungsten.raf 
https://filebin.net/5ziqv0lctubpe5dy/FUJIFILM_X100S_daylight.dng
https://filebin.net/5ziqv0lctubpe5dy/FUJIFILM_X100S_tungsten.dng
https://filebin.net/5ziqv0lctubpe5dy/FUJIFILM_X100S.dcp

So far I also tested the FUJIFILM FinePix F600EXR linear DNG vs RAF and there was no problem there.

**Comment by Beep6581** [comment]
The colors are also very broken when using the matrix.

![screenshot_20180409_220618](https://user-images.githubusercontent.com/5844619/38520254-8ee56f86-3c42-11e8-82e2-ef6cef10f38c.png)
![screenshot_20180409_220714](https://user-images.githubusercontent.com/5844619/38520260-94697a2e-3c42-11e8-861e-25523c4f34cc.png)

**Comment by Beep6581** [comment]
For reference, the same shot but in RAF format, DCP on the left and matrix on the right.
![screenshot_20180409_221148](https://user-images.githubusercontent.com/5844619/38520409-04dfbab6-3c43-11e8-811e-0787e0b45c3c.png)

**Comment by Beep6581** [comment]
The same issue with FUJIFILM X100T.

**Comment by Beep6581** [comment]
Same with FUJIFILM X-Pro2.

**Comment by Beep6581** [comment]
Same with FUJIFILM X-T1.

**Comment by heckflosse** [comment]
Could be related to #4129

**Comment by Beep6581** [comment]
I was off on the wrong track.

The color issues were caused by curve auto-matching failing:
![screenshot_20180409_225412](https://user-images.githubusercontent.com/5844619/38522447-eeae0e40-3c48-11e8-8675-97c348cc7d9c.png)

I guess the curve matching failed because of the difference in bit depth between the "linear DNG" and RAF files - the linear DNGs load overexposed.

If I apply the "Standard Film Curve - ISO Low" procesing profile and set the white-point correction to 0.25, the image looks correct:
![screenshot_20180409_225850](https://user-images.githubusercontent.com/5844619/38522671-94565cee-3c49-11e8-84bf-8eb012580d73.png)

**Comment by Beep6581** [comment]
The same happens with "linear DNG" (i.e. demosaiced) DNGs from all other makes I tried - Canon and Nikon. They all open too bright, and need white-point correction 0.25 to match the real raws.

Neutral applied to all:
![imgur-2018_04_09-23 13 29](https://user-images.githubusercontent.com/5844619/38523405-a84c7632-3c4b-11e8-95d6-a2099a0c79ac.png)

**Comment by agriggio** [comment]
so, do I understand correctly that the failure in curve matching is caused by the wrong white point, and so the title of the issue is still right?

**Comment by Beep6581** [comment]
I can only guess as to that being the cause of the curve fail, but what is clear is that linear DNGs use the wrong white level in RT, i.e. this issue is a not-solved duplicate of #4129.

**Comment by agriggio** [comment]
I think more related is #4472 
Did you try this patch? https://github.com/Beep6581/RawTherapee/issues/4472#issuecomment-376566111

**Comment by Beep6581** [comment]
I will try it this evening.
