### ISSUE TITLE
Suggestion: Colouring of overexposed areas

### ISSUE THREAD

**Issue by morosakubek** [Beep6581/RawTherapee#4497]
Dear programmers, maybe an interesting option and I think that many people would like to be able to colorize (single color, or best gradient) overexposed areas (out-of-gamut).

cheers,

**Comment by agriggio** [comment]
you mean like this?
![clipping](https://user-images.githubusercontent.com/11982086/38545190-c7c634ea-3ca9-11e8-9c0c-83faf3b0a46e.jpeg)

**Comment by morosakubek** [comment]
No, in output. I mean that if I have an overexposed sky and it is pink and blue, I would like the stain to have a colour of my choice. Or I have a bonfire and I would like the burnout to be yellow.

**Comment by morosakubek** [comment]
And to make it work only on the out-of-game parts, and not on all the highlights zones.

**Comment by agriggio** [comment]
@morosakubek this similar to what the "Colour propagation" highlight reconstruction mode does to some extent, if I correctly understand what you are describing.

IMHO, anything fancier than that is much better handled by GIMP and friends than RT...

**Comment by morosakubek** [comment]
@agriggio Yes, only with your own choice of color (not the one assumed by the algorithm).
