### ISSUE TITLE
Camera model alias matching support for DCPs

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4500]
In order to avoid having the same DCP file duplicated under several names, RT should have a file which maps the name of the DCP to all possible aliases a given camera make and model uses.

Only Canon, Minolta and Panasonic use aliases (ctrl+f for "aliases"):
http://rawspeed.org/CameraSupport.html#canon

Currently needed mappings:
https://github.com/Beep6581/RawTherapee/blob/dev/rtdata/dcpprofiles/camera_model_aliases.txt

**Comment by Floessie** [comment]
I already have a working implementation. Will branch and push tonight.

**Comment by Floessie** [comment]
Merged in #4502. Closing.
