### ISSUE TITLE
New "nightly" tag crashes WindowsInnosetup

### ISSUE THREAD

**Issue by gaaned92** [Beep6581/RawTherapee#4507]
The presence of a  "nightly" tag is incompatible with WindowsInnoSetup

```
Parsing [Setup] section, line 42
Error on line 42 in Y:\rtinstall\new-shadows-highlightsrelease64\WindowsInnoSetup.iss: Value of [Setup] section directive "VersionInfoVersion" is invalid.
Compile aborted.
```
For the branch new-shadows-highlights, in the generated windowsInnoSetup.iss we have
```
#define MyAppVersion "nightly-3-gc4567414"
#define MyAppVersionNumeric "nightly.3"
```

In line 42 we have
VersionInfoVersion={#MyAppVersionNumeric} which  crashes with incompatible "nightly.3" value

So could you delete the tag?

**Comment by Beep6581** [comment]
@gaaned92 there is nothing wrong with the tag `nightly`
https://git-scm.com/docs/git-check-ref-format

Sounds like this section needs to be updated to avoid this problem:
https://github.com/Beep6581/RawTherapee/blob/dev/UpdateInfo.cmake#L57

**Comment by gaaned92** [comment]
> there is nothing wrong with the tag nightly

I didn't wanted to say that. I was just surprised by the appearance of this tag without notice (at least known by me). 
Furthermore, I don't see what issue this new tag solve, at least for windows builds. Previously we knew from what stable release the dev or feature build was derived. This information is lost.


> Sounds like this section needs to be updated to avoid this problem:

more drastic:

```
diff --git a/tools/win/InnoSetup/WindowsInnoSetup.iss.in b/tools/win/InnoSetup/WindowsInnoSetup.iss.in
index 235d6496..6814d9c7 100644
--- a/tools/win/InnoSetup/WindowsInnoSetup.iss.in
+++ b/tools/win/InnoSetup/WindowsInnoSetup.iss.in
@@ -38,7 +38,7 @@
 AppId={#MyAppName}{#MyAppVersion}
 AppName={#MyAppName}
 AppVersion={#MyAppVersion}
-VersionInfoVersion={#MyAppVersionNumeric}
+;VersionInfoVersion={#MyAppVersionNumeric}
 AppPublisher={#MyAppPublisher}
 AppPublisherURL={#MyAppURL}
 AppSupportURL={#MyAppURL}
```

VersionInfoVersion is used to identify the file version of installer so not useful.
Numeric version could be suppressed from UpdateInfo.cmake if it is only used by WindowsInnoSetup.

**Comment by gaaned92** [comment]
https://github.com/Beep6581/RawTherapee/issues/4510

**Comment by Beep6581** [comment]
@gaaned92 I too don't yet understand why the tag is needed, but that's a separate issue. The question here is whether `VersionInfoVersion` is needed even if the `nightly` tag problem didn't exist.
http://www.jrsoftware.org/ishelp/index.php?topic=setup_versioninfoversion

It seems that `VersionInfoVersion` really is unnecessary, as you wrote.

Any objection to remove it @gaaned92 @sguyader @Hombre57 ?

**Comment by gaaned92** [comment]
@Beep6581 
I rechecked and  `VersionInfoVersion` appears only in the "properties" panel of exe installer:


 
![rtproperties](https://user-images.githubusercontent.com/13785581/38781045-ec68f776-40df-11e8-914e-4c5e784c5ac7.jpg)

See "version du fichier" (file version). I doubt if anybody ever looked at that!
So for me it'OK to do a commit to remove it from windowsInnoSetup and UpdateInfo.cmake

**Comment by gaaned92** [comment]
@aferrero2707 
Thanks for modification. Version is ok now.
As soon as @Beep6581 make a decision about VersionInfoVersion we can close this thread.

**Comment by Beep6581** [comment]
`AppVersion` is accurate, `VersionInfoVersion` is not - removed.
