### ISSUE TITLE
Tag "nightly" makes version in AboutThisBuild handicapped

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4509]
If you checkout `dev` and compile, you will get this in AboutThisBuild:
```
Version: nightly-4-gc3739694
Branch: dev
Commit: c3739694
Commit date: 2018-04-14
```

```
-- Git checkout information:
--      Commit description:     nightly-4-gc3739694
--      Branch:                 dev
--      Commit:                 c3739694
--      Commit date:            2018-04-14
--      Commits since tag:      4
--      Commits since branch:   4
--      Version (unreliable):   nightly.4
```

`dev` currently is at:
`5.4-205-g`c3739694

Commit f8c06863 was tagged `nightly`

`git describe --tags` shows:
`nightly-4-g`c3739694

`git describe` shows:
`5.4-205-g`c3739694

@aferrero2707 is the `nightly` tag really needed? I presume the tag will be moved to HEAD every day or every week - if so, what purpose does having a tag which moves about serve?
If it's needed, we must find a workaround for the problems it raises.

**Comment by Beep6581** [comment]
This patch has only been tested with the latest `dev` checked out. I can do more testing once answers to the questions above are known.

```diff
diff --git a/UpdateInfo.cmake b/UpdateInfo.cmake
index 8ffaf063..60eee8cc 100644
--- a/UpdateInfo.cmake
+++ b/UpdateInfo.cmake
@@ -25,7 +25,7 @@ if (REL_INFO_FILE STREQUAL REL_INFO_FILE-NOTFOUND)
     # Get version description.
     # Depending on whether you checked out a branch (dev) or a tag (release),
     # "git describe" will return "5.0-gtk2-2-g12345678" or "5.0-gtk2", respectively.
-    execute_process(COMMAND ${GIT_CMD} describe --tags --always OUTPUT_VARIABLE GIT_DESCRIBE OUTPUT_STRIP_TRAILING_WHITESPACE WORKING_DIRECTORY "${PROJECT_SOURCE_DIR}")
+    execute_process(COMMAND ${GIT_CMD} describe --always OUTPUT_VARIABLE GIT_DESCRIBE OUTPUT_STRIP_TRAILING_WHITESPACE WORKING_DIRECTORY "${PROJECT_SOURCE_DIR}")
 
     # Get branch name.
     # Will return empty if you checked out a commit or tag. Empty string handled later.
@@ -39,15 +39,12 @@ if (REL_INFO_FILE STREQUAL REL_INFO_FILE-NOTFOUND)
 
     # Get number of commits since tagging. This is what "GIT_DESCRIBE" uses.
     # Works when checking out branch, tag or commit.
-    # Get a list of all tags in repo:
-    execute_process(COMMAND ${GIT_CMD} tag --merged HEAD OUTPUT_VARIABLE GIT_TAG WORKING_DIRECTORY "${PROJECT_SOURCE_DIR}")
-    # Replace newlines with semicolons so that it can be split:
-    string(REPLACE "\n" ";" GIT_TAG_LIST "${GIT_TAG}")
-    execute_process(COMMAND ${GIT_CMD} rev-list --count HEAD --not ${GIT_TAG_LIST} OUTPUT_VARIABLE GIT_COMMITS_SINCE_TAG OUTPUT_STRIP_TRAILING_WHITESPACE WORKING_DIRECTORY "${PROJECT_SOURCE_DIR}")
+    execute_process(COMMAND ${GIT_CMD} describe --tags --exclude=nightly --abbrev=0 OUTPUT_VARIABLE GIT_LATEST_TAG OUTPUT_STRIP_TRAILING_WHITESPACE WORKING_DIRECTORY "${PROJECT_SOURCE_DIR}")
+    execute_process(COMMAND ${GIT_CMD} rev-list ${GIT_LATEST_TAG}..HEAD --count OUTPUT_VARIABLE GIT_COMMITS_SINCE_TAG OUTPUT_STRIP_TRAILING_WHITESPACE WORKING_DIRECTORY "${PROJECT_SOURCE_DIR}")
 
     # Get number of commits since branching.
     # Works when checking out branch, tag or commit.
-    execute_process(COMMAND ${GIT_CMD} rev-list --count HEAD --not --tags OUTPUT_VARIABLE GIT_COMMITS_SINCE_BRANCH OUTPUT_STRIP_TRAILING_WHITESPACE WORKING_DIRECTORY "${PROJECT_SOURCE_DIR}")
+    execute_process(COMMAND ${GIT_CMD} rev-list --count HEAD --exclude=nightly --not --tags OUTPUT_VARIABLE GIT_COMMITS_SINCE_BRANCH OUTPUT_STRIP_TRAILING_WHITESPACE WORKING_DIRECTORY "${PROJECT_SOURCE_DIR}")
 
     # If user checked-out something which is not a branch, use the description as branch name.
     if (GIT_BRANCH STREQUAL "")
```

```
-- Git checkout information:
--      Commit description:     5.4-205-gc3739694
--      Branch:                 dev
--      Commit:                 c3739694
--      Commit date:            2018-04-14
--      Commits since tag:      205
--      Commits since branch:   205
--      Version (unreliable):   5.4.205
```

**Comment by aferrero2707** [comment]
@Beep6581 a tag has to be given each time a new release is created... that was the main reason I had for keeping the "nightly" packages in a separate repository.

Anyhow, the "nightly" tag is created only once. When new package are pushed to the nightly release, the tag is not updated. Therefore it should be enough to give the current dev branch a new tag in order to have it shown again in the AboutThisBuild.txt

**Comment by Beep6581** [comment]
> a tag has to be given each time a new release is created

Is this for GitHub's purposes, or why? And how does that tie-in to the tag having to be created only once? A tag points to a commit - if it's not updated, it keeps pointing to the same old commit, so how does that help with the "nightly" concept?

**Comment by aferrero2707** [comment]
In fact, releases are normally used to distribute a specific version of the software, that gets "labelled" by the tag. By distributing in a single release some nightly binaries that evolve over time, we are "forcing" the concept of release, because in this case the tag does not make much sense (the binaries are even corresponding to more than one branch).

However, releases are the only practical way I'm aware of for distributing binary artefacts in the free version of github, hence I have nothing better to propose...

**Comment by gaaned92** [comment]
@aferrero2707 
`In fact, releases are normally used to distribute a specific version of the software, that gets "labelled" by the tag`

In my opinion, it is certainly true for "stable "releases but not for rolling releases (unstable releases, nightly builds as you want to name them)

An other solution adopted by the RT dev to distribute releases corresponding to different branches and different versions (rolling releases ),  is to give to each release a significant name including a composite tag
\<Branch\>_\<Commit description\>
For instance  `Rawtherapee_dev_5.4-205-gc3739694_WinVista`
With this convention, there is no ambiguity and no need to tag each time an unstable release is produced.

**Comment by Beep6581** [comment]
@aferrero2707 I still don't understand why the need to make a `nightly` tag in the `dev` branch, if that tag points to some arbitrary commit (specifically, commit f8c06863), and never changes. Could you explain that please? Where does this requirement come from?

**Comment by Beep6581** [comment]
One way of avoiding this problem entirely is to make the tag point to a commit before 5.4 was released, or to the 5.4 release itself.
```
git tag -d nightly
git tag nightly a5e8eb9c
git push origin nightly
```

**Comment by aferrero2707** [comment]
I modified the tag as you suggested, now the `nightly` tag in the "Nightly Builds" release points to `a5e8eb9c`:

<img width="696" alt="screen shot 2018-04-15 at 15 45 11" src="https://user-images.githubusercontent.com/6229237/38779090-e10b9a30-40c3-11e8-9b14-896a3273baef.png">


GitHub requires a tag to be associated to a given release, because that's how the corresponding page is accessed. For example, for the "Nightly Builds" the URL is `https://github.com/Beep6581/RawTherapee/releases/tag/nightly`

**Comment by Beep6581** [comment]
Branches and tags are both refs, which are pointers to commits. The difference is that tags don't move, while branches do.

I just tried tagging a branch, and it seemed to work:
```
git tag foo dev
```

Anyway, I think we can close this. I'll wait till tomorrow.

**Comment by Beep6581** [comment]
Closing as fixed.

**Comment by Beep6581** [comment]
If you are still experiencing the problem that RT builds with a description such as `nightly-43-g3ee1ecf61`, pull `dev`, delete the `nightly` tag, pull `dev` again to pull in the fixed tag, and merge `dev` into your branch if you have one.

Steps:
```bash
git checkout dev
git pull
git tag -d nightly
git pull

# Check that the tag is now correct:
git show --no-patch nightly
# It should point to commit a5e8eb

git checkout <yourbranch>
git merge dev
```
