### ISSUE TITLE
Tag nightly broke CI build of deb packages

### ISSUE THREAD

**Issue by mbajor** [Beep6581/RawTherapee#4510]
The error is:
`dpkg-source: error: version number does not start with digit`

nightly~git.20180414.23.g38d8fbfcc is not proper version.

How should I versioning deb packages now?

**Comment by heckflosse** [comment]
@mbajor Marcin, we hopefully solve this soon: #4509

**Comment by mbajor** [comment]
@heckflosse I'm affraid that this patch will not help.
I have limited possibilities to download sources for CI build. OBS doesn't have access to Git data. Only sources are downloaded without .git folder.

Downloading and versioning is defined in file
https://build.opensuse.org/package/view_file/home:rawtherapee/rawtherapee-unstable/_service?expand=1
Now the version pattern is
`@PARENT_TAG@~git.%cd.@TAG_OFFSET@.g%h`
then bellow script is executed for create version info
```
echo "Generate release info"
echo $1
version=$1
array=(${version//\~/ })
tag=${array[0]}
array=(${array[1]//\./ })
commit=${array[3]}
commit_date=${array[1]}
length=${#commit} 
commit_stripped=${commit:1:length-1}
commit_since_tag=${array[2]}
echo -e "set(GIT_DESCRIBE $tag-$commit_since_tag-$commit)
set(GIT_BRANCH dev)
set(GIT_COMMIT $commit_stripped)
set(GIT_COMMIT_DATE $commit_date)
set(GIT_COMMITS_SINCE_TAG $commit_since_tag)
set(GIT_COMMITS_SINCE_BRANCH "")
set(GIT_VERSION_NUMERIC_BS $tag.$commit_since_tag)">ReleaseInfo.cmake
```
I can only use for version pattern:
```
      %ct               Commit time as a UNIX timestamp, e.g. 1384855776.
                        This is the default.
      %at               Author time as a UNIX timestamp, e.g. 1384855776.
      %cd               Commit date in YYYYMMDD format, e.g. 20131119
      %ad               Author date in YYYYMMDD format, e.g. 20131119
      %h                Abbreviated hash, e.g. cc62c54
      @PARENT_TAG@      The first tag that is reachable, e.g. v0.2.3
      @TAG_OFFSET@      The commit count since @PARENT_TAG@, e.g. 9```

**Comment by aferrero2707** [comment]
I think the best is to associate this tag (which was automatically created by github when creating the nightly release) to a dedicated branch, instead of `dev`. I can take care of this a bit later today.

The tag is needed to reference the release with the github API that is used to automatically upload the packages...

**Comment by mbajor** [comment]
@aferrero2707 @heckflosse I found that I can filter tags by "match-tag" parameter in OBS.
\*.\* pattern is enough so OBS CI works again.

**Comment by Beep6581** [comment]
@mbajor what was the previous value of `match-tag`?

**Comment by mbajor** [comment]
@Beep6581 The value was not set in config, becasue @PARENT_TAG@ has always been a version number.
Now I have to filter tags excluding other than \*.\*

**Comment by aferrero2707** [comment]
@mbajor do you still have issues after the `nightly` tag was modified to point to a commit prior to `5.4` (as explained [here](https://github.com/Beep6581/RawTherapee/issues/4509#issuecomment-381398749))?
