### ISSUE TITLE
Canon EOS 4000D

### ISSUE THREAD

**Issue by suslikk** [Beep6581/RawTherapee#4520]
Need best support for Canon EOS 4000D
[IMG_4402.zip](https://github.com/Beep6581/RawTherapee/files/1951055/IMG_4402.zip)

**Comment by Benitoite** [comment]
It seemed to work.

**Comment by cuniek** [comment]
go to COLOR TAB -> COLOUR MANAGEMENT -> CUSTOM
click it to open dialog that allows to select color profile. Find folder with color profiles (program files -> rawtherapee -> dcpprofiles). Select Canon 400D. Enjoy.

PS
I don't know why it is not selected by default and why Camera Standard looks so bad.

**Comment by Beep6581** [comment]
@cuniek 4000D not 400D.

**Comment by Thanatomanic** [comment]
Your test image works fine now, closing this issue.
