### ISSUE TITLE
Canon EOS M50 CR3 raw support

### ISSUE THREAD

**Issue by j03jones** [Beep6581/RawTherapee#4531]
Hello,
I am having issues with support for the Canon EOS M50. The camera outputs a new .CR3 file extension. I have uploaded a sample photo from the camera to https://raw.pixls.us/ and was told to open an issue here from Google Plus to better help. RawTherapee fails to recognize the new .CR3 when attempting to view photos.

**RawTherapee Version:** 
Branch: default
Version: 4.2.0
Changeset: c81d9026d25c
Compiler: x86_64-linux-gnu-gcc 5.2.1
Processor: undefined
System: Linux
Bit depth: 64 bits
Gtkmm: V2.24.4
Build type: Release
Build flags: -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -std=c++11 -D_FORTIFY_SOURCE=2   -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG
Link flags:  -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed
OpenMP support: ON
MMAP support: ON

**Camera:** Canon EOS M50

**Sample Photos:**
https://filebin.net/6k7v22b8m01xysin

If there is anything I forgot that you may need, I apologize and will be glad to add anything that is needed. Thank you for your time and effort.

**Comment by agriggio** [comment]
Hi @j03jones,
currently CR3 raw files are not supported by RT. We don't have a decoder yet. BTW, are you aware that you are using an "ancient" version of RT? The current one is 5.4 (though it won't change anything regarding the M50, a lot has changed since 4.2...)

**Comment by j03jones** [comment]
Thank you for your response and information about the decoder. I will have to update the repo to the official. My version was pulled from Ubuntu repository.

**Comment by LebedevRI** [comment]
Cross-referencing https://github.com/darktable-org/rawspeed/issues/121 https://github.com/Exiv2/exiv2/issues/236 https://redmine.darktable.org/issues/12246

@j03jones regarding RPU, how many raw modes does that camera have? It looks like there are two? 
Also, does the aspect ratio really produce different **raw** files?

**Comment by j03jones** [comment]
It does have two different raw outputs (.CR3, C-RAW).

**Comment by DawidLoubser** [comment]
Not sure if this helps, just wanted to mention that I have uploaded two additional sample CR3 files to https://raw.pixls.us/ - one RAW (uncompressed) and one C-RAW (compressed), distinguishable by the comments attached to the uploaded files.

I can't wait until RawTherapee supports this format - how can I as a software engineer that has never looked at RAW codecs, help?

**Comment by malcyL** [comment]
I just replaced my ageing Canon 550D / Rebel T2i to the new Canon RP. It's also the same as the Canon M50 in that it creates RAW files with the CR3 file extension. 

That's the M50, R (#5317) and RP camera's using this format now.

It would be really great if RawTherapee supported it.

**Comment by dmitry-guryanov** [comment]
I also have Canon Rp.

If I understood correctly, rt used dcraw to decode raw files, but few years ago it's discontinued. So now rt maintains it's own version of dcraw and any new code should go directly into rtengine/dcraw.cc? Am I right?

**Comment by heckflosse** [comment]
@dmitry-guryanov 
> any new code should go directly into rtengine/dcraw.cc? Am I right?

Yes and no. If you have code for decoding cr3 files, it can be also for libraw or rawspeed. Just point us to the code so we can adopt it for RT dcraw.cc. Or if it's for dcraw.cc we can tell libraw and rawspeed about that.

**Comment by dmitry-guryanov** [comment]
Thanks! Unfortunately I don't have the code.

**Comment by agriggio** [comment]
I've seen rawdigger advertising some cr3 support recently. so I guess it will land in libraw at some point...

**Comment by Beep6581** [comment]
I opened issue #5319 for tracking support for decoding the CR3 format. Let's use this issue only for auxiliary support (white levels, matrix, DCP, etc.) specific to the Canon EOS M50, once decoding is implemented.

**Comment by Beep6581** [comment]
@j03jones @malcyL @dmitry-guryanov RawTherapee now supports decoding CR3 raw files (but not metadata). Feel free to open a new issue and supply daylight + incandescent tungsten shots of a [color target](http://rawpedia.rawtherapee.com/How_to_create_DCP_color_profiles) as well as LENR=on [white frame](http://rawpedia.rawtherapee.com/Adding_Support_for_New_Raw_Formats) shots (set 2).

This issue is only for the Canon EOS M50, open new issues for other cameras.

**Comment by Thanatomanic** [comment]
Recent Adobe Camera Raw has a color matrix available, but adding it to `camconst.json` is not useful yet because the metadata is not read. For future reference: `{8532, -701, -1167, -4095, 11879, 2508, -797, 2424, 7010}`
