### ISSUE TITLE
Pentax's HDR file in PEF format not recognized as HDR

### ISSUE THREAD

**Issue by Hombre57** [Beep6581/RawTherapee#4532]
Title say it all.

**Comment by Hombre57** [comment]
@Beep6581 @heckflosse Changeset ec2181f should solve this issue.

PS: ... in `hdr-pef` branch.

**Comment by Beep6581** [comment]
Confirmed that 16-/24-/32-bit floating-point HDR DNGs are now detected correctly.

**Comment by Beep6581** [comment]
@Hombre57 branch hdr-pef is still around. Is it needed?
