### ISSUE TITLE
16 bits floating point image shown as 32 bits image in Quick Info

### ISSUE THREAD

**Issue by Hombre57** [Beep6581/RawTherapee#4533]
e.g. files out of HDRMerge.

**Comment by Beep6581** [comment]
Yeah confirmed.

**Comment by Hombre57** [comment]
@Beep6581 @heckflosse Changeset ec2181f should solve this issue.

PS: ... in `hdr-pef` branch.

**Comment by Beep6581** [comment]
Confirmed that 16-/24-/32-bit floating-point HDR DNGs are now detected correctly.
