### ISSUE TITLE
In windows8 the console does not work in release and debug

### ISSUE THREAD

**Issue by Desmis** [Beep6581/RawTherapee#4535]
Since some days, when I run from msys2

./rawtherapee w

the console does not work in release and debug...
With older compilation (20 days ago) no problem all works fine

with that it is almost impossible to develop a program :)

**Comment by Desmis** [comment]
I try with "dev"  - "5d27eea"  - April 28, all works fine

**Comment by Desmis** [comment]
I think it is due to commit 483c0ae 
GIMP RawTherapee plugin cannot find executable in Windows #4514

Or perhaps no ?? It's probably else where

**Comment by Desmis** [comment]
Afer verification and different compilation

In branch "testoutputprofile" all works fine (compilation, dispaly in console) 
with 
git checkout ccf642b ==> OK
git checkout 5a91377 ==> Ok
git checkout 3ebbdf ==> OK

git checkout 483c0ae ==> Does not work

**Comment by gaaned92** [comment]
It seems to me that the behaviour is now in conformity with the help obtained with `./rawtherapee -h`.

-w suppresse the `Windows` console so there is no effect if run from a msys2 console.

if run from msys2 console
-  ./rawtherapee 
 verbose=false: no verbose text displayed in MSYS2 console; RT opens
 verbose = true: verbose text displayed in MSYS2 console. idem with -w (as -w has no effect). RT opens
- ./rawtherapee -h: help displayed in MSYS2 console. 
- ./rawtherapee -v: version displayed in MSY2 console

Why do you want a `Windows` console when running in MSYS2 environment?

If you run from a DOS console, it is different.

**Comment by Desmis** [comment]
@gaaned92 
sometimes ago, there is a change and with Ingo, he says to me to run Rawtherapee in Msys2 console
with : ./rawtherapee w
It does not work, it is probably normal, but for me, no

I just try in DOS console, and > Rawtherapee  w
It works :)

Thank you

**Comment by heckflosse** [comment]
@Desmis Jacques, sorry for being late to the discussion.

Can you tell me what does not work when calling `rawtherapee` in msys2 console?

**Comment by Desmis** [comment]
In msys2 console with 
./rawtherapee w
The system begin, but no console at all :)

In DOS, all works fine

**Comment by heckflosse** [comment]
@Desmis Jacques

with this patch you should get your printfs in msys2 console when starting rt from msys2 console.
Does that solve your issue?

```diff
diff --git a/rtgui/main.cc b/rtgui/main.cc
index 8ba7fb21..327b0ab3 100644
--- a/rtgui/main.cc
+++ b/rtgui/main.cc
@@ -468,6 +468,12 @@ int main (int argc, char **argv)
     Glib::init();  // called by Gtk::Main, but this may be important for thread handling, so we call it ourselves now
     Gio::init ();
 
+#ifdef WIN32
+    if (GetFileType (GetStdHandle (STD_OUTPUT_HANDLE)) == 0x0003) {
+        // started from msys2 console => do not buffer stdout
+        setbuf(stdout, NULL);
+    }
+#endif
 
 #ifdef BUILD_BUNDLE
     char exname[512] = {0};

```

**Comment by Desmis** [comment]
I am not at home. I will test soon.
Thank you :)

**Comment by Desmis** [comment]
I just test the patch

It does not work !

But no problem, I will use DOS console :)

Thank you

**Comment by heckflosse** [comment]
@Desmis Jacques, what do you mean by `it does not work`?
The intention of the patch is **NOT** to open a console, **BUT** showing the output from printf in msys2 console when RT is started from msys2 console, which didn't work correctly before.

**Comment by Desmis** [comment]
@heckflosse 

Ok now I see, and it works :)

Thank you
jacques
