### ISSUE TITLE
Error when building autowblocal and cat02wb for W32

### ISSUE THREAD

**Issue by gaaned92** [Beep6581/RawTherapee#4536]
When building these branches for W32, I get this error:

```
D:/RAWTHERAPEE/RTSOURCE/rawtherapee/rtengine/cat02adaptation.cc: In function 'void rtengine::{anonymous}::ciecamcat02loc_float(rtengine::LabImage*, rtengine::LabImage*, int, double, int, const rtengine::procparams::ColorManagementParams&, const rtengine::procparams::ColorAppearanceParams&)':
D:/RAWTHERAPEE/RTSOURCE/rawtherapee/rtengine/cat02adaptation.cc:255:109: error: no matching function for call to 'rtengine::Ciecam02::jch2xyz_ciecam02float(float&, float&, float&, float&, float&, float&, float&, float&, float&, float&, float&, float&, const int&, const float&, float&, float&, float&, float&, float&, float&)'
                                                     f2,  c2, nc2, gamu, pow1n, nbbj, ncbj, flj, czj, dj, awj);
                                                                                                             ^
In file included from D:/RAWTHERAPEE/RTSOURCE/rawtherapee/rtengine/cat02adaptation.cc:24:0:
D:/RAWTHERAPEE/RTSOURCE/rawtherapee/rtengine/ciecam02.h:66:17: note: candidate: static void rtengine::Ciecam02::jch2xyz_ciecam02float(float&, float&, float&, float, float, float, float, float, float, float, float, int, float, float, float, float, float, float, float)
     static void jch2xyz_ciecam02float ( float &x, float &y, float &z,
                 ^~~~~~~~~~~~~~~~~~~~~
```

It builds for W64

**Comment by Desmis** [comment]
@gaaned92 
I ignore totaly why :)

**Comment by Desmis** [comment]
@gaaned92 

André
J'ai lu la documentation de MSYS2  qui n'est pas claire
Si je veux développer/ compiler en 32 bits est ce que 
a) il faut installer 2 versions, par exemple Mingw64 sur Msys64 et Mingw32 sur Msys32
b) il y a un moyen simple à partir de Mingw64 de compiler en 32 bits

En dehors des ajouts -DCMAKE_C_FLAGS="-mstackrealign" -DCMAKE_CXX_FLAGS="-mstackrealign"

merci

jacques

**Comment by gaaned92** [comment]
- perhaps t@heckflosse @Floessie @agriggio  could help?

- When you install MSYS2, you should get 3 shells: msys2 shell, mingw32 shell and mingw64 shell.
msys2 shell should be used for updating the whole MSYS2.


- To build for 32bit,  first you have to install all required packages with pacman (see rawpedia windows). they are prefixed by mingw-w64-i686. 
Second you use the mingw32 shell (NOT mingw64 shell) that provides all environment variable with the same scripts as for 64 bits (be aware to use different build and install dir from 64bits builds). Thats all.

But nevertheless don't worry about that. Surely some coding guru will lurk in this thread. at least I hope so!

**Comment by Floessie** [comment]
@gaaned92 Could you try this patch on `autowblocal`?

```patch
diff --git a/rtengine/cat02adaptation.cc b/rtengine/cat02adaptation.cc
index cefcc1981..829dd1bcf 100644
--- a/rtengine/cat02adaptation.cc
+++ b/rtengine/cat02adaptation.cc
@@ -252,7 +252,7 @@ void ciecamcat02loc_float(LabImage* lab, LabImage* dest, int tempa, double gree,
                     Ciecam02::jch2xyz_ciecam02float(xx, yy, zz,
                                                     J,  C, h,
                                                     xw2, yw2,  zw2,
-                                                    f2,  c2, nc2, gamu, pow1n, nbbj, ncbj, flj, czj, dj, awj);
+                                                    c2, nc2, gamu, pow1n, nbbj, ncbj, flj, czj, dj, awj);
                     float x, y, z;
                     x = xx * 655.35f;
                     y = yy * 655.35f;
```

Best,
Flössie

**Comment by gaaned92** [comment]
@Floessie  Builds and runs on 32 bits
ok also on 64bits
Thanks

**Comment by Desmis** [comment]
@Floessie 
Thank you, for this good analyse. It is clearly a "merge" problem. But why it compile in W64

@gaaned92 
I will push to commit, one for "autowblocal" and one for "cat02wb"
Thank you to have found this error :)

jacques

**Comment by Desmis** [comment]
@gaaned92 
The 2 push are done :)

**Comment by Floessie** [comment]
@gaaned92 Thanks for testing!

@Desmis De rien. :smile: 

> But why it compile in W64

The problem is in a part of the code where `__SSE2__` is *not* defined, which isn't the case for x86-64/AMD64. So we don't see it on a 64bit PC-OS like W64 or Linux/amd64. I couldn't even reproduce it on Linux/i386, because RT was configured with SSE2 support.

Best,
Flössie

**Comment by gaaned92** [comment]
I think it can be closed
