### ISSUE TITLE
Resizable histogram

### ISSUE THREAD

**Issue by Thanatomanic** [Beep6581/RawTherapee#4537]
For some image manipulations it is worthwhile to pay close attention to the histogram. Unfortunately, the current histogram panel is rather limited in size / aspect ratio (procedure is set in `get_preferred_height_for_width_vfunc()` in `histogrampanel.cc`.) It does not seem to be possible to manually set the height of the panel using a stylesheet, so I would like to request to make the histogram resizable similar to how you can already resize the snapshot list (using GtkPaned).
This is especially useful for people using high resolution monitors, where the histogram is just tiny.

I have been trying to figure out how to do this, but the construction of the GUI and its elements is rather complex ;-)

**Comment by Beep6581** [comment]
PR #4618
