### ISSUE TITLE
camconst.json typo?

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4542]
I'm trying to figure out how Panasonic black levels work for #4540 and found this:
https://github.com/Beep6581/RawTherapee/blob/dev/rtengine/camconst.json#L1640
I suppose the "15" is just a random typo? The entry is too old to find who wrote it, history ends on commit d5ca351c2080bc18f401ff9993e09d0289352dde in 2015.

**Comment by heckflosse** [comment]
ping @iliasg

**Comment by iliasg** [comment]
@Beep6581 Hi .. I came back home yesterday so in the next days I'll be able to update camcost.json with many new models. A lot of work is near completion so I think I will be ready for the weekend ..

It was me who pushed Ingo for this solution some years ago which is same as how D.Coffin implemented in Dcraw.c 

The black level of Panasonic has two parts 
BlackLevelRed/Green/Blue and 
BlackLevel1/2/3 which actually describe an offset which needs to be added to the Red/Green/Blue values to come to the correct BlackLevel value RT should use.  
All six values were reported in older versions of exiftool .. but recent exiftool versions stoped reporting the BlacLevel1/2/3 
exiftool 10.6.8.0 ..
![panasonic_gx9_exif](https://user-images.githubusercontent.com/15012599/39713059-f606dcf8-522d-11e8-8ebb-ef72cf64288d.png)
At first Dcraw used a single harcoded value (around 143). At some point Dcraw.c started using the (usually varying ) BlackLevelRed/Green/Blue from exif and then hardcoded the offset (15) .. so I (we) opted to be compatible with Dcraw and used the same strategy in camconst.json 
In the above sample Dcraw reads the 128,130,128 black levels and we need to add the offset which is 12+4 = 16*
*The Libraw team decoded the BlackLevel1/2/3 values and at least at the start they used the total of the three 1/2/3 values (i.e 16+4+1 = 17) as offset to the BlackLevelRed/Green/Blue .. but by crosschecking with actual black frames I came at the conclusion that only using BlacLevel2 & 3 was preferable .. maybe this is no longer true .. we'll need to investigate some black frames to be sure ..

**Comment by Beep6581** [comment]
> in the next days I'll be able to update camcost.json with many new models

Excellent!

> All six values were reported in older versions of exiftool .. but recent exiftool versions stoped reporting the BlacLevel1/2/3

Confirmed. ExifTool-10.72 prints those values using for example the Panasonic DMC-GX7 RW2 converted to DNG:
https://filebin.net/7llyuoukc4lzzk97/panasonic_lumix_dmc_gx7_15.dng?t=6s3kan43
```text
$ exiftool -G5 -s "Panasonic_-_DMC-G7_-_4_3.dng" | grep Black
[TIFF-IFD0-SubIFD] BlackLevelRepeatDim          : 2 2
[TIFF-IFD0-SubIFD] BlackLevel                   : 143 143 143 143
[TIFF-IFD0-SubIFD1] ReferenceBlackWhite         : 0 255 128 255 128 255
[TIFF-IFD0-MakerNotes-AdobePano] BlackLevel1    : 1
[TIFF-IFD0-MakerNotes-AdobePano] BlackLevel2    : 4
[TIFF-IFD0-MakerNotes-AdobePano] BlackLevel3    : 12
[TIFF-IFD0-MakerNotes-AdobePano] BlackLevelRed  : 128
[TIFF-IFD0-MakerNotes-AdobePano] BlackLevelGreen: 128
[TIFF-IFD0-MakerNotes-AdobePano] BlackLevelBlue : 128
```
ExifTool-10.94 does not:
```text
$ ./exiftool -G5 -s ~/downloads/"Panasonic_-_DMC-G7_-_4_3.dng" | grep Black
[TIFF-IFD0-SubIFD] BlackLevelRepeatDim          : 2 2
[TIFF-IFD0-SubIFD] BlackLevel                   : 143 143 143 143
[TIFF-IFD0-SubIFD1] ReferenceBlackWhite         : 0 255 128 255 128 255
[TIFF-IFD0-MakerNotes-AdobePano] BlackLevelRed  : 128
[TIFF-IFD0-MakerNotes-AdobePano] BlackLevelGreen: 128
[TIFF-IFD0-MakerNotes-AdobePano] BlackLevelBlue : 128
```

I can't check with the latest ExifTool, because it's still hosted on SourceForge and SF is of course currently out of order... :roll_eyes: 

For going forward, it would be prudent to rely on tags which Exiv2 can read, since we need to start using it. The data in `/rtexif/` comes from ExifTool, I update that manually once every few months.

**Comment by iliasg** [comment]
Hmm .. interesting that Adobe use +15 as offset .. we'll need to take a look at some black frames for as many as possible Panasonic models .. :( .. let's start with gx9 ..

**Comment by Beep6581** [comment]
@iliasg 

camconst.json says that `BlackLevelRed`, `BlackLevelGreen` and `BlackLevelBlue` are the **base** here https://github.com/Beep6581/RawTherapee/blob/dev/rtengine/camconst.json#L281
but it says that `BlackLevelRed15` (which does not exist, only `BlackLevelRed` exists, without the `15`) is an **offset** here:
https://github.com/Beep6581/RawTherapee/blob/dev/rtengine/camconst.json#L1640

You explained to me that `BlackLevel3` + `BlackLevel2` are the **offset** here:
https://github.com/Beep6581/RawTherapee/issues/4574#issuecomment-393222017

So there is completely conflicting info.

Is the following suggested patch correct?
```diff
diff --git a/rtengine/camconst.json b/rtengine/camconst.json
index d2c8f8ae..597c5e4d 100644
--- a/rtengine/camconst.json
+++ b/rtengine/camconst.json
@@ -278,12 +278,15 @@ About black levels:
     can be derived from masked pixels (typical for Canon cameras) or otherwise be extracted from some tag.
 
     Some formats have built-in subtraction information and are pre-processed by dcraw to end up at a black level of
-    zero (Phase One's IIQ).  For Panasonic raws beginning from dcraw v9.21 dcraw/RT reads base BL from Exif data (tags 0x001c
-    BlackLevelRed, 0x001d BlackLevelGreen, 0x001e BlackLevelBlue) and we define in "ranges": { "black": the needed offset
-    of around 15. The (total) BL RT displays is base+offset In all, you typically should not care about the black
-    level in camconst.json, any information that can be derived from the raw file itself should not be specified in
-    camconst.json! Sony's ARW2 is one of the few exceptions (with single black level around 512, or 800 for
-    RX10/100 models), but dcraw generally has good constants for these already.
+    zero (Phase One's IIQ).
+
+    For Panasonic cameras, the black level defined in camconst.json is the black level offset, which comes from
+    BlackLevel3 + BlackLevel2. RawTherapee then reads the base black levels from Exif data (0x001c BlackLevelRed,
+    0x001d BlackLevelGreen and 0x001e BlackLevelBlue) and adds them to the offset.
+
+    In all, you typically should not care about the black level in camconst.json, any information that can be derived from
+    the raw file itself should not be specified in camconst.json! Sony's ARW2 is one of the few exceptions (with a single
+    black level around 512, or 800 for RX10/100 models), but dcraw generally has good constants for these already.
 
     Currently we have chosen not to provide any guide how to measure black levels as we don't think it will be a common task
     (it's also more difficult to do than measure white levels). If you experience a black level issue it's more likely due
@@ -1637,11 +1640,6 @@ Camera constants:
         "ranges": { "white": 4050 } // safe for worst case detected, nominal is 4093
     },
 
-/*  Since dcraw_v9.21 Panasonic base BL is read from Exif (tags 0x001c BlackLevelRed15 is BL offset.
-    dcraw/RT read the base black from Exif and calculates total BL = BLbase+BLoffset, 0x001d BlackLevelGreen, 0x001e BlackLevelBlue
-    and we define here the needed offset of around 15. The total BL is base+offset
-*/
-
     { // Quality C, proper ISO 100-125-160 samples missing, pixelshift files have no black offset etc. #4574
         "make_model": [ "Panasonic DC-G9" ],
         "dcraw_matrix": [ 7685, -2375, -634, -3687, 11700, 2249, -748, 1546, 5111 ], // Adobe DNG Converter 10.3 ColorMatrix2
```

**Comment by iliasg** [comment]
I think the correction is fine :)

**Comment by Beep6581** [comment]
Great, done in commit f1037460
