### ISSUE TITLE
HaldCLUT doesn't work

### ISSUE THREAD

**Issue by klimentyev** [Beep6581/RawTherapee#4548]
In RawTherapee 5.3 and 5.4 on Linux (Calculate Linux 64 bit based on Gentoo), film simulation doesn't work. It was correct in v 4.x. I choose a film from the list, but nothing happens in "live" mode. After processing nothing happens too...
P.S. For last AppImage 5.4, the behavior is the same.

**Comment by heckflosse** [comment]
Works fine on Windows7/64

**Comment by klimentyev** [comment]
What additional information can I provide? I choose different film and have no effect. The path to HaldCLUT is correct, the list of film is correct too.

**Comment by heckflosse** [comment]
Just to exclude it: Is the tool enabled?
![grafik](https://user-images.githubusercontent.com/13733487/39943520-7070b03a-5563-11e8-8ed7-0653441ea89f.png)

**Comment by klimentyev** [comment]
Thank you very much! I switched on it after your comment.
