### ISSUE TITLE
Rename HDR Tone Mapping to Dynamic Range Compression

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4553]
Someone (@agriggio ?) suggested renaming "HDR Tone Mapping" to "Dynamic Range Compression". Sounds better in my opinion. Let's do it?

**Comment by sguyader** [comment]
Renaming the tool is fine by me. There's already a "Tone mapping" tools, so it might be less confusing to some with the new proposed name.

**Comment by Floessie** [comment]
> Sounds better in my opinion.

Definitely. Go for it! :+1:

**Comment by agriggio** [comment]
Yes, I agree

**Comment by Benitoite** [comment]
I agree also.  Maybe not related, but if we have a dynamic range compressor, is it possible to have expansion as well?

**Comment by Beep6581** [comment]
Since we agree on this, what about the tool called "Tone Mapping"? It is based on a paper titled Edge-Preserving Decompositions for Multi-Scale Tone and Detail Manipulation, and its effects are not what one expects when doing tone mapping in other software, so its name is not very descriptive.

**Comment by heckflosse** [comment]
@Beep6581 

`Edge-Preserving Decompositions for Multi-Scale Tone and Detail Manipulation` would increase the width of the tool panel a lot :[

**Comment by heckflosse** [comment]
How about `EPD Tone Mapping` ?

**Comment by agriggio** [comment]
@Beep6581 "detail boost"?
@Benitoite I think we have already contrast sliders for that

**Comment by Beep6581** [comment]
Detail Boost sounds appropriate, but it would also warrant moving the tool into the Details tab...

**Comment by TooWaBoo** [comment]
...or HDR dynamic compression

**Comment by agriggio** [comment]
:+1: to moving the current "Tone Mapping" to the details tab, and to rename it.
But apart from that, are we ok to rename "HDR Tone Mapping" to "Dynamic Range Compression"? Is it enough to update the relevant entries in the language files? Or do we need more?

**Comment by Beep6581** [comment]
@agriggio I'm on it.
