### ISSUE TITLE
Update rtexif using ExifTool-10.96

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4554]
Update rtexif using ExifTool-10.96

**Comment by Hombre57** [comment]
@Beep6581 What's the idea exactly ?

**Comment by Beep6581** [comment]
@Hombre57 idea of?

**Comment by Hombre57** [comment]
@Beep6581 What do you mean by "Update rtexif" ? Camera and lens list ? Or replacing it by ExifTool (instead of Exiv2) ?

**Comment by Beep6581** [comment]
@Hombre57 the data in https://github.com/Beep6581/RawTherapee/tree/dev/rtexif needs to be updated in order to identify new lenses and cameras. I've been doing that for 3 years. Replacing that with something better is handled by issue #3801.

There is a commit (immediately above your "What's the idea exactly" question) and a pull request pending, are they not visible on your end?

**Comment by Hombre57** [comment]
@Beep6581 

> There is a commit (immediately above your "What's the idea exactly" question) and a pull request pending, are they not visible on your end?

They are visible if I doesn't overlook them at 1:30 AM... Sorry for the noise.

**Comment by Beep6581** [comment]
No problem ;)
I'll merge.
