### ISSUE TITLE
Highlight compression threshold gets reset differently

### ISSUE THREAD

**Issue by Thanatomanic** [Beep6581/RawTherapee#4562]
A rather minor thing, but I noticed that when you press the general Reset button in the Exposure tab, the "Highlight compression threshold" gets set to 0. However, if you press the "Reset to Default" button paired with the slider it sets it to 33.

**Comment by Beep6581** [comment]
```text
rtengine/improcfun.cc:5462:    hlcomprthresh = 33;
rtengine/procparams.cc:330:    hlcomprthresh(33),
rtgui/tonecurve.cc:114:    hlcomprthresh = Gtk::manage (new Adjuster (M("TP_EXPOSURE_COMPRHIGHLIGHTSTHRESHOLD"), 0, 100, 1, 33));
```

Is this safe to change to 0?
https://github.com/Beep6581/RawTherapee/blob/dev/rtengine/improcfun.cc#L5462
