### ISSUE TITLE
Gtk::ToggleButton where Gtk::Button should be

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4564]
There are various places which use `Gtk::ToggleButton` where I think a `Gtk::Button` would be more intuitive because the operation is a one-time thing:
* Exposure - Auto Levels
* Exposure - Reset
* Black-and-White - Channel Mixer - Auto
* Black-and-White - Channel Mixer - Reset

Examples of places where a `Gtk::ToggleButton` is justified:
* Auto-Matched Tone Curve, because when toggled it responds to changes upstream, e.g. when you enable the DCP tone curve.

What do you think?

@Desmis could you comment on whether channel mixer "auto" and "reset" react to anything *after* being enabled?

**Comment by Desmis** [comment]
@Beep6581 
Excuse my bad comprehension of english. But I don't understand all :)

If you think it is better "Gtk::Button" why not ? but for me, it's clear,  but other examples have shown that I was not a reference in this regard :)
jacques

**Comment by TooWaBoo** [comment]
Exposure - Auto Levels must be a toggle button. This function can be copied and saved to the pp3 and when applied to an image (copy or from pp3) it will change the exposure.

**Comment by Desmis** [comment]
@Beep6581 
I think I understand the question ! ( not sure...)

* for me : 
Black-and-White - Channel Mixer - Auto , must be a toogle button
Black-and-White - Channel Mixer - Reset, is not a toogle button, but a Gtk::Button. But we can suppress call to events 
/*
    if(listener) {
        listener->panelChanged (EvNeutralBW, M("GENERAL_RESET"));
    }
*/
That will simplified the system. It is enough to comment this code (or suppress), and also in procevents.h and put to zero in refreshmap.cc

How I do ? 
a) directly I chnage "dev" ?
b) I create a new branch to valid ?

**Comment by Beep6581** [comment]
@TooWaBoo yes, I agree.
@Desmis you're right that "Reset" is a `Gtk:Button`... I was under the impression that it was a Gtk::ToggleButton based on its appearance - I will have to double-check the RT theme. At this point I'm not sure whether anything needs to be changed.
It's good that we at least revised this and made sure it's as it should be.

**Comment by Beep6581** [comment]
The confusion was caused by the theme. I propose this patch:
```diff
diff --git a/rtdata/themes/RawTherapee-GTK3-20_.css b/rtdata/themes/RawTherapee-GTK3-20_.css
index ba58e412..cc533320 100644
--- a/rtdata/themes/RawTherapee-GTK3-20_.css
+++ b/rtdata/themes/RawTherapee-GTK3-20_.css
@@ -222,7 +222,7 @@ button  {
     padding: 0;
     min-height: 5px;
     min-width: 5px;
-    background-image: linear-gradient(#343434, #2E2E2E, #292929);
+    background-image: linear-gradient(to bottom, rgba(100,100,100,.3), rgba(30,30,30,.3));
 }
 
 /* Curve mode buttons and drop-downs */
@@ -247,7 +247,7 @@ radiobutton > radio {
     background-image: linear-gradient(#343434, #2E2E2E, #292929);
 }
 
-button:hover , button.flat:hover, checkbutton:hover > check, radiobutton:hover > radio {
+button.flat:hover, checkbutton:hover > check, radiobutton:hover > radio {
     background-image: linear-gradient(shade(#343434,1.3), shade(#2E2E2E,1.3), shade(#292929,1.3));
 }
 
@@ -255,6 +255,22 @@ button.popupbutton-arrow {
     min-width: 18px;
 }
 
+button:hover  {
+    background-image: linear-gradient(to bottom, rgba(150,150,150,.3), rgba(80,80,80,.3));
+}
+
+button:active  {
+    background-image: linear-gradient(to bottom, rgba(30,30,30,.3), rgba(0,0,0,.3));
+}
+
+button:checked  {
+    background-image: linear-gradient(to bottom, rgba(30,30,30,.8), rgba(0,0,0,.8));
+}
+
+button:checked:hover  {
+    background-image: linear-gradient(to bottom, rgba(60,60,60,1), rgba(30,30,30,1));
+}
+
 /* Save, Cancel, OK ... buttons */
 .dialog-action-area button {
     min-height: 24px;
```

Unpatched. Notice that "Reset" looks like a ToggleButton which is pressed, which makes no sense here since resetting is a one-time thing. The comboboxes are also too attention-grabbing.
![1u](https://user-images.githubusercontent.com/5844619/40280704-b3258856-5c57-11e8-9150-b90c350dd5b0.png)

Patched:
![1p](https://user-images.githubusercontent.com/5844619/40280705-b82253ac-5c57-11e8-87df-478754e99beb.png)

Unpatched, "Reset" looks like its a checked ToggleButton:
![2u](https://user-images.githubusercontent.com/5844619/40280715-ce3784a0-5c57-11e8-873a-c3a96b50ba93.png)

Patched:
![2p](https://user-images.githubusercontent.com/5844619/40280716-d2729596-5c57-11e8-8cb9-887de3a841bd.png)

Unpatched, both "Auto" and "Reset" look like they're checked:
![3u](https://user-images.githubusercontent.com/5844619/40280722-ee153b00-5c57-11e8-98dc-d43a995a29d6.png)

Patched:
![3p](https://user-images.githubusercontent.com/5844619/40280724-f27e5afa-5c57-11e8-8c73-3d074ff4715a.png)

**Comment by Hombre57** [comment]
@Beep6581 Good for me, :+1: to commit
