### ISSUE TITLE
Update Japanese UI

### ISSUE THREAD

**Issue by Yz2house** [Beep6581/RawTherapee#4566]
I updated Japanese translation for UI.
rgds
[Japanese.txt](https://github.com/Beep6581/RawTherapee/files/2016887/Japanese.txt)

**Comment by Beep6581** [comment]
Thanks @Yz2house 
You might want to review the latest changes and update the translation:
https://github.com/Beep6581/RawTherapee/commits/dev/rtdata/languages/default
Click on the blue hash button on the right to see what changed in each commit, e.g. today I changed the `ADJUSTER_RESET_TO_DEFAULT` key and some other keys.

**Comment by Yz2house** [comment]
I'd like to help the translation for RawPedia next.  I will send the request form.
rgds
