### ISSUE TITLE
Black-and-White auto channel mixer bug

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4570]
1. Clear the processing profile from some file from the File Browser via right-click.
2. Open the raw file,
3. Apply neutral,
4. Enable Black-and-White
5. Select the Channel Mixer
![screenshot_20180520_181750](https://user-images.githubusercontent.com/5844619/40280907-4971c44e-5c5a-11e8-9e3b-c4068c665dda.png)
6. Click "Auto"
Something happens, the sliders turn grey for a moment, the history shows R=G=B=0, and the "Auto" `Gtk::ToggleButton` remains unchecked. It's a bug that history shows "0", since the values are actually 34/31/35. It's also a bug that the "Auto" ToggleButton is not checked - it should be checked since it was just clicked.
![screenshot_20180520_180704](https://user-images.githubusercontent.com/5844619/40280861-b6d8d6ae-5c59-11e8-81ee-805299ac5c64.png)
7. Click "Auto" again, now it's checked.
![screenshot_20180520_180831](https://user-images.githubusercontent.com/5844619/40280871-bc578094-5c59-11e8-8372-36b18f4eae1d.png)
8. Go back in history to "B&*W - Mode | Channel Mixer"
9. Click on "Auto". Now history correctly shows 34/31/35, but the button is again not checked.

One more thing which could be a bug: the preview in the screenshot from point 5 is almost identical to the preview in point 7 - how can that be? The "Color Filter" slider values between 5 and 7 are very different, the "Preset" is different, and the R/G/B label shows very different percentages, yet the previews are almost identical. Conversely, the previews between points 6 and 7 are very different, but the R/G/B percentage values are quite similar.

**Comment by Desmis** [comment]
I push a change in a new  branch "blackwhiteauto".

I think it solves the problem (almost in most cases) - it is quite complex because update  GUI is always after treatment and it cost time.
I change also some default settings

**Comment by Beep6581** [comment]
Hey @Desmis 

The improvements are good!

There is one small issue still:
* I point 6 above, when I click on Channel Mixer's Auto button for the first time, history now shows "B&W - CM - Auto | (Unchanged)".
* If I click it again, it shows "B&W - CM - Auto | Disabled".
* And if I click it again, it shows "B&W - CM - Auto | Enabled". So the first time it should show "Enabled" not "(Unchanged)".

**Comment by Desmis** [comment]
@Beep6581 
I push a change. I think it solved this case :)

jacques

**Comment by Beep6581** [comment]
The latest commit also deleted a valid DCP file:
https://github.com/Beep6581/RawTherapee/commit/69dd5fbf5c0e7990168443fdf8f720c85bad561e

**Comment by Beep6581** [comment]
I will test the branch soon, and if it works well then I will manually merge the code changes into `dev`.

**Comment by Beep6581** [comment]
@Desmis I confirm the fix :+1: 
If you don't object, I will merged this tomorrow.

**Comment by Beep6581** [comment]
This diff should have all required changes:
```diff
diff --git a/rtengine/improccoordinator.cc b/rtengine/improccoordinator.cc
index f39fe341..cac1d643 100644
--- a/rtengine/improccoordinator.cc
+++ b/rtengine/improccoordinator.cc
@@ -556,7 +556,6 @@ void ImProcCoordinator::updatePreviewImage (int todo, Crop* cropCall)
                 if (settings->verbose) {
                     printf ("ImProcCoordinator / Auto B&W coefs:   R=%.2f   G=%.2f   B=%.2f\n", bwAutoR, bwAutoG, bwAutoB);
                 }
-
                 abwListener->BWChanged ((float) rrm, (float) ggm, (float) bbm);
             }
 
diff --git a/rtengine/improccoordinator.h b/rtengine/improccoordinator.h
index ada7ed75..5144c772 100644
--- a/rtengine/improccoordinator.h
+++ b/rtengine/improccoordinator.h
@@ -69,7 +69,6 @@ protected:
 
     double lastAwbEqual;
     double lastAwbTempBias;
-
     ImProcFunctions ipf;
 
     Glib::ustring monitorProfile;
diff --git a/rtengine/procparams.cc b/rtengine/procparams.cc
index 00419693..36fa4aa2 100644
--- a/rtengine/procparams.cc
+++ b/rtengine/procparams.cc
@@ -1842,7 +1842,7 @@ BlackWhiteParams::BlackWhiteParams() :
     enabledcc(true),
     enabled(false),
     filter("None"),
-    setting("NormalContrast"),
+    setting("RGB-Rel"),
     method("Desaturation"),
     mixerRed(33),
     mixerOrange(33),
diff --git a/rtgui/blackwhite.cc b/rtgui/blackwhite.cc
index 6970a2f3..630bde61 100644
--- a/rtgui/blackwhite.cc
+++ b/rtgui/blackwhite.cc
@@ -128,7 +128,7 @@ BlackWhite::BlackWhite (): FoldableToolPanel(this, "blackwhite", M("TP_BWMIX_LAB
     setting->append (M("TP_BWMIX_SET_ROYGCBPMREL"));
     setting->append (M("TP_BWMIX_SET_INFRARED"));
 
-    setting->set_active (0);
+    setting->set_active (11);
     settingHBox->pack_start (*setting);
     mixerVBox->pack_start (*settingHBox);
     settingconn = setting->signal_changed().connect ( sigc::mem_fun(*this, &BlackWhite::settingChanged) );
@@ -388,9 +388,22 @@ bool BlackWhite::BWComputed_ ()
 
     disableListener ();
     mixerRed->setValue (nextredbw);
+    adjusterChanged(mixerRed, mixerRed->getValue());
     mixerGreen->setValue (nextgreenbw);
+    adjusterChanged(mixerGreen, mixerGreen->getValue());
     mixerBlue->setValue (nextbluebw);
+    adjusterChanged(mixerBlue, mixerBlue->getValue());
+    autoconn.block (true);
+    autoch->set_active (true);
+    autoconn.block (false);
+    lastAuto = false;
+    nextcount++;
+    //printf("nextcount=%i\n", nextcount);
     enableListener ();
+    if (listener  && nextcount <= 1 ) {
+        // activated only 1 time, but perhaps in some cases if we want that all is update pp3, auto, sliders : nextcount <= 2 but it cost time and result is identical
+        listener->panelChanged (EvAutoch, M("GENERAL_ENABLED"));
+    }
 
     updateRGBLabel();
 
@@ -577,7 +590,7 @@ void BlackWhite::write (ProcParams* pp, ParamsEdited* pedited)
     pp->blackwhite.mixerPurple = mixerPurple->getValue ();
     pp->blackwhite.beforeCurve = beforeCurve->getCurve ();
     pp->blackwhite.afterCurve = afterCurve->getCurve ();
-
+//printf("mblue=%i \n",  pp->blackwhite.mixerBlue);
     int tcMode = beforeCurveMode->get_active_row_number();
 
     if      (tcMode == 0) {
@@ -789,6 +802,7 @@ void BlackWhite::filterChanged ()
 
     if (listener && (multiImage || getEnabled())) {
         listener->panelChanged (EvBWfilter, filter->get_active_text ());
+        listener->panelChanged (EvAutoch, M("GENERAL_ENABLED"));
     }
 }
 
@@ -883,10 +897,11 @@ void BlackWhite::neutral_pressed ()
     enableListener();
 
     updateRGBLabel();
-
+    nextcount = 0;
     if(listener) {
         listener->panelChanged (EvNeutralBW, M("GENERAL_RESET"));
     }
+
 }
 
 void BlackWhite::enabledcc_toggled ()
@@ -1088,7 +1103,7 @@ void BlackWhite::adjusterChanged (Adjuster* a, double newval)
         if (multiImage && autoch->get_inconsistent()) {
             autoch->set_inconsistent (false);
         }
-
+        nextcount = 0;
         autoconn.block(true);
         autoch->set_active (false);
         autoconn.block(false);
diff --git a/rtgui/blackwhite.h b/rtgui/blackwhite.h
index 5f0ffec4..07ad6a16 100644
--- a/rtgui/blackwhite.h
+++ b/rtgui/blackwhite.h
@@ -138,6 +138,7 @@ private:
     double nextredbw;
     double nextgreenbw;
     double nextbluebw;
+    int nextcount = 0;
 
     IdleRegister idle_register;
 };
```

**Comment by Beep6581** [comment]
Patch committed, thank you for fixing it @Desmis .
