### ISSUE TITLE
PDAF lines pattern for A7RIII

### ISSUE THREAD

**Issue by agriggio** [Beep6581/RawTherapee#4572]
I don't have the chance right now to push this to `dev`, so I'm reporting it here. Hopefully someone else can commit for me :-) 

Here's the PDAF pattern for the Sony A7RIII:

```txt
    {
        "make_model": "Sony ILCE-7RM3",        
        "pdafPattern" : [0, 24, 36, 60, 84, 120, 132, 156, 192, 204, 240, 252, 276, 300, 324, 360, 372, 396, 420, 444, 480, 492, 504, 540, 564, 576, 612, 636, 660, 696, 720, 732, 756, 780, 804, 840],
        "pdafOffset" : 31
    }
```

A good picture to test that it works as expected (using the PDAF lines filter) as [this one from dpreview](https://www.dpreview.com/sample-galleries/0095576088/sample-gallery-sony-24-105-f4-g-oss/3004141138) (though you have to boost the edges or increase the contrast to see the striping more clearly -- I used "edge sharpness" in wavelets for my tests)

**Comment by heckflosse** [comment]
@agriggio I commited to dev using the web interface ;-)
