### ISSUE TITLE
Panasonic DC-G9

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4574]
Preliminary support for the Panasonic DC-G9:
```javascript
    { // Quality X, #4574
        "make_model": [ "Panasonic DC-G9" ],
        "dcraw_matrix": [ 7685, -2375, -634, -3687, 11700, 2249, -748, 1546, 5111 ], // Adobe DNG Converter 10.3 ColorMatrix2
        "ranges": { "black": 15 }
    },
```

https://filebin.net/bkttmnu1sikp26ez

@iliasg could you please explain how to find the black level offset? The camconst header isn't clear on that. `BlackLevelRed`, `BlackLevelGreen` and `BlackLevelBlue` are the base, but where does the offset value `15` come from?

>     For Panasonic raws beginning from dcraw v9.21 dcraw/RT reads base BL from Exif data (tags 0x001c BlackLevelRed, 0x001d BlackLevelGreen, 0x001e BlackLevelBlue) and we define in "ranges": { "black": the needed offset of around 15. The (total) BL RT displays is base+offset

```text
-TIFF-IFD0:Make=Panasonic
-TIFF-IFD0:Model=DC-G9
-TIFF-IFD0-SubIFD:BlackLevelRepeatDim=2 2
-TIFF-IFD0-SubIFD:BlackLevel=144 143 143 144
-TIFF-IFD0-SubIFD1:ReferenceBlackWhite=0 255 128 255 128 255
-TIFF-IFD0-MakerNotes-AdobePano:BlackLevel1=1
-TIFF-IFD0-MakerNotes-AdobePano:BlackLevel2=1
-TIFF-IFD0-MakerNotes-AdobePano:BlackLevel3=12
-TIFF-IFD0-MakerNotes-AdobePano:BlackLevelRed=129
-TIFF-IFD0-MakerNotes-AdobePano:BlackLevelGreen=128
-TIFF-IFD0-MakerNotes-AdobePano:BlackLevelBlue=129
```

And for reference, two other cameras which use an offset of 15 in `camconst.json`:
```text
Panasonic - DMC-LX10 - 4_3.dng
-TIFF-IFD0:Make=Panasonic
-TIFF-IFD0:Model=DMC-LX10
-TIFF-IFD0-SubIFD:BlackLevelRepeatDim=2 2
-TIFF-IFD0-SubIFD:BlackLevel=143 143 143 143
-TIFF-IFD0-SubIFD1:ReferenceBlackWhite=0 255 128 255 128 255
-TIFF-IFD0-MakerNotes-AdobePano:BlackLevel1=1
-TIFF-IFD0-MakerNotes-AdobePano:BlackLevel2=3
-TIFF-IFD0-MakerNotes-AdobePano:BlackLevel3=12
-TIFF-IFD0-MakerNotes-AdobePano:BlackLevelRed=128
-TIFF-IFD0-MakerNotes-AdobePano:BlackLevelGreen=128
-TIFF-IFD0-MakerNotes-AdobePano:BlackLevelBlue=128
-TIFF-IFD0-MakerNotes-AdobePano-JpgFromRaw-APP1-IFD0:Make=Panasonic
-TIFF-IFD0-MakerNotes-AdobePano-JpgFromRaw-APP1-IFD0:Model=DMC-LX10

Panasonic - DMC-LX15 - 3_2.dng
-TIFF-IFD0:Make=Panasonic
-TIFF-IFD0:Model=DMC-LX15
-TIFF-IFD0-SubIFD:BlackLevelRepeatDim=2 2
-TIFF-IFD0-SubIFD:BlackLevel=141 141 141 141
-TIFF-IFD0-SubIFD1:ReferenceBlackWhite=0 255 128 255 128 255
-TIFF-IFD0-MakerNotes-AdobePano:BlackLevel1=1
-TIFF-IFD0-MakerNotes-AdobePano:BlackLevel2=3
-TIFF-IFD0-MakerNotes-AdobePano:BlackLevel3=12
-TIFF-IFD0-MakerNotes-AdobePano:BlackLevelRed=126
-TIFF-IFD0-MakerNotes-AdobePano:BlackLevelGreen=126
-TIFF-IFD0-MakerNotes-AdobePano:BlackLevelBlue=126
-TIFF-IFD0-MakerNotes-AdobePano-JpgFromRaw-APP1-IFD0:Make=Panasonic
-TIFF-IFD0-MakerNotes-AdobePano-JpgFromRaw-APP1-IFD0:Model=DMC-LX15
```

**Comment by shoffmeister** [comment]
FWIW, the Panasonic G9 has a high-resolution mode (where it composits eight exposures into one photo). The raw format used there is relatively new (first seen in the G9, and then only in the GH5s).

See https://github.com/darktable-org/rawspeed/blob/develop/src/librawspeed/decompressors/PanasonicDecompressorV5.cpp for the current rawspeed implementation, inspired by a commit in libraw. See the commit history for details. I had a quick look at the current state of the repo on the dev branch and could not find that format implemented.

Samples for the new format are on raw.pixls.us

**Comment by iliasg** [comment]
@Beep6581 

> could you please explain how to find the black level offset? The camconst header isn't clear on that. BlackLevelRed, BlackLevelGreen and BlackLevelBlue are the base, but where does the offset value 15 come from?

I use BlackLevel3 + BlackLevel2 i.e for G9 it should be 12+1=13 .. but as this calculation differs from the reported in DNG exif values .. we need to investigate black frames 
I hope I'll manage to work on this in the next few days :(

**Comment by iliasg** [comment]
Found some samples from web .. the camconst item is valid only for normal files .. pixelshift files (both the combination of 8 frames and the companion single frame)  have no black offset .. and a bit different white level at ISO100 .. 
Also checked the black offset value by inspecting raw histograms at high ISOs (so that raw values near zero exist ) .. indeed it clips at 15-16 so the calculated value from blacklevel1/2/3 prooved wrong 
```
    { // Quality C, proper ISO 100-125-160 samples missing, pixelshift files have no black offset etc 
        "make_model": [ "Panasonic DC-G9" ],
        "dcraw_matrix": [ 7685,-2375,-634,-3687,11700,2249,-748,1546,5111 ], // DNG_v10.1 D65
        "ranges": {
            "black": 15, // 15 is BL offset. dcraw/RT read the base black from Exif and calculates total BL = BLbase+BLoffset
            "white": [
                { "iso": 100, "levels": 3000 }, // gaussian 3100-3600 Exif_linearitylimit 2111
                { "iso": 125, "levels": 3500 }, // guessed
                { "iso": [ 160, 200, 250, 320, 400,500, 640, 800, 1000, 1250, 1600, 2000, 2500, 3200, 4000, 5000, 6400, 12800, 25600 ], "levels": 4080 } // nominal 4095
            ]
        }
    },
```

**Comment by Beep6581** [comment]
@iliasg should I commit, or will this be part of a bigger camconst update which you mentioned a week or two ago?

**Comment by iliasg** [comment]
@Beep6581 Morgan, no problem if you commit .. I'll synchronize 
I have very limited time and resources at present .. so a major update will be only possible at the end of the month

**Comment by Beep6581** [comment]
Committed in 971658da
