### ISSUE TITLE
Combined Amaze/VNG4 demosaic

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#4579]
I created amaze_vng4 branch with a combined amaze/vng4 demosaic. It blends the result of vng4 demosaic and amaze demosaic based on contrast. Currently the threshold is hard coded. I mapped it to EAHD demosaic for tests.

Here are first results:

Left is amaze, right is plain vng4
![grafik](https://user-images.githubusercontent.com/13733487/40660855-8558bcf2-6352-11e8-9dca-0c205a70d323.png)

Left is Amaze, right is Amaze/vng4 combined
![grafik](https://user-images.githubusercontent.com/13733487/40660895-9c6d93fe-6352-11e8-9361-27eaf62e3e09.png)

**Comment by sguyader** [comment]
@heckflosse Neat idea and results, Ingo!

**Comment by TooWaBoo** [comment]
Hey, looks good, merge it. 😁

**Comment by heckflosse** [comment]
I cleaned the code and created an own entry for `AMaZE+VNG4` in demosaic combobox

**Comment by heckflosse** [comment]
@TooWaBoo 

> Hey, looks good, merge it.

5 hours between the first mockup and a merge really is not enough time ;-)

**Comment by heckflosse** [comment]
related to #2008

**Comment by ff2000** [comment]
Ok, this is getting better and better...

Amaze, sharpening + microcontrast, NR: 20 luma, 60 detail:
![p1090042](https://user-images.githubusercontent.com/1973708/40833247-046fd5ee-6596-11e8-884e-e8811537a737.jpg)
Amaze.Vng4: DualDemosaicContrast=40, sharpening + microcontrast, NR: 0 luma, 0 detail
![p1090042-1](https://user-images.githubusercontent.com/1973708/40833470-ad7b33f4-6596-11e8-82da-827e05346c0d.jpg)

This is ISO 1000 on Micro Four Thirds, with an adapted Micro-Nikkor (https://kenrockwell.com/nikon/105af.htm) - not the very best lens considering resolution for the pixelpitch of that sensor.

I played with other files and for some I could enable microcontrast where previously it just detroyed "flat" areas. Same applies to Local Contrast.

Thx for your continued efforts!

**Comment by iliasg** [comment]
Ingo, you made an old dream come true !! many thanks :)

**Comment by Hombre57** [comment]
@heckflosse Code cleanup in commit 928309f3aab7adc520d2676970cf9dca85e8308e
