### ISSUE TITLE
Corrupt bar on right in SONY ILCE-7M2 DNGs

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4585]
![screenshot_20180601_002118](https://user-images.githubusercontent.com/5844619/40811507-c3021c66-6531-11e8-87a9-4ad3d3648d31.png)
https://filebin.net/xl9p4nd9pc98h81u/2018-05-26_mollan_11.dng?t=wqb6k0h3
Using a0b8626b (branch `amaze_vng4`) with `dev` 6fcc8251 merged into it.

**Comment by heckflosse** [comment]
Confirmed with all demosaicers, even with 'None'

**Comment by iliasg** [comment]
Dcraw.c cuts off the 24 right columns for ARW .. while not from the DNG .. should we use adobecoeff for this case, or add frame data in camconst.json ? .. although in the camconst case we are not sure what will happen with the APS-C cropped DNGs ..

**Comment by Beep6581** [comment]
I'm still experiencing this bug. How do I add an entry to `camconst.json` so that it affects DNG but not ARW?

Permanent test image:
http://rawtherapee.com/shared/test_images/cat_iso100.dng

**Comment by Beep6581** [comment]
Does anyone have an idea how to fix this?

**Comment by heckflosse** [comment]
@Beep6581 looking...

**Comment by heckflosse** [comment]
Here's a fix

```diff
diff --git a/rtengine/dcraw.cc b/rtengine/dcraw.cc
index d302eb425..df78f29b0 100644
--- a/rtengine/dcraw.cc
+++ b/rtengine/dcraw.cc
@@ -10044,6 +10044,9 @@ dng_skip:
     memcpy (rgb_cam, cmatrix, sizeof cmatrix);
     raw_color = 0;
   }
+  if (!strcmp(make,"Sony") && raw_width == 6048 && width == 6048) {
+    width -= 24;
+  }
   if(!strncmp(make, "Panasonic", 9) && !strncmp(model, "DMC-LX100",9))
 	adobe_coeff (make, model);
   if(!strncmp(make, "Samsung", 7) && !strncmp(model, "GX20",4))

```

Edit: I just updated the patch

**Comment by Thanatomanic** [comment]
I'm not an expert here, but wouldn't it be more convenient to put this kind of modification in `camconst`?

**Comment by Beep6581** [comment]
@Thanatomanic as far as I know, camconst doesn't differentiate between raw formats, and this is only an issue for DNG.

**Comment by heckflosse** [comment]
@Thanatomanic you're right. We can remove the -= 24 for arw and dng for this camera from dcraw code and define the raw crop in camconst.json because in this special case camconst does not have to differentiate between dng and arw.

**Comment by heckflosse** [comment]
@Beep6581 @Thanatomanic Here's an alternative patch:

```diff
diff --git a/rtengine/camconst.json b/rtengine/camconst.json
index fd7b4bf0f..13b0117da 100644
--- a/rtengine/camconst.json
+++ b/rtengine/camconst.json
@@ -2319,6 +2319,7 @@ Camera constants:
 
     { // Quality A
         "make_model": "Sony ILCE-7M2",
+        "raw_crop": [ 0, 0, 6024, 4024 ],
         "dcraw_matrix": [ 5271,-712,-347,-6153,13653,2763,-1601,2366,7242 ], // DNGv8.7.1
         "ranges": { "black": 512, "white": 16300 }
     },
diff --git a/rtengine/dcraw.cc b/rtengine/dcraw.cc
index d302eb425..a315efe7b 100644
--- a/rtengine/dcraw.cc
+++ b/rtengine/dcraw.cc
@@ -9874,7 +9874,7 @@ konica_400z:
     width -= height > 3664 ? 8 : 32;
     if (!strncmp(model,"DSC",3))
       black = 200 << (tiff_bps - 12);
-  } else if (!strcmp(make,"Sony") && raw_width == 6048) {
+  } else if (!strcmp(make,"Sony") && strcmp(model,"ILCE-7M2") && raw_width == 6048) {
     width -= 24;
     if (strstr(model,"RX1") || strstr(model,"A99"))
       width -= 6;

```

**Comment by Beep6581** [comment]
@heckflosse fix confirmed, thank you!
