### ISSUE TITLE
macos builds are not signed by an identified developer

### ISSUE THREAD

**Issue by phillipao** [Beep6581/RawTherapee#4592]
Version: 5.4
OS: macOS 10.13.4 High Sierra

Description:
I downloaded 5.4 from http://rawtherapee.com/releases_head/mac/RawTherapee_OSX_10.9_64_5.4.zip and attempted to run the app from the included dmg. My Gatekeeper settings allow only apps from the store or from identified developers. When trying to run RawTherapee, Gatekeeper blocked the app, saying '"RawTherapee" can't be opened because it is from an unidentified developer'.

I'm sure this only affects a small set of potential users with restrictive security settings, but speaking as one of them, it would be great to be able to use RawTherapee :)

**Comment by phillipao** [comment]
I don't know if the Developer Program fee is an issue (I'm guessing yes). If so, it's possible to get a fee waiver: https://developer.apple.com/support/membership-fee-waiver/. It would require registered nonprofit status in the US. Just a few yaks to shave :)

**Comment by phillipao** [comment]
Just realized this can also be worked around by going to Security & Privacy settings. There's a notification there that RawTherapee was blocked, and there's an option to open it anyway. Very hidden, but doable.

**Comment by Beep6581** [comment]
We won't be bending over backwards for Apple.

**Comment by patdavid** [comment]
Just as a small reference, Apple does document how to change the setting globally, as well as a per-app basis:

https://support.apple.com/en-us/HT202491

**Comment by Beep6581** [comment]
Thanks @patdavid , we should link to that on our website.

**Comment by phillipao** [comment]
Yeah, shame about the fee. Seems like a reasonable security feature except
for that.

**Comment by Benitoite** [comment]
Normally what I do is open the app by right clicking the app and selecting Open, and then click Open in the dialog. I don’t know if that gets you by any “gatekeeper”.  

Last I heard the fee was 99 bucks a year, and I’m sure it’s gone up? I haven’t checked recently.

**Comment by Beep6581** [comment]
The macOS 10.9-10.12 download page already linked to https://support.apple.com/kb/PH25088
Now it links to both.

![screenshot_20180611_153609](https://user-images.githubusercontent.com/5844619/41234697-3063c0d0-6d8d-11e8-92e5-d8cf14c74fb0.png)
