### ISSUE TITLE
Panasonic DMC-G8 profile missing

### ISSUE THREAD

**Issue by ff2000** [Beep6581/RawTherapee#4596]
I recently found out about the camera model aliases and that it contains an alias for my G81. But there seems to be no profile for the DMC-G8 (which the G81 is an alias for).
Has the profile been missed (not added) when committing or does that alias file just list all know aliases irrespective their support in RawTherapee?

**Comment by iliasg** [comment]
Do you mean a dcp profile ?. RT crew need samples of color targets to build dedicated color profiles ..
http://rawpedia.rawtherapee.com/How_to_create_DCP_color_profiles

**Comment by ff2000** [comment]
Yes, that's what I meant. I know that you need samples and if I had an appropriate lighting + colorchecker I would create them.
I opened this issue because I was confused to find the camera in the aliases file as there is no dcp profile. I know it's easy to forget to "git add" a file.

So there is no dcp file? I think this issue can get closed then.

**Comment by Beep6581** [comment]
The aliases are there because we know of their existence, but we don't have color target shots for most of them.
