### ISSUE TITLE
Simplify local adjustments

### ISSUE THREAD

**Issue by ff2000** [Beep6581/RawTherapee#4598]
The current way is to edit the photo, add it to the queue, edit again for one local adjustment, add it to the queue, second local adjustment, and so on. Then (after converting) open them in (e.g.) gimp as layers and merge them.

I see two options:
1) Implement it using masks. This probably requires a lot of work. But it could be really useful as you can see how local adjustments change the look of the entire photo.
2) Something like "virtual copies" of images. Can be done via symlinks but IMO it's easier if such an option is offered in RawTherapee. Also this would require an action "open as layers in gimp" (which I couldn't find, so I assume it doesn't exist, yet).

Of course it would be awesome if both options were implemented, but for the start 2) would be enough to simplify and speed up editing.

**Comment by Beep6581** [comment]
We are aware of the situation, and it is addressed in other issues, pending on an engine redesign.

**Comment by strogonoff** [comment]
Persistent snapshots could also work, as far as I’m concerned…

([Judging by the docs](https://rawpedia.rawtherapee.com/Editor#Snapshots), I suppose the eventual idea might be to have persistent history as well—IMO snapshots could be more than enough, but that’s just me.)
