### ISSUE TITLE
refined noise reduction (for amaze+vng4)

### ISSUE THREAD

**Issue by ff2000** [Beep6581/RawTherapee#4599]
The amaze+vng4 and especially the contrast threshold in sharpening and microcontrast tools make a real difference for me. Thx alot again!

On top of that it would be great if it was possible to apply different noise reduction for the parts demosaiced with amaze and vng4 so that flat areas can be further cleaned up from noise without removing too much detail from the other parts.

But probably it's easier to also use an approach with a contrast thresholdwith different settings for below and above it.

**Comment by Beep6581** [comment]
The tool already has support for separately attenuating the action of luminance and chrominance noise reduction based on luminance, isn't that enough?

**Comment by heckflosse** [comment]
A contrast threshold to restrict the median in denoise to flat areas could be interesting

**Comment by ff2000** [comment]
If that means no noise reduction at all for non-flat regions it wouldn't be that useful, if it means luminance=0 it could be fine.
For example here:
https://www.dropbox.com/s/rpmf9ig9kjhrfi6/_1110099.RW2?dl=0
The feathers in the face are fine with NR luminance at 0 - but it still needs NR. The background is fine at about 25 (and detail at 0, obviously).

**Comment by heckflosse** [comment]
Well, it would mean what I wrote above: Restrict the median part of NR (have a look at the lower part of the NR tool) to flat regions controlled by a contrast threshold adjuster. That would allow to smooth flat regions using the median without affecting regions with details.

**Comment by ff2000** [comment]
Thx for the clarification. I forgot about the median filter as I never liked its output. As soon as it really smooths out flat regions it starts to create "banding"/hard edges/color blobs and looks like water painting (on images that really need stronger NR). I've played a lot with it now and for noisy images I most of the time just like the "grain" of pure NR more than the median filter, even with 3x3 window.
But probably it just needs some improvements. (Is it possible to add different blur implementations?)

Nevertheless having a contrast threshold there could be an improvement.

Two files I played with:
https://www.dropbox.com/s/wjtr9fq8q38nbep/_1120720.RW2?dl=0
(slightly misfocused) The OOF-areas show hard contrast, probably makes it difficult for median filter.

https://www.dropbox.com/s/166jl22z71act58/_1120659.RW2?dl=0
pp3: https://www.dropbox.com/s/qm0m91okexb6j6h/_1120659.RW2.pp3?dl=0
The trunk right of the bird shows "banding" (don't know if this is the right term) in the transition area to the brighter sand below it.

**Comment by Beep6581** [comment]
> the median filter (...) But probably it just needs some improvements. (Is it possible to add different blur implementations?)

It's not a blur, it's a median.
https://en.wikipedia.org/wiki/Median_filter

**Comment by Beep6581** [comment]
This issue requested being able to use different noise reduction settings for the AMaZE and for the VNG4 parts of an image when using AMaZE+VNG4. That is not possible in the current pipeline, so I am closing this issue.

The idea of using a contrast threshold for the median filter is interesting, but it's an entirely different thing than what was requested here, so as discussed with Ingo in IRC that idea might go into a new issue (though Ingo reports that current tests show poor results for window sizes >= 5x5).
