### ISSUE TITLE
Some fixes for French language

### ISSUE THREAD

**Issue by lebarhon** [Beep6581/RawTherapee#4603]
If you are filing a bug report, please first read the guide How to Write Useful Bug Reports:
http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports
You must provide the required information in order for your bug report to be valid.
Delete this text before posting.

**Comment by lebarhon** [comment]
Hi,
[RTFrancais.txt](https://github.com/Beep6581/RawTherapee/files/2096886/RTFrancais.txt)
Here are some fixes for the TP_DIRPYRDENOISE part.

**Comment by Beep6581** [comment]
@lebarhon good work. 
As always, you will find the latest `Francais` and `default` in https://github.com/Beep6581/RawTherapee/tree/dev/rtdata/languages
