### ISSUE TITLE
Slider operation issues

### ISSUE THREAD

**Issue by ff2000** [Beep6581/RawTherapee#4615]
Sliders behave weird for me: Click on the button and slide it right/left quickly works fine. As soon as I try to slowly adjust the value it seems to fall into a "precision mode" where I have to drag the mouse further for less change. This has a bad side effect: often the button jumps back resulting in a big change of the value (in the opposite direction I actually operate it). This gets even more difficult when I watch the photo for changes while slowly operating the slider.

**Comment by Beep6581** [comment]
This is a GTK+ 3 feature, not a RT one. All GTK3 programs behave like that. Hit the Shift key to go in or out of precision mode.

**Comment by TooWaBoo** [comment]
The fine-tune mode can be entered by clicking and holding the slider knob for 2 seconds (the trough becomes thick) and then move the knob.
