### ISSUE TITLE
Float value input box: +/- should operate on integer and fractional part

### ISSUE THREAD

**Issue by ff2000** [Beep6581/RawTherapee#4616]
Input boxes for float values (e.g. the one for Luminance in noise reduction) are really slow to operate with the +/- buttons making them basically unusable. With the new Sharpening Contrast Mask Preview you can watch how you can click on +/- without getting any change.

It would be really great to just place the cursor right (fractional part) or left (integer part of the floating number) of the decimal separator and +/- would operate on that part making it possible to get quick large steps but also small ones.

**Comment by Thanatomanic** [comment]
Personally, I would find that really annoying, because I have to worry about where my cursor is.
Alternatively, Ctrl or Alt click on the +/- could make the stepsize bigger. This could also be compatible when people use the arrow keys to increment the slider.

**Comment by Beep6581** [comment]
SpinButton behavior is governed by GTK3 not by RT.

**Comment by ff2000** [comment]
It would already help a lot if the increment step was set appropriately. E.g. for Luminance 1.0 or 0.5 would be good IMO (0.01 really is hardcore ;)). Didn't look at other spin boxes but there are several that deserve higher increment steps.

**Comment by Thanatomanic** [comment]
If I look in the gtk documentation, there seems to be an option to have two events to increment the value.
https://developer.gnome.org/gtk3/stable/GtkSpinButton.html

Could something be done with gtk_spin_button_set_increments () ?

**Comment by heckflosse** [comment]
Currently when holding Ctrl while using the arrow keys or when using PgUp/PgDwn keys RT uses a doubled increment.
https://github.com/Beep6581/RawTherapee/blob/dev/rtgui/adjuster.cc#L329
We can at least discuss about changing this value ;-)

**Comment by ff2000** [comment]
2018-06-15 18:56 GMT+03:00 Ingo Weyrich <notifications@github.com>:

> Currently when holding Ctrl while using the arrow keys or when using
> PgUp/PgDwn keys RT uses a doubled increment.
> https://github.com/Beep6581/RawTherapee/blob/dev/rtgui/adjuster.cc#L329
>
Thx for the reference! Though it's the constructor that is used in all
places.

>
> We can at least discuss about changing this value ;-)
>
OK. Though I think that for the mentioned Luminance (LumDetail is the same)
even 0.01*x with a universally applicable x is too slow ;)

IMO if someone needs that extra precision it's still possible to enter
custom values.

**Comment by Beep6581** [comment]
All RT SpinButtons could use a review regarding their step and page increments.

When I press + or - I would like to see a difference in the image. If I want fractions, I type those. Currently, pressing + or - in most SpinBoxes is next to useless.

Noise Reduction - Luminance would be entirely fine for me with a step of 1 and page of 10.

But what we're discussing now is entirely not what this issue is about, which will make finding this in the future difficult. Please open a new issue for reviewing all RT SpinButtons if you're offering to do the work.

This issue requests something which is not possible in GTK3 (well, not possible reasonably easily, and we're not exactly overflowing with bored GTK3 developers), so I'm closing it. Of course feel free to re-open it if there's a patch.

**Comment by ff2000** [comment]
Sorry that I don't have any experience with GTK, otherwise this would have been more to the point and requested something that's possible.

@heckflosse I nevertheless wanted to offer a different approach: What about this:

```
    spin->set_digits (digits);
    // from vmin to vmax in 100 steps when holding CTRL
    const int quickstep = (vmax - vmin) / 100;
    spin->set_increments (vstep, quickstep);
```

**Comment by ff2000** [comment]
2018-06-15 19:15 GMT+03:00 Beep6581 <notifications@github.com>:

> Please open a new issue for reviewing all RT SpinButtons if you're
> offering to do the work.
>

I could try to find some better values for the tools I use but I don't know
if those values will fit for every camera out there.
I simply lack the knowledge of what happens behind the scene and I think
that will be needed.

Talking about Luminance I even think an integer as input would be accurate
enough, max. 1 digit. Same for Detail. There were other places I came
across too much accuracy.
I think those should be addressed as well - but I am sure you won't like
the values I come up with :(

**Comment by Beep6581** [comment]
@ff2000 I like the `/100` idea.
Issue opened #4617

**Comment by heckflosse** [comment]
I also like the `/100` idea, but we have sliders which allow only integer values between 0 and 3 for example.
For this cases we have to refine the calculation.
