### ISSUE TITLE
Speedup for VNG4 demosaic

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#4633]
Because VNG4 demosaic gets used more often now as AMaZE+VNG4 is available I will try to make it a bit faster. Don't expect too much. First small improvments will follow at the weekend.

**Comment by heckflosse** [comment]
It's weekend. I will push some speedups.
I test using a 24 MP ARW file on an AMD FX8350
Processing times as usual measured in queue by taking the median of 7 measures.

Before changes: 1000 ms

**Comment by heckflosse** [comment]
d53e44d
Processing time: 960 ms

**Comment by heckflosse** [comment]
c44b8ca
Processing time: 880 ms

**Comment by Thanatomanic** [comment]
Fun to follow you work on this :smiley:

**Comment by heckflosse** [comment]
1b291ae
Processing time: 860 ms
Now I'm out of ideas, at least for today...

**Comment by heckflosse** [comment]
I will pr this now. If further speedups are possible, we can do them for 5.6

In case of interest:
[Here](https://github.com/Beep6581/RawTherapee/blob/vng4-speedup/rtengine/vng4_demosaic_RT.cc#L237) is one hotspot

**Comment by Floessie** [comment]
@heckflosse
> Here is one hotspot

I've no quick idea, but the double indexing could be a problem. Maybe the data layout isn't very cache friendly. Did you have a look at the assembly?

**Comment by heckflosse** [comment]
13abcd0
Processing time: 845 ms

**Comment by heckflosse** [comment]
894fb8d
Processing time: 800 ms

**Comment by heckflosse** [comment]
@Floessie Do you know a less restrictive compile time (preprocessor) switch for this than __SSE2__ ?

https://github.com/Beep6581/RawTherapee/blob/dev/rtengine/vng4_demosaic_RT.cc#L247

Edit: I need a compile time switch which tells about being sizeof(float) = 32bit

**Comment by Floessie** [comment]
@heckflosse How about [`__STDC_IEC_559__`](https://stackoverflow.com/a/21408489)? My GCC 6.3 at least sets this.

**Comment by heckflosse** [comment]
@Floessie That was my first try, but my msys2/gcc 8.x didn't set it :(

**Comment by Floessie** [comment]
@heckflosse :facepalm: Then we need a CMake check...

**Comment by heckflosse** [comment]
@Floessie :+1: for the CMake check. Though there should be no hurry as my __SSE2__ check should be ok atm
