### ISSUE TITLE
Artifacts appears sometime when using Highlight reconstruction Colour propagation together with the combined xtrans demosaicers

### ISSUE THREAD

**Issue by casta** [Beep6581/RawTherapee#4639]
I just encountered a display intermittent bug with dual X-Trans demosaicer (both 1-pass + fast and 3-pass + fast).
It happens when moving the contrast slider, but is intermittent. For the same contrast value it sometimes appears, and sometime disappears, so it sounds like some race condition.

See screenshot.
![rt-1pass fast-bug](https://user-images.githubusercontent.com/835444/41836261-7cc53210-785a-11e8-84d1-d9d655d1d8dc.png)

I can provide the raf file + pp3, but only privately (I do not want my son published all around internet).

Thank’s for all your work !!

**Comment by Beep6581** [comment]
@casta it looks like the red parts appear in areas with clipping, so please photograph or find a similar raw file where you can reproduce the problem and upload a sample raw file + PP3 using https://filebin.net/
and provide the missing info (complete version information): http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports

**Comment by heckflosse** [comment]
@casta If you can't provide the raw file, please attach at least the pp3 file (just add a .txt suffix to attach it here)

**Comment by casta** [comment]
PP3 is here: https://cloud.xwing.info/s/o7m28EZ3T3Yt6qc
I send you a link privatlely with the raf file through your forum account

Of course, this was tested with last master

**Comment by casta** [comment]
By the way, the running configuration:

Version: 5.4-432-gae9ea3d3
Branch: dev
Commit: ae9ea3d3
Commit date: 2018-06-25
Compiler: x86_64-pc-linux-gnu-gcc 7.3.0
Processor: Intel(R)\ Core(TM)\ i7-4790\ CPU\ @\ 3.60GHz
System: Linux
Bit depth: 64 bits
Gtkmm: V3.22.2
Lensfun: V0.3.2.0
Build type: Gentoo
Build flags: -march=native -O3 -mtune=native -pipe -std=c++11  -Werror=unused-label -flto -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations  -ftree-vectorize
Link flags: -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -Wl,--sort-common  -flto
OpenMP support: yes
MMAP support: ON

**Comment by heckflosse** [comment]
It turned out that this is a bug in highlight reconstruction colour propagation. Still searching...

**Comment by heckflosse** [comment]
I don't think it's an openmp race because my usual test (process the same image 5 times in a row and check for differences) shows no differences and also because the symptomatic (error is reproducible on linux but not on windows) is a hint for access to uninitialized memory.

**Comment by sguyader** [comment]
I haven't encountered this with any of my images, despite using Color propagation often (X-T2, Linux Manjaro)

**Comment by casta** [comment]
Yes, me too, color propagation is my default highlight recovering method and I never encountered this… until I played with the dual demosaicers, that triggers the case.
We saw that with Ingo this afternoon, fast demosaicing / contrast threashold change triggers it.

**Comment by heckflosse** [comment]
It's really hard to trigger. Sometimes I need more than 20 tries.

**Comment by heckflosse** [comment]
It can also be triggered without changing contrast threshold just by quickly switching between two demosaicers very often. Quickly switching between fast and 1-pass can trigger it.
Slowly switching between demosaicers I didn't manage to trigger it.

**Comment by heckflosse** [comment]
I turned out, that in the combined xtrans demosaicers the 1 pix border of the fast demsaic version was not set, which led to access to uninitialized memory.

**Comment by casta** [comment]
Great !!
I cannot reproduce anymore with your fix

Thanks
