### ISSUE TITLE
Resolution Smaller Than Source RAW File

### ISSUE THREAD

**Issue by jedypod** [Beep6581/RawTherapee#4642]
Greetings! 
I have a raw dng file that is 1920x1080. I can decode this raw file at this resolution in Darktable, Krita, Digikam, and even dcraw commandline, but in RawTherapee it decodes at 1912x1072, with 4 pixels cropped on each side. I understand why this is done: to keep the best demoisaic quality over the entire frame. 

With a high resolution still image, this cropping is usually fine. However, when dealing with lower resolution raw video, these 8 missing pixels can be quite significant.

Doing a bit of research on the other issues posted here, it has been a request that has recurred a few times: 
https://github.com/Beep6581/RawTherapee/issues/2339
https://github.com/Beep6581/RawTherapee/issues/4197
https://github.com/Beep6581/RawTherapee/issues/2698
https://discuss.pixls.us/t/rawtherapee-different-image-size/4285
https://discuss.pixls.us/t/raw-image-resolution-size-bug/2662/2

I would like to make a feauture request to make this cropping behavior optional, for cases like lower resolution raw files.

I would really like to use RawTherapee for raw video debayer, because I find it's demoisaic options and algorithms to be superior to the other linux options, however the reduction in resolution is a deal-breaker for my specific use case.

I have included a 1920x1080 raw dng file for testing if it is helpful.

[M24-1221_000202.dng.tar.gz](https://github.com/Beep6581/RawTherapee/files/2135105/M24-1221_000202.dng.tar.gz)

Thanks for your consideration!

**Comment by Beep6581** [comment]
@jedypod hi, could you please upload the DNG file (not zipped) to RPU?
https://raw.pixls.us/

**Comment by heckflosse** [comment]
I will see what I can do...

**Comment by heckflosse** [comment]
@jedypod I created `fullraw` branch, which should solve the issue. There maybe some side effects which need to be solved. Please test...

**Comment by heckflosse** [comment]
Currently 0pix border works only for bayer files.
Is that needed also for xtrans files?

**Comment by jedypod** [comment]
Thank you!

I've uploaded the DNG file to the raw archive that @Beep6581 linked to above. 
- The DNG is sourced from a Canon 5D mk3, and was recorded using Magic Lantern in 12 bit lossless compression mode. The DNG was converted from MLV format into DNG using mlvfs and then re-converted into a lossless compressed DNG file using digikam. 

I pulled the latest from git, recompiled from the `remotes/origin/fullraw` branch. I tested with gui and commandline and am still getting the same resolution as before. I'm not sure if I'm messing up something. Is there any preference I need to enable to change the behavior or any other thing I need to do? I'll try to test some more when I have time tomorrow.

Thanks for your help! This is promising.

**Comment by heckflosse** [comment]
@jedypod 
![grafik](https://user-images.githubusercontent.com/13733487/42025674-723bb838-7ac5-11e8-9f4a-790dfb757fe8.png)

**Comment by heckflosse** [comment]
@jedypod There is a bug in full processing (queue/saveas) which leads to old behaviour (4pix border). I will fix that...

**Comment by heckflosse** [comment]
@jedypod The above mentioned bug is fixed now

**Comment by jedypod** [comment]
Thanks @heckflosse - I have successfully compiled the latest git branch and it is working very well! I have successfully tested this added functionality pretty extensively and haven't seen any other bugs yet.

I'll keep testing and report back here if I find anything. 

Thank you! This is why I love the open source community :)

**Comment by heckflosse** [comment]
@jedypod Thanks for testing :+1:
