### ISSUE TITLE
Resize should not automatically upscale

### ISSUE THREAD

**Issue by Thanatomanic** [Beep6581/RawTherapee#4643]
Currently, if you have the `Resize` module enabled and export an image with dimensions lower than those set in the module, the image is upscaled. It would be convenient to disable this behavior by default, instead of having to disable the module for images that have been cropped more than others.

**Comment by Hombre57** [comment]
A combobox with those entries should be added I guess : `Downscale only`, `Upscale only` (who will use this ?), `Upscale and downscale` ?

**Comment by Beep6581** [comment]
I agree.
My opinion is that a "Downscale only" checkbox should be enough.

**Comment by Thanatomanic** [comment]
Awesome @agriggio! I'll do some testing.

**Comment by Thanatomanic** [comment]
This is now nicely implemented by @agriggio, but there is some discussion in the last commit regarding backwards compatibility and having the checkbox on/off by default. @Beep6581 @heckflosse, if you read my arguments, would you still consider that backwards compatibility should not be broken here?

**Comment by Beep6581** [comment]
I agree that backward compatibility should be preserved where possible.

@Thanatomanic just above you wrote,

> if you read my arguments, would you still consider that backwards compatibility should **not** be broken here?

but in the PR you argued that it does make sense to do something which will change the behavior when reading old files arguing that the previous behavior was unwanted,

> I would very much prefer that upscaling is set to false for previous versions. In my mind this should have always been the correct behavior (and upscaling should be regarded as a bug, not a feature).

I suppose you meant "would you still consider that backwards compatibility **should** be broken here?"

Disclaimer: this doesn't affect me at all, and I wouldn't be surprised if I could count the number of people with a vested interest in this on one finger ;)

**Comment by Thanatomanic** [comment]
It was early in the morning  :sleeping:  Yes, I meant to say *should* be broken. I still think that wouldn't hurt too many people, if anyone.

**Comment by Beep6581** [comment]
I would assume that people who encountered unwanted upscaling in the past already edited their PP3s to prevent it from happening, so by preserving the old behavior with old PP3s things are still good. I'm curious, why is this still an issue for you, what is the scenario?

**Comment by Thanatomanic** [comment]
Am I correct to assume that when an old pp3 is loaded where the upscaling setting is not present, the default value will be added?

Let's consider a user in the old situation and assume that for general photo editing, upscaling upon export is undesirable.
I think it's reasonable to consider that the user uses Resize by default for export, e.g. to max. 3000x3000 pixels. The problem occurs that when Crop gets enabled (for whatever reason), the user now needs to pay attention to the crop size and then decide to disable Resize to prevent upscaling. I think this kind of cross-checking shouldn't be necessary.
If you forget to check for Crop/Resize conflicts in RT and happen do some quality check on your output, then accidental upscaling is easy to detect for an extreme crop, but much harder if you'd cropped to only 2950 pixels or something.

Our user is of course smart. He learned that he needs to check in RT, so he has disabled Resize on images where there is too much cropping going on. Suddenly an "Allow upscaling" button appears. Two options:

- **Checked**. Our user has no problems with old images, because he has disabled Resize on them anyway. Though, for new images he always needs to uncheck this box (and/or update his default profiles) in order to not think about the Resize/Crop interplay again.
- **Unchecked**. Our user has no problems with old images, because he has disabled Resize on them anyway. And good news, he doesn't need to do anything special for the future anymore, because upscaling doesn't happen anymore by default. No more keeping an eye on his Crop and Resize values. And a minor bonus: in the off chance that he forgot to disable Resize so for some old cropped images, they will now no longer incorrectly upscale if they get exported again.

This is the best I can come up with why I think having unchecked as the default has way more benefits than having it checked. 

The only users I can think of that are negatively affected from having the default being unchecked are those that deliberately want to upscale their images. And even then it's only an issue when they want to export them again. If you think that actually concerns a large number of users, then I will rest my case.

**Comment by Beep6581** [comment]
Agreed, preserving the old behavior (I don't want to use the term "preserve compatibility") for the sake of preserving the old behavior seems counter-productive here. @agriggio already agreed. @heckflosse ?

**Comment by heckflosse** [comment]
Status?

**Comment by Beep6581** [comment]
I documented this today, including the automatic enabling of "avoid upscale" for old PP3s, even though I don't think that's been coded yet.
http://rawpedia.rawtherapee.com/Resize
