### ISSUE TITLE
Bug? - RT Lab setting is ignored when PP3 loaded

### ISSUE THREAD

**Issue by RawConvert** [Beep6581/RawTherapee#4644]
This is with RT 5.4.412 built 17 June.
You open the raw file, then load a .pp3 previously created when you saved as a jpeg, but RT ignores a Lab setting which is an LH change via Equalizer.  The .pp3 contains an L custom curve also.  So when you click the down arrow for LH, and click Equalizer, the preview changes (darkens), correctly reflecting the LH setting whose curve you now see.  This consistently happens with the files uploaded, but does not happen with another raw file I tried.  Also, the act of clicking Equalizer creates an LH entry in History, so that's consistent with the preview changing I suppose, but the point is it was already in the .pp3.

The raw and pp3 are here - https://filebin.net/vveonznyakm1wgp8
For data privacy, please try to avoid keeping permanent copies of the raw file, just let filebin expire it in 2 months.

Build details - 
Commit: b626b4e   
Commit date: 2018-06-17
Compiler: cc 5.4.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.18.0
Lensfun: V0.2.8.0
Build type: release
Build flags:  -std=c++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -O3 -DNDEBUG -ftree-vectorize
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON

**Comment by heckflosse** [comment]
@RawConvert In your pp3 there is no modified LH curve:
```
[Luminance Curve]
Enabled=true
Brightness=0
Contrast=0
Chromaticity=0
AvoidColorShift=false
RedAndSkinTonesProtection=0
LCredsk=false
LCurve=1;0;0;0.48663101604278086;0.51871657754010692;1;1;
aCurve=0;
bCurve=0;
ccCurve=0;
chCurve=0;
lhCurve=0;
hhCurve=0;
LcCurve=0;
ClCurve=0;
```

**Comment by RawConvert** [comment]
Apologies, I must have been confused, doh.  It's that thing where the curve is retained from the previous Raw.  I thought I had output a revised jpeg, but it looks like I hadn't...  Have just re-output and now the LH is ok.  (Although it still puts an item in History even though all you've done is click on LH to see the curve displayed - but you haven't changed anything...)

**Comment by heckflosse** [comment]
@RawConvert 
>Although it still puts an item in History even though all you've done is click on LH to see the curve displayed - but you haven't changed anything...

You changed the curve mode from `Linear` to `Equalizer`

**Comment by RawConvert** [comment]
No!  I'm loading a jpg.out pp3 which has the eq curve in it - not the one I uploaded above but today's freshly output one.  So when it loads, the LH button is showing the curve icon, not the linear icon.  So the eq is being applied as soon as it's loaded, which is correct, and which is confirmed by the preview not changing when I select Eq (to show the curve).  So I'd say the history entry is incorrect, not needed.  But I also accept this is not a major issue!

**Comment by RawConvert** [comment]
P.S. I see that if you click the LH **button** in order to show the curve, then there's no history added, but there is if you do it via the dropdown (even though it's already on Eq)...

**Comment by heckflosse** [comment]
@RawConvert 
>I see that if you click the LH button in order to show the curve, then there's no history added, but there is if you do it via the dropdown (even though it's already on Eq)...

confirmed

**Comment by Beep6581** [comment]
Invalid.

**Comment by RawConvert** [comment]
Invalid?

**Comment by Beep6581** [comment]
RT Lab setting is not ignored when PP3 loaded.
