### ISSUE TITLE
Automatically crop based on aspect ratio in metadata

### ISSUE THREAD

**Issue by tsi12** [Beep6581/RawTherapee#4649]
As known, latest models of panasonic cameras (GX-80 in my case) produce raw image file of entire sensor area (ratio 4:3) regardless of aspect ratio setting in camera menu. Some raw convertors like silkypix can read some tag and crop image as noted in menu. Is it possible to implement that in RT?

**Comment by heckflosse** [comment]
I'm not against this. But there are more important things to do at the moment imho.

**Comment by Thanatomanic** [comment]
A slightly newer issue explains this request more thoroughly: https://github.com/Beep6581/RawTherapee/issues/4982
