### ISSUE TITLE
Brushes

### ISSUE THREAD

**Issue by HowardBiel** [Beep6581/RawTherapee#4651]
Brushes should be implemented

**Comment by Thanatomanic** [comment]
Can you elaborate? What do you want to do with a brush?

**Comment by agriggio** [comment]
someone should pay for them

**Comment by heckflosse** [comment]
@HowardBiel 
> Brushes should be implemented

`should be implemented` is not how FOSS works.

I guess you meant `implementing brushes in near future would be nice` ;-)
