### ISSUE TITLE
Filmstrip height not high enough after latest dev

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#4655]
I guess this issue belongs to the Filebrowser scroll changes from last update.

![grafik](https://user-images.githubusercontent.com/13800920/42138041-3234bcf8-7d77-11e8-8d50-610f113e2cbd.png)

```
Version: 5.4-460-g8a9f102c
Branch: dev
Commit: 8a9f102c
Commit date: 2018-07-01
Compiler: gcc 7.3.0
Processor: undefined
System: Windows
Bit depth: 64 bits
Gtkmm: V3.22.0
Lensfun: V0.3.2.0
Build type: release
Build flags: -mwin32 -m64 -mthreads -msse2 -std=c++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -Wno-aggressive-loop-optimizations -DNDEBUG -O3 -ftree-vectorize
Link flags: -m64 -mthreads -static-libgcc -march=native -s -O3
OpenMP support: ON
MMAP support: ON
```
ping @Thanatomanic

**Comment by Thanatomanic** [comment]
Could you post a screenshot of your General preferences? When does this happen, immediately after startup and opening an image?

**Comment by TooWaBoo** [comment]
It's immediately after startup.

![grafik](https://user-images.githubusercontent.com/13800920/42138118-87cde8aa-7d78-11e8-9329-68408e2a9f6e.png)

**Comment by Thanatomanic** [comment]
Unfortunately I cannot reproduce...

Immediately after opening:
![image](https://user-images.githubusercontent.com/6567747/42138260-ec435480-7d7a-11e8-8f72-6259de7bb977.png)
My settings:
![image](https://user-images.githubusercontent.com/6567747/42138264-f660b25a-7d7a-11e8-8ecc-55045f79c26a.png)

Could it be due to the theme you're using?

**Comment by TooWaBoo** [comment]
It's theme independend. I also changed the thumbnail height. It's always the same.

**Comment by Thanatomanic** [comment]
Maybe it's OS dependent? DPI dependent?
I run Win 7, you seem to be on Win 10.

**Comment by heckflosse** [comment]
I investigate as well atm

**Comment by TooWaBoo** [comment]
I've removed the code below from thumbbrowserbase.cc and this fixed it.
Line 522
```
 else { // hide scrollbars when a filter is applied which returns no files
        hscroll.hide();
        vscroll.hide();
    }
```

**Comment by heckflosse** [comment]
@TooWaBoo 

seems to be my fault :(((

**Comment by heckflosse** [comment]
I should concentrate on rt engine instead of doing side steps on gui.....

**Comment by heckflosse** [comment]
That's not funny :laughing:

**Comment by heckflosse** [comment]
@Thanatomanic feel free to fix my mistakes...

**Comment by TooWaBoo** [comment]
@heckflosse 
It's funny (for me). 😇

**Comment by heckflosse** [comment]
LOL

**Comment by Thanatomanic** [comment]
@heckflosse, can you simply revert commit `cccfb02`?
