### ISSUE TITLE
Minor request: make icons more in line with their meaning

### ISSUE THREAD

**Issue by Thanatomanic** [Beep6581/RawTherapee#4658]
So, this is really minor, but something I did not find intuitive. And since #4469 is being worked on, I'll ask anyway. Might I suggest a minor alteration to the following icons in the filebrowser?
![image](https://user-images.githubusercontent.com/6567747/42182495-a93b4624-7e3e-11e8-962e-a8726ed4926c.png)

While it is clear that a magnifying glass means inspection, and a red cross means something is not there (but now it's a double negative... not not deleted = kept), I don't think the pair of trash icons match well. I would expect opposite indicators for an opposite operation, e.g. a green tick and red cross.
The same goes for the 'show saved' and 'show unsaved' icons. Now one is vague and the other clear. This is somehow each other's opposite, but not very obvious. There a green tick and red cross would also be clearer.

**Comment by Beep6581** [comment]
@Thanatomanic I actually already changed those icons. I tweaked a few others as well, and they will all require review and some further tweaking. Let's do all that in #4469.
