### ISSUE TITLE
Problem with Msys2 and pacman

### ISSUE THREAD

**Issue by Desmis** [Beep6581/RawTherapee#4661]
To day I want to updatee Msys2
As others days  after call to msys2 and the shell windows is open
I run
$ pacman -Syu

and I have this message
error GPGME : moteur de chiffrement incorrect
etc.
I search on the web and found this link
https://github.com/Alexpux/MSYS2-packages/issues/393

I have tried some ideas, but nothing work...
What is the solution ?
Uninstall msys2, and re-install ??

Thank you

**Comment by heckflosse** [comment]
@Desmis Jacques
Can you try pacman -Syuu ?

**Comment by Desmis** [comment]
@heckflosse 

I have tried, same error message :)

**Comment by heckflosse** [comment]
Strange. I just did `pacman -Syuu` about half an hour ago without problems

**Comment by Thanatomanic** [comment]
Also no problem here (Win7)...

**Comment by Desmis** [comment]
Me also, I find that strange , but Mingw64 works and compile fine :)

I think, the best solution , because all is write in Alexpux/MSYS2-packages#393, is near Chineese for me, is to unistall all msys2 and reinstall afer
Is there a precaution to do that ??

In that case, I will uninstall tomorrow afternoon...and reinstall because it takes many many time !

**Comment by Desmis** [comment]
Or to preserve Mingw64 which works well, can I make a second installation of Msy2 in a second folder

Actually it is in Msys64
Is a second installation in a folder as Msys_64_ can works whitout problems ? Or is the best solution "uninstall" then "install" ?

**Comment by heckflosse** [comment]
@Desmis Just rename your current msys64 folder to msys64_old, then install from scratch into msys64 folder. If that does not work you can rename back to msys64.

**Comment by Desmis** [comment]
@heckflosse 
I will do that tomorrow !
But a question, why this strange problem....
Perhaps I have had a problem with an update of Firefox (ver 61)...my computer hangs...I need to uninstall Firefox, now I used Google Chrome ??

Thank you

Jacques

**Comment by TooWaBoo** [comment]
@Desmis 
Disable your Antivirus/Firewall and try again.

**Comment by Desmis** [comment]
I try, same problem
I rename Msys64 and reinstall
And I see during installation Avast put in quarantine "gpg-agent.exe"
I re-put this file in good place, same problem

I re-reinstall another time, with strictly apply Rawpedia
When I want to cmake, cmake says me "liiptcdta" not found
I re-re-re-Download and build libiptcdata

Then I re-cmake, always lipitcdta not found
At this stage, **nothing works at all**, including all Mys64old

I cannot compile anything
What I missed ?

**Comment by Desmis** [comment]
I think I will all uninstall, now nothing, nothing works...
I am very angry, annoyed and I do not understand anything

Of course, during installation, I have disabled "avast"

**Comment by Desmis** [comment]
And more , I cannot uninstall :)

**Comment by Desmis** [comment]
After, many many many many tries, many reboot, ..., Msys2 seems uninstall...
I will start again tonight, otherwise change computer ???

**Comment by Desmis** [comment]
Comment,I am angry against myself:)

**Comment by Desmis** [comment]
Of course it is only my fault.
I hope my «old» computet will works :)

**Comment by Desmis** [comment]
After clean register, clean all, etc.
Then re-install all
Now all works 
* Msys2 and pacman
* mingw64 compile and program runs fine

Big job, all because of antivirus, which quarantines a file without offering a choice (it happens when I update Msys2 with "pacman -Syuu"), I was not always in front of my computer and I did not see the message "avast"
:)

**Comment by TooWaBoo** [comment]
@Desmis 
Congratulation 😊

**Comment by Desmis** [comment]
@TooWaBoo 
Thank you

But a question, I don't recall how to config "git" with Windows to use "kdiff3" as mergetool

I know the command

git config --global merge.tool kdiff3
git config --global mergetool.kdiff3.cmd '"C:\\Program Files\\KDiff3\\kdiff3" $BASE $LOCAL $REMOTE -o $MERGED'

But how to do if I want it is always configure

Where is gitconfig ?
Thank you

**Comment by TooWaBoo** [comment]
I don't know. I'm using MSYS only for compiling.

**Comment by Beep6581** [comment]
> I don't recall how to config "git" with Windows to use "kdiff3" as mergetool

@Desmis see https://stackoverflow.com/questions/33308482/git-how-configure-kdiff3-as-merge-tool-and-diff-tool/33348841#33348841

> Where is gitconfig ?

```
git config --list --show-origin
```

**Comment by Desmis** [comment]
@Beep6581 
Thank you :)
