### ISSUE TITLE
Does not keep format when saving.

### ISSUE THREAD

**Issue by Tataute** [Beep6581/RawTherapee#4662]
I am using the following version (although I had the same problem with 5.2) : Version: 5.4
Branch: 5.4
Commit: a5e8eb9c8
Commit date: 2018-03-20
Compiler: gcc 7.3.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.22.0
Lensfun: V0.3.2.0
Build type: release
Build flags:  -m64 -mwin32 -mthreads -Wno-aggressive-loop-optimizations -std=c++11 -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations  -DNDEBUG  -O3
Link flags: -m64 -mthreads  -static-libgcc   -mtune=generic  -s -O3 -fno-use-linker-plugin
OpenMP support: ON
MMAP support: ON
Camera : FUJI XT-2
Problem : this is my first usage of RT - I have resized pictures which I then saved under a specific format (say JPeg 8bit, 100%, best quality or TIFF or whatever format), my savings are correct and JPeg files are about 20Mo except for one picture which always saves in a reduced format of about 300 Ko !!!
I have tried again several times without success.
Can you help?
Thanks

**Comment by Beep6581** [comment]
@Tataute user support is done via our forum:
https://discuss.pixls.us/c/software/rawtherapee

Open a new topic, and remember to include screenshots of the problem along with the PP3 file. A video recording would be ideal.
