### ISSUE TITLE
Support for Fuji X-T100

### ISSUE THREAD

**Issue by agriggio** [Beep6581/RawTherapee#4666]
RT only decodes a thin strip of the frame for the new X-T100 camera. It sets a raw crop of `0 0 2857 100`, regardless of what  I put in `camconst.json`. Example raw files are available on the web (e.g. dpreview)

**Comment by sguyader** [comment]
@agriggio you beat me on this. What seems strange to me is that the raw filed from the X-A5, which has the same sensor as the X-T100, open without problems.
I also noticed that sometimes, the presence of an X-T100 raw in a folder prevents the file browser to display the thumbnails of other raw files.

**Comment by heckflosse** [comment]
I just tried with three X-T100 files. All worked fine. Can you please submit files which show the issue

**Comment by iliasg** [comment]
I think,that after the commit of dcraw.c V928 changes all fuji files work fine ..

**Comment by heckflosse** [comment]
@iliasg Thanks for confirmation :+1:
