### ISSUE TITLE
Raw histogram review

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#4667]
Imho the raw histogram needs a review. I don't mean the gui part (this is already covered in a different issue), but the engine part, which collects the data for the raw histogram.
Have a look at this screenshot
![grafik](https://user-images.githubusercontent.com/13733487/42386520-0aa6648a-8140-11e8-848e-e57a93cd1ea3.png)
According to the raw histogram what would you expect to be the largest raw green value knowing that the white level of the image is 15500?
I would expect a value of ~10000
But it is ~6300

**Comment by heckflosse** [comment]
Here's a screenshot of a first mockup which comes closer to the real values
![grafik](https://user-images.githubusercontent.com/13733487/42387114-affdc4e0-8141-11e8-9537-28e34a182787.png)
The bottom right point of the green curve now is at (~6.5 / 16) * 15500 = ~6300

**Comment by Thanatomanic** [comment]
I would be in favor of a RAW histogram that has the effective black and white points as respective left and right boundaries.

**Comment by heckflosse** [comment]
@Thanatomanic 
That's the case in my mockup screenshot

**Comment by Thanatomanic** [comment]
And while we're at it: am I correct to assume the reason why RT doesn't simply show _all_ the values, but limits it to 256 bins, has to do with performance?

**Comment by heckflosse** [comment]
@Thanatomanic 
Do you mean the right boundary should be ~6300 in my example?
I don't think performance was a reason. But how would you show for example 16384 values on the screen?

**Comment by heckflosse** [comment]
@Thanatomanic How about returning the uncompressed raw histogram to the gui instead of the 8-bit compressed one? Then the gui code(r) can do whatever needed with the values

**Comment by Thanatomanic** [comment]
> @Thanatomanic How about returning the uncompressed raw histogram to the gui instead of the 8-bit compressed one? Then the gui code(r) can do whatever needed with the values

That would seem like a reasonable thing to do. But wouldn't it be even better if the gui asks the engine to provide a version that is binned based on the available room to draw? A histogram of 300px wide with 16384 points (or 65535 for a higher bit depth) seems a bit overkill :wink:

**Comment by heckflosse** [comment]
@Thanatomanic 
That would mean the gui has to call the engine each time the user changes the width of the histogram. If the engine simply provides the 16-bit histogram (maybe also white and black levels for future use) the gui get once provided with the values and don't have to ask each time.

Edit: iirc currently the gui can not even ask the engine for the histogram. It's the engine which calls the gui telling it `Here are the histogram values. Do whatever you want with them. I will throw my copy away now`

**Comment by Thanatomanic** [comment]
@heckflosse Fair enough. The current binning functionality should be transferred to the gui part in that case, since you will need some form of binning in any case.

Also, see #1598 for some older considerations on the RAW histogram.

**Comment by heckflosse** [comment]
@Thanatomanic :+1: for transferring the current binning functionality to the gui part.

**Comment by heckflosse** [comment]
Raw histogram for float dng files in 0..1 range is wrong. I'll fix that
Example:
![grafik](https://user-images.githubusercontent.com/13733487/42409313-dde17450-81d8-11e8-8432-c24f2d699c21.png)

**Comment by Beep6581** [comment]
For reference, here are raw histograms of the flat-field photo `D700_20160102_7318.NEF` and from [`amsterdam.pef`](http://rawtherapee.com/shared/test_images/amsterdam.pef):
https://filebin.net/1038667o8fiac86b

**Comment by heckflosse** [comment]
I just continued working on this issue.

I created `rawhistogram_fixes` branch. First commit removes the gamma from calculation of raw histogram values.

Here again my question from first post:
According to the raw histogram what would you expect to be the largest raw green value knowing that the white level of the image is 15500?
I would expect a value of ~10000
But it is ~6300

Before:
![grafik](https://user-images.githubusercontent.com/13733487/45898471-587e6a00-bdda-11e8-9358-0e54bfc1b7f5.png)

After:
![grafik](https://user-images.githubusercontent.com/13733487/45898690-038f2380-bddb-11e8-8ea2-b7379530c823.png)

**Comment by heckflosse** [comment]
Fixed wrong raw histogram for float dng files in [0.0;1.0] range. Example file:
http://www.rawtherapee.com/shared/test_images/hdrmerge_range_0-1.dng

Before
![grafik](https://user-images.githubusercontent.com/13733487/45915613-0714c000-be58-11e8-8ac2-740dc0041ac7.png)

After
![grafik](https://user-images.githubusercontent.com/13733487/45915625-3b887c00-be58-11e8-85d9-5b126da2f905.png)

**Comment by heckflosse** [comment]
Closing this as it's much better than before.
