### ISSUE TITLE
Old request revisited: proper reset button for Crop tool

### ISSUE THREAD

**Issue by Thanatomanic** [Beep6581/RawTherapee#4668]
I would like to revisit issue #382, but I'm unsure what the typical approach is: make a new issue like this, or post in the old issue?

In any case, I would like to propose to give the Crop tool a proper reset button, in addition to the current behavior. Virtually all tools have one, so it would only make sense to make this behavior uniform.

**Comment by Beep6581** [comment]
Old, imported issues look messy, so unless there is stuff of value in them, it's better to open a new, clean one.

Agreed, a reset button would be nice.

**Comment by Thanatomanic** [comment]
Done with https://github.com/Beep6581/RawTherapee/commit/c8300b137cb8aba10ec5b418bfe0110ff8ab3a3e
