### ISSUE TITLE
Floating point dng files in [0;1] range have black thumbnail

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#4669]
[Example file](http://rawtherapee.com/shared/test_images/hdrmerge_range_0-1.dng)

**Comment by Beep6581** [comment]
Fix confirmed.

Procedure:
1. Delete cache folder and *.pp3
2. Open unpatched RT. Check thumb.
3. Apply neutral. Check thumb.

Repeat for patched RT.

**Comment by heckflosse** [comment]
@Beep6581 Thanks for testing and confirming the fix :+1:

**Comment by heckflosse** [comment]
It also reduces the decoding time a bit when opening float dng files :)
