### ISSUE TITLE
[5.4-694 Linux x64] With HDR DNG, preview is way darker than processed output

### ISSUE THREAD

**Issue by FM33** [Beep6581/RawTherapee#4671]
I think it is the preview that is darker and not the other way around because the picture is abnormally dark at first opening and needs extreme settings to make it look the good way.
Files, including screenshots & pp3 : 
https://framadrop.org/r/ZQj_XjoQLO#vhLvPytClSn3pv1qcJDmQqt7w6e06bAvDGj8lAcSjqM=
DNG was issued from HDRMerge 0.5.0

Version: 5.4-694-gc1463c7ed
Branch: newlocallab
Commit: c1463c7ed
Commit date: 2018-06-14
Compiler: cc 7.3.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.22.2
Lensfun: V0.3.2.0
Build type: release
Build flags: -std=c++11 -Wno-deprecated-declarations -Wno-unused-result -std=c++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -O3 -DNDEBUG
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON

**Comment by gaaned92** [comment]
@FM33
 With tone Maping and Dynamic range compression activated, the preview is only valid at 1:1 zoom and above.( notice the small icons 1:1 at the right of command).

**Comment by heckflosse** [comment]
@FM33 Please try using neutral profile to rule out the possibility it's caused by the input being a hdr file

**Comment by Beep6581** [comment]
You have 5 tools marked as "1:1" enabled in your PP3.

![zoom-100-identifier](https://user-images.githubusercontent.com/5844619/42418498-2100f494-82a2-11e8-9bdb-451327ca051d.png)

> The effects of this tool are only visible or only accurate at a preview scale of 1:1.

The zoomed-to-100% preview matches the saved image perfectly.

**Comment by FM33** [comment]
Indeed.
I didn't notice about that 1:1 because I always used these tools without noticing any difference, but it's my first time with HDR.
Sorry for the noise.
