### ISSUE TITLE
Call Histogram matching only if necessary

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#4674]
Histogram matching is an expensive function because it decodes and demosaics the raw file.
For this reason it should only be called if necessary.
This issue is about reducing the calls.
Currently if you open a file which has histogram matching enabled and was already opened before, the histogram matching is called even if the current curve is already the result of histogram matching.
Also if you process a file in queue which you just sent to queue from editor, currently histogram matching gets called again though not necessary.

I will try to solve this two cases.

**Comment by heckflosse** [comment]
@agriggio Alberto, if your time permits, can you have a look at my changes?

**Comment by agriggio** [comment]
@heckflosse I'll do my best
