### ISSUE TITLE
Crash in highlight recovery when using AHD demosaic

### ISSUE THREAD

**Issue by polezhaevdmi** [Beep6581/RawTherapee#4692]
Sorry for the disturbance, but seems I found something fresh...

Issue description: actual RT may crush during final raw file processing (with unconditional termination), the root of cause is not exactly clear, but coupled with highlight recovery algorithm. I'm suspecting the engine crushes if no HL overload is found, instead of do nothing.

Facts I was able to found:
- The effect was observer at all RT versions, GUI, GUI-debug and console;
- The GUI-debug version under GDB hangs, at first, instead of crush but at the phase 'thread apply all bt full' the GDB crushes, thus, the logfile might be not complete; [rt_log.txt](https://github.com/Beep6581/RawTherapee/files/2216410/rt_log.txt)
- Only the [HLRecovery] processing section influences the effect. If the 'Enabled=' parameter is 'false', the effect does not appear;
- The 'Method=' parameter does not influence the effect;
- Effect is found at RT version 5.4, the 5.3 version processes the same files with same settings successfully;
- Not any file might cause crush, I collected 3 files from about 200 (the HL recovery processing settings were the same across all group).

Steps to reproduce:
- Download the example files with settings at https://filebin.net/h3k8w6gx80fjvb24
- Put at least one file to the processing queue;
- Wait until processing crush.

Hardware.
 System Manufacturer	Gigabyte Technology Co., Ltd.
 System Type	x64-based PC
 Processor 	Intel(R) Core(TM) i7-3820 CPU @ 3.60GHz, 5601 Mhz, 4 Core(s), 8 Logical Processor(s)
 BIOS Version/Date	American Megatrends Inc. F7, 19.03.2014
 Hardware Abstraction Layer	Version = "6.1.7601.24094"
 Installed Physical Memory (RAM)	64,0 GB
 Canon EOS5DMkIII;

OS.
 OS Name	Microsoft Windows 7 Ultimate
 Version	6.1.7601 Service Pack 1 Build 7601
 Total Physical Memory	63,9 GB
 Available Physical Memory	21,9 GB
 Total Virtual Memory	160 GB
 Available Virtual Memory	117 GB
 Page File Space	95,9 GB

Raw Therapee (http://rawtherapee.com/releases_head/windows/RawTherapee_5.4_WinVista_64.zip).
 Version: 5.4
 Branch: 5.4
 Commit: a5e8eb9c8
 Commit date: 2018-03-20
 Compiler: gcc 7.3.0
 Processor: generic x86
 System: Windows
 Bit depth: 64 bits
 Gtkmm: V3.22.0
 Lensfun: V0.3.2.0
 Build type: release

**Comment by Beep6581** [comment]
@polezhaevdmi can you reproduce (and provide a backtrace) using the latest development build?
https://discuss.pixls.us/t/download-rawtherapee-development-builds/2924

**Comment by polezhaevdmi** [comment]
@Beep6581, indeed. I tried 3 variants from https://keybase.pub/gaaned92/RTW64NightlyBuilds/, as https://github.com/aferrero2707/RawTherapee/releases/tag/continuous looks very old for our task. 
The effect is solid, it exists in all builds I tried. With a single change: now gdb does not crush, unlike the attempt above. Thus, the log files should be complete.

1. RawTherapee_newlocallab_5.4-772-ge65c6786f_WinVista_64.zip
[rtlog_01.txt](https://github.com/Beep6581/RawTherapee/files/2218643/rtlog_01.txt)

2. RawTherapee_5.4_WinVista_64.zip
[rtlog_02.txt](https://github.com/Beep6581/RawTherapee/files/2218648/rtlog_02.txt)

3. RawTherapee_32b-tiff-output-cli_5.4-481-gd217dcd2c_WinVista_64.zip
[rtlog_03.txt](https://github.com/Beep6581/RawTherapee/files/2218653/rtlog_03.txt)
