### ISSUE TITLE
Scrambled preview image in file browser on OSX

### ISSUE THREAD

**Issue by okoncevoy** [Beep6581/RawTherapee#4717]
When I try to rotate unaltered photo file browser view. 
As soon as I select other photo or un select current. Preview looks completely fine. 

**RT**
Version: 5.4
Branch: 5.4
Commit: a5e8eb9c8
Commit date: 2018-03-20
Compiler: clang-mp-3 3.9.1
Processor: generic x86
System: Apple
Bit depth: 64 bits
Gtkmm: V3.22.2
Lensfun: V0.3.2.0
Build type: release
Build flags:  -std=c++11 -mtune=generic -Werror=unused-label -mmacosx-version-min=10.9 -flto -fopenmp=libiomp5 -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -O3 -DNDEBUG -ftree-vectorize
Link flags:  -mtune=generic -headerpad_max_install_names -flto
OpenMP support: ON
MMAP support: ON

Was installed from image taken from http://rawtherapee.com/releases_head/mac/RawTherapee_OSX_10.9_64_5.4.zip

**System**
macOS High Sierra 10.13.5
2.9 GHz Intel Core i5
RAM 8GB 1600 MHz (DDR3)
Nvidia GeForce GTX 660M 512 MB

**Steps to reproduce**

1. Open folder using file browser that contains .NEF files (I own only Nikon)
2. Select any un edited image and try to rotate.
3. Preview of selected file gets scrambled (See screenshot)
![rt](https://user-images.githubusercontent.com/790446/43678871-6e6752f0-9823-11e8-86ad-432d88d55638.png)

**Comment by Beep6581** [comment]
http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports

**Comment by hholtm** [comment]
Behavior with latest Win64-dev (RawTherapee_dev_5.4-644-g263d96eec_WinVista_64.zip):
Rotate an unedited pef-file (90° right) in RT-browser: 
first rotate: preview gets scrambled, any further rotate also after closing and reopening RT: preview is ok
But after 1st rotating an unedited raw and without editing it and 2nd trying to change the directory RT gets closed immediately and a .pp3-file is created.
If the rotated file has been opend in editor before trying to change the directory everything is ok.

Perhaps someone can test this behavior?

Heinrich

**Comment by Benitoite** [comment]
I’m getting file browser preview scrambling rotating fresh CR2s on both MacOS 10.12 and a Debian-based container.
