### ISSUE TITLE
How to check validity of the binaries in case the website is/was compromised?

### ISSUE THREAD

**Issue by JochemKuijpers** [Beep6581/RawTherapee#4719]
Hi, **this is not a code issue**, but I could not find where to report this otherwise. If I'm in the wrong place, please let me know where to send this.

Just a few minutes ago, the main website (http://rawtherapee.com/...) threw HTTP 500 errors:
![http500](https://user-images.githubusercontent.com/1162720/43727058-2ed040b4-99a1-11e8-8985-3ef773097820.png)

When accessing using HTTPS, I got an error from Firefox complaining about an invalid root certificate.

> rawtherapee.com uses an invalid security certificate.
> 
> The certificate is not trusted because the issuer certificate is unknown. The server might not be sending the appropriate intermediate certificates. An additional root certificate may need to be imported. The certificate is only valid for . 
> 
> Error code: SEC_ERROR_UNKNOWN_ISSUER

Currently the website is back up on HTTP, but still throws this error for HTTPS. I'm assuming I got (un)lucky and caught someone working on the website and HTTPS is still misconfigured at the moment. 

I'm still somewhat worried that the website might have been compromised.

How can I check the validity of the binaries on the website? Are the checksums published anywhere besides on the main website? (which is back up right now)

**Comment by patdavid** [comment]
We are working through some things for the website that I'm hoping to get done this fall.  This will include proper certs.

**Comment by JochemKuijpers** [comment]
@patdavid You're confirming the website is not compromised and the binaries _should_ be safe?

**Comment by patdavid** [comment]
I am _not_.  I _am_ saying we hope to have something better in place (relatively) soon.  The only guarantee you might get at the moment is getting the source and auditing it yourself, then compiling (and trusting everything in the toolchain). :)

You could reach out to the builder/packager and ask for a hash if you wanted to verify independently for now...

**Comment by Beep6581** [comment]
One shouldn't put too much faith in HTTPS, it's a hurdle not a guarantee.
The website does not and never did support HTTPS or have a certificate, and it is not and never has been compromised. And if the server was compromised, HTTPS wouldn't help one bit.

**Comment by patdavid** [comment]
>  HTTPS wouldn't help one bit.

Technically, this would ensure that the compromised data was not modified during transit from the server to the client...

**Comment by Beep6581** [comment]
Yes, but if the server was compromised, this data would contain more than you paid for ;)

**Comment by JochemKuijpers** [comment]
HTTPS isn't just a safety feature, it'll also help the project since search engines value proper HTTPS. 
Improper configurations might only scare away users that land on error pages.

If the server does not support HTTPS, you can consider ignoring requests on port 443 (ignoring incoming traffic on unsupported ports isn't a bad idea anyway). It'll just timeout instead of throwing a scary-looking error page at users.

(I don't mind the issue being closed by the way, I'm just throwing in my 2 cents)

**Comment by Beep6581** [comment]
The website now offers HTTPS.
