### ISSUE TITLE
Support for Blackmagic Pocket Cinema Camera cdng files

### ISSUE THREAD

**Issue by Generic-Patriot** [Beep6581/RawTherapee#4731]
There is poor direct support for Blackmagic Pocket Cinema Camera cinema DNG files, as of version 5.4.  When I open them in Rawtherapee, they show up as patterned magenta static that somewhat shows the relief of the image, like you can faintly make out a highpass filtered version. Screenshots of this are in the google drive link below (released under CC0 liscense), as well as the original raw file, which I also uploaded to the pxls raw file library under creative commons liscense.  

https://drive.google.com/drive/folders/1Hee8lQDQCmPBwVdmh3FIRcG0BlfSIkLR?usp=sharing

The files work great when run through Adobe DNG converter, but this is an unnecessary step.

**Comment by Beep6581** [comment]
Duplicate of #4285
