### ISSUE TITLE
Nikon D800 12bit DNG wrong white point

### ISSUE THREAD

**Issue by jannefoo** [Beep6581/RawTherapee#4735]
Version: 5.4
Branch: 5.4
Commit: a5e8eb9c8
Commit date: 2018-03-20
Compiler: gcc 7.3.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.22.0
Lensfun: V0.3.2.0
Build type: release
Build flags:  -m64 -mwin32 -mthreads -Wno-aggressive-loop-optimizations -std=c++11 -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations  -DNDEBUG  -O3
Link flags: -m64 -mthreads  -static-libgcc   -mtune=generic  -s -O3 -fno-use-linker-plugin
OpenMP support: ON
MMAP support: ON

screens: dng: https://i.imgur.com/6vgsTZ8.jpg and original nef: https://i.imgur.com/RoO5Bd3.jpg
files: https://filebin.net/spwz3b87rrkognho

adobe dng converter 10.4.0.976, settings: compatibility camera raw 7.1, no lossy compression, no embed fast load data, preserve pixel count

**Comment by Thanatomanic** [comment]
Possible duplicate: #4524

**Comment by Beep6581** [comment]
Agreed, closing as duplicate.
