### ISSUE TITLE
Color readout wrong for artificial test chart (in just one case)

### ISSUE THREAD

**Issue by Thanatomanic** [Beep6581/RawTherapee#4737]
Take the following test chart for colors: https://www.dropbox.com/s/1xq4nkgsu5nigds/test_colorbars_1920x1080.tif?dl=0 (original source [here](http://www.cs.cmu.edu/~hattorih/file/image/test_colorbars_1920x1080.png))
Disable all profile corrections, and readout the cyan color. My latest dev build shows it has 0.4% red in it, and it has a saturation value of 99.6%. This is clearly wrong.

Interestingly, all other pure colors seem to have the right readout.

**Comment by Thanatomanic** [comment]
Might be related: #2133

**Comment by Thanatomanic** [comment]
I'm investigating this. First little verification: in `image8.cc` the buffers are read correctly from file. I.e. I see (0,255,255) instead of (1,255,255) popping up.

**Comment by Thanatomanic** [comment]
Second verification: in `improccoordinator.cc` when `updateLRGBHistograms()` is called, the colors are still correct.
However, I cannot figure out where the image is actually drawn to the screen. I am tangled in a web of classes, functions, handlers and buffers related to the cropwindow, imagearea and whatnot, that is simply too much for me to follow through the various source files. Is there any way to untangle this apparent spaghetti?

**Comment by agriggio** [comment]
@Thanatomanic I feel your pain. going from memory, the buffer that goes to the screen is filled in `dcrop.cc`

**Comment by Thanatomanic** [comment]
I have now spent a few hours trying to wrap my head around everything that's going on in `dcrop.cc`.  Mind-boggling stuff there... Is all that code really necessary and as simple as it can be? :open_mouth: 

As far as the bug is concerned, my suspicion is that it's either due to a floating point inaccuracy and/or a clipping issue through some RGB->Lab->RGB conversion taking place. In particular I ended up in `iplab2rgb.cc` in the `copyAndClampLine()` function where both some clipping and rounding takes place.

```
inline void copyAndClampLine(const float *src, unsigned char *dst, const int W)
{
    for (int j = 0, iy = 0; j < W; ++j) {
        float r = src[iy] * MAXVALF;
        float g = src[iy+1] * MAXVALF;
        float b = src[iy+2] * MAXVALF;
        if (r > MAXVALF || g > MAXVALF || b > MAXVALF) {
            filmlike_clip(&r, &g, &b);
        }
        dst[iy] = uint16ToUint8Rounded(CLIP(r));
        dst[iy+1] = uint16ToUint8Rounded(CLIP(g));
        dst[iy+2] = uint16ToUint8Rounded(CLIP(b));
        iy += 3;
    }
}
```

To see what these do, in `dcrop.cc` just before `parent->ipf.lab2monitorRgb(labnCrop, cropImg);` is called, I dumped the contents of `labnCrop` and show the conversion steps from (L,a,b,) -> (X,Y,Z) -> (R,G,B) -> (R,G,B) after filmlike_clip -> (R,B,G) after uint16ToUint8Rounded. These are my findings:

For a white pixel:
`(32767.7,-1.37329,3.479 -> 63185.9,65533.6,54050.1 -> 65538.7,65535.5,65492.8 -> 65535,65532,65492.8 -> 255,255,255)`
For a red pixel: 
`(17789.4,26481.2,22901.2 -> 28575.1,14580,912.225 -> 65528.8,-0.53294,-0.955105 -> 65528.8,-0.53294,-0.955105 -> 255,0,0)`
For a green pixel:
`(28776.7,-25977,26539.8 -> 25238.4,46982.7,6361.3 -> 7.94307,65535.7,-3.67123 -> 7.94296,65535,-3.67123 -> 0,255,0)`
For a blue pixel:
`(9686.74,22375.8,-36709.1 -> 9372.44,3970.96,46776.6 -> 2.08111,0.339894,65497.4 -> 2.08111,0.339894,65497.4 -> 0,0,255)`
For a cyan pixel (the bugged one!):
`(29709.4,-16603.1,-4898.8 -> 34610.8,50953.6,53137.9 -> 9.98292,65536,65493.7 -> 9.98292,65535,65492.7 -> 1,255,255)`
For a purple pixel:
`(19714.9,30653,-19822.5 -> 37947.6,18551,47688.8 -> 65530.9,-0.201315,65496.5 -> 65530.9,-0.201315,65496.5 -> 255,0,255)`
For a yellow pixel:
`(31983.9,-5160.86,30602.4 -> 53813.6,61562.7,7273.52 -> 65536.8,65535.1,-4.62665 -> 65535,65533.4,-4.62665 -> 255,255,0)`

I have no way of knowing if the math is correct, that's way out of my league :smile:

Edit: my test image for this issue is http://rawtherapee.com/shared/test_images/8_bit_chroma_subsampling.png as provided by @Beep6581 in another issue.

**Comment by Beep6581** [comment]
I just came across this, maybe related? #3383 Luma coefficients wrong/inconsistent?

**Comment by agriggio** [comment]
> Is all that code really necessary and as simple as it can be? 😮

I think you know the answer already :-)

**Comment by Thanatomanic** [comment]
Cannot reproduce any more, closing.
