### ISSUE TITLE
Bug: "Profiled Lens Correction" and "Color Management -> Working Profile"

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#4745]
**Working Profile > Gamma and Slope** are ingnored if **Profiled Lens Correction** is active and any slider in the **Exposure Tool** is changed. (Tested latest "dev")

How to reproduce:
1. Open an image and apply "Neutral"
2. Set Profiled Lens Correction to e.g. Lensfun -> Auto matched
3. Set Tone response curve to Custom
4. Set Color Management -> Working Profile -> Gamma and Slope to maximum
5. Change any slider in the Exposure tool
**Result** -> Gamme and Slope are ignored.

6. Change Gamme or Slope
**Result** -> Gamma and Slope are correctly applied to the image.

**Comment by agriggio** [comment]
"gamma and slope" seem to interact badly with many other modules. something similar happens also with tone curves, and possibly other settings too. I think the feature needs more work...

**Comment by heckflosse** [comment]
Fix:

```diff
diff --git a/rtengine/dcrop.cc b/rtengine/dcrop.cc
index 0b5198c3..2d376044 100644
--- a/rtengine/dcrop.cc
+++ b/rtengine/dcrop.cc
@@ -807,7 +807,7 @@ void Crop::update(int todo)
 
     }
 
-    if (todo & M_AUTOEXP) {
+    if (todo & (M_AUTOEXP | M_RGBCURVE)) {
         if (params.icm.workingTRC == "Custom") { //exec TRC IN free
             Glib::ustring profile;
             profile = params.icm.workingProfile;
diff --git a/rtengine/improccoordinator.cc b/rtengine/improccoordinator.cc
index 50cab329..3e9d7ab8 100644
--- a/rtengine/improccoordinator.cc
+++ b/rtengine/improccoordinator.cc
@@ -497,7 +497,7 @@ void ImProcCoordinator::updatePreviewImage(int todo, Crop* cropCall)
 
     progress("Exposure curve & CIELAB conversion...", 100 * readyphase / numofphases);
 
-    if (todo &  M_AUTOEXP) {
+    if (todo &  (M_AUTOEXP | M_RGBCURVE)) {
         if (params.icm.workingTRC == "Custom") { //exec TRC IN free
             Glib::ustring profile;
             profile = params.icm.workingProfile;

```

**Comment by Desmis** [comment]
@heckflosse 
Ingo, thank you very much :)

This patch fixed the bug
I have tried this morning (I have not been at home during 1 mounth... vacation in Mercantour) another solution, by putting the procedure further upstream, but your solution is simpler!

Jacques

**Comment by heckflosse** [comment]
@Desmis Jacques, de rien!

Thanks for testing. I will push now.

**Comment by Desmis** [comment]
@heckflosse 
thanks :)
