### ISSUE TITLE
Hasselblad H4D-40 file loads unusually slow

### ISSUE THREAD

**Issue by Thanatomanic** [Beep6581/RawTherapee#4748]
I was just playing around with some files of different make and origin from raw.pixls.us, when I tried to open this one: https://raw.pixls.us/getfile.php/2425/nice/Hasselblad%20-%20Hasselblad%20H6D-100cMS%20-%2016bit%20(4:3).fff (105.6 MP)
and this one: https://raw.pixls.us/getfile.php/931/nice/Hasselblad%20-%20Hasselblad%20H4D-40%20-%2016bit%20(4:3).fff (40.2 MP)
The former file loads in roughly 4 seconds, while the latter takes me roughly 45 seconds (!). No clue why, but I'll just report it.

**Comment by Benitoite** [comment]
Could you include some details about your system, ram, os, in your report.

**Comment by Thanatomanic** [comment]
Windows 7 (x64)
24 GB RAM
Intel Core i7-3770 @3.40 GHz

Not a bad machine if I say so myself :wink:

**Comment by Thanatomanic** [comment]
Maybe helpful: [verbose output from RT](https://pastebin.com/mduS6aeE).
It really seems that loading the file is the bottleneck. I also tried loading it from my SSD. Does not change loading times.

**Comment by Thanatomanic** [comment]
![image](https://user-images.githubusercontent.com/6567747/44616630-8dd37e80-a853-11e8-8ac8-76b369095244.png)

**Comment by heckflosse** [comment]
@Thanatomanic Thanks for reporting.
It's caused by wrong (or unsupported) Hasselblad flat field data.
Here's a fix

```diff
diff --git a/rtengine/dcraw.cc b/rtengine/dcraw.cc
index da66bd6d..32fc9902 100644
--- a/rtengine/dcraw.cc
+++ b/rtengine/dcraw.cc
@@ -2080,8 +2080,12 @@ void CLASS hasselblad_correct()
         ffcols = get2();
         ffrows = get2();
         fseek(ifp, hbd.flatfield + 16 * 2, SEEK_SET);
+        unsigned toRead = sizeof(ushort) * 4 * ffcols * ffrows;
+        if (toRead > ifp->size) { // there must be something wrong, see Issue #4748
+            return;
+        }
 
-        ushort *ffmap = (ushort *)malloc(sizeof(*ffmap) * 4 * ffcols * ffrows);
+        ushort *ffmap = (ushort *)malloc(toRead);
         for (i = 0; i < 4 * ffcols * ffrows; i++) ffmap[i] = get2();
 
         /* Get reference values from center of field. This seems to be what Phocus does too,


```

**Comment by Thanatomanic** [comment]
I am amazed by the speed you found a fix :astonished: 
But yes, it is fixed, thanks!

**Comment by Thanatomanic** [comment]
@heckflosse Oh wait, closing too soon, it still needs to be pushed to `dev`..
