### ISSUE TITLE
Store histogram settings across sessions

### ISSUE THREAD

**Issue by casta** [Beep6581/RawTherapee#4749]
Hi,

Related to PR #4618 I tested with master commit 5471b34a

There is an issue with the new histogram state memorization. Here are the steps:
- enable luminance histogram
- restart RT
- luminance is again disabled, but should stay enabled.

Other params seems correctly saved.

Thank’s !

Exact build version info:
Version: nightly-556-g5471b34a
Branch: dev
Commit: 5471b34a
Commit date: 2018-08-23
Compiler: x86_64-pc-linux-gnu-gcc 8.2.0
Processor: Intel(R)\ Core(TM)\ i5-4690\ CPU\ @\ 3.50GHz
System: Linux
Bit depth: 64 bits
Gtkmm: V3.22.2
Lensfun: V0.3.2.0
Build type: Gentoo
Build flags: -march=native -O3 -mtune=native -pipe -std=c++11  -Werror=unused-label -flto -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations  -ftree-vectorize
Link flags: -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -Wl,--sort-common  -flto
OpenMP support: yes
MMAP support: ON

**Comment by Thanatomanic** [comment]
As far as I am aware, there was/is no such setting. It can be introduced of course.

Please check `rtgui/options.cc` to verify.

**Comment by Thanatomanic** [comment]
@Beep6581 I'll take up this one

**Comment by Beep6581** [comment]
Re-opened due to red, green, blue, luminance, chromaticity and raw histogram states not being remembered. Only the histogram mode and RGB indicator bar were saved.
I only found these in my options file:
```
HistogramPosition=1
HistogramBar=true
HistogramHeight=200
HistogramDrawMode=1
```

**Comment by Beep6581** [comment]
Ah, I see in the git log that commit f59e7c3 which introduced saving these settings was reverted by commit 30b36e637.
Testing the branch now.

**Comment by Beep6581** [comment]
I found no issues with the branch.

**Comment by Thanatomanic** [comment]
Done with 85d55eb
