### ISSUE TITLE
Improve decoding speed of Nikon NEF files

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#4751]
Being a Nikon Shooter (D700), today I tried to improve decoding speed of Nikon 14 bit lossless compressed NEF files. In a first mockup I got a roughly 20% speedup for decoding (dcraw.cc function nikon_load_raw) measured on D800 files (though only when loading the files from a fast storage like e.g. SSD. Decoding a file which is loaded from an USB 2.0 connected drive will not get a speedup).

Any Nikon shooter here who likes to contribute to this issue?

**Comment by heckflosse** [comment]
I just created nikon_deode branch with a ~20% speedup for decoding of all nikon NEF files when loaded from a fast storage medium.

**Comment by Thanatomanic** [comment]
Nikon shooter here, so I like that you're working on a speedup! What kind of contribution are you looking for?

**Comment by heckflosse** [comment]
@Thanatomanic Tests would be very welcome.

Concerning processing time:
I always measure processing in queue 7 times and take the median of the 7 measures. This leads to robust results and (because of queue processing) avoids influence of progress bar on processing time.

**Comment by heckflosse** [comment]
@Thanatomanic Of course ideas to further reduce decoding time are welcome too :)

The decoding time for a 14-bit lossless compressed D850 NEF was ~900 ms before and now is ~700 ms at my system.

**Comment by heckflosse** [comment]
With last commit decoding time for a 14-bit lossless compressed D850 NEF is ~660 ms

**Comment by heckflosse** [comment]
With last commit decoding time for a 14-bit lossless compressed D850 NEF is ~635 ms

**Comment by heckflosse** [comment]
I tested with a files from a lot of different Nikon cameras using a lot of different encodings which are

```
12-bit lossy compressed
12-bit lossy compressed with split
12-bit lossless compressed
14-bit lossy compressed
14-bit lossy compressed with split
14-bit lossless compressed
```

All seem to work fine

**Comment by heckflosse** [comment]
As I'm out of ideas now to further redcude decoding time of NEF files, I would like to merge this branch into dev to get more tests asap.

Any objections?

Ingo

**Comment by Thanatomanic** [comment]
I can only take a look at this some other day this week, would that be okay? As I'm not familiar with the programmatic part of RAW decoding, I doubt that I can find another speedup, but I want to give it a go as an exercise.

**Comment by heckflosse** [comment]
@Thanatomanic Roel, take your time to look at the changes. Code review is very welcome too. In my experience, further speedup by me may be possible later after some weeks.....

**Comment by Lompik** [comment]
FWIW, I also see ~20% (1200ms to 1000ms) improvement on ```14-bit lossless uncompressed``` nef files.

**Comment by heckflosse** [comment]
@Lompik I didn't change anything for `lossless uncompressed` files, only for compressed files (lossless and lossy)

**Comment by Lompik** [comment]
@heckflosse you're right. Actually my tests were on ```14bit lossless compressed``` files according to my camera(d600) settings. There is no option for ```uncompressed```. Same speedup gains with ```14bit lossy compressed```. 

PS: I also see speedup with ```-O3``` compiler flag, from ```400ms```(dev branch, down from 1200 above) to ```300ms``` for the ```nikon_load_raw``` function.

**Comment by heckflosse** [comment]
@Lompik Thanks for testing and feedback :+1:

**Comment by Thanatomanic** [comment]
Finally did some testing, and there's indeed a clear speed-up, so that's wonderful @heckflosse 
On my machine I get a median timing going from 399 ms to 294 ms.

(on a side-note, applying a profile on my regular HD is still dead slow for me (calls to `nikon_load_raw` take up to 50000 ms), but a direct export afterwards only takes 300 ms, so weird)

**Comment by heckflosse** [comment]
@Lompik Do you say without -O3 it needs 1200ms/1000ms and with -O3 it needs 400ms/300ms?
Well, fortunately -O3 is default in RT for release builds

Edit: -O3 is default for windows builds. If it's not default for non windows builds, we should make it default.

**Comment by heckflosse** [comment]
@Thanatomanic Roel, thanks for testing :+1: I will merge now to get even more tests

**Comment by Thanatomanic** [comment]
@heckflosse Please do. I'm staring at the code, trying to figure out what is going on in `nikbithuff`, but definitely not seeing a way to optimize further.

**Comment by heckflosse** [comment]
@Thanatomanic Concerning further speedup of nikon_load_raw() it should be possible to call a special nikbithuff function, which does not check for EOL for roughly the first half of the file when build is made using MMAP...

**Comment by Lompik** [comment]
@heckflosse you understood right. My first attempt was not using release builds.

I just tested with ```-O2``` which yield similar results to ```-O3```. Most linux distros will build with ```-O2``` via env vars fortunately. My distro's rawtherapee binaries seems as fast as with optimization on.

**Comment by heckflosse** [comment]
@Lompik 
> Most linux distros will build with -O2

Then we should add at least `-ftree-vectorize` for the case -O3 is not used

**Comment by Lompik** [comment]
i believe that's what is being done L58 in cmakelist.txt. https://github.com/Beep6581/RawTherapee/blob/dev/CMakeLists.txt#L58

**Comment by heckflosse** [comment]
@Lompik Ah, yes, I remember vaguely.

I'm getting old... :( https://github.com/Beep6581/RawTherapee/commit/7507b74d6fe0668343732b6c468b5fd5b1ba5a6d

**Comment by azav** [comment]
Your first step should be in measuring the throughput off of your storage devices so that you can categorize which part of the process is reading the file off of the media.  The loading it into memory and unpacking+ allocating memory is one of the next steps.  But you gotta know how long it takes to get it off of the media first.

For example, PNG files consist of ZIP chunks within the file.  If anyone's played with the parameters in 7Zip on Windows, you'll know that there are many parameters that can be used to compress a ZIP file.  Some of them determine unpacking speed, some of them contribute to saving speed.  Some options take much longer but can create monumentally smaller files when saving.  

Knowing (measuring) the speed of transmission of reading from the media removes any doubt about which part of the file loading process is taking time.  In my world, it's always the first thing I want to know.
