### ISSUE TITLE
Update dcraw with version 9.28?

### ISSUE THREAD

**Issue by rpittaro** [Beep6581/RawTherapee#4753]
If you are filing a bug report, please first read the guide How to Write Useful Bug Reports:
http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports
You must provide the required information in order for your bug report to be valid.
Delete this text before posting.

**Comment by rpittaro** [comment]
Update dcraw with Verion 9.28?

**Comment by TooWaBoo** [comment]
Already done in latest development build.

**Comment by heckflosse** [comment]
Done in https://github.com/Beep6581/RawTherapee/commit/7d9caf04435562b6a7523510b6051f6155789dd3

**Comment by rpittaro** [comment]
Thanks!!,
Downloaded a development version and,it now works with my Nikon B700 camera which is why I was waiting for the DCRAW update.
Regards,
Rick
