### ISSUE TITLE
Crash when opening large folders

### ISSUE THREAD

**Issue by rpittaro** [Beep6581/RawTherapee#4758]
I'm trying development version 5.4-755-gc3543d2ef .
Windows 10
HPZ220 Workstation 12G Memory, Xeon Processor AMD graphic card.

When I try to open certain folders with a large number of images the program closes before completing loading the thumbnails. I haven't seen the effect on any smaller folders, but I don't think it's strictly the folder size or the number of images. It loads the thumbnails and runs properly on one  40 GBYTE folder with 2000 images (1000 JPG, 1000 NRW)  but crashes when loading files from another 28 GBYTE folder with 1600 images (800 JPG, 800 NRW).  It also crashes on a 32 GBYTE folder with 4800 images (all JPG). Theses folders all load OK  with release version 5.2. I appreciate that this is a development version, just reporting the bug so it might be fixed in the next release version. I've "scanned" the folders and don't see anything obvious but Idon't know what to look for.
Thanks for the great work on RawTherapee.
Rick

**Comment by heckflosse** [comment]
@rpittaro Does it also crash on a folder without JPG files?

**Comment by Beep6581** [comment]
@rpittaro a stack backtrace would give invaluable information:
http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports#When_RawTherapee_crashes_-_An_introduction_to_stack_backtraces

**Comment by rpittaro** [comment]
I will attempt to do a back trace and send the info
Thanks
Rick

**Comment by rpittaro** [comment]
I ran the debugger didn’t get to the stack back trace but this is a screen shot of the error it threw. I’ll do more if it will help.
Thanks,
Rick

**Comment by rpittaro** [comment]
Here is the backtrace.
Regards,
Rick

**Comment by rpittaro** [comment]
Ingo,
It has not had a problem with opening folders with only NRW files but I haven’t yet tried many of those . I will try to open more folders.

Thanks,
Rick

**Comment by Beep6581** [comment]
@rpittaro it seems that attachments are lost when one replies by email, so we didn't get the stack backtrace screenshot or log. Could you reply from GitHub?
https://github.com/Beep6581/RawTherapee/issues/4758

**Comment by rpittaro** [comment]
Will Do
Rick

**Comment by heckflosse** [comment]
@rpittaro That's a bug reading one of the jpg files. Maybe a corrupted file.

**Comment by Beep6581** [comment]
@rpittaro please upload `D:\\PHOTOS\\SALVBARD\\RICK1\\DSCN2795.JPG` using https://filebin.net/ and paste the link here.

**Comment by rpittaro** [comment]
a.. It looks corrupted!

**Comment by heckflosse** [comment]
@rpittaro Even if it's corrupted, RT should not crash. If possible, please provide the file, so we can fix the crash

**Comment by rpittaro** [comment]
After removing the file the folder loads fine. I followed the above instructions and uploaded the file.

**Comment by gaaned92** [comment]
@heckflosse is'nt it a bad effect of https://github.com/Beep6581/RawTherapee/issues/4713, as I have to patch in order to build?

**Comment by heckflosse** [comment]
@gaaned92 I still use the old version of libjpeg-turbo. With that version RT does not crash with the file provided by @rpittaro . It reports in console:
```
Corrupt JPEG data: premature end of data segment
Unsupported marker type 0x08
```

**Comment by gaaned92** [comment]
@heckflosse 
Are you able to solve https://github.com/Beep6581/RawTherapee/issues/4713 ?
If not, I am going to revert blibjpeg-turbo

**Comment by heckflosse** [comment]
@gaaned92 I will try to solve it but I can not promise

**Comment by gaaned92** [comment]
@heckflosse in the mean time, I revert libjpeg-turbo
@rpittaro  sorry for the inconvenience. I will rebuild tomorrow.

edit: can you test?
> RawTherapee_dev_5.4-778-g61e033ae1_WinVista_64.zip

uploaded at
https://keybase.pub/gaaned92/RTW64NightlyBuilds/

**Comment by gaaned92** [comment]
@heckflosse perhaps you can close this topic.
