### ISSUE TITLE
Output profile rendering intent

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4762]
Hello

We are allowed to specify the output profile's rendering intent, however when using our RT profiles the rendering intent makes absolutely no difference to the saved image. When does it work? Is this documented somewhere?

@Desmis maybe you know?

**Comment by Desmis** [comment]
@Beep6581 
A long time ago (several years) that I found that "intent" did not work.
The new profiles have not changed anything. I do not know why, probably LCMS ??

**Comment by Beep6581** [comment]
The rendering intent combo doesn't work when using our profiles because they don't contain mapping tables.

Duplicate of #3118
