### ISSUE TITLE
Add more scopes

### ISSUE THREAD

**Issue by eprovst** [Beep6581/RawTherapee#4763]
Scopes help us to quickly see what is wrong with an image and also give us the ability to do certain corrections 'by the numbers' that are hard to judge on a screen.

Potential scopes include:

**Vectorscope**  
Currently RawTherapee only has histograms which is great to see the overall lightness, redness, etc. of the image. However, it's often useful to have an idea of the color balance in terms of hue and saturation -- eg. to check skintones; this is exactly what a vectorscope is. For the skintones use case a skintone line is also a must have on a vectorscope.

A possible alternative to a vectorscope is a chrominance chart which fits easier within the current interface.

**More to be added.**

**Comment by Thanatomanic** [comment]
I agree that a vectorscope and color wheels could be nice additions. I have done some color grading for film on a hobby project, and both the vectorscope and color wheels can be very convenient to use.
Personally, I would not call this a high priority thing though, because I believe the proposed color wheel operations can already be achieved using other tools available in RT. Maybe not as convenient ...

We might get some inspiration from the way darktable has implemented their ~~vector scope~~ (my bad, darktable only has a waveform tool).

**Comment by eprovst** [comment]
I agree that it isn't a high priority however it's a really nice to have :smile: But it's true anything you can do with color wheels can also be done with levels although color wheels make it a lot easier to get the color you want.

I can't recall Darktable having a vectorscope, however when it comes to design I think something similar to the one in Nuke (with less lines), Final Cut or Speedgrade would work. As long as it has the skintone line and a reasonable mapping of color and saturation it will be ideal for the purpose of photography. I don't think there is a need to see the NTSC color targets for example.

**Addition:** 0 saturation should also be marked on the vectorscope of course.

**Comment by heckflosse** [comment]
@ElecProg Some screenshots or a video would help more than 1000 words for this issue!

**Comment by Thanatomanic** [comment]
![image](https://user-images.githubusercontent.com/6567747/44935880-bf2bdd00-ad72-11e8-9a9d-d97d9bda55ad.png)
This is how the ~~scope~~ waveform looks like in darktable.

![image](https://user-images.githubusercontent.com/6567747/44935958-13cf5800-ad73-11e8-8a47-fc8ac264594a.png)
This is what DaVinci Resolve can give you in terms of color gauges.

**Comment by eprovst** [comment]
Third Davinci scope in @Thanatomanic s comment. You wont need all the lines and boxes on that scope for photography. So you could simplify the design quite a bit.

However a chrominance chart like used in CameraBag might fit better within the current UI, it's basically a vectorscope cut open and put into a rectangle.

**Comment by eprovst** [comment]
**Chrominance chart:**  
As noted in my earlier comment a chrominance chart might be a better fit withing RT, as it has the same dimensions as a histogram. On the horizontal axis we have the hue and on the vertical axis saturation (bottom being 0% and top 100%). On my sketch it seems as if this would have to create a blob however in practice all pixels in the picture would be plotted which would create a similar look as a vectorscope.

The long vertical line represents the skintone line and the shorter would show the position of the pixel under the cursor.

![chrom](https://user-images.githubusercontent.com/5394549/45347553-b6c27600-b5ac-11e8-8c42-6fd95c0a2616.png)

Horizontal dotted lines showing certain saturation levels might also be useful.

The main difficulty in a chrominance chart is the plotting of pixels with low or no saturation as they have a rather ambiguous hue.

**Comment by Beep6581** [comment]
Here's a nice rundown of various color representation widgets:
https://blog.frame.io/2017/09/27/introduction-to-video-scopes/

**Comment by eprovst** [comment]
As the article states, having the option to limit the scope to a selection on the image might also be useful.

**Comment by Beep6581** [comment]
I like the ability to see beyond the output limits.

**Comment by sguyader** [comment]
I discovered the RGB parade in a video NLE (Kdenlive) and I think it's really useful. But it takes more screen estate.

**Comment by eprovst** [comment]
Note: Updated issue to better reflect the current discussion. Moved color wheels to a separate issue (#4804)

**Comment by X-Raym** [comment]
Vectorscope would be nice. An handy way to check for saturation. It is easy to put a bit more saturation than needed. Such scope could prevent that. Thx!

**Comment by Beep6581** [comment]
https://discuss.pixls.us/t/waveform-histogram/14138/16

**Comment by Lawrence37** [comment]
I'm working on an implementation of a waveform viewer. A vectorscope is a possibility, but I need more information such as the color representation (Hue-Saturation, Chroma-hue, ???) and what information is relevant to photographers.

**Comment by eprovst** [comment]
@Lawrence37 great news!

**About vectorscopes:**  
I think both Chroma-Hue and Saturation-Hue have their uses, though chroma might be fairly computationally expensive, I'm not sure.

The 'skin-tone line' is a lifesaver in portraits (skin-tones are 'memory colours' so if you get them wrong they 'feel' wrong) so I feel like that one has to be included. Different skin-tones are mainly dependent on saturation and luminance and lie either above or below the line, so you really only need one.

The concentric circles denoting 25, 50, 75 and 100 percent saturation are also fairly useful to get an idea of the actual saturation.

**Generally about scopes:**  
The brightness of the dots in the scope should be changeable to more clearly see details when the scope is 'blown out'.

Highlighting the pixel below the cursor in the image on the scope also seems like a useful feature to have.

Edit: clarification.

**Comment by Lawrence37** [comment]
Thanks @elecprog. According to my research, most vectorscopes use the U and V in the YUV color space. I guess I will try several color representations and see if they are useful or redundant.

**Comment by Lawrence37** [comment]
Here's how the standard vectorscope (U-V) compares to Hue-Saturation and Hue-Chroma vectorscopes. Each have their strengths and weaknesses, although U-V and H-C are somewhat similar.

Image | H-S | U-V | H-C
-|-|-|-
![image](https://user-images.githubusercontent.com/45837045/88963174-54d08f80-d25c-11ea-808e-dcf4c38df9f7.png) | ![image](https://user-images.githubusercontent.com/45837045/88965345-7da65400-d25f-11ea-88ff-5d17c6174279.png) | ![image](https://user-images.githubusercontent.com/45837045/88964434-3e2b3800-d25e-11ea-8795-c3fe93d47dba.png) | ![image](https://user-images.githubusercontent.com/45837045/88963352-919c8680-d25c-11ea-861a-ae18fb8edebf.png)
![image](https://user-images.githubusercontent.com/45837045/88963545-d7f1e580-d25c-11ea-9409-024c95e59de5.png) | ![image](https://user-images.githubusercontent.com/45837045/88965593-d675ec80-d25f-11ea-8f9e-b66978a93bb9.png) | ![image](https://user-images.githubusercontent.com/45837045/88964714-9e21de80-d25e-11ea-9af8-dd2a98e85d43.png) | ![image](https://user-images.githubusercontent.com/45837045/88963628-feb01c00-d25c-11ea-9056-f19edbd481c4.png)
![image](https://user-images.githubusercontent.com/45837045/88963756-328b4180-d25d-11ea-806e-215599ee7efc.png) | ![image](https://user-images.githubusercontent.com/45837045/88965675-f3aabb00-d25f-11ea-8937-1cb82d0c9d28.png) | ![image](https://user-images.githubusercontent.com/45837045/88964816-c27dbb00-d25e-11ea-9b73-0306dd99ec6c.png) | ![image](https://user-images.githubusercontent.com/45837045/88963834-4df64c80-d25d-11ea-95d0-e1e1de652669.png)
![image](https://user-images.githubusercontent.com/45837045/88963959-7c742780-d25d-11ea-98ba-ab5e788f5606.png) | ![image](https://user-images.githubusercontent.com/45837045/88965757-12a94d00-d260-11ea-8a71-e542b97f17b7.png) | ![image](https://user-images.githubusercontent.com/45837045/88964877-d9bca880-d25e-11ea-9e60-df5db9daa4e9.png) | ![image](https://user-images.githubusercontent.com/45837045/88963930-6cf4de80-d25d-11ea-9d6f-740563d350c1.png)

**Comment by Lawrence37** [comment]
I will go ahead with the H-S and H-C vectorscopes. The H-S vectorscope is useful for preventing over saturation and the H-C vectorscope is good for general purposes. They also complement the HSV and L* a* b* display below the navigator.

The "skin tone line" is problematic. I have not found any good resources on "typical" HSV or L* a* b* skin tone values.

**Comment by Thanatomanic** [comment]
Does this help?
https://munsell.com/color-blog/color-of-flesh/#:~:text=The%20fact%20is%20that%20most,everyone%20averages%205YR%2C%20chroma%203.

https://www.sciencedirect.com/science/article/pii/S0022202X92903477

**Comment by Lawrence37** [comment]
Thanks @Thanatomanic. The first link helped with the the L* a* b* value. For HSV, I transformed the U-V skin tone line.

**Comment by Thanatomanic** [comment]
I think this issue can be closed due to https://github.com/Beep6581/RawTherapee/commit/f9e8fb41242460add0ef1c97a979e4bd48d61106 and the great work by @Lawrence37
