### ISSUE TITLE
Recreate bundled ICC profiles with consistent and correct description and copyright

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4769]
As mentioned in [#4478](https://github.com/Beep6581/RawTherapee/issues/4478#issuecomment-417932713), the bundled ICC profiles need to be re-generated with consistent description and copyright tags.

**Comment by Beep6581** [comment]
@Desmis I'm assuming our currently-bundled profiles were generated using some other software because our ICC Profile Generator did not exist at the time. If I recreate all of our bundled profiles using our own ICC Profile Creator and setting correct properties (primaries, TRC, illuminant, ICC version), copyright and description, will they contain all the needed info and be good to replace the current ones?

**Comment by Desmis** [comment]
@Beep6581 
I  think yes :)

But be careful, the name of the "new" files must be exactly the same

**Comment by Beep6581** [comment]
This issue is handled by #4980
