### ISSUE TITLE
Placement of checkbox in Preferences could be improved

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4772]
In Preferences > Layout, the "Use tab icons instead of text" checkbox is placed in such a way that it sticks to a grid near the right side of the window which makes it go out of view when the window is even 1290px wide (or less).

Screencast:
https://filebin.net/lz8xr59h4kqq3yy7/vid1-2018-09-02_22.44.59_x264_crf23.mp4?t=qj60g1gu

**Comment by TooWaBoo** [comment]
I think this feature can be removed, I've never seen a screenshot with text instead of icons.

**Comment by heckflosse** [comment]
I take this
