### ISSUE TITLE
Toolbar scroll bug workaround

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#4781]
Played with the new scrolled toobars and found a possible workaround for the freeze.
First of all the toolbar freezes only if you scroll in the bottom part of the toolbar. (It looks like Gtk bug).
What I did is to add a huge margin to the bottom of the toolbar container and cut it off with the scrolled tool container, e.g.
```
#EditorTopPanel {
    margin-bottom: 50px;
}
#EditorToolbarTop {
    margin-bottom: -50px;
}
```
With this workaround the toolbar doesn't freeze anymore. I've modified the TooWaBoo theme and fixed the top and bottom toolbar. There is still a problem with the bottom toolbar. It's not possible to scroll over the comboboxes.
To fix the Query- and Filter toolbar I need another container inside the scroll containers.

Please test these modifications if it works on other OS too.
[TooWaBlue_Scroll_test-GTK3-20_.css.txt](https://github.com/Beep6581/RawTherapee/files/2356953/TooWaBlue_Scroll_test-GTK3-20_.css.txt)

I've tested on Win10 x64 and Gtk+3.24.0

ping @Hombre57 , @Beep6581

**Comment by Benitoite** [comment]
No problems with repo TWB themes or Scroll_test on macOS (gtk 3.22.30) here.

**Comment by Hombre57** [comment]
@TooWaBoo What's your GTK and OS version ?

**Comment by TooWaBoo** [comment]
@Hombre57 
Win10 x64 and Gtk+3.24.0

**Comment by Hombre57** [comment]
@TooWaBoo That's weird ! 3.22 here and it works better than in 3.24 !? I'm still trying to create a better workaround, usable for Gtk3.18 users too.

**Comment by Benitoite** [comment]
Upgraded to gtk+3.24.0 on macOS and have flickering tooltip titles also.  Had one non-repeatable crash scrolling a toolbar while on TWB-dark. Scroll_test still has flickering tooltip titles.

**Comment by Hombre57** [comment]
@TooWaBoo Does the new `scrolled-toolbar-fix` branch fix the freeze problem (w/o your patch) ?

**Comment by TooWaBoo** [comment]
@Benitoite 
I've found these issues in RT with Gtk+3.24.0
_Filename tooltip over thumbnails and History tooltip are flickering.
Scrolling with the mouse wheel in the file browser and filmstrip doesn't work anymore.
Zooming with the mouse wheel in the preview doesn't work anymore.
Rounding of "em" values in themes has changed. (this affects only the TWB theme)_

@Hombre57 
I will test.

**Comment by TooWaBoo** [comment]
@Hombre57 
The answer is here: https://github.com/Beep6581/RawTherapee/issues/4035#issuecomment-419275367

**Comment by Hombre57** [comment]
@TooWaBoo Damn it!

I tried again to reproduce the error with dev minus the unsupported line, but now it works ! So I don't understand why it froze before and how to reproduce.

Could you start RT from a com and line console, but executing this first : `set GTK_DEBUG=interactive`. Then use the top left icon of the inspector window to locate the toolbar's widget. It should have the same height than its children. I know that containers can be smaller than the child in HTML, but don't know for GTK.

**Comment by TooWaBoo** [comment]
@Hombre57 
There is no inspector. I'm on Windows and have only MSYS installed.

**Comment by heckflosse** [comment]
@TooWaBoo in msys2 comandline execute this (no `set`)

```
GTK_DEBUG=interactive rawtherapee
```

**Comment by TooWaBoo** [comment]
@heckflosse 
Thanks, it works
@Hombre57 
Bingo, I've found the culprit, like my first thought there is a hidden scrollbar which makes this trouble.
In css it can be fixed with this simple style.
```
.scrollableToolbar scrollbar:not(.overlay-indicator) slider:not(.dummy) {
    padding: 0;
    margin: 0;
    min-height: 0;
    min-width: 0;
    border: none;
}
```
![grafik](https://user-images.githubusercontent.com/13800920/45213582-3d6b1080-b298-11e8-823c-0ce347fe273e.png)

**Comment by Beep6581** [comment]
Using CSS to hack around UI issues should be done as a last resort.

1. What exactly is the problem? Scrolling doesn't work when using GTK+ 3.24 when hovering over the area into which a horizontal scrollbar would appear, is that correct?
2. Is it really a bug, or are we doing something wrong?
3. Can it be fixed in RT's GTK+ code?
4. Have you reported it upstream to GTK+? If so, please provide a link.

@Hombre57 
https://developer.gnome.org/gtk3/stable/ch26s02.html#id-1.6.3.4.14

**Comment by TooWaBoo** [comment]
1. Yes but it's not related to the Gtk version
2. That's what we try to figure out
3. I don't know
4. I'm the wrong person to do that. I didn't write the code and I don't understand the code in details

**Comment by TooWaBoo** [comment]
Only for testing.
[RawTherapeeScrollfix-GTK3-20_.css.txt](https://github.com/Beep6581/RawTherapee/files/2360987/RawTherapeeScrollfix-GTK3-20_.css.txt)
[TooWaBlueScrollfix-GTK3-20_.css.txt](https://github.com/Beep6581/RawTherapee/files/2360988/TooWaBlueScrollfix-GTK3-20_.css.txt)

**Comment by Benitoite** [comment]
> @Benitoite
> I've found these issues in RT with Gtk+3.24.0
> Filename tooltip over thumbnails and History tooltip are flickering.

This flickering appears to be a commonality between windows and mac.

Testing Scrollfix on macOS, seems to scroll fine.

Occasionally do get a crash involving the quartz backend: https://gitlab.gnome.org/GNOME/gtk/issues/1312

**Comment by TooWaBoo** [comment]
@Benitoite 
Thanks for the feedback.
btw. Can you check if these issues https://github.com/Beep6581/RawTherapee/issues/4784 exists on MacOS too and leave a comment there, please?

**Comment by Hombre57** [comment]
@TooWaBoo @Beep6581 @Benitoite

Ok to merge `scrolled-toolbar-fix` into `dev` ?

**Comment by TooWaBoo** [comment]
Yes, it fixes some GTK+ 3.24 issues too, but the toolbutton scrollbug in GTK+ 3.24 still exists.
https://github.com/Beep6581/RawTherapee/issues/4784

**Comment by TooWaBoo** [comment]
The toolbar-scroll-bug still exists in GTK+ >3.18. ShalI I activate the theme workaround?

**Comment by Hombre57** [comment]
@TooWaBoo  I don't manage to find a better way using Gtk's function, so I'd say yes.

**Comment by Hombre57** [comment]
And could you add it in RawTherapee's theme as well ?

**Comment by TooWaBoo** [comment]
OK, I will do it this evening.

**Comment by TooWaBoo** [comment]
Done, closing issue.
