### ISSUE TITLE
Deleting find criteria in file browser by pressing the x some times does not work in TooWaBlue theme

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#4782]
To reproduce:

Use TooWaBlue theme
Use SETM (may also happen using METM, but didn't test)
enter `nrw` as find string and hit enter
open a file
go back to filebrowser
press the x next to the find => does not reset

Works fine in RawTherapee theme

@TooWaBoo

**Comment by TooWaBoo** [comment]
Thanks for reporting. I will check.

**Comment by TooWaBoo** [comment]
Found the culprit. Fix coming with next update.

**Comment by TooWaBoo** [comment]
@heckflosse 
Created a PR. You can close this issue.

**Comment by Beep6581** [comment]
@TooWaBoo could you please explain what had changed that required these em changes and where this change was, and show a before/after screenshot of the problem with the old values?

**Comment by TooWaBoo** [comment]
@Beep6581 
```
e.g. font size 9, 96dpi   old | new
min-height: 2.1667em     24px | 25px
min-height: 2.1666em     24px | 24px

margin: 0.16667em         2px | 2px
margin: 0.16666em         2px | 2px

padding: 0.16667em        2px | 2px
padding: 0.16666em        2px | 2px
```
This looks easy to fix but the differences in combinations of borders, margin, paddings, min-height, min-width or if the size of an object is calculatetd from inside to outside or vice versa makes it impossible to make it work for the old and new GTK+.

To avoid this the only way I've found is to use 18 decimals for an em-value. There are still some slightly differences between GTK+ 3.24 and GTK+ 3.23 when changing font size or DPI but the layout is consistent in itself.

**Comment by Beep6581** [comment]
It's this GTK+ issue, affects `min-(width|height)`:
https://gitlab.gnome.org/GNOME/gtk/issues/1088

**Comment by TooWaBoo** [comment]
That's exactly the point.

**Comment by TooWaBoo** [comment]
@heckflosse 
This issue is fixed and can be closed.

**Comment by heckflosse** [comment]
Fix confirmed
