### ISSUE TITLE
Leica Camera AG LEICA M MONOCHROM (Typ 246) support

### ISSUE THREAD

**Issue by kaelte** [Beep6581/RawTherapee#4785]
```
iMac15,1
CPU: Intel Core i7 4 GHz
RAM: 32 GB
```
```
macOS 10.13.6 (17G65)
Darwin 17.7.0
Version: 5.4
```
[Raw Therappee Version](https://rawtherapee.com/releases_head/mac/RawTherapee_OSX_10.9_64_5.4.zip)
```
Branch: 5.4
Commit: a5e8eb9c8
Commit date: 2018-03-20
Compiler: clang-mp-3 3.9.1
Processor: generic x86
System: Apple
Bit depth: 64 bits
Gtkmm: V3.22.2
Lensfun: V0.3.2.0
Build type: release
Build flags:  -std=c++11 -mtune=generic -Werror=unused-label -mmacosx-version-min=10.9 -flto -fopenmp=libiomp5 -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -O3 -DNDEBUG -ftree-vectorize
Link flags:  -mtune=generic -headerpad_max_install_names -flto
OpenMP support: ON
MMAP support: ON
```
[Sample Photos (DNG,JPD,PP3) DownLoad](https://cncloud.zaclys.com/index.php/s/tQC9tERfpmEsSJA)

Photos in DNG taken with LEICA M Monochrom (Typ 246) do not look right. The following JPG has been created using RT without any image processing. The DNG looks the same on the screen.
![JPG created by Raw Therappee](https://cncloud.zaclys.com/index.php/s/tQC9tERfpmEsSJA/download?path=%2F&files=20180430-115118_LEICA_M_MONO.jpg)

Here the JPG created by the camera itself:

![JPG created by camera](https://cncloud.zaclys.com/index.php/s/tQC9tERfpmEsSJA/download?path=%2F&files=20180430-115118_LEICA_M_MONO_Camera.JPG)

**Comment by Benitoite** [comment]
Same result with latest dev/Mac and dev/Debian docker container.

**Comment by heckflosse** [comment]
This patch fixes it:
```diff
diff --git a/rtengine/dcraw.cc b/rtengine/dcraw.cc
index ccfd16187..bd9fa4b47 100644
--- a/rtengine/dcraw.cc
+++ b/rtengine/dcraw.cc
@@ -1136,7 +1136,7 @@ void CLASS lossless_dng_load_raw()
       fseek (ifp, get4(), SEEK_SET);
     if (!ljpeg_start (&jh, 0)) break;
     jwide = jh.wide;
-    if (filters) jwide *= jh.clrs;
+    if (filters || (colors == 1 && jh.clrs > 1)) jwide *= jh.clrs;
     jwide /= MIN (is_raw, tiff_samples);
     switch (jh.algo) {
       case 0xc1:

```
![grafik](https://user-images.githubusercontent.com/13733487/45264643-151e1600-b440-11e8-9532-3f4e158a575b.png)

**Comment by Benitoite** [comment]
I can make a test build for Mac but it will be with gtk 3.24.0, which has some bugs with the Mac/quartz backend. https://gitlab.gnome.org/GNOME/gtk/issues/1312

**Comment by Benitoite** [comment]
@heckflosse Patch works fine. 
@kaelte In case you want to try, here is a patched development build. [...]

Goofing around:
![screen shot 2018-09-09 at 7 02 59 pm](https://user-images.githubusercontent.com/17919239/45272738-e7e35f00-b463-11e8-8be0-c1fdd377aef9.jpg)

**Comment by heckflosse** [comment]
Can one of the contributors please commit this patch? I'm on a different branch atm and don't want to switch.

**Comment by Floessie** [comment]
@heckflosse Why don't you stash?

**Comment by heckflosse** [comment]
@Floessie because I didn't know about it :frowning_face:

**Comment by Benitoite** [comment]
@heckflosse 
https://github.com/Beep6581/RawTherapee/pull/4787

**Comment by Floessie** [comment]
@heckflosse Glad, my question opened up the path to enlightenment. :bulb: :wink:

**Comment by heckflosse** [comment]
fixed with 0aa1158

**Comment by kaelte** [comment]
Thanks to all for your work. @Benitoite your build works fine. Thanks!

**Comment by Benitoite** [comment]
@kaelte  
https://filebin.net/fn5divy9zkbgczzo/RawTherapee_OSX_10.9_64_5.4-817-g696930387.zip?t=e47wryvw
Here is a new build, stable gtk 3.22.30 included.
