### ISSUE TITLE
Scrolled toolbar problem with GTK+ 3.18

### ISSUE THREAD

**Issue by agriggio** [Beep6581/RawTherapee#4786]
The constructor of `MyScrolledToolbar` calls the method `set_propagate_natural_height`; this seems to be not available on GTK+ 3.18. I had to comment-out the line to make RT compile... are we dropping support for 3.18? I hope not, that's the version I'm still using.

**Comment by Benitoite** [comment]
FWIU, 3.24.x is supposed to be the ultimate (the final) gtk+3 version.  Previously 3.22.x was the ultimate version.  It seems like the trend is to migrate to 3.24.x for RT 5.5, if I’m following the roadmap correctly.  If RT team really intended to require 3.24.x we should adjust CMakeLists.txt.

**Comment by Beep6581** [comment]
I think RawTherapee 5.5 should be able to compile using GTK+ 3.18 as a significant number of distribution releases made "not so long ago" still only support it, e.g. Ubuntu 16.04 LTS, and most releases only support 3.22. No releases support 3.24 yet.

https://distrowatch.com/search.php?pkg=gtk%2B&relation=similar&pkgver=3.24&distrorange=InLatest#pkgsearch

**Comment by agriggio** [comment]
:+1: to what @Beep6581 said. I'm using a distro based on Ubuntu 16.04, and I have no plan to upgrade for the foreseeable future...

**Comment by Benitoite** [comment]
I think a lot of people have used 3.24 already because it showed up in msys2, the windows distribution.  I did build it on Mac from gitlab.gnome.org to test what @TooWaBoo and @Hombre57 were doing with it.  They can probably then backport to support 3.18 ?

**Comment by Hombre57** [comment]
@agriggio @Benitoite I've merged `scrolled-toolbar-fix` into dev to fix this problem. As reported by @Floessie , a `Gtk-WARNING` may appear, I'll try to solve that ASAP.

@Beep6581 The thing is that for newcomers, MSYS2 only provide the bleeding edge version of Gtk and may prevent them to build RT on Windows if we stick to a previous version, not available anymore.

**Comment by heckflosse** [comment]
@Hombre57 as long as we stay backwards compatible to 3.18, I see no problem in supporting 3.24
