### ISSUE TITLE
Cancel button in SaveAs dialog doesn't respond on first click

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#4788]
I have to click twice. Same for esc key in SaveAs dialog

**Comment by TooWaBoo** [comment]
It's not a bug, it's a feature.
If you have a look on the filename on top, you will see a list of saved files. The first click is to close this list.
This list appears only for files where the filename starts with the one in the entry field.
![grafik](https://user-images.githubusercontent.com/13800920/45299428-de153680-b50b-11e8-87a6-c2e01f17013a.png)

**Comment by heckflosse** [comment]
@TooWaBoo Ok, closing.
