### ISSUE TITLE
Rawtherapee 5.4-817-g696930387 Winx64 does not start.

### ISSUE THREAD

**Issue by Kildor** [Beep6581/RawTherapee#4793]
Today I updated my mingw64 installation (pacman -Su) and recompiled RT.

When I tried to run it the program doesn't start. When I run it with GDB I got this message: 
```
[New Thread 9968.0xdc0]
terminate called after throwing an instance of 'Gdk::PixbufError'
[Thread 9968.0x3a74 exited with code 3]
[Thread 9968.0x41a4 exited with code 3]
[Thread 9968.0x1830 exited with code 3]
[Thread 9968.0x4348 exited with code 3]
[Thread 9968.0x34e8 exited with code 3]
[Thread 9968.0x3dd8 exited with code 3]
[Thread 9968.0x41c8 exited with code 3]
[Thread 9968.0xdc0 exited with code 3]
[Thread 9968.0x43b4 exited with code 3]
[Inferior 1 (process 9968) exited with code 03]
```
Cleaning appdata folder and settings do not help.
My system is Win10.

I don't know what other information I can provide.
```
Version: 5.4-817-g696930387
Branch: dev
Commit: 696930387
Commit date: 2018-09-11
Compiler: gcc 8.2.0
Processor: undefined
System: Windows
Bit depth: 64 bits
Gtkmm: V3.22.2
Lensfun: V0.3.95.0
Build type: release
Build flags:  -std=c++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -O3 -DNDEBUG -ftree-vectorize
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON
```

**Comment by Beep6581** [comment]
@Kildor 
1. Delete the build folder and rebuild - paste the full build log, from "cmake" till end of compilation and linking.
2. Please paste the full backtrace after typing `bt full` when running a **debug** build from GDB.

**Comment by heckflosse** [comment]
@Kildor you've to revert lensfun

```
pacman -U /var/cache/pacman/pkg/mingw-w64-x86_64-lensfun-0.3.2-4-any.pkg.tar.xz
```

**Comment by heckflosse** [comment]
@Kildor maybe also
```
pacman -U /var/cache/pacman/pkg/mingw-w64-x86_64-libjpeg-turbo-1.5.3-1-any.pkg.tar.xz
```

**Comment by Kildor** [comment]
I reverted jpeg-turbo (otherwise it didn't compile). Also I reverted lensfun (and got error about lensfun database version).

https://pastebin.com/txhL3dDz -- compile log

https://pastebin.com/1hzYLicF -- GDB log. There is no stacktrace.

Interesting thing: there is no errors with rawtherapee running under GDB if no dlls are in rt folder. But, if I copy dlls from mingw bin folder, I get this problem.

Here is list of dlls:
libatk-1.0-0.dll
libatkmm-1.6-1.dll
libbz2-1.dll
libcairo-2.dll
libcairo-gobject-2.dll
libcairomm-1.0-1.dll
libdatrie-1.dll
libepoxy-0.dll
libexpat-1.dll
libffi-6.dll
libfftw3f-3.dll
libfontconfig-1.dll
libfreetype-6.dll
libfribidi-0.dll
libgcc_s_seh-1.dll
libgdk-3-0.dll
libgdk_pixbuf-2.0-0.dll
libgdkmm-3.0-1.dll
libgio-2.0-0.dll
libgiomm-2.4-1.dll
libglib-2.0-0.dll
libglibmm-2.4-1.dll
libgmodule-2.0-0.dll
libgobject-2.0-0.dll
libgomp-1.dll
libgraphite2.dll
libgtk-3-0.dll
libgtkmm-3.0-1.dll
libharfbuzz-0.dll
libiconv-2.dll
libintl-8.dll
libjpeg-8.dll
liblcms2-2.dll
liblensfun.dll
liblzma-5.dll
libpango-1.0-0.dll
libpangocairo-1.0-0.dll
libpangoft2-1.0-0.dll
libpangomm-1.4-1.dll
libpangowin32-1.0-0.dll
libpcre-1.dll
libpixman-1-0.dll
libpng16-16.dll
libsigc-2.0-0.dll
libstdc++-6.dll
libsystre-0.dll
libthai-0.dll
libtiff-5.dll
libtre-5.dll
libwinpthread-1.dll
zlib1.dll

**Comment by Beep6581** [comment]
Thank you. The build log uses `-DCMAKE_BUILD_TYPE="release"`, I assume you used `-DCMAKE_BUILD_TYPE="debug"` for the build you ran through GDB? Otherwise looks fine.
If our Windows build instructions are [up to date](https://github.com/Beep6581/RawTherapee/issues/4404#issuecomment-420582941), maybe a DLL version conflict?

**Comment by Kildor** [comment]
>  I assume you used -DCMAKE_BUILD_TYPE="debug" for the build you ran through GDB?

Yes.

> If our Windows build instructions are up to date, maybe a DLL version conflict?

May be.
There are some dlls not listed in rawpedia which are requested by RT. Also if I delete all dlls and copy requested ones trying to start the program, I do not copy some of them listed in rawpedia.

**Comment by TooWaBoo** [comment]
This is my list of .dlls
```
libatk-1.0-0.dll
libatkmm-1.6-1.dll
libbz2-1.dll
libcairo-2.dll
libcairo-gobject-2.dll
libcairomm-1.0-1.dll
libcroco-0.6-3.dll
libdatrie-1.dll
libepoxy-0.dll
libexpat-1.dll
libffi-6.dll
libfftw3f-3.dll
libfontconfig-1.dll
libfreetype-6.dll
libfribidi-0.dll
libgcc_s_seh-1.dll
libgdk-3-0.dll
libgdkmm-3.0-1.dll
libgdk_pixbuf-2.0-0.dll
libgio-2.0-0.dll
libgiomm-2.4-1.dll
libglib-2.0-0.dll
libglibmm-2.4-1.dll
libgmodule-2.0-0.dll
libgobject-2.0-0.dll
libgomp-1.dll
libgraphite2.dll
libgtk-3-0.dll
libgtkmm-3.0-1.dll
libharfbuzz-0.dll
libiconv-2.dll
libintl-8.dll
libjpeg-8.dll
liblcms2-2.dll
liblensfun.dll
liblzma-5.dll
libpango-1.0-0.dll
libpangocairo-1.0-0.dll
libpangoft2-1.0-0.dll
libpangomm-1.4-1.dll
libpangowin32-1.0-0.dll
libpcre-1.dll
libpixman-1-0.dll
libpng16-16.dll
librsvg-2-2.dll
libsigc-2.0-0.dll
libstdc++-6.dll
libsystre-0.dll
libthai-0.dll
libtiff-5.dll
libtre-5.dll
libwinpthread-1.dll
libxml2-2.dll
zlib1.dll
```

**Comment by Beep6581** [comment]
Stale.
