### ISSUE TITLE
newlocallab

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#4808]
@Desmis Jacques, I would like to merge dev into newlocallab. Ok?

**Comment by Desmis** [comment]
Ok :)


Le sam. 15 sept. 2018 20:14, Ingo Weyrich <notifications@github.com> a
écrit :

**Comment by heckflosse** [comment]
@Desmis Jacques, merged and pushed. I hope all still works as expected.

**Comment by Desmis** [comment]
@heckflosse 
Ingo
I have not been at home yesterday...
I just push "newlocallab", all seems to work fine :)

Thank you
Jacques
