### ISSUE TITLE
review of 'float *ImProcFunctions::CompressDR(float *Source, int W_L, int H_L, float Compression, float DetailBoost, float *Compressed)' in 'rtengine/ipwavelet.cc'

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#4815]
While looking at Coverity issue `185778 Resource leak` I detected that above mentioned function clearly needs a review...

**Comment by heckflosse** [comment]
The changes from above give the same output as before with far less code in about 1/3 of processing time and also fix Coverity issue 185778

**Comment by Desmis** [comment]
@heckflosse 
Ingo
Tested and works fine :)
Good work

jacques
