### ISSUE TITLE
Allow codesign on macOS

### ISSUE THREAD

**Issue by Benitoite** [Beep6581/RawTherapee#4817]
To allow one to codesign RT on mac, it is necessary to adapt tools/osx/macosx_bundle.sh in order to:

- [x] Part 1: Make the `Frameworks` dir flat.
https://github.com/Beep6581/RawTherapee/pull/4816

- [x] Part 2: `codesign` the `.app` and `.dmg`
https://github.com/Beep6581/RawTherapee/pull/4819  We pass the signing identity thru a cmake parameter. Then macosx_bundle.sh signs the `app` before making the `dmg`, and signs the `dmg` before making the `zip`.

- [x] Part 3: document in [RawPedia](http://rawpedia.rawtherapee.com/MacOS#Compiling).

💈

**Comment by Benitoite** [comment]
Part 2: https://github.com/Beep6581/RawTherapee/pull/4819

This allows the mac build to be codesigned by the macosx_bundle.sh script.
If the builder leaves out the `-DCODESIGNID:STRING=` parameter, the build still works ok without signature.

**Comment by Beep6581** [comment]
PRs for parts 1 and 2 merged.

**Comment by Benitoite** [comment]
Thanks @Beep6581 
Part 3: http://rawpedia.rawtherapee.com/MacOS#Compiling has been updated to include:

If you wish to codesign your build, add to the cmake command with your details:
`-DCODESIGNID:STRING="Developer ID Application: Firstname Lastname (XXXXXXXXXX)"`
The app and the generated `dmg` will be codesigned.

**Comment by Beep6581** [comment]
@Benitoite fantastic, thank you :+1:
