### ISSUE TITLE
PixelShift for Panasonic G9 and Olympus OM-DE M1

### ISSUE THREAD

**Issue by Desmis** [Beep6581/RawTherapee#4820]
@heckflosse 

Ingo
Do you plan to program your very good "pixelshift" for Panasonic G9 and Olympus OM-DE M1.
Only for intellectual reasons, I tried to read a high resolution image of G9, to compare a 4/3 sensor with a sony 24 * 36... to see differences, and of course it does not work :)

Currently pixelshift only works for Pentax and Sony

Thank you
Jacques

**Comment by heckflosse** [comment]
@Desmis Jacques, as far as I know the pixelshift raw files from Panasonic and Olympus contain just one frame which is already combined. Pentax and Sony pixelshift raw files contain the 4 individual frames which can then be combined and motion corrected in rt. Unfortunately that's not possible if the frames are already combined in camera.

**Comment by Desmis** [comment]
OK
Thank you :)

**Comment by ff2000** [comment]
@heckflosse: I know Olympus spits out one single frame as seperate RAW file (AFAIR named .ori) together with the combined pixel shift file. I don't know if it is possible to use this to auto-correct movement. It usually is used to manually correct movement.
For Panasonic I think they do the same.

**Comment by Desmis** [comment]
I am not sure to all understand, as usual my english is bad. It seems thats in Panasonic there is a shift of half pixels, and 8 frames. It's leads to x2 resolution, and obviously results are very good (this assumes that the subject, the image is absolutely static)
Of course, algorithm (must be) is different ??

Three links :
https://www.bhphotovideo.com/explora/photography/tips-and-solutions/pixel-shift-shootout-olympus-vs-pentax-vs-sony-vs-panasonic
https://www.dpreview.com/forums/thread/4251525
https://creativityinnovationsuccess.wordpress.com/2017/11/22/the-panasonic-lumix-dc-g9-80-megapixel-high-resolution-mode-and-portraiture-old-and-new/

**Comment by heckflosse** [comment]
I had a look at the links from above. If I understood correctly, there is no way to get the individual raw frames from Oly/Pana pixelshift files.

**Comment by Desmis** [comment]
OK, thank you :)
