### ISSUE TITLE
Save Reference Image generates a 16-bit Float TIFF

### ISSUE THREAD

**Issue by agriggio** [Beep6581/RawTherapee#4824]
As the subject says, using "save reference image" results in a 16-bit float TIFF, which then causes troubles to dcamprof/argyll. I think this was unintentional, caused by 30efa5930da20985d47c6706f2801245f68798af (the signature of `ImageIO::saveTIFF` was changed, and the code in `improccoordinator.cc` not updated accordingly).

Here's the patch:

```diff
diff --git a/rtengine/improccoordinator.cc b/rtengine/improccoordinator.cc
--- a/rtengine/improccoordinator.cc
+++ b/rtengine/improccoordinator.cc
@@ -1354,7 +1354,7 @@
 
     im->setMetadata(imgsrc->getMetaData()->getRootExifData());
 
-    im->saveTIFF(fname, 16, true);
+    im->saveTIFF(fname, 16, false, true);
     delete im;
 
     if (plistener) {
```

Ping @Hombre57

**Comment by Hombre57** [comment]
@agriggio Yes, I've overlooked this occurence, sorry. Please commit.
