### ISSUE TITLE
Fuji X-T3 raw files are missing a few rows at the bottom

### ISSUE THREAD

**Issue by agriggio** [Beep6581/RawTherapee#4825]
It seems that X-T3 raw files get decoded with a few missing rows at the bottom of the frame. See for instance one of dpreview's studio scene RAF files, and compare with the embedded jpg. Using camconst doesn't seem to be enough, I had to resort to the following patch to make the missing rows reappear. I'd appreciate a code review though.

ping @heckflosse 

```diff
diff --git a/rtengine/dcraw.cc b/rtengine/dcraw.cc
--- a/rtengine/dcraw.cc
+++ b/rtengine/dcraw.cc
@@ -9084,6 +9084,9 @@
     parse_tiff (thumb_offset+12);
 /*RT*/    exif_base = thumb_offset+12;
     apply_tiff();
+    if (!strcmp(model, "X-T3")) {
+        height = raw_height - 2;
+    }
     if (!load_raw) {
       load_raw = &CLASS unpacked_load_raw;
       tiff_bps = 14;
```

**Comment by heckflosse** [comment]
@agriggio Alberto, there also seems to be a black border at the right

**Comment by agriggio** [comment]
@heckflosse I was using the `camconst.json` entry you posted on pixls to fix that. Do you prefer to hardcode it in `dcraw.cc`?

**Comment by heckflosse** [comment]
@agriggio No, we should include it in official camconst.json and only hardcode the change from your patch

**Comment by sguyader** [comment]
The fact that RawTherapee was able to open X-T3 raw files even with wrong borders, gave some free advertisement for RT on dpreview, since people who wanted to check raws on their side couldn't do it with the official Adobe software!

**Comment by heckflosse** [comment]
@agriggio Alberto, in case you add the raw crop for x-t3 to camconst.json, can you please also unify the two entries for `Sony ILCE-7M3` ?
https://github.com/Beep6581/RawTherapee/blob/dev/rtengine/camconst.json#L2301
https://github.com/Beep6581/RawTherapee/blob/dev/rtengine/camconst.json#L2336

**Comment by agriggio** [comment]
sure

**Comment by heckflosse** [comment]
@agriggio Alberto, will you make the changes to camconst.json or shall I include them into the patch from #4585 ?

Edit: scratch my question. I didn't see your commit
