### ISSUE TITLE
Selecting multiple images in browser crashes RT

### ISSUE THREAD

**Issue by mattiaverga** [Beep6581/RawTherapee#4828]
Rawtherapee 5.4 from Fedora 28 RPMs
If I try to select two or more images in browser tab either by shift-clicking or shift-arrow Rawtherapee crashes.
See [backtrace.txt](https://github.com/Beep6581/RawTherapee/files/2407838/backtrace.txt).

https://retrace.fedoraproject.org/faf/reports/2317502/

**Comment by Beep6581** [comment]
@mattiaverga cannot reproduce in Fedora 28 using RT 5.4 from the repo, nor using a debug build of the latest dev.

Were there any non-ascii characters in your filenames and full pathnames?

Can you reproduce using these two images?
http://rawtherapee.com/shared/test_images/amsterdam.pef
http://rawtherapee.com/shared/test_images/moon.nef

Can you compile RT yourself and reproduce using the latest dev?
http://rawpedia.rawtherapee.com/Linux

**Comment by mattiaverga** [comment]
@Beep6581 I'm one of the maintainers of RT in Fedora repos, the original bug was reported by a user and I then discovered I can reproduce it always on my own system.

I tried with the two images you provided, I put them in `/home/marvin/test/` path (so without non-ascii chars) and I still get the crash. The new backtrace is at https://bugzilla.redhat.com/show_bug.cgi?id=1632010 (the original user who reported the problem has made his report private).

I will try to compile the dev version of RT next week and see if it still crashes.

**Comment by mattiaverga** [comment]
So, it seems that the problem is in my RT options file.
I deleted RT config directory and with the default values I don't get the crash.
The problematic line is:
```
[Batch Processing]
AdjusterBehavior=0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;
```
that in my own configuration was set to:
```
[Batch Processing]
AdjusterBehavior=1;1;1;1;1;1;1;1;1;1;0;0;1;1;1;0;1;1;1;1;1;1;1;1;1;0;0;0;0;0;0;0;1;1;0;0;1;1;1;1;1;1;1;1;1;1;1;0;0;0;0;0;0;0;0;0;0;0;0;0;0;1;1;1;1;1;1;1;1;1;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;1;1;1;1;1;1;1;1;0;0;0;0;0;0;0;
```
Reverting that line to defaults solves the problem.

**Comment by Beep6581** [comment]
@mattiaverga  I could not reproduce the crash using your `AdjusterBehavior` (in Sabayon) in 5.4 or dev.

Could you try backing up your `~/.config/RawTherapee*` and `~/.cache/RawTherapee*` and seeing if you can still reproduce?

**Comment by Beep6581** [comment]
I tried both lines, but to be clear, which one is supposed to cause the crash - the all-zeros or the mixed one?

**Comment by mattiaverga** [comment]
The crash happens with the mixed line.
Also I noticed that the all zero line (which is the default created when running RT for the first time) is 130 values long, while the mixed line (which is probably inherit from a previous RT version which I upgraded) is 118.
[This](https://github.com/Beep6581/RawTherapee/files/2408790/options.txt) is the option file which in my case causes the crash.

**Comment by Floessie** [comment]
@Beep6581 @heckflosse Don't know, if that matters here, but there's a bug in [`Thumbnail::getProcParams()`](https://github.com/Beep6581/RawTherapee/blob/dev/rtgui/thumbnail.cc#L171) (as innocent as it may look). There is potential for a data race, because the lock is long gone when the reference to the data is used. Premature optimization...

HTH,
Flössie

**Comment by Beep6581** [comment]
@mattiaverga can you reproduce this in 5.5(rc*)?

**Comment by mattiaverga** [comment]
I'll give it a try as soon as possibile... which could be not before the next weekend.

**Comment by mattiaverga** [comment]
@Beep6581 I've just tried and I still get the crash.
The problematic setting is still the `AdjusterBehavior` line. If I delete it and let RT recreate it at next startup, I don't get the problem anymore.

The difference between the line in the old options file and the new seems to be in the length of the line:
 ```
[Batch Processing]
-AdjusterBehavior=0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;
+AdjusterBehavior=0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;
```

**Comment by Floessie** [comment]
@mattiaverga Does this help?

```patch
diff --git a/rtgui/options.cc b/rtgui/options.cc
index c267c4651..d9d274e7a 100644
--- a/rtgui/options.cc
+++ b/rtgui/options.cc
@@ -1283,27 +1283,27 @@ void Options::readFromFile(Glib::ustring fname)
                 if (keyFile.has_key("GUI", "HistogramPosition")) {
                     histogramPosition = keyFile.get_integer("GUI", "HistogramPosition");
                 }
-                
+
                 if (keyFile.has_key("GUI", "HistogramRed")) {
                     histogramRed = keyFile.get_boolean("GUI", "HistogramRed");
                 }
-                
+
                 if (keyFile.has_key("GUI", "HistogramGreen")) {
                     histogramGreen = keyFile.get_boolean("GUI", "HistogramGreen");
                 }
-                
+
                 if (keyFile.has_key("GUI", "HistogramBlue")) {
                     histogramBlue = keyFile.get_boolean("GUI", "HistogramBlue");
                 }
-                
+
                 if (keyFile.has_key("GUI", "HistogramLuma")) {
                     histogramLuma = keyFile.get_boolean("GUI", "HistogramLuma");
                 }
-                
+
                 if (keyFile.has_key("GUI", "HistogramChroma")) {
                     histogramChroma = keyFile.get_boolean("GUI", "HistogramChroma");
                 }
-                
+
                 if (keyFile.has_key("GUI", "HistogramRAW")) {
                     histogramRAW = keyFile.get_boolean("GUI", "HistogramRAW");
                 }
@@ -1311,11 +1311,11 @@ void Options::readFromFile(Glib::ustring fname)
                 if (keyFile.has_key("GUI", "HistogramBar")) {
                     histogramBar = keyFile.get_boolean("GUI", "HistogramBar");
                 }
-                
+
                 if (keyFile.has_key ("GUI", "HistogramHeight")) {
                     histogramHeight = keyFile.get_integer ("GUI", "HistogramHeight");
                 }
-                
+
                 if (keyFile.has_key ("GUI", "HistogramDrawMode")) {
                     histogramDrawMode = keyFile.get_integer ("GUI", "HistogramDrawMode");
                 }
@@ -1507,7 +1507,7 @@ void Options::readFromFile(Glib::ustring fname)
                     if (rtSettings.ACESp0 == "RTv4_ACES-AP0") {
                         rtSettings.ACESp0 = "RTv2_ACES-AP0";
                     }
-                    
+
                 }
 
                 if (keyFile.has_key("Color Management", "ACES-AP1")) {
@@ -1515,7 +1515,7 @@ void Options::readFromFile(Glib::ustring fname)
                     if (rtSettings.ACESp1 == "RTv4_ACES-AP1") {
                         rtSettings.ACESp1 = "RTv2_ACES-AP1";
                     }
-                    
+
                 }
 
                 if (keyFile.has_key("Color Management", "GamutLch")) {
@@ -1593,6 +1593,9 @@ void Options::readFromFile(Glib::ustring fname)
             if (keyFile.has_group("Batch Processing")) {
                 if (keyFile.has_key("Batch Processing", "AdjusterBehavior")) {
                     baBehav = keyFile.get_integer_list("Batch Processing", "AdjusterBehavior");
+                    if (baBehav.size() != ADDSET_PARAM_NUM) {
+                        baBehav.assign(ADDSET_PARAM_NUM, 0);
+                    }
                 }
             }
 
```

Best,
Flössie

**Comment by Floessie** [comment]
@Beep6581 Do you prefer a full reset (like above) if the sizes mismatch or a resize with `0`?

**Comment by Beep6581** [comment]
@Floessie a resize with `0` would probably be more user-friendly.

**Comment by Floessie** [comment]
I'll just push, it's a no brainer (even if it doesn't solve this very issue).

**Comment by mattiaverga** [comment]
I can confirm that the patch in the proposed PR fixes the issue.

**Comment by Beep6581** [comment]
@Floessie @mattiaverga can we close?

**Comment by Floessie** [comment]
@Beep6581 :+1: from me.
