### ISSUE TITLE
Raw chromatic aberration correction's Avoid Color Shift causes purple halo due to garbage pixels near edge

### ISSUE THREAD

**Issue by falket** [Beep6581/RawTherapee#4831]
With ca autocorrection and avoid color shift enable, i get a strange purple halo at the bottom of the picture.

Canon Powershot Sx 220 with CHDK, raw converted to dng with adobe dng to avoid wasting space.

Screenshots and files:

https://drive.google.com/open?id=1zmufXV6gVQA8Yfr0Cb2EtEmzRqMIjwC-

Tya.

`Version: 5.4-903-g`7e36e86
```
Branch: dev
Commit: 7e36e86
Commit date: 
Compiler: cc 6.4.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.22.2
Lensfun: V0.3.2.0
Build type: release
Build flags:  -std=c++11  -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -O3 -DNDEBUG -ftree-vectorize
Link flags:   
OpenMP support: ON
MMAP support: ON
```

**Comment by Beep6581** [comment]
Confirmed in `5.4-903-g`7e36e86df, even with iterations=1.

![screenshot_20180924_101315](https://user-images.githubusercontent.com/5844619/45942381-78807a00-bfe2-11e8-8d9d-c3de8da810b7.png)

**Comment by falket** [comment]
Thank you. Btw, why the right preview is a little bit disaligned (higher) compared to the left one? even on my pc.

**Comment by Beep6581** [comment]
It's a theme issue, #4778

**Comment by heckflosse** [comment]
That's caused by the last rows of the image which are a bit off as you can see in this screenshot (Amaze demosaic, border = 0, no ca correction). I will try to fix it...
![grafik](https://user-images.githubusercontent.com/13733487/45946603-a1f4d200-bff1-11e8-8d32-b9a16ace0061.png)

**Comment by heckflosse** [comment]
After thinking a bit more about the issue, I came to the conclusion, that trying to fix this garbage in => garbage out problem in ca correction code is not a proper solution.
We should define a raw crop in camconst.json to mask out the last one or two row, which contain the garbage.

Here's a screenshot made with raw border = 0 and demosaic none. It's clearly visible that the blue values in the last row are much too high.
![grafik](https://user-images.githubusercontent.com/13733487/45949326-d8cfe580-bffb-11e8-9524-3a340a10655d.png)

@falket Do you have more files from that camera to check whether the problem exists not only in the file you posted?

**Comment by falket** [comment]
@heckflosse uploaded here (one is "out of chdk" without being lossless compressed with dng converter, same problem): https://drive.google.com/open?id=1zmufXV6gVQA8Yfr0Cb2EtEmzRqMIjwC-

I have tried other 3 cameras with chdk but they don't have this problem.

**Comment by heckflosse** [comment]
@falket Thanks for the files :+1:
