### ISSUE TITLE
Selecting several images on the library view triggers a segfault

### ISSUE THREAD

**Issue by Dapid** [Beep6581/RawTherapee#4841]
Attempting to select any two raw files (for example, to apply the same settings) triggers an immediate core dump. ABRT has been kind enough to provide a full backtrace and version information here: https://bugzilla.redhat.com/show_bug.cgi?id=1634056 , but here are the highlights:

Error message on the terminal:
```
/usr/include/c++/8/bits/stl_vector.h:932: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = int; _Alloc = std::allocator<int>; std::vector<_Tp, _Alloc>::reference = int&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.
Aborted (core dumped)
```

RawTherapee version: rawtherapee-5.4, from the repositories, build 1.

Operative system: Fedora 28

**Comment by Dapid** [comment]
Following an idea from #4828, I cleared my cache and inspected my .config/RawTherapee/options file. It turns out I had an old flat field directory that is no longer there. I removed it, and now it works flawlessly.

**Comment by Beep6581** [comment]
@Dapid do you still have your old config file, or your old flatfield entry from the config file, or can you reproduce now by editing your options file and changing the flatfield dir?

**Comment by Dapid** [comment]
I did not keep the old config file, but I recreated it, and that did not trigger the error. My guess is that there was something on the cache.

Is the cache versioned? A solution would be to read the version of RT that created it, and if it differs, nuke it.
