### ISSUE TITLE
Lumix DMC-FZ45 raw preview rendered in black and white

### ISSUE THREAD

**Issue by falket** [Beep6581/RawTherapee#4846]
Hello everyone,

 i was playing with a raw took with the Lumix DMC-FZ45 here:

https://raw.pixls.us/getfile.php/2580/nice/Panasonic%20-%20DC-FZ45%20-%204:3.RW2

The preview using neutral profile is in black and white. Output seems ok.

Version: 5.4-909-g5073303
Branch: dev
Commit: 5073303
Commit date: 
Compiler: cc 6.4.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.22.2
Lensfun: V0.3.2.0
Build type: release
Build flags:  -std=c++11  -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -O3 -DNDEBUG -ftree-vectorize
Link flags:   
OpenMP support: ON
MMAP support: ON

Thank you in advance.

**Comment by heckflosse** [comment]
Works fine here using rt 5.4-918.
Left is using neutral profile. Right is neutral profile + 'black and white'
![screenshot_2018-10-01_17-04-23](https://user-images.githubusercontent.com/13733487/46297076-1a343800-c59c-11e8-9dcc-d26309b91bfe.png)

**Comment by Beep6581** [comment]
Works fine here too.

Having said that, I wanted to check the color matrix, and the metadata reported using Exiv2 and ExifTool shows:
```
Model=DC-FZ45
```
However, there is no mention of that model on Panasonic's website nor in Google, and our `rtdata/dcpprofiles/camera_model_aliases.json` doesn't handle it. There is a "D**M**C-FZ45" but no "DC-FZ45". Adobe DNG Converter doesn't identify the raw file as a supported format, so I wonder what's going on.

@falket have you edited that raw file in any way? Have you edited its metadata? Have you downloaded it from the camera using anything other than copying the file over using your file manager? Nikon's camera image downloading utility was known to alter and corrupt raw files, for example.

**Comment by falket** [comment]
Tried with 919 it works. And retried with 908 works again.... sorry i don't understand what's happened.

I haven't edited the file in any way (md5sum is 554d7325536578cfacbea7e10e9128bc ).

There are other raw samples on photographyblog.com . Here the camera is DMC-FZ45, i don't know what happened with raw.pixls.us samples. Btw, i don't have the camera, i was just playing since i saw one.

Found out there is a also a similar problem of #4831, if you try for example with 2nd raw second column raw sample (London's bridge) in the review on  photographyblog.com  (Raw chromatic aberration correction's Avoid Color Shift causes purple halo due to garbage pixels near edge )

Thank you again.

**Comment by Beep6581** [comment]
Ok, closing as invalid.
