### ISSUE TITLE
not responding

### ISSUE THREAD

**Issue by LanaDmitreva** [Beep6581/RawTherapee#4848]
Hello!
I often stop the program when working with the conductor 
![fvxcgfg](https://user-images.githubusercontent.com/43805985/46395181-fdffda80-c704-11e8-82ad-f79c6e8c2e76.jpg)
. With other such problems there.
My system is Windows 10, Motherboard P7P55D-E, Xenon x3470, 12Gb RAM, ATI radeon 7850, SSD 120 Gb Samsung EVO

**Comment by Thanatomanic** [comment]
What are you reporting actually?

**Comment by LanaDmitreva** [comment]
Here's a [video](https://youtu.be/kcY1uM1tdsc), [video 2](https://www.youtube.com/watch?v=MAz7FtTFYRU), still very slowly starting. What can be done?

**Comment by Thanatomanic** [comment]
The slightly slow startup is something I recognize. The program locking up should be fixed in version 5.5: see #4576. For now, let the folder load before you switch.

**Comment by LanaDmitreva** [comment]
Ok 😊
