### ISSUE TITLE
Crash on startup when reading folder with corrupt DNGs

### ISSUE THREAD

**Issue by st-tsourkan** [Beep6581/RawTherapee#4853]
RT version: 5.4 (Win7/Win10 x64). I can't to write version exactly, because my RT can't start (crashes).

1. In folder was damaged photos (DNG files from Pentax, which were bad copied from damaged hard drive). RawTherapee has crushed.
2. When I've restarted RawTherapee, it crushed again at start (program window appeared at screen for 0,5 second and disappeared). RT can't start normally.
3. I have deleted folder with damaged photos (I've hope that RT will open default folder), but RT still crushes at start. I've delete RT from my PC, installed it back (to other folder), but it still crushes!

Tell me please, where RT saves information about last opened folder. In c:\ProgramData I've found nothing, in applicatyion folder (c:\ProgramFiles\RawTherapee\5.4) to.

P.S. I can't make any screenshot, 'cause my RT can't start.

**Comment by Beep6581** [comment]
@st-tsourkan please upload some sample corrupt DNG files using https://filebin.net/

**Comment by Beep6581** [comment]
No reply - closing.
