### ISSUE TITLE
Make initial size of splash screen window fit splash image

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4855]
When running RT for the first time (clean config folder), the splash screen window is much larger than the splash screen image. Doesn't look professional. The default size should shrink to fit the contents.

**Comment by Beep6581** [comment]
Actually, the first thing the user sees is the "Release Notes" tab of the "About" window. While the release notes look fine when the window is large, if you switch to the "Splash" tab, then it looks bad.

![screenshot_20181007_214629](https://user-images.githubusercontent.com/5844619/46586145-7d313d80-ca7a-11e8-812d-a8bb104f38ac.png)
![screenshot_20181007_214635](https://user-images.githubusercontent.com/5844619/46586146-7d313d80-ca7a-11e8-8490-ebd97e85b584.png)

**Comment by heckflosse** [comment]
@Beep6581 Imho this can be closed.

**Comment by Beep6581** [comment]
Yes, invalid and duplicate of  #4918
