### ISSUE TITLE
Curve adjustment point pipette sometimes unresponsive

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4859]
`5.4-942-g`b9fe496d9

Using the Lab HH curve for instance, when I am zoomed-to-fit, enable Lab, enable the HH curve, and then enable the curve pipette, hovering over the canvas does not produce the white vertical line as it should until I do something which refreshes the preview, e.g. click it or zoom in/out or drag it.

If I turn the picker off and on again, the bug repeats itself. Some event goes missing.

**Comment by heckflosse** [comment]
That sounds like a fallout from my latest optimizations. I will take a look

**Comment by Beep6581** [comment]
@heckflosse thank you, I confirm the fix.
