### ISSUE TITLE
mac clang 3.9.1 error on initialize variable-sized array

### ISSUE THREAD

**Issue by Benitoite** [Beep6581/RawTherapee#4862]
I am receiving this error with clang 3.9.1:
```

/Users/tune/repo-rt/rtengine/FTblockDN.cc:808:31: error: variable-sized object may not be initialized
            float *LbloxArray[denoiseNestedLevels * numthreads] = {};
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/tune/repo-rt/rtengine/FTblockDN.cc:809:32: error: variable-sized object may not be initialized
            float *fLbloxArray[denoiseNestedLevels * numthreads] = {};
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```
Introduced in @heckflosse https://github.com/Beep6581/RawTherapee/commit/bf13654a67320a73ef778b047c5f44fcb3f6927e#diff-230d9b623490c3e055ae81276bf45dd2R808

@heckflosse Had a solution for this before also:
https://github.com/Beep6581/RawTherapee/commit/b762804b809889e8e1fd81a244820d2e3d27cdd8

**Comment by Benitoite** [comment]
Thx @Floessie fix compiles!

**Comment by Floessie** [comment]
@Benitoite Yeah, tested it with Clang 3.9.1 under Linux. :smile:
