### ISSUE TITLE
Batch Edit Fails

### ISSUE THREAD

**Issue by Lowkus** [Beep6581/RawTherapee#4863]
Version: 5.4
Branch: 5.4
Commit: a5e8eb9c8
Commit date: 2018-03-20
Compiler: gcc 7.3.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.22.0
Lensfun: V0.3.2.0
Build type: release
Build flags:  -m64 -mwin32 -mthreads -Wno-aggressive-loop-optimizations -std=c++11 -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations  -DNDEBUG  -O3
Link flags: -m64 -mthreads  -static-libgcc   -mtune=generic  -s -O3 -fno-use-linker-plugin
OpenMP support: ON
MMAP support: ON

Intel Core i7-6900K CPU @ 3.2Ghz
128GB Installed Memory
64-Bit OS (Win7)

Problem: Editing pictures in the batch editor will change the thumbnail appearance, but the files do not maintain the edits once they are opened in the editor.

Steps:
1) Edit one of several raw pictures in the editor.
2) Use the file browser, batch mode.
3) Select the edited picture and the other unedited pictures.
4) Click the + on each modified property so that all the pictures have the same values.
5) Click the - on each modified property to bring the values back to matching the original edited values.
6) Open the Editor.  Notice the thumbnails appear to have the changed batch values.
7) Look through the batch edited pictures using the Editor.  Each picture that is opened will revert to its appearance from before the batch editing was applied.  Effectively the batch editing is not actually applied to any of the images.

This screenshot is mask-darkened to put focus on the thumbnail that is about to be double-clicked.  You can see that the thumbnail is bright, it is the result of a batch edit to bring up exposure on the thumbnails.
![beforeopening_01](https://user-images.githubusercontent.com/33506088/46893764-efad6f00-ce26-11e8-9ab5-a3ac188c6a5c.png)

This screenshot is not masked in any way, the thumbnail was opened, the picture immediately reverted to what it looked like before it was batch edited (it was a dark exposure before the batch edit).  The thumbnail immediately darkened to match the loaded picture.  This behavior will happen when I open any of the batch edited pictures.
![afteropening_01](https://user-images.githubusercontent.com/33506088/46893763-efad6f00-ce26-11e8-9e59-4b39622e2943.png)

**Comment by heckflosse** [comment]
> 128GB Installed Memory

nice :+1:

**Comment by Beep6581** [comment]
Hi @Lowkus 

I cannot reproduce the problem.

Please write the steps to reproduce with more details, and include the following info:
* A screenshot of Preferences > Image Processing
* A screenshot of Preferences > Dynamic Profile Rules
* A screenshot of Preferences > Batch Processing
* Which specific tool and sliders you used.

A video recording would be best.
https://getsharex.com/

**Comment by Beep6581** [comment]
No response - closing.
