### ISSUE TITLE
32-bit int and float and 16-bit float TIFF files do not appear in File Browser

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4868]
32-bit floating-point and integer and 16-bit floating-point files (all uncompressed) do not appear in the File Browser, and nothing in the console.

Samples:
https://filebin.net/ibf01swz2pxw3avu

```
Version: 5.4-946-g81dd3dc3d
Branch: dev
Commit: 81dd3dc3d
Commit date: 2018-10-14
Compiler: cc 6.4.0
Processor: Intel(R)\ Core(TM)\ m3-6Y30\ CPU\ @\ 0.90GHz
System: Linux
Bit depth: 64 bits
Gtkmm: V3.22.2
Lensfun: V0.3.2.0
Build type: release
Build flags:  -std=c++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -O3 -DNDEBUG -ftree-vectorize
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON
```

@Hombre57 mentioned that 32-bit files should be supported as input, so tagging this as a bug.

**Comment by heckflosse** [comment]
Confirmed for uncompressed files

**Comment by Beep6581** [comment]
The alpha channel caused the file to be skipped.

Could RT handle files with an alpha channel, just ignore it? They are extremely common, in fact now that GIMP-2.10 is available we have the option of automatically adding an alpha channel when opening an image.

**Comment by Hombre57** [comment]
@Beep6581 @heckflosse Fix is in the `gimp-hdr-files` branch. I've added support (i.e. ignoring) of alpha channel for LogLuv data format too, untested.

**Comment by Beep6581** [comment]
Fix confirmed in 16-bit float and int and 32-bit float (LogLuv not tested), thank you @Hombre57
