### ISSUE TITLE
TP_GAMMA_OUTPUT in Preferences > Batch Processing

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4871]
Preferences > Batch Processing shows an entry "TP_GAMMA_OUTPUT"

**Comment by Desmis** [comment]
fixed with commit 726990

**Comment by Beep6581** [comment]
For reference, the commit:
https://github.com/Beep6581/RawTherapee/commit/72699902a3f8064aee1fd1c2fbaae8a19f9368b2

Ah! Thank you @Desmis :)
