### ISSUE TITLE
Clicking thumbs and switching tabs very slow

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4873]
I deleted my `options` file and the `cache`, then compiled and ran `5.4-959-g`009c1082f

Switching tabs when I start RT is instant, but clicking thumbs or switching tabs takes about a second once I select a thumb.

Here's a video:
https://filebin.net/e5nn147lq268xmyc/vid1-2018-10-17_20.00.51.mp4?t=immwchw6

```
Version: 5.4-959-g009c1082f
Branch: dev
Commit: 009c1082f
Commit date: 2018-10-17
Compiler: cc 6.4.0
Processor: Intel(R)\ Core(TM)\ m3-6Y30\ CPU\ @\ 0.90GHz
System: Linux
Bit depth: 64 bits
Gtkmm: V3.22.2
Lensfun: V0.3.2.0
Build type: release
Build flags:  -std=c++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -O3 -DNDEBUG -ftree-vectorize
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON
```
`gtk+-3.22.30`

**Comment by Beep6581** [comment]
Just tried in `5.4-957-g`7388a9a5e and it's fine there, so it was something in PR #4857 which caused this.
@Floessie can you reproduce, and is there any other info I can provide?

**Comment by Beep6581** [comment]
I just compiled `5.4-961-g`a7f64a53a and can no longer reproduce...
Will close this issue tomorrow if I still can't reproduce.

**Comment by ff2000** [comment]
I also observed some weird behaviour since that change:
Scrolling in the File Browser is wonky.
Sometimes scrolling down with the mouse will scroll the view upwards. I thought twice I spotted a pattern but that wasn't true.
// edit: made an error when branching. Need to recompile once again which will unfortunately take quite some time... Sorry for the noise!
// edit 2: reverted 2125f42 and the problem persists. So this is a seperate issue.

**Comment by Floessie** [comment]
@Beep6581 @ff2000 I know this big change looks scary at first, but the changes are about making it harder to do something stupid. Thus it should theoretically contain less errors than before. But of course there can be new regressions that I introduced. That said, please keep on testing the new code. I'll be back on Monday and will try to sort things out.

Best,
Flössie

**Comment by Beep6581** [comment]
When I ran into this problem I tried rebooting and could still reproduce after rebooting several times.

I stopped being able to reproduce once I recompiled. Several reboots later and with a web browser and VirtualBox running, I still cannot reproduce, so closing.
