### ISSUE TITLE
"processing profile -> reset to default" and "processing profile -> clear" seem broken

### ISSUE THREAD

**Issue by agriggio** [Beep6581/RawTherapee#4874]
The above functions from the film strip contextual menu seem to be broken. Nothing happens. I suspect this is a side-effect of the new optimizations to avoid reprocessing thumbnails. Since "reset to default" is currently the only way to force the re-application of a dynamic profile, I'll mark this as urgent.
Ping @heckflosse

**Comment by heckflosse** [comment]
I will have a look

**Comment by agriggio** [comment]
Thanks for the quick fix! :+1:
