### ISSUE TITLE
Building on Ubuntu 18:04 works but cannot open any files

### ISSUE THREAD

**Issue by danwalmsley** [Beep6581/RawTherapee#4878]
I managed to build the dev branch on 18:04 and run it.

However when I try to browse to a folder with images in it, none are shown.

The version i installed with apt-get install rawtherapee works btw.

Any ideas what could be the problem? Thanks

**Comment by Beep6581** [comment]
@danwalmsley you haven't provided any useful information.
http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports

**Comment by danwalmsley** [comment]
1) dev branch
2) 
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

Step 1) build
Step 2) run rawtherapee
Step 3) locate in the folder browser a folder containing image files. (our file attached)
[card.zip](https://github.com/Beep6581/RawTherapee/files/2492688/card.zip)
Step 4) see no files shown in the folder browser.

![screenshot from 2018-10-18 17-09-33](https://user-images.githubusercontent.com/4672627/47168386-a6629100-d2f8-11e8-914c-602712f07f01.png)

**Comment by danwalmsley** [comment]
again installing official build, it works,

but when I build myself it doesnt, I also tried some other tagged versions and they dont work either.

not sure what other information I can provide?

**Comment by Thanatomanic** [comment]
I can at least verify that your file can be opened in my own dev build.

**Comment by danwalmsley** [comment]
Is there a log or something I can provide, could it be a missing dependency wrong verision library, btw there are no exceptions or error messages printed out to console either.

**Comment by Beep6581** [comment]
@danwalmsley try
```
rm -rvI ~/.config/RawTherapee*
```

Then ensure that Preferences > Parsed Extensions includes your file types.

**Comment by Beep6581** [comment]
User support is via the forum.

**Comment by danwalmsley** [comment]
> @danwalmsley try
> 
> ```
> rm -rvI ~/.config/RawTherapee*
> ```
> Then ensure that Preferences > Parsed Extensions includes your file types.

The rm command fixed the issue, thank you for your excellent developer support.
