### ISSUE TITLE
Nikon Z7 initial camconst entry

### ISSUE THREAD

**Issue by agriggio** [Beep6581/RawTherapee#4880]
Colour matrix from the Adobe DNG converter 11.0, and PDAF lines info from Bill Claff:

```javascript
    { // Quality C, only colour matrix and PDAF lines info
        "make_model" : "Nikon Z 7",
        "dcraw_matrix" : [10405,-3755,-1270,-5461,13787,1793,-1040,2015,6785], // Adobe DNG Converter 11.0 ColorMatrix2
        "pdaf_pattern" : [0, 12],
        "pdaf_offset" : 29
    },
```
The PDAF info can be used to fix the banding affecting shadows of the Z7 under some circumstances -- RT is currently the only tool that can do that autmatically (more info [here](https://www.dpreview.com/forums/post/61814192))

**Comment by heckflosse** [comment]
I added a `Camera Support` Label to available labels and assigned it to the issue

**Comment by Beep6581** [comment]
Hi @heckflosse 
The intention behind the already-existing "[raw](https://github.com/Beep6581/RawTherapee/issues?q=is%3Aopen+is%3Aissue+label%3Araw)" label is to apply to issues related to [support for raw formats](http://rawpedia.rawtherapee.com/Adding_Support_for_New_Raw_Formats) - dcraw, camconst, etc. Do we need a new label?

**Comment by heckflosse** [comment]
@Beep6581 I thought the "raw" label was for issues related to raw processing. My bad.
