### ISSUE TITLE
Zoom to 1:1 does not update the view

### ISSUE THREAD

**Issue by Thanatomanic** [Beep6581/RawTherapee#4883]
This has been happening recently. Whenever I work in 'fit crop' mode, or otherwise zoomed out and then go to 1:1 zoom, the image zooms but stays pixelated. So the processing pipe isn't run?
When I pan the image, it does get updated.

Side-note: this is now the 600th active issue. Hurray? 😉

**Comment by heckflosse** [comment]
Sounds like a fallout from my recent optimizations. Though I can not reproduce here.

**Comment by TooWaBoo** [comment]
I can't reproduce it either.

**Comment by Thanatomanic** [comment]
Here's an example of what happens: https://filebin.net/2lx13ph0si57dalv
I also notice that when I have gone to 1:1 the cursor behaves strangly, as if there is some hidden element blocking input.

**Comment by Thanatomanic** [comment]
FWIW: 
```
Version: 5.4-964-g18f812d96
Branch: dev
Commit: 18f812d96
Commit date: 2018-10-19
Compiler: gcc 8.2.0
Processor: undefined
System: Windows
Bit depth: 64 bits
Gtkmm: V3.22.2
Lensfun: V0.3.2.0
Build type: release
Build flags: -Wno-parentheses -std=c++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -O3 -DNDEBUG -ftree-vectorize
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON

```

**Comment by TooWaBoo** [comment]
I did a clean compilation. Can you test it if it has the same bug, please? I still can't reproduce the bug.
https://filebin.net/6xtoxilonr6qoc1c
It's a zip file, no installer.

**Comment by Thanatomanic** [comment]
@TooWaBoo I could not reproduce the problem in your build... How is that possible? 😕 

As an aside, I notice some other interesting things:
1) double clicking in the film strip does not work immediately. I have to triple click (single click = select, double click = open). This is not the behavior I see in my own latest dev-build.
2) ~~Zoom factors are retained when opening a new image. If I am at 1:1 zoom in one picture, and open another one from the filmstrip the zoom stays at 1:1. I don't remember how the behavior was in 5.4, but this is again different from what I experience in my own latest dev-build.~~
3) Your build appears to be much faster in showing the images than my own. Uh...? Why?

Edited a little.

**Comment by heckflosse** [comment]
@Thanatomanic 
![grafik](https://user-images.githubusercontent.com/13733487/47307313-075ad380-d62f-11e8-9e1f-ba0b87a8f7df.png)

**Comment by Thanatomanic** [comment]
@heckflosse Thanks for showing me again that options exist for a good reason...

**Comment by Thanatomanic** [comment]
@TooWaBoo On IRC @heckflosse and I have found the cause of the problem. If I set the 'Preview Demosaic Method' to 'As in PP3' everything works as expected.

**Comment by heckflosse** [comment]
I will take this. Most likely a fallout of my optimizations...

**Comment by heckflosse** [comment]
I could reproduce. Trying to fix now

**Comment by heckflosse** [comment]
This should fix it:

```diff
diff --git a/rtengine/improccoordinator.cc b/rtengine/improccoordinator.cc
index f81aabd30..6547c37b6 100644
--- a/rtengine/improccoordinator.cc
+++ b/rtengine/improccoordinator.cc
@@ -903,7 +903,7 @@ void ImProcCoordinator::updatePreviewImage(int todo, bool panningRelatedChange)
 
     // process crop, if needed
     for (size_t i = 0; i < crops.size(); i++)
-        if (crops[i]->hasListener() && (panningRelatedChange || (todo & (M_MONITOR | M_RGBCURVE | M_LUMACURVE)) || crops[i]->get_skip() == 1)) {
+        if (crops[i]->hasListener() && (panningRelatedChange || (highDetailNeeded && options.prevdemo != PD_Sidecar) || (todo & (M_MONITOR | M_RGBCURVE | M_LUMACURVE)) || crops[i]->get_skip() == 1)) {
             crops[i]->update(todo);     // may call ourselves
         }
 
```

**Comment by heckflosse** [comment]
@Thanatomanic Thanks for pushing the fix :+1:
