### ISSUE TITLE
Automatically determined parameter should always be able to be overriden by user

### ISSUE THREAD

**Issue by Thanatomanic** [Beep6581/RawTherapee#4889]
There is some discussion on how the GUI should look and behave when a checkbox exists that enables some automatic behavior. See e.g. @heckflosse and @agriggio in https://github.com/Beep6581/RawTherapee/issues/4866#issuecomment-432278164_

My opinion is that whenever an 'Auto' checkbox exists it should have the following simple behavior:
1) If it is checked, the corresponding slider should move to the automatically calculated value. _The slider should remain active._
2) If the user disagrees with the automatic value he can immediately move the slider. This uncheckes the 'Auto' checkbox.

This is different from the current behavior, because the slider actually becomes inactive when 'Auto' is checked, and the automatically calculated value is never shown to the user.

Reason enough for a change in usability?

**Comment by ff2000** [comment]
I don't really like that unlabeled checkbox. You have to hover it in order to get to know what it does. A togglebutton labeled "Auto" would make more sense to me.
Probably could be replaced with a normal button for things that really get calculated just once.

**Comment by Thanatomanic** [comment]
@ff2000 Do you know DxO PhotoLab and how they handle the automatic stuff? I'm quite a fan of their approach:
![ddtmo52](https://user-images.githubusercontent.com/6567747/47430851-cd0e4500-d79a-11e8-876f-ba083f465f6e.jpg)

**Comment by ff2000** [comment]
I don't know DxO (Linux is all I have). But that is different!
It uses a wand to signal that some automagic stuff is happening, I am quite sure this wand is only used for this specific use of an "auto" state. A checkbox is just a general widget that, especially if it isn't placed near a label. Of course we could use a specially styled checkbox. Or a togglebutton with that "wand" icon instead of an "auto" label ;)

**Comment by Beep6581** [comment]
I agree that a checkbox by itself is vague, even though one quickly learns what it does from the tooltip.

I don't know about DxO, but our "auto" state is persistent, so a checkbox is semantically perfect for the role.

I see three paths we could take:
1. Leave it as is.
2. Replace it with a toggle-button icon.
3. Prepend an "Auto" label.

My opinions:
* I don't mind 1.  
* The problem with 2 is that there is no universal symbol for "automatic", so no matter which symbol we come up with, it will still not clarify what it does for everyone, some people will still fall back to checking the tooltip.
* 3 seems ideal to me. "Auto" is nice and short, and is understood in all the languages I know, so the risk of ending up with a long label is small.

**Comment by ff2000** [comment]
If it is a unique icon like a magic wand or a wizard's hat it will be recognized, I think. Probably there will be more such automagic values in the future.
Another option would be to use those auto values as a default value and simply use a "reset to default" icon instead...

**Comment by Floessie** [comment]
> If it is a unique icon like a magic wand or a wizard's hat it will be recognized, I think.

We could turn Ingo's avatar into an icon which would make the wizardry immediately clear. :grin:

**Comment by Thanatomanic** [comment]
> I don't know about DxO, but our "auto" state is persistent, so a checkbox is semantically perfect for the role.

@Beep6581 I agree with your reasoning. My proposal would modify the current behavior slightly so that the persistance could easily be cancelled by the user. Woud you be okay with that?

**Comment by Beep6581** [comment]
@Thanatomanic I agree with your proposal.

**Comment by heckflosse** [comment]
The issues from op are fixed with 4a25633. Ok to close the issue?
