### ISSUE TITLE
improve support for float DNGs

### ISSUE THREAD

**Issue by agriggio** [Beep6581/RawTherapee#4900]
Currently, the support for DNG files with floating-point data is very limited, essentially the bare minimum to handle what HDRMerge produces. This is issue aims at improving the situation, and cover more cases.

Reference discussion (with more info and sample images):
https://discuss.pixls.us/t/help-with-a-floating-point-dng-file-and-processing-it-in-rt

I will create a branch `floatdng` to work on this. It will also incorporate the patch for #4472 (because that's part of fixing the problems)

**Comment by heckflosse** [comment]
@agriggio 

I just merged dev into floatdng branch and tested. With [this](https://raw.pixls.us/getfile.php/2433/nice/Blackmagic%20-%20Pocket%20Cinema%20Camera%20-%2012bit%20(16:9).dng) (non-float) dng I get differences:

Both are with neutral profile.

dev:
![grafik](https://user-images.githubusercontent.com/13733487/48678617-d4502500-eb85-11e8-8b78-6c59c50bad01.png)

current floatdng (with dev merged into it):
![grafik](https://user-images.githubusercontent.com/13733487/48678628-f649a780-eb85-11e8-8adb-d263796996a0.png)

**Comment by heckflosse** [comment]
@agriggio It's caused by https://github.com/Beep6581/RawTherapee/commit/632c1362c82045d78767e9a835b75b235893092f

**Comment by heckflosse** [comment]
Maybe related: https://github.com/Beep6581/RawTherapee/issues/2809

**Comment by heckflosse** [comment]
@agriggio Alberto, honouring the `BaselineExposure` tag for DNG files is a really nice addition :+1: 
But it breaks compatibility and currently crashes with [this file](https://raw.pixls.us/getfile.php/2055/nice/YI%20TECHNOLOGY%20-%20M1%20-%2012bit%20(4:3).DNG) because the `BaselineExposure` tag is read as NaN

**Comment by agriggio** [comment]
@heckflosse ok, I guess we have to decide what to do about it. I'd go for maximum compliance over backwards compatibility in this specific case, but I understand others might have different opinions. regardless, the code should be more robust wrt. bogus values, I'll see what I can do about it.

**Comment by agriggio** [comment]
@heckflosse here's a patch to apply `BaselineExposure` only for float DNGs, as discussed on IRC

```diff
diff --git a/rtengine/rawimage.cc b/rtengine/rawimage.cc
--- a/rtengine/rawimage.cc
+++ b/rtengine/rawimage.cc
@@ -503,6 +503,10 @@
         fseek (ifp, data_offset, SEEK_SET);
         (this->*load_raw)();
 
+        if (!float_raw_image) { // apply baseline exposure only for float DNGs
+            RT_baseline_exposure = 0;
+        }
+
         if (plistener) {
             plistener->setProgress(0.9 * progressRange);
         }
```

Ok to commit?

**Comment by heckflosse** [comment]
@agriggio :+1:

**Comment by agriggio** [comment]
Done. Should we merge this before 5.5? Any more testing that needs to be done?

**Comment by heckflosse** [comment]
@agriggio iirc there were still black thumbnails. Have to check again.

**Comment by agriggio** [comment]
> there were still black thumbnails

Oh, do you have an example?

**Comment by heckflosse** [comment]
@agriggio I will check when I fixed the bug I introduced with my last commit to dev...

**Comment by heckflosse** [comment]
@agriggio Found it. The file `0181_5211_16_bit_float_monochrome.dng` in the zip linked in [this post](https://discuss.pixls.us/t/help-with-a-floating-point-dng-file-and-processing-it-in-rt/9522/14) opens fine in Editor, but has a black thumbnail.

**Comment by agriggio** [comment]
thanks, I'll take a look!

**Comment by heckflosse** [comment]
@agriggio I forgot to mention, that the thumb of the file is fine in dev

**Comment by agriggio** [comment]
@heckflosse here's a patch, can you please take a look that I did it properly?

```diff
diff --git a/rtengine/rtthumbnail.cc b/rtengine/rtthumbnail.cc
--- a/rtengine/rtthumbnail.cc
+++ b/rtengine/rtthumbnail.cc
@@ -62,15 +62,15 @@
 void scale_colors (rtengine::RawImage *ri, float scale_mul[4], float cblack[4], bool multiThread)
 {
     DCraw::dcrawImage_t image = ri->get_image();
+    const int height = ri->get_iheight();
+    const int width = ri->get_iwidth();
+    const int top_margin = ri->get_topmargin();
+    const int left_margin = ri->get_leftmargin();
+    const int raw_width = ri->get_rawwidth();
+    const bool isFloat = ri->isFloat();
+    const float * const float_raw_image = ri->get_FloatRawImage();
 
     if (ri->isBayer()) {
-        const int height = ri->get_iheight();
-        const int width = ri->get_iwidth();
-        const bool isFloat = ri->isFloat();
-        const int top_margin = ri->get_topmargin();
-        const int left_margin = ri->get_leftmargin();
-        const int raw_width = ri->get_rawwidth();
-        const float * const float_raw_image = ri->get_FloatRawImage();
 #ifdef _OPENMP
         #pragma omp parallel for if(multiThread)
 #endif
@@ -110,14 +110,6 @@
             }
         }
     } else if (ri->isXtrans()) {
-        const int height = ri->get_iheight();
-        const int width = ri->get_iwidth();
-        const bool isFloat = ri->isFloat();
-        const int top_margin = ri->get_topmargin();
-        const int left_margin = ri->get_leftmargin();
-        const int raw_width = ri->get_rawwidth();
-        const float * const float_raw_image = ri->get_FloatRawImage();
-
 #ifdef _OPENMP
         #pragma omp parallel for if(multiThread)
 #endif
@@ -157,6 +149,20 @@
                 image[row * width + col][ccol] = rtengine::CLIP (val);
             }
         }
+    } else if (isFloat) {
+#ifdef _OPENMP
+        #pragma omp parallel for if(multiThread)
+#endif
+        for (int row = 0; row < height; ++row) {
+            for (int col = 0; col < width; ++col) {
+                for (int i = 0; i < ri->get_colors(); ++i) {
+                    float val = float_raw_image[(row + top_margin) * raw_width + col + left_margin + i];
+                    val -= cblack[i];
+                    val *= scale_mul[i];
+                    image[row * width + col][i] = val;
+                }
+            }
+        }
     } else {
         const int size = ri->get_iheight() * ri->get_iwidth();
```

**Comment by heckflosse** [comment]
Compiling...

**Comment by heckflosse** [comment]
@agriggio Works fine now :+1:

**Comment by agriggio** [comment]
merged, closing
