### ISSUE TITLE
Queue can not be started with only one image.

### ISSUE THREAD

**Issue by abertens** [Beep6581/RawTherapee#4903]
Hi there!

Today I downloaded last git commit 5cb42f29e3773e7ef454037e717418a2a64a61a0, from Oct 28, 2018.

I found a problem with Queue: if I put only one image on Queue, I can not activate the start button. With two or more, it works. 
It worked with my previous download from Oct 25 (fef2f73aa7d8d413551ca0a777164835afbe3445).

Best regards,
Andres Bertens

Version: 5.4-1012-g5cb42f29e
Branch: 5.4-1012-g5cb42f29e
Commit: 5cb42f29e
Commit date: 2018-10-28
Compiler: cc 6.3.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.22.0
Lensfun: V0.3.2.0
Build type: Release
Build flags:  -std=c++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -O3 -DNDEBUG -ftree-vectorize
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON

**Comment by Thanatomanic** [comment]
Thanks for the quick notice, but people are already working on it: #4902
