### ISSUE TITLE
Get rid of aehistogram files in RT cache?

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#4904]
Currently RT writes one 32kb aehistogram file per image into the Cache folder.
Afaik this file is only needed to be able to preview changes of the auto-levels clip percentage
![grafik](https://user-images.githubusercontent.com/13733487/47728350-78693f00-dc5e-11e8-927a-fc57b2a0ee48.png)
in the thumbnail.

Is writing a 32kb cache file for this single feature really needed?

Edit: currently we use the aehistogram file when doing auto-levels on a thumb. Though we could do that already when generating the thumb and write the auto-levels values in the *.txt cache file where all the other values are stored. Of course that would mean, auto-levels on a thumb would always be calculated using a constant clip% value.

**Comment by Thanatomanic** [comment]
Could you elaborate slightly on why this procedure is the way it is?

**Comment by heckflosse** [comment]
I can only guess because I didn't code that:

To be able to auto-level exposure in batch (on thumbs in filebrowser) one needs a histogram of the image data or the already calculated auto-level values.
Because there is one variable (the clip%) we can't store the calculated values in cache as they would change when changing clip%. To avoid loading the raw file again to get the image data when applying auto-levels in batch, the histogram gets written to the cache file in the aehistogram folder of the cache.

If we use a fixed clip% when calculating auto-levels in batch, we can get rid of that cache file by calculating the auto-level values when building the thumb the first time and storing the values in the cache file in the 'data' folder of the cache.

**Comment by Thanatomanic** [comment]
Honestly, I've never even tweaked the 0.02% (is it really 0.02% or actually 2%?).

How much of a difference will there be between a thumbnail at 0% and a value of 0.1 (let's take that as an extreme). If it matters only slightly, I don't think its reasonable to store the aehistogram.

**Comment by heckflosse** [comment]
@Thanatomanic 

> Honestly, I've never even tweaked the 0.02%

Same here

**Comment by heckflosse** [comment]
Some additional information:

The auto-level values calculated from the thumb are only used for the thumb. When opening a file or processing a file they are calculated again (more accurate) in case auto-levels is enabled.

**Comment by Beep6581** [comment]
Just wanted to point some things out:
* The "clip" feature has been broken for many releases #2088. Its correctly-working form hasn't been around for very long, perhaps since May 2017.
* RawTherapee switched from using Auto Levels to using Auto-Matched Tone Curve in its default profile for raw photos in January 2018.
* Clip%'s effect is subtle on most images.
* The thumbnails already aren't accurate. They don't reflect the effects of tools like Contrast by Detail Levels, CIECAM02, Retinex, Raw Black Points (perhaps a bug), and perhaps Flat Field and Dark Frame. Last I checked they also weren't color-managed.

**Comment by heckflosse** [comment]
@Beep6581 

> RawTherapee switched from using Auto Levels to using Auto-Matched Tone Curve in its default profile for raw photos in January 2018.

Yes, and I appreciate that. Though there are still raw files where the 'Auto-Matched Tone Curve' does not work because the embedded jpeg (for whatever reason) is very small (Phase One raw files for example).

**Comment by Beep6581** [comment]
Someone who buys a Phase One camera doesn't settle for auto levels ;)

**Comment by TooWaBoo** [comment]
I do not use auto-exposure. I have never got a usable result.

**Comment by Thanatomanic** [comment]
I wouldn't say I never got a pleasant result, so dismissing the auto exposure entirely  seems a bit harsh. But it's good to think about improvements for 5.6.

**Comment by heckflosse** [comment]
With above commit no new aehistogram cache files will be written. Old entries still will be used.

**Comment by Beep6581** [comment]
@heckflosse does this mean the behavior in batch mode is that a clip=0.2% is always used for new images? Info needed for docs: http://rawpedia.rawtherapee.com/Exposure#Clip_.25

**Comment by heckflosse** [comment]
@Beep6581 It means, 0.02% is always used for the thumbs of new images.

**Comment by Beep6581** [comment]
Documentation updated:
http://rawpedia.rawtherapee.com/Exposure#Clip_.25
http://rawpedia.rawtherapee.com/File_Paths#Cache
