### ISSUE TITLE
Queue Start button does not work

### ISSUE THREAD

**Issue by waxhead** [Beep6581/RawTherapee#4906]
Just a quick one, latest git pull of dev tonight and it appears that the start button in the Queue isn’t enabled, so I can’t start processing any images sitting in the queue:

```
Version: nightly-819-gcef5d1277
Branch: dev
Commit: cef5d1277
Commit date: 2018-10-30
Compiler: cc 8.2.1
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.22.2
Lensfun: V0.3.2.0
Build type: release
Build flags: -std=c++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -O3 -DNDEBUG -ftree-vectorize
Link flags: -march=native
OpenMP support: ON
MMAP support: ON
```

**Comment by Beep6581** [comment]
Probably related to #4895, handled in #4902

**Comment by agriggio** [comment]
is someone working on this? any hotfix possible?

**Comment by Thanatomanic** [comment]
Let's hope @thirtythreeforty can help out.

**Comment by thirtythreeforty** [comment]
Yep, thanks for the ping, I'm working on it, watch #4902.  @waxhead does your problem differ from the behavior described [in this comment](https://github.com/Beep6581/RawTherapee/pull/4895#issuecomment-433705990)?

**Comment by waxhead** [comment]
Hi,

I'd say the issue is the same
 I only had one image to process.

Image is still on queue, but I won't be able to do much more testing until
tonight.

Peter.

**Comment by thirtythreeforty** [comment]
OK, if you add a second image, the button will enable.  Sorry for the trouble.  It should be fixed soon.

**Comment by Beep6581** [comment]
I ran into this issue today, and can help test patches.

**Comment by thirtythreeforty** [comment]
I think I'm in good shape now, please test the linked PR!

**Comment by heckflosse** [comment]
@thirtythreeforty Tested, no issues found :+1:
