### ISSUE TITLE
Post-Resize Sharpening Contrast Threshold defaults to 0

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4909]
Post-Resize Sharpening > Contrast Threshold defaults to 0. The main Sharpening tool's Contrast Threshold defaults to 20.

**Comment by heckflosse** [comment]
I've no idea for a better pr sharpening threshold atm.

**Comment by Beep6581** [comment]
When I downscale without PRS, then open the downscaled image in RT to use the contrast mask preview to find ideal settings, I usually end up around 15-20.
