### ISSUE TITLE
Tweak Dynamic Range Compression defaults

### ISSUE THREAD

**Issue by agriggio** [Beep6581/RawTherapee#4912]
IMHO the current defaults for the Dynamic Range Compression tool are a bit too aggressive. They might work well for HDR images, but for standard ones the result tends to be too flat. I'd like to propose the following defaults:

- amount: 15-20 (I use 17, the current default is 30)

- threshold: 30 (the current one is 0)

Also, "threshold" is not a very informative name. I think "detail" is better.
Opinions?

**Comment by Beep6581** [comment]
Null problemo.
