### ISSUE TITLE
Speedup for color toning lab regions

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#4914]
I will create a new branch where I make some speedups for lab regions.

**Comment by heckflosse** [comment]
I measure on my AMD FX8350 using a 24Mp file with one lab colortoning region.

Processing time before optimizations: ~3540 ms

**Comment by heckflosse** [comment]
41b802b
Processing time: ~1460 ms

**Comment by agriggio** [comment]
\o/

**Comment by heckflosse** [comment]
dd635de
Processing time: ~1260 ms

**Comment by heckflosse** [comment]
906cf63
Processing time: ~1100 ms

**Comment by heckflosse** [comment]
e199d1e
Processing time: ~1040 ms

**Comment by heckflosse** [comment]
240f1ea
Processing time: ~1020 ms
