### ISSUE TITLE
Make splash image fit its window better

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4918]
Now that the Preferences window is resizable, by default it opens significantly larger than the splash screen, which doesn't look professional.

1. One solution would be to make the default window size fit the splash screen (would require @Hombre57 's help).
1. Another solution would be to center the splash image and to change its background color so that is blends with the window. I don't yet know whether a transparent background would work (there is a glow around the logo), and if we instead make it match the default theme's colors then it wont look good with other themes.
1. Third option, there is no Splash tab, and the image loads as a windowless image, centered on the screen during RT startup.

Any ideas?

**Comment by heckflosse** [comment]
@Beep6581 Can you show a screenshot which shows what's currently wrong with the splash screen?

**Comment by Beep6581** [comment]
The first time someone runs RT they will see the Release Notes tab in the About window. That looks fine, but if they switch to the Splash tab, they see this:
![screenshot_20181105_103911](https://user-images.githubusercontent.com/5844619/47990188-31a89880-e0e7-11e8-9e17-d9811c803917.png)

Suggestion 2 above is nonsense, it wouldn't improve anything.

A splash screen is meant to be displayed while a program loads, so suggestion 3 above is most in-line with the concept of a splash screen.

**Comment by heckflosse** [comment]
Here's how it looks on my machine:
![grafik](https://user-images.githubusercontent.com/13733487/47990807-c069e500-e0e8-11e8-9946-30df433245cc.png)

**Comment by Beep6581** [comment]
@heckflosse you're right. KDE lets you specify window rules, for example to make specific windows assume specific sizes at specific locations, and I had two rules for RawTherapee which I forgot about, they caused my default About window to be larger.

With the rules removed:
![screenshot_20181105_110832](https://user-images.githubusercontent.com/5844619/47991888-af6ea300-e0eb-11e8-9500-1a6c74ef9045.png)

**Comment by Beep6581** [comment]
Closed as invalid.
