### ISSUE TITLE
Raw ca correction 'Avoid colour shift' sometimes produces a colour shift

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#4928]
Example: Left neutral profile, middle neutral + raw ca correction + avoid colour shift, right same as middle, but with patched code

![grafik](https://user-images.githubusercontent.com/13733487/47951295-fbd8a800-df5e-11e8-95e1-905f62116279.png)

```diff
diff --git a/rtengine/gauss.cc b/rtengine/gauss.cc
index ab080a3c4..b7de67851 100644
--- a/rtengine/gauss.cc
+++ b/rtengine/gauss.cc
@@ -1143,7 +1143,7 @@ template<class T> void gaussianBlurImpl(T** src, T** dst, const int W, const int
 {
     static constexpr auto GAUSS_SKIP = 0.25;
     static constexpr auto GAUSS_3X3_LIMIT = 0.6;
-    static constexpr auto GAUSS_DOUBLE = 70.0;
+    static constexpr auto GAUSS_DOUBLE = 25.0;
 
     if(buffer) {
         // special variant for very large sigma, currently only used by retinex algorithm

```

**Comment by heckflosse** [comment]
Unfortunately the patch does not solve all cases. For example this one still shows the issue:
Left neutral profile, middle neutral + raw ca correction + avoid colour shift, right same as middle, but with patched code

![grafik](https://user-images.githubusercontent.com/13733487/47951680-4c063900-df64-11e8-93d9-c5daaa548e09.png)

**Comment by heckflosse** [comment]
Using the better double precision gaussian blur increases processing time by ~10% in case avoid colour shift is enabled. If there are no objections, I will push the patch asap

**Comment by TooWaBoo** [comment]
@heckflosse 
Where does the pink cast in the clouds is comming from?
I can't really see a different between the middle and right image.

**Comment by heckflosse** [comment]
@TooWaBoo The pink cast is a result from 'avoid colourshift'. There is quite heavy ca (or fringe) whichs correction leads to a shift of the average colour in that regions, which then leads to a wrong correction by 'avoid colour shift'.
I showed the example to show, that the issue is not solved for all cases. You can't see a difference between middle and right in last screenshot because there is no difference.

**Comment by TooWaBoo** [comment]
@heckflosse 
Ahh, I thought I'm blind. 😅
No objections to merge.
