### ISSUE TITLE
Special characters were still removed when merging `colortoning-labregions`

### ISSUE THREAD

**Issue by Thanatomanic** [Beep6581/RawTherapee#4932]
@agriggio @Beep6581 I'm not sure how, but first Floessie mentioned that special characters seem to have been removed [here](https://github.com/Beep6581/RawTherapee/pull/4893#pullrequestreview-168677151) by Alberto's editor. Then they got [fixed](https://github.com/Beep6581/RawTherapee/pull/4893/commits/fb44445f2acb061e5f017b6ea92a834e2002bcdd). Except that when the merge of the branch happened, they [appeared again](https://github.com/Beep6581/RawTherapee/commit/5e30b5ac586b38ec01fcf0a5824e8d09c851570d#diff-15796f585e0153b85a2ae16ef213f6f9). 

See now https://github.com/Beep6581/RawTherapee/blob/dev/rtdata/languages/default#L405 for example that a fix is still necessary.

**Comment by agriggio** [comment]
Sorry, I don't know what is going on. I have something misconfigured I suppose...

**Comment by Beep6581** [comment]
I fixed it by cherry-picking commit 43876abb81471cabbd6219ce6188c68056fc35b2.

**Comment by agriggio** [comment]
I have now forced Emacs to use utf-8 as the default coding system, hopefully this will solve the issue for good... sorry again
