### ISSUE TITLE
Segfault when using Tonemapping on completely black data

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#4934]
To reproduce:

1. Open the tiff from [here](https://discuss.pixls.us/t/playraw-landsat-8-image-of-lake-elton/9676?u=heckflosse)
2. apply the pp3 I attached
3. enable `Haze Removal`
4. enable `Show Depth Map`
5. set `Depth` to zero => segfault

[LC08_L1TP_171026_20170912_20170928_01_T1-Lake-Elton.tif.pp3.txt](https://github.com/Beep6581/RawTherapee/files/2545814/LC08_L1TP_171026_20170912_20170928_01_T1-Lake-Elton.tif.pp3.txt)

**Comment by ff2000** [comment]
Doesn't crash for me.
I'm on Linux.

**Comment by heckflosse** [comment]
Making debug build now to provide a bt full

**Comment by Beep6581** [comment]
No crash for me either.
![screenshot_20181104_193534](https://user-images.githubusercontent.com/5844619/47968332-d33cd500-e068-11e8-8df7-94bd76fd258a.png)

**Comment by Beep6581** [comment]
I'm a bit confused though, as the title says "completely black data" but the linked TIFF is not black, and the new title says "tonemapping" not "haze removal", so maybe I didn't test the right tool.

**Comment by heckflosse** [comment]
Setting Haze removal to 'Show depth map' using depthz value zero leads to a completely black image which then leads to a segfault if Tonemapping is enabled.

**Comment by heckflosse** [comment]
I will take this one. It's clearly a bug in the old Tonemapping
