### ISSUE TITLE
Russian translation updated

### ISSUE THREAD

**Issue by Kildor** [Beep6581/RawTherapee#4936]
Hello.
Here is subj. I've translated Russian version (some fixes, some updates) and run generateTranslationDiffs for all existed translations, because new tools have no strings in other, except default files.

There are two diffs in archive. translations.diff is full list of i18n files, russian.diff contains only Russian file, if there are any objections to update all files.

[translations.zip](https://github.com/Beep6581/RawTherapee/files/2545885/translations.zip)

**Comment by Beep6581** [comment]
Hey

As explained here https://discuss.pixls.us/t/localization-how-to-translate-rawtherapee-and-rawpedia/2594 please upload the file `Russian`, not a patch.

**Comment by Beep6581** [comment]
@Kildor I managed to use your diff, but in the future please send the `Russian` file, not a patch.
