### ISSUE TITLE
TooWaBlue: Warning in console

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#4941]
Using TooWaBlue theme I get the following warning in console:

```
Gtk-WARNING **: 08:19:21.883: for_size smaller than min-size (16 < 17) while measuring gadget (node button, owner GtkToggleButton)
```

No warning when using RawTherapee theme

**Comment by gaaned92** [comment]
same here

`(rawtherapee.exe:15268): Gtk-WARNING **: 20:18:30.961: for_size smaller than min-size (19 < 20) while measuring gadget (node button, owner GtkToggleButton)`

**Comment by TooWaBoo** [comment]
Yes, I know but I couln't find the culprit yet and I don't know how this could happen but I'm working on it.

**Comment by TooWaBoo** [comment]
Yeah, found it, it was the recent folder list combobox. Fix provided.

**Comment by heckflosse** [comment]
@TooWaBoo Fix confirmed. Thank you :+1:

**Comment by TooWaBoo** [comment]
This can be closed.
