### ISSUE TITLE
openSUSE compilation is not working as described

### ISSUE THREAD

**Issue by Thanatomanic** [Beep6581/RawTherapee#4947]
Looking at this issue #4752 I tried building the latest dev on openSUSE Leap 42.3. However, I run into multiple issues and have so far not built RT succesfully. The goal of this issue is to list the problems so that the docs may be updated at some point.

- Requires `sudo zypper git`
- By default GCC 4.8 is installed, which is not enough for RT. Updating is rather difficult, but this worked (substituting for gcc-8): https://askubuntu.com/questions/26498/how-to-choose-the-default-gcc-and-g-version
- Compiler script hangs on lensfun, even though it is installed...

To be continued...

**Comment by Thanatomanic** [comment]
Additional things needed to get through the build script and start building:
- Need to build and install `lensfun` from scratch
- Need to build and install `libiptcdata` from scratch
- `sudo zypper libcanberra-gtk3-devel`

Only to almost immediately stop building on an error
```
In file included from /usr/include/glibmm-2.4/glibmm.h:91,
                 from /home/roel/programs/code-rawtherapee/rtexif/rtexif.h:32,
                 from /home/roel/programs/code-rawtherapee/rtexif/stdattribs.cc:26:
/usr/include/glibmm-2.4/glibmm/threads.h: In member function ‘GPrivate* Glib::Threads::Private<T>::gobj()’:
/usr/include/glibmm-2.4/glibmm/threads.h:661:29: error: cannot convert ‘GPrivate’ {aka ‘_GPrivate’} to ‘GPrivate*’ {aka ‘_GPrivate*’} in return
   GPrivate* gobj() { return gobject_; }
```

I am out of my depth here and fear that many more modifications will be necessary. @Beep6581 Suggestion to remove openSUSE Leaf 42.3 from the supported builds for RT 5.4 / 5.5.

**Comment by Thanatomanic** [comment]
I've tried openSUSE Leaf 15.0 which works already much better out of the box.

Assuming you have a working compiler setup you need:
```
sudo zypper cmake gtk3-devel gtkmm3-devel liblcms2-devel fftw3-devel libitpcdata-devel libtiff-devel libjpeg-devel libcanberra-gtk3-devel
```

lensfun needs to be installed manually unfortunately

```
wget https://sourceforge.net/projects/lensfun/files/0.3.2/lensfun-0.3.2.tar.gz
tar xvf lensfun-0.3.2.tar.gz
cd lensfun-0.3.2.tar.gz
mkdir build
cd build
cmake ../
make
sudo make install
```

Afterwards running `./build-rawtherapee` seems to work like a charm.
**Update**: yes RT runs!

**Comment by Beep6581** [comment]
@Thanatomanic lets update the docs tailoring them to openSUSE 15.

**Comment by Thanatomanic** [comment]
RawPedia has been updated.
