### ISSUE TITLE
Artifacts caused by weighted standard tone curve

### ISSUE THREAD

**Issue by hholtm** [Beep6581/RawTherapee#4948]
Take a raw (dng) with a highlighted area, e.g. sun, 

1. open with profile auto-matched curve iso low
2. activate tonecurve 2 / custom / weighted standard
3. change tonecurve: artefacts ocure in highligted area
4. change mode to any other than weighted standard: everything is ok

I tested this behavior with RT-dev-1091. No artefact could be seen even with tonecurve 2 / custom / weighted standard.

So I'm not sure is something unexpected in dev-1098 or should tonecurve 2 / custom / weighted standard not be used with dng and highlighted area? Perhaps someone can give a hint.

Heinrich

**Comment by Thanatomanic** [comment]
If possible can you provide:
- a screenshot
- a dng + pp3 file for us to test

**Comment by hholtm** [comment]
I forgot:
I'm using RT with Win10/64

**Comment by hholtm** [comment]
![t1](https://user-images.githubusercontent.com/39562391/48260392-9fbcca80-e41b-11e8-9522-242f2f302f5b.JPG)
first without using toncurve 2, second with changed tonecurve

**Comment by hholtm** [comment]
files: https://filebin.net/ykhci069uyxs5q96

**Comment by heckflosse** [comment]
Confirmed
