### ISSUE TITLE
Document Dynamic Range Compression

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4952]
The Dynamic Range Compression tool needs to be documented.

**Comment by Thanatomanic** [comment]
Done http://rawpedia.rawtherapee.com/Dynamic_Range_Compression

**Comment by agriggio** [comment]
Thanks for taking care of this! :+1: 
A couple of comments:
1. Amount is proportional to beta, not anchor
2. Anchor is essentially just an exposure compensation
3. The default value for Detail is now 30

**Comment by Beep6581** [comment]
We also need to mention when to use this, and when not to use it, i.e. the effect depends on each image and so is unsuitable for panoramic photos pre-stitching.

**Comment by Beep6581** [comment]
detail=threshold=alpha
amount=beta
@agriggio is there an equivalent of "anchor" in the original Fattal paper and terminology?

**Comment by Beep6581** [comment]
Scratch that, the Fattal paper doesn't mention alpha nor beta so the question is irrelevant.

**Comment by Thanatomanic** [comment]
They do... Don't have it here on mobile, but it's somewhere top left of a page

**Comment by Thanatomanic** [comment]
See here: http://www.cs.huji.ac.il/~danix/hdr/hdrc.pdf Page 5 on the top left.

I'll update the docs with the new information.

**Comment by Beep6581** [comment]
@Thanatomanic thank you I :man_facepalming: ctrl+f'd for "alpha" and "beta" instead of α and β 
I'm already updating the docs, but I would appreciate if you could proof-read it once I commit.

**Comment by Beep6581** [comment]
Done:
http://rawpedia.rawtherapee.com/Dynamic_Range_Compression

@agriggio @Thanatomanic if you agree with what I wrote, then I will proceed to add screenshots.

**Comment by Thanatomanic** [comment]
@Beep6581 Wonderful. Three things:

1. The first line of the second paragraph is essentially repeating the first line of the first paragraph. Better remove or rewrite.
2. As @agriggio mentioned, my original write-up was wrong. The beta parameter is linked to the amount, not the anchor.
3. Would be nicer to adopt the way Wikipedia uses references, so that we can give proper reference to Mr. Fattal. See https://en.wikipedia.org/wiki/Wikipedia:Citing_sources

Edit: please go ahead with the screenshots!

**Comment by Beep6581** [comment]
@Thanatomanic I made some small edits probably while you were reading.

1. The first paragraph is about the concept of dynamic range in general. The second paragraph is specifically about the dynamic range of a scene. The closing sentence of the first paragraph makes the transition. Do you still think we should remove the opening sentence of the second paragraph?
2. Fixed.
3. Could you make the reference change please?
4. I also removed references to default values - those sometimes change, and often the documentation is overlooked when the change is made. It's a burden to maintain with no real benefit.

I will add screenshots tomorrow or later in the week.

**Comment by agriggio** [comment]
@Beep6581 @Thanatomanic thanks a lot! The docs are great imho :+1:

**Comment by Thanatomanic** [comment]
I've made some changes to the text and included a composition of comparison images. As far as I am concerned, this is now good for the next release.
