### ISSUE TITLE
Document ICC Profile Creator

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4959]
The ICC Profile Creator tool needs to be documented.

**Comment by Beep6581** [comment]
@Desmis is there anything about the ICC Profile Creator which may not be obvious from the user interface? Maybe the recent changes in #4980 introduced something which needs to be documented?

**Comment by Desmis** [comment]
@Beep6581 

I think a document is necessary, but the remarks of @gaaned92 , brings me a lot of questioning

Color management is something complex, often empirical, full of approximations and fruit of experience.
Writing something simple is easy if we assume that everyone understands the basic concepts and their implications (here color management only for ICC profile and usage)
* primaries and implication
* chromaticity diagram and xyY coordonates
* white point(s) and PCS
* conversion RGB-XYZ and implication
* XYZ values and incidences
* chromaticity adaptation (Bradford, Cat02, Von Kries)
* tags in ICC profiles
* Illuminants (D50, stdA,...D80)   - link with white balance, and incidence on gamut (via Lab and XYZ) 
* TRC with LUT or calculated
* etc.
* etc.
Can you "help" me to find the good  way

After that, If diagram are necessary, to explain and comment the text (in french), I can made those with XYZ / Lab, but I need some help for CIExyz and primaries

Jacques

**Comment by Beep6581** [comment]
@Desmis the topic is complex and the subject could fill a book - and indeed has filled quite a few. I think trying to document all of this would be overwhelming and to a large degree a duplication of information which is already out there. So to make it more manageable, I propose documenting only the idiosyncrasies of our ICC Profile Generator, if any, and leaving all the required background knowledge for the user to discover in books and on other internet sites on their own.

The question then is what do we need to document? The tool seems straightforward, granted one has the background knowledge from elsewhere. Here are some questions that come to mind which I think we should document, in no particular order:
* Very briefly, why would I use this generator at all?
* Which standard(s) do the primaries come from? We could link to those standards (wikipedia, PDF, etc).
* Are the gamma and slope values in the description used by any program, or is that just for the human?
* I created an ICC profile, how do I use it as the working space in RT?
* I created an ICC profile, how do I use it as the output space in RT?
* I created an ICC profile, how do I use it as the monitor profile in RT? (I don't see why anyone would, but people have asked in the forum, so maybe we should briefly mention this).

**Comment by Desmis** [comment]
I will write a text probably tomorrow, of course you can (must) change and adpat it

Other thing, I have write sometimes ago, a text in french for "Tone response curve" (working profile) , and of course you can change it 
https://rawpedia.rawtherapee.com/Color_Management/fr#Gamma_-_TRC_-_Tone_response_Curve

**Comment by Desmis** [comment]
@Beep6581 
I have put in Rawpedia https://rawpedia.rawtherapee.com/ICC_Profile_Creator/fr
You can add/substract what you want, especially links - if you find it useful for example for primaries, profiles, etc.

Jacques

**Comment by Desmis** [comment]
I have done a small update

**Comment by Beep6581** [comment]
@Desmis excellent! I will keep this issue open until I translate it.

**Comment by Beep6581** [comment]
http://rawpedia.rawtherapee.com/ICC_Profile_Creator

**Comment by Hombre57** [comment]
@Beep6581 (ping @Demis for control)

I'd add :

"Please refer to available literature about color-space and ICC profiles.

**Append gamma and slope values to the description**

Check this button to append a "gamma=xxx slope=yyy" to the Copyright (see below).

This is a hack, as a workaround, to have a proper color gradation when the profile is saved to ICC V2 format and then used in RawTherapee (it has no other utility). It will look for those values in the copyright of ICC V2 profiles, and if provided, will be able to use a matrix instead of the embedded tone curve.

**Copyright**

Set the copyright of your profile here, or use the reset button to set it back to the RawTherapee CC0 copyright.

**Beware:** the standard enable you to set the copyright in different language using 2 standards : 
- LanguageCode: first name language code from ISO 639-2
  http://lcweb.loc.gov/standards/iso639-2/iso639jac.html
- CountryCode: first name region code from ISO 3166
 http://www.iso.ch/iso/en/prods-services/iso3166ma/index.html

Actually, this description and copyright string are internally set as being "EN-US", which mean English, USA variant. As such, and if you want to distribute the created profile, please set an English description and copyright and avoid non-ANSI chars."

**Comment by Beep6581** [comment]
@Hombre57 could you refresh my memory, why was the hack needed - what's wrong with using the curve instead of the matrix in ICC v2? Was that the sawtooth histogram issue? Was the problem in RT or LCMS or elsewhere or unknown?

**Comment by Desmis** [comment]
@Hombre57  @Beep6581 

Of what we speak ? There is no text (or just a little) in "ICC Profile Creator" page ...
For "append gamma and slope values to description", it seems to me, it is for the user, so he knows the value of TRC without using tools. It's the tag "dmdd" which contain always (if v2) values for gamma and slope.These values are used in RT to work around an LCMS bug. In this case, the calculation of gamma and slope with LCMS is updated, to prevent a histogram with fishbone

**Comment by Hombre57** [comment]
@Beep6581 

To complement @Desmis comment, see [around this post](https://github.com/Beep6581/RawTherapee/issues/4478#issuecomment-387397475).

**Comment by Hombre57** [comment]
@Desmis That's not only for the user, this addition is used by RT.

**Comment by rogerxxxx** [comment]
Maybe I'm just ignorant, but how about a small/quick how to use the tool for building a simply ICC profile?

The "https://rawpedia.rawtherapee.com/ICC_Profile_Creator/fr" should be converted to the "/us" page as well.

There's enough terminology within that page to make 99.9% of the populace of the world appear to look like dummies!

**Comment by TechXavAL** [comment]
Rescuing this issue. Sorry if I'm out of topic (I think I'm not).

Even if not all the topics, controls and peculiarities of the tool are covered, there's already [an Spanish documentation for it](https://rawpedia.rawtherapee.com/ICC_Profile_Creator/es). It covers some basics and terminology while explaining how to use the tool itself.

It should be easy to translate with an online translator.

Just in case it proves to be useful.

**Comment by h0jeZvgoxFepBQ2C** [comment]
How can I start this creator? I'm a newbie, couldnt find it?

**Comment by rogerxxxx** [comment]
What is your purpose for creating a color profile?

Are you creating a profile to match the color within your studio or
other specific location/scenario?

Or, are you creating a color profile for your (new) digital camera
that does not have a color profile within RawTherapee -- for getting
acceptable colors for raw images taken with your (new) camera when
importing the raw images into RawTherapee?

I think this #4959 issue was pertaining to the first location/scenario
ICC/ICM color profile scenario, as we already have the process for
creating camera ICC/ICM profiles somewhat well documented and, last I
knew, well maintained.

I think most, and especially myself, finally just gave-up on the
exquisite ICC/ICM color profiles per location/scenario, as it is
already tedious enough calibrating the camera with a gray/white card
prior to taking photos.  I usually do not bother with a gray card for
measuring exposure, but do try to calibrate white balance as getting
good exact colors is more important then getting a good exposure.  The
later can easily be adjusted later if slightly dark or bright.  I also
set my camera for something like -0.3 on exposure and -0.7 on flash,
or something similar, so I'm already taking very slightly dimmer than
eye-ball exposures, as my camera takes overly bright photos, or photos
without shadows.

**Comment by h0jeZvgoxFepBQ2C** [comment]
It may be embarrassing to hear, but I only want to create a new ICC profile for my laptop for OSX, since for sleeping I would like to have a really dark profile and the minimum light setting from my macbook is still to high, even with the lowest setting. So I would like to make the screen as dark as possible :) So I tried to create a new ICC profile, but couldnt find where I can find this creator tool inside RawTherapee :)

**Comment by Thanatomanic** [comment]
@h0jeZvgoxFepBQ2C This definitely not what you should use the ICC profile creator in RawTherapee for, but if you want to experiment, you can find the profile creator here: 
![image](https://user-images.githubusercontent.com/6567747/114868064-d0c43500-9df5-11eb-99d7-fd8d504ac293.png)

However, this issue is not the right place to continue this discussion. Please consult the internet on how to calibrate your screen to certain conditions. Feel free to join https://discuss.pixls.us to ask your question there.

**Comment by h0jeZvgoxFepBQ2C** [comment]
Thank you! 

I also didnt ask for help with the calibration, the issue says "Document ICC Profile Creator" and in the documentation it's not shown where to find this profile creator, so I just wanted to point out it would be great do improve the documentation here :)

Thanks for the help!

**Comment by TechXavAL** [comment]
@h0jeZvgoxFepBQ2C 

Even though it is briefly named in the [File Browser Spanish documentation page](https://rawpedia.rawtherapee.com/File_Browser/es#La_ventana_del_Navegador_de_Archivos) (first image, photo caption), you're right it's mostly not documented, even not entirely in the [ICC Profile Creator Spanish documentation](https://rawpedia.rawtherapee.com/ICC_Profile_Creator/es) I pointed to in my previous post.

I will add an explanation about where to find the button in the Spanish documentation. And while the English counterpart is updated, it shouldn't be too difficult reading it with an online translator.

However, as @Thanatomanic has told you, your needs won't be fulfilled with this tool. At least not if you want to preserve color fidelity.

**Comment by Desmis** [comment]
@Beep6581 

 I've just finished a change in Rawpedia for "ICC profile creator".
https://rawpedia.rawtherapee.com/ICC_Profile_Creator

I was inspired by Xavier's presentation @TechXavAL and added links to "Abstract profile" which uses similar code and many similar conceptual aspects https://rawpedia.rawtherapee.com/Color_Management#Abstract_Profiles

The documentation is in French and English thanks to Wyane's translation @waynesutton50

Jacques

**Comment by Beep6581** [comment]
Looks good. I made some changes and will close.

@TechXavAL when uploading icons please use PNG files from the "dark" folder (those made for a light background, as they use dark colors), keeping the original filename. Generate them using:
```
./tools/generatePngIcons rtdata/images/svg/gamut-plus.svg
```

**Comment by TechXavAL** [comment]
@Beep6581 

Didn't know how to generate icons that way. Will do from now on.

And sorry, but I can't seem to find where that "dark" folder is. The svg icons I have in my sourcecode folder are all dark versions (dark background, light grey icon).

**Comment by Beep6581** [comment]
@TechXavAL when you use `generatePngIcons`, you will find two folders, "dark" and "light", in /tmp.

On a side note, Inkscape kept changing their CLI options for a while, which means the script may fail depending on which version of Inkscape is installed. If the script fails to work, shoot and I'll help you get it working. Let me know which version of Inkscape you're using.

**Comment by TechXavAL** [comment]
@Beep6581 

I'm using Inkscape 1.1

It seems to work fine, more or less...

I get this:

>Warning: Option --without-gui= is deprecated
>Warning: Option --export-png= is deprecated

And these are the icons generated from _aperture.svg_:

_Light_ folder: 
![aperture](https://user-images.githubusercontent.com/52250392/120813472-314a3580-c54e-11eb-83dd-786dfcc29d7e.png)

_Dark_ folder:
![aperture](https://user-images.githubusercontent.com/52250392/120813511-3c04ca80-c54e-11eb-87b3-0c665ff6d295.png)

Even though it may seem the contrary, I think you prefer the _Light_ folder icon, don't you?
