### ISSUE TITLE
Document Dual Demosaic

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4961]
Update the Demosaicing documentation with the dual-demosaic options.

**Comment by heckflosse** [comment]
I'm not a native english speaker. What does `Document` mean? ;-)

**Comment by Beep6581** [comment]
It's something homo sapiens used to do before YouTube.

**Comment by heckflosse** [comment]
What's YouTube?

**Comment by Beep6581** [comment]
Added Dual Demosaic (as part of rewriting the whole Demosaicing article):
http://rawpedia.rawtherapee.com/Demosaicing
