### ISSUE TITLE
Document Microcontrast

### ISSUE THREAD

**Issue by Thanatomanic** [Beep6581/RawTherapee#4962]
It's current documentation is gloriously unfulfilling: http://rawpedia.rawtherapee.com/Edges_and_Microcontrast

In the best case, I think it deserves a separate entry.

**Comment by heckflosse** [comment]
Because of Capture sharpening, micro contrast now is less usefull => setting milestone for documentation to 5.9

**Comment by TechXavAL** [comment]
There's a [new Spanish documentation](https://rawpedia.rawtherapee.com/Edges_and_Microcontrast/es#Microcontraste) about microcontrast online.

This tool is definitely not obsolete, as explained in the documentation.

Hope it helps

_Note: if the comparison image doesn't show the «command» circle in the middle, just reload the page. The javascript is a bit picky and doesn't load right every time the page loads._

**Comment by heckflosse** [comment]
> This tool is definitely not obsolete

I agree :+1:

**Comment by Desmis** [comment]
I made the English (with help of Wayne @waynesutton50) and French version of "egges and microcontrast".

I was inspired by the work of Xavier @TechXavAL 
https://rawpedia.rawtherapee.com/Edges_and_Microcontrast

jacques

**Comment by Beep6581** [comment]
Gents, RawPedia is written in markup. Only use HTML when it is absolutely crucial to make things work, i.e. to unbreak things. Don't use custom HTML/CSS just to show an image. I don't want to have to untangle a spaghetti of markup and HTML when migrating the documentation to its next incarnation, as happens every few years.

This is a no-go:
```
<div class="img-comp-wrapper img-comp-right">
<div class="thumbinner thumbcompare tnone" style="width: 877px">
<imgcomp img1='microcontrast-off.jpg' img2='microcontrast-on.jpg'  width=877/>
<div class="thumbcaption">
Using the Microcontrast tool: although you shouldn't expect dramatic changes, the difference is noticeable, especially in the orange and beige feathers, as well as in the legs and the texture of the wooden beam. The image is more tactile, more real.<br/><small>''Original image from [http://www.photographyblog.com Photography Blog]''</small>
</div>
</div>
</div>
```

[Use:](https://www.mediawiki.org/wiki/Help:Images)
```
<div align="center">
<gallery mode="packed" caption="Effects of Microcontrast">
File:microcontrast-off.jpg|thumb|none|877px|Microcontrast off.
File:microcontrast-on.jpg|thumb|none|877px|Microcontrast on.
</gallery>
</div>
```

Furthermore, don't use images from third parties.

**Comment by Beep6581** [comment]
@TechXavAL are `Edges.jpg` and `Seagull-microcontrast.jpg` photos you shot and own and release under CC-BY-SA?

**Comment by Desmis** [comment]
@Beep6581 

OK, I am not at all a Rawpedia specialist....and OK for your version....I change also french version in the same way.

For your information in 2010, Manuel and I worked together...on this subject. On the noise also with Emil Martinec.  (Perfectraw and Dcraw)

Jacques

**Comment by heckflosse** [comment]
@Beep6581 

`Seagull-microcontrast.jpg` is a photo I shot. No problem to use it.

**Comment by TechXavAL** [comment]
@Beep6581 

Not mine:

Edges.jpg: https://discuss.pixls.us/t/play-raw-toronto-on-mobile-from-bus/10490

Seagull-microcontrast.jpg: https://discuss.pixls.us/t/play-raw-seagull/15294

**Comment by Beep6581** [comment]
Thanks @Desmis 

So both images require attribution but the creator hasn't been attributed anywhere. I added attribution to each image's description, e.g. http://rawpedia.rawtherapee.com/File:Seagull-microcontrast.jpg

When uploading images you can now select the licence:
![screenshot_20210604_150729](https://user-images.githubusercontent.com/5844619/120806473-3061d580-c547-11eb-9e97-a3e800f8b35e.png)

MediaWiki seems to have no field dedicated to specifying the creator, so please include the attribution (e.g. John Doe) and source (link to wherever John Doe expressed that his work is either public domain or CC-BY-SA) in the image summary if using an image which is public domain or CC-BY-SA but not created by you.

**Comment by Desmis** [comment]
@Beep6581 
I am very worried about all the work done on LA...there are many, many images that are either screenshots or raw files. 
The work is likely to be very important.

All raw, or screenshots are from me, or Pixls.us

**How do you "modify" an existing image** without starting over. Excuse my incompetence but I don't understand anything

Fo raw files, I can add a "licence" in the text in the rawpedia text that describes the image without changing anything in the image? (easy)

please advise me, but if I had known before it would have been considerably easier

jacques
