### ISSUE TITLE
Compiling RT 5.5 on FreeBSD 11.2

### ISSUE THREAD

**Issue by Thanatomanic** [Beep6581/RawTherapee#4964]
This is a non-issue, just for reference sake. While it is possible to get RT 5.5 to work on FreeBSD 11.2, there seems to be no openmp support (at least not in my VirtualBox installation), so performance will be very limited.
In any case, since FreeBSD does not come with a default desktop shell, it does not seem very likely for anyone to use it for any serious desktop and photo editing work. My suggestion: we don't officially support the OS.

Still, if anyone wants to build it, use these steps:

- First install these packages: `pkg install wget git cmake pkgconf gtkmm30 lensfun fftw3 fftw3-float libiptcdata libcanberra-gtk3`
- `nproc` is not available, so run `sysctl -n hw.ncpu` and remember the value
- Download the build script, as described [here](http://rawpedia.rawtherapee.com/Linux#Compilation) and modify it by changing `make --jobs="$cpuCount" install || exit 1` so that it reads `make -j# install || exit 1` where you replace the # with the number of cores you found earlier.
- If you want to reduce the number of warnings while compiling, make sure to also add the line: ` -DCMAKE_CXX_FLAGS="-Wno-deprecated -Wno-parentheses" \` (you'll still get a lot of warnings, probably because of Clang)

Good luck...

**Comment by heckflosse** [comment]
> My suggestion: we don't officially support the OS.

:+1:

**Comment by valpackett** [comment]
RT is already packaged in the official ports collection, so you can just `pkg install rawtherapee`. (The port will be updated from 5.4 to 5.5 soon, now that 5.5 is released.)

There is an `OPENMP` option in the port, by the way. It uses LLVM libomp (which has an idle CPU usage issue: #5105)

> nproc
> make -j#

Use Ninja!

> since FreeBSD does not come with a default desktop shell, it does not seem very likely for anyone to use it for any serious desktop and photo editing work

Arch Linux and Gentoo don't come with a default desktop shell either, I guess no one would ever use them for any serious desktop and photo editing work :P

**Comment by Benitoite** [comment]
Have you tried (building+installing+using) libiomp5?  It seems to work on mac/darwin with a number of cmake flags: `-DOpenMP_C_FLAGS=-fopenmp=lomp -DOpenMP_CXX_FLAGS=-fopenmp=lomp -DOpenMP_C_LIB_NAMES="libiomp5" -DOpenMP_CXX_LIB_NAMES="libiomp5" -DOpenMP_libiomp5_LIBRARY="/opt/local/lib/libiomp5.dylib" -DOpenMP_CXX_FLAGS="-Xpreprocessor -fopenmp /opt/local/lib/libiomp5.dylib -I/opt/local/include" -DOpenMP_CXX_LIB_NAMES="libiomp5" -DOpenMP_omp_LIBRARY=/opt/local/lib/libiomp5.dylib -DOpenMP_C_FLAGS="-Xpreprocessor -fopenmp /opt/local/lib/libiomp5.dylib -I/opt/local/include"`

**Comment by valpackett** [comment]
> libiomp5

According to [their website](https://www.openmprtl.org), Intel OpenMP (`libiomp5`) is now LLVM OpenMP (`libomp`). Or it's deprecated in favor of `libomp`.

> The development of the open-source OpenMP* runtime now happens in the context of LLVM*.

`libomp` is already the preferred implementation on FreeBSD, it's installed with `pkg install openmp`, and the RawTherapee package already uses it.

**Comment by Thanatomanic** [comment]
@myfreeweb @Benitoite If you can write working instructions to compile the latest `dev` on FreeBSD, with `libomp` and `ninja` we're of course happy to include them on RawPedia. However, my personal feeling is that the FreeBSD userbase of RT is very small and it might not be worth the hassle.

**Comment by Beep6581** [comment]
No progress, closing.
