### ISSUE TITLE
Potential tiny typo in dcraw.cc

### ISSUE THREAD

**Issue by Thanatomanic** [Beep6581/RawTherapee#4971]
@heckflosse Can you take a look if https://github.com/Beep6581/RawTherapee/blob/dev/rtengine/dcraw.cc#L9141 is correct? Clang complains that `&&` should probably be `&`. However, maybe some automagic casting takes place where a boolean is interpreted as 0 or 1?

**Comment by heckflosse** [comment]
@Thanatomanic I checked. That code is called for Fuji files. For normal Fuji files with one frame `i` will be zero whereas for EXR files which contain two frames `i` is a number > 0 (for example 813818). I guess the number is the offset of the frame data for the second frame.

Means, the && is perfectly fine here. Using & would fail

**Comment by Thanatomanic** [comment]
Would it be reasonable to get rid of the warning by doing: `is_raw += (get4() == 1) : 1 ? 0`?

**Comment by heckflosse** [comment]
@Thanatomanic 
That would fail to compile ;) And after swapping `?` and `:` it would fail to detect the second frame of Fuji EXR files.

This one works.
```
is_raw += (i = get4()) > 0 ? 1 : 0;
```
Can you check if it gets rid of the warning?

**Comment by heckflosse** [comment]
Hmm, offset could be negative as well, better:
```
is_raw += (i = get4()) != 0 ? 1 : 0;
```

**Comment by Thanatomanic** [comment]
@heckflosse Whoops 😋 
Using your last suggestions gets rid of the warning. Shall I commit?

**Comment by heckflosse** [comment]
Yes, please

**Comment by Thanatomanic** [comment]
Closed with https://github.com/Beep6581/RawTherapee/commit/83975938ef6984d9722ffe1b3df219c16d8845d1

**Comment by Floessie** [comment]
@Thanatomanic @heckflosse Hint for next time: To clamp a value to 0/1 you can safely cast it to `bool` in C++.

```c++
is_raw += static_cast<bool>(i = get4());
```
