### ISSUE TITLE
Auto-matched curve fails on this image

### ISSUE THREAD

**Issue by ff2000** [Beep6581/RawTherapee#4979]
Top is with Standard Film Curve - ISO Low, Bottom with Auto-Matched Tone Curve - ISO Low:
![Sample](https://user-images.githubusercontent.com/1973708/48310985-b50f3180-e5a0-11e8-8219-36596785f980.jpg)
Look at the finer branches along the ridge, with auto matched they get light blobs that blend with the sky.

Sample Raw file is here:
https://www.dropbox.com/s/dog6utxzn6wzna4/P1130671.RW2?dl=0

Usually Auto matched Curve does a really great job for me. In the above case it creates a wide plateau in the mid tones which might be the root of this issue.

**Comment by Beep6581** [comment]
Caused by a bad auto-matched curve shape:
![screenshot_20181112_102636](https://user-images.githubusercontent.com/5844619/48338284-873ff080-e665-11e8-86d5-39273bd41c48.png)

**Comment by agriggio** [comment]
I have an idea, I'll see whether it works.. thanks for the example

**Comment by agriggio** [comment]
Here's a candidate patch. I hope it applies cleanly on `dev` (I'm currently on another branch). 
Note it would need to be tested on several images to make sure it doesn't introduce side-effects...

```diff
diff --git a/rtengine/histmatching.cc b/rtengine/histmatching.cc
--- a/rtengine/histmatching.cc
+++ b/rtengine/histmatching.cc
@@ -216,6 +216,45 @@
 
     curve.push_back(1.0);
     curve.push_back(1.0);
+
+    // we assume we are matching an S-shaped curve, so try to avoid
+    // concavities in the upper part of the S
+    const auto getpos =
+        [](float x, float xa, float ya, float xb, float yb)
+        {
+            // line equation:
+            // (x - xa) / (xb - xa) = (y - ya) / (yb - ya)
+            return (x - xa) / (xb - xa) * (yb - ya) + ya;
+        };
+    idx = -1;
+    for (size_t i = curve.size()-1; i > 0; i -= 2) {
+        if (curve[i] <= 0.f) {
+            idx = i+1;
+            break;
+        }
+    }
+    if (idx >= 0 && size_t(idx) < curve.size()) {
+        // idx is the position of the first point in the upper part of the S
+        // for each 3 consecutive points (xa, ya), (x, y), (xb, yb) we check
+        // that yb is above the point at x of the line between the other two
+        // if this is not the case, we remove the middle point
+        while (size_t(idx+5) < curve.size()) {
+            float xa = curve[idx];
+            float ya = curve[idx+1];
+            float x = curve[idx+2];
+            float y = curve[idx+3];
+            float xb = curve[idx+4];
+            float yb = curve[idx+5];
+            float yy = getpos(x, xa, ya, xb, yb);
+            if (yy > y) {
+                // we have to remove (x, y) from the curve
+                curve.erase(curve.begin()+(idx+2), curve.begin()+(idx+4));
+            } else {
+                // move on to the next point
+                idx += 2;
+            }
+        }
+    }
         
     if (curve.size() < 4) {
         curve = { DCT_Linear }; // not enough points, fall back to linear
```

**Comment by agriggio** [comment]
BTW @ff2000 does the camera have a built-in (software-based) graduated ND filter?

**Comment by ff2000** [comment]
@agriggio Patch applied fine on dev and it resolved the issue. I converted several other photos, some were fine and some showed the issue before the patch. All seems to work fine without any issue after applying the patch. Thank you very mutch!

And the camera does not have an integrated Grad ND filter. The EXIF contains an "Internal ND Filter" field (which I recently discovered) but I don't know why... Is there a reason you ask?

**Comment by agriggio** [comment]
Hi @ff2000,
thanks for testing! :+1: 

> And the camera does not have an integrated Grad ND filter. The EXIF contains an "Internal ND Filter" field (which I recently discovered) but I don't know why... Is there a reason you ask?

Well, the embedded JPEG shows signs of a grad ND filter applied on the sky and the tip of the mountain, so I was just curious...

**Comment by ff2000** [comment]
Ah, OK. No, that was the light. It was cloudy the whole day and just before sunset the sun slowly came out from behind the clouds and a small band of fire creeped up the hill. That image was just a moment before the sun completely came out.

![p1130790](https://user-images.githubusercontent.com/1973708/48398697-3514d300-e72a-11e8-822e-1e4db94e4f64.jpg)

In the background you see the shadow of the cloud, in the front it's from the mountain behind me.
This is the light on the peak:

![p1130825](https://user-images.githubusercontent.com/1973708/48398938-eca9e500-e72a-11e8-9cbd-c16cda39a586.jpg)

**Comment by Beep6581** [comment]
I compared before the patch (`5.4-1136-g`ad8a52ce8) to after the patch (`5.4-1142-g`834f6bafe) on 33 images. Generally there was very little if any difference in most of the images.

A few showed this drop of the darker tones, unpatched:
![screenshot_20181115_101546](https://user-images.githubusercontent.com/5844619/48542445-77234d80-e8bf-11e8-826f-a5e92cb29d80.png)
Patched:
![screenshot_20181115_101551](https://user-images.githubusercontent.com/5844619/48542458-7d192e80-e8bf-11e8-8947-f7a69abb360d.png)

The most extreme difference was on this photo, unpatched:
![screenshot_20181115_101152](https://user-images.githubusercontent.com/5844619/48542478-87d3c380-e8bf-11e8-9b7d-98348cc7b2ba.png)
Patched:
![screenshot_20181115_101206](https://user-images.githubusercontent.com/5844619/48542487-8d310e00-e8bf-11e8-90c2-e6cd34bcc14b.png)

Where there was a difference, in one case the unpatched version matched the embedded JPEG more closely, while in another case the patched one matched it better, so no clear winner in that regard.

Confirmed that the patch prevents the wonky curve in `P1130671.RW2`, unpatched:
![screenshot_20181115_102733](https://user-images.githubusercontent.com/5844619/48543146-31678480-e8c1-11e8-932a-8630c980a9c4.png)
Embedded:
![screenshot_20181115_102739](https://user-images.githubusercontent.com/5844619/48543152-362c3880-e8c1-11e8-85b2-db43936820e0.png)
Patched:
![screenshot_20181115_102744](https://user-images.githubusercontent.com/5844619/48543161-3a585600-e8c1-11e8-81d1-966b5492f70b.png)
