### ISSUE TITLE
Remove 'debug' output from logging in verbose mode

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#4985]
When running RT in verbose mode, it logs a lot of stuff, which to me looks likes debug output which was forgotten to remove. This issue is to remove that logging output.

Example:
Starting RT in verbose mode whith a raw in folder which has vibrance tool enabled, you'll get this in console, though without a hint, from which raw it is (useless information)

```
vibrance:  p0=0.24  p1=0.42  p2=0.59  s0=0.83 s1=0.88 s2=0.94
           pastel=1.300000   satur=1.300000   limit= 0.77   chromamean=0.00000
```

**Comment by Beep6581** [comment]
I got these in the console today:
```
printf("dmdd=%s\n", modelDesc.c_str());
```
https://github.com/Beep6581/RawTherapee/blob/dev/rtengine/iplab2rgb.cc#L338

**Comment by heckflosse** [comment]
@Beep6581 I will remove it

**Comment by heckflosse** [comment]
There is a wrong logging in verbose mode if the camera is not found in lensfun database.
To reproduce: Set verbose=true in options and open http://www.rawtherapee.com/shared/test_images/crash_kodak_pb645m.dcr

Console output:
```
LENSFUN:
  camera: AEE
  lens: ---
  correction: NONE
```

@agriggio Alberto, any idea?
