### ISSUE TITLE
Lens names in metadata filter not updated after RTExif upgrade

### ISSUE THREAD

**Issue by Thanatomanic** [Beep6581/RawTherapee#4987]
@Beep6581 I don't know if this was to be expected, but after #4977 my Tamron 70-200 mm lens on Nikon was added and it does show up in the editor:

![image](https://user-images.githubusercontent.com/6567747/48507289-c891f500-e84b-11e8-9e70-84ba23fc7f55.png)

However, in the metadata filters in the file browser I still see the old name:

![image](https://user-images.githubusercontent.com/6567747/48507315-e19aa600-e84b-11e8-9460-7889931de41f.png)

Is this expected? Is it a bug? Can it be remedied?

**Comment by heckflosse** [comment]
@Thanatomanic Did you clear the cache?

**Comment by Thanatomanic** [comment]
It got updated, so this is a non-issue. I simply don't know when to expect to clear my cache...

**Comment by heckflosse** [comment]
@Thanatomanic To get an idea when to clear the cache, have a look at the Exif section of a cache file, for example:

```
[ExifInfo]
Valid=true
FNumber=4
Shutter=0.0050000000000000001
FocalLen=105
FocalLen35mm=105
FocusDist=0
ISO=200
IsHDR=false
IsPixelShift=false
ExpComp=0.00
Lens=MF 105.0mm f/4.0
CameraMake=NIKON
CameraModel=D700
```
