### ISSUE TITLE
Impossible to build libiptcdata, following the malfunction of msys2

### ISSUE THREAD

**Issue by Desmis** [Beep6581/RawTherapee#4993]
Yesterday I decided to update Msys2 (I do it about every 15 days)
As  my computer is protected from viruses by Avast, I disabled  Avast for 1 hour
I begin  the update by
$ pacman -Syu
But just after startup, and before you say yes, I had a mishap of more than an hour, and when I came back to my computer to launch pacman, the antivirus probably reactivated and I forgot that
And when Avast found "gpg-agent.exe", he considered it a virus, quarantined, without asking my opinion, and immediatly the system crash
When I reboot, impossible to launch Msys2 or Mingw64

I tried, tried, but finally I decided to uninstall MSys2 and re-install
How I do, step by step
1) uninstall Msys2
2) clean register
3) reboot system
4) install Msys2
5) immediately after, I used the lines of Rawpedia for Windows 64 bits
$ pacman -S tar gzip nano make diffutils intltool git
$ pacman -S mingw-w64-x86_64-gcc mingw-w64-x86_64-gdb mingw-w64-x86_64-make mingw-w64-x86_64-pkg-config mingw-w64-x86_64-cmake
pacman -S mingw-w64-x86_64-gtkmm mingw-w64-x86_64-gtkmm3 mingw-w64-x86_64-lcms2 mingw-w64-x86_64-fftw mingw-w64-x86_64-lensfun

At this stage
 mingw-w64-x86_64-libjpeg-turbo
mingw-w64-x86_64-lensfun
mingw-w64-x86_64-gtk3
mingw-w64-x86_64-gtkmm3
are compatible "version" 

Then I want to build libiptcdata, I strictly followed the instructions
$ curl -LO http://downloads.sourceforge.net/project/libiptcdata/libiptcdata/1.0.4/libiptcdata-1.0.4.tar.gz
$ tar xzf libiptcdata-1.0.4.tar.gz
$ cd libiptcdata-1.0.4
Then
$ ./configure --prefix=/mingw64

And I have this message
jacques@pc-bureau MSYS ~
4/libiptcdata-1.0.4.tar.gzs.sourceforge.net/project/libiptcdata/libiptcdata/1.0.4
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   383  100   383    0     0    666      0 --:--:-- --:--:-- --:--:--   666
100  555k  100  555k    0     0   134k      0  0:00:04  0:00:04 --:--:--  251k

jacques@pc-bureau MSYS ~
$  tar xzf libiptcdata-1.0.4.tar.gz

jacques@pc-bureau MSYS ~
$ cd libiptcdata-1.0.4

jacques@pc-bureau MSYS ~/libiptcdata-1.0.4
$ ./configure --prefix=/mingw64
configure: loading site script /etc/config.site
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking build system type... **Invalid configuration `x86_64-pc-msys': system `msys' not recognized
configure: error: /bin/sh ./config.sub x86_64-pc-msys failed**

libiptcdata is not installed...

To continue, I modify pacman.conf with
IgnorePkg = mingw-w64-x86_64-libjpeg-turbo
IgnorePkg = mingw-w64-x86_64-lensfun
IgnorePkg = mingw-w64-x86_64-gtk3
IgnorePkg = mingw-w64-x86_64-gtkmm3

Then
$ pacman -Syu
All libraries are update excepted those above

I re-tried to buils libiptcdata, same message
What's is wrong ? what I missed ?
Thank you for help me 

Jacques

**Comment by Thanatomanic** [comment]
@Desmis I found an issue elsewhere that seems similar to yours: https://github.com/JuliaLang/julia/issues/6234

Just to check: do you start `mingw64.exe` or `msys2.exe`? You should use the former, not the latter, when doing every step you described above.

**Comment by Thanatomanic** [comment]
Also, can you whitelist entire directories in Avast? It might help you with complications in the future.

**Comment by Desmis** [comment]
@Thanatomanic 

I used msys2...and if I read "Rawpedia", It's write, but for me not visible enough, because
a) lost in the text
b) it's write "MinGW-w64 Win32 Shell" instead of "mingw64"
I think a slight modification of Rawpedia, would be welcome, to prevent this 

I just try with launch with mingw64, and now libiptcdata is build
I re-compile, all seems to work fine

Thank you very very much 
Jacques

**Comment by Thanatomanic** [comment]
@Desmis I agree that the Windows page is a little unclear. I'll put it on my todo list :smiley:

**Comment by Desmis** [comment]
@Thanatomanic 

thank you :)

**Comment by gaaned92** [comment]
@Thanatomanic 
I wrote an updated version of the rawpedia page `windows` in my user's page gaaned92.
Could you review it.

As above error is very common with MSYS2, I paid attention to always identify the shell to use.

**Comment by gaaned92** [comment]
@Thanatomanic  @Desmis 
I wrote an completely updated rawpedia windows page in  http://rawpedia.rawtherapee.com/User:Gaaned92
Could you review it before I copy back my user page in the window page?

**Comment by Desmis** [comment]
@gaaned92 
it seems clearer to me.
Remark : 
* In my reinstallation of Msys2 , I have tried  with
a) first , update of Msys2 by $ pacman -Syu, just after installation
In this case, all package are uptodate and needs have to be downgraded, 
This morning I did not how to do, where are the "old" package (you bring a response), and my system does not work correctly (I cannot found "old" packages)

b) second, just after run Msys2 installation, whitout executing Pacman -Syu
I install all tools, (miscellenaous, developpement, libraries, etc.),  
Then changing git with "Ignorepkg"
Then running Msys2 with Pacaman -Syu
and all is good..
jacques
