### ISSUE TITLE
Rewriting of Rawpedia Windows build page

### ISSUE THREAD

**Issue by gaaned92** [Beep6581/RawTherapee#4994]
@Thanatomanic  @iliasg  @Beep6581 @heckflosse @TooWaBoo @Hombre57  and all devs
As the windows build page was obsolete on some aspects, incomplete , I completely rewrote it in http://rawpedia.rawtherapee.com/User:Gaaned92

Please Correct it and review it in order I copy it back in the windows page.
Thank you.

**Comment by Thanatomanic** [comment]
Excellent work @gaaned92, I'll take a look and update the Windows page.

**Comment by Thanatomanic** [comment]
@gaaned92 I never really got lensfun to work under Windows. Even when following your instruction, nothing shows in RT. Any clue to why that is?

**Comment by gaaned92** [comment]
@Thanatomanic 
I can think of two points:
- you have to downgrade lensfun . last version is incompatible with RT.
- the version of the lensfun  database you use is not compatible with  the version of the lensfun program.(e.g. database version 2 and liblensfun.dll requiring version 1)

I tested the Msys2 lensfun sa few months ago. As it is very old, I   build lensfun and I download the database from  lensfun repository. But now I can no longer update past the commit that broke compatibility.

I am going to retest the MSYS2 lensfun

**Comment by gaaned92** [comment]
@Thanatomanic 
I just built a dev version with MSYS2 lensfun. It is ok. This time the database in ./share/lensfun  is version_1.

 I am going to check the recipe. 
edit: seems ok

**Comment by heckflosse** [comment]
@Thanatomanic Please post the Lensfun section at the end of your options file

**Comment by Thanatomanic** [comment]
@heckflosse The last line reads:
```
[Lensfun]
DBDirectory=C:/msys64/mingw64/share/lensfun
```
This is formatted differently from all other folders (\\ instead of /), but manually changing the slashes that does not make RT recognise the database. This is the actual location of the `version_1` folder in my file system:
![image](https://user-images.githubusercontent.com/6567747/48733137-f7400f00-ec41-11e8-9d8e-a451458da2a0.png)

**Comment by Thanatomanic** [comment]
@gaaned92 I am using the properly downgraded version of lensfun.
Edit: `mingw-w64-x86_64-lensfun-0.3.2-4-any.pkg.tar` as far as I know.

**Comment by heckflosse** [comment]
@Thanatomanic Can you try

```
[Lensfun]
DBDirectory=
```

That works fine on my Win7

**Comment by gaaned92** [comment]
In order to work it should be
[Lensfun]
DBDirectory=C:/msys64/mingw64/share/lensfun/version_1

With DBDirectory= , the Lensfun Database has to be copied.

**Comment by Thanatomanic** [comment]
> [Lensfun]
> DBDirectory=C:/msys64/mingw64/share/lensfun/version_1

This works, but how does this even get set? The build instructions ask for `-DLENSFUNDBDIR=share/lensfun` which 1) is not the right folder for the database and 2) in no way modifies my options file. Not even the default options file in the `build` folder.

Is this a bug? I am confused now.

**Comment by gaaned92** [comment]
@Thanatomanic 
The LENSFUNDBDIR specifies the  path where the Lensfun DB is to be searched.
This path is not hard coded but is included in a new generated default option file. Existing option file is not modified.

- DLENSFUNDBDIR=share/lensfun specifies that the LF database (the xml files )are to be searched in 
the relative path ./share/lensfun
 In this case, you have  to **copy the database in this location**.
A fresh install without the config folder will work

- you can  define absolute path as DLENSFUNDBDIR=/c/msys64/mingw64/share/lensfun/version_1.  As above only if you create a new option file, will it be taken into account. 
 Fresh install without the config folder will not work unless you have MSYS2 installed.

I hope it is now clear.

**Comment by Thanatomanic** [comment]
Thanks @gaaned92 for explaining, it works now. Though, I think there's a few issues with this approach (and not in the least why there is no option in Preference to set the directory from there... I'll start a new issue about that at some point)

**Comment by gaaned92** [comment]
@Beep6581 
If you agree, I will copy back the windows page where further corrections will be possible.

**Comment by gaaned92** [comment]
The windows page is updated
