### ISSUE TITLE
Rename Profiled Lens Correction options

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4997]
Since the Profiled Lens Correction panel does not currently allow us to manually specify the actual correction parameters (lens distortion parameters a, b and c, image shift parameters d and e, image shear parameters g and t, etc.), the current naming is misleading. I want to rename:
* "Auto-matched correction parameters" > "Automatically select lens profile"
* "Manual correction parameters" > "Manually select a lens profile"
* "LCP File" > either "LCP file" or "Manually select LCP file".

Any objections or suggestions?

Ping @agriggio

**Comment by agriggio** [comment]
no objection :+1:
