### ISSUE TITLE
Nikon Z 6

### ISSUE THREAD

**Issue by agriggio** [Beep6581/RawTherapee#4998]
There are some raw samples online (e.g. dpreview), and the latest Adobe DNG converter (11.1 Beta) supports the camera. So I thought this would be just a matter of adding the proper colour matrix to `camconst.json` (apart from the new uncompressed raw, which is apparently a new format). 
However, the raw files I tried (from dpreview) seem to be quite odd. It's as if the black and white levels are completely off... I get pink highlights and magenta casts. I tried to mess with the levels but I couldn't get very far. But I know very little about this, so I got stuck very quickly. Ping @heckflosse @iliasg, maybe this is better left to you :-)

**Comment by agriggio** [comment]
Ok, after digging a bit more, I found the culprit (via google, in fact :wink: ). It's not the levels, it's the curve.
See here: https://redmine.darktable.org/issues/12322 (thanks @LebedevRI)
Here's the rawspeed commit from which I adapted the patch:
https://github.com/darktable-org/rawspeed/commit/856c951d202bf7474aaae272ca2dfc3d2260fcdf#diff-4b9c299bd5e478f76359a1c720fcf42a

Here's a tentative fix:

```diff
diff --git a/rtengine/dcraw.cc b/rtengine/dcraw.cc
--- a/rtengine/dcraw.cc
+++ b/rtengine/dcraw.cc
@@ -1330,10 +1330,10 @@
     if (ver0 == 0x46) tree = 2;
     if (tiff_bps == 14) tree += 3;
     read_shorts (vpred[0], 4);
-    max = 1 << tiff_bps & 0x7fff;
+    max = 1 << (tiff_bps - (ver0 == 0x44 && ver1 == 0x40 ? 2 : 0)) & 0x7fff;
     if ((csize = get2()) > 1)
         step = max / (csize-1);
-    if (ver0 == 0x44 && ver1 == 0x20 && step > 0) {
+    if (ver0 == 0x44 && (ver1 == 0x20 || ver1 == 0x40) && step > 0) {
         for (int i=0; i < csize; i++)
             curve[i*step] = get2();
         for (int i=0; i < max; i++)
```

Here's a D65 color matrix extracted with Adobe DNG converter 11.1 beta (in dcraw format):

```txt
[8210, -2534, -683, -5355, 13338, 2212, -1143, 1929, 6464]
```

**Comment by LebedevRI** [comment]
> There are some raw samples online (e.g. dpreview)

Indeed, there are none on [RPU](https://raw.pixls.us/) as of now.
If anyone has that camera, please do consider contributing the full sample set.
(Same for Canon EOS R, GoPro FUSION)

**Comment by agriggio** [comment]
speaking of canon, does rawspeed decode cr3?

**Comment by LebedevRI** [comment]
No. (not the image compression itself. the ISO M container is trivial)
I think it will be close to the GoPro's wavelet decompressor, but i haven't really looked..

**Comment by heckflosse** [comment]
Here's a patch for a better (but still wrong) decoding of uncompressed 14bit files from Z6. Maybe it's a first step...

```diff
diff --git a/rtengine/dcraw.cc b/rtengine/dcraw.cc
index f61cd94c2..da805942d 100644
--- a/rtengine/dcraw.cc
+++ b/rtengine/dcraw.cc
@@ -2562,6 +2562,7 @@ void CLASS packed_load_raw()
 
   bwide = raw_width * tiff_bps / 8;
   bwide += bwide & load_flags >> 9;
+  bwide += row_padding;
   rbits = bwide * 8 - raw_width * tiff_bps;
   if (load_flags & 1) bwide = bwide * 16 / 15;
   bite = 8 + (load_flags & 56);
@@ -6759,8 +6760,13 @@ void CLASS apply_tiff()
 	    load_raw = &CLASS packed_load_raw;
 	} else if ((raw_width * 2 * tiff_bps / 16 + 8) * raw_height == tiff_ifd[raw].bytes) {
 	    // 14 bit uncompressed from Nikon Z7, still wrong
-	    // each line has 8 padding byte. To inform 'packed_load_raw' about his padding, we have to set load_flags = padding << 9
-	    load_flags = 8 << 9;
+	    // each line has 8 padding byte.
+	    row_padding = 8;
+	    load_raw = &CLASS packed_load_raw;
+	} else if ((raw_width * 2 * tiff_bps / 16 + 12) * raw_height == tiff_ifd[raw].bytes) {
+	    // 14 bit uncompressed from Nikon Z6, still wrong
+	    // each line has 12 padding byte.
+	    row_padding = 12;
 	    load_raw = &CLASS packed_load_raw;
 	} else
 	  load_raw = &CLASS nikon_load_raw;			break;
diff --git a/rtengine/dcraw.h b/rtengine/dcraw.h
index f9591b640..dd4831625 100644
--- a/rtengine/dcraw.h
+++ b/rtengine/dcraw.h
@@ -47,7 +47,9 @@ public:
     ,order(0x4949)
     ,ifname(nullptr)
     ,meta_data(nullptr)
-    ,shot_select(0),multi_out(0)
+    ,shot_select(0)
+    ,multi_out(0)
+    ,row_padding(0)
 	,float_raw_image(nullptr)
     ,image(nullptr)
     ,bright(1.)
@@ -88,7 +90,7 @@ protected:
     unsigned tiff_nifds, tiff_samples, tiff_bps, tiff_compress;
     unsigned black, cblack[4102], maximum, mix_green, raw_color, zero_is_bad;
     unsigned zero_after_ff, is_raw, dng_version, is_foveon, data_error;
-    unsigned tile_width, tile_length, gpsdata[32], load_flags;
+    unsigned tile_width, tile_length, gpsdata[32], load_flags, row_padding;
     bool xtransCompressed = false;
     struct fuji_compressed_params
     {

```

**Comment by agriggio** [comment]
any objections to pushing the rawspeed patch above?

**Comment by heckflosse** [comment]
@agriggio No objections. Please include my patch.
