### ISSUE TITLE
Profiled Lens Correction does not seem to use (Unchanged) mode in Batch Edit

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#5002]
`dev` `5.4-1196-g`61d8a4f25

When selecting multiple photos with different Profiled Lens Correction settings, the "(Unchanged)" radiobutton in the Batch Edit tab never becomes selected. Unless I misunderstood its purpose, this is a bug.

**Comment by Thanatomanic** [comment]
As it stands now, the "(Unchanged)" radiobutton is always checked, and does not get unchecked when you actually change the lens profile settings. Still a bug.

**Comment by TooWaBoo** [comment]
Fixed it.

**Comment by Lawrence37** [comment]
Fix confirmed in 5.9. For some reason, Profiled Lens Correction does not know it's in batch mode in the current `dev`. That's a new issue though.
