### ISSUE TITLE
Some translations are lost in latest dev

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#5003]
@Beep6581 
Latest dev lost some translation through the whole GUI. I think there went something wrong.

Example
![unbenannt](https://user-images.githubusercontent.com/13800920/48833236-36be4680-ed7b-11e8-9efd-0436c85518d2.png)

btw. It would look better when you swap `crop mask color` and `color picker font`.

**Comment by Beep6581** [comment]
@TooWaBoo several strings in `default` were changed, so they were removed from the translations by key else the translations would be wrong and out of sync.

I noticed that you made some of the same changes changes in `Deutsch` in the past that I made in `default` yesterday, for example you dropped the word "Mask" when you translated `TP_RETINEX_MAP;Mask method`. I tried to preserve your changes where they matched the strings in the new `default` where possible.

I agree with the suggested swap and will do that now.
