### ISSUE TITLE
normalizeFloat override warning when building with clang

### ISSUE THREAD

**Issue by Thanatomanic** [Beep6581/RawTherapee#5009]
Building with clang gives a warning of the following kind:

```
In file included from C:/msys64/home/Roel/rt-dev/rtengine/lcp.h:32:
C:/msys64/home/Roel/rt-dev/rtengine/imagefloat.h:221:26: warning: 'normalizeFloat' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
    virtual void         normalizeFloat(float srcMinVal, float srcMaxVal);
                         ^
C:/msys64/home/Roel/rt-dev/rtengine/iimage.h:88:18: note: overridden virtual function is here
    virtual void normalizeFloat (float srcMinVal, float srcMaxVal) {};
                 ^
1 warning generated.
```

Since `imagefloat.h` is included in many files, this completely spams the build log. Easy fix I assume @heckflosse ?

**Comment by Floessie** [comment]
@Thanatomanic Why not just fix it?

**Comment by Thanatomanic** [comment]
@Floessie Because I lack the knowledge to judge if this was programmed intentionally for some reason, or if it would somehow break something else. I seriously need to start understanding some C++ keywords better 🙄 

I'll try fixing it!
