### ISSUE TITLE
Warning something clobbered in `savePNG`

### ISSUE THREAD

**Issue by Thanatomanic** [Beep6581/RawTherapee#5014]
No clue what that means, but I'm just relaying my build warning using `-Wextra`

```
C:/msys64/home/Roel/rt-dev/rtengine/imageio.cc: In member function 'int rtengine::ImageIO::savePNG(const Glib::ustring&, int) const':
C:/msys64/home/Roel/rt-dev/rtengine/imageio.cc:975:56: warning: argument 'bps' might be clobbered by 'longjmp' or 'vfork' [-Wclobbered]
 int ImageIO::savePNG  (const Glib::ustring &fname, int bps) const
                                                    ~~~~^~~
```

**Comment by ff2000** [comment]
Man gcc: "Warn for variables that might be changed by "longjmp" or "vfork"."
bps was declared volatile until recently, changed here: https://github.com/Beep6581/RawTherapee/commit/bfe84655630db4a5816003dab3782b9b79261e8d#diff-9cc64a95ee3135fa9f9d133820af996d

**Comment by Floessie** [comment]
Now, before reverting that change think about having a `volatile` copy of the by-value input parameter that won't affect the function signature for purely internal reasons.
