### ISSUE TITLE
Gamutcheck for monitor

### ISSUE THREAD

**Issue by Desmis** [Beep6581/RawTherapee#5019]
Actually "Gamut check" to see Out of gamut colors only works well with RTv2 and gamma simple.

If you use ICC v2  and TRC as sRGB or BT709, the image is full of  green dots
if you use ICCv4 nothing works

At first I think a problem with LUT, I tried many solutions and always same problem

I tried RTv2 and Rtv4 with TRC sRGB or BT709 with Photoshop and all works well==>it is not a LUT problem

I think it is a LCMS bug, the "same" as I implemented in "iplab2rgb.cc" to sove bad result in histogram for low light
I use the same solution in "improcfun.cc", but always dots
I think another bug, I solved by a strange action, only for blue tag, I replace TRC sRGB or same by gamma simple, and result seems good

For ICCv4, I used the same strange action, and now RTv4 seems to work well !!!

I don't understand why this very strange change works,...but it seems to work in  all cases with files RTv2 or RTv4

I create a branch "gamutcheck_monitor"

jacques

**Comment by Thanatomanic** [comment]
@Desmis You're infinitely more an expert on color management than I am, but with all the heated talk about color management and workflows happening [on the forums](https://discuss.pixls.us/t/hdr-aces-and-the-digital-photographer-2-0/9918/120), and quite some outstanding issues here (#4150 #4361 #4583 #4737 to name a few), would it be a good idea for v5.6 to:

1. Carefully revisit the our color mangement throughout the pipeline
2. Build a series of test cases to figure out what should be happening and what is actually happening
3. Consult others for input

What do you think?

**Comment by Desmis** [comment]
@Thanatomanic 
I will open an issue for "review" 
Jacques

**Comment by Desmis** [comment]
I have modified the patch with enhancement from Alberto @agriggio 

All seems to work well, now you can check the gamut with monitor, for RTv2 and RTv4

As I will be away since tomorrow, If somebody can merge this barnch, if of course he agree with this change

Jacques

**Comment by agriggio** [comment]
I just pushed a fix for this (see my comment in #5035 as well)
