### ISSUE TITLE
Setting of C_FLAGS and CXX_FLAGS is persistent

### ISSUE THREAD

**Issue by Thanatomanic** [Beep6581/RawTherapee#5020]
Try the following:

```
cd build
rm -rf *
cmake -G "MSYS Makefiles" -DLENSFUNDBDIR=/mingw64/share/lensfun -DCMAKE_BUILD_TYPE="release" -DPROC_TARGET_NUMBER="2" -DCACHE_NAME_SUFFIX="5-dev" -DCMAKE_C_COMPILER="gcc" -DCMAKE_CXX_COMPILER="g++" -DCMAKE_CXX_FLAGS="-Wno-parentheses" ..
cmake -G "MSYS Makefiles" -DLENSFUNDBDIR=/mingw64/share/lensfun -DCMAKE_BUILD_TYPE="release" -DPROC_TARGET_NUMBER="2" -DCACHE_NAME_SUFFIX="5-dev" -DCMAKE_C_COMPILER="gcc" -DCMAKE_CXX_COMPILER="g++"  ..
```

If you look for example in the `build\rtengine\CMakeFiles\rtengine.dir\flags.make` file, you will see that after the second cmake command the CXX_FLAGS from the first are still set. I believe this should not happen - or at least is _very_ counter intuitive.
Maybe related to #4976.

**Comment by Floessie** [comment]
As far as I can tell, CMake is meant to be run once. If I change the toolchain for an already configured project when crosscompiling, it's not enough to run CMake a second time. Does `autoconf` permit a second run with fundamental parameters changed? Even if so, is that crucial?

As for your problem: You can have as many build dirs as you like. I have one for release, one for debug, and one for Clang. Sometimes I create a new one for testing and throw it away afterwards. That's how I understand CMake persistence.

HTH,
Flössie

**Comment by heckflosse** [comment]
@Floessie 

> I have one for release, one for debug, and one for Clang

Same here, `rebuild`, `debuild` and `clbuild` for release, debug and clang

**Comment by Thanatomanic** [comment]
Thanks, I'll adjust my workflow if what I was doing is not the intended use of CMake :-)

**Comment by Beep6581** [comment]
Same here, as per the `build-rawtherapee` script.
