### ISSUE TITLE
If a custom TRC is set, it is applied after every edit

### ISSUE THREAD

**Issue by Thanatomanic** [Beep6581/RawTherapee#5023]
I am not quite sure how to give this one a proper title, but it's easy to reproduce:

1. Apply neutral
2. In Working Profile, set a custom TRC and change the Gamma or Slope
3. Repeatedly enable/disable a module [1]
4. The image gets darker or lighter after every operation.

It is only a visual thing while editing, because if you reload or zoom the image the effect is gone

Note 1: It only works for modules that work in RGB space, Lab tools are unaffected

**Comment by heckflosse** [comment]
@Thanatomanic @Beep6581 @Desmis @agriggio Currently the effect of custom TRC is not visible on the thumbnail. Shall I add that for 5.5?

**Comment by Desmis** [comment]
@heckflosse 

Ingo
Thanks for solving this situation
jacques

**Comment by heckflosse** [comment]
@Desmis Jacques, de rien :)
