### ISSUE TITLE
can't open any image

### ISSUE THREAD

**Issue by fasssc2** [Beep6581/RawTherapee#5038]
RT 5.4 for Windows Vista/7/8/10 64-bit - fast

when i try to open an image from my computer the program doesn't open it idk why

![image](https://user-images.githubusercontent.com/45392484/49083114-f9125f80-f24b-11e8-8d23-3964c29c03e7.png)

i downloaded raw therapee from https://rawtherapee.com/downloads

**Comment by Thanatomanic** [comment]
The only reason for that to happen is if there are no images in that folder. Did you double click the folder?

Could you also please check in your preferences (I don't know the exact name of the tab, I think the third) if there are ticks for all file formats?

**Comment by fasssc2** [comment]
I didn't touch anything.
Yesterday used to works but today don't.

There are imagine in the folder.
I also tried to open other folder but it's the same things.
(Sorry for the english, i'm italian and i don't speak very well english)

---------- Forwarded message ---------

**Comment by fasssc2** [comment]
I didn't touch anything.
Yesterday used to works but today don't.

There are imagine in the folder.
I also tried to open other folder but it's the same things.
(Sorry for the english, i'm italian and i don't speak very well english)

Il giorno Mar 27 Nov 2018, 13:59 Roel Baars <notifications@github.com> ha
scritto:

**Comment by ff2000** [comment]
I had something similar happen when I had a huge panorama lying in the same folder. You have a scrollbar in the bottom that indicates a huge amount of horizontal space in use.
You can play with the filter and only activate one filytype at a time. Perhaps that helps to find out the "bad" images.

I think the thumb view could do a better job with layout in such cases.

**Comment by fasssc2** [comment]
in fact the horizontal bar does not indicate anything, because when I open
the application it is so, even if I do not touch anything. it's always like
that, so I do not think it has anything to do with it

Il giorno Mar 27 Nov 2018, 14:09 ff2000 <notifications@github.com> ha
scritto:

**Comment by Thanatomanic** [comment]
Can you copy/paste a screenshot of the contents of the folder in Windows Explorer? Please enable thumbnails, if possible.

**Comment by fasssc2** [comment]
![image](https://user-images.githubusercontent.com/45392484/49084814-d2a2f300-f250-11e8-82c3-9079dfcf64e9.png)

**Comment by fasssc2** [comment]
![image](https://user-images.githubusercontent.com/45392484/49084885-ff570a80-f250-11e8-8e9c-4ccd4855d7e9.png)

**Comment by fasssc2** [comment]
i always used raw therapee without changing any settings. the other day it came out an updating i think and I can't open image anymore.
i haven't change camera or phone i always take the same picture with the same settings so idk.
I'm not that good with computer but i don't think i touched something wrong ahahah

**Comment by heckflosse** [comment]
Please have a look at the file extensions in preferences:
![grafik](https://user-images.githubusercontent.com/13733487/49085963-9ae97a80-f253-11e8-8dbd-a984ff15a87e.png)

**Comment by fasssc2** [comment]
![image](https://user-images.githubusercontent.com/45392484/49092954-739aa980-f263-11e8-968f-6da926233e3f.png)

**Comment by Thanatomanic** [comment]
Now that's interesting...
Could you please type the following in Windows Explorer: `%LOCALAPPDATA%` and then look up the RawTherapee folder there and remove the options file. Then restart RT.

**Comment by fasssc2** [comment]
I added "cr2" (the format of te image) at parsed extension, now it works!

**Comment by Beep6581** [comment]
@fasssc2 delete your `options` file as described here:
http://rawpedia.rawtherapee.com/Preferences#Parsed_Extensions

**Comment by Beep6581** [comment]
@fasssc2 which version did you update from?

**Comment by Beep6581** [comment]
> You have a scrollbar in the bottom that indicates a huge amount of horizontal space in use.

@ff2000 it fooled me too, but now I reproduced (gtk+-3.22.30, Sabayon) that RT shows the same "huge-space" scrollbars when opening a completely empty folder:
![screenshot_20181128_073321](https://user-images.githubusercontent.com/5844619/49133482-96b76e80-f2e0-11e8-8882-f282072213f7.png)
