### ISSUE TITLE
can't use the hsv

### ISSUE THREAD

**Issue by fasssc2** [Beep6581/RawTherapee#5039]
RT 5.4 for Windows Vista/7/8/10 64-bit - fast
 the color doesn't change i don't know what to do 
![image](https://user-images.githubusercontent.com/45392484/49094398-7519a100-f266-11e8-94f0-ca5742f16a57.png)

**Comment by heckflosse** [comment]
![grafik](https://user-images.githubusercontent.com/13733487/49094535-cb86df80-f266-11e8-97ee-1b831923dff6.png)

and read http://rawpedia.rawtherapee.com/Main_Page
