### ISSUE TITLE
When exiting fullscreen, buttons become misaligned

### ISSUE THREAD

**Issue by snappyapple632** [Beep6581/RawTherapee#5041]
I am using the 64-bit version of RawTherapee 5.4 on Windows 10 build 1809. In the screenshot, RawTherapee selects Preferences, but the mouse cursor is blow the button. This occurs after entering and exiting fullscreen mode. 
![bug](https://user-images.githubusercontent.com/40573129/49196134-96e65700-f33e-11e8-8a89-9b3ec0df5b82.png)

**Comment by gaaned92** [comment]
@snappyapple632 
I cannot reproduce here with Rawtherapee5.4 and W10.
Could you please provide the simplest step by step procedure to reproduce.
Meanwhile, I found some glitches in the operating of this function. I will document in other thread.

**Comment by Beep6581** [comment]
@snappyapple632 can you reproduce this using the latest development build?
Try `RawTherapee_dev_*` from:
https://keybase.pub/gaaned92/RTW64NightlyBuilds/
If you can reproduce, show an uncropped screenshot of the whole screen.

**Comment by snappyapple632** [comment]
I am not able to reproduce it now. I will be closing this thread until it pops up again in my use and until I can gather more accurate instructions.
