### ISSUE TITLE
Crop Reset-Button sets X=Y=0

### ISSUE THREAD

**Issue by ff2000** [Beep6581/RawTherapee#5045]
The crop reset button (#5015) should use the method implemented in https://github.com/Beep6581/RawTherapee/commit/4a6449b310f57b27c07017e4fa96f1eec7c5284f - properly center-align the selection.

**Comment by Thanatomanic** [comment]
Can you explain why something else should happen? My impression of a reset is that you get the values back as if you applied the Neutral profile, i.e. the full uncropped image.

**Comment by TooWaBoo** [comment]
@Thanatomanic 
You forgot the ratio setting. ;-)

**Comment by Thanatomanic** [comment]
Two things can happen:

1. The crop is reset taking into account the ratio that has been set,
2. The crop is reset _and_ the ratio is reset to 'As Image'.

My intention has always been the second option, and then - indeed - I forgot to reset the ratio. But @ff2000 seems to want the first options.

So, opinions? @Beep6581 @heckflosse

**Comment by Beep6581** [comment]
I don't have a _strong_ preference, but the second option sounds better to me.

**Comment by ff2000** [comment]
I thought it was intentional that the ratio was kept.
I don't really care if it's reset to cameras native ratio  or keep the one set in the UI.
