### ISSUE TITLE
Panasonic DC-LX100M2 raw support

### ISSUE THREAD

**Issue by age1988** [Beep6581/RawTherapee#5049]
Is it possible to add support for Panasonic lx100 mark2 .
link to the sample .RW2 raw
https://filebin.net/eeqfofmhc894u6r2

**Comment by Beep6581** [comment]
Preliminary support added for RawTherapee 5.5.

@age1988 could you get us sets 1 and 2 with intermediate ISO values as described here?
http://rawpedia.rawtherapee.com/Adding_Support_for_New_Raw_Formats

**Comment by age1988** [comment]
It works very well in the dev version, thank you.
Should the raw files  be totally overexposed?

**Comment by Beep6581** [comment]
As stated in the documentation.
