### ISSUE TITLE
mac/gui: The tiny plus/minus buttons have disappeared. Where do they come from?

### ISSUE THREAD

**Issue by Benitoite** [Beep6581/RawTherapee#5051]
![screenshot 2018-12-01 at 9 46 33 am](https://user-images.githubusercontent.com/17919239/49331198-3d547700-f54e-11e8-91c1-83e21c5d6755.png)

I've built RT for macOS on a fresh system and seem to have lost these two icons.  Does anyone know where they come from?   It happens on all themes, and on every system with this bundle.

```
Version: 5.4-1281-gd0fe52c3e
Branch: dev
Commit: d0fe52c3e
Commit date: 2018-11-30
Compiler: clang 10.0.0.10001145
Processor: generic x86
System: Apple
Bit depth: 64 bits
Gtkmm: V3.22.3
Lensfun: V0.3.95.0
Build type: release
Build flags: -std=c++14 -std=c++11 -mtune=generic -Werror=unused-label -mmacosx-version-min=10.9 -flto -Xpreprocessor -fopenmp /opt/local/lib/libiomp5.dylib -I/opt/local/include -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -O3 -DNDEBUG -ftree-vectorize
Link flags:  -mtune=generic -headerpad_max_install_names -flto
OpenMP support: ON
MMAP support: ON

```
(ignore the dual -std definitions for now that has been fixed)

**Comment by Beep6581** [comment]
Those two icons are called `list-add-symbolic` and `list-remove-symbolic`, and they come from `adwaita-icon-theme` or whatever icon theme your system is configured to use for GTK3 apps.

**Comment by Benitoite** [comment]
Thanks for the help @Beep6581  I had to install the adwaita icons from its repo. Once I did and reran the bundling script the icons magically appeared in the program.  Didn't even have to restart the app. 
I have the list-add and list-remove icons, but still don't have the drop-down thingies:
![screenshot 2018-12-01 at 10 57 53 pm](https://user-images.githubusercontent.com/17919239/49336756-e5a12480-f5bc-11e8-86d0-a3872476109a.png)
I those are svg's I may need librsvg.

**Comment by Beep6581** [comment]
@Benitoite that's `pan-down-symbolic`.

**Comment by Beep6581** [comment]
For reference, File Browser treeview:
![imgur-2018_12_02-14 34 50](https://user-images.githubusercontent.com/5844619/49340401-86382880-f63f-11e8-956c-7a1bc84dfccf.png)

Metadata panel:
![imgur-2018_12_02-14 35 40](https://user-images.githubusercontent.com/5844619/49340405-951edb00-f63f-11e8-823a-746d449d5894.png)

**Comment by Beep6581** [comment]
And comboboxes should also have the `pan-down-symbolic` icon:
![imgur-2018_12_02-14 36 51](https://user-images.githubusercontent.com/5844619/49340422-d7481c80-f63f-11e8-9c8a-edef227c6811.png)

Queue:
![imgur-2018_12_02-14 37 23](https://user-images.githubusercontent.com/5844619/49340453-4e7db080-f640-11e8-85da-e837995cffaa.png)

Film Simulation:
![screenshot_20181202_143923](https://user-images.githubusercontent.com/5844619/49340445-2d1cc480-f640-11e8-83c9-f4c346dff047.png)

Profiled Lens Correction:
![imgur-2018_12_02-14 40 18](https://user-images.githubusercontent.com/5844619/49340451-402f9480-f640-11e8-934e-e23d80ce26da.png)

**Comment by Benitoite** [comment]
An old `/opt/local/share/icons/Adwaita` copied over from my previous install includes all the correct icons.
![screenshot 2018-12-02 at 9 52 46 am](https://user-images.githubusercontent.com/17919239/49343136-fa130a80-f618-11e8-8835-a6092ca57c64.png)
Case closed, thanks again.
