### ISSUE TITLE
Simplify resetting white balance to "camera"

### ISSUE THREAD

**Issue by ff2000** [Beep6581/RawTherapee#5054]
When manually adjusting white balance the WB-selector jumps to "Custom". If I later want to reset it to camera I have to scroll through the whole list of available WB presets, as "Custom" is at the bottom and "Camera" is on the top. Unfortunately the WB selector is some sort of self-scrolling widget that takes some time to navigate through.
It would be easier if the "Custom" entry was either on top or below "Camera".
IMO it also is useless to make the selector scrollable in the first place as it doesn't contain that many items. [[This seems to be a GTK feature to keep the selected item under the mouse cursor. When maximized there is not enough space above the widget so it has to scroll. So if the order of entries get changed some item always will cause the scrollbars to appear...]]
And I also think the "reset to default" button shouldn't set an arbitrary default value but the "camera" value. Whenever I want to reset e.g. temperature to camera I want to click that button.

**Comment by Thanatomanic** [comment]
> And I also think the "reset to default" button shouldn't set an arbitrary default value but the "camera" value. Whenever I want to reset e.g. temperature to camera I want to click that button.

This makes sense to me :+1:
Similar to the introduction of a reset button for the crop, we could introduce a general reset button for the white balance. The reset being "Camera".

**Comment by Thanatomanic** [comment]
@ff2000 This might have been one of the smallest most unobtrusive GUI changes ever ;-)
![image](https://user-images.githubusercontent.com/6567747/119217813-01764900-badd-11eb-8669-e2b5bb6a1977.png)
