### ISSUE TITLE
Get rid of special windows code

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#5058]
I created a [branch](https://github.com/Beep6581/RawTherapee/tree/get-rid-of-special-windows-code) to get rid of special windows code.

The first commit gets rid of rtgui/windirmonitor.cc and .h

@Thanatomanic @Hombre57 @Desmis @TooWaBoo 
Please test whether RT still detects new files/folders in the currently active folder.

**Comment by Thanatomanic** [comment]
Interesting, I will check somewhere during the week!

**Comment by heckflosse** [comment]
No hurry please. That's for 5.6

**Comment by heckflosse** [comment]
I added a commit which gets rid of special windows code in `MultiLangMgr::getOSUserLanguage()`

**Comment by TooWaBoo** [comment]
@heckflosse 
So far no issues found.

**Comment by heckflosse** [comment]
Test case for last commit: zooming thumbnails in file browser should still work.

**Comment by heckflosse** [comment]
I think we can close this. Objections?
