### ISSUE TITLE
Release Candidate is flagged by TrendMicro as ransomware.....

### ISSUE THREAD

**Issue by todd-prior** [Beep6581/RawTherapee#5069]
Tried to install the current release candidate for windows and it is flagged by Trend Micro as ransomware...has anyone else encountered this??

**Comment by Benitoite** [comment]
Yes this is common with various anti-malware solutions.  I assume you are trying 
https://rawtherapee.com/releases_head/windows/RawTherapee_releases-5.5-rc1_WinVista_64.exe
?

**Comment by todd-prior** [comment]
I was….thanks for the comments

**Comment by Beep6581** [comment]
https://www.virustotal.com/#/file/6833e2710dfeb89652841c83a18875e64f8de04fa0a68b693c3f96a662035fea/detection
