### ISSUE TITLE
Keybase.pub Windows Builds

### ISSUE THREAD

**Issue by raceviper13** [Beep6581/RawTherapee#5073]
@gaaned92 The keybase.pub repository for your Windows builds is great.  I appreciate the work you do to get them in there on a regular timeframe.  Is there anyway we can tag the files with a date?  I cannot see any date anywhere for the files to help me see what was compiled, and when.  Thanks!

**Comment by gaaned92** [comment]
@raceviper13 
I will see if it is possible in keybase.pub. Otherwise I will add the date in the zip name.


> RawTherapee_dev_5.4-1329-g033b021b9_WinVista_64_181208-1751.zip                                                                                                 

 uploaded at          
https://keybase.pub/gaaned92/RTW64NightlyBuilds/

**Comment by gaaned92** [comment]
@raceviper13 
If not possible with keybas.pub, I will add the date to the zip name.

**Comment by raceviper13** [comment]
Thank you!  This helps me a lot.

**Comment by gaaned92** [comment]
You are welcome!
Can we close?

**Comment by raceviper13** [comment]
yes.
