### ISSUE TITLE
Spanish translation completed RawRherapee 5.4

### ISSUE THREAD

**Issue by Faber777** [Beep6581/RawTherapee#5079]
Spanish translation completed
Hi. I am a photographer and several years ago I used raw terapee, seeing that the lack of translation of a good part of the Spanish language slowed down my work and decided to translate what was missing. This helped me a lot, now I decide to share it. I hope that this will help other Hispanics to be encouraged to use the program and it is my way of enriching for years of good services of Rawtherapee. Saludos
[Espanol.txt](https://github.com/Beep6581/RawTherapee/files/2660192/Espanol.txt)

**Comment by Beep6581** [comment]
@Faber777 thank you, I committed your changes for inclusion in RawTherapee 5.5.  There are a few new strings which need to be translated, see the file in `dev`:
https://github.com/Beep6581/RawTherapee/blob/dev/rtdata/languages/Espanol
