### ISSUE TITLE
New Spanish language update

### ISSUE THREAD

**Issue by Faber777** [Beep6581/RawTherapee#5085]
Hi.
I re-send the file in Spanish, completed with the Spanish translation from line 2273 to line 2463. I think it's coming to an end.
It also contains some corrections regarding the previous file sent a few days ago.
[espanol.txt](https://github.com/Beep6581/RawTherapee/files/2665441/espanol.txt)

**Comment by Beep6581** [comment]
Thank you @Faber777

**Comment by Faber777** [comment]
final corrections to Spanish:
I attach a few entries where I made corrections to Spanish


[espanol -correcciones_2.txt](https://github.com/Beep6581/RawTherapee/files/2687148/espanol.-correcciones_2.txt)

**Comment by Faber777** [comment]
I attach a few entries where I made corrections to Spanish
[espanol_correcciones.txt](https://github.com/Beep6581/RawTherapee/files/2687188/espanol_correcciones.txt)

**Comment by Beep6581** [comment]
@Faber777 replace the old entries in https://github.com/Beep6581/RawTherapee/blob/dev/rtdata/languages/Espanol with the new ones and submit the whole file in a new issue
