### ISSUE TITLE
Possible problem compiling RT5.5 rc2 just now

### ISSUE THREAD

**Issue by RawConvert** [Beep6581/RawTherapee#5090]
The terminal output from the "make" command included this -
.....
[ 83%] Building CXX object rtgui/CMakeFiles/rth.dir/rawcacorrection.cc.o
[ 84%] Building CXX object rtgui/CMakeFiles/rth.dir/rawexposure.cc.o
[ 84%] Building CXX object rtgui/CMakeFiles/rth.dir/recentbrowser.cc.o
/home/paulssd2/RT55rc2/code-rawtherapee/rtengine/lj92.c: In function ‘lj92_decode’:
/home/paulssd2/RT55rc2/code-rawtherapee/rtengine/lj92.c:558:14: warning: ‘Px’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         left = Px + diff;
              ^
/home/paulssd2/RT55rc2/code-rawtherapee/rtengine/lj92.c:524:9: note: ‘Px’ was declared here
     int Px;
         ^
[ 84%] Building CXX object rtgui/CMakeFiles/rth.dir/renamedlg.cc.o
[ 84%] Built target rth-cli
[ 85%] Building CXX object rtgui/CMakeFiles/rth.dir/resize.cc.o
[ 85%] Building CXX object rtgui/CMakeFiles/rth.dir/retinex.cc.o
......

**Comment by Floessie** [comment]
The compiler is too cautious, there is [no problem](https://github.com/Beep6581/RawTherapee/blob/920e9f7a16fe1f9e0d6d70d1a547f52781d97cc0/rtengine/lj92.c#L509). But to help the analysis we could initialize `Px` with `0`.

**Comment by RawConvert** [comment]
It would be nice if the compile produced no "worrying" messages, so yes, let Px = 0 somewhere !
