### ISSUE TITLE
Processing profile selector is spammed with (Custom) entries after applying profiles using the load button

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#5092]
While testing #5089 I applied pp3 files using the load button several times, which resulted in this nonsense:
![grafik](https://user-images.githubusercontent.com/13733487/49866927-5dffb500-fe09-11e8-8096-c0531490aaed.png)

**Comment by Hombre57** [comment]
@heckflosse @Beep6581 Fixed in commit 71a5521 . Please test branch `profile-panel-bugfix`

**Comment by Hombre57** [comment]
Branch `profile-panel-bugfix` merged into dev.

**Comment by Hombre57** [comment]
@Beep6581 This fix is pretty simple, could it be part of 5.5 ?

**Comment by Beep6581** [comment]
Sure thing @Hombre57
