### ISSUE TITLE
Cleanup of bundled processing profiles

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#5093]
Some of our bundled processing profiles:
* Do not work.
* Do things in an over-complicated and outdated way, instead of making use of newer, friendlier tools.
* Do things which they shouldn't be doing.
* Are not documented.
* Are not maintained by anyone.

For example the Faded profiles use the channel mixer for color toning instead of using one of our 7 dedicated color toning tools. If a user feels that "faded chocolate" is a bit too chocolate, it's not a simple and intuitive adjustment to change that. Furthermore, the channel mixer values stored in that profile no longer work (fallout from #4805), and even if they were updated, the profile still does not work - the channel mixer is not enabled. Who knows what else. Lastly, the profile does things it should not be doing - a profile intended for color toning has no business changing the noise reduction settings.

I want to remove the following unmaintained profiles for 5.5:
* Black-and-White (main argument: they're almost identical)
* Faded (broken, made obsolete by new and much more user-friendly color toning tools)
* Generic (broken and not interesting, don't work with histogram matching, intention not documented)
* Portrait
* Skintones (not documented, partially broken)

I've seen posts by people who had tried RawTherapee and reported that all the presets look bad. Not surprising. I hope that removing these unmaintained profiles will prevent that. We can work on new profiles for 5.6.

**Comment by Hombre57** [comment]
I tried a faded profile just now, and the effect looked weird mostly because it doesn't enable the tools it modify. So :+1:

**Comment by Beep6581** [comment]
Deleted unmaintained profiles in 1e45112d4 , updated other profiles in c8042271d.

**Comment by dogo77** [comment]
Hi, 
i just updated RT to 5.5 and the first thing i missed were the bundled profiles… :D
Although most profiles didn't fit my nedds/taste i have been a heavy user of the skintones/TM preset as they worked very well with my ILCE-6000 and geve the desired look.

So 2 Questions from my side:
1) Where can i find the old presets for downloading and reimporting  them? In an older branch?
2) will they really come back in 5.6? ;)

i for my side can't corroborate "that all the presets look bad." As a more or less very unexperienced user (i just started shooting raw in August '18) they gave me a good start with nice output files right from the start and made me start learning RT over DT.

NTL, Thanks for that release!

**Comment by Beep6581** [comment]
Hey @dogo77 

You can find them here:
https://github.com/Beep6581/RawTherapee/tree/5.4/rtdata/profiles

New tools bring new possibilities. There will be new profiles in 5.6.

**Comment by saalaa** [comment]
Hey, since this is still open, I'll just point out that no new profiles have been added and we're currently at version 5.6 :)

May I suggest colaborating with these projects : 

- https://github.com/GLTR87/RawTherapee-presets-Fuji-inspired
- https://github.com/pixlsus/RawTherapee-Presets
