### ISSUE TITLE
Retinex with chroma and mixed algoritm with Dehaze

### ISSUE THREAD

**Issue by Desmis** [Beep6581/RawTherapee#5099]
I just create a new branch "retinex_chroma_dehaz"

1) I add a slider "chroma", now Retinex acts on luminance and chroma
I copy the work i have realized 2 years ago in waveletnew  for Retinex in Raw mode
It is not optimzed for SSE

2) I add a slider "Dehaze" which take into account alberto works, adapted  to retinex. just at the beginning of Retinex
The 2 algorithms works together, Dehaze take into account retinex settings (strength, radius, contrast)

The result seems good (for my point of view)

jacques

**Comment by heckflosse** [comment]
@Desmis 
> It is not optimzed for SSE

I will have a look

**Comment by Desmis** [comment]
@heckflosse 

Ingo, thank you very much 

jacques

**Comment by Beep6581** [comment]
* The preview matches the output, good.
* Bug in history:
  1. Open photo, enable Retinex
  1. Set Dehaze to 100
  1. Go back in history - the slider changes to 0 but the preview does not change, it still looks like dehaze=100.
* There are hard-coded 200ms delays (in this branch and in `dev`), they should probably be replaced with `options.adjusterMaxDelay`
* The language string keys should be changed for readability, `DEHAZ` > `DEHAZE`, `RETIDEHAZ` > `RETINEX_DEHAZE`, `CHRRT` > `CHROMA`, etc. There is nothing to gain by using obfuscated abbreviations.
* Chroma can already be controlled using L\*a\*b\*, dehazing can already be done using the Dehaze tool, so the practical benefit of these is not clear to me. I only have two hazy test-images, so it's likely I'm not seeing the full benefit.
* In one of my two test-images http://rawtherapee.com/shared/test_images/dehaze2.nef , using Retinex > Dehaze leads to haloing around the left edge. The halo does not appear when using Retinex + the Haze Removal tool in the Detail tab in `dev`,
  * Advanced > Retinex > Dehaze (`retinex_chroma_dehaz` `5.4-1364-g`9968d4936): 
![screenshot_20190402_104122](https://user-images.githubusercontent.com/5844619/55388692-04e09c00-5534-11e9-82fd-aed1698657f5.png)
  * Detail > Haze Removal + Advanced > Retinex (`dev` `5.5-282-g`458f47d12): 
![screenshot_20190402_104145](https://user-images.githubusercontent.com/5844619/55388785-2b063c00-5534-11e9-8ba6-682b31a74957.png)
