### ISSUE TITLE
Better xtrans fast algorithm

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#5107]
I changed the calculation of the green channel in xtrans fast implementation.
The current version calculates the average of the sorrounding 5 greens when at a red or blue location while using the original value when at a green location. That leads to a kind of dotty look.
The new version always calculates the average of the sourrounding 5 greens.
That leads to a smoother look.
Left is current version, right is new version
![grafik](https://user-images.githubusercontent.com/13733487/50218046-e2fb4900-038a-11e9-8593-da8dff3eab1e.png)

branch follows

@sguyader what do you think?

**Comment by Beep6581** [comment]
@heckflosse I'd go with whichever gets denoised better.

**Comment by heckflosse** [comment]
The same with denoise. This time left is the new version and right the old version
![grafik](https://user-images.githubusercontent.com/13733487/50219022-286d4580-038e-11e9-9565-5dcd85cb80c1.png)

**Comment by heckflosse** [comment]
Here's an ISO 200 shot with a bit of sharpening applied
Left is new version, right is old version
![grafik](https://user-images.githubusercontent.com/13733487/50219181-a598ba80-038e-11e9-9f67-7cdc32f64b07.png)

**Comment by sguyader** [comment]
@heckflosse I'll try later. Where can I find it?

**Comment by heckflosse** [comment]
@sguyader I just created branch `xtrans_fast_smooth`

**Comment by heckflosse** [comment]
As an alternative also
```
green[row][col] = sum[1] * 0.1f + rawData[row][col] * 0.5f;
```
could be used

Example: left current code, middle branch code, right using the alternative calculation:
![grafik](https://user-images.githubusercontent.com/13733487/50222878-dfbb8980-0399-11e9-9902-f6bdd5ae9a69.png)

**Comment by sguyader** [comment]
@heckflosse I think I prefer the old algorithm to the `xtrans_fast_smooth` one. The new blurs too much detail, and even in combination with the 3-pass, the smooth areas tend to look blotchier to me.
Can I try the second alternative?

**Comment by heckflosse** [comment]
@sguyader To simplify testing, I just added an adjuster ;-)
At value zero it's old behaviour. At value 100 it's behaviour from first commit...

**Comment by heckflosse** [comment]
@sguyader I forgot to mention that the new adjuster is only visible in 3-pass+fast and 1-pass+fast, not in plain fast

**Comment by sguyader** [comment]
@heckflosse I failed to find cases in my images where the new fast algo improves things, but as I said yesterday I found that it tends remove some microcontrast in foliage or rocks for example. and in noisy images, the noise looks coarser to me, which I don't find desirable.

**Comment by heckflosse** [comment]
@sguyader Thanks for testing :+1: Btw: I got the idea to test this as I saw this noise comparison on dpreview.
https://www.dpreview.com/forums/post/62062522?image=0

I will stop work on this branch now, but let the branch and the issue open for a while

**Comment by sguyader** [comment]
It was just my opinion, I'd like to hear others'.
Can you implement the second alternative algorithm you showed? It looked more balanced to me, smoothing a little bit but still keeping more detail than the "new fast".

**Comment by heckflosse** [comment]
@sguyader Oh, I thought you tried already my second alternative with the adjuster

**Comment by heckflosse** [comment]
@sguyader Just pull the branch and use the adjuster. Value zero is like dev, value 1 is like first commit, value 0.5 is like the alternative

Edit: and everything in between is also possible using different adjuster values

**Comment by heckflosse** [comment]
@sguyader Sébastien, I mean this adjuster:
![grafik](https://user-images.githubusercontent.com/13733487/50317828-f22ee380-04bd-11e9-8a06-31909b4a1794.png)

**Comment by sguyader** [comment]
Okay, I thought the adjuster was just 0/100, old/first commit, I didn't try at 50. I'll try tomorrow.

**Comment by sguyader** [comment]
@heckflosse I've tried to compare a few images with the slider at 0,50 or 100, but I failed to find instances when I prefer the result of green smoothing. In clean images there's not much difference, but when noise start to kick in, I prefer the original fine grain than the modified blotchier grain.

I have one question: is there a possibility that playing with the Haze Removal depth slider can affect the demosaicing? A couple times I saw something strange, when it looked like the dual-demosaicing was reversed: detailed regions where demosaiced with the fast algo (and maybe, but not surely, the smooth regions were demosaiced with the 3-pass algo). I couldn't reproduce it when I wanted, though. But what is surprising, is that when I compared saved images which apparently had this weird thing, I preferred the look of images with edges and detailed regions demosaiced with the "smooth green" fast algo with slider at 50. It's too bad, those saved images have been overwritten.
It may be worth trying to try a new dual-demosaicing algo : detailed regions demosaiced with the smooth green fast algo, and smooth regions with the original fast algo? But I'm not sure it makes sense. Don't spend too much time on this, the current dual-demosaicing for X-trans is already the best in business.

**Comment by heckflosse** [comment]
@sguyader 
> is there a possibility that playing with the Haze Removal depth slider can affect the demosaicing?

Looking at the code I would exclude that

> It may be worth trying to try a new dual-demosaicing algo : detailed regions demosaiced with the smooth green fast algo, and smooth regions with the original fast algo?

I guess you already know the answer because it was you, who correctly showed the artifacts using fast xtrans for detailed regions by setting the contrast threshold adjuster to too large value ;-)

> the current dual-demosaicing for X-trans is already the best in business

\o/

Anyway, I will close now. It was worth trying out at least :smiley:

**Comment by iliasg** [comment]
@heckflosse 
Ingo, 
- At least at the Dpreview sample in the linked post I see that many (if not most) "dotty" pixels come from clipping at the BlackLevel .. while none of these appear as clipped in ACR's demosaic .. it would be a better compromise if we just count the clipped pixels as unreliable and only use a weighted average on them.

- For the calculation of green value on Red and Blue places .. I am not sure if it's exactly the average of the 5 green neighbours .. if it's so I think we should better use a weighted average also .. I think it will not give a significant speed penalty .. just use the inverse square law for the diagonal greens
Green_at_B = (Gleft+Gtop+Gbottom +0.5*(Gtop_right+Gbottom_right)) *0.25
R  G  G  B  G  G  R
G  B  R  G  R  B  G
R  G  G  B  G  G  R
B  G  G  R  G  G  B
G  R  B  G  B  R  G

I think @sguyader Seb will be happier after this ;)

Happy the coming year ..

**Comment by sguyader** [comment]
Thanks for taking a look @iliasg

**Comment by heckflosse** [comment]
@iliasg I will try that next days

**Comment by heckflosse** [comment]
@iliasg @sguyader Here's a first screenshot using the fast interpolation suggested by Ilias

Left is old fast xtrans, right is new
![grafik](https://user-images.githubusercontent.com/13733487/50540907-14e68980-0b9b-11e9-9bd6-9c75dade1b21.png)

**Comment by heckflosse** [comment]
And here's the patch:

```diff
diff --git a/rtengine/xtrans_demosaic.cc b/rtengine/xtrans_demosaic.cc
index ed253749b..580905973 100644
--- a/rtengine/xtrans_demosaic.cc
+++ b/rtengine/xtrans_demosaic.cc
@@ -978,6 +978,7 @@ void RawImageSource::fast_xtrans_interpolate (const array2D<float> &rawData, arr
     int xtrans[6][6];
     ri->getXtransMatrix(xtrans);
 
+    const float weight[3][3] = {{0.25f, 0.5f, 0.25f}, {0.5f, 1.f, 0.5f}, {0.25f, 0.5f, 0.25f}};
     #pragma omp parallel for
 
     for(int row = 1; row < height - 1; row++) {
@@ -986,26 +987,31 @@ void RawImageSource::fast_xtrans_interpolate (const array2D<float> &rawData, arr
 
             for(int v = -1; v <= 1; v++) {
                 for(int h = -1; h <= 1; h++) {
-                    sum[fcol(row + v, col + h)] += rawData[row + v][(col + h)];
+                    sum[fcol(row + v, col + h)] += rawData[row + v][(col + h)] * weight[v + 1][h + 1];
                 }
             }
 
             switch(fcol(row, col)) {
             case 0:
                 red[row][col] = rawData[row][col];
-                green[row][col] = sum[1] * 0.2f;
-                blue[row][col] = sum[2] * 0.33333333f;
+                green[row][col] = sum[1] * 0.5f;
+                blue[row][col] = sum[2];
                 break;
 
             case 1:
-                red[row][col] = sum[0] * 0.5f;
                 green[row][col] = rawData[row][col];
-                blue[row][col] = sum[2] * 0.5f;
+                if (fcol(row, col - 1) == fcol(row, col + 1)) { // Solitary green pixel always has exactly two direct red and blue neighbors in 3x3 grid
+                    red[row][col] = sum[0];
+                    blue[row][col] = sum[2];
+                } else {
+                    red[row][col] = sum[0] * 1.3333333f;
+                    blue[row][col] = sum[2] * 1.3333333f;
+                }
                 break;
 
             case 2:
-                red[row][col] = sum[0] * 0.33333333f;
-                green[row][col] = sum[1] * 0.2f;
+                red[row][col] = sum[0];
+                green[row][col] = sum[1] * 0.5f;
                 blue[row][col] = rawData[row][col];
                 break;
             }

```

**Comment by falket** [comment]
The new one seems better to me, with less artifacts. 

I see "strange" pixels almost only where there are chromatic aberrations, but maybe after a lensfun correction situation will be even better? Unfortunatly i can't compile on my pc and afaik there isn't yet an appimage of this version.

**Comment by iliasg** [comment]
@heckflosse 
> Left is old fast xtrans, right is new

Ingo, by "old fast" do you mean the first of your patches (without weights) ?.

The new, looks better .. less blury and with better color definition (well this was a surprise ;) )
Some "dots" are better defined and although this makes them more intrusive, I think this also makes the denoise easier .. 

Where can we find the raw samples you use ?
Usefull would be to use samples of resolution targets (from Dpreview, Imaging Resource, or ) to also check the fidelity of the various methods ..

I have lost all my compiling infrastructure (disk crashed again ..) .. I hope I'll be able to compile and test in the next days ..

**Comment by heckflosse** [comment]
@iliasg No, old means the one in dev (without weights)
For the last screenshot I used the raf from [here](https://discuss.pixls.us/t/playraw-eating-cicchetti-with-ghosts-in-venezia/5805)

I don't intend to make the fast xtrans demosaic a good xtrans demosaic. It will stay lousy at high contrast.
Imho the main usecase for fast xtrans demosaic is for flat regions in dual demosaic...

**Comment by iliasg** [comment]
@heckflosse Ingo .. thanks for declaring the intended use for fast .. I thing I (and not only I) had misunderstood it ;)

Now that I understand better ..

You want the fast demosaic for rendering smooth flat areas .. but not only this .. you also use it for the detection of flat areas .. correct ?.

So .. an unconditional 3X3 blur (like in your first patch) 
- is helpfull for smoothing 
- is damaging the detection of contrast at the borders of the flat areas and on fine details in flat areas ..
- is damaging the appearanse of noise by spreading say a single outlier pixel to a 3X3 (or maybe 5X5 ??) area .. this also makes denoising harder ..

Your (our) target is to find a formula (i.e. weighting method) which smooths effectivelly but has the less possible damaging effects .. and also be fast ;)

I think the 1/d^2 weighting is a good starting compromise .. maybe a fine tuning will help say instead of 1/d^2 we could use 1/d^1.4 ..

 All the above are theoretical .. I 'll be in better shape if/when I 'll manage to compile and test ..

BTW .. how about trying the 1/d^2 rule for 1-pass/3-pass intepolations also ? I mean the green_on blue/red part mostly ..

**Comment by heckflosse** [comment]
@iliasg 
> You want the fast demosaic for rendering smooth flat areas .. but not only this .. you also use it for the detection of flat areas .. correct ?.

Correct.

> So .. an unconditional 3X3 blur (like in your first patch)
>
>    is helpfull for smoothing
>    is damaging the detection of contrast at the borders of the flat areas and on fine details in flat areas ..
>    is damaging the appearanse of noise by spreading say a single outlier pixel to a 3X3 (or maybe 5X5 ??) area .. this also makes denoising harder ..

All this is correct as well, but the original fast xtrans demosaic (in dev) also had no weights because at the time I wrote it the intention was to have a fast xtrans demosaic for preview zoom ratios <= 50%, where quality was not really important. 
Now, as we use it in dual demosaic, quality became more important, but only for flat regions.

Imho the last patch (with the weights you suggested) gives better result than the current dev code for fast xtrans and I would like to commit it after @sguyader has tested.

**Comment by iliasg** [comment]
@heckflosse OK fine .. I trust Seb's tests more than mine ;)

Ingo, as I was absent from recent RT developments I missed the work you've made with dual demosaics :( .. I'd like to understand what you did and discuss some ideas .. should I open a new issue, reopen the old .. something else ??

**Comment by heckflosse** [comment]
@iliasg Ilias, for new ideas about dual demsoaic please open a new issue

**Comment by sguyader** [comment]
@heckflosse Info I'll test your patch tomorrow

**Comment by sguyader** [comment]
@heckflosse I must be doing something wrong, I applied the patch with success, but I fail to see any difference between dev and patched on my images (I tried different kinds of images, low or high iso).

**Comment by sguyader** [comment]
@heckflosse I must be doing something wrong, I applied the patch with success, but I fail to see any difference between dev and patched on my images (I tried different kinds of images, low or high iso).

**Comment by heckflosse** [comment]
@sguyader I get the differences only when using plain fast demosaic. When using 3-pass + fast they are not visible by eyeball because their visibility is mainly in contrasty regions which are taken from 3-pass.
However, the weighting Ilias suggested is definitely more correct than the old fast xtrans in dev.

**Comment by sguyader** [comment]
Ok, indeed I was using 3-pass + fast, now with plain fast I see that the new weighting scheme is better. +1 for pushing it to dev.

**Comment by heckflosse** [comment]
Ok to close?

**Comment by sguyader** [comment]
Ok for me.

**Comment by iliasg** [comment]
OK for me too ..

@heckflosse Ingo,
I'd just like to know how this change affects the use of fast demosaic for the detection of flat areas .. is it any better now ?

**Comment by heckflosse** [comment]
@iliasg The detection of flat regions for dual demosaic uses the more detailed demosaicer (3-pass/1-pass for xtrans amaze/dcb/rcd for bayer). So no changes here.
