### ISSUE TITLE
Ctrl Shift Right Click not deleting colour picker points

### ISSUE THREAD

**Issue by RawConvert** [Beep6581/RawTherapee#5108]
I'd put several colour pickers on the preview.  The tooltip says you can delete them all with ctrl shift rt.click but the result seems just the same as an ordinary right click i.e. picker tool turned off.
Version: 5.5-12-g39d37a6
Branch: dev
Commit: 39d37a6
Commit date: 2018-12-17

**Comment by heckflosse** [comment]
@RawConvert ctrl shift right click on a picker removes them all

**Comment by TooWaBoo** [comment]
You must click on one of the color picker.
EDIT: @heckflosse was faster. :-)

**Comment by RawConvert** [comment]
Ah ok, thanks.
