### ISSUE TITLE
Image editor preview differs from processed image

### ISSUE THREAD

**Issue by hyannes** [Beep6581/RawTherapee#5109]
This issue is pretty much persistent on profiles that have a lot of changes made to the exposure tab, though I've never seen it occur on any image that's only been lightly edited. It's nothing particularly big nor is it noticeable at first, but you can notice contrast and highlight differences from the previewed and processed image after a second look. I've tried pin-pointing the particular culprit setting that's responsible for this slight difference in preview and output, but I suspect that it might be the combination of settings that lead to this(??) I might be mistaken, since I don't really know anything about it but I've been really bothered by this issue and it has been haunting me ever since RT 5.4. That said, I've searched for similar issues and [this](https://github.com/Beep6581/RawTherapee/issues/1118) was the closest one that fits my description, except that its profile/setting/processing independent and I suspect mine _is_ dependent. (Again, I could be wrong)

This is an output and preview image comparison for the auto-levels: 
![auto](https://user-images.githubusercontent.com/46019383/50275583-bb6eb400-0450-11e9-8de6-936efb328eda.gif)

This is for the heavily tweaked profile: 
![not-auto](https://user-images.githubusercontent.com/46019383/50275635-e0632700-0450-11e9-8a7e-67738d12cd5c.gif)

Absolutely subtle, and add the horrible GIF quality, it's barely noticeable. But still paying attention to the contrast on my cat's nose, fur going up to the eye, the fur around the eye and the contrast within the eye itself, I would say it becomes flatter. It was quite worse before I updated to 5.5 (from 5.4). The highlights would be somewhat compressed despite not using any kind of highlight compression and that would make the image look very flat. 

I'm sorry if this issue has already been solved but I've already tried a lot of things and I didn't really want to resort to this, yet here I am.

Auto-levels pp3: 
[IMG_1061.jpg.out.zip](https://github.com/Beep6581/RawTherapee/files/2698161/IMG_1061.jpg.out.zip)

Edited pp3: 
[IMG_1061-3.jpg.out.zip](https://github.com/Beep6581/RawTherapee/files/2698157/IMG_1061-3.jpg.out.zip)

JPEG image (yes, it was shot on JPEG and not on RAW): 
![img_1061](https://user-images.githubusercontent.com/46019383/50276032-f7564900-0451-11e9-8489-baad88a8a04c.JPG)

If I'm still lacking requirements, please do tell.

Version: 5.5
Branch: 5.5
Commit: d9ac23555
Commit date: 2018-12-17
Compiler: gcc 8.2.1
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.22.3
Lensfun: V0.3.2.0
Build type: release
Build flags:  -m64 -mwin32 -msse2 -mfpmath=sse -mthreads -Wno-aggressive-loop-optimizations -Wno-parentheses -std=c++11 -mtune=generic -Werror=unused-label -Wall -Wuninitialized -Wno-deprecated-declarations -Wno-unused-result -fopenmp -Werror=unknown-pragmas  -DNDEBUG  -O3 -ftree-vectorize
Link flags: -m64  -mthreads  -static-libgcc   -mtune=generic  -s  -O3  -fno-use-linker-plugin
OpenMP support: ON
MMAP support: ON

**Comment by Thanatomanic** [comment]
For your edited pp3, you have some tools enabled that require you to view the image 1:1 to see the effect properly. That can explain the difference between output and zoomed-out preview.

As for both outputs: I get a perfect match between the (1:1) preview in RT and the corresponding output. Your external photo viewer might not be color managed properly, which can cause visual differences.

Probably not a bug in RT.

**Comment by hyannes** [comment]
I see! Thank you for the fast response and I'll keep this in mind next time. I'm rather new to RawTherapee so I don't exactly know how preview and output works except for the fact I have to edit to get what kind of effect I want

**Comment by Thanatomanic** [comment]
@hyannes Reading this might help too if you're new: http://rawpedia.rawtherapee.com/The_Image_Editor_Tab
