### ISSUE TITLE
Default profiles should have either raw or lensfun ca correction enabled, but not both together

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#5110]
Auto-Matched Curve - ISO Low.pp3 currently has

```
[Exposure]
Auto=false
HistogramMatching=true

[HLRecovery]
Enabled=true
Method=Blend

[LensProfile]
LcMode=lfauto
UseDistortion=true
UseVignette=true
UseCA=true

[Color Management]
ToneCurve=false
ApplyLookTable=true
ApplyBaselineExposureOffset=true
ApplyHueSatMap=true
DCPIlluminant=0

[RAW]
CA=true
```

Having raw CA correction and lensfun CA correction enabled leads to bad CA correction in case the lensfun profile has CA correction. 
Example: left lensfun + raw ca correction, right only raw ca correction
![grafik](https://user-images.githubusercontent.com/13733487/50342906-47eaa680-0525-11e9-9d81-88abb1418f65.png)

**Comment by Beep6581** [comment]
Closing as fixed.
