### ISSUE TITLE
Opening a locked RAW file in RawTherapee causes crash

### ISSUE THREAD

**Issue by teplit** [Beep6581/RawTherapee#5111]
If a RAW file is firstly opened in Adobe Camera Raw, then it is not possible to open it in RawTherapee without closing Camera Raw.

Steps to reproduce the problem without Camera Raw on Windows system:
1. Via RawTherapee File Browser open a folder with a RAW file
2. From Windows command interpreter (cmd.exe) execute `notepad >> RAWfile`, where RAWfile is the path to chosen RAW file located in the same folder
3. Try to open the same RAW file from RawTherapee File Browser

These steps cause RawTherapee 5.5 (commit d9ac23555) to crash.

**Comment by gaaned92** [comment]
Crash confirmed

`If a RAW file is firstly opened in Adobe Camera Raw, then it is not possible to open it in RawTherapee without closing Camera Raw.`
That seems a sane behaviour. Nevertheless, Rawtherapee should not crash.

**Comment by Thanatomanic** [comment]
> That seems a sane behaviour.

That actually does not seem like sane behavior to me. We only need to open the file in read-only mode. I am no expert in how Windows handles file i/o behind the scenes, but I would assume opening in read-only should always be possible.

**Comment by heckflosse** [comment]
This fixes the crash:

```diff
diff --git a/rtengine/rawimagesource.cc b/rtengine/rawimagesource.cc
index 9f8720d1b..4dc966e72 100644
--- a/rtengine/rawimagesource.cc
+++ b/rtengine/rawimagesource.cc
@@ -473,7 +473,7 @@ RawImageSource::~RawImageSource ()
         delete riFrames[i];
     }
 
-    for(size_t i = 0; i < numFrames - 1; ++i) {
+    for(size_t i = 0; i + 1 < numFrames; ++i) {
         delete rawDataBuffer[i];
     }
 
```

**Comment by heckflosse** [comment]
Now the crash is fixed, but I get a warning in console:
```
Gtk-Message: 20:05:07.637: GtkDialog mapped without a transient parent. This is discouraged.
```

Fixed with this patch which includes the first patch:

```diff
diff --git a/rtengine/rawimagesource.cc b/rtengine/rawimagesource.cc
index 9f8720d1b..4dc966e72 100644
--- a/rtengine/rawimagesource.cc
+++ b/rtengine/rawimagesource.cc
@@ -473,7 +473,7 @@ RawImageSource::~RawImageSource ()
         delete riFrames[i];
     }
 
-    for(size_t i = 0; i < numFrames - 1; ++i) {
+    for(size_t i = 0; i + 1 < numFrames; ++i) {
         delete rawDataBuffer[i];
     }
 
diff --git a/rtgui/filepanel.cc b/rtgui/filepanel.cc
index 23b7c3983..aef2b0a22 100644
--- a/rtgui/filepanel.cc
+++ b/rtgui/filepanel.cc
@@ -301,7 +301,7 @@ bool FilePanel::imageLoaded( Thumbnail* thm, ProgressConnector<rtengine::Initial
 #ifdef WIN32
                     else {
                         Glib::ustring msg_ = Glib::ustring("<b>") + M("MAIN_MSG_CANNOTLOAD") + " \"" + thm->getFileName() + "\" .\n" + M("MAIN_MSG_TOOMANYOPENEDITORS") + "</b>";
-                        Gtk::MessageDialog msgd (msg_, true, Gtk::MESSAGE_ERROR, Gtk::BUTTONS_OK, true);
+                        Gtk::MessageDialog msgd (*parent, msg_, true, Gtk::MESSAGE_ERROR, Gtk::BUTTONS_OK, true);
                         msgd.run ();
                         goto MAXGDIHANDLESREACHED;
                     }
@@ -322,7 +322,7 @@ bool FilePanel::imageLoaded( Thumbnail* thm, ProgressConnector<rtengine::Initial
             }
         } else {
             Glib::ustring msg_ = Glib::ustring("<b>") + M("MAIN_MSG_CANNOTLOAD") + " \"" + thm->getFileName() + "\" .\n</b>";
-            Gtk::MessageDialog msgd (msg_, true, Gtk::MESSAGE_ERROR, Gtk::BUTTONS_OK, true);
+            Gtk::MessageDialog msgd (*parent, msg_, true, Gtk::MESSAGE_ERROR, Gtk::BUTTONS_OK, true);
             msgd.run ();
         }
 #ifdef WIN32

```

**Comment by heckflosse** [comment]
@Thanatomanic 
> but I would assume opening in read-only should always be possible.

It seems we open in read-only mode already
https://github.com/Beep6581/RawTherapee/blob/dev/rtengine/myfile.cc#L136

Edit: I just saw that my pointer was for the case MMAP is disabled...

**Comment by gaaned92** [comment]
But we don't know what is doing CR!

**Comment by heckflosse** [comment]
@gaaned92 
> But we don't know what is doing CR!

?

Edit: Did you mean ACR?
