### ISSUE TITLE
Preview sometimes goes magenta at >=100% preview when using Ciecam02 and defringe

### ISSUE THREAD

**Issue by RawConvert** [Beep6581/RawTherapee#5116]
Not really a great xmas present...!
With the linked CR2 and PP3, I find that as I zoom in, all is ok to 100%, but from 200% on, the preview gets a heavy magenta / lilac cast.  Have re-booted and also re-invoked RT but problem persists.  Switching off CIECAM or Defringe returns the preview to normal.

https://filebin.net/i8hj0y6dm0bknwbz

**Comment by RawConvert** [comment]
system details - RT Version: 5.5-12-g39d37a6   Branch: dev    Commit: 39d37a6   Commit date: 2018-12-17
Ubuntu

**Comment by heckflosse** [comment]
@RawConvert 

Seems related to Defringe in combination with Ciecam02

Edit: this was not meant to repeat your finding (which was already very good). But I detected that using a different white balance also fixed the issue but I could rule this out, means it was definitely related to ciecam + defringe

**Comment by heckflosse** [comment]
@RawConvert Thanks for reporting this bug and providing raw and pp3 to reproduce :+1:

**Comment by RawConvert** [comment]
you're welcome

**Comment by heckflosse** [comment]
@RawConvert 
> Not really a great xmas present...!

Getting presents from at least one year ago usually is not great ;-)
Though in this case it's ok, because it's a bug which imho was also already in 5.4 and maybe even before 5.4
