### ISSUE TITLE
Update AppData file

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#5117]
As requested in #5114
- Update `id`
- Add `launchable-type`
- Add `releases`
- Add `provides`

**Comment by scx** [comment]
It would be nice if you could provide **OARS** rating:
https://github.com/flathub/flathub/wiki/AppData-Guidelines#oars-information
https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-content_rating
https://hughsie.github.io/oars

See also: **kudos**
https://github.com/flathub/flathub/wiki/AppData-Guidelines#kudos
https://gitlab.gnome.org/GNOME/gnome-software/blob/master/doc/kudos.md
