### ISSUE TITLE
Leave the old pic showing while computing the next one 

### ISSUE THREAD

**Issue by drenghel** [Beep6581/RawTherapee#5120]
Hi,

first, thanks y'all for this awesome piece of software !
second, I couldn't find my request anywhere, because it's hard to describe.
  
When I'm working a set of pics, more specifically pics taken at the same spot with varying settings, I try to switch between them quickly, to pick the best of them, but as loading a pic is resource intensive and there is a lag time with no picture shown ("amaze demosaicing")...
 So it gets pretty hard to figure out just with the naked eye.

There you go, I tried to be clear !

I'm thinking that it shouldn't be so hard to tweak the code to leave the old image showing while computing the next one.

_(PS, I could maybe do it by myself but I don't know the code base :) )_

**Comment by Beep6581** [comment]
@Andre-Rb 
1. Please don't write everything in bold, that's like shouting. I edited your post to remove the bold.
2. > "but as loading a pic is resource intensive and there is a lag time with no picture shown"
    
    That is not the case. The next image replaces the current image instantly once the next image is done loading, and this is on a 0.9GHz laptop.

Which operating system are you using?
Are you using RawTherapee 5.5?

**Comment by drenghel** [comment]
My bad about the bold thingy, I was trying to separate me blabbering & actual intel.

I just downloaded the latest (5.5) and you're very much right, it does work now !
I was using an older one 5.4, from the community repo of my Manjaro distro.

The package is not on the stable branch yet :( ...

So I guess the case is close :)  
Thanks for your time.
