### ISSUE TITLE
Odd behaviour with Profiled Lens Correction and Vignetting Correction

### ISSUE THREAD

**Issue by RawConvert** [Beep6581/RawTherapee#5121]
There seems to be an anomaly connected to opening a raw for the first time.
1. Open first time (never been opened before).  Set some Vig. amount if zero.  Select Automatic for P.L.C. See in the history it says Vignetting disabled (but it has left the Amount unchanged)

2. Now repeat with same Raw...  First set LCP to None and exit preview to RT browser.  Re-select raw and select Auto PLC.  This time no history entry for Vig.

Questions...  why is behaviour different first time around?...   should the Vig be disabled in any case?...

The camera and lens must be recognised or the above behaviour may not happen.

**Comment by Beep6581** [comment]
@RawConvert please provide the necessary raw file(s), PP3, screenshots, version info, and clearly described steps to reproduce (I am unable to follow your steps):
http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports

**Comment by RawConvert** [comment]
Ok well I thought it was not too bad to follow.  Anyway, trying again today I'm struggling to reproduce it.  After some experimenting, I've found another way to reproduce the same issues.
1. Open a raw where the camera and lens are known to RT i.e. "camera" and "lens" will both get populated when you select Auto for PLC.  (Not sure this is essential but that's what I've been working with)
2. Select Neutral profile and see "(Neutral)+" in the history.  (What does the plus signify pls?)
3. Set Vig. amount to say 20.
4. Select Auto for PLC.
5. See that according to history Vig. has been disabled.  But the amount is still 20.  Issue 1.
6. Now select None for PLC.
7. Now select Auto again.  Note that this time Vig. is not mentioned in history.   Issue 2 - the difference in behaviour.
8. If you want select Neutral and go round again...

files - https://filebin.net/3hnqcls1uwc7wit7

A question please, as I got quite confused looking into this.  Preferences say "Clear all cached files except for processing profiles" in file browser tab.  Suppose you are using pp3 sidecars and have deleted the raw pp3, i.e. xxxx.CR2.pp3 in my case.  And cleared cache.  Is there still info about this photo in the cache?  Or to put it another way, how can you get back to the situation of a brand new raw file?  Is it enough to clear the cache in Prefs and delete the raw pp3?  Or does RT still have some knowledge of the image?

**Comment by RawConvert** [comment]
Ok from rawpedia looks like the cache is not used if you select "save profile next to input" in Prefs.  Is that true as far as you know pls?

**Comment by TooWaBoo** [comment]
@RawConvert 
What's "PLC"?

**Comment by Thanatomanic** [comment]
I think it's an uncommon abbreviation of Profiled Lens Correction

**Comment by Thanatomanic** [comment]
> See that according to history Vig. has been disabled. But the amount is still 20. Issue 1.

@RawConvert For me this step is confusing and not reproducible. What do you see in your history after you have selected Auto the first time? I see this:
![image](https://user-images.githubusercontent.com/6567747/50562314-471af700-0d13-11e9-956b-90f6323c1e82.png)

I see very little reason why setting PLC to Auto would reset your manual vignetting setting actually..

**Comment by TooWaBoo** [comment]
@RawConvert 

![grafik](https://user-images.githubusercontent.com/13800920/50562420-0b346180-0d14-11e9-9e69-bece9712e826.png)
The history only shows (Neutral)+ if `Processing profile fill mode` button is pressed.

I do get the same result like @Thanatomanic.

**Comment by RawConvert** [comment]
Thanks re. neutral plus.
Here's a screen shot where I've set neutral, added some vig., then set auto P.L.C.  You can see the vig. disabled text.  The "disabled" and "automatically" both appear when auto PLC is clicked. I agree there should be very little reason for this, but it is happening!
![vig1](https://user-images.githubusercontent.com/16868433/50564205-0921d100-0d1b-11e9-95f4-317b31c8fbc1.png)

I now continue to go back to no PLC then back to Auto.  The perspective corrections are simply to stop the lens correction history items getting merged together so you can see the whole sequence.
![vig2](https://user-images.githubusercontent.com/16868433/50564248-63bb2d00-0d1b-11e9-8061-40e7f8c2f293.png)

RT is great but I have a feeling that random strange things happen often enough to be a little disturbing.

**Comment by Thanatomanic** [comment]
I see what you mean here and this does not disregard your bugreport, but I think you need to update your lensfun database. On my system your camera+lens combination has vignetting support in lensfun. In yours it does not (because the toggle gets disabled in auto mode).

**Comment by heckflosse** [comment]
Your lens correction profile does not support vignetting correction. That's why it's disabled. It also does not support CA correction, but as CA correction is not enabled, it does not have to be disabled.

All fine here

**Comment by heckflosse** [comment]
@Thanatomanic was faster :)

**Comment by TooWaBoo** [comment]
@RawConvert 
I could reproduce it.
Your Lens Profile has no vignetting information. If you set profile `Neutral` Lensfun vignetting is active. When you click on `Auto`, Lensfun vignetting will be set to disabled 'cause of your profile and this triggers the history message. It has nothing to do with the `Vignetting Correction` tool.

EDIT: @heckflosse: Not only @Thanatomanic :-)

**Comment by heckflosse** [comment]
Well, ticket opened 2 days ago at a saturday between xmas and newyear. 3 contributors took care of the issue and it's solved (explained) now (I think). I would call this good support, not random strange things ;-)

Ok to close?

**Comment by RawConvert** [comment]
It's very good support, like when you quickly fixed the magenta issue the other day!

Before closing, a few thoughts... I know little about lensfun and thought I didn't even have it.  I've never done anything myself to install it.  When I compile, I get a error/warning message usually, here's we are from when I built 5.5 rc1 (don't always log this stuff...) -

...
-- Performing Test _fftw3f_multithread - Failed
-- Performing Test LENSFUN_HAS_LOAD_DIRECTORY
-- Performing Test LENSFUN_HAS_LOAD_DIRECTORY - Failed
...

I was looking for lens profiles to do with this issue and found dcp's in /rawtherappe/dcpprofiles,  e.g. Canon EOS 6D.dcp.  I couldn't find lens profiles, I guess these are all in the 1Mb-or-so dcp file?  Is all this lensfun or stuff from adobe DNG?  Am I actually using lensfun?  (Not that it's a problem if I am)

Anyway maybe the history item saying vig. disabled should be explicit and mention Lensfun, so no one will be confused like I was.  And if I'm not using lensfun, maybe it shouldn't say it at all. Just a thought...

Happy New Year folks!

**Comment by Beep6581** [comment]
> See that according to history Vig. has been disabled. But the amount is still 20. Issue 1.

Those are two completely different tools, and even if they weren't, turning a tool off does not reset its values, so either way all is good.

> Now select Auto again. Note that this time Vig. is not mentioned in history. Issue 2 - the difference in behaviour.

It was disabled once because it's not available in that lensfun profile, as explained by others above. Since it was already disabled once, there is no history entry because nothing has changed.

You can help improve your camera+lens lensfun profile:
https://discuss.pixls.us/t/create-lens-calibration-data-for-lensfun/9848

> I was looking for lens profiles to do with this issue and found dcp's

There are two systems available for correcting optical issues:
1. Lensfun. Lensfun's profiles reside in `/usr/share/lensfun/` and in `/var/lib/lensfun-updates/`
2. Adobe's Lens Correction Profiles (LCP). http://rawpedia.rawtherapee.com/How_to_get_LCP_and_DCP_profiles

DCP files control color and have nothing to do with lensfun: http://rawpedia.rawtherapee.com/How_to_create_DCP_color_profiles#What_Are_DCP_Profiles_and_Why_Do_I_Need_Them.3F

> Anyway maybe the history item saying vig. disabled should be explicit and mention Lensfun

The Lens/Geometry and Chromatic Aberration tools and history entries need a revision, but that's a separate issue - #5132

**Comment by Beep6581** [comment]
http://rawpedia.rawtherapee.com/Lens/Geometry#Profiled_Lens_Correction

**Comment by RawConvert** [comment]
@Beep6581 , thanks for explaining optical correction vs. DCP/colour.

Re. your comment "turning a tool off does not reset its values", note that there is no on/off button for vig, surely the only way to turn it off is to put Amount back to zero.  Which is why I thought the history message was so misleading before lensfun came into the picture.
