### ISSUE TITLE
Processing profile button - rawpedia documentation issue

### ISSUE THREAD

**Issue by RawConvert** [Beep6581/RawTherapee#5124]
Re. this section -  "Partial Processing Profiles and Fill Modes

Processing profiles can be copied, pasted, loaded, saved and applied in full or partially. Clicking the buttons in the Processing Profile Selector handles them in full, while ctrl+clicking those buttons handles them partially - a windows pops up letting you choose which parameters to include."

A window doesn't pop up on a ctrl-click on my Ubuntu system + rt5.5 rc2+dev.
Also the icons in rawpedia don't match the actual ones (for press and release)
Minor point - there's only one button surely? not buttons plural.

**Comment by heckflosse** [comment]
I agree, that a screenshot in rawpedia showing the 4 buttons would be helpful
![grafik](https://user-images.githubusercontent.com/13733487/50573344-75134080-0dd2-11e9-9137-e84cef82cd0c.png)

**Comment by RawConvert** [comment]
Yes, making clear ctrl+click applies to the two rightmost.
I thought it was talking all about the leftmost button that is on its own.  Here rawpedia could include the words pressed and released like in the tool tip, together with updated icons (the bit below the part I quoted).

**Comment by heckflosse** [comment]
@RawConvert 
> making clear ctrl+click applies to the two rightmost.

To the 4 rightmost

**Comment by RawConvert** [comment]
Erm..!  well I'm finding ctrl has no effect on Load And Save (the left 2 of the 4) - ctrl+click and click both give the dialogue window to choose the file.  Whereas ctrl+click on the right 2 really does give a window for selecting the settings to copy or paste.

**Comment by RawConvert** [comment]
Ah, just went one step further and chose a file, now getting the selection window! ok!!

**Comment by Thanatomanic** [comment]
Fixed: http://rawpedia.rawtherapee.com/Editor#Processing_Profile_Selector
and http://rawpedia.rawtherapee.com/Sidecar_Files_-_Processing_Profiles#Partial_Processing_Profiles_and_Fill_Modes
