### ISSUE TITLE
Select + bring into view image passed as argument to RT executable

### ISSUE THREAD

**Issue by PhilBaz** [Beep6581/RawTherapee#5125]
@Please make active image highlighted and focused in the film strip on right click open…

This is currently missing so you have to go searching through.

Also, is EXIF data overlay in film strip now gone? could have sworn it was there previously. Would be nice to have it.

**Comment by Beep6581** [comment]
> make active image highlighted and focused in the film strip on right click open

It is.

> Also, is EXIF data overlay in film strip now gone? could have sworn it was there previously. Would be nice to have it.

Though that has nothing to do with this issue, see http://rawpedia.rawtherapee.com/Keyboard_Shortcuts
"Toggle thumbnail information"

**Comment by PhilBaz** [comment]
Sorry, but when i right-click a raw file and choose open with RT the filmstrip at the top of the editor is not focused on the selected image.

It starts at the beginning of the set. Windows 10.

**Comment by PhilBaz** [comment]
It also is not focused in the file browser...

Sorry, I see how to show labels in the film strip now.

**Comment by Beep6581** [comment]
@PhilBaz your initial post did not explain where you right-clicked from, which OS you use, etc. See http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports

I confirm that when a file is passed as an argument to the RawTherapee executable and the Filmstrip is visible, then the loaded image is neither selected nor in view.

@PhilBaz as a workaround, you can hit the "x" keyboard shortcut to select+bring into view the current image.

**Comment by PhilBaz** [comment]
Okay, thanks. Using x definitely works. Fantastic. From a user perspective, it would be great if this was the default behavior.

Sorry for this whole thing being a pain in the ass. Thank you very much for all your efforts with RT. It is truly a fantastic tool.

**Comment by Beep6581** [comment]
@PhilBaz not need to be sorry, your report was correct, and we are looking into it.

**Comment by Beep6581** [comment]
Fix committed, tested without side-effects in all tab modes (SETM/METM/etc) with existing and non-existing photos.

**Comment by heckflosse** [comment]
@Beep6581 Fix confirmed :+1:
