### ISSUE TITLE
RT 5.5 loosing all history entries between application restarts

### ISSUE THREAD

**Issue by justdanyul** [Beep6581/RawTherapee#5135]
RT Version 5.5
OS: Arch Linux
WM: i3wm

My issue is, when I open RT and make some edits to a photograph, each step shows up as expected in the History. However, after closing RT, and revisiting the same photograph, all the steps in the history is lost.

The pp3 sidecar file still exists, and the steps are certainly being applied to the image, however, I lose the stepwise history which doesn't allow me to go back in time and undo adjustments.

It feels like the pp3 files somehow aren't being reparsed by the history pane.

**Comment by Thanatomanic** [comment]
Simple answer: this is by design. 

@Beep6581 I cannot find an issue that actually describes this feature request. I'm sure it is there...

**Comment by Beep6581** [comment]
@Thanatomanic e.g. #2477 which was handled by #463
