### ISSUE TITLE
Panasonic DC-GX9 white and black levels

### ISSUE THREAD

**Issue by CorentinDeBoisset** [Beep6581/RawTherapee#5137]
Update from #4540 

I reuploaded the pictures. I put them on [your pastebin](https://filebin.net/owgvkcgwworevdi8)

ping @Beep6581

**Comment by Thanatomanic** [comment]
@CorentinDeBoisset This issue has not been taken up since you first posted it, but I am willing to do so if you can reupload your pictures.
