### ISSUE TITLE
Cannon PowerShot SX40HS

### ISSUE THREAD

**Issue by wamslers** [Beep6581/RawTherapee#5140]
Per http://rawpedia.rawtherapee.com/Adding_Support_for_New_Raw_Formats I am attaching a photo set for the Cannon PowerShot SX40HS. I do not believe this camera has LENR, so I am only including the first set. ISO settings only go up to 3200. FYI, am using CHDK to capture RAW.

https://filebin.net/2vxtx03g8j7j6dn4

Thank you!

**Comment by Thanatomanic** [comment]
Hi @wamslers could you reupload your files if possible? I can analyse them.
