### ISSUE TITLE
Attempt to write value larger than 0xFFFFFFFF in 32 bit package (5.5)

### ISSUE THREAD

**Issue by stratocaster7** [Beep6581/RawTherapee#5141]
I'm a packager for mageia linux. We recently attempted to backport version 5.5 to our stable branch. QA has found that 32 bit 5.5 fails to process files that worked with 5.3. 64 bit is ok. The error text is

$ rawtherapee-cli -o p.tif -t -c P7212390.ORF 
RawTherapee, version 5.5, command line.
Output is 16-bit integer.
Processing: P7212390.ORF
TIFFWriteDirectoryTagIfdIfd8Array: Attempt to write value larger than
0xFFFFFFFF in Classic TIFF file..
TIFFWriteDirectoryTagIfdIfd8Array: Attempt to write value larger than
0xFFFFFFFF in Classic TIFF file..
Error saving to: p.tif

Our bug is https://bugs.mageia.org/show_bug.cgi?id=24092

The only other thing that changed in our package aside from the rawtherapee version itself was that I attempted to use O3 as recommended if that matters. I do not have the photo they used but will try to get it if needed.

**Comment by Floessie** [comment]
Confirmed on Debian 9 i386 and Debian unstable PPC.

**Comment by Floessie** [comment]
Bisected:

> There are only 'skip'ped commits left to test.
> The first bad commit could be any of:
> 3dcce23c24d093f7c9719addd99c7b9d5589a827
> 4c3e7b8efac0116e1d9cc16ddf7464f3d257fa6c
> 431d1342028b7a8bfd11679c5db68dafc3c4ef1d
> 524b0056dcead2b69d2861cdf8e9e0ef8c5f362f
> b61a4cdc26d03e7c75f36d698e30becedf1e1438

**Comment by heckflosse** [comment]
@Floessie Can you provide a raw file to reproduce? Then I can test disabling SSE2 in the code from the commits you mentioned

**Comment by Floessie** [comment]
@heckflosse I checked the commits manually by undefing `__SSE2__` in `rtengine.h` plus some consecutive fixes. All commits were good. :unamused: 

Now I'm bisecting on a non-SSE2 VM (I checked that `__SSE2__` isn't defined). Stay tuned...

**Comment by heckflosse** [comment]
@Floessie 
Can you test this fix please?
```diff
diff --git a/rtengine/curves.h b/rtengine/curves.h
index fe93bcde5..bd625ea48 100644
--- a/rtengine/curves.h
+++ b/rtengine/curves.h
@@ -967,7 +967,7 @@ inline void StandardToneCurve::BatchApply(
             break;
 #endif
         }
-        curves::setLutVal(lutToneCurve, r[i], g[i], b[i]);
+        setUnlessOOG(r[i], g[i], b[i], lutToneCurve[r[i]], lutToneCurve[g[i]], lutToneCurve[b[i]]);
         i++;
     }
 
@@ -993,7 +993,7 @@ inline void StandardToneCurve::BatchApply(
 
     // Remainder in non-SSE.
     for (; i < end; ++i) {
-        curves::setLutVal(lutToneCurve, r[i], g[i], b[i]);
+        setUnlessOOG(r[i], g[i], b[i], lutToneCurve[r[i]], lutToneCurve[g[i]], lutToneCurve[b[i]]);
     }
 #endif
 }

```
I don't know whether it fixes this issue. But it was definitely wrong here for non SSE builds.

**Comment by Floessie** [comment]
@heckflosse Your patch doesn't solve this issue. Good catch though. :+1:

**Comment by Floessie** [comment]
With intermediate fixes (`git stash` to the rescue) I was able to nail it down to 96863bb95648575f8528dfa75bbf232c9c4deb40.

**Comment by Floessie** [comment]
Ping @Hombre57.

I tried several things to no avail and suspect the move of the EXIF writing code higher up has an influence here.

**Comment by Hombre57** [comment]
@stratocaster7 Could you provide the raw file please ( -> filebin.net ) ?

**Comment by stratocaster7** [comment]
Yes, I will try to get it from our QA folks.

**Comment by Floessie** [comment]
@Hombre57 `amsterdam.pef` will do...

**Comment by stratocaster7** [comment]
https://drive.google.com/drive/folders/1OlmTW3i4qbk_KB_-9d5Z-lwIdU1VDxFz

Please let us know when you have them so we can take it down.

**Comment by Hombre57** [comment]
@stratocaster7 Done, thanks.

I'm trying to build a 32 bits version and see if it happen on windows system too.

**Comment by gaaned92** [comment]
RT 32bits last dev on W10 , no crash, no message in verbose mode. OK

**Comment by Floessie** [comment]
Problem still present on i386 Debian 10.

**Comment by 10110111** [comment]
I've found that it's because `TIFFTAG_EXIFIFD` has type `IFD8` in libtiff 4.0.0 and higher (see [this discussion](https://feedback.photoshop.com/conversations/default_topic/tifftag_exififd34665-tag-data-type-in-latest-photoshop-software-and-the-version-of-libtiff-library/5f5f459a4b561a3d4255f4e2)), and this type is 64-bit, unlike previous versions where it was `long`, which is 32-bit.

The result is that [this line](https://github.com/Beep6581/RawTherapee/blob/d7f9e1f51c740e625485155e9ecb17b1ffa15acf/rtengine/imageio.cc#L1413) that reads
```
TIFFSetField (out, TIFFTAG_EXIFIFD, 8);
```
writes `int(8)` into a va-list, which gets read as `uint64_t`, yielding garbage in the upper dword. The result is something like `0x7fffabcd00000008` instead of `0x8`, which indeed is larger than `0xFFFFFFFF`.

Changing the above mentioned line to
```
TIFFSetField (out, TIFFTAG_EXIFIFD, uint64_t(8));
```
fixes the problem for me.

**Comment by Floessie** [comment]
@10110111 Ruslan, thanks a lot for your investigations. Would you mind filing a PR with either `static_cast<std::uint64_t>(8)` or `8ULL`?

Good job! :+1: 

Best,
Flössie

**Comment by 10110111** [comment]
> either `static_cast<std::uint64_t>(8)` or `8ULL`

I guess there should be a middle-ground option, `UINT64_C(8)` :) . Static-casting a literal looks quite strange, and this one will be equivalent to the suffixed version, still being explicit about fixed 64-bit size. If you don't mind, I'll submit this one in a PR.

**Comment by Floessie** [comment]
@10110111 @Thanatomanic I can confirm the fix on Debian 11 i386.

@stratocaster7 Could you report back on the Mageia Bugzilla?

Best,
Flössie

**Comment by stratocaster7** [comment]
QA has approved the patched package so it appears the fix is good for us too. Thanks.

https://bugs.mageia.org/show_bug.cgi?id=29295

**Comment by barracuda156** [comment]
> I've found that it's because `TIFFTAG_EXIFIFD` has type `IFD8` in libtiff 4.0.0 and higher (see [this discussion](https://feedback.photoshop.com/conversations/default_topic/tifftag_exififd34665-tag-data-type-in-latest-photoshop-software-and-the-version-of-libtiff-library/5f5f459a4b561a3d4255f4e2)), and this type is 64-bit, unlike previous versions where it was `long`, which is 32-bit.
> 
> The result is that [this line](https://github.com/Beep6581/RawTherapee/blob/d7f9e1f51c740e625485155e9ecb17b1ffa15acf/rtengine/imageio.cc#L1413) that reads
> 
> ```
> TIFFSetField (out, TIFFTAG_EXIFIFD, 8);
> ```
> 
> writes `int(8)` into a va-list, which gets read as `uint64_t`, yielding garbage in the upper dword. The result is something like `0x7fffabcd00000008` instead of `0x8`, which indeed is larger than `0xFFFFFFFF`.
> 
> Changing the above mentioned line to
> 
> ```
> TIFFSetField (out, TIFFTAG_EXIFIFD, uint64_t(8));
> ```
> 
> fixes the problem for me.

@10110111 Just in case, maybe you have an idea how to address this one? https://github.com/Beep6581/RawTherapee/issues/7052
