### ISSUE TITLE
softproof not working when no printer profile is set (no sRGB preview on wide gamut screens)

### ISSUE THREAD

**Issue by blitzgneisserin** [Beep6581/RawTherapee#5143]
RT Version: 5.5; Branch: releases; Commit: d9ac23555; Commit date: 2018-12-17
system: Manjaro Linux Cinnamon 18.0; Acer V-3-372 laptop; BenQ SW240 (wide gamut) monitor
![bildschirmfoto vom 2019-01-16 11-08-30](https://user-images.githubusercontent.com/16564210/51238399-24294d80-1977-11e9-84e6-b19e5ef1f491.png)
To see/reproduce the issue, you need a wide gamut screen and a photo which contains colors that are outside of sRGB (or an output profile that has a smaller or different gamut than the screen that you are using).
Printer profile is not set; output profile is sRGB (e.g. RTv2_sRGB); this way, you should see how the photo would look on an sRGB screen, when you press the softproof button, i.e., if you have a photo with colors outside of sRGB, the photo should look less saturated. However, this is not the case, the preview does not change.
You can check this with any photo that contains out-of-gamut colors, here is an example:
https://c2.staticflickr.com/8/7907/46031491074_b0f095333a_k.jpg
Please let me know if you need more info.

**Comment by agriggio** [comment]
Confirmed. The problem is again the use of profiles with parametric TRCs, that make LCMS work in "unbounded" mode. Something similar was happening also for the out of gamut check.

Here is a proposed "hack" to force LCMS to clip, which is needed for softproofing:

```diff
diff --git a/rtengine/improcfun.cc b/rtengine/improcfun.cc
--- a/rtengine/improcfun.cc
+++ b/rtengine/improcfun.cc
@@ -338,14 +338,39 @@
                 //     flags |= cmsFLAGS_GAMUTCHECK;
                 // }
 
+                const auto make_gamma_table =
+                    [](cmsHPROFILE prof, cmsTagSignature tag) -> void
+                    {
+                        cmsToneCurve *tc = static_cast<cmsToneCurve *>(cmsReadTag(prof, tag));
+                        if (tc) {
+                            const cmsUInt16Number *table = cmsGetToneCurveEstimatedTable(tc);
+                            cmsToneCurve *tc16 = cmsBuildTabulatedToneCurve16(nullptr, cmsGetToneCurveEstimatedTableEntries(tc), table);
+                            if (tc16) {
+                                cmsWriteTag(prof, tag, tc16);
+                                cmsFreeToneCurve(tc16);
+                            }
+                        }
+                    };
+
+                cmsHPROFILE softproof = ProfileContent(oprof).toProfile();
+                if (softproof) {
+                    make_gamma_table(softproof, cmsSigRedTRCTag);
+                    make_gamma_table(softproof, cmsSigGreenTRCTag);
+                    make_gamma_table(softproof, cmsSigBlueTRCTag);
+                }
+
                 monitorTransform = cmsCreateProofingTransform (
                                        iprof, TYPE_Lab_FLT,
                                        monitor, TYPE_RGB_FLT,
-                                       oprof,
+                                       softproof, //oprof,
                                        monitorIntent, outIntent,
                                        flags
                                    );
 
+                if (softproof) {
+                    cmsCloseProfile(softproof);
+                }
+
                 if (monitorTransform) {
                     softProofCreated = true;
                 }
```

In order to test this on a normal screen with a gamut close to sRGB, I have created a couple of artificial "tiny" profiles, that should have a gamut significantly smaller than sRGB. You can find them here:
https://filebin.net/f9bpjgihr0y3jvng

Without the patch applied, using the image linked above, you should see no difference in the output when softproofing is enabled. With the patch applied, differences should be visible (assuming your screen is reasonably close to sRGB, at least).

Ping @Desmis

**Comment by gaaned92** [comment]
It work now
https://keybase.pub/gaaned92/RTW64NightlyBuilds/RawTherapee_dev_5.5-70-softproof_WinVista_64_190116.zip
