### ISSUE TITLE
Difficulties for me to merge dev in newlocallab due to change in idle_register

### ISSUE THREAD

**Issue by Desmis** [Beep6581/RawTherapee#5151]
I tried to merge "dev" in "newlocallab"

All is OK except when I compile!
2 messages for "idle_register". I solved the first easily (in locallab.cc), I just copy as in another function  

But for the second, @pandagrapher has done a modification in "toolpanelcoord.cc" ==> line 468

    // Locallab spot curves are set visible if at least one photo has been loaded (to avoid
    // segfault) and locallab panel is active
    // When a new photo is loaded, Locallab spot curves need to be set visible again
    const auto func = [](gpointer data) -> gboolean {
        ToolPanelCoordinator* const self = static_cast<ToolPanelCoordinator*>(data);

        if (self->photoLoadedOnce && (self->toolPanelNotebook->get_nth_page(self->toolPanelNotebook->get_current_page()) == self->locallabPanelSW))
        {
            self->locallab->subscribe();
        }

        return FALSE;
    };

    if (event == rtengine::EvPhotoLoaded) {
        idle_register.add(func, this);
    }

    photoLoadedOnce = true;

I don't know how to do ?

Thank you, for help.
Jacques

**Comment by Floessie** [comment]
Salut Jacques,

untested:

```c++
const auto func =
    [this]() -> bool
    {
        if (photoLoadedOnce && (toolPanelNotebook->get_nth_page(toolPanelNotebook->get_current_page()) == locallabPanelSW)) {
            locallab->subscribe();
        }

        return false;
    };

if (event == rtengine::EvPhotoLoaded) {
    idle_register.add(func);
}
```

HTH,
Flössie

**Comment by Desmis** [comment]
@Floessie 

Thank you very much
I will try tomorrow 

jacques

**Comment by Desmis** [comment]
@Floessie 
Good code, thank you, merge done
jacques

**Comment by Floessie** [comment]
@Desmis Super! Closing.
