### ISSUE TITLE
RawTherapee 5 significantly changes color balance for Canon EOS 1300D

### ISSUE THREAD

**Issue by micheal65536** [Beep6581/RawTherapee#5154]
Having updated RawTherapee from 4.2 to 5.5 I found that my existing raw files and processing profiles gave significantly different results and that the default appearance of raw files loaded into RawTherapee for editing is significantly different to what it was previously. While minor changes to results can be expected between versions, this is a significant change that causes disruption to my workflow.

In particular, images seem to have more of a "red" color tint, compared to the "blue/green" color tint that they had previously (assuming no color corrections/adjustments have been applied). I traced the origin of this change to commit f490c6468221913e72626def9d9e09178c42a06b between versions 4.2 and 5.0, which introduced camera data specifically for the Canon EOS 1300D camera that I am using.

As this change is disruptive to me, I would appreciate it if someone with more knowledge of the RawTherapee internals could let me know what this camera data does in particular, what camera data would have been used previously before the data for this camera was added, and how I could use the same data as before in current RawTherapee versions.

**Comment by Beep6581** [comment]
That commit, and several others, do [this](http://rawpedia.rawtherapee.com/How_to_create_DCP_color_profiles) and [this](http://rawpedia.rawtherapee.com/Adding_Support_for_New_Raw_Formats). To go back to incorrect colors, delete the entry from `camconst.json` and delete the input profile. The end result might still differ as many things changed since 4.2 in 2014.

**Comment by micheal65536** [comment]
Yes I am aware that the commits are adding support for the camera and that what I am wanting is technically "incorrect" colors.

However manually editing/deleting the files installed with RawTherapee is inconvenient as this will break with package upgrades. What I would like to know is what "profile" RawTherapee will use by default when the camconst entry and camera-specific input profile are missing and how I can recreate this using either the user-provided camconst file in the config directory or a user-provided input profile file.

**Comment by Thanatomanic** [comment]
Without entries in `camconst.json` RT usually relies on the matrices provided in this file https://github.com/Beep6581/RawTherapee/blob/dev/rtengine/dcraw.cc. Beware, it's not entirely trivial to distill all the right values from that file.

Edit: upon closer inspection, it only seems the white levels have changed. The color matrix ought to be the same before and after the addition of the 1300D to `camconst.json`. Slightly wild guess here, but changing the white levels retro-actively and achieving your old look, might simply be achieved by playing with the Raw White Points slider in the Raw editor tab.

@micheal65536 If you could provide us with a raw sample + pp3 + desired output jpeg that you have been using in v 4.2 I could check for you if this works.

**Comment by micheal65536** [comment]
I had already looked at the `dcraw.cc` file and found the tables/matrices. However that file did not contain data for the 1300D either at the time that 4.2 was released. Therefore, some other "default" values must have been used.

I will see if I can find a sample that I am able to provide here, otherwise I will need to produce one which might take a while.

**Comment by micheal65536** [comment]
Raw photo: https://drive.google.com/file/d/1NC5D4rnl0_23Dd8bLU_g79jcTbpiZfGV/view?usp=sharing

Processed photo: https://drive.google.com/file/d/1atCPEtfduX7W_QunTnvlJLwLBwS29nOu/view?usp=sharing

Processing profile: https://drive.google.com/file/d/1d8ssU5AUlLMi42v1FBqAWxPKvxGgNF4G/view?usp=sharing
