### ISSUE TITLE
Sharpen mask enabled even with contrast threshold set to 0 - Bug

### ISSUE THREAD

**Issue by age1988** [Beep6581/RawTherapee#5155]
It looks like there's always some masking when sharpening, there's should be a white mask when setting contrast threshold to 0 
[https://i.imgur.com/X5HgG1n.jpg](https://i.imgur.com/X5HgG1n.jpg)

**Comment by heckflosse** [comment]
@age1988 
> there's should be a white mask when setting contrast threshold to 0

The visualization of the mask is not completely white by design. Even at threshold 0 the image shines through the mask a bit. That's intended.

**Comment by Thanatomanic** [comment]
@heckflosse I'm not sure if it is necessary to have a slight opacity on the mask. What is the rationale behind it?
I would agree with @age1988 here that I would also expect a fully white mask when the threshold is zero.

**Comment by heckflosse** [comment]
@Thanatomanic 
> I'm not sure if it is necessary to have a slight opacity on the mask.

It's not really an opacity. It's simply the result of not changing Lab ab values because I prefer this:
![grafik](https://user-images.githubusercontent.com/13733487/52048479-c89cb980-254b-11e9-87d1-18bb02e6636a.png)

over this:
![grafik](https://user-images.githubusercontent.com/13733487/52048530-e79b4b80-254b-11e9-8fcd-ba7547c6fcda.png)

**Comment by Beep6581** [comment]
I like the mask the way it is, with the color shining through. I can pan around the image and still see features. Even with the colors shining through clearly everything's masked and it's really impossible to confuse the two states:

Threshold 0:
![screenshot_20190203_214018](https://user-images.githubusercontent.com/5844619/52182329-57376200-27fc-11e9-8b67-21b214e733a5.png)

Threshold 1:
![screenshot_20190203_214025](https://user-images.githubusercontent.com/5844619/52182332-5acae900-27fc-11e9-8a10-7fb096ec5e07.png)

**Comment by heckflosse** [comment]
@age1988 It's a bit about the expectation to have a monochrome mask, But I decided against this expectation because I think colours shining throuugh the mask gives additonal feedback when panning...

Edit: In conclusion: I would that call a feature, not a bug ;-)
