### ISSUE TITLE
Flat-field correction: Option for color cast correction only

### ISSUE THREAD

**Issue by Bezierr** [Beep6581/RawTherapee#5158]
This is an enhancement request, not a bug report.

In Lightroom, when using flat-field correction, you can specify whether to only correct color cast, or to correct both color cast and fall-off. It would be a great enhancement to RawTherapee's flat-field correction if you could make the same choice (e.g. using a simple check box) instead of always having both color cast and fall-off corrected.

Best regards,
Bezier

**Comment by Thanatomanic** [comment]
See #4196. I think this request is better formulated, but in essence is the same.

**Comment by Bezierr** [comment]
It is indeed, and my motivation is exactly the same. Sorry, #4196 did not show up in the "related issues" so I was not aware of its existence.

Best regards,
Bezier

**Comment by Beep6581** [comment]
Closing as duplicate of #4196
