### ISSUE TITLE
Switch in GTK+ 3.24.4 crashes on most fonts (Windows)

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#5160]
This issue is related to the On/Off switch in the queue which only accepts some fonts e.g. like `Segoe Normal` but crashes with e.g. `Arial Normal`.

To fix it I suggest to replace the switch with a toggle button. Works fine with all fonts.

For testing you can download the changed files from here: https://filebin.net/u1nkm9t03li8e6p5

![t1](https://user-images.githubusercontent.com/13800920/52162272-7f767200-26d1-11e9-8a8e-bf59aad668fe.png)
![t2](https://user-images.githubusercontent.com/13800920/52162274-8309f900-26d1-11e9-8d05-55b73f367ddd.png)
![r1](https://user-images.githubusercontent.com/13800920/52162275-856c5300-26d1-11e9-907d-b265c95a0b14.png)
![r2](https://user-images.githubusercontent.com/13800920/52162276-87361680-26d1-11e9-8fa5-703dcc9d25ab.png)

**Comment by TooWaBoo** [comment]
I've found these interesting article on the web.
https://blog.gtk.org/2019/01/14/theme-changes-in-gtk-3/

https://www.linuxuprising.com/2019/01/gtk-developers-are-testing-updated.html

**Comment by Beep6581** [comment]
I don't mind the change, looks nice, but I find it hard to believe such a bug would have gone unnoticed by GTK+ devs and testers, so I wonder, have you verified that the crash happens in stock GTK+ and isn't a result of hacks and workarounds in RT? You can use [Glade](https://glade.gnome.org/) to easily find out.

Can you provide a debug backtrace?

**Comment by TooWaBoo** [comment]
The bug is not theme related. I have run RT without any theme, Rt theme and TWB theme.
I've installed glade but I've no clue what I should do. 🤔
How do I do debug backtrace on windows?

**Comment by Beep6581** [comment]
With Glade you can easily design a form and a switch and test whether it runs or crashes, though I don't recall how to set the font (I don't have it installed, I just formatted my laptop).

As for GDB on Windows, RawPedia should have that covered: http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports#Step_by_step

**Comment by TooWaBoo** [comment]
Here comes the backtrace: [backtrace.txt](https://github.com/Beep6581/RawTherapee/files/2824812/backtrace.txt)
Font: Arial
RT crashes immediately without showing any window.

**Comment by TooWaBoo** [comment]
`mingw-w64-x86_64-gtk3-3.24.5-1` is out and the font bug is solved.
Closing issue.
