### ISSUE TITLE
Segfault in lmmse demosaic

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#5161]
There's a really hard to reproduce segfault in lmmse demosaic.
Searching.....

**Comment by Hombre57** [comment]
@heckflosse 

http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports

(sorry, couldn't resist :smile: )

**Comment by heckflosse** [comment]
@Hombre57 If I would be able to reproduce it always, I would have written a better bug report. :smile: 

Currently I nailed it down to NaN values produced by lmmse. Still searching

**Comment by heckflosse** [comment]
Status report: 

1) I can reproduce the segfault especially with large files but only in Release builds.
2) When lmmse demosaicing a large file (>= 36 MP) 70 times in a row I get at crash (sometimes on first processing, somtimes on last processing)
3) Changing lmmse working space from [0.f;1.f] range to [0.f;65535.f] range it's absolutely stable

**Comment by heckflosse** [comment]
Good news:

After upgrading gcc I can't reproduce the issue anymore.
Works fine using
```
$ gcc --version
gcc.exe (Rev1, Built by MSYS2 project) 8.2.1 20181214
```
