### ISSUE TITLE
Compiler warning, "slopetag" not initialized

### ISSUE THREAD

**Issue by RawConvert** [Beep6581/RawTherapee#5162]
I built RT dev today,
Version: 5.5-97-gb0b0e13,   Branch: dev,   Commit: b0b0e13,   Commit date: 2019-01-31
and the "make" gives this output -
...
[ 83%] Building CXX object rtgui/CMakeFiles/rth.dir/rawcacorrection.cc.o
[ 84%] Building CXX object rtgui/CMakeFiles/rth.dir/rawexposure.cc.o
[ 84%] Building CXX object rtgui/CMakeFiles/rth.dir/recentbrowser.cc.o
/home/paulssd2/RTdev3feb/code-rawtherapee/rtengine/iccstore.cc: In member function ‘toProfile’:
/usr/include/c++/5/ostream:221:29: warning: ‘slopetag’ may be used uninitialized in this function [-Wmaybe-uninitialized]
       { return _M_insert(__f); }
                             ^
/home/paulssd2/RTdev3feb/code-rawtherapee/rtengine/iccstore.cc:351:30: note: ‘slopetag’ was declared here
             double gammatag, slopetag;
                              ^
[ 84%] Built target rth-cli
[ 84%] Building CXX object rtgui/CMakeFiles/rth.dir/renamedlg.cc.o
[ 85%] Building CXX object rtgui/CMakeFiles/rth.dir/resize.cc.o_
...

Even if not a bug it would be nice to have it compile clean.

Also when I run this new version (in a command window) I get these 2 lines before I do anything in RT -
no mmap
no mmap

Ubuntu 16.04
Best wishes to all developers.

**Comment by heckflosse** [comment]
I dont get this warning using gcc 8.2.1

**Comment by Beep6581** [comment]
No such warning with GCC 7.3.0.

**Comment by RawConvert** [comment]
Mine looks old, 
$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
though sudo apt update doesn't mention it.

What is "mmap" pls?

**Comment by heckflosse** [comment]
@RawConvert 
Can you build and run rt with this patch applied please? It will spit out the filenames where the mmap failed.

```diff
diff --git a/rtengine/myfile.cc b/rtengine/myfile.cc
index 920421188..0b6edd8b9 100644
--- a/rtengine/myfile.cc
+++ b/rtengine/myfile.cc
@@ -107,7 +107,7 @@ IMFILE* fopen (const char* fname)
     void* data = mmap(nullptr, stat_buffer.st_size, PROT_READ, MAP_PRIVATE, fd, 0);
 
     if ( data == MAP_FAILED ) {
-        printf("no mmap\n");
+        printf("no mmap %s\n",fname);
         close(fd);
         return nullptr;
     }

```

**Comment by RawConvert** [comment]
Lol!  I haven't been into code for many years!  Can you give me some more detailed instructions, like where to put this piece of code etc...

**Comment by heckflosse** [comment]
@RawConvert Oh, I thought you built RT from source as you used the latest version...

I will just push this change to dev because it makes sense to get the filename shown in console in case mmap failed. Then you'll have that in next appimage or whatever you use.

In case you build from source, just copy the patch to a file named 'xyz.patch' in your rawtherapee clone folder and `git apply xyz.patch`. Then build

**Comment by RawConvert** [comment]
I do indeed build from source but just follow the recipe in rawpedia, so I don't need to understand much to do that!  Agree I guess, make the change.
I might have a go with the patch.  Would the sequence of the main commands then be -
git clone https://github.com/Beep6581/RawTherapee ~/folder/code-rawtherapee
git checkout dev
git apply xyz.patch
cmake \ etc....
make
...

By the way it's fails rather than failes :)

**Comment by heckflosse** [comment]
@RawConvert 

I just pushed to dev. Just build latest dev code ;-)

**Comment by RawConvert** [comment]
Ok, though out of interest, did I have the correct sequence?

**Comment by heckflosse** [comment]
@RawConvert 

cd into your rawtherapee-code folder
git apply xyz.patch
cd into your build folder
make

**Comment by Beep6581** [comment]
@RawConvert since you use Linux, I will add a little shortcut to what @heckflosse wrote to avoid having to save the patch to disk. You can just copy the patch (selecting all lines in the web browser will do, since X copies selected text to the [CLIPBOARD](https://en.wikipedia.org/wiki/Clipboard_(computing)#X_Window_System) clipboard), then:
```bash
cd ~/programs/code-rawtherapee
git apply < <(xclip -o)
~/scripts/build-rawtherapee -b
```

**Comment by RawConvert** [comment]
I've re-built dev, Version: 5.5-98-g9210a56,  Branch: dev,  Commit: 9210a56,  Commit date: 2019-02-04
and the two mmap messages are not being produced.  ?

I also tried the patch but that failed - 
cd ~/RTdev4feb/code-rawtherapee
git apply xyz.patch
error: patch failed: rtengine/myfile.cc:107
error: rtengine/myfile.cc: patch does not apply

But then I thought because the patch has been coded in already, maybe that's why it didn't apply.
@Beep6581 thanks for your method but I wanted to do simple commands that I have a chance of understanding whereas your method is too clever for me!

Anyway the msgs have gone, which presumably is not what was expected.

**Comment by heckflosse** [comment]
@RawConvert 
> But then I thought because the patch has been coded in already, maybe that's why it didn't apply.

Exactly.

> Anyway the msgs have gone, which presumably is not what was expected.

Too bad. I thought we could nail this issue with the patch (which does not more than showing the names of the files) :frowning:

**Comment by heckflosse** [comment]
@RawConvert Thanks for testing. Really appreciated :+1:
