### ISSUE TITLE
No "Start Process" button in raw to jpeg window.

### ISSUE THREAD

**Issue by mackydread** [Beep6581/RawTherapee#5163]
RawTherapee 5.5. Trying to process raw file into jpeg. There is no "Start processing" button to press to begin action. Watched a video of same action, & there was a "Start process" button in the video. Running MacOS Mojave.
![image](https://user-images.githubusercontent.com/47331994/52228509-74c30500-28aa-11e9-91af-8c270319f33e.png)

**Comment by Thanatomanic** [comment]
@mackydread You should turn the Queue ON

**Comment by mackydread** [comment]
Thats just it. I pressed that button as it looked off, then everything disappears.Now it seems frozen and nothing happens
![image](https://user-images.githubusercontent.com/47331994/52229364-a3da7600-28ac-11e9-939c-50b5444526f8.png)

**Comment by Thanatomanic** [comment]
You seem to miss the obvious answer here: if you pressed the button and stuff disappears, your export was succesful. Please check your output directory and see the JPEG there.

**Comment by Beep6581** [comment]
:man_facepalming:

**Comment by mackydread** [comment]
It is not there. Used lightroom for years & only reason I tried this is because Lightroom does not currently have an update for my new nikon camera raw file.Window does not have a start button in raw-jpeg mac os, if on button is clicked whole thing goes off & file disappears, no saved file in destination folder. Just tried it inNikon Capture NX-D and it worked fine. But Nikon NX-D does not have a "contact sheet" facility on it otherwise I'd use that.

**Comment by Thanatomanic** [comment]
Let's backtrack a little. In your post you say

> There is no "Start processing" button to press to begin action. Watched a video of same action, & there was a "Start process" button in the video.

What video was this? Maybe there was a "Start process" button in an ancient version of RT, but recently it is the Queue switch.

Could you do two things:

1. Try to export directly to your home folder or desktop, instead of the folder "Raw therappee test"
2. Use your OS search function to look for a file named DSC_1313.jpg

**Comment by mackydread** [comment]
Here is the link to the video & you'll see what I mean, although I've just noticed video is three years old. Look at it from 8.30secs into video 
https://youtu.be/sOogn08CWeQ 
I'll also try what you suggested.

**Comment by heckflosse** [comment]
@mackydread 

Please try saving to templated folder
![grafik](https://user-images.githubusercontent.com/13733487/52234530-2faacd00-28c2-11e9-8c99-8bbea47ec418.png)

Also, was the folder you had opened in rt file browser the `Raw therappee test` folder?
I ask because this should not happen.:
![grafik](https://user-images.githubusercontent.com/13733487/52234717-992adb80-28c2-11e9-8aca-6098cb997908.png)

It should be `(a number >= 0)`

**Comment by mackydread** [comment]
Original RAW file is from external hard drive, I should be able to open, edit, and export and save as a jpg anywhere I like. To be honest Im giving up & deleting this program as its clear to me that its not going to do what I want. I'm not ignorant on how to use programs as an avid photoshop/lightroom/Indesign/iLLustrator user. I/m just going to download capture Pro which I know will work. Thanks for your help anyway.

**Comment by heckflosse** [comment]
Yeah, that's exactly the kind of feedback we need in case of issues :frowning_face:

**Comment by mackydread** [comment]
It doesn't work the way i want or expect it to.What do you want me to say? It freezes, takes a long time to do anything, even your colleague pointed out a couple of things that are not right from the jpg. I have enough ram, hard drive room, etc. Every program runs great on it including the program Ive just downloaded to replace this one. Sorry but that's just how it is.

**Comment by heckflosse** [comment]
@mackydread 
> It doesn't work the way i want or expect it to

That may be caused by a bug in RT. To solve this bug we need feedback.

For example I asked you to try to save to a different location, but you didn't try at all. If saving to a different location works, that would possibly give us some feedback to nail the  bug...
