### ISSUE TITLE
Preview goes black if you change tone mapping compression strength

### ISSUE THREAD

**Issue by RawConvert** [Beep6581/RawTherapee#5164]
https://filebin.net/g6dg6qs2fnrvwbu8
With current Dev RT built yesterday, the preview window goes black if you make any change away from zero.  The control in question is Compression Strength using Tone Mapping method in the Residual Image section of Wavelet Levels.  I haven't tried it on other raws.  Please delete any copies of my raw once you've investigated.

**Comment by heckflosse** [comment]
The other control in question is `Local contrast`. Disabling Local contrast also gets rid of the issue

**Comment by gaaned92** [comment]
W10, last dev

CIECAM2 enabled, 5 wavelet levels :  preview goes black using compression strength
CIECAM2 enabled, 6 wavelet levels : preview ok
CIECAM2 disabled, 5 wavelet levels: crash
CIECAM2 disabled, 6 wavelet levels : preview ok

I can reproduce black preview on other photo but not the crash.

**Comment by heckflosse** [comment]
This should fix it:

```diff
diff --git a/rtengine/EdgePreservingDecomposition.cc b/rtengine/EdgePreservingDecomposition.cc
index f71e0043e..17f12a699 100644
--- a/rtengine/EdgePreservingDecomposition.cc
+++ b/rtengine/EdgePreservingDecomposition.cc
@@ -892,12 +892,12 @@ void EdgePreservingDecomposition::CompressDynamicRange(float *Source, float Scal
 #endif
 
         for(int ii = 0; ii < n - 3; ii += 4) {
-            _mm_storeu_ps( &Source[ii], xlogf(LVFU(Source[ii]) + epsv));
+            _mm_storeu_ps( &Source[ii], xlogf(vmaxf(LVFU(Source[ii]), ZEROV) + epsv));
         }
     }
 
     for(int ii = n - (n % 4); ii < n; ii++) {
-        Source[ii] = xlogf(Source[ii] + eps);
+        Source[ii] = xlogf(std::max(Source[ii], 0.f) + eps);
     }
 
 #else
@@ -906,7 +906,7 @@ void EdgePreservingDecomposition::CompressDynamicRange(float *Source, float Scal
 #endif
 
     for(int ii = 0; ii < n; ii++) {
-        Source[ii] = xlogf(Source[ii] + eps);
+        Source[ii] = xlogf(std::max(Source[ii], 0.f) + eps);
     }
 
 #endif

```
