### ISSUE TITLE
Consider dropping libiptcdata

### ISSUE THREAD

**Issue by mattiaverga** [Beep6581/RawTherapee#5165]
The latest release of libIPTCdata is 10 years old and it seems there has been no development since. In Linux Fedora there is the willingness of retiring it from the distribution, but the only package which requires it is RT.
I want to ask if you would consider to drop the libIPTCdata requirement in favour of Exiv2 (I just don't know if there are big differences which could make this impossible, it seems to me that other softwares just rely only on Exiv2).

**Comment by Thanatomanic** [comment]
Please see #3801. It's on the list...

**Comment by Beep6581** [comment]
Closing as duplicate.
