### ISSUE TITLE
Unknown lens LUMIX G VARIO 12-35mm F2.8II

### ISSUE THREAD

**Issue by DefteZ** [Beep6581/RawTherapee#5166]
New lens LUMIX G VARIO 12-35mm mark is not recognized by RawTherapee
Can you please add support of this.

Old version of this lens described in rtexif/olympusattribs.cc:
`line 179:  lenses["02 15 10"] = "Lumix G X Vario 12-35mm f/2.8 Asph. Power OIS";`

New version id is "LUMIX G VARIO 12-35mm F2.8II"

> exiftool -Lens -LensID '/home/user/test.RW2'
> Lens ID                         : LUMIX G VARIO 12-35mm F2.8II

Tested on version: 5.5-1 (Linux, Fedora)

**Comment by Beep6581** [comment]
Thanks for reporting, but we don't add support for individual lenses - we use whatever the latest version of ExifTool supports before making a new release. I'll update the lens 'database' now, you can try compiling the `dev` branch tomorrow.

**Comment by DefteZ** [comment]
I have sent a patch to Lensfun project https://sourceforge.net/p/lensfun/code/merge-requests/4/
I guess that it should helps

**Comment by Beep6581** [comment]
@DefteZ great.

I just updated `dev` using exiftool-11.26. I'll update again before we release 5.6 in March.
