### ISSUE TITLE
Softer unsharp mask with radius >= 1 

### ISSUE THREAD

**Issue by age1988** [Beep6581/RawTherapee#5168]
After some tests with Rawtherapee and other raw editor I think that the unsharp mask in Rawtherapee is a little more aggressive compared to the one in darktable or g'mic.
It's pratically perfect when the radius is < 1 but a little harsh otherwise.
It would be great to "match" the darktable's UM when the radius is bigger or the same of 1.

**Comment by heckflosse** [comment]
Can you please post examples (screenshots...)? I have no experience with the USM in DT

**Comment by age1988** [comment]
Same radius (1.6), amount and 0 threshold:
[https://filebin.net/ya5e4ghoxfb4dph9](https://filebin.net/ya5e4ghoxfb4dph9)
The dt versions (or the g'mic unsharp mask in the L channel)  look less sharpened but overall cleaner compared to Rawtherapee

**Comment by gaaned92** [comment]
@age1988 
Are you sure your images are different because I can see no difference ( grain extract in GIMP)?

**Comment by age1988** [comment]
Yes I see it :-)
For small difference I use the custom mode blend layer in g'mic and this formula
`if(a==b,1,0)`
[https://filebin.net/dwg45xhy7rcc0zhp](https://filebin.net/dwg45xhy7rcc0zhp)

**Comment by heckflosse** [comment]
@age1988 
Of course the files are not identical. Please show us where the differences are `visible`.
It does not make sense to waste time searching for them if you already know where the visible differences are.
Here's a screenshot which shows the differences at left. But I can not see them in the original images
![grafik](https://user-images.githubusercontent.com/13733487/52521258-a6eeb100-2c74-11e9-9ca4-f05610bd2635.png)

**Comment by age1988** [comment]
Yes definitely is a real small difference.

**Comment by Beep6581** [comment]
There is no visible difference, and if you think you're seeing one, especially in a side-by-side comparison, then you're imagining things.

**Comment by age1988** [comment]
I mean that the issue could be closed because the difference is really small, but yes it's there.
