### ISSUE TITLE
RT crashes after a few minutes of work

### ISSUE THREAD

**Issue by Erop1** [Beep6581/RawTherapee#5169]
Dear rawtherapee team,

I love RT, but it crashes every time I use it, after a few minutes of work.
I can’t tell when it’s going to happen. It seems to happen by random.
So I made a video recording of my screen and a stack backtrace, which you can download under the following link:

https://www.magentacloud.de/share/mk-wfp6zhz

gdb does not accept the “set logging on” command. But I inserted the stack backtrace report by copy and paste into the text file. I hope this is OK. 

I had the same problems with older versions of RT. I think the problems came about with version 4.2 or something like that. But I’m not sure about that any more. 

A few month ago I switched from Windows 7 64 Bit to Windows 10 64 Bit (same Computer, new SSD, new Windows installation), but the problems remained. 

The crashes do not depend on the rawfile or the camera manufacturer. 

My system:
Windows 10 64 Bit
Intel Core i5-2500K
8 GB RAM
AMD Radeon HD 6570
Two displays

rawtherapee:
Version: 5.5
Branch: 5.5
Commit: d9ac23555
Commit date: 2018-12-17
Compiler: gcc 8.2.1
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.22.3
Lensfun: V0.3.2.0
Build type: release
Build flags:  -m64 -mwin32 -msse2 -mfpmath=sse -mthreads -Wno-aggressive-loop-optimizations -Wno-parentheses -std=c++11 -mtune=generic -Werror=unused-label -Wall -Wuninitialized -Wno-deprecated-declarations -Wno-unused-result -fopenmp -Werror=unknown-pragmas  -DNDEBUG  -O3 -ftree-vectorize
Link flags: -m64  -mthreads  -static-libgcc   -mtune=generic  -s  -O3  -fno-use-linker-plugin
OpenMP support: ON
MMAP support: ON

If more information is needed, I will try to provide it. 

Thank you for helping!
Egor

**Comment by heckflosse** [comment]
@Erop1 Thanks for the good bug report :+1: 
I will push a fix soon
