### ISSUE TITLE
Crash When Opening Large Image Files

### ISSUE THREAD

**Issue by mike40376** [Beep6581/RawTherapee#5170]
Windows 10 x64
i7-4790k
16GB ram

I have a very large screenshot file captured by nvidia ansel and when I try to open it rawtherapee closes, it either crashes so hard even the debug exe crashes or it just closes. I've tried opening 100mb files they work okay but when I get up to 500mb this starts happening. I know I have enough RAM to open it because it worked fine in GIMP just took about 5 minutes. This also happens in the file browser and not when the file is actually being opened.

**Comment by heckflosse** [comment]
@mike40376 
File size does not matter. What are width and height of the image?

**Comment by Beep6581** [comment]
@mike40376 http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports

**Comment by mike40376** [comment]
@Beep6581 
I'm on version 5.5, I'd provide a backtrace but I can't due to the batch window closing with no output. I can send in a recording if you want but I cant upload the big file to GitHub.

**Comment by mike40376** [comment]
@heckflosse 
File size is 64000x27000

**Comment by Beep6581** [comment]
@mike40376 from the link I sent you,
>  Windows, **open up the command prompt**, navigate to your RawTherapee directory and assuming that the filename of the RawTherapee debug executable is rawtherapee-DEBUG.exe then type:
gdb rawtherapee-DEBUG.exe

Open the command prompt first, then run GDB. That way, whatever happens, the command prompt should remain open.

**Comment by heckflosse** [comment]
@mike40376 could be an unchecked memory allocation.
64000 * 27000 * 3 channels (I assume) * 4 bytes (RT uses float internally) per channel = ~19,25 GB memory to load the image

**Comment by mike40376** [comment]
@heckflosse 
When I opened it in GIMP it worked and on the bottom it said it took 12gb to load the image

**Comment by mike40376** [comment]
@Beep6581 
Last entry on the CMD was

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 13808.0xc24]
0x00007ffc52314510 in msvcrt!memmove () from C:\WINDOWS\System32\msvcrt.dll
(gdb)

**Comment by heckflosse** [comment]
@mike40376 
> When I opened it in GIMP it worked and on the bottom it said it took 12gb to load the image

Well, RT : 64000 * 27000 * 3 channels * 4 are ~19,25 GB
while GIMP : 64000 * 27000 * 4? channels * 2 are ~12,8  GB

**Comment by mike40376** [comment]
@heckflosse 
Ahh I didn't realize they differed from the way they opened/displayed files, if that's accurate then RAM is definitely the issue.

**Comment by heckflosse** [comment]
@mike40376 
> then RAM is definitely the issue.

not definitely. Could also be an overflow when calculating an address.
For that reason I would like to verify the issue with your file.
Could you upload it to filebin.net and post the link here?

**Comment by mike40376** [comment]
@heckflosse 
https://filebin.net/wtw7arign6ezwma7

**Comment by heckflosse** [comment]
@mike40376 Thank you :+1:

**Comment by heckflosse** [comment]
@mike40376 I was wrong. Just opening the image needs ~ width * height * 3 byte, because the input is 8bit. I already found and locally fixed some bugs. Opening the image in editor now works, as well as thumb generation. Full processing in queue/saveas still crashes.
Opening the image takes ~20 seconds on my machine
![grafik](https://user-images.githubusercontent.com/13733487/52583019-e660fd00-2e2e-11e9-84d7-bd27620b32e2.png)

**Comment by heckflosse** [comment]
The two commits from above avoid the crashes when building a thumb from this file and when opening this file in editor.
Full processing of this file still crashes. I'll continue tomorrow

**Comment by mike40376** [comment]
@heckflosse 
That's good to know that there's a fix thanks for the extensive testing

**Comment by heckflosse** [comment]
I found and fixed another bug related to processing of large files.
After fixing this bug I could process the 64000x27000 image in queue using neutral profile on my machine with 32GB Ram and 16 GB swap space.

I will commit the fix soon.

**Comment by heckflosse** [comment]
With the fixes from above, I could process the 64000x27000 file using neutral profile without issues.
Also reduced the peak memory usage to process non raw files in queue

**Comment by Beep6581** [comment]
Closing as fixed.
