### ISSUE TITLE
Division by zero in Tone Mapping

### ISSUE THREAD

**Issue by RawConvert** [Beep6581/RawTherapee#5171]
I was experimenting with Tone Mapping to see how it affected the tree in the supplied filebin and noticed that as I moved the Scale slider the preview darkened at certain specific points then returned to normal as I continued to move it.  This effect was sensitive - just one unit of movement was enough to make the difference.  After a while RT crashed out completely.  There were errors messages in the Terminal window, see filebin, I think one being produced each time the preview darkened.
Version: 5.5-98-g9210a56    Branch: dev    Commit: 9210a56    Commit date: 2019-02-04

https://filebin.net/mpv5nue16vf2mc79

Please delete copies of the CR2 once this issue is concluded/reproduced.

**Comment by heckflosse** [comment]
@RawConvert Please try latest code. Because of https://github.com/Beep6581/RawTherapee/commit/5ddbefd8c49159535bf0f493557e141587a130fb

**Comment by heckflosse** [comment]
@RawConvert Bug confirmed. Looking...

**Comment by heckflosse** [comment]
It is `Local Contrast` in combination with `Tone Mapping` which causes the crash in this case.
Still don't know why...

**Comment by heckflosse** [comment]
@agriggio any idea?

**Comment by heckflosse** [comment]
Update: It's clearly a bug in Tonemapping. Still searching...

**Comment by TechXavAL** [comment]
Maybe the same problem?

I can consistently crash RT 5.8dev (commit 6c1055f98) on linux Mint 19.3.

The raw image comes from this Playraw: https://discuss.pixls.us/t/besoin-d-aide-image/18712/1

The pp3 with the problem ready to crash RT is this one: 
[IMG_1270.CR2_TMbroken.pp3.zip](https://github.com/Beep6581/RawTherapee/files/4772893/IMG_1270.CR2_TMbroken.pp3.zip)

Just open the image and apply this pp3, resize to 1:1 zoom and show this preview:

![screenTM](https://user-images.githubusercontent.com/52250392/84541452-b4e49400-acf7-11ea-8613-68e60de00a05.jpg)


Turn on Tone Mapping, slide Edge stopping over 3.79 and the program will crash

However if you show e.g. the street in the preview, the program won't crash. Note that Local Contrast is turned on, too.

**Comment by heckflosse** [comment]
@TechXavAL Thanks for your report. I will give it another try to fix the issue at the weekend. Can not promise success though...

**Comment by TechXavAL** [comment]
@heckflosse No problem. I already know that I'm fine by not going past 3.6 in Edge stopping.

**Comment by Desmis** [comment]
@heckflosse 
Ingo
I tried with of course the same file, and the same pp3
But I enable "Tone mapping" in Local adjustments with the same "settings" @TechXavAL 

I try, try, try... no crash...in this case TM is call internal to "iplocallab.cc"
Of course, I choose a big RT-spot beyond the preview...hence we are for "epd" in the same case.


And if I try with "TM main"...crash : in this case TM is call from improccordinator and dcrop

But why ?

Jacques

**Comment by Desmis** [comment]
@heckflosse 
Ingo
I disable "epd" in rttumbnail.cc ==> no crash ??

Jacques

**Comment by Desmis** [comment]
Yes it crash also  ...sorry :)

But in "local adjustments", the image becomes "dark"... with "local contrast"

**Comment by heckflosse** [comment]
@Desmis Jacques, for whatever reason Tone Mapping sometimes produced -inf values. I just clamped them to 0 to fix the crash

**Comment by Desmis** [comment]
@heckflosse 
I don't know

But (I speak of main TM), if you put in  "Local contrast"  "darkness level" = 0 , no crash, darkness level =0.02 crash
