### ISSUE TITLE
Chromaticity histogram appears wrong?

### ISSUE THREAD

**Issue by RawConvert** [Beep6581/RawTherapee#5172]
These two screen grabs show chrom. being reduced via the CL curve in Lab.  As the point is moved to the right, the chrom reduces in the dark tones as expected in the preview, but the yellow histogram trace increases on the left side, rather than decreasing.
![clcurve-before](https://user-images.githubusercontent.com/16868433/52537601-6ec49c80-2d60-11e9-9bcc-92a0e5c1ab7d.png)
![clcurves-after](https://user-images.githubusercontent.com/16868433/52537604-7421e700-2d60-11e9-9120-f944c55900a6.png)

Version: 5.5-98-g9210a56   Branch: dev    Commit: 9210a56    Commit date: 2019-02-04

**Comment by Beep6581** [comment]
As you move the curve's "black" point to the right, the amount of pixels having a minimal chromaticity increases, so a vertical spike appears in the histogram at the left end. The spike tells you that a lot of pixels have that chromaticity, and the position of the spike on the x axis tells you what chromaticity that is - in this case the minimal chromaticity (0%?). Looks good to me.

**Comment by RawConvert** [comment]
I see what you mean.
When I see multiple traces on a graph, I assume the x-axis is the same for them all, so I assumed that for chrom. (though I know a histogram isn't quite the same as a graph).  So I thought it would be showing a measure of chrom. for each of the 256? bins that make up the "brightness" histograms.

I'm not sure when or how I would use a chrom. histogram but another possibility, apart from the two above, would be to have all the hues as the x-axis.  This would show up any large imbalance in colours that you might have for some reason.
