### ISSUE TITLE
Filmstrip moves active image to the far left

### ISSUE THREAD

**Issue by Thanatomanic** [Beep6581/RawTherapee#5174]
I think #5125 actually had a side-effect, although @Beep6581 said it didn't. Or maybe there was another commit that changed the filmstrip behavior, but I'm not seeing it. In any case, the issue below is not present in 5.5 (release version) but it is in dev. For what it's worth, I'm using SETM.

What's the issue: whenever I select an image from the filmstrip, it moves the strip so that the selected image is the one on the far left. I would very much prefer the selected image to be (somewhat) in the middle. This is especially annoying when working on a sequence of images where you repeatedly have to scroll to get the earlier images in view.

**Comment by TooWaBoo** [comment]
This will fix it. Check it out.
Change yellow to blue. 😀
### editorpanel.cc
![unbenannt](https://user-images.githubusercontent.com/13800920/52899103-6fd54e00-31e6-11e9-97d8-b5200cbb678a.png)

**Comment by heckflosse** [comment]
@TooWaBoo Your modification breaks this:
```
    // When passing a photo as an argument to the RawTherapee executable, the user wants
    // this auto-loaded photo's thumbnail to be selected and visible in the Filmstrip.
```

**Comment by heckflosse** [comment]
@TooWaBoo scratch my comment from above.

**Comment by TooWaBoo** [comment]
> @TooWaBoo scratch my comment from above.

I will. 😁

**Comment by heckflosse** [comment]
@TooWaBoo But F3/F4 does not behave as before...

**Comment by heckflosse** [comment]
@TooWaBoo before modification after F4 the current thumb in filmstrip is always the leftmost (if there are enough thumbs on the right)
after modification sometimes after F4 the current thumb in filmstrip is the rightmost even if there are enough thumbs on the right.

**Comment by TooWaBoo** [comment]
This should fix the F3/F4 behaviour.
![grafik](https://user-images.githubusercontent.com/13800920/52900712-6dc8ba80-31f9-11e9-9a61-07016f8f5d28.png)

EDIT: Oh sh..., it doesn't. I've to play a bit more.

**Comment by TooWaBoo** [comment]
Ok, now all changes together.
### editorpanel.cc
![52899103-6fd54e00-31e6-11e9-97d8-b5200cbb678a](https://user-images.githubusercontent.com/13800920/52903221-a462fd00-321a-11e9-99f4-5995c921c9e1.png)

### filebrowser.cc
If you use F3/F4, shift F3/F4 or Left-, Right-button the filmstrip is always alignd left.

![grafik](https://user-images.githubusercontent.com/13800920/52903189-27378800-321a-11e9-978e-5f9158bee3a6.png)
![grafik](https://user-images.githubusercontent.com/13800920/52903250-e4c27b00-321a-11e9-901e-36eec5ffb9ae.png)

**Comment by heckflosse** [comment]
@TooWaBoo Why don't you post a patch file (or the content of a patch file)? It's as easy as 
```
git diff > toowaboo.patch
```
Then open in editor and insert it here.

**Comment by heckflosse** [comment]
@TooWaBoo Honestly, I won't apply screenshot patches anymore. I did it once today (and I didn't it correct, because it was confusing). This led to even more confusion and waste of your and my time.

Please, post a patch or create a pr.

Ingo

**Comment by Beep6581** [comment]
> whenever I select an image from the filmstrip, it moves the strip so that the selected image is the one on the far left. I would very much prefer the selected image to be (somewhat) in the middle.

Agreed, centered would be preferable over left-aligned.

**Comment by Beep6581** [comment]
We haven't defined what the desired behavior is, so here goes. I like my selected thumbnail centered so that I can see what came before and what's next, but I don't necessarily always want it centered - I would prefer scrolling to not occur if the previous/next thumb is fully visible.

That is exactly what branch `centeredthumb` does:
https://github.com/Beep6581/RawTherapee/compare/centeredthumb

**Comment by Beep6581** [comment]
PR #5183 created.

**Comment by shastah** [comment]
> I would prefer scrolling to not occur if the previous/next thumb is fully visible

Does that mean selecting next(prev) image would effectively not scroll filmstrip until image that gets selected is second most-right(left) displayed in the filmstrip, and _then_ every subsequent F4(F3) would scroll it by one?

If my understanding above is correct, is there a way to make it always(*) centered? A setting in preferences perhaps?

(*) Until there are not enough images to scroll filmstrip more left or right, of course

**Comment by Beep6581** [comment]
> Does that mean selecting next(prev) image would effectively not scroll filmstrip until image that gets selected is second most-right(left) displayed in the filmstrip, and _then_ every subsequent F4(F3) would scroll it by one?

The first part is correct, the second is not. Once selection gets to the second-most thumb from the right, and you switch to the next image, that image's thumb will now be centered. In other words, it doesn't scroll unless necessary, and when it is necessary then it centers the thumb.

> is there a way to make it always(*) centered? A setting in preferences perhaps?

Yes, that's even simpler to code, but could be annoying when you want to keep everything as it is and just switch to the next image.

> A setting in preferences perhaps?

I'd rather not add bloat.

Here's a video of the behavior in branch `centeredthumb`:
https://filebin.net/ti5tj508h8q8cmhe/video-2019-02-24_12.07.46.mp4?t=65ddos94

**Comment by Beep6581** [comment]
Closing as fixed.
