### ISSUE TITLE
Seg fault on start in Wayland Plasma 15.15

### ISSUE THREAD

**Issue by mihapiha** [Beep6581/RawTherapee#5176]
Rawtherapee won't start on Wayland session of KDE Plasma (I am using KDE Neon with Plasma 5.15). It stops with a seg fault.

[raw-log.txt](https://github.com/Beep6581/RawTherapee/files/2866523/raw-log.txt)

**Comment by heckflosse** [comment]
http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports

**Comment by TooWaBoo** [comment]
@mihapiha 
Looks like the Adwaita cursor files are missing.

**Comment by mihapiha** [comment]
@TooWaBoo that was it, thanks :) It worked in X11 session though
