### ISSUE TITLE
Lab histogram and main histogram seem misaligned

### ISSUE THREAD

**Issue by RawConvert** [Beep6581/RawTherapee#5180]
Using the "point" icon in the Lab L* histogram relates the mouse position on the preview to the value on the histogram.  And the main histogram shows this too.  The two are significantly different as shown by the screen grabs below (RT gives a short white bar at the base of the main histogram indicating position).
RT 5.5-98
![histo-anomaly-1](https://user-images.githubusercontent.com/16868433/52914558-d4191000-32c1-11e9-9660-60cb8157bd85.png)
![hosto-anomaly2](https://user-images.githubusercontent.com/16868433/52914560-d8452d80-32c1-11e9-9ecd-81857131fbac.png)
![histo-anomaly3](https://user-images.githubusercontent.com/16868433/52914561-db401e00-32c1-11e9-9401-97ebee63ff50.png)

Also, why does the L* hist only use the first half or so of the x axis?  (CIECAM is like this too I think)

**Comment by Thanatomanic** [comment]
> Also, why does the L* hist only use the first half or so of the x axis? (CIECAM is like this too I think)

Regarding this, please see #4933

**Comment by Beep6581** [comment]
http://rawpedia.rawtherapee.com/Exposure#Tone_Curves

> The histogram displayed as the curve's background shows you the levels of the data as it flows into the curve at that point in the processing pipeline. You will notice that it differs from the main histogram which shows you the levels of the final image, at the very end of the pipeline.

http://rawpedia.rawtherapee.com/Lab_Adjustments#L_Curve

> The histogram on the L curve reflects lightness prior the Lab adjustments.

I am in the process of rewriting RawPedia material related to curves so these links may change.

**Comment by RawConvert** [comment]
Ok thanks.  But then re. the 2nd quote, why does the L* histogram change when you move a point?

**Comment by Beep6581** [comment]
I don't know. It could be a bug, or outdated docs. I hope @heckflosse 's investigation while looking into #4933 will reveal which it is.

**Comment by RawConvert** [comment]
I think it's important to have the histogram behaving nicely.  If you want a steep (or flat) bit of curve in a given place, the histogram on which you're drawing the curve needs to be accurate.

**Comment by heckflosse** [comment]
@Beep6581 
> outdated docs

exactly, should be
```
The histogram on the L curve reflects lightness after the Lab adjustments.
```

**Comment by Beep6581** [comment]
Docs updated.
