### ISSUE TITLE
Windows 10: Can't access folder C:\Users\Public\Pictures

### ISSUE THREAD

**Issue by clasatau** [Beep6581/RawTherapee#5185]
Hi,

I am using a fresh installation of Rawtherapee:
Version: 5.5
Branch: 5.5
Commit: d9ac23555
Commit date: 2018-12-17
Compiler: gcc 8.2.1
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.22.3
Lensfun: V0.3.2.0
Build type: release
Build flags:  -m64 -mwin32 -msse2 -mfpmath=sse -mthreads -Wno-aggressive-loop-optimizations -Wno-parentheses -std=c++11 -mtune=generic -Werror=unused-label -Wall -Wuninitialized -Wno-deprecated-declarations -Wno-unused-result -fopenmp -Werror=unknown-pragmas  -DNDEBUG  -O3 -ftree-vectorize
Link flags: -m64  -mthreads  -static-libgcc   -mtune=generic  -s  -O3  -fno-use-linker-plugin
OpenMP support: ON
MMAP support: ON

Operating System: Windows 10 Home 64 bit

I can't access the folder C:\Users\Public\Pictures where I have saved all my raw files. In the file browser I can navigate to C:\Users\Public but there no subfolder Pictures is listed. Using the Windows explorer the situation is similar because the subfolder Pictures seems to be a hidden and protected system file. I can make it appear in windows explorer by unticking the folder option  "hide protected system files (recommended)" (don't know if these are the exact words in english because I am using a german environment) and by choosing "show hidden files and folders". Additionally I can access the folder via the library "Pictures" which contains - among others - the Folder C:\Users\Public\Pictures.

In rawtherapee I even can't access the Folder via a symbolic link which I created elsewhere. 

The only possibility to access this Folder is to specify it as a command line argument when starting Rawtherapee from a cmd-shell. But then I am still unable to switch to subfolders of C:\Users\Public\Pictures.

I hope this issue can be solved soon because it keeps me from using this greate piece of software which seems to have matured a lot since I have used it some years ago.

**Comment by heckflosse** [comment]
I you can't use the Windows explorer to view this folder, it's very unlikley RT can solve this issue

**Comment by Thanatomanic** [comment]
@clasatau Why are you saving stuff in the `\Public\` folder anyway?

![image](https://user-images.githubusercontent.com/6567747/53237777-db606500-3697-11e9-8667-423af4adc832.png)

Unless you have a very strange setup of Windows, clicking on Pictures there will lead you to `C:\Users\<YourUserNameHere>\Pictures` which should definitely exist. If it doesn't, it's most certainly an issue of your Windows installation and not something we can fix.

**Comment by gaaned92** [comment]
@clasatau 
W10 home 64bits, no peculiar tweaking
RT 5.5 

* my C: drive is my system drive (a SSD). I avoid as far as possible to put data in this disk. My D: drive is a 1TB HDD where I put all my data ( in peculiar photos, mails, documents...).
Thus I never had the opportunity to test RT with C:\users\...
*  I made a test with `c:\users\Public\pictures`

   * In an administrator Windows account I copy an image folder `MyPics` to `C:\users\public\pictures`
   * I switch to a user windows account
   * I open RT5.5. I can select in the [RT File Browser](http://rawpedia.rawtherapee.com/File_Browser) the folder `C:\users\public\pictures\MyPics`, view the thumbnails and open an image.



> Using the Windows explorer the situation is similar because the subfolder Pictures seems to be a hidden and protected system file. I can make it appear in windows explorer by unticking the folder option "hide protected system files (recommended)"

That should not be. The subfolder` public\pictures` is a public folder visible from all users and is not a system folder that should be hidden or protected. 
At least it is not the case on my system.

**Comment by clasatau** [comment]
Thanks to all who took the time to investigate the issue.

I managed to solve the issue by unsetting the hidden attribute of the folder Pictures in C:\Users\Public. This was not possible via GUI because even in an explorer started with administrator privileges the "hidden" checkbox was greyed out. So I launched a Shell with administrator privileges, unset hidden and system attributes with `attrib -H -S Pictures /D` and then reset System Attribute with `attrib +S Pictures /D`. The last one I did to re-enable the localized folder name "Öffentliche Bilder". 

@gaaned92 I don't know either why by default the folder was hidden. I didn't set it manually.
@Thanatomanic I saved all my Picture files in the Public\Pictures folder to be able to access them from all user accounts.


So to improve Rawtherapee it would be desirable to enable access to the libraries under Windows (see screenshot) and/or to make it possible to display hidden folders in the file browser.
![screenshot](https://user-images.githubusercontent.com/47870196/53287060-42088000-3777-11e9-8eb2-260a5253babe.png)

**Comment by heckflosse** [comment]
@clasatau There is already an option to show hidden folders/files. Unfortunately you can't set it in preferences dialog (don't know why).
But you can manually set in in the options file. Just change the entry
```
BrowserShowsHidden=false
```
to
```
BrowserShowsHidden=true
```

Don't use notepad.exe to modify the options file. It does not handle the line endings.
Notepad++ handles them fine.

**Comment by heckflosse** [comment]
One possible solution: Use the setting from windows file manager. Same behaviour as before for other OS

```diff
diff --git a/rtgui/options.cc b/rtgui/options.cc
index b7975ddfe..1faedcaa1 100644
--- a/rtgui/options.cc
+++ b/rtgui/options.cc
@@ -352,7 +352,13 @@ void Options::setDefaults()
     fbShowDateTime = true;
     fbShowBasicExif = true;
     fbShowExpComp = false;
+#ifdef WIN32
+    SHELLFLAGSTATE sft = { 0 };
+    SHGetSettings(&sft, SSF_SHOWALLOBJECTS);
+    fbShowHidden = sft.fShowAllObjects;
+#else
     fbShowHidden = false;
+#endif
     fbArrangement = 2;                  // was 0
     navRGBUnit = NavigatorUnit::PERCENT;
     navHSVUnit = NavigatorUnit::PERCENT;
@@ -930,9 +936,11 @@ void Options::readFromFile(Glib::ustring fname)
                     fbShowExpComp = keyFile.get_boolean("File Browser", "BrowserShowsExpComp");
                 }
 
+#ifndef WIN32
                 if (keyFile.has_key("File Browser", "BrowserShowsHidden")) {
                     fbShowHidden = keyFile.get_boolean("File Browser", "BrowserShowsHidden");
                 }
+#endif
 
                 if (keyFile.has_key("File Browser", "MaxPreviewHeight")) {
                     maxThumbnailHeight = keyFile.get_integer("File Browser", "MaxPreviewHeight");
@@ -1887,7 +1895,9 @@ void Options::saveToFile(Glib::ustring fname)
         keyFile.set_boolean("File Browser", "BrowserShowsDate", fbShowDateTime);
         keyFile.set_boolean("File Browser", "BrowserShowsExif", fbShowBasicExif);
         keyFile.set_boolean("File Browser", "BrowserShowsExpComp", fbShowExpComp);
+#ifndef WIN32
         keyFile.set_boolean("File Browser", "BrowserShowsHidden", fbShowHidden);
+#endif
         keyFile.set_integer("File Browser", "ThumbnailSize", thumbSize);
         keyFile.set_integer("File Browser", "ThumbnailSizeTab", thumbSizeTab);
         keyFile.set_integer("File Browser", "ThumbnailSizeQueue", thumbSizeQueue);

```

**Comment by Hombre57** [comment]
@heckflosse The user have to restart RT if the Windows parameter change, but I think it's totally fine. :+1:  to commit.

**Comment by Thanatomanic** [comment]
@heckflosse I think your patch is fine to commit too. The alternative would be to make a toggle in the file dialog, but it's probably GTK that handles that...
