### ISSUE TITLE
Crash in Windows opening folder with only Thai characters in name

### ISSUE THREAD

**Issue by ve3** [Beep6581/RawTherapee#5186]
RawTherapee 5.5
Windows 10 64 bit

Open program and it just close. No window appear.

**Comment by Beep6581** [comment]
https://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports
https://rawpedia.rawtherapee.com/How_to_fix_crashes_on_startup

**Comment by ve3** [comment]
It's clean, new and first install.

And that bug reports page I can't get anything more than this because it just run the process and end.

**Comment by Thanatomanic** [comment]
@ve3 I hope you understand that going from your description it is literally impossible to provide any form of support?

**Comment by ve3** [comment]
[log.txt](https://github.com/Beep6581/RawTherapee/files/2893649/log.txt)

**Comment by Thanatomanic** [comment]
It seems to crash on `libthai-0.dll`. Is that the default language for your operating system?
Can you try the following:

1. Go to `C:\Users\<YourUserName>\AppData\Local\RawTherapee5` (or whatever the RT folder is called exactly)
2. Open the `options` file in notepad or similar and put
```
Language=English (US)
LanguageAutoDetect=false
```
3. Save and restart RT. Does it work?

**Comment by ve3** [comment]
No, my default OS language is English (US).

I tried to change options as you said and change `StartupPath=C:\\test`.
Program can now opened but when I browse to the folder that contain Thai language, the program crash again.

I had installed v 5.4 but it seems to be working fine.

**Comment by Thanatomanic** [comment]
> Program can now opened but when I browse to the folder that contain Thai language, the program crash again.

Is it just one folder that gives problems, or many? Are there Thai characters in the filename or folder name or both? Could it be related to a specific file?

Using the latest dev build I do not have any trouble with Thai characters in either a folder name or file name.

![image](https://user-images.githubusercontent.com/6567747/53240022-d4d4ec00-369d-11e9-8005-a509c28db72a.png)

**Comment by Beep6581** [comment]
@ve3 since RT runs fine in c:\temp but crashes when you browse to your photo folder most likely due to Thai characters somewhere in the filename or file metadata, isolate the crash to a single file (as described in the link I sent you) and upload this file using https://filebin.net/ , then paste the final link here.

**Comment by ve3** [comment]
It is not just one folder but any folder that contain Thai characters.
If folder name is English but file names are Thai or English+Thai such as **Helloสวัสดี.jpg** then it is working fine.
This means it may not because of a file name.

Here is GIF screenshot. [https://gifyu.com/image/3MRN](https://gifyu.com/image/3MRN)

**Comment by heckflosse** [comment]
@ve3 Please try a build from [here](https://discuss.pixls.us/t/download-rawtherapee-development-builds/2924). Iirc there was a bug in 5.5 related to Windows and languages, which is already fixed.

**Comment by Floessie** [comment]
de6ee45?

**Comment by heckflosse** [comment]
@Floessie Yes, that's the one I had in mind. Though it should not cause a crash...

**Comment by ve3** [comment]
> RawTherapee_newlocallab_5.5-664-g22323852a_WinVista_64_190221.zip

This one seems to be fixed. Thank you.

**Comment by Beep6581** [comment]
Closing as fixed.
