### ISSUE TITLE
.RWL files RAW format from LEICA D-LUX 7

### ISSUE THREAD

**Issue by DSOUTY** [Beep6581/RawTherapee#5188]
Hi
Can RawTherapee work with .RWL files RAW format from LEICA D-LUX 7 ?
Thanks in advance !
Dominique

If you are filing a bug report, please first read the guide How to Write Useful Bug Reports:
http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports
You must provide the required information in order for your bug report to be valid.
Delete this text before posting.

**Comment by Beep6581** [comment]
https://github.com/Beep6581/RawTherapee/blob/releases/RELEASE_NOTES.txt#L13
