### ISSUE TITLE
5.6 macOS build crashes on launch

### ISSUE THREAD

**Issue by gkthau** [Beep6581/RawTherapee#5190]
Hi,

I had been having trouble installing the official version of RT 5.5. On running the application the program crashes immediately. The error log says:

exception Type:        EXC_BAD_INSTRUCTION (SIGILL)

Searching the forums, it seems to be the same issue as experienced by some Mac users, e.g.:
https://github.com/Beep6581/RawTherapee/issues/4091
https://github.com/Beep6581/RawTherapee/issues/4547

The problem only happens on my Mac Pro 2006 1,1, but the official version of RT 5.5 runs fine on my more recent Macbook Pro  2015. Both are running OS X El Capitan 10.11.6. I also tried other versions of  RT, and the only one which would work on my Mac Pro was  RT 5.0-r1-gtk3. 

I decided to compile RT from scratch, following the wiki instructions. After a few tries, I got a version which works! I have uploaded it to https://filebin.net/wuk0vc614t2jxbmi  in case it is useful for anyone experiencing the same problem.  The cmake command was:

cmake -DCMAKE_BUILD_TYPE="release" -DPROC_TARGET_NUMBER="1" -DPROC_LABEL="generic processor" -DCACHE_NAME_SUFFIX="5-dev" -DCMAKE_C_COMPILER="clang-mp-3.9" -DCMAKE_CXX_COMPILER="clang++-mp-3.9" -DWITH_LTO="OFF" ..

i.e. no DLENSFUNDIR

One has to put the following into the file ~/Library/Application Support/RawTherapee/config

[Lensfun]
DBDirectory=/opt/local/share/lensfun/version_1

Hope this is useful to someone....

**Comment by Benitoite** [comment]
Could you give the latest dev build a try?  https://discuss.pixls.us/t/download-rawtherapee-development-builds/2924

This is interesting because I have never been able to reproduce on 10.11 

There is much missing info. http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports

For instance, what CPU are installed in the macpro1,1?  I’m wondering if turning LTO off made the difference for you.

**Comment by gkthau** [comment]
The latest dev built 5.5-106-g8eba1c40a also doesn’t run on the Mac Pro 2006. The error report is attached as a file
[error.txt](https://github.com/Beep6581/RawTherapee/files/2898944/error.txt)
. Unfortunately I don’t know how to run gdb on OSX, so no stack backtrace.

Here are more details:

Version:
- v5.1 to 5.5 official builds don’t run on the Mac Pro 2006 but ok with Macbook Pro 2015.
- RT 5.0-r1-gtk3 works on all Macs

Operating system:
- All computers run on El Capitan OS X 10.11.6


- CPU: On the 2006 Mac Pro: 2 x 2.66 GHz Quad-Core Intel Xeon x5355)
- RAM: 14 MB 

I tried building v5.5 with the following flags: -DWITH_LTO=ON -DCMAKE_AR=/usr/bin/gcc-ar -DCMAKE_RANLIB=/usr/bin/gcc-ranlib . During make it crashes:

[  4%] Building CXX object rtexif/CMakeFiles/rtexif.dir/panasonicattribs.cc.o
[  4%] Linking CXX static library librtexif.a
Error running link command: No such file or directory
make[2]: *** [rtexif/librtexif.a] Error 2
make[1]: *** [rtexif/CMakeFiles/rtexif.dir/all] Error 2
make: *** [all] Error 2

**Comment by gkthau** [comment]
One thing I forgot to add:

In order to run OS X 10.11.6 on the Mac Pro 2006, some hacking was involved:
https://forums.macrumors.com/threads/2006-2007-mac-pro-1-1-2-1-and-os-x-el-capitan.1890435/

One consequence is no "metal" API support with my graphics card.

**Comment by Benitoite** [comment]
Sorry I’m overseas for a month so I can’t analyze this very completely yet, but thanks for the data.  At first glance it looks like pango freaks out about something. Did your libraries come from macports, homebrew, or scratch build?  Also if you build with clang 3.9, are you sure gcc-ar is compatible?  Could you provide the error log for the linking error you got with LTO on. It says no such file, not sure what it’s not finding.  Have you tried plain-ole `ar` and `ranlib`?
