### ISSUE TITLE
Lensfun lens selection broken in latest windows builds.

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#5194]
In latest windows builds (nightly) and in my own windows build, the lensfun lens selection is broken.
If I want to select a Nikkor Ais lens I can't do that anymore, because the scroll-arrow at the bottom of the lens list is not available. Maybe a gtk issue?

Edit: works fine in official windows build of RT 5.5

Can other windows builders confirm? I'm on Windows7/64

![grafik](https://user-images.githubusercontent.com/13733487/53340505-73b15080-3909-11e9-957b-05648fc9cd6e.png)

**Comment by gaaned92** [comment]
Yes confirmed on W10 64.

**Comment by TooWaBoo** [comment]
Confirmed W10 x64 Home

**Comment by heckflosse** [comment]
@gaaned92 @TooWaBoo 
Do you know what to downgrade to make it working again?

**Comment by TooWaBoo** [comment]
@heckflosse 
I think you have to downgrade to:
`mingw-w64-x86_64-gtk3-3.22.30-1` and `mingw-w64-x86_64-gtkmm3-3.22.3-1`
All higher versions have some issues.

**Comment by heckflosse** [comment]
@TooWaBoo Thanks :+1: 
Works fine after downgrading

**Comment by gaaned92** [comment]
@heckflosse @TooWaBoo 
Do you think:
-  it is a bug in GTK3 that will be corrected by GTK3 people
-  or a modification of behaviour (a feature), requiring a modif in RT.
In the mean time, I am going to downgrade!
Thanks.

**Comment by heckflosse** [comment]
I think it is a bug in GTK3

**Comment by LordPhoenixfr** [comment]
Hi folks
Just to say I have same problem here with rawtherapee 5.5 and Ubuntu 18.10.

**Comment by Beep6581** [comment]
I need to know for the 5.6 release notes which version(s) of GTK+ are affected. @LordPhoenixfr @heckflosse @TooWaBoo @gaaned92 which versions are you using?

**Comment by Beep6581** [comment]
No problem with GTK+ 3.24.1 in Linux.

**Comment by TooWaBoo** [comment]
@Beep6581 
Windows 10, GTK+ 3.24.5

**Comment by Floessie** [comment]
- Debian 10 (GTK+ 3.24.5): :x:
- Debian 9 (GTK+ 3.22.11): :heavy_check_mark: 
- FreeBSD 12 (GTK+ 3.22.30): :heavy_check_mark:

**Comment by gaaned92** [comment]
@Beep6581 
W10, downgraded to GTK+ 3.22.30-1 :heavy_check_mark:

**Comment by Beep6581** [comment]
@TooWaBoo is 3.24.5 good or bad?
@gaaned92 what did you downgrade from?

**Comment by Beep6581** [comment]
@Benitoite says 3.24.7 works fine.

**Comment by TooWaBoo** [comment]
> @TooWaBoo is 3.24.5 good or bad?

This version has the lensfun bug.

**Comment by gaaned92** [comment]
I downgraded from 3.24.5 which has the lensfun bug.

3.24.7 is not available on MSYS2

**Comment by Benitoite** [comment]
Just checking to see if I tested the correct bug.
![Screen Shot 2019-03-30 at 11 05 25 AM](https://user-images.githubusercontent.com/17919239/55279947-29423b80-52dc-11e9-9768-6c590043fb49.png)

**Comment by heckflosse** [comment]
@Benitoite You tested the correct bug :+1:

**Comment by Benitoite** [comment]
@heckflosse 😌 
Perhaps we can raise an issue so that package gets updated sooner than later? @lazka made the last update to gtk 3.24.5, maybe he can help.

https://github.com/msys2/MINGW-packages/issues

**Comment by Beep6581** [comment]
In summary:
* 3.24.1 is the last-known good version before 3.24.5 which is known to have broken `Gtk::ComboBox` scrollers, and 3.24.7 is the first-known good version since the bug.
* When making RawTherapee 5.6 builds, please use GTK+ <=3.24.1 or >=3.24.7.

https://gitlab.gnome.org/GNOME/gtk/tags

**Comment by lazka** [comment]
@Benitoite I'll look into (but I can't upload packages to MSYS2, so it might take a while)

**Comment by Beep6581** [comment]
Maybe we should warn if someone uses a problematic version of GTK+. Branch `warncombo` does that, see PR #5253 
Anyone for or against merging that? Please test it if you're for merging it.

**Comment by lazka** [comment]
> @Benitoite I'll look into (but I can't upload packages to MSYS2, so it might take a while)

done: https://github.com/msys2/MINGW-packages/pull/5125

**Comment by LordPhoenixfr** [comment]
GTK version is 3.24.4 here…
