### ISSUE TITLE
xtrans border

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#5198]
This issue is about improving xtrans border issues.

First part will fix a pattern which sometimes show up at the one pixel border of xtrans files as shown here using the example file from [here](https://discuss.pixls.us/t/flat-field-correction-pattern-noise/11578/3?u=heckflosse)

The screenshot clearly shows some artifacts at lower border
![grafik](https://user-images.githubusercontent.com/13733487/53599599-daec3080-3ba7-11e9-845d-79abfcc6b8a1.png)

**Comment by heckflosse** [comment]
Commit from above gives this border which is clearly better:
![grafik](https://user-images.githubusercontent.com/13733487/53600560-23a4e900-3baa-11e9-80f3-6f8ee0a93d83.png)

**Comment by heckflosse** [comment]
Second part gives a tiny improvement for border inerpolation by using the same weights as in fast_xtrans_interpolate.

**Comment by heckflosse** [comment]
Third part adds an adjuster to allow user defined border for xtrans in the same range as it's already available for bayer
![grafik](https://user-images.githubusercontent.com/13733487/53642317-ce141f00-3c31-11e9-9f18-8f44ef2209b3.png)

**Comment by heckflosse** [comment]
@sguyader Sébastien, please test, if your time permits.

**Comment by sguyader** [comment]
@heckflosse can you tell what to test exactly? What does the new slider do?
And you have a complete patch with all the new modifications?

**Comment by heckflosse** [comment]
@sguyader 
The slider just allows to use some pixels more than before at the borders. It's mainly for consistency (for bayer the slider was already available) but can give you some more space to e.g. distortion correct or straighten an image. The default value of 7 is the value used before changes. A value of 0 gives you 7 additional pixels at each border.

> And you have a complete patch with all the new modifications?

It's all in xtransborder branch.

**Comment by sguyader** [comment]
> It's all in xtransborder branch.

Ah ok, I didn't see that!

**Comment by sguyader** [comment]
@heckflosse  Ingo it seems to work as expected.

**Comment by heckflosse** [comment]
Fixed with 520a3709bf426ebdace39a12f5dd08fee6f75feb
Closing
