### ISSUE TITLE
Use v4 sRGB profile by default

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#5200]
We once agreed ([1](https://github.com/Beep6581/RawTherapee/issues/4478#issuecomment-389182186)) that RawTherapee should use the v4 ICC sRGB profile `RTv4_sRGB.icc` by default, and it did ([2](https://github.com/Beep6581/RawTherapee/issues/4478#issuecomment-403447200)), but today [I noticed](https://github.com/Beep6581/RawTherapee/issues/5199#issuecomment-468770894) that it no longer does. Commit d55d3446f60246aa206f57c5d7cf1dda06f3f268 changed 
`rtSettings.srgb = "RTv4_sRGB";`
to
`rtSettings.srgb = "RTv2_sRGB";`

@Desmis was that an accident? If so, could you revert to v4 please?

Secondly, I noticed and don't understand https://github.com/Beep6581/RawTherapee/blob/dev/rtgui/options.cc#L1465
`if RTv4_* then rtSettings.* = RTv2_*`? RT uses v2 even if I explicitly set v4 in the `options` file? I'm tired so I might be reading it incorrectly, but please verify.

Ping @agriggio

**Comment by agriggio** [comment]
@Beep6581 I have no idea what the purpose of those options lines are, but I agree that they look strange at least.

**Comment by Desmis** [comment]
@Beep6581 
for rtSettings.srgb = "RTv4_sRGB";
to
rtSettings.srgb = "RTv2_sRGB";
Yes it is a mistake
For the other it is "normal"


I commit and push the change

**Comment by Beep6581** [comment]
> I commit and push the change

Thank you.

> For the other it is "normal"

Could you please explain what the intention is behind changing for example `RTv4_Large` to `RTv2_Large` without the user knowing about this?

**Comment by Desmis** [comment]
@Beep6581 
LCMS does not allow to generate ICCv2 directly. 
It is necessary to go through a "copy" of a similar version of a reference v2.
If you look to "Elle Stone" generator, you can look a similar process.

jacques

**Comment by Beep6581** [comment]
Thank you @Desmis 
Closing as fixed.
