### ISSUE TITLE
Raw ca correction tiles per thread

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#5203]
The raw ca correction is a tiled processing whith a chunk size of 1. That means a tile is assigned to a thread and when the thread finished the processing of the tile, a new tile is assigned to the thread until all tiles are processed.
Today I played a bit with the chunk size and detected tha a chunk size of 1 is not the best solution (on my system at least).

To simpilfy testing I created [a new branch](https://github.com/Beep6581/RawTherapee/tree/rawca_cunksize) which adds an adjuster to preferences to set the chunk size (number of tiles per thread).
![grafik](https://user-images.githubusercontent.com/13733487/53696583-c89d0d00-3dc8-11e9-89b3-03b58ad23d62.png)

At my 8-core AMD FX 8350 a value of 16 gives an ~20% speedup for raw ca correction one iteration, avoid color shift disabled.

**Comment by heckflosse** [comment]
On my old dual-core laptop the best setting is 8 tiles per thread. But the speedup is only ~5%

**Comment by Thanatomanic** [comment]
My results on my 8 ~core~ threaded i7 3770 for a Nikon D800 36.2 MP file. The effect is measurable, but rather minimal (n = 10 per bin).
![image](https://user-images.githubusercontent.com/6567747/53697775-17e93a80-3dd5-11e9-8b56-2a37f2fecfe9.png)

**Comment by Thanatomanic** [comment]
@heckflosse Disregard the data point at 32. I see now that it is impossible to go that far. I entered the value and clicked okay, but didn't see it got reverted to 16.

**Comment by Thanatomanic** [comment]
Second test run, this time with a smaller 18 MP file from a Canon EOS 4000D.
![image](https://user-images.githubusercontent.com/6567747/53697939-b629d000-3dd6-11e9-9f3c-6c1f35928a71.png)

**Comment by heckflosse** [comment]
@Thanatomanic Thanks for testing and feedback :+1: 

I added the same for rcd demosaic.

My results for rcd demosaic using a D850 file on my FX8350 8-core

```
chunk size 1: 550 ms
chunk size 2: 480 ms
chunk size 4: 470 ms
chunk size 6: 455 ms
chunk size 8: 470 ms
```

**Comment by heckflosse** [comment]
I accidently committed also a change to amaze demosaic (chunk size 8). That speeds up Amaze demosaic for a D800 file from 500 ms to 460 ms. No testing gui for that at the moment...

**Comment by heckflosse** [comment]
Another examply for rcd demosaic. This time a 100 MP Phase-One file
```
chunk size 1: 1105 ms
chunk size 6:  980 ms
```

**Comment by heckflosse** [comment]
@Thanatomanic Your and my results show that the current default of 1 for CA-correction is the worst case.
Even if it's a small improvement, all improvements sum up. Let's wait for tests from other contributors on different machines. Maybe we find a better default value than the current 1 which works fine on all machines we are testing on.

Same for rcd

**Comment by Beep6581** [comment]
CPU: x86_64 Intel(R) Core(TM) m3-6Y30 https://ark.intel.com/content/www/us/en/ark/products/88198/intel-core-m3-6y30-processor-4m-cache-up-to-2-20-ghz.html
8GB RAM

Tested tiles per thread for raw CA: 1, 2, 4, 8, 16.
10 runs each time, with noting unnecessary running in the background.

The line represents the median:
![chart](https://user-images.githubusercontent.com/5844619/53702630-3bc67380-3e09-11e9-9934-c7178c5763a9.png)

**Comment by heckflosse** [comment]
Changing the scheduling also give a small performance boost for rgbproc(). I will add a commit (for tests) soon.

**Comment by heckflosse** [comment]
To simplify testing I added tiles per thread for some other tiled algorithms:
![grafik](https://user-images.githubusercontent.com/13733487/54075163-4c109f80-429c-11e9-81ca-361a381ca1c2.png)

I also added a 'Measure' checkbox to log timings in console

Edit: also added a helper function to recuce duplicated code in rtgui/preferences.cc....

**Comment by heckflosse** [comment]
Some infos to this branch:

1) I don't intend to get this into 5.6
2) For all tiled processings I tested, the current (dev) default of 1 has the worst processing time.
3) The optimal value highly depends on the machine RT is running on.
4) on my machine the optimal value is 6 except for Amaze where it's 7
5) the optimal value also depends on image size. For example demosaicing a 1920x1080 file using 6 tiles per thread may not be optimal while it may be optimal for a 100MP file.
6) for 5.7 I intend to implement some self-learning mechanism (means after processing for example 100 of my D700 files RT knows the optimal values for this files on my machine)

**Comment by heckflosse** [comment]
Some timings from my AMD FX8350 8-core measured on a Nikon D850 file (always median of 7 measures)

rgb processing using neutral profile

1 tile per thread : 403 ms
6 tiles per thread: 332 ms

amaze demosaic

1 tile per thread : 634 ms
6 tiles per thread: 585 ms

rcd demosaic

1 tile per thread : 573 ms
6 tiles per thread: 495 ms

raw ca correction 2 iterations with avoid color shift enabled

1 tile per thread : 835 ms
6 tiles per thread: 777 ms
