### ISSUE TITLE
New Portuguese (pt) translation

### ISSUE THREAD

**Issue by xendez** [Beep6581/RawTherapee#5210]
Hi,
here it is the Portuguese translation: [Portugues.txt](https://github.com/Beep6581/RawTherapee/files/2953613/Portugues.txt)

Started working on Brazilian Portuguese translation, improved, translated the remaining untranslated strings, compared to the original in English and tested. Can be considered the version used in all Portuguese speaking countries (Portugal, Angola, Mozambique, East-Timor, Cape Verde, São Tomé and Príncipe, Guinea-Bissau and some other regions like Macau, Goa...) except Brazil.

The following strings were removed from the original in Brazilian Portuguese translation since they where not present in [English file](https://github.com/Beep6581/RawTherapee/blob/dev/rtdata/languages/English%20(US)), please confirm if this is correct:
HISTOGRAM_TOOLTIP_FULL;Alternar histograma completo (desligado) ou dimensionado (ligado).
ICCPROFCREATOR_ADD_PARAM_IN_DESC;Anexar os valores gama e declive para a descrição
TP_BWMIX_AUTOCH_TIP;Calcular valores otimizando o misturador de canais.
TP_BWMIX_NEUTRAL_TIP;Repor todos os valores (filtro de cores, misturador de canais) para o padrão.
TP_GAMMA_CURV;Gama
TP_GAMMA_FREE;Gama livre
TP_GAMMA_OUTPUT;Gama de saída
TP_GAMMA_SLOP;Declive (linear)

This file was tested in RawTherapee 5.5
I've encountered other problems and have some suggestions, but it's better to open another ticket.

**Comment by Beep6581** [comment]
Hey @xendez 

There is no "Portugues (Brasil)" in [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes), so please help clarify:
- Is our file titled "Portugues (Brasil)" really in the [Brazilian dialect](https://en.wikipedia.org/wiki/Brazilian_Portuguese)?
- Is your file in "Brazilian Portuguese" or in the proper ISO 639-1 "pt" Portuguese?

**Comment by xendez** [comment]
> 
> 
> Hey @xendez
> 
> There is no "Portugues (Brasil)" in [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes), so please help clarify:
> 
>     * Is our file titled "Portugues (Brasil)" really in the [Brazilian dialect](https://en.wikipedia.org/wiki/Brazilian_Portuguese)?
> 
>     * Is your file in "Brazilian Portuguese" or in the proper ISO 639-1 "pt" Portuguese?

You are correct in both. The file I uploaded is in the proper ISO 639-1 "pt" Portuguese. And the existing file "Portugues (Brasil)" is really in the Brazilian dialect.
The situation is a bit like English USA / UK / and others, but the differences are a bit more that those.

There is no ISO 639-3 code for Brazilian dialect, since it is in fact Portuguese language. And although there are other Portuguese dialects, the difference is not so great except the one used in Brazil. We have only the [IETF](https://en.wikipedia.org/wiki/IETF_language_tag) code for Brazilian Portuguese (pt-br).

Is there any problem using both translations (pt and pt-br) in RawTherapee?

**Comment by Beep6581** [comment]
@xendez thank you. I re-generated your file, maybe you'd like to translate the last few new strings before I commit (they're at the end of the file, and they're are not in English* yet, but they will be in a few days):
https://filebin.net/y1gnao2sx6vdzcyy

**Comment by xendez** [comment]
Here it is.
[Portugues.txt](https://github.com/Beep6581/RawTherapee/files/2954711/Portugues.txt)
