### ISSUE TITLE
Problems and suggestions in RawTherapee interface translation

### ISSUE THREAD

**Issue by xendez** [Beep6581/RawTherapee#5211]
While I was translating to Portuguese (pt) I've found the following problems:

* The following strings are centered on interface, should be aligned to the left like the others:
  * PREFERENCES_PROFILESAVELOCATION;Processing profile saving location.
 Also the other strings in this "block"...
  * TP_RESIZE_METHOD;Method:
  TP_RESIZE_SPECIFY;Specify:
  TP_RESIZE_APPLIESTO;Applies to:
  I think these are 2 "blocks" in the interface, so probably it's not applied to a specific string but a group of them.

* In Preferences > Batch processing > "Add" column is to narrow: is translated to Portuguese as "Adicionar" but I just see "Adiciona" in the UI, probably the column width should be flexible according to the text (thinking in others languages too).

* strings not translatable at this moment, or at least not present in [Original English file](https://github.com/Beep6581/RawTherapee/blob/dev/rtdata/languages/English%20(US)) to translate:
  * Preferences > General > Appearance > Main font click --> "Pick a font", "search font name", "Select" button and "Cancel" button
  * Preferences > General > Appearance > Navigator guide color > click on the color box --> text on dialog to choose the color is not translated: "Pick a color", "Custom", "Select" button and "Cancel" button.
  * Preferences > Image processing > Profiles for standard processing > For raw photos ---> all menus items like "Auto-Matched Curve - ISO Low...". I suspect it's not easy to translate this, but would be great if possible.
  * Preferences > Batch processing > Highlight preservation
  * Batch tab > Queue > "On" and "Off" are not translated
  * change UI to "Single Editor Tab Mode" in Preferences; restart; 2-click on a miniature to edit a photo: in the top right corner I see "Decoding" not translated, but the other messages shown there are translated (for example the strings "PROGRESSBAR_READY;Ready" and "PROGRESSBAR_LOADJPEG;A carregar o ficheiro JPEG..." are translated)
  * in the input field "PREFERENCES_OUTDIRTEMPLATE;Use template" where is shown by default the value "%p1/converted/%f". May be we should be able to translate the word "converted". Of course the user can change that, but could be translated by default.
  * Many messages shown in the progress bar at the bottom of editor window are not translated, for example "CA Auto Correction..." while applying auto correction. Edit: I can't see completely the other messages shown. It's too fast.

* suggestions to change original English strings. Since I don't have experience in RawTherapee I can be wrong (first line is the original in English and the second line is the suggestion):
  * TP_CROP_PPI;PPI=
  TP_CROP_PPI;PPI:
  Change "=" to ":" like in other strings. ~~And why not the more common and probably more correct "DPI:"?~~ Edit: I thought it was Points Per Inch, but it's Pixels Per Inch. My fault.
  * PREFERENCES_MENUOPTIONS;Context Menu Options
  PREFERENCES_MENUOPTIONS;Group the Following Context Menu Options (restart required)
  These options only "group" the menu options, they don't add or remove the options like the current English string suggests, right? And a restart is needed...
  * TP_CROP_SELECTCROP;Select
  TP_CROP_SELECTCROP;Set area
  It's not select in a traditional sense, but a "click+drag+release" action, i.e. set manually, right?
  * FILEBROWSER_BROWSEPATHBUTTONHINT;Click to browse to the chosen path.
  FILEBROWSER_BROWSEPATHBUTTONHINT;Click to browse to the chosen path and Find.
  ...or something similar, since that button also search the file names simultaneously. May be should be "separated" in another button specific to find next to find input filed and before the clear find input field button.
  * MAIN_FRAME_PLACES_DEL;Del
  MAIN_FRAME_PLACES_DEL;Remove
  No need to be abbreviated and it seems "remove" is more clear in this context like a "favorites" list. "Delete" is more common on deleting files from the disk.
  * TP_LENSPROFILE_USE_HEADER;Select distortions to correct:
  TP_LENSPROFILE_USE_HEADER;Distortions to correct:
  Like in others string, everything can be "selected", so there is no need to say "Select". This way is more simple and clear.
  * TP_LENSPROFILE_MODE_HEADER;Select the lens profile:
  TP_LENSPROFILE_MODE_HEADER;Lens profile:
  idem
  * "hot/bad pixels" and "hot/dead pixels" are the same thing? If true, there should be a consistency.

**Comment by Beep6581** [comment]
Thank you for the detailed list @xendez 
I fixed what could be fixed.

> Preferences > General > Appearance > Main font click --> "Pick a font", "search font name", "Select" button and "Cancel" button
Preferences > General > Appearance > Navigator guide color > click on the color box --> text on dialog to choose the color is not translated: "Pick a color", "Custom", "Select" button and "Cancel" button.

These use the language set by the system locale. See #5243
