### ISSUE TITLE
Update Brazilian Portuguese (pt-br) translation

### ISSUE THREAD

**Issue by xendez** [Beep6581/RawTherapee#5212]
[Portugues (Brasil).txt](https://github.com/Beep6581/RawTherapee/files/2954743/Portugues.Brasil.txt)

Here it is the Brazilian Portuguese (pt-br) translation. Note that I'm not a native Brazilian so this should be reviewed one day by a native. But probably my changes are 100% correct or near that. I don't feel comfortable translating long sentences in Brazilian dialect so I left some of them untranslated. I did what I could. The last strings like "PREFERENCES_CHUNKSIZE_RAW" where added and translated too.

To other Brazilian translators (in case you see this): to improve the translation and for a better understanding of the original in English, specially abbreviations like "W - CA"... see the Portuguese (pt) translation as a reference ([Portugues.txt](https://github.com/Beep6581/RawTherapee/files/2954711/Portugues.txt)). I've "decoded" most of them in the translation, since in Portuguese is not very common to used them in this context (but they should be short if possible!). I didn't change that and other strings in this pt-br translation since is better to leave some type of decisions to native speakers.

**Comment by Beep6581** [comment]
> abbreviations like "W - CA" (...) I've "decoded" most of them

@xendez this makes the strings very long, too long to fit into a narrow History column. One solution, which the `default` file may adopt at some point, is to split the string with a newline `\n` between the parent tool's name and the widget's name, as the Deutsch translation currently does.
