### ISSUE TITLE
Diificulties to merge branch "newlocallab" with "dev" - procparams ?

### ISSUE THREAD

**Issue by Desmis** [Beep6581/RawTherapee#5214]
@Floessie 
I tried to merge "newlocallab" with "dev".
I used for that 
git mergetool

I am not able to merge due (I think) to the changes in procparams.
I read #5197
I include for testing
 #include "procparams.h" in "iplocallab.cc"

I change in "improcfun.h" 
const LocallabParams &loc
by
const procparams::LocallabParams &loc

But LocallabParams is ignored

Can you help me.
Thank you

Jacques

**Comment by Floessie** [comment]
@Desmis Jacques, sure. Can you push a new branch with your current merge work, so that I can take a look?

**Comment by Desmis** [comment]
@Floessie 
I just push a new branch "localparam" with my "try"

I changed "manually"
* iplocallab.cc
* improcfun.h
* locallab.cc
* controlspotpanel.cc
* improccoordoinator.cc
* paramsedited.cc

Others files have been merge either "auto", either with "mergetool"

Thank you for your help.

I will be away this afternoon
Jacques

**Comment by Floessie** [comment]
@Desmis Thanks, I'll have a look within the next few days.

**Comment by heckflosse** [comment]
@Desmis @Floessie I'll take a look now

**Comment by heckflosse** [comment]
@Desmis Jacques, I merged and pushed to newlocallab. I hope all works correctly. Please test.

Ingo

**Comment by Floessie** [comment]
@heckflosse Ingo, thanks! :+1: I'm a bit busy ATM...

**Comment by heckflosse** [comment]
@Desmis Jacques, please take a look at this lines:
https://github.com/Beep6581/RawTherapee/blob/newlocallab/rtgui/partialpastedlg.cc#L665

There I used a different solution to get the number of spots. I hope that's correct.

**Comment by Desmis** [comment]
@Floessie 
thanks for taking my request into consideration

@heckflosse 
Ingo, thank you very much, you are always as "Lucky Luke" faster than its shadow
All seems to works fine (to verify!)

I test your change above for "partialpaste"
1) it works fine when, I copy then paste
2) the system crash, when I copy then partial paste "locallab"
It's not my code, but that of @pandagrapher

jacques

**Comment by heckflosse** [comment]
Maybe @Pandagrapher can have a look...

**Comment by Pandagrapher** [comment]
@Desmis 
I won’t be able to have a look at it before this WE. I have just quickly looked at the merge commit. Maybe the crash is due to updates of lines 665 and 667 in partialpastedlg.cc: try replacing `srcPE` by `srcPP`. These lines are for when srcPE doesn’t exist and so that’s why I use `srcPP` instead

**Comment by Desmis** [comment]
@Pandagrapher 
I have tried to replace "srcPE" by "srcPP", but it does not work 

jacques

**Comment by heckflosse** [comment]
@Desmis Jacques, I just pushed a fix

**Comment by Desmis** [comment]
@heckflosse 
Ingo
I just tested. it works fine
Thank you very much

jacques
@Pandagrapher

**Comment by heckflosse** [comment]
@Desmis Ok to close?

**Comment by Desmis** [comment]
@heckflosse 
OK
