### ISSUE TITLE
Weird grainy images when exporting (all file formats) or zooming in

### ISSUE THREAD

**Issue by kenogo** [Beep6581/RawTherapee#5217]
**Version:** 5.5
**OS:** Manjaro Linux (Kernel 4.19.28-1)
[**Link to files**](https://cloud.taxinachtegel.de/s/43RqcE8SEk24e4j)

When I zoom into the picture opened in RawTherapee (no matter if I edited it or not), it becomes very grainy and "colorful" after a certain zoom amount. I don't really know how to describe it. Check out `screenshot-zoomed-in.png` in the provided link to see for yoursellf, There's also a `screenshot-zoomed-out.png` to show that everything looks normal when you zoom out by just a bit. When I export the result to any file format, it keeps this graininess at any zoom level. I've tried multiple image viewers and it shows up in all of them. In the link, I provided a `DSCN0082.edit.jpg` so you can check that out. The raw and pp3 are also available.

I should mention that I took the photos with a Nikon camera which uses the proprietary .NRW file format. However, I used Adobe's DNG converter on a Windows VM to obtain DNG files, and the same process works on my mom's Linux Mint laptop (RawTherapee 4.2.0).

![screenshot-zoomed-in](https://user-images.githubusercontent.com/24212659/54306717-4b447a00-45ca-11e9-9633-6bd931ac5c0f.png)
![screenshot-zoomed-out](https://user-images.githubusercontent.com/24212659/54306729-51d2f180-45ca-11e9-9d6f-0531c4beba70.png)

**Comment by kenogo** [comment]
I just found out my mom's RawTherapee version. I'll try to build that one and check if the problem persists on my machine.

**Comment by heckflosse** [comment]
@kenogo I don't know why it looks good in old RT 4.2, but it's definitely caused by sharpening settings. 
Radius 1.34 in combination with amount 1000 is really strong.

Can you please check the amount value in RT 4.2? Perhaps it's an incompatibility with old .pp3 file.

![grafik](https://user-images.githubusercontent.com/13733487/54308308-0b7f9180-45ce-11e9-9fb6-72c0eef3bcb9.png)

**Comment by kenogo** [comment]
@heckflosse Thanks a lot, I was being dumb, turns out this isn't a bug. I remember having messed around with sharpening but thought I turned it off later, apparently I didn't. I'm very new to photo editing so I don't really know what I'm doing. Thanks again!

**Comment by heckflosse** [comment]
@kenogo You're welcome
