### ISSUE TITLE
Failure to compile spot-removal-tool

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#5232]
Hey @Hombre57 

This is using `5.5-249-g`030ea83af
Using cairomm-1.12.0, GCC-7.3.0.

```
Program name: rawtherapee
Build type: debug
Build without updating: true

-- CMAKE_BUILD_TYPE: debug
-- Configuring done
-- Generating done
-- Build files have been written to: /home/morgan/programs/code-rawtherapee/build-spot-removal-tool-debug
[  0%] Creating AboutThisBuild.txt and other version-dependent files
-- git command found: /usr/bin/git
-- Git checkout information:
--      Commit description:     5.5-249-g030ea83af
--      Branch:                 spot-removal-tool
--      Commit:                 030ea83af
--      Commit date:            2019-03-19
--      Commits since tag:      221
--      Commits since branch:   221
--      Version (unreliable):   5.5.221
-- CACHE_NAME_SUFFIX is "5-dev"
[  0%] Built target UpdateInfo
[  4%] Built target rtexif
[ 42%] Built target rtengine
[ 42%] Building CXX object rtgui/CMakeFiles/rth-cli.dir/main-cli.cc.o
[ 42%] Building CXX object rtgui/CMakeFiles/rth-cli.dir/threadutils.cc.o
[ 43%] Building CXX object rtgui/CMakeFiles/rth-cli.dir/pathutils.cc.o
[ 44%] Building CXX object rtgui/CMakeFiles/rth.dir/thumbbrowserentrybase.cc.o
[ 45%] Building CXX object rtgui/CMakeFiles/rth.dir/spot.cc.o
In file included from /home/morgan/programs/code-rawtherapee/rtgui/toolpanelcoord.h:55:0,
                 from /home/morgan/programs/code-rawtherapee/rtgui/batchtoolpanelcoord.h:23,
                 from /home/morgan/programs/code-rawtherapee/rtgui/filepanel.h:23,
                 from /home/morgan/programs/code-rawtherapee/rtgui/rtwindow.h:22,
                 from /home/morgan/programs/code-rawtherapee/rtgui/main-cli.cc:31:
/home/morgan/programs/code-rawtherapee/rtgui/spot.h:51:5: error: ‘OPIcon’ does not name a type; did you mean ‘GIcon’?
     OPIcon sourceIcon;             // to show the source location
     ^~~~~~
     GIcon
/home/morgan/programs/code-rawtherapee/rtgui/spot.h:52:5: error: ‘Circle’ does not name a type; did you mean ‘nice’?
     Circle sourceCircle;           // to show and change the Source radius
     ^~~~~~
     nice
/home/morgan/programs/code-rawtherapee/rtgui/spot.h:53:5: error: ‘Circle’ does not name a type; did you mean ‘nice’?
     Circle sourceMODisc;           // to change the Source position
     ^~~~~~
     nice
/home/morgan/programs/code-rawtherapee/rtgui/spot.h:54:5: error: ‘Circle’ does not name a type; did you mean ‘nice’?
     Circle targetCircle;           // to show and change the Target radius
     ^~~~~~
     nice
/home/morgan/programs/code-rawtherapee/rtgui/spot.h:55:5: error: ‘Circle’ does not name a type; did you mean ‘nice’?
     Circle targetMODisc;           // to change the Target position
     ^~~~~~
     nice
/home/morgan/programs/code-rawtherapee/rtgui/spot.h:56:5: error: ‘Circle’ does not name a type; did you mean ‘nice’?
     Circle sourceFeatherCircle;    // to show the Feather radius at the Source position
     ^~~~~~
     nice
/home/morgan/programs/code-rawtherapee/rtgui/spot.h:57:5: error: ‘Circle’ does not name a type; did you mean ‘nice’?
     Circle targetFeatherCircle;    // to show the Feather radius at the Target position
     ^~~~~~
     nice
/home/morgan/programs/code-rawtherapee/rtgui/spot.h:58:5: error: ‘Line’ does not name a type; did you mean ‘vint’?
     Line link;                     // to show the link between the Source and Target position
     ^~~~
     vint
/home/morgan/programs/code-rawtherapee/rtgui/spot.h:60:5: error: ‘OPIcon’ does not name a type; did you mean ‘GIcon’?
     OPIcon *getActiveSpotIcon ();
     ^~~~~~
     GIcon
[ 45%] Building CXX object rtgui/CMakeFiles/rth.dir/thumbimageupdater.cc.o
make[2]: *** [rtgui/CMakeFiles/rth-cli.dir/build.make:89: rtgui/CMakeFiles/rth-cli.dir/main-cli.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:243: rtgui/CMakeFiles/rth-cli.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 45%] Building CXX object rtgui/CMakeFiles/rth.dir/thumbnail.cc.o
In file included from /usr/include/cairomm-1.0/cairomm/device.h:24:0,
                 from /usr/include/cairomm-1.0/cairomm/surface.h:39,
                 from /usr/include/gdkmm-3.0/gdkmm/pixbuf.h:39,
                 from /usr/include/gdkmm-3.0/gdkmm/dragcontext.h:30,
                 from /usr/include/gtkmm-3.0/gtkmm.h:90,
                 from /home/morgan/programs/code-rawtherapee/rtgui/spot.h:7,
                 from /home/morgan/programs/code-rawtherapee/rtgui/spot.cc:5:
/usr/include/cairomm-1.0/cairomm/refptr.h: In instantiation of ‘Cairo::RefPtr<T_CppObject>::RefPtr(const Cairo::RefPtr<T_CastFrom>&) [with T_CastFrom = RTSurface; T_CppObject = Cairo::ImageSurface]’:
/home/morgan/programs/code-rawtherapee/rtgui/spot.cc:242:78:   required from here
/usr/include/cairomm-1.0/cairomm/refptr.h:311:32: error: cannot convert ‘RTSurface*’ to ‘Cairo::ImageSurface*’ in initialization
   pCppRefcount_(src.refcount_())
                                ^
/usr/include/cairomm-1.0/cairomm/refptr.h: In instantiation of ‘Cairo::RefPtr<T_CppObject>::RefPtr(const Cairo::RefPtr<T_CastFrom>&) [with T_CastFrom = Cairo::ImageSurface; T_CppObject = RTSurface]’:
/home/morgan/programs/code-rawtherapee/rtgui/spot.cc:247:251:   required from here
/usr/include/cairomm-1.0/cairomm/refptr.h:311:32: error: cannot convert ‘Cairo::ImageSurface*’ to ‘RTSurface*’ in initialization
/usr/include/cairomm-1.0/cairomm/refptr.h: In instantiation of ‘Cairo::RefPtr<T_CppObject>::RefPtr(Cairo::RefPtr<T_CastFrom>&&) [with T_CastFrom = Cairo::ImageSurface; T_CppObject = RTSurface]’:
/home/morgan/programs/code-rawtherapee/rtgui/spot.cc:247:251:   required from here
/usr/include/cairomm-1.0/cairomm/refptr.h:292:35: error: cannot convert ‘Cairo::ImageSurface*’ to ‘RTSurface*’ in initialization
   pCppRefcount_ (src.pCppRefcount_)
                                   ^
make[2]: *** [rtgui/CMakeFiles/rth.dir/build.make:1662: rtgui/CMakeFiles/rth.dir/spot.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:282: rtgui/CMakeFiles/rth.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by Hombre57** [comment]
I had the same problem and it will be solved when my last PR will me merged back into `spot-removal-tool` branch.

**Comment by Floessie** [comment]
But even if I merge in `main-cli-includes` there's still the problem, that `Cairo::ImageSurface` and `RTSurface` are unrelated as far as I can tell...

**Comment by Desmis** [comment]
I had the same problem when I wanted to update "newlocallab"

**Comment by Hombre57** [comment]
@Floessie @Beep6581 I know, it's still WIP. I'll hopefully solve the build problems tonight, but I still have to update `improccoordinator.cc` to make it work.

@Desmis RTSurface is a new class added in the HiDPI branch. It contains a public `Cairo::RefPtr<Cairo::ImageSurface> surface` parameter that you can use.

**Comment by Floessie** [comment]
@Hombre57 
> RTSurface is a new class added in the HiDPI branch. It contains a public Cairo::RefPtr<Cairo::ImageSurface> surface parameter that you can use.

A public member variable makes it hard to change things locally later (e.g. adding a debug message whenever it is accessed) and breaks data encapsulation. If it's not too late, maybe add a simple `const Cairo::RefPtr<Cairo::ImageSurface>& RTSurface::get() const` (but not inline) and make `surface` private. That will help debugging and refactoring.

Best,
Flössie

**Comment by Hombre57** [comment]
@Floessie Done, committed to Dev. Thanks for this hint :+1: 

Now back to fix the build crash...

**Comment by Hombre57** [comment]
Build crash fixed. Patch committed to close this issue, however RT still crash when using this tool. (WIP)

**Comment by Floessie** [comment]
@Hombre57 Would you mind if I streamline `RTSurface` a bit? My proposal wasn't completely const-correct and parameter passing in that class isn't optimal. While poking around with the header I found out that a change results in a recompilation of most of `rtengine` (which wasn't expected). It's because of the `rtgui/edit.h` inclusion in `rtengine/pipettebuffer.h` which can be omitted.

Shall I start a cleanup branch or do you feel uncomfortable with me turning your code inside out? I'm not offended if it's the latter. :smile: Maybe it's too early for the cleanup and you want to finish the spot removal tool first...

Best,
Flössie

**Comment by Beep6581** [comment]
Compilation fix confirmed.

**Comment by Hombre57** [comment]
@Floessie I'll wait for your commit, no problem. Then I'll split `edit.h` in 2 or 3 includes to avoid rebuilding everything once I touche this header file, then I'll continue with fixing this tool.

I'm not comfortable AT ALL with the `const`, `explicite` stuff (or technique you posted recently), so don't hesitate to post a patch in the issue or contact me if you want to push a commit directly in my branch, since my code will be suboptimal in this matter (at least).

**Comment by Hombre57** [comment]
@Floessie 

PS: If your change is valid for dev too, maybe it would be better to commit it there, I'll merge it back (we don't know when `spot-removal-tool` will be merged... :roll_eyes: ).

**Comment by Floessie** [comment]
@Hombre57 Yes, I'll branch off from `dev`. No need to wait for my branch. It won't be merged to `dev` before the 5.6 release, so I'm in no hurry. :slightly_smiling_face: Thanks for your work with the GUI! `spot-removal-tool` will be great!

**Comment by Floessie** [comment]
@Hombre57 I've started a new branch called [`rtsurface-cleanup`](https://github.com/Beep6581/RawTherapee/tree/rtsurface-cleanup). While working on it I think I've found a bug in [`RTSurface::updateImages()`](https://github.com/Beep6581/RawTherapee/blob/d059caa7de9b923feb5a2e00c62970d519420442/rtgui/rtsurface.cc#L120): Shouldn't that be `auto&` so that the entry gets updated? If so, please fix this in `dev` as it might be important for 5.6.

Thanks,
Flössie

**Comment by Hombre57** [comment]
@Floessie Well :sweat_smile: , I didn't managed to get the auto-updated feature to work at all, thanks for having found the solution :1st_place_medal: . I'll test that (but I guess you already did) and commit.

**Comment by Floessie** [comment]
@Hombre57 
> I'll test that (but I guess you already did) and commit.

I hope this is really the fix. If you tell me how this function is most easily triggered I can test under Linux...
