### ISSUE TITLE
Panasonic Lumix S1 correction of blown highlights produces nasty pink

### ISSUE THREAD

**Issue by CharlesRT2** [Beep6581/RawTherapee#5234]
I downloaded the raw file from this page
https://www.dpreview.com/sample-galleries/9191191786/panasonic-lumix-s1-sample-gallery/6514852574

When I correct for the blown highlights, the blown areas - in their entirety, not partial subregions - turn a nasty pink, instead of a dull gray for example. It happens whether I reduce exposure, use Highlight Compression, or apply Dynamic Range Compression.

The problem is not limited to this camera. Whether by coincidence or not, I noticed the problem after updating to version 5.5.

It looks like something from chromatic aberration, but I do not see where that may be the culprit. No lens profile is involved. The .pp3 file attached.

[PanasonicS1_sample1.dng.pp3.txt](https://github.com/Beep6581/RawTherapee/files/2986502/PanasonicS1_sample1.dng.pp3.txt)

**Comment by TooWaBoo** [comment]
Downloaded the RAW from the link above and I got this with latest dev. 🤔

![grafik](https://user-images.githubusercontent.com/13800920/54673597-dce84600-4afa-11e9-9823-870288246185.png)

**Comment by Beep6581** [comment]
Confirmed in `5.5-243-g`d059caa7d as well as in 5.5
![screenshot_20190320_103537](https://user-images.githubusercontent.com/5844619/54674071-f342d180-4afb-11e9-81e3-a0cb68fd5933.png)

So I wonder which program @CharlesRT2 was using? :)

**Comment by agriggio** [comment]
I suspect an intermediate dng conversion (looking at the pp3 name)

**Comment by Beep6581** [comment]
And the latest Adobe DNG Converter 11.1 does not support those raw files yet.

**Comment by CharlesRT2** [comment]
There is a public beta version of Adobe DNG Converter that supports conversion of the Panasonic S1 .rw2 files to .dng. I used that and opened the .dng in RT.

But as I mentioned, the problem occurs on other cameras. 
![pinkscreenshot](https://user-images.githubusercontent.com/16884929/54703800-baecc480-4af6-11e9-85d3-680d2d97819b.jpg)
Here is the raw file from another camera, which uses .dng as its native raw file format, along with a simple .pp3. 
https://filebin.net/c40hs2fitryhhgqh

Attempts to tame blown highlights make a nasty pink.

And you might want to revise the revised title of the thread.

**Comment by TooWaBoo** [comment]
@CharlesRT2 
Check `Highlight recontruction` and the pink cast should be gone.

**Comment by CharlesRT2** [comment]
> 
> @CharlesRT2
> Check `Highlight reconstruction` and the pink cast should be gone.

Thank you, that's my user error. I will say, I had tried the new Dynamic Range Compression, and for this feeble user, the dialog is too far down from the Highlight Reconstruction checkbox.
