### ISSUE TITLE
File Browser filename tooltips no longer shown

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#5235]
Filename tooltips mostly no longer work when hovering over thumbnails in the File Browser, neither in dev head nor in 5.5. Out of over 50 attempts, a tooltip appeared only about 5 times, and not reproducibly.

Tested in Linux using gtk+-3.24.1. Maybe a GTK+ issue?

**Comment by Floessie** [comment]
Debian 10, GTK 3.24.5: Tooltips appear reliably, but if a tooltip appears it will stay in that position even when you hover over another image. The text is updated, though.

**Comment by Floessie** [comment]
Same setup. 5.3, 5.4: No thumbnails at all. 5.5: Same as `dev`.

**Comment by heckflosse** [comment]
On Win7/64: As @Floessie wrote in his first comment.

**Comment by Floessie** [comment]
Debian 9, GTK 3.22.11: Same as on Debian 10.

**Comment by okoncevoy** [comment]
Same on OSX
```
Version: 5.5-243-gd059caa7d
Branch: dev
Commit: d059caa7d
Commit date: 2019-03-19
Compiler: clang-mp-7 7.0.1
Processor: i386
System: Apple
Bit depth: 64 bits
Gtkmm: V3.22.3
Lensfun: V0.3.2.0
Build type: Debug
Build flags:  -std=c++11  -Werror=unused-label -mmacosx-version-min=10.9 -Wall -Wuninitialized -Wno-deprecated-declarations -Wno-unused-result -fopenmp=libomp -Werror=unknown-pragmas -g -ftree-vectorize
Link flags:   -headerpad_max_install_names
OpenMP support: ON
MMAP support: ON
```

**Comment by Beep6581** [comment]
Can no longer reproduce using 
`5.7-262-g`164fab28e
gtkmm-2.24.5
gtk+-3.24.11
