### ISSUE TITLE
Adding clarity filter from waveletnew branch into dev

### ISSUE THREAD

**Issue by sguyader** [Beep6581/RawTherapee#5241]
I tried the clarity filter (and also the unsharp mask) from waveletnew, but I don't know whether this branch will ever get merged into dev.
This issue is to request for merging part of it (clarity/unsharp mask) into dev, if possible.
Results of the use of the clarity are very nice, as I try to show here: https://discuss.pixls.us/t/trying-to-emulate-adobes-clarity-in-rawtherapee/11844

**Comment by Desmis** [comment]
@sguyader 
I just commit a new branch "wavelenh".

Thank you for your comparison work :)

Wavelenh = wavelet original + "clarity - sharp mask" (from waveletnew) + soft radius

Easy to produce "wavelenh", the most work is for GUI....

I add 2 sliders  to soft result for wavelet: 
1) Soft radius to down "relief - prespective effects", in Clarity...
2) another Soft radius, in Final Touchup, with the same goal

Jacques

**Comment by sguyader** [comment]
@Desmis 
I tried the "wavelenh" branch, overall it seems to work fine. There's a very slight difference, all settings equal, to what we can get from the "waveletnew" branch, but it's minimal.
Two things that look strange to me in "clarity":
1. When the TP_WAVELET_SOFTRAD slider is increased from 0.0 to 0.1, there's a huge difference
2. When I check the TP_WAVELET_SHOWMASK box, it turns the "clarity" filter off, and shows just a blurred image (I was expecting some sort of grey or yellow mask)

**Comment by Desmis** [comment]
@sguyader
for 1. it is "normal", I can try to minimize, but if the function Guidefilter is actived, its has always an action.

for 2. in wavelet the mask are not as in "unsharp mask"
This mask are the image of the wavelet with the settings "predifined" by "Clarity" - in this cases this correspond to level > 7 (except if you change) and residual image
for sharp mask, it is the same things "black background" and level < 3...of course except if you change
 
When you choose "Sharp mask and Clarity"...looks at Wavelet settings
if you select "Clarity"
background = Residual
Process : above the level
Level 7 - all directions
You can change 7
When you select show mask you see settings above

if you select "Sharp mask"
background = Black
Process : below or equal the level
Level 3 - all directions
You can change 3
When you select show mask you see settings above

**Comment by sguyader** [comment]
@Desmis ok I understand. So everything seems running fine for clarity. I haven't tried the unsharp mask yet.

**Comment by Desmis** [comment]
@sguyader 

In fact it is not an "unshap mask", but a "sharp mask"...
I combined 2 wavelet decomposition, with different coefficient (different for Clarity and Sharp mask)

**Comment by sguyader** [comment]
Jacques, yes sorry it's bad habit, I'll be be more careful with my vocabulary 😉

**Comment by Desmis** [comment]
Sébastien, no problem at all :)

I just change sensitivity for "Soft radius"...with a new commit
Say me if it's better

Thank you

**Comment by Desmis** [comment]
@sguyader 
Another changes  for Soft radius, and Label "show mask", in last commit

jacques

**Comment by sguyader** [comment]
@Desmis 
Jacques I tested the last commit. Everything works and looks fine.
Though, I find the effect of "Soft radius" very subtle, it's not easy to really see what it does. I end up leaving it at 0.
Also, I don't really understand how to use the "Show wavelet mask" feature. How can I interpret what it shows?

In French for Jacques (to make it clearer):
Jacques, tout semble bien fonctionner.
Par contre, je trouve que l'effet de "Soft radius" est vraiment subtile, peut-être trop subtile ? Je ne vois pas trop ce que ça fait à l'image, du coup je le laisse à 0 (en fait à 0 ça préserve un peu mieux les détails en basses lumières j'ai l'impression, et c'est un peu ce qu'on veut dans l'effet "clarity").
Aussi, je ne comprends pas trop ce que fait "Show wavelet mask". Comment interpréter ce que ça montre ?

**Comment by Desmis** [comment]
En fait cela montre la decomposition en ondelette qui sera «assemblée» avec
l'image originale.
Soft radius comme son nom l'indique reduit les differences les plus
marquées entre l'image originale et l'image modifiée. C'est affaire de
goût, moi j'aime bien des valeurs faibles 2 à 5.
Jacques

Le lun. 25 mars 2019 13:53, Sébastien Guyader <notifications@github.com> a
écrit :

**Comment by Desmis** [comment]
Pour aller plus loin. Lorsque «show» est activé. Va dans Settings et change
le level ( 7 par défaut). Bien sûr il faut que la taille de l'image dans le
preview le permet.. Essaye avec 5 ou 6 - ou avec 8 ou 9 (si possible)
Soft radius est utile si on utilise des levels élevés et des coefficient
merge élevés.
Jacqued

**Comment by Desmis** [comment]
@sguyader 
Je ne sais pas si c'est la bonne appellation "Show wavelet mask". Si on utilise "sharp mask" cela ressemble un peu à un masque.
Par contre si on utilise Clarity, on a une image plus ou moins floue.

Il faut comprendre et imaginer l'image en 3 dimensions, alors que nos habitudes sont à 2 dimensions (longueur - largeur - taille des pixels).
Avec les ondelettes on décompose l'image comme une pyramide. L'utilisateur choisit le nombre de niveaux de décomposition (par défaut 7).
Chaque niveau contient seulement les éléments qui ont des "écarts" avec leurs voisins
* le niveau 1 contient les informations des zones qui correspondent à un contraste d'une zone de 2 pixels * 2 pixels (+1 -1 pour X -- +1 - 1 pour Y)
* ...
* le niveau 7 contient les informations des zones qui correspondent à un contraste d'une zone de 128 pixels * 128 pixels (+64 -64 pour X -- +64 - 64 pour Y)
* etc.
L'image résiduelle contient le "reste"
Si par exemple on a une image uniformément "plate" - uniforme", il n'y aura pour chaque niveau aucune information, et l'image résiduelle correspondra à l'image originale

Quand on utilise "Clarity", on assemble avec les coefficients de "merge" les composantes "L" (luminance) et "ab" (pour la couleur)...en fait c'est un peu plus complexe...
1) l'image complète  en par exemple 8 niveaux et l'image résiduelle (avec ses traitements wavelet...)
2) une partie de l'image que tu vois dans "masque" aux niveaux supérieurs à 7, donc ici 7 et 8 et l'image résiduelle (avec les traitements wavelet, mais bien sûr pas ceux des niveaux inférieurs à 7).
Donc dans la fusion on "oublie" les 6 premiers niveaux....
Ce sont eux par leur absence qui vont créer l'effet "Clarity", mais aussi l'impression de relief, d'où "Soft radius" pour atténuer l'effet.

Quand on utilise "sharp mask" l'assemblage est différent
1) l'image complète en par exemple 8 niveaux et l'image résiduelle
2) une partie de l'image que tu vois dans "masque" aux niveaux inférieurs à 3 , donc ici 3, 2 et 1. Mais il faut un fond noir pour ne pas ajouter une couleur à la fusion.
Donc ici on oublie les niveaux supérieurs à 3 et l'image résiduelle.
C'est l'ajout des 3 premiers niveaux qui va créer l'effet"sharp"

Est-ce plus clair ?
Si cela te semble utile peux-tu traduire ?

**Comment by Desmis** [comment]
@sguyader 
Pour continuer l'explication
Si on divise "merge Luma" et "merge chroma" pat 100, on obtient une valeur comprise entre -0.5 et 1.0
merge luma = mL
merge chroma = mC

Si j'appelle
orig ==> image original non traitée wavelet
origwav ==> image original traitée wavelet
mask ==>  partie de l'image traitée wavelet
origfinal ==> image traitée finale avec traitement wavelet + "Sharp mask and clarity"

Dans le cas de "Clarity"
origfinal L = (1 + mL) * origwav L - mL * mask L
origfinal a = (1 + mC) * origwav a - mC * mask a
origfinal b = (1 + mC) * origwav b - mC * mask b

Dans le cas de "Sharp mask"
origfinal L = origwav L  +  mL * mask L
origfinal a = origwav a  +  mC * mask a
origfinal b = origwav b +  mC * mask b

Ensuite on applique uniquement sur la luminance, GuideFilter (Soft  radius), sur l'écart "Tosoft" entre
Tosoft = origfinal L - orig

jacques

**Comment by sguyader** [comment]
@Desmis  Jacques, je pense avoir compris dans les grandes lignes. Pour "clarity" et "sharp mask", c'est un peu comme si on dupliquait les couches des niveaux supérieurs à 6, et inférieur à 4, respectivement, et qu'on qu'on les ajoutait à l'image traitée par ondelettes. Est-ce à peu près ça ?

Je me pose des questions quant à l'utilité du bouton "Show mask" pour "sharp mask", car certes on visualise une sorte de masque, mais on n'a aucun contrôle sur l'effet. Autant pour "clarity", si "show mask" est activé on peut faire varier le nombres de niveux dans "wavelet levels" et voir directement l'effet que ça a sur le "masque", autant pour "sharp mask" on ne peut jouer sur rien car le curseur "merge lumùa" n'a pas d'effet en mode "show mask".

**Comment by Desmis** [comment]
@sguyader 
Pour la première partie c'est un peu cela...

Les fonctionnalités de "showmask" avec "Clarity" et "Sharp mask" sont identiques, les 2 curseurs "Merge Luma" et "Merge chroma" sont sans action, car ils interviennent "après", avec un rôle de "blender".

Par contre pour l'un comme pour l'autre, on peut changer les niveaux de décomposition
* plus ou moins par rapport à 7 pour Clarity
* plus ou moins par rapport à 3 pour Sharp Mask
Attention, les réglages "pour voir" dans Show Mask sont oubliés (trop complexe à gérer), car en fait on gère 2 process qui se cumulent. Donc si on teste par exemple le "masque" avec "Show mask" et qu'on choisit une valeur différente de celle par défaut, si tu veux effectivement avoir cet effet, il est nécessaire de le faire en mode "sans show mask"

Tes commentaires m'amènent une remarque que j'ai déjà faite pour "locallab", l'apport d'outils - méthodes qui sortent du cas "habituel" (à la Photoshop...), obligent à un dés-apprentissage  cognitif, pour apprendre autre chose....

Merci pour tes essais et commentaires

Jacques

**Comment by sguyader** [comment]
Jacques, ce que je voulais dire c'est qu'en fait avec "clarity" actif, si on joue sur "wavelet levels" on voit une différence car on peut sélectioner + ou - que 7 niveaux, ce qui est la valeur seuil pour "clarity". En revanche pour "sharp mask" qui a une valeur seuil au niveau 3, on ne peut pas voir l'effet de "wavelet levels" car le niveau minimum est 4. Mais c'était avant que je comprenne le fonctionnement, mon idée est nulle et non avenue.
C'est en jouant avec "Process below or equal level" que l'on peut voir l'effet, y-compris sur le "sow mask". Le seul soucis c'est que quand on active/désactive "show mask", par defaut ça se remet sur "Process below or equal level=3" pour "sharp mask". Ca n'est pas bien grave, c'est juste que si en visualisant le masque on trouve que mettre la valeur seuil à 2 correspond à ce que l'on, quand on désactive le masque le niveau seuil est automatiquement remis à 3, il faut donc penser à le remettre à 2 manuellement. Mais je suppose que c'est inévitable, car si tu ne mets cette fonction automatique par défaut, ça risque d'apporter plus de problèmes  quand on veut activer "clarity" ou "sharp mask" la première fois et qu'on est nouvel utilisateur de la fonction.

**Comment by sguyader** [comment]
Anyway, I think this branch is working fine, and I'd like very much for it to be merged into dev.

**Comment by Desmis** [comment]
@sguyader 
Thank you for testing :)

Is there an opposition to merge this branch in dev ?

In this case (no opposition), I will do that "tuesday" when I come back from Paris

jacques

**Comment by Beep6581** [comment]
@Desmis please do not merge, we are in 5.6 feature-freeze. This needs further testing, optimization and review, and then when ready it can be merged for 5.7.

**Comment by heckflosse** [comment]
@Desmis Jacques, I agree with @Beep6581

**Comment by Beep6581** [comment]
Review of branch `wavelenh` `5.5-274-g`e8847a663
* The preview matches the saved image quite well.
* The effect can be very pleasing (samples at the end).
* "Sharp-mask and Clarity" seems to have no effect when method=none, so there is no need to have a "none" option since the sub-tool can be turned off.
* Issue 1:
1. Open photo, enable Wavelets.
1. Enable "Sharp-mask and Clarity".
1. Tick "Show wavelet 'mask'". The progress bar appears but nothing happens.
1. Set method to anything other than "none". Still no mask visible.
1. Un-tick "Show wavelet 'mask'". The progress bar moves but nothing happens.
1. Tick "Show wavelet 'mask'" again. Now the mask is visible, but the "Sharp-mask and Clarity" sub-tool turns off! A checkbox inside a (sub-)tool cannot have an effect on the tool if it's disabled.
1. Un-tick "Show wavelet 'mask'", now the sub-tool is turned back on! Nothing else changes in Wavelet Settings.
* Issue 2:
1. Open photo, enable Wavelets.
1. Enable "Sharp-mask and Clarity".
1. Set method to anything other than "none".
1. Disable "Sharp-mask and Clarity". The preview turns gray for a short moment.
* Issue 3: changing the method updates the preview first back to the "none" state, then to the new method.
* Double-decimal precision for "soft radius" seems unnecessary, in my tests 0-100 was enough.

And a sample I found very pleasing:
http://rawtherapee.com/shared/test_images/blue_horse.nef
None:
![blue_horse none](https://user-images.githubusercontent.com/5844619/55392953-92c08500-553c-11e9-890d-392dca8e748a.jpg)
[blue_horse none.jpg.out.pp3.txt](https://github.com/Beep6581/RawTherapee/files/3033293/blue_horse.none.jpg.out.pp3.txt)
Sharp mask:
![blue_horse sharp_mask](https://user-images.githubusercontent.com/5844619/55392985-a1a73780-553c-11e9-864c-711c6ca8c17e.jpg)
[blue_horse sharp_mask.jpg.out.pp3.txt](https://github.com/Beep6581/RawTherapee/files/3033295/blue_horse.sharp_mask.jpg.out.pp3.txt)
Clarity:
![blue_horse clarity](https://user-images.githubusercontent.com/5844619/55392999-a835af00-553c-11e9-9019-91e885f391fb.jpg)
[blue_horse clarity.jpg.out.pp3.txt](https://github.com/Beep6581/RawTherapee/files/3033296/blue_horse.clarity.jpg.out.pp3.txt)

**Comment by Desmis** [comment]
@Beep6581 
Thank you for testing

The main problem is to undrestand how it works, it is explain in French above
In resumed we combined 2 process "wavelet", and there are effectively 2 calls...

For issue 2 = normal, its the time needs by RT to change between process 1, and procees 2

For the others cases, it is very difficult to manage "mask" because you have 2 process.

 I added this feature - compared to waveletnew (Sharp mask and Clarity was tested 3 or 4 years ago) - to improve understanding but your remarks as well as those of @sguyader show the opposite, this only adds to the misunderstanding.

Moreover the display of the mask is difficult to manage because of the 2 processes.

My proposal is to remove this possibility which creates more problems than it solves

In some cases, with "big" values (level > 7) , merge luma > 80, and with some images, double precision brings more progressiveness

**Comment by heckflosse** [comment]
@Desmis 

>For issue 2 = normal, its the time needs by RT to change between process 1, and procees 2

Can you point me to the code where that happens?

**Comment by Desmis** [comment]
I push a commit
* disabled "Showmask" which creates more problems than it solves
* change method to only 2 choice "clarity" and "sharp-mask"
* change precision "soft radius" from 0.01 to 0.1

@heckflosse 
Ingo the parts of code are in
* improccoordinator.cc lines 873 to 885 ==> there is 2 calls to ip_wavelet
* dcrop.cc lines 1009 to 1021 ==> there is 2 calls to ip_wavelet

jacques

And I found some links where we speak of "Clarity" in wavelet years ago

https://discuss.pixls.us/t/bring-on-the-sharp-mask-and-clarity-wavelet-tool/4568

https://discuss.pixls.us/t/how-does-one-emulate-the-lrs-clarity-slider-in-rt/1109

https://github.com/Beep6581/RawTherapee/issues/2982

**Comment by Desmis** [comment]
I push some changes

Better work with "Soft radius"
Take into account general settings in algorithm clarity

Improvments to "residual" image - contrast, compression,...

**Comment by Desmis** [comment]
I push others changes, all in "Residual image"

* improve tone-mapping 
* improve contrast
* improve shadowsHighlight

jacques

**Comment by Thanatomanic** [comment]
Since the `wavelenh` does not exist anymore, this issue can be closed.
