### ISSUE TITLE
`DateTimeOriginal` not found in Leica DNG

### ISSUE THREAD

**Issue by Floessie** [Beep6581/RawTherapee#5251]
Hi fellows,

Over at PIXLS we have a [report](https://discuss.pixls.us/t/no-date-time-taken-shown-for-leica-m8-dng-files-in-file-browser/11905) about missing date information when decoding a Leica DNG.

I compared the file in the Geeqie EXIF window to a working image and found out that the DNG's `DateTimeOriginal` (0x9003) resides in `Exif.Image` while the working one has it in `Exif.Photo` (whatever that means). I added an `exif->printAll()` [here](https://github.com/Beep6581/RawTherapee/blob/68ba87a71ff670b08e2db0d5b887517f41d3d9b7/rtengine/imagedata.cc#L263) et voilà: we only decode the `Exif.Photo` tags.

Basically I see two options:
1. Fallback to `DateTimeDigitized`:
```patch
diff --git a/rtengine/imagedata.cc b/rtengine/imagedata.cc
index 4dcfe80ff..6d924d9a4 100644
--- a/rtengine/imagedata.cc
+++ b/rtengine/imagedata.cc
@@ -260,7 +260,7 @@ FrameData::FrameData (rtexif::TagDirectory* frameRootDir_, rtexif::TagDirectory*
             iso_speed = tag->toDouble ();
         }
 
-        if ((tag = exif->getTag ("DateTimeOriginal"))) {
+        if ((tag = exif->getTag("DateTimeOriginal")) || (tag = exif->getTag("DateTimeDigitized"))) {
             if (sscanf ((const char*)tag->getValue(), "%d:%d:%d %d:%d:%d", &time.tm_year, &time.tm_mon, &time.tm_mday, &time.tm_hour, &time.tm_min, &time.tm_sec) == 6) {
                 time.tm_year -= 1900;
                 time.tm_mon -= 1;
```
2. Search the tree recursively for `DateTimeOriginal`:
```patch
diff --git a/rtengine/imagedata.cc b/rtengine/imagedata.cc
index 4dcfe80ff..e2402a62d 100644
--- a/rtengine/imagedata.cc
+++ b/rtengine/imagedata.cc
@@ -260,7 +260,7 @@ FrameData::FrameData (rtexif::TagDirectory* frameRootDir_, rtexif::TagDirectory*
             iso_speed = tag->toDouble ();
         }
 
-        if ((tag = exif->getTag ("DateTimeOriginal"))) {
+        if ((tag = exif->findTag("DateTimeOriginal", true))) {
             if (sscanf ((const char*)tag->getValue(), "%d:%d:%d %d:%d:%d", &time.tm_year, &time.tm_mon, &time.tm_mday, &time.tm_hour, &time.tm_min, &time.tm_sec) == 6) {
                 time.tm_year -= 1900;
                 time.tm_mon -= 1;
```

Both changes fix the problem, so pick one of the them or come up with another. :wink: 

Best,
Flössie

**Comment by Beep6581** [comment]
Looks like `photo` and `image` are just discrete groups of tags, and `DateTimeDigitized` and `DateTimeOriginal` should be in the same group - `ExifIFD`.

http://www.cipa.jp/std/documents/e/DC-008-2012_E.pdf

https://www.sno.phy.queensu.ca/~phil/exiftool/TagNames/EXIF.html
> The EXIF meta information is organized into different Image File Directories (IFD's) within an image. The names of these IFD's correspond to the ExifTool family 1 group names. When writing EXIF information, the default Group listed below is used unless another group is specified.

So the Leica M8 isn't sticking to the spec.

I would go for the second option - search for `DateTimeOriginal`, for consistency's sake. The spec is not very clear on the real-world difference between `DateTimeOriginal` vs `DateTimeDigitized` so I assume the possibility that the two could differ even in digital still cameras ("DSC") .

**Comment by Floessie** [comment]
@Beep6581 I'm not able to push before Sunday evening. Feel free to commit.
