### ISSUE TITLE
Slim down locallab pp3 files

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#5255]
As the newlocallab branch currenty makes some progress driven by more than one contributor, I suggest the following:

For each locallab spot only save the settings to pp3 file which are not at default value.

What dou you think?

I can take care about that in case there's no objection.

Ingo

**Comment by Pandagrapher** [comment]
@heckflosse 
That will be a different behavior compared to other RT tools, no?. Other idea: to reduce Locallab parameters length in pp3, only save parameters for activated Locallab tools

Pierre

**Comment by Desmis** [comment]
@heckflosse 
Ingo
Sure, it will be a  nice improvment.
An yes, you can :)

jacques

**Comment by Pandagrapher** [comment]
.pp3 file size has been reduced by only saving added tools for each spot. This improvement is included in the content which has been merge into `dev`. So this issue can be now closed.
