### ISSUE TITLE
Spot locallab overflowing since new spot delimiters or perhaps new installation Msys2 ?

### ISSUE THREAD

**Issue by Desmis** [Beep6581/RawTherapee#5263]
This morning I have had a crash of my computer, then MSYS2 is broken

I desinstall old Msys2
I reinstall MSY2 with process discribe in "Rawpedia"

I downgrade 
mingw-w64-x86_64-lensfun-0.3.2-4-any.pkg.tar.xz
mingw-w64-x86_64-libjpeg-turbo-1.5.3-1-any.pkg.tar.xz

Then I make cmake
and I have the message 
you are using GTK-3.24.5 please dowgrade to gtk-3.24.1

I download : mingw-w64-x86_64-gtk3-3.24.1-1-any.pkg.tar.xz in /g/msys/
then I update by
pacman -U /g/msys/mingw-w64-gtk3-3.24.1-1-any.pkg.tar.xz
Msys2 says me lib is installed

But when I run cmake, systems seems to ignore this gtk-3.24-1 and cmake says  I have always 3.24.5

All compile fine, no problem
when I run, no problem, except with "Locallab spot"

As you can see, action is overflowing spot 
![overflowspot](https://user-images.githubusercontent.com/13764697/55547078-d6e48e80-56d0-11e9-86d0-432e5d48687f.jpg)

what I missed ?

**Comment by Desmis** [comment]
here file aboutthisbuild.txt

Version: 5.5-922-g6a23c48f1
Branch: newlocallab
Commit: 6a23c48f1
Commit date: 2019-04-04
Compiler: gcc 8.3.0
Processor: undefined
System: Windows
Bit depth: 64 bits
Gtkmm: V3.24.0
Lensfun: V0.3.2.0
Build type: release
Build flags:  -std=c++11 -march=native -Werror=unused-label -Wall -Wuninitialized -Wno-deprecated-declarations -Wno-unused-result -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON

**Comment by Desmis** [comment]
@pandagrapher
It seems it is not MSYS2 that leads to bad behavior

I just compile, a repo, which is not updated with the new spots (new elipse...)
And in this case - with the "old" spot, there is no overflow

Donc en français, je pense que le dernier "commit" et "pull request" amène une anomalie dans la nouvelle taille du spot a) prise en compte par iplocallab.cc et affichée par controlspotpanel.cc et locallab.cc

jacques

**Comment by Desmis** [comment]
@pandagrapher
Here 2 images of the same action
1) with "old" spot
![notoverflow](https://user-images.githubusercontent.com/13764697/55551647-9e967d80-56db-11e9-96e5-7867e47e912b.jpg)

2) new spot
![overflowwithnewspot](https://user-images.githubusercontent.com/13764697/55551667-a9511280-56db-11e9-89ac-653dea2f92b8.jpg)

**Comment by Pandagrapher** [comment]
@Desmis 
Ouppppssss my fault. Here a patch which corrects the bug :
```diff
diff --git a/rtgui/controlspotpanel.cc b/rtgui/controlspotpanel.cc
index 9b8e618..0fecf9b 100644
--- a/rtgui/controlspotpanel.cc
+++ b/rtgui/controlspotpanel.cc
@@ -1130,11 +1130,11 @@
     const int shape_ = row[spots_.shape];
     const bool isvisible_ = row[spots_.isvisible];
 
-    const int decayX = locX_ * (imW / 2000);
-    const int decayXL = locXL_ * (imW / 2000);
-    const int decayY = locY_ * (imH / 2000);
-    const int decayYT = locYT_ * (imH / 2000);
-    const rtengine::Coord origin(imW / 2 + centerX_ * imW / 2000, imH / 2 + centerY_ * imH / 2000);
+    const int decayX = (double)locX_ * (double)imW / 2000.;
+    const int decayXL = (double)locXL_ * (double)imW / 2000.;
+    const int decayY = (double)locY_ * (double)imH / 2000.;
+    const int decayYT = (double)locYT_ * (double)imH / 2000.;
+    const rtengine::Coord origin((double)imW / 2. + (double)centerX_ * (double)imW / 2000., (double)imH / 2. + (double)centerY_ * (double)imH / 2000.);
 
     const auto updateSelectionCircle = [&](Geometry * geometry, const int offsetX, const int offsetY) {
         const auto cir = static_cast<Circle*>(geometry);
```

Pierre

**Comment by Desmis** [comment]
@Pandagrapher 
This fix the bug.
I will push directly the change to "Beep6581-newlocallab"

Merci

Jacques

**Comment by heckflosse** [comment]
@Desmis As I merged meanwhile, shall I push the fix?

**Comment by Desmis** [comment]
@heckflosse 
Now you can, I just push the fix from @Pandagrapher 

jacques

**Comment by heckflosse** [comment]
I already did ;-)

**Comment by Desmis** [comment]
Ok, thank you :)

jacques

**Comment by heckflosse** [comment]
Fix confirmed. Ok to close?

**Comment by Desmis** [comment]
Ok
