### ISSUE TITLE
locallab: dialog to rename a spot has no default button

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#5266]
When renaming a locallab spot I would like the ok button to be the default button of the rename dialog, so I can just press enter to commit the new name.
![grafik](https://user-images.githubusercontent.com/13733487/55581549-70399200-571d-11e9-9670-8cfb3255eae1.png)

**Comment by Pandagrapher** [comment]
@heckflosse @Desmis 
I have fixed this issue with commit `152d8c3`
Pierre

**Comment by Desmis** [comment]
Ok thank you :)

jacques

**Comment by Pandagrapher** [comment]
@heckflosse 
Is it ok to close this issue?
Pierre

**Comment by heckflosse** [comment]
@Pandagrapher Works fine, closing. Thanks for the fix :+1:
