### ISSUE TITLE
ProcEvent int() operator should be const

### ISSUE THREAD

**Issue by fortiernor** [Beep6581/RawTherapee#5267]
I am writing some tests to explore RT and hopefully contribute by making history incorporate changes made in prior sessions. I have a lot of experience in Java but little in C++, so my understanding may be at fault here.
I need to obtain the code of some ProcEvents to ensure they are the correct instances. If I try to print out a ProcEvent code I would do this:
```std::to_string(getEvent())```
where getEvent() returns a ProcEvent. However I then get this error in compile:
```error: passing 'const rtengine::ProcEvent' as 'this' argument discards qualifiers [-fpermissive]```
QtCreator IDE message is clearer to me:
```error: no matching function for call to to_string()```
```note: candidate function not viable: no known conversion from 'const  rtengine::ProcEvent' to int for 1st argument```

However if I modify the declaration / definition of ProcEvent operator int() from
```operator int() { return code_; }```
to
```operator int() const { return code_; }```
(ProcEvents.h, l.535, in current dev) then my code compiles without error or warning.
In Stroustrup's A Tour of C++, p. 49, he uses const in a similar way when he defines conversion operators for his complex class.

This is Archlinux 5.0.4-arch1-1-ARCH #1 SMP PREEMPT, gcc version 8.2.1 20181127 (GCC), QtCreator 4.8.2.

**Comment by Hombre57** [comment]
@fortiernor @Floessie I've pushed this minor change to `dev`.

@fortiernor Just FYI, there's a stalled issue #2624 about supporting multiple snapshots per image. Maybe this discussion will be of any interest to you. Have you opened an issue for your intended patch ?
