### ISSUE TITLE
locallab: after deleting a spot the active spot always is the first spot

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#5269]
It would be more logical if, after deleting a spot, the active spot would be the one before the deleted spot.

**Comment by sguyader** [comment]
Agreed, I was thinking the same.

**Comment by Pandagrapher** [comment]
Fixed with commit `13cad6c`: now the first remaining spot before the deleted one is selected after deletion.

Pierre

**Comment by Pandagrapher** [comment]
@heckflosse 
Commit merged: is it ok to close this issue?
Pierre

**Comment by heckflosse** [comment]
@Pandagrapher Yes
