### ISSUE TITLE
Locallab: allow show all / hide all spots

### ISSUE THREAD

**Issue by sguyader** [Beep6581/RawTherapee#5270]
When you have several RTspots, sometimes you want to have a better idea of the overall effect and just want to hide all the spots. Adding a button for "show all" / "hide all" spots would be more efficient than show/hide each individual spot.

**Comment by Pandagrapher** [comment]
@sguyader 
To avoid having more buttons, what about shift+click on existing one to show/hide all ?

Pierre

**Comment by sguyader** [comment]
@Pandagrapher Yes shift+click is good idea!

**Comment by Pandagrapher** [comment]
Ok it’s on my todo list ;)

**Comment by Pandagrapher** [comment]
@sguyader 
Added with commits `e431e86` and `03c6141` ;)

Pierre

**Comment by sguyader** [comment]
@Pandagrapher Pierre I can't test these changes, as I'm away until next week. But thanks a lot!

**Comment by Pandagrapher** [comment]
Commit merged: is it ok to close this issue?
Pierre

**Comment by sguyader** [comment]
Nobody complained, closing.
