### ISSUE TITLE
locallab sharpening default values

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#5271]
The current sharpening default values for locallab spots are not the same as the ones for sharpening in dev. I suggest to use the default values from dev also for newlocallab.

**Comment by Desmis** [comment]
@heckflosse 
Yes we can !
You do ?

jacques

**Comment by heckflosse** [comment]
@Desmis I will do that

**Comment by Desmis** [comment]
@heckflosse 
Can I push a change, the "same" for retinex as for cbdl to improve "range" of shape detection, or shall I wait ?

jacques

**Comment by heckflosse** [comment]
@Desmis push :)

**Comment by Desmis** [comment]
@heckflosse 
Thank you :)
Done

Btw : I have "format" Iplocallab.cc with astylert :)
jacques

**Comment by Desmis** [comment]
@heckflosse 

Ingo
Can I push a change, or shall I wait ?
I just add (easy) a simplified "clarity" with CBDL, of course limited to 5 levels

jacques

**Comment by heckflosse** [comment]
@Desmis push

**Comment by Desmis** [comment]
@heckflosse 
Ingo
Done
Thank you
jacques

**Comment by Desmis** [comment]
@heckflosse 
Ingo
I have found a huge bug in "Blur and noise"
It's my fault, it is an very old bug...

Please, can you not post any commit 
Thank you

jacques

**Comment by heckflosse** [comment]
@Desmis Jacques, ok

**Comment by Desmis** [comment]
@heckflosse 

Thank you

This bug is huge, since how time ???
Because one year ago, it's work...
But I have found...

**Comment by Desmis** [comment]
@heckflosse 
@sguyader
Now it works as it would be :)
Tomorrow, I will clean code in GUI

Thank you
jacques

**Comment by Desmis** [comment]
@heckflosse 
Ingo
I will soon push a commit with clean GUI blurnoise

jacques

**Comment by Desmis** [comment]
@heckflosse 
Ingo

Done :)
thank you
