### ISSUE TITLE
Haze Removal causes clipping only for RAW (NO FIX)

### ISSUE THREAD

**Issue by sdfsssdf** [Beep6581/RawTherapee#5272]
hi there
can you add some switch to not affect hi-lights on dehaze?
please look on attached pics. it clipps  hi-lights even on 0.
so even if in ACR we use clarity+dehaze on 100, it never clips.
it works much better but this little problem must be solved, can you do something with it?

best regards

![on](https://user-images.githubusercontent.com/49338306/55676670-c6702600-5913-11e9-96c0-9c38651da4c1.jpg)
![off](https://user-images.githubusercontent.com/49338306/55676671-c6702600-5913-11e9-883e-1fdb9a54f51f.jpg)

P,S
it seems that this does not always works the same, and only for RAW. for jpg it has a different effect for some reason... I thought that this problem is more global and constant, so Im sorry about it.
I turned off all the settings and found few that enhance the effect, but even without them it is here.
so I attach this particular raw and settings.
[issue.zip](https://github.com/Beep6581/RawTherapee/files/3051495/issue.zip)

**Comment by Thanatomanic** [comment]
While this may be an actual issue, this is absolutely not the way a bug report should be written.
1. The title is nondescriptive and unnecessarily demanding.
2. You do not provide any of the required information (http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports).
3. You use multiple tools at the same time, so there's no way to tell what is actually going on.
4. You are not using the dehazing tool for its intended use, i.e. there is very likely no haze in a photo of a keyboard.

@sdfsssdf Please modify your issue to address all points.

**Comment by sdfsssdf** [comment]
@Thanatomanic
1. I'm not a pro debugger .. and I have no idea what the problem is and what I need for it to become "scriptive"
I found the problem and posted it .. further editing as it is convenient, for him comfort, always produce the author of the repository.
2. 3. In one you are right, it seems that this does not always works the same, and only for RAW. for jpg it has a different effect for some reason... I thought that this problem is more global and constant, so Im sorry about it.
I turned off all the settings and found few that enhance the effect, but even without them it is here.
so I attach this particular raw and settings.
[issue.zip](https://github.com/Beep6581/RawTherapee/files/3051495/issue.zip)
but
your 4th point, it looks inappropriate. I use what I consider necessary ok? This is my business and I will decide what and when to use. I did not come here to take advice on color correction, and not to argue about tastes.

**Comment by heckflosse** [comment]
@sdfsssdf 
> I use what I consider necessary ok? This is my business and I will decide what and when to use. I did not come here to take advice on color correction, and not to argue about tastes.

It's perfectly fine that you use what you consider necessary. It's our business to decide what to do in RawTherapee and when to do that.

**Comment by Beep6581** [comment]
Haze Removal does not clip highlights in the sample photo. There is also no haze in the sample photo.

**Comment by Beep6581** [comment]
Correction: Haze Removal causes clipping with strength=0 when the working space is small (sRGB, some in Adobe RGB).

**Comment by sdfsssdf** [comment]
@Beep6581 

> Correction: Haze Removal causes clipping with strength=0 when the working space is small (sRGB, some in Adobe RGB).

it only for raw,please try my settings when i use same pic in jpg in same sRGB it not clips.
anyway can it be fixed or add addishional checkbox in this ?
best regards
