### ISSUE TITLE
Allow disabling scaling

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#5276]
I just ran the 5.6-rc1 AppImage and found that the default font size is 10 which results in scaling and blurriness of icons which are designed to be pixel-sharp. I want to change this for 5.6.

@Hombre57 is it enough to set `fontSize = 9;` to have no scaling on a clean install in Windows, Linux and macOS?
https://github.com/Beep6581/RawTherapee/blob/dev/rtgui/options.cc#L345

**Comment by Beep6581** [comment]
Top if current default on a clean install, bottom is with font size 9 (Linux):
![rt_font_10_9](https://user-images.githubusercontent.com/5844619/55952391-ce083580-5c59-11e9-8b86-45b69158ee4b.png)

**Comment by Beep6581** [comment]
Setting `fontSize = 9;` in `options.cc` made no difference on a clean run, seems the default font size is inherited from my system.

**Comment by Hombre57** [comment]
@Beep6581 I don't mind setting the default value to whetever you want, but keep in mind that the scale factor depend on font size AND system wide font scaling (e.g. a Windows desktop will have 120% font scaling by default).

Please assign this to yourself as you'll decide and it's a [one liner](https://github.com/Beep6581/RawTherapee/blob/bb58e65ffca32d89368ae914316d18fb4f3f4288/rtgui/options.cc#L345).

**Comment by TooWaBoo** [comment]
FYI
On WIN10 and a clean run, the default font is set to `Segoe UI` and `font size 9`.

**Comment by Beep6581** [comment]
The default font size is inherited from the system, and that's fine, however that can result in scaling when the inherited font size is not 9pt, possibly also depending on DPI, so I'm changing the title of this issue.

As discussed with @Hombre57 in IRC, it wouldn't hurt to have a checkbox to completely disable scaling. Most people do not have HiDPI screens, and won't for years to come. Such a checkbox would be a safe fallback for [people for whom scaling causes problems](https://discuss.pixls.us/t/test-rawtherapee-5-6-rc1/12073/6?u=morgan_hardwood).

**Comment by Hombre57** [comment]
@Beep6581 Do you mean disabling scaling depending on the font size but still scaling for HiDPi screens, or totally disabling HiDPI support ?

**Comment by TooWaBoo** [comment]
> ... to completely disable scaling.

The themes are created with the unit `em`. Switching off scaling is only possible for the icons.

**Comment by Beep6581** [comment]
> or totally disabling HiDPI support ?

I'm not clear on what you understand by that, as what we're doing goes against the GTK+ definition of HiDPI:

> @ebassi | If you're messing around with the DPI, though, you're not doing anything hidpi-related, so you should stop using the term "hidpi". hidpi has precise semantics.

@Hombre57 I'm suggesting a checkbox which results in RT-5.5 behavior, where the icon sizes are unaltered, and RT does not alter the DPI, the scale, or anything else. Of course it would be great if RT could scale everything correctly on every platform - then this checkbox would serve just as a fallback for when things don't work, so that we can get 5.6 out the door. That's assuming that such a checkbox is a simple patch and doesn't further complicate things :)

**Comment by Hombre57** [comment]
@Beep6581 Forcing GDK_SCALE to 1 comes just after entering `main`, so prepare removing HiDPI support from the release notes [EDIT: which isn't really HiDPI support anyway]. I'll create a new branch in few minutes.

**Comment by Hombre57** [comment]
@Beep6581 Should be solved by commit 89e6363, in new `hidpi-optional` branch.

**Comment by Hombre57** [comment]
@Beep6581 Small bugfix added in commit feb122553e5ddfa81b8054ee6cc62c5e7e02d73a.

**Comment by Hombre57** [comment]
Oh, and forgot to mention that the new option disable the feature entirely, but still works as before if checked.

To have real HiDPI support, you'll have to wait for its support in Gtk::CellRenderer or create your own image renderer. Unless you find more/better info in the doc than I did.

**Comment by Beep6581** [comment]
@Hombre57 thank you, `hidpi-optional` works fine here, +1 for merge.

**Comment by Hombre57** [comment]
@Beep6581 Do I have to make a double merge ( `hidpi-optional` into `icon-size-fix` then into `dev`) ? Or can I merge `hidpi-optional` to `dev` directly ?

**Comment by Beep6581** [comment]
@Hombre57 either is fine, but as it's unrelated to `icon-size-fix` I would merge it directly to `dev`.

**Comment by Hombre57** [comment]
Then second question : can I merge `icon-size-fix`, it works fine for Linux and Windows and makes partly solve things for MacOS.

**Comment by Beep6581** [comment]
@Hombre57 when I tested `icon-size-fix` two days ago (#5281) it caused no issues on my end (it made no difference I could spot). Compiling again now.

**Comment by Beep6581** [comment]
@Hombre57 no problems here, +1 for merge to `dev`.

**Comment by Hombre57** [comment]
@Beep6581 `hidpi-optional` and `icon-size-fix` merged into `dev`.
