### ISSUE TITLE
wrong Colors raw

### ISSUE THREAD

**Issue by sdfsssdf** [Beep6581/RawTherapee#5277]
hi
im on ver5.5 win10x64
please say me whats going with the colors and how to do fix it? or it some bug with only my camera raw?
i put screenshot to show how colors different from another soft, (DNG_Profile_Editor also PS)
so in DNG_Profile_Editor and PS i have real colors like it must be with my corrected profile.
[files.zip](https://github.com/Beep6581/RawTherapee/files/3071624/files.zip)
i was think if i correct profile inside it and load into RawTherapee it will be good
but RawTherapee do colors very bleached, and not real as it is...
if i setup DCP illuminant in 2850 it become more same at all, but have a big problems in understanding red channel..
i try to change all options that i light up in red frame in attached pic, also try to change WB, but nothing change it atleast near to normal colors..
please help me
p/s i dont use any settings for this step, and load it in (neutral)

**Comment by Thanatomanic** [comment]
Please post your question on our forum at http://discuss.pixls.us, since this is (most likely) not a bug report.

**Comment by sdfsssdf** [comment]
i post it as you said, but it looks like bug or camera not supporting..
hope somebody help me bc it real problem for me...
also they have many limits for some rules// temporarily limit what new users can do
im not shure i can get answer there..bc im new there.

**Comment by sdfsssdf** [comment]
@Beep6581 

https://discuss.pixls.us/t/wrong-colors-raw/12084
hope dev. can say any solution for me or do something with this problem

i understand that different editors works different, but if i put color profile i wanna see profile colors…
i love setup all details etc in RawTherapee, but it real problem to setup colors becouse i see reference, it so far from real, i dont wanna lose my converting setup but it makes me very sad
I spent about an hour blindly adjusting the color in DNG_Profile_Editor so that the RT displays what I need … it’s very sad…
atleast if there some software that can edit profile like DNG_Profile_Editor, but RawTherapee will accept it, can be a "solution" please let me know

best regards

**Comment by Beep6581** [comment]
I will reply in the forum.
