### ISSUE TITLE
HiDPI support on MacOS

### ISSUE THREAD

**Issue by Hombre57** [Beep6581/RawTherapee#5282]
This issue is to discuss how to get better support of HiDPI on MacOS, as discussed in [this thread](https://discuss.pixls.us/t/test-rawtherapee-5-6-rc1/12073) and [this thread](https://discuss.pixls.us/t/help-test-rawtherapee-on-retina-4k-etc-hidpi-monitors/10705).

@Benitoite I'll need your help to test patch. At first, I find surprising that you had to raise the font size up to 18pt to get clean font while still being the same size than the title ([in this screenshot](https://pixls-discuss.s3.dualstack.us-east-1.amazonaws.com/original/3X/5/0/508188eb49647648ba999337b9159ed30f4d64be.png)), which should be 10-11pt I guess. So it doesn't surprise me that icons are that big considering the 18/9pt ratio.

Could you please apply this patch ( [hidpi-printf.txt](https://github.com/Beep6581/RawTherapee/files/3076284/hidpi-printf.txt) ) to get debug output and report here with different system resolution, including one flagged as HiDPI (960x540) ?

@Beep6581 I want to fix this issue today or tomorrow, but it will depend on the availability of testers (i.e. @Benitoite :wink: ).

**Comment by Benitoite** [comment]
Ok I can test today after an errand.

**Comment by Hombre57** [comment]
@Benitoite Here is an updated patch, one printf was wrong.

[hidpi-printf.txt](https://github.com/Beep6581/RawTherapee/files/3076463/hidpi-printf.txt)

Forgot to mention : to be applied into `icon-size-fix` branch.

**Comment by Benitoite** [comment]
updated patch applied and built. These are the screenshots for RawTherapee theme 9pt and 14pt. (restart required, etc.)

Terminal output:
```
$ ~/repo-rt/build/RawTherapee.app/Contents/MacOS/rawtherapee 
GDK_SCALE is 1
Resolution / Before: 72.000
Resolution / After : 72.000
"Non-Default" font size(14) * scale(1) / fontScale(1.556)
CSS:
* { font-family: PxPlus IBM VGA8; font-size: 14pt}

>>> RTScalable::init start
setDPInScale(72.000, 1) -> DPI: 72.000, Scale: 1
<<< RTScalable::init end
```

![Screen Shot 2019-04-13 at 12 17 41 PM](https://user-images.githubusercontent.com/17919239/56084300-3be16800-5de6-11e9-9cee-02153b5a123e.png)

![Screen Shot 2019-04-13 at 12 20 19 PM](https://user-images.githubusercontent.com/17919239/56084328-98448780-5de6-11e9-8105-1a0ed31de70f.png)

**Comment by Hombre57** [comment]
The icon size seems logical in regard of your font size in pt. Maybe a `sans` font would make the size difference less visible.

Now the interesting bit will be with a HiDPI resolution.

**Comment by Hombre57** [comment]
It would be nice if Paul Miller could use this version to report the debug output.

**Comment by Benitoite** [comment]
I have offered Paul Miller a link to https://kd6kxr.keybase.pub/RawTherapee_OSX_10.9_64_5.5-292-gd01d99481-patchAA.zip the patched mac build on the pixls.us forum.
Here is a screenshot of Helvetica 12.
![Screen Shot 2019-04-13 at 1 34 20 PM](https://user-images.githubusercontent.com/17919239/56085015-65ec5780-5df1-11e9-8bd2-f280de997ee9.png)

**Comment by Hombre57** [comment]
@Benitoite What is the debug output for this screenshot ? What is the folder name inside `cache/svg2png` ? What is the size of e.g. `exposure.png` inside this folder ?

**Comment by Benitoite** [comment]
```
GDK_SCALE is 1
Resolution / Before: 72.000
Resolution / After : 72.000
"Non-Default" font size(12) * scale(1) / fontScale(1.333)
CSS:
* { font-family: Helvetica; font-size: 12pt}

>>> RTScalable::init start
setDPInScale(72.000, 1) -> DPI: 72.000, Scale: 1
<<< RTScalable::init end

```

`cache/svg2png/96`
Dimensions: exposure.png = 32 x 32

**Comment by TooWaBoo** [comment]
The icons are to big (32 x 32) on @Benitoite's screenshot. The GUI on the Mac with `font size 12pt` should look identical to Linux/Win in `font size 9`. Icon size should be (24 x 24).

EDIT: Hmmm 🤔, on Windows/Linux the base font size is `9pt`. I think we have to use `12pt` as the base font size in the calculation for the scaling factor on the Mac.

Windows/Linux
`(System-dpi / 96dpi) * (RT-font-size / 9pt) = Scaling factor`

Mac
`(System-dpi / 72dpi) * (RT-font-size / 12pt) = Scaling factor`

**Comment by Hombre57** [comment]
@TooWaBoo Thanks for the tip ; I've committed a patch that works fine here. Could you please test @Benitoite , with this updated patch applied ?

[hidpi-printf.txt](https://github.com/Beep6581/RawTherapee/files/3077211/hidpi-printf.txt)

**Comment by TooWaBoo** [comment]
@Hombre57 
Works fine on Win10.

**Comment by Hombre57** [comment]
@Floessie I remember that you told me something about the RTImage not being updated on font size change, but don't remember in which issue/PR and what it was. Do you have better memory than me ?

**Comment by Floessie** [comment]
@Hombre57 I'm honestly sorry, but I can't remember as well. Must have been quite some time ago...

**Comment by Benitoite** [comment]
looks nice on 1080p with latest patch @Hombre57 
```
GDK_SCALE is 1
Resolution / Before: 72.000
Resolution / After : 72.000
"Non-Default" font size(12) * scale(1) / fontScale(1.000)
CSS:
* { font-family: Helvetica; font-size: 12pt}

>>> RTScalable::init start
setDPInScale(72.000, 1) -> DPI: 72.000, Scale: 1
<<< RTScalable::init end

```
![Screen Shot 2019-04-15 at 2 21 54 AM](https://user-images.githubusercontent.com/17919239/56121696-8a495080-5f25-11e9-9d29-9eab372a6209.png)

**Comment by Benitoite** [comment]
@Hombre57 also see [Paul Miller's test](https://discuss.pixls.us/t/test-rawtherapee-5-6-rc1/12073/73?u=hiram) on his Retina laptop screen.

**Comment by TooWaBoo** [comment]
The icons of Paul Miller's test are twice as big as they should be. The GUI size is o.k. Did he do the test with the latest patch?

**Comment by Benitoite** [comment]
@toowaboo yes latest patch

**Comment by Hombre57** [comment]
The latest patch should have disabled the 2x scale factor. Looking...

**Comment by Hombre57** [comment]
@Benitoite Which branch is `gace5a0113` ?

**Comment by Beep6581** [comment]
@Hombre57 `origin/icon-size-fix` ace5a011369f60928f8c975155dd93c19a911d9f (the "g" in your string is not part of the commit hash).

**Comment by Hombre57** [comment]
@Benitoite Then the 2x scale for icons is normal. With the latest dev (with merged branch), pseudo-HiDPI support is disabled by default. Enabling it will not make work on MacOS, unless you use a _native scale_ resolution.

**Comment by Hombre57** [comment]
@Benitoite Could you have a look at [this page](https://www.tekrevue.com/tip/hidpi-mode-os-x/) ? There's a Preference panel where a resolution is tagged as **HiDPI**, but does it still exist on latest MacOS version ? Or something similar ? Those tagged version shouldn't work for RT, to be verified.

**Comment by Beep6581** [comment]
To clarify, we believe those resolutions tagged " (HiDPI)" are incompatible with RawTherapee's pseudo-HiDPI mode (you must manually enable pseudo-HiDPI mode in Preferences in the latest dev, `5.5-306-g`7d33fc40c), while the ones not tagged are compatible. Please verify, and would be great if you could make a build for paulmiller to verify.

**Comment by Benitoite** [comment]
@Hombre57 a couple of these hidpi modes exist in the latest macOS. Effective resolution is low and usually not available by default.  
@Beep6581 ok i can make a dev branch build.

**Comment by Benitoite** [comment]
@Beep6581 on my 1080p system, enabling pseudo-hidpi mode in RT and restarting has no effect (is deselected after restart).
@Hombre57 @TooWaBoo It seems to me like 10pt is too small to be the default font size on mac. Maybe I'm just old?

Some 1080p screenshots:

10pt (default):
![Screen Shot 2019-04-16 at 8 18 44 AM](https://user-images.githubusercontent.com/17919239/56224180-032ed200-6024-11e9-9f52-6777d76c735c.png)

11pt:
![Screen Shot 2019-04-16 at 8 20 59 AM](https://user-images.githubusercontent.com/17919239/56222388-c57c7a00-6020-11e9-897c-7066124fcb4e.png)

12pt:
![Screen Shot 2019-04-16 at 8 20 05 AM](https://user-images.githubusercontent.com/17919239/56222378-c1e8f300-6020-11e9-9c69-7eb37812e271.png)

**Comment by TooWaBoo** [comment]
@Benitoite 
At font size 10pt and 11pt the buttons have a bevel but on 12pt the buttons are flat. Do you know why?
I've created a new issue to discuss this problem: https://github.com/Beep6581/RawTherapee/issues/5285

**Comment by Beep6581** [comment]
On my system, Sabayon Linux, enabling Pseudo-HiDPI mode has no visible effect when the font size is set to 9pt. This is correct. When the font size is anything else, with Pseudo-HiDPI mode disabled the icons do not scale, while if you enable Pseudo-HiDPI mode the icons are scaled (of course after restarting).

**Comment by Beep6581** [comment]
Off-topic, but I'm curious, @Benitoite why are all your screenshots so dark, even when the histogram shows there should be white clipping?

**Comment by Beep6581** [comment]
@Hombre57 we discussed last night that the resolutions tagged "(HiDPI)" in macOS interact badly with RT's HiDPI. But what about the situation where the macOS "Display" panel doesn't show any resolutions, as in paulmiller's screenshots? https://discuss.pixls.us/t/test-rawtherapee-5-6-rc1/12073/13?u=morgan_hardwood

**Comment by Hombre57** [comment]
@Beep6581 I googled that for 30mn but still no answer, unless you "option-clic" on the Scaled radio button, but [Apple's online help](https://support.apple.com/en-us/HT202471) says that it's only for external monitor.

Looks like they sometime push the simplicity philosophy a bit too far.

**Comment by Beep6581** [comment]
Close?

**Comment by Hombre57** [comment]
@Beep6581 Only real HiDPI support (from Gtk pov) will solve this issue. I'll open a new issue and close this one with a reference.

**Comment by Hombre57** [comment]
There' still partial pseudo-HiDPI support, solving this issue will be done by solving issue #5291, so closing as a duplicate.

**Comment by Benitoite** [comment]
> Off-topic, but I'm curious, @Benitoite why are all your screenshots so dark, even when the histogram shows there should be white clipping?

@Beep6581 I want to blame the macOS screenshot widget crop tool... 

Here are some tests:
![Screen Shot 2019-05-12 at 11 56 55 PM](https://user-images.githubusercontent.com/17919239/57601609-c914fb00-7511-11e9-9e89-ac5d7c491a49.png)


![Screen Shot 2019-05-13 at 12 01 47 AM](https://user-images.githubusercontent.com/17919239/57601867-830c6700-7512-11e9-877c-59d920c40cb6.png)

Safari seems to not hue down the way RT does.

**Comment by Beep6581** [comment]
@Benitoite when I download and view the same image in Geeqie, it's bright as expected, but in Google Chrome (74.0.3729.108) it's dim. Geeqie lets you disable the color profile, use the embedded profile, or use a different profile - none of these options result in a dark image. However, when I strip the ICC profile from the downloaded image (`exiftool -overwrite_original -icc_profile= foo.png`), then it is no longer dim in Google Chrome. I'll file a bug report for Geeqie.

**Comment by Beep6581** [comment]
What puzzled me was that the image looks correct in Geeqie regardless of color profile mode. After some though, I conclude that Geeqie is behaving well, and that Google Chrome probably does read the embedded profile but does so incorrectly, which is why the image looks well without the profile and why it looks consistently well in Geeqie regardless of color profile mode.

I wonder why a "display" device class profile (monitor profile) is being embedding in the PNG - it should embed sRGB or Adobe RGB, and the monitor profile should be used by the image viewing software, not embedded.

**Comment by Beep6581** [comment]
For reference:
![screenshot_20190513_091305](https://user-images.githubusercontent.com/5844619/57604024-7106e480-7563-11e9-9be9-bfa80d517bc5.png)

But I'm hijacking this issue now. If you'd like to continue, let's do so via the forum.

**Comment by Benitoite** [comment]
Thx @Beep6581 
See https://discuss.pixls.us/t/macos-screenshot-widget-color-seems-wrong-in-some-apps/12543/2
