### ISSUE TITLE
locallab - come up with more suitable name

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#5283]
I'm seeing "locallab" and "Local L\*a\*b\*" used in more and more places, but that name does not reflect what the tool currently does - I'm assuming the tool is not confined to the L\*a\*b\* color space, and even if it is, that's something to be mentioned in the docs, but does not have to constitute its name.

@Desmis @Pandagrapher et al, let's come up with a better, ultimate name so that we can start cleaning up the nomenclature.

Ideas:
* "Spots".
* We have a "L*a*b* Adjustments" tool, so we could call this "Local Adjustments".
* "Local Edits"

I like "Spots" because its nice and short, I just don't know what your plans for the tool are, and whether it will be confined to spots, or whether it will also support e.g. on-canvas painting.

**Comment by Desmis** [comment]
@Beep6581 
it's the stock market with ideas, the best are welcome

I initially called this module "Locallab" which turned into "Local L*a*b*" because, it is a **local** control, and all the modules works in **Lab**, and never in RGB

Jacques

**Comment by Desmis** [comment]
Today there are only "Spot" that work on the "gradient" mode... with only 2 "delimiters" - ellipse and rectangle.
 It's only a GUI problem (I don't know how to do !) to have another(s) delimiters. The "only" constraint is : the "curve" must pass by 2 summits (X and Y), be inscribed in the rectangle - center - X - Y, and to be homothetic. in this case the GUI will produce a LUT usable as "ellipse"

I did not foresee - it is also mainly a problem of GUI - to make retouches with brushes ...

But with with current spots, it is possible to remove a lot of imperfections (grease, traces, dirt ..), especially with "Color and Light", "CBDL", "Blur"

jacques

**Comment by heckflosse** [comment]
@Desmis 
> and all the modules works in Lab, and never in RGB

with the exception of `dehaze` ;-)

**Comment by Desmis** [comment]
An other exception
Warm cool with Ciecam :)

**Comment by Benitoite** [comment]
Radial adjustments

**Comment by Desmis** [comment]
A few words that may appear, in combination or not

Adjustements,  Edit, Gradient,  L *a * b * , Lab, Local,  Radial, Rawtherapee, RT, RT-Spot, Spot, U (you), U-RTspot, etc.

**Comment by Thanatomanic** [comment]
My 2 cents on this would to go for the slightly more verbose "Local adjustments". I would associate "Spots" with a spot removal tool / clone brush. "Local adjustments" also allow for future development into all kinds of shapes and sizes of adjustments.

**Comment by sguyader** [comment]
I was going to suggest "Local adjustments" as well.

**Comment by heckflosse** [comment]
:+1: for `Local adjustments`

**Comment by Desmis** [comment]
As many peoples are for "Local Adjustements", instead of Local L * a * b *  I just change all labels with "Local Adjustements"

**Comment by Desmis** [comment]
I will be away next week

jacques

**Comment by Beep6581** [comment]
Great.
