### ISSUE TITLE
newlocallab: Spot WB, crop and straighten from toolbar are broken

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#5286]
To reproduce:

1) Open an image
2) click Spot WB button in toolbar. Result: WB tool is opened but editor is still in hand-mode
![grafik](https://user-images.githubusercontent.com/13733487/56241329-e59a5080-6095-11e9-81ae-6f20742a6587.png)

Works fine in dev.

**Comment by Pandagrapher** [comment]
It’s maybe due to my commit `690df79e`
Gonna have a look

Pierre

**Comment by Pandagrapher** [comment]
Well finally it wasn't due to that commit but it's now fixed with commit `3423e45`

Pierre

**Comment by heckflosse** [comment]
@Pandagrapher Can you pr your changes?

**Comment by Pandagrapher** [comment]
@heckflosse 
Done ;)

**Comment by Pandagrapher** [comment]
@heckflosse 
Is it ok to close this issue?
Pierre

**Comment by heckflosse** [comment]
@Pandagrapher Yes, closing. Thanks a lot for the fixes :+1:
