### ISSUE TITLE
Treeview cell background color makes text difficult to read

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#5297]
The background color of the cell which corresponds to the spot you're currently hovering over is quite aggressive and makes the text difficult to read. Could it use a more eye-friendly color?

![screenshot_20190423_134452](https://user-images.githubusercontent.com/5844619/56578448-fdaa2c80-65cd-11e9-91ea-216832604202.png)

**Comment by Desmis** [comment]
I forgot to mention it here, but I made a change - in the same hue range, but I think easier to read, in the last commit

**Comment by Beep6581** [comment]
Fix confirmed.
