### ISSUE TITLE
Click spot center area to move it

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#5298]
Currently one must click on the spot outline to move the spot. It would be nice if we could move it by clicking anywhere within the central spot, not only on its outline.

![screenshot_20190423_134809](https://user-images.githubusercontent.com/5844619/56578679-8032ec00-65ce-11e9-8b44-292c44782426.png)

**Comment by Pandagrapher** [comment]
@Beep6581 
If you want to test:
``` diff
diff --git a/rtgui/controlspotpanel.cc b/rtgui/controlspotpanel.cc
index 6c08eca..905088c 100644
--- a/rtgui/controlspotpanel.cc
+++ b/rtgui/controlspotpanel.cc
@@ -1110,6 +1110,7 @@
     cirYT->filled = true;
     cirYT->datum = Geometry::IMAGE;
     centerCircle = new Circle();
+    centerCircle->filled = true;
     centerCircle->datum = Geometry::IMAGE;
     centerCircle->radiusInImageSpace = true;
     shape_ellipse = new Ellipse();
```

Additional info: Can also move the spot selecting the ellipse/rectangle.

Pierre

**Comment by Beep6581** [comment]
@Pandagrapher thank you. Tried and tested. I find that much easier to use!

Note that `rtgui/controlspotpanel.cc` and `rtgui/controlspotpanel.h` use wrong line endings. I can push a fix if you like - let me know when to do it.

**Comment by heckflosse** [comment]
@Pandagrapher Works fine. :+1: for push

**Comment by Pandagrapher** [comment]
@Beep6581 

> Note that rtgui/controlspotpanel.cc and rtgui/controlspotpanel.h use wrong line endings. I can push a fix if you like - let me know when to do it.

As I need to push the patch, I will correct the wrong line endings too (I have changed my IDE parameter not to have this problem anymore)

**Comment by Pandagrapher** [comment]
Done with commit `4cc2a34`

Pierre
