### ISSUE TITLE
Minimum required version of cmake

### ISSUE THREAD

**Issue by scx** [Beep6581/RawTherapee#5302]
According to the [CMakeLists.txt](https://github.com/Beep6581/RawTherapee/blob/5.6/CMakeLists.txt#L5), **RawTherapee** requires `cmake` >= _2.8.8_.

However, I was unable to build **RawTherapee** using `cmake` _2.8.12.2_.
```]
CMake Error at rtdata/CMakeLists.txt:52 (install):
  install FILES given directory
  "/home/scx/rpmbuild/BUILD/rawtherapee-5.6/rtdata/images/png" to install.
```

Fortunately, it works with `cmake` _3.13.4_.

See also:
https://github.com/Beep6581/RawTherapee/issues/5115#issuecomment-485904108

**Comment by Beep6581** [comment]
Likely the mininum version of CMake in the docs and in `CMakeLists.txt` is outdated. I don't know how to check which version is the real minimum.

RawTherapee requires GTK+ >=3.18, which is from [September 2015](https://download.gnome.org/sources/gtk+/3.18/). Based on this, and based on your comment above, I think it should be fine to bump the minimum required CMake version to one from around the same time as the minimum GTK+ version, and that would be [CMake 3.3.0](https://blog.kitware.com/cmake-3-3-0-released/). The minimum for Apple is 3.3, according to https://github.com/Beep6581/RawTherapee/blob/dev/CMakeLists.txt#L1

Anyone against?

**Comment by Beep6581** [comment]
CMake 2.8.8 is from April 18, 2012.

**Comment by scx** [comment]
@Beep6581 

> Likely the mininum version of CMake in the docs and in `CMakeLists.txt` is outdated. I don't know how to check which version is the real minimum.
> 
> RawTherapee requires GTK+ >=3.18, which is from [September 2015](https://download.gnome.org/sources/gtk+/3.18/). Based on this, and based on your comment above, I think it should be fine to bump the minimum required CMake version to one from around the same time as the minimum GTK+ version, and that would be [CMake 3.3.0](https://blog.kitware.com/cmake-3-3-0-released/). The minimum for Apple is 3.3, according to https://github.com/Beep6581/RawTherapee/blob/dev/CMakeLists.txt#L1
> 
> Anyone against?

As far as I know, **CMake** _2.8.12.2_ (_2018-12-06_) is the latest version from _2.x_ branch, so we must switch to **CMake** _3_ anyway.
I am not totally sure, but I think that this may be a problematic part:
https://github.com/Beep6581/RawTherapee/blob/5.6/rtdata/CMakeLists.txt#L11-L13
```
file(GLOB IMG_SVG LIST_DIRECTORIES false "images/svg/*")
file(GLOB IMG_PNG LIST_DIRECTORIES false "images/png/*")
file(GLOB IMG_ICO LIST_DIRECTORIES false "images/*")
```

Please take a look at `LIST_DIRECTORIES`.
It was probably introduced in **CMake** _3.3_, because I don't see it in **CMake** _3.2_.
https://cmake.org/cmake/help/v3.3/command/file.html
https://cmake.org/cmake/help/v3.2/command/file.html

I don't know if **CMake** _3.3_ is the real minimum, but I think that it would be a good start to put this version in `CMakeLists.txt`.
Today even EL6 has **CMake** _3.6_ in [EPEL](https://koji.fedoraproject.org/koji/buildinfo?buildID=953356), so it shouldn't be a problem to anyone.

**Comment by scx** [comment]
As far as I know, only users of **Debian** _8_  (_Jessie_ AKA _oldstable_ - public support until _2020-06-30_) or **Ubuntu** _14.04 LTS_ (_Trusty Tahr_ - public support until 2019-04) may be against it. However, I doubt they would use the latest version of **RawTherapee**. Moreover, it should be relatively easy to backport `CMakeLists.txt` to **CMake** _2.8_.

**Comment by Floessie** [comment]
Debian 8 has GTK+ 3.14, so you can't build RT there anyway. Don't know if 3.3 is the sweet spot. If I'm not completely wrong, 3.5 introduced features needed for modern CMake. Maybe ask @cryptomilk, who modernized CMake for `librtprocess`.

**Comment by cryptomilk** [comment]
I would suggest to require 3.5 which offers the features used by modern cmake. It is also available in most distributions which is not EOL yet.

https://cliutils.gitlab.io/modern-cmake/

**Comment by Beep6581** [comment]
3.5 it is.
