### ISSUE TITLE
Problem with fix on "First doubleclick on an image after starting rt does not open the image, fixes #5294"

### ISSUE THREAD

**Issue by abertens** [Beep6581/RawTherapee#5308]
Hi there!

Commit 6e364e4c80416189ec8e1ef478497d13de14140f (First doubleclick on an image after starting rt does not open the image, fixes #5294) has a side effect on my platform Linux (Debian 9 / XFCE).

When I select a folder in the left pane, I can't navigate through images at right pane with keyboard (after a single click on one of them).
Right pane seems not to grab keyboard focus and every key is received by left pane.
Is this the expected behaviour?

Reverting commit makes it work again ok.

Version: 5.6-22-g3289835ca
Branch: 5.6-22-g3289835ca
Commit: 3289835
Commit date: 2019-04-24
Compiler: cc 6.3.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.22.0
Lensfun: V0.3.2.0
Build type: Release
Build flags: -std=c++11 -march=native -Werror=unused-label -Wall -Wuninitialized -Wno-deprecated-declarations -Wno-unused-result -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags: -march=native
OpenMP support: ON
MMAP support: ON

Also, About window still shows "Release Candidate 1".

Regards,
Andres Bertens

**Comment by heckflosse** [comment]
@abertens Thanks for reporting. Bug confirmed. I will revert the commit.

**Comment by Beep6581** [comment]
> Also, About window still shows "Release Candidate 1".

![screenshot_20190425_201252](https://user-images.githubusercontent.com/5844619/56758290-8ffd2c80-6796-11e9-9f07-34c7d5e698ce.png)

**Comment by abertens** [comment]
![Screenshot_2019-04-25_14-15-36](https://user-images.githubusercontent.com/40841548/56758472-ba35f680-6764-11e9-97de-43362c184769.png)

?

**Comment by Beep6581** [comment]
@abertens seems you have a problem with your cloned repo. Easiest way is to delete it and clone again.

**Comment by Beep6581** [comment]
I think I know why you're seeing "Release Candidate 1". You probably ran `5.6-rc1` before, then built or installed `5.6`. Well RawTherapee now creates PNG icons from SVG images on the fly, and it stores them in a cache. Since you already had a `splash.png` from running `5.6-rc1`, the old file was used.

Solution: delete the folder `svg2png` from the [cache](http://rawpedia.rawtherapee.com/File_Paths#Cache).

**Comment by heckflosse** [comment]
@Beep6581 

> delete the folder svg2png from the cache.

Now I get this:
![grafik](https://user-images.githubusercontent.com/13733487/56760249-1b78bc80-679b-11e9-972e-f4e8acb17f12.png)

**Comment by abertens** [comment]
Beep6581, you are right. Removing svg2png from cache shows the correct image/name.
Thanks.

**Comment by heckflosse** [comment]
@Beep6581 With a fresh clone it works fine :)
![grafik](https://user-images.githubusercontent.com/13733487/56761517-d3a76480-679d-11e9-9961-16f2da4939c5.png)

**Comment by abertens** [comment]
@heckflosse @Beep6581 

Sorry. I did a fresh clone and it did not replaced the image.
Removing svg2png from cache did the trick.

Regards,
Andres Bertens

**Comment by heckflosse** [comment]
@abertens I had to remove `svg2png` and use a fresh clone. Sorry for having been unclear.
