### ISSUE TITLE
Frequent crashes in macOS

### ISSUE THREAD

**Issue by wilchak** [Beep6581/RawTherapee#5312]
Hello,
I really like the software but it crashes a lot. There doesn't seem to be much of a pattern. Usually (but not always) it happens when changing folders in the file browser.... but it's not one particular folder that does it- seems to be random. Sometimes it happens shortly after starting the program, sometimes it will take ~20 mins.

Platform: MacOS 10.14.4
Version: 5.6

Attaching the crash reporter files from MacOS.
I can install a debug build if necessary, but there does seem to be plenty of stack trace info in here.
Thank you.

[rawtherapee-bin_2019-04-23-005149_AT-086.txt](https://github.com/Beep6581/RawTherapee/files/3125291/rawtherapee-bin_2019-04-23-005149_AT-086.txt)
[rawtherapee-bin_2019-04-23-235853_AT-086.txt](https://github.com/Beep6581/RawTherapee/files/3125292/rawtherapee-bin_2019-04-23-235853_AT-086.txt)
[rawtherapee-bin_2019-04-25-204656_AT-086.txt](https://github.com/Beep6581/RawTherapee/files/3125293/rawtherapee-bin_2019-04-25-204656_AT-086.txt)
[rawtherapee-bin_2019-04-25-210250_AT-086.txt](https://github.com/Beep6581/RawTherapee/files/3125294/rawtherapee-bin_2019-04-25-210250_AT-086.txt)
[rawtherapee-bin_2019-04-25-215738_AT-086.txt](https://github.com/Beep6581/RawTherapee/files/3125295/rawtherapee-bin_2019-04-25-215738_AT-086.txt)
[rawtherapee-bin_2019-04-25-224033_AT-086.txt](https://github.com/Beep6581/RawTherapee/files/3125296/rawtherapee-bin_2019-04-25-224033_AT-086.txt)
[rawtherapee-bin_2019-04-25-234023_AT-086.txt](https://github.com/Beep6581/RawTherapee/files/3125297/rawtherapee-bin_2019-04-25-234023_AT-086.txt)
[rawtherapee-bin_2019-04-26-192016_AT-086.txt](https://github.com/Beep6581/RawTherapee/files/3125298/rawtherapee-bin_2019-04-26-192016_AT-086.txt)
[rawtherapee-bin_2019-04-26-213149_AT-086.txt](https://github.com/Beep6581/RawTherapee/files/3125299/rawtherapee-bin_2019-04-26-213149_AT-086.txt)
[rawtherapee-bin_2019-04-27-201202_AT-086.txt](https://github.com/Beep6581/RawTherapee/files/3125300/rawtherapee-bin_2019-04-27-201202_AT-086.txt)
[rawtherapee-bin_2019-04-27-201211_AT-086.txt](https://github.com/Beep6581/RawTherapee/files/3125301/rawtherapee-bin_2019-04-27-201211_AT-086.txt)
[rawtherapee-bin_2019-04-27-203649_AT-086.txt](https://github.com/Beep6581/RawTherapee/files/3125302/rawtherapee-bin_2019-04-27-203649_AT-086.txt)
[rawtherapee-bin_2019-04-28-134801_AT-086.txt](https://github.com/Beep6581/RawTherapee/files/3125303/rawtherapee-bin_2019-04-28-134801_AT-086.txt)

**Comment by Benitoite** [comment]
The latest dev build from [discuss.pixls.us](https://discuss.pixls.us/t/download-rawtherapee-development-builds/2924) has most libraries updated... 
https://kd6kxr.keybase.pub/RawTherapee_OSX_10.9_64_5.6-17-g6e364e4c8.zip
That's definitely worth a test.  
Also, wonder if you have some files or folders with international characters? Or system is set to some odd combination of language and region (for example, English-Germany).

**Comment by wilchak** [comment]
No funny international character stuff. Just tested with the latest dev build (5.6.17-g6e), crashes still happening.... always when double clicking on a folder in the file browser to switch to it.

[rawtherapee-bin_2019-04-28-203004_AT-086.txt](https://github.com/Beep6581/RawTherapee/files/3125721/rawtherapee-bin_2019-04-28-203004_AT-086.txt)

**Comment by Beep6581** [comment]
@wilchak delete all files from the `themes` subfolder (`RawTherapee-GTK3-20_.css`, etc.), re-run RT (it will look bad), and test - does it still crash?

**Comment by wilchak** [comment]
I removed all the files from the `themes` folder and..... two things! 1) I can't get it to crash 🙂, and 2) the interface is noticeably snappier. Must be some weird stuff going on in the GTK theme engine....

**Comment by Beep6581** [comment]
Were you using "Pseudo HiDPI mode"? If you look in your [`options`](http://rawpedia.rawtherapee.com/File_Paths#Config) file, you will see `PseudoHiDPISupport=true or false`

**Comment by wilchak** [comment]
Can confirm `PseudoHiDPISupport=false` in my options file.

**Comment by Beep6581** [comment]
And this was the macOS build from our website? i.e. https://rawtherapee.com/releases_head/mac/RawTherapee_OSX_10.9_64_5.6.zip

**Comment by wilchak** [comment]
Yes, using the official 5.6 release build and latest dev build (5.6.17-g6e).

Ok, an update: I was able to get the dev build to crash too, but only after connecting my external monitor (which is how I usually work). 

[rawtherapee-bin_2019-04-29-173115_AT-086.txt](https://github.com/Beep6581/RawTherapee/files/3129293/rawtherapee-bin_2019-04-29-173115_AT-086.txt)

**Comment by Beep6581** [comment]
@Benitoite which version of GTK+ does your build use?

@wilchak could you try to narrow this down to some easy-to-reproduce action? You said the crash happens when you try to access a folder. Can you reproduce if you apply the "Neutral" profile to all photos in that folder, then try to access it?

**Comment by Benitoite** [comment]
Using gtk 3.24.8, last release.

**Comment by wilchak** [comment]
Having trouble reproducing now (including with Neutral as default and without). I will comment if I can get another crash.

**Comment by wilchak** [comment]
Ok, 5.6-26 crashes immediately on startup. See two attached crash logs. HOWEVER, when all the files are removed from the themes directory, the app works fine.

[rawtherapee-bin_2019-05-01-214914_AT-086.txt](https://github.com/Beep6581/RawTherapee/files/3136529/rawtherapee-bin_2019-05-01-214914_AT-086.txt)
[rawtherapee-bin_2019-05-01-214922_AT-086.txt](https://github.com/Beep6581/RawTherapee/files/3136530/rawtherapee-bin_2019-05-01-214922_AT-086.txt)

**Comment by Floessie** [comment]
Looks like a concurrent call to GTK from a non-Main thread. `FileCatalog::_refreshProgressBar()` is illegally called from the thread pool.

**Comment by wilchak** [comment]
5.6-26 now crashing every time I hit OK in the Preferences window.
[rawtherapee-bin_2019-05-02-200625_AT-086.txt](https://github.com/Beep6581/RawTherapee/files/3140322/rawtherapee-bin_2019-05-02-200625_AT-086.txt)
[rawtherapee-bin_2019-05-02-200716_AT-086.txt](https://github.com/Beep6581/RawTherapee/files/3140323/rawtherapee-bin_2019-05-02-200716_AT-086.txt)

**Comment by Floessie** [comment]
This one is different from the earlier crash. My guess: a GTK bug on MacOS...

**Comment by Benitoite** [comment]
I have updated the mac app at https://kd6kxr.keybase.pub/RawTherapee_OSX_10.9_64_5.6-26-ga2e2ace1c.zip
It is based on the latest of branch `gtk-3-24` which is ahead of the last release.

**Comment by wilchak** [comment]
No crashes yet! Seems promising.

**Comment by Benitoite** [comment]
gtk-3-24 has been advanced 100 commits!  https://kd6kxr.keybase.pub/RawTherapee_OSX_10.9_64_5.6-26-ga2e2ace1c.zip

**Comment by wilchak** [comment]
The latest two dev builds (most recent.... 5.6-54-g2bed5dc5, and the previous one also) repeatedly crash when a particular folder is opened from the recent folders menu. But... not every time. Just like, 3/4 times. Attaching the crash logs, but what's strange is that they are all different. I honestly just don't know.

[rawtherapee-bin_2019-06-02-211937_AT-086.txt](https://github.com/Beep6581/RawTherapee/files/3245492/rawtherapee-bin_2019-06-02-211937_AT-086.txt)
[rawtherapee-bin_2019-06-02-211652_AT-086.txt](https://github.com/Beep6581/RawTherapee/files/3245493/rawtherapee-bin_2019-06-02-211652_AT-086.txt)
[rawtherapee-bin_2019-06-02-211214_AT-086.txt](https://github.com/Beep6581/RawTherapee/files/3245494/rawtherapee-bin_2019-06-02-211214_AT-086.txt)

**Comment by Benitoite** [comment]
Hi, thanks for testing! Which “theme” are you using, and can you make it crash with TooWaaBlueDark?

**Comment by Floessie** [comment]
* rawtherapee-bin_2019-06-02-211937_AT-086.txt seems to me like a GTK bug.
* rawtherapee-bin_2019-06-02-211652_AT-086.txt is the one I tried to mitigate in [refreshprogressbar-experiments](https://github.com/Beep6581/RawTherapee/tree/refreshprogressbar-experiments).
* rawtherapee-bin_2019-06-02-211214_AT-086.txt is a race inside `FileBrowserEntry::FileBrowserEntry()`. I'll fix that.

**Comment by Floessie** [comment]
@Benitoite Could you provide @wilchak with a build from `refreshprogressbar-experiments` to see, if this fixes at least the two bugs I identified? I've updated the branch to `dev`.

**Comment by Benitoite** [comment]
@wilchak @Floessie Sure, https://kd6kxr.keybase.pub/RawTherapee_OSX_10.9_64_5.6-63-gbc3cc988d.zip

**Comment by wilchak** [comment]
Crash from the latest 5.6-73: 
[rawtherapee-bin_2019-06-22-154120_Lil-Trashy.txt](https://github.com/Beep6581/RawTherapee/files/3317223/rawtherapee-bin_2019-06-22-154120_Lil-Trashy.txt)

**Comment by heckflosse** [comment]
@wilchak 

http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports

**Comment by Benitoite** [comment]
@wilchak is that 5.6.73 from dev branch?  Could you try the https://kd6kxr.keybase.pub/RawTherapee_OSX_10.9_64_5.6-63-gbc3cc988d.zip

**Comment by wilchak** [comment]
It's been holding up pretty well, but just hit a crash today with the latest 5.6-199 dev build running on macOS 10.14.6. Can reliably reproduce by going to Preferences > Color Management > clicking on "Directory containing color profiles" 

Crash log: 
[rawtherapee-bin_2019-07-25-211611_Lil-Trashy.log](https://github.com/Beep6581/RawTherapee/files/3433806/rawtherapee-bin_2019-07-25-211611_Lil-Trashy.log)

**Comment by Beep6581** [comment]
@wilchak try narrowing it down to a specific file in the folder which gets opened by default when you click "Directory containing color profiles", then zip and upload the file.

**Comment by wilchak** [comment]
I believe it's an issue with the file picker window, since I get a very similar crash when I use the "save current profile" button.

Crash from clicking "save current profile" 
[rawtherapee-bin_2019-07-25-211830_Lil-Trashy.log](https://github.com/Beep6581/RawTherapee/files/3435472/rawtherapee-bin_2019-07-25-211830_Lil-Trashy.log)

**Comment by Beep6581** [comment]
Well let's try to find out. Close RT, create an empty folder somewhere, let's say in `/home/wilchak/empty`, then edit your [options](http://rawpedia.rawtherapee.com/File_Paths) file and set:
```
ICCDirectory=/home/wilchak/empty
```
Run RT and click the button, see what happens.

**Comment by wilchak** [comment]
Setting ICCDirectory to an empty folder has no effect on the crashing behavior I described above. Since we already know that the (same or very similar) crash can also be triggered by clicking the "save current profile" button, we know it is not an issue with the ICCDirectory folder, since the profile save window does not open up to that folder. Furthermore, if you actually look at the two crash logs I attached above, it is evident that the crash is happening inside libgio, which doesn't parse ICC profiles... it just opens the file picker window. So the behavior I'm describing is consistent with what the crash logs suggest: the issue is with the file picker window code. Chances are this is just a build issue though, since the log suggests that libgio was built for macOS 10.15. So maybe this is a bug in the beta SDK from Apple?

**Comment by Beep6581** [comment]
> Furthermore, if you actually look at the two crash logs I attached above

Unless you actually identified the cause of the crash, everything is an assumption. I did look at the logs, and decided a quick and simple test would be good. I hope we can do without snide remarks in the future.

**Comment by wilchak** [comment]
I did identify the _location_ of the crash. It is in libgio. (Not RawTherapee itself, so you don't need to be defensive about it.) I appreciate your thorough approach. And again- I have only respect for the developers of this excellent software. But I don't much like jumping through obviously irrelevant hoops. If you'd prefer to not have my help, just communicate that to me and you won't hear from me again.

**Comment by Benitoite** [comment]
The 10.15-built lib is definitely not supposed to be there.  It should be built for 10.9, I will have to check the glib build.

**Comment by fferreres** [comment]
I have a similar problem with the latest stable 5.7 release, using Mohave. Whenever I try to, for example, set a directory in Settings -> Image Processing -> Directories the moment I click to select it crashes. Similarly, if I choose a Folder in the editor window to select a profile. 

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x4] Symbol missing

Dyld Error Message:
  Symbol not found: _objc_alloc_init
  Referenced from: /Applications/RawTherapee.app/Contents/MacOS/bin/../../Frameworks/libgio-2.0.0.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libobjc.A.dylib

I have a fresh cache and config trying to diagnose the problem for a few hours after moving from 5.5 which worked flawlessly. I am using Mohave and High Sierra in the past.

**Comment by Beep6581** [comment]
@Benitoite is that the same issue?
https://discuss.pixls.us/t/rawtherapee-5-7-released-plus-a-new-website/13980/145?u=morgan_hardwood

**Comment by Benitoite** [comment]
Yes I believe so.  This is due to glib switching to meson... need to figure out how to set the sysroot for the older sdk.

**Comment by fferreres** [comment]
If there's any workaround users can do that any can think of, like upgrading a library, changing a library path, etc. In the meantime, I am using RT 5.5 which works flawlessly and and by far the best RAW developer program.

**Comment by Benitoite** [comment]
https://kd6kxr.keybase.pub/RawTherapee_OSX_10.9_64_5.7.zip
`meson` gained the `sys_root`ing ability via a cross-file a few days ago, so here is a new build that I have submitted.

**Comment by Beep6581** [comment]
Ping @wilchak

**Comment by wilchak** [comment]
> Ping @wilchak

Working pretty well so far, thanks!

**Comment by glitterdust** [comment]
I found this issue since RT crashed every time I attempted to save a file.
The download from @Benitoite seems to have solved the issue for me.

**Comment by wilchak** [comment]
Hi, I've been experiencing some new recurring crashes when editing. Attached are two crash logs, which appear to be the same bug. I am running the latest release build of 5.8 on macOS 10.15.3.

[rawtherapee-bin_2020-03-19-184226_Lil-Trashy.txt](https://github.com/Beep6581/RawTherapee/files/4357238/rawtherapee-bin_2020-03-19-184226_Lil-Trashy.txt)
[rawtherapee-bin_2020-03-19-185345_Lil-Trashy.txt](https://github.com/Beep6581/RawTherapee/files/4357239/rawtherapee-bin_2020-03-19-185345_Lil-Trashy.txt)

**Comment by Benitoite** [comment]
That is a RawTherapee exit so will need to test against a recent dev build and report any errors. 
My most recent build:
https://kd6kxr.keybase.pub/RawTherapee_OSX_10.9_64_5.8-317-g6563989f5.zip

**Comment by wilchak** [comment]
Will try that, thanks.

**Comment by wilchak** [comment]
Looks like that 5.8-317 build is now crashing on startup with the 10.15.4 update.

> Exception Type: EXC_CRASH (Code Signature Invalid)
> Exception Codes: 0x0000000000000000, 0x0000000000000000
> Exception Note: EXC_CORPSE_NOTIFY
> 
> Termination Reason: Namespace CODESIGNING, Code 0x1

Unclear what exactly they changed in the most recent release.... confusing because running codesign --verify --verbose on the RawTherapee.app bundle says everything is fine.
