### ISSUE TITLE
CR3 image decoding support

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#5319]
There is an increasing number of cameras using the Canon Raw v3 (CR3) format. This issue is about adding support for decoding CR3 in RawTherapee, regardless of specific camera model.

CR3 specification:
https://github.com/lclevy/canon_cr3

**Comment by miguel-porto** [comment]
Hi, how is the progress of this feature? Desperately needing it... ;-)
BTW, congrats on this great piece of software!

**Comment by Thanatomanic** [comment]
@miguel-porto There has been more discussion on the subject recently. See here: https://discuss.pixls.us/t/not-yet-canon-raw-files-cr3-recognised-by-rawtherapee/14042
If you desperately need it, you may opt to contact Canon yourself: https://discuss.pixls.us/t/canon-cr3-raw-support-your-move/14192

**Comment by miguel-porto** [comment]
Oh, didn't know the problem was still at that level, sorry. Just came across this issue first. Thanks for the clarification.

**Comment by albfe** [comment]
Hello, it looks like the new snapshot of LibRaw supports CR3!
https://www.libraw.org/news/libraw-snapshot-201910
Code should be available in their Github repo :)

**Comment by Beep6581** [comment]
Commit 0cf3f16df adds basic CR3 decoding support. Metadata is not supported yet.

**Comment by albfe** [comment]
Thanks a lot for the effort: it works!
Of course it is not yet usable, without metadata support, but I guess it will be coming with time :) 

Thanks again!

**Comment by heckflosse** [comment]
@albfe We started work on it today. Porting the code to decode the files was easy. Give us some time for the remaining parts (Metadata...)

**Comment by albfe** [comment]
@heckflosse , I completely understand and my intention was not to criticize, but rather to thank you for having started working on this. Sorry if we misunderstood. My note about metadata was for other possible users that are waiting for cr3 support, so that they don't expect it is fully usable right now, just that.

BTW, even EOS R crop seems to be working well.

**Comment by Krijger** [comment]
Should I expect to see CR3 files already? I built the code for Mac OS (including the latest cr3 related commit from `dev`) and am not seeing the CR3 files in the File Browser.

**Comment by heckflosse** [comment]
@Krijger Is CR3 enabled in preferences? 
![grafik](https://user-images.githubusercontent.com/13733487/70653006-f1a1d680-1c53-11ea-850e-ca991f581a12.png)

**Comment by Krijger** [comment]
@heckflosse hmm, it's not even in the list

**Comment by Krijger** [comment]
I checked my app contents for files in it that might explain this, it may have to do with the following file tree.

```
└── Contents
    │   ├── share
    │   │   ├── mime
    │   │   │   ├── image
    │   │   │   │   ├── bmp.xml
    │   │   │   │   ├── x-bzeps.xml
    │   │   │   │   ├── x-canon-cr2.xml
    │   │   │   │   ├── x-canon-crw.xml
```

I got the mime from `shared-mime-info` (installed with homebrew), (EDIT) which apparently does not yet know about CR3 https://gitlab.freedesktop.org/xdg/shared-mime-info/blob/master/freedesktop.org.xml.in#L4753, so I wonder where your installation gets the option from. What package installs the correct mimes ?

**Comment by heckflosse** [comment]
@Krijger Just add cr3 to the list
![grafik](https://user-images.githubusercontent.com/13733487/70657925-249c9800-1c5d-11ea-9107-ad8a7b063960.png)

**Comment by Krijger** [comment]
Thanks! I actually looked for an option like that, but completely missed the preference pane not completely being shown (I scrolled the extension list, and missed the scrollbar on the outer panel). This may be a Mac OS GUI issue, because I think it should be displayed completely by default?

<img width="573" alt="Screenshot 2019-12-12 at 14 28 00" src="https://user-images.githubusercontent.com/3886732/70716048-d1255b00-1ceb-11ea-9e04-22e864d86fef.png">

I can confirm that this works.

**Comment by heckflosse** [comment]
Full CR3 support will not be possible for 5.8 => change milestone to 5.9

**Comment by Beep6581** [comment]
Clarification: metadata support is missing.

**Comment by Benitoite** [comment]
> I checked my app contents for files in it that might explain this, it may have to do with the following file tree.
> 
> ```
> └── Contents
>     │   ├── share
>     │   │   ├── mime
>     │   │   │   ├── image
>     │   │   │   │   ├── bmp.xml
>     │   │   │   │   ├── x-bzeps.xml
>     │   │   │   │   ├── x-canon-cr2.xml
>     │   │   │   │   ├── x-canon-crw.xml
> ```
> 

`share/` should be in a folder called `Resources/` under `Contents/`

![Screen Shot 2020-02-05 at 6 59 41 AM](https://user-images.githubusercontent.com/17919239/73853117-2f9b2100-47e5-11ea-9275-4ae7026d3371.png)

**Comment by mart-w** [comment]
I just realised that [exiftool](https://github.com/exiftool/exiftool) supports reading and writing metadata to and from CR3 files. Is this something that could be utilised for RawTherapee, as well?

**Comment by SchoolGuy** [comment]
I am getting started on photography with my new EOS RP. Is there anything I can do to help to get the metadata support in RawTherapee? I looked at the list of pictures which are required and I didn't find my camera so I suspect that all files needed are already provided? I would love to help as I really would prefer using an open-source-tool against the propitiatory tool from Canon... (Also this runs under Linux in contrast to the Canon Tool.)

**Comment by noirsabb** [comment]
Hi

I am trying to upload a bunch of white frame files for a 1DX Mark III (which I have access to for a while), however uploading the zipped file to filebin (about 460MB) continually fails. There was a note about uploading the file to another site, but the name of that site currently escapes me. If someone can let me know of that site, please let me know.

**Comment by Thanatomanic** [comment]
@noirsabb would it help to divide the files in a couple of separate zip files and upload those to filebin?
Also, if you're looking for specific support for your camera in terms of white levels, please open a new issue.

**Comment by noirsabb** [comment]
@Thanatomanic unfortunately upload fails after a few seconds. 

As to support for CR3 files, unfortunately as yet RT (dev, version: 5.8-2375-g6b749bcbf) displays CR3 files produced by the camera as white or washed out, although the thumbnails look OK. I can work with the raw white points to get some detail, but the results cannot be used. I followed a hack in another thread setting bpp (?) in dcraw.cpp (?) to 14, and was able to get something to work with, although I am aware CR3 support is in progress. Issue #5319 no longer encompasses (general) CR3 decoding? I will create a new one if you like.

**Comment by Thanatomanic** [comment]
CR3 decoding is working in general. I think it is better to open separate threads for specific camera's to make sure the `camconst.json` values are populated so that the colours become correct.

**Comment by aspyct** [comment]
Hello good people,

I've just compiled the dev branch on windows. I'm still getting "Exif data not available" for a CR3 file from a Canon 250D. Is that expected?

If so, I'd be willing to help solve this. Would that be feasible for someone new to the codebase, or is it an in-depth task? Any pointer is appreciated.

**Comment by Thanatomanic** [comment]
@aspyct The support is always welcome! However, we're making the [transition to use exiv2](https://github.com/Beep6581/RawTherapee/pull/5889) for metadata support. The good people there will work on CR3 support and will probably have that available by the end of March. Until then, there will be no CR3 metadata support in RawTherapee.

**Comment by aspyct** [comment]
Oh, end of March sounds great! Considering I'm not exactly up to speed with c++, it's probably best I leave this task to the pros then! I'm sure I'll find other ways to support RT in the future :)

Thanks for your prompt reply 👍

**Comment by Beep6581** [comment]
This issue added CR3 data decoding support for v5.9. Metadata support will be handled in issue #6248
