### ISSUE TITLE
newlocallab cppcheck

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#5322]
I ran cppcheck on rtgui/locallab.cc and it found two susipicious parts:

https://github.com/Beep6581/RawTherapee/blob/newlocallab/rtgui/locallab.cc#L3410
```
    // Update Sharpening GUI according to inverssha button state (to be compliant with updateSpecificGUIState function)
    if (multiImage && inverssha->get_inconsistent()) {
        sensisha->show();
    } else if (inverssha->get_active()) {
        sensisha->show();
    } else {
        sensisha->show();
}
```
Either there's a bug or one could simply write
```
sensisha->show();
```

and same thing here:
https://github.com/Beep6581/RawTherapee/blob/newlocallab/rtgui/locallab.cc#L5688

@Desmis Jacques, can you have a look please?

**Comment by Desmis** [comment]
@heckflosse 

Ingo

You are true...This strange choice is due to an "old choice" setting....
Probably ?? there are others  similar things 

Can you change ?

Thank you
jacques

**Comment by heckflosse** [comment]
@Desmis Sure I can change it, but to what? To 

```
sensisha->show();
```
?

**Comment by Desmis** [comment]
yes
