### ISSUE TITLE
Lens correction isn't applied

### ISSUE THREAD

**Issue by LowFlyer** [Beep6581/RawTherapee#5331]
Some files ( not all ) created by my Mavic 2 Pro do not show properly in RawTherapee, as if the lens correction was not applied.  ( The same file shows properly in LR )

I suspect that the problem is with the Mavic2, and am trying to get a better understanding so I can try to report the problem to DJI if needed.

A sample file and screen shot can be found here  https://filebin.net/fb9dahutojlrbmrs

Windows 10

RawTherapee Version

Version: 5.6
Branch: 5.6
Commit: 5a4ed7317
Commit date: 2019-04-20
Compiler: gcc 8.3.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.24.1
Lensfun: V0.3.2.0
Build type: release
Build flags:  -m64 -mwin32 -msse2 -mfpmath=sse -mthreads -Wno-aggressive-loop-optimizations -Wno-parentheses -std=c++11 -mtune=generic -Werror=unused-label -Wall -Wuninitialized -Wno-deprecated-declarations -Wno-unused-result -fopenmp -Werror=unknown-pragmas  -DNDEBUG  -O3 -ftree-vectorize
Link flags: -m64  -mthreads  -static-libgcc   -mtune=generic  -s  -O3  -fno-use-linker-plugin
OpenMP support: ON
MMAP support: ON

**Comment by TooWaBoo** [comment]
If your camera and/or lens is not listed in the lensfun database then you need a proper lens correction profile (.lcp) for your camera and lens. e.g one from Adobe LR. 😉
You'll find them in `C:\ProgramData\Adobe\CameraRaw\LensProfiles...` if you have installed any Adobe product.

![grafik](https://user-images.githubusercontent.com/13800920/58037850-b19bca80-7b2e-11e9-9daf-d47d1b9c3b6a.png)

**Comment by falket** [comment]
@LowFlyer 

This is a beta i've made, it fixes distortion very well but vignetting seems a little bit overcorrected.

Please test it, i don't have such drone.

[DjiMavic2pro.zip](https://github.com/Beep6581/RawTherapee/files/3224923/DjiMavic2pro.zip)

Paste the text into actioncams.xml

```
<lens>
    <maker>Hasselblad</maker>
    <model>L1D-20c &amp; compatibles</model>
    <model lang="en">fixed lens</model>
    <model lang="de">festes Objektiv</model>
    <mount>l1d20c</mount>
    #<type>equisolid</type>
    <cropfactor>2.8</cropfactor>
    <aspect-ratio>3:2</aspect-ratio>
    <calibration>
        #<distortion model="ptlens" focal="10" a="-0.017" b="0.135" c="-0.148"/>
        <distortion model="ptlens" focal="10" a="0.013" b="-0.071" c="0.021"/>
        <vignetting model="pa" focal="10.26" aperture="2.8" distance="10" k1="-1.2916209" k2="0.4334955" k3="0.0033620" />
        <vignetting model="pa" focal="10.26" aperture="2.8" distance="1000" k1="-1.2916209" k2="0.4334955" k3="0.0033620" />
        <vignetting model="pa" focal="10.26" aperture="4.0" distance="10" k1="-0.8430337" k2="-0.2003009" k3="0.2895499" />
        <vignetting model="pa" focal="10.26" aperture="4.0" distance="1000" k1="-0.8430337" k2="-0.2003009" k3="0.2895499" />
        <vignetting model="pa" focal="10.26" aperture="5.6" distance="10" k1="-0.8584973" k2="0.2175409" k3="-0.0849049" />
        <vignetting model="pa" focal="10.26" aperture="5.6" distance="1000" k1="-0.8584973" k2="0.2175409" k3="-0.0849049" />
        <vignetting model="pa" focal="10.26" aperture="8.0" distance="10" k1="-1.0385375" k2="0.8660400" k3="-0.5107065" />
        <vignetting model="pa" focal="10.26" aperture="8.0" distance="1000" k1="-1.0385375" k2="0.8660400" k3="-0.5107065" />
        <vignetting model="pa" focal="10.26" aperture="11.0" distance="10" k1="-1.0413657" k2="0.8181471" k3="-0.4115250" />
        <vignetting model="pa" focal="10.26" aperture="11.0" distance="1000" k1="-1.0413657" k2="0.8181471" k3="-0.4115250" />
    </calibration>
</lens>
```

**Comment by falket** [comment]
`<lens>
        <maker>Hasselblad</maker>
        <model>L1D-20c &amp; compatibles</model>
        <model lang="en">fixed lens</model>
        <model lang="de">festes Objektiv</model>
        <mount>l1d20c</mount>
#        <type>equisolid</type>
        <cropfactor>2.8</cropfactor>
        <aspect-ratio>3:2</aspect-ratio>
        <calibration>
            #<distortion model="ptlens" focal="10" a="-0.017" b="0.135" c="-0.148"/>
            <distortion model="ptlens" focal="10" a="0.013" b="-0.071" c="0.021"/>
           <vignetting model="pa" focal="10.26" aperture="2.8" distance="10" k1="-1.2916209" k2="0.4334955" k3="0.0033620" />
           <vignetting model="pa" focal="10.26" aperture="2.8" distance="1000" k1="-1.2916209" k2="0.4334955" k3="0.0033620" />
           <vignetting model="pa" focal="10.26" aperture="4.0" distance="10" k1="-0.8430337" k2="-0.2003009" k3="0.2895499" />
           <vignetting model="pa" focal="10.26" aperture="4.0" distance="1000" k1="-0.8430337" k2="-0.2003009" k3="0.2895499" />
           <vignetting model="pa" focal="10.26" aperture="5.6" distance="10" k1="-0.8584973" k2="0.2175409" k3="-0.0849049" />
           <vignetting model="pa" focal="10.26" aperture="5.6" distance="1000" k1="-0.8584973" k2="0.2175409" k3="-0.0849049" />
           <vignetting model="pa" focal="10.26" aperture="8.0" distance="10" k1="-1.0385375" k2="0.8660400" k3="-0.5107065" />
           <vignetting model="pa" focal="10.26" aperture="8.0" distance="1000" k1="-1.0385375" k2="0.8660400" k3="-0.5107065" />
           <vignetting model="pa" focal="10.26" aperture="11.0" distance="10" k1="-1.0413657" k2="0.8181471" k3="-0.4115250" />
           <vignetting model="pa" focal="10.26" aperture="11.0" distance="1000" k1="-1.0413657" k2="0.8181471" k3="-0.4115250" />
        </calibration>
    </lens>`

**Comment by LowFlyer** [comment]
I will try and report Thank you:)                                                                                                                                                                         Sent from my BlackBerry Smartphone

**Comment by falket** [comment]
@LowFlyer Seems to work

![Schermata a 2019-05-27 22-40-53](https://user-images.githubusercontent.com/15281362/58438719-87b74a80-80d0-11e9-8790-fb73c879ecef.png)

**Comment by Beep6581** [comment]
@falket @lowflyer submit the profile upstream to Lensfun:
https://lensfun.github.io/calibration/
