### ISSUE TITLE
Lens Correction in LR crashes RT

### ISSUE THREAD

**Issue by dunker56** [Beep6581/RawTherapee#5332]
Version Details: 5.3
Operating System name and version Windows 10, updated to concurrent.

My bug doesn't require an upload I don't think but I can give you a sample file but I believe this is a common issue.

I shoot with Pentax, K-1 and KP, it doesn't matter which. The RAW file is DNG from the camera. I can import the file first into LR and then apple a Lens Correction. I can then EXPORT the file from LR as a DNG.
**Trying to use RT with that Lens Corrected DNG file results in immediate crash.**

Of course if not visiting LR first with the DNG file natively taken from the camera without lens correction applied from LR it works fine in RT.

Thanks.

**Comment by Beep6581** [comment]
RawTherapee 5.3 is unsupported.

> Upload the raw + PP3. Make your raw and PP3 files available to us by uploading them to a file sharing service such as www.filebin.net if your bug involves a particular raw file, a particular setting, or lack of support for your raw file.

> Make sure you use the latest version of RawTherapee

http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports#Requirements_of_a_good_bug_report

>  I can import the file first into LR and then apple a Lens Correction. I can then EXPORT the file from LR as a DNG.

Sounds like the "raw file" is no longer a raw file. Upload both the original raw file and the one you exported from LR.

**Comment by heckflosse** [comment]
@dunker56 Closing as you did not provide a file as requested.
