### ISSUE TITLE
Translation in french : redimensionnement

### ISSUE THREAD

**Issue by ghost** [Beep6581/RawTherapee#5334]
There is a mispelling in the translation files in French. The word "redimensionnement" is incorrectly spelled "redimentionnement" in 3 locations.

https://github.com/Beep6581/RawTherapee/blob/b2936d185de9e672e434edf5476d02422457309d/rtdata/languages/Francais#L1020
https://github.com/Beep6581/RawTherapee/blob/b2936d185de9e672e434edf5476d02422457309d/rtdata/languages/Francais#L1789
https://github.com/Beep6581/RawTherapee/blob/b2936d185de9e672e434edf5476d02422457309d/rtdata/languages/Francais#L104

**Comment by Desmis** [comment]
For  me in french ==> **redimensionnement**

**Comment by Floessie** [comment]
@jomuller @Desmis Merged. Merci!
