### ISSUE TITLE
Newly compiled RT Dev crashes straight away with Segmentation fault

### ISSUE THREAD

**Issue by RawConvert** [Beep6581/RawTherapee#5340]
Just (29May2019) compiled RT Dev as per attached and it crashes.
[seg-fault.txt](https://github.com/Beep6581/RawTherapee/files/3233945/seg-fault.txt)

**Comment by Beep6581** [comment]
http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports

**Comment by Thanatomanic** [comment]
@RawConvert No such problems here on `dev`. You should try and compile a debug version and run RT through gdb.

**Comment by RawConvert** [comment]
@Thanatomanic , thanks.  I tried again tonight, this time no crash!!  Seems ok...
