### ISSUE TITLE
White dot artifacts caused by CIECAM02

### ISSUE THREAD

**Issue by RawConvert** [Beep6581/RawTherapee#5342]
This screen grab shows the problem -
![white-artefacts](https://user-images.githubusercontent.com/16868433/58672236-df0e2280-833d-11e9-98ad-21dc09e31fa0.png)
This is with current DEV RT 5.6-54 but also occurs with 5.6-16.  Ubuntu 16.04 LTS
50 Meg pxl 5DSR raw file
The raw and .pp3 are here -  https://filebin.net/f9kxx16vqaen990t
The filebin says 2 weeks expiry - used to be 2 months I think?
Some of the artefacts are present in the jpegs output from this raw.

**Comment by heckflosse** [comment]
@RawConvert Thanks for reporting. Bug confirmed. It's caused by CIECAM 02. I will have a look.
