### ISSUE TITLE
Vibrance causes RT to freeze

### ISSUE THREAD

**Issue by user2155** [Beep6581/RawTherapee#5346]
The bug with Vibrance - it hangs the program:

How to reproduce the bug:
Start the program, using its file browser open file "Ice-cream_car_CRW_2893.DNG" (file "Ice-cream_car_CRW_2893.DNG.pp3" should be in the same directory), in "Color" tab make "Vibrance" enable. It start processing image and never stops, consuming 50% of CPU.

The program responses for mouse clicks (I can zoom in/out, etc), but I can't quit the program, I have to terminate it. The bug occures only if skin-tone cutve HH is not linear.

In RawTherapee 5.5 I had the same bug.

Raw file,  PP3 and screenshoot:
https://filebin.net/jy63r5f3p2idtiyf/FREEZE.zip?t=ul28z6cz

RawTherapee:
Version: 5.6
Branch: 5.6
Commit: 5a4ed7317
Commit date: 2019-04-20
Compiler: gcc 8.3.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.24.1
Lensfun: V0.3.2.0
Build type: release
Build flags:  -m64 -mwin32 -msse2 -mfpmath=sse -mthreads -Wno-aggressive-loop-optimizations -Wno-parentheses -std=c++11 -mtune=generic -Werror=unused-label -Wall -Wuninitialized -Wno-deprecated-declarations -Wno-unused-result -fopenmp -Werror=unknown-pragmas  -DNDEBUG  -O3 -ftree-vectorize
Link flags: -m64  -mthreads  -static-libgcc   -mtune=generic  -s  -O3  -fno-use-linker-plugin
OpenMP support: ON
MMAP support: ON

OS:
Windows 10 Pro 64 bits 
Version    1903 (OS Build 18362.145)
BuildLab   18362.19h1_release.190318-1202
BuildLab   18362.1.amd64fre.19h1_release.190318-1202

**Comment by heckflosse** [comment]
@user2155 Thanks for reporting. Bug confirmed. Looking...

**Comment by Floessie** [comment]
Works fine on Linux.

**Comment by Beep6581** [comment]
Bug confirmed in Sabayon using `5.6-55-g`386ae560b

**Comment by Beep6581** [comment]
Fix confirmed.
