### ISSUE TITLE
Revise Color Management article

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#5351]
Revise http://rawpedia.rawtherapee.com/Color_Management
Ref: https://discuss.pixls.us/t/rt-output-profiles/12931/3

**Comment by TechXavAL** [comment]
@Beep6581 

There's a much improved and complete explanation about Color management [in the Spanish documentation](https://rawpedia.rawtherapee.com/Color_Management/es), which may solve this issue and the [issue 2198](https://github.com/Beep6581/RawTherapee/issues/2198), if you wish to take a look at it.

I'm not saying to translate it straight away, but it may offer ideas for the English documentation.

Just in case it's of any help.

**Comment by Desmis** [comment]
@Beep6581 

- the Color Management article has been revised to include the TRC (which was released in V5.8 and not documented) and has been expanded to take into account the additional "Abstract Profile" functions, and now "ICC profile creator"
https://rawpedia.rawtherapee.com/ICC_Profile_Creator
https://rawpedia.rawtherapee.com/Color_Management#Abstract_Profiles

- In addition, a general article has been written on colorimetry
https://rawpedia.rawtherapee.com/Toolchain_Pipeline#Colorimetry

- Also the Ciecam documentation has been improved with links to "Local Adjustments"
https://rawpedia.rawtherapee.com/CIECAM02


Of course we can always write something more about Color Management and Colorimetry as Xavier did @TechXavAL ... Color Management  and colorimetry are subjects of endless debates
 
The translation for the Color Management supplement will also need to be revised at some stage to improve the readability but as it is mainly background reading, it should not be a show-stopper for V5.9

jacques

**Comment by Desmis** [comment]
@Beep6581 

I rewrite (with Wayne help) the french and english "Output profile"
https://rawpedia.rawtherapee.com/Color_Management#Output_Profile

jacques

**Comment by Beep6581** [comment]
@Desmis 

The original paragraph, 

> The main histogram, navigator and clipping indicators will use either the working or the output profile, depending on your setting in Preference > [[Preferences#General_Tab|General]].

was changed to

> The main histogram and clipping indicators will also use the output profile. However, the preview image will only show those colors that can be displayed by the screen. These may be more or less than the selected output profile if the monitor profile has been configured in Preferences.

1. Why was the reference to "Navigator" removed? If not by accident, then what does the Navigator now use?
2. In the original paragraph, the part "depending on your setting in Preference > General" is obsolete, since this was replaced by the <img src="http://rawpedia.rawtherapee.com/images/0/06/Gamut-hist.png"> button in the Editor tab. However, the new paragraph doesn't explain that at all, and implies that the working profile is never used for the main histogram, Navigator or clipping indicators. Last I looked, the main histogram and Navigator use either the working profile, or the gamma-corrected output profile. Is this still accurate?

**Comment by Desmis** [comment]
@Beep6581 

It was an error due to my old French version.
I am in the process of correcting it

jacques

**Comment by Beep6581** [comment]
@Desmis thank you, looks good :+1:
