### ISSUE TITLE
Adding new locallab spot changes exposure of image

### ISSUE THREAD

**Issue by ff2000** [Beep6581/RawTherapee#5353]
version: Updated locallab branch today at 9534981127524b89876434c36b86e2fb184602ec

I edited a photo, created one locallab spot and did local adjustments. Then I wanted to edit a second area, but adding a new spot changed the exposure of the photo, even though the new spot didn't contain any adjustments.

edits after first spot:
![locallab_exposure_1](https://user-images.githubusercontent.com/1973708/59562899-42d16480-903b-11e9-8961-df3049b8c115.jpeg)

new spot added:
![locallab_exposure_2](https://user-images.githubusercontent.com/1973708/59562903-4fee5380-903b-11e9-80ca-98d54ea9d3f9.jpeg)

**Comment by Desmis** [comment]
@ff2000 
I can not do anything if I do not have the context...
Please provide raw and pp3

Thank you

**Comment by ff2000** [comment]
Hi Jaques,
I sent you a RAW + pp3, share with other devs as you need.
Here is a short video that shows the effect:
https://youtu.be/bUVbTDxJa68

**Comment by Desmis** [comment]
@ff2000 
I push a change 9a46885, I think it solved the bug

Thank you :)

jacques

**Comment by ff2000** [comment]
Thank you, it seems it is fixed now.
Couldn't trigger it anymore with several images.
