### ISSUE TITLE
handles of locallab spot interfer with crop borders

### ISSUE THREAD

**Issue by ff2000** [Beep6581/RawTherapee#5354]
locallab at 9534981127524b89876434c36b86e2fb184602ec

To reproduce:
* enable crop
* add a locallab spot
* move one of the four points of locallab spot so it sits over the crop border, then release the mouse button.
* Hover the spot point again so it gets highlighted, click and try to move it.

result: Instead of the point you move the crop.
expected result: adjustment of spot outline.

**Comment by Desmis** [comment]
@ff2000 
I can not do anything if I do not have the context...
Please provide raw and pp3

Thank you

**Comment by ff2000** [comment]
Hi Jaques,
I sent you a RAW + pp3, share with other devs as you need.
Here is a short video that shows the effect:
https://youtu.be/zuMB117qX0Y

**Comment by sguyader** [comment]
This is independent on the image and pp3, I've experienced the same issue several times with my images.

**Comment by Desmis** [comment]
@pandagrapher
Could you have a look ?

Thank you 
jacques

**Comment by Pandagrapher** [comment]
@Desmis 
I gonna try to see if I can deactivate mouse interactions with crop when using Locallab tab

Pierre

**Comment by Beep6581** [comment]
Issue confirmed in `newlocallab` `5.6-1151-g`882f14f7d.

**Comment by Hombre57** [comment]
Could you please merge with dev, the patch from issue #5415 should have fixed to problem.

**Comment by Desmis** [comment]
@Hombre57 

Done, thank you :)

**Comment by ff2000** [comment]
This seems to be fixed now. THX!
