### ISSUE TITLE
Panasonic DC-GX7MK3 lensfun support

### ISSUE THREAD

**Issue by yuzuyuzu1121** [Beep6581/RawTherapee#5355]
Panasonic GX7MK3 is not on the camera list under
- Transform -> Profiled Lens Correction

resulting no correction can by applied when using automatic selection.

Attached is the sample raw file of GX7MK3 for reference. Thank you.

Version : rawtherapee-5.6-2.fc30.x86_64

[P1002445.zip](https://github.com/Beep6581/RawTherapee/files/3301946/P1002445.zip)

**Comment by Beep6581** [comment]
@yuzuyuzu1121 http://rawpedia.rawtherapee.com/Lens/Geometry#Lensfun
