### ISSUE TITLE
RT scanning every single in the folder when I right-click > "Open in RT"

### ISSUE THREAD

**Issue by jbruchon** [Beep6581/RawTherapee#5356]
Version 5.6 on Windows 10 64-it. Every time I open a specific raw file with a right-click an "Open in RawTherapee," the program takes forever to load. I did some digging with Process Explorer and discovered that this is because RT is scanning EVERY FILE in whatever directory the raw file is located in when I'm only trying to open that one single file. Because all of these files are on a network drive over a wireless connection, this results in start times frequently in excess of 5 minutes. The program should not be looking at other files if I am asking it to work only on one specific file.

Edit: it did it again when I clicked on the "Preferences" button! Why is the program reading gigabytes of files for no useful reason?

**Comment by gaaned92** [comment]
@jbruchon
https://keybase.pub/gaaned92/RTW64NightlyBuilds/RawTherapee_dev_5.6-90-g66c9cd617_WinVista_64_190624.zip
uploaded

**Comment by gaaned92** [comment]
@jbruchon
Did you try the above build including @heckflosse correction?
Did it solved your issue?

**Comment by jbruchon** [comment]
@gaaned92 Yes, it works as expected now.

**Comment by heckflosse** [comment]
Closed as fixed.
