### ISSUE TITLE
Chromatic aberration auto-correction in RT 5.5 produces garbage for DSC-R1 SR2 file at column 3799 of 3917

### ISSUE THREAD

**Issue by dakhubgit** [Beep6581/RawTherapee#5357]
Version: 5.5
Branch: releases
Commit: d9ac23555
Commit date: 2018-12-17
Compiler: cc 8.2.0
Processor: generic
System: Linux
Bit depth: 64 bits
Gtkmm: V3.24.0
Lensfun: V0.3.2.0
Build type: Release
Build flags: -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Wdate-time -D_FORTIFY_SOURCE=2 -std=c++11  -Werror=unused-label -Wall -Wuninitialized -Wno-deprecated-declarations -Wno-unused-result -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags: -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed
OpenMP support: ON
MMAP support: ON

Linux lola 5.0.0-17-lowlatency #18-Ubuntu SMP PREEMPT Tue Jun 4 16:13:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Often (but not always so) when opening a raw SR2 file from the Sony DSC-R1 camera, there is a single pixel line in the last 10% of the image that contains seriously discolored pixels.  This ruins a lot of images unless one crops off the problem.

It does not occur with the neutral processing profile but does with the default "auto curve from image -- low iso" profile.  The trigger for this problem is the chromatic aberration auto-correction check mark in the raw processing tag.  I get the same kind of artifact at the same (or rather similar) column in the last 10% of the image for many images.  This is a serious problem for using Rawtherapee.
[rawsamples.zip](https://github.com/Beep6581/RawTherapee/files/3318770/rawsamples.zip)

**Comment by heckflosse** [comment]
@dakhubgit Use RT 5.6 or add this to your camconst.json file:

```
    { // Quality C
        "make_model": [ "Sony DSC-R1" ],
        "raw_crop": [ 0, 0, 3924, 2608 ]
    },
```

**Comment by dakhubgit** [comment]
Ingo Weyrich <notifications@github.com> writes:

> @dakhubgit Use RT 5.6 or add this to your camconst.json file:
>
> ```
>     { // Quality C
>         "make_model": [ "Sony DSC-R1" ],
>         "raw_crop": [ 0, 0, 3924, 2608 ]
>     },
> ```

"Add this to" implies editing the system file which has comments
strongly discouraging it.  It turns out that I needed to create a
~/.config/RawTherapee/camconst.json file with the contents

{"camera_constants": [
    { // Quality C
        "make_model": [ "Sony DSC-R1" ],
        "raw_crop": [ 0, 0, 3924, 2608 ]
    }
]}

something which is explained nowhere obvious but was derived by analogy
with the structure of the existing camconst.json file.

I have another problem where an image of sun-backlit poppy flowers looks
totally bland in Rawtherapee while the in-camera image is rather
powerful.  It turns out that switching off highlight reconstruction and
dialling up the raw whitepoint to 2.0 from its default 1.0 gets a rather
similar image which gets its visual appeal by drastic clipping of the
red channel.  I would assume that getting closer to camera processing
(which more likely than not is "less correct" than Rawtherapee's
downscaling of the colors) would again necessitate working on the
camera_constants, and they may depend on the color mode.  I don't have
an immediate comparison right now, but the DSC-R1 has modes "Standard",
"Vivid", and "Adobe RGB".

I may try to see whether I can provide the described sample images.

Thanks for the support!

-- 
David Kastrup

**Comment by heckflosse** [comment]
@dakhubgit Ok to close the issue?

**Comment by dakhubgit** [comment]
Ingo Weyrich <notifications@github.com> writes:

> @dakhubgit Ok to close the issue?

Oh, sorry.  Yes, the issue as such appears to be addressed in
Rawtherapee 3.6.

-- 
David Kastrup
