### ISSUE TITLE
DSC-R1 white point support

### ISSUE THREAD

**Issue by dakhubgit** [Beep6581/RawTherapee#5359]
The Sony DSC-R1 has level C support in camconst.json.  I have frequent color and exposure inconsistencies, so this seems worth of improvement.  I do suspect that some variable information is contained in the EXIF data since results may end up having quite some variation.  Nevertheless, getting started with raw whitepoints seems like a good idea.

I have taken photographs of a wall lit with flash to a degree that overexposure indication covered the full area as far as I could see.  Nevertheless, there is some variation in compression ratios suggesting that I have not always been successful in overexposing every pixel.

For the base ISO level of ISO160, I have taken examples for all of the color modes Normal, Vivid, and Adobe RGB and all apertures.  ISO200 and ISO400 have all apertures but just in Normal mode, ISO800-ISO3200 have been covered just in F2.8.  Please tell me if more samples would be required.

The samples are at [this filebin.net link](https://filebin.net/mozbe6rc6kqzs67w)

**Comment by heckflosse** [comment]
@dakhubgit Thanks for the files :+1: 
You should get better results with this entry (whitelevel changed)
```
    { // Quality C
        "make_model": [ "Sony DSC-R1" ],
        "raw_crop": [ 0, 0, 3924, 2608 ],
        "ranges": {
            "white": 16368 
        }
    },
```
