### ISSUE TITLE
Sony Cyber-shot DSC-R1 color problems

### ISSUE THREAD

**Issue by dakhubgit** [Beep6581/RawTherapee#5360]
Here is a problem with cinnabar moth caterpillars on ragwort.  The image in the preview (extract with `exiftool -b -PreviewImage DSC09675.SR2 > preview.jpg`) shows orange-black striped caterpillars corresponding to the actual color of the caterpillars.  I have not found a feasible way to get RawTherapee to convert this orange color to anything but a darker shade of yellow.  Certainly not using "Automatched Curve, ISO low", the default processor.

This is using a recent Rawtherapee from master (settings updated according to #5359 but does not make a difference).
Version: 5.6-54-g2bed5dc52
Branch: dev
Commit: 2bed5dc52
Commit date: 2019-05-26
Compiler: cc 8.3.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.24.0
Lensfun: V0.3.2.0
Build type: Debug
Build flags:  -std=c++11  -Werror=unused-label -Wall -Wuninitialized -Wno-deprecated-declarations -Wno-unused-result -fopenmp -Werror=unknown-pragmas -g -ftree-vectorize
Link flags:   
OpenMP support: ON
MMAP support: ON

[DSC09675.zip](https://github.com/Beep6581/RawTherapee/files/3334642/DSC09675.zip)

**Comment by heckflosse** [comment]
@dakhubgit Adobe ships a dcp for dsc-r1 with dng converter. Here's the howto:
http://rawpedia.rawtherapee.com/How_to_get_LCP_and_DCP_profiles

Here's before/after. Left is without dcp, right is with dcp
![grafik](https://user-images.githubusercontent.com/13733487/60269204-4b088a00-98ee-11e9-86d8-b8bb8826e4a1.png)

**Comment by dakhubgit** [comment]
> @dakhubgit Adobe ships a dcp for dsc-r1 with dng converter. Here's the howto:
> http://rawpedia.rawtherapee.com/How_to_get_LCP_and_DCP_profiles
> 
> Here's before/after. Left is without dcp, right is with dcp

The orange using the DCP is a bit more pronounced on my computer than the screenshot would suggest and does make the difference between unsuitable and reasonable.  Where do we go from here regarding general use?  The DCP is proprietary to Adobe.  Looking under Color Management/Input Profile, "Camera Standard" cannot do orange.  "No Profile" works decidedly better in that regard but the colors are somewhat garish.  Would it be feasible to cook up (possibly starting from the DCP) sort of a color matrix default for camconst.json that will work better than the current "Camera Standard"?

**Comment by heckflosse** [comment]
@dakhubgit That would be the way to go:
http://rawpedia.rawtherapee.com/How_to_create_DCP_color_profiles

**Comment by dakhubgit** [comment]
Well, as can be guessed from my choice of a 15-year old camera, that sort of equipment for absolute colometry is not quite in my price league.  Since the raw files contain a JPEG preview with the camera's idea about colorisation, the question is whether one could reasonably average the variant color models (in this case standard, vivid, AdobeRGB) from a large enough corpus of raw images.  That should make it possible to get rid of the worst offenses with regard to color, but I don't know just what kind of tools might be usable for making and refining this sort of correlation.

**Comment by Beep6581** [comment]
To improve color support of the SONY DSC-R1, use a better input profile. To get a better profile into RawTherapee we need a photograph of a color target - instructions in @heckflosse 's link.

**Comment by dakhubgit** [comment]
Here is additional info: exiftool used on the raw files for files shot with AdobeRGB mode states "Color space: uncalibrated" while files shot in Standard color mode have "Color space: sRGB" (either raw file shows Color mode: standard).  The AdobeRGB raw files are not consistent in what kind of color deviations they show in Rawtherapee.  The files in Standard mode are rendered pretty much spot-on by Rawtherapee whether using a .dcp file or not.  So it would appear that creating a "better input file" is not all that it takes: the color space needs to get recognised by the EXIF reader, and I suspect that additional information (or color tables) is hidden somewhere.

Since the JPG files are actually more accurate using AdobeRGB color space: is there any feasible way of figuring out where the additional info apparently not available to Rawtherapee is hidden?

**Comment by Beep6581** [comment]
`ColorSpace` applies to the embedded JPEG. Nothing to do with the raw data. I don't know what `ColorMode` applies to in Sony files, probably also the JPEG.
