### ISSUE TITLE
Exif support for Xiaomi Redmi Note 7 DNG

### ISSUE THREAD

**Issue by yeatzeck** [Beep6581/RawTherapee#5361]
Please add support for Xiaomi Redmi Note 7 in RawTherapee.
I uploaded to https://raw.pixls.us/ an unmodified DNG/raw photo (file: IMG_20190615_155524.dng) taken with latest OpenCamera on RN7. The phone firmware is unmodified (official global ROM, MIUI 10.3.4 based on Android 9). I can upload more raw files with corresponding JPGs if there is a need for them (OpenCamera takes JPG/DNG at once), just let me know.
Thank you very much.
Regards,

**Comment by heckflosse** [comment]
@yeatzeck The DNG you uploaded to raw.pixls.us opens fine here. What kind of support do you mean?

**Comment by yeatzeck** [comment]
Thank you for your response.

I tried RawTherapee 5.6 and the newest RawTherapee LAB. None of them shows properly Redmi Note 7 EXIF image data from DNG.

Also the "Auto-Matched Curve Low / High ISO" profile does not match the brightness, contrast nor colors of the JPG file, as it usually more or less does with NEF/JPG pair my Nikon. It looks like the profile does not work. If you want, I can provide a pair of DNG and JPG from RN7 for comparison.

I would be grateful if you would fix the EXIF data and check why the Auto-Matched Curve profile does not work.

There is also no working Lens Profile option, but from what I know from the RawTherapee documentation, other software (Lensfun) is responsible for that.

Thank you once again for your time.

With regards,

Jacek


Wysłane z aplikacji Poczta<https://go.microsoft.com/fwlink/?LinkId=550986> dla Windows 10

________________________________
Od: Ingo Weyrich <notifications@github.com>
Wysłane: Thursday, July 4, 2019 4:36:04 PM
Do: Beep6581/RawTherapee
DW: yeatzeck; Mention
Temat: Re: [Beep6581/RawTherapee] Support for Xiaomi Redmi Note 7 DNG (#5361)


@yeatzeck<https://github.com/yeatzeck> The DNG you uploaded to raw.pixls.us opens fine here. What kind of support do you mean?

**Comment by heckflosse** [comment]
About auto-matched curve: There is no jpeg embedded in the dng. Without an embedded jpeg, auto-matched curve does not work.

I will have a look about the exif.

**Comment by Beep6581** [comment]
@yeatzeck do you have access to a [color target](http://rawpedia.rawtherapee.com/How_to_create_DCP_color_profiles#Color_Targets)?

**Comment by yeatzeck** [comment]
Hi,

I don’t have access to a color target.

Sorry.

Regards,

Jacek

**Comment by Entropy512** [comment]
Hmm...  Let me guess, this is another Xiaomi product that sets an improper color matrix in the DNG?

(Improper color matrix is a well documented deficiency of their Mi Sphere 360...)

**Comment by Lawrence37** [comment]
EXIF is supported with #5889. Colors are desaturated, but it's likely due to a bad color matrix.

**Comment by Beep6581** [comment]
@Lawrence37 I tried adding an entry to camconst with the color matrix values from Adobe DNG Converter 15.5 and RT claims in the verbose console output that it picked the values up, but the preview looks identical to the stock value. The test photo I have from RPU (the cat) is not very colorful but I would expect to see some difference. Now that RT uses Exiv2, are color matrix values from camconst.json still used, and do they take precedence over any other source?

```
    {
        "make_model": [ "Xiaomi Redmi Note 7" ],
        "dcraw_matrix": [ 17904, -8510, -2730, -9956, 19269, 401, 321, -1285, 6664 ] // ColorMatrix1 using illuminant D65 from Adobe DNG Converter 15.5
        //"dcraw_matrix": [ 17421.875, -8281.25, -2656.25, -9687.5, 18750, 390.625, 312.5, -1250, 6484.375 ] // ColorMatrix1 using illuminant D65 from stock DNG
    },
```

**Comment by Lawrence37** [comment]
I also noticed the ADC matrix did not affect the colors and thought it's because the matrix is wrong too. I tried with an obviously incorrect matrix in `camconst.json` and the colors did change.
