### ISSUE TITLE
Canon EOS RP should be supported, even without .CR3 format suport

### ISSUE THREAD

**Issue by jmtilli** [Beep6581/RawTherapee#5363]
I'm using RawTherapee 5.5 and noticed it doesn't support EOS RP's RAW file format .CR3. Fair enough: I'll use the Adobe DNG converter and use DNG files in RawTherapee in the meantime and hope somebody creates an open source implementation for .CR3 in the long run.

Now, if I open a DNG file on RawTherapee, the Profiled Lens Correction doesn't detect the camera (it detects only the lens), and thus, distortions are not corrected. I have to manually select the Camera model to be "Canon EOS 6D Mark II" (has exactly same sensor as EOS RP, apart from some minor microlens adjustments related to RF mount).

Now, I understand adding support for .CR3 format might be a lot of work. However, RawTherapee should support at least automatic detection of EOS RP as the camera from Adobe DNG files. This way, lens distortions would be corrected automatically.

Before full .CR3 format support, RawTherapee should have basic EOS RP support (it can be simple copy-paste from EOS 6D Mark II support as the sensor is the exact same sensor apart from microlens adjustments).

**Comment by heckflosse** [comment]
@jmtilli RT uses [lensfun](https://github.com/lensfun/lensfun). That's the right place to get lens correction support for your camera.
