### ISSUE TITLE
RawTherapee didn't show any RAW images on AMD Ryzen 2500U Pro, Win 10

### ISSUE THREAD

**Issue by marekdovina** [Beep6581/RawTherapee#5364]
RawTherapee version 5.6
Microsoft Windows 10 Enterprise 1903 (OS Build 18362.175) 64bit
AMD Ryzen 5 PRO 2500U w/ Radeon Vega Mobile Gfx
Radeon Software Version 19.6.3

When I navigate to folder with RAW images (in my case from Samsung Galaxy S9+ in dng format), they not show in RawTherapee (cannot see, cannot edit, like they didn't exists). This is not issue on my other Intel based computer. JPG images I can see, but RAW images not. I can open RAW images with default Windows application or in Adobe app. 

![Capture](https://user-images.githubusercontent.com/5641348/60673609-6e947d00-9e78-11e9-832c-23e3e980bbf5.PNG)

[log.txt](https://github.com/Beep6581/RawTherapee/files/3359725/log.txt)

**Comment by heckflosse** [comment]
![grafik](https://user-images.githubusercontent.com/13733487/60677238-3e051100-9e81-11e9-8974-1c7cf738ecd8.png)

**Comment by marekdovina** [comment]
@heckflosse yes, it was one of first thing I checked. I did some research before I post this topic and checked all similar issues I was able to find, last steps was to check other software and I find only mentioned app worked (I did not check other paid software, used Windows default app and LR just to check if they works, I have similar issue also with other opensource software, but as I want to use RawTherapee, I focused on it)

**Comment by heckflosse** [comment]
@maweceq Can you upload such a dng to filebin.net and post the link here?

**Comment by marekdovina** [comment]
@heckflosse as I already mentioned it should be not in file itself, as I have no issue to open them and edit in RawTherapee on Intel based computer

**Comment by heckflosse** [comment]
@maweceq Just as a test, can you copy [this file](http://rawtherapee.com/shared/test_images/amsterdam.pef) into an empty folder and open the folder in RT?

**Comment by marekdovina** [comment]
@heckflosse I did it and this test file works

![Capture2](https://user-images.githubusercontent.com/5641348/60682645-5894b580-9e94-11e9-97f0-9477a739ec69.PNG)

I [share one file](https://filebin.net/msfgx5f1cj0hkefc/20190605_175412.dng?t=rnsboy8r) I know I already open and edit in RawTherapee on my Intel computer but cannot be loaded on my AMD machine

**Comment by heckflosse** [comment]
@maweceq The file you shared is a jpeg with .dng ending. Just rename dng to jpg and rt will show it.

**Comment by marekdovina** [comment]
@heckflosse Hmm what happen to it... I didn't realize it, thank you for a point.. Now I see that filesize differs from original I have on backup disk.. I have no idea what happen to all this dng files I have stored on google drive.. if this is the case than it is not RT bug but gdrive ...

**Comment by marekdovina** [comment]
finally I can confirm that google drive screw-up all my dng files and that is the real reason RawTherapee cannot process this files anymore. Thank you @heckflosse with helping me. Now I must check which images I lost definitely and which I have good backups.

**Comment by heckflosse** [comment]
@maweceq You're welcome. I hope you get your lost files back somehow.
