### ISSUE TITLE
Panasonic Lumix DC-G91 raw support (wanted)

### ISSUE THREAD

**Issue by sbolten** [Beep6581/RawTherapee#5372]
Uploaded sample raw shot with the Panasonic Lumix DC-G91 (aka G90/G95).
Asking to support this model in darktable.
If you need more samples (different crops, etc) just let me know.

Regards,
Stephan

**Comment by sbolten** [comment]
Wrong group - sorry

**Comment by Beep6581** [comment]
@sbolten regardless of group, if you have access to a color target, you could send us StdA + D50/D65 shots.

http://rawpedia.rawtherapee.com/How_to_create_DCP_color_profiles#Shooting_the_Color_Target
