### ISSUE TITLE
Save some ui space

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#5374]
A single screenshot may say more than a lot of words:
![grafik](https://user-images.githubusercontent.com/13733487/61175825-3dbdf180-a5b6-11e9-88ee-c282a8c624a3.png)

**Comment by heckflosse** [comment]
ping @Hombre57

**Comment by Hombre57** [comment]
@heckflosse I'm not at home, but I'll try to have a look tomorrow, otherwise on Monday evening.

**Comment by heckflosse** [comment]
@Hombre57 No need to hurry! I was just an idea...

**Comment by Beep6581** [comment]
This would remove functionality (the path bar) from the Filmstrip. Agreed in IRC to close the issue.
