### ISSUE TITLE
Fuji X-T30 X-Rite ColorChecker Passport

### ISSUE THREAD

**Issue by GSpronck** [Beep6581/RawTherapee#5387]
Recently I bought a Fuji X-T30 camera. The colors in RawTherapee were a bit messy and I had a X-Rite ColorChecker Passport so I diceded to create my own color profiles.

I took shots of it in the sun and using and old fashion light bulb and a slightly more modern Philips HalogenA 100W light. 

I had the opportunity to measure both lights in a freshly calibrated integraing sphere. Therefore I mentionned their color temperatures which can be regarded accrate to about +/- 15 to 20K. I took the photoghaps in a room which has black walls, floor and ceiling, therefore the influence of stray light is negligible. 

For the exposure settings I used a graycard and did expusore bracketing to +/- 1 stop in 1/3 stop increments.

I hope it's uasble for you. If you made a profile with this pictures, can you provide it to mee? I did make my own, but by using DNG-converter, X-Rite's own software and probably and not that much experiance with creating color profiles.

https://wetransfer.com/downloads/01839e3b73dde171ce801678f5401a3b20190723174209/b7e9c7f9468e133fe9ff8b73a8b6858120190723174209/da5766

**Comment by Beep6581** [comment]
@GSpronck thank you, I will take a look soon.

**Comment by Beep6581** [comment]
@GSpronck could you re-upload the files please?

**Comment by GSpronck** [comment]
You can download the files until 17 september using the following link:

https://wetransfer.com/downloads/d0421c0b0eb1dd3684d9050dec37ca1620190910171156/fc25d43627f789d2233586cb1100777620190910171156/5fa539

**Comment by Beep6581** [comment]
![screenshot_20200124_010958](https://user-images.githubusercontent.com/5844619/73034788-42f1d800-3e46-11ea-9f01-d5a9f233f630.png)
