### ISSUE TITLE
Backwards thumbnail selection using Shift-key unexpectedly shifts starting point of selection

### ISSUE THREAD

**Issue by Thanatomanic** [Beep6581/RawTherapee#5389]
To reproduce:
1. Go to thumbnail browser
2. Select a photo
3. Press shift
4. Select a few photo's earlier
5. Keep holding shift
6. Select even earlier photo's

Expected behaviour: photo selected in (2) stays the reference point of the selection
Observed behaviour: photo selected in (4) becomes new reference point of the selection

The expected behaviour comes from the behaviour observed in Windows Explorer, where your range selection is always relative to the file that was selected first. I do not know how the file manager in Linux or OSX behaves.

Tested as always on latest dev on Win10 MSYS2 build.

**Comment by heckflosse** [comment]
Confirmed

**Comment by heckflosse** [comment]
@Thanatomanic 
Can you try this patch please?
```diff
diff --git a/rtgui/thumbbrowserbase.cc b/rtgui/thumbbrowserbase.cc
index 8392e1b61..1800d6460 100644
--- a/rtgui/thumbbrowserbase.cc
+++ b/rtgui/thumbbrowserbase.cc
@@ -178,15 +178,18 @@ void ThumbBrowserBase::selectRange (ThumbBrowserEntryBase* clicked, bool additio
     if (!additional || !lastClicked) {
         // Extend the current range w.r.t to first selected entry.
         ThumbIterator front = std::find(fd.begin(), fd.end(), selected.front());
+        ThumbIterator back = std::find(fd.begin(), fd.end(), selected.back());
         ThumbIterator current = std::find(fd.begin(), fd.end(), clicked);
 
         if (front > current) {
-            std::swap(front, current);
+            front = current;
+        } else {
+            back = current;
         }
 
         clearSelection(selected);
 
-        for (; front <= current && front != fd.end(); ++front) {
+        for (; front <= back && front != fd.end(); ++front) {
             addToSelection(*front, selected);
         }
     } else {

```

**Comment by Thanatomanic** [comment]
The patch solves the backwards selection issue. However, when you select backward and then forward, the backwards selected items stay selected. This is also not common behaviour in Windows (and possibly other OSes).

**Comment by heckflosse** [comment]
> when you select backward and then forward, the backwards selected items stay selected. This is also not common behaviour in Windows (and possibly other OSes).

Confirmed. My patch didn't change this behaviour.

**Comment by heckflosse** [comment]
@Thanatomanic Ok to commit my patch? It solves one case at least.

**Comment by Thanatomanic** [comment]
@heckflosse Okay. I can make a new issue for the other selection problem.
