### ISSUE TITLE
Canon EOS Rebel T7

### ISSUE THREAD

**Issue by MoralCode** [Beep6581/RawTherapee#5400]
uploaded a couple `.CR2`s to pixls.us

**Comment by Beep6581** [comment]
The Canon EOS Rebel T7 works fine in 5.6 - image looks fine, no highlight issues, and Exif intact. The issue lacks any indication of what could be lacking.

@MoralCode if you want to help improve Canon EOS Rebel T7 support, provide a set of [white frames](http://rawpedia.rawtherapee.com/Adding_Support_for_New_Raw_Formats) (LENR on and off) and a photo of a [color target](http://rawpedia.rawtherapee.com/How_to_create_DCP_color_profiles).
