### ISSUE TITLE
2 bugs in colour toning

### ISSUE THREAD

**Issue by cuniek** [Beep6581/RawTherapee#5403]
OS: win 7 64
version: RawTherapee_dev_5.6-219-g972d6907d_W64_SSE4_190806.zip as well as official 5.6 release

bug 1) 
-open any file and turn on Colour Toning
-use "saturation 2 colours" or "Colour balance..." mode
-strength slider doesn't work as intented (0=no effect, 1=maximum effect, therefore no difference between 1 and 100)

bug 2)
-open any file and turn on Colour Toning
-use "Colour balance..." mode
-apply some changes (especially in shadows) with "Preserve Luminance" turned on, and "Strength" different than 100 = dramatic color errors as well as squares in top-left corner (multithreading?)

adding some screenshots

![2019-08-08_110137](https://user-images.githubusercontent.com/26029842/62689985-219e4c00-b9cc-11e9-96d3-0922b1609f0a.jpg)

![2019-08-08_110234](https://user-images.githubusercontent.com/26029842/62690002-2bc04a80-b9cc-11e9-9840-34259b3d2905.jpg)

**Comment by heckflosse** [comment]
Closed by accident, the fix is for bug 1)

**Comment by Thanatomanic** [comment]
There's probably something wrong with the strength slider in the second case too. For highlights and midtones it doesn't do anything and for shadows it screws things up.

**Comment by heckflosse** [comment]
The fix from above partly fixes bug 2) as well (the squares in top-left corner). For the remaining bug I need help from @Desmis

**Comment by Thanatomanic** [comment]
~~I think there is an uninitialized variable here:~~

EDIT: Nevermind... still looking

**Comment by heckflosse** [comment]
This kind of fixes it:

```diff
diff --git a/rtengine/improcfun.cc b/rtengine/improcfun.cc
index 8d6272a06..d5d69e933 100644
--- a/rtengine/improcfun.cc
+++ b/rtengine/improcfun.cc
@@ -3951,9 +3951,9 @@ void ImProcFunctions::toningsmh(float r, float g, float b, float &ro, float &go,
         // b = CLIP(b);
     }
 
-    ro = r;
-    go = g;
-    bo = b;
+    ro = std::max(r, 0.f);
+    go = std::max(g, 0.f);
+    bo = std::max(b, 0.f);
 }
 
 /**

```

**Comment by Thanatomanic** [comment]
Possibly a better one, copying over the logic from the treatment of the hightlights:

```diff
diff --git a/rtengine/improcfun.cc b/rtengine/improcfun.cc
index 8d6272a06..9615714e3 100644
--- a/rtengine/improcfun.cc
+++ b/rtengine/improcfun.cc
@@ -3785,11 +3785,12 @@ void ImProcFunctions::toningsmh(float r, float g, float b, float &ro, float &go,
 
     {
         const float corr = 20000.f * RedLow * kl * rlo;
+
         if (RedLow > 0.f) {
+            r += corr;
+        } else {
             g -= corr;
             b -= corr;
-        } else {
-            r += corr;
         }
 
         // r = CLIP(r);
@@ -3799,27 +3800,27 @@ void ImProcFunctions::toningsmh(float r, float g, float b, float &ro, float &go,
 
     {
         const float corr = 20000.f * GreenLow * kl * rlo;
+
         if (GreenLow > 0.f) {
+            g += corr;
+        } else {
             r -= corr;
             b -= corr;
-        } else {
-            g += corr;
         }
 
         // r = CLIP(r);
-        // b = CLIP(b);
         // g = CLIP(g);
+        // b = CLIP(b);
     }
 
-
     {
-        const float corr = 20000.f * BlueLow * kl * rlob;
+        const float corr = 20000.f * BlueLow * kl * rlo;
 
         if (BlueLow > 0.f) {
+            b += corr;
+        } else {
             r -= corr;
             g -= corr;
-        } else {
-            b += corr;
         }
 
         // r = CLIP(r);

**Comment by heckflosse** [comment]
@Thanatomanic Great :+1: for commit

**Comment by Desmis** [comment]
I am not at home, I used my Smartphoe to get Internet

This modification is good :)

jacques
