### ISSUE TITLE
Difficulties to merge dev into newlocallab

### ISSUE THREAD

**Issue by Desmis** [Beep6581/RawTherapee#5405]
@heckflosse 
Ingo

You have profoundly changed, "dirpyr_equalizer.cc" (and .h)
With Locallab I used a modified (with huge modifications).
With my current poor means, I am not at home, and have only limited resources...I cannot merge "locallab" with "dev"

Could you help me ?

Thank you

jacques

**Comment by heckflosse** [comment]
@Desmis Jacques, I will have a look now

**Comment by Desmis** [comment]
@heckflosse 

Thank you...
jacques

**Comment by heckflosse** [comment]
@Desmis Jacques, I merged. I hope everything works correctly

**Comment by Desmis** [comment]
@heckflosse 

Ingo

All works, thank you very much...

But works with a 4G connexion to get internet on my old PC, it is very very difficult...

Thank you again

jacques
