### ISSUE TITLE
Panasonic DC-GF10

### ISSUE THREAD

**Issue by falket** [Beep6581/RawTherapee#5411]
I post an issue here for support of Panasonic DC-GF10.

Sample just uploaded at raw.pixls.us, currently colors are not that great.

As soon as i can (camera is not mine) i'll upload also 3:2 16:9 and 1:1 .

Thank you in advance.

**Comment by Beep6581** [comment]
5.6:
![screenshot_20190814_115942](https://user-images.githubusercontent.com/5844619/63012756-0f6c5400-be8b-11e9-9c40-74d4385d85a0.png)

`5.6-242-g`6d777ce94:
![screenshot_20190814_115908](https://user-images.githubusercontent.com/5844619/63012755-0f6c5400-be8b-11e9-80b2-e4dbc5ed3a5b.png)
