### ISSUE TITLE
On preview widgets are not clipped to ImageArea

### ISSUE THREAD

**Issue by Hombre57** [Beep6581/RawTherapee#5418]
Widgets gets drawn over top toolbar buttons, e.g. with the Gradient widgets.

![unclipped-widgets](https://user-images.githubusercontent.com/13788115/63224805-b6255d00-c1c9-11e9-8204-cd42c54e15e3.jpg)

Windows7 / Gtkmm: V3.22.2 here. @Beep6581 @TooWaBoo Could you confirm on your side to ? What's your Gtkmm version ?

**Comment by Hombre57** [comment]
@heckflosse @Beep6581 Fixed in branch `clipped-main-crop-window`. I'll commit tonight if no one objects.

**Comment by TooWaBoo** [comment]
@Hombre57 
Can not reproduce with Gtkmm: V3.24.1 on Win10.

**Comment by Hombre57** [comment]
@TooWaBoo Thanks for confirming my guess. I'll still commit, as it doesn't harm.

**Comment by Hombre57** [comment]
Committed to dev ( 5b320c9e3524fa7244307a9000d170ad9987ebde )
