### ISSUE TITLE
Strange things in the code

### ISSUE THREAD

**Issue by shlyakpavel** [Beep6581/RawTherapee#5423]
https://github.com/Beep6581/RawTherapee/blob/b6d333ee72dcae2b57a7048a367933be8e89d9bf/rtgui/thresholdselector.cc#L635
https://github.com/Beep6581/RawTherapee/blob/b6d333ee72dcae2b57a7048a367933be8e89d9bf/rtgui/thresholdselector.cc#L651
How are these possible inside the switch-case?

**Comment by Hombre57** [comment]
@shlyakpavel Wow ! Don't know what I did here, I'd say incomplete code refactoring. Thanks for the report, I'll fix that asap.

**Comment by Hombre57** [comment]
@shlyakpavel Fixed in commit ec818167166b4ed9f6b073c6a0e54a8d2555bdc8, closing.
