### ISSUE TITLE
Custom default profile 

### ISSUE THREAD

**Issue by orwell1984** [Beep6581/RawTherapee#5432]
I'd love to be able to set my custom saved profile as a default. I don't think it's possible now.

**Comment by heckflosse** [comment]
![grafik](https://user-images.githubusercontent.com/13733487/64075416-48dcf600-ccb8-11e9-84ed-8f297f89a155.png)

**Comment by orwell1984** [comment]
@heckflosse  @Beep6581 what I meant is that in this menu, I can't navigate to some folder and take a .pp3 file to set as default.

**Comment by Beep6581** [comment]
@orwell1984 this is clearly explained in the documentation.
