### ISSUE TITLE
Hasselblad H6D-100cMS pixelshift files do not decode correctly

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#5434]
I will try to fix that. I will start with a code review of the hasselblad_load_raw() function to get better readable code.

**Comment by Thanatomanic** [comment]
The effect of the wrong decode is actually quite nice. Can't we keep it? 😉 

![image](https://user-images.githubusercontent.com/6567747/64322065-1ede4900-cfc2-11e9-9c7e-6c57046d4643.png)

**Comment by ahoenselaar** [comment]
The right-shifting behavior in the multi-shot codepath looks strange:
https://github.com/Beep6581/RawTherapee/blob/dev/rtengine/dcraw.cc#L2469
Why encode the noisy LSB only to shift it out eventually?
It is also not clear how high local contrast can be encoded correctly. After the right-shift, the Huffman encoded diff can correct the predicted pixel value only by +/- 16,384, or half the required range.
In fact, the artifacts do appear after decoding highlights.

**Comment by ahoenselaar** [comment]
Removing the right-shifting brings the levels in line with Phocus. Adjusting the predictor to match lossless JPEG predictor 5 fixes the artifact. It raises a new issue, though, as the predicted values wraps around in very bright parts of the image. Likely, the predictor used by Hasselblad has some additional tweaks.

https://github.com/ahoenselaar/RawTherapee/commit/7885e113b8835c367c8150c2a400ec755cbca1c2

![image](https://user-images.githubusercontent.com/3757431/66264972-16448280-e7bb-11e9-9349-493824bbd584.png)

**Comment by heckflosse** [comment]
@ahoenselaar Thanks for working on this issue :+1:
Unfortunately I can not test atm because I'm on holidays and my laptop has only 3GB RAM, which is not enough for this huge files

**Comment by ahoenselaar** [comment]
https://github.com/ahoenselaar/RawTherapee/commit/de1c04b6336aef0cf52a477b7924952995c7c32e  reverts the predictor to the same one used for non-pixelshift files and results in correct decoding without artifacts. I wonder why the predictor was changed in the original dcraw commit that added pixelshift support.
![Screenshot_2019-10-19_11-35-14](https://user-images.githubusercontent.com/3757431/67150505-b6db7d80-f264-11e9-8f99-01c41a2e130e.png)
