### ISSUE TITLE
Make histogram lines thicker and blue histogram lighter

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#5438]
http://rawpedia.rawtherapee.com/Editor#Main_Histogram

When making screenshots for RawPedia, I had to make small changes to the main histogram:
- I changed the blue histogram from `0.0, 0.0, 1.0` to `0.0, 0.4, 1.0` as the pure-blue is difficult to see.
- I changed the line thickness to 2px.
I made these changes because the vanilla histogram, especially the blue one, is difficult to see in anything but a dark environment (I'm writing this from the patio, calibrated screen on max brightness), even more so when printed on paper from RawPedia.

```diff
diff --git a/rtgui/histogrampanel.cc b/rtgui/histogrampanel.cc
index 12da0cc0d..d733e333f 100644
--- a/rtgui/histogrampanel.cc
+++ b/rtgui/histogrampanel.cc
@@ -142,7 +142,7 @@ HistogramPanel::HistogramPanel ()
     showGreen->set_image (showGreen->get_active() ? *greenImage : *greenImage_g);
     showBlue->set_image  (showBlue->get_active()  ? *blueImage  : *blueImage_g);
     showValue->set_image (showValue->get_active() ? *valueImage : *valueImage_g);
-    showChro->set_image  (showChro->get_active()   ? *chroImage : *chroImage_g);
+    showChro->set_image  (showChro->get_active()  ? *chroImage  : *chroImage_g);
     showRAW->set_image   (showRAW->get_active()   ? *rawImage   : *rawImage_g);
     if (options.histogramDrawMode == 0)
         showMode->set_image(*mode0Image);
@@ -471,7 +471,7 @@ void HistogramRGBArea::updateBackBuffer (int r, int g, int b, const Glib::ustrin
         cc->set_operator (Cairo::OPERATOR_OVER);
 
         cc->set_antialias(Cairo::ANTIALIAS_NONE);
-        cc->set_line_width (1.0 * s);
+        cc->set_line_width (2.0 * s);
 
         if ( r != -1 && g != -1 && b != -1 ) {
             if (needRed) {
@@ -502,7 +502,7 @@ void HistogramRGBArea::updateBackBuffer (int r, int g, int b, const Glib::ustrin
 
             if (needBlue) {
                 // Blue
-                cc->set_source_rgb(0.0, 0.0, 1.0);
+                cc->set_source_rgb(0.0, 0.4, 1.0);
                 if (options.histogramDrawMode < 2) {
                     cc->move_to(b * (winw - 1.) / 255.0 + 0.5*s, 0);
                     cc->line_to(b * (winw - 1.) / 255.0 + 0.5*s, winh - 0);
@@ -962,7 +962,7 @@ void HistogramArea::updateBackBuffer ()
 
         if (needBlue) {
             drawCurve(cr, bhchanged, realhistheight, w, h);
-            cr->set_source_rgb (0.0, 0.0, 1.0);
+            cr->set_source_rgb (0.0, 0.4, 1.0);
             cr->stroke ();
             drawMarks(cr, bhchanged, realhistheight, w, ui, oi);
         }
@@ -990,7 +990,7 @@ void HistogramArea::drawCurve(Cairo::RefPtr<Cairo::Context> &cr,
 {
     double s = RTScalable::getScale();
 
-    cr->set_line_width(s);
+    cr->set_line_width(2.0 * s);
     cr->move_to (0, vsize - 1);
     scale = scale <= 0.f ? 0.001f : scale; // avoid division by zero and negative values
 
```

- Before
![screenshot_20190904_153015](https://user-images.githubusercontent.com/5844619/64259396-459c7100-cf29-11e9-8f93-8e1e29a9f187.png)
- After
![screenshot_20190904_153026](https://user-images.githubusercontent.com/5844619/64259407-4a612500-cf29-11e9-9b01-5cd1527bc637.png)
- Before
![screenshot_20190904_153206](https://user-images.githubusercontent.com/5844619/64259421-4fbe6f80-cf29-11e9-8758-d728155535fc.png)
- After
![screenshot_20190904_153200](https://user-images.githubusercontent.com/5844619/64259429-53ea8d00-cf29-11e9-8b53-00867ba8ac17.png)

Onions?

**Comment by heckflosse** [comment]
Garlic

**Comment by Floessie** [comment]
I like the thinner lines better, but the lighter blue is a winner.

**Comment by Thanatomanic** [comment]
I agree with @Floessie, the blue is great, but the thicker lines make the whole thing look a little cramped when you minimize the size of the histogram.

**Comment by Entropy512** [comment]
I personally liked the thicker lines, at least in the screenshots.

But additional enhancements can wait for 5.8 - I might also fiddle with that a bit when I get back.  Maybe having the thickness depend on the histogram size would solve the issue of it being cramped when the histogram is small?
