### ISSUE TITLE
Crop area not shown on File Browser window thumbnails.

### ISSUE THREAD

**Issue by abertens** [Beep6581/RawTherapee#5440]
Hi there,

I have just realized that since commit  "Fix crash while rotating several thumbnails in File Browser" (ce04447c7a98b675071f565b0dfe38aedcf41fd9) from Sep 3, 2019, crop area is not shown anymore on File Browser window thumbnails.
On Editor window, the crop area is shown correctly.

Is this on purpose or a side effect?

My platform is Linux, Debian 10, XFCE:
Version: 5.6-274-gce04447c7
Branch: 5.6-274-gce04447c7
Commit: ce04447c7
Commit date: 2019-09-03
Compiler: cc 8.3.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.24.0
Lensfun: V0.3.2.0
Build type: Release
Build flags:  -std=c++11 -march=native -Werror=unused-label -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON

Regards,
Andres Bertens

**Comment by abertens** [comment]
@heckflosse
Thank you; it's ok now!
I do not know if it is worth to note that now the crop border area is not shown with a dotted line.

Regards,
Andres

**Comment by heckflosse** [comment]
@abertens I will have a look
