### ISSUE TITLE
Tool Shortcuts

### ISSUE THREAD

**Issue by slarti-zak** [Beep6581/RawTherapee#5442]
I propose (customizable) shortcuts for all tools, not only crop/whitebalance/straighten tools that interact with the screen using a picker or crop area.

The behavior would be that pressing a tool shortcut would jump to the tool in the tools panel and open it if it was collapsed.

Maybe also include a keyboard modifier to toggle enable/disable state of the tool to quickly compare the effect of the tool.

**Comment by Beep6581** [comment]
Not doable, and duplicate of #1472

**Comment by slarti-zak** [comment]
Sorry that I have expressed myself in an unclear way. I mainly opened this issue to propose that all tools (noise reduction, exposure, ...) should have shortcuts. They could be hardcoded in a first step.

#1472 would of course be nice for this but not mandatory. It could be done in a second step.
