### ISSUE TITLE
Flatfield on HDR DNG

### ISSUE THREAD

**Issue by nvki** [Beep6581/RawTherapee#5443]
I cant get flatfield correction with HDR .dng files to work, even with the flatfield image converted to the same format. As it was claimed to work in the 4.1 release notes I am wondering what I might be doing wrong?

The raw files I used for testing can be found [here](https://1drv.ms/u/s!AmGpeugw5ph9gfcdHbB7bcYhcHRPKQ?e=F6DIiO)

**Comment by heckflosse** [comment]
@nvki Iirc, flat fields and the images they are applied to must have same dimensions, which is not the case in your example files.

**Comment by nvki** [comment]
oh damn, I totally forgot that hdrmerge performs alignment and cropping per default. Thanks for the clarification, will try it asap!

**Comment by nvki** [comment]
yep, just as @heckflosse said I messed up the image dimensions. this issue can be marked closed
