### ISSUE TITLE
non-raw photo without exif data: RT does not record in software section

### ISSUE THREAD

**Issue by arturoisilvia** [Beep6581/RawTherapee#5466]
If a 'jpg' (non-raw) photo does not have any exif data, when re-processing it in RawTherapee and saving it, you should embed your stamp in the software section of the exif data: 'Software: RawTherapee 5.7'

Version: 5.7
Branch: releases
Commit: f335efe6a
Commit date: 2019-09-10
Compiler: x86_64-w64-mingw32-gcc\ 8.2.0
Processor: generic x86
System: Windows
Bit depth: 64 bits

**Comment by Beep6581** [comment]
Subjective, and falls under #3801
