### ISSUE TITLE
Travis CI broken due to desktop file

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#5470]
Updating our desktop file to version 1.1 in PR #5460 broke Travis CI, meaning automated builds fail.

```text
Desktop file: /work/appimage/RawTherapee.AppDir/rawtherapee.desktop
/work/appimage/RawTherapee.AppDir/rawtherapee.desktop: error: value "1.1" for key "Version" in group "Desktop Entry" is not a known version
/work/appimage/RawTherapee.AppDir/rawtherapee.desktop: warning: key "Keywords" in group "Desktop Entry" is a reserved key for KDE
ERROR: Desktop file contains errors. Please fix them. Please see
       https://standards.freedesktop.org/desktop-entry-spec/1.0/n       for more information.
```

https://api.travis-ci.org/v3/job/588727835/log.txt

Seems we are limited to what CentOS7 supports, which is desktop-file-utils-0.23.2
https://centos.pkgs.org/7/centos-x86_64/desktop-file-utils-0.23-2.el7.x86_64.rpm.html

Solutions:
1. Revert to Desktop Entry Specification 1.0.
1. Get CentOS to support Desktop Entry Specification 1.1.
1. Skip desktop file validation.
1. Drop AppImage support for CentOS.

I assume there is no quick fix for 2, maybe 3 is possible @aferrero2707 ?
@scx could you do 1?

**Comment by aferrero2707** [comment]
We could update the desktop file validation tool from sources on the CentOS system used for building, but I guess that the resulting AppImage will then not be compatible anymore with several old systems that do not support version 1.1 of the desktop entry specification.

Is there a strong reason for this version update?

**Comment by scx** [comment]
@Beep6581 
> could you do 1?

It really shouldn't be a problem for EL7.

```
$ cat /etc/system-release
CentOS Linux release 7.6.1810 (Core) 
$ curl https://raw.githubusercontent.com/Beep6581/RawTherapee/851a12e165c50333dcd779f78ea0658c38798972/rtdata/rawtherapee.desktop.in -s -o rawtherapee.desktop
$ desktop-file-validate rawtherapee.desktop
$ echo $?
0
$ grep '^Version=' rawtherapee.desktop
Version=1.1
```
```
$ cat /etc/system-release
Red Hat Enterprise Linux Server release 7.7 (Maipo)
$ curl https://raw.githubusercontent.com/Beep6581/RawTherapee/851a12e165c50333dcd779f78ea0658c38798972/rtdata/rawtherapee.desktop.in -s -o rawtherapee.desktop
$ desktop-file-validate rawtherapee.desktop
$ echo $?
0
$ grep '^Version=' rawtherapee.desktop
Version=1.1
```

As you can see, `Version` `1.1` is valid even for EL7:
```
$ desktop-file-edit --set-key=Version --set-value=2.0 rawtherapee.desktop
rawtherapee.desktop: error: value "2.0" for key "Version" in group "Desktop Entry" is not a known version
Error on file "rawtherapee.desktop": Failed to validate the created desktop file
$ desktop-file-edit --set-key=Version --set-value=1.2 rawtherapee.desktop
rawtherapee.desktop: error: value "1.2" for key "Version" in group "Desktop Entry" is not a known version
Error on file "rawtherapee.desktop": Failed to validate the created desktop file
$ desktop-file-edit --set-key=Version --set-value=1.1 rawtherapee.desktop
$ echo $?
0
```

And of course, the validation process works fine, because it will fail for unknown versions:

```
$ sed -i -re 's/^(Version=).*/\12.0/' rawtherapee.desktop
$ grep '^Version=' rawtherapee.desktop
Version=2.0
$ desktop-file-validate rawtherapee.desktop
rawtherapee.desktop: error: value "2.0" for key "Version" in group "Desktop Entry" is not a known version
$ echo $?
1
```
```
$ sed -i -re 's/^(Version=).*/\11.2/' rawtherapee.desktop
$ grep '^Version=' rawtherapee.desktop
Version=1.2
$ desktop-file-validate rawtherapee.desktop
rawtherapee.desktop: error: value "1.2" for key "Version" in group "Desktop Entry" is not a known version
$ echo $?
1
```

So, it looks like this is an AppImage issue.
However, it should be possible to change the Version number to `1.0`, although some software may ignore `Keywords` then.
Please note that the `Version` field isn't even mandatory, so it's often ignored or just doesn't matter.
The only problem I can imagine is about the Trinity desktop environment. Because it is based on KDE 3, it may still use the old `Keywords` variant, in which values were separated by commas instead of semi-colons.
```
$ desktop-file-edit --set-key=Version --set-value=1.0 rawtherapee.desktop
$ grep '^Version=' rawtherapee.desktop
Version=1.0
$ desktop-file-validate rawtherapee.desktop
$ echo $?
0
```

@aferrero2707 
> Is there a strong reason for this version update?

I changed the `Version` number mainly because it standardize the `Keywords` key.
https://specifications.freedesktop.org/desktop-entry-spec/1.1/apfs02.html
Previously, it was just an extension used by KDE.
https://specifications.freedesktop.org/desktop-entry-spec/1.0/apb.html

Anyway, if `Version` `1.1` works for EL7, then it should work as well for any other current desktop-oriented distribution. To be honest, I doubt that RawTherapee could run on any distribution older than EL7 (which was released in 2014!).

**Comment by Beep6581** [comment]
So let's get rid of the keywords section, reduce the number of potential problems and required maintenance, and downgrade to 1.0.

**Comment by scx** [comment]
According to the desktop-file-utils changelog, full support for version 1.1 desktop files was introduced in `0.23`, which was released in 2016.
https://gitlab.freedesktop.org/xdg/desktop-file-utils/blob/0dbfdfe12e320487735a05ef9b436ce144ee2633/NEWS#L29
This package is available in EL7 and Debian 9 Stretch (oldstable).

EL 7 was released in 2014 with desktop-file-utils `0.21`. This package has been updated to `0.22` in EL 7.2, then to `0.23` in EL 7.4.
EL 7.0-7.1: desktop-file-utils `0.21`
EL 7.2-7.3: desktop-file-utils `0.22`
EL 7.4-7.7: desktop-file-utils `0.23`
Generally speaking, CentOS provides support only for the latest minor release. The same applies to EPEL (Extra Packages for Enterprise Linux).
RHEL, on the other hand, offers Extended Update Support Add-on. However, even with EUS, support for EL 7.3 expired on November 30, 2018.
https://access.redhat.com/support/policy/updates/errata#Extended_Update_Support
There is also something called `Update Services for SAP Solutions Add-on`. It should provide support for EL 7.2 until November 30, 2019, and support for EL 7.3 until November 30, 2020.
https://access.redhat.com/support/policy/updates/errata#Update_Services_for_SAP_Solutions
However, I sincerely doubt that anyone would use RawTherapee in such configuration. It is like playing the latest games on Windows Embedded POSReady 2009 (extended support ended on April 9, 2019) or Windows Server 2003 R2 (extended support ended on July 14, 2015). Nobody really do that.

**Comment by Beep6581** [comment]
> I sincerely doubt that anyone would use RawTherapee in such configuration

I agree, CentOS seems to be anything but a photography platform, but then again if we can keep supporting it though the minimal effort required to revert our Desktop file spec from 1.1 to 1.0 then why not.

**Comment by scx** [comment]
> So let's get rid of the keywords section, reduce the number of potential problems and required maintenance, and downgrade to 1.0.

I'd keep the `Keywords` section, and downgrade the `Version` number to `1.0`.
Keywords are important because they affect the search results in Gnome Software and similar applications.
Alternatively, we can move `Keywords` to the AppData file.
https://www.freedesktop.org/software/appstream/docs/chap-CollectionData.html#tag-ct-keywords

**Comment by Beep6581** [comment]
@scx so `Keywords=raw;photo;photography;develop;pp3;graphics;` would pass validation when using `Version=1.0` even though it might fail to be parsed by Trinity? If so, I can revert the keywords line.

**Comment by scx** [comment]
> @scx so `Keywords=raw;photo;photography;develop;pp3;graphics;` would pass validation when using `Version=1.0` even though it might fail to be parsed by Trinity? If so, I can revert the keywords line.

Yes, the `Keywords` field is fine even for `Version` `1.0`. It was just not standardized at the time. The worst thing that can happen is a warning, but definitely not a validation failure.
```
$ desktop-file-edit --set-key=Version --set-value=1.0 rawtherapee.desktop
$ grep '^Version=' rawtherapee.desktop
Version=1.0
$ grep '^Keywords=' rawtherapee.desktop
Keywords=raw;photo;photography;develop;pp3;graphics;
$ desktop-file-validate rawtherapee.desktop
$ echo $?
0
```

**Comment by Beep6581** [comment]
Issue fixed, closing.
