### ISSUE TITLE
Last step remains visible in progress bar when invoking external editor

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#5475]
Open an image in the editor and hit ctrl+e to open it in an external program. The progress bar shows several steps, and the last step remains visible after the external editor is launched. I have to trigger a new event for the progress bar to be cleared.

**Comment by Beep6581** [comment]
This bug was already present in 5.7. The last step remains visible in the progress bar, whatever it was.

**Comment by Beep6581** [comment]
This clears the progress bar:
```diff
diff --git a/rtgui/editorpanel.cc b/rtgui/editorpanel.cc
index 6aab153a1..f023ebd76 100644
--- a/rtgui/editorpanel.cc
+++ b/rtgui/editorpanel.cc
@@ -2079,6 +2079,7 @@ bool EditorPanel::idle_sentToGimp (ProgressConnector<int> *pc, rtengine::IImagef
 {
     img->free ();
     int errore = pc->returnValue();
+    setProgressState(false);
     delete pc;
 
     if (!errore) {
```

**Comment by heckflosse** [comment]
@Beep6581 Please push!
