### ISSUE TITLE
Please allow the crop aspect ratio to be unlocked by default

### ISSUE THREAD

**Issue by przepompownia** [Beep6581/RawTherapee#5476]
Hello

I did not found how to customize this behavior in the user settings of v 5.7 so I suspect that is currently impossible. Each time I want to open new image to crop, I have to remember about unlock the aspect ratio manually.

Regards

**Comment by heckflosse** [comment]
@przepompownia

Save a profile with lock disabled and set it as default profile in preferences.

**Comment by przepompownia** [comment]
Thanks!
