### ISSUE TITLE
NewLocalLab RT 5.7-1149: Green frame when processing Canon CR2

### ISSUE THREAD

**Issue by arturoisilvia** [Beep6581/RawTherapee#5484]
When I apply inverse in "Local Adjustement-> Smooth - Blur & Noise" to Canon CR2 photos, a green frame appears in the final processed photo.
That frame is not produced in Fuji RAF and Ricoh DNG.

[IMG_3622.zip](https://github.com/Beep6581/RawTherapee/files/3692438/IMG_3622.zip)

Edit:/ Add:
Version: 5.7-1149-gc2e308e84
Branch: newlocallab
Commit: c2e308e84
Commit date: 2019-10-03
Compiler: x86_64-w64-mingw32-gcc\ 8.2.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.24.1
Lensfun: V0.3.2.0
Build type: Release
Build flags: -mwin32\ -m64\ -mthreads\ -msse2\ -std=c++11\ -mtune=generic\ -Werror=unused-label\ -Wall\ -Wuninitialized\ -Wcast-qual\ -Wno-deprecated-declarations\ -Wno-unused-result\ -fopenmp\ -Werror=unknown-pragmas\ -Wno-aggressive-loop-optimizations\ -DNDEBUG\ -O3\ -ftree-vectorize
Link flags: -m64\ -mthreads\ -static-libgcc\ -mtune=generic\ -s\ -O3
OpenMP support: ON
MMAP support: ON

**Comment by Desmis** [comment]
@arturoisilvia 
I cannot reproduce !
I tested with your files (CR2, pp3)

No frame in preview
No frame in TIF
No frame in various JPG  (100%, 70%, best compression, balanced...)
jacques

**Comment by arturoisilvia** [comment]
To me it goes like so:
Loads the image
Click on 'Processing profile fill mode': button released: (To understand us: icon with 2 stripes(or lines), no 4 stripes)
load the pp3
Processes the image: 'Processing queue'
Jpeg 8 bit - 85% quality - balanced

Wait for me to do more tests.
It is possible that this pp3 is not right.

**Comment by Desmis** [comment]
I just did as you indicate (with queue)

Same result, no frame

jacques

**Comment by arturoisilvia** [comment]
Well, it only happens to me.
I can't make the green frame with new pp3.
That pp3 should not be fine.
We give the error closed. If I left again I will let you know.

Greetings and sorry for the inconvenience.
Arturo.

**Comment by Desmis** [comment]
No problem at all :)
