### ISSUE TITLE
Capture Sharpening missing from "Parameters to save" partial processing profile dialog box

### ISSUE THREAD

**Issue by edsvo** [Beep6581/RawTherapee#5487]
Version: 5.7-129-ga87d104 (appimage)
Operating System: Ubuntu 18.04.3 LTS

Click the Editor tab to display the Editor. Hold down the control key and click the "Save current profile" button. Enter a file name. A "Parameters to save" dialog box appears.

In the list of parameters to save, Capture Sharpening does not appear.

**Comment by Beep6581** [comment]
Related: capture sharpening parameters are always saved https://github.com/Beep6581/RawTherapee/issues/5412#issuecomment-531653893
