### ISSUE TITLE
"Parameters to save" dialog and file dialog order should be swapped

### ISSUE THREAD

**Issue by edsvo** [Beep6581/RawTherapee#5491]
Version: 5.7-129-ga87d104 (appimage)
Operating System: Ubuntu 18.04.3 LTS

When holding the control key and clicking either the "Load a profile from file" button or the "Save current profile" button, the following sequence occurs:

1) A file dialog appears.
2) A parameters dialog ("Parameters to load" or "Parameters to save") appears.

This sequence make perfect sense when _loading_ a partial profile but I think this sequence is highly unintuitive and confusing when _saving_ a partial profile.

When saving a partial profile, I would expect to first be able to choose what parameters to save and only then have a file dialog appear allowing me to choose a file to save to.

**Comment by edsvo** [comment]
I think the current behavior contributed to the confusion experienced here:

https://github.com/Beep6581/RawTherapee/issues/5124#issuecomment-450748035

**Comment by Beep6581** [comment]
I agree and created PR #5501
