### ISSUE TITLE
Panasonic DMC-GX7 color target

### ISSUE THREAD

**Issue by fsenore** [Beep6581/RawTherapee#5500]
I have shot the two images requested to create the Panasonic GX7 camera profile.
I hope that they are good enough.
I took the images in north western Italy.
I bought my ColorCheker about 6-7 years ago, sorry but I don't remember exactly.

https://filebin.net/s88j86s5nb3a74gp/Panasonic_DMC-GX7_daylight.RW2?t=3fd88c5r
https://filebin.net/s88j86s5nb3a74gp/Panasonic_DMC-GX7_incandescent.RW2?t=3fd88c5r

Please let me know if everythin is OK.

Fulvio Senore

**Comment by Beep6581** [comment]
Thank you @fsenore , they are good.
