### ISSUE TITLE
NIKON D50 white frames

### ISSUE THREAD

**Issue by edsvo** [Beep6581/RawTherapee#5502]
Version: 5.7-134-gbbb410f (appimage)
Operating System: Ubuntu 18.04.3 LTS

For raw files from the Nikon D50, even when completely overexposed, measured values in the green channel (measured near the center of the frame) never exceed 99.6%. Red and blue do reach 100%.

My concern is that uncorrected this might affect highlight reconstruction. I don't know if green only reaching 99.6% is anything to worry about.

camconst.json does not include an entry for the Nikon D50.

Per the RawPedia article "Adding Support for New Raw Formats," I have taken a photo set which can be found at https://filebin.net/94j3sm7o0bdsfx8i/nikon-d50.zip?t=24mwdtlv

The Nikon D50 supports ISOs of 200, 400, 800, and 1600 with no intermediate ISOs.

**Comment by Thanatomanic** [comment]
@edsvoboda Could you please reupload your files? I can investigate.
