### ISSUE TITLE
Capture Sharpening: Highlights zone with Color Propagation are filled in a purple color

### ISSUE THREAD

**Issue by arturoisilvia** [Beep6581/RawTherapee#5505]
When I apply Exposure-> Highlight reconstruction-> Method: Color Propagation when there is a Highlight zone, Capture Sharpening fills the highlight area with purple by touching any of its sliders
-------
Version: 5.7-139-g8e99401ac
Branch: dev
Commit: 8e99401ac
Commit date: 2019-10-21
Compiler: x86_64-w64-mingw32-gcc\ 8.2.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.24.1
Lensfun: V0.3.2.0
Build type: Release
Build flags: -mwin32\ -m64\ -mthreads\ -msse2\ -std=c++11\ -mtune=generic\ -Werror=unused-label\ -Wall\ -Wuninitialized\ -Wcast-qual\ -Wno-deprecated-declarations\ -Wno-unused-result\ -fopenmp\ -Werror=unknown-pragmas\ -Wno-aggressive-loop-optimizations\ -DNDEBUG\ -O3\ -ftree-vectorize
Link flags: -m64\ -mthreads\ -static-libgcc\ -mtune=generic\ -s\ -O3
OpenMP support: ON
MMAP support: ON

**Comment by heckflosse** [comment]
@arturoisilvia Please provide an example file + .pp3 to reproduce. I tried to reproduce, but could not.

**Comment by heckflosse** [comment]
@arturoisilvia Can reproduce now.

**Comment by arturoisilvia** [comment]
[Para enviar.zip](https://github.com/Beep6581/RawTherapee/files/3755263/Para.enviar.zip)

**Comment by arturoisilvia** [comment]
Thank you!
