### ISSUE TITLE
Local Lab: Found a crash

### ISSUE THREAD

**Issue by arturoisilvia** [Beep6581/RawTherapee#5507]
Hello!, proceed:

    1 Open image
    2 Local Adjustements-> ON
    3 Add
    4 Color & Light - Small defects: red eyes, dust-> ON
    5 Soft radius: 100
    6 Move point of Color correction grid
    Crash

Version: 5.7-1216-g41563a3ac
Branch: newlocallab
Commit: 41563a3ac
Commit date: 2019-10-21
Compiler: x86_64-w64-mingw32-gcc\ 8.2.0
Processor: generic x86
System: Windows 
Bit depth: 64 bits
Gtkmm: V3.24.1
Lensfun: V0.3.2.0
Build type: Release
Build flags: -mwin32\ -m64\ -mthreads\ -msse2\ -std=c++11\ -mtune=generic\ -Werror=unused-label\ -Wall\ -Wuninitialized\ -Wcast-qual\ -Wno-deprecated-declarations\ -Wno-unused-result\ -fopenmp\ -Werror=unknown-pragmas\ -Wno-aggressive-loop-optimizations\ -DNDEBUG\ -O3\ -ftree-vectorize
Link flags: -m64\ -mthreads\ -static-libgcc\ -mtune=generic\ -s\ -O3
OpenMP support: ON   MMAP support: ON

**Comment by Desmis** [comment]
@arturoisilvia 
Diificult to reproduce, but effectivly, sometimes crash

I push a commit (I hope) solve this problem

Thank you for testing :)

jacques

**Comment by arturoisilvia** [comment]
@Desmis 
With version 5.7-1266 I no longer crash.
Has it been fixed?
In that case we can give the bug as fixed.
However I will continue testing.
Regards, Arturo.

**Comment by Desmis** [comment]
@arturoisilvia 

I think crash is fixed 

jacques

**Comment by arturoisilvia** [comment]
Jacques, look to see what happens with Denoise-> Luminance coarse (Wav)
When you move the slider with the mouse also crash with 5.7-1266
Do I open a new thread with this bug?

**Comment by Desmis** [comment]
I will have a look

jacques

**Comment by Desmis** [comment]
@arturoisilvia 
I have found the bug....
I will psuh a commit soon :)

jacques

**Comment by arturoisilvia** [comment]
ok.

**Comment by Desmis** [comment]
@arturoisilvia 
Fixed with commit a2d5ef3

Thank you for testing :)

I take this issue to talk about new features
* recursive data
* RGB Tone curve in Color and Light - standard, weight standard, luminance, film like
* merge image (original) with opacity  - with or without mask LCH - settings menu and mask 7: normal, addition, substract, difference, overlay, screen, soft light,  hard light, divide, darken only, lighten only, exclusion
* add TRC to equalizer

**Comment by arturoisilvia** [comment]
Perfect!
I will try it as soon as I am

Thank you very much. Regards, Arturo.

**Comment by Desmis** [comment]
I just add, for merge image, the possibility to merge with previous RT-spot

Same mode as for original

I have update Rawpedia always in french

http://rawpedia.rawtherapee.com/Local_Adjustments/fr

**Comment by arturoisilvia** [comment]
Thanks again,
I will follow and test carefully the news you introduce that I suppose you will also announce in pixls.

Greetings.
