### ISSUE TITLE
Auto-matched camera profile no longer working in 5.7

### ISSUE THREAD

**Issue by RobinHerink** [Beep6581/RawTherapee#5511]
Hi, I've been a very happy user of Rawtherapee since about 5.0, so first let me say a huge thank you to all involved in its development!
Unfortunately my custom profile for my Panasonic camera stopped "auto-matching" in the last version. The "Auto-matched camera profile" is greyed out. I have the profile stored in /.config/RawTherapee/dcpprofiles/ and until 5.6 it always matched my Panasonic photos. (The full name is "Panasonic DMC-G80.dcp", which matches the camera detected in Rawtherapee). It can be manually selected but that would be a nuisance with every photo.
Any idea why it stopped working? Maybe it's looking for the profile in a different folder? The behaviour is the same whether I use a packaged version or an appimage, 5.6 works, 5.7 doesn't.
Thanks!
![Screenshot_20191028_102438](https://user-images.githubusercontent.com/10381479/67667096-67d0cf00-f96d-11e9-89d6-4abc4c8d925b.jpeg)
![Screenshot_20191028_102457](https://user-images.githubusercontent.com/10381479/67667097-67d0cf00-f96d-11e9-82c7-325b3b2e7689.jpeg)

**Comment by Beep6581** [comment]
Hey @RobinHerink 
Upload a sample raw file, the DCP file, and your [`options`](http://rawpedia.rawtherapee.com/File_Paths#Config) file.

**Comment by RobinHerink** [comment]
Hey @Beep6581 
After your comment it occurred to me to try and delete (rename) my options file and suddenly even 5.7 auto-matches the camera again. But I'd like to keep my options file since there are quite a few things I have set up. Could you have a look at the file and see what's wrong in it? What 5.7 doesn't like while 5.6 works? I've just noticed the same is true for my previous camera (Canon 5D Mark II), 5.7 doesn't auto-match its profile.
Thanks again!
[options.zip](https://github.com/Beep6581/RawTherapee/files/3778394/options.zip)

**Comment by RobinHerink** [comment]
OK so I've been fiddling with it a little and found an interesting thing. The wrong setting is actually language selection! My system language is Czech and a new options file defaults to that - and when I change it to English (either US or UK), auto-matching the camera profile stops working. And the strangest thing is that any other language I select works! Only when English is selected, it doesn't. Hope this helps.

**Comment by fernandocollova** [comment]
@RobinHerink Thanks for your comment! I'm having the exact same issue in RT 5.9, my system language is `Espanol (Latin America)` but I prefer using RawThereapee in `English (US)`, and auto detection only works when I select `Use system language` :/
