### ISSUE TITLE
Camera Fujifilm X-T2 - Request for DCP

### ISSUE THREAD

**Issue by offminor** [Beep6581/RawTherapee#5513]
Would it be possible for someone in the Dev Team to produce a DCP fpr the Fujifilm X-T2 camera 
and incorporate it in the RT5.8 or later version of the Appimage
I have here assembled all the required data as per Rawpedia and hope you will find it adequate
I have uploaded 6 RAW files to Filebin and the URL for the upload is given here below.

Regards  

Adapted Lens: Olympus Zuiko-Autozoom 35-70mm f3.6
Target: Xrite Colorchecker Passport-Photo2
Purchased new: 19 July 2019

3 hand held D65 exposures at -1.0 EV / 0.0 EV / +1.0 EV
At constant aperture f8.0

Target location:
On surface of pedestrian pathway at 8.0m from intersection
in middle of Richmond Green–West London
Coords: N 51.461729 : E -0.307262

Height of grass on Richmond Green: approx 30mm throughout
Nearest tree line from target: approx 70m to NW

Time of shooting; 26 August 2019 close to zenith at approx 11.50 UT

3 tripod mounted StdA exposures at -1.0 EV / 0.0 EV / +1.0 EV
At constant aperture f8.0

Target location:
On floor of darkened room
Illuminant:
Pear shaped 40W/ 2900 Kelvin clear glass tungsten incandescent lamp

RAW FileNames uploaded to Filebin:

https://filebin.net/p87m535schx59rz3

Fujifilm X-T2 D65 -1.0 EV.RAF
Fujifilm X-T2 D65  0.0 EV.RAF
Fujifilm X-T2 D65 +1.0 EV.RAF

Fujifilm X-T2 StdA -1.0 EV.RAF
Fujifilm X-T2 StdA  0.0 EV.RAF
Fujifilm X-T2 StdA +1.0 EV.RAF

**Comment by Beep6581** [comment]
@offminor that's a very well written request, well done :)

Could you show me a photo of the lightbulb please (turned off, in daylight)?

**Comment by offminor** [comment]
Thanks for your comment @Beep6581. I have uploaded 2 small files to Filebin showing the bulb and package. These were taken with my mobile phone.

I have just noticed that my camera exposure setting was Centre Weighted for the three D65 RAF but mistakenly set to Spot for the three StdA RAF files. If you prefer the 
![DSC_01](https://user-images.githubusercontent.com/33794496/68072637-cdfb8e80-fd7f-11e9-9547-9b4565c594c4.JPG)
![DSC_02](https://user-images.githubusercontent.com/33794496/68072638-ce942500-fd7f-11e9-8f52-6209508ba591.JPG)

StdA files to be Centre Weighted also, then please let me know and I will re-shoot them. 

Apologies for the error

**Comment by Beep6581** [comment]
DCP created and tested, looks good.

**Comment by fiepfiep** [comment]
Hi, 
I am using rawtherapee 5.8 and my fuji XT2 using 18-55 or 27mm.
I feel this DCP profile gives a slightly red color cast to the image, especially on skin tones.
Using the XPRO2 color profile which has the same sensor, gives better color accuracy.

**Comment by Thanatomanic** [comment]
Is this a bug report, or an issue of taste? If our DCP was created properly using color calibration targets and the correct illuminants, then there is nothing to be done. You're always welcome to make your own profile and share it for comparison.
