### ISSUE TITLE
Crash when finished editing and running batch processing.

### ISSUE THREAD

**Issue by waxhead** [Beep6581/RawTherapee#5521]
latest pull from trunk:

Version: 5.7-213-ge5258e6f6
Branch: dev
Commit: e5258e6f6
Commit date: 2019-11-08
Compiler: cc 9.2.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.24.2
Lensfun: V0.3.2.0
Build type: debug
Build flags:  -std=c++11 -march=native -Werror=unused-label -Werror=delete-incomplete -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -fopenmp -Werror=unknown-pragmas -g -ftree-vectorize
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON

I had edited a number of images and went ot the Queue tab and started the processing queue.

There is no log file from gdb, just the following:

[Thread 0x7ffff18b9700 (LWP 31604) exited]
[Thread 0x7ffff1ba4080 (LWP 31600) exited]

Program terminated with signal SIGKILL, Killed.
The program no longer exists.
(gdb) set pagination off
(gdb) set logging file log.txt
(gdb) set logging on
Copying output to log.txt.
(gdb) info threads
No threads.
(gdb) thread apply all bt full
(gdb) 

I'll continue to run under gdb to see if I can get anything more helpful.

**Comment by Floessie** [comment]
Hi Peter,

Seems like you got hit by the OOM killer. There is nothing we can do or debug after a SIGKILL. If you can reproduce the crash, maybe we can look into memory hogs in your specific workflow.

Best,
Flössie

**Comment by waxhead** [comment]
Thanks Floessie. Now I know that I'll take a look at how to track that down

How did you know it was OOM killer?  The SIGKILL?

I've not had this issue before, I am on the newer kernel. I'd need to check
which 5.x Linux kernel I'm now on.

I'm also running Firefox and Evolution mail client, which I'll admit isn't
something I've run much in the past.

Peter.

**Comment by waxhead** [comment]
Linux Kernel:

Linux kanga 5.3.8-3-MANJARO #1 SMP PREEMPT Sun Nov 3 14:19:23 UTC 2019 x86_64 GNU/Linux

OK, so with a bit of googling I've used the following script to track RT's memory use:

```
#!/bin/sh

while (true) do 
	timestamp=$(date "+%Y-%m-%d_%H-%M-%S");
	mem=$(ps -eo size,pid,user,command --sort -size | grep -i rawtherapee |grep -v grep |awk '{ hr=$1/1024 ; printf("%13.2f Mb ",hr) } { for ( x=4 ; x<=NF ; x++ ) { printf("%s ",$x) } print "" }' |    cut -d "" -f2 | cut -d "-" -f1);
       echo "$timestamp	$mem"	
	sleep 2; 
done;

```

With the following output of the memory use while I was editing photos and then turned on the queue processing:

[rt-memuse.txt](https://github.com/Beep6581/RawTherapee/files/3835260/rt-memuse.txt)

And here's the restart memory use with processing in the queue:

[rt-memuse-restart-and-process-only.txt](https://github.com/Beep6581/RawTherapee/files/3835281/rt-memuse-restart-and-process-only.txt)

And this one is where I started the logging again, carrying on from the processing in the queue:

[rt-memuse-restart-carry-on.txt](https://github.com/Beep6581/RawTherapee/files/3835335/rt-memuse-restart-carry-on.txt)


I'll see if there's something about this kernel that might be triggering this.

**Comment by waxhead** [comment]
Here's some extra information:
```
Nov 12 20:10:24 kanga kernel: oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/user@1000.service,task=rawtherapee,pid=2709,uid=1000
Nov 12 20:10:24 kanga kernel: Out of memory: Killed process 2709 (rawtherapee) total-vm:10529468kB, anon-rss:4946444kB, file-rss:0kB, shmem-rss:11820kB

Nov 12 20:30:04 kanga kernel: oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/user@1000.service,task=rawtherapee,pid=5606,uid=1000
Nov 12 20:30:04 kanga kernel: Out of memory: Killed process 5606 (rawtherapee) total-vm:8910696kB, anon-rss:4585240kB, file-rss:0kB, shmem-rss:10380kB


Nov 12 20:44:54 kanga kernel: oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/user@1000.service,task=rawtherapee,pid=32425,uid=1000
Nov 12 20:44:54 kanga kernel: Out of memory: Killed process 32425 (rawtherapee) total-vm:5844272kB, anon-rss:2723932kB, file-rss:0kB, shmem-rss:7252kB
```

**Comment by Floessie** [comment]
@waxhead How much RAM and swap do you have?

**Comment by waxhead** [comment]
OK, so digging into this a little further it would appear I don't have any swap, neither a swap partition, which I have always set up as a a general rule of 2x RAM, which in this installation I didn't, but also, there's not swap file!

I was running vmstat at the time of running RT, and having discovered the lack of swap I created a swap file and the following is the vmstat output:
```
2  0      0 1464660  32904 1026400    0    0     0   126  629 3005  2  1 97  0  0
 8  0      0 750348  32912 1032812    0    0     1    15 6336 31727 26  3 70  0  0
18  0 152064 470476    916 501860 4866 37615  8967 37761 9769 10884 77  9 13  0  0
 3  0 139264 1544552   4708 549704    9    0  6006    20 6537 13901 79  4 16  0  0
 9  0 206848 161188   4312 376280    0 13477   332 13523 7395 24255 61  8 31  0  0
 1  0 219904 220252   1772 455860 20351 27354 39435 27354 10429 10506 80  7 12  1  0
 8  0 215552 851968   2816 487676  841    0  3156    12 7433 30962 55  5 39  0  0
10  1 305152 650336  11236 536840 23531 42420 59867 42556 11792 13963 76  9 14  1  0
 1  1 396800 1438180   8240 558076 11064 27898 38074 30918 8044 14079 68  7 23  1  0
procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
 1  0 395264 1413100  12168 572996  203    0  3592  2900 1218 3064  5  1 93  0  0
 0  0 395264 1392224  13004 592528    3    0  4115  1144  533 1022  1  0 99  0  0
 0  0 395264 1390988  13140 593760   18    0   202    74  323 1224  1  0 99  0  0
 0  0 395264 1383524  13140 594164    6    0   100     0  256  731  1  0 99  0  0
 0  0 393984 1380792  13148 595756  358    0   870     3  287  996  1  0 99  0  0
```

It's clear that RT was using the availalbe memory and then we can see swap starts getting used.  For good measure to push the point I opened Evolution the mail client. Everything is still running.

I suspect the issue is down to not have any swap.

**Comment by waxhead** [comment]
@Floessie 8G of RAM and no swap...  :-/

**Comment by waxhead** [comment]
I'll probably close this issue shortly.

**Comment by waxhead** [comment]
OK, clearly fixed with adding swap back to the system. Can't believe it was like that for so long... unless it was something with the Linux Kernel change in Manjaro I did a while back... ?

**Comment by Floessie** [comment]
@waxhead You're also hit by #4416. Franz added a new option in #5465. Maybe you can give `-DENABLE_TCMALLOC=ON` a try...
