### ISSUE TITLE
I have added a CR3, raw file from a EOS M6 Mark II camera from canon. Can Rawtherapee and darktable be update to read this file?

### ISSUE THREAD

**Issue by Harry456-foto** [Beep6581/RawTherapee#5522]
If you are filing a bug report, please first read the guide How to Write Useful Bug Reports:
http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports
You must provide the required information in order for your bug report to be valid.
Delete this text before posting.

**Comment by Beep6581** [comment]
Duplicate of #5319

**Comment by Beep6581** [comment]
@Harry456-foto RawTherapee now supports decoding CR3 raw files (but not metadata). Feel free to open a new issue and supply daylight + incandescent tungsten shots of a [color target](http://rawpedia.rawtherapee.com/How_to_create_DCP_color_profiles) as well as LENR=on [white frame](http://rawpedia.rawtherapee.com/Adding_Support_for_New_Raw_Formats) shots (set 2).

**Comment by Harry456-foto** [comment]
I have uploaded following files from the camera Canon EOS M6 MKII:

RAW/CRAW | Aspect   ratio | Name
-- | -- | --
RAW | 3:2 | IMG_RAW_3_2.CR3
CRAW | 3:2 | IMG_CRAW_3_2.CR3
RAW | 4:3 | IMG_RAW_4_3.CR3
CRAW | 4:3 | IMG_CRAW_4_3.CR3
RAW | 16:9 | IMG_RAW_16_9.CR3
CRAW | 16:9 | IMG_CRAW_16_9.CR3
RAW | 1:1 | IMG_RAW_1_1.CR3
CRAW | 1:1 | IMG_CRAW_1_1.CR3

Can you update Rawtherapee so that the CR3 files are recognised?

**Comment by Beep6581** [comment]
@Harry456-foto it does already. Color target shots still needed.
