### ISSUE TITLE
Local Lab: Crash in Mask L(L) de Smooth-Blur....

### ISSUE THREAD

**Issue by arturoisilvia** [Beep6581/RawTherapee#5526]
English version

1) Crash in Mask L(L) of Smooth-Blur....
	Add
	Smooth - Blur - Noise - Grain -> ON
	1+* Mask and modifications - Smooth....
		Mask L(L): Standar-> move point and crash

2) Another issue:
I usually use the Color & Light module and the area and intensity where I apply the mask I consider it important.

In '7 Mask and modifications' I select 'Preview selection deltaE' and see where the mask is in B&W with yellow background that I am applying and its intensity. So far so good. But if I then touch any slider to graduate the mask in yellow disappears. Is it a bug or am I missing something to do?

3) And then, apart, in settings there is a 'Mask DeltaE image' checkbox that I don't know what it is for. There is no documentation.
--------------------------------------------------------------------
version Français

1) Crash in Mask L(L) of Smooth-Blur ....
	Ajouter
	Smooth - Blur - Noise - Grain -> ON
	1 + * Masque et modifications - Lisse ....
		Masque L (L): Standard-> point de déplacement et crash

2) Une autre question:
J'utilise habituellement le module Couleur et lumière, ainsi que la zone et l'intensité d'application du masque que je considère important.

Dans '7 Masque et modifications', je sélectionne 'Aperçu sélection deltaE' et je vois où se trouve le masque en noir et blanc sur fond jaune que j'applique et son intensité. Jusqu'ici tout va bien. Mais si je touche ensuite un curseur, le masque disparaît en jaune. Est-ce un bug ou est-ce que je manque quelque chose à faire?

3) Et puis, mis à part, dans les paramètres, il y a une case à cocher 'Image de masque DeltaE' que je ne sais pas à quoi ça sert. Il n'y a pas de documentation.

(all with G transl)

Edit (I forgot)
Version: 5.7-1383-gd9be38e6c
Branch: newlocallab
Commit: d9be38e6c
Commit date: 2019-11-12
Compiler: x86_64-w64-mingw32-gcc\ 8.2.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.24.2
Lensfun: V0.3.2.0
Build type: Release
Build flags: -mwin32\ -m64\ -mthreads\ -msse2\ -std=c++11\ -mtune=generic\ -Werror=unused-label\ -Werror=delete-incomplete\ -Wall\ -Wuninitialized\ -Wcast-qual\ -Wno-deprecated-declarations\ -Wno-unused-result\ -fopenmp\ -Werror=unknown-pragmas\ -Wno-aggressive-loop-optimizations\ -DNDEBUG\ -O3\ -ftree-vectorize
Link flags: -m64\ -mthreads\ -static-libgcc\ -mtune=generic\ -s\ -O3
OpenMP support: ON      MMAP support: ON

**Comment by Desmis** [comment]
@arturoisilvia 

Thank you for testing :)
1) Effectively there was a bug with contrast curve L(L) in mask 1
With the last commit, its fixed. 0e409e7

2) it is a bug, I will have a look

Thank you 

jacques

**Comment by Desmis** [comment]
@arturoisilvia 
I just fixed the bug "Preview selection deltaE"... commit 636b364
But this bug was very very big, it made the use of "locallab" almost impossible : it's the story of the cat biting its tail :)

For "Mask deltaE image", it is in Rawpedia
https://rawpedia.rawtherapee.com/Local_Adjustments/fr#Case_.C3.A0_cocher_.22Mask_deltaE_Image.22_et_curseur_.22Scope_Mask_DeltaE_image_.28menu_Settings.29

But I have to resume the documentation for:
1) change in the location and functionnalities "Merge files" (in Color and light)
2) add documentation for "Structure mask"

Thank you again for this precious collaboration

jacques

**Comment by Desmis** [comment]
I just update "Rawpedia" (always in french)
http://rawpedia.rawtherapee.com/Local_Adjustments/fr

**Comment by arturoisilvia** [comment]
Thank you very much for the speed in solving these bugs. You know there is nothing worse than a crash: as soon as it occurs you lose all the work you were doing. That is why it is important to cover them all and that it does not happen to anyone as it would be a frustration.

As soon as it is available I will check how the Preview selection deltaE has been. I didn't expect him to give so much war. I consider it a very interesting tool, as much as the control of the point U that is a success with respect to the strokes.

I will look at Rawpedia and see if I clarify with the part of the masks.

Well, I said, thanks for the solutions and for my part I will continue testing and chasing the crash :)

Regards, Arturo.

**Comment by Desmis** [comment]
@arturoisilvia 

Thank you very much :)

jacques
