### ISSUE TITLE
PPI information not being saved in tiff exif. 

### ISSUE THREAD

**Issue by harshbarj** [Beep6581/RawTherapee#5527]
When saving a tiff file the exif field for the file ppi is blank. A jpeg file saved from the same file at the same time does contain this correct information. The original file is 400ppi and when saved as a tiff (any type) it is blanked out and windows incorrectly identifies it as 96ppi.

Running windows 10 enterprise and rawtherapee 5.6. All files used are scanned on a Epson expression 11000xl scanner or a bookeye 4 professional book scanner. All files also are saved in tiff format with either LZW(bookeye) or zip(epson) compression in tiff. All files share the same bug in the end.

**Comment by Beep6581** [comment]
Handled by #3801
