### ISSUE TITLE
Bug in open of a .pp3 file with selected settings?

### ISSUE THREAD

**Issue by CharlesRT2** [Beep6581/RawTherapee#5528]
RT 5.7 Windows 64, Sept. 13, 2019 published build.

I have a .pp3 file that begins noise reduction the way I like (attached after rename to .txt). For a long time it has worked. Recently, open of the file changes other settings. Specifically,
    1. Open a raw file (several .DNG files tried)
    2. Change Color Management | Input Profile from Auto-matched to Custom, and open a .dcp
    3. Open the .pp3 file -- the setting reverts to Auto-matched
This happens whether I open the .pp3 file in plain manner, or hold Ctrl and check Noise Reduction for selective load.

Have I made an error, or is there a bug?

[NRstart.txt](https://github.com/Beep6581/RawTherapee/files/3844018/NRstart.txt)

**Comment by Beep6581** [comment]
@CharlesRT2 set your processing profile fill mode to "preserve" and try again
http://rawpedia.rawtherapee.com/Sidecar_Files_-_Processing_Profiles#Partial_Processing_Profiles_and_Fill_Modes

**Comment by Beep6581** [comment]
Works fine here in "preserve" mode, `5.7-232-g`c2ed31991

**Comment by CharlesRT2** [comment]
> > Works fine here in "preserve" mode, `5.7-232-g`[c2ed319](https://github.com/Beep6581/RawTherapee/commit/c2ed31991bd8faee2882c7f997c5a663e82c5518)

Thank you. That button was my problem. I recall that I accidentally clicked on that button months ago and fixed it with advice. So this is the second time. If it is only me, so be it, my job to learn; if it happens to other people, maybe there is a UI issue.

Thanks again.
