### ISSUE TITLE
Lens corrections for Panasonic 42.5mm f/1.7 are not available

### ISSUE THREAD

**Issue by fm2003** [Beep6581/RawTherapee#5530]
When opening an image that was shot with the Panasonic 42.5mm f/1.7, the corrections for geometric distortion and chromatic aberration are not available (this happens with the two cameras I have: the Panasonic G80 and the GX80). The lens is recognised, but the correction checkboxes are greyed out. Also, a warning tooltip is shown next to the "manually selected" part, with the text "Warning: the crop factor used for lens profiling is larger than the crop factor of the camera, the results might be wrong." I am not sure whether this warning is related to the unavailability of the lens corrections, but I thought I'd tell it just in case it's relevant. The issue is illustrated in this screenshot:

![Schermafdruk van 2019-11-18 13-21-47](https://user-images.githubusercontent.com/12736814/69052110-74919180-0a06-11ea-8dba-ed3ea70d2fb4.png)

Interestingly, when opening an image taken with the 42.5mm and applying the "Auto-Matched Curve - ISO Low" profile, the lens corrections *are* applied. But then when I make any change (such as tweaking the white balance), the image reverts back to the uncorrected view. When I apply the "Neutral" profile, the lens corrections are not applied, and I have no way to apply them. I have attached the RAW file that is being developed in the screenshot above: [20191117_210313.RW2.zip](https://github.com/Beep6581/RawTherapee/files/3858466/20191117_210313.RW2.zip)

I am using RawTherapee version 5.7 from the AppImage (but this issue happened in earlier versions too):
```
Version: 5.7
Branch: releases
Commit: f335efe
Commit date: 
Compiler: cc 7.3.1
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.22.2
Lensfun: V0.3.2.0
Build type: release
Build flags:  -std=c++11  -Werror=unused-label -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -fopenmp -Werror=unknown-pragmas -O2 -DNDEBUG -ftree-vectorize
Link flags:   
OpenMP support: ON
MMAP support: ON
```

I am on Debian 10 (buster): `Linux 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux`

I have run `lensfun-update-data` to make sure the latest version of the Lensfun database is used. The issue does not occur with any of the other lenses I have.

**Comment by Beep6581** [comment]
Confirmed in `5.7-232-g`c2ed31991 that on opening the raw some minor lens distortion correction is being applied though the PLC checkboxes are all grayed-out, and that when touching the white balance temperature slider the corrections are unapplied.

**Comment by dimanech** [comment]
Hi guys,
@fm2003 thank you for reporting this issue and @Beep6581 @Lawrence37  for investigating and fix!
I have same issue and could share **workaround**. 
You could apply profiled lens correction from **File browser -> Batch Edit**. In this case you could correct lens for all shots before exporting files.
