### ISSUE TITLE
Regression in Olympus E-M10MarkII raw black levels

### ISSUE THREAD

**Issue by abertens** [Beep6581/RawTherapee#5535]
Hi there,

Yesterday downloaded rawtherapee from git, built it and when opening any color image in editor, they have a pink cast (Linux Debian 9).

Version: 5.7-248-g7b54c7f2a
Branch: 5.7-248-g7b54c7f2a
Commit: 7b54c7f2a
Commit date: 2019-11-21
Compiler: cc 6.3.0
Processor: generic
System: Linux
Bit depth: 64 bits
Gtkmm: V3.22.0
Lensfun: V0.3.2.0
Build type: Release
Build flags:  -std=c++11  -Werror=unused-label -Werror=delete-incomplete -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags:   
OpenMP support: ON
MMAP support: ON

![ratherapee-pink-cast](https://user-images.githubusercontent.com/40841548/69422929-b7ec4880-0d03-11ea-8974-9bbd89650804.png)

Regards,
Andres Bertens

**Comment by Beep6581** [comment]
Hi @abertens , see:
http://rawpedia.rawtherapee.com/Adding_Support_for_New_Raw_Formats
We need to measure the white and black levels and make an input profile.

**Comment by abertens** [comment]
Hi @Beep6581,

I have almost two years using RawTherapee with my Olympus Camera.

Till commit from 4 days back, it worked ok:

Version: 5.7-235-g62eb970ae
Branch: 5.7-235-g62eb970ae
Commit: 62eb970ae
Commit date: 2019-11-17
Compiler: cc 6.3.0
Processor: generic
System: Linux
Bit depth: 64 bits
Gtkmm: V3.22.0
Lensfun: V0.3.2.0
Build type: Release
Build flags:  -std=c++11  -Werror=unused-label -Werror=delete-incomplete -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags:   
OpenMP support: ON
MMAP support: ON

**Comment by Floessie** [comment]
Confirmed. Bisecting...

**Comment by heckflosse** [comment]
@Floessie As I tested today with some M5MarkIII files, I sometimes got the pink cast, but not always (on the same file).

**Comment by Floessie** [comment]
@heckflosse It's 0cf3f16dfa58b4fcefd6d49965f8337333f076a4.

**Comment by heckflosse** [comment]
@Floessie Must be the dcraw.cc part of the commit then... looking

**Comment by Floessie** [comment]
@heckflosse I took the sample from [raw.pixls.us](https://raw.pixls.us/getfile.php/2785/nice/Olympus%20-%20E-M10%20Mark%20II%20-%2016bit%20(4:3).ORF). It reliably fails on my Debian 9 setup.

**Comment by Floessie** [comment]
@heckflosse Desturbing finding: decodes reliably **well** on my Debian 10 setup.

**Comment by heckflosse** [comment]
@Floessie 
https://github.com/Beep6581/RawTherapee/commit/0cf3f16dfa58b4fcefd6d49965f8337333f076a4#diff-9967648f0eb70b821877dd6105e978efR5604

`RT_canon_CR3_data.CR3_CTMDtag` is checked, but not initialized. Can you confirm?

**Comment by heckflosse** [comment]
@Floessie 
This fixes it:
```diff
diff --git a/rtengine/dcraw.h b/rtengine/dcraw.h
index 75570b065..0265219c7 100644
--- a/rtengine/dcraw.h
+++ b/rtengine/dcraw.h
@@ -68,6 +68,7 @@ public:
         gamm[0]=0.45;gamm[1]=4.5;gamm[2]=gamm[3]=gamm[4]=gamm[5]=0;
         user_mul[0]=user_mul[1]=user_mul[2]=user_mul[3]=0;
         greybox[0]=greybox[1]=0; greybox[2]=greybox[3]= UINT_MAX;
+        RT_canon_CR3_data.CR3_CTMDtag = 0;
     }
 
 protected:

```
Can you confirm?

**Comment by abertens** [comment]
@Floessie @heckflosse @Beep6581

Proposed patch from @heckflosse fixes the issue!

Thank you!

**Comment by Beep6581** [comment]
I could reproduce and will test the patch this evening.

**Comment by Beep6581** [comment]
Fix confirmed.
