### ISSUE TITLE
Impossible to open sub-menu in film simulation

### ISSUE THREAD

**Issue by roessli** [Beep6581/RawTherapee#5537]
Hello,
The submenus of the film simulation cannot be re-opened anymore if they were opened once. 
For example, in the menu film simulation -> color only Agfa and Lomography are not affected.
The other menus do not re-open if they were opened once.  
I was using RAWTHERAPEE 5.7 but the RAWTHERAPEE 5.7-dev shows the same effect.
I am using Debian on Chrome OS
Linux penguin 4.19.69-06666-g6c4f8cbba24e 
In the attached file the Kodak menu does not open. It did open when it was cklicked first time.
![Screenshot 2019-11-23 at 12 48 35](https://user-images.githubusercontent.com/49119505/69478175-d465af00-0def-11ea-97af-aa67923f7e47.png)

Thank You,
Bertrand Roessli

**Comment by Beep6581** [comment]
@roessli upgrade GTK+ to the latest version and recompile.

**Comment by ror6ax** [comment]
I can reproduce this on 5.8 running on Fedora.
