### ISSUE TITLE
Sometimes processing profiles are not saved - macOS

### ISSUE THREAD

**Issue by akidee** [Beep6581/RawTherapee#5541]
Version: 5.6
Mac OS 10.11

I open RT, choose a photo, make sure that I load my own neutral profile, then apply some changes (e. g. camera input profile, ...), then I want to save these changes as a camera profile which only contains these changes, so I press "Save Profile" along with Ctrl. only choose the parts I need, then save. Sometimes it is saved, but sometimes not. The resulting pp3 file only contains this and of course nothing happens when I load it:

```
[Version]
AppVersion=5.6
Version=346
```

**Comment by Beep6581** [comment]
@akidee please be more specific about what you did exactly. In fact, record a video showing everything from starting RT to the empty saved profile.

**Comment by akidee** [comment]
This should be enough:
- I open RT.
- I select a RAW image for editing.
- I set its processing profile to "(Neutral)".
- I set its demosaicing method to "LMMSE"
- On the top right-hand corner, I press on the button "Save current profile" along with pressed "Ctrl" key.
- I enter the name for the pp3.
- The dialog "Parameters to save" appears. I click on "Everything" two times to makes sure that none of the many parameters are selected
- I select one checkbox: "Demosaic method"
- I click "OK"
This time it worked. Resulting profile content:
```
[Version]
AppVersion=5.6
Version=346

[RAW Bayer]
Method=lmmse
DualDemosaicAutoContrast=true
DualDemosaicContrast=20

[RAW X-Trans]
Method=3-pass (best)
DualDemosaicAutoContrast=true
DualDemosaicContrast=20

```

- I set its processing profile back from "(Custom)" to "(Neutral)".
- I load my own profile by clicking on the button "Load a profile from file"
- For example I choose a default crop profile, with this content:
```
[Version]
AppVersion=5.6
Version=346

[Crop]
Enabled=true
X=16
Y=10
W=6000
H=4000
FixedRatio=false
Ratio=As Image
Orientation=As Image
Guide=Frame

[RAW Bayer]
Border=0

[RAW X-Trans]
Border=7
```
- Click "OK" in the dialog.
- I set its demosaicing method to "AMaZE"
- I set its demosaicing method to "LMMSE"
- On the top right-hand corner, I press on the button "Save current profile" along with pressed "Ctrl" key.
- I enter the name for the pp3.
- The dialog "Parameters to save" appears. I click on "Everything" two times to makes sure that none of the many parameters are selected
- I select one checkbox: "Demosaic method"
- I click "OK"
Resulting profile content:
```
[Version]
AppVersion=5.6
Version=346

```

From now on I can try to save whatever I like, it will not save the full information to the pp3 file. I must restart RT to make it work again.

**Comment by Beep6581** [comment]
Screen recording not provided.

I followed the steps and could not reproduce in `5.7-252-g`f054ed00e in Linux.

@akidee see if this build works on your system:
https://kd6kxr.keybase.pub/RawTherapee_OSX_10.9_64_5.7.zip

**Comment by Beep6581** [comment]
No response, closing.
