### ISSUE TITLE
macOS Catalina crash: can't open

### ISSUE THREAD

**Issue by fanckush** [Beep6581/RawTherapee#5543]
The moment I open RT it crashes on macOS 10.15
The error report is big but this section below seems to be causing the issue
RT 5.7.0 (installed using brew)
``` 
Dyld Error Message:
Termination Reason:    DYLD, [0x3] Wrong version

Application Specific Information:
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/Applications/RawTherapee.app/Contents/Frameworks

Library not loaded: /usr/lib/libexpat.1.dylib
Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
Reason: Incompatible library version: ImageIO requires version 7.0.0 or later, but libexpat.1.dylib provides version 1.0.0
```

Isn't libexpat a native/default library that is preinstalled in macOS? I'm not sure how to fix this

**Comment by Beep6581** [comment]
@fanckush can you reproduce using this build? https://kd6kxr.keybase.pub/RawTherapee_OSX_10.9_64_5.7.zip

**Comment by fanckush** [comment]
Sooo this has been opened before #5385. sorry for not double checking before opening.

**Comment by fanckush** [comment]
@Beep6581 yes it still crashes with the same error

**Comment by fanckush** [comment]
Do you have dev builds or do I have to manually build RT from master to get this working?

**Comment by Beep6581** [comment]
We don't have an automated macOS build system. @Benitoite is all we have.
