### ISSUE TITLE
Problem with Fujifilm X-A10's RAF files

### ISSUE THREAD

**Issue by michalzkosmosu** [Beep6581/RawTherapee#5545]
So far, the RAW files from my camera, Fujifilm X-A10, have not been running in any software available on Linux – neither RawTherapee nor Darktable. With hope I was checking every version of both programs, but it was always the same – the RAF files didn't even open. Since I only use Linux, it means that my camera is lying unused. And finally in version 4.7 of RawTherapee for the first time something changed – the RAF files started to open. And some sliders even work (like an exposure), but others don't do anything (like a color mixer). Could some good soul check what could be the cause? It would mean a lot to me.

Sample RAF: http://www.robmydobrze.pl/pliki/DSCF6141.RAF

OS: Xubuntu 19.10; App: RawTherapee 4.7 (flatpak)

**Comment by Beep6581** [comment]
Works fine in RawTherapee 5.7.
![screenshot_20191127_101331](https://user-images.githubusercontent.com/5844619/69709924-a5f11800-10fe-11ea-87dc-bf85fab0a30d.png)

**Comment by Beep6581** [comment]
If you have access to a color target, you could send us daylight + StdA shots http://rawpedia.rawtherapee.com/How_to_create_DCP_color_profiles

**Comment by michalzkosmosu** [comment]
I don't know if you've read my entire message. RAWs have recently started to run, but not everything works, for example a color mixer: http://www.robmydobrze.pl/pliki/raf_fujifilm_xa10.gif

![Color mixer](http://www.robmydobrze.pl/pliki/raf_fujifilm_xa10.gif)

**Comment by Floessie** [comment]
@michalzkosmosu Just turn it on and it will start to work. :wink:

**Comment by michalzkosmosu** [comment]
What an embarrassment. Haha. It's true.
