### ISSUE TITLE
Update automated development build filenames

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#5551]
The automated build filenames for RawTherapee and HDRMerge will use this template:
```text
hdrmerge_release-v0.6_continuous-67-g1f0b1a0_20190927.AppImage
________ ____________ ______________________ ________.________
  name      branch         git describe        date     ext
```

Releases will use:
```text
hdrmerge_v0.6.AppImage
________ ____.________
  name   tag    ext
```

Fields separated by underscores, where a field is the output of a command such as `git describe`.

https://github.com/jcelaya/hdrmerge/releases/tag/nightly
https://github.com/Beep6581/RawTherapee/releases/tag/nightly

https://github.com/aferrero2707/hdrmerge-ci/blob/master/package-appimage.sh#L115
https://github.com/aferrero2707/rt-appimage/blob/master/ci/package-appimage.sh#L227
https://github.com/aferrero2707/rt-win64/blob/master/ci/package-msys2.sh#L37
https://github.com/aferrero2707/rt-win64/blob/master/ci/package-w64.sh#L37

https://github.com/aferrero2707/rt-win64/blob/master/.travis.yml
https://github.com/aferrero2707/rt-appimage/blob/master/.travis.yml

**Comment by aferrero2707** [comment]
What about the target operating system? This might be needed if for example we generate zip files for both Win64 and macOS, and the branch and build dates are the same.

**Comment by Beep6581** [comment]
@aferrero2707 no problem adding OS names when the need arises.

**Comment by Beep6581** [comment]
Fixed for AppImage, now for Windows.

**Comment by aferrero2707** [comment]
Thanks! Could you take care of the windows script as well, or should I do that?

**Comment by Beep6581** [comment]
@aferrero2707 as we're releasing this weekend and time's running short, if you could do the Windows script that would be great :+1: 

Development:
```text
RawTherapee_branch_gitdescribe_date.exe
RawTherapee_branch_gitdescribe_date_win64.zip
```

Tagged release:
```
RawTherapee_gitdescribe.exe
RawTherapee_gitdescribe_win64.zip
```

So basically:
```bash
if [[ $RT_BRANCH = releases ]]; then
    ver="${GIT_DESCRIBE}"
else
    ver="${RT_BRANCH}_${GIT_DESCRIBE}_${curr_date}"
fi
```
and then append `win64` for the zip file only.

**Comment by aferrero2707** [comment]
@Beep6581 I am taking care of the windows package naming right now...

**Comment by aferrero2707** [comment]
@Beep6581 @heckflosse windows names should be fine now. Could you check that the release packages also install in the appropriate folder?
https://github.com/Beep6581/RawTherapee/releases/download/nightly/RawTherapee_5.7.exe
https://github.com/Beep6581/RawTherapee/releases/download/nightly/RawTherapee_5.7_win64.zip

**Comment by Beep6581** [comment]
Thank you @aferrero2707
