### ISSUE TITLE
macOS compilation failure in improcfun.cc error: use of undeclared identifier 'options'

### ISSUE THREAD

**Issue by blj86** [Beep6581/RawTherapee#5553]
In a new attempt to build the dev branch to test performance on MacOS due to the recent reported HDPI issue to see if this particular branch behaves any differently I came a cross a compilation error that may be MacOS specific not positive.

when trying to build off the latest dev commit 00441924eb46a24a49e356776f86fcd530694250

I get the following compilation error.

`Source/code-rawtherapee/rtengine/improcfun.cc:302:56: error: use of
      undeclared identifier 'options'
        monitor = ICCStore::getInstance()->getProfile (options.rtSettings.srgb);`

Just figured I would bring this to attention.

**Comment by Floessie** [comment]
@blj86 Could you please test again with latest `dev`?

**Comment by Beep6581** [comment]
Compiled fine in Sabayon.

**Comment by blj86** [comment]
@Floessie 
Compiled fine just checked this morning. :+1:
