### ISSUE TITLE
Black line in Ellipse

### ISSUE THREAD

**Issue by arturoisilvia** [Beep6581/RawTherapee#5554]
Hi,
I was going to do a little tutorial about masks and I found this little mistake:

1) Local Complexity Adjustements: Normal
2) Upload the image (IMG_3782.CR2) and its corresponding pp3. We will see this: (1 Enlarge to 600 pct.JPG)
3) Increase to 600%
4) It is observed that in the Ellipse of Control Spot # 2 the Transition Value of Transition Gradient transcends the ellipse (2 Transition Value at 100.JPG) and generates a black line.
5) The correct thing would be a Transition Value cap at 89.5% (3 Transition Value at 89.5.JPG)

[Error linea negra transition gradient.zip](https://github.com/Beep6581/RawTherapee/files/3926319/Error.linea.negra.transition.gradient.zip)

A greeting.

Version: 5.7-1522-gfc20b950a
Branch: newlocallab
Commit: fc20b950a
Commit date: 2019-12-04
Compiler: x86_64-w64-mingw32-gcc\ 8.2.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.24.2
Lensfun: V0.3.2.0
Build type: Release
Build flags: -mwin32\ -m64\ -mthreads\ -msse2\ -std=c++11\ -mtune=generic\ -Werror=unused-label\ -Werror=delete-incomplete\ -Wall\ -Wuninitialized\ -Wcast-qual\ -Wno-deprecated-declarations\ -Wno-unused-result\ -fopenmp\ -Werror=unknown-pragmas\ -Wno-aggressive-loop-optimizations\ -DNDEBUG\ -O3\ -ftree-vectorize
Link flags: -m64\ -mthreads\ -static-libgcc\ -mtune=generic\ -s\ -O3
OpenMP support: ON
MMAP support: ON

**Comment by arturoisilvia** [comment]
With rectangle too.
It is produced in:
- Method: Excluding Spot
- Scope: 100
- Transition value: 100

[Error linea negra transition gradient 2.zip](https://github.com/Beep6581/RawTherapee/files/3926826/Error.linea.negra.transition.gradient.2.zip)

**Comment by Desmis** [comment]
@arturoisilvia 
I will have a look :)

Thank you  for your work :)

jacques

**Comment by Desmis** [comment]
@arturoisilvia 
Yes, there is somewhere a bug in calculation

To prevent black line at bottom (and also a small at right), I push a change, but I don't think it is perfect... 

jacques

**Comment by Desmis** [comment]
@arturoisilvia 
I think (I hope) the bug is solved issue 99d0a54

The problem was "round" of real values to integer, in some cases 1 pixel was not take into account, and with excluding spot, it creates "black line", no data...

jacques

**Comment by arturoisilvia** [comment]
Ok, I'll try it when that next issue is.
A greeting.

Arturo.

**Comment by arturoisilvia** [comment]
Perfect!. I see that in vers. 1532 has been corrected.
Thank you. I will continue testing....
A greeting.
Arturo.
