### ISSUE TITLE
Flush denormals to zero in gauss.cc

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#5560]
Today I detected that using capture sharpening on images with large overexposed regions takes more processing time than on images without overexposed regions.

I found the culprit and would like to get some tests on different cpus.

Here's the file I used for my test: 
https://filebin.net/aeqchxv9hqtjwiz5

Here's a patch with the benchmark code:
```diff
diff --git a/rtengine/capturesharpening.cc b/rtengine/capturesharpening.cc
index 910de6fd3..d01c1b224 100644
--- a/rtengine/capturesharpening.cc
+++ b/rtengine/capturesharpening.cc
@@ -833,7 +833,9 @@ BENCHFUN
     }
     // calculate contrast based blend factors to reduce sharpening in regions with low contrast
     array2D<float>& blend = clipMask; // we can share blend and clipMask buffer here
+StopWatch Stop1("buildBlendMask");
     buildBlendMask(L, blend, W, H, contrast, 1.f, sharpeningParams.autoContrast, clipMask);
+Stop1.stop();
     if (plistener) {
         plistener->setProgress(0.2);
     }

```

Just apply CS with default settings to the above file und look at console. I get this:
```
buildBlendMask took 319 ms
```

Now apply this patch:
```diff
diff --git a/rtengine/gauss.cc b/rtengine/gauss.cc
index 8d9e5de38..b9d5637ae 100644
--- a/rtengine/gauss.cc
+++ b/rtengine/gauss.cc
@@ -1538,6 +1538,15 @@ template<class T> void gaussianBlurImpl(T** src, T** dst, const int W, const int
 
 void gaussianBlur(float** src, float** dst, const int W, const int H, const double sigma, bool useBoxBlur, eGaussType gausstype, float** buffer2)
 {
+#ifdef __SSE2__
+    const auto oldMode = _MM_GET_FLUSH_ZERO_MODE();
+    _MM_SET_FLUSH_ZERO_MODE(_MM_FLUSH_ZERO_ON);
+#endif
+
     gaussianBlurImpl<float>(src, dst, W, H, sigma, useBoxBlur, gausstype, buffer2);
+
+#ifdef __SSE2__
+    _MM_SET_FLUSH_ZERO_MODE(oldMode);
+#endif
 }
 
```

Now I get this:
```
buildBlendMask took 65 ms
```

I tested on AMD FX 8350. Can someone with different cpu please test?

**Comment by Thanatomanic** [comment]
The difference on my machine isn't as big as yours, but a difference all the same:

with SSE patch: `buildBlendMask took 67 ms`
without SSE patch: `buildBlendMask took 172 ms`

**Comment by heckflosse** [comment]
@Thanatomanic Thanks for testing. :+1:

**Comment by heckflosse** [comment]
Related, but a bit technical: https://web.archive.org/web/20161015154158/http://grouper.ieee.org/groups/754/meeting-minutes/02-09-19.html#underflow

**Comment by snappyapple632** [comment]
I have a machine with a 9900K, but I know nothing related to code. If you can guide me through this or provide precompiled programs, I'd be glad to test it out.

**Comment by Floessie** [comment]
@heckflosse Median of 5 samples on AMD Epyc (Zen1):

Test | w/o patch | w/ patch
-|-|-
48 threads | 18ms | 18ms
1 thread | 243ms | 246ms

Basically no difference.

**Comment by abertens** [comment]
Thinkpad X230, Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz (# of Cores 2. # of Threads 4).

Last read from several tries for each:
Without SSE patch: 370ms
With SSE patch: 125ms

Regards.

**Comment by heckflosse** [comment]
I already pushed a fix, but to a different part of the code where only the blendmask which is used for capture sharpening and dual demosaic is affected (though, blendmask for standard sharpening and pr sharpening also are affected). The blendmask is a mask in the range [0;1] which does not need handling of denormals.
