### ISSUE TITLE
Adding a Help button to open Rawpedia

### ISSUE THREAD

**Issue by TechXavAL** [Beep6581/RawTherapee#5566]
Almost every program has an internal help documentation, and if they don't at the very least they have a link to a website where there is info about the program.

RT don’t have any of these: maybe it's possible adding a question-mark-button next to the preferences button, that when clicked will open Rawpedia in the default browser

And given it's not so difficult to implement, maybe it could be added in the coming 5.8 release.

**Comment by snappyapple632** [comment]
This would help improve the newbie experience as RawTherapee can be a bit overwhelming with the sheer amount of tools it offers. I myself don't understand certain tools, even though I've used this software for about two years now.
