### ISSUE TITLE
RAW Tab disappears

### ISSUE THREAD

**Issue by Nordicpicturesdotnet** [Beep6581/RawTherapee#5570]
1.  I searched here and on google for the issue without finding a solution.
2. I use Gimp 5.7 downloaded 5.6 to check if the issue is related to the last version. It was the same in both versions.
3. ![Untitled](https://user-images.githubusercontent.com/59046101/71155792-cc5a2d00-223e-11ea-84c1-4208dd51995b.png)

4. When I try to edit a picture in the editor everyting seems to work until i hit the raw tab.
the screenshot shows that all functions in the raw tab are available, before I double click the picture to edit it:
![Screen-12-19-2019_84204_AM](https://user-images.githubusercontent.com/59046101/71155374-d3cd0680-223d-11ea-9153-bb97e653f566.png)

But after I doubleclicked the picture to edit it, the functions in the raw tab dissappear.

![Screen-12-19-2019_84304_AM](https://user-images.githubusercontent.com/59046101/71155881-0e836e80-223f-11ea-9e3d-1d0a8ab7ed01.png)

 I need to remove hot pixels. If you have a solution I would be really happy not to try another buggy or expensive raw converter(or both).

**Comment by heckflosse** [comment]
Your file is an already demosaiced m-raw or s-raw file. When you open such a file in RT, it hides all tools which can not be used with already demosaiced files. Shoot raw, not m-raw or s-raw.
