### ISSUE TITLE
Sony A6300 ColorChecker shots

### ISSUE THREAD

**Issue by Entropy512** [Beep6581/RawTherapee#5580]
D50 and stdA at https://filebin.net/ru7dcujz5eaoj00z

I will add a DCP later today, although as I understand it, @Beep6581 prefers to do the profiling runs himself, but I wouldn't mind some input on my own attempts at profiling.  :)

**Comment by Beep6581** [comment]
Hi @Entropy512 , could you re-upload the files and ping me?

**Comment by Entropy512** [comment]
https://filebin.net/dgjbravvlxmeh350 @Beep6581 here you are.

I'd be curious how the DCP I generated compares to yours.

Side note, you probably didn't see me ask this on pixls since you were on vacation, but I'm curious - what's the reasoning for passing -C for the D50 profile but not stdA in the instructions at https://rawpedia.rawtherapee.com/How_to_create_DCP_color_profiles#Creating_DCP_profiles_using_DCamProf ?  Is that something you usually make a decision on a per-profile basis based on how dcamprof behaves when presented with particular data?

**Comment by Beep6581** [comment]
@Entropy512 there is no need for `-C` when using D50:
https://www.ludd.ltu.se/~torger/dcamprof.html#camera_cat

**Comment by Entropy512** [comment]
OK, so then should that be removed from the command line shown on rawpedia?

If I'm reading that correctly, relighting in general should not be necessary for targets that have complete spectral data (which I believe we do have for the CC24/CCPassport?  I can't recheck that until tomorrow.)

**Comment by Beep6581** [comment]
@Entropy512 it's unnecessary in that example as far as I know, so it could be removed, but at the risk of forgetting to put it back in if you use a calibration illuminant different from D50.

**Comment by Entropy512** [comment]
If I'm reading it correctly, then it looks like you don't need it even if the calibration illuminant is different, IF the calibration target you are using has spectral data instead of just XYZ data for each patch - which is the case at least for the .cie files in dcamprof's data-examples directory?

**Comment by Beep6581** [comment]
Yes, that seems to be the case for data from dcamprof, though the data from ArgyllCMS does not contain spectral data as far as I can tell.
