### ISSUE TITLE
Sony A6500 ColorChecker shots

### ISSUE THREAD

**Issue by Entropy512** [Beep6581/RawTherapee#5581]
D50 and stdA at https://filebin.net/fst2hoskz0hojvae for profiling

**Comment by Entropy512** [comment]
I'm guessing @Beep6581 is on vacation for the holidays.

The links have expired for this and the A6300 shots.  Please let me know when a good time to reupload them would be.

**Comment by heckflosse** [comment]
@Entropy512 I downloaded the files

**Comment by Entropy512** [comment]
OK, sounds good.  Let me know if there are any issues with the shots provided.  I'm back home so I can reshoot if weather cooperates.

**Comment by Entropy512** [comment]
@Beep6581 in case @heckflosse didn't forward you the files, let me know if you need me to reupload these too or you already got them from him.

**Comment by Beep6581** [comment]
I have them.
