### ISSUE TITLE
Applying geometric transformations leads to dark artifacts in combination with capture sharpening

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#5588]
The bicubic interpolation we use for geometric transformations leads to artifacts in combination with capture sharpening especially in areas with high contrast. I will create a pr soon to avoid that.
Here's a first screenshot. Left with current code, right with new code:
![grafik](https://user-images.githubusercontent.com/13733487/71583388-7de64180-2b0e-11ea-93ef-490bc3c39043.png)

**Comment by heckflosse** [comment]
The artifacts also appear without using capture sharpening.
With the raw from [here](https://discuss.pixls.us/t/play-raw-daylight-haze/10491) I get dark artifacts when rotating by 0.01 degree
Left neutral profile, right neutral profile + 0.01 degree rotation with old transform code
![grafik](https://user-images.githubusercontent.com/13733487/71624555-6fb62500-2be3-11ea-83dc-cb5f80488e28.png)

The same, but with the new logarithmic transform code
![grafik](https://user-images.githubusercontent.com/13733487/71624574-8c525d00-2be3-11ea-97b5-039e5185032d.png)

**Comment by heckflosse** [comment]
With latest commit you can now switch between linear and logarithmic transform for Lens/Geometry
![grafik](https://user-images.githubusercontent.com/13733487/71685770-94ec9400-2d99-11ea-8cfc-6d1d312b33d2.png)

Here's another example. Left is without lensfun distortion correction. Middle is with lensfun distortion correction using 'Linear'. Right is with lensfun distortion correction using 'Logarithmic'.
![grafik](https://user-images.githubusercontent.com/13733487/71685694-666eb900-2d99-11ea-82d9-ed1e7de4dfaf.png)

Edit: this example was without using capture sharpening

**Comment by Thanatomanic** [comment]
> The bicubic interpolation we use for geometric transformations leads to artifacts in combination with capture sharpening especially in areas with high contrast. 

Hmmm, not withstanding your work Ingo, but isn't this merge a little premature? Your initial observation appeared to be a more general thing so I wonder: what is the cause of these artifacts in Linear mode? I mean, the new Logarithmic mode definitely works better whenever Linear gave artifacts, but it creates its own problems in noisy blacks. So is this an improvement on a whole?
It also introduces another choice for users, one that to me doesn't look very intuitive as to what I should expect from these modes...

**Comment by heckflosse** [comment]
@Thanatomanic 

For sharp (contrasty) input (as CS gives) the linear transform leads to dark artifacts because cubic transform overshoots in linear mode. As I showed, also non CS images can be very contrasty (leading to dark halos).

I can restrict it to be automatically used only if CS is enabled

**Comment by heckflosse** [comment]
@Thanatomanic 
> So is this an improvement on a whole?

Imho it is, as it gives better results for the majority of use cases.

For the remaining use cases linear is still available
