### ISSUE TITLE
Frequent crashes of file browser under macOS

### ISSUE THREAD

**Issue by rfranke** [Beep6581/RawTherapee#5596]
Using the released binaries 5.7 or an own build of the current dev branch under macOS 10.15.2.

RT crashes sporadically during startup. If RT starts, then a crash can easily be produced by repeatedly switching image directories.  The error message is mostly `Segmentation fault: 11`, but may also be `Bus error: 10` or `Abort trap: 6`.

**Comment by rfranke** [comment]
This direct update of the progress bar fixes the crashes. I don't notice a loss of functionality:
```diff
diff --git a/rtgui/filecatalog.cc b/rtgui/filecatalog.cc
index a283398..d2c2ccc 100644
--- a/rtgui/filecatalog.cc
+++ b/rtgui/filecatalog.cc
@@ -800,7 +800,7 @@ void FileCatalog::previewReady (int dir_id, FileBrowserEntry* 
 
     previewsLoaded++;
 
-    _refreshProgressBar();
+    filepanel->loadingThumbs("", (double)previewsLoaded / previewsToLoad);
 }
```

**Comment by heckflosse** [comment]
@rfranke 
> I don't notice a loss of functionality

I didn't test your patch, but does the label of the filebrowser tab still show the progress?

**Comment by rfranke** [comment]
It doesn't :-( 
Just the progress bar shows the progress in percent. The label of the filebrowser tab stays at 0 and updates once at the end.

**Comment by rfranke** [comment]
Well, compiled without the patch once more. The label in the filebrowser tab stays in grey background color during load under macOS, i.e. does not show the progress either, but frequently causes a crash.
Maybe the label and the icon should not be recreated for each update, but just update their content?

**Comment by heckflosse** [comment]
> Maybe the label and the icon should not be recreated for each update, but just update their content?

:+1:

**Comment by rfranke** [comment]
PR #5619 should fix this (tested under MacOS and Linux).
