### ISSUE TITLE
Scroll increment for trackpad under macOS -- what about other systems?

### ISSUE THREAD

**Issue by rfranke** [Beep6581/RawTherapee#5599]
Running the released 5.7 binaries or an own build of the current dev branch under macOS 10.15.2.

Using the built-in trackpad of my MacBook, the thumbnail browser scrolls ways too fast. This is due to multiplication of the delta values of the trackpad with the thumb size in the order of 100, i.e. the browser scrolls 100 times too fast.

The multiplication makes sense for step increments. Connecting a mouse with scroll wheel, one incremental step on the wheel will scroll by one thumb.

The following modification fixes scroll increments with my trackpad (don't multiply delta value with thumb size).

How do trackpads behave on other systems?

```diff
diff --git a/rtgui/thumbbrowserbase.cc b/rtgui/thumbbrowserbase.cc
index 5f75ab4..05c06b0 100644
--- a/rtgui/thumbbrowserbase.cc
+++ b/rtgui/thumbbrowserbase.cc
@@ -86,20 +86,23 @@ void ThumbBrowserBase::scroll (int direction, double deltaX, d
         return;
     }
     //GDK_SCROLL_SMOOTH can come in as many events with small deltas, don't quant
-    double coef;
+    double vcoef, hcoef;
     if(direction == GDK_SCROLL_SMOOTH) {
-        coef = delta;
+        vcoef = deltaY;
+        hcoef = deltaX;
     } else if (direction == GDK_SCROLL_DOWN) {
-        coef = +1.0;
+        vcoef = +1.0 * vscroll.get_adjustment()->get_step_increment();
+        hcoef = +1.0 * hscroll.get_adjustment()->get_step_increment();
     } else {
-        coef = -1.0;
+        vcoef = -1.0 * vscroll.get_adjustment()->get_step_increment();
+        hcoef = -1.0 * hscroll.get_adjustment()->get_step_increment();
     }
 
     // GUI already acquired when here
     if (direction == GDK_SCROLL_UP || direction == GDK_SCROLL_DOWN || direction =
         if (arrangement == TB_Vertical) {
             double currValue = vscroll.get_value();
-            double newValue = rtengine::LIM<double>(currValue + coef * vscroll.ge
+            double newValue = rtengine::LIM<double>(currValue + vcoef,
                                                     vscroll.get_adjustment()->get
                                                     vscroll.get_adjustment()->get
             if (newValue != currValue) {
@@ -107,7 +110,7 @@ void ThumbBrowserBase::scroll (int direction, double deltaX, d
             }
         } else {
             double currValue = hscroll.get_value();
-            double newValue = rtengine::LIM<double>(currValue + coef * hscroll.ge
+            double newValue = rtengine::LIM<double>(currValue + hcoef,
                                                     hscroll.get_adjustment()->get
                                                     hscroll.get_adjustment()->get
             if (newValue != currValue) {
```

**Comment by rfranke** [comment]
Scrolling appears to be a nightmare. See an implementation I came up with for #5593 after tests of the combinations of mac:trackpad, mac:macmouse, mac:pcmouse, linux:pcmouse. Tests for linux:trackpad and windows are still missing but should work according to the current implementation of smooth scrolling with steps in RT.

I wonder if gestures introduced with Gtk 3.14 are more compatible across platforms and devices.

**Comment by Thanatomanic** [comment]
Ping @Entropy512 because of #5426. Also @rfranke take a look at #4663, #4652, #3923 and #1901 for some more history into similar issues regarding scrolling.

**Comment by rfranke** [comment]
Thank you for the links. Sorry to say that, but the implementation appears easiest for Apple by just using `event->delta_x` and `event->delta_y`. Also a magic mouse just behaves like the trackpad.

A lot of additional code, a user defined scroll step, and two work arounds were needed to adapt delta_x/delta_y for PC:
https://github.com/Beep6581/RawTherapee/pull/5593/commits/e4c9e1470f631b76cd2c91940cf555b304b6dd63

If people experience too fast scroll speeds on new Windows laptops, then the scroll step has possibly been removed there as well.

**Comment by Entropy512** [comment]
Hmm, I'll take a look at this again, I was planning on doing some cleanups (see discussion there, including links to GTK documentation saying you shouldn't have both smooth and non-smooth scrolling in the event mask simultaneously) but never got around to it.

Most of my initial work was just to fix an obvious deficiency in Linux.  It sounds like you're having a different issue where either GTK+ is emitting delta values way too large for smooth scroll events?

Define "too fast" - is it such that a slight movement of the scroll mechanism moves you almost immediately to the beginning/end of the file browser, or to minimum/maximum zoom?  If so, we definitely still have some bugs similar to what I fixed.

If it's just subjectively too fast for your tastes, there were some users who felt that one click of a mouse with detents = one thumbnail was too fast.  That was more of a matter of subjective preference, although it also appeared to be affected by relative size of thumbnails vs. size of screen - people with larger thumbnails (larger percentage of the screen) had more issues, so one possible approach might be to have a "maximum percentage of screen" limit for these cases.

**Comment by rfranke** [comment]
> Define "too fast" - is it such that a slight movement of the scroll mechanism moves you almost 
> immediately to the beginning/end of the file browser, or to minimum/maximum zoom? 
> If so, we definitely still have some bugs similar to what I fixed.

Yes. It is almost impossible to move one or two thumbs forward. It appears that the emitted deltas are already scaled and the additional scaling by RT with the thumb size of 100-200 makes the scrolling 100-200 times too fast.

**Comment by Entropy512** [comment]
I'll have to look at what the multiplication factors are on my machine.

Something seems to be behaving strange on MacOS, either the deltas are being prescaled by GTK+ or somehow the scaling factor is bogus on Mac...  I don't know about windows but I'm having good results with multiple mechanical mice (all have scroll detents, I haven't yet tried a mouse that doesn't have scroll detents.  I know these exist because I remember using them before, but don't have any at the moment...) and with multiple trackpads (on both an Acer Aspire R15 and an Asus ROG GU502gv)

Maybe this is a GTK+ regression on MacOS?????

On Ubuntu 19.10, what I see is that even with a non-smooth-scroll device, I get smooth scroll events with a delta of +/- 1.0.

Interesting, https://gitlab.gnome.org/GNOME/gtk/issues/1308 had renewed activity about 2 months ago...  Possibly relevant???

Also, from information provided by @Hombre57 - addressing the comment made in https://gitlab.gnome.org/GNOME/gtk/merge_requests/335#note_319067 was on my TODO list but I still haven't gotten around to it.  I'll try and take a look later this week.

**Comment by rfranke** [comment]
> Maybe this is a GTK+ regression on MacOS?????

It appears too smart for a regression. Somehow the mouse/trackpad driver knows about the display size and scales the deltas.

Edit: or maybe really a regression, like a relative value multiplied with 100 giving percentage?

**Comment by rfranke** [comment]
Did some more tests meanwhile. The Apple magic mouse (with built-in trackpad instead of a scroll wheel) behaves like a PC mouse under Linux Ubuntu 18.04. RT receives each event twice, as a smooth scroll event 4 with direction +-1.0 and as non-smooth scroll events 0-3 with direction 0.0.

Under macOS 10.15.2, RT receives only non-smooth scroll events 0-3 from a PC mouse. The direction is greater 0.0 and adapted to the scroll speed (called "kinetic" in the Gtk issue 1308 linked above). Using an Apple magic mouse, RT receives smooth scroll events 4 with kinetic positive and negative directions as well as sporadic non-smooth scroll events 0-3 with absolute kinetic directions.

The event mask `Gdk::SCROLL_EVENT` vs `Gdk::SMOOTH_SCROLL_EVENT` makes no difference on either system.

These observations suggest that the smooth scroll events 4 (GDK_SCROLL_SMOOTH) are redundant and don't give additional information on both systems. Maybe the consideration of GDK_SCROLL_SMOOTH in combination with additional scaling of reported directions causes the problem under macOS.

Note that use of scroll events for zooming in the RT Editor works on both systems and with both mouse devices satisfactory. Only the scrolling of thumbnails is unusable under macOS.

**Comment by rfranke** [comment]
Yet another observation: scrolling of thumbnails with touchpad on a Windows laptop is ok.

Meaning, the question part of this issue has been answered: only a mac issue.
But the discussion at https://gitlab.gnome.org/GNOME/gtk/issues/1308  is about factors of 1.3-1.5 or 0.5, whereas RT suffers from a factor of 100-200 under macOS. So maybe not an enhancement, but a bug, possibly introduced with #5430 for macOS?

**Comment by rfranke** [comment]
I followed up the issue and found how it is treated by Gtk scrollbars: https://gitlab.gnome.org/GNOME/gtk/blob/gtk-3-24/gtk/gtkrange.c#L3080

PR #5607 provides the fix for RT.

**Comment by Entropy512** [comment]
BTW, sorry I haven't gotten around to reviewing this stuff in more detail...  Adjusting to being back at work after nearly 3 weeks off has been kinda brutal.  :)
