### ISSUE TITLE
Question about White Balance method.

### ISSUE THREAD

**Issue by ilia3101** [Beep6581/RawTherapee#5602]
What method does rawtherapee use for white balancing images? Is it raw channel gain or does it use the something like a bradford transform?

**Comment by Thanatomanic** [comment]
Please see: http://rawpedia.rawtherapee.com/White_Balance
The starting point for the calculation is here: https://github.com/Beep6581/RawTherapee/blob/dev/rtengine/improccoordinator.cc#L1136

**Comment by ilia3101** [comment]
Thanks!
