### ISSUE TITLE
crash in Tab: transform

### ISSUE THREAD

**Issue by arturoisilvia** [Beep6581/RawTherapee#5604]
Hi, 
Found a crash:

Tab: transform
Module Lens/Geometry
	Method: Logarithmic
	Chromatic Aberration Correction: move some slider
crash.

Regards,

-----------------------
Version: 5.7-1752-g7b7c161d3
Branch: newlocallab
Commit: 7b7c161d3
Commit date: 2020-01-08
Compiler: x86_64-w64-mingw32-gcc\ 8.2.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.24.2
Lensfun: V0.3.2.0
Build type: Release
Build flags: -mwin32\ -m64\ -mthreads\ -msse2\ -std=c++11\ -mtune=generic\ -Werror=unused-label\ -Werror=delete-incomplete\ -Wall\ -Wuninitialized\ -Wcast-qual\ -Wno-deprecated-declarations\ -Wno-unused-result\ -fopenmp\ -Werror=unknown-pragmas\ -Wno-aggressive-loop-optimizations\ -DNDEBUG\ -O3\ -ftree-vectorize
Link flags: -m64\ -mthreads\ -static-libgcc\ -mtune=generic\ -s\ -O3
OpenMP support: ON
MMAP support: ON

**Comment by heckflosse** [comment]
Can you reproduce the crash in `dev` ?

**Comment by arturoisilvia** [comment]
I just installed and tested it: It also crashes

-----
Version: 5.7-396-g09b1a5fad
Branch: dev
Commit: 09b1a5fad
Commit date: 2020-01-10
Compiler: x86_64-w64-mingw32-gcc\ 8.2.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.24.2
Lensfun: V0.3.2.0
Build type: Release
Build flags: -mwin32\ -m64\ -mthreads\ -msse2\ -std=c++11\ -mtune=generic\ -Werror=unused-label\ -Werror=delete-incomplete\ -Wall\ -Wuninitialized\ -Wcast-qual\ -Wno-deprecated-declarations\ -Wno-unused-result\ -fopenmp\ -Werror=unknown-pragmas\ -Wno-aggressive-loop-optimizations\ -DNDEBUG\ -O3\ -ftree-vectorize
Link flags: -m64\ -mthreads\ -static-libgcc\ -mtune=generic\ -s\ -O3
OpenMP support: ON
MMAP support: ON

**Comment by heckflosse** [comment]
Can you please provide a raw and a pp3 to reproduce?

**Comment by heckflosse** [comment]
Scratch my last comment. I could reproduce it.

**Comment by heckflosse** [comment]
@arturoisilvia I will fix this at the weekend...

**Comment by arturoisilvia** [comment]
Ok.
