### ISSUE TITLE
LocalLab: cannot choose the type of mask in Vibrance section

### ISSUE THREAD

**Issue by arturoisilvia** [Beep6581/RawTherapee#5609]
You cannot choose the type of mask in Vibrance section in windows Version: 5.7-1778-gaeafd4426:

![Error vibrance](https://user-images.githubusercontent.com/55624244/72411868-3bf30780-376c-11ea-9179-67904224fb0c.JPG)

----
Version: 5.7-1778-gaeafd4426
Branch: newlocallab
Commit: aeafd4426
Commit date: 2020-01-14
Compiler: x86_64-w64-mingw32-gcc\ 8.2.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.24.2
Lensfun: V0.3.2.0
Build type: Release
Build flags: -mwin32\ -m64\ -mthreads\ -msse2\ -std=c++11\ -mtune=generic\ -Werror=unused-label\ -Werror=delete-incomplete\ -Wall\ -Wuninitialized\ -Wcast-qual\ -Wno-deprecated-declarations\ -Wno-unused-result\ -fopenmp\ -Werror=unknown-pragmas\ -Wno-aggressive-loop-optimizations\ -DNDEBUG\ -O3\ -ftree-vectorize
Link flags: -m64\ -mthreads\ -static-libgcc\ -mtune=generic\ -s\ -O3
OpenMP support: ON
MMAP support: ON

**Comment by Desmis** [comment]
@arturoisilvia 
Thank you for testing :)

Fixed in commit 4578d98

jacques
