### ISSUE TITLE
Profiled Lens Correction (Lensfun) DB missing

### ISSUE THREAD

**Issue by longos08** [Beep6581/RawTherapee#5622]
Hi,

On MAC OS Catalina 10.15.2 and RT 5.7 I don't see any values in lens correction camera/lenses dropdown boxes. I checked the lensfun folder within RT application and it's populated with different xml files for various cameras including Canon. I updated lensfun DB and restarted RT - no help.
#This is where I checked the lens profiles
/Applications/RawTherapee.app/Contents/Resources/share/lensfun
#OS 
19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64
![image](https://user-images.githubusercontent.com/11753335/73138382-fa802780-409c-11ea-8e85-d856adf51f2b.png)

**Comment by rfranke** [comment]
Same issue here. It's related to the directory of the lens database. For my own build this is:
```
release/MacOS/../../Resources/../../Resources/./share/lensfun
```
i.e. one `../../Resources` too much. You might apply the following quick fix to your installation of the released 5.7 binaries:
```
cd /Applications/RawTherapee.app
ln -s Contents/Resources Resources
```

**Comment by longos08** [comment]
Thanks for the quick revert! Fix helped.

**Comment by Thanatomanic** [comment]
@longos08 I reopen this issue, because the underlying problem of a wrong directory being set is not fixed

**Comment by ronanM** [comment]
Same problem (no camera list, no lens list) with `Linux Kubuntu 19.10` (`snap` installation).

```
Version: 5.7
Branch: releases
Commit: f335efe
Commit date: 
Compiler: cc 7.3.1
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.22.2
Lensfun: V0.3.2.0
Build type: release
Build flags:  -std=c++11  -Werror=unused-label -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -fopenmp -Werror=unknown-pragmas -O2 -DNDEBUG -ftree-vectorize
Link flags:   
OpenMP support: ON
MMAP support: ON
```

**Comment by rfranke** [comment]
Thank you for the info. I had not tried the snap installation under Linux, but it sounds reasonable that a Linux AppImage has the same issue as a Mac App.

**Comment by Benitoite** [comment]
Here is a new build with lensfun installed to test:
https://kd6kxr.keybase.pub/RawTherapee_OSX_10.9_64_5.8.zip

**Comment by ronanM** [comment]
On `Linux Kubuntu 19.10` with the version `5.8` (https://rawtherapee.com/shared/builds/linux/RawTherapee_5.8.AppImage) the lenses drop-down boxes (for **manually selected**) are still empty.

**Comment by Benitoite** [comment]
@ronanM Thanks
@Beep6581 and @aferrero2707 are the AppImage gurus.

**Comment by rfranke** [comment]
@Benitoite Congrats that you finally made it!
Can access memory cards now, thank's to the hint at rawtherapee.com to grant full disk access to `/bin/sh`. The small triangles are visible.
For some reason I still need the above link for the lensfun database:
```
cd /Applications/RawTherapee.app
ln -s Contents/Resources Resources
```
How did you configure `LENSFUNDBDIR`?
Where does RT store the options file now -- don't find a `~/.config/RawTherapee*` ?

**Comment by Benitoite** [comment]
5.8 was built thusly:

https://github.com/Benitoite/RTdeps/blob/209288ea5093478864a70bb32b008b1142928e50/macbuildRT.sh#L232

`cd ~ && git clone https://github.com/Beep6581/RawTherapee.git repo-rt && cd ~/repo-rt && sudo rm -f -r build && git checkout 5.8 mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE="release"       -DPROC_TARGET_NUMBER="1" -DPROC_LABEL="generic processor" -DCACHE_NAME_SUFFIX="5-dev" -DCMAKE_C_COMPILER="clang" -DCMAKE_CXX_COMPILER="clang++" -DWITH_LTO="ON" -DCMAKE_OSX_SYSROOT="/" -DCMAKE_OSX_DEPLOYMENT_TARGET="10.9"  -DLOCAL_PREFIX:STRING="/opt"  -DLENSFUNDBDIR="./share/lensfun" -DCODESIGNID:STRING="Developer ID Application: Xxxxx Xxxxx (ABCDEFGHIJ)" -DNOTARY:STRING="--username aaaa@aaaa.aaaa --password abcd-efgh-hijk-lmno" -DCMAKE_CXX_FLAGS="-Wno-deprecated-register -Wno-unused-command-line-argument -std=c++11" -DCMAKE_C_FLAGS="-Wno-deprecated-register -Wno-unused-command-line-argument" -DOpenMP_C_FLAGS=-fopenmp=lomp -DOpenMP_CXX_FLAGS=-fopenmp=lomp -DOpenMP_C_LIB_NAMES="libomp" -DOpenMP_CXX_LIB_NAMES="libomp" -DOpenMP_libomp_LIBRARY="/opt/local/lib/libomp.dylib" -DOpenMP_CXX_FLAGS="-Xpreprocessor -fopenmp /opt/local/lib/libomp.dylib -I/opt/local/include" -DOpenMP_CXX_LIB_NAMES="libomp" -DOpenMP_omp_LIBRARY=/opt/local/lib/libomp.dylib -DOpenMP_C_FLAGS="-Xpreprocessor -fopenmp /opt/local/lib/libomp.dylib -I/opt/local/include"   -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON .. && make -j8 install && sudo make macosx_bundle`

So, that lensfun directory is in the Application Bundle under `RawTherapee.app/Contents/Resources/share/lensfun` and use `cmake -DLENSFUNDBDIR="./share/lensfun"` etc.

The RawTherapee options are in its macOS designated area, `~/Library/Application\ Support/RawTherapee/config/options`

**Comment by rfranke** [comment]
OK, even though you configure `-DLENSFUNDBDIR="./share/lensfun"`, `~/Library/Application\ Support/RawTherapee/config/options` says (last lines):
```
[Lensfun]
DBDirectory=../../Resources/./share/lensfun
```
This results in twice `../../Resources/../../Resources/./share/lensfun`, i.e. `RawTherapee.app/Resources/share/lensfun`.

Did you apply [this commit](https://github.com/Beep6581/RawTherapee/commit/2cc89183df862c1744a6578032803737b64fe467#diff-af3b638bc2a3e6c650974192a53c7291) (#5622) that should fix it?

**Comment by Benitoite** [comment]
2cc8918  did make it into the 5.8 tag. 
My options file has
```
[Lensfun]
DBDirectory=./share/lensfun
```
This bit now gone:
https://github.com/Beep6581/RawTherapee/blob/364fe35023874276b9572f58a62b9e62787bc981/CMakeLists.txt#L255-L257
used to apply to all three platforms, but we probably only didn't need the lines on macOS.

See #5639

Also, the prepending `./` looks superfluous, which I might have copied from somewhere at some point before updating the wiki.  Not having the `./` would have maybe not tripped the code in the first place being a relative path.

If you are on `5.8` and have a bad `LENSFUNDBDIR` in your options file, be sure to delete your options file...

**Comment by rfranke** [comment]
Yes, it works after removal of an old `~/Library/Application\ Support/RawTherapee`. Meaning that this issue can be considered solved for macOS :-)

**Comment by ronanM** [comment]
For Linux, replace the value (set by a previous version ?) in `~/.config/RawTherapee/options`:

from
```
[Lensfun]
DBDirectory=
```

to
```
[Lensfun]
DBDirectory=share/lensfun/version_1
```

**Comment by aferrero2707** [comment]
@ronanM does it mean that there is nothing to be fixed in the AppImage, and it is only a configuration problem?

**Comment by ronanM** [comment]
I think the case `DBDirectory=` should be manage to be automatically replaced by the good value.

**Comment by Beep6581** [comment]
@aferrero2707 the appimage works fine on my system.
