### ISSUE TITLE
Removing cropped areas in batch mode RT 5.7 on MAC OS Catalina 10.15.2

### ISSUE THREAD

**Issue by longos08** [Beep6581/RawTherapee#5624]
Hi,

I found a way how to export image without the cropped area by resizing the image to the dimensions of the cropped image - see picture attached.  Before this "trick" I was exporting using batch export which can only allow me to assign one dimension for all images. Now my workflow is split into 2 parts. First I export cropped images 1-by-1. Non-cropped images I do export using the batch file export. Wondering if there is a way how to remove cropped areas in batch...

![image](https://user-images.githubusercontent.com/11753335/73144223-81092900-40de-11ea-8143-20771ba79841.png)

**Comment by Benitoite** [comment]
So what you are saying is that batch crop is broken?   Does this occur for you in https://kd6kxr.keybase.pub/RawTherapee_OSX_10.9_64_5.8.zip ?

**Comment by Beep6581** [comment]
@longos08 can you explain the problem more clearly?

**Comment by longos08** [comment]
ok, will try to explain more clearly...
1. Firstly what I want to achieve / problem statement? 
"How do I export the cropped image without the black areas? ideally in a batch mode and not one by one" This is how it works in LR. LR when exporting into JPEG removes areas that are cropped however in RT when using batch export cropped areas are blackened and not removed...
2. In order to remove the cropped area what I do is I change the dimensions of the image based on cropped image, I resize it, make it smaller and export. But this operation is not batch, I have to do it image-by-image as each cropped image typically has different dimensions.
![image](https://user-images.githubusercontent.com/11753335/73984629-11176000-4974-11ea-9d30-b95d1e03f259.png)

**Comment by longos08** [comment]
> So what you are saying is that batch crop is broken? Does this occur for you in https://kd6kxr.keybase.pub/RawTherapee_OSX_10.9_64_5.8.zip ?

I didn't test the version you mention.

**Comment by heckflosse** [comment]
@longos08 

If you crop, you do not need to resize to the same dimensions.
Just disable the resize tool
Except you want to use post-resize-sharpening
Then you have to enable the resize tool. But that's no problem because you can use this settings then which also work for batch:
![grafik](https://user-images.githubusercontent.com/13733487/74024149-7cc3f200-49a1-11ea-82df-1ee167fc083b.png)

**Comment by longos08** [comment]
> @longos08
> 
> If you crop, you do not need to resize to the same dimensions.
> Just disable the resize tool
> Except you want to use post-resize-sharpening
> Then you have to enable the resize tool. But that's no problem because you can use this settings then which also work for batch:
> ![grafik](https://user-images.githubusercontent.com/13733487/74024149-7cc3f200-49a1-11ea-82df-1ee167fc083b.png)

Ahaaaa :). Thanks. Let's close this one.

**Comment by longos08** [comment]
Thanks for how-to!
