### ISSUE TITLE
Crash clicking "load a profile from file" on macOS High Sierra 10.13.6

### ISSUE THREAD

**Issue by Waveluke** [Beep6581/RawTherapee#5626]
Regardless of the processing profile currently loaded or use of neutral processing profile, raw file used, or raw file location, I was consistently able to make Rawtherapee crash by clicking the load a profile from file icon in the editor tab.  Below is the specs of the version of Rawtherapee being run and the OS specs.

Attatched is the auto-generated crash report log generated by Apple, and a video screen record of the crash.
[RT load profile crash report.txt](https://github.com/Beep6581/RawTherapee/files/4126603/RT.load.profile.crash.report.txt)
[RT bug load pp3_1.mp4.zip](https://github.com/Beep6581/RawTherapee/files/4126605/RT.bug.load.pp3_1.mp4.zip)

Rawtherapee version

Version: 5.7
Branch: 5.7
Commit: f335efe6a
Commit date: 2019-09-10
Compiler: clang 11.0.0.11000020
Processor: generic x86
System: Apple
Bit depth: 64 bits
Gtkmm: V3.24.1
Lensfun: V0.3.95.0
Build type: release
Build flags: -std=c++11 -std=c++11 -mtune=generic -Werror=unused-label -mmacosx-version-min=10.9 -flto -Wall -Wuninitialized -Wcast-qual -Wno-de

precated-declarations -Wno-unused-result -Xpreprocessor -fopenmp /opt/local/lib/libomp.dylib -I/opt/local/include -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags:  -mtune=generic -headerpad_max_install_names -flto
OpenMP support: ON
MMAP support: ON

OS version

macOS High Sierra
Version 10.13.6
iMac (Retina 5k, 27-inch, 2017)
Processor 3.4 GHz Intel Core i5
Memory 16 GB 2400 MHz DDR4
Startup Disk Mackintosh HD
Graphics Radeon Pro 570 4096 MB
Serial Number C02VP0QAJ1GN

**Comment by Waveluke** [comment]
Hello, this is my first bug report.  Feel free to give me any feedback on future bug reports, so I can be more helpful of the developers.  Note that while I recognize that running the debug version of RT would be ideal, I am betatesting on Imac computers that I do not have the administrative privilege to install the debug version of RT, if it even exists for Mac.

**Comment by Beep6581** [comment]
Hi @Waveluke , all good with your bug report :) @rfranke and @Benitoite might have some questions or new builds for you to test.

**Comment by Waveluke** [comment]
Ok, note that I do not have admin privileges on these macs, so new builds I cannot readily test**, though I will be cranking out a few more bug reports on various issues I have discovered on macOS High Sierra Version 10.13.6, so I just wanted to make sure that my reports were done with the best technique possible.   I did notice the revision of the title and will follow that form. 

**Update, this is true, as of now, however, I will make a concerted efforts to obtain administrator privileges, or find an administrator to install said new builds, though I cannot guarantee anything.

**Comment by rfranke** [comment]
Can't reproduce the error on my MacBook running Catalina 10.15.2. According to your error message, the GTK library `libgio-2.0.0.dylib` packaged with RT has been built for 10.15 and doesn't find an expected symbol in the system library `libobjc.A.dylib` under 10.13:
```
Dyld Error Message:
  Symbol not found: _objc_alloc_init
  Referenced from: /RawTherapee.app/Contents/Frameworks/libgio-2.0.0.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libobjc.A.dylib
```
I wonder if we can do much aside from building a specific version of RT for 10.13 High Sierra. Why don't you upgrade your system or alternatively run a matching older version of RT?

**Comment by Waveluke** [comment]
> Can't reproduce the error on my MacBook running Catalina 10.15.2. According to your error message, the GTK library `libgio-2.0.0.dylib` packaged with RT has been built for 10.15 and doesn't find an expected symbol in the system library `libobjc.A.dylib` under 10.13:

This seems highly plausible, as this is just one of many performance and stability issues I have had on this mac computer lab install, which has been puzzlingly counter to my experience running Rawtherapee on Windows (Nothing but sunshine and roses).  I'll pass this advise on to the tech administrator of this lab, trying both of your suggestions, and report back if neither work.

**Comment by Benitoite** [comment]
@Waveluke Here is a new build if you would like to test this issue further.
https://kd6kxr.keybase.pub/RawTherapee_OSX_10.9_64_5.8.zip

**Comment by Waveluke** [comment]
> 
> 
> @Waveluke Here is a new build if you would like to test this issue further.
> https://kd6kxr.keybase.pub/RawTherapee_OSX_10.9_64_5.8.zip

OK, I will test it out once I find a friend who has admin priviledges on a Imac running High Sierra.  I found the bug on a computer I don't have admin priviledges, so there will be some delay.

**Comment by Benitoite** [comment]
@Waveluke the build is also released on RawTherapee.com

**Comment by Benitoite** [comment]
@Waveluke BTW, if you need a working 5.7 https://kd6kxr.keybase.pub/RawTherapee_OSX_10.9_64_5.7.zip

@Beep6581 it can probably replace the non-working https://rawtherapee.com/shared/builds/mac/RawTherapee_OSX_10.9_64_5.7.zip

**Comment by Jaxan** [comment]
I had the same issue with RT 5.7 on MacOS High Sierra. RT 5.8 doesn't crash anymore :-).
