### ISSUE TITLE
Canon EOS M6 Mark II raw decoding support

### ISSUE THREAD

**Issue by Harry456-foto** [Beep6581/RawTherapee#5627]
I have uploaded following files from the camera Canon EOS M6 MKII:

RAW/CRAW | Aspect   ratio | Name
-- | -- | --
RAW | 3:2 | IMG_RAW_3_2.CR3
CRAW | 3:2 | IMG_CRAW_3_2.CR3
RAW | 4:3 | IMG_RAW_4_3.CR3
CRAW | 4:3 | IMG_CRAW_4_3.CR3
RAW | 16:9 | IMG_RAW_16_9.CR3
CRAW | 16:9 | IMG_CRAW_16_9.CR3
RAW | 1:1 | IMG_RAW_1_1.CR3
CRAW | 1:1 | IMG_CRAW_1_1.CR3

Can update Rawtherapee so that it will recognise these filetypes?

**Comment by Beep6581** [comment]
It does already. Color target shots in incandescent tungsten + daylight still needed, as written here: https://github.com/Beep6581/RawTherapee/issues/5522#issuecomment-555644025

**Comment by Harry456-foto** [comment]
Hi Roman,

 

Do you need 8 images of each ( tungsten and daylight) 16 in total ore are 2 images sufficient?

 

 

Kind regards,

 

Harry Cornelis

 

Van: Beep6581 [mailto:notifications@github.com] 
Verzonden: vrijdag 31 januari 2020 19:01
Aan: Beep6581/RawTherapee
CC: Harry456-foto; Author
Onderwerp: Re: [Beep6581/RawTherapee] Canon EOS M6 Mark II raw decoding support (#5627)

 

It does already. Color target shots in incandescent tungsten + daylight still needed, as written here: #5522 (comment) <https://github.com/Beep6581/RawTherapee/issues/5522#issuecomment-555644025>

**Comment by Beep6581** [comment]
Making an input profile requires two photos of a color target, one in daylight and the other incandescent.
http://rawpedia.rawtherapee.com/How_to_create_DCP_color_profiles

**Comment by Harry456-foto** [comment]
Hi Roman,

 

I have uploadad these files:

 

IMG_Tungsten.CR3

IMG_daylight_inside.CR3

IMG_daylight_outside.CR3

 

IMG_Tungsten.CR3 : tungsten light inside the house

IMG_daylight_inside.CR3: daylight inside the house

IMG_daylight_outside.CR3: daylight outside the house, in the garden.

 

These are all images of colorfull toys.

 

Kind regards.

 

Harry Cornelis

 

Van: Beep6581 [mailto:notifications@github.com] 
Verzonden: vrijdag 31 januari 2020 22:35
Aan: Beep6581/RawTherapee
CC: Harry456-foto; Author
Onderwerp: Re: [Beep6581/RawTherapee] Canon EOS M6 Mark II raw decoding support (#5627)

 

Making an input profile requires two photos of a color target, one in daylight and the other incandescent.
http://rawpedia.rawtherapee.com/How_to_create_DCP_color_profiles

**Comment by Harry456-foto** [comment]
Hi,

 

I have installed Rawtherape 5.8 but I still can’t see the CR3 files of my Canon M6 MKII.

 

Do I have to change something in the configuration?

 

 

Met vriendelijke groeten,

 

Harry Cornelis

 

Van: Beep6581 [mailto:notifications@github.com] 
Verzonden: vrijdag 31 januari 2020 22:35
Aan: Beep6581/RawTherapee
CC: Harry456-foto; Author
Onderwerp: Re: [Beep6581/RawTherapee] Canon EOS M6 Mark II raw decoding support (#5627)

 

Making an input profile requires two photos of a color target, one in daylight and the other incandescent.
http://rawpedia.rawtherapee.com/How_to_create_DCP_color_profiles

**Comment by Harry456-foto** [comment]
Hi,

 

I can edit CR3-files directly, by right click and open with Rawtherapee 5.8 but I can’t see the CR3 files in the file explorer in Rawtherapee 5.8.

 

Do I have to change a configuration for this? 

 

 

Met vriendelijke groeten,

 

Harry Cornelis

 

Van: harry [mailto:harry_cornelis@skynet.be] 
Verzonden: zaterdag 8 februari 2020 2:00
Aan: 'Beep6581/RawTherapee'; 'Beep6581/RawTherapee'
CC: 'Author'
Onderwerp: RE: [Beep6581/RawTherapee] Canon EOS M6 Mark II raw decoding support (#5627)

 

Hi,

 

I have installed Rawtherape 5.8 but I still can’t see the CR3 files of my Canon M6 MKII.

 

Do I have to change something in the configuration?

 

 

Met vriendelijke groeten,

 

Harry Cornelis

 

Van: Beep6581 [mailto:notifications@github.com] 
Verzonden: vrijdag 31 januari 2020 22:35
Aan: Beep6581/RawTherapee
CC: Harry456-foto; Author
Onderwerp: Re: [Beep6581/RawTherapee] Canon EOS M6 Mark II raw decoding support (#5627)

 

Making an input profile requires two photos of a color target, one in daylight and the other incandescent.
http://rawpedia.rawtherapee.com/How_to_create_DCP_color_profiles

**Comment by Harry456-foto** [comment]
Hi,

 

I have found it: I had to add an extention to the list but because my screen is too small I didn’t see the buttons at the bottom of the window.

 

It works now.

 

Sorry for annoying.

 

 

Met vriendelijke groeten,

 

Harry Cornelis

 

Van: harry [mailto:harry_cornelis@skynet.be] 
Verzonden: zaterdag 8 februari 2020 2:00
Aan: 'Beep6581/RawTherapee'; 'Beep6581/RawTherapee'
CC: 'Author'
Onderwerp: RE: [Beep6581/RawTherapee] Canon EOS M6 Mark II raw decoding support (#5627)

 

Hi,

 

I have installed Rawtherape 5.8 but I still can’t see the CR3 files of my Canon M6 MKII.

 

Do I have to change something in the configuration?

 

 

Met vriendelijke groeten,

 

Harry Cornelis

 

Van: Beep6581 [mailto:notifications@github.com] 
Verzonden: vrijdag 31 januari 2020 22:35
Aan: Beep6581/RawTherapee
CC: Harry456-foto; Author
Onderwerp: Re: [Beep6581/RawTherapee] Canon EOS M6 Mark II raw decoding support (#5627)

 

Making an input profile requires two photos of a color target, one in daylight and the other incandescent.
http://rawpedia.rawtherapee.com/How_to_create_DCP_color_profiles

**Comment by Harry456-foto** [comment]
Hi,

 

I can edit CR3 files but as far as I can see is the meta-data (exif-data) not imported into RAWtherapee.

 

Can you have a look at it?

 

Met vriendelijke groeten,

 

Harry Cornelis

 

Van: harry [mailto:harry_cornelis@skynet.be] 
Verzonden: zaterdag 8 februari 2020 14:24
Aan: 'harry'; 'Beep6581/RawTherapee'; 'Beep6581/RawTherapee'
CC: 'Author'
Onderwerp: RE: [Beep6581/RawTherapee] Canon EOS M6 Mark II raw decoding support (#5627)

 

Hi,

 

I have found it: I had to add an extention to the list but because my screen is too small I didn’t see the buttons at the bottom of the window.

 

It works now.

 

Sorry for annoying.

 

 

Met vriendelijke groeten,

 

Harry Cornelis

 

Van: harry [mailto:harry_cornelis@skynet.be] 
Verzonden: zaterdag 8 februari 2020 2:00
Aan: 'Beep6581/RawTherapee'; 'Beep6581/RawTherapee'
CC: 'Author'
Onderwerp: RE: [Beep6581/RawTherapee] Canon EOS M6 Mark II raw decoding support (#5627)

 

Hi,

 

I have installed Rawtherape 5.8 but I still can’t see the CR3 files of my Canon M6 MKII.

 

Do I have to change something in the configuration?

 

 

Met vriendelijke groeten,

 

Harry Cornelis

 

Van: Beep6581 [mailto:notifications@github.com] 
Verzonden: vrijdag 31 januari 2020 22:35
Aan: Beep6581/RawTherapee
CC: Harry456-foto; Author
Onderwerp: Re: [Beep6581/RawTherapee] Canon EOS M6 Mark II raw decoding support (#5627)

 

Making an input profile requires two photos of a color target, one in daylight and the other incandescent.
http://rawpedia.rawtherapee.com/How_to_create_DCP_color_profiles

**Comment by Thanatomanic** [comment]
@Harry456-foto Please do not reply to GitHub issues directly from e-mail again. This seriously messes up the layout.

And there is already an issue for things related to CR3 support. #5319 Both of your points are known.
