### ISSUE TITLE
Canon EOS M6 Mark II color targets

### ISSUE THREAD

**Issue by Harry456-foto** [Beep6581/RawTherapee#5628]
Yesterday, have uploaded following files from the Canon Camera M6 MKII:

RAW/CRAW | Aspect   ratio | Name
-- | -- | --
RAW | 3:2 | IMG_RAW_3_2.CR3
CRAW | 3:2 | IMG_CRAW_3_2.CR3
RAW | 4:3 | IMG_RAW_4_3.CR3
CRAW | 4:3 | IMG_CRAW_4_3.CR3
RAW | 16:9 | IMG_RAW_16_9.CR3
CRAW | 16:9 | IMG_CRAW_16_9.CR3
RAW | 1:1 | IMG_RAW_1_1.CR3
CRAW | 1:1 | IMG_CRAW_1_1.CR3

Today I have uplodaded:

IMG_Tungsten.CR3
IMG_daylight_inside.CR3
IMG_daylight_outside.CR3

Can you update Rawtherapee so that I can edit CR3 canon files?

I have Rawtherapee 5.7 inbstalled but I can't edit these files.

Kind Regards,

Harry Cornelis
IMG_daylight_outside.CR3

**Comment by Thanatomanic** [comment]
Harry, could you please upload the files to https://filebin.net and post the link here? The DCP-related shots should not be uploaded to raw.pixls.us, that's not the purpose of the repository.

**Comment by Harry456-foto** [comment]
I could only upload 1 file https://filebin.net/kxlq01tweiphdf66

The other files gave network problems. Should I sent them to you via wetransfer?

Met vriendelijke groeten,
Harry Cornelis

**Comment by Thanatomanic** [comment]
A WeTransfer link would be equally useful. Thank you for the effort.

(btw, I've cleaned up your post a little bit, replying directly from email is kinda messy)

**Comment by Harry456-foto** [comment]
Img_tungsten.zip and others: https://filebin.net/jpky96yeve7nhz9m

Kind regards,
Harry Cornelis

**Comment by Thanatomanic** [comment]
Now that you've uploaded them I see that you actually didn't shoot a color chart (e.g.  X-Rite ColorChecker Passport Photo or similar). @Beep6581 can correct me if I'm wrong, but without a color chart there is no possibility to calibrate.

**Comment by Harry456-foto** [comment]
I don’t have a color chart. Do I have to buy it?

 

 

Met vriendelijke groeten,

 

Harry Cornelis

 

Van: Thanatomanic [mailto:notifications@github.com] 
Verzonden: zaterdag 1 februari 2020 14:28
Aan: Beep6581/RawTherapee
CC: Harry456-foto; Author
Onderwerp: Re: [Beep6581/RawTherapee] Canon EOS M6 Mark II color targets (#5628)

 

Now that you've uploaded them I see that you actually didn't shoot a color chart (e.g. X-Rite ColorChecker Passport Photo or similar). @Beep6581 <https://github.com/Beep6581>  can correct me if I'm wrong, but without a color chart there is no possibility to calibrate.

**Comment by Beep6581** [comment]
The Canon EOS M6 Mark II is already supported, but lacks an input profile. Creating an input profile requires photographs of a color target under daylight and under incandescent tungsten light.

More info:
http://rawpedia.rawtherapee.com/Adding_Support_for_New_Raw_Formats
http://rawpedia.rawtherapee.com/How_to_create_DCP_color_profiles

Color target shots not provided, closing.
