### ISSUE TITLE
canon_cr3_decoder.cc references

### ISSUE THREAD

**Issue by Alexey-Danilchenko** [Beep6581/RawTherapee#5634]
Please fix the copyright references for the CR3 decoder. It is in all entirety lifted from LibRaw https://github.com/LibRaw/LibRaw/blob/master/src/decoders/crx.cpp yet bears no copyright from LibRaw. References to ART as well are a bit misleading since no such project can easily be found.

**Comment by Beep6581** [comment]
@Alexey-Danilchenko 

> yet bears no copyright from LibRaw

https://github.com/Beep6581/RawTherapee/blob/dev/rtengine/canon_cr3_decoder.cc#L41

Is anything missing?

**Comment by Alexey-Danilchenko** [comment]
Check the link I have in my post to LibRaw version - notice their copyright?

**Comment by Alexey-Danilchenko** [comment]
What is ART btw? You have "Code adapted from ART" but I could not find any references to their source/origin.

**Comment by heckflosse** [comment]
> What is ART btw?

https://bitbucket.org/agriggio/art/src/master/

**Comment by Beep6581** [comment]
@Alexey-Danilchenko thanks for pointing that out, I'm committing a fix.

ART is a fork of RawTherapee.

**Comment by agriggio** [comment]
@Alexey-Danilchenko apologies, this is my fault. I took an old copyright header for LibRaw instead of the proper one. I'll fix this in ART as well asap.
