### ISSUE TITLE
Rawtherapee v5.8 not opening canon m-Raw images correctly 

### ISSUE THREAD

**Issue by adriangonsalves** [Beep6581/RawTherapee#5638]
I can reproduce this issue on windows and Linux. It seems to be specificaly related to opening canon M-raw images (raw images but scaled down). 
[https://cpn.canon-europe.com/content/education/infobank/image_compression/file_types_raw_sraw_and_jpeg.do](https://cpn.canon-europe.com/content/education/infobank/image_compression/file_types_raw_sraw_and_jpeg.do)

In v5.6 (i have also tested V5.7 on windows) the image renders correctly, however in v5.8 it renders the image way , way too dark. Find attached screenshots of the same 
![Screenshot_rawtherapee_5 8](https://user-images.githubusercontent.com/12772129/73991073-abde5300-4910-11ea-980d-d4a7ec155075.png)
![Screenshot  Raw_therapee_5 6](https://user-images.githubusercontent.com/12772129/73991075-abde5300-4910-11ea-9c7e-3312662e9238.png)

I have stored the sample CR2 and the corresponding pp3 file here  - 
[https://drive.google.com/drive/folders/1J6ebSFcHiqPlUS3Dn9sNA_KoFplzd0mW?usp=sharing](https://drive.google.com/drive/folders/1J6ebSFcHiqPlUS3Dn9sNA_KoFplzd0mW?usp=sharing)

I have tested with regular raw files and they seem to work fine

**Comment by Benitoite** [comment]
Same on macOS.

**Comment by heckflosse** [comment]
> M-raw images (raw images but scaled down).

They are not raw. They are already demosaiced.

I will have a look...

**Comment by heckflosse** [comment]
It's caused by https://github.com/Beep6581/RawTherapee/commit/0cf3f16dfa58b4fcefd6d49965f8337333f076a4

Looking how to fix it...
