### ISSUE TITLE
RT 5.8 File Browser Not Showing CR3 Thumbnails

### ISSUE THREAD

**Issue by rich-james** [Beep6581/RawTherapee#5640]
In RT 5.8 Windows 8.1 x64:

File Browser not displaying thumbnails for any CR3 files in a directory.  However, individual CR3 files can be opened and modified without issue in the Editor using a right click, "Open with RawTherapee" command.

In Preferences > File Browser > Parsed Extensions, CR3 is not listed as an option for selection.  You have do an Add for CR3 to get the thumbnails to display.

**Comment by Benitoite** [comment]
No problem with .CR3 thumbnails on MacOS `5.8` and `dev`.
Perhaps try deleting your options file and re run your `5.8`?
![Screen Shot 2020-02-07 at 11 34 25 AM](https://user-images.githubusercontent.com/17919239/74060292-826c0880-499e-11ea-8e9e-655d8d4ea2bd.png)

**Comment by rich-james** [comment]
Thanks! Deleting the options file worked.  Now CR3 shows up as a checked option in the list of parsed extensions.  

BTW, the new Capture Sharpening is a great addition.

    On Friday, February 7, 2020, 11:40:18 AM PST, Benitoite <notifications@github.com> wrote:  
 
 
No problem with .CR3 thumbnails on MacOS 5.8 and dev.
Perhaps try deleting your options file and re run your 5.8?
