### ISSUE TITLE
Samsung Galaxy S7 DCP profiles

### ISSUE THREAD

**Issue by NAwlinsContrarian** [Beep6581/RawTherapee#5647]
I'm submitting Samsung Galaxy S7 raw files of my X-Rite ColorChecker Passport for your use in creating DCP profiles for RawTherapee users. I also have the DCP files--both a dual-illuminant and separate sunlight and tungsten--but I understand that you want to make the DCPs yourselves. The two DNGs are posted at:

https://filebin.net/2byvzwevvkydi0pg

**Comment by Beep6581** [comment]
> for your use in creating DCP profiles for RawTherapee users

@NAwlinsContrarian you'd need to state that you're releasing the raw files into the public domain.

**Comment by NAwlinsContrarian** [comment]
Yes, I am releasing these two DNG raw files (Samsung Galaxy S7 photos of my X-Rite ColorChecker Passport) into the public domain.

**Comment by Thanatomanic** [comment]
@NAwlinsContrarian If you still have these DNGs available, would you be willing to reupload them?

**Comment by Beep6581** [comment]
@Thanatomanic no need, I have already handled them, just haven't committed the DCP yet.

**Comment by Beep6581** [comment]
All accepted color target raw files can be found here: http://rawtherapee.com/shared/colortarget/
