### ISSUE TITLE
Regression: NIKON D5100 14-bit uncompressed raw files open black - Corrupt data near ...

### ISSUE THREAD

**Issue by drvanger** [Beep6581/RawTherapee#5654]
Nikon NEF file made with Nikon D5100 open as if they were completely black. In the file browser they are displayed correctly, but after opening a file in the editor by enter, the image becomes black. After that, they display as black rectangles also in the file browser. This happens only after the update to version 5.8. Version 5.7 and before worked correctly with the same raw files. As far as I can determine, this happens to all of my NEF files (several of which were edited with previous versions of Rawtherapee). I attached screenshots and uploaded a sample NEF file with an autogenerated pp3 file to: [here](https://drive.google.com/open?id=1ycFVH3q0iOQBffita41E1UWUnuOLHZXf)
After opening the file for editing, the following error message appears in the terminal: 
```
/home/duri/Képek/2019_tel/rtbug/new/newest/DSC_9677.NEF: Corrupt data near 0x20879a0
/home/duri/Képek/2019_tel/rtbug/new/newest/DSC_9677.NEF: Corrupt data near 0x20879a0
/home/duri/Képek/2019_tel/rtbug/new/newest/DSC_9677.NEF: Corrupt data near 0x20879a0 
```

I'm using linux (Manjaro, kernel 5.4.18-1 but I could reproduce it with openSUSE 15.0 (linux 4.12.14)), and tried to use the official packages, as well as compiling Rawtherapee 5.8 from source. 

![RT-browser-screenshot](https://user-images.githubusercontent.com/42266827/74589493-1e80ba00-5006-11ea-90a3-d81a3310869c.png)
![RT-editor](https://user-images.githubusercontent.com/42266827/74589494-20e31400-5006-11ea-9d91-fd6e27c53b4b.png)

**Comment by Beep6581** [comment]
Tested using other NIKON D5100 raw files (from [RPU](https://raw.pixls.us/)). Confirmed that compressed (lossless and lossy type 2) open correctly in `5.8-47-g`12b1d8f76, while 14-bit uncompressed open black.

**Comment by Beep6581** [comment]
Confirmed that 5.7 opened all three types correctly.

**Comment by heckflosse** [comment]
Caused by https://github.com/Beep6581/RawTherapee/commit/bd6088837c99b95f9a9c53fdd5ff4990f1c550c0

**Comment by heckflosse** [comment]
Last row of this files contains garbage
![grafik](https://user-images.githubusercontent.com/13733487/74592607-3286e480-5023-11ea-9f3e-c25b0adc3a8a.png)

I can fix that by reducing height by one or by two for this files. I prefer reducing height by two to get an even height.

**Comment by ValZapod** [comment]
You need to patch D5100 with https://simeonpilgrim.com/nikon-patch/nikon-patch.html to reproduce that! I can confirm the fix, uncompressed does open after commut above.
