### ISSUE TITLE
Sigma C 18-200 mm f/3.5-6.3 DC Macro OS HSM detection

### ISSUE THREAD

**Issue by KrzysztofWardynszkiewicz** [Beep6581/RawTherapee#5657]
RawTherapee 5.8 detects my 'Sigma C 18-200 mm f/3.5-6.3 DC Macro OS HSM' as Tamron.

Here is one of problematic NEF's:
https://www.dropbox.com/s/7nxnx8uu3hczohh/DSC_0001.NEF?dl=0

**Comment by Beep6581** [comment]
ExifTool-11.83 which RT5.8 uses detected it as:
```
Lens ID                         : Unknown (89 3F 2D 80 2C 40 4B 0E)
Lens Spec                       : 18-200mm f/3.5-6.3 G VR
```
ExifTool-11.87 detects it as:
```
Lens ID                         : Sigma 18-200mm F3.5-6.3 DC Macro OS HS | C
Lens Spec                       : 18-200mm f/3.5-6.3 G VR
```

Closing as handled by #3801
