### ISSUE TITLE
RawTherapee 5.8 Issue Processing Canon EOS 60D Files

### ISSUE THREAD

**Issue by AnthraxCat** [Beep6581/RawTherapee#5659]
RawTherapee Info:
Version: 5.8
Branch: releases
Commit: 9a9e0acbf
Commit date: 2020-02-04
Compiler: x86_64-w64-mingw32-gcc\ 8.2.0

Windows 10 64bit

Issue:

When loading RAW photos, they are completely messed up. They show up correctly in the preview bar at the top of the editor, but when loaded into the editor become irreversibly green and extremely black. No default profile is being applied, clearing profile does nothing. Applying a neutral profile does nothing, nor does applying personal profiles that worked in the past. The issue persists across different folders, dates, and drives.
![RawTherapee_Issue1](https://user-images.githubusercontent.com/61339275/75085786-ee478880-54e9-11ea-82c7-8a18a5d33e4f.png)
![RawTherappe_Issue2](https://user-images.githubusercontent.com/61339275/75085785-edaef200-54e9-11ea-85b8-da1c11b9a3e8.png)

RAWs appear correctly in the File Explorer, but have whatever is messing up applied immediately after opening them.
![RawTherappe_Issue3](https://user-images.githubusercontent.com/61339275/75085789-f6072d00-54e9-11ea-83d9-47dbac15f1a4.png)

The distortion can be cleared by clearing the profiles, but setting it to Neutral, or any other profile will immediately restore the distorted colour profile.
![RawTherappe_Issue4](https://user-images.githubusercontent.com/61339275/75085791-f69fc380-54e9-11ea-9062-022401dd06db.png)

Images continue to be horribly distorted when exported to JPEG.
![IMG_5265](https://user-images.githubusercontent.com/61339275/75085615-4d0c0280-54e8-11ea-83f7-bcbfbf8f0d53.jpg)

These images were all processed originally in 5.4 or 5.7 so I know there is nothing wrong with the files themselves. Deleting the old PP3 files does not resolve the issue. Uninstalled all previous RawTherapee installs, as well as 5.8 and reinstalled and the issue persists.

**Comment by Thanatomanic** [comment]
Can you please upload your raw file for investigation? I tested all available 60D samples on https://raw.pixls.us and they seem to work fine (RAW, mRAW, sRAW, 14-bit DNG).

**Comment by AnthraxCat** [comment]
The RAW file I have in the screenshots is here: https://filebin.net/t8ngzuw5c0pa99de

**Comment by Thanatomanic** [comment]
This was actually addressed in #5638 and fixed in https://github.com/Beep6581/RawTherapee/commit/4221fdf31e43658cef98ad660ad398b8ae81b8d7

If you want to update your version of RT, please try a nightly build from here: https://github.com/Beep6581/RawTherapee/releases/tag/nightly 
(scroll all the way down and get the RawTherapee_dev_5.8-53-g17767ce0a_20200218.exe or win_64.zip version)
