### ISSUE TITLE
White balance shows wrong method when opening a file which was set to Auto in 5.8

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#5668]
To reproduce
1) Start RT 5.8 release
2) open a file
3) set wb to auto
4) close RT
5) Start RT dev build
6) open the file
now the method shows 'Camera' but uses the values from before

**Comment by Desmis** [comment]
@heckflosse 

Ingo
I tried to solved this problem.

First I tested with ppversion by increasing ppversion and change code, not good (for me)  :)

Then I tested in procparams if "white balance" "settings" is "Auto" and change to "autold"

Seems to work, but I am doubtfully 

I create a branch "wrong_oldwbauto"

Can you test

Thank you

jacques

**Comment by heckflosse** [comment]
@Desmis Jacques, I will test now

**Comment by heckflosse** [comment]
@Desmis Jacques, may I push to your branch?

**Comment by Desmis** [comment]
@heckflosse 
Ingo
No problem at all :)

**Comment by heckflosse** [comment]
@Desmis I pushed a simplified fix based on your fix.

**Comment by Desmis** [comment]
OK I will test

Thank you

Jacques

**Comment by Desmis** [comment]
@heckflosse 

Ok, It works well, and you simplify my code

Do you think we can merge ?

If so, you can, thank you (or if you want me to do it, I can)
jacques

**Comment by heckflosse** [comment]
@Desmis Jacques, please merge :+1:

**Comment by Desmis** [comment]
@heckflosse 

Ingo

merge :)
