### ISSUE TITLE
The diagonal line in the curve tools is difficult to see

### ISSUE THREAD

**Issue by teplit** [Beep6581/RawTherapee#5687]
I use calibrated and profiled 24” 4K monitor with measured static contrast below 700. On it the dashed diagonal line of the curve tools is thin and difficult to distinguish from the background (especially for curve tools without histogram). For me it is not a problem to see thin lines provided they are not difficult to differentiate from the background.

I use RawTherapee 5.8 on Windows 10 (1909) machine.

**Comment by simohno** [comment]
Oh God I notice _now_ there is one, after 2 months of using RT! 😁 It's really thin and dark. It would be one more comfort, and could be drawn in a medium-light gray indeed

**Comment by teplit** [comment]
The problem concerns the default RawTherapee theme called RawTherapee. It is substantially less pronounced in other themes.

**Comment by Thanatomanic** [comment]
@TooWaBoo I've pushed a fix for this, but if you don't like how it works with your themes, please let me know and we'll revert.
