### ISSUE TITLE
Tokina 11-20 lens correction does't seem to be applied

### ISSUE THREAD

**Issue by paolostivanin** [Beep6581/RawTherapee#5688]
I can see from [here](https://github.com/Beep6581/RawTherapee/blob/40018b1e9ad9e0db306ffac6e6c7ceaac97927f6/rtexif/nikonattribs.cc#L897) that the Tokina 11-20 f/2.8 for Nikon is supported.
I opened a NEF shot with this lens and I don't understand whether Rawtherapee is automatically applying lens correction or not. (`Automatically selected`  in `Lens/Geometry - Profiled Lens Correction` is selected).
From the `History` panel there is no sign of lens correction being applied.
So I wanted to apply it manually and, therefore, I opened the Tokina list from the `Lens/Geometry` panel under `Manually selected - Lens - Tokina` but I don't see this lens in the list.

OS: `openSUSE Tumbleweed x64 with GNOME 3.34`
Kernel: `5.5.7`
Rawtherapee: `v5.8`

[example_nef.zip](https://github.com/Beep6581/RawTherapee/files/4349554/example_nef.zip)

![main win](https://user-images.githubusercontent.com/1040943/76973128-cf44e680-692f-11ea-90e0-91a373bc7c25.png)

**Comment by gaaned92** [comment]
@paolostivanin 
To get an automatic correction you need the 2 following ;
- Rawtherapee must correctly decode the lens maker and the lens name. That is not an easy task. to verify click on the information button in the editor and note the lens name. I think it is decoded ok on your version.
![rawtherapee_fuccYpBoAM](https://user-images.githubusercontent.com/13785581/77001484-527b3200-695a-11ea-9955-74f1116dce88.png)

- the lens must be present in the lensfun database . hereunder it is present:
![rawtherapee_1Wiqmy3HPN](https://user-images.githubusercontent.com/13785581/77001800-cddce380-695a-11ea-97e9-c610de1b502a.png)
So  your database is not up to date. 
The way to update the database is to use the script `lensfun-update-data`, but as I am not a Linux user, I cannot help.
Or perhaps you could download a more recent development RT build for your system.
Could somebody more knowledgeable on Linux and Lensfun explain how to update?

**Comment by paolostivanin** [comment]
Thanks a lot! I wasn't aware of the lensfun part :)
I was able to update it easily on openSUSE by installing `lensfun-tools` and then executing `sudo /usr/bin/lensfun-update-data` . I discovered that the packages are quite outdated there, so I'm also gonna update them on openSUSE :+1:
