### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by dafrasaga** [Beep6581/RawTherapee#5689]
Hi with the new dev version if I move the soft radius slider of Shap-mask and Clarity on Wavelets I get Segmentation fault

**Comment by Desmis** [comment]
@dafrasaga 
I cannot reconstitued....
Could you give an example (raw, pp3)

Thank you :)

jacques

**Comment by dafrasaga** [comment]
Hi Desmis, these are the files
I open the file with neutral profile, after I enable wavelet+sharp and mask and when I touch Soft Radius RT crashes into segmentation fault



[Pictures.zip](https://github.com/Beep6581/RawTherapee/files/4353299/Pictures.zip)

**Comment by Thanatomanic** [comment]
~~I also cannot reproduce. Your provided PP3 is simply a neutral profile?
@dafrasaga Which version of RT are you using? If possible, use a development debug build and provide a backtrace of the crash (http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports)~~

I spoke too soon. I have a crash! Investigating...

**Comment by Thanatomanic** [comment]
To reproduce, do what @dafrasaga said: open image, apply Neutral, turn on "Wavelet levels", turn on "Sharp-mask and Clarity" and adjust the slider for "Soft Radius".
The crash only happens when you're not at 100%.

Here's a backtrace 
[debuglog.txt](https://github.com/Beep6581/RawTherapee/files/4353462/debuglog.txt)

**Comment by Thanatomanic** [comment]
In addition: I tried several other images, and there I could not reproduce the crash. So it has something to do with this particular RAW file as well...

**Comment by Desmis** [comment]
@dafrasaga  @Thanatomanic 

I have found the bug.... carelessness on my part

I commi with a fix soon :)

Thank you very much
jacques

**Comment by Desmis** [comment]
@dafrasaga  @Thanatomanic 

Push commit d63fb77

I hope it fix the crash :)

**Comment by dafrasaga** [comment]
Thanks..it seems fixed .
