### ISSUE TITLE
Raw CA correction sometimes fails, lens profiled CA correction is even worse

### ISSUE THREAD

**Issue by afontenot** [Beep6581/RawTherapee#5719]
**Description**

Not-so-infrequently I will have images with CA (chromatic aberration) bad enough that RawTherapee can't handle them, and I have to fall back to using e.g. Lightroom. Here is an example of such an image: 

Rawtherapee (cropped):

![IMG_8648_rt_small](https://user-images.githubusercontent.com/3870410/79943546-fe161700-841d-11ea-8af8-6d0d52db3722.png)

Lightroom (cropped):

![IMG_8648_lr_small](https://user-images.githubusercontent.com/3870410/79943569-079f7f00-841e-11ea-9771-e84b31ca1694.png)

Lightroom is here using all its default settings, except that I turned up the "remove CA" slider slightly because the default didn't get rid of all of it. Rawtherapee has tone curve settings and white balance set to match Lightroom as closely as possible, to make the comparison more 1:1. RAW CA is enabled and the iterations are set to max, and lens corrections are turned off. *However*, the same problem is *clearly* visible with the neutral profile and any number of CA iterations. I'm including the original RAW file for developers to look at.

I also tried manually setting the RAW CA sliders, but couldn't do better than the automatic version. Turning off RAW CA and turning on the lens correction CA made the problem *much* worse. (This might be a bug in its own right?)

Sorry that this is maybe not a very useful report if you're already aware of the problem. Basically, my issue is that "CA removal is bad, sometimes", and this keeps me from consistently using RawTherapee.

**Version Info**

Arch Linux 5.6.4-arch1-1

RawTherapee 5.8-1 (official Arch package)

**Test files**

I'm placing the following image(s) under [CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/).

https://drive.google.com/drive/folders/1ZH-mJjYdUKxVIZ8jAeeNV1-6r6lOkq_U

**Comment by Thanatomanic** [comment]
It's hard to compare with Lightroom because any number of hidden things could be happening. If you enable the Defringe module in RT you get rid of pretty much any hint of CA. And to be honest, I think the default result with auto-correction CA applied is already quite good considering the lens and contrasty lighting conditions make this a prime example of strong CA.

Neutral (+1 EV exposure)
![IMG_8648](https://user-images.githubusercontent.com/6567747/79952581-ef118200-847a-11ea-9841-5f61d571629b.png)

Neutral (+1 EV exposure, raw CA correction: two iterations, Avoid color shift unchecked)
![IMG_8648-1](https://user-images.githubusercontent.com/6567747/79952636-02bce880-847b-11ea-8047-2284a289d409.png)

Neutral (+1 EV exposure, raw CA correction: two iterations, Avoid color shift unchecked, Defringe enabled on default settings)
![IMG_8648-2](https://user-images.githubusercontent.com/6567747/79952845-52031900-847b-11ea-89d6-3d0c9f28fc12.png)

**Comment by Thanatomanic** [comment]
If I try a little harder to match the tone of the image with your LR export, I even think RT does a _better_ job at removing CA and false colors. Note for example the thicker branch in the middle of the 'open' sky. In your LR export I see a hint of blue / red color cast across the branch. There is none in this RT edit.

![IMG_8648-3](https://user-images.githubusercontent.com/6567747/79953371-09982b00-847c-11ea-9567-2c64506b119e.png)
[IMG_8648-3.png.out.pp3.txt](https://github.com/Beep6581/RawTherapee/files/4514464/IMG_8648-3.png.out.pp3.txt)

**Comment by afontenot** [comment]
I'll take another look at it. Granted, it might be possible to match or even improve on Lightroom with enough work (although it's quite possible that Lightroom would be further improved by bumping up the anti-CA slider a little more).

My point with this bug report, at least in part, is that I didn't have to do anything to get this to work in Lightroom. I just imported the image, decided the default anti-CA wasn't quite strong enough, bumped the slider a little more, and exported. With RawTherapee I found it impossible to match the 10 seconds of work in Lightroom after an hour of messing with sliders. Granted, maybe I'm not good enough at using RT and it would be easier for someone else. If that's turns out to be the consensus, consider this bug report a "make anti-CA more intuitive / easier to use" request. We apparently have (at least) 3 different modules that attempt to do anti-CA?

Edit: okay, so I had another quick look, and have to add what's partially an apology and partially another bug report. The following settings are *very* confusing IMO:

![ca_correction_not_finetune](https://user-images.githubusercontent.com/3870410/79977468-28ce9280-8453-11ea-8abb-d34dc9baa805.png)

This is all part of the lens / geometry module. Note that [correct] chromatic aberration is *not* checked. Despite this, if the two sliders shown are activated, CA correction *will* be applied!! I had assumed that the "chromatic aberration" checkbox in the module would enable / disable CA corrections for the module. Not so! I apparently had these sliders activated (probably from a preset) when I exported the images shown in my initial bug report. These sliders were making the problem *much* worse that it otherwise would be, as shown in @Thanatomanic's results.

So apparently, there are at least four anti-CA controls? And it's sometimes unclear which ones are active and which ones are not. I think this situation could be improved, but maybe you want another bug report for that.

**Comment by Thanatomanic** [comment]
> My point with this bug report, at least in part, is that I didn't have to do anything to get this to work in Lightroom. I just imported the image, decided the default anti-CA wasn't quite strong enough, bumped the slider a little more, and exported. With RawTherapee I found it impossible to match the 10 seconds of work in Lightroom after an hour of messing with sliders. Granted, maybe I'm not good enough at using RT and it would be easier for someone else. If that's turns out to be the consensus, consider this bug report a "make anti-CA more intuitive / easier to use" request. We apparently have (at least) 3 different modules that attempt to do anti-CA?

Try this in RT for a less-than-10-second-approach: apply the 'Auto-Matched Curve - ISO Low' profile to your image and enable Defringe, then tell me how well you like that starting point for further development 😉 

RawTherapee and Lightroom simply have different philosophies regarding photo processing. Lightroom is more top-down, RawTherapee is more bottom-up, if you get my meaning.

**Comment by Thanatomanic** [comment]
@afontenot 
>This is all part of the lens / geometry module. Note that [correct] chromatic aberration is not checked. Despite this, if the two sliders shown are activated, CA correction will be applied!! I had assumed that the "chromatic aberration" checkbox in the module would enable / disable CA corrections for the module. Not so!

Yes, there are a number of CA-like tools in RT. Their function is different in each case, but feel free to make a separate issue to discuss simplifiying this.

**Comment by afontenot** [comment]
I've done that, thanks.

**Comment by afontenot** [comment]
I'm closing this for now in favor of https://github.com/Beep6581/RawTherapee/issues/5723. I think the following two things have resolved this issue, as far as I can immediately tell:

1. Make sure you don't have multiple, incompatible CA corrections enabled (see the above bug).
2. Try the fringe removal tool. I hadn't attempted to fix anything with that recently, but it got rid of a lot of the remaining CA in my image.

If I encounter more images that can't be repaired using this approach, I'll either reopen this bug or file a new one.
