### ISSUE TITLE
Profiles menu doesn't fully expand when near the top of the screen

### ISSUE THREAD

**Issue by afontenot** [Beep6581/RawTherapee#5725]
For clarity, I'm talking about this menu:

![rt_profiles_menu](https://user-images.githubusercontent.com/3870410/80047827-4d625300-84c3-11ea-80db-d040d45d3517.png)

Even though there is plenty of room to expand downward on my screen, this tiny menu opens open with scrollbars and is difficult to use and click on as a result.

Here is a screenshot of the problem:

![0273](https://user-images.githubusercontent.com/3870410/80047931-8dc1d100-84c3-11ea-9edc-28180d6d34dc.png)

I recorded a short video that shows trying to open and use this menu:

https://drive.google.com/open?id=1r_1Je8rBnfFbxDuCtKV7CWSY4YFoPjE3

Admittedly this is a nit of an issue, but it's one I encounter on almost every image I open, so it's bothered me enough to report it.

**Version Info**

RawTherapee 5.8

Arch Linux 5.6.4-arch1-1

KDE Plasma 5.18.4.1

**Comment by Thanatomanic** [comment]
Thanks for the video and screenshots, but this issue was already raised very recently in #5699.

**Comment by afontenot** [comment]
Sorry, my search didn't pull it up for some reason.
