### ISSUE TITLE
Automated Windows builds have broken Lensfun integration

### ISSUE THREAD

**Issue by MJacal** [Beep6581/RawTherapee#5729]
Builds, provided by [aferrero2707](https://github.com/Beep6581/RawTherapee/releases/tag/nightly)

RawTherapee_dev_5.8-394-g22eee9787_20200414
RawTherapee_dev_5.8-395-gd165a08e3_20200420
RawTherapee_dev_5.8-397-g276ae214f_20200423

RT doesn't "see" the Lensfun data in
RawTherapee\share\lensfun\version_1

Moving them one level up fixes the main problem.
But the data are also outdated. Timestamp 1447322002

**Comment by gaaned92** [comment]
When describing a bug, don't forget to provide all information. What is your system?

For the first issue, here should be an other way to cure the problem:
- find your options file and edit it
- at the end of file, you will find a lensfun section
- modify the relative file adding  ` /version-1` 
- save  and start RT

Should be definitive until @aferrero2707 moves DB one levelup.

For the second problem, depends on system.

**Comment by aferrero2707** [comment]
@gaaned92 @MJacal in fact, there was a problem in the update of the lensfun DB. From a recent build log:
```
/usr/bin/env: â€˜python3â€™: No such file or directory
cp: cannot stat '/var/lib/lensfun-updates/version_1/*': No such file or directory
```

This is now fixed for all branches. Could you please check?
Thanks!

**Comment by MJacal** [comment]
Fixed, functional and updated, thank you! I have checked `dev` and `newlocallab`, installers and zipped "portable" packages.

I believe i can close this now, be well!
