### ISSUE TITLE
Windows: gdbus.exe required to get -R option working

### ISSUE THREAD

**Issue by gaaned92** [Beep6581/RawTherapee#5738]
see https://discuss.pixls.us/t/how-do-i-switch-from-edit-window-to-browser-window/1723/33 for reference.

The -R option never worked satifactorily on windows. As I don't use this feature, I never worried until the thread above.

Can a dev explain what is the use of this exe and where it is called in RT and validate this addition?

@aferrero2707 when validated, can you add gdbus.exe to your windows builds?
Are there other builders providing official windows stable and nightly build?
I will update rawpedia/windows accordingly.

What about Linux and Mac?

**Comment by Lawrence37** [comment]
I saw a recent comment on Pixls about this topic. Since gdbus is used for inter-process communication, I think RawTherapee uses it to check for another running instance and instruct that instance to open the image. The download-and-run package includes gdbus.exe, but the installer does not. The Inno setup configuration does not include it in the installer.

**Comment by gaaned92** [comment]
First you need to copy gdbus.exe in the installation directory identified by {#MyBuildBasePath} 

Then I  think that adding this line
`Source: "{#MyBuildBasePath}\gdbus.exe"; DestDir: "{app}"; Flags: skipifsourcedoesntexist ignoreversion`
in  the  [files] section of `tools\win\InnoSetup\WindowsInnoSetup.iss.in`
will include gdbus.exe in the installer.

**Comment by Lawrence37** [comment]
Is the `skipifsourcedoesntexist` important? If gdbus.exe is necessary to make RawTherapee behave as documented, then ideally it should be mandatory. However, if there is a good reason why gdbus should not be included in certain packages, we can make it optional.

**Comment by gaaned92** [comment]
You are right. gdbus must be included in all packages.
