### ISSUE TITLE
Locallab bug: Scale on lightness slider is off

### ISSUE THREAD

**Issue by Waveluke** [Beep6581/RawTherapee#5752]
When I use the color and light tool in the local adjustments module, the rate of darkening from negative lightness settings tends to be not that significant, and then when I set it from -99 to -100, the effect jumps drastically, to an extreme and unuseable amount.  It would be much better served by a greater scale than what I observed with a resolution of the discontinuity in response, in terms of usefulness in making tonal adjustments.

Here is an approximate graph that illustrates the observed behavior, with reference ideal as the second graph, with arbitrary brightening units in the y axis:

![bad_behavor](https://user-images.githubusercontent.com/44814594/81880925-98600b00-9543-11ea-88c1-fa8cdb34a388.png)
![ideal_behavor](https://user-images.githubusercontent.com/44814594/81880923-97c77480-9543-11ea-8ca4-76e933ddc166.png)

Video demonstration: https://drive.google.com/open?id=1YgSml2zGV0wyJ2X1W5XTnwjHsMx155-e

System version: Windows 10 Education
CPU AMD Ryzen 5 1500X Quad-Core Processor 3.50 GHz
16 GB RAM

Rawtherapee Version: 5.8-1953-g24bad487a
Branch: newlocallab
Commit: 24bad487a
Commit date: 2020-05-13
Compiler: gcc\ 9.3.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.24.2
Lensfun: V0.3.2.0
Build type: Release
Build flags: -mwin32\ -m64\ -mthreads\ -msse2\ -std=c++11\ -mtune=generic\ -Werror=unused-label\ -Werror=delete-incomplete\ -fno-math-errno\ -Wall\ -Wuninitialized\ -Wcast-qual\ -Wno-deprecated-declarations\ -Wno-unused-result\ -Wunused-macros\ -fopenmp\ -Werror=unknown-pragmas\ -Wno-aggressive-loop-optimizations\ -DNDEBUG\ -O3\ -ftree-vectorize
Link flags: -m64\ -mthreads\ -static-libgcc\ -mtune=generic\ -s\ -O3
OpenMP support: ON
MMAP support: ON
Build OS: Linux 4.4.0-101-generic x86_64
Build date: Wed, 13 May 2020 20:50:07 +0000 UTC
Build epoch: 1589403007
Build UUID: e05ebbc4-037d-4d57-ad20-ebf7264ab7b0

**Comment by Desmis** [comment]
@Waveluke 
Effectively this bug is due to have a special behavior in "inverse"...make the external part black.
I have suppress this behavior in direct.

Jacques

**Comment by Waveluke** [comment]
@Desmis
"I have suppress this behavior in direct."

Based on the wording it is a little unclear. Did you fix the issue?

**Comment by Desmis** [comment]
@Waveluke 
**Yes it's fixed**
With the comment I said above...only in "direct" mode
When you work in "inverse", 2 yeras ago, peoples ask me to add this feature

jacques
