### ISSUE TITLE
Quickly inspect file in file browser i.e. quickly enlarge single thumbnail

### ISSUE THREAD

**Issue by oisanjaya** [Beep6581/RawTherapee#5762]
I'm aware of inspect tab that display file (or it's embedded jpeg) at 100% at mouse hover but are there any way to quickly display this image in whole and back to regular browser grid view? Like pressing space in lightroom while browsing files.
sometimes I need to inspect image as whole and to open the image into editor took too much processing (demosaicing and all)

**Comment by Thanatomanic** [comment]
This is implemented https://github.com/Beep6581/RawTherapee/pull/5593
