### ISSUE TITLE
RawTherapee 5.8 for Mac will not run from an /Applications subfolder

### ISSUE THREAD

**Issue by fl33bag** [Beep6581/RawTherapee#5763]
- RawTherapee.app (v. 5.8–see below) for Mac won't launch from */Applications/Photography/RAW Therapee* (note space in last folder's name). Nothing whatsoever happens when attempting to open it by double-clicking its icon in the Finder.
- Similarly it won't launch from */Applications/Photography/RawTherapee* (no spaces in path name).
- It **does**, however, open when launched from */Applications*.

I expect it to run from any location.
```Version: 5.8
Branch: 5.8
Commit: 9a9e0acbf
Commit date: 2020-02-04
Compiler: clang 11.0.0.11000033
Processor: generic x86
System: Apple
Bit depth: 64 bits
Gtkmm: V3.24.2
Lensfun: V0.3.95.0
Build type: release
Build flags: -Wno-deprecated-register -Wno-unused-command-line-argument -std=c++11 -std=c++11 -mtune=generic -Werror=unused-label -Werror=delete-incomplete -mmacosx-version-min=10.9 -flto -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Xpreprocessor -fopenmp /opt/local/lib/libomp.dylib -I/opt/local/include -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags:  -mtune=generic -headerpad_max_install_names -flto
OpenMP support: ON
MMAP support: ON

**Comment by Benitoite** [comment]
Due to hardened runtime/sandboxing the app must be installed in `/Applications`
To install the RawTherapee application, open the .dmg and drag the RawTherapee app onto the `/Applications` folder.
