### ISSUE TITLE
[feature request]you guys just don't known what a photographyer really need

### ISSUE THREAD

**Issue by chenjie199234** [Beep6581/RawTherapee#5766]
1.image stack:
with this feature,we can
1.1:mock long time exposure
1.2:remove people to get a clean image
1.3:reduce noise
1.4:depth of field merge
...

2.panorama:
with this feature,we can
take a large scene

3.timelapse:
smooth exposure,color,white balance and deflicker
with this feature,we can
make a timelapse

**Comment by Thanatomanic** [comment]
Your title is extremely impolite and not at all how a feature request works.
RawTherapee is a raw processor, not a general purpose image editing software.
