### ISSUE TITLE
lensfun not working properly in dev-appimage

### ISSUE THREAD

**Issue by hholtm** [Beep6581/RawTherapee#5775]
In latest dev appimage (RawTherapee_dev_5.8-441-gf0720ff_20200521.AppImage) lensfun doesn't work/is not included. OS is Linux Mint 19.3. On starting RT it's adding an entry in the options file under [Lensfun]: "DBDirectory=share/lensfun/version_1". This location doesn't exist in my data system. AFAIK lensfun should be included in appimage. So the options entry seems not to make sense or should be changed perhaps. 
Observed problems: in lensfun camera Pentax K-70 (my cam) and a recently integrated lens (HD Pentax DA 55-300mm PLM ...) are missing, while other lenses can be found in manual mode.
Same problem with last locallab2 appimage.
Any help is very much appreciated.
Heinrich
ping @aferrero2707

**Comment by hholtm** [comment]
solved

**Comment by Beep6581** [comment]
@hholtm explain how you solved it, for posterity.

**Comment by hholtm** [comment]
@Beep6581 It has been solved by @aferrero2707 / CarmeloDrRaw, see https://discuss.pixls.us/t/profiled-lens-correction-is-missing-my-camera-lens/10121
