### ISSUE TITLE
Raw photos have got magenta overlay with RT compiled by GCC 10.1

### ISSUE THREAD

**Issue by otula71** [Beep6581/RawTherapee#5777]
**RT version:** version independent problem (git versions as well as last stable version).
**GCC version:** 10.1 (there is no problem with GCC 9)
**Linux version:** updated Arch Linux (64bit).
**Exact steps to reproduce the problem:** build the RT using **GCC 10.1**
**Affected file:** any raw file from any camera (JPEGs or TIFFs are OK)
[Affected output](https://www.abclinuxu.cz/data/prilohy/5/0/243805-_mg_0174rt-2733304561731061825.jpg)
The [same file](https://www.abclinuxu.cz/data/prilohy/5/0/243805-_mg_0174rt2-862985178136401097.jpg) from a RT compiled using GCC 9.

**Maybe the problem is here:**
`[ 11%] Building CXX object rtengine/CMakeFiles/rtengine.dir/dcraw.cc.o
In file included from /usr/include/string.h:495,
                 from /usr/include/glib-2.0/glib/gtestutils.h:30,
                 from /usr/include/glib-2.0/glib.h:85,
                 from /home/ota/abs/rawtherapee/rawtherapee/trunk/src/rawtherapee-5.8/rtengine/dcraw.cc:12:
In function ‘void* memcpy(void*, const void*, size_t)’,
    inlined from ‘int fread(void*, int, int, IMFILE*)’ at /home/ota/abs/rawtherapee/rawtherapee/trunk/src/rawtherapee-5.8/rtengine/myfile.h:130:16,
    inlined from ‘void DCraw::parse_makernote(int, int)’ at /home/ota/abs/rawtherapee/rawtherapee/trunk/src/rawtherapee-5.8/rtengine/dcraw.cc:5631:13:
/usr/include/bits/string_fortified.h:34:33: warning: ‘void* __builtin___memcpy_chk(void*, const void*, long unsigned int, long unsigned int)’ specified size between 18446744071562067968 and 18446744073709551615 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]
   34 |   return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
      |          ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`

**Comment by Floessie** [comment]
Duplicates #5749.
