### ISSUE TITLE
Auto ITC WB is affected by CA correction setting

### ISSUE THREAD

**Issue by rom9** [Beep6581/RawTherapee#5785]
Using Auto-ITC white balance method on [this example raw file](https://discuss.pixls.us/t/white-aronskelk-arum/18504), yields slightly different temperature and tint values depending on whether the CA auto-correction feature is enabled or disabled.
Steps to reproduce:
1. open the raw file from the link above
1. select the "Neutral" profile
1. in the "White Balance" tool, select the "Auto ITC" from the Method dropdown. Computed wb values should be: `Temp: 5752  Tint: 0.980`.
1. now, in the "Raw" panel -> "Chromatic Aberration Correction" tool, enable the "Auto-correction" flag.
1. go back to the "White Balance" tool; wb values have changed to: `Temp: 5702,  Tint: 1.020`

This doesn't seem to happen when using "Auto RGB grey" WB method.

Similarly, Auto ITC white balance also seems to be affected by the "Preprocess WB" parameter. See also: https://github.com/Beep6581/RawTherapee/pull/5662#issuecomment-637657621

**Comment by Thanatomanic** [comment]
If CA correction is always applied before white balance calculations, the only strange thing is that you don't see a difference with the RGB grey method, right?

**Comment by rom9** [comment]
Well, if i set a fixed white balance and i place a lockable color picker in the picture, enabling or disabling the Auto CA Correction flag does not produce any color change (same color picker values), so this would lead me to believe that the CA Correction itself does not change the overall color in this image.

**Comment by heckflosse** [comment]
As Raw CA-Correction changes raw red and blue (but not green) values, it is very likely that it has an influence on everything applied after it....

**Comment by rom9** [comment]
Yes, in fact i was wrong: i've processed the image with fixed WB, both with and without Auto CA correction, and computed the difference in GIMP:
![image](https://user-images.githubusercontent.com/4711834/83569655-1bfa8f80-a525-11ea-89c3-daf9b7b99392.png)
There is a very small difference (notice the levels notches), so maybe the ITC WB method somehow "amplifies" this difference, while the Auto RGB grey method tolerates it more easily...

**Comment by Desmis** [comment]
It's obvious that with Itc wb, there is differences, when color in process "before" changes.

The algorithm compares color (those of image, and 200 spectral colors) , while "autowb" works with grey :)

jacques

**Comment by rom9** [comment]
Ok, so i guess this actually is expected behavior...
If you all agree, i'm going to close this issue (and sorry for the false alarm :-D)

**Comment by Thanatomanic** [comment]
~~I still have a question. If you use Camera WB (5899, 1.018), then I see absolutely no visual difference on the image whether I turn on CA Auto-correction, or change the preprocess WB mode, or both at the same time.
So, if these settings don't matter with a _fixed_ WB, why do they matter with the _automatic_ WB?~~

Edit: okay, I should've read @rom9 's post better lol. Disregard my question. If there are differences, apparently also very small ones, can have a big impact on the automatic wb.
