### ISSUE TITLE
MacOS: Command-H (Hide Application), Command-Option-H (Hide all others) do not work

### ISSUE THREAD

**Issue by dconrad5** [Beep6581/RawTherapee#5790]
I'm on macOS Catalina, Rawtherapee version 5.8. I believe this could be considered related to #3510 "Some keyboard shortcuts not working in macOS", which I haven't tested extensively but at least some of the issues mentioned there are still present.

This is a pretty simple bug, Command-H, which is supposed to hide the application, does nothing. Same with Command-Option-H, which is supposed to hide all other applications.

**Comment by Benitoite** [comment]
Duplicate of #3510

**Comment by dconrad5** [comment]
I do think it's worth noting that Command-H and Command-Option-H do not seem to be mentioned in #3510 though. And that Command-Q works.

**Comment by Beep6581** [comment]
Please add missing/relevant shortcuts to #3510
