### ISSUE TITLE
Processing Profiles dropdown box is annoying to use

### ISSUE THREAD

**Issue by dconrad5** [Beep6581/RawTherapee#5792]
When using a trackpad on a dropdown box, I usually click once to open it, and then click again to select what I want rather than click-hold-release to select. This behavior will often result in annoying mis-selection of a profile on the Processing Profiles dropdown box.

If I'm on the (Last Saved) selection and click on approximately the top 1/3 of the dropdown, it will immediately load (Neutral). Similarly, if I have (Neutral) or a profile from My Profiles loaded and click on the bottom approximately one-third of the box, it will immediately go to the next selection down.

Alternatively, sometimes when clicking the cursor moves a little, so if I click on the center 1/3 of the dropdown and accidentally move the cursor a little before letting it up, it will select something I don't want. I hope you can see how annoying this can be!

I think there's a couple things at play here - not having a minimum click-hold-release time for selecting something, and the height of the selection box being bigger than the height of the items in the dropdown once opened up.

I hope that all makes sense! Let me know if more details or screenshots are needed. EDIT: I'm on MacOS Catalina, RT 5.8.

**Comment by Pandagrapher** [comment]
@dconrad5 
> When using a trackpad on a dropdown box, I usually click once to open it, and then click again to select what I want rather than click-hold-release to select.

That's how ComboBox works in GTK: click to show elements list, click again to select one.

I have tested on my side using trackpad: I have never reproduced this behavior (with RT 5.8 and RT dev on Catalina). Is there top/bottom arrows when showing the elements list? Perso, I prefer setting the mouse cursor on one of them to fully opening the elements list before selecting an element: this avoids some list move when trying to select an element (maybe the source of your problem?).

**Comment by dconrad5** [comment]
I'll try to get a video of the issue tonight, as I don't feel screenshots will do it justice. It's not that the list misbehaves once it's already open, but that it erroneously selects a profile immediately upon opening it, which causes a need to wait for the new (erroneous) profile to load and then open the list again to select the actual desired profile.

**Comment by dconrad5** [comment]
Ok, so admittedly it doesn't happen every time and it's more like the outer 1/6 of the button or something, but this video should give a good idea of what it looks like. It seems to be more likely in the "downward" direction than the "upwards" one.

https://youtu.be/O8AnRx5P5Nk

EDIT: One thing is that it might be due to extremely small movements between click and release? It seems to happen more when the click is "sloppier".

**Comment by Pandagrapher** [comment]
I reproduce the problem only if the click is long. It seems the difference (not huge) between the click-select-click and the click-drag-release behavior depends of the click length.

It never happens tho if you use the touch-for-click behavior of your trackpad.

Unfortunately, the GTK widget behavior cannot be changed easily...

**Comment by dconrad5** [comment]
What if the button were made smaller or the list items were made bigger, so the cursor would always be on the currently selected item when the list opens? You can see that at the edges of the button, the cursor is on an adjacent item when the list opens. Would this type of solution be possible?

Or possibly is the click length required for click-drag-release configurable in GTK?

It seems to happen when there is a tiny, almost imperceptible movement of the mouse in between click and release. Like moving your hand sideways while clicking.

**Comment by dconrad5** [comment]
At the risk of spamming this with unnecessary information, I just want to add that I just realized it does happen sometimes where it selects the current profile again. I don't think this is _as_ big of a deal because it doesn't cause it to reload the profile or change any settings, but it does mean you need to open the combo box again and ultimately gives a slightly "janky" feel (imo).

Is the widget GtkComboBox? What are the relevant files where it's added/its behavior is defined? I might look at it myself just out of curiosity. Maybe someone has had a similar issue before on a different project and found a solution/workaround.

Found this is potentially a fundamental bug in GTK: https://gitlab.gnome.org/GNOME/gtk/-/issues/1954

**Comment by Pandagrapher** [comment]
@dconrad5 
It's Gtk ComboBoxText widget:
https://developer.gnome.org/gtkmm/stable/classGtk_1_1ComboBoxText.html
Which is used in `rtgui/profilepanel.h/.cc`.

**Comment by Beep6581** [comment]
@dconrad5 @Pandagrapher can you reproduce this in other GTK3-using software? If so, we should close this and report upstream.

**Comment by dconrad5** [comment]
Per the above referenced GTK issue 1954, I followed it to the original submitter there's inkscape bug report. I downloaded inkscape and sure enough, it happens there too:

https://www.youtube.com/watch?v=25WObLr1vWg&feature=youtu.be

I also verified the GTK issue 1954 occurs in the gtk3-demo program as well:

https://www.youtube.com/watch?v=NXltDQMZoqU&feature=youtu.be

**Comment by Pandagrapher** [comment]
Problem already reported as GTK known issue:
https://gitlab.gnome.org/GNOME/gtk/-/issues/258

**Comment by dconrad5** [comment]
If I'm reading this right, this bug has been open and known for... 14 years? And nobody has bothered to fix it? Welp...
