### ISSUE TITLE
R++,G----,B+ wrong color in output files, not reproducible in appimage

### ISSUE THREAD

**Issue by vivo75** [Beep6581/RawTherapee#5817]
Hi,
   I've a problem with a recent build of rawtherapee in gentoo - something recent, was not present when 5.8 has been released.

There is a strong violet colorization of the image both as seen in monitor and as produced by rawtherapee

facts:
- We are comparing rawtherapee built with my ebuild in gentoo _and_ appimage 5.8 both are built from commit 9a9e0ac
- linked libraries are similar, gentoo has libpng version 16, appimage  has 15, scanelf sees more libraries in appimage version (cairo & co)
- the problem is present when looking at the monitor _and_ when outputting jpeg or tiff images
- while it looks like a color profile issue extracting the profile embedded within the images show their checksum is identical.
- same for all other exifdata, only timestamps change everithing else is equal
- both rawtherapee and rawtherapee-cli are affected
- all RT config files in $HOME have been wiped out to avoid confusion
- the raw file come from a camera ILCE-7RM2  lens Sony FE 24-105mm F4 G OSS
- opening a random jpg in rawtherapee does NOT show the issue
- pixel difference: 
  gentoo/F1R03114.tif:   TOP,LEFT  97.1 ; 92,7 ; 98,0 [RGB]
  appimage/F1R03114.tif: TOP,LEFT  95.1 ; 96.3 ; 97.8 [RGB]

I can upload all the files you want everywhere you like, 600MB with both tiff

**Comment by ff2000** [comment]
Known issue. https://github.com/Beep6581/RawTherapee/issues/5749
There also are solutions: revert to gcc9 or disable -ftree-loop-vectorize (which IMO should be done automatically since https://github.com/Beep6581/RawTherapee/commit/49c4d0a27c3de089a8f50695cddc73532d622f95 )

**Comment by Thanatomanic** [comment]
Please update your local repository and checkout the `dev` branch. This should resolve your issue.
