### ISSUE TITLE
Replace dcraw with faster raw decoder (libraw?)

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#583]
Originally reported on Google Code with ID 594

```
This is an enhancement suggestion.

dcraw is not optimized for speed, which shows as rather slow loading times of RAW files
compared to the competition. When working with RawTherapee, I think the slow loading
times is disturbing so it would be valuable with an improvement.

libraw is based on dcraw and does (so far) not provide much speed improvement.

It seems like Klaus Post's RawSpeed library could be a good alternative though, currently
used in RawStudio and Darktable.

A quick test made on my workstation showed that a .CR2 (canon RAW) that took 1800 ms
to unpack (only unpacking measured, no post-processing) with dcraw took 580 ms with
RawSpeed. A .NEF (Nikon RAW) file that took 1370 ms to unpack with dcraw took 680 ms
with RawSpeed. That is 2 - 3 times faster, and the difference between 1,8 and 0,6 seconds
load time is certainly noticed by the user.

The drawback with RawSpeed is that it does not support all formats, so you need to
have a solution where you combine that and dcraw/libraw, which Darktable currently
does.
```

Reported by `torger@ludd.ltu.se` on 2011-03-23 15:04:12

**Comment by Beep6581** [comment]
If we were to use rawspeed we would need to include it in RT's sources because it can only be used bundled, it cannot be built as a shared lib. The master branch of rawspeed is currently very old, the development branch is active and doubled the commit count since the original rawspeed author Klaus transferred rawspeed to @LebedevRI. We could include the files from the `develop` branch, or to be a little safer we could use the rawspeed version used by darktable since it would have been already tested.

https://sonarcloud.io/dashboard?id=rawspeed%3Adevelop
https://github.com/darktable-org/darktable/tree/master/src/external

**Comment by LebedevRI** [comment]
> the original rawspeed author Klaus transferred rawspeed to @LebedevRI.

Just to clarify, not to me, to @darktable-org, i'm just acting as a maintainer

**Comment by agriggio** [comment]
any estimate on the required effort? @heckflosse Ingo, do you have any idea? what would be the user visible impact? (thinking of pixelshift and `camconst.json` in particular)

**Comment by heckflosse** [comment]
@agriggio Currently we can not replace dcraw by rawspeed for a lot of reasons:

1. rawspeed does not support multiframe raw files which are needed for pixelshift
2. rawspeed does not support compressed fuji files
3. switching from camconst.json to the rawspeed mechanism is not easy

But: We could try to use rawspeed additionally to dcraw for decoding files which currently are not supported by dcraw.

**Comment by agriggio** [comment]
@heckflosse thanks for confirming what was my understanding as well. I think having rawspeed as an optional component would be interesting indeed.

**Comment by LebedevRI** [comment]
> 2. rawspeed does not support compressed fuji files

Actually, perhaps someone can help me here.
I need some raw file which triggers this branch:
https://github.com/Beep6581/RawTherapee/blob/6e55f6bab5ac9289c4bacf2e6cded9b92c3a3d24/rtengine/fujicompressed.cc#L76-L80

I would post it on disscuss, but i suppose more people here know how to actually check it (e.g. put `derror();` in that branch, and see if any raw stops to load?)

**Comment by LebedevRI** [comment]
> 2. rawspeed does not support compressed fuji files

[Done.](https://github.com/darktable-org/darktable/commit/be764c89f16cb92ecdabf036eb64a2b07afa2aa3)

**Comment by heckflosse** [comment]
@LebedevRI I really like that you solved this issue in RawSpeed! But to avoid confusion, as your fix is not related to rt, I will close this issue now. 
That does not mean, I won't pick up this again. It's just to avoid confusion of rt users.

Ingo
