### ISSUE TITLE
Canon 90D Support White Frames and Illuminant Frames

### ISSUE THREAD

**Issue by blj86** [Beep6581/RawTherapee#5835]
I understand CR3 is still not fully supported yet however, I felt it beneficial to submit White and Illuminant frames for camera support in RT since it is a newer camera and I happen to own one as well as a color target.  Used google drive as filebin was not working.  Link is active files should be available approximately 10 mins or so from the posting of issue upload is still in progress.  **Consider all these files CC0 please read the text file in the archive for details why I am mentioning it here as well as in the text file.**

https://drive.google.com/drive/folders/1Y7XbRTt1QtPQR6Zby_aUsy4i3awixr9x?usp=sharing

**Comment by Thanatomanic** [comment]
@blj86 Thank you for this set! It seems nice and complete :-)
Could you try out how well this profile works on several different photo's taken with your 90D? (remove the .txt file extension)

[RT_Test_Canon EOS 90D.dcp.txt](https://github.com/Beep6581/RawTherapee/files/4882330/RT_Test_Canon.EOS.90D.dcp.txt)

**Comment by Thanatomanic** [comment]
The above profile was made using the X-Rite software. 

Can you also test this profile made with DCamProf? [RT_Test_Canon EOS 90D-DCamProf.dcp.txt](https://github.com/Beep6581/RawTherapee/files/4882415/RT_Test_Canon.EOS.90D-DCamProf.dcp.txt)

@Beep6581 Has been the expert on making these profiles, but I think I did all right, following the instructions here http://rawpedia.rawtherapee.com/How_to_create_DCP_color_profiles

Edit: I have assumed you have bought your ColorChecker after November 2014, and therefore used `cc24_ref-new.cie` as per instructions of the DCamProf manual.

**Comment by blj86** [comment]
@Thanatomanic Yes the color checker is the new passport 2 model and purchased just this year.
Manually loading these DCP profiles they seem to work really well.

Some observations.  Loaded with Neutral profile.  Added the DCP under custom in version 5.8 of RT.  Did not change any options so it was at interpolated and only base table selected.  Then used auto matched curve.

The DCamProf dcp is way better then the XRite profile.  The XRite profile seems to be very saturated.  This could be due to the fact that DCampProf makes more detailed profiles.  If I reset the auto matched tone curve and enable it in the DCP I get the same or similar results and also using the tone curve option + look up table option nails the colors even better.

So I think everything is Ok on the Illuminants.  The DCamProf profile is far better for sure.

**Comment by Thanatomanic** [comment]
Then I think we can happily include the DCamProf profile in the next release of RawTherapee! 

Let's keep this issue open until the white-levels problem is solved.

**Comment by Beep6581** [comment]
For some years now I've been creating RawTherapee's DCP profiles using LumaRiver Profile Designer. There must be accompanying raw files (StdA + D50/D65) uploaded to our server so that a DCP can be checked and re-generated should the need arise (different approach, bug in the DCP software, etc). The profiles use the "neutral" tone reproduction operator of the "skin & sky" variant:

> Neutral — this is the signature tone operator of Lumariver Profile Designer and the DCamProf technology it’s based upon. By advanced perceptual modeling it keeps color appearance neutral/unchanged when contrast is changed. (...) The neutral tone reproduction operator is the one we strongly recommended, and is a key feature that sets Lumariver Profile Designer apart from other profile makers. The fundamental idea of it is to keep colors perceptually the same after the contrast has been applied. No hue shifts, no saturation increase or decrease. It’s not possible to make such an operator 100% perfect as it’s somewhat subject dependent, and can also vary a bit over the image surface, but we dare to claim that it is as close as it can get.

> TRO Variant: Skin&Sky — highlight rolloff optimized for skintones and sky, which means earlier desaturation in the skintone range (to make skintone highlights look “lighter” and “fresher”), and later desaturation in the sky blue range (to keep natural saturation in skies).

Sometimes manual tweaks to red and blue are necessary should hue shifts occur in highly saturated areas.

As I'm on limited bandwidth and don't want to download a gigabyte unnecessarily, please upload the DCP shots (StdA + D50/D65) separately and I'll generate a DCP using LRPD.

**Comment by blj86** [comment]
@Beep6581 Not a problem.

https://drive.google.com/drive/folders/1Y7XbRTt1QtPQR6Zby_aUsy4i3awixr9x?usp=sharing

Same link as before reposting it for ease.  There are 3 shots in each folder due to bracketing.  The base file with no number at the end is the Base exposure the -1 is -1 ev and the -2 is +1 ev.  Just for reference. I believe the daylight will need to use the -1 EV that was a hard shot to properly expose... and the STDA the base shot should be fine I think. Those were taken with a Clear 2700K tungsten bulb (best I could find to be honest these are hard to find at close temperature most I have seen are only 2200k).  Included all 3 shots just to make sure you have the options.

**Comment by Thanatomanic** [comment]
Closing for now, the available profile should be of sufficient quality.
