### ISSUE TITLE
Fuji X-T3 support - White Frames

### ISSUE THREAD

**Issue by dancat** [Beep6581/RawTherapee#5839]
I took some sets of white frames for Fuji X-T3 as specified in http://rawpedia.rawtherapee.com/Adding_Support_for_New_Raw_Formats#White_Levels 

They can be found here: 
https://filebin.net/voo04y6andiobdk3

Let me know if more are needed.

All the best,
Daniel

**Comment by Thanatomanic** [comment]
Hi @dancat I analyzed the files and I think I have some decent estimates for white levels. Can you test these on some regular (overexposed) photos, if you modify your `camconst.json` file with the changes below? I have split the entry for the X-T3 from the others, because I cannot be sure they behave the same.

```
    { // Quality C, only raw crop
        "make_model": [ "FUJIFILM X-T30", "FUJIFILM X-PRO3", "FUJIFILM X100V", "FUJIFILM X-T4" ],
        "dcraw_matrix": [ 13426,-6334,-1177,-4244,12136,2371,-580,1303,5980 ], // DNG_v11, standard_v2 d65
        "raw_crop": [ 0, 5, 6252, 4176]
    },
    
    { // Quality A, samples provided by Daniel Catalina (#5839)
        "make_model": "FUJIFILM X-T3",
        "dcraw_matrix": [ 13426,-6334,-1177,-4244,12136,2371,-580,1303,5980 ], // DNG_v11, standard_v2 d65
        "raw_crop": [ 0, 5, 6252, 4176],
        "white": [ 16170, 16275, 16170 ] // non-uniform distribution on sensor above these values
        // negligible aperture scaling effect
    },
```

Edit: fixed a typo with a comma

**Comment by dancat** [comment]
Sure, I will give it a go the next days and provide feedback.

**Comment by dancat** [comment]
out of curiosity, does the X-T3 sensor shows the same non-uniformity as the one from X-T2 (in https://github.com/Beep6581/RawTherapee/issues/5824#issuecomment-653139151)?

**Comment by Thanatomanic** [comment]
Yes, there is a similar pattern, though slightly different and with a more pronounced center.
![image](https://user-images.githubusercontent.com/6567747/87192233-5d394880-c2f6-11ea-9508-620e8250f17e.png)

I also found very curious patterns actually, where the 6x6 blocks of the X-Trans matrix had very similar intensities all throughout the image:

Close-up
![image](https://user-images.githubusercontent.com/6567747/87192039-eac86880-c2f5-11ea-889c-650a7f35748a.png)

Larger area
![image](https://user-images.githubusercontent.com/6567747/87192074-f3b93a00-c2f5-11ea-8d7a-057a1acbdbaa.png)

Be aware that the absolute difference between a white and black pixel here is only 120 units (a signal of 16263 vs. 16383). Still, interesting to see.

**Comment by dancat** [comment]
I tested it with only a few files, as the camera is new for me, and all seems fine.

**Comment by dancat** [comment]
For a more 'in depth' test, maybe we can ask nice people from the pixls.us forum to help? 
I will have some more images to play with in about a week, as I will go a little bit in vacation.

**Comment by pi99y** [comment]
Hi, I see you're grouping this also with the X-Pro3 model. I shot a series on that model for reference / comparison. Thanks! https://github.com/Beep6581/RawTherapee/issues/5860

**Comment by dancat** [comment]
@Thanatomanic  I am now back from vacation and tested with more of photos and everything is fine.

**Comment by pi99y** [comment]
> I have split the entry for the X-T3 from the others, because I cannot be sure they behave the same.

@Thanatomanic would you be so kind to check my post https://github.com/Beep6581/RawTherapee/issues/5860 where I provided the white frames for X-Pro3, one of the cameras that is/was grouped with the X-T3, please? Thank you!

PS: I'm also ready to do any testing regarding this if you want me to...
