### ISSUE TITLE
Dark level (and white?) are off for NIKON P1000

### ISSUE THREAD

**Issue by dimonoid** [Beep6581/RawTherapee#5842]
It looks like the black point is off too. There are some pixels with values 190, even a little bit lower. Because of that my dark frames didn't work as intended by introducing, not removing noise. 
Also white point looks really too high. I measured it 3903 at iso 100 to 3905 at iso 6400. I don't know where the previous number 4087 is coming from, it looks impossible.
Here is what I got:
```
{ // Quality B
        "make_model": "NIKON COOLPIX P1000",
        "dcraw_matrix": [ 14294, -6116, -1333, -1628, 10219, 1637, -14, 1158, 5022 ], // ColorMatrix2 from Adobe DNG Converter 11.4
        "ranges": { "black": 190, "white": 3903 }//3903 instead of 4087, 190 instead of 200
    },
```

_Originally posted by @dimonoid in https://github.com/Beep6581/RawTherapee/issues/5734#issuecomment-657152140_

**Comment by Thanatomanic** [comment]
Thanks for reporting. I like to check things myself. So, to solve this once and for all, please provide a full set of fully overexposed shots for all possible ISO values (see http://rawpedia.rawtherapee.com/Adding_Support_for_New_Raw_Formats) and possibly a set of overexposed shots at different apertures as well.
Make sure you overexpose fully, e.g. shooting at a clear bright sky with f/5.6 and 1/2s shutter should usually do the trick.

As for the black values, take shots with the lens cap on (and possibly in a dark room if there could be light leakage). Preferably also shot at a few different ISO levels.

**Comment by dimonoid** [comment]
Is there a reason to shoot at f/5.6 ? I used f/2.8.

**Comment by Thanatomanic** [comment]
If your camera does scaling of the raw values with aperture setting, the f/5.6 pretty much guarantees that you're not running into that effect. Like explained on RawPedia, that is the preferred setting for these shots.

**Comment by dimonoid** [comment]
Please note, level of glowing noise(bias?) can be divided into 3 groups, for photos with 
```
>= 2s; 
 2s<  to <=1/500s;
more then 1/500s; . 
```

The largest for >= 2s.

**Comment by dimonoid** [comment]
LENR is available only at ISO 800 or lower while exposure 2 seconds or longer. It looks like white level doesn't depend on aperture as I expected. 
Should I take black photos with different apertures also?

**Comment by Thanatomanic** [comment]
> LENR is available only at ISO 800 or lower while exposure 2 seconds or longer

Good, then please provide shots with LENR ON for these ISO values and 2 s exposure

> Should I take black photos with different apertures also?

That won't be necessary I believe

**Comment by dimonoid** [comment]
Here is the archive. There is some variability (about 1 in 10 photos with higher noise) when shooting several photos with the same settings in the row. I don't know why this happens, so please disregard any obvious outliers.

https://drive.google.com/file/d/1xcc2c4gBnlviMZGU2yOQ3tsVGUSIY8ic/view?usp=sharing

**Comment by Thanatomanic** [comment]
@dimonoid Thank you, I'm downloading and will take a look!

**Comment by dimonoid** [comment]
@Thanatomanic please let me know if you need any other photos to create "quality A" settings

**Comment by Thanatomanic** [comment]
While lot of your shots are not overexposed on the entire sensor I think I managed to get some more realistic values. This is my statistical analysis of all usable images, including the LENR ones. The orange bars are the new white level estimates. Note that this is a small zoomed-in section of the histogram near the clipping point. The variation between ISO values is negligible.

![image](https://user-images.githubusercontent.com/6567747/87241060-85709680-c41f-11ea-8281-6fdf04d5752c.png)

The current black level of 200 is correct, as you can see in this plot of the histogram of your provided images. The sigmoid behavior gets wider with higher ISO, which is to be expected. The inflection point is the correct setting for the black point as far as I know.
![image](https://user-images.githubusercontent.com/6567747/87241329-61fb1b00-c422-11ea-9215-4d707738d47f.png)

**Comment by Thanatomanic** [comment]
@dimonoid Please test the new `camconst.json` values. I hope your highlights behave better now.

> Because of that my dark frames didn't work as intended by introducing, not removing noise.

I believe that dark frame subtraction helps to reduce noise due to the shown sigmoid curve. It should not introduce more noise. If so, please make a separate issue for this and provide a RAW + corresponding dark frame.

**Comment by dimonoid** [comment]
Thanks, white level works! It looks like the dark level is approximately 198.3(closer to 198) . If you subtract dark frame from another dark frame, the mean value of noise should stay the same. If you use 200, the amount of noise is increasing when applying dark frame subtraction. If use anything below 198, mean is it is decreasing. Look at the histogram in RT while enabling/disabling dark frame subtraction.

**Comment by Thanatomanic** [comment]
I made plots of the inflection point (which should give the most versatile estimate for the black level) and make three vertical lines: 198, 199 and 200. Indeed, the 200 seems a slight overestimation of the black level, though the 198 seems to underestimate it. The horizontal line is at y = 0.5. Ideally all curves should intersect there, but the red channel in particular is a little low here.

Red channel: 
![image](https://user-images.githubusercontent.com/6567747/87417156-11c1bb80-c5d0-11ea-9624-126435c31578.png)

Green channel:
![image](https://user-images.githubusercontent.com/6567747/87417187-1be3ba00-c5d0-11ea-846c-1b95d6a5d402.png)

Blue channel:
![image](https://user-images.githubusercontent.com/6567747/87417219-23a35e80-c5d0-11ea-86bf-01e1ae34b4da.png)

**Comment by dimonoid** [comment]
@Thanatomanic , @pmjdebruijn 

Bump. Letting you know that on latest firmware 1.6 they fixed a bug with high ISOs, because of this white levels can be affected. High ISO photos were indeed captured at low ISOs because of a firmware bug, according to Nikon website, now it was fixed. 

Config may need to be edited.

https://downloadcenter.nikonimglib.com/en/download/fw/449.html
