### ISSUE TITLE
Minor cosmetic changes to histogram

### ISSUE THREAD

**Issue by Thanatomanic** [Beep6581/RawTherapee#5843]
I just pushed [this change](https://github.com/Beep6581/RawTherapee/commit/dced61b619793512c1aa63e75d5c2b86fd9ba812), although my intention was to create a branch and then make a PR. That failed... 🙄  (the branch was made, I committed from local, but there were no changes when I tried to make the PR?)

So, just to inform you and still ask if there are any objections and necessary reversal: I made a tiny change to the look of the histogram. I added a tiny padding around the curve. This makes it easier to see the clipped lines.
![image](https://user-images.githubusercontent.com/6567747/87239355-864cfc80-c40e-11ea-9df9-92f4d9a0b478.png)

**Comment by Thanatomanic** [comment]
I have now invalidated the positions of the RGB bar, but I actually think they were not okay anyhow (0 and 255 were not showing up). I'll make a fix.

**Comment by Thanatomanic** [comment]
Should be fixed with c364e206359b2f22ebd24adf2855a35a173ad9ec

**Comment by Lawrence37** [comment]
With your changes, is there an easy way to tell where the histogram stops and the padding begins?

**Comment by Thanatomanic** [comment]
I think so, because there are still two vertical gridlines at 0 and 255.
