### ISSUE TITLE
Bug in Gimp with images saved with RTv4 output profiles

### ISSUE THREAD

**Issue by sguyader** [Beep6581/RawTherapee#5853]
I get crashes when working with images exported from RT (5.8) or ART (1.4) with RTv4 output profiles, when doing some operations on layers.
To reproduce:
- save an image in RT/ART with RTv4 profile (I tried sRGB and Rec2020, same behaviour) ; it doesn't matter whether you export to TIFF or JPG, same behaviour
- open the image in Gimp (tried Gimp 2.10.18 and Gimp compiled form git, same behaviour)
- when prompted about the profile conversion, click on "keep" to keep the embedded color profile
- duplicate the base layer
- select the paint brush and paint over the second layer -> instantaneous crash

From the Gimp debug report I get nothing but:
```
> fatal error: Segmentation fault

Stack trace:

# Stack traces obtained from PID 724435 - Thread 724435 #

No threads.
```

If I choose to convert the color profile to Gimp built-in sRGB, no crash. If I export the image from RT/ART with an RTv2 profile, no crash.

**Comment by heckflosse** [comment]
So, GIMP crashes, not RT?

**Comment by Thanatomanic** [comment]
Have you reported this to the GIMP developers? I mean, it could be that our v4 profiles have some sort of error, but clearly it's GIMP that crashes and not RT (or some other applications that I use to check my exported files)  :wink:

**Comment by sguyader** [comment]
Right, it's only Gimp, not RT which crashes. Since the RTv4 profile was developed by the RT team I think, I thought I'd report the problem here first in case the bug is inherent to the profiles and not Gimp.

**Comment by Beep6581** [comment]
@sguyader please open an issue at GIMP's bug tracker:
https://gitlab.gnome.org/GNOME/gimp/-/issues

**Comment by sguyader** [comment]
I reported the issue to Gimp: https://gitlab.gnome.org/GNOME/gimp/-/issues/5432
