### ISSUE TITLE
Regression in Sony lens identification

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#5855]
There is a regression in Sony lens identification.

I bisected the bad commit to 24684e5cb which shows "Unknown (70-200mm f/4.0)" and also lensfun identification fails.

The previous commit 227c2fbba is good and shows "Sony FE 70-200mm f/4 G OSS".

Test image:
http://rawtherapee.com/shared/test_images/chicken.arw

**Comment by Beep6581** [comment]
Upstream issue opened:
https://github.com/exiftool/exiftool/issues/54

**Comment by Floflo81** [comment]
Nice to see this is being worked on.
I think it is a duplicate of issue #5670
Check this other issue for other examples

**Comment by Beep6581** [comment]
Hi @Floflo81 
Yes, it is a duplicate, thanks.
