### ISSUE TITLE
Fujifilm X-Pro3 - White Frames

### ISSUE THREAD

**Issue by pi99y** [Beep6581/RawTherapee#5860]
Hi, 
I shot a series of white frames as per http://rawpedia.rawtherapee.com/Adding_Support_for_New_Raw_Formats#White_Levels to add/improve the Fujifilm X-Pro3 white levels support.

Files are available here: https://filebin.net/rjuatk2vdl246ect/x-pro3whiteframes.7z?t=f39zpmcq (for a week)

Thank you!

**Comment by Thanatomanic** [comment]
I can confirm that these result in the exactly the same values as for the X-T3. Thank you for providing them, and I will update the white levels for the X-Pro3 when closing #5839.

**Comment by pi99y** [comment]
> I can confirm that these result in the exactly the same values as for the X-T3. Thank you for providing them, and I will update the white levels for the X-Pro3 when closing #5839.

Thank you!
