### ISSUE TITLE
Canon EOS 1DX Mark III CR3 Raw Support

### ISSUE THREAD

**Issue by noirsabb** [Beep6581/RawTherapee#5862]
Hi

As of dev, version: 5.8-2375-g6b749bcbf, CR3 files produced by a Canon EOS 1DX Mark III display as white or washed out, although the thumbnails look OK. I can work with the raw white points to get some detail, but the results cannot be used. I followed a hack in another thread setting bpp (?) in dcraw.cpp (?) to 14, and was able to get something to work with. I am aware CR3 decoding and metadata support is in progress.

I would like to request support for decoding CR3 files produced by Canon EOS 1DX Mark III cameras in RawTherapee. 

I have uploaded white frame and colour chart files from this camera to WeTransfer, download link is 

https://we.tl/t-MHgi6I8Nnq

Let me know if further information or files are required.

**Comment by Thanatomanic** [comment]
@noirsabb Sorry for a lack of action here. https://github.com/Beep6581/RawTherapee/commit/d36545b71a48cd8ae3a4eeccd318baedcf86b9e1 provides basic support for this camera after analysis of the white frames.

@Beep6581 There are still two color checker cards that can be processed into a DCP file. An Adobe color matrix is still lacking, so this would be a valuable addition. Please let me know when you have time and need the files, or confirm that I can make them instead.

**Comment by noirsabb** [comment]
Thanks. I have been getting by using the 1DX Mark II entry in comconst.json and some profiles with various black points set.

**Comment by Thanatomanic** [comment]
Hi @noirsabb, could you maybe check this DCP file? Please test it on a few of your sample photo's by loading it manually through the Color Management tool.
[Canon EOS-1D X Mark III.zip](https://github.com/Beep6581/RawTherapee/files/6697117/Canon.EOS-1D.X.Mark.III.zip)

I'm particularly interested in the color rendition of shots taken in artificial lighting.

**Comment by noirsabb** [comment]
Hi
Apologies for the late reply. I do not have any complaints processing images with the above mentioned camera using RT.
Let me know if you would like me to try the DCP file with some images.
I could try LED lighting as well as flash, as well as some poor bedroom lighting.


NS

    On Tuesday, 22 June 2021, 08:06:34 pm UTC, Thanatomanic ***@***.***> wrote:  
 
 


Hi @noirsabb, could you maybe check this DCP file? Please test it on a few of your sample photo's by loading it manually through the Color Management tool.
Canon EOS-1D X Mark III.zip

I'm particularly interested in the color rendition of shots taken in artificial lighting.

**Comment by noirsabb** [comment]
@Thanatomanic 

Thanks!

NS
