### ISSUE TITLE
RT crashing and can't debug

### ISSUE THREAD

**Issue by t-o-d-d** [Beep6581/RawTherapee#5876]
For the past few weeks (after fresh format reinstalling Windows) I’ve been getting bad RT crashes with the dev builds where the only thing I can do is sign out of Windows to get RT to close out. It locks in File Browser view most often when opening and trying to scroll an image folder. RT often stops painting thumbnails about half way down if large enough folder, and begins to lock up and stops responding. If I don’t try to load an image, sometimes RT will crash and I can tell it to close from the not responding prompt and it will. If I try to load an image though, it will always lock up and the only way I can close RT is to restart the PC or log out of the pc. The larger number of images in the folder the more likely the crash. Some builds the crashes have been more frequent, some less frequent, and with the most recent dev_5.8-2419-g25c5e62b7_20200806 it has been the worst, crashing no matter what, and thumbnails won’t even load.

I’ve been trying to run the debug since not long after the crashes started but could never get it to crash when running it. Today for the first time it crashed with the debug running but then GDB never stopped so I could turn on the logging. Eventually I just had to sign off to get it all to close out.

I have dev builds still installed going back to dev_5.8-2374-g746be1816_20200719 so I will be experimenting more, but thought it was time to throw a flair.

I’m on Windows 10 Pro 10.0.19041 Build 19041. Everything was fine with RT before my reinstall of Windows, but it was an older release of Win10.

Version: 5.8-2419-g25c5e62b7
Branch: dev
Commit: 25c5e62b7
Commit date: 2020-08-05
Compiler: gcc\ 10.1.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.24.2
Lensfun: V0.3.2.0
Build type: Release
Build flags: -mwin32\ -m64\ -mthreads\ -msse2\ -std=c++11\ -mtune=generic\ -Werror=unused-label\ -Werror=delete-incomplete\ -fno-math-errno\ -Wall\ -Wuninitialized\ -Wcast-qual\ -Wno-deprecated-declarations\ -Wno-unused-result\ -Wunused-macros\ -fopenmp\ -Werror=unknown-pragmas\ -Wno-aggressive-loop-optimizations\ -DNDEBUG\ -O3\ -ftree-vectorize
Link flags: -m64\ -mthreads\ -static-libgcc\ -mtune=generic\ -s\ -O3
OpenMP support: ON
MMAP support: ON
Build OS: Linux 4.4.0-101-generic x86_64
Build date: Thu, 06 Aug 2020 21:30:09 +0000 UTC
Build epoch: 1596749409
Build UUID: 54226276-fef0-4d05-86b0-2108761732aa

**Comment by Thanatomanic** [comment]
> I’m on Windows 10 Pro 10.0.19041 Build 19041. Everything was fine with RT before my reinstall of Windows, but it was an older release of Win10.

I am on the same version of Windows 10, and I haven't experienced any sudden increase of crashes (= zero), so I think we can rule that out as a cause quickly.

What do you consider a 'large folder'?

For thumbnails that won't even load: please try to clear your cache. Go to Windows Explorer, type in %LOCALAPPDATA%, look for any RawTherapee folder there, enter the folder and remove the cache folder entirely. This clears our any thumbnails that were already generated, so when restarting RT you might experience some delays as they are rebuilt for the folder you're in.

If the crashes still persist, it may be interesting to know a bit more about your system. Do you load the images from an SSD or HDD or over the network? How much RAM does your machine have?


Last thing I notice: 

> Version: 5.8-2419-g25c5e62b7
Branch: dev
Commit: 25c5e62
Commit date: 2020-08-05
Compiler: gcc\ 10.1.0
Processor: generic x86

Apparently the automated builds are still using gcc 10.1.0 which was known to contain a bug. We had a workaround for that though, so it shouldn't cause crashes.

**Comment by heckflosse** [comment]
Are this crashes or freezes?

**Comment by t-o-d-d** [comment]
I currently have my cache folder on a ram drive but have tried moving it back to default and it still crashes even from empty cache folder. 

I have 32GB ram, a 250GB m.2 OS drive and a 1GB SSD data drive. This same config before I reloaded Windows and never had a crash of RT on that load. One thing is different on this reload is that I switched from Avast free AV to Bitdefender free AV. I made an exclusion to the RT folder in Bitdefender but considering uninstalling it just because I've never used it before. Was just trying it out to see if it's less of a resource hog than Avast.. 

It's strange because sometimes the same RT build will seem to run fine, then other times it crashes/freezes. I don't know what the difference is between a crash and freeze. I can say most the time now when it crashes/freezes, I cannot get it to close even from task manager. Have to sign out of Windows. Everything else on the computer by the way is stable. No other issues.

**Comment by Thanatomanic** [comment]
A crash is a sudden closure of the application (GUI disappears), a freeze is an application that becomes unresponsive to user input (GUI stays visible / greyed out).

**Comment by t-o-d-d** [comment]
Aha so these are freezes. It greys out eventually but still on screen and unresponsive. Stuff (entries or whatever they're called) continues to happen in GDB...

**Comment by Thanatomanic** [comment]
> I cannot get it to close even from task manager. Have to sign out of Windows. 

This is the really odd part for me. Can you try to monitor the CPU, RAM and disk usage when using RT until it freezes? Is there another application really active in the meanwhile, for example your virus scanner, or some Windows process?

**Comment by t-o-d-d** [comment]
Tried this just now. RT was top on CPU list. I saw Bitdefender jump when RT loaded. RT was fine as I browsed into a folder with at least a couple hundred images. When I tried to load an image RT immediately disappeared from the list. It froze but then I was able to close it from the Windows error prompt... I saw Bitdefender jump a little bit then it settled down. Going to try uninstalling it now...

**Comment by t-o-d-d** [comment]
So far so good.. No freeze with Bitdefender uninstalled after loading up a few different large folders and opening a file... I am pretty certain it was the culprit...

**Comment by t-o-d-d** [comment]
Anybody recommend a lightweight AV for Windows? :)

**Comment by Thanatomanic** [comment]
Personally I don't use any AV in Windows and never had trouble, but maybe you'd better ask this question in your topic on pixls.us 😃 

Can we close? - it is a known problem that sometimes AV can interfere, without a clear solution

**Comment by t-o-d-d** [comment]
Yes please do. Pretty confident problem solved.

**Comment by heckflosse** [comment]
> I currently have my cache folder on a ram drive but

I want to come back to this, though not related to this issue:

If your RT cache is on a ram drive, which is not backed up and restored to/from a physical drive on restart of your OS, RT needs to build the cached thumbnails of a folder again when opening this folder (which means it will need to read all raw files of this folder, makes thumbs of them and write them to the cache folder), whichs content will be lost at next restart of OS if it's on ram drive.

Better avoid to hold your RT cache on a ram drive unless you have good reasons to do this...

Edit: about storage location of RT Cache best practices

1) Store RT Cache on SSD
2) if there's not enough space on your SSD to store RT Cache, use a spinning drive
3) don't store RT Cache on a network drive

**Comment by t-o-d-d** [comment]
That makes sense. I will change it back to SSD. Thanks
