### ISSUE TITLE
16-bit Hald CLUTs

### ISSUE THREAD

**Issue by strogonoff** [Beep6581/RawTherapee#5877]
From my understanding, Hald CLUTs (made by Patrick David et al.) distributed [from RawPedia](https://rawpedia.rawtherapee.com/Film_Simulation) are 8-bit, is that correct?

Is huge file size (and the associated hosting/traffic expenses) the main reason for not distributing 16-bit Hald CLUTs? Or will they objectively not produce a difference?

**Comment by Thanatomanic** [comment]
The answer is given on the RawPedia page you linked:

> Color transformation precision depends on the number of levels (columns) in the HaldCLUT image, and on the bit depth used to store the HaldCLUT image. If working on a 32-bit image (or an any-bit image in 32-bit space) using a 12-level HaldCLUT stored in an 8-bit file, for example, the HaldCLUT stores color values with less precision than your image (or your working space) can store. **This should not be a problem though, as unknown colors are interpolated from known values, so posterization should not occur.** The bit depth of the image format you use to store the HaldCLUT depends on your needs, and is not strictly related to the number of levels the HaldCLUT contains. **Photographers will be fine using 8-level HaldCLUTs stored in 8-bit images even when processing higher bit-depth photographs.**

(emphasis added by me)

**Comment by Beep6581** [comment]
@dtschump wrote code which shrinks a HaldCLUT's size down to a few kilobytes. Would be nice if this was adopted in RT. That's issue #5228

**Comment by strogonoff** [comment]
I see. I'd be happy to contribute a hosting facility for 16-bit CLUTs, if files remain large in foreseeable future.

I think I'm not the only one who'd rather cut down on interpolation (even if it's not entirely warranted)
