### ISSUE TITLE
Canon EOS 5D mk IV not detected (Linux, from source)

### ISSUE THREAD

**Issue by KarlMagnusLarsson** [Beep6581/RawTherapee#5883]
My camera Canon EOS 5D mk IV is not detected in the transform menu, when I use a build created from source using Linux Debian Testing (Bullseye). 

How shall I patch the source or the configuration to have Canon EOS 5D mk IV automatically detected?

Version: github source commit 130fbb8eb2efa70f89b36f7bf8c9722e804b73eb (Aug-10 2020)
OS: Debian Testing (Bullseye)
Build follows https://rawpedia.rawtherapee.com/Linux

Steps to reproduce:
1: git clone https://github.com/Beep6581/RawTherapee
2: mkdir build
3: cd build
4: cmake \
    -DCMAKE_BUILD_TYPE="release"  \
    -DCACHE_NAME_SUFFIX="5-dev" \
    -DPROC_TARGET_NUMBER="2" \
    -DBUILD_BUNDLE="ON" \
    -DBUNDLE_BASE_INSTALL_DIR="$HOME/programs/rawtherapee" \
    -DOPTION_OMP="ON" \
    -DWITH_LTO="OFF" \
    -DWITH_PROF="OFF" \
    -DWITH_SAN="OFF" \
    -DWITH_SYSTEM_KLT="OFF" \
    ..
5: make -j8
6: make install
7: ~/programs/rawtherapee/rawtherapee
8: Double click on Canon raw CR2 file. (example: 0Y8A6791.CR2 attached)
https://drive.google.com/file/d/1lXMJnhM5AADF396yuIPmA6HDRCZ_Bv1Q/view?usp=sharing
9: select Transform (alt-t) tool
10: Lens profile is automatically selected and lens Canon EF 24-70 f/2.8 L is found. However the camera field is empty. If I manually select camera then only Canon EOS 5D, EOS 5D mk II or EOS 5D mk III are available.
Expected: Canon EOS 5D mk IV should have been automatically selected (and available in menu). 

The regular OSX 5.8 dmg from https://rawtherapee.com/shared/builds/mac/RawTherapee_5.8.dmg does detect Canon EOS 5D mk IV camera automatically (and has it in camera manual selection menu). The Debian package apt install rawtherapee does not have Canon EOS 5D mk IV, only mk I-II and III.

How shall I patch the source or the configuration to have Canon EOS 5D mk IV automatically detected?

**Comment by KarlMagnusLarsson** [comment]
The cmake result from step 4 is here
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_BUILD_TYPE: release
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'gtk+-3.0>=3.16'
--   Found gtk+-3.0, version 3.24.20
-- Checking for module 'gtkmm-3.0>=3.16'
--   Found gtkmm-3.0, version 3.24.2
-- Checking for module 'glib-2.0>=2.44'
--   Found glib-2.0, version 2.64.4
-- Checking for module 'glibmm-2.4>=2.44'
--   Found glibmm-2.4, version 2.64.2
-- Checking for module 'cairomm-1.0'
--   Found cairomm-1.0, version 1.12.2
-- Checking for module 'gio-2.0>=2.44'
--   Found gio-2.0, version 2.64.4
-- Checking for module 'giomm-2.4>=2.44'
--   Found giomm-2.4, version 2.64.2
-- Checking for module 'gthread-2.0>=2.44'
--   Found gthread-2.0, version 2.64.4
-- Checking for module 'gobject-2.0>=2.44'
--   Found gobject-2.0, version 2.64.4
-- Checking for module 'sigc++-2.0>=2.3.1'
--   Found sigc++-2.0, version 2.10.2
-- Checking for module 'lensfun>=0.2'
--   Found lensfun, version 0.3.2.0
-- Checking for module 'librsvg-2.0>=2.40'
--   Found librsvg-2.0, version 2.48.7
-- Checking for module 'lcms2>=2.6'
--   Found lcms2, version 2.9
-- Checking for module 'expat>=2.1'
--   Found expat, version 2.2.9
-- Checking for module 'fftw3f'
--   Found fftw3f, version 3.3.8
-- Checking for module 'libiptcdata'
--   Found libiptcdata, version 1.0.5
-- Checking for module 'libtiff-4>=4.0.4'
--   Found libtiff-4, version 4.1.0
-- Found JPEG: /usr/lib/x86_64-linux-gnu/libjpeg.so (found version "62") 
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Found PNG: /usr/lib/x86_64-linux-gnu/libpng.so (found version "1.6.37") 
-- Checking for module 'libcanberra-gtk3'
--   Found libcanberra-gtk3, version 0.30
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Performing Test _fftw3f_multithread
-- Performing Test _fftw3f_multithread - Failed
-- Performing Test LENSFUN_HAS_LOAD_DIRECTORY
-- Performing Test LENSFUN_HAS_LOAD_DIRECTORY - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/magnus/usr/source/RawTherapee/build

**Comment by Lawrence37** [comment]
~You have lensfun version 0.3.2.0 which doesn't have the 5D mk IV. Try a newer version or~ add [this](https://github.com/lensfun/lensfun/blob/79ff00ad8c5524a0264f554e116edd79e2b241d7/data/db/slr-canon.xml#L61) entry to your lensfun database.

Edit: More information here: http://rawpedia.rawtherapee.com/Lens/Geometry#Lensfun

**Comment by Thanatomanic** [comment]
I have zero problems recognizing the camera and lens with lensfun on my (just updated) Windows build. Please run `lensfun-update-data` and make sure your RawTherapee options file points to the right path for lensfun.
```
[Lensfun]
DBDirectory=....

**Comment by Thanatomanic** [comment]
@Lawrence37 
>You have lensfun version 0.3.2.0 which doesn't have the 5D mk IV. Try a newer version or add this entry to your lensfun database.

A newer version of lensfun (the library) is not the right way to solve this issue. Running `lensfun-update-data` and updating the database is. The 5D Mk IV is supported in lensfun 0.3.2.

**Comment by KarlMagnusLarsson** [comment]
@Lawrence37 @Thanatomanic 
Thank you for checking the issue and for the help.

@Thanatomanic 
Your hint worked for me. 
I ran lensfun-update-data as normal user and pointed [Lensfun] DBDirectory= in options file to the database that lensfun-update-data stated it had created.
