### ISSUE TITLE
Inspect tab disappeared?

### ISSUE THREAD

**Issue by albfe** [Beep6581/RawTherapee#5895]
I have been using RawTherapee built from sources (git) on Fedora 31. I have noticed that the "Inspect" tab disappeared from the browser mode. I am not sure on when, as I am not using the browser mode often, but probably some weeks ago (when I noticed the first time it was certainly at least 1 month ago, but then I haven't had time to check more carefully until today.
I have searched here and on the forum and could not find anything about the Inspect tab. Thus, I am reporting this as a bug.

**Comment by Thanatomanic** [comment]
Please do a search of the GitHub issue list before posting. The preview windows is being modified and there is some ongoing discussion: https://github.com/Beep6581/RawTherapee/issues/5867

Edit: not to be too snarky, but this should have come up in your search https://github.com/Beep6581/RawTherapee/search?q=inspect&type=Issues

**Comment by albfe** [comment]
I did search, but for some reasons I could not find anything, sorry for that and thanks for pointing me to the issue
