### ISSUE TITLE
Can't recognize the bayer pattern and/or the correct order of pixels

### ISSUE THREAD

**Issue by dimonoid** [Beep6581/RawTherapee#5897]
Please check .DNG of this photo:
https://www.dpreview.com/sample-galleries/0635778599/sony-a7r-iv-sample-gallery/8754459393

Photo looks highly pixelated(left-right pixels in each 2x2 pixels in wrong order?), and almost all the settings in the tab "Raw" do not get loaded at all including chromatic aberration removal setting.

Yes, I know that this photo is 539 MB and loading takes some time, but ram is not an issue.

Tested on 5.8 release.

**Comment by Thanatomanic** [comment]
This is not a RAW file, but a processed pixel shift file. This is also what the image description says:

> 16-shot pixel shift, for higher resolution (240MP) and to cancel the effect of the Bayer CFA. Exposed for the highlights, then tonemapped in ACR. Download original to get a sense of the malleability of pixel shift raw files. (Multiple pixel shift raw files were combined using PixelShift2DNG to create a composite DNG, which was then processed in Adobe Camera Raw)

I don't think it is very reasonable to say that support for files like these is going to be very good soon - maybe ever. But @heckflosse might have another idea 🙂

**Comment by heckflosse** [comment]
> I don't think it is very reasonable to say that support for files like these is going to be very good soon - maybe ever. But @heckflosse might have another idea 

This is simply a processed (demosaiced) raw file, as @Thanatomanic already wrote. Nothing we can improve here. If it would be a pixelshift file with 16 frames, we could implement motion detection as we did for 4 frame pixelshift files. But even for the ARQ files which are build from 16 frames consisting of 4 x 4 frames, where each pack is already combined from 4 frames without motion detection, it is not possible to implement this. Latter is a design fault from Sony imho.

I intend to close this issue.
