### ISSUE TITLE
Strange green/black images from canon SRAW1/2 files

### ISSUE THREAD

**Issue by Jacalz** [Beep6581/RawTherapee#5898]
## Description
Due to my CF-cards being rather slow, I wanted to turn down the resolution of my raw files to save some space on my Canon 5D Mark 2 that I recently got. However, in doing so, I noticed that the SRAW1 and SRAW2 options lead to images being are pretty much unusable and unrecognizable inside rawtherapee. They show up with some sort of green and black colour.

I have tested the files and they work perfectly fine in Darktable.

## Actual result (Canon SRAW1 or SRAW2)
![image](https://user-images.githubusercontent.com/25466657/91664872-43480500-eaf2-11ea-82a4-253568ac96b1.png)

## Expected result (regular RAW file)
![image](https://user-images.githubusercontent.com/25466657/91664862-2ad7ea80-eaf2-11ea-97c8-956263787a27.png)

## Camera and lens hardware
- **Camera:** Canon EOS 5D Mark II with firmware 2.1.2 (same issue with 1.0.7).
- **Lens:** Canon EF 24-105 f4 L IS USM

## Sample raw files (zip file)
Looks like GitHub won't allow me to upload more than 10MB files. A ufile upload will have to do for now (30 days expiration sadly).
https://ufile.io/0ewvq2xy

**Comment by Thanatomanic** [comment]
Is it safe to assume you are using the RT 5.8 release version? This bug was fixed in the development builds some time ago: https://github.com/Beep6581/RawTherapee/commit/4221fdf31e43658cef98ad660ad398b8ae81b8d7

**Comment by Jacalz** [comment]
Yeah that absolutely correct. Thanks for the blazing fast response. I put down way too much time to get everything sorted for the bug report which meant that I forgot to mention the application version. Silly me, sorry about that 😅

Is a new release imminent or should I make sure to back port the commit to my Linux distribution? 🙂

**Comment by Jacalz** [comment]
Will give develop a try to see if that fixes my issues before I close this though 🙂

**Comment by Thanatomanic** [comment]
If it's critical for your work, you should probably try to build yourself or grab the AppImage from the nightly builds here: https://github.com/Beep6581/RawTherapee/releases/tag/nightly

I'm not sure on a date for a next release.

**Comment by Jacalz** [comment]
Alright, thank you 🙂

**Comment by Jacalz** [comment]
I compiled with the patch and it works again now. I will make sure to get the patch backported into the rawtherapee package in my Linux disturbution as soon as builds complete :)
