### ISSUE TITLE
Add Nikon Z5 color matrix to camconst.json

### ISSUE THREAD

**Issue by Kaens** [Beep6581/RawTherapee#5900]
Uploaded a bunch of raws to the raw.pixls.us repo; can't find them again but hopefully that's not a failure.

**Comment by Thanatomanic** [comment]
@Kaens What is your issue?

**Comment by Kaens** [comment]
It's a new camera profile set request, I suppose. I came here via the raw.pixls.us page where I was for that exact purpose but for darktable.

Now that you mention it though, I did have an issue that doesn't have to do with any camera. I can't even check if rt works with z5. (The `-cli` won't produce any file output, either (not even an error message), and for the `-s` option, the sidecar on it should be inside NKSC_PARAM as per what Nikon's software is doing as opposed to what the help says.)

Here's the `rawtherapee_debug.exe` v5.8 output on my W10x64:
```
Gtk:ERROR:../gtk+-3.24.13/gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unable to load image-loading module: c:\lib\gdk-pixbuf-2.0\2.10.0\loaders\libpixbufloader-png.dll: 'c:\lib\gdk-pixbuf-2.0\2.10.0\loaders\libpixbufloader-png.dll': The specified module could not be found. (gdk-pixbuf-error-quark, 5)
Bail out! Gtk:ERROR:../gtk+-3.24.13/gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unable to load image-loading module: c:\lib\gdk-pixbuf-2.0\2.10.0\loaders\libpixbufloader-png.dll: 'c:\lib\gdk-pixbuf-2.0\2.10.0\loaders\libpixbufloader-png.dll': The specified module could not be found. (gdk-pixbuf-error-quark, 5)
Exception code=0x80000003 flags=0x0 at 0x00007FFDC9609562
```

**Comment by Thanatomanic** [comment]
Please don't use the same thread for different issues. The repository on raw.pixls.us does not contain any Z5 samples, so something went wrong.

The color profile for the Nikon Z5 was added in the latest update of Adobe Camera Raw (12.4), so could be added to `camconst.json`.

**Comment by Kaens** [comment]
https://raw.pixls.us/data/Nikon/NIKON%20Z%205/ Here are the samples (somehow only 4 of them at the time of writing), they are there. Somebody must've gotten around to adding them.

**Comment by kdm9** [comment]
These seem to be in ART, should I add the Z5 to my EOS R5/R6 PR? (#5905)

**Comment by Thanatomanic** [comment]
The changes from ART in PR #5905 look good, closing for now.
