### ISSUE TITLE
scrolling with the mouse wheel in the file browser is disabled when using filters on colour labels and change folder.

### ISSUE THREAD

**Issue by LordPhoenixfr** [Beep6581/RawTherapee#5912]
When I activate the colour filters on the file browser and change folders while keeping the same filters, it is no longer possible to scroll through the photos with the mouse wheel. If I delete all the colours filters, the scrolling returns and remains if I reactivate the filters. If I change the folder again and go back to the previous one, the problem repeats itself until I deactivate them again.

Version: 5.8
Branch: releases
Commit: 9a9e0acbf
Commit date: 2020-02-04
on Ubuntu 20.04

**Comment by ff2000** [comment]
I tried to reproduce. Both v5.8 and very recent git dev allowed me to scroll after enabling color filters.

But I generally have issues from time to time with scrolling in RT. Happens very sporadically but then I can't use my scroll wheel at all - file browser, side panels, image editor - nothing works. Probably that's what you were seeing?
This AFAIK is a known issue.
A workaround is to switch to a different window (e.g. you webbrowser, or DE's file browser, or whatever) and then back to the RT window. Scrolling will work again after that.

**Comment by LordPhoenixfr** [comment]
> I tried to reproduce. Both v5.8 and very recent git dev allowed me to scroll after enabling color filters.

It’s not only after enabling color filter, it’s after enabling color filter and changing folder…

> 
> But I generally have issues from time to time with scrolling in RT. Happens very sporadically but then I can't use my scroll wheel at all - file browser, side panels, image editor - nothing works. Probably that's what you were seeing?

I don’t think so, I don’t remember such problems 

> This AFAIK is a known issue.
> A workaround is to switch to a different window (e.g. you webbrowser, or DE's file browser, or whatever) and then back to the RT window. Scrolling will work again after that.

Not for me.

**Comment by ff2000** [comment]
https://youtu.be/J94xTWs-Waw

**Comment by heckflosse** [comment]
@LordPhoenixfr Immediately after your last post I tried and could reproduce it. Now I can not reproduce it anymore. Looks like some random behaviour (maybe caused by an uninitialized variable). As I could reproduce it once, I think the issue is valid and needs further investigation.
