### ISSUE TITLE
Feature request: option to choose, show history after close RT.

### ISSUE THREAD

**Issue by nquantum** [Beep6581/RawTherapee#5917]
I've learn it nature by design to clear history after close RT. How ever use case is one day later I choose come back adjust here and there I can review what I've done so far or not have done yet. I tweak some thing say explosure still good but I have new experience that new way is better so I come adjust some. I think it have value. And it deserve word "history" is to history and can re_adjust any time. So if it still in doubt about benefit, how about make it option in setting wether or not to preserve history next time, let user to choose. Maybe clear history by default setting is ok. But have some option to change. Just like Autodest Fusion360 preserve all action user have done from begin to finish and can tweak any of them any time. Some work history is so long and similar action perform they group together those those similar action and can expand to show all of history.

In stead that just put in all in sidecar little people can see and use. I think is good to have option to choose wether or not to preserve history when close.

Thank so much. 
Ps. I also thinking about thise history in Gimp and Photoshop too.

**Comment by nquantum** [comment]
And please, please have snapshot in sidecar file. Say I have color version, black and white, etc version to choose from each time open raw file that already "cooked" also review what have done.

**Comment by simohno** [comment]
Hi
If you didn't know, the last feature you mention is integrated in the ART software, a derivative of RawTherapee
https://bitbucket.org/agriggio/art/wiki/Home

**Comment by Thanatomanic** [comment]
@nquantum This idea is not going to get implemented any time soon. Please see https://github.com/Beep6581/RawTherapee/issues/2624

@simohno Please don't use our issue tracker to advertise other software, even if we're friends with the developers
