### ISSUE TITLE
Camconst.json support for Canon EOS R + bug opening files

### ISSUE THREAD

**Issue by jonathanBieler** [Beep6581/RawTherapee#5922]
I'm opening this after reading the last comment on #5319. Cr3 support in 5.8 is great but I'm having some colors issue with my EOS R, the image comes as desaturated and the colors are a bit off (specially the greens, they are brownish).

Here's an example (top is jpg out of the camera, bottom is cr3 in 5.8) : https://imgur.com/a/0aVVecL

If I understand correctly, you guys need some calibration data to get the colors correctly ? I can maybe help with that.

**Comment by Thanatomanic** [comment]
There is also #5317 which was closed without a fix. The color matrix should be available in Adobe DNG (EOS R is listed here https://helpx.adobe.com/camera-raw/kb/camera-raw-plug-supported-cameras.html), and that would already help a lot with the colors. I'll see if I can extract it.

As for a better profile, please see this http://rawpedia.rawtherapee.com/Adding_Support_for_New_Raw_Formats or for even more fine-grained controle this http://rawpedia.rawtherapee.com/How_to_create_DCP_color_profiles

**Comment by jonathanBieler** [comment]
Cool thanks. Do you need the white frames ? I can probably do those.

**Comment by Thanatomanic** [comment]
@jonathanBieler  Yes please!

**Comment by jonathanBieler** [comment]
Here, I think I did them correctly : https://filebin.net/cnwvkzw18ww48upo

Interestingly trying to open them makes RawTherapee crash.

**Comment by heckflosse** [comment]
> Interestingly trying to open them makes RawTherapee crash.

Crash confirmed.

**Comment by Thanatomanic** [comment]
@jonathanBieler I've added as much information as I could based on a conversion to DNG's.
The bug for opening these CR3 files remains...

**Comment by jonathanBieler** [comment]
I've tried to replace my Camconst.json with the new one but that didn't worked well :

https://i.imgur.com/Ecsj7XF.png

Is it supposed to work or do I need to wait for a new release ?

**Comment by Thanatomanic** [comment]
I think there have also been some bug fixes since v.5.8, so you'd have to use a [nightly build](https://github.com/Beep6581/RawTherapee/releases/tag/nightly) to test it out.

**Comment by jonathanBieler** [comment]
Yep that works, it's almost perfect, very close to the image out of the camera. I also haven't had any crashes with "normal" pictures, I haven't tried long exposures though.

Thanks for your work on RT, it's awesome.

**Comment by Krijger** [comment]
@Thanatomanic I already provided files for Canon EOS R to @Beep6581 in #5317 (although this information may be too late to be useful now)
