### ISSUE TITLE
DJI Mavic Air 2 (FC3170) White Frames

### ISSUE THREAD

**Issue by andreskrey** [Beep6581/RawTherapee#5933]
Hi!,

I've noticed the lack of support for the new **DJI Mavic Air 2** and wanted to collaborate with sample white frames.

I've included **two sets**:

Set 1: 7 pics, **0.5/sec**, ISO 100/200/400/800/1600/3200/6400
Set 2: 7 pics, **2/sec**, ISO 100/200/400/800/1600/3200/6400

Can't tell you if the camera has built-in LENR but both sets should look different if it does. Pictures were gathered by pointing the camera to my computer display at max brightness with a white background.

File here: https://filebin.net/1yc8qozz1gz6ba0e

Files are straight from the drone. EXIF was tweaked to remove GPS data and camera's serial number.

Not sure if you can add support to the following issues with these frames, but nonetheless I wanted to mention them. Let me know if you need new issues for these bugs:

1) Built-in lens profile **is not applied** when loading the picture into RawTherapee. Lightroom loads them by default and reduces the barrel distortion.
2) All pictures have a weird blue shift on the edges and a red shift on the center. All pictures, no matter the scenery, **have a warm center and cold edges**. Let me know if you want samples. This does not happen on Lightroom.

**Comment by Thanatomanic** [comment]
@andreskrey I have downloaded the files and will inspect them soon.

The lens profile support is handled outside of RawTherapee at the Lensfun project https://lensfun.github.io

I will take a look at the coloration shifts you mention.

**Comment by andreskrey** [comment]
Do let me know if you need more samples. Not sure if you'll be able to see the color shifts on the samples. Happy to help you here :)

I'll check the lensfun project regarding the lens profile, thanks for the heads up.

**Comment by Thanatomanic** [comment]
@andreskrey I don't see the color shifts in the samples you provided. If you can shoot a uniform target (preferably a white wall illuminated by daylight) to show this effect I would be interested to see it.
The samples for the camera that I found on DPReview did not seem to show anything special.

As for the basic white-level support, it is now added to `camconst.json` with https://github.com/Beep6581/RawTherapee/commit/cde7aababbbf60188dab8133bc6c7fd991cacc0f. There doesn't seem to be any difference between ISO values nor with the chosen shutter speeds.

**Comment by andreskrey** [comment]
Forgive my ignorance, but given that the lens profile correction is built-in the DNG file, shouldn't RT be able to extract and apply it? I've searched across all issues in the repo [and found one](https://github.com/Beep6581/RawTherapee/issues/4049) that more or less mention what I'm questioning here.

I'm guessing that RT doesn't support built-in profiles and needs manual correction via lensfun?

I'll get you the pics with the color shifts this weekend.

**Comment by andreskrey** [comment]
Here are the pics with the color shifts: https://filebin.net/3wze0v6xicktkjcp

Both pictures were taken pointing the camera to a white-ish wall, illuminated indirectly by daylight.

By loading the images on RT you'll see immediately what I mean, the thumbnails will have blue edges and a red center. Cranking up and down the exposure will exaggerate the effect as well.

![image](https://user-images.githubusercontent.com/8786949/95470336-94aca500-0978-11eb-8f33-20a8bcd886f2.png)

One example with exp compensation -0.5:

![image](https://user-images.githubusercontent.com/8786949/95470499-c9206100-0978-11eb-8980-b110513138d4.png)


Let me know what you think @Thanatomanic

**Comment by Thanatomanic** [comment]
@andreskrey I don't know what to think after seeing these images. I don't see this effect in other samples I can find online, for example https://www.dpreview.com/sample-galleries/4451978106/dji-mavic-air-2-sample-gallery/2014742306 or here https://www.tomsguide.com/reviews/dji-mavic-air-2

Could it be your camera or lens has a malfunction somehow? In any case, I don't think we can improve the support for your camera much further and will close this issue.

As for the lens profile: as explained in #4049 some metadata that can be stored in a DNG is not read by RawTherapee. For now, a lensfun profile is your best bet.
