### ISSUE TITLE
Color label not effective anymore for filtering, after resetting to default processing profile

### ISSUE THREAD

**Issue by simohno** [Beep6581/RawTherapee#5936]
To reproduce this bug:

- Assign a color label (e.g. Red) to a file
- Open it in Editor mode and do whichever edit (or even none)
- Reset to default the processing profile (right click on thumbnail > Operations on processing profile > Reset to default)
- Switch back to Navigator mode
- Filter the files by Red label

Now the main window does not show the file, although without activating the filter, the thumbnail border shows correctly the Red flag (I suppose that resetting to default the PP should not alter the labels/ratings already made).
Manually re-assigning the Red label will show again the file in filtering by colour.

The bug also happens with Ratings (stars *****).

_Version: 5.8-2470-g35519dfd3
Branch: dev
Commit: 35519dfd3
Commit date: 2020-09-17
Compiler: x86_64-w64-mingw32-gcc\ 9.3.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.24.2
Lensfun: V0.3.2.0
Build type: Release
Build flags: -mwin32\ -m64\ -mthreads\ -msse2\ -std=c++11\ -mtune=generic\ -Werror=unused-label\ -Werror=delete-incomplete\ -fno-math-errno\ -Wall\ -Wuninitialized\ -Wcast-qual\ -Wno-deprecated-declarations\ -Wno-unused-result\ -Wunused-macros\ -fopenmp\ -Werror=unknown-pragmas\ -Wno-aggressive-loop-optimizations\ -DNDEBUG\ -O3\ -ftree-vectorize
Link flags: -m64\ -mthreads\ -static-libgcc\ -mtune=generic\ -s\ -O3
OpenMP support: ON
MMAP support: ON
Build OS: Linux 4.4.0-101-generic x86_64
Build date: Thu, 17 Sep 2020 21:51:06 +0000 UTC
Build epoch: 1600379466
Build UUID: 2fc27ff0-e681-487d-bed3-37f147c38df0_

**Comment by Thanatomanic** [comment]
Bug confirmed. It seems it specifically has to do with the 'Processing profile > Reset to default' option.

**Comment by Thanatomanic** [comment]
This bug has probably been present for a long time. I tested with RT5.7 and could reproduce as well.

**Comment by simohno** [comment]
Hello, any news concerning this bug?

**Comment by Lawrence37** [comment]
Color labels are stored in processing profiles which makes it easy to accidentally modify. This patch should fix the bug.

```diff
diff --git a/rtgui/filebrowser.cc b/rtgui/filebrowser.cc
index a8ce94e7f..0d2451b59 100644
--- a/rtgui/filebrowser.cc
+++ b/rtgui/filebrowser.cc
@@ -985,11 +985,19 @@ void FileBrowser::menuItemActivated (Gtk::MenuItem* m)
         }
 
         for (size_t i = 0; i < mselected.size(); i++)  {
-            mselected[i]->thumbnail->createProcParamsForUpdate (false, true);
+            const auto thumbnail = mselected[i]->thumbnail;
+            const auto rank = thumbnail->getRank();
+            const auto colorLabel = thumbnail->getColorLabel();
+            const auto stage = thumbnail->getStage();
+
+            thumbnail->createProcParamsForUpdate (false, true);
+            thumbnail->setRank(rank);
+            thumbnail->setColorLabel(colorLabel);
+            thumbnail->setStage(stage);
 
             // Empty run to update the thumb
-            rtengine::procparams::ProcParams params = mselected[i]->thumbnail->getProcParams ();
-            mselected[i]->thumbnail->setProcParams (params, nullptr, FILEBROWSER, true, true);
+            rtengine::procparams::ProcParams params = thumbnail->getProcParams ();
+            thumbnail->setProcParams (params, nullptr, FILEBROWSER, true, true);
         }
 
         if (!mselected.empty() && bppcl) {
```

**Comment by simohno** [comment]
Great, what is the next step? Should a collaborator make this the change into _filebrowser.cc_ or test it in an own copy?
I'm not an expert

**Comment by Lawrence37** [comment]
@simohno I'm giving people time to test/comment if they wish. I will commit the change very soon.
