### ISSUE TITLE
Compiling error on ubuntu 16.04: /home/xxx/programs/rt_git/RawTherapee/rtgui/delayed.h:161:24: error: ‘Glib::SignalProxy’ has not been declared

### ISSUE THREAD

**Issue by lummukka** [Beep6581/RawTherapee#5943]
Hi, compiling on ubuntu 16.04 stopped working newly. I have been pulling latest dev branch with git pull. What could be wrong?

```
 Building CXX object rtgui/CMakeFiles/rth.dir/batchtoolpanelcoord.cc.o
In file included from /home/xxx/programs/rt_git/RawTherapee/rtgui/adjuster.h:22:0,
                 from /home/xxx/programs/rt_git/RawTherapee/rtgui/adjuster.cc:19:
/home/xxx/programs/rt_git/RawTherapee/rtgui/delayed.h:161:24: error: ‘Glib::SignalProxy’ has not been declared
     void connect(Glib::SignalProxy<void, Ts...> signal, const sigc::slot<void, Ts...>& slot, const sigc::slot<void, Ts...>& immediate_slot = {})
                        ^
/home/lxxx/programs/rt_git/RawTherapee/rtgui/delayed.h:161:35: error: expected ‘,’ or ‘...’ before ‘<’ token
     void connect(Glib::SignalProxy<void, Ts...> signal, const sigc::slot<void, Ts...>& slot, const sigc::slot<void, Ts...>& immediate_slot = {})

  
-- git command found: /usr/bin/git
-- Git checkout information:
--     Commit description:    5.8-2530-g5fd640f
--     Branch:                dev
--     Commit:                5fd640f
--     Commit date:           2020-10-09
--     Commits since tag:     2449
--     Commits since branch:  2449
--     Version (unreliable):  5.8.2449
-- Build information:
--     Build OS:              Linux 4.4.0-189-generic x86_64
--     Build date:            Fri, 09 Oct 2020 16:41:41 +0000 UTC
--     Epoch:                 1602261701
--     UUID:                  bd4dd5f6-681a-4c01-93f6-c00b2c9f1786
```

Br
Vesa

**Comment by heckflosse** [comment]
@lummukka 

please post the whole content of `AboutThisBuild.txt`

@Floessie that sounds a bit like your `delayed` changes...

**Comment by lummukka** [comment]
Here comes: 

```
#cat build/AboutThisBuild.txt
 
Version: 5.8-2530-g5fd640f
Branch: dev
Commit: 5fd640f
Commit date: 2020-10-09
Compiler: cc 5.4.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.18.0
Lensfun: V0.3.95.0
Build type: release
Build flags:  -std=c++11 -march=native -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON
Build OS: Linux 4.4.0-189-generic x86_64
Build date: Fri, 09 Oct 2020 16:43:46 +0000 UTC
Build epoch: 1602261826
Build UUID: 2283f0b1-a833-454b-93df-f8485b7530b6
```

**Comment by heckflosse** [comment]
> Compiler: cc 5.4.0

That's really old.

**Comment by Floessie** [comment]
@heckflosse I rather think it's a GTK issue:

```
/home/xxx/programs/rt_git/RawTherapee/rtgui/delayed.h:161:24: error: ‘Glib::SignalProxy’ has not been declared
```

The oldest VM I've currently at hand is Debian Stretch with GTK 3.22 and GCC 6.3. I'll be on vacation starting tomorrow and am packing today, so this has to wait at least a week.

**Comment by Floessie** [comment]
I had a look at the [glibmm-2.46 sources](https://ftp.gnome.org/pub/GNOME/sources/glibmm/2.46/): It's still a non-variadic template implementation (pre-C++11), so there's nothing we can do but to revert the `delayed` changes.

**Comment by Thanatomanic** [comment]
Or we raise our minimal requirements? Ubuntu 16.04 was released 4 years ago and reaches end of support on April 30, 2021.

**Comment by Floessie** [comment]
`delayed.h` is no big deal. We can drop it or we can raise our requirements. Opinions?

**Comment by heckflosse** [comment]
I'm for raising our requirements. But imho it's up to you, @Floessie, to decide that, as you're building also for ppc and whatever.

**Comment by Floessie** [comment]
Me too. Though I'm building for different architectures, it's always the latest sh** :wink:, and I seldom have a very old VM at hand. The problem is, that it's hard to emulate an old (pre C++11) glibmm. But we can do without `delay.h` as we always did. It was just meant as an optimization.

**Comment by Floessie** [comment]
Okay. If noone objects, I'll raise the [glibmm requirements](https://github.com/Beep6581/RawTherapee/blob/dev/CMakeLists.txt#L459) to [2.48](https://github.com/GNOME/glibmm/commit/f6e46c68fd2b7289964e6e0d446b11658187b68d).

**Comment by zflat** [comment]
@Floessie any advice on how to compile on 16.04 now? Here is the package that I have available:

```
apt-cache policy libglibmm-2.4-dev
libglibmm-2.4-dev:
  Installed: 2.46.3-1
  Candidate: 2.46.3-1
  Version table:
 *** 2.46.3-1 500
        500 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
```

The docs (https://rawpedia.rawtherapee.com/Linux#Ubuntu_16.04_LTS) do not have any information about getting the correct  version. Does 16.04 support need to be dropped? Should that be updated in the docs?

**Comment by Thanatomanic** [comment]
The changes made by this PR https://github.com/Beep6581/RawTherapee/pull/5878 means that the newest version of RawTherapee you can compile and run on Ubuntu 16.04 LTS is now 5.8.
There is no safe development build in between that you can compile, so there will be a few issues that you will only be able to fix when you update your distro.

**Comment by Floessie** [comment]
@zflat Yes, sorry, this means you have to update your distro. With at least one of my installations I'm in the same boat, as Debian Jessie is no longer maintained. So I'll upgrade or reinstall during the winter holidays, that's life. :neutral_face:

**Comment by Thanatomanic** [comment]
@zflat The documentation has been updated to reflect the new situation.
