### ISSUE TITLE
Enable edge detection on wavelets will cause crash if contrast settings change

### ISSUE THREAD

**Issue by RichardRegal** [Beep6581/RawTherapee#5945]
Open a raw file and select neutral profile.
Navigate to Advanced tab.
Enable Wavelet Lettings.
Enable Contrast (within Wavelet Levels). 
Enable Edge Sharpness (within Wavelet Levels)
Enable Edge detection (within Edge Sharpness)
Make any change to the Contrast Levels and watch the program crash.

I tried debug and instead of crashing when I adjusted the contrast levels in wavelets the program crashed as soon as I opened the picture with a pp3 that had those settings. I therefore have 2 logs for you, one with RawTherapee-debug (logD) and one with RawTherapee (logN)

Raw file and pp3 at https://filebin.net/q37gj8797j4waut2
[logD.txt](https://github.com/Beep6581/RawTherapee/files/5359982/logD.txt)
[logN.txt](https://github.com/Beep6581/RawTherapee/files/5359983/logN.txt)

Intel Xeon CPU E3-1245v3 @ 3.40GHz 3.40 GHz
32.0 GB RAM
Windows 10 Pro Version 2004 OS Build 19041.508
Windows Feature Experience Pack 120.2212.210

ASUS BIOS

LaCie 321 Display
NVIDIA Quadro K4000 Driver Version 27.21 14.5177 (13 Jul 2020)

RawTherapee
Version: 5.8-2497-gd6f8de428
Branch: dev
Commit: d6f8de428
Commit date: 2020-10-06
Compiler: x86_64-w64-mingw32-gcc\ 9.3.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.24.2
Lensfun: V0.3.2.0
Build type: Release
Build flags: -mwin32\ -m64\ -mthreads\ -msse2\ -std=c++11\ -mtune=generic\ -Werror=unused-label\ -Werror=delete-incomplete\ -fno-math-errno\ -Wall\ -Wuninitialized\ -Wcast-qual\ -Wno-deprecated-declarations\ -Wno-unused-result\ -Wunused-macros\ -fopenmp\ -Werror=unknown-pragmas\ -Wno-aggressive-loop-optimizations\ -DNDEBUG\ -O3\ -ftree-vectorize
Link flags: -m64\ -mthreads\ -static-libgcc\ -mtune=generic\ -s\ -O3
OpenMP support: ON
MMAP support: ON
Build OS: Linux 4.4.0-101-generic x86_64
Build date: Wed, 07 Oct 2020 07:05:52 +0000 UTC
Build epoch: 1602054352
Build UUID: f1325d00-cf63-47f6-ba31-5d0eb3f081ae

**Comment by RichardRegal** [comment]
Probably a more useful log file now as I was able to generate the error on pressing wavelet contrast in RT-debug.exe.
[logA.txt](https://github.com/Beep6581/RawTherapee/files/5360068/logA.txt)

Also it is not something caused by the removing of the clash with wavelet denoise as this problem also happened on Version: 5.8-2482-gea156df1a

**Comment by Desmis** [comment]
@RichardRegal 

Fixed with commit "8e92c13"
Thank you for testing :+1: 

jacques

**Comment by RichardRegal** [comment]
@Desmis 
Thanks.
