### ISSUE TITLE
Version 5.8 could not start after fresh install in windows 10

### ISSUE THREAD

**Issue by rhlinden** [Beep6581/RawTherapee#5947]
**OUTPUT**
    
    c:\BIN\RawTherapee\5.8>rawtherapee-debug.exe

    (rawtherapee-debug.exe:13940): Gtk-WARNING **: 12:22:00.586: Could not load a pixbuf from /org/gtk/libgtk/theme/Adwaita/assets/check-symbolic.svg.
    This may indicate that pixbuf loaders or the mime database could not be found.

    (rawtherapee-debug.exe:13940): Gtk-WARNING **: 12:22:01.195: Could not find the icon 'list-remove-symbolic-ltr'. The 'hicolor' theme
    was not found either, perhaps you need to install it.
    You can get a copy from:
            http://icon-theme.freedesktop.org/releases
    **
    Gtk:ERROR:../gtk+-3.24.13/gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unable to load image-loading module: c:\lib\gdk-pixbuf-2.0\2.10.0\loaders\libpixbufloader-png.dll: 'c:\lib\gdk-pixbuf-2.0\2.10.0\loaders\libpixbufloader-png.dll': Impossível localizar o módulo especificado. (gdk-pixbuf-error-quark, 5)
    Bail out! Gtk:ERROR:../gtk+-3.24.13/gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unable to load image-loading module: c:\lib\gdk-pixbuf-2.0\2.10.0\loaders\libpixbufloader-png.dll: 'c:\lib\gdk-pixbuf-2.0\2.10.0\loaders\libpixbufloader-png.dll': Impossível localizar o módulo especificado. (gdk-pixbuf-error-quark, 5)
    Exception code=0x80000003 flags=0x0 at 0x00007FFD440512A2
**DETAILS**
    
    Version: 5.8
    OS: Windows 10
    Description: Freshly installed from the file RawTherapee_5.8.exe (dowloaded in 2020/10/11) using default options
    except path (changed c:\program files\ to c:\bin\) produces the previous output (in debug) and don't start

**Comment by Beep6581** [comment]
@rhlinden close RawTherapee, uninstall it, delete the file called ```options``` located in the config folder (see link below), and then re-install it.

http://rawpedia.rawtherapee.com/File_Paths#Config

**Comment by rhlinden** [comment]
Hello @Beep6581 

Thank you for your help.

I did what you suggest.
Uninstall,verify that directory c:\bin\RawTherapee is empty, delete the file %LOCALAPPDATA%\AppData\Local\RawTherapee\options, reinstall.
Got exactly the same result.
Would it be of any help if I send you a 
    dir /s
or the content or the file ?
    %LOCALAPPDATA%\AppData\Local\RawTherapee\options
or any other information that could be of any help?

Best regards
Ricardo

**Comment by Beep6581** [comment]
Hi @rhlinden 
Ok, we're off to a clean start. Since the problem persists, please invoke gdb and get a stack backtrace:
http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports#Step_by_step

**Comment by rhlinden** [comment]
Hello Beep6581

Open a new ticket following instructions of the page
http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports#Step_by_step
NEW BUG: #5953

Best regards
Ricardo

**Comment by Thanatomanic** [comment]
@rhlinden This is the content of your other post for reference here

> Output log file
> [log.txt](https://github.com/Beep6581/RawTherapee/files/5374621/log.txt)
> 
> \AppData\Local\RawTherapee\options (with txt extention due to limitation of github)
> [options.txt](https://github.com/Beep6581/RawTherapee/files/5374658/options.txt)
> 
> List of files in C:\BIN\RawTherapee\5.8 path
> [files.txt](https://github.com/Beep6581/RawTherapee/files/5374667/files.txt)

**Comment by Thanatomanic** [comment]
After looking at your gdb log file it seems there is no crash, the file is really short. Can you elaborate on what you did, what you saw and in particular what made you decide that the application was not going to start or that it has crashed?

**Comment by Beep6581** [comment]
@rhlinden could you try the latest dev build? If ```rawtherapee.exe``` crashes, then run ```rawtherapee-debug.exe``` through GDB and provide the stack backtrace. Attach it to this issue.

**Comment by Beep6581** [comment]
Latest dev build:
https://github.com/Beep6581/RawTherapee/releases/download/nightly/RawTherapee_dev_5.8-2497-gd6f8de428_20201007_win64.zip

**Comment by rhlinden** [comment]
Hello @Thanatomanic 
I open a new ticket as suggest at point number 8 in the instruction of the page

    http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports#Step_by_step

It instructs to _**Open a new issue**_ to upload the files. I took it literally. I'm sorry about that.
Thank you for being so kind to close the unneeded issue and transferring the files for reference of this one issue.

I decided that there was a problem because the application did not start when invoked.
I was able to see it briefly (less than a second) in the task manager (sysinternals/process explorer) and then shut down (disappear).
I confirmed that assumption by using the debug version (rawtherapee-debug.exe), that reports a list of messages that seams a symptom of problems/errors during start. Those messages are included in the first message of this issue report.

Hello @Beep6581 
I uninstalled the current version and deleted completely the directory and it's contents and sub-directories

    %LOCALAPPDATA%\AppData\Local\RawTherapee

Download the file you suggest and inzip it to the empty directory

    C:\BIN\RawTherapee\5.8

Tried to run the debug version from the command line and got the following output

    C:\BIN\RawTherapee\5.8>rawtherapee-debug.exe
    
    (rawtherapee-debug.exe:11964): Gtk-WARNING **: 14:44:33.920: Could not load a pixbuf from                     
    /org/gtk/libgtk/theme/Adwaita/assets/check-symbolic.svg.
    This may indicate that pixbuf loaders or the mime database could not be found.
    
    (rawtherapee-debug.exe:11964): Gtk-WARNING **: 14:44:34.868: Could not find the icon 'list-remove-symbolic-ltr'. The 
    'hicolor' theme
    was not found either, perhaps you need to install it.
    You can get a copy from:
            http://icon-theme.freedesktop.org/releases
    **
    Gtk:ERROR:../gtk+-3.24.23/gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load 
    /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unable to load image-loading module: C:\lib\gdk-pixbuf- 
    2.0\2.10.0\loaders\libpixbufloader-png.dll: 'C:\lib\gdk-pixbuf-2.0\2.10.0\loaders\libpixbufloader-png.dll': Imposs¡vel localizar 
    o m¢dulo especificado. (gdk-pixbuf-error-quark, 5)
    Bail out! Gtk:ERROR:../gtk+-3.24.23/gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): 
    Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unable to load image-loading module: C:\lib\gdk- 
    pixbuf-2.0\2.10.0\loaders\libpixbufloader-png.dll: 'C:\lib\gdk-pixbuf-2.0\2.10.0\loaders\libpixbufloader-png.dll': Imposs¡vel 
    localizar o m¢dulo especificado. (gdk-pixbuf-error-quark, 5)

The output seems to be similar the the one reported in the first message of this issue.

Although I don't know the application, the dependencies the installation method or any other details of this application it seem to me that the problem seem to be related with access to the module libpixbufloader-png.dll.
That file exists in the directory:

    C:\BIN\RawTherapee\5.8\lib\gdk-pixbuf-2.0\2.10.0\loaders\libpixbufloader-png.dll

Please note that I unziped the latest dev build to **C:\BIN\RawTherapee\5.8**
Can that be due to a anti-virus incompatibility? How can I verify or discard that possibility?
Can it be due to the fact I have my OS (Windows 10) configured for Portuguese (that presents some output problems - m¢dulo should be módulo or Imposs¡vel should be Impossível).

See attached the new log.txt file:
[log.txt](https://github.com/Beep6581/RawTherapee/files/5378941/log.txt)

Best regards
Ricardo

**Comment by Thanatomanic** [comment]
@rhlinden Hi Ricardo, thanks for testing further. I don't think the localization will be an issue here. Are you 100% sure the log file you added is the result from following steps 2 through 7 from the http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports#Step_by_step page?
It is very suspicious that the log is so short and doesn't even mention the actual error.

**Comment by rhlinden** [comment]
Hi Thanatomanic 

I rechecked that the log is the right log file and it contains only the list of threads and nothing similar to a crash.

I'm including the console output of the execution of **gdb rawtherapee-DEBUG.exe** .
In this file the message shows up before the list of threads.
I don't know if you can find any value out of that info, but in doubt I'm including it.

[gdb_output.txt](https://github.com/Beep6581/RawTherapee/files/5379314/gdb_output.txt)

I found interesting that the message appears after **r** and before **set pagination off** 
I also found interesting  **warning: Can not parse XML library list; XML support was disabled at compile time**

Please let me know if any of that info is off any help.
Please let me know if you need any other information.

Best regards
Ricardo

**Comment by Beep6581** [comment]
It looks like the problem occurs outside of RT, possibly in that GTK+ module, and it corrupts the stack, making troubleshooting difficult. Temporarily disabling the antivirus program and re-testing would be an easy and good thing to try. We know that RT 5.8 does run on a fresh Windows 10 installation, so whatever's happening seems specific to your machine.

**Comment by rhlinden** [comment]
Hello @Beep6581 

You are right. 
The problem disappears if I install in **c:\program files\rawtherapee** instead of **c:\bin\rawtherapee**   
Even without disabling anti-virus. (that would't be an option anyway).

I suggest some action is adopted to avoid repetition of this situation. 
For instance remove the option of installing in a different place than **c:\program files\rawtherapee** if this proves to be the real problem.

Best regards
Ricardo

**Comment by gaaned92** [comment]
I never noticed that! I cannot start RT or ART from C:\bin.
I get the same message as above.
No problem if RT is installed elswhere.

Does anybody know what is special with that directory that it makes GTK bug?

**Comment by Thanatomanic** [comment]
I don't know what is special about the `bin` folder, but this is such an edge case that I don't think it's worthwhile to fix.
(Aside: this is the first time I have seen someone on Windows wanting to use Unix folder names to install applications... )

**Comment by TessHull** [comment]
four years later and coming back to RawTherapee after a gap in photography,  I found this issue after a fresh install of RawTherapee wouldn't start.  I'd like to state that when installing programs in a non-C: location, I almost always use unix folder naming because that is my mental default.  I fell into this. If this is a known issue, please put a mention in the installer location chooser.

**Comment by BiscuitAtLinux** [comment]
> four years later and coming back to RawTherapee after a gap in photography, I found this issue after a fresh install of RawTherapee wouldn't start. I'd like to state that when installing programs in a non-C: location, I almost always use unix folder naming because that is my mental default. I fell into this. If this is a known issue, please put a mention in the installer location chooser.

You are not alone. I also hit this when verifying https://github.com/RawTherapee/RawTherapee/issues/7314. I like using `bin` for portable applications.
