### ISSUE TITLE
DCP dual-illuminant / Panasonic DC-S5

### ISSUE THREAD

**Issue by maxmoritz** [Beep6581/RawTherapee#5951]
Hi,

I've taken some time to shoot raw using my brand ne Panasonic DC-S5 to be used to create DCP in Rawtherapee.
According to https://rawpedia.rawtherapee.com/How_to_create_DCP_color_profiles I've shot two sets of raw, one during sunshine and another set StdA using a regular old light bulb. 

Each set includes three exposure bracketed raw files. 

Sunlight:
https://filebin.net/rpw5pblzw6902pjj

StdA:
https://www.swisstransfer.com/d/b086c609-d3c3-4860-9254-8b4f51f80f36

Enjoy.

**Comment by Beep6581** [comment]
Reopened due to wrong temp/tint when testing 63001c4. Check illuminant order and matrices.

**Comment by Barugon** [comment]
It looks like the DC-S5 needs an entry in `camconst.json`. If I copy the entry for DC-S1 and edit the model to be DC-S5 then it looks pretty good but I don't know what the actual values should be.

**Comment by Thanatomanic** [comment]
If @maxmoritz could reupload his shots, or if @Beep6581 can investigate, that would be helpful.

**Comment by maxmoritz** [comment]
Hi @Thanatomanic,

I've uploaded the files again:

StdA: https://www.swisstransfer.com/d/7f6b3ed4-476b-4777-82af-fe9adf35e2b5
Sunlight: https://www.swisstransfer.com/d/d566ec75-7205-4b28-b119-53fb83febd03

**Comment by iliasg** [comment]
> 
> 
> It looks like the DC-S5 needs an entry in `camconst.json`. If I copy the entry for DC-S1 and edit the model to be DC-S5 then it looks pretty good but I don't know what the actual values should be.

This is correct, (checked by converting to DNG ;)) .. Instead of copying the DC-S1 item .. just add add the dc-s5 in the model line .. 
`       "make_model": [ "Panasonic DC-S1", "Panasonic DC-S5" ],`

**Comment by Thanatomanic** [comment]
I tested some shots from the DC-S5 from various places and of various scenes (different lighting). I did not find any weird color behavior. @Beep6581 Not sure what you found, but the DCP now shipping with RT seems good.

**Comment by Thanatomanic** [comment]
Closing until further notice
