### ISSUE TITLE
DCP dual-illuminant / Fujifilm X-T4

### ISSUE THREAD

**Issue by maxmoritz** [Beep6581/RawTherapee#5952]
Hi,

I've taken some time to shoot raw using my X-T4 to be used to create DCP in Rawtherapee.
According to https://rawpedia.rawtherapee.com/How_to_create_DCP_color_profiles I've shot two sets of raw, one during sunshine and another set StdA using a regular old light bulb.

Each set includes three exposure bracketed raw files.

Sunlight:
https://www.swisstransfer.com/d/56bb4c9f-d6c4-4c33-b082-22ef30096401

StdA:
https://www.swisstransfer.com/d/66e6d5f0-c265-4584-8dc3-054ba8b7b4fb

Enjoy.

**Comment by Thanatomanic** [comment]
Confirmation that I have downloaded the files for further processing, thank you

**Comment by Thanatomanic** [comment]
@Beep6581 It's up to you if you want to do the processing. I have your script now and could also do it.

**Comment by Beep6581** [comment]
@Thanatomanic I'll do it.

**Comment by Thanatomanic** [comment]
In view of the delay, I have generated a DCP instead. @maxmoritz Would you be willing to test if this improves the color rendition of your X-T4 files?
[FUJIFILM X-T4.zip](https://github.com/Beep6581/RawTherapee/files/6696854/FUJIFILM.X-T4.zip)
Unpack, and load the DCP file from the Color Management tool
![image](https://user-images.githubusercontent.com/6567747/122985946-0dd11880-d39f-11eb-8631-87aeb1ff363b.png)
