### ISSUE TITLE
Log report (Associated with bug (#5947))

### ISSUE THREAD

**Issue by rhlinden** [Beep6581/RawTherapee#5953]
Folow procedure in page 
http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports#Step_by_step

Output log file
[log.txt](https://github.com/Beep6581/RawTherapee/files/5374621/log.txt)

\AppData\Local\RawTherapee\options (with txt extention due to limitation of github)
[options.txt](https://github.com/Beep6581/RawTherapee/files/5374658/options.txt)

List of files in C:\BIN\RawTherapee\5.8 path
[files.txt](https://github.com/Beep6581/RawTherapee/files/5374667/files.txt)

This files are associated with bug #5947

**Comment by Thanatomanic** [comment]
This should have been posted directly to #5947
