### ISSUE TITLE
Local adjustments tab vs. hand icon

### ISSUE THREAD

**Issue by Floessie** [Beep6581/RawTherapee#5957]
Salut,

When selecting the local adjustments tab, the hand tool icon above the image turns into a crosshairs icon. Is that expected?

![screenshot1](https://user-images.githubusercontent.com/10133457/96616403-cf142b80-1302-11eb-93c5-9a20c50d055b.jpg)

![screenshot2](https://user-images.githubusercontent.com/10133457/96616420-d804fd00-1302-11eb-854d-f7dda9053457.jpg)

Best,
Flössie

**Comment by Pandagrapher** [comment]
@Floessie 
Locallab GUI is based on `EditWidgets` mechanism (so as `Gradient` tool I believe) which activates this icon when overlay widgets are shown. So, when spot widgets appear (i.e. when Locallab tool is selected), the crosshairs icon is displayed.

Normally, the activated button is used to hide overlay widget clicking on it. But, as with Locallab it is automatically managed according to tab selection, this button has no effect on purpose with Locallab (it is just an indicator that overlay widgets are shown).

Best,
Pierre

**Comment by Floessie** [comment]
@Pandagrapher Pierre, merci beaucoup. So this is known and expected. Closing.
