### ISSUE TITLE
How can I color calibrate the gamma of my laptop screen using the ICC Profile Creator?

### ISSUE THREAD

**Issue by gaveitatry02** [Beep6581/RawTherapee#5959]
I was using Windows 10 - Color Management to change the gamma of my laptop screen.  It worked.  The problem is that the Color Management tool uses a slider instead of exact numbers.  So, if I want to finetune it and make a small adjustment, I can't.  I was using the up and down buttons on my keyboard to move the slider, but I don't think this yields dependable results.  So that's why I started searching online for an alternative tool.

I found your ICC Profile Creator, and wanted to give it a try.  I opened it up, changed the gamma to a random number (1.40) and then saved it as an ICC profile.  I then opened up that ICC profile in the Color Management tool and set it as default, but nothing happened.  I did a few more experiements, selecting random things from the ICC Profile Creator dropdown menus, e.g. - sRGB as Primary, but still did not work.  No change whatsoever from the my laptop's default ICC profile and the one I downloaded from the ICC Profile Creator.

Please help.

**Comment by Thanatomanic** [comment]
I'm sorry, but you don't seem to understand the purpose of the ICC profile creator or what color managing your desktop means. If you want to know more, please see the https://pixls.us forum and ask around to help get yourself educated.

**Comment by gaveitatry02** [comment]
Geez, what an effin retard.  Why are you even on this Github?

**Comment by gaveitatry02** [comment]
Oh yeah, I wanted to say that you are a stinkin n66r that doesn't know how to talk to people.  Go k yourself man.  If you ever fcking talked to someone like that in real life, they would smash your face in.  All your "sorry" and "pleases" can't disguise your f'd up attitude.  Hope you get AIDS and die.
