### ISSUE TITLE
RTv2_Medium.icc and RTv4_Medium.icc TRC's do not match

### ISSUE THREAD

**Issue by Thanatomanic** [Beep6581/RawTherapee#5962]
The ICC v2 'Medium' profile that we ship has a simple gamma encoding with an exponent of 2.2, whereas the ICC v4 profile has an sRGB function (like all the other profiles). @Desmis Any thoughts about why this is different?

Screenshot of the v2 profile in ICC Profile Inspector
![image](https://user-images.githubusercontent.com/6567747/96870393-22a48780-1471-11eb-82be-381bf6105d2b.png)

Screenshot of the v4 profile in ICC Profile Inspector
![image](https://user-images.githubusercontent.com/6567747/96870493-4667cd80-1471-11eb-97cc-00d20d6bd3e8.png)

**Comment by Desmis** [comment]
@Thanatomanic 

Probably a mistake when I made the profile package. Very easy to change.
I suggest that you make this change with "ICC profile creator", but if you want me to change it, no problem.

jacques

**Comment by TechXavAL** [comment]
And when this problem is dealt with, wouldn't it be a good idea changing all the profiles not being sRGB and set in each of them the appropriate gamma, according to standards?

**Comment by Thanatomanic** [comment]
@TechXavAL That is another discussion we can have.

For now, closing with https://github.com/Beep6581/RawTherapee/commit/19ecd8e81dec3606e858f065541b9372af3ae227
