### ISSUE TITLE
new Chinese(Simplified) translation for RT 5.8

### ISSUE THREAD

**Issue by syyrmb** [Beep6581/RawTherapee#5963]
[Chinese (Simplified).zip](https://github.com/Beep6581/RawTherapee/files/5432356/Chinese.Simplified.zip)

    I made a Chinese(Simplified) translation based on the old one included in RT 5.8. 
    Most tools' name in the processing panel are translated (except those in the Advanced tab), however I haven't translate many tool-tips.
    Wording consistency is improved, many mistranslations are also corrected.

**Comment by Beep6581** [comment]
Thank you @syyrmb

I fixed some trailing whitespace and a broken line (MEDIAN_TYPE_TOOLTIP).

I also deleted the untranslated strings pending a review of `default`. Wait with further translation until `default` has been reviewed, else some translations might be wrong or lost. You will know when the review is complete by keeping an eye on issue #5984.
