### ISSUE TITLE
Warnings on compilation of dev build

### ISSUE THREAD

**Issue by TechXavAL** [Beep6581/RawTherapee#5965]
I've had a bunch of warnings when compiling the latest dev build:

Linux Mint 20
RT5.8dev commit: f9e8fb412
Clean compilation (that is, source-code and older compilation folders deleted)
Using the auto-script, set to compile the dev branch

This is the configuration part:

> -- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_BUILD_TYPE: release
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'gtk+-3.0>=3.16'
--   Found gtk+-3.0, version 3.24.20
-- Checking for module 'gtkmm-3.0>=3.16'
--   Found gtkmm-3.0, version 3.24.2
-- Checking for module 'glib-2.0>=2.44'
--   Found glib-2.0, version 2.64.3
-- Checking for module 'glibmm-2.4>=2.44'
--   Found glibmm-2.4, version 2.64.2
-- Checking for module 'cairomm-1.0'
--   Found cairomm-1.0, version 1.12.2
-- Checking for module 'gio-2.0>=2.44'
--   Found gio-2.0, version 2.64.3
-- Checking for module 'giomm-2.4>=2.44'
--   Found giomm-2.4, version 2.64.2
-- Checking for module 'gthread-2.0>=2.44'
--   Found gthread-2.0, version 2.64.3
-- Checking for module 'gobject-2.0>=2.44'
--   Found gobject-2.0, version 2.64.3
-- Checking for module 'sigc++-2.0>=2.3.1'
--   Found sigc++-2.0, version 2.10.2
-- Checking for module 'lensfun>=0.2'
--   Found lensfun, version 0.3.2.0
-- Checking for module 'librsvg-2.0>=2.40'
--   Found librsvg-2.0, version 2.48.7
-- Checking for module 'lcms2>=2.6'
--   Found lcms2, version 2.9
-- Checking for module 'expat>=2.1'
--   Found expat, version 2.2.9
-- Checking for module 'fftw3f'
--   Found fftw3f, version 3.3.8
-- Checking for module 'libiptcdata'
--   Found libiptcdata, version 1.0.5
-- Checking for module 'libtiff-4>=4.0.4'
--   Found libtiff-4, version 4.1.0
-- Found JPEG: /usr/lib/x86_64-linux-gnu/libjpeg.so (found version "80") 
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Found PNG: /usr/lib/x86_64-linux-gnu/libpng.so (found version "1.6.37") 
-- Checking for module 'libcanberra-gtk3'
--   Found libcanberra-gtk3, version 0.30
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Performing Test _fftw3f_multithread
-- Performing Test _fftw3f_multithread - Failed
-- Performing Test LENSFUN_HAS_LOAD_DIRECTORY
-- Performing Test LENSFUN_HAS_LOAD_DIRECTORY - Success

The building process goes without problems, but when the linking starts I get this (I have edited my local path and changed it by `~`):

> [100%] Linking CXX executable rawtherapee
In function ‘memcpy’,
    inlined from ‘fread’ at ~/software-dev/sourcecode-rawtherapee/rtengine/myfile.h:130:16,
    inlined from ‘parse_makernote’ at ~/software-dev/sourcecode-rawtherapee/rtengine/dcraw.cc:5624:13:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:34:33: warning: ‘__builtin___memcpy_chk’ specified size between 18446744071562067968 and 18446744073709551615 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]
   34 |   return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
      |                                 ^
~/software-dev/sourcecode-rawtherapee/rtengine/dcraw.cc: In member function ‘nikon_yuv_load_raw’:
~/software-dev/sourcecode-rawtherapee/rtengine/dcraw.cc:1412:33: warning: ‘yuv[3]’ may be used uninitialized in this function [-Wmaybe-uninitialized]
 1412 |       rgb[0] = yuv[b] + 1.370705*yuv[3];
      |                                 ^
~/software-dev/sourcecode-rawtherapee/rtengine/dcraw.cc:1402:17: note: ‘yuv[3]’ was declared here
 1402 |   int row, col, yuv[4], rgb[3], b, c;
      |                 ^
~/software-dev/sourcecode-rawtherapee/rtengine/dcraw.cc:1413:33: warning: ‘yuv[2]’ may be used uninitialized in this function [-Wmaybe-uninitialized]
 1413 |       rgb[1] = yuv[b] - 0.337633*yuv[2] - 0.698001*yuv[3];
      |                                 ^
~/software-dev/sourcecode-rawtherapee/rtengine/dcraw.cc:1402:17: note: ‘yuv[2]’ was declared here
 1402 |   int row, col, yuv[4], rgb[3], b, c;
      |                 ^
~/software-dev/sourcecode-rawtherapee/rtengine/imageio.cc: In member function ‘getAutoMatchedToneCurve’:
~/software-dev/sourcecode-rawtherapee/rtengine/histmatching.cc:296:105: warning: ‘h’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  296 |                 std::cout << "histogram matching: the embedded thumbnail is too small: " << w << "x" << h << std::endl;
      |                                                                                                         ^
~/software-dev/sourcecode-rawtherapee/rtengine/histmatching.cc:282:16: note: ‘h’ was declared here
  282 |         int w, h;
      |                ^
~/software-dev/sourcecode-rawtherapee/rtengine/histmatching.cc:291:22: warning: ‘w’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  291 |         } else if (w * 33 < fw || w * h < 19200) {
      |                      ^
~/software-dev/sourcecode-rawtherapee/rtengine/histmatching.cc:282:13: note: ‘w’ was declared here
  282 |         int w, h;
      |             ^
[100%] Built target rth-cli
~/software-dev/sourcecode-rawtherapee/rtengine/dcraw.cc: In member function ‘nikon_yuv_load_raw’:
~/software-dev/sourcecode-rawtherapee/rtengine/dcraw.cc:1412:33: warning: ‘yuv[3]’ may be used uninitialized in this function [-Wmaybe-uninitialized]
 1412 |       rgb[0] = yuv[b] + 1.370705*yuv[3];
      |                                 ^
~/software-dev/sourcecode-rawtherapee/rtengine/dcraw.cc:1402:17: note: ‘yuv[3]’ was declared here
 1402 |   int row, col, yuv[4], rgb[3], b, c;
      |                 ^
~/software-dev/sourcecode-rawtherapee/rtengine/dcraw.cc:1413:33: warning: ‘yuv[2]’ may be used uninitialized in this function [-Wmaybe-uninitialized]
 1413 |       rgb[1] = yuv[b] - 0.337633*yuv[2] - 0.698001*yuv[3];
      |                                 ^
~/software-dev/sourcecode-rawtherapee/rtengine/dcraw.cc:1402:17: note: ‘yuv[2]’ was declared here
 1402 |   int row, col, yuv[4], rgb[3], b, c;
      |                 ^
[100%] Built target rth

RawTherapee gets fully compiled and it seems to work well, but the linking process takes around 5mins, when it usually took 30sec or so.

**Comment by heckflosse** [comment]
> but the linking process takes around 5mins, when it usually took 30sec or so

Did you make a debug build?

**Comment by TechXavAL** [comment]
No, standard compilation. Same as many times before, but this time with warnings.

It seems that when those warnings appear, the process keeps trying something on my machine until it does it, or until it takes it as not possible. But no message about what happens, though.

**Comment by heckflosse** [comment]
@TechXavAL Do you use LTO in your latest build?

**Comment by TechXavAL** [comment]
Yes, I do:

> cmake \
>     -DCMAKE_BUILD_TYPE="$buildType"  \
>     -DCACHE_NAME_SUFFIX="5-$master" \
>     -DPROC_TARGET_NUMBER="2" \
>     -DBUILD_BUNDLE="ON" \
>     -DBUNDLE_BASE_INSTALL_DIR="${installDir}" \
>     -DOPTION_OMP="ON" \
>     -DWITH_LTO="ON" \
>     -DWITH_PROF="OFF" \
>     -DWITH_SAN="OFF" \
>     -DWITH_SYSTEM_KLT="OFF" \
>     -DWITH_BENCHMARK="OFF" \

**Comment by heckflosse** [comment]
That explaines the long link time

**Comment by TechXavAL** [comment]
You're right.

I've turned off that option, recompiled and everything goes smoothly, without warnings.

I think it has been a mistake on my part, so you may close this issue if you think it's _«fixed»_

Thanks

**Comment by heckflosse** [comment]
I will let the issue open for a while. Perhaps someone can fix the warnings. I can not, because LTO is not supported on Windows.

**Comment by Floessie** [comment]
I'll have a look.
