### ISSUE TITLE
Extreme values in Log Encoding causes crash

### ISSUE THREAD

**Issue by Lawrence37** [Beep6581/RawTherapee#5967]
After enabling Log Encoding in local adjustments and setting the White Ev to 0.1, RawTherapee crashes. The release build terminates with a segmentation fault and the debug build produces this message:
```
rtengine/iplocallab.cc:1707: void rtengine::ImProcFunctions::log_encode(rtengine::Imagefloat*, const rtengine::local_params&, bool, int, int): Assertion `std::isfinite(f)' failed.
```

`f` is `inf` due to math with very large numbers.

**Comment by Desmis** [comment]
I cannot reproduce, could you furnish raw and pp3

Thank you

jacques

**Comment by Desmis** [comment]
I think I have found one case where probably must be a crash, when 
dynamic_range = lp.whiteev - lp.blackev is too low and leads to divide near zero

I push a change :)

jacques

**Comment by Lawrence37** [comment]
Amsterdam.pef starting with the neutral profile causes a crash. Every image I tried caused a crash too. I will try the latest change to see if the problem is still there.

**Comment by Lawrence37** [comment]
I can still crash RT with White Ev = 0.5, Black Ev = -16, and Target gray point = 10.
[amsterdam.pef.pp3.txt](https://github.com/Beep6581/RawTherapee/files/5440426/amsterdam.pef.pp3.txt)

**Comment by Desmis** [comment]
@Lawrence37 

With the last commit, I hope the crash is always fixed

commit 445505a

jacques

**Comment by Lawrence37** [comment]
Hi @Desmis. Sorry to bother you again. I can crash RT with the following:
Black Ev = -16
White EV = 1
Value = 1
Target gray point = 5
Logarithm base = 1.3
[amsterdam.pef.pp3.txt](https://github.com/Beep6581/RawTherapee/files/5447311/amsterdam.pef.pp3.txt)

I admit no one is likely to use such an extreme combination, but it can happen accidentally. Is it reasonable to clamp the values instead of using asserts?
https://github.com/Beep6581/RawTherapee/blob/784be4a5e84794886fbdcad7eb2f42b02f2ad4b3/rtengine/iplocallab.cc#L1713-L1719

**Comment by Lawrence37** [comment]
Hi @Desmis. Sorry to bother you again. I can crash RT with the following:
Black Ev = -16
White EV = 1
Value = 1
Target gray point = 5
Logarithm base = 1.3
[amsterdam.pef.pp3.txt](https://github.com/Beep6581/RawTherapee/files/5447311/amsterdam.pef.pp3.txt)

I admit no one is likely to use such an extreme combination, but it can happen accidentally. Is it reasonable to clamp the values instead of using asserts?
https://github.com/Beep6581/RawTherapee/blob/784be4a5e84794886fbdcad7eb2f42b02f2ad4b3/rtengine/iplocallab.cc#L1713-L1719

**Comment by Desmis** [comment]
I took the code from ART...from Darktable

The only point which change is the size of the spot... and in some cases crash because the range light is bad....(its the case by default with Amsterdam...)
I think in some cases, that can append in ART or Darktable

I change a little some parameters to avoid that... In fact no importance all images have more than 1 Ev....

I push this small changes

Thanks for testings :)


jacques

**Comment by Desmis** [comment]
As you prposed, I clamp various values...
In addition to avoiding crashes, the results are better (in some cases)  :)

Jacques

**Comment by Lawrence37** [comment]
Interestingly, ART release build doesn't segfault.

With the most recent change, Log Encoding no longer crashes RT no matter how hard I try. Closing this issue.
