### ISSUE TITLE
Gtk::Grid::attach_to_next gives compilation error with gtkmm 3.22

### ISSUE THREAD

**Issue by aferrero2707** [Beep6581/RawTherapee#5969]
The new code that ahs been recently introduced in the histogram panel gives a compilation error with gtkmm 3.22, which is the version I am using on CentOS7 for packaging the AppImages.

The compilation error is the following:
```
/sources/rtgui/histogrampanel.cc:655:85: error: no matching function for call to ‘Gtk::Grid::attach_next_to(HistogramRGBAreaVert&, HistogramArea&, Gtk::PositionType)’
         gfxGrid->attach_next_to(*histogramRGBAreaVert, *histogramArea, Gtk::POS_LEFT);
```
It is due to the fact that in gtkmm 3.22 the additional `width` and `height` parameters of the `attach_to_next` function do not have default values (see documentation [here](https://developer.gnome.org/gtkmm/3.22/classGtk_1_1Grid.html#ae42f1ae2fc23e16880c51438afa8fbcf)).

A simple fix would be to explicitly set the width and height to 1 in the function call. Would that be ok?

**Comment by Thanatomanic** [comment]
I guess that would be a very easy fix to keep compatibility. Go ahead 👍

**Comment by aferrero2707** [comment]
Ping @Beep6581 and @heckflosse to see if they would agree to commit the fix...

**Comment by Floessie** [comment]
@aferrero2707 I can reproduce the issue on Debian Stretch. I'll fix it on `dev`.
