### ISSUE TITLE
Possible enhancement for haze removal

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#5972]
I really like the haze removal tool not only to remove haze, but also for its effect on non hazy images.
But the normal mode often adds too much saturation while the luminance-mode often does the opposite (at least perceptual)

I propose to add a blend between both modes with a simple adjuster (0 to 100), where 0 means luminance-mode, 100 means normal mode and any value between 0 and 100 just does a blend between both modes.

I had a look at the code, and performance-wise this should be possible with very small (if at all) increase in processing time.

What do you think?

Here an example with current RT (left without haze removal, middle with haze removal in luminance mode, right with haze removal in normal mode). The idea is to replace the luminance checkbox by an adjuster to allow a blend between middle and right.
![grafik](https://user-images.githubusercontent.com/13733487/97445290-6560d680-192d-11eb-8d6d-3bfed7d12eb7.png)

**Comment by mbaz** [comment]
I think this is a great idea; I often avoid this tool because it adds so much saturation.

**Comment by Thanatomanic** [comment]
I seldomly use dehazing, but a blend seems like a good solution.

But what about your "poor man's dehaze"? Since that seems an either/or solution, could it be added as a checkbox? Like 'Offset dehaze'?

**Comment by heckflosse** [comment]
> But what about your "poor man's dehaze"

I still really like the "poor man's dehaze", but i'm still not sure how to put it in GUI...

**Comment by heckflosse** [comment]
I will try to make a `blend` PR tomorrow. Should be quite easy...

**Comment by heckflosse** [comment]
I create the `dehaze_blend` branch to allow testing.
It's not complete atm.

Todos:
backwards compatibility
Local adjustments
...

Processing time did not increase at my machine.
Memory usage is the same as before.
I replaced the `luminance` checkbox by a `Saturation` adjuster (feel free to suggest a better name).
At value 0 it behaves like the `luminance` mode, at value 100 it behave like the `normal` mode. All values between 0 and 100 just blend between the two modes.

**Comment by heckflosse** [comment]
I tried the dehaze-blend with a lot of files (not only hazy ones).
In my opinion it makes the dehaze tool much more easier to use.
Before, it was a kind of binary choice between luminance and standard mode.
Now it's much more flexible.

Just my 2 cents...

**Comment by heckflosse** [comment]
I just found a bug in my branch which causes strange output on full export. Searching...

**Comment by heckflosse** [comment]
> I just found a bug in my branch which causes strange output on full export. Searching...

That was a false alarm.
