### ISSUE TITLE
Local Adjustments Blur in inverse mode produces bad output

### ISSUE THREAD

**Issue by Lawrence37** [Beep6581/RawTherapee#5974]
There is some undesired interaction between the Gaussian blur and guided filter settings. It happens when Gaussian radius is set but the mode is guided filter, and vice versa.
![image](https://user-images.githubusercontent.com/45837045/97790743-6ccfec00-1b88-11eb-8d0e-654e2e48fb38.png)

To reproduce:
1. Start with neutral profile.
2. Enable Local Adjustments and add a spot with the Blur/Grain & Denoise tool.
3. Change the blur radius to 10, for example.
4. Change mode to Guided Filter.
5. Enable Inverse.
6. Zoom in and out and pan around.

Example PP3: [amsterdam.pef.pp3.txt](https://github.com/Beep6581/RawTherapee/files/5469900/amsterdam.pef.pp3.txt)

The exported image does not have the strange pattern, but it's dark (see the Navigator thumbnail) even though I don't expect a blur to have any effect on image lightness. The problem goes away when the radius for the current mode is set. In the example above, this means setting Soft radius greater than 0.

**Comment by Thanatomanic** [comment]
I can confirm that the lightness changes unexpectedly. Though, I don't see the strange patterns.

**Comment by Desmis** [comment]
I have push a fix - branch localguiblur

I did this (only for inverse)  by updating the variables through the GUI, resetting other instances than the current one to their default values

jacques

**Comment by Lawrence37** [comment]
I can confirm that the GUI changes work, but I found another way to reproduce the issue. Gaussian blur, radius set, inverse mode, chrominance only:
![image](https://user-images.githubusercontent.com/45837045/98483133-d1a7c980-21ba-11eb-8240-6e5ca09da37b.png)

Sometimes, the image gets darker, sometimes I see the pattern, and sometimes it looks like the screenshot above.

**Comment by Desmis** [comment]
@Lawrence37 

Thank you for testing :)

In fact 2 bugs...very old
1) the one you mentionned
2) another where blur (and all functions Blur, Guided Filter..) chroma was desabled ....

The pull-request solve (I hope) 
https://github.com/Beep6581/RawTherapee/pull/5989

Thank you again

Jacques

**Comment by Lawrence37** [comment]
@Desmis
The fix works, but there is a side-effect when FFT is used.
![image](https://user-images.githubusercontent.com/45837045/98583663-94564100-2279-11eb-9a76-33d2aa49f7fb.png)

**Comment by Desmis** [comment]
@Lawrence37 

Thank you for testing :)

I just merge the pull-request

I cannot reproduce.....

I use your histry message...to ty to reproduce :)

On your image , you don't use FFT...(standard mode)

Good night

Thank you again :)

Jacques

**Comment by Lawrence37** [comment]
The tooltip for the radius says FFT is used when radius > 30. The problem occurs when radius > 30 or when FFT is forced on in advanced mode. In some (random?) cases, everything works perfectly.

**Comment by Desmis** [comment]
@Lawrence37 

Yes I know :+1: 
But I  thought you might have left the advanced mode, and it might be a problem resetting variables.

I think, It is not due to FFT, because, now I can reproduce, even when I disabled FFT code...
This happens only in inverse mode... Curious...the code is the same...And It's random...

Thnak you again for testing

Jacques

**Comment by Desmis** [comment]
@Lawrence37 

I think, I have found the bug...
It's not, FFTW
It's not Blur
It's not Guided Filter...

It's only (old) bad code in "InverseBlurNoise_Local", the function call to use deltaE and transition...

I push the change

Jacques

**Comment by Lawrence37** [comment]
Works perfectly now. Thanks Jacques!

**Comment by Desmis** [comment]
@Lawrence37 

A good news :+1: 

Thank you

Jacques
