### ISSUE TITLE
Local Adjustments Exposure tool sometimes ignores settings

### ISSUE THREAD

**Issue by Lawrence37** [Beep6581/RawTherapee#5975]
This bug sometimes affects the preview and also the exported image. When Exposure compensation is not 0 and Laplacian threshold (in Contrast Attenuator) is 0 or 0.1, the adjustment region is darkened regardless of the settings. Here, I've set Exposure compensation to +1.5:

| Good output | Buggy output |
| - | - |
| ![image](https://user-images.githubusercontent.com/45837045/97791811-abb76f00-1b93-11eb-9201-9ca5b6b2e205.png) | ![image](https://user-images.githubusercontent.com/45837045/97791571-013e4c80-1b91-11eb-8d79-3264909f1462.png) |

Steps to reproduce:
1. Start with neutral profile.
2. Enable Local Adjustments and add a spot with the Dynamic Range & Exposure tool.
3. Set Exposure compensation to any value except 0.
4. Zoom in and out and pan around until the bug appears.

**Comment by Desmis** [comment]
@Lawrence37 

I cannot reconstituded...
I applied your settings....zoom in and out pan around....nothing

But because you have this behavior I have changed the way "exposure" and "Laplacian" work together for Laplacian's very low values.

Branch : laeexpos

jacques

**Comment by Thanatomanic** [comment]
@Lawrence37 FWIW I could also not reproduce on my machine.

**Comment by Lawrence37** [comment]
I narrowed down the problem to this part. `data_tmp` gets filled with `nan`s in some cases. Any ideas why this can happen?
https://github.com/Beep6581/RawTherapee/blob/444027fcf969f840d331af96215c622420951fa9/rtengine/iplocallab.cc#L3990-L3993

**Comment by Desmis** [comment]
@Thanatomanic  Thank you :)
@Lawrence37 



I never found 'nan', but I expect it can ...
The I add a process to change data_tmp with datain (of couse if isnan)

Commit e3123b

data_tmp are datas generates by Laplacian
Very difficult to find...when all works fine :)

Jacques

**Comment by Lawrence37** [comment]
Removing the nans certainly makes the results look better, but the preview may not match the output in some cases.

Maybe something is different with my build?
PP3: [amsterdam.pef.pp3.txt](https://github.com/Beep6581/RawTherapee/files/5504092/amsterdam.pef.pp3.txt)
FFTW version: 3.3.8
AboutThisBuild:
```
Version: 5.8-2640-gbebc315cf
Branch: dev
Commit: bebc315cf
Commit date: 2020-11-05
Compiler: cc 10.2.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.24.2
Lensfun: V0.3.2.0
Build type: release
Build flags:  -std=c++11 -march=native -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON
Build OS: Linux 5.9.3-arch1-1 x86_64
Build date: Sat, 07 Nov 2020 00:38:01 +0000 UTC
Build epoch: 1604709481
Build UUID: c0a7b8b7-472a-426c-8424-a92e2d935fac
```

**Comment by Desmis** [comment]
@Lawrence37 

The good news...is that we are in the good way :)  Thanks to @Thanatomanic 

The bad news, I don't know why !!!

But, I see I put probably a bad data in case of "nan"...I change to zero... to test :)

commit bceed0d1b  - branch 'laeexpos'

Jacques

**Comment by Lawrence37** [comment]
I think I found the problem. `dE` can become negative due to rounding error. This patch fixes the issue for me.
```diff
diff --git a/rtengine/iplocallab.cc b/rtengine/iplocallab.cc
index a6e46b53a..554d3cf65 100644
--- a/rtengine/iplocallab.cc
+++ b/rtengine/iplocallab.cc
@@ -275,14 +275,13 @@ void deltaEforLaplace(float *dE, const float lap, int bfw, int bfh, rtengine::La
     }

     const float ade = 1.f / (maxdE - maxC);
-    const float bde = -ade * maxC;

 #ifdef _OPENMP
     #pragma omp parallel for schedule(dynamic,16)
 #endif
     for (int y = 0; y < bfh; y++) {
         for (int x = 0; x < bfw; x++) {
-            dE[y * bfw + x] = dE[y * bfw + x] >= maxdE ? ade * dE[y * bfw + x] + bde : 1.f;
+            dE[y * bfw + x] = dE[y * bfw + x] >= maxdE ? ade * (dE[y * bfw + x] - maxC) : 1.f;
         }
     }
 }
```

**Comment by Desmis** [comment]
@Lawrence37 

Thank you very much to have found this curious behavior  :)

I tested this change on several images, no differences... But if it solves the bug, it's fine :)

I push this change to dev

Thank you again

Jacques

**Comment by Lawrence37** [comment]
I'm glad the issue is fixed without differences in output on your end. Thanks!
