### ISSUE TITLE
Making adjustments borks Pop profile

### ISSUE THREAD

**Issue by Barugon** [Beep6581/RawTherapee#5977]
If I select one of the Pop profiles and then make adjustments, it looks like it messes up the settings in CIECAM02.

Here is the photo loaded (default profile is Neutral).
![Screenshot from 2020-11-01 19-00-07](https://user-images.githubusercontent.com/16503728/97825855-b4cc3d00-1c74-11eb-8d19-94138e7dc64c.png)

Here I select the Pop 3 Skin profile.
![Screenshot from 2020-11-01 19-00-29](https://user-images.githubusercontent.com/16503728/97825876-c6154980-1c74-11eb-902e-3aa5c78ffceb.png)

Here is after I bump the exposure compensation by +0.05.
![Screenshot from 2020-11-01 19-03-36](https://user-images.githubusercontent.com/16503728/97825930-f826ab80-1c74-11eb-96c3-9baea45f5ef7.png)

Version: 5.8-2623-gaae90a0ad
Branch: dev
Commit: aae90a0ad
Commit date: 2020-10-27
Compiler: cc 10.2.1
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.24.2
Lensfun: V0.3.2.0
Build type: release
Build flags:  -std=c++11 -march=native -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -fopenmp -Werror=unknown-pragmas -O2 -DNDEBUG -ftree-vectorize
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON
Build OS: Linux 5.8.16-300.fc33.x86_64 x86_64
Build date: Tue, 27 Oct 2020 21:03:59 +0000 UTC
Build epoch: 1603832639
Build UUID: 1a3603da-19fe-438b-855b-f3b4665d5fd6

**Comment by Barugon** [comment]
This was built a couple days ago using the build-rawtherapee script.

**Comment by heckflosse** [comment]
@Barugon 
> Here is after I bump the exposure compensation by +0.05

You bumbed by +1.05

**Comment by heckflosse** [comment]
I confirm a bug

neutral + pop1
![grafik](https://user-images.githubusercontent.com/13733487/97863224-edb4f200-1d06-11eb-933a-b8685fec25c5.png)

disabled ciecam02
![grafik](https://user-images.githubusercontent.com/13733487/97863249-f73e5a00-1d06-11eb-9091-87f23cba86a5.png)

enabled ciecam02 again. Should look the same as the first screenshot
![grafik](https://user-images.githubusercontent.com/13733487/97863291-09b89380-1d07-11eb-9b50-5dad025d3740.png)

**Comment by Beep6581** [comment]
Confirmed in e94b981ec, regression.

**Comment by heckflosse** [comment]
I will bisect...

**Comment by heckflosse** [comment]
It's this commit 27c4c546ef31a455539a72cc1dd5dcd91fce25b6 which causes the issue.
@Desmis Jacques, any idea?

**Comment by heckflosse** [comment]
I guess I know how to fix it...

**Comment by Desmis** [comment]
@heckflosse 
The commit only work on GUI and does not change, algorithm or code....
If you want all the tools (as before) select "advanced"

In "standard " all settings "advanced" are set to default values....It's the same approach with wavelet levels, and with Local adjustments

jacques

**Comment by heckflosse** [comment]
@Desmis Jacques, the problem is, that in old .pp3 files there is no `complex` key. In this case we have to set `expert`.
I'm just trying that for `colorappearance`. Perhaps we have to do that as well for wavelets. Local adjustments need no change as there we do not need to be backwards compatible

**Comment by Desmis** [comment]
@heckflosse 

Yes we must do for wavelet...
I push a change now :)

Jacques

**Comment by heckflosse** [comment]
@Desmis Jacques, thank you for fixing it in wavelet :+1:

**Comment by Barugon** [comment]
This is working for me now. Thanks.
