### ISSUE TITLE
Preprocess White Balance tool sometimes disappears

### ISSUE THREAD

**Issue by reffort** [Beep6581/RawTherapee#5978]
Using dev-5.8-2629 10/30 AppImage:  After working with a JPEG file in the editor, and then switching to a raw file, the Preprocess White Balance tool no longer appears in the Raw tab (see attached screen capture).  If RT is shut down and restarted, Preprocess White Balance reappears.  

![nowbpp-1](https://user-images.githubusercontent.com/13387711/97914045-dda40f00-1d14-11eb-8b33-4367503ee664.png)

**Comment by rom9** [comment]
Ooops... :-D
Thanks! Nice catch, this was pretty bad. It should be fixed now in `dev`.

**Comment by reffort** [comment]
Works great! Thanks!

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
