### ISSUE TITLE
Local Adjustments: Disable Spot does not work with the Excluding Spot method

### ISSUE THREAD

**Issue by arturoisilvia** [Beep6581/RawTherapee#5980]
Hello!,
I have a black background:
![Captura1_cr](https://user-images.githubusercontent.com/55624244/98275960-91b3cd00-1f95-11eb-83d8-88ed13f2a1cf.JPG)

I want to exclude the flower:
![Captura2_cr](https://user-images.githubusercontent.com/55624244/98275984-9bd5cb80-1f95-11eb-9809-1e69c27f5e85.jpg)

But if I disable Spot, the background does not turn black. Should not?:
![Captura3_cr](https://user-images.githubusercontent.com/55624244/98276062-bad45d80-1f95-11eb-9137-7273fdd42d52.jpg)

Cheers!
Arturo.
Version: 5.8-2625-g6f7f41237 windows.

**Comment by Desmis** [comment]
@arturoisilvia 

Fixed in PR https://github.com/Beep6581/RawTherapee/pull/5981

jacques

**Comment by arturoisilvia** [comment]
Ok, thanks.
