### ISSUE TITLE
Panasonic Lumix DC-S5: color temperature and tint are incorrect

### ISSUE THREAD

**Issue by Barugon** [Beep6581/RawTherapee#5987]
The color temperature and tint are way off. This is the raw file as initially loading with Neutral as the default profile.

![Screenshot from 2020-11-08 01-18-58](https://user-images.githubusercontent.com/16503728/98461405-ae503080-2160-11eb-8a6c-9592ad7ec113.jpg)

Here's what happens if I set the white balance to daylight:

![Screenshot from 2020-11-08 01-29-28](https://user-images.githubusercontent.com/16503728/98461587-34b94200-2162-11eb-92fc-0b3b34fef6a9.jpg)

**Comment by Barugon** [comment]
Version: 5.8-2645-g9963d1f52
Branch: dev
Commit: 9963d1f52
Commit date: 2020-11-08
Compiler: cc 10.2.1
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.24.2
Lensfun: V0.3.2.0
Build type: release
Build flags:  -std=c++11 -march=native -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -fopenmp -Werror=unknown-pragmas -O2 -DNDEBUG -ftree-vectorize
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON
Build OS: Linux 5.8.18-300.fc33.x86_64 x86_64
Build date: Sun, 08 Nov 2020 08:55:53 +0000 UTC
Build epoch: 1604825753
Build UUID: 66ee044d-0673-4cdb-a656-659b2bc316d3

**Comment by ChasingShadows** [comment]
I think the Panasonic DC-S5 is not yet supported. In other words you need to follow the description for getting support for new cameras at http://rawpedia.rawtherapee.com/How_to_create_DCP_color_profiles

**Comment by Barugon** [comment]
@ChasingShadows 
https://github.com/Beep6581/RawTherapee/commit/63001c41a338f5e78adee0e8a21b3af52be2626c

**Comment by ChasingShadows** [comment]
The ticket #5951 mentioned by the above commit has been reopened because of errors in tint and color temperature...

**Comment by Barugon** [comment]
Can we just have the S5 do the same thing as the S1 (at least for now)?

**Comment by Barugon** [comment]
This has long since been resolved. Closing.
