### ISSUE TITLE
Denoise does not work properly on Fuji x-trans raw files

### ISSUE THREAD

**Issue by okwes** [Beep6581/RawTherapee#5988]
Denoise does not work properly on Fuji x-trans files at least from the x-t3 and causes colors to be oddly desaturated and mixed often yielding in unusable results. This does not occur if denoise is applied to the exported image only when working with the raw. 

### Step to produce
1. Enable noise reduction on xtrans file, this issue occurs regardless of any prior edits to the photo and will occur if set to neutral or not 
### System info
`Linux wtopdevice 4.15.0-122-generic #124-Ubuntu SMP Thu Oct 15 13:03:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
### Exported photo 100% center view without noise reduction
![DSCF6354crop](https://user-images.githubusercontent.com/22987969/98506066-b378b280-2228-11eb-8546-0e9925642c67.png)
### Exported photo 100% center view with noise reduction, default settings used for noise reduction
![DSCF6354denoisedrawcrop](https://user-images.githubusercontent.com/22987969/98506055-aeb3fe80-2228-11eb-9cbf-f058eda6b2a1.png)

Notice how the orange looses much of its color and how some of the orange gets blended with the trees without leaves. This issues occurs with all my raw files from my x-t3 and the bug exists in both the current release and the dev builds, tested on build 2629.

raw file and pp3: https://drive.google.com/drive/folders/1gcOEDyP-06_0Z-0NNkoYrt3oQeJpMURf?usp=sharing

Thank you guys so much for such a great raw developer! :)

**Comment by ff2000** [comment]
NR desaturating the image is not limited to xtrans files.
Here an example from my Panasonic G81:
![Screenshot_20201113_075152](https://user-images.githubusercontent.com/1973708/99034245-688ed000-2585-11eb-835a-1f0f38bf8c63.jpg)
AFAIR this was discussed already in the past, but I can't find it ATM.
There was a solution proposed with a GMIC filter.

**Comment by okwes** [comment]
Thanks, hmmm that's interesting that it desaturates so much for all the raw files. The way I tested it to make sure it was my camera was to export a the image and then apply the noise reduction after and compare it to when applied to the raw. I guess this was wrong as I assumed applying it to the jpeg or whatever would be the same the other raw formats instead instead the inverse is true.

![out](https://user-images.githubusercontent.com/22987969/99083471-99760180-2593-11eb-904b-faf738e8b4ec.gif)
For context both images in this gif have denoise applied, one is just applied to the exported image instead of the raw

Should I just close this issue or is there an actual reason or bug here because it process the jpeg so differently from the raws
