### ISSUE TITLE
Windows 10: RT can not be pinned to the start menu and is not found in search results

### ISSUE THREAD

**Issue by rebio** [Beep6581/RawTherapee#5990]
Version: 5.8; Branch: releases; System: Windows, Windows 10; Bit depth: 64 bits

----
**1)**
I can not pin RT to the start menu in Windows 10 with _right click_ + _pin to startmenu_ . I also can not drag&drop the application from the install folder into the start menu.

**2)**
When I search for RT in the start menu search RT is not displayed unless you tipe "rawtherapee". So eg. just "raw" will not show it.

I would say this is not so the fault of RT and can be fixed easily. The solution is to just copy a shortcut to the exe-file into the folder `%AppData%\Microsoft\Windows\Start Menu\Programs`

When the folder contains the shortcut, RT can be found in the start menu search when just "ra" is typed in. Right click to pin it to the start menu also works.

See also: https://superuser.com/questions/947985/cant-pin-some-applications-to-start-menu-in-windows-10

**Comment by ChasingShadows** [comment]
I'm on Windows 10 as well. When I search for RT I just search for "ra" and it is found. And I have it pinned as well.

**Comment by Thanatomanic** [comment]
![image](https://user-images.githubusercontent.com/6567747/98648038-08eeb580-2336-11eb-93ce-f824b06f74d5.png)
I can also not reproduce.

There is an option during installation to create a Start Menu entry. If ticked, this creates a shortcut. It also shows up as a 'Recently added'. There is nothing else to do, sorry.

![image](https://user-images.githubusercontent.com/6567747/98648482-a4802600-2336-11eb-9e70-ab00597962b7.png)
