### ISSUE TITLE
(RT development) Haze removal: Luminance only option is gone?

### ISSUE THREAD

**Issue by ghost** [Beep6581/RawTherapee#5993]
**QUESTION**

I just noticed that the _Luminance only_ option is no longer available in the *Haze removal* module.

Is there a specific reason for this? I looked, but am not able to find anything.

I'm still a relatively new rawtherapee user, but I have used it already in my edits.

Maybe this is relevant:

* RawTherapee : version 5.8-2658-gaa0a7e473
* OS               : Linux (kernel 5.8.10-1)
* Distro           : Debian Buster (rel. 10.6)
* Self compiled : Yes.

**Comment by Floessie** [comment]
@jade-nl See #5972.

HTH,
Flössie

**Comment by ghost** [comment]
Ah, that explains it! Thanks.

And it also establishes that I'm not getting senile: I thought I noticed a bit less saturation when I used it.... Good job for as far as I can tell.

My search-foo does need some work I guess.....

Anyway, closing this one.
