### ISSUE TITLE
Nightly Dev Builds for Windows not being updated.

### ISSUE THREAD

**Issue by RichardRegal** [Beep6581/RawTherapee#6000]
https://github.com/Beep6581/RawTherapee/releases/tag/nightly is not updating the Windows builds again.

**Comment by Thanatomanic** [comment]
Ping @aferrero2707

**Comment by aferrero2707** [comment]
@Thanatomanic @RichardRegal there is an issue with package signatures that I need to investigate. I will let you know when I manage to solve it.

**Comment by RichardRegal** [comment]
@aferrero2707 Thanks.

**Comment by RichardRegal** [comment]
@aferrero2707 Any News?

**Comment by gaaned92** [comment]
@RichardRegal In the meantime until @aferrero2707 can solve the issue, you can find W10 Rawtherapee nightly builds here https://keybase.pub/gaaned92/RTW64NightlyBuilds/

Be aware to choose an architecture compatible with your processor
generic for all processors (the less optimized), skylake for skylake intel processors and above, znvver2 for ryzen2 processors and icelake for recent intel microarchitecture.

**Comment by RichardRegal** [comment]
@gaaned92 Thanks. Given that I have a Xeon E3 1245 v3 the generic is the one I went for.

**Comment by aferrero2707** [comment]
I'm on it, but look harder than I initially thought...

**Comment by gaaned92** [comment]
Given that I have a Xeon E3 1245 v3 has a Haswell architecture. Did you try the skylake build?
Going to build a haswell build. Done
you can download RawTherapee_dev_5.8-2669-g548f2103e_W64_haswell_201203.7z

**Comment by RichardRegal** [comment]
@gaaned92 I didn’t bother trying the Skylake as the generic works well enough. I was not asking for a special build, but I do appreciate your having made one.

**Comment by gaaned92** [comment]
It's just a matter of optimization. The specific builds can optimize further with the use of additional instruction sets.
Though there is provision for that in RT I never made benchmark.

**Comment by heckflosse** [comment]
native builds for my CPU (AMD FX8350) are roughly 10% faster than generic builds

**Comment by michaelezra** [comment]
Which build would be most suitable for Sandy Bridge E i7 3930K CPU?

**Comment by gaaned92** [comment]
Sandy bridge is still older than haswell.  The best is to try the skylake build, if it fails the haswell build then the generic build. 
It's not a pain to build for specific architecture, but I fear to multiply the builds as it will become difficult to manage.
generic build is based on a X86-64 architecture which includes no instruction extension. Perhaps I should replace generic build by a Sandy bridge build:
- it is sufficiently old to be compatible with almost all PC used for photo
- it includes the main instruction sets MMX, SSE, SSE2, SSE3, SSSE3, SSE4.1, SSE4.2, POPCNT, AVX, AES and PCLMUL

**Comment by michaelezra** [comment]
that would be great:)!!!

**Comment by heckflosse** [comment]
@michaelezra Hi Michael, great to see you posting here :+1: Hope you're well.

As in past (when you compiled RT yourself), it's still no miracle to build RT on windows ;-) Making a native build will give you the best performance.

Ingo

**Comment by michaelezra** [comment]
Hi Ingo!:) thank you, hope you are well as well. 

What a great team we have here, miss you guys. Sorry I could not contribute for the past few years. 
I should try to make the native build, that's a great idea:)

Michael

**Comment by aferrero2707** [comment]
@gaaned92 @heckflosse @Beep6581 I have managed to fix the issues with the automated windows builds, but I am now forced to compile RT with lensfun 3.95 and upgrade the database version from 1 to 2.

Could you remind me what is the appropriate install location for the lensfun DB in the windows case?

**Comment by Thanatomanic** [comment]
Doesn't the change to lensfun 3.95 completely break profiled lens detection?

After installation my lensfun directory resides in `C:\Program Files\RawTherapee\5.8\share\lensfun\` which contains up to date xml files. That has a `version_1` folder as well, but that seem to contain very old files (2015).

**Comment by aferrero2707** [comment]
I can still use 0.3.2, but in that case I need to compile it from sources in order to run the `lensfun-update-data` script. Not a big issue if needed...

**Comment by gaaned92** [comment]
I use -DLENSFUNDBDIR=./share/lensfun to put the DB in that location.
I build myself  lensfun. I am now at master_v0.3.95-633-g3baedcb7
I have a version 2 and I don't think something is broken but perhaps some testing should be done. 

v0.3.2 is so old that I think it's time to upgrade.

**Comment by Beep6581** [comment]
> Could you remind me what is the appropriate install location for the lensfun DB in the windows case?

Hi @aferrero2707 , I don't know, the distro I'm currently using (Sabayon) only ships 0.3.2 from November 2015, which uses DB version 1.
https://github.com/lensfun/lensfun/tags

**Comment by aferrero2707** [comment]
Ok, so I think that the takeaway message is that it is still wiser to stick to 0.3.2, and run some tests to see if DB version 2 works fine.

I might try to provide an appimage with lensfun 0.3.95, if that could help...

**Comment by aferrero2707** [comment]
@RichardRegal @gaaned92 a new Win64 automated build is finally available again! Could you please give it a try and let me know if there are issues?

Thanks!

**Comment by RichardRegal** [comment]
@aferrero2707 Downloaded and working for me. Thanks.

**Comment by gaaned92** [comment]
@aferrero2707  It's working ok. Thanks

**Comment by RichardRegal** [comment]
@aferrero2707 Last night’s update didn’t I’m afraid.

**Comment by gaaned92** [comment]
Here, last update RawTherapee_dev_5.8-2672-g37f406627_20201212 works.
@RichardRegal could you be more specific about the issue?

**Comment by arturoisilvia** [comment]
win64.zip works fine for me:
RawTherapee_dev_5.8-2672-g37f406627_20201212_win64.zip

**Comment by afr-e** [comment]
Latest works for me too

**Comment by RichardRegal** [comment]
@aferrero2707 There was a period when 2672 for Linux was on the site but the latest Windows version was still 2671. However that has since been corrected.

**Comment by gaaned92** [comment]
Perhaps @RichardRegal if it is OK, you can close the issue

**Comment by RichardRegal** [comment]
Closing the issue now.
