### ISSUE TITLE
Exported image does not have edits

### ISSUE THREAD

**Issue by KLHN** [Beep6581/RawTherapee#6006]
Version: 5.8
Branch: releases
Commit: 9a9e0acbf
Commit date: 2020-02-04
Compiler: x86_64-w64-mingw32-gcc\ 8.2.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.24.2
Lensfun: V0.3.2.0
Build type: Release
Build flags: -mwin32\ -m64\ -mthreads\ -msse2\ -std=c++11\ -mtune=generic\ -Werror=unused-label\ -Werror=delete-incomplete\ -Wall\ -Wuninitialized\ -Wcast-qual\ -Wno-deprecated-declarations\ -Wno-unused-result\ -fopenmp\ -Werror=unknown-pragmas\ -Wno-aggressive-loop-optimizations\ -DNDEBUG\ -O3\ -ftree-vectorize
Link flags: -m64\ -mthreads\ -static-libgcc\ -mtune=generic\ -s\ -O3
OpenMP support: ON
MMAP support: ON

WINDOWS 10 Pro
Intel Core i5-8500 CPU @3.00GHz 
32.0 GB RAM
64 Bit Operating x64 based processor

Steps to reproduce: 
Image is microscopic scalar with no embedded profiles 8bit
Neutral profile to start, then advanced settings 
Process: ALL LEVELS ALL DIRECTIONS
Wavelet levels modified
Contrast
Denoise and Refine
Edge Sharpness
Residual Image
Final Touch up

All steps are not required to reproduce problem- just any wavelet transforms applied
 Export image by quick export or queue 
Image appears grainy and like partially processed. 
Also appears grainy with excess noise when opened in PS directly out of RT
The problem persists despite changing export settings, file type, profiles etc.. 
![RT error](https://user-images.githubusercontent.com/74974161/100112260-082d4780-2e3d-11eb-9b9b-01875e6c7551.JPG)
![RT error zoomed](https://user-images.githubusercontent.com/74974161/100112281-0ebbbf00-2e3d-11eb-9a99-bb9f85086f08.JPG)

**Comment by Thanatomanic** [comment]
@KLHN Thanks for also reporting here. I already mentioned this on Pixls, but you should be comparing at 100% zoom level. The Wavelet tool only gives accurate previews in that situation (as indicated by the '1:1' icon in the module title).

**Comment by KLHN** [comment]
Ok well the issue appears to resolve when i run the development version of RT. 5.5-2652-g1bd22668f 

Happy to upload a 1:1 using the standard "stable release" if the issue needs to be further investigated with better examples. 

Will repost if it happens again on DV
