### ISSUE TITLE
Feature Request: Ability to turn the tooltips ON/OFF

### ISSUE THREAD

**Issue by ghost** [Beep6581/RawTherapee#6007]
A way to turn on/off the tooltips would be rather nice to have.

First of all: I do really like the tooltips, but... At the moment it is too much of a good thing, to be honest, and gets in the way of the more important stuff (sliders, info, etc).

Although I'm not a developer and don't know the technical implications I see 2 ways this could be implemented: 

1. Using the preferences menu
2. Via a keyboard shortcut

I would prefer to have a keyboard shortcut to do this. If I look at the way I use other software I really like to turn the tips on for a moment to refresh/update my memory and immediately after to turn it off again.

Also see this pixls discussion: [A way to turn off/on the tool tips?](https://discuss.pixls.us/t/a-way-to-turn-off-on-the-tool-tips/21456?u=jade_nl)

Might be linked to  #2221

**Comment by ff2000** [comment]
A better way might be to add a "?" icon in the tool's title bar that opens either a help panel or a help window that shows a detailed description of the tool (intention, way to use, ...) and all its sliders and how they interact. 

// edit:
Especially in Local Adjustments the titles unfortunately are quite long/descriptive, so an option to disable the "?" should be considered. Perhaps add [icon-size] pixels to the panel width if it is enabled. Also a shortcut to pop up the help for the tool under the mouse cursor could be good.

**Comment by ghost** [comment]
A clickable "?" icon would make sense to me.

No need to disable that, you need to actually click on it make the tooltip/help text appear, in which case it doesn't matter if there is elaborate/long info.

This is assuming that this can be implemented system wide in a relatively easy way.

I do believe that Morgan (@Beep6581) is toying with the idea to disable tooltips altogether: I'm not against that per se but at the moment there's info in the tooltips that is not on RawPedia ("the docs"). That needs to be straightened out before (if) the tooltips are going to be disabled altogether.

**Comment by ghost** [comment]
Closing this one.

The still open #2221 should also fix this one.
