### ISSUE TITLE
Local Adjustments: Inconsistency in Preview ΔE

### ISSUE THREAD

**Issue by ghost** [Beep6581/RawTherapee#6008]
The majority of the tools do not need any special action to make sure that the preview is shown when activating it. Clicking on the *Preview ΔE* will immediately show the preview. This is not the case for the following tools:

* Softlight & Original Retinex
* Dehaze & Retinex

You need to increase these tools' *strength* setting by one step to get the preview to actually show up.

I'm not sure if there is a reason why this is so, but I'm assuming that this is a bug. You want to be able to fine-tune the shape and its setting without any of the tool changes already being applied.

To reproduce:

1. Load an image,
2. Activate *Local Adjustments* and click *add*
3. Use *add tool to current spot...* to select *Dehaze & Retinex*
4. Click on *Preview ΔE* -> No preview visible
5. Increase Dehaze *Strength* by one step -> preview is visible
6. Delete the *Dehaze & Retinex* tool
7. Use *add tool to current spot...* to select *Color & Light*
8. Click on *Preview ΔE* -> Preview is immediately visible

The * Dehaze & Retinex* tool has another (linked?) issue: When only using *Retinex* and no changes are made to the Dehaze section, the preview doesn't work as expected when increasing Retinex's *Strength* setting. I'm not yet familiar with Retinex, so I'm not sure if the preview isn't shown at all or that artifacts are created.

**Comment by Desmis** [comment]
@jade-nl 

Thank you for testing :)

Retinex is strongly complex...and when I associated with Dehaze, this poses problems, not with algorithms, but precisely when you want to associate visualization functions. For example,  what seems simple, but is not, is previewdE.

PreviewdE was at origine, in each function "mask and modifications"..We ask me, to put outside, in "settings".. I understand perfectly the goal, but it is very complex in this case.

I will commit a "workaround", which should improve a little bit .
Now, with "Dehaze" alone, I think it works well
Indeed, If you enable "Retinex", the only way to make "previewde" work is by using  "Mask and modifications"

Retinex can create artifacts...in some cases...

Jacques

**Comment by ghost** [comment]
@Desmis 

Just pulled and rebuild RT.

-Fixed-
* The *Dehaze & Retinex* is satisfactory fixed for my taste. I already had a stab at the *Mask and modifications* option with the other tools. Just rechecked and that works nicely when one wants to use Retinex and see the Preview ΔE masking.

-Still Open-
* This leaves the similar *Softlight & Original Retinex* issue, which I assume is in the same realm as the Dehaze & Retinex when it comes to complexity. Both settings (*Softlight* or *Original Retinex*) need an increase in strength before the default green preview shows up. No strange behaviour on the Retinex front in this case though.

In general: Man, Local Adjustments is a powerful and very useful addition to RT. Thank you! (and possible others that helped to develop this one).

**Comment by Desmis** [comment]
@jade-nl 
I had forgotten "Soft Light and Original Retinex" ... probably the age ... Here no problem to solve this problem

I just push a commit

Just a remark, "Retinex Original"  here is completely different from "Retinex with Dehaze"...even if the goal is sometimes the same...adapt the image to the perception of our eyes and our brain

Thank you
Jacques

**Comment by ghost** [comment]
Pulled, rebuild and checked: All fixed.

Thanks for the speedy fix!
