### ISSUE TITLE
Where is code for detail window?

### ISSUE THREAD

**Issue by irthomasthomas** [Beep6581/RawTherapee#6010]
Hi,

I wanted to play with the code and create an option to have the detail window always open. As this is my first time dealing with the rt source code, I was hoping someone could point me in the right direction and tell me where to find the code for the detail window and gui elements?

Cheers

**Comment by heckflosse** [comment]
@irthomasthomas 
it's inside this file. Search for `decorated`. That's the detail window part
https://github.com/Beep6581/RawTherapee/blob/dev/rtgui/cropwindow.cc
