### ISSUE TITLE
ui components way too big to be normally used, and is not alterable

### ISSUE THREAD

**Issue by xade93** [Beep6581/RawTherapee#6011]
Version: 1:5.8-1
OS: Arch Linux Rolling Release
Reproduce: Just open the application.
![Screenshot from 2020-11-29 01-35-52](https://user-images.githubusercontent.com/24752033/100522092-40d57400-31e3-11eb-8388-5bcb5e88eaa6.png)
The problem, as you may see in the photo, is that the size of icons and ui components become way too big to be used normally. I searched the preference, I have "Pseudo Hi-DPi" option disabled, I tried enable it and restart, but nothing changed. Dragging the edges of the frames won't help also.
Tested with latest GNOME3 on Xorg and i3 desktop environment.
All other applications in my computer has correct component sizes and ratios.

Thanks.

**Comment by Thanatomanic** [comment]
I noticed this recently too for a fresh installation. If you go to Preferences and reduce the font size to 9 it should look much better.

**Comment by xade93** [comment]
> I noticed this recently too for a fresh installation. If you go to Preferences and reduce the font size to 9 it should look much better.

thanks, that worked like a charm. I shall try it before posting an issue.

However, just by the way, it would be so much better if the user can scale the thumbnail browser in File Browser, like by Ctrl+Wheel or some slidebar xD

thanks for the help!
