### ISSUE TITLE
Ciecam02 vectorized / non-vectorized code mixup?

### ISSUE THREAD

**Issue by Thanatomanic** [Beep6581/RawTherapee#6020]
@Desmis  After looking into your Ciecam02 code, I noticed this:
https://github.com/Beep6581/RawTherapee/blob/548f2103e2c84352b21fabb69e2f8e2ecfff0e55/rtengine/improcfun.cc#L1034-L1084
Are you sure this is doing the correct thing? First I see vectorized SSE code, but within the same `ifdef` block I also see non-vectorized code.

**Comment by Desmis** [comment]
@Thanatomanic 

This part of code (with SSE) is not mine, but from @heckflosse 
And I think, it's very old...
jacques

**Comment by heckflosse** [comment]
That's for the remaining pixels (k < width - 3) of the sse code

**Comment by Thanatomanic** [comment]
@heckflosse Thanks, my worry was unfounded 😄
