### ISSUE TITLE
Running on M1 with Rosetta 2?

### ISSUE THREAD

**Issue by strogonoff** [Beep6581/RawTherapee#6023]
This is just a question—did anyone try running RawTherapee on Apple hardware with M1 CPU?

I’m currently only planning on getting one and want to check which software I’ll be able to continue using.

I understand that a dedicated Apple silicon build is unlikely to happen so soon, so all I’m wondering is if it works under Rosetta 2.

**Comment by frgazor** [comment]
I only did a quick test with some adjustments and export and it works. And despite rosetta it's quite fast.

**Comment by heckflosse** [comment]
There are a some algorithms in RT, which make use of SSE code. For these I would expect to perform worse on M1 CPU. But in past, we coded more for compiler auto vectorization. If the compiler does a good job on this, I would expect good performance for M1 CPU. Unfortunately, atm, in my tests clang is much worse than gcc (at least on x86_64). Maybe clang is better on M1... Can't test

**Comment by strogonoff** [comment]
> There are a some algorithms in RT, which make use of SSE code. For these I would expect to perform worse on M1 CPU. But in past, we coded more for compiler auto vectorization. If the compiler does a good job on this, I would expect good performance for M1 CPU. Unfortunately, atm, in my tests clang is much worse than gcc (at least on x86_64). Maybe clang is better on M1... Can't test

(If it’ll help, I could help running tests on macOS/M1 a bit later in January)

**Comment by heckflosse** [comment]
@strogonoff 
> (If it’ll help, I could help running tests on macOS/M1 a bit later in January)

that would be great, especially native builds would be interesting :+1:

**Comment by strogonoff** [comment]
I can’t see the inspector option to run RT under Rosetta 2 (and Rosetta 2 is definitely installed), but I’ll keep digging…

I have the hardware now and will see how far a native build goes before it fails. I have little background with this tech stack so if there is something obvious I should adjust before building I would appreciate any pointers.

**Comment by strogonoff** [comment]
> I only did a quick test with some adjustments and export and it works. And despite rosetta it's quite fast.

Which release did you use? Or did you build from source? “Open using Rosetta" does not show up for me somehow for RT (weirdly enough, I can see it for other apps).

Perhaps it opens using Rosetta by default, being an Intel app?

But then I wonder why it crashes immediately🤔

**Comment by frgazor** [comment]
I used latest binary build available for download (5.8). You don't have to do anything with rosetta, just copy everything to /Applications and it will run just like any other app.

**Comment by strogonoff** [comment]
Interesting. I have a habit of placing non-critical apps under `~/Applications`. It worked consistently so far (in fact, macOS gives that folder the special icon and all). However, on Big Sur RT only successfully launched from within the global `/Applications`.

Thanks @frgazor!
