### ISSUE TITLE
Consistent crash during DCB demosaicing, only affecting one camera

### ISSUE THREAD

**Issue by wilchak** [Beep6581/RawTherapee#6034]
I have a profile that immediately crashes RT when applied to any raw files from the Nikon D3X. Can't reproduce with raws from any other camera. And it only happens when DCB is used as the demosaicing method.

My debug build crashes at the terminal with this message: 

rawtherapee: /home/andrew/code/RawTherapee/rtengine/demosaic_algos.cc:1070: void rtengine::RawImageSource::dcb_hid(float (*)[3], int, int): Assertion `indx - u - 1 >= 0 && indx + u + 1 < u * u' failed.

Here's a link to a NEF and a PP3 that crash: https://user.fm/files/v2-6ac2011ea8ca21f9230745d45d511c67/rt.zip

Here's a full stack trace from the debug build: [log.txt](https://github.com/Beep6581/RawTherapee/files/5742391/log.txt)

Version: 5.8-2695-g5a2d2dc6b
Branch: dev
Commit: 5a2d2dc6b
Commit date: 2020-12-24
Compiler: cc 10.2.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.24.3
Lensfun: V0.3.95.0
Build type: debug
Build flags:  -std=c++11 -march=native -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -fopenmp -Werror=unknown-pragmas -g -ftree-vectorize
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON
Build OS: Linux 5.9.14-xanmod1-1 x86_64
Build date: Fri, 25 Dec 2020 20:12:54 +0000 UTC
Build epoch: 1608927174
Build UUID: 109bb055-303f-4aad-8bd7-ad00fc43c597

Thank you!!!

**Comment by Thanatomanic** [comment]
Hi @wilchak, thank you for providing the necessary information including a stack trace. Unfortunately, your provided NEF and PP3 load just fine in my recent release build of RT on Windows. So unfortunately, I cannot be of more assistance here. If @heckflosse has some time, he might be able to take a look as he understands the demosaicing algo's much better than I do.

**Comment by Lawrence37** [comment]
I can reproduce the crash on Linux. Additionally, the release build segfaults.

**Comment by heckflosse** [comment]
I cannot reproduce the crash, but this patch could fix it
```diff
diff --git a/rtengine/demosaic_algos.cc b/rtengine/demosaic_algos.cc
index a31415968..85197d766 100644
--- a/rtengine/demosaic_algos.cc
+++ b/rtengine/demosaic_algos.cc
@@ -972,11 +972,11 @@ inline void RawImageSource::dcb_initTileLimits(int &colMin, int &rowMin, int &co
     }
 
     if( y0 + TILESIZE + TILEBORDER >= H - border) {
-        rowMax = TILEBORDER + H - border - y0;
+        rowMax = std::min(TILEBORDER + H - border - y0, rowMax);
     }
 
     if( x0 + TILESIZE + TILEBORDER >= W - border) {
-        colMax = TILEBORDER + W - border - x0;
+        colMax = std::min(TILEBORDER + W - border - x0, colMax);
     }
 }
 
```

**Comment by Lawrence37** [comment]
@heckflosse With the patch, RT no longer crashes.

**Comment by heckflosse** [comment]
@Lawrence37 Thanks for testing and confirming the fix
