### ISSUE TITLE
Apple Pro RAW support

### ISSUE THREAD

**Issue by dimonoid** [Beep6581/RawTherapee#6036]
Hello, I just found samples of new raw format.
https://www.reddit.com/r/iphone/comments/jyjtt8/proraw_example_files/
Surprisingly, they are in .DNG format(though might have some extra metadata / AI stuff). 
As a comparison with normal DNG, Pro RAW appears 2 times larger per photo.
When I open using rawtherapee, the files look pinkish and with broken debayering.

What are the chances that support of those files will ever be added? 
What is your opinion on the potential of the new format and how is it better than the traditional .DNG standard?

**Comment by reggybe** [comment]
Pro RAW means here Processed RAW, so **already debayered**. The DNG file format from Apple is **NOT** a RAW-file, and should be worked on as a normal DNG, JPG, TIF file.

**Comment by Entropy512** [comment]
More specifically, it's "Linear DNG" conforming to DNG 1.6 specifications.

The only changes in 1.6 are some new metadata tags not really relevant to RT, so the DNGs should just work out of the box, I'm 95% certain RT supports Linear DNG.

**Comment by iliasg** [comment]
For the moment, I can open and edit these files after first converting with the latest Adobe DNG converter.
There are some rare problems with hot pixels though :(

The original ProRaw files use tiling which is not supported by dcraw.c decoder used by RT .. (I am not sure if it's the tiling that dcraw cannot hold or just some related metadata ..) 
Libraw decodes them .. ;)
