### ISSUE TITLE
Enable Olympus .ORI files in File Browser

### ISSUE THREAD

**Issue by ff2000** [Beep6581/RawTherapee#6044]
When shooting Olympus HighRes files the camera produces the actual HighRes file as .ORF but also saves the first single frame as a seperate .ori file. Those files can later be used to replace areas with artefacts due to object movement.
For example look at the two photos:
https://www.dropbox.com/s/mjn1jgazofxfmee/PC240006.ORF?dl=0
https://www.dropbox.com/s/mi6xgj49iio4le4/PC240006.ORI?dl=0
The .orf show artefacts where a van and a bus were driving on the street in the left third of the image while the .ori contains perfectly fine vehicles.

It would make things easier if one could interact directly with the .ori files in the file browser (apply profiles, clear caches, etc.)

I tried this patch, but it seems it wasn't applied to my preferences:

``` patch
diff --git a/rtdata/options/options.lin b/rtdata/options/options.lin
index 580390b28..82f437cdf 100644
--- a/rtdata/options/options.lin
+++ b/rtdata/options/options.lin
@@ -12,8 +12,8 @@ MultiUser=true
 
 [File Browser]
 # Image filename extensions to be looked for, and their corresponding search state (0/1 -> skip/include)
-ParseExtensions=3fr;arw;arq;cr2;cr3;crf;crw;dcr;dng;fff;iiq;jpg;jpeg;kdc;mef;mos;mrw;nef;nrw;orf;pef;png;raf;raw;rw2;rwl;rwz;sr2;srf;srw;tif;tiff;x3f;
-ParseExtensionsEnabled=1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;0;1;1;1;1;1;1;1;1;1;1;1;
+ParseExtensions=3fr;arw;arq;cr2;cr3;crf;crw;dcr;dng;fff;iiq;jpg;jpeg;kdc;mef;mos;mrw;nef;nrw;orf;ori;pef;png;raf;raw;rw2;rwl;rwz;sr2;srf;srw;tif;tiff;x3f;
+ParseExtensionsEnabled=1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;0;1;1;1;1;1;1;1;1;1;1;1;
 
 [Output]
 PathTemplate=%p1/converted/%f
```

**Comment by ChasingShadows** [comment]
You know that you can add any file extension in the settings? 
![image](https://user-images.githubusercontent.com/55600750/103475898-90462b80-4db1-11eb-96a5-e2bd2193fb68.png)

**Comment by ff2000** [comment]
@ChasingShadows yes I know, that's what I did after the patch failed.
I just think it would be nice to have them enabled by default.

**Comment by heckflosse** [comment]
Isn't the options file only installed on a fresh install to not overwrite an exisiting options file by accident?

**Comment by ChasingShadows** [comment]
Yes, I think that @heckflosse is right ...

**Comment by ff2000** [comment]
If that's true also for -DBUILD_BUNDLE=true it would the explanation.
Now the question is should RT support .ori files?

**Comment by heckflosse** [comment]
> Now the question is should RT support .ori files?

If RT can open them, we should add the ori extension, but maybe not enable it by default, because .ori is a very bad choice for an extension of an image file imho...

**Comment by Entropy512** [comment]
> because .ori is a very bad choice for an extension of an image file imho...

Oh?  I'm kind of curious what it's also used for?

To add to the confusion, the Xphase "Pro" saves with the ORI file extension, but that format isn't RAW by any means.

**Comment by heckflosse** [comment]
> Oh? I'm kind of curious what it's also used for?

https://fileinfo.com/extension/ori

**Comment by Thanatomanic** [comment]
As I also said in the PR, I have only found one single `*.ori` file on my Windows computer (some more `*.orig` files though). We cannot handle all possible confusing file extensions. If somebody combines _actual_ Olympus ORI files in the same folder with manually renamed ORI files and/or other non-RAW ORI files, people need to reconsider their archival/ordering skills 😉 

What concerns me more is the fact that RT seemingly cannot update the options file when a file extension is added. But I guess that's not the easiest thing to fix.

**Comment by Entropy512** [comment]
Hmm...  Well, I'm not sure how to do the initial migration from the current format, but perhaps going forward, the extensions configuration in the file should be treated as a "differences from default" list?

If the options file lists a particular extension as "add", and it's already in the defaults - ignore it.  (In the event that it's ever removed from defaults again, probably shouldn't remove it from the file.)

If the options file lists it as "subtract/disable" - remove it, or if it's already gone (in the rare case that the defaults had something removed), do nothing.
