### ISSUE TITLE
Very small spot & tone mapping hangs CPU

### ISSUE THREAD

**Issue by chaimav** [Beep6581/RawTherapee#6053]
RawTherapee_dev_5.8-2711 / Windows 10 / i3 8100 
I added a very small spot and tried to apply tone mapping mapping. The CPU maxes out out and hangs.
PP3: https://drive.google.com/file/d/1HXXXKSoWM4aGcw5iSFYR5FXkOLC6vXK5/view?usp=sharing

**Comment by Desmis** [comment]
@chaimav 
I confirm...
I change the minimum spot size for TM to 64 , as Denoise
Under these values no action.

I just push a change in DEV

Thank you

Jacques

**Comment by chaimav** [comment]
Just installed RawTherapee_dev_5.8-2717 and confirmed it no longer hangs the CPU.

**Comment by Desmis** [comment]
Ok thank you very much 

jacques

**Comment by arturoisilvia** [comment]
With win 5.8-2717:

I don't understand .... what has to be below 64 for it not to work? 
Tone Mapping: 'Spot size' is working for me with any value.

**Comment by Desmis** [comment]
@arturoisilvia 
Under 64 the system may hang sometimes...not always...but in my case, the system hangs...

I change the minimum value, before it was 5...now 64. I tried with 39...and sometimes it hang

there are 4 values  for spot minimum size depending on the tools : 5, 32, 39, 64....all are small

jacques

**Comment by arturoisilvia** [comment]
OK understood.
Thank you!.

**Comment by chaimav** [comment]
> With win 5.8-2717:
> 
> I don't understand .... what has to be below 64 for it not to work?
> Tone Mapping: 'Spot size' is working for me with any value.

Did you load the test PP3?

**Comment by arturoisilvia** [comment]
@chaimav 
Yes, and I also tried a new pp3 from scratch just in case your pp3 was corrupt: in both cases I was blocked by setting the cpu to 100%.

It seems that now with dev-2717 it has been fixed.

A greeting
Arturo.
