### ISSUE TITLE
Improvement for rcd demosaic

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#6054]
In collaboration with @jenshannoschwalm from darktable and Luis (https://github.com/LuisSR/RCD-Demosaicing) we made some changes to rcd demosaic. I will post the RT code in a new branch.

Advantages are:

1) 20% faster
2) got rid of SSE code
3) reduced border interpolation from 9 to 6 pixels

**Comment by Thanatomanic** [comment]
@heckflosse and others: good to see a nice collaborative effort!

> got rid of SSE code

This actually made things faster? Or at least not slower?

**Comment by heckflosse** [comment]
Same speed. gcc seems to vectorize very good. Didn't test on clang...

**Comment by heckflosse** [comment]
I tested on a windows clang build.

Old version needs ~580ms for a 45.6MP file.
New version needs ~550ms for the same file.

For comparison: new version on a windows gcc build needs ~230ms

**Comment by reffort** [comment]
Is the image quality affected by this?  RCD is already fast, so it would be a shame if there were any reduction in image quality for such a negligible (550/580 = ~5%) speed increase.

**Comment by heckflosse** [comment]
Well, the output from clang builds and gcc builds is equal. With new code gcc builds are ~20% (which is not negligible) faster than with old code. I did not detect any differences visible by eyeball between new and old code.

**Comment by heckflosse** [comment]
Closed with 049a614

**Comment by reffort** [comment]
Well, with the quoted numbers:

> Old version needs ~580ms for a 45.6MP file.
> New version needs ~550ms for the same file.

that's a 5.2% difference--not much.

If you are saying that the code changes were done to benefit gcc, it was already twice as fast as the new Windows/clang build, based on the numbers you provided above. 20% would translate to about 45 ms.

Improving code efficiency and speed are great, but the speedup is only 30-45ms on a large file for something that's done sporadically. If there is a reduction in output image quality, it is permanent.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

**Comment by heckflosse** [comment]
@reffort

> If there is a reduction in output image quality

As you can see in the source code

```
// Luis Sanz Rodriguez significantly optimised the v 2.3 code and simplified the directional
// coefficients in an exact, shorter and more performant formula.
```
it was the original author of RCD who made the main changes.
Then Hanno and I optimized it further in collaboration with him.

**Comment by photopea** [comment]
I tried to replace all std::fabs() with squaring in rcd_demosaic.cc, and it gives almost the same visual result.

@LuisSR could you check if replacing the absolute value with squaring still is "scientificly meaningful"? Multiplication is faster to compute than the absolute value, as it does not require branching.
