### ISSUE TITLE
NIKON COOLPIX P950 NRW files - request for camconst.json parameters for rawtherapee 5.8

### ISSUE THREAD

**Issue by arvindpgh** [Beep6581/RawTherapee#6066]
Have uploaded NRW files at filebin.net for working out parameters of the camera for the camconst.json file used with rawtherapee 5.8 under Ubuntu 18.04

Single zip file NIKON-P950.zip
filebin URL is  https://filebin.net/bkc7ut2u0f8j8h1w

The procedure followed is taken from here --> http://rawpedia.rawtherapee.com/Adding_Support_for_New_Raw_Formats

Thanks for the help.

**Comment by Thanatomanic** [comment]
Thanks for this, I'll take a look soon

**Comment by Thanatomanic** [comment]
Hi @arvindpgh, could you also please upload a shot that is completely black, taken with the lenscap on? Low ISO, no LENR please.

**Comment by arvindpgh** [comment]
Will do shortly and confirm.  Thanks.

**Comment by arvindpgh** [comment]
Full black files uploaded
Link ->  https://filebin.net/1pogufi069emz5gk

Thanks again

**Comment by Thanatomanic** [comment]
@arvindpgh I've just committed the relevant information. The nightly build of tomorrow will contain support for the P950. Thank you for providing the shots.

@agriggio You may want to copy over stuff for ART

**Comment by arvindpgh** [comment]
@Thanatomanic thank you very much for the support.  Much appreciated..
