### ISSUE TITLE
Local edit, dynamic range compression bug: right side border

### ISSUE THREAD

**Issue by chaimav** [Beep6581/RawTherapee#6067]
I tried using the local dynamic range tool in the latest dev build and noticed some odd behavior. When it is applied to the whole image, the right hand side seems to have a some sort of border.
RawTherapee 5.8-2726, Widows 10, i3-8100.

More info and test case: https://discuss.pixls.us/t/local-edit-dynamic-range-compression-bug/22814

**Comment by Desmis** [comment]
@chaimav 
Thank you again for testing "deep" :)

This bug also happen in "vertical", and also with others tools using FFTW

I tried to optimize FFTW....to save time the FFTW function is faster when the size of the window (part of the image) is a multiple of: 2^n * 3^p * 5¨h * 7^t*(11^y | 13^z), and for each direction H and W

In the case of the 2 delimiters H, or the 2 delimiters W are outside the image, calculation was not good.

I just change. 
I hope this will fix the bug  :)

Jacques

**Comment by chaimav** [comment]
> @chaimav
> Thank you again for testing "deep" :)

That's easy. As it is already so mature I have made the dev version my main one.

> I just change.
> I hope this will fix the bug :)
> 
> Jacques

Thanks for fixing it and all of the other hard work you do. When it hits the nightly build I'll give it a shot and see if the fix worked for me.

**Comment by chaimav** [comment]
I just installed 5.8-2735 and cannot repeat the bug. :-)
