### ISSUE TITLE
Placement of local adjustments in the processing order 

### ISSUE THREAD

**Issue by mikae1** [Beep6581/RawTherapee#6069]
Following [a discussion on Pixls.us](https://discuss.pixls.us/t/some-news-about-rawtherapee-s-local-adjustments-and-recent-rawpedia-updates/22789/15) I'm submitting this issue to discuss the future placement of local adjustments in the [processing order](https://rawpedia.rawtherapee.com/Toolchain_Pipeline#Processing_order).

I make the case that local adjustments should come as early as possible in the processing order as putting global adjustments before them will significantly limit the editing headroom for local adjustments.

As an example… Global adjustments such as `Film simulation` (LUTs) or `RGB curves` usually increases contrast and thus darkens shadows. Trying to raise those darkened shadows — during dodging and burning via local adjustments — after globally applied LUTs and curves will leave the photographer with much limited editing headroom.

Following my reasoning local adjustments should definitely go before `13. Process RGB` in the [processing order](https://rawpedia.rawtherapee.com/Toolchain_Pipeline#Processing_order). Perhaps even earlier.

To demonstrate having what having local adjustments before global in the image processing pipeline means, I'm showing Lightroom:
![lr_pipeline](https://user-images.githubusercontent.com/773707/104965105-429b0700-59de-11eb-96bf-a923d90dde05.gif)

I first use the global tone curve to clip `almost` the entire image (clipping shown in blue). I can then use the local adjustment brush to “recover” clipped data. This also applies to other tools in Lightroom like the global exposure slider. This would not have been possible if global adjustment came before local adjustments in the processing order (as is the case with the current implementation in RawTherapee).

**Comment by Desmis** [comment]
@mikae1 
I have nothing against changing the order of the Rawtherapee pipeline.. 
It will be very difficult, if not impossible, to move "Local Adjustments" (LA) which is in "full frame" mode and in Lab mode, while "Film simulation" is embedded in an RGB process with tiles.

May be is simpler (possible) to move "Film simulation" after  LA, but its suppose a double conversion Lab <==> RGB
Or, move "LA", before all RGB process with Tiles...I didn't look, but this will probably lead to other inconveniences. In this case it's suppose a double conversion RGB<=>Lab  

other opinions ?

Jacques

**Comment by Desmis** [comment]
@mikae1 
I just push a new branch "lanewlocation" 
I change the localization in the process (pipeline) for the 3 process : Dcrop.cc, Improccordinator.cc, Simpleprocess.cc
I change also (of course), events, in refreshmap.cc
On reflection I think there are only advantages to doing this (begin with more  linear datas) , so it's a good thing.

Now the "Local adjustments" is before all "rgb" process in tiles mode.
The reaction time is slightly longer due to the more upstream management of the process.

For me it's seem to work !

@heckflosse 
Ingo
Could you have a look to my work ?
Thank you

Jacques

**Comment by mikae1** [comment]
> I just push a new branch "lanewlocation"
> I change the localization in the process (pipeline) for the 3 process : Dcrop.cc, Improccordinator.cc, Simpleprocess.cc
> I change also (of course), events, in refreshmap.cc

I wish I could comment this, but being a photographer and retoucher rather than a programmer I hope someone else can chime in. 🙂

> On reflection I think there are only advantages to doing this (begin with more linear datas) , so it's a good thing.

The advantage of moving local adjustments up in the processing order is huge! The most extreme and apparent example I could come to think of is some [lith print](https://www.google.com/search?q=lith+print&hl=sv&tbm=isch) emulations I've had to do over the years. A global curve is set that clips blacks all over the place. Now local adjustments can still be used bring parts of the image back from clipped.

> Now the "Local adjustments" is before all "rgb" process in tiles mode.

Awesome @Desmis , this was fast! 🙌 May I ask what "in tiles mode" means in this context?

**Comment by Desmis** [comment]
@mikae1 
In Rawtherapee, some procees uses "tiles", instead of "all image".
The image is "divided" in many "squares" (tiles)...with a complex recovery betwwen this "tiles".
This has the consequence of reducing the need for resources (memory...)

You can find "Tiles"
1) here in the 'rgb' process, of course "Local adjustments" is not inside
2) Noise reduction
3) Wavelet levels
4) some Demosaicing methods

But actually, there is some bad behavior... with events...

Jacques

**Comment by ff2000** [comment]
Some time ago I asked something similar and was told it wasn't doable/possible. My issue was that when doing black&white conversions local adjustments become nearly useless as B&W conversion is done before LA.
This change is really handy and I hope it will make it into DEV (after other devs agree on it).
Thanks @Desmis :+1:

**Comment by Thanatomanic** [comment]
I have not tested the code, but at first glance all seems well. Since the local adjustments are new for version 5.9 there is no backward compatibility to take into account, which is good too.

**Comment by Desmis** [comment]
@Thanatomanic  @heckflosse @Floessie ... and others :)

I'm sure this change is very important, I've tried to make the necessary changes, but it is difficult !

Obviously, change the location... In dcrop.cc, Improccoordinator.cc, Simpleprocess.cc with a double conversion rgb<>lab
This part seems to work well

Then change the "events". 
 it may seem obvious, but the set of functions in improccordinator.cc and dcrop with the "todo" needs to be change, as well as the events in refreshmap.cc
1) For example all "Locallab" events that were at "LUMINANCECURVE" are now at "AUTOEXP"...
2) I have change the "todo"

But after testing, I saw that all "RGB process" ("exposure", "Shadows/ highlight", "RGB Curves", ""Film Negative", "HSV equalizer", "Channel mixer", "Vibrance", "BW", "Film silulation", "Color toning",....were having a bad impact on "Local Adjustments" which was further upstream...
3) All these "process" was with event "RGBCURVE", I had to change them to "AUTOEXP"

Now, all seems to work ? These changes leeds  to a small increase in reaction times, but I think acceptable

On the other hand I don't know how to treat what is induced by M_TRANSFORM. I Think to "Vignette filter" and "Graduated Filter"....there are big malfunctions if Local Adjustments  is activated. I don't know how to do!...and may be there is others process 'bad' ?

Please can you help me, as well as check what I've done , including 1) 2) 3)

Thank you very much

Jacques

**Comment by heckflosse** [comment]
@Desmis I will have a look at the weekend

**Comment by Desmis** [comment]
@heckflosse 

Ingo

Thank you very much :)

Jacques

**Comment by Desmis** [comment]
Hello.

By changing, in refreshmap.cc all TRANSFORM to HDR,  all functions as "vignetting", "Gradient", "rotation", "Vignetting correction", "Distorsion", etc. Now seems to work fine, whithout interference on "Local adjustments"

But I repeat myself, we can't have our cake and eat it too, and by definition putting this process first will cause others to get behind it :)
Which coupled with the double conversion, will give a bit slower reaction times (e.g. for zooms). 
Nevertheless, I think that the balance of advantages/disadvantages is clearly in favor of moving LA upstream.

Jacques

**Comment by mikae1** [comment]
> You can find "Tiles"
> 
>     1. here in the 'rgb' process, of course "Local adjustments" is not inside
> 
>     2. Noise reduction
> 
>     3. Wavelet levels
> 
>     4. some Demosaicing methods

🙌

**Comment by Desmis** [comment]
@heckflosse 

Ingo

I havefound another bad behavior...
In dcrop.cc for denoise...It needs now
Line 648
        if (todo & (M_INIT | M_LINDENOISE | M_HDR)) {

Am I pushing for this change, where do I wait ?
I'm absolutely not sure about my work...It's a field for me, full of unknown things? Maybe from the beginning, when I "moved up" (for "LA")  from "RGBCURVE" to "AUTOEXP" I was wrong !

Thank you again

Jacques

**Comment by Desmis** [comment]
Change push - commit 98f326df3

All seems to work... to verify  :)

jacques
