### ISSUE TITLE
Feature request: Support .cube 3d lut files

### ISSUE THREAD

**Issue by abnormally-distributed** [Beep6581/RawTherapee#6070]
Is there any chance of cube file support being added to rawtherapee in 5.9? I have tons of cube files, and while I could convert them to PNG , PNGs take up significantly more hard drive space. What might be 1-2 mb at max for a cube file translates to 10-15x the size when converted to a haldclut png. Darktable offers cube support, but they lack dcp and lcp profile support. Would be fantastic to be able to use cubes in rawtherapee!

**Comment by Thanatomanic** [comment]
Please see https://github.com/Beep6581/RawTherapee/issues/5704
