### ISSUE TITLE
Branch cleanup

### ISSUE THREAD

**Issue by Thanatomanic** [Beep6581/RawTherapee#6071]
I know progress is a slow beast since we're not many people, and we have many ideas. This is reflected in the fact that we have 68 branches at the moment, 26 are considered _active_ and 40 are considered _stale_ (excluding the `releases` branch). I think these branches fall into one or more of the following categories:
- **Already merged.** I suspect these branches can be removed.
- **Started but abandoned.** Good ideas that came to life, but died somewhere along the way. In some cases these branches are from people who do not actively contribute anymore to RT (Hombre57 and agriggio). What to do? Time and energy has been invested at some point, so it may be a pity to delete. Then again, as the main branch continues to develop, it gets progressively harder to finish the features and merge these branches.
- **Almost done, needs just a little work.** There are a few branches that seem (almost) finished, but were never merged for some good reason (e.g. `poor_man_dehaze`). What would be needed to merge these? Or should some be abandoned/deleted?
- **Actually active branches** There are few open PRs and branches being worked on will definitely (currently) be merged in the near future. These should obviously be kept.

The current tally of the developers who last contributed to each branch is as follows:

_Active branches_ (26)
- @Desmis 18x
- @heckflosse 5x
- @Floessie 1x
- @rom9 1x
- @Thanatomanic 1x

_Stale branches_ (40)
- @heckflosse 13x
- @Desmis 8x
- @Hombre57 8x
- @Beep6581 4x
- @Floessie 3x
- @Lawrence37 2x
- @agriggio 1x
- @Thanatomanic 1x

Unless people have a strong opinion on the matter, it seems useful to me to start a good round of cleaning. Especially with the small team that we are, I think it is not sensible to have so many half-completed ideas hanging around (it's just not realistic to think everything will still be finished at some point). But of course opinions may vary, so let's discuss 🙂

**Comment by Desmis** [comment]
@Thanatomanic 
I totally approve of this approach. 15 days ago I already did a cleaning. I have just done a new one.

One remark. I've been doing a lot of merge recently and this should be over. Each of these branches has been done to facilitate exchanges with other collaborators. I took the principle to facilitate the dialogues of "a big modification" (labels, tooltip, GUI translation, code...) is concretized by a new branch  :)

jacques

**Comment by rom9** [comment]
@Thanatomanic  Agreed. Regarding my `filmneg` branch, i left it there to use it as a base for the upcoming over/under-exposure improvements, but i'm still not done analyzing the data from my test negative... so i didn't write any code yet :-/
I will delete the branch now, i can always re-create it when i have something to show :-)

**Comment by Lawrence37** [comment]
I removed my branches. They were all merged and can be recovered from my fork if needed.

**Comment by Beep6581** [comment]
I have cleaned up dead branches in the past (#1122 #4339 etc), but be careful doing so. The information in an issue which gets closed remains accessible in perpetuity, while code in a deleted branch eventually gets deleted as well. That is to say, we should identify branches for deletion based on whether the code within them is not and will not be of value, not whether it's just stale or not. Leaving stale but potentially useful branches alone does not add to maintenance.
