### ISSUE TITLE
Local Adjustments: Disable Spot does not work with Denoise

### ISSUE THREAD

**Issue by arturoisilvia** [Beep6581/RawTherapee#6074]
Hello!
Disabling 'Disable spot' has no effect on 'Blur / Gain & Denoise' -> 'Denoise':
1.
![Captura1](https://user-images.githubusercontent.com/55624244/105774828-13e4d980-5f66-11eb-87f8-04f3332f3043.JPG)
2.
![Captura2](https://user-images.githubusercontent.com/55624244/105774842-1a735100-5f66-11eb-9b1f-df4e7b2615f4.JPG)
3.
![Captura3](https://user-images.githubusercontent.com/55624244/105774867-219a5f00-5f66-11eb-936b-99999369c46d.JPG)
.
Version: 5.8-2738-g8ca07e858
Branch: dev
Commit: 8ca07e858
Commit date: 2021-01-24
Compiler: x86_64-w64-mingw32-gcc\ 9.3.0
Processor: generic x86
System: Windows

A similar case has already been fixed: https://github.com/Beep6581/RawTherapee/issues/5980

Cheers!
Arturo.

**Comment by Desmis** [comment]
@arturoisilvia 

Thank you for testing :)

Fixed, this forgotten "Enable / disable" for de noise
Commit a5280fddf

Jacques

**Comment by arturoisilvia** [comment]
Ok, thanks.
