### ISSUE TITLE
Add an option to use lens corrections and flat fields embedded in image metadata

### ISSUE THREAD

**Issue by ghost** [Beep6581/RawTherapee#6076]
This would be great because many cameras store lens corrections in image metadata. Already present in ART

**Comment by Thanatomanic** [comment]
Can you point us to what you mean? This is a very sparse feature request.

**Comment by ghost** [comment]
I'm sorry, looks like this is already done in the nightly builds. I'm closing this issue then

**Comment by ghost** [comment]
Edit: it isn't. In ART you can choose "embedded in metadata" under Profiled Lens Correction to correct distortion and vignetting based on the image metadata. There is also this option for the Flat Field. In ART you can go there and check "Embedded in metadata", but there is no option for this in Rawtherapee

**Comment by Thanatomanic** [comment]
Thank you for the updated explanation. Still, especially if this is already discussed and/or implemented elsewhere, please point us to 1) the code, 2) the issue in ART or 3) the pull request that handled the addition of the feature.

**Comment by ghost** [comment]
I think it was added in version 1.7:
https://discuss.pixls.us/t/art-new-releases/16500/110
Also: 
https://bitbucket.org/agriggio/art/commits/1de9ad8bedd1659541da6b64b662639484b1c758
https://bitbucket.org/agriggio/art/commits/33d835b86c0581a6e9892f8adadd41ade3ec8c61
