### ISSUE TITLE
The gamma is incorrect in the preview mode

### ISSUE THREAD

**Issue by ghost** [Beep6581/RawTherapee#6081]
Version 5.8, Windows
Please see http://www.ericbrasseur.org/gamma.html

**Comment by ff2000** [comment]
I just recently reported this issue:
https://github.com/Beep6581/RawTherapee/issues/6021
(A little clumsy wording because I basically know nothing about all that...)

**Comment by ghost** [comment]
Ok, thank you, I'm closing this one
