### ISSUE TITLE
Feature request: User defined crop guides.

### ISSUE THREAD

**Issue by ghost** [Beep6581/RawTherapee#6086]
The request: The possibility for the user to create and add guides to the crop module.

This was asked for on pixls ([Additional frame guides in crop tool](https://discuss.pixls.us/t/additional-frame-guides-in-crop-tool/23145/)).

@heckflosse mentioned that the current guides are hardcoded. I'm not a developer and thus have no idea how hard it is to implement a 'dynamic guide' possibility,  so adding a few hardcoded extra guides would be a second choice but very welcome nonetheless!

The 9 guides available to the  user at the moment do not include some types and/or variations that might be beneficial to the user. The 2 that jump out, for me that is, are:

- Additions to the current Harmonic means guide: A stand alone  spiral (fluent and sectioned) and the spiral on top of the current harmonic means. You do need to be able to flip these horizontally and/or vertically.
- A simple circular perspective guide.

The reason I would like to see a solution that makes it possible for the user to add guides has to do with the almost limitless amount of guides that can be produced and used. I have been looking into dynamic symmetry lately and adding the "standard" ones alone would make the list way to long for normal use.

EDIT: 2 people made the same FR at the same time, so this one and #6085 are about the same thing. Can someone merge these?

**Comment by Thanatomanic** [comment]
Merging issues is not really possible. @jade-nl, you have worded your issue nicely here, so maybe just copy/paste it in https://github.com/Beep6581/RawTherapee/issues/6085
Closing this one now.
