### ISSUE TITLE
Huge load on CPU causing fan noise to act up when starting Raw Therapee.

### ISSUE THREAD

**Issue by Curious2021** [Beep6581/RawTherapee#6088]
Windows 10 latest build. 
Dell XPS 17 9700 with 32 gigs of RAM with 1T of storage.

Installed Raw Therapee 5.8 a few days ago and immediately noticed my fans acting up just for opening up the program. I didn’t do anything other than simply opening the program and my CPU fan noise immediately goes into overdrive. Closing Raw Therapee immediately stops the fan noise. Cannot use Raw Therapee until this issue is fixed.

**Comment by Thanatomanic** [comment]
RawTherapee is probably generating thumbnails at the moment. Does the CPU usage decrease after doing nothing for a while (~ few minutes) and staying in the file browser?

**Comment by Curious2021** [comment]
No. I did’t get the chance to do that since the fan noise was concerning me a great deal. I had to turn it off because of the fan noise and didn’t understand why my computer fan noise was going crazy. Is there a setting where I can disable indexing the photos to stop this if that’s what’s causing the problem? Because just turning on Raw Therapee was causing my fan noise to go way up.

**Comment by Thanatomanic** [comment]
It seems you are afraid of using your CPU? If you are already concerned about noise when starting RT, you will probably never dare to export images as that is also very CPU intensive and your CPU needs its cooling.

The indexing cannot be turned off because it is our aim to provide accurate thumbnails as part of a good workflow, sorry.

**Comment by Curious2021** [comment]
There must be something else that’s causing the problem in Raw Therapee because I also have Dark Table and this doesn’t give me fan noise issues when indexing photos. Given that comparison between both programs and since they have to index photos...and assuming both programs index photos correctly then it can’t be the indexing that’s causing the problem in Raw Therapee. There’s got to be something else causing the fan noise to act up. Is there anything else I can do to stop the fan noise acting up in Raw Therapee?

I have 
Faststone Image Viewer
Luminar Ai
Corel Paintshop Pro Ultimate 2021
ACDsee Photo Ultimate 2021
Darktable

And none of these programs are causing my fans to act up when opening up any of them. But when I open up Raw Therapee...my fan noise starts going up and I can definitely notice the difference. So something is wrong. I had no choice but turn off Raw Therapee. This is my list of programs I have on my laptop right now and the only one causing the fan noise issue is Raw Therapee.

**Comment by Thanatomanic** [comment]
I'm afraid the answer is currently no, but maybe @heckflosse can still chime in.

**Comment by gaaned92** [comment]
didn’t understand why my computer fan noise was going crazy

When fans are going to be crazy noisy as you write, perhaps it is time  to change them.
Going 100% CPU for a long time should not be a problem, When running FAH full power, my PC stays at 100%CPU without noticeable noise.

**Comment by heckflosse** [comment]
To test whether the thumbnail creation causes the "issue" you can

1) create an empty folder (for example `c:\empty_folder`
2) start rt from commandline `rawtherapee c:\empty_folder`

Maybe also related: 
http://rawpedia.rawtherapee.com/Film_Simulation#Startup_time

**Comment by Curious2021** [comment]
The problem for me is the Dell XPS 17 has an unacknowledged logic flaw in the battery power usage. The issue is the Dell XPS 17 line only has 130 watt battery bricks supplied with this model. So Dell is using a proprietary technology to power this laptop model. Apparently if the Dell XPS 17 has a increase in CPU load, like loading up Raw Therapee, Dell is allowing the XPS 17 model to draw battery power to compensate for CPU load even if the laptop is plugged into the wall socket like I have. So if I left Raw Therapee on at this fan noise level chances are my battery would start draining even though I’m plugged into the wall. I didn’t want to take this chance so I stopped Raw Therapee to stop the fan noise. Not that I have a problem with fan noise. It’s just because I’m aware of this issue with my laptop draining the battery with this model by Dell that has me concerned. But my laptop has been perfect all this time....but I am aware of this issue and experienced this problem only when certain processes act up causing battery drain.

Edit: I’m going to try the command line suggestion to see if this fixes the problem. if it does...then it’s comical that I’d have to do this to fix fan noise issues. But that only suggests there’s something in Raw Therapee that’s causing my fans to act up like this. But it shouldn’t do this if that’s what this problem is - thumbnail indexing. I’d be more concerned if I do this test and the fan noise is still acting up. So I’m hoping your trick works...but that would only mean you have a problem with CPU load when indexing.

**Comment by Thanatomanic** [comment]
While I agree that RT has areas where its CPU usage has room for improvement, I don't think we can be asked to find a solution for what is essentially a hardware choice/problem on your side.

I will close this issue for now and hope for your understanding of our point of view.

Edit: if you can pinpoint a more exact problem with high CPU load, of course feel free to address this.
