### ISSUE TITLE
Canon R6 Not reading white balance info from Camera

### ISSUE THREAD

**Issue by itsmark166** [Beep6581/RawTherapee#6089]
Windows 10 18363
Version: 5.8-2743-g6b1e5d618
Branch: dev
Commit: 6b1e5d618
Commit date: 2021-01-30
Compiler: x86_64-w64-mingw32-gcc\ 9.3.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.24.2
Lensfun: V0.3.2.0
Build type: Release
Build flags: -mwin32\ -m64\ -mthreads\ -msse2\ -std=c++11\ -mtune=generic\ -Werror=unused-label\ -Werror=delete-incomplete\ -fno-math-errno\ -Wall\ -Wuninitialized\ -Wcast-qual\ -Wno-deprecated-declarations\ -Wno-unused-result\ -Wunused-macros\ -fopenmp\ -Werror=unknown-pragmas\ -Wno-aggressive-loop-optimizations\ -DNDEBUG\ -O3\ -ftree-vectorize
Link flags: -m64\ -mthreads\ -static-libgcc\ -mtune=generic\ -s\ -O3
OpenMP support: ON
MMAP support: ON
Build OS: Linux 4.4.0-101-generic x86_64
Build date: Sun, 31 Jan 2021 00:27:26 +0000 UTC
Build epoch: 1612052846
Build UUID: a8a38e4a-303d-4945-94a9-10e7456ced59

Tried an earlier development build as well with same issue. No matter what file I open from my Canon R6 - raw or jpeg - Raw therapee is applying the same white balance even though I have selected 'camera'

![RTR6](https://user-images.githubusercontent.com/78375002/106495940-33bf5480-64b4-11eb-94f7-a3444dcc4db8.JPG)

I am not able work out where RT has got those values from but they are used across every R6 image that I have. Functionality for all other files that I have - other canon cameras and sony cameras is as expected and works perfectly.

Thanks everyone. RT is the bees knees.

Mark

**Comment by Thanatomanic** [comment]
What would be your expectation in this case? What does another raw processor do?

Can you provide at least two images that were certainly taken in very different lighting conditions? I'm not sure myself on where RT gets the WB from, but I can imagine this is related to the Exif information which cannot be read from CR3 files (yet).

**Comment by itsmark166** [comment]
Yes, I had wondered if it was related to the exif information but was unable to check this out - internet searches go no further than linking exif to aperture, iso, shutter speed. RT is showing the exif information for the jpegs but the white balance values remain the same for all jpeg images (although slightly different to the value that RT is coming up with for the raw file). For a while I had a canon M50 which is also .CR3 files. RT would not give the exif info for the raw files but didn't come up with a message saying 'exif info not available' which is what happens with R6 files. White balance was read correctly for the M50 files

I've only had the R6 for 5 months and have been making do with the Canon DPP4 software which hides white balance information from you. The pictures look fine (if over done as Canon seems to like)  so I guess it is reading the information ok. In this software if you click on 'temperature' in the white balance options it defaults to 5200 so you cannot see the camera value. Dreadful software that takes up huge resources for doing not much!

Github won't let me upload a raw file - can you advise how to do this? Says it is unsupported format and a zip version is too big at 25Mb


![IMG_0063](https://user-images.githubusercontent.com/78375002/106509321-63c32380-64c5-11eb-8c94-2064fa540045.JPG)

![_MG_0118](https://user-images.githubusercontent.com/78375002/106509655-cddbc880-64c5-11eb-8a84-050b5d6328ca.JPG)


First one is a very bright day and the second a very gloomy day. Hopefully this will show you the behaviour I am seeing.

Thanks for the reply. I appreciate it.

Mark

**Comment by Thanatomanic** [comment]
@itsmark166 You can try using https://filebin.net or https://www.file.io to share large files

**Comment by heckflosse** [comment]
> Github won't let me upload a raw file - can you advise how to do this? Says it is unsupported format and a zip version is too big at 25Mb

Upload to filebin.net and post the link

**Comment by heckflosse** [comment]
@Thanatomanic was a minute faster ;-)

**Comment by itsmark166** [comment]
p.s. I realise that the .CR3 file format is a bit of nightmare. For ages I thought my M50 was a useless camera - in DPP4 the images looked sort of smeared out. Not pretty. It was only once RT got to be able to open them that I realised they were quite good images!

https://filebin.net/fe6dh1660hcfghfy

https://filebin.net/snck0gvd50e0scaj

Raw files! that is a handy tool. Thanks for sharing that bit of knowledge with me. 

Cheers

**Comment by Thanatomanic** [comment]
In verbose mode I get this:
```
Loading Canon EOS R6 image from O:\Fotos dev\RAWTest\6089\_MG_0118.CR3...
(...)
cam_mul:[0.000000 1.000000 0.000000 0.000000], AsShotNeutral:[0.000000 1.000000 0.000000 0.000000]
pre_mul:[1.000000 0.472506 0.676417 0.472506], scale_mul:[4.129489 1.951209 2.793258 1.951209], cblack:[512.000000 512.000000 512.000000 512.000000]
rgb_cam:[ [ 1.747137 -0.179389 0.001763], [-0.848595 1.655280 -0.607484], [0.101458 -0.475891 1.605721] ]
Raw As Shot White balance: temp 6464.412689, tint 0.968395
Load O:\Fotos dev\RAWTest\6089\_MG_0118.CR3: 283215 usec
cam_mul:[0.000000 1.000000 0.000000 0.000000], AsShotNeutral:[0.000000 1.000000 0.000000 0.000000]
pre_mul:[1.000000 0.438074 0.539893 0.438074], scale_mul:[4.129489 1.809022 2.229481 1.809022], cblack:[512.000000 512.000000 512.000000 512.000000]
rgb_cam:[ [ 1.747137 -0.179389 0.001763], [-0.848595 1.655280 -0.607484], [0.101458 -0.475891 1.605721] ]
Raw Reference white balance: temp 8284.503937, tint 1.067959, multipliers [1.903198 2.004031 2.695749 | 1.984654 2.486521 2.140646]
(...)
Loading Canon EOS R6 image from O:\Fotos dev\RAWTest\6089\IMG_0063.CR3...
(...)
cam_mul:[0.000000 1.000000 0.000000 0.000000], AsShotNeutral:[0.000000 1.000000 0.000000 0.000000]
pre_mul:[1.000000 0.472506 0.676417 0.472506], scale_mul:[4.129489 1.951209 2.793258 1.951209], cblack:[512.000000 512.000000 512.000000 512.000000]
rgb_cam:[ [ 1.747137 -0.179389 0.001763], [-0.848595 1.655280 -0.607484], [0.101458 -0.475891 1.605721] ]
Raw As Shot White balance: temp 6464.412689, tint 0.968395
Load O:\Fotos dev\RAWTest\6089\IMG_0063.CR3: 314484 usec
cam_mul:[0.000000 1.000000 0.000000 0.000000], AsShotNeutral:[0.000000 1.000000 0.000000 0.000000]
pre_mul:[1.000000 0.498144 0.692998 0.498144], scale_mul:[4.129489 2.057081 2.861729 2.057081], cblack:[512.000000 512.000000 512.000000 512.000000]
rgb_cam:[ [ 1.747137 -0.179389 0.001763], [-0.848595 1.655280 -0.607484], [0.101458 -0.475891 1.605721] ]
Raw Reference white balance: temp 6279.636383, tint 1.067223, multipliers [2.066515 1.838175 1.970455 | 1.984654 1.937168 1.882510]
```

I get exactly the same white balance when opening Canon R6 files from other sources. Actually, also the same white balance when opening Canon R5 shots. Like this one:
```
Loading Canon EOS R5 image from O:\Fotos dev\RAWTest\Canon - Canon EOS R5 - 3_2.CR3...
(...)
cam_mul:[0.000000 1.000000 0.000000 0.000000], AsShotNeutral:[0.000000 1.000000 0.000000 0.000000]
pre_mul:[1.000000 0.463878 0.762843 0.463878], scale_mul:[4.129230 1.915457 3.149954 1.915457], cblack:[511.000000 511.000000 511.000000 511.000000]
rgb_cam:[ [ 1.535096 -0.173338 -0.013738], [-0.554577 1.652719 -0.453483], [0.019481 -0.479381 1.467221] ]
Raw As Shot White balance: temp 6464.412689, tint 0.968395
Load O:\Fotos dev\RAWTest\Canon - Canon EOS R5 - 3_2.CR3: 569825 usec
cam_mul:[0.000000 1.000000 0.000000 0.000000], AsShotNeutral:[0.000000 1.000000 0.000000 0.000000]
pre_mul:[1.000000 0.522803 0.893723 0.522803], scale_mul:[4.129230 2.158772 3.690389 2.158772], cblack:[511.000000 511.000000 511.000000 511.000000]
rgb_cam:[ [ 1.535096 -0.173338 -0.013738], [-0.554577 1.652719 -0.453483], [0.019481 -0.479381 1.467221] ]
Raw Reference white balance: temp 5644.969940, tint 1.051800, multipliers [2.134739 1.780721 1.684671 | 2.014563 1.719542 1.787501]
```

(edited) So values between camera's seem to be different (which makes sense), but the `Raw As Shot White balance` is still identical.

**Comment by itsmark166** [comment]
Well, at least I am not making it up! So it is definitely reading the white balance from the shot as the same. I don't understand what the raw reference white balance values are? They vary from image to image but obviously don't affect what RT displays to me.
M

**Comment by itsmark166** [comment]
Can anyone tell me what might happen now? I think raw therapee depends on the skill of a group of volunteers who might well be pre-occupied with other things. The issues listed seem more of a wish list than bug reports.
Is it just a case of waiting to see if someone with the technical expertise required sees this report and has time to fix it? I imagine that working out canon code from raw files is extremely difficult and is very time consuming.
Thanks in advance.

**Comment by Thanatomanic** [comment]
As you say, it depends on who wants to spend time to fix this issue. All issues are seen, not all are commented on, and with only ~2,5 developers we cannot fix everything and do some cherry picking.

That being said, I suppose this issue can only be fixed after we have access to all metadata in the CR3 files, which will only happen after exiv2 supports it (happens soon) and we transition to using exiv2 (happens soon after).

**Comment by itsmark166** [comment]
2 to 5 developers? Wow, their commitment is amazing. I thought there were 10s of people working on it. Are there lots of people who take the code away and adapt it for themselves?  Is there a way of contributing financially? I don't use all of the features of the software as I am more a photographer than image processor but to have something for free that is better in many ways to camera raw/lightroom is simply amazing.  Inevitably there are things that we might all like RT to do but I'm not adding them here as I feel that this should be a bug report only page.

**Comment by Thanatomanic** [comment]
Hi @itsmark166, unless contributing financially is on the order of a year's salary, I don't think this will help much to speed up development 😉 

As for your request, just stay tuned. A lot will still happen this year.

**Comment by ThorNielsen** [comment]
I've also experienced the same issue with a strong colour cast from most R6 RAW files. It turned out to be very simple to read the white balance -- I've pasted a patch below which fixes the problem.

```
From 04465a214d65fe77713e529c5dce3b99cda67528 Mon Sep 17 00:00:00 2001
From: Thor Gabelgaard Nielsen <email.hidden@example.org>
Date: Thu, 30 Dec 2021 15:36:36 +0100
Subject: [PATCH] Add support for reading Canon R6 white balance from CR3.

---
 rtengine/dcraw.cc | 14 ++++++++++++++
 1 file changed, 14 insertions(+)

diff --git a/rtengine/dcraw.cc b/rtengine/dcraw.cc
index 07586bc3e..e9d9c54f0 100644
--- a/rtengine/dcraw.cc
+++ b/rtengine/dcraw.cc
@@ -6061,6 +6061,20 @@ get2_256:
       offsetChannelBlackLevel2 = save1 + (0x0149 << 1);
       offsetWhiteLevels = save1 + (0x031c << 1);
       break;
+
+    case 3656: // EOS R6, ColorDataSubVer 33
+      // imCanon.ColorDataVer = 10;
+      imCanon.ColorDataSubVer = get2();
+
+      // The constant 0x0055 was found in LibRaw; more specifically by
+      // spelunking in LibRaw:src/metadata/canon.cpp.
+      fseek(ifp, save1 + (0x0055 << 1), SEEK_SET);
+      FORC4 cam_mul[c ^ (c >> 1)] = (float)get2();
+
+      offsetChannelBlackLevel = save1 + (0x326 << 1);
+      offsetChannelBlackLevel2 = save1 + (0x157 << 1);
+      offsetWhiteLevels = save1 + (0x32a << 1);
+      break;
     }
 
     if (offsetChannelBlackLevel)
-- 
2.25.1
```

**Comment by itsmark166** [comment]
Thank you very much. Unfortunately I do not have the knowledge or skill to
know what to do with what you have sent me! I would love to be able to use
Raw Therapee with my R6 files but I think I will have to wait a while
longer unless someone can release a version with your adaptation already in
the programme.

Best wishes

Mark

**Comment by ThorNielsen** [comment]
Hi Mark,
Unfortunately I'm unable to make a Windows build for you as I'm on Linux. However next year (i.e. tomorrow ☺), I will try to make a pull request (just have to figure those out), so this fix can be included in the official release.

By the way, I see in your first screenshots that you are also missing the EXIF data. That has already been fixed in the branch metadata-exiv2, and works fine for me with an R6 -- but I'm not sure what's currently happening to that (except for the fix above I'm not involved in development of RawTherapee).

**Comment by itsmark166** [comment]
Thanks again. I hope a new version will be out soon! However, I understand
it all relies on the efforts of a very few people (who don't earn any money
from this) so I know I have to be patient. I wish I had the skills to
contribute and also wish canon were not such a pain in the **** when it
comes to their raw files!
I mainly use my A7iii and those files are perfect in Raw Therapee. The R6
has much better eye and tracking focus so I use it for running dog pictures
and other action shots.


best wishes

Mark

**Comment by ThorNielsen** [comment]
Hi again, @itsmark166, I just wanted to let you know that I've made a pull request (#6397) with the appropriate changes, so hopefully it will be merged and soon available in a development version.
