### ISSUE TITLE
capture sharpening creates double lines

### ISSUE THREAD

**Issue by ff2000** [Beep6581/RawTherapee#6094]
I really like how capture sharpening can recover crisp details in many shots.
Unfortunately with contrasty edges it tends to produce double lines. E.G. shooting a branch against white snow:
![Screenshot_20210205_101720](https://user-images.githubusercontent.com/1973708/107007830-bc334300-679b-11eb-8b58-ba6144966a4a.jpg)
As I shoot a lot of HighRes now with my OLY I need the power of Capture sharpening to fix the general blurriness of the RAW files...
![Screenshot_20210205_102248](https://user-images.githubusercontent.com/1973708/107008667-b9851d80-679c-11eb-8417-c364f293b152.jpg)

I can reduce that effect by dialing down the radius and/or the iterations, but it also greatly reduces the sharpness of the resulting image.

**Comment by Thanatomanic** [comment]
I believe this comes down to: for any automagic tool, you have to make a compromise somewhere. The automatic radius finds a value that is pretty large (> 1 px) which results in an overshoot of the sharpening and a darkening of edges. This is a known result of the underlying sharpening algorithm. Unless @heckflosse says otherwise, I think the only thing that we _might_ do here, is fine-tune the automatic radius code a bit. The algorithm itself is sound.

**Comment by ff2000** [comment]
This is with a small diameter (0.6):
![Screenshot_20210205_120412](https://user-images.githubusercontent.com/1973708/107019402-484c6700-67aa-11eb-8cbb-42a1e0b33ca7.jpg)
RAW file: https://www.dropbox.com/s/vkdki4i9f6i03nq/P2010311.ORF?dl=0

HiRes with 0.85:
![Screenshot_20210205_121039](https://user-images.githubusercontent.com/1973708/107020159-328b7180-67ab-11eb-99d1-330ba21a561e.jpg)
RAW file: https://www.dropbox.com/s/ife1579nxmc78b6/P2010323.ORF?dl=0

I do not think it entirely is the fault of the radius. As it looks to me I have a gradient getting lighter towards the bright snow. CS enhances the overall contrast of that gradient, but also sees the edge of the trunk and creates a strong contrast leading to a black line between the snow and the trunk.

**Comment by TechXavAL** [comment]
It seems to me that a big part of this problem comes from the Iterations set.

By default there are 20 iterations and auto-limit is turned on. Even if usually this is all you need, there are situations (and I think this is one of them) where you may wish to lower that number to something between 8 and 12 (by trial and error).

Think about iterations as sharpening the sharpened image a number of times: the artifacts are quickly piled on top of previous ones, making them too obvious.

You may have to do this at the same time as lowering radius enough to prevent oversharpening (white and/or black haloing, and too obious jagged lines).

With really difficult images you will have to check again and again until you find a sweet spot.

HTH.

**Comment by heckflosse** [comment]
@ff2000 Can you provide a raw? I would like to test something...

**Comment by Thanatomanic** [comment]
@heckflosse The last post with images contains links to the RAW files

**Comment by heckflosse** [comment]
Oh, must have been blind :-(

**Comment by ff2000** [comment]
The second post contains links to RAW files.
Here is the RAW file from the first post:
https://www.dropbox.com/s/jnjbccyxsguicme/P1120122.ORF?dl=0
And the Non-HighRes .ori file:
https://www.dropbox.com/s/3ijp8wvsny68hoi/P1120122.ORI?dl=0
Might be interesting as it was a quite foggy day and the tree is covered in snow and fog (hence generally little sharpness), also it shows the strongest halo.

Here is another one that shows the effect inverted:
![Screenshot_20210205_180126](https://user-images.githubusercontent.com/1973708/107057476-2f5ca980-67dc-11eb-94f3-bd3b8d4c9e71.jpg)
https://www.dropbox.com/s/2u53uktqcp9qqog/P2010332.ORF?dl=0
And pp3:
https://www.dropbox.com/s/1dbxtfr7rki8ot8/P2010332.ORF.pp3?dl=0

**Comment by heckflosse** [comment]
> Might be interesting as it was a quite foggy day

That's the point. The fog confuses the radius auto-calculation. Using the poor_man_dehaze branch you see 3 black levels in console when opening a raw. If you set them in gui, you get a much better radius auto-calculation for this foggy shots.

![grafik](https://user-images.githubusercontent.com/13733487/107066781-abf08780-67de-11eb-855d-505024e92d2f.png)

**Comment by heckflosse** [comment]
Just for fun another example what you can get by using the `poor_man_dehaze` black levels on hazy shots.
Distance to subject was about 7 to 10 km. Left neutral profile, right with `poor_man_dehaze` black levels
![grafik](https://user-images.githubusercontent.com/13733487/107073345-8c119180-67e7-11eb-9d56-9da3d619eaad.png)

**Comment by TechXavAL** [comment]
@heckflosse : I can't wait for this tool to be merged into dev :smile: 

@ff2000 : those are my attempts with other CS settings. I've applied a heavy defringing, too. Adjust contrast and lightness to taste.

![P1120122](https://user-images.githubusercontent.com/52250392/107075044-ddbb1b80-67e9-11eb-8003-2678b3c2aaa4.jpg)
[P1120122.jpg.out.pp3.zip](https://github.com/Beep6581/RawTherapee/files/5934594/P1120122.jpg.out.pp3.zip)


![P2010311](https://user-images.githubusercontent.com/52250392/107075139-fe837100-67e9-11eb-86d9-a78b1a287e91.jpg)
[P2010311.jpg.out.pp3.zip](https://github.com/Beep6581/RawTherapee/files/5934596/P2010311.jpg.out.pp3.zip)


![P2010323](https://user-images.githubusercontent.com/52250392/107075162-07744280-67ea-11eb-8431-f75c2026d9e2.jpg)
[P2010323.jpg.out.pp3.zip](https://github.com/Beep6581/RawTherapee/files/5934598/P2010323.jpg.out.pp3.zip)


![P2010332](https://user-images.githubusercontent.com/52250392/107075184-0f33e700-67ea-11eb-954a-c28583c410fb.jpg)
[P2010332.jpg.out.pp3.zip](https://github.com/Beep6581/RawTherapee/files/5934599/P2010332.jpg.out.pp3.zip)

I was more interested in good CS settings, as it seems to be your doubt, but most probably I would have fully processed those images differently. Anyway, hope it helps.

**Comment by ff2000** [comment]
> > Might be interesting as it was a quite foggy day
> 
> That's the point. The fog confuses the radius auto-calculation. Using the poor_man_dehaze branch you see 3 black levels in console when opening a raw. If you set them in gui, you get a much better radius auto-calculation for this foggy shots.
> 
> ![grafik](https://user-images.githubusercontent.com/13733487/107066781-abf08780-67de-11eb-855d-505024e92d2f.png)

The only foggy shot was P1120122.ORF - all other shots had the tree surrounded by absolutely no fog, subjects stood clear in the field. And I do not want to get rid of the fog by dehazing. The High Res Shots generally look a bit foggy/hazy. It's 80MP due to the Algo (shifting/blending 8 shots), Oly somewhere states that one should scale them down to 40/50MP. And after that (with proper sharpening) the images IMO look great. (I just mention this in case the appearance confused you).

It took me some time now to test the suggestions due to limited time on my dad's PC. And as I already saw before limiting radius/iterations reduces the sharpening to an amount that is barely visible. As I already said I love how CS can pull out details, everything about it in these shots is great, it's just with these single high-contrast branches where it produces Halos.

As it seems this is a corner case I will now just make 2 conversions and blend them in Gimp.
