### ISSUE TITLE
Processing profile created at the wrong place

### ISSUE THREAD

**Issue by polezhaevdmi** [Beep6581/RawTherapee#6100]
Found the RT 5.8 saves processing profile file near the image, despite of corresponding setting. Look at the image, please, the desired (for me) settings are set. As for me, I need no extra profiles at all: the <IMAGE>.pp3 file, which is near to RAW and defines the 'development' - is completely OK.
Tried to run RT as Administrator (assuming the cache is unavailable for write) - the effect remaining the same.
Tried to 'massage setting': change the output profile setting to another, save, change back, save again. In vain.

Could any try to reproduce the effect to confirm the issue is found? Thank You!

<img width="677" alt="rt01" src="https://user-images.githubusercontent.com/29210645/107276205-5a086580-6a5b-11eb-84ab-5f0fe89a9040.png">

----- OS Info --------
Edition	Windows 10 x64
Version	20H2
OS build	19042.789

------- RT Info --------
[AboutThisBuild.txt](https://github.com/Beep6581/RawTherapee/files/5946653/AboutThisBuild.txt)

**Comment by Thanatomanic** [comment]
I cannot reproduce on my end, same configuration. What happens when you remove `IMG_9410.CR2.pp3` and open the `IMG_9410.CR2` again from RT?

![image](https://user-images.githubusercontent.com/6567747/107280621-dbaac400-6a58-11eb-9191-18f49a4cd22c.png)

**Comment by polezhaevdmi** [comment]
@Thanatomanic, You are great! The development settings are restored, IMG_9410.CR2.pp3 file is not appeared during RAW to TIFF development. The IMG_9410.CR2.pp3 was re-created when I saved the processing parameters. 
I continued:
- The .tif.out.pp3 and .cr2.pp3 files were deleted - the settings restored (from cache file);
- The .tif.out.pp3 and cache .cr2.*.pp3 files were deleted + the .cr2.pp3 file put near to RAW - the settings restored;
- All three files deleted - the settings were reset.
- The cache .cr2.*.pp3 was deleted, the .tif.out.pp3 and .cr2.pp3 profiles are different - the .cr2.pp3 took priority.

Thus, now RT looks for THREE files, and it is still possible to use generated .cr2.pp3 files as development profile.
Sorry for the disturbance, if no ideas will be generated, I'll close the issue. However, the .tif.out.pp3 file still looks unnecessary...

**Comment by Lawrence37** [comment]
The *.tif.out.pp3 files are generated when you save an image and will always be saved in the same directory. If you don't the .pp3, make sure to uncheck the "Save processing parameters with image" option in the [save dialog](http://rawpedia.rawtherapee.com/File:Save_window.png).

**Comment by polezhaevdmi** [comment]
Yes, I may skip the *.tif.out.pp3 during individual file processing, but I'm not able to do the same during batch (which I using) processing session. In my RT workflow (which I used with pre-5.8 RT) the initial 'recipe' files *.cr2.pp3 were compiled with RTProfileSelector, during the 'preparing to develop' all changes are stored in the same files, which were automatically used to batch develop all RAWs to TIFF (the iterations at that phase are also possible). The presence of  TWO profile files per RAW in the same folder, IMO, is not a mistake-proof approach. 
@Lawrence37, from the other hand, if I save the developed file via save dialog and the setting "Save processing parameters with image" does exist here, why that setting was not made 'global' (and place it in the RT settings)? And, seems, the proposition, finally, exists: please, if possible, add the global parameter like "Output Profile placement" := {Near Output file, Near Input File, Profile Cache, None} or simple checkbox (like in save dialog).

Anyway, as the logics of recipe file relationship is discussed and clear now, now the workaround looks simple (however, not convenient) for me: do not forget to delete *.tif.out.pp3 on RT exit after each batch conversion.

**Comment by Lawrence37** [comment]
When you say batch conversion, are you talking about the queue? If so, the queue also has the "Save processing parameters with image" option. As for why the setting is not in preferences, I don't know the original reason. To me, it makes sense because you may want to save the pp3 for some images but not others. It would be a hassle to have to go into preferences every time. Also, I think the option defaults to the most recent setting, so you can uncheck it once and leave it.

**Comment by polezhaevdmi** [comment]
@Lawrence37, You are great, many thanks! Exactly. My fault: I'm did not investigate all possible places in RT. Sorry for waste Your and @Thanatomanic time.
After deselection RT behavior changed as desired.

<img width="964" alt="rt03" src="https://user-images.githubusercontent.com/29210645/107544133-90b4bc00-6bd2-11eb-942f-a979db8d70b7.png">
