### ISSUE TITLE
How to keep all pp3 files in a single folder?

### ISSUE THREAD

**Issue by Nicknroll** [Beep6581/RawTherapee#6110]
Can't figure out how to keep all pp3 files in a single folder instead of autosaving them in a root folder alongside with images. 
Is there some option for this?

**Comment by Thanatomanic** [comment]
Hi, the whole idea behind the pp3 files is that they are _sidecar_ files, which should belong together with your images. If you do not care about that, or dislike that idea, there is an option in Preferences to store pp3 files in the cache. I'm not a 100% sure how well the cache handles files with identical names.

![image](https://user-images.githubusercontent.com/6567747/107755101-a89b5580-6d22-11eb-8779-569c75bac092.png)

**Comment by Nicknroll** [comment]
Hi!
Great, i somehow missed this option, thank you!
I guess this is a good idea for photography series to keep files together, but in my case, for renderings, i add/move/delete a lot of files in a same folder, so in the end it appears like a mess.
