### ISSUE TITLE
Local adjustments Blur & Noise radius > 1.5 increases saturation

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#6117]
left radius 1.5, right radius 1.6
![grafik](https://user-images.githubusercontent.com/13733487/108204953-ba1a9e00-7124-11eb-842e-959b52164e1a.png)

**Comment by Desmis** [comment]
@heckflosse 

Ingo

There was an (old) bug...
I think this branch  "lablurbug" solve the problem
https://github.com/Beep6581/RawTherapee/tree/lablurbug

Jacques

**Comment by Lawrence37** [comment]
Fix confirmed.
