### ISSUE TITLE
make iplocallab.cc a cppcheck and also -Wdouble-promotion clean

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#6119]
I would like to make iplocallab.cc a bit more cppcheck clean at the weekend.
@Desmis Jacques, can you avoid changes to iplocallab.cc until monday?

**Comment by Desmis** [comment]
@heckflosse 
Ingo

No problem at all 

In addition, I would not be available for a week, because my family is coming to visit us in Fréjus.

jacques

**Comment by heckflosse** [comment]
@Desmis 
> my family is coming to visit us in Fréjus.

lucky you. In Germany that's not allowed atm

**Comment by Desmis** [comment]
@heckflosse 
Ingo

Yes, but before,  all my family do an anti covid test
jacques

**Comment by heckflosse** [comment]
I changed the topic title because I will try now to make iplocallab.cc also -Wdouble-promotion clean
