### ISSUE TITLE
Local Adjustments: Spot outline stays visible when turning of the module.

### ISSUE THREAD

**Issue by ghost** [Beep6581/RawTherapee#6124]
**Short description**
The outline of the spot area stays visible when turning off the module.

**Steps to reproduce**
1. Activate *Local Adjustments* module,
2. Add an instance (default ellipse spot outline becomes visible),
3. (Extra) Add tool (Color & light, but any will do),
4. (Extra) Turn on *Preview delta E*,
5. Deactivate the module.

At this point the module should be completely inactive, but the spot area outline is still visible. It is also possible to move around and change the area when the module is turned off.

I added steps 3 and 4 to show that the *Preview delta E* **is** turned off.

**Expected behavior**
Everything related to this module to be turned off / inactive when the module is turned off.

**Screenshot**
The module is turned off in this screenshot:
![la off](https://user-images.githubusercontent.com/56407344/108684424-cb7bf580-74ea-11eb-8b70-62784834f4ff.png)

**Platform**

* OS                : Linux (kernel 5.9.15-1)
* Distro            : Debian Buster (rel. 10.8)
* Graphics driver   : nvidia (460.39)

**Hardware**

* CPU              : AMD Ryzen 5 3600 6-Core Processor
* GPU              : GeForce RTX 2060 SUPER 7979 MiB
* Memory           : 32 Gb + 15 Gb Swap

**Build info**

* Compiler      : gcc 8.3.0
* Cmake         : 3.13.4
* Glib          : 2.58.3-2

**Additional context**

* RawTherapee version : 5.8-2801-gd6c826519
* Basic pull+build.
* (Extra) Optimization  : None
* Cmake options used:
    -DCMAKE_BUILD_TYPE="release"  \
    -DBUNDLE_BASE_INSTALL_DIR="$HOME/.local/rawtherapee" \
    -DCACHE_NAME_SUFFIX="5-dev" \
    -DPROC_TARGET_NUMBER="2" \
    -DBUILD_BUNDLE="ON" \
    -DOPTION_OMP="ON" \
    -DWITH_LTO="OFF" \
    -DWITH_SAN="OFF" \
    -DWITH_SYSTEM_KLT="OFF"

**Comment by Thanatomanic** [comment]
@jade-nl See also https://github.com/Beep6581/RawTherapee/issues/5811 which describes another downside of this

**Comment by ghost** [comment]
Closing this one.

Basically a duplicate of #5811.
