### ISSUE TITLE
Error with Msys2

### ISSUE THREAD

**Issue by Desmis** [Beep6581/RawTherapee#6129]
I tried to update msys2

command line
$ pacman -Syuu

and I get...
jacques@pc-bureau MSYS ~
$ pacman -Syuu
:: Synchronisation des bases de données de paquets…
 mingw32                                        894,4 KiB   311 KiB/s 00:03 [##########################################] 100%
 mingw32.sig                                    438,0   B  0,00   B/s 00:00 [##########################################] 100%
erreur : mingw32 : la clé « 4A6129F4E4B84AE46ED7F635628F528CF3053E04 » est inconnue
:: Importer la clé PGP 4A6129F4E4B84AE46ED7F635628F528CF3053E04 ? [O/n] O
erreur : mingw32 : la signature de « David Macek <david.macek.0@gmail.com> » est de confiance inconnue
erreur : la mise à jour de mingw32 a échoué (base de données non valide ou corrompue (signature PGP))
 mingw64                                        897,7 KiB   308 KiB/s 00:03 [##########################################] 100%
 mingw64.sig                                    438,0   B  0,00   B/s 00:00 [##########################################] 100%
erreur : mingw64 : la signature de « David Macek <david.macek.0@gmail.com> » est de confiance inconnue
erreur : la mise à jour de mingw64 a échoué (base de données non valide ou corrompue (signature PGP))
 msys                                           300,4 KiB   294 KiB/s 00:01 [##########################################] 100%
 msys.sig                                       438,0   B  0,00   B/s 00:00 [##########################################] 100%
erreur : msys : la signature de « David Macek <david.macek.0@gmail.com> » est de confiance inconnue
erreur : la mise à jour de msys a échoué (base de données non valide

What I missed ?
Jacques

**Comment by adamreichold** [comment]
Maybe your [keyring](https://www.msys2.org/dev/keyring/) is out of date? Could you try updating only the package `msys2-keyring` first?

**Comment by Desmis** [comment]
Excuse my bad knowledge...

What you mean , is it ?
$ pacman -Syu msys2-keyring 
If it's true...does not work...

jacques

**Comment by adamreichold** [comment]
I think it would be
```
pacman -Sy msys2-keyring
```
but I did not use Pacman in the recent past so YMMV.

**Comment by Desmis** [comment]
I tried with these informations

https://www.msys2.org/news/

Big update...but nothing work....(no update)...

Jacques

**Comment by adamreichold** [comment]
The steps described in https://www.msys2.org/news/#2020-06-29-new-packagers look reasonable, i.e. manually downloading `msys2-keyring` using `curl`.

**Comment by Thanatomanic** [comment]
@Desmis I remember having the same problem some time ago, but indeed @adamreichold 's linked solution worked for me

**Comment by Desmis** [comment]
@Thanatomanic  @adamreichold 

I tried another time....with all the steps

Msys2 says me all is update...
But when I compile i have this message

-- Git checkout information:
--     Commit description:    5.8-2780-g902fdbd6c
--     Branch:                lagrain
--     Commit:                902fdbd6c
--     Commit date:           2021-02-23
--     Commits since tag:     2699
--     Commits since branch:  2699
--     Version (unreliable):  5.8.2699
-- Build information:
--     Build OS:              MINGW64_NT-6.2-9200 3.1.7-340.x86_64 x86_64
--     Build date:            Tue, 23 Feb 2021 10:02:03 +0000 UTC
--     Epoch:                 1614074523
--     UUID:                  bdb98353-8d0e-4394-a13f-790b64527a71
-- CACHE_NAME_SUFFIX is "5-dev"
[  0%] Built target UpdateInfo
[  4%] Built target rtexif
Scanning dependencies of target rtengine
[  5%] Building CXX object rtengine/CMakeFiles/rtengine.dir/dcrop.cc.obj
[  6%] Building CXX object rtengine/CMakeFiles/rtengine.dir/diagonalcurves.cc.obj
[  6%] Building CXX object rtengine/CMakeFiles/rtengine.dir/dual_demosaic_RT.cc.obj
[  6%] Building CXX object rtengine/CMakeFiles/rtengine.dir/dirpyr_equalizer.cc.obj
[  7%] Building CXX object rtengine/CMakeFiles/rtengine.dir/dynamicprofile.cc.obj
[  7%] Building CXX object rtengine/CMakeFiles/rtengine.dir/eahd_demosaic.cc.obj
[  7%] Building CXX object rtengine/CMakeFiles/rtengine.dir/EdgePreservingDecomposition.cc.obj
[  8%] Building CXX object rtengine/CMakeFiles/rtengine.dir/fast_demo.cc.obj
In file included from C:/msys64/mingw64/include/atkmm-1.6/atkmm/object.h:30,
                 from C:/msys64/mingw64/include/gtkmm-3.0/gtkmm/widget.h:35,
                 from C:/msys64/mingw64/include/gtkmm-3.0/gtkmm/action.h:31,
                 from C:/msys64/mingw64/include/gtkmm-3.0/gtkmm/toggleaction.h:29,
                 from C:/msys64/mingw64/include/gtkmm-3.0/gtkmm.h:108,
                 from G:/code/repo-rtdev1/rtgui/cursormanager.h:21,
                 from G:/code/repo-rtdev1/rtgui/editcallbacks.h:22,
                 from G:/code/repo-rtdev1/rtengine/dcrop.cc:34:
C:/msys64/mingw64/include/atkmm-1.6/atkmm/component.h:5:10: fatal error: atkmmconfig.h: No such file or directory
    5 | #include <atkmmconfig.h>
      |          ^~~~~~~~~~~~~~~
make[2]: *** [rtengine/CMakeFiles/rtengine.dir/build.make:368: rtengine/CMakeFiles/rtengine.dir/dcrop.cc.obj] Error 1
make[2]: *** Waiting for unfinished jobs....
compilation terminated.
make[1]: *** [CMakeFiles/Makefile2:235: rtengine/CMakeFiles/rtengine.dir/all] Error 2
make: *** [Makefile:149: all] Error 2

**Comment by heckflosse** [comment]
> C:/msys64/mingw64/include/atkmm-1.6/atkmm/component.h:5:10: fatal error: atkmmconfig.h: No such file or directory
5 | #include <atkmmconfig.h>

cmake and make from scratch in a fresh build dir

**Comment by Desmis** [comment]
@heckflosse 
Ingo

With a new build
All works fine
Now I am with gcc 10.2

Thank you very much
jacques
