### ISSUE TITLE
Segfault in wavelet/denoise

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#6140]
To reproduce:

1) open http://rawtherapee.com/shared/test_images/clematis_vitalba.nef
2) apply the attached .pp3 file
3) enable Denoise and Refine
![grafik](https://user-images.githubusercontent.com/13733487/109317718-47f53800-784d-11eb-9be7-69fb113e00c6.png)

=> segfault

[clematis_vitalba.nef.zip](https://github.com/Beep6581/RawTherapee/files/6050511/clematis_vitalba.nef.zip)

**Comment by arturoisilvia** [comment]
I can't reproduce on a new pp3.
With your clematis_vitalba.nef.pp3 (versión: AppVersion=5.8-2782-g4f880b346)  makes crash in any photo. ok.

But with new pp3: (My versión is AppVersion=5.8-2776-gf72747771) no crash.

Won't you get your pp3 corrupt? or have you tried from a neutral profile?

**Comment by heckflosse** [comment]
@arturoisilvia I tested again on dev with a new pp3 from dev. Still crashes. Anyway, if a corrupted pp3 would lead to a crash, that also would need to be fixed. With the pr it's fixed.

Edit: the bug was that the decomposition of Lab a and b channels had more wavelet levels than the decomposition of the Lab L channel.
