### ISSUE TITLE
Undocumented search feature in exif tab can be annoying

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#6142]
In the exif tab the search feature (which is not documented in rawpedia) is enabled.
Example to reproduce
1) Open an image
2) switch to exif (metadata) tab
3) Expand for example the `Exif` tree
4) press the f-key 
=> for example the tag FNumber will be selected

That can be nice, but that also can be very annoying.

Assume your image is opened in 1:1 view, you want to look something in exif tab and then want to zoom out to fit to screen.
Because the exif tab is selected and has focus, the search kicks in when you press the f-key instead of zooming out to fit to screen.

Perhaps someone has an idea to make this less annoying.

**Comment by TechXavAL** [comment]
Maybe setting off the search feature by default, and only enable it after hitting the slash («**/**») key, same as you have in Firefox browser.

Another option would be using the «Ctrl+f» shortcut while having the Exif tree focused, although this may be confusing, as it is a key combo already used in the File Browser

**Comment by heckflosse** [comment]
> Another option would be using the «Ctrl+f» shortcut while having the Exif tree focused

Cool, that would be a one line code change :+1:

**Comment by heckflosse** [comment]
We should document ctrl-f functionality. It also works in Folders view by default if Folders view has focus :grinning:

**Comment by TechXavAL** [comment]
Pinging @Beep6581 

I will add it to the Spanish documentation

**Comment by heckflosse** [comment]
I suggest to disable the `automatic` search in Exif tab. If someone needs it, a ctrl-f will do it.

**Comment by heckflosse** [comment]
Suggested patch:

```diff
diff --git a/rtgui/exifpanel.cc b/rtgui/exifpanel.cc
index 6fc79d004..eeff0c8c7 100644
--- a/rtgui/exifpanel.cc
+++ b/rtgui/exifpanel.cc
@@ -42,7 +42,7 @@ ExifPanel::ExifPanel() :
     exifTree->set_headers_visible (false);
     exifTree->set_rules_hint (false);
     exifTree->set_reorderable (false);
-    exifTree->set_enable_search (true);
+    exifTree->set_enable_search (false);
     exifTree->get_selection()->set_mode (Gtk::SELECTION_MULTIPLE);
     scrolledWindow->set_shadow_type (Gtk::SHADOW_NONE);
     scrolledWindow->set_policy (Gtk::POLICY_ALWAYS, Gtk::POLICY_ALWAYS);

```

**Comment by heckflosse** [comment]
Any objections to commit the patch?

**Comment by Thanatomanic** [comment]
Seems all right :+1:

**Comment by Beep6581** [comment]
> Pinging @Beep6581
> 
> I will add it to the Spanish documentation

**Comment by Beep6581** [comment]
> Pinging @Beep6581
> 
> I will add it to the Spanish documentation

Hey @TechXavAL 

Where have you documented it? Seems there have been no edits to Keyboard Shortcuts http://rawpedia.rawtherapee.com/index.php?title=Keyboard_Shortcuts/es&action=history

**Comment by Beep6581** [comment]
@TechXavAL I updated Ctrl+f in Keyboard Shortcuts. Stay tuned for more changes - #6197

**Comment by TechXavAL** [comment]
@Beep6581 

👍🏻  The Spanish Keyboard Shortcuts page is still pending to be reviewed/finished. The current version was uploaded a long time ago, as you may see by the page title style...

Will do ASAP
