### ISSUE TITLE
Possible speedup for a loop in wavelet code

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#6143]
In wavelet code there is still one pixel-loop which uses std::pow instead of the much faster pow_F
https://github.com/Beep6581/RawTherapee/blob/dev/rtengine/ipwavelet.cc#L1393

@Desmis Jacques, can you provide a pp3 which calls this loop? I will test and optimize then.

**Comment by Desmis** [comment]
@heckflosse 
Ingo
Here a possible pp3 which call the loop 

[_D4D1775.NEF-test.txt](https://github.com/Beep6581/RawTherapee/files/6054594/_D4D1775.NEF-test.txt)
 
jacques

**Comment by heckflosse** [comment]
I measured using 
http://rawtherapee.com/shared/test_images/clematis_vitalba.nef

and the attached pp3
[clematis_vitalba.nef.zip](https://github.com/Beep6581/RawTherapee/files/6056523/clematis_vitalba.nef.zip)

```
Before: ~3080 ms
After:  ~1530 ms
```

**Comment by Desmis** [comment]
@heckflosse 
I just tested the new branch

Before = 1700 ms
After = 1100 ms

No visible differences.
Very very small differences in TIF 16 bits

Good job

Jacques
