### ISSUE TITLE
DNG file is being open with the wrong size

### ISSUE THREAD

**Issue by azevedomt82** [Beep6581/RawTherapee#6151]
I'm using a ricoh theta z1 360 camera which (with the double fish eye plugin) outputs a 1.4 DNG file that can be found in the link below:
https://u.pcloud.link/publink/show?code=kZ3ciuXZFP2GRRgNatFYDQ90BGlLqkxFaUSV

When I open the file on rawtherapee, it opens with a shorter dimension.
The original is 7296 x 3648, and and in the software says it is 7288 x 3640.

And when rendering, it doesn't goes back to the original size...

I'm using the latest version of RT and I'm on windows 10

![image](https://user-images.githubusercontent.com/79909521/109638047-72910a80-7b45-11eb-944b-14eb24b611d3.png)

thanks

**Comment by Thanatomanic** [comment]
![image](https://user-images.githubusercontent.com/6567747/109639652-b852d080-7b4f-11eb-869b-dc4ae27013dd.png)

Set this to 0 to solve your problem. This border is meant to alleviate demosaicing artifacts on regular imagery, but obviously fails for this specific purpose where the exact resolution is important.

**Comment by Thanatomanic** [comment]
Note: the info-display you highlight on the left has an update problem https://github.com/Beep6581/RawTherapee/issues/5954. If you export your image, you should be fine.
