### ISSUE TITLE
Vertical crop of sliders

### ISSUE THREAD

**Issue by rebio** [Beep6581/RawTherapee#6154]
**Short description**
Sometimes the vertical size of a control field is clipped. I wasn't able to work out any circumstances under which it happens or can be reproduced.

**Steps to reproduce**
1. Load any image
2. Go to a tool that has vertical sliders (eg. Hue/Saturation/Dynamic under the color-tab) and expand it

Now sometimes this bug happens sometimes it does not. I have no idea what causes it or was able to work out or test what could might cause it. The appearance seems random. It happend the most under the Hue/Saturation/Dynamic field, but I guess that this is more than likely because it is the one I use the most.

After some time (I also was not able to figure out how or why) the box expands and the full height is shown.
What I tried so far that didn't change the cropped field:
- scroll up and down in the box
- change the values
- turn the field off and on again

**Expected behavior**
I would expect the field to open like every other field

**Additional information**
RT:
> Version: 5.8-2802-g84751ad26 (2021-03-01 - win64)
> Branch: dev
> Commit: 84751ad26
> Commit date: 2021-03-01
> Compiler: x86_64-w64-mingw32-gcc\ 9.3.0
> Processor: generic x86
> System: Windows
> Bit depth: 64 bits
> Gtkmm: V3.24.3
> Lensfun: V0.3.2.0
> Build type: Release
> Build flags: -mwin32\ -m64\ -mthreads\ -msse2\ -std=c++11\ -mtune=generic\ -Werror=unused-label\ -Werror=delete-incomplete\ -fno-math-errno\ -Wno-attributes\ -Wall\ -Wuninitialized\ -Wcast-qual\ -Wno-deprecated-declarations\ -Wno-unused-result\ -Wunused-macros\ -fopenmp\ -Werror=unknown-pragmas\ -Wno-aggressive-loop-optimizations\ -DNDEBUG\ -O3\ -ftree-vectorize
> Link flags: -m64\ -mthreads\ -static-libgcc\ -mtune=generic\ -s\ -O3
> OpenMP support: ON
> MMAP support: ON
> Build OS: Linux 4.4.0-101-generic x86_64
> Build date: Mon, 01 Mar 2021 23:36:34 +0000 UTC
> Build epoch: 1614641794
> Build UUID: fe7b4455-0570-4fdf-95bd-0eb80bb80975

Note: I first observed this bug in 5.8 (I got more into using RT with 5.8 so it might existed for longer). I used the dev version to see if it's maybe fixed by now. I was also able to observe this bug in recent dev builds. 
But as said: It has a random appearance and I have no idea how to reproduce it. If you have any idea what I could test please let me know.

OS:
> CPU: AMD Ryzen 7 4800H with Radeon Graphics
> RAM: 32GB
> OS: Windows 10, 64-bit

UI with cropped field on the right
![UI - clipped graphs](https://user-images.githubusercontent.com/10911084/110036360-2c060080-7d3d-11eb-830d-979df6ee1829.png)

**Comment by ff2000** [comment]
I also see this issue.
As it looks I can force a repaint when hovering in the top right corner of the sliders widget.
The widget unfortunately paints over its borders after you can trigger a repaint:
![Screenshot_20210305_070902](https://user-images.githubusercontent.com/1973708/110069987-b1ab9f80-7d81-11eb-8e33-bd16fa21a40b.png)
Note how "Contrast by Detail Level" and "Haze Removal" has the "Hue" sliders as background.

This issue might be as simple as just an incorrect initial size hint.

**Comment by Thanatomanic** [comment]
Afaik, this is a very old problem for which nobody has ever found a solution. But maybe there is new insight possible from Gtk wizards in the community 😄

**Comment by Thanatomanic** [comment]
@ff2000 @rebio Please see here https://github.com/Beep6581/RawTherapee/issues/3973

**Comment by rebio** [comment]
@Thanatomanic Close as duplicate then?
In #3973 it is pretty well described how you can reproduce this bug.
And the solution is to hover over one of the small buttons on the right side.

#3973 is closed as duplicate of #3525

**Comment by Thanatomanic** [comment]
Agreed
