### ISSUE TITLE
CAC remove the purple fringing 

### ISSUE THREAD

**Issue by coldbath** [Beep6581/RawTherapee#6155]
hi, 
Recently, I used rawTherapee to handle Chromatic Aberration Correct problem, mind to remove the purple fringing(caused by Lateral Chromatic Aberration). 

The raw data type is bayer(RGGB), generate by camera, like this.
https://drive.google.com/file/d/1j5FtO0wqXWgTz1WNyVp11aH299CMdOqp/view?usp=sharing

And I modify the source code, read the raw data, execute the CAC module, get and save the new raw data.
https://drive.google.com/file/d/142ZxGP4vZ-IcvIpDOJlv_jYgCzmDi_hx/view?usp=sharing

Here is the jpgs, which transformed by the raw data:
before
![before](https://user-images.githubusercontent.com/20087254/110056842-7c5f7b80-7d9a-11eb-9633-6bad28bc8fe6.jpg)

after
![after](https://user-images.githubusercontent.com/20087254/110056870-85e8e380-7d9a-11eb-826f-faa918772bbf.jpg)

We can find that there are many red noise color generate in the after image.

Also, I have used the Defringe module to remove purple fringe on JPG, but this method may remove the real purple object and color.

Does anyone can give me some suggestion, thx so much!

**Comment by Thanatomanic** [comment]
@coldbath You use a heavy fish-eye lens _and_ you say you modified RT's source code without specifying what you changed (and why?) _and_ you modified raw data yourself (how?) _and_ you still expect the Defringe module to work well without artifacts? To be honest, I think you are kind of expecting too much from RT at that point.

I don't think this is either a bug report nor a feature request, so closing this. Maybe you'll have better luck asking your question on our support forum: https://discuss.pixls.us
