### ISSUE TITLE
LA: After choosing rectangle, it can't be put into full-image

### ISSUE THREAD

**Issue by arturoisilvia** [Beep6581/RawTherapee#6161]
It is a small design flaw. It is not very important, but it is not expected.

Open an image
Add new spot
Check on: Show additional settings
Select in RT-spot shape: Rectangle
And now, select in Spot method: Full image.

Does not change to Full image.

Version: 5.8-2807-g31641f948 win64.zip

**Comment by Thanatomanic** [comment]
Confirmed

**Comment by Desmis** [comment]
@arturoisilvia 
I just push a commit... 9b2e955  .I hope this bad behavior is fixed :)

Jacques

**Comment by arturoisilvia** [comment]
Problem solved.
Thank you Jacques.
