### ISSUE TITLE
Local Adjustments: Changes are applied the whole image instead of just the spot

### ISSUE THREAD

**Issue by rebio** [Beep6581/RawTherapee#6163]
**Right before I start:** In my head a _local adjustment_ only should effect the selected area. If this is not how RT handles it, you can close this bug report right away.

**Short description**
When I use local adjustments areas outside the selected area are changed as well.

**Steps to reproduce**
1. Select an image
2. Turn on local adjustments
3. Add an area
4. Add multiple effects (I used "Color & Light", "Shadows/Highlights & Equalizer", "Sharpening" and "Contras by Detail levels"
Note: Only adding the last one seems to have an effect on the entire image.
5. Toggle LA to see effect

**Expected behavior**
Expected behaviour is that the change only effects the selected part of the image.

**Additional information**
Just pointing to #5991 and repost that such a feature would be nice for here ^^'
RT:
> Version: 5.8-2807-g31641f948
> Branch: dev
> Commit: 31641f948
> Commit date: 2021-03-05
> Compiler: x86_64-w64-mingw32-gcc\ 9.3.0
> Processor: generic x86
> System: Windows
> Bit depth: 64 bits
> Gtkmm: V3.24.3
> Lensfun: V0.3.2.0
> Build type: Release
> Build flags: -mwin32\ -m64\ -mthreads\ -msse2\ -std=c++11\ -mtune=generic\ -Werror=unused-label\ -Werror=delete-incomplete\ -fno-math-errno\ -Wno-attributes\ -Wall\ -Wuninitialized\ -Wcast-qual\ -Wno-deprecated-declarations\ -Wno-unused-result\ -Wunused-macros\ -fopenmp\ -Werror=unknown-pragmas\ -Wno-aggressive-loop-optimizations\ -DNDEBUG\ -O3\ -ftree-vectorize
> Link flags: -m64\ -mthreads\ -static-libgcc\ -mtune=generic\ -s\ -O3
> OpenMP support: ON
> MMAP support: ON
> Build OS: Linux 4.4.0-101-generic x86_64
> Build date: Fri, 05 Mar 2021 23:19:16 +0000 UTC
> Build epoch: 1614986356
> Build UUID: 54c4682e-8883-4897-bfd1-fe559694fcd4

OS:
> CPU: AMD Ryzen 7 4800H with Radeon Graphics
> RAM: 32GB
> OS: Windows 10, 64-bit

It seems like I can neither upload the RAW nor the pp3 file here so I can only share some screenshots :(
I tried to reproduce the bug with a randomly selected image and RT worked as I would expect it to and did not change the entire image. So I guess the images are essential to the problem. Where can I upload the images if github does not allow them to be uploaded here? The RAW file has ~30MB.

Image with LA **off**:
![LA - effect on whole image 02](https://user-images.githubusercontent.com/10911084/110323054-53e2b600-8014-11eb-91fa-0b571d89c6c7.jpg)

Image with LA **on**:
![LA - effect on whole image 01](https://user-images.githubusercontent.com/10911084/110323096-6361ff00-8014-11eb-8024-78f51e010b86.jpg)

The effected part is the area above the sleeping puppy.

**Comment by heckflosse** [comment]
@rebio please provide the .pp3 you used

**Comment by Desmis** [comment]
@rebio 

Very curious....
I tried with several images...all works...


provide the pp3...(and the raw)

jacques

**Comment by rebio** [comment]
@heckflosse @Desmis 

I have tried, but github will not let me do it. Do I have to pack in a ZIP file? If I can not post it on github, is there any prefered place 
![github - no pp3](https://user-images.githubusercontent.com/10911084/110331803-d9b82e80-801f-11eb-99da-09273bbe5428.png)

EDIT: I saw the link on RawPedia to www.filebin.net, but over there it also tells me that it is "Unable to save file"

EDIT 2: Using a ZIP file for it seems to work for the pp3 (since the pp3 has the same effect on a random image as well, I might not have to try to upload the RAW afterall)
[pp3.zip](https://github.com/Beep6581/RawTherapee/files/6101881/pp3.zip)

EDIT 3: I tried uploading the RAW file here in a ZIP file. It tells me "Yowza, that's a big file" (file needs to be smaller than 10MB). Since the pp3 also worked on a random image for me, let me know if you still need the RAW file

**Comment by Desmis** [comment]
@rebio 
I try your pp3 on two raw files
Everything seems to work as expected

jacques

**Comment by Desmis** [comment]
@rebio 
I re re try and I found a bad behavior with CBDL

Jacques

**Comment by rebio** [comment]
@Desmis
I just re-tested the pp3 on several images and they work pretty much the same for me. That is very strange.
I mean I'm _only_ using the version from 2021-03-05, but that should not be the big dealbreaker, right?
EDIT: I just updated to RawTherapee_dev_5.8-2810-gdda9b8ed6_20210307 and I got the same results.

Add sharing the RAW file: I tried several file sharing sites and they all either told me that the file is too big or canceled the upload. Any ideas on what page I could use for that?

**Comment by Desmis** [comment]
it's a very curious phenomenon...
With your pp3,
1)  I disable the other spot, same bad behavior
2) i disable progressively the others tools - color and light, shadows/highlight, sharpeing, and always the same bad behavior

Only CBDL remains...if I activate it, the image outside the spotlight changes slightly

Nox, if I clear the PP3 and open a spot, with the same "CBDL" as in your pp3...all works well...

Curious

I look...(I have found a small bug...but without interaction...)

Jacques

**Comment by Desmis** [comment]
I think - to  verify - I found why ? 
It seems the same type of problem than with «local contrast»
Here it's interaction with «main Shadows/highlight»
Tomorrow afternoon I will try to solve==> move sh ol Lab process
Jacques

**Comment by Desmis** [comment]
@rebio 
@heckflosse  
@Thanatomanic 

I just create a Pull Request with "shadows/highlight main" place now in Lab adjustements, instead of Rgbproc.
https://github.com/Beep6581/RawTherapee/pull/6164

All seems to work !
Could you check ?

Thank you

Jacques

**Comment by rebio** [comment]
@Desmis 

I tried the lastest version (RawTherapee_dev_5.8-2813-gbb08b6bed_20210309_win64) and I can not use this build.
The program opens and it seems to even load the images. And as soon as you would expect it to be ready for work it closes again right away.

**Comment by Thanatomanic** [comment]
@rebio Please see this: https://github.com/Beep6581/RawTherapee/issues/6167 and wait until tomorrow. Hopefully the nightly builds will be working again.

**Comment by Desmis** [comment]
@rebio @heckflosse  @Thanatomanic 
I hope it's solved :)

Note that here (in this case) it is a bug due to the interaction between processes, which should be solved by changing the place

But there are cases where the area outside the RT-spot will be slightly changed, especially if the RT-spot significantly changes the luminance
* cases where the general histogram (luminance) is used to calculate certain functions of the tool, for example "contrast" in Lab adjustments, Ciecam, or some parts of wavelet levels (denoise with MAD - median absolute deviation, etc.)
* cases where guidefilter (guid on luminance)  is used to smooth or modifie the image (shadows  Highlight for example, with radius incidence)
* and perhaps others cases
In these 3 cases it is not a bug, but the result of a sum of processses


jacques

**Comment by rebio** [comment]
@Desmis 
I just tested RawTherapee_dev_5.8-2814-g227ae487d_20210313_win64 and it seems to work fine.

EDIT: I did not close the Issue since I have no idea how the mods want such to be handled for bug reports

**Comment by rebio** [comment]
Since all other issues with fixed issues were closed I guess this one can be closed as well
