### ISSUE TITLE
Raw black points: Green2 Does not change color when click button restore value to 0

### ISSUE THREAD

**Issue by arturoisilvia** [Beep6581/RawTherapee#6165]
Playing with this module, (of which I still do not dominate it) I have seen a small flaw in its behavior:

Raw tab -> Raw Black Points: Put some random values ​​in Red, Green1 and Blue with Link greens activated. (Don't worry about the results)

Click on Green2's 'reset to default value' button to set Green2 and Green1 to 0.

Image does not change.

Version: 5.8-2810-gdda9b8ed6 win64.zip

**Comment by heckflosse** [comment]
Confirmed.
