### ISSUE TITLE
RawTherapee_dev_5.8-2813 nightly crashes on open

### ISSUE THREAD

**Issue by chaimav** [Beep6581/RawTherapee#6167]
Windows 10, i3 8100
I tried installing the latest nightly (RawTherapee_dev_5.8-2813-gbb08b6bed_20210309.exe) and it crashed right after opening. I uninstalled and re-installed and it still crashed.

**Comment by Thanatomanic** [comment]
Most likely because of this: https://github.com/Beep6581/RawTherapee/issues/6166
Please wait a few days and try again.
