### ISSUE TITLE
New Chinese(Simplified) translation for RT 5.8

### ISSUE THREAD

**Issue by syyrmb** [Beep6581/RawTherapee#6168]
[Chinese (Simplified).zip](https://github.com/Beep6581/RawTherapee/files/6121115/Chinese.Simplified.zip)

Major translation errors correction, fixed a lot of mis-translations. I'll try to work on a RT 5.9 translation.

BTW, the English version's *PREFERENCES_OVERLAY_FILENAMES_FILMSTRIP* key misspelled "panel" as "pannel",
*TP_WAVELET_MEDILEV_TOOLTIP* misspelled "recommended" as "recommanded".

**Comment by Beep6581** [comment]
Hey

Thank you.

I suggest not making further updates until the Local Adjustments pull requests are resolved, otherwise you might need to redo many keys:
https://github.com/Beep6581/RawTherapee/pulls
