### ISSUE TITLE
IPTC data gets stripped when exporting JPG using Metadata copy mode "Copy unchanged"

### ISSUE THREAD

**Issue by ajaycapers** [Beep6581/RawTherapee#6170]
**Steps to reproduce**
1. Take Original Image in JPG format (see attached, named Original.jpg). It has the Tag "Test", the Copyright "© Emiel Kappert" and the Usage "© All rights reserved".
2. Go to RawTherapee (Version 5.8) Editor. Don't change anything, set the Metadata copy mode to "Copy unchanged" and export the image. (Image attached: "Original_copy_unchanged.jpg)
3. Repeat step 2 with Metadata copy mode set to "Apply modifications" (Image attached: Original_apply_modifications.jpg)
4. View the metadata (in my case in Digikam)

**Expected behavior**
The expected behavior is that in both case, both the metadata and information should not change. 
However, with "Copy unchanged" activated, all metadata is stripped. 
With "Apply modifications" activated, Tags and Names are copied correctly, the Copyright symbol in the Copyright field is distorted to Â©, and the Copyright Usage is deleted completely.

**Additional information**
Some essentials:
- Version of RawTherapee: 5.8
- Version of your operating system: Windows 10 Home 20H2

Other useful information:
- Image files attached (without pp3, since the information should be stored into the image itself)

![Original](https://user-images.githubusercontent.com/80634659/111073161-f51eb000-84dd-11eb-87e0-281070b14d78.JPG)
![Original_apply_modifications](https://user-images.githubusercontent.com/80634659/111073163-f64fdd00-84dd-11eb-9e3a-8a15ae817a21.jpg)
![Original_copy_unchanged](https://user-images.githubusercontent.com/80634659/111073164-f6e87380-84dd-11eb-803e-7c295c97b9d6.jpg)

**Comment by Thanatomanic** [comment]
The EXIF data is copied over correctly as far as I can see:
**original image**
![image](https://user-images.githubusercontent.com/6567747/111751546-ed238f00-8894-11eb-9f30-d7a4db7b9acb.png)

**exported image**
![image](https://user-images.githubusercontent.com/6567747/111751623-03314f80-8895-11eb-96f4-534bdecd1030.png)

However, the IPTC data does not get copied over, which seems to be a bug.
**original image**
![image](https://user-images.githubusercontent.com/6567747/111752123-98344880-8895-11eb-9cb7-7fa43d60143e.png)

**exported image**
![image](https://user-images.githubusercontent.com/6567747/111752152-a1bdb080-8895-11eb-86fa-383369306798.png)

> ... the Copyright symbol in the Copyright field is distorted to Â© ...

I believe there is something wrong with that field data in the first place. If you check the exif data using `ExifTool` you will see this:
```
Copyright                       : ┬® Emiel Kappert
```
There is already a strange character there, so RT tries its best to interpret that... I don't think that particular point is a bug.

**Comment by Thanatomanic** [comment]
@ajaycapers There has been an earlier report of bad character handling in metadata, so there might still be something going on there https://github.com/Beep6581/RawTherapee/issues/3659

**Comment by Lawrence37** [comment]
Fixed in `dev`, likely by #5889.
