### ISSUE TITLE
Please provide install package for Mac M1 (new ARM-based architecture) CPU.

### ISSUE THREAD

**Issue by kgfly** [Beep6581/RawTherapee#6188]
On http://www.rawtherapee.com/downloads/, currently, for mac OS, there is only 64bit install package.

So please provide install package for Mac M1 (new ARM-based architecture) CPU. Thanks.

The new ARM-based architecture CPU is the default CPU on Mac air and macbook pro 13 inch. 

Thanks.

**Comment by kgfly** [comment]
One quick question: does RawTherapee use lots of Intel SSE (I guess so).

If yes, then it means all these code need be rewritten, which seem a nightmare. However, the workaround is to use

https://github.com/DLTcollab/sse2neon

**Comment by Thanatomanic** [comment]
@9527KGG This PR https://github.com/Beep6581/RawTherapee/pull/6152 seems to have resulted in a running version of RT on Mac M1, but not in all cases. If possible we will try to provide a package for ARM with the next release. I think it would be very helpful if you could test compilation on your own machine.

(but to be honest, I have zero experience with macOS, so we will definitely need help... maybe @stwunsch could chime in?)

**Comment by kgfly** [comment]
I wish I could help. But I don't have a Mac M1 CPU machine yet..... (I am still using my old Intel Mac machine, because my favorite apps, such as RawTherapee .... have not supported Mac M1 CPU yet....)

Mac OS originated from BSD Unix, while Linux is a Unix-like OS. They have lots of similarities. My concern is that if RawTherapee uses instructions which binds with Intel Arch, such as Intel SSE/SSE2/AVX/AVX2, there could be pain when porting, though wrapper lib, such as https://github.com/DLTcollab/sse2neon would help for sure.

**Comment by Floessie** [comment]
@9527KGG 
>  My concern is that if RawTherapee uses instructions which binds with Intel Arch, such as Intel SSE/SSE2/AVX/AVX2, there could be pain when porting, though wrapper lib, such as https://github.com/DLTcollab/sse2neon would help for sure.

RT is properly `#ifdef`ed for SSE, just take a look at the code. I more or less regularly build it on PPC.

HTH,
Flössie

**Comment by kgfly** [comment]
Thanks, @Floessie , I took a quick look. Currently, eg the code is

#ifdef __SSE2__
   call sse instruction (**fast mode**)
#else
   call none sse instruction (**slow mode**)
#endif

If current code is compiled on ARM CPU, ARM CPU will call none sse instructions, which is slow mode. The perf will drop a lot. So it's not good.

ARM has SSE corresponding instructions, called Neon. So the most expected code should look like:

#ifdef __SSE2__
   call sse instruction (**fast mode on Intel **)
#ifdef __NEON__ // I am not sure the exact macro name. This is just an example.
   call neon instruction (**fast mode on ARM **)
#else
   call none sse/neon instruction (**slow mode**)
#endif

But this requires lots of work. However,  https://github.com/DLTcollab/sse2neon offers a wrapper lib which converts SSE to corresponding Neon. The change would be much less.

Thoughts?

**Comment by Floessie** [comment]
@9527KGG 
> #ifdef SSE2
> call sse instruction (fast mode)
> #else
> call none sse instruction (slow mode)
>#endif

>If current code is compiled on ARM CPU, ARM CPU will call none sse instructions, which is slow mode. The perf will drop a lot. So it's not good.

IMHO it's not "fast mode" vs. "slow mode" but "hand-optimized" vs. "generic". While the hand-optimized code often cannot be further optimized by the compiler, the generic code will. If I enable AltiVec on PPC (`-maltivec`), the compiler's auto-vectorizer kicks in and produces SIMD code. Same is true for NEON. "The perf will drop a lot." on the other hand isn't true. There will be pieces of code that won't come out as optimized as @heckflosse's SSE2 wizardry now, but might in the near future. It's like the old "assembler" vs. "high-level language" debate.

> However, https://github.com/DLTcollab/sse2neon offers a wrapper lib which converts SSE to corresponding Neon. The change would be much less.

Thanks for the tip. This looks like a nice drop-in for code based exclusively on Intel intrinsics. Whether or not it makes sense for RT should be decided by someone building on ARM on the basis of benchmarks.

Best,
Flössie

**Comment by Thanatomanic** [comment]
> Whether or not it makes sense for RT should be decided by someone building on ARM on the basis of benchmarks.

@Floessie Agreed.

However, the original issue was to provide a M1 compatible installer for our next release. As far as I understand #6152 this does not require any further modifications to the codebase, and the macOS build will automatically work on M1? Or do we need separate builds?

**Comment by Floessie** [comment]
@Thanatomanic The code as-is is perfectly portable (even to big endian architectures).

**Comment by Benitoite** [comment]
I've generated an Apple M1 `arm64` test build.  Everything works the same as on Intel, with the slider buttons not grabbable on macOS 12 *Monterey*-beta due to a possible change in mouse reportage.

https://kd6kxr.keybase.pub/RawTherapee_macOS_11.3_arm64_5.8-3033-g55ceb5b24.zip

PR for bundle fix:
https://github.com/Beep6581/RawTherapee/pull/6346

**Comment by nomar500** [comment]
Hi @Benitoite, 
Having re-read the rawpedia page for MacOS compilation, I still have a few questions: 

1. what's your approach to making a build and a bundle for M1 Mac? Could you kindly share the options and flags you use? (i.e. are they literally what we see in rawpedia 🤔 ?)
2. if you've tried your luck at using `llvm` instead of Apple Clang, I'd be curious to know how you managed it... (see section "f" of my post, last year: https://github.com/Beep6581/RawTherapee/pull/6152#issuecomment-796241373)

Thanks very much.

**Comment by kgfly** [comment]
Current latest release, https://github.com/Beep6581/RawTherapee/releases, is still 5.8, which is close to 2 years old. Will next release include m1 native install package? BTW, when will next release happen?
(I just came cross that Darktable already has m1 native install package)

Thanks.

**Comment by nomar500** [comment]
hi @Benitoite, 
Since you've been active on MacOS aspects today, I'm bumping up this post, too.
What's your approach to making a build and a bundle for M1 Mac? Could you kindly share the options and flags you use? (i.e. are they literally what we see in rawpedia 🤔 ?)

I successfully build but I can't bundle properly. I mean: the bundle script works, I have an image, but when I drop it on the Applications folder to install it, I'm not able to open RT from there.

Here's my make script: 

```bash
#!/bin/bash

mkdir -p build 
cd build
pwd
sudo rm -r *

which brew || exit 2

eval $(/opt/homebrew/bin/brew shellenv)

#cmake --log-level=VERBOSE --log-context -DCMAKE_BUILD_TYPE="Release" \
cmake -DCMAKE_BUILD_TYPE="Release" \
      -DLOCAL_PREFIX:STRING="$(brew --prefix)" \
      -DOSX_DEV_BUILD="ON" \
      -DPROC_TARGET_NUMBER="2" \
      -DCACHE_NAME_SUFFIX="5.8-dev" \
      -DWITH_LTO="ON" \
      -DCMAKE_C_COMPILER="clang" \
      -DCMAKE_CXX_COMPILER="clang++" \
      -DCMAKE_OSX_ARCHITECTURES="arm64" \
      -DLENSFUNDBDIR="/Applications/RawTherapee.app/Contents/Resources/share/lensfun" \
      -DCMAKE_OSX_DEPLOYMENT_TARGET="12.6" \
      -DCMAKE_AR:STRING="$(brew --prefix llvm)/bin/llvm-ar" \
      -S ..

make -j$(sysctl -n hw.ncpu) install
sudo make macosx_bundle
```

**Comment by Benitoite** [comment]
Thank you, I will take a look shortly.  In the meantime could you post AboutThisBuild.txt and any error message and the Crash Report?

**Comment by Benitoite** [comment]
@nomar500  https://github.com/Beep6581/RawTherapee/issues/6660#issuecomment-1411334222

For #6188 a Universal app bundle will be provided (In an Universal app, the executive and library binaries contain both platforms' codes).  It is hard-coded to work in the `/Applications` folder.

**Comment by Benitoite** [comment]
https://rawtherapee.com/shared/builds/mac/RawTherapee_macOS_11.7_Universal_5.9.zip has been published. I'm going to open [an issue](https://github.com/Beep6581/RawTherapee/issues/6700) regarding the arm64 Performance>Threads=0 crash, hopefully that can be hammered out before RT-5.10.

**Comment by Lawrence37** [comment]
Closing this because the download on the website for 5.9 works for ARM.
