### ISSUE TITLE
Latest development version -> Wavelet levels: Toning section only works if Chroma section is enabled.

### ISSUE THREAD

**Issue by ghost** [Beep6581/RawTherapee#6191]
**Short description**
It is not possible to use the _Toning_ section (in the _Wavelet levels_ tab) if the Chroma section is disabled.

The docs don't (yet?) mention any links between the Chroma and the Toning section, let alone that one needs to be active in order to use the other.

**Steps to reproduce**
1. Load RAW file (this one makes it rather obvious: [RAW on pixls.us](https://discuss.pixls.us/t/finding-my-style/23885). No need to do any other adjustments).
2. Activate _Wavelet levels_
3. Activate _Toning_
4. Set both _red-green_ and _blue-yellow_ to absurd values to make it clearly visible. Pull both bars all the way to the top.
5. **No changes are visible at all**
6. Activate *Chroma*
7. **Changes made in Toning show up.**

Sidecar for the above mentioned image: [family.toand007_1.raf.pp3.txt](https://github.com/Beep6581/RawTherapee/files/6229651/family.toand007_1.raf.pp3.txt) Wavelets and Toning are set and turned on, chroma is still turned off.

**Expected behavior**
To be able to make changes with just the Toning section without the need to activate the Chroma section.

**Additional information**
- Version of RawTherapee -> 5.8-2906-ga6478854e

This behaviour does not happen with the appimage with version 5.8-2735-g8bb06c2. It functions as described under the above Expected behaviour section.

**Platform**

* OS                : Linux (kernel 5.9.15-1)
* Distro            : Debian Buster (rel. 10.9)

**Build info**

* Compiler      : gcc 8.3.0
* Cmake         : 3.13.4
* Glib          : 2.58.3-2
* Gtk+          : 3.24.5-1
* Exiv2         : 0.27.3
* Optimization  : None

**Build using**

```
cmake \
    -DCMAKE_BUILD_TYPE="relwithdebinfo"  \
    -DBUNDLE_BASE_INSTALL_DIR="$HOME/.local/rawtherapee" \
    -DCACHE_NAME_SUFFIX="5-dev" \
    -DPROC_TARGET_NUMBER="2" \
    -DBUILD_BUNDLE="ON" \
    -DOPTION_OMP="ON" \
    -DWITH_LTO="OFF" \
    -DWITH_SAN="OFF" \
    -DWITH_SYSTEM_KLT="OFF" \
    ..
```

**Comment by TechXavAL** [comment]
Confirmed in RAF files. Not happening in NEF files (everything normal with Nikon files).

Haven't checked with other formats.

**Comment by ghost** [comment]
I also tested stable appimage 5.8 and that one is also OK.

This is something that has been introduced between commits 2735 (g8bb06c2) and 2906 (ga6478854e)

@TechXavAL: I can reproduce this with NEFs, ARWs and ORFs as well. I'm assuming that it is global.

**Comment by Desmis** [comment]
@jade-nl @TechXavAL 

On my dev version (windows) , all works well  :)

Nothing has been done in the code for this part recently... curious ?

But I look at the code, and in some cases Wavelet decomposition "a and b" (color Lab) was not done. I made the correction just now 
Commit e98288ab3

Thank you for testing

Jacques

**Comment by ghost** [comment]
@Desmis : Fixed!

Thanks for the fast service :smile: 

Closing this one.

**Comment by Desmis** [comment]
@jade-nl 

Do you know "Lucky luck"... faster than his shadow   :)

jacques

**Comment by ghost** [comment]
Oh man that brings back memories! I think I read all of them back when.

**Comment by heckflosse** [comment]
I'm a fan of Calvin & Hobbes :smile: 

https://www.gocomics.com/calvinandhobbes/1987/06/11
