### ISSUE TITLE
Overwrite Symlink Fails

### ISSUE THREAD

**Issue by jcjgraf** [Beep6581/RawTherapee#6192]
**Short description**
When I try to store an image to a symlink (i.e. try to overwrite the symlink) the save operation fails.

**Steps to reproduce**
- Assume the following setup
```
--- a.jpg
 |- b.jpg
 |- a_sym.jpg -> a.jpg
```

- Open `b.jpg` in Rawtherapee (and do some arbitrary edits)
- Save it to `a_sym.jpg`.
- A prompt says that the image already exists and asks if it should be overwritten
- Confirm the overwriting

**Expected behavior**
The symlink gets overwritten (the symlink and not the file appointed by the link). I.e. we end up with:
```
--- a.jpg
 |- b.jpg
 |- a_sym.jpg
```

**Actuak behavior**
The saving fails with a message that the image could not be stored

**Additional information**
If you think that this setup with symlinks is rather arbitrary, it is actually not if you use something like [git-annex](https://git-annex.branchable.com/)

Rawtherapee Version:
```
Version: 5.8
Branch: releases
Commit: 9a9e0acbf
Commit date: 2020-02-04
Compiler: cc 9.2.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.24.2
Lensfun: V0.3.95.0
Build type: Release
Build flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -std=c++11  -Werror=unused-label -Werror=delete-incomplete -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
OpenMP support: ON
MMAP support: ON
```

System Information
```
$ uname -sr
Linux 5.10.25-1-lts
```

**Comment by ghost** [comment]
I'm not able to reproduce what you describe.

No questions are asked to confirm overwriting, instead a new file with a unique numeric identifier added is created. It doesn't matter if the already existing file is a symlink or not.

I started with:

```
-rw-rw---- 1 jade jd 37000 mrt 31 15:52 a.jpg
lrwxrwxrwx 1 jade jd     5 mrt 31 15:52 a_sym.jpg -> a.jpg
-rw-rw---- 1 jade jd 37000 mrt 31 15:52 b.jpg
```

After dummy edit and saving as /path/to/a_sym I end up with:
```
-rw-rw---- 1 jade jd 37000 mrt 31 15:52 a.jpg
-rw-r----- 1 jade jd 25335 mrt 31 15:53 a_sym-1.jpg
lrwxrwxrwx 1 jade jd     5 mrt 31 15:52 a_sym.jpg -> a.jpg
-rw-rw---- 1 jade jd 37000 mrt 31 15:52 b.jpg
-rw-r----- 1 jade jd 15777 mrt 31 15:52 b.jpg.pp3
```

Tried this with stable 5.8 and latest development version (5.8-2907-g1aea98b83) and the result is the same with both. I looked for an overwrite/create unique file option in the preferences, but I did not find one. I do believe this behaviour is the sane solution if no option is present, although having the option to overwrite could be a nice feature/addition.

Could this be an Ubuntu restriction/problem instead? I'm assuming you use Ubuntu based on the LTS part in _Linux 5.10.25-1-**lts**_  (I'm on the latest stable Debian - Buster/10.9).

**Comment by jcjgraf** [comment]
You are right, the simlink itself is not the problem. I have discovered that there is a permission problem with my particular setup. I.e. only the symlink is writeable while the file appointed to is not. So everything is fine with RawTherapee. Though, it would be favourable if RawTherapee was replacing the symlink with the new file instead of keeping the symlink and changing the original file. But probably I just have to live with that.

@jade-nl Such an option actually exists. You can find it in the save dialog (which opens for me only when I press CTRL+S instead of using the save button at the bottom left). There is an option called *Automatically add a suffix if the file already exists*.

**Comment by ghost** [comment]
> Such an option actually exists.

I wasn't aware of ctrl-s, might come in handy.

Thanks.

**Comment by jcjgraf** [comment]
> I wasn't aware of ctrl-s, might come in handy.

Grate that both have gained something from this issue. Thanks again
