### ISSUE TITLE
Shape detection adjusters range mismatch

### ISSUE THREAD

**Issue by Lawrence37** [Beep6581/RawTherapee#6198]
In the shape detection settings for local adjustments, the ΔE scope threshold and ΔE decay adjuster's maximum values do not match the values in rtengine. In the GUI, the max threshold is 10 and the max decay is 10.
https://github.com/Beep6581/RawTherapee/blob/128de03aed60d85252e77df71f060daf28fcec49/rtgui/controlspotpanel.cc#L73-L74
In rtengine, they are 8 and 4.
https://github.com/Beep6581/RawTherapee/blob/128de03aed60d85252e77df71f060daf28fcec49/rtengine/iplocallab.cc#L788-L790 https://github.com/Beep6581/RawTherapee/blob/128de03aed60d85252e77df71f060daf28fcec49/rtengine/iplocallab.cc#L803-L805
The ranges should match. Also, it would be better to clip the values instead of setting them to the default e.g., `iterati = LIM(iterati, 0.2f, 4.0f);`.

**Comment by Desmis** [comment]
@Lawrence37 

Thank you for testing :)
Good catch...

For the range it is an oversight on my part. Moreover LIM treats better the problem in case 

I just push a change in dev

Thank you again

Jacques

**Comment by Lawrence37** [comment]
Works well. Thanks.
