### ISSUE TITLE
LA: Duplicate full image spot while zoomed creates preview sized spot

### ISSUE THREAD

**Issue by chaimav** [Beep6581/RawTherapee#6200]
RT 5.8-2826, Windows 10, i3 8100

Steps to recreate:
-Create a full image spot
-Zoom in on the image
-Click the duplicate button

The duplicate spot is the size of the preview window and not the whole image.
![Full image duplicate bug](https://user-images.githubusercontent.com/47765782/114027302-38eaa800-9845-11eb-8107-7dab4007e553.JPG)

**Comment by arturoisilvia** [comment]
NO!----> I prefer as it is: preview sized spot,-----
Sorry. You're talking about the full size, OK.

**Comment by chaimav** [comment]
Yes, its an issue with full image only, which should extend beyond the edges of the image. A new spot works fine, its the 'duplicate' function that is problematic.

**Comment by Desmis** [comment]
@chaimav 
I just push a change in "dev"...
Now, when you duplicate a RT-spot "Full image", the new one is also "full image" (with delimiters very outside the preview)

Jacques

**Comment by Desmis** [comment]
@chaimav 
There was another bad behavior...
When RT-spot is outside preview (one or more delimiters), the duplicate spot is not good...

I solved this bad behavior in dev

Jacques

**Comment by chaimav** [comment]
> @chaimav
> I just push a change in "dev"...
> Now, when you duplicate a RT-spot "Full image", the new one is also "full image" (with delimiters very outside the preview)
> 
> Jacques

I can confirm it works correctly now in 5.8-2847

**Comment by chaimav** [comment]
> @chaimav
> There was another bad behavior...
> When RT-spot is outside preview (one or more delimiters), the duplicate spot is not good...
> 
> I solved this bad behavior in dev
> 
> Jacques

I am not sure what behavior you were seeing so I cannot confirm if it is fixed or not.

**Comment by Desmis** [comment]
@chaimav 
Of course, not in the last dev..
Put a RT-spot with one delimiters outside preview...Zoom untill preview is full....
Duplicate...and you will see that the duplicate spot is different from original.

Now, it works in all cases

Jacques
