### ISSUE TITLE
When I try to save a work, Raw Therapee crashes no matter if it is via editor or queue tab.

### ISSUE THREAD

**Issue by angeloamaral** [Beep6581/RawTherapee#6205]
Thank you and sorry in advance because I'm using Linux a few months and I know nothing about programming.
I have read what I was told to read and what I get is bellow. If it is insufficient for some help, I will understand completely.

Shall we?

When I try to save a work, Raw Therapee crashes no matter if it is via editor or queue tab.

Version details:
Version: 5.8
Branch: releases
Commit: 9a9e0acbf
Commit date: 2020-02-04
Compiler: cc 9.2.1
Processor: generic
System: Linux
Bit depth: 64 bits
Gtkmm: V3.24.2
Lensfun: V0.3.2.0
Build type: Release
Build flags: -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Wdate-time -D_FORTIFY_SOURCE=2 -std=c++11  -Werror=unused-label -Werror=delete-incomplete -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags: -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed
OpenMP support: ON
MMAP support: ON

My operating system name and version:
Linux [my computer's name] 5.8.0-50-generic #56~20.04.1-Ubuntu SMP Mon Apr 12 21:46:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

The exact steps to reproduce the problem:
When I try to save some works - large JPG files with their processing profiles -, Raw Therapee crashes no matter if it is via editor (ctrl+s) or queue tab.

I can't show a screenshot of the problem because the program just close by itself when I try to save as I said above.

I can't get a stacktrace from a debug build. I have read but I can't understand. I am still trying.

It occurs with large JPG images and their processing profile, but I selected a couple for this matter. They are attached.
I can work perfectly with RAW files and smaller JPG files.

Thank you one more time.

PS (1): I'm having some trouble for attaching the image (size) and pp3 file. I'll submit this and update this issue.
PS (2): Raw Therapee crashes even if I try ctrl+e to edit on an external editor. I'll resize the image via GIMP.
PS (3): OK! I attached the pp3 file as a txt file and the jpg file as a reduced png file edited on GIMP.

**Comment by angeloamaral** [comment]
![Rolo 001 120mm 009](https://user-images.githubusercontent.com/81112925/114960658-dfced580-9e3d-11eb-8512-e5bf0070c0d2.png)

[Rolo 001 120mm 009.txt](https://github.com/Beep6581/RawTherapee/files/6321993/Rolo.001.120mm.009.txt)

**Comment by Thanatomanic** [comment]
@angeloamaral Thanks for reporting, but I'm afraid that testing without the original image makes it impossible to reproduce your issue. Could you perhaps upload your problematic files to https://filebin.net or a Google Drive folder or any other file sharing tool online?

>When I try to save some works - large JPG files with their processing profiles -, Raw Therapee crashes no matter if it is via editor (ctrl+s) or queue tab.

When does it crash exactly? I assume after you press the button to process the queue? And after you complete the file save dialog?

**Comment by Floessie** [comment]
@angeloamaral This sounds like you're running out of memory. How much memory (RAM) do you have installed on your machine and available to the OS? Typing `free` in a shell should give you a hint.

**Comment by angeloamaral** [comment]
> @angeloamaral Thanks for reporting, but I'm afraid that testing without the original image makes it impossible to reproduce your issue. Could you perhaps upload your problematic files to https://filebin.net or a Google Drive folder or any other file sharing tool online?
> 
> > When I try to save some works - large JPG files with their processing profiles -, Raw Therapee crashes no matter if it is via editor (ctrl+s) or queue tab.
> 
> When does it crash exactly? I assume after you press the button to process the queue? And after you complete the file save dialog?

I can upload my problematic files. I will share the link here later.

It crashes exactly after these steps:
1. I type ctrl+s
2. I complete the file save dialog
3. Press Ok button
4. The status bar (of saving process) reaches 50% and stays there for a while.

Or after press the button to process the queue and the status bar (of saving process) reaches 50% and stays there for a while.

**Comment by angeloamaral** [comment]
> @angeloamaral This sounds like you're running out of memory. How much memory (RAM) do you have installed on your machine and available to the OS? Typing `free` in a shell should give you a hint.

![image](https://user-images.githubusercontent.com/81112925/115163262-915c4980-a07e-11eb-8887-ed6b1773a40d.png)

**Comment by angeloamaral** [comment]
> @angeloamaral Thanks for reporting, but I'm afraid that testing without the original image makes it impossible to reproduce your issue. Could you perhaps upload your problematic files to https://filebin.net or a Google Drive folder or any other file sharing tool online?
> 
> > When I try to save some works - large JPG files with their processing profiles -, Raw Therapee crashes no matter if it is via editor (ctrl+s) or queue tab.
> 
> When does it crash exactly? I assume after you press the button to process the queue? And after you complete the file save dialog?

Here is the folder link to original files of the crash: https://drive.google.com/drive/folders/1Wu0aYuF-4sQ_mBGzjzX8YK-oh-_UW6fz?usp=sharing

**Comment by angeloamaral** [comment]
I've tried to compile RawTherapee myself through the automatic way as said on RawPedia (http://rawpedia.rawtherapee.com/Linux#The_Automatic_Way). I am trying to get a stacktrace from a debug build but it seems to difficult for me. Right now I am stuck in an error as below - I am just trying to help you guys to help me.

![image](https://user-images.githubusercontent.com/81112925/115166750-1baaaa80-a08b-11eb-81bb-67f5b770cf0d.png)

I'll keep trying... Now through the manual way.

**Comment by Lawrence37** [comment]
RawTherapee used 9+ GB of memory when I saved the image. Your system only has 10 GB, so it's very likely RT crashed because your computer ran out of memory. By the way, the error you got while trying to compile means CMake is not installed.

Edit: It seems like noise reduction is causing the high memory usage.

**Comment by angeloamaral** [comment]
> RawTherapee used 9+ GB of memory when I saved the image. Your system only has 10 GB, so it's very likely RT crashed because your computer ran out of memory. By the way, the error you got while trying to compile means CMake is not installed.
> 
> Edit: It seems like noise reduction is causing the high memory usage.

Thanks for the answers. I'll try again without noise reduction.

**Comment by angeloamaral** [comment]
> RawTherapee used 9+ GB of memory when I saved the image. Your system only has 10 GB, so it's very likely RT crashed because your computer ran out of memory. By the way, the error you got while trying to compile means CMake is not installed.
> 
> Edit: It seems like noise reduction is causing the high memory usage.

It worked! It worked! (Without noise reduction)
So, it's a memory problem, right? By exclusion.
Before I close this issue, to learn to get a stacktrace from a debug build, could someone tell me what I have to do to fix this (below)?

![image](https://user-images.githubusercontent.com/81112925/115174465-aa292700-a09f-11eb-8ab2-81f5e944b2f3.png)

[CMakeError.log](https://github.com/Beep6581/RawTherapee/files/6332910/CMakeError.log)
[CMakeOutput.log](https://github.com/Beep6581/RawTherapee/files/6332911/CMakeOutput.log)

**Comment by Lawrence37** [comment]
You are missing Lensfun. Make sure you have installed all the dependencies. http://rawpedia.rawtherapee.com/Linux#Dependencies

**Comment by angeloamaral** [comment]
Ok. Thank you very much.

**Comment by heckflosse** [comment]
@angeloamaral About noise reduction:
http://rawpedia.rawtherapee.com/Preferences#Threads

**Comment by angeloamaral** [comment]
> @angeloamaral About noise reduction:
> http://rawpedia.rawtherapee.com/Preferences#Threads

Thanks a lot!
