### ISSUE TITLE
Nikon - D810 - 12bit compressed  small raw  ,  It looks like rt5.8 got the wrong white point

### ISSUE THREAD

**Issue by wbzqe** [Beep6581/RawTherapee#6206]
**Short description**

Nikon - D810 - 12bit compressed  small raw  ,  It looks like rt5.8 got the wrong white point ,  In `neutral` mode, the image is too bright and some are overexposed. If  set the `white-point correction` to `0.25`,  the result looks correct

**Additional information**

log output by rt5.8 ubuntu when load  Nikon - D810 - 12bit compressed ((8)), small raw (3:2).NEF

From the log, the white point of 12bit is in the normal range, so I don’t know what happened :(

```
constants exists for "Nikon D810" in camconst.json
black levels: R:0 G1:0 B:0 G2:0 (provided by dcraw)
white levels: R:4075 G1:4075 B:4075 G2:4075 (provided by camconst.json)
raw crop: 0 0 3680 2456 (provided by camconst.json)
color matrix provided by camconst.json
cam_mul:[1.964844 1.000000 1.324219 0.000000], AsShotNeutral:[0.508946 1.000000 0.755162 0.000000]
pre_mul:[1.000000 0.508946 0.673956 0.508946], scale_mul:[16.082209 8.184980 10.838705 8.184980], cblack:[0.000000 0.000000 0.000000 0.000000]
rgb_cam:[ [ 1.581643 -0.179189 0.013541], [-0.389732 1.582755 -0.425772], [-0.191911 -0.403566 1.412230] ] (not bayer)
Raw As Shot White balance: temp 5644.969940, tint 1.096562, multipliers [2.206524 1.834745 1.729786 | 2.062443 1.841539 1.760289]
```

Here are two samples  from [raw.pixls.us](https://raw.pixls.us/)

incorrect ：[Nikon - D810 - 12bit compressed ((8)), small raw (3:2).NEF](https://raw.pixls.us/getfile.php/2036/nice/Nikon%20-%20D810%20-%2012bit%20compressed%20((8)),%20small%20raw%20(3:2).NEF)

correct ：[Nikon - D810 - 12bit compressed ((6)) (3:2).NEF](https://raw.pixls.us/getfile.php/2035/nice/Nikon%20-%20D810%20-%2012bit%20compressed%20((6))%20(3:2).NEF)

**Comment by Thanatomanic** [comment]
There doesn't seem to be an issue in the nightly builds
![image](https://user-images.githubusercontent.com/6567747/115107090-09d0e680-9f69-11eb-96f5-fd058863151f.png)

Please use that if you want to have correct behavior: https://github.com/Beep6581/RawTherapee/releases/tag/nightly

**Comment by Thanatomanic** [comment]
btw, the 'small raw' you link to is not a Bayer file, but is already demosaiced. That is the likely reason both files still act differently.

**Comment by wbzqe** [comment]
> btw, the 'small raw' you link to is not a Bayer file, but is already demosaiced. That is the likely reason both files still act differently.

Thank you for your reply ！@Thanatomanic 

I also noticed that this type is not Bayer data, It's just that the 'small raw' image is more normal exposure when I open it in Darktable and CameraRaw and  a lot brighter in RT,  so I'm wondering if it's a bug, or if it can be optimized.
