### ISSUE TITLE
Colour balance issues for negatives

### ISSUE THREAD

**Issue by ChristopheBernard** [Beep6581/RawTherapee#6213]
This a report on RawTherapee_dev_5.8-2735-g8bb06c2_20210121

The colour balance on inverted negatives seems to be badly off. I loaded a negative image NEF (Nikon D7000), then starting from a Neutral profile, I

1. Toggled "Film negative" on
2. Cropped to inside the picture
3. Clicked Auto levels in Exposure
4. Clicked method -> Automatic -> RGB Grey in White balance

I get a picture with a massive red cast. If I pick an area with the colour picker to make it neutral, it turns very red too.

![image](https://user-images.githubusercontent.com/14012015/115508750-f9c54980-a27d-11eb-85d1-a87555ad7ef2.png)

**Comment by Thanatomanic** [comment]
Have you read the documentation on how to use the Film Negative tool? http://rawpedia.rawtherapee.com/Film_Negative
This is not the right way to do it.

**Comment by rom9** [comment]
Hi @ChristopheBernard,
 the wiki is not yet updated for the dev version, since it's not released yet.
Auto-WB doesn't work with the new version of the film negative tool. Try instead to set WB to daylight, or (better) the actual color temperature of the backlight you used to digitize the negative.
Then, use the color balance sliders inside the film negative tool itself to adjust the output image.
This difference is due to the fact that the new version of the filmneg tool works in a different stage of the processing pipeline.

Let me know if it works :-)

alberto

**Comment by ChristopheBernard** [comment]
Thank you for your answers. 

Daylight and other preset colour balances work. As does temperature correlation. I just hoped I could use the colour picker or the automatic white balance.

Also note that the dynamic range compression is not compatible with that new colour pipeline I think.

**Comment by rom9** [comment]
> Also note that the dynamic range compression is not compatible with that new colour pipeline I think.

you mean, this tool?

![image](https://user-images.githubusercontent.com/4711834/115551728-c5688200-a2ab-11eb-98f5-2992eba0b14b.png)

This one should work, actually... it is applied right after filmneg.
What's the problem, exactly ?

**Comment by ChristopheBernard** [comment]
Yes I was writing about this tool. Actually I made a mistake.

Trying to find more familiar behaviour in colour balance, I had been building more ancient dev commits up to June 2020 and this was not working with one of them.

With the latest one, it works fine.

i am very sorry for my mistake.

Best regards,

**Comment by ChristopheBernard** [comment]
OK. I did some more experimenting, and here is what I see (nightbuild version 5.8-2735-g8bb06c2).

1. The preset colour balances seem to apply in reverse. I would expect a sunny colour balance to give a colder image and a shade or cloudy colour balance to return a warmer image. It is the opposite for negatives. So the colour balance setting is for the negative image, not for the positive inverted image it seems

2. The preview gives strange results for the dynamic range compression. When the image is previewed entirely it is OK. If I zoom into the image, then the preview is inverted (looks like a negative again).

See the attached screen grabs. The only difference between both is that the preview has moved to right in the second capture to be partially obscured by the button column on the right.

![image](https://user-images.githubusercontent.com/14012015/115561077-80e1e400-a2b5-11eb-9f51-3e54ed93e65c.png)

![image](https://user-images.githubusercontent.com/14012015/115561143-91925a00-a2b5-11eb-9d3d-264a10d3ce7f.png)

**Comment by Thanatomanic** [comment]
> The preset colour balances seem to apply in reverse. I would expect a sunny colour balance to give a colder image and a shade or cloudy colour balance to return a warmer image. It is the opposite for negatives. So the colour balance setting is for the negative image, not for the positive inverted image it seems

Of course, because the temperature/tint settings work with respect to normal photographs. For correct use of the Film Negative tool you should not use the White Balance module (keep it on Camera). There is separate white balance tooling in the Film Negative tool itself. But @rom9 knows better.

> The preview gives strange results for the dynamic range compression. When the image is previewed entirely it is OK. If I zoom into the image, then the preview is inverted (looks like a negative again).

Confirmed!

**Comment by rom9** [comment]
Ouch! This doesn't sound right... I'll take a look this evening, thanks for testing :-)

**Comment by rom9** [comment]
Should work now, nice catch, thanks ;-)
I never noticed that the image buffer was overwritten by the fattal/dehaze code.

> For correct use of the Film Negative tool you should not use the White Balance module (keep it on Camera).

Yep, that's the easiest way to do it: set the in-camera WB for the _backlight_ , then shoot the negative, and then you can leave the default (WB = Camera) in RawTherapee. Then, do all your color balancing from the FilmNegative tool :-)

alberto
