### ISSUE TITLE
Switching bundled profiles does not reset all tools

### ISSUE THREAD

**Issue by chaimav** [Beep6581/RawTherapee#6218]
RT 5.8 and RT 5.8-2847 for Windows

1. Enable Color > Black and white tool
2. Select and bundled profile (besides neutral)

The profile will apply but the Black and white tool will remain enabled. Expected behavior is that it would reset.  The same thing happens if you select  Raw > film negative.

My presumption is that these profiles predate these tools and therefore the pp3 don't account for them. To test this, I opened the neutral profile (which turned everything off) then a bundled one and saved it as new profile. When I toggled the B&W or film neg tool and then re-opened this new profile they did indeed reset.

It would seem to me that simply re-creating the pp3's for the bundled profiles would solve this issue.

**Comment by ghost** [comment]
Doesn't this work as designed?

There's the *Processing profile fill mode* selector which determines what is being processed when loading a profile: You can choose the *Fill* or the *Preserve* modes.

If I give that a try I get either of your scenarios, depending on the setting of that mode.

Read about it here: [Sidecar Files / Processing Profiles](https://rawpedia.rawtherapee.com/Sidecar_Files_-_Processing_Profiles), specifically the *6 Partial Processing Profiles and Fill Modes*.

**Comment by chaimav** [comment]
@jade-nl Thanks. I was not aware of the fill vs preserve button.
