### ISSUE TITLE
Strength Control on Local Adjustment Spots RTDev

### ISSUE THREAD

**Issue by AndyAstbury** [Beep6581/RawTherapee#6221]
The main Wavelets panel has a strength control at the top of it, so you can 'turn down' the 'volume' of your carefully crafted adjustments and slider ratios etc. It gives you that final tweak of finesse.
So I was wondering if that would be possible on Local Adjustment Spots as it would just add the same finesse without  having to go back down the panel and adjust multiple controls.

**Comment by waynesutton50** [comment]
Having seen how useful it is in Wavelets, I think this would be a big plus for Local Adjustments

**Comment by TechXavAL** [comment]
If this is ever implemented, could it be added to each spot, instead of to the whole tool?

That way you will have complete control over each spot.

**Comment by Desmis** [comment]
A "strength" slider only makes sense if it is specific to each Spot and each tool

I have chosen a number of tools that I believe are more than sufficient to meet Andy's needs
* local contrast & wavelet (new)
* log encoding (already operational)
* denoise (new)
* color and light (new)
* Dynamic Range and exposure (new)
* SH and Tone equalizer (new)
* retinex (already operational)
* tone mapping (new)

Some have caused me a lot of trouble (denoise, Tone mapping)

This modification required a lot of code, but this is not a problem if it answers a request

You can find the changes in the branch - "lastrength"

I will create a PR this afternoon

Jacques

**Comment by AndyAstbury** [comment]
Yes, please merge into current dev build, and many thanks to Jacques for implementing this in such a short time - brilliant!

**Comment by waynesutton50** [comment]
I've just tried the latest commit and haven't found any obvious problems. Thanks to Andy for the idea and to Jacques for the implementation.

**Comment by Desmis** [comment]
@AndyAstbury  @waynesutton50 @TechXavAL 

Merge

Jacques
