### ISSUE TITLE
Canon EF 70-300mm f/4-5.6 IS II USM reported as "Unknown 70-300"

### ISSUE THREAD

**Issue by Jacalz** [Beep6581/RawTherapee#6224]
**Short description**

I am having an issue with my Canon CR2 raw files from my "Canon EF 70-300mm f/4-5.6 IS II USM" being reported as "Unknown 70-300" from my Canon 5d Mark 2. All my other lenses work fine, so I decided to open this issue to try and get it fixed. It is quite annoying.

I thought that this was because exiv2 did not support it, but it looks like it actually does:
```
$ exiv2 -pt 70-300exiv2.jpg | grep -ai lens
Exif.CanonCs.LensType                        Short       1  Canon EF 70-300mm f/4-5.6 IS II USM
Exif.CanonCs.Lens                            Short       3  70.0 - 300.0 mm
Exif.Canon.LensModel                         Ascii      70  EF70-300mm f/4-5.6 IS II USM
```

I found https://github.com/Beep6581/RawTherapee/issues/5670 which seems related, but it looks to be specific to Sony cameras if I understood things correctly, so I figured it would be best to open a new issue. Sorry if I am creating a duplicate.

**Steps to reproduce**
1. Open a CR2 image taken with the lens.
2. Look at the information box.

**Expected behavior**

Should say "Canon EF 70-300mm f/4-5.6 IS II USM" instead of "Unknown 70-300".
![image](https://user-images.githubusercontent.com/25466657/116822633-1f0c5e80-ab80-11eb-9369-d11b7e0620d1.png)

**Additional information**
- Version of RawTherapee: 5.8 with https://github.com/Beep6581/RawTherapee/commit/4221fdf31e43658cef98ad660ad398b8ae81b8d7 backported.
- Version of your operating system: Solus Linux 4.2 using Linux kernel 5.11.12 and Budgie desktop.

The zip file contains a CR2 image that exhibits from this issue.
[_MG_7884.zip](https://github.com/Beep6581/RawTherapee/files/6411972/_MG_7884.zip)

**Comment by rebio** [comment]
Just a guess on my side, but I think it's related to #5691 ("Lens autodetect can't find Canon EF-M 18-55mm lens").
It's not RT but lensfun as far as I know.
See also https://github.com/lensfun/lensfun and maybe drop the issue there

EDIT: After taking a look at #5363 ("Canon EOS RP should be supported, even without .CR3 format suport") I'm pretty sure it's lensfun

**Comment by Jacalz** [comment]
Lensfun does not contain corrections for this lens as far as I know. Can it really be causing this issue then?

**Comment by rebio** [comment]
> Lensfun does not contain corrections for this lens as far as I know. Can it really be causing this issue then?

Not sure on this, but I think RT uses lensfun for extracting the lens name as well (would make some sense since it would need to pass on the data to lensfun to select the correct profile anyway. So why not use their naming directly?)

**Comment by Jacalz** [comment]
Good point. Will see if I can make some corrections for the lens and put it into lensfun.

**Comment by Lawrence37** [comment]
As far as I know, RT does not get the lens name from Lensfun.

**Comment by Thanatomanic** [comment]
@Lawrence37 Correct. The issue @rebio filed with the lensfun team is moot. This has to do with the metadata extraction that RT does. Our `rtexif` module needs manual updates by cross-checking the lens and camera identifiers that `exiv2` and `ExifTool` support. This is something we should definitely do before releasing 5.9 (or #5889 needs to be merged).

**Comment by Beep6581** [comment]
I'll do it One Last Time© for 5.9, then its exiv2 mergy mergy time.

**Comment by Beep6581** [comment]
No need to have this issue open.

**Comment by Jacalz** [comment]
Is there any plan on when 5.9 will release then?

**Comment by Thanatomanic** [comment]
If you look at the main Issue page, it is one of the two pinned issues: https://github.com/Beep6581/RawTherapee/issues/5632

**Comment by Jacalz** [comment]
Thanks 👍

**Comment by doumeb** [comment]
Hey I have the same problem with this Canon EF 70-300mm f/4-5.6 IS II USM
And the other work fine with my canon 6D mark2 on darktable. 24-70 L F4 and 40 F2.8
I'm on the 4.0 of darktable and ubuntu 22.04
