### ISSUE TITLE
Sony A1 lossless compressed files not supported

### ISSUE THREAD

**Issue by Baltmin** [Beep6581/RawTherapee#6226]
New lossless compressed format of sony A1 is not supported. I can only open the dng files converted from ACR but this results in a black layout on the bottom and right of the image which requires cropping for every single photo.

**Comment by Thanatomanic** [comment]
Please provide a sample file

**Comment by Baltmin** [comment]
This is .dng from Adobe camera raw after doing enhance detail. It is the only way to open these files in RT. The original lossless compressed .ARW file does not open at all in RT 5.8.

![DSC09039-Enhanced_resize](https://user-images.githubusercontent.com/83581222/116864716-35f29580-ac00-11eb-8025-c66e26a08e74.jpg)

**Comment by Baltmin** [comment]
I can't provide a lossless compressed raw file here, as there is a 10MB limit. I can do it through onedrive or dropbox if this is helpful.

**Comment by Thanatomanic** [comment]
Yes, please provide an original raw file, for example using https://filebin.net. Especially if it does not open in RT now, this will be helpful to support it in the future.

**Comment by Baltmin** [comment]
Here is the raw file. Thank you!

https://filebin.net/34xnh58w7fkyn5dm/DSC07383.ARW?t=wgniofxu

**Comment by Thanatomanic** [comment]
@Baltmin I've downloaded your file. Making this work, will require some time and is not a high priority issue atm, so please be patient :-)
