### ISSUE TITLE
german translation for LA

### ISSUE THREAD

**Issue by marter001** [Beep6581/RawTherapee#6229]
Hello,

looking forward to the next dev or release 5.9, for my own better understanding, i started to translate the Local Adjustments into german.

I learned, I am far away to bring this to end, because LA contains some really tricky algorythm, tools and expressions i dont understand yet. I would like to share the work i did until now and continue any support will be greatly welcome. 

marter

[Deutsch.zip](https://github.com/Beep6581/RawTherapee/files/6429410/Deutsch.zip)

**Comment by Beep6581** [comment]
Hey

That's great, but as you noticed things could probably be improved. Please wait with translations until a review of the `default` file is completed - keep an eye on issue #5664.

**Comment by marter001** [comment]
yes, youre right, i saw that issue after setting up this one. I will wait, until #5664 is closed.

**Comment by marter001** [comment]
Now the full german translation for RT 5.9 is avalable, it is based on the default-file of Version: 5.8-3105-g262d00bf1and 
I would be glad to see it added soon.
Thanks for the support to mozzihh (Henning Sidow at pixls.us) 

[Deutsch.zip](https://github.com/Beep6581/RawTherapee/files/9331208/Deutsch.zip)
