### ISSUE TITLE
Using Ninja build system (on Windows)

### ISSUE THREAD

**Issue by Thanatomanic** [Beep6581/RawTherapee#6231]
Edit: I've edited my post after @ff2000 pointed out I was overlooking something important...
~~Compiling or recompiling RT on Windows in MSYS2 using the currently suggested approach takes _a lot_ of time. The main issue is that we use "MSYS Makefiles" and `make`. However, building for Ninja works without fail as well and is _much_ faster.~~

There is the option to use the Ninja build system out of the box on MSYS2. Ninja automatically parallelizes jobs (ncores + 2) and may be (slightly) faster when recompiling than using the traditional "MSYS Makefiles" and running `make -j#`. The approach is simply:
```
cmake -g "Ninja" (add all your regular switches here)
cmake --build . --target install
```

**Test results on a 4 core system**
MSYS Makefiles + `make -j6`: 7m32s
Ninja + cmake: 5m46

This gives a nice (and consistent) speed boost. I propose we update our documentation to reflect this. Maybe this extends to other OSes as well? And maybe the automated builds can also benefit from this.

**Comment by ff2000** [comment]
Could it be that ninja automatically builds multiple objectfiles at once (number determined by CPU cores/threads) while MSYS Makefiles just runs 1?
Does MSYS Makefiles support "-j" switch? And does it speed up the build?

**Comment by Thanatomanic** [comment]
Oh boy, I feel silly. Yes, Ninja is multithreaded out of the box which explains the speed-up perfectly. 
When running `make -j6 install` with the MSYS Makefiles approach the build process takes 7m32s which is comparable.

Still, there may be two arguments to go for Ninja:
1. It runs the maximum number of parallel jobs automatically 🙃 
2. From what I read online, it is supposedly faster when recompiling (smarter/faster to figure out what needs to be rebuilt).

Any thoughts, or was this all just wishfull thinking on my part?

**Comment by Thanatomanic** [comment]
I've done some more testing. Ninja does seem consistently faster.

3 runs with MSYS Makefiles + `make -j6 install`: 7m32s, 7m8s, 7m39s
3 runs with Ninja + `cmake`: 6m37, 6m28, 6m25

Just to be sure, I also did a MSYS Makefiles + `cmake` run, which also ended up taking >7m, so it seems that Ninja is the real cause of the speedup.

**Comment by gaaned92** [comment]
Thanks for improvement. I tested building RT and ART.
It requires minimum modifications of procedures and the builds are OK.
I didn't make benchmarks but if it improves the rebuilding speed, it's all benefit.

You have a typo. It works with a blank before install
`cmake --build . -- install`

You can also speed up CMAKE by defining in `.bash_profile`
`export CMAKE_BUILD_PARALLEL_LEVEL="n"
`
Once approved, could you update rawpedia/windows accordingly

**Comment by Thanatomanic** [comment]
@gaaned92 Thanks for testing that it works on your end!
I made a different typo actually, the proper command should be `cmake --build . --target install`.

**Comment by Thanatomanic** [comment]
I've rewritten http://rawpedia.rawtherapee.com/Windows extensively and simultaneously included Ninja. Closing for now.

**Comment by Desmis** [comment]
@Thanatomanic 
I just update msys2 with 
Pacman -SYuu
then
Pacman -Syu

Then I open a new clone

When I want to compile
I get


jacques@pc-bureau MINGW64 ~
$ cd /g/code/repo-rt2/build

jacques@pc-bureau MINGW64 /g/code/repo-rt2/build
$ cmake -G "Ninja" -DLENSFUNDBDIR=share/lensfun -DCMAKE_BUILD_TYPE="release" -DPROC_TARGET_NUMBER="2" -DCACHE_NAME_SUFFIX="5-dev" ..CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "G:/code/repo-rt2/build/CMakeFiles/CMakeOutput.log".

jacques@pc-bureau MINGW64 /g/code/repo-rt2/build
$


What I missed ?
I have tried 
cmake -g "Ninja"

Jacques

**Comment by Thanatomanic** [comment]
Thanks @Desmis, I thought I had read that Ninja was part of the default installation of MSYS2. I guess I was wrong.
Could you try `pacman -S mingw-w64-x86_64-ninja` and then try to build again?

**Comment by Desmis** [comment]
I will try this morning :)


jacques

**Comment by Desmis** [comment]
@Thanatomanic 

Ok, works fine
Thank you
Jacques

**Comment by Thanatomanic** [comment]
I've updated RawPedia to reflect this.

**Comment by Desmis** [comment]
ok thank you :)
