### ISSUE TITLE
Noise Reduction Detail Recovery Different from 5.8

### ISSUE THREAD

**Issue by Lawrence37** [Beep6581/RawTherapee#6235]
From here https://discuss.pixls.us/t/noise-reduction-in-dev/24621
Detail recovery is more aggressive in the current dev compared to the 5.8 release.

I have bisected the commits and found it is caused by 806c086fbcc92c6a11bb714d1bce37b13d41c34b. Patch coming soon.

**Comment by Thanatomanic** [comment]
@Lawrence37 great find! Such a subtle thing..
