### ISSUE TITLE
Olympus E-M10 Mark IV has pink highlights despite `camconst.json` entry

### ISSUE THREAD

**Issue by Thanatomanic** [Beep6581/RawTherapee#6236]
After https://github.com/Beep6581/RawTherapee/commit/6c96bf7507d631284c4c71134f12e09e3dbe9090 I added this entry to `camconst.json`,
https://github.com/Beep6581/RawTherapee/blob/6c96bf7507d631284c4c71134f12e09e3dbe9090/rtengine/camconst.json#L1986-L1990

However, this sample file https://raw.pixls.us/getfile.php/4132/nice/Olympus%20-%20E-M10%20Mark%20IV%20-%2016bit%20(4:3).ORF still shows strong purple highlights. The highest raw values seem to be 4095 on all channels.
![image](https://user-images.githubusercontent.com/6567747/118165643-d2007600-b424-11eb-98be-45c373e06de6.png)

Not sure what is going on.

**Comment by Lawrence37** [comment]
`range` is supposed to be `ranges`. Fixed and working now.
