### ISSUE TITLE
Leica M8 sample interpreted with wrong bit depth

### ISSUE THREAD

**Issue by Thanatomanic** [Beep6581/RawTherapee#6237]
When preparing https://github.com/Beep6581/RawTherapee/commit/6c96bf7507d631284c4c71134f12e09e3dbe9090 I checked this https://raw.pixls.us/getfile.php/2988/nice/Leica%20-%20M8%20-%208bit%20uncompressed%20(3:2).DNG sample and it seems like the file is being interpreted with a wrong bit-depth.

![image](https://user-images.githubusercontent.com/6567747/118166344-a762ed00-b425-11eb-8d83-45dd4d312dcc.png)

**Comment by SimonSegerblomRex** [comment]
I'm probably missing something, but why did you introduce this regression in 6c96bf7 @Thanatomanic? Removing the Leica M8 entry (which looks like settings for a 14 bit mode) from `camconst.json` fixes this issue.

**Comment by Thanatomanic** [comment]
Well, verbose mode tells me that `dcraw` provides a white level of 16383, when I load the raw data in my own analysis script, the values lie between 2 and 16256. So I wouldn't assume that setting a white level of 16383 in `camconst.json` would hurt, but apparently it does.
Judging from the regular gaps in the histogram, there seems to be 8-bit data in the file that gets expanded to 14-bit. Weird behavior to say the least...

**Comment by Thanatomanic** [comment]
@SimonSegerblomRex I've pushed a fix https://github.com/Beep6581/RawTherapee/commit/7e36240f3af05bdb17e33db135c0e0ea0bef0bb3 
But there is something fishy going on with what `dcraw` does, what it reports and how the `camconst.json` override that seems okay actually screws things up. Something to figure out at some point...
