### ISSUE TITLE
On-Preview Editing Widgets: Crashes and Other Issues

### ISSUE THREAD

**Issue by Lawrence37** [Beep6581/RawTherapee#6244]
@AndyAstbury Let's continue the discussion from #6242 here. I managed to trigger a crash while dragging a spot and pressing the enter/return key. It also happens with the graduated filter and perspective control lines. Can you confirm if your bluetooth mice have issues with these tools as well?

**Bug Description**
1. On some hardware, releasing the mouse button while dragging a spot removal spot has no effect. The spot continues to follow the mouse. Refer to this [comment](https://github.com/Beep6581/RawTherapee/issues/6242#issuecomment-842465893) for the original issue.
2. While dragging one of the on-preview widgets, pressing the enter/return key causes a segfault here (`editSubscriber` is null) https://github.com/Beep6581/RawTherapee/blob/d11d834045ef9f6e8cbbf63f734c07be3654123e/rtgui/cropwindow.cc#L708-L714

**Comment by heckflosse** [comment]
> While dragging one of the on-preview widgets, pressing the enter/return key causes a segfault here (editSubscriber is null)

This should fix the crash:

```diff
diff --git a/rtgui/cropwindow.cc b/rtgui/cropwindow.cc
index a3e00c80a..4a136266b 100644
--- a/rtgui/cropwindow.cc
+++ b/rtgui/cropwindow.cc
@@ -705,15 +705,15 @@ void CropWindow::buttonRelease (int button, int num, int bstate, int x, int y)
         state = SNormal;
         needRedraw = true;
     } else if (state == SEditDrag1 || state == SEditDrag2 || state == SEditDrag3) {
-        if        (state == SEditDrag1) {
-            needRedraw = editSubscriber->button1Released();
-        } else if (state == SEditDrag2) {
-            needRedraw = editSubscriber->button2Released();
-        } else if (state == SEditDrag3) {
-            needRedraw = editSubscriber->button3Released();
-        }
-
         if (editSubscriber) {
+            if        (state == SEditDrag1) {
+                needRedraw = editSubscriber->button1Released();
+            } else if (state == SEditDrag2) {
+                needRedraw = editSubscriber->button2Released();
+            } else if (state == SEditDrag3) {
+                needRedraw = editSubscriber->button3Released();
+            }
+
             rtengine::Crop* crop = static_cast<rtengine::Crop*>(cropHandler.getCrop());
             Coord imgPos;
             action_x = x;

```

**Comment by AndyAstbury** [comment]
@Lawrence37 Applying and editing (stretch/contract/rotate) a graduated filter is faultless with Bluetooth devices. Hitting return/enter simple turns the grad viz off and does not cause cursor to vanish, and I can simply add more adjustments - so I'd say that the grad filter function works fine.
As for perspective control, well, I have no clue how to apply editable control lines - some documentation seems to have escaped me.  The sliders all function as expected.

**Comment by Lawrence37** [comment]
That's odd. Both tools use the same underlying code to receive input device events. If the graduated filter is fine, there must be something wrong with the bit of code specific to spot removal. I can't find anything though. Just to confirm, were you adjusting the graduated filter using the sliders, or with the on-preview widget?

**Comment by AndyAstbury** [comment]
Grad filter widget rotate and stretch/compress - and I can use the perspective tool now I know what to do!

**Comment by Lawrence37** [comment]
@AndyAstbury
Although I don't know what is causing the spot dragging issue, I just merged some changes into `dev` that could affect the behavior. Could you please check if the issue persists or has changed in any way?

**Comment by AndyAstbury** [comment]
@Lawrence37 - just updated to g2e6e52f33 - still the same disconnect between the spots after move/resize when using bluetooth pointer.  With wired everything seems fine.
But as I said before it might be a OSX/Parallels problem on my system so I would poll other wireless/bluetooth pointer users who are not using a VM.

**Comment by Lawrence37** [comment]
@AndyAstbury I managed to borrow a Bluetooth mouse but could not replicate the issue. Let's see if anyone runs into the same problem once the beta version is out.

**Comment by AndyAstbury** [comment]
@Lawrence37 - like I said, it's more likely to be my OS/Parallels/Linux interface that's causing the problem.  Will check the MacBeta when it's released.
Cheers!

**Comment by Pandagrapher** [comment]
I use a Bluetooth mouse with MacOS : I never reproduced this issue with `dev`.

**Comment by Lawrence37** [comment]
Closing this for now because the last remaining issue may not be a RawTherapee problem and no one else has managed to reproduce it.
