### ISSUE TITLE
Abstract Profile: With option sRGB "Destination Primaries" is not activated

### ISSUE THREAD

**Issue by arturoisilvia** [Beep6581/RawTherapee#6245]
When for the first time "sRGB g=2.4 s=12.92" is selected directly, "Destination primaries" and "Black-and-White" check are not activated. 

The first time with the other combobox options works fine. 

You can repeat the error after pressing "Reset" button

-------------------
Version: 5.8-2929-gbe3579e93 windows 10.exe

**Comment by Desmis** [comment]
@arturoisilvia 

Thank you for testing :)

I just push a commit  8c49b240f in dev, that solve this bad behavior

jacques

**Comment by arturoisilvia** [comment]
I have already checked it.
It works fine now. Problem solved.
Thanks Jacques.
