### ISSUE TITLE
Random crashes switching keyboard language. 

### ISSUE THREAD

**Issue by Nicknroll** [Beep6581/RawTherapee#6249]
Hi!
From the very beginning of my use RT i had this problem, when i switching my keyboard ru->eng, to make hotkeys work, i often get random crash, also when i switch back to RT from other tabs(browser, messenger etc.) where i used other language it leads to crash too. Sometimes it happens, sometimes not, so i have no idea what information to provide to check this issue.
It gets annoying because each time i loose my processing settings of current file.

So, please let me know is there some solution or this is known issue.

- RT 5.8
- Microsoft Windows 10 Pro V10.0.19042 Build 19042

Regards
Nick

**Comment by Nicknroll** [comment]
no hints what could be a problem?

**Comment by Thanatomanic** [comment]
@Nicknroll is there a reason why you closed the issue? If the crash is reproducible on your computer, we could investigate.
