### ISSUE TITLE
Perspective tool: Freeze on undo of added control lines

### ISSUE THREAD

**Issue by rebio** [Beep6581/RawTherapee#6251]
**Short description**
RawTherapee freezes when you undo perspective corrections with control lines. It seems that RT does not like the _Edit_ pencil icon to be selected when the changes are undone (Note: I'm writing this while testing, so the information might be all over the place)

**Steps to reproduce**
1. Load any image
2. Go to the "Transform" tab
3. Change "Perspective" from _Single_ to _Camera-based_
4. Click on the _Edit_ button of the control lines
5. Add a few control lines
6. Undo the steps or click on first part of the _History_ on the left
7. RT freezes

RT does only crash when you undo the first selection in the perspective correction (History name "Perspective - Methode | Camera-based") and only if control lines are used (I tried to crash RT with other settings but had no 'luck').
RT does also crash when you delete the control lines.

RT does **not** crash when...
- ...the drop down menu is changed to _Single_ again (so actually also undoing the change). Now you can even undo past "Perspective - Methode | Camera-based". If you undo that switch to _Single_ by adding another control line, RT will again freeze on undo
- ...no control points are added in the perspective correction
- ...you unselect the _Edit_ button
- ...you apply the changes before undoing the changes

**Expected behavior**
RT undoes the changes without freezing.

**Additional information**
**Source:** I downloaded this version from the nightly builds download page
**OS:** Windows 10 (20H2) x64
**RawTherapee:**
- Version: 5.8-2934-gc32623882
- Branch: dev
- Commit: c32623882
- Commit date: 2021-05-21
- Compiler: x86_64-w64-mingw32-gcc\ 9.3.0
- Processor: generic x86
- System: Windows
- Bit depth: 64 bits
- Gtkmm: V3.24.3
- Lensfun: V0.3.2.0
- Build type: Release
- Build flags: -mwin32\ -m64\ -mthreads\ -msse2\ -std=c++11\ -mtune=generic\ -Werror=unused-label\ -Werror=delete-incomplete\ -fno-math-errno\ -Wno-attributes\ -Wall\ -Wuninitialized\ -Wcast-qual\ -Wno-deprecated-declarations\ -Wno-unused-result\ -Wunused-macros\ -fopenmp\ -Werror=unknown-pragmas\ -Wno-aggressive-loop-optimizations\ -DNDEBUG\ -O3\ -ftree-vectorize
- Link flags: -m64\ -mthreads\ -static-libgcc\ -mtune=generic\ -s\ -O3
- OpenMP support: ON
- MMAP support: ON
- Build OS: Linux 4.4.0-101-generic x86_64
- Build date: Fri, 21 May 2021 23:52:33 +0000 UTC
- Build epoch: 1621641153
- Build UUID: dae0651c-0874-4dea-a451-d3130b278aac

I can add the pp3 file, but I'm not sure if this helps since it does not seem to be the change itself, but the button that freezes RT and the button is unselected on restart.

**Comment by Lawrence37** [comment]
I pushed a fix. Let me know if it does not completely solve the issue, and thanks for reporting this bug.
