### ISSUE TITLE
Perspective tool: Strange amplification interaction with Local Adjustments

### ISSUE THREAD

**Issue by rebio** [Beep6581/RawTherapee#6252]
**Short description**
The perspective tool has some strange interactions if Local Adjustment are active (see video file).

**Steps to reproduce**
1. Add some type of Local Adjustment area with a clearly visible effect (I used a larger circle with a maxed out "Lightness" slider in "Color & Light")
2. Go to _Perspective_ in the _Transformation_ tab
3. Switch between the Methods a few times (_Single_ and _Camera-based_) or move the "Focal length" or "Crop factor" slider
4. The effect of the Local Adjustment is amplified

The funny thing is it really seems to amplify the change itself. So lightened areas get brighter, darkened areas get darker and sharpened areas get sharper. Sometimes the zoom level seems to matter for the effect (I was eg. only able to see the over-sharpened effect when I zoomed in a bit), but I guess that's different for each of the Local Adjustment effect type and not the entire bug itself.

The amplification is reverted if...
- the image is moved around
- any perspective slider is changed (Does not apply for "Focal length" and "Crop factor")
- any change is done to the image that requires it to be _recalculation_ (so actually any change that you can see)
- you undo the change or select a different change in the history

The amplification is **not** reverted if...
- the "L\*a\*b - Adjustments" (first tab) are activated and changed
- any value is changed that can not be seen because it's section is not activated

The amplification is also **not** applied to the image itself on export. So it seems to be just a visual bug.

**Expected behavior**
Not amplify the change for the Local Adjustment area.

**Additional information**
**Source:** I downloaded this version from the nightly builds download page
**OS:** Windows 10 (20H2) x64
**RawTherapee:**
- Version: 5.8-2934-gc32623882
- Branch: dev
- Commit: c32623882
- Commit date: 2021-05-21
- Compiler: x86_64-w64-mingw32-gcc\ 9.3.0
- Processor: generic x86
- System: Windows
- Bit depth: 64 bits
- Gtkmm: V3.24.3
- Lensfun: V0.3.2.0
- Build type: Release
- Build flags: -mwin32\ -m64\ -mthreads\ -msse2\ -std=c++11\ -mtune=generic\ -Werror=unused-label\ -Werror=delete-incomplete\ -fno-math-errno\ -Wno-attributes\ -Wall\ -Wuninitialized\ -Wcast-qual\ -Wno-deprecated-declarations\ -Wno-unused-result\ -Wunused-macros\ -fopenmp\ -Werror=unknown-pragmas\ -Wno-aggressive-loop-optimizations\ -DNDEBUG\ -O3\ -ftree-vectorize
- Link flags: -m64\ -mthreads\ -static-libgcc\ -mtune=generic\ -s\ -O3
- OpenMP support: ON
- MMAP support: ON
- Build OS: Linux 4.4.0-101-generic x86_64
- Build date: Fri, 21 May 2021 23:52:33 +0000 UTC
- Build epoch: 1621641153
- Build UUID: dae0651c-0874-4dea-a451-d3130b278aac

https://user-images.githubusercontent.com/10911084/119240382-0f60b400-bb47-11eb-811e-639ee2d614f6.mp4

**Comment by Thanatomanic** [comment]
Thanks for reporting. I've seen a similar thing before recently, but I can't find the relevant issue or commit. It is indeed only a visual bug. @Desmis could you take a look?

**Comment by Desmis** [comment]
I think, I am not sure, it is an interaction between "events"...in the pipeline - only with "improccoordinator.cc" and "dcrop.cc"...

See "refresmap.h" and "dcop  / improcoordinator"

LA is "guided" by  "M_AUTOEXP" and  "AUTOEXP"
Perspective is guided by "M_TRANSFORM " and "TRANSFORM"  / "VOID" 

But, I have not "the" solution :)

Jacques

**Comment by Thanatomanic** [comment]
I have found the similar issue: https://github.com/Beep6581/RawTherapee/issues/6132

**Comment by Desmis** [comment]
@Thanatomanic 
It may sound like the same thing, but here it's a little different. In the case of "local contrast" it was mainly the location in the pipeline that was at stake (with of course also an event).

Here, as long as you don't activate the new features (which are really very good), the system works correctly...(Method - simple : horizontal : vertical) enable before "LA".

Clearly I think (??) it's the addition of new features that creates the problem...but that's not why it's easy to deal with

**Comment by heckflosse** [comment]
I will have a look

**Comment by heckflosse** [comment]
this should fix it:

```diff
diff --git a/rtengine/refreshmap.h b/rtengine/refreshmap.h
index 05a8f7f44..b53252796 100644
--- a/rtengine/refreshmap.h
+++ b/rtengine/refreshmap.h
@@ -61,7 +61,7 @@
 #define CAPTURESHARPEN                   (M_INIT|M_SPOT|M_LINDENOISE|M_HDR|M_TRANSFORM|M_BLURMAP|M_AUTOEXP|M_RGBCURVE|M_LUMACURVE|M_LUMINANCE|M_COLOR|M_CSHARP)
 #define HDR                                     (M_SPOT|M_LINDENOISE|M_HDR|M_TRANSFORM|M_BLURMAP|M_AUTOEXP|M_RGBCURVE|M_LUMACURVE|M_LUMINANCE|M_COLOR)
 #define SPOTADJUST                                                       (M_SPOT|M_HDR|M_BLURMAP|M_AUTOEXP|M_RGBCURVE|M_LUMACURVE|M_LUMINANCE|M_COLOR)
-#define TRANSFORM                                                         (M_TRANSFORM|M_BLURMAP|M_AUTOEXP|M_RGBCURVE|M_LUMACURVE|M_LUMINANCE|M_COLOR)
+#define TRANSFORM                                                         (M_SPOT|M_HDR|M_TRANSFORM|M_BLURMAP|M_AUTOEXP|M_RGBCURVE|M_LUMACURVE|M_LUMINANCE|M_COLOR)
 #define AUTOEXP                                                                    (M_SPOT|M_HDR|M_AUTOEXP|M_RGBCURVE|M_LUMACURVE|M_LUMINANCE|M_COLOR)
 #define RGBCURVE                                                                                          (M_RGBCURVE|M_LUMACURVE|M_LUMINANCE|M_COLOR)
 #define LUMINANCECURVE                                                                                               (M_LUMACURVE|M_LUMINANCE|M_COLOR)

```

**Comment by Desmis** [comment]
@heckflosse 

Ingo
I think (I am sure), this patch fix the bad behavior :)

jacques

**Comment by rebio** [comment]
@heckflosse 
I checked if this is fixed now:
- Windows 7: Yes (But I did not test if it even existed before updating)
- Windows 10: It's still there

**Comment by Thanatomanic** [comment]
> Windows 7: Yes (But I did not test if it even existed before updating)
Windows 10: It's still there

That should not be possible.
