### ISSUE TITLE
film negative: unexpected "white balance" tool behaviour: output level keeps rising

### ISSUE THREAD

**Issue by nomar500** [Beep6581/RawTherapee#6257]
RT-5.8, run on M1 mac.

- `AboutThisBuild.txt`

```
Version: 5.8-2947-g2f2720b76
Branch: dev
Commit: 2f2720b76
Commit date: 2021-05-23
Compiler: 
Processor: 
System: 
Bit depth: 
Gtkmm: V
Lensfun: V
Build type: 
Build flags: 
Link flags: 
OpenMP support: 
MMAP support: 
Build OS: Darwin 20.4.0 arm64
Build date: Sun, 23 May 2021 20:03:43 +0000 UTC
Build epoch: 1621800223
Build UUID: 9054050a-1325-4de1-9ba2-762282429a88
```

cc. @rom9 

When attempting to reproduce #6230, I have noticed the *`film negative`* _white balance_ tool behaves in an unexpected fashion: 
- choosing "obviously" wrong middle gray values throws some kind of offset into the mix and makes it seemingly impossible to go back to normal values (by selecting a more suitable middle gray target, that is).
- it appears to be related to the "Output level" slider: it keeps rising.

step 1.
Starting point: 
<img width="1113" alt="image" src="https://user-images.githubusercontent.com/80070738/119403813-381bb180-bcdf-11eb-877e-fabdd41e6bfd.png">

step 2. 
"oops, I clicked on the red paint, on the bus"
<img width="1113" alt="image" src="https://user-images.githubusercontent.com/80070738/119403928-600b1500-bcdf-11eb-974f-9d4db9c6b546.png">

step 3.
"this time, I've sample white paint, on the bus"
<img width="1113" alt="image" src="https://user-images.githubusercontent.com/80070738/119404005-7c0eb680-bcdf-11eb-810a-e9e172804b22.png">

step 4 (repeats step 2).
see Output level is now obviously higher
<img width="1113" alt="image" src="https://user-images.githubusercontent.com/80070738/119404066-90eb4a00-bcdf-11eb-90c2-6c0a7329237c.png">

step 5 (repeats step 3).
<img width="1113" alt="image" src="https://user-images.githubusercontent.com/80070738/119404146-b1b39f80-bcdf-11eb-8e66-19bdbcf3ccc6.png">

❓ is this expected ?

To work around this issue, the "obvious" fix is: 
- pick a suitable gray area and MANUALLY adjust Output level slider until histogram is decent (i.e. not clipped)

**Comment by Thanatomanic** [comment]
I can confirm the behavior by just repeatedly sampling different areas of different hues and lightness.

**Comment by rom9** [comment]
Sorry @Thanatomanic , i'm afraid i did a big mess with my last push attempting to fix this issue... i don't know how that "Merge remote tracking..." commit ended up there.
I'm trying to find a way to undo that, google seems to suggest `git revert` or `git reset` ... any idea on how to fix it?
Sorry again :-(

**Comment by Thanatomanic** [comment]
I think everything is fine and nothing needs to be done. Take for example a look at https://github.com/Beep6581/RawTherapee/blob/dev/rtgui/controllines.cc. While your 'Merge remote tracking' commit says it altered that file, the latest _actual_ commit to the file was by Lawrence a few days ago.

**Comment by rom9** [comment]
Yes, maybe you're right, i also saw a similar pattern with commit e63c9336a6dfd64c13b37434805ffa51b5f0e729 some days ago.
Also, i tried cloning a fresh copy of the repo, and the content seems as expected.
OMG, thanks, i was literally panicking  :-)
I must have done something wrong though, i need to improve my git knowledge... sorry again.

Anyway, the spot sampling should be fixed now.

@nomar500 can you try again with current dev ?

**Comment by nomar500** [comment]
@rom9, thanks :)

meh, unfortunately, #6270 is on my plate, I can't seem to build, for the moment. I'll keep you posted.

**Comment by nomar500** [comment]
@rom9, 
as promised, since #6270 is not a problem anymore, I was able to carry out a few tests on your fix.
It appears to work just fine! Thanks. 😃
