### ISSUE TITLE
Preview DeltaE for Contrast by Detail Levels doesn't work as expected

### ISSUE THREAD

**Issue by chaimav** [Beep6581/RawTherapee#6258]
RT 5.8-2945, Windows 10.

Using Preview DeltaE for the Contrast by Detail Levels does not show green highlights
![Contrast levels](https://user-images.githubusercontent.com/47765782/119548647-6abbbd80-bd64-11eb-904d-7033ae96257e.JPG)

This is what I expected it to look like (using a different tool)
![Local contast](https://user-images.githubusercontent.com/47765782/119548735-82934180-bd64-11eb-94b8-8ee1c2c81406.JPG)

Interestingly, if I push the contrast to the extreme, I see yellow and blue highlights, but still no green.
![Contrast levels extreme](https://user-images.githubusercontent.com/47765782/119548861-a8b8e180-bd64-11eb-9d21-80a462dc8a41.JPG)

**Comment by Desmis** [comment]
@chaimav 
With Contrast by detail Level, you MUST use  - Mask and modifications (standard or advanced) / Preview dE

As already mentioned, the "preview dE" button in settings - which I was asked to add -  can only work well with "Color" Spots (Color and Light, SH, Vibrance..) and a tool only activated.

You have the same behavior with Retinex...In this case (and also Denoise....) others algorithms are used for dE and transitions.

Jacques
