### ISSUE TITLE
Perspective tool: Strange visual interaction with Local Adjustments (part 2)

### ISSUE THREAD

**Issue by rebio** [Beep6581/RawTherapee#6259]
**Short description**
The effect of a local adjustment spot is sometimes visually removed from the preview.

**Steps to reproduce**
1. Open a file
2. Add an LA spot with good visibility (I have chosen "Color & Light" with a maxed out Lightness slider and colour correction with a maxed out strength slider)
3. Go to the perspective tool and move some sliders
This did not work with "Focal length" and "Crop factor" for me.
Sometimes one slider works, the next time the exact same slider did not. Usually "Rotation", "Vertical" and "Horizontal" were the esiest to reproduce. But sometimes the spot also _vanished_ as I clicked on a previous step in the history.
4. The spot vanishes
Sometimes it has some very strange fade-in and fade-out effects. Eg. Sometimes when moving the rotation slider the spot faded in at the very end of the slider and faded out when I moved the slider back. The next time the same thing happened with the "Vertical" or "Horizontal" slider, but this time the fade out happened when I moved it away from the default position and it faded back in when I moved it back to it's original position.
Just an idea: Maybe this is caused by the spot? When the spot is moved over a certain not so often used colour, the area is decreased and fades out? On the other had the doggo is pretty much back all round and there should thereby not be a _fade in/out_ look.

**Expected behavior**
Always show the spot and never have any interaction between it and the sliders

**Notes**
- **The change is only a visual bug**
No matter how much I tested, the final image always showed up with the change applied to it
- Some non-perspective changes make the spot is visible again (eg. exposure, Contrast by Detail Levels) others did not (eg. L\*a\*b - Adjustments, Sharpening, Shadows/Lights)
- When you single click or hold and drag the spot is visible. When the click is over or you let go of the mouse button, the spot vanishes again
- Sometimes #6252 is back again and is activated by the Focal length and crop factor sliders. But not reproducable. On my Windows 7 machine I never had the issue. On my Windows 10 machine it sometimes shows itself again

**Additional information**
**Source:** I downloaded this version from the nightly builds download page
**OS:** Windows 10 (20H2) x64
**RawTherapee:**
- Version: 5.8-2945-g36f1300a6
- Branch: dev
- Commit: 36f1300a6
- Commit date: 2021-05-22
- Compiler: x86_64-w64-mingw32-gcc\ 9.3.0
- Processor: generic x86
- System: Windows
- Bit depth: 64 bits
- Gtkmm: V3.24.3
- Lensfun: V0.3.2.0
- Build type: Release
- Build flags: -mwin32\ -m64\ -mthreads\ -msse2\ -std=c++11\ -mtune=generic\ -Werror=unused-label\ -Werror=delete-incomplete\ -fno-math-errno\ -Wno-attributes\ -Wall\ -Wuninitialized\ -Wcast-qual\ -Wno-deprecated-declarations\ -Wno-unused-result\ -Wunused-macros\ -fopenmp\ -Werror=unknown-pragmas\ -Wno-aggressive-loop-optimizations\ -DNDEBUG\ -O3\ -ftree-vectorize
- Link flags: -m64\ -mthreads\ -static-libgcc\ -mtune=generic\ -s\ -O3
- OpenMP support: ON
- MMAP support: ON
- Build OS: Linux 4.4.0-101-generic x86_64
- Build date: Sat, 22 May 2021 23:53:34 +0000 UTC
- Build epoch: 1621727614
- Build UUID: 7fbca5cf-84a3-4978-b5cb-36646f15e7a8

**Images**
The setup before any change
![RawTherapee - Perspective Tool - vanishing point - visible point](https://user-images.githubusercontent.com/10911084/119551175-3f9b9300-bd91-11eb-8a2d-a887a3428d08.png)

The setup when the point has vanished
![RawTherapee - Perspective Tool - vanishing point - vanished point](https://user-images.githubusercontent.com/10911084/119551190-44604700-bd91-11eb-88d1-d2fcd6979e6d.png)

The setup when you clicked once or dragged it around
![RawTherapee - Perspective Tool - vanishing point - click and drag](https://user-images.githubusercontent.com/10911084/119552082-3f4fc780-bd92-11eb-8957-fcc621973e32.png)

**Comment by Thanatomanic** [comment]
@rebio You're testing on a wrong commit (36f1300) instead of where @heckflosse actually made the fix (https://github.com/Beep6581/RawTherapee/commit/2f2720b763eb15118d4150d97c4e21ebcb497de7)

I cannot reproduce this issue on the latest `dev` (https://github.com/Beep6581/RawTherapee/commit/6e68cab5d970191b92e03aa7da7e6b0be7d9a3e4).

**Comment by rebio** [comment]
> @rebio You're testing on a wrong commit ([36f1300](https://github.com/Beep6581/RawTherapee/commit/36f1300a6b39f5addb3aa47f156582089d8de375)) instead of where @heckflosse actually made the fix ([2f2720b](https://github.com/Beep6581/RawTherapee/commit/2f2720b763eb15118d4150d97c4e21ebcb497de7))

The automated builds seem to be stuck again. Latest for Windows is 5.8-2945-g36f1300a6_20210523.

**Comment by rebio** [comment]
This issue can no longer be reproduced with version 5.8-2980-g2e6e52f33

**Comment by Beep6581** [comment]
> The automated builds seem to be stuck again. 

Fixed, for now.
