### ISSUE TITLE
Perspective tool: Control sliders exist two times

### ISSUE THREAD

**Issue by rebio** [Beep6581/RawTherapee#6260]
**Short description**
The same control sliders exist two times

**Steps to reproduce**
1. Open the perspective tools and scroll down

**Expected behavior**
Only have two handles or tell me in a tooltip the use of the second one.

**Notes**
Is it a bug? I'm not sure.
I'm maybe not professional enough to see the use in this, but I can negate the change of the one slider by reversing it's value in the second box. That seems somewhat useless to me (unless your image is that hard distorted that you need the same effect a second time - I guess thats unlikely though and if your image is that bad it is ruined anyway)

**Additional information**
**Source:** I downloaded this version from the nightly builds download page
**OS:** Windows 10 (20H2) x64
**RawTherapee:**
- Version: 5.8-2945-g36f1300a6
- Branch: dev
- Commit: 36f1300a6
- Commit date: 2021-05-22
- Compiler: x86_64-w64-mingw32-gcc\ 9.3.0
- Processor: generic x86
- System: Windows
- Bit depth: 64 bits
- Gtkmm: V3.24.3
- Lensfun: V0.3.2.0
- Build type: Release
- Build flags: -mwin32\ -m64\ -mthreads\ -msse2\ -std=c++11\ -mtune=generic\ -Werror=unused-label\ -Werror=delete-incomplete\ -fno-math-errno\ -Wno-attributes\ -Wall\ -Wuninitialized\ -Wcast-qual\ -Wno-deprecated-declarations\ -Wno-unused-result\ -Wunused-macros\ -fopenmp\ -Werror=unknown-pragmas\ -Wno-aggressive-loop-optimizations\ -DNDEBUG\ -O3\ -ftree-vectorize
- Link flags: -m64\ -mthreads\ -static-libgcc\ -mtune=generic\ -s\ -O3
- OpenMP support: ON
- MMAP support: ON
- Build OS: Linux 4.4.0-101-generic x86_64
- Build date: Sat, 22 May 2021 23:53:34 +0000 UTC
- Build epoch: 1621727614
- Build UUID: 7fbca5cf-84a3-4978-b5cb-36646f15e7a8

**Images**
![RawTherapee - Perspective Tool - multiple tools](https://user-images.githubusercontent.com/10911084/119554815-082ee580-bd95-11eb-81fe-51dd3e12eceb.png)

**Comment by Thanatomanic** [comment]
I'm sorry, but I know you have seen this. I wonder if you have understood it? https://github.com/Beep6581/RawTherapee/issues/6241
The sliders are part of different boxes, so they have different purposes. I think @Lawrence37 explains them well.
