### ISSUE TITLE
Perspective tool: Local Adjustment spots are not changed with the rest of the image

### ISSUE THREAD

**Issue by rebio** [Beep6581/RawTherapee#6261]
**Short description**
Local Adjustments spots stay in their place when the perspective tool is used

**Steps to reproduce**
1. Add a Local Adjustment spot with good visibility (I have chosen "Color & Light" with a maxed out Lightness slider and colour correction with a maxed out strength slider)
2. Go to the perspective tool
3. Change some sliders
4. The LA spot stays in the same position while the rest of the image is corrected

**Expected behavior**
The Local Adjustment spot is moved, rotated, shifted, etc. with the entire image

**Comment**
I guess this is caused by the _first generation_ of LA that was focused on getting it to work.
But it's suboptimal when I add a bunch of LA spots, perspective corrected the image and then had to readjust the LA spots again. And since the spot settings are limited in terms of their placement and rotation (see also #6254 ) it could be a quite the annoying task to do.
More than likely as a non pro-photographer I'm not used to a fixed cycle and I'm maybe doing changes in the wrong order. However, the perspective tool is located in the tab AFTER the LA tab. So if you just go from left to right (and do not want to hop between the tabs), you will get to the perspective tool after the (eventually used) Local Adjustments

Note: I selected any slider and not a particular one.

**Additional information**
**Source:** I downloaded this version from the nightly builds download page
**OS:** Windows 10 (20H2) x64
**RawTherapee:**
- Version: 5.8-2945-g36f1300a6
- Branch: dev
- Commit: 36f1300a6
- Commit date: 2021-05-22
- Compiler: x86_64-w64-mingw32-gcc\ 9.3.0
- Processor: generic x86
- System: Windows
- Bit depth: 64 bits
- Gtkmm: V3.24.3
- Lensfun: V0.3.2.0
- Build type: Release
- Build flags: -mwin32\ -m64\ -mthreads\ -msse2\ -std=c++11\ -mtune=generic\ -Werror=unused-label\ -Werror=delete-incomplete\ -fno-math-errno\ -Wno-attributes\ -Wall\ -Wuninitialized\ -Wcast-qual\ -Wno-deprecated-declarations\ -Wno-unused-result\ -Wunused-macros\ -fopenmp\ -Werror=unknown-pragmas\ -Wno-aggressive-loop-optimizations\ -DNDEBUG\ -O3\ -ftree-vectorize
- Link flags: -m64\ -mthreads\ -static-libgcc\ -mtune=generic\ -s\ -O3
- OpenMP support: ON
- MMAP support: ON
- Build OS: Linux 4.4.0-101-generic x86_64
- Build date: Sat, 22 May 2021 23:53:34 +0000 UTC
- Build epoch: 1621727614
- Build UUID: 7fbca5cf-84a3-4978-b5cb-36646f15e7a8

**Images**
The image with an LA spot and then with a changed slider. The LA spot stays in the same position on the _global layer_ but is not adjusted with the rest of the image
![RawTherapee - Perspective Tool - moving LA spot 01](https://user-images.githubusercontent.com/10911084/119556732-42998200-bd97-11eb-860a-5aa0b175bc63.png)
![RawTherapee - Perspective Tool - moving LA spot 02](https://user-images.githubusercontent.com/10911084/119556914-7aa0c500-bd97-11eb-98d0-6a89f58b04ed.png)

**Comment by Thanatomanic** [comment]
This is intended behavior and I daresay impossible to change. The perspective corrections happen earlier in the pipeline than the local adjustments. That means you will not see the spot move along with the perspective correction. It stays in the same relative location to the image frame.
Also, because of the way the spots work, it is impossible to transform them along with the changes to the perspective. Imagine, how would the spot ellipse and rectangle look like?

> However, the perspective tool is located in the tab AFTER the LA tab.

Do you save the raw tab for last as well?
