### ISSUE TITLE
Wavelet levels -> wavelet levels < 7 + contrast + denoise = segfault or weird behaviour

### ISSUE THREAD

**Issue by ghost** [Beep6581/RawTherapee#6264]
**Short description**
I ran into some unwanted behaviour when using the *Wavelet Level* section using 2 different development versions of RawTherapee. The result is slightly different, the steps to reproduce are the same.

Using *RawTherapee_dev_5.8-2948-g6189a0e_20210524.AppImage*

Activating both Contrast and Denoise and Refine results in a black/white pattern when the Wavelet levels setting is set to **6** or lower.

Using *RawTherapee, version 5.8-2983-g4c2f9c7c5 (latest build)*

Activating both _Contrast_ and _Denoise and Refine_ results in a grey screen or a segfault when the Wavelet levels setting is set to **5**

I've ran into this issue in the past but was never able to narrow it down to specific steps. I've always thought that it was a wavelet denoise issue in combination with settings from another module altogether. This seems to be purely wavelet related though.

**Steps to reproduce**
1. Load an image,
2. Activate _Wavelet levels_ module,
3. Activate *Contrast*,
4. Activate *Denoise and Refine*,
5. Go to the _Wavelet Settings_ section and lower the Wavelet levels to 6 (or 5 depending on version)
6. See the above mentioned result(s)

**Expected behavior**
Being able to use Wavelet module without crashes or weird behaviour

**Video of this behaviour**

Black and white weirdness in [2958 \[mp4\]](https://user-images.githubusercontent.com/56407344/119970127-e2752c80-bf9e-11eb-8e78-277d60c1f3db.mp4)

Greyed out and crash in [2983 \[mp4\]](https://user-images.githubusercontent.com/56407344/119972147-64feeb80-bfa1-11eb-833a-7a21cc80b4ee.mp4)

**Additional information**

Just in case: 2 of the images I used can be found on pixls:

* [the bird](https://discuss.pixls.us/t/sharpening-and-denoising-with-dt-and-others/25210)
* [the house](https://discuss.pixls.us/t/play-raw-amulree-kirk/12259)

My base profile: [base.profile.pp3.txt](https://github.com/Beep6581/RawTherapee/files/6560225/base.profile.pp3.txt)
I have also replicated this issue when starting with a neutral profile and then doing the above mentioned steps.

I can replicate this in 2 different versions:

* 2983-g4c2f9c7c5
* 2948-g6189a0e (appimage)

The first one is self build:

* OS                : Linux (kernel 5.9.15-1 x86_64 amd64)
* Distro            : Debian Buster (rel. 10.9)
* Graphics driver   : nvidia (460.39)

**Build info**

* Compiler      : gcc 8.3.0
* Cmake         : 3.13.4
* Glib          : 2.58.3-2
* Gtk+          : 3.24.5-1
* Exiv2         : 1.0.0.9
* Lensfun       : 0.3.2-4

**Build using:**

cmake \
    -DBUNDLE_BASE_INSTALL_DIR="$HOME/.local/${TRGT}" \
    -DBUILD_BUNDLE="ON" \
    -DCACHE_NAME_SUFFIX="5-dev" \
    -DCMAKE_BUILD_TYPE="release"  \
    -DPROC_TARGET_NUMBER="2" \
    -DOPTION_OMP="ON" \
    -DBUILD_SHARED="OFF" \
    -DWITH_LTO="ON" \
    -DWITH_BENCHMARK="OFF" \
    -DWITH_MYFILE_MMAP="ON" \
    -DWITH_PROF="OFF" \
    -DWITH_SAN="OFF" \
    -DWITH_SYSTEM_KLT="OFF" \
    .. || exit 249

**Build flags:**

    -DNDEBUG
    -O3
    -Wall
    -Wcast-qual
    -Werror=delete-incomplete
    -Werror=unknown-pragmas
    -Werror=unused-label
    -Wno-attributes
    -Wno-deprecated-declarations
    -Wno-unused-result
    -Wuninitialized
    -Wunused-macros
    -flto
    -fno-math-errno
    -fopenmp
    -ftree-vectorize
    -march=native
    -std=c++11

**Comment by heckflosse** [comment]
I tried to reproduce, but could not.

**Comment by ghost** [comment]
I did some more testing:

* I installed RawTherapee_dev_5.8-2948-g6189a0e_20210524.AppImage on my older **Intel box** and I **cannot** reproduce this issue.
* I tried reproducing this using the old, stable RawTherapee_5.8.AppImage on both my older Intel and current AMD machine: I **cannot** reproduce.
* On my AMD box and using dev_5.8-2948 (appimage) and 5.8-2983 (self build) I removed everything and started with a clean slate: I **can** reproduce this issue.
* This is not limited to the 3 images shown in my initial post. It does seem that different images sometimes have different results. Here are two using 5.8-2983 that are partially greyed out (this turn out to be the more common scenario):

NEF (D90):

![d90 nef](https://user-images.githubusercontent.com/56407344/119991103-a2bb3e80-bfb8-11eb-88e8-8303d7297a5b.png)

ARW (ILCE 6000):

![ilce 6000 arw](https://user-images.githubusercontent.com/56407344/119991112-a64ec580-bfb8-11eb-8c10-5e287616fce4.png)

A hard crash only occurs when more editing involving other modules is done (I'm as of yet not able to determine which combo's trigger it).

As mentioned in my initial post: I've run into this issue before but was not able to reproduce it, now I am. It is the reason that I reluctantly use Wavelet levels when editing my own images (a crash looses all the edits, wavelet and others alike...), even though it is a very nice tool to have in your toolbox. 

Could this be specific hardware in combo with RT related in any way?

**Hardware**

* CPU              : AMD Ryzen 5 3600 6-Core Processor
* GPU              : GeForce RTX 2060 SUPER 7979 MiB
* Memory           : 32 Gb + 15 Gb Swap

**Comment by Desmis** [comment]
I cannot reproduce

**Comment by ghost** [comment]
Mmmm.....

The following is all done with _5.8-2981-gfba97f62b_

--18:25--

I just rebuild rawtherapee with _relwithdebinfo_ (and turned  LTO OFF, which is the default). I still get the exact same behaviour (a segfault when using the bird pic).

What makes this ff-ing frustrating is that when I run rawtherapee via gdb to catch some info it does not segfault but the result are not consistent: It either shows the black/white version as shown in one of the mp4s or it just works.....

--18:40--

Lets try _debug_ instead of relwithdebinfo.

No problems whatsoever, works as it should! Either via gdb or direct. Just a bit too slow to make this a workable solution though :rofl:

LTO ON or OFF doesn't make a difference.

--18:55--

Back to a _release_ and LTO=ON build

RawTherapee immediately crashes when loading the bird (I didn't turn off the denois part in my previous test....)

This is just weird.....

**Comment by Desmis** [comment]
@jade-nl 
Have you tried with the wavelet and denoise version of Local adjutments...(identical or similar functions...)
Depending on the result, this could orientate the research (OMP ?, ??) 

Thank you

**Comment by ghost** [comment]
Just to reiterate what I'm working with and to be on the same page;

* [This bird](https://discuss.pixls.us/t/sharpening-and-denoising-with-dt-and-others/25210)
* [This pp3](https://github.com/Beep6581/RawTherapee/files/6562671/bird.costa.rica.cr2.pp3.txt) (had to add _dot txt_ due to github's upload rules)

Loading these and turning on *Denoise and Refine* crashes version _5.8-2981-gfba97f62b_

With the same bird and pp3 as starting point:

* Added a *Local contrasts and Wavelet* spot, selected wavelets and moved all sliders
* Added a separate *Blur/Grain & Denoise* spot (checked all 3 modes and turned up all sliders that could be)
* added a third spot and added **both** *Local contrasts and Wavelet* and *Blur/Grain & Denoise* to this one spot (one spot 2 tools)
* Added a third tool, _Contrast by detail level_, to the third spot (this one is also wavelet based if I'm not mistaken).

No weirdness happens during all of the above.

This is the pp3 I ended up with after all the above: [bird.costa.rica.cr2.pp3.txt](https://github.com/Beep6581/RawTherapee/files/6562719/bird.costa.rica.cr2.pp3.txt) I randomly set values for the sliders.

PS: Going back to the wavelet module after all this and turning on denoise still crashes RT.

**Comment by ff2000** [comment]
Debian AFAIK uses systemd as init. Likely it already has enabled saving of coredumps. You can list and load these with "coredumpctl". This doesn't require running the process in gdb.

I unfortunately also wasn't able to reproduce the crash.

**Comment by Desmis** [comment]
@jade-nl 
Very difficult to find...beacuse with my Windows8 and Intel (old), all works fine...
So, blindly, I make a try for you to try, inverting 2 treatments that determine the level of decomposition

Branch "wavecrash"
https://github.com/Beep6581/RawTherapee/tree/wavecrash

**Comment by ghost** [comment]
@ff2000 : Thanks for that info. _coredumpctl_ isn't installed by default, but that was remedied easily. And a little early morning reading got me to use it (hopefully correctly...). Here's some output that was generated after segfaulting (backtrace file is at the end):
```

[stasis] root ~ # coredumpctl
TIME                            PID   UID   GID SIG COREFILE  EXE
Sat 2021-05-29 08:46:15 CEST  30247  1001  1111  11 present   /home/jade/.local/rt.dvlp/rawtherapee
```

And some more in-depth info:

```
[stasis] root ~ # coredumpctl gdb /home/jade/.local/rt.dvlp/rawtherapee
           PID: 30247 (rawtherapee)
           UID: 1001 (jade)
           GID: 1111 (jd)
        Signal: 11 (SEGV)
     Timestamp: Sat 2021-05-29 08:46:05 CEST (11min ago)
  Command Line: /home/jade/.local/rt.dvlp/rawtherapee
    Executable: /home/jade/.local/rt.dvlp/rawtherapee
 Control Group: /user.slice/user-1000.slice/session-2.scope
          Unit: session-2.scope
         Slice: user-1000.slice
       Session: 2
     Owner UID: 1000 (druuna)
       Boot ID: ffda2f6916cc4546b8a46d0171c49209
    Machine ID: 318f8b1d3cc94646b01efecd1202a7df
      Hostname: stasis
       Storage: /var/lib/systemd/coredump/core.rawtherapee.1001.ffda2f6916cc4546b8a46d0171c49209.30247.1622270765000000
       Message: Process 30247 (rawtherapee) of user 1001 dumped core.
                
                Stack trace of thread 4442:
                #0  0x000055cd80098f95 n/a (/home/jade/.local/rt.dvlp/rawtherapee)

GNU gdb (Debian 8.2.1-2+b3) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/jade/.local/rt.dvlp/rawtherapee...(no debugging symbols found)...done.
[New LWP 4442]
[New LWP 30247]
[New LWP 4448]
[New LWP 30248]
[New LWP 4446]
[New LWP 4450]
[New LWP 4441]
[New LWP 4452]
[New LWP 4445]
[New LWP 4451]
[New LWP 4444]
[New LWP 4447]
[New LWP 30253]
[New LWP 4443]
[New LWP 30257]
[New LWP 30259]
[New LWP 30251]
[New LWP 30250]
[New LWP 30255]
[New LWP 30249]
[New LWP 4449]
[New LWP 30258]
[New LWP 30256]
[New LWP 30254]
[New LWP 30252]
[New LWP 30266]
[New LWP 30280]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/home/jade/.local/rt.dvlp/rawtherapee'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055cd80098f95 in rtengine::ImProcFunctions::softLight(rtengine::LabImage*, rtengine::procparams::SoftLightParams const&) [clone ._omp_fn.0] ()
[Current thread is 1 (Thread 0x7fbe7dffb700 (LWP 4442))]
(gdb) set logging file mybacktrace.txt
(gdb) set logging on
Copying output to mybacktrace.txt.
(gdb) set pagination off
(gdb) thread apply all bt full

```

And this is the backtrace that was created by that last command: [mybacktrace.txt](https://github.com/Beep6581/RawTherapee/files/6564161/mybacktrace.txt)

**Comment by ghost** [comment]
@Desmis : I'll give that a go, but I do have to do some other stuff first. Stay tuned......

**Comment by ghost** [comment]
@Desmis 

Decided to postpone my other "duties" and test the _wavecrash_ branch: It still crashes.

**EDIT**: Build with _release_ instead of *relwithdebinfo*. Rebuilding as I type, info in new post follows shortly

Sorry.

**Comment by Desmis** [comment]
@jade-nl 
I don't think "soflight" is the cause....only due to bad datas ?

Could you look at "console messages"

Here with your raw (bird) and pp3
Without denoise wavelet

minQ=1.994351 maxQ=175.824295  Qpro=230.020416
Ip Wavelet uses 1 main thread(s) and up to 8 nested thread(s) for each main thread
cp4=30.000000 cpmul5=0.000000 cp6=0.000000 cp7=0.000000 cp8=0.000000
levwbef=5
levwafter=5
Level decomp L=5
CHRO var0=0.000001 va1=0.000001 va2=0.000001 va3=0.000001 va4=0.000001 val5=0.000001 va6=0.000010
Leval decomp a=5
Leval decomp b=5
minQ=1.915441 maxQ=176.847763  Qpro=230.020416


With Denoise wavelet - and slider denoise = 0
minQ=1.994351 maxQ=175.807602  Qpro=230.020416
Ip Wavelet uses 1 main thread(s) and up to 8 nested thread(s) for each main thread
cp4=30.000000 cpmul5=0.000000 cp6=0.000000 cp7=0.000000 cp8=0.000000
levwbef=7
levwafter=7
Level decomp L=7
CHRO var0=0.000100 va1=0.000005 va2=0.000001 va3=0.000001 va4=0.000010 val5=0.000001 va6=0.000010
Leval decomp a=6
Leval decomp b=6
minQ=1.915441 maxQ=176.645676  Qpro=230.020416


With Denoise wavelet - sliders different from 0, and chrominance denoise
Ip Wavelet uses 1 main thread(s) and up to 8 nested thread(s) for each main thread
cp4=30.000000 cpmul5=0.000000 cp6=0.000000 cp7=0.000000 cp8=0.000000
levwbef=7
levwafter=7
Level decomp L=7
LUM var0=0.004555 var1=0.022130 var2=0.018000 var3=0.001509 var4=0.000001
denoise standard L
CHRO var0=1.026169 va1=0.513085 va2=0.307851 va3=0.153925 va4=0.153925 val5=0.002226 va6=0.000010
Leval decomp a=6
denoise standard a
Leval decomp b=6
Denoise standard b
minQ=1.855173 maxQ=176.573318  Qpro=230.020416

jacques

**Comment by ghost** [comment]
Man this get weirder by the minute:

If I build using *release* + the *wavecrash* branch: It crashes. Same behaviour as before.
If I build using *relwithdebinfo* + the *wavecrash* branch: No crash and no weirdness. This is different then before (then it crashed, but did not crash when running via rawtherapee from within gdb).

Just rebuild again with *release* + *wavecrash*: Yep, that one crashes.

BTW: I do see some extra info in the terminal when building with the wavecrash branch. I see lines like this:

```
cp4=30.000000 cpmul5=-nan cp6=0.000000 cp7=0.000000 cp8=-624161080998984594950717440.000000
levwbef=5 
cp4=30.000000 cpmul5=-nan cp6=0.000000 cp7=0.000000 cp8=2207395086336.000000
levwbef=7 
Segmentation fault (core dumped)
RawTherapee, version 5.8-2983-gfa59b9d01
``` 

Just in case: This is the backtrace file that belongs to the *release* + *wavecrash* build: [backtrace.txt](https://github.com/Beep6581/RawTherapee/files/6564278/backtrace.txt)

**Comment by ghost** [comment]
Just tried: The softlight module does have an influence and is the cause why it crashes.

If I turn the softlight module off and the denoise section in wavelets on, rt doesn't crash but this happens instead:

![softlight off denoise on](https://user-images.githubusercontent.com/56407344/120063628-ab168680-c057-11eb-9711-a416b530d3e6.png)


EDIT: Switching from *wavelet levels* 5 to 6 or 7 solves it, as does turning off the *contrast* section

EDIT 2 : This "only" affects the edit window. If I switch to the file browser all is ok and if I process the image via the queue all edits are there as well. I can't see what I'm doing in the edit window, but this info might be helpful.

**Comment by Desmis** [comment]
@jade-nl 
I see that multipliers contrast are bad in your case...I set to zero when not used.

Can you try the new commit 13b2adb70

Thank you

**Comment by Desmis** [comment]
Sorry  I have forgotten one commit...

New now fbeb3d195

**Comment by Desmis** [comment]
Yes Softlight shows the bad behavior with a crash, it is the first after wavelet...Hence if wavelet is corrupted, softlight crash

**Comment by ghost** [comment]
You are the man! This seems to be fixed.

I do need to do some more extensive testing but I just tried 2 completely different RAWs, turned on, then off, just about all the options available in many combinations and all seems to work as expected now.

Thank you, I'm very happy this is fixed.

BTW, terminal output looks like this now:

```
cp4=0.000000 cpmul5=0.000000 cp6=0.000000 cp7=0.000000 cp8=0.000000 levwbef=1 
```

All lines are the same except: _levwbef=_ shows up as either 1,5,6 or 7 (98% it is 7)

Closing this one now. If I do run into an issue relating to this I can always reopen it.

Have a nice weekend!

**Comment by Desmis** [comment]
@jade-nl 

Happy to have found the bug...

I clean code, then if ok,
* new test  by you
 * then I merge

**Comment by ghost** [comment]
No problem, I'll test anything you throw my way!

**Comment by Desmis** [comment]
@jade-nl 

Last commit to test (only clean code)
f188e3cd2

Thank you to have found this bug :)

jacques

**Comment by ghost** [comment]
@Desmis 

Just rebuild and did some more testing, also including other modules, with this latest f188e3c build: 

* All seems OK,
* No more _cp4=_ messages in the terminal.

> Thank you to have found this bug :)

No, thank you for fixing them! :)

**Comment by Desmis** [comment]
OK I will push the PR soon :)

jacques

**Comment by Desmis** [comment]
merge in dev
