### ISSUE TITLE
LA: Soft Light & Original Retinex: bad behavior.

### ISSUE THREAD

**Issue by arturoisilvia** [Beep6581/RawTherapee#6266]
Hi,
Add a new spot
Add tool: "Color & Light".
Move the Lightness slider to maximum so that there is some change.

Add tool: "Soft Light & Original Retinex"
Turn off the "Soft Light & Original Retinex" module <--- IMPORTANT!!!!
Set "Advanced"
Choose Original Retinex
Change in combobox "Show Fourier (f) process" to another item different from the first one.
All other modules are overridden (Color & Light is turned off)

With Soft Light & Original Retinex module OFF, It should not change the behavior of the other modules.

-------------------------------------------------------

Version: RawTherapee_dev_5.8-2948-g6189a0e81_W64_generic_210524.7z 
by gaaned92 en windows 10.

**Comment by Desmis** [comment]
@arturoisilvia 

Yes there is a bad behavior...
Difficult to solve in all cases...because it uses the same algo as Masks...
I will push a change tomorrow...that will solve the main problem

Jacques

**Comment by AndyAstbury** [comment]
In all my RT videos in the future I will always advise users to add just 1 tool to a spot, irrespective of tool mix and any bad behaviors, because it makes editing easier.
If you have 1 spot with 3 tools attached it is a lot harder to decide on what tool property you may want to change later, and a lot easier to identify the changes needed if you use 3 spots with 1 tool each.

**Comment by Desmis** [comment]
The modifications I just made try to avoid bad behaviors, for all masks (including Original retinex) 

Commit ef49d9eef

jacques

**Comment by arturoisilvia** [comment]
@AndyAstbury 
I do not advise you to do so. It can be a bad habit. Just because it happened in one module does not mean that you have lost confidence in a spot with several modules.

Besides it is much more comfortable and practical than if each module has its mask. In fact if you look here:

http://rawpedia.rawtherapee.com/Local_Adjustments#An_example_using_Andy_Astbury.27s_harvest_mouse_image

It talks about: "Dynamic range & Exposure", "Shadows/Highlights & Tone Equalizer", "Blur/Grain & Denoise"...
Are you really going to make a spot for each module?

**Comment by arturoisilvia** [comment]
@Desmis 
Thank you Jacques. I will try it as soon as I get it.

Arturo.
