### ISSUE TITLE
Survey about Open Source Image editors for Master's thesis

### ISSUE THREAD

**Issue by nedunga0** [Beep6581/RawTherapee#6269]
Hello,

My name is Anupama Nedungadi and I am a Master’s student at the University of Geneva. For my thesis, I am looking at internationalization and localization practices in open source image editors, meaning how and why (or why not) the software has been translated into another language. 
I have curated a list of image editors, graphic editors and the likes hosted on SourceForge, GitHub and GitLab, and this list includes the software RawTherapee.

I am contacting you to ask for your participation in a survey. This is a key element of my Master’s thesis. I am aware of the fact that we don't know each other and that you don't owe me anything, but I am really dependent on your help since my topic is quite niche. I also believe we should shine a spotlight on open source software and its translation in particular, as little research has been done in this area recently.

The survey will be open until the 16th of June 2021, and it should only take you around 10 minutes as most questions are multiple choice. Your answers will be anonymous.

https://formulaire.unige.ch/outils/limesurveyfac/traduction-interpretation/index.php/697247?lang=en

Again, thank you for taking the time to read this email and helping a slightly stressed student out!

Best regards,
Anupama Nedungadi

**Comment by Beep6581** [comment]
I filled it out, hope it helps.
