### ISSUE TITLE
Local Adjustments Exposure compensation acts differently on clipped highlights

### ISSUE THREAD

**Issue by Lawrence37** [Beep6581/RawTherapee#6274]
**Short description**
Local Adjustments > Dynamic Range & Exposure > Exposure compensation changes the lightness of clipped highlights at a different rate compared to the rest of the photo.

**Steps to reproduce**
1. Open an image with some clipped highlights. Start with the Neutral profile.
2. Enable Local Adjustments and add a full image spot with the Dynamic Range & Exposure tool.
3. Set Scope to 100 to make the tool affect the whole image.
4. In Exposure Tools, set everything to 0 so that nothing is enabled.
5. Drag the Exposure compensation down and observe how the image changes.

**Expected behavior**
Clipped highlights darken at more or less the same rate as the rest of the image.

**Screenshots**
Without adjustment: 
![image](https://user-images.githubusercontent.com/45837045/120906758-0248c800-c611-11eb-97b3-1856a1c248c7.png)

Clipped highlights don't darken as quickly as the rest of the image:
![image](https://user-images.githubusercontent.com/45837045/120906766-1f7d9680-c611-11eb-9be4-36c0f5cd2362.png)

At this point, the clipped highlights "catch up":
![image](https://user-images.githubusercontent.com/45837045/120906776-39b77480-c611-11eb-8090-a12016a4747a.png)

Now it darkens quicker than the rest of the image:
![image](https://user-images.githubusercontent.com/45837045/120906794-52c02580-c611-11eb-895b-550e6cbf714a.png)

**Comment by Desmis** [comment]
@Lawrence37 

Yes, I know...and I think there is no solution...with "exposure"...

By the way, as I mention in the Rawpedia documentation, I ranked this algorithm last...and there is a reason....
https://rawpedia.rawtherapee.com/Local_Adjustments#Five_ways_to_change_the_exposure_and_lift_the_shadows
In this case - as in a majority of cases - algorithm "Tone equalizer' is much better

jacques

**Comment by Lawrence37** [comment]
Good to know.
Is it an inherent limitation of the algorithm? What is the cause/explaination of the behavior?

**Comment by Desmis** [comment]
It's inherent at this algorithm...
The main explanation is in "LA" exposure works only on L (Lab), in main it works in rgb.

On the other hand, I had thought of removing this algorithm from "LA", because if we compare it to the others (Tone equalizer, TRC, Log encoding...), it is always lower
To a lesser degree, Shadows/Highlights  is also in a majority of cases inferior to others.
If you read the Darktable forum you will see that they came to similar conclusions.

gradually with LA users will have to change their behavior, by unlearning and learning new practices

Jacques

**Comment by Lawrence37** [comment]
I would not have guessed that Lab would work so poorly in this case. With the steps I mentioned, all values are clipped prior to local adjustments, so Lab should be able to handle it without issues. Am I missing something?

**Comment by Desmis** [comment]
Yes but in this case, look at the Lab values in the cloud...L=100 a=0 b=0, the algorithm is unable to deal with this

But I recall for me, the worst algorithm to handle exposure in LA is "exposure".

jacques

**Comment by Lawrence37** [comment]
I agree the other tools are more useful than Exposure compensation. Nevertheless, I attempted to find the cause.
https://github.com/Beep6581/RawTherapee/blob/d86888e93f3c3999261cc5b32143449fc325a606/rtengine/iplocallab.cc#L3090-L3104
`hlfactor` is wrong for clipped values. It turns out this is because `exp_scale` is wrong too. Why is `pow_F` returning bad values? Keep in mind the second argument: `lp.expcomp + addcomp`
`pow_F` is defined in two places:
https://github.com/Beep6581/RawTherapee/blob/d86888e93f3c3999261cc5b32143449fc325a606/rtengine/opthelper.h#L23
https://github.com/Beep6581/RawTherapee/blob/d86888e93f3c3999261cc5b32143449fc325a606/rtengine/sleef.h#L29
The one in sleef.h is redundant. After removing that one and surrounding `b` in parentheses, I get better results. There is still a problem when Exposure compensation is `> -0.6`. I noticed `lp.expcomp` doesn't match the values in the UI and found this:
https://github.com/Beep6581/RawTherapee/blob/d86888e93f3c3999261cc5b32143449fc325a606/rtengine/iplocallab.cc#L1650-L1656
Removing this solves the final issue, but I have no idea what the purpose of this code is and if it is a bad idea to remove it.

**Comment by Desmis** [comment]
@Lawrence37 

Could you send me the code for "surrounding" (After removing that one and surrounding b in parentheses)

The last part for expcomp < 0.6 was a precedent issue....because some users found that the system varied too quickly for low values. I think now we can disabled at least for negative values...

Thank you

Jacques

**Comment by Lawrence37** [comment]
I changed `(xexpf(b*xlogf(a)))` to `(xexpf((b)*xlogf(a)))`.

**Comment by Desmis** [comment]
OK for this case, but this change will affect all pow_F calls in RT...?

But, excuse my bad english...and my bad knowledge in C++.I now know what an added parenthesis () does

:)

**Comment by Lawrence37** [comment]
I briefly checked all the usages and none of them should be affected by the extra parentheses. The extra parentheses is the correct version, so if the change breaks something, it's because it wasn't using pow_F correctly in the first place. If you don't want to change pow_F, you can just change `const float exp_scale = pow_F(2.f, lp.expcomp + addcomp);` to `const float exp_scale = pow_F(2.f, (lp.expcomp + addcomp));`.

The parentheses are necessary because `#define` macros are just text substitutions. So here,  `const float exp_scale = pow_F(2.f, lp.expcomp + addcomp);` will become ` const float exp_scale = (xexpf(lp.expcomp + addcomp*xlogf(2.f)));`. Multiplication comes before addition, so the result is wrong.

**Comment by Thanatomanic** [comment]
Please wait before committing this change directly to `dev`, this feels like a major change that needs some testing.

**Comment by Thanatomanic** [comment]
~~@Lawrence37 Please see https://godbolt.org/z/jYfrc65nn
I implemented both variants of `pow_F` and they result in exactly the same values. I'm not sure why you see differences... Changing compiler or optimization level in Godbolt also doesn't matter.~~

Edit: nevermind, my example was flawed. When you enter an arithmetic expression into the `pow_F` it indeed expands wrongly.

**Comment by Lawrence37** [comment]
There is no difference in that example because you used simple arguments. When dealing with macros, the tricky parts come from order of operations and using code with side-effects.
Edit:  I see your edit now. :)

**Comment by Thanatomanic** [comment]
@Desmis @Lawrence37 I went through all cases of `pow_F` and was only able to find the single case Lawrence found for this bug report where there is an unguarded arithmetic expression in the second argument. All other instances of `pow_F` are good and bug-free.

@Lawrence37 Feel free to update `pow_F` function, that should fix this bug and not affect anything else as far as I can see. FWIW you can remove the definition in `sleef.h`, like I also did here https://github.com/Beep6581/RawTherapee/pull/6262

**Comment by Desmis** [comment]
I just create a new branch "laexposure" with 3 changes
1) remove pow_F from sleep.h
2) added a new pow_Fr in opthelper.h
#define pow_F(a,b) (xexpf(b*xlogf(a)))
#define pow_Fr(a,b) (xexpf((b)*xlogf(a)))
3) in iplocallab.cc I change in "exlabLocal" pow_F by pow_Fr and I remove the lines to increase sensitivity for low values

Now the behavior is better...Thanks to @Lawrence37 

Jacques

**Comment by Desmis** [comment]
I just create a PR
* I remove pow_Fr
* change pow_F
* change iplocallab.cc 
* clean code
