### ISSUE TITLE
libiptcdata no longer needs manual compilation on Windows MSYS2 builds

### ISSUE THREAD

**Issue by Thanatomanic** [Beep6581/RawTherapee#6280]
I accidentally stumbled on https://github.com/msys2/MINGW-packages/pull/7406. Thanks to @Biswa96 for their work the `libiptcdata` library is now provided with MSYS2!

Would have been nicer if either them or @Beep6581 would have mentioned it here as well...
But anyway, I'll update the docs in a moment.

**Comment by Thanatomanic** [comment]
The updated docs will have to wait, I can't seem to login to RawPedia. "There seems to be a problem with your login session; this action has been canceled as a precaution against session hijacking. Please resubmit the form. "

**Comment by Biswa96** [comment]
1. I would suggest to test that package with this project in all possible way.
2. Instead of removing the libiptcdata compilation steps from the docs, I would suggest to make it optional. After all I followed those steps to make libiptcdata package.

**Comment by Thanatomanic** [comment]
@Biswa96 Thanks for the suggestion. I have successfully compiled RawTherapee using the MSYS provided package. If it was dysfunctional, I would have expected compilation or linking errors, so all is good :+1:

I have updated the documentation.
