### ISSUE TITLE
RT-dev: Canon CR3 files rendered white in edit window

### ISSUE THREAD

**Issue by KarlMagnusLarsson** [Beep6581/RawTherapee#6289]
**Short description**
Canon CR3 files rendered white in edit window when opened.

**Steps to reproduce**
1: git clone https://github.com/Beep6581/RawTherapee.git
2: build RT from source
3: run RT and open attached CR3 file in edit window: [example-file](https://drive.google.com/file/d/1ReDKOUqXcjWK5Ev9qxlIwMfkh5VSQKdX/view?usp=sharing) (Canon R5)
4: RT Edit window renders a white frame. 

**Expected behavior**
It should be a rendering of the photo.

**Additional information**
- Version of RawTherapee: 5.8-3000-g7e36240f3
- Version of your operating system: Debian testing Bullseye Linux debian 5.10.0-7-amd64 #1 SMP Debian 5.10.40-1 (2021-05-28) x86_64 GNU/Linux
- If you built from source, the contents of the `AboutThisBuild.txt` file in the installation folder
Version: 5.8-3000-g7e36240f3
Branch: dev
Commit: 7e36240f3
Commit date: 2021-06-21
Compiler: cc 10.2.1
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.24.2
Lensfun: V0.3.2.0
Build type: release
Build flags:  -std=c++11 -march=native -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wno-attributes -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON
Build OS: Linux 5.10.0-7-amd64 x86_64
Build date: Mon, 21 Jun 2021 18:06:13 +0000 UTC
Build epoch: 1624298773
Build UUID: 

Other useful information:
The error is probably introduced at commit 7e36240f3. 
If I checkout the commit before; commit 31e178a4d  and rebuild, then everything is fine (5.8-2999-g31e178a4d).

**Comment by gaaned92** [comment]
@Thanatomanic 
Confirmed. Could it be a syntax error?

**Comment by Thanatomanic** [comment]
Thanks for reporting @KarlMagnusLarsson. @gaaned92 has the right idea, it was a single comma...
