### ISSUE TITLE
Uncertain: SSE2 and regular codepaths doubling in LMMSE

### ISSUE THREAD

**Issue by Thanatomanic** [Beep6581/RawTherapee#6292]
@heckflosse or @Floessie 

Because folks at darktable have ported our LMMSE code, I took a look at our implementation and noticed that there seem to be a few `#ifdef __SSE2__` statements without an `#else` clause. After the `#endif` the non-SSE code simply follows without guard. For example here:

https://github.com/Beep6581/RawTherapee/blob/4ab54c9fda8ec9e18603ec768e2b039d1f2c9217/rtengine/lmmse_demosaic.cc#L265-L390

Wouldn't that mean the SSE code is always overridden and things are being done twice?

**Comment by heckflosse** [comment]
> Wouldn't that mean the SSE code is always overridden and things are being done twice?

No, have a look at the declaration place (scope) of `cc` ;-)

**Comment by heckflosse** [comment]
@Thanatomanic 

the pattern is:

```
int cc = 0;
#ifdef __SSE2__
for (; cc < witdh - 3; cc += 4)
  // do something vectorized
  ;
#endif
for (; cc < witdh; ++cc)
  // do something scalar
  ;

**Comment by Thanatomanic** [comment]
I see, nothing wrong at least. Perhaps the compiler even optimizes it away. Though stylistically I don't like that I must interpret what the first loop does (if it runs) in order to know that the second one is skipped.

**Comment by Floessie** [comment]
@Thanatomanic There's nothing to optimize away or to be skipped: not every width is divisible by four.
