### ISSUE TITLE
Ampersand in lens type leads to blank "quick info" box in editor

### ISSUE THREAD

**Issue by wilchak** [Beep6581/RawTherapee#6294]
RawTherapee always displays an empty info box when editing RAWs generated by the Pansonic GF6. I have only noticed this behavior with this one camera. You can see in the attached screenshot that the info box shows up, just with no text. However, in the file browser, you can see that RT is correctly reading the EXIF information, and I can confirm that Dynamic-based profile selection does match correctly on the EXIF info for these files. I can further confirm that other applications can read these RAWs' EXIF just fine. So this is just a small cosmetic bug regarding the quick info box in the editor.

![screencap of issue](https://user-images.githubusercontent.com/2185789/123561841-ce2c7700-d778-11eb-932f-44a3fde2d1a9.png)
![screencap of exif in browser](https://user-images.githubusercontent.com/2185789/123561842-d08ed100-d778-11eb-910d-488ae1e7a289.png)
Filebin link to a GF6 RAW: https://filebin.net/10h39eqb8q3hruza

Version: 5.8-2999-g31e178a4d
Branch: dev
Commit: 31e178a4d
Commit date: 2021-06-19
Compiler: cc 11.1.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.24.3
Lensfun: V0.3.95.0
Build type: relwithdebinfo
Build flags:  -std=c++11 -march=native -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wno-attributes -flto -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -fopenmp -Werror=unknown-pragmas -O2 -g -DNDEBUG -ftree-vectorize
Link flags:  -march=native -flto
OpenMP support: ON
MMAP support: ON
Build OS: Linux 5.12.11-xanmod1-1 x86_64
Build date: Sat, 19 Jun 2021 20:04:27 +0000 UTC
Build epoch: 1624133067
Build UUID: dac20c8e-dcfd-4792-82cd-f06d2a83a7a8

**Comment by Thanatomanic** [comment]
When opening this file, the command line tells me:
```
(rawtherapee.exe:3528): Pango-WARNING **: 13:24:18.631: pango_layout_set_markup_with_accel: Error on line 1: Entity did not end with a semicolon; most likely you used an ampersand character without intending to start an entity — escape ampersand as &amp;

(rawtherapee.exe:3528): Pango-WARNING **: 13:24:18.638: pango_layout_set_markup_with_accel: Error on line 1: Entity did not end with a semicolon; most likely you used an ampersand character without intending to start an entity — escape ampersand as &amp;
```

This is because the lens used has the following name: `LAOWA C&D-Dreamer MFT 10mm F2.0`. The ampersand should be escaped when loading.

**Comment by Floessie** [comment]
@Thanatomanic Something like this?

```diff
diff --git a/rtgui/editorpanel.cc b/rtgui/editorpanel.cc
index a365a8599..d12489a13 100644
--- a/rtgui/editorpanel.cc
+++ b/rtgui/editorpanel.cc
@@ -1335,8 +1335,8 @@ void EditorPanel::info_toggled ()
 
     if (idata && idata->hasExif(selectedFrame)) {
         infoString = Glib::ustring::compose ("%1 + %2\n<span size=\"small\">f/</span><span size=\"large\">%3</span>  <span size=\"large\">%4</span><span size=\"small\">s</span>  <span size=\"small\">%5</span><span size=\"large\">%6</span>  <span size=\"large\">%7</span><span size=\"small\">mm</span>",
-                                              Glib::ustring (idata->getMake() + " " + idata->getModel()),
-                                              Glib::ustring (idata->getLens()),
+                                              escapeHtmlChars (idata->getMake() + " " + idata->getModel()),
+                                              escapeHtmlChars (idata->getLens()),
                                               Glib::ustring (idata->apertureToString (idata->getFNumber(selectedFrame))),
                                               Glib::ustring (idata->shutterToString (idata->getShutterSpeed(selectedFrame))),
                                               M ("QINFO_ISO"), idata->getISOSpeed(selectedFrame),
```

If that's sufficient, I'll push directly to `dev`.

HTH,
Flössie

**Comment by Thanatomanic** [comment]
@Floessie This does the trick! Thanks :+1:
