### ISSUE TITLE
With output profile as ADOBE RGB 1998 I get colors that are not correct even while the working profile is set to ADOBE RGB.

### ISSUE THREAD

**Issue by PeriscopeInGit** [Beep6581/RawTherapee#6295]
I am having difficulty match colors for ADOBE RGB 1998 set as output profile. I copied icc file from Adobe website to RawTherapee /usr/share/RawTherapee icc profile output folder. Is this supported? The color does not match even with the editor view in RawTherapee and the green below the tree looks very unnatural.

I can summarize below what does not cause any effects
- output image bit precision (8 bit 16 bit integer/float etc)
- output image format ( tiff/jpg/png)
- image browser ( - mixed results GIMP with no color management used, RTv4_sRGB color matches perfectly but not ADOBE RGB 1998 even if I use the working profile as the default ADOBE RGB ( which I hope hasn't changed since 1998 , ImageViewer sends colors off even for sRGB.)

More info:
- OS is Ubuntu 20.04, RawTherapee version is 5.8, In editor I disabled (color management by chose profile to "None" and no soft-proofing)
- OS icc profile for Monitor is also set to ADOBE RGB icc ( though that should not matter as the difference between workspace color in Rawtherapee and jpg in Adobe RGB is evident)

The link below has raw file, and pp3 and Jpg for both RTv4_sRGB and AdobeRGB. 
https://github.com/PeriscopeInGit/ForBeep 

RAW 34 MB :( in Google drive link below:
https://drive.google.com/drive/folders/1o0KUksD9kVuR5OpuuoxtKAOKZq2p3kg_?usp=sharing

I LOVE using RawTherappe and the great work that has gone into it. I am however thinking if this (ADOBE RGB output profile)is not supported? Or is it just silly me doing something wrong? 

In any case I hope you can help.

**Comment by Thanatomanic** [comment]
I'm on mobile, so not able to verify thoroughly, but

> More info:

> OS is Ubuntu 20.04, RawTherapee version is 5.8, In editor I disabled (color management by chose profile to "None" and no soft-proofing)
> OS icc profile for Monitor is also set to ADOBE RGB icc ( though that should not matter as the difference between workspace color in Rawtherapee and jpg in Adobe RGB is evident)

This is both not correct procedure. Don't set input profile to none if you want accurate color representation. And don't set AdobeRGB as monitor profile (it's not a monitor profile).

**Comment by PeriscopeInGit** [comment]
Thanks for the quick turn around!

I have set input profile to the recommended one. It is that option at the bottom of editor where you can chose whether RT uses what profile(e.g. use system profile) which is None. 

Agree on monitor profile comment. That was a desperation. 

Will wait for your comments once you are able to check files. 

Thanks,

**Comment by Thanatomanic** [comment]
@PeriscopeInGit I can see no differences when I view your supplied JPEGs in RawTherapee or in GIMP (keep profile on import). Processing your raw with the provided pp3 files also gives identical output, whether I set the output profile to my system's Adobe RGB profile or RTv4_sRGB.

> image browser ( - mixed results GIMP with no color management used, RTv4_sRGB color matches perfectly but not ADOBE RGB 1998 

You say "matches perfectly" - but against what? What are you comparing that makes you think something is wrong?

**Comment by PeriscopeInGit** [comment]
Thanks. I have attached screenshots of the difference in AdobeRGB jpg and AdobeRGB Rawtherapee Editor View. I am unable to find the 'matches perfectly' (processed image Vs what I see on RawTherapee Editor View) image as I tried so many image and profile combinations (RT V2 V4 _sRGB and plain sRGB). I will get back on the exact match as well but I think its fair to say the following. 

I think my issue is better described as not matching colors in RawTherapee Editor View and External Editor even if external editor uses no color management. 

Added screenshots in the link below:
https://github.com/PeriscopeInGit/ForBeep

**Comment by PeriscopeInGit** [comment]
I may have identified the cause. I don't remember having received an option of whether to keep /convert profile when I opened first time in GIMP. I will redo this test and confirm back tomorrow. Thanks!

**Comment by PeriscopeInGit** [comment]
All right, needed to keep GIMP color management on to be able to get the match( GIMP and RT editor) colors for ADOBE RGB. A Not sure why they  worked fine with Color Management off for sRGB. I did not try other color profiles. But in any case this is not a RT issue. 

Also it does not prompt to convert profile for ADOBE RGB as I guess this is built in profile available with GIMP.

Putting comparison screenshots in the link(https://github.com/PeriscopeInGit/ForBeep). Guess this thread can be closed. 
Thank you!

**Comment by Lawrence37** [comment]
> Not sure why they worked fine with Color Management off for sRGB.
Probably because many programs interpret colors as sRGB in the absence of proper color management.

**Comment by PeriscopeInGit** [comment]
True. Checked on gimp docs. When color management is turned off it uses sRGB.
