### ISSUE TITLE
RAW support for Panasonic GH5M2

### ISSUE THREAD

**Issue by peti** [Beep6581/RawTherapee#6297]
I have uploaded RAW reference images taken with the Panasonic GH5 Mark II to <https://raw.pixls.us/>. I hope those are helpful in the process of adding support for that (brand-new) camera.

**Comment by vladipus** [comment]
Upvoting this.
Thank you for your work.

**Comment by asbachb** [comment]
I guess this is still an issue in 5.8? I just got pink squares when opening raw files from a GH5 Mark II.

**Comment by asbachb** [comment]
I don't know of it's helpful, but it seems that `libraw` added support for that model: https://github.com/LibRaw/LibRaw/commit/2a9a4de21ea7f5d15314da8ee5f27feebf239655

**Comment by erentar** [comment]
It is still an issue, i get the pink squares too.

**Comment by sgotti** [comment]
Created PR #7073 to add support for Panasonic DC-GH5M2
