### ISSUE TITLE
Local adjustments - renamed spot isnt shown in History

### ISSUE THREAD

**Issue by marter001** [Beep6581/RawTherapee#6298]
[Version]
AppVersion=5.8-2983-g3f58095b6
Version=349

when renaming a spot for local adjustments, this will be shown in the history as expected. If there is any further change on this spot, the history again will not show the new name, but (new spot) as before.

Edit: after reopen the pic in editor, the new name is shown correctly in history.

**Comment by Lawrence37** [comment]
This patch fixes it. I will commit it to dev if there are no problems.
```diff
diff --git a/rtgui/controlspotpanel.cc b/rtgui/controlspotpanel.cc
index bdf723992..4bab0da9c 100644
--- a/rtgui/controlspotpanel.cc
+++ b/rtgui/controlspotpanel.cc
@@ -703,6 +703,9 @@ void ControlSpotPanel::on_button_rename()
             row[spots_.name] = newname;
             treeview_->columns_autosize();
             listener->panelChanged(EvLocallabSpotName, newname);
+            if (controlPanelListener) {
+                controlPanelListener->spotNameChanged(newname);
+            }
         }
     }
 }
diff --git a/rtgui/controlspotpanel.h b/rtgui/controlspotpanel.h
index b748df544..3854692fd 100644
--- a/rtgui/controlspotpanel.h
+++ b/rtgui/controlspotpanel.h
@@ -34,6 +34,7 @@ public:
     virtual ~ControlPanelListener() {};
 
     virtual void resetToolMaskView() = 0;
+    virtual void spotNameChanged(const Glib::ustring &newName) = 0;
 };
 
 
diff --git a/rtgui/locallab.cc b/rtgui/locallab.cc
index 6f59d3b0f..2473e6807 100644
--- a/rtgui/locallab.cc
+++ b/rtgui/locallab.cc
@@ -1180,6 +1180,13 @@ void Locallab::updateShowtooltipVisibility(bool showtooltip)
     }
 }
 
+void Locallab::spotNameChanged(const Glib::ustring &newName)
+{
+    for (auto && tool : locallabTools) {
+        tool->setSpotName(newName);
+    }
+}
+
 void Locallab::addTool(Gtk::Box* where, LocallabTool* tool)
 {
     tool->getExpander()->setLevel(3);
diff --git a/rtgui/locallab.h b/rtgui/locallab.h
index 1c3c06167..8b7050c26 100644
--- a/rtgui/locallab.h
+++ b/rtgui/locallab.h
@@ -200,6 +200,7 @@ private:
 
     // ControlSpotListener function
     void resetToolMaskView() override;
+    void spotNameChanged(const Glib::ustring &newName) override;
 
     // LocallabToolListener function
     void resetOtherMaskView(LocallabTool* current) override;
```

**Comment by Desmis** [comment]
@Lawrence37 

I just tested your patch...It's OK, now works fine :)

jacques

**Comment by Floessie** [comment]
@Lawrence37 

```patch
+void Locallab::spotNameChanged(const Glib::ustring &newName)
+{
+    for (auto && tool : locallabTools) {
+        tool->setSpotName(newName);
+    }
+}
```

Is the `&&` a typo, or what's the benefit here?

Best,
Flössie

**Comment by Floessie** [comment]
@Lawrence37 [Enlightening answer by Howard Hinnant.](https://stackoverflow.com/a/13130795) So I seem to be the one who didn't catch up with the `auto&&` idiom, still prefering `auto` for values, `const auto&` for const access, and `auto&` for non-const references in range based for loops. :wink: Thus I'll change the latter (`auto&`) to `auto&&` in my coding, but will still use `auto` and `const auto&` for more precision and better review. Thanks for making me aware! :+1:

**Comment by heckflosse** [comment]
Hmm, why do all tools of a spot have the same name? Wouldn't it be better to store it only once?

**Comment by Lawrence37** [comment]
The tools initially get the name from reading the `ProcParams` individually, which is why each tool has a copy of the spot name. It might be feasible to store the name in `Locallab` because it is the one supplying the `ProcParams` and guarantees all the tools operate on the same spot. I will try this approach.
