### ISSUE TITLE
[Rawpedia] Typo in chapter "The Queue"

### ISSUE THREAD

**Issue by ascherer** [Beep6581/RawTherapee#6300]
**Additional information**
On page [The Queue](http://rawpedia.rawtherapee.com/Queue) in section "Adding Images to the Queue" the second item should read **Put to the head/tail of the processing queue** instead of **…the the…**.

The _same_ typo occurs in the next section "Queue Settings", too.

**Comment by Thanatomanic** [comment]
Thanks @ascherer for reporting. It is fixed now.
