### ISSUE TITLE
[Rawpedia] Markup visible in chapter "The Editor"

### ISSUE THREAD

**Issue by ascherer** [Beep6581/RawTherapee#6301]
**Additional information**
On the page [The Editor](http://rawpedia.rawtherapee.com/Editor) in section "Eek! My Raw Photo Looks Different than the Camera JPEG" there's a visible pair of `[b]` and `[/b]` instead of the expected **bold** effect on the text **RawTherapee does not "add noise"!**

**Comment by Thanatomanic** [comment]
Fixed
