### ISSUE TITLE
Canon EOS-1Ds Mark II support

### ISSUE THREAD

**Issue by mburns9** [Beep6581/RawTherapee#6307]
The Canon EOS-1Ds Mark II is one of the best cameras for realistic color, and it deserves more than a matrix color profile in RawTherapee.

(I did my own icc profile using linearly interpolated data from the linked GretagMacbeth CC24 capture, by feeding the interpolated data to the argyll colprof tool. Compared to the dcamprof icc profile that I also made, the colprof icc file yields more accuracy in the less saturated colors, but it yields more saturation in the saturated colors, just where dcamprof yields less saturation.)

https://drive.google.com/file/d/1UzF2_eqvqnREn1tVoL5YUsPLNaEP93Qo/view?usp=sharing

This capture file (CR2 format) is of a GretagMacbeth ColorChecker 24 taken on a late spring afternoon. There was a cloudless blue sky in Grand Rapids MI only two and a half hours after local noon. The exposure was EV14.2, f/22 and speed 1/40 on the Canon EOS-1Ds Mark II camera, also documented as compensation +2/3. The lens was a Canon EF 85mm f/1.8.

**Comment by Thanatomanic** [comment]
@mburns9 Your Google Drive link requires me to ask for access. Could you please provide an alternative (public) download link?

**Comment by mburns9** [comment]
https://drive.google.com/file/d/1UzF2_eqvqnREn1tVoL5YUsPLNaEP93Qo/view?usp=sharing

It is my mistake. The sharing option is now set.

**Comment by mburns9** [comment]
https://drive.google.com/file/d/1LZlfSyC-XZrDoStnEv78aImrHO7LpNte/view?usp=sharing
Here is a cc24 raw taken with a clear bulb tungsten light and metered and exposed at EV3.

**Comment by mburns9** [comment]
The older cc24 raw is no doubt overexposed. I will have to try again.

**Comment by mburns9** [comment]
https://drive.google.com/file/d/1LZlfSyC-XZrDoStnEv78aImrHO7LpNte/view?usp=sharing
This is better now: a cc24 raw taken with a clear bulb tungsten light, metered at EV2 and exposed at EV1.

**Comment by mburns9** [comment]
https://drive.google.com/file/d/1uUDdA8-FXpJoemCvXxm9o51N37sIZZ1P/view?usp=sharing

The link for the daylight cc24 raw is now changed to this.

**Comment by mburns9** [comment]
All of the RawTherapee requirements for support of this camera are fulfilled in the last two links. There is no clipping in the raw files.

If I had any credit here, I could do the dual-illuminant profile myself and post it.

(I have also posted the necessary files for support of the Canon EOS 5D Mark II.)

**Comment by Thanatomanic** [comment]
[Canon EOS-1Ds Mark II.zip](https://github.com/Beep6581/RawTherapee/files/8111882/Canon.EOS-1Ds.Mark.II.zip)

Hi @mburns9 sorry for taking so long... Could you maybe test out the DCP in the attachment? I assume you know how to apply it manually in RT?

**Comment by mburns9** [comment]
https://drive.google.com/file/d/1Kc2sU6g24j1b_ahb5Fsxj8o97h96L3Xa/view?usp=sharing

Your profile seems all in order. Pink flowers are more pink. Browns are deeper. Over exposures are handled. And it must be the dual illuminant that makes a big difference in this copper ceilling. I suppose that this ceiling should not be rendered yellowish, as it is rendered by the standard matrix.

**Comment by mburns9** [comment]
https://drive.google.com/file/d/1dD7wnrt4A3kQgUOta7wbbJdDZzmILHJZ/view?usp=sharing
Here is the raw file for the copper ceiling.
