### ISSUE TITLE
Outdated Documentation for Saving/Opening Partial Profiles

### ISSUE THREAD

**Issue by Lawrence37** [Beep6581/RawTherapee#6309]
In http://rawpedia.rawtherapee.com/Sidecar_Files_-_Processing_Profiles#Partial_Processing_Profiles_and_Fill_Modes, it reads

> Note that when loading or saving a profile, the parameter window appears after the file selection dialog.

This is only true for *loading* a profile. The order when *saving* a partial profile changed with #5501.

**Comment by Beep6581** [comment]
Fixed.
