### ISSUE TITLE
Local Adustments: 'Film Grain' tool generating innacurate 1:1 preview

### ISSUE THREAD

**Issue by marcapelini** [Beep6581/RawTherapee#6311]
The "Film Grain" tool in the "Local Adjustments" tab does not show a correct rendering of the output image at 1:1 magnification.  The noise in the preview looks much smoother and finely-grained than the one in the actual output file, making the preview image useless for evaluating the effect of the adjustments available in the tool ('Distribution (ISO)', 'Gamma', 'Strength').

Example of the image preview 1:1 in RT side-by-side with to the TIFF output opened in GIMP:

![rt_vs_gimp_film_grain](https://user-images.githubusercontent.com/1328887/126710375-504f9fae-6262-41f9-895c-0caf35b39fa1.png)

Above issue found in RawTherapee built from source using the 'build-rawtherapee' shell script with no modification of any parameters. Operating system is Kubuntu 20.04. Problem noticed on my first try of the LA/'Film Grain' tool several weeks ago, but confirmed with the current contents of 'dev' branch:

![rt_git_repo](https://user-images.githubusercontent.com/1328887/126711460-671def71-4ecb-49ae-aabf-7b945ea6a1c5.png)

For the above example: 
 * Applied the ‘neutral’ profile upon opening the image 
 * Enabled the ‘Black-and-White’ module without changing anything (not necessary to reproduce the problem, but it's part of my workflow and it's easier to see the difference in the monochrome image), 
 * Added a new spot in LA with method ‘Full image’. 
 * Adjusted the ‘Film grain’ parameters as shown, looking at the image at 100% to try to see the effect of each parameter as I changed its value.

The problem doesn't not seem particular to any camera or maker, as I confirmed it with raw files from different cameras (Panasonic GM1, Panasonic GX1, Panasonic LX7, Canon 350D, Canon G9, Canon G3), so I judge it not necessary to upload an example raw file. The steps are easy to follow, so no particular pp3 file needed either.

To further investigate the issue I installed the most recent Win64 build from https://keybase.pub/gaaned92/RTW64NightlyBuilds/ (RawTherapee_dev_5.8-3009-gd7f9e1f51_W64_generic_210705.7z) on an old Windows 7 machine, and confirmed exactly the same behaviour as in the current Linux build as above:

![rt_vs_tiff_win_film_grain](https://user-images.githubusercontent.com/1328887/126712022-3db0debb-f971-42d7-8565-5c328ebf0430.png)

I took a look at the source code in 'ipgrain.cc' and seeing it has been ported from Darktable, I opened the same image in DT with similar adjustments to the ones applied in RT, and the preview image corresponded as expected with the TIFF image converted with DT:

![dt_vs_gimp_film_grain](https://user-images.githubusercontent.com/1328887/126712445-c5b3dd88-bafa-4009-a21e-8775b6e3e506.png)

I also tried the 'Film Grain' module in ART which I believe has also been ported from DT, and the 1:1 preview in ART  corresponded with the TIFF output from that program:

![art_vs_gimp_film_grain](https://user-images.githubusercontent.com/1328887/126712639-6ae89d58-3451-44ca-bf44-d8405e85f881.png)
 
Please let me know if you need any further information to characterise this problem.

**Comment by Desmis** [comment]
I push a commit to fixe this bad behavior (I hope)
I open a pull-request
https://github.com/Beep6581/RawTherapee/pull/6313

jacques

**Comment by marcapelini** [comment]
> I push a commit to fixe this bad behavior (I hope)
> I open a pull-request
> #6313
> jacques

Perfect Jacques! That was really quick! ;-)

Comparing the result side by side, the preview looks faithful to the generated TIFF.  I checked the histogram in Gimp for a selection on both the preview and the TIFF file, and the statistics (mean/std dev/median) matched perfectly.

![rt_vs_gimp_film_grain_pr_6313](https://user-images.githubusercontent.com/1328887/126881421-9c8b7e4d-693f-4bbc-88d0-67f698281eb7.png)

I think I'll keep using this build with the PR applied until the change is merged into 'dev'.  Many thanks! 

Should I close the issue myself?

**Comment by Lawrence37** [comment]
@marcapelini I linked this issue to the pull request so it will automatically close when the PR is merged.
