### ISSUE TITLE
Needs expat>=2.1 on Fedora 34

### ISSUE THREAD

**Issue by asalois** [Beep6581/RawTherapee#6320]
**Short description**
The problem was in the fedora section of the wiki about dependencies

"expat-devel" was left out.

**Steps to reproduce**
After installing dependencies like below from the wiki

sudo dnf install git make cmake curl gcc gcc-c++ gtk3-devel gtkmm30-devel lensfun-devel librsvg2-devel lcms2-devel fftw-devel libiptcdata-devel libtiff-devel libjpeg-turbo-devel libcanberra-devel libatomic 

I ran 
$ cmake \
-DCMAKE_BUILD_TYPE="release"
-DCACHE_NAME_SUFFIX="5-dev"
-DPROC_TARGET_NUMBER="2"
-DBUILD_BUNDLE="ON"
-DBUNDLE_BASE_INSTALL_DIR="$HOME/programs/rawtherapee"
-DOPTION_OMP="ON"
-DWITH_LTO="OFF"
-DWITH_PROF="OFF"
-DWITH_SAN="OFF"
-DWITH_SYSTEM_KLT="OFF"
..

and got

- CMAKE_BUILD_TYPE: release
-- Checking for module 'expat>=2.1'
-- Package 'expat', required by 'virtual:world', not found
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:556 (message):
A required package was not found
Call Stack (most recent call first):
/usr/share/cmake/Modules/FindPkgConfig.cmake:778 (_pkg_check_modules_internal)
CMakeLists.txt:487 (pkg_check_modules)

-- Configuring incomplete, errors occurred!
See also "/home/alexsalois/programs/code-rawtherapee/build/CMakeFiles/CMakeOutput.log".
See also "/home/alexsalois/programs/code-rawtherapee/build/CMakeFiles/CMakeError.log".

**Expected behavior**
 cmake     -DCMAKE_BUILD_TYPE="release"      -DCACHE_NAME_SUFFIX="5-dev"     -DPROC_TARGET_NUMBER="2"     -DBUILD_BUNDLE="ON"     -DBUNDLE_BASE_INSTALL_DIR="$HOME/programs/rawtherapee"     -DOPTION_OMP="ON"     -DWITH_LTO="OFF"     -DWITH_PROF="OFF"     -DWITH_SAN="OFF"     -DWITH_SYSTEM_KLT="OFF"     ..
-- CMAKE_BUILD_TYPE: release
-- Checking for module 'expat>=2.1'
--   Found expat, version 2.4.1
-- Checking for module 'fftw3f'
--   Found fftw3f, version 3.3.8
-- Checking for module 'libiptcdata'
--   Found libiptcdata, version 1.0.5
-- Found TIFF: /usr/lib64/libtiff.so (found suitable version "4.2.0", minimum required is "4.0.4")  
-- Found JPEG: /usr/lib64/libjpeg.so (found version "62") 
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.11") 
-- Found PNG: /usr/lib64/libpng.so (found version "1.6.37") 
-- Checking for module 'libcanberra-gtk3'
--   Found libcanberra-gtk3, version 0.30
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Performing Test _fftw3f_multithread
-- Performing Test _fftw3f_multithread - Failed
-- Performing Test LENSFUN_HAS_LOAD_DIRECTORY
-- Performing Test LENSFUN_HAS_LOAD_DIRECTORY - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/alexsalois/programs/code-rawtherapee/build

**Additional information**
<!-- Some essentials:
- Version of RawTherapee from dev branch 
             "On branch dev Your branch is up to date with 'origin/dev'."
- Version of your operating system Fedora 34 kernel 5.13.4-200.fc34.x86_64

This was fixed by "sudo dnf install expat-devel"

**Comment by Thanatomanic** [comment]
Thanks, it was missing indeed. I added it http://rawpedia.rawtherapee.com/Linux#Fedora
