### ISSUE TITLE
Transferring the ratings/rankings from xmp sidecar files to pp3 sidecar files 

### ISSUE THREAD

**Issue by Raagcity** [Beep6581/RawTherapee#6322]
Hey Guys! I would love to know if there's a way to get the ratings/ranking from an existing xmp sidecar file into the pp3 sidecar file? I mainly want this because the culling process in RawTherapee is a lot slower than something like Darktable.  I absolutely love the features of RawTherapee but the slow culling is huge bottle-neck when trying to go through 500+ images. Is there a solution to this problem that I don't know about? 

Thank you in advance!

**Comment by Thanatomanic** [comment]
I guess this is very similar/identical to https://github.com/Beep6581/RawTherapee/issues/6084
In the meanwhile I do not know of a workaround. Perhaps you can ask around on our support forum: https://discuss.pixls.us
