### ISSUE TITLE
Add decoration border filter

### ISSUE THREAD

**Issue by Jupi007** [Beep6581/RawTherapee#6325]
Hi,
first at all, big thanks for this professional app I use almost every day.

But there is an annoying thing in my workflow:
usually, when I want to develop an image in B&W, I add a thin white border.
And this require each time to run Gimp, add the border, and then export. When I need to render a lot of photos, it becomes quickly annoying.

Honestly, I don't know if it's a good idea to integrate this to RT, but I think having a decoration border filter with only basic settings (width and color) could be very useful for many people.

Thanks :)

**Comment by Floessie** [comment]
Hi @Jupi007,

> And this require each time to run Gimp, add the border, and then export. When I need to render a lot of photos, it becomes quickly annoying.

An ad hoc solution for bulk modifications like boders is ImageMagick's `convert`. On Linux you can use `xargs` or shell scripting for the "bulk" part.

HTH,
Flössie

**Comment by Jupi007** [comment]
Hi @Floessie,
thanks for the quick response.

> An ad hoc solution for bulk modifications like boders is ImageMagick's `convert`. On Linux you can use `xargs` or shell scripting for the "bulk" part.

I guess it's a polite way to say no ;)
Don't worry I understand, but I still would love seen a new border filter against the very useful vignetting one.

Thanks anyway for the "bulk" solution :)

**Comment by Thanatomanic** [comment]
No reason to close the issue. @Floessie just provided a workaround for the time being. Yours is a valid request.

**Comment by arturoisilvia** [comment]
@Jupi007 
Provisionally, until there is a border module, with local adjustments in advanced mode you can make a black or white border (color is not possible) with the tone curve of the "color & light" module.
Arturo.

**Comment by arturoisilvia** [comment]
I just did a white frame or border demo on: 
[https://discuss.pixls.us/t/play-with-color/26267/5](https://discuss.pixls.us/t/play-with-color/26267/5)
Arturo.

**Comment by Jupi007** [comment]
> No reason to close the issue. @Floessie just provided a workaround for the time being. Yours is a valid request.

I'm really sorry to have closed the issue abruptly @Thanatomanic.
So that mean we could get a border module, that's awesome :)

> @Jupi007
> Provisionally, until there is a border module, with local adjustments in advanced mode you can make a black or white border (color is not possible) with the tone curve of the "color & light" module.
> Arturo.

Thanks a lot @arturoisilvia , but I can't find the `local adjustments` tab, does this require the dev version (I'm using RT 5.8)?

> I just did a white frame or border demo on:
> https://discuss.pixls.us/t/play-with-color/26267/5
> Arturo.

That's exactly that I want to do!

**Comment by arturoisilvia** [comment]
> but I can't find the local adjustments tab, does this require the dev version (I'm using RT 5.8)?

@ Jupi007  :
Yes, local adjustments are in the development builds.

These development builds are here:
http://rawpedia.rawtherapee.com/Download

Of them, if you use windows, the most updated is the unofficial build.

Then you have the local adjustments manual here:
http://rawpedia.rawtherapee.com/Local_Adjustments

And finally I advise you to watch Andy Astbury's videos:
https://www.youtube.com/c/AndyAstbury/search?query=rawtherapee

Specifically, the local adjustments ones:
https://www.youtube.com/c/AndyAstbury/search?query=rawtherapee%20adjustment

You will enjoy a lot!!!
Best regards,
Arturo.

**Comment by Jupi007** [comment]
Okay, will take a look at the dev build and also the videos!
I can't believe that there is ("will" as it's still in dev branch) local adjustments in RT 😊

Big thanks for your help @arturoisilvia  👍
