### ISSUE TITLE
CIE Illuminant reset to D50 when activating modules.

### ISSUE THREAD

**Issue by ghost** [Beep6581/RawTherapee#6326]
**Short description**
In certain cases loading a wavelet levels profile after activating CIE CAM and setting different Illuminant resets this illuminant back to the default D50 (5003K).

**EDIT** -> *See my second comment. This turns out to be not wavelet levels specific but most likely a more global CIE CAM issue*

**Steps to reproduce**
1. Load an image (any RAW or TIFF will do),
2. Set/load *Neutral* profile,
3. Activate _CIE CAM_ ,
4. Set Cat02/16 mode to *Automatic Symmetric*,
5. Select *Incadescent StdA 2856K* as Illuminant (any one will do, except the default D50. This one to make it more obvious),
6. Load the wavelet profile from file,
7. Activate *Wavelet levels*,
8. There's already a clearly visible unwanted change,
9. Look at the CIE CAM Illuminant setting (this is still as set previously),
10. Look at the temperature field, which is now reset to 5003 (D50).

The above needs a wavelet levels only(?) profile. You can create your own or use the one I provided. I tried a few different ones and the end-result is the same. Even an empty one (=defaults only) will do: [base.01.edge.residual.pp3.zip](https://github.com/Beep6581/RawTherapee/files/6930138/base.01.edge.residual.pp3.zip)

**Extra info**

To give you an idea without having to do the above steps:

https://user-images.githubusercontent.com/56407344/128157651-8a35a785-4b6a-4a7a-ac01-40cf2509c990.mp4

The interesting part is that the applied wavelet levels settings that are in the applied profile are part of my base profile. This base profile is always applied when it encounters a RAW file. In this case everything works as expected:

https://user-images.githubusercontent.com/56407344/128161576-d3b198db-6b0e-497f-a6cb-e94bc1d20fd7.mp4

**Expected behavior**

No reset of any non-wavelet settings when loading a wavelet profile.

**Additional information**
- Version of RawTherapee: 5.8-2995-g166538d (appimage) _and_ 5.8-3055-g2b2f1f5bd (latest self build)

**Platform**

* OS                : Linux (kernel 5.9.15-1 x86_64 amd64)
* Distro            : Debian Buster (rel. 10.10)
* Graphics driver   : nvidia (460.39)

**Build info**

* Compiler      : gcc 8.3.0
* Cmake         : 3.13.4
* Glib          : 2.58.3-2
* Gtk+          : 3.24.5-1
* Exiv2         : 1.0.0.9
* Lensfun       : 0.3.2-4

**Build using:**

cmake \
    -DBUNDLE_BASE_INSTALL_DIR="$HOME/.local/${TRGT}" \
    -DBUILD_BUNDLE="ON" \
    -DCACHE_NAME_SUFFIX="5-dev" \
    -DCMAKE_BUILD_TYPE="release"  \
    -DPROC_TARGET_NUMBER="2" \
    -DOPTION_OMP="ON" \
    -DBUILD_SHARED="OFF" \
    -DWITH_LTO="ON" \
    -DWITH_BENCHMARK="OFF" \
    -DWITH_MYFILE_MMAP="ON" \
    -DWITH_PROF="OFF" \
    -DWITH_SAN="OFF" \
    -DWITH_SYSTEM_KLT="OFF" \
    ..

**Build flags:**

    -DNDEBUG
    -O3
    -Wall
    -Wcast-qual
    -Werror=delete-incomplete
    -Werror=unknown-pragmas
    -Werror=unused-label
    -Wno-attributes
    -Wno-deprecated-declarations
    -Wno-unused-result
    -Wuninitialized
    -Wunused-macros
    -flto
    -fno-math-errno
    -fopenmp
    -ftree-vectorize
    -march=native
    -std=c++11

**Comment by ghost** [comment]
It turns out that this is not caused by the _wavelet levels_  module. I can reproduce this in another way as well:

1. Load an image (any RAW or TIFF will do),
2. Set/load *Neutral* profile,
3. Activate _CIE CAM_ ,
4. Set Cat02/16 mode to *Automatic Symmetric*,
5. Select *Incandescent StdA 2856K* as Illuminant (any one will do, except the default D50. This one to make it more obvious),
7. Activate *Local Adjustments*,
8. Add a tool (any tool will do),
9. Select/Go back to the *Illuminant Incandescent StdA 2856K* step in the History,
10. Turn *Local Adjustments* module ON,
11. Look at the CIE CAM Illuminant setting (this is still as set previously),
12. Look at the temperature field, which is now reset to 5003 (D50).

Here's a visual:

https://user-images.githubusercontent.com/56407344/128593478-2947f877-a31a-4aa9-9e8b-664ae6181583.mp4

It does not matter which module you use. Enabling any module (step 7), going back to _Illuminant_  in the history (step 9) and re-enabling the previous module (step10) will trigger this reset behaviour in the CIE CAM module.

**Comment by Lawrence37** [comment]
This fixes the problem. @Desmis Please make sure I'm not doing anything wrong.
```diff
diff --git a/rtgui/colorappearance.cc b/rtgui/colorappearance.cc
index 8b57aadb4..a9634d60b 100644
--- a/rtgui/colorappearance.cc
+++ b/rtgui/colorappearance.cc
@@ -1398,9 +1398,11 @@ void ColorAppearance::convertParamToNormal()
     wbmodel->set_active (0);
     if (presetcat02->get_active ()) {
         wbmodel->set_active (2);
+        illumChanged();
     }
     if (catmethod->get_active_row_number() == 1  || catmethod->get_active_row_number() == 2) {
             wbmodel->set_active (2);
+        illumChanged();
     }
 
     greenout->setValue(def_params.greenout);
```

**Comment by ghost** [comment]
@Lawrence37

Just to let you know: I edited colorappearance.cc, applied your changes and rebuild: This solves the problem.

But I don't come even close to being able to determine if this change has any other side effects.

Anyway: Much appreciated!

**Comment by Desmis** [comment]
@Lawrence37 @jade-nl 

This patch is good :)

You can push to dev.

Thank you very much

Jacques
