### ISSUE TITLE
exporting an editet file shows strange colored lokal adjusted area

### ISSUE THREAD

**Issue by marter001** [Beep6581/RawTherapee#6328]
Hi there,

I am on windows and using dev RT-5.8-3040-g94b5f7232, expanded from 7z.
After editing a PlayRAW on pixls.us , it happened, that exported files show a blue circle on local spots with second tool activated.

I am not able to reproduce this on any file, but two computers of different hardware came up with the same result on this file.

![blue_eye_sharpening_off](https://user-images.githubusercontent.com/78749513/128235252-e7820383-0387-45c1-9f98-d8e8ab12e1ed.jpg)

(pls also see the dicussion concerning this "bug" here: https://discuss.pixls.us/t/happy-little-doggy-with-some-crazy-contrast/26237)

[DSC_1291.NEF.pp3.txt](https://github.com/Beep6581/RawTherapee/files/6933620/DSC_1291.NEF.pp3.txt)

I tried to reproduce this on other pictures, but was not really succesfull. Only one other showed the blue circle after exporting /saving to disk again:
![bluecircle](https://user-images.githubusercontent.com/78749513/128233121-bfa2ab31-a62e-4274-b045-4a36f3fad2c4.jpg)

Both are NEF-files but i cannot reproduce this behaviour on third NEF-file.

Being a little bit confused how to write a helpful bug report in this case, pls let me know which additional information will help.

**Comment by Desmis** [comment]
@marter001 

Hello
I look to your image and pp3...
The problem is with denoise....the spot is too small in high...(100 pixels)
I change the code and add a tooltip to prevent action if the spot is too small (now the minimum RT-spot size for denoise is 128x128)

I will push a change soon

Push commit  35e6a0e

Jacques

**Comment by marter001** [comment]
@Desmis 

Hello Jacques,

that was quick, thank you very much. I feared that my brief description would be too incomprehensible.
