### ISSUE TITLE
Saving profile to directory without permission results in blocked UI

### ISSUE THREAD

**Issue by marter001** [Beep6581/RawTherapee#6329]
System:
Windows 10 Home, Version 20H2, Build 19042.1110

RawTherapee:
Version: 5.8-3014-g94b5f7232
Branch: dev
Commit: 94b5f7232
Commit date: 2021-07-27

**Steps to reproduce**
- open a photo (raw)
- move any slider or just
- press save profile
- **NOW:** choose a folder in which you dont have the rights to save a file
(here preset i found: c:\Program Files\RawTherapee\RawTherapee_dev_5.8-3014-g94b5f7232_W64_Skylake_210727)
- Click "ok"
- Get informed by an infobox you dont have rights to save a file here
- Close this infobox by clicking „ok“
(From now on, it doesnt matter, if you save the profile to another folder or not)
- Choose a different folder and save the file anywhere or
- Just click „cancel“
- The Box „save a profile“ wont close anymore there is no chance to get back to the editor
- Finally shut down Raw Therapee by using the taskmanager.

**Expected behavior**
After saving a profile, the box „save profile“ should close.
After clicking „cancel“ the box „save profile“ should close.
Raw Therapee should come back to the editor

**Additional information**
Saving the profile in a different folder and overwriting an existing file will show the buttons YES / NO in english, seems they are not getting translated by the default-file.

**Comment by Thanatomanic** [comment]
I can confirm this on my Windows build as well.

**Comment by ghost** [comment]
This is not reproducible on my Linux machine (Debian 10.10/Buster).

Tried using _5.8-2995_ and _5.8-3050_

**Comment by marter001** [comment]
tried on a different machine, but also on windows with RT 5.8 release (no dev): 
same result as described above, need to use taskmanager to shut down RT
