### ISSUE TITLE
Demosaic Method: None (Shows sensor pattern) renders incorrectly in all images at high zoom levels

### ISSUE THREAD

**Issue by derMart** [Beep6581/RawTherapee#6334]
Depending on the actual zoom and viewport, the image in preview will render some pixels incorrectly with demosaicing method none.

Here is an example:

![Peek 2021-08-12 11-57](https://user-images.githubusercontent.com/1069456/129178832-c3184606-be2e-4d22-b260-51cb710f19e8.gif)

When the viewport portion changes, some blue pixels appear and disappear. When all color channels are visible, the blue pixels are rendered sometimes in dark green instead of blue:

![Screenshot from 2021-08-12 12-00-23](https://user-images.githubusercontent.com/1069456/129179043-1768a0bd-cbf5-4bf6-aa9d-d27a3fb691b6.png)

In the Navigator window, the color information remains correct though.
I have experienced this with the red color channel too (not sure about green) in a lot of different .cr2 files.
Also, it affects not only a small portion of the pixels as in the example, sometimes even large areas are affected.
(sorry, it seems it is not possible to upload the .pp3 file or .CR2 file with the issue, only a small fraction of file types are supported by github sadly)

Might this be some interpolation issue?

**Additional information**
- Version of RawTherapee: 5.8 Appimage
- Version of your operating system: Ubuntu 20.04

**Comment by Lawrence37** [comment]
You can attach a pp3 as a .txt file or use filebin.net. Are any geometric transformations (lens correction, rotation, perspective, etc.) being applied?

**Comment by derMart** [comment]
ok, here is the pp3 file: [IMG_9182.CR2.pp3.txt](https://github.com/Beep6581/RawTherapee/files/6999941/IMG_9182.CR2.pp3.txt)
No, there are no geometric transformations applied as far as I can tell.

**Comment by heckflosse** [comment]
Applying noise reduction on a not demosaiced file causes this. Because it does not make sense to apply noise reduction on a not demosaiced file, I think no further action will be taken on this.

**Comment by derMart** [comment]
It seems, the defringe option has the most influence on the problem, not sure if noise reduction contributes too (that is hard to tell).
Still, it seems very buggy that the visual output of the defringe in the preview window does not match the navigator's rgb values, independent of the possibility that defringe may not make any sense here. Though  I do not know in detail what defringe does, but this seems like a local filter, so to me it's also odd that it's output is so sensitive to just small viewport changes.

**Comment by Thanatomanic** [comment]
@derMart I see you point about the differences between the navigator and the preview. However, the 'None' demosaicer only exists for analytical purposes, and therefore bypasses active modules when it reads out the raw pixel values. So the fact that the readout does not reflect the effects on the image is expected behavior.

As for the changing effects you see when you enable tools and move the image, these are also expected. Some tools only process the visible preview area for performance reasons. 

I don't think there's anything to be done here.

**Comment by derMart** [comment]
@Thanatomanic thank you for your explanation. Although, I find that behaviour of mismatching preview output and navigator window very unintuitive.

As for the the changing effect while moving the image, however, I am not able to relate your explanation. I figured that the defringe tool only processes the preview area. Again, this seems like a local filter whose output only depends on neighboring pixels. If so, when panning the image as in the gif above, I would expect a changing output only on the edges of the preview window (due to changing boundary conditions), but not in the middle of the preview, as can be seen.

**Comment by Lawrence37** [comment]
RawPedia explains that the navigator shows the actual raw data when there is no demosaicing (http://rawpedia.rawtherapee.com/Editor#Navigator). It would be helpful if the navigator had a message to indicate this.

> RawTherapee 5.1 onward can show the real raw photosite values. To see them, set the Navigator to use the [0-255] range, apply the Neutral processing profile, then set the Demosaicing method to "None". The Navigator will show the real raw photosite values after black level subtraction within the range of the original raw data.

I can observe the changing values when everything except noise reduction is disabled. Noise reduction works across many pixels, so that may explain changes in the middle of the preview.

**Comment by derMart** [comment]
> I can observe the changing values when everything except noise reduction is disabled. Noise reduction works across many pixels, so that may explain changes in the middle of the preview.

As trying to state already above, the behaviour shown in the gif is also present if only Defringe is applied, without any noise reduction! According to RawPedia (http://rawpedia.rawtherapee.com/Defringe) Defringe is a local filter, depending on neighboring pixels (with radius 2.0 in my case, I suppose the radius is in pixel units (... hmm, fractional pixel dimensions ... ?), but the unit actually is not documented). So, having a radius of 2 px, I would only expect changes within 2 px away from the viewport boundary, when panning around. (Thinking about that, I would not expect changes at all, as I would implement such a local filter with max. 5 px radius to always look up 5 pixels over the viewport boundaries to get consistent results.) Hence my irritation.
