### ISSUE TITLE
Nikon Z7ii

### ISSUE THREAD

**Issue by bdkramer** [Beep6581/RawTherapee#6336]
Nikon Z7ii raw samples have been uploaded to the raw.pixls.us repository.

**Comment by Thanatomanic** [comment]
What do you expect we do here? Nikon Z7 II NEF files open just fine in RT 5.8 `dev`. So, decoding these images is no problem. For color support [we need additional information](http://rawpedia.rawtherapee.com/Adding_Support_for_New_Raw_Formats) and [this](http://rawpedia.rawtherapee.com/How_to_create_DCP_color_profiles).

**Comment by Thanatomanic** [comment]
Actually, even the camera color matrix is already supported.
https://github.com/Beep6581/RawTherapee/blob/7a88a0c6c00afd1ab32cff78d4fb5aad86098901/rtengine/camconst.json#L1907-L1910

**Comment by bdkramer** [comment]
My apologies, it's been a while since I'd tried working with them in RT, and I hadn't checked it with the recent updates. Please disregard if the files are no longer useful.
