### ISSUE TITLE
LA: Wrong "Color Correction Grid" black dot color

### ISSUE THREAD

**Issue by arturoisilvia** [Beep6581/RawTherapee#6340]
Hi,
Tab Local Adjustments -> Module: Color & Light -> Color Correction Grid

In the grid, the white point is supposed to be the lights and the black point the shadows.
But I notice that the black point is coloring the inverse color: Is this behavior correct?

![Captura3](https://user-images.githubusercontent.com/55624244/129928709-3b2b95fc-b984-4b9f-82f3-208252f24563.JPG)
![Captura4](https://user-images.githubusercontent.com/55624244/129928721-c50cede4-fa47-46fe-9700-a9c9f5398309.JPG)
![Captura1](https://user-images.githubusercontent.com/55624244/129928722-9fa82ae5-00a3-4770-956b-19b75005b7eb.JPG)
![Captura2](https://user-images.githubusercontent.com/55624244/129928726-189d8e35-8add-4dad-8ef6-bff548c3eb9e.JPG)

-----------------------------------
Version: 5.8-3015-g35e6a0e40
Branch: dev
Commit: 35e6a0e40
Commit date: 2021-08-06
Compiler: cc 10.3.0
Processor: generic
System: Windows
Bit depth: 64 bits

**Comment by Desmis** [comment]
@arturoisilvia 

This is the "normal" behavior of "Color correction grid" (inspired by in "Color tab", "Color toning" / "L* a* b* color correction grid").

The 2 points (black and white) allow a shift of the initial color. The "black" shifts the component a* (red/magenta - green), the "white" shifts the component b* (blue - yellow)

Depending on the choice in the combobox: "Direct" simply applies the shifts, "Color toning" takes into account the luminance.

The original GUI is adapted from the "color correction" module of Darktable. Original copyright (c) 2009--2010 johannes hanika.

jacques

**Comment by arturoisilvia** [comment]
Ok, so the behavior is correct.
I consider it solved.
Thank you Jacques.

**Comment by Beep6581** [comment]
Color tab > Color Toning
![screenshot_20210819_120122](https://user-images.githubusercontent.com/5844619/130050021-82d8eae9-e7e0-4242-954a-8ad9ac21dc9a.png)
Seems to work exactly as expected - intuitively and in accordance with the GUI.

Local Adjustments > Color & Light > Color Toning, strength: 0
![screenshot_20210819_120302](https://user-images.githubusercontent.com/5844619/130050036-56d53c28-4679-4878-b9d6-2dd20edbfb13.png)

Local Adjustments > Color & Light > Color Toning, strength: 100
![screenshot_20210819_120311](https://user-images.githubusercontent.com/5844619/130050045-563d6ccd-0e09-4a73-a16a-623c5772e159.png)

How can this be correct, if we consider "correct" to mean intuitive and in alignment with what the GUI shows?
- Color toning the shadows towards red with 0 strength should leave the image unaltered. That is not the case, as the shadows are toned red.
- Color toning the shadows towards red with 100 strength should tone the shadows red. That is not the case, as the shadows are toned blue.

**Comment by Desmis** [comment]
I push a commit which must fix this anomaly  a2c8f329a

jacques

**Comment by Beep6581** [comment]
@Desmis 5.8-3027-ga2c8f329a it now seems to work correctly (i.e. strength=0 means no change, and making shadows red at strength=100 with the spot center over a shadow does indeed make them red). Closing as fixed.
