### ISSUE TITLE
history_msg_844 is missing

### ISSUE THREAD

**Issue by marter001** [Beep6581/RawTherapee#6341]
Hi there,

i am using Version: 5.8-3015-g35e6a0e40
Branch: dev
Commit: 35e6a0e40
Commit date: 2021-08-06

Short description
when using the tool "color and light" in "Local Adjustments" in advanced mode, you will find a checkbox "FFTW" belonging to mask and modifications - blur mask .
By clicking this checkbox (activate / deactivate) the history will show HISTORY_MSG_844 instead of "using Fourier transform"

expexted behaviour
by clicking this checkbox (activate / deactivate) the history should show "using Fourier transform"

Inserting a line "HISTORY_MSG_844;using Fourier transform" to the default-file will solve this.

![history_msg_844](https://user-images.githubusercontent.com/78749513/130200929-d9732db5-c726-4ff2-8843-48a864bda949.jpg)

**Comment by Thanatomanic** [comment]
@Desmis It seems to have got lost here: https://github.com/Beep6581/RawTherapee/commit/5b97e0cde3717268c1974e839099c73dfaeaa48f

**Comment by Desmis** [comment]
I just add history msg 844 and improve the 2 others msg "blur mask"

Commit 855fe9b8e

jacques
