### ISSUE TITLE
Empty input file message and a white jpg/tif when using CIECAM

### ISSUE THREAD

**Issue by ghost** [Beep6581/RawTherapee#6343]
**Short description**

I gave this image on pixls a go: [DJI Air 2S Raw image processing](https://discuss.pixls.us/t/dji-air-2s-raw-image-processing/26520/4)

When telling RT to export this edit as JPEG it is busy for a bit, an **Empty input file** gets written in the terminal and a very small white jpg with the dimensions of the original is created. Also tried using TIF as export format; Same result.

After some experimenting I found out that if I turn off the *CIE Colour App...* module and export all is well.

~~Using the CIECAM module and the options seen in the below included sidecar are rather normal for me. Never had any issues. This is the first time, for as far as I can remember, that I edit a DNG in combination with CIECAM though.~~

_After some more testing: This is specific to this sidecar and NOT DNG specific. I can reproduce this on other RAW formats by loading this sidecar._

**Steps to reproduce**

Not sure if turning the CIECAM module on/off will do the trick but here is the sidecar that I created: [DJI_0033.with.ciecam.jpg.out.pp3.zip](https://github.com/Beep6581/RawTherapee/files/7025864/DJI_0033.with.ciecam.jpg.out.pp3.zip)

The RAW file: [DJI_0033.DNG.zip](https://github.com/Beep6581/RawTherapee/files/7025882/DJI_0033.DNG.zip)

**Expected behavior**

Being able to export after editing.

**Additional information**

* RawTherapee version : 5.8 Latest development version (also reproduced on 5.8-2995)

**Platform**

* OS                : Linux (kernel 5.9.15-1 x86_64 amd64)
* Distro            : Debian Buster (rel. 10.10)
* Graphics driver   : nvidia (460.39)

**Build info**

* Compiler      : gcc 8.3.0
* Cmake         : 3.13.4
* Glib          : 2.58.3-2
* Gtk+          : 3.24.5-1
* Exiv2         : 1.0.0.9
* Lensfun       : 0.3.2-4

**Build using:**

cmake \
    -DBUNDLE_BASE_INSTALL_DIR="$HOME/.local/${TRGT}" \
    -DBUILD_BUNDLE="ON" \
    -DCACHE_NAME_SUFFIX="5-dev" \
    -DCMAKE_BUILD_TYPE="release"  \
    -DPROC_TARGET_NUMBER="2" \
    -DOPTION_OMP="ON" \
    -DBUILD_SHARED="OFF" \
    -DWITH_LTO="ON" \
    -DWITH_BENCHMARK="OFF" \
    -DWITH_MYFILE_MMAP="ON" \
    -DWITH_PROF="OFF" \
    -DWITH_SAN="OFF" \
    -DWITH_SYSTEM_KLT="OFF" \
    .. || exit 249

**Build flags:**

    -DNDEBUG
    -O3
    -Wall
    -Wcast-qual
    -Werror=delete-incomplete
    -Werror=unknown-pragmas
    -Werror=unused-label
    -Wno-attributes
    -Wno-deprecated-declarations
    -Wno-unused-result
    -Wuninitialized
    -Wunused-macros
    -flto
    -fno-math-errno
    -fopenmp
    -ftree-vectorize
    -march=native
    -std=c++11

**Comment by ghost** [comment]
Did some more testing:

I reduced the amount of modules. These are the ones that are needed to reproduce the white image on export:

* Defringe
* Colour Management
* CIEcam
* Wavelet levels
* Local Adjustments

Turning any single one of the above off and you end up with a non-white jpeg. The *Empty input file* message remains though.

* White balance
* Demosaic

This seems to be one of those really specific cases that goes haywire. Not sure if it is worth delving into this one but I do want this to be on record just in case anyone else runs into this. That might be a sign to take action. So feel free to close this if you (maintainer/developer) feels likewise.

**Comment by Thanatomanic** [comment]
I can confirm the behavior. Looking...

**Comment by Thanatomanic** [comment]
@jade-nl For your supplied DNG, this is the minimal partial-profile pp3 I could produce that exports a blank image. Test by applying Neutral first. Disabling any module will export the image normally.
[DJI_0033.DNG-minimal.pp3.txt](https://github.com/Beep6581/RawTherapee/files/7026132/DJI_0033.DNG-minimal.pp3.txt)
Enabled modules: Defringe, Color Toning (Color Correction Regions), CIECAM, Wavelets, RAW CA Correction

However, applying this pp3 to other test images, e.g. the often-used `amsterdam.pef`, will not result in a blank image. I need the following partial-profile pp3 to get a blank image.
[amsterdam.pef-minimal.pp3.txt](https://github.com/Beep6581/RawTherapee/files/7026128/amsterdam.pef-minimal.pp3.txt)
In addition to the above modules, this case also requires Noise Reduction and Capture Sharpening to be enabled.

Could you test if you can reproduce this?

**Comment by Thanatomanic** [comment]
I can even reproduce the bug in the 5.8 release version.

I will need to inspect the pp3 more closely to see if there is any malformed entries, otherwise, this is possibly quite an old bug.

**Comment by ghost** [comment]
Using the DJI_0033.DNG-minimal.pp3.txt sidecar as described by you: 

* as is -> white jpeg
* turning of either of the ones mentioned results in a normal, non-white image.

I did test this earlier on on other images (othe DNGs and other RAW formats) but I get inconsistent results. Using [this cat on pixls](https://discuss.pixls.us/t/play-raw-a-cats-portrait/11122):

* both your supplied sidecars produce a normal, non-white image,
* using my above posted sidecar produces a white image.

**Comment by ghost** [comment]
Just ran into another one: Different RAW, different edit but same result: JPEG turns up white after exporting.

RAW: [rockies.on.cloudy.sky.cr2.zip](https://github.com/Beep6581/RawTherapee/files/7045307/rockies.on.cloudy.sky.cr2.zip)
Sidecar: [rockies.on.cloudy.sky.cr2.pp3.zip](https://github.com/Beep6581/RawTherapee/files/7045312/rockies.on.cloudy.sky.cr2.pp3.zip)

More weirdness is going on here though: Using the _Wavelet Level_ -> *Edge sharpness* I'm not able to zoom to 100% or larger. If I do the preview turn white or black. Different edge sharpness settings influence this behaviour. Not sure if this is related and need to do some more testing on that one and possibly file a different bug repart.

**Comment by ghost** [comment]
Did some testing with this new case. I'm all but 100% sure that the _100%(+) Zoom + Wavelet Level -> Edge sharpness_ issue I encounter is related to the original *white jpeg export* issue.

I reduced the amount of modules used to those that influence this faulty zoom behaviour ([rockies.minimal.pp3.txt](https://github.com/Beep6581/RawTherapee/files/7045830/rockies.minimal.pp3.txt)). The modules left are the same as found above and turning either of them off fixes both this zooming and the original export problem.

**Comment by Desmis** [comment]
@jade-nl  @Thanatomanic 

First of all, I apologize for this late intervention.

I am an old man (about 74) and I have serious health problems. Also it's exasperating to wait for I don't know what to publish 5.9; we are walking on our heads.

This problem is very old, about 10 years, and it is largely due to the shortcomings of Ciecam02 which often lead to artifacts when combining ciecam and other modules.

So, the code has been made progressively to not take into account some modules when Ciecam is activated (those you mention).

I think that at one time the GUI was supposed to (?) restore "normal" operation, but the time and simplification have probably decided otherwise.

Now that ciecam16 is implemented it should solve the problems.

As a result I have :
a) put in "Preferences", a checbox to activate the artifacts control (probable case ciecam02)
b) activated Ciecam16 by default (I hope no artifacts in all cases)

I create a new branch "ciecam_empty'


jacques

**Comment by ghost** [comment]
@Desmis 

First of all: No need to apologize. At all! I did know you're elderly, did not know about your health issues.... So with that in mind: Take your time.

Besides that, you are always fast to reply and fast to solve problems. That is much appreciated, but now knowing about your health: Please do take good care of yourself first and foremost.

---

OK, back to the issue at hand.

I just cloned/build your _ciecam_empty_ branch and that part seems to be working. And I can confirm the following.

* Preferences option is present and checked by default,
* CIEcam now starts in _Ciecam16_ mode by default,

Older edits, the two posted earlier in this thread, still show the same symptoms in this new branch. I'm presuming that is because the CIEcam options are already dialled in via the pp3s thus triggering the faulty behaviour.

I am, however, still able to trigger this behaviour.

* I created a profile based on the *rockies.minimal.pp3* posted above and did not include CIEcam. This [test profile](https://github.com/Beep6581/RawTherapee/files/7060340/minimal.trigger.test.minus.ciecam.pp3.txt).
* Loaded the rockies RAW,
* Applied *neutral* profile,
* Applied the test profile,
* Set zoom to 100%,
* Turn on CIEcam,
* Set complexity to _advanced_,
* Set *Image Adjustments* to *All*,
* In- or Decrease the *Hue* value slider (amount does not matter),
* Set Colour Curve to *Control Cage* and *Chroma*
* In- or Decreasing the curve triggers the white screen.

This seems to be another curve related issue (same as or equivalent to #6344).

**Comment by Desmis** [comment]
I cannot reconstitued....
Are you sure, after "preferences" /"color management", "Ciecam" /"avoid artifacts" 
* the check box "Avoid artifacts" is disabled
* **you restart RT**

In others cases, sure you have the same behavior....

But with the curve, the raw file provide (rockies...), the "test profile" and the process you gave.... not white screen... but perhaps there is somewhere a bad code....

I am on Windows 8

Thank you for testing :)

jacques

**Comment by ghost** [comment]
My apologies! Your implemented solution does work.

I misinterpreted/misunderstood the *Avoid artefacts* option by thinking that if it is turned on the problem would go away, but in reality it needs to be turned off. My bad for not trying out both possibilities.

This does come with the possible side effect that artefacts can now be  introduced. For me, not having that safety net isn't a problem. Artefacts aren't limited to this specific thing and I know that pushing certain option too hard can do this. I trust that my attentiveness  will notice this ugliness if it shows up.

This is solved for as far as I can tell. I'm going to leave this open until your branch is merged into the master/dev branch.

Thanks for your effort and time.

**Comment by Desmis** [comment]
Thank you very much

I will merge tomorrow...or later

Jacques

**Comment by Floessie** [comment]
> Also it's exasperating to wait for I don't know what to publish 5.9; we are walking on our heads.

Same sentiment here... :worried:

**Comment by Desmis** [comment]
merge with dev :)

jacques

**Comment by ghost** [comment]
Thanks!

Closing this one
