### ISSUE TITLE
CIECAM: Brightness via tone curve is buggy.

### ISSUE THREAD

**Issue by ghost** [Beep6581/RawTherapee#6344]
**Short description**

A very minute in/decrease when using the Brightness Tone Curve in CIEcam introduces a very large initial brightness difference.

It depends on the RAW used if the difference is too bright or too dark. The effect is seen in both directions: So increasing it or decreasing it will brighten too much, both ways in one RAW and darken, both ways in other RAWS.

_BTW:_ This might be related to a very old, still open, issue: https://github.com/Beep6581/RawTherapee/issues/3019

**Steps to reproduce**
1. Load an image,
2. Load neutral profile (not needed, just making sure we start neutral),
3. Go to and activate CIECAM module
4. Section: *Settings - Preset*, set the following options:
  * _Complexity_: Advanced
  * _CAM Model:_ both options show this
  * _Cat02/16 mode_: all three options show this
5. Section: *Image Adjustments*, set the following options:
  * _Algorithm_: All (any will do, just to have access to Brightness Q slider later).
6. Set _Tone curve 1_ (or 2) to *Brightness* and _Type_ to anything but not *Linear* or *Parametric*
7. Click on the line to create a point (problem became visible, unless you are really lucky),
8. Right click on the created point to get edit access,
9. Set both I and O to 50
10. Increase either I or O to 50.001 (smallest increase possible)
11. **-->** A huge difference in brightness was just introduced (_the bug_)
12. Reset both I and O to 50
13. Decrease either I or O to 49.999
14. **-->** The same huge difference in brightness is introduced. Notice that the brightness changed the same way. Step 10 and 13 both decrease _or_ increase the value.
15. Reset both I and O to 50
16. Use the _Brightness (Q)_ slider
17. Slowly in/decrease the slider
18. This works as expected.

**Screencast**

This one shows the above steps:

https://user-images.githubusercontent.com/56407344/130358554-878585f2-58f0-4192-8d5c-daa780f9e3cb.mp4

PS: I was very lucky in the above video when creating an initial point :-)

Here's one that goes the opposite way; Lighter instead of darker:

https://user-images.githubusercontent.com/56407344/130358730-2dd68a61-ddf6-4136-a21e-547b97614bcf.mp4

**Expected behaviour**
Gradual/fluent changes when adjusting the brightness tone curve.

**Additional information**

* RawTherapee version : _Multiple_
  * 5.8 official stable appimage,
  * 5.8-2995-g166538d appimage,
  * 5.8-3068-g0f106f980 (very latest dev version, self build).

**Platform**

* OS                : Linux (kernel 5.9.15-1 x86_64 amd64)
* Distro            : Debian Buster (rel. 10.10)
* Graphics driver   : nvidia (460.39)

**Comment by Desmis** [comment]
@jade-nl 

I know this "bad behavior"...very very old....since 2012. The problem is that brightness unlike lightness is an open scale. Probably a problem in conversion J ==> Q
I will have (another time) a look....but I do not guarantee anything  :)

But it is (partially) why I did not put curves in the LA version (with Log encoding advanced) , or in the branch "lagamcie" .This branch (waiting for 5.9 to be released) contains various advances - cam16 (simplified) - Jzazbz (experimental) - various gamma to make Lab data variable (linear==>gamma= 3==>gamma > 3) for several tools - TRC for residual wavelet,  - Log encoding auto for very underexposed images,...

Jacques

,

**Comment by ghost** [comment]
> I will have (another time) a look....but I do not guarantee anything :)

No worries. If I look at the issues list I see problems that are more important then this one.

Having this specific tone curve in good working order would be a nice-to-have, but using the slider instead is enough in probably 95+% of the cases. I also haven't heard/read about this one, here at GitHub or elsewhere, so I can only presume that it isn't used all that much....

Anyway: Thanks for taking the time to answer and also explain some stuff.

**Comment by Desmis** [comment]
@jade-nl 

After many unsuccessful attempts (why ??) , I disabled the 2 brightness curves in advanced mode. I also updated the tooltips.
I leave the code unchanged to allow a possible reactivation

And as you say, perhaps nobody used this feature...I think sliders are enough in most cases...

commit in dev - b528d6791

More information on the "lagamcie" branch, 
* I introduced the sigmoid concept (both for CAM16 and for Jzazbz)
* Jzazbz is only available in advanced mode
* 
Jacques

**Comment by ghost** [comment]
@Desmis 

> I disabled the 2 brightness curves in advanced mode. [...]

I can certainly live with this. Better then having a tone curve option that does not work.

The **J(J)** naming instead of *Lightness* needs a bit of getting used to, but the tooltip makes clear what it is all about.

One point that needs to be changed/fixed, though. The tooltip of the second tone curve says:

> Same usage as with the **second** exposure tone curve

**Second** should be **First**, right?

Thanks for your time and effort.

**Comment by Desmis** [comment]
In fact J is not exactly Lightness...More with Jz it's brightness....
Oh yes for the second tooltip  (old bug...)

thank you for testing :)


Jacques

**Comment by Desmis** [comment]
Done :)

Thank you

Jacques

**Comment by ghost** [comment]
And also _J(J) tone curve_ instead of _exposure tone curve_, that's even better :-)

Your quick response is, as always, appreciated.

Closing this one.
