### ISSUE TITLE
Crash when browsing to folder with this file

### ISSUE THREAD

**Issue by chaimav** [Beep6581/RawTherapee#6352]
I tried loading the HDR image from this Play Raw [thread ](https://discuss.pixls.us/t/improve-window-look/26563) and whenever I try to open it by browsing to its folder, RawTherapee instantly crashes. 
Windows 10 i3 8100.
Tried with versions: 5.8 official release, the latest nightly 5.8-2893, and [gaaned92](https://keybase.pub/gaaned92/RTW64NightlyBuilds/)'s 5.8-3037 Skylake and all crash.

**Comment by syyrmb** [comment]
It also crashes on my computer (Win 10 21H1, both on RT 5.8 and latest dev). I think that raw file has some issues, Affinity Photo can't read it properly and just gives a black image with color particals.
![Photo_IrJC1jkO86](https://user-images.githubusercontent.com/73344201/131865072-476642aa-97dc-44b3-9353-26049f54c91c.png)

**Comment by chaimav** [comment]
Thanks for confirming. Even if the file is corrupt, at worst it should throw an error message and not just close without warning.

**Comment by ghost** [comment]
This also isn't a Windows issue, crashes here as well. Using the latest self build development version:

* 5.8-3077-g047485b8b
* OS                : Linux (kernel 5.9.15-1 x86_64 amd64)
* Distro            : Debian Buster (rel. 10.10)

Yeah, this file has issues. XnView also doesn't like it (it doesn't crash though....).

**Comment by heckflosse** [comment]
The dng has wrong info for top and left margin. Hacking the code to set both to zero I get this:

![grafik](https://user-images.githubusercontent.com/13733487/131994287-2011de73-3e29-4d0b-b95f-c00a75a70de8.png)

trying to find a solution...
