### ISSUE TITLE
Potential Integer Overflow in rtengine/klt/klt.cc

### ISSUE THREAD

**Issue by KSB21ST** [Beep6581/RawTherapee#6354]
It seems that there exists a potential integer overflow. Please find the following description:

1. _readHeader(...) is called
https://github.com/Beep6581/RawTherapee/blob/2d3e45721159c66ed37e24175a562f6d85d350b6/rtengine/klt/writeFeatures.cc#L763

2. Inside  _readHeader(...), nFeatures can be an arbitrary large number
https://github.com/Beep6581/RawTherapee/blob/2d3e45721159c66ed37e24175a562f6d85d350b6/rtengine/klt/writeFeatures.cc#L555

3. KLTCreateFeatureTable(...) is called with the second argument as nFeatures 
https://github.com/Beep6581/RawTherapee/blob/2d3e45721159c66ed37e24175a562f6d85d350b6/rtengine/klt/writeFeatures.cc#L771

4. Call to malloc with the large integer can cause a memory allocation with an overflowed size
https://github.com/Beep6581/RawTherapee/blob/2d3e45721159c66ed37e24175a562f6d85d350b6/rtengine/klt/klt.cc#L232

**Comment by heckflosse** [comment]
afiak 'writeFeatures.cc` is not used in RT. I vote for closing this issue.

**Comment by heckflosse** [comment]
closed by accident

**Comment by Thanatomanic** [comment]
Indeed, thanks for the report, but as @heckflosse mentions, we do not make use of this particular functionality of the library. If anything, this should be reported upstream: http://cecas.clemson.edu/~stb/klt/ (but that project has not had an update in nearly 15 years).
