### ISSUE TITLE
RT shuts down when opening a specific dng-file

### ISSUE THREAD

**Issue by marter001** [Beep6581/RawTherapee#6355]
I was trying to join a Play Raw in pixls.us, pls see here: 

https://discuss.pixls.us/t/improve-window-look/26563

and downloaded the 3 mentioned dng-files:
https://a42578-drive.mycozy.cloud/public?sharecode=tOGchMZlqrAL

With RT i am not able, to edit these files, because RT shuts down without any error-message when trying to open. 

**Steps to reproduce**
1. open RT
2. Explore the folder containing the mentioned dng-files
3. doubleclick one of them
4. RT shuts down, no error message, no entry in eventlog, no pp3-file created

**Expected behavior**
RT should open the file for processing

**System information**
I am working on
Windows 10 Home - 64-Bit
Version	20H2
Build	19042.1165
Windows Feature Experience Pack 120.2212.3530.0
Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz   3.60 GHz, x64-based
RAM	40,0 GB

RawTherapee:
Version: 5.8-3015-g35e6a0e40
Branch: dev
Commit: 35e6a0e40
Commit date: 2021-08-06
Compiler: cc 10.3.0
Processor: Skylake
System: Windows
Bit depth: 64 bits
downloaded  from /keybase/public/gaaned92/RTW64NightlyBuilds

but also fomer versions (downloaded from github) are crashing when opening these files.

**Additional information**
1. I downloaded them several times to make sure, i am not working on a damaged file
2. RT works fine on other dng-files downloads for Play Raw, they can be opened and processed 
3. It seems that other users were able to open those files with RT
4. Other software is opening these files as expected

**Comment by syyrmb** [comment]
AFAIK it was just fixed yesterday, see https://github.com/Beep6581/RawTherapee/issues/6352.

**Comment by marter001** [comment]
oh thanks, sorry for confusing.

**Comment by Heddesdorfer** [comment]
RT shuts down if the dng file is defect. Adobe created a defect dng file and RT shuts down while reading the directory.
So the basic error is on Adobe DNG Converter, but it would be nice if RT would place a message concerning this special file and keep on working instead of crashing. BTW: it happened with WIN10 21H2 and Manjaro 21.3.5. (After that I created another dng with dnglab and it worked.)

**Comment by Lawrence37** [comment]
@Heddesdorfer The DNGs in the initial post open fine in the current dev version. If you have other DNGs that still cause a crash, please open a new issue and provide the necessary information as indicated in [RawPedia](http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports).
