### ISSUE TITLE
White Balance auto on with temperature correlation mode

### ISSUE THREAD

**Issue by arturoisilvia** [Beep6581/RawTherapee#6365]
Set White Balance to Automatic-> Temperature Correlation mode.
If you now turn off the same White Balance module, it automatically turns on again.

Expected behavior: The White Balance module should be turned off.

----------------
Version: 5.8-3046-g5268b94cf
Branch: dev
Commit: 5268b94cf
Commit date: 2021-09-04
Compiler: cc 10.3.0
Processor: generic
System: Windows

**Comment by arturoisilvia** [comment]
I have changed the title to make it more descriptive when searching.

**Comment by heckflosse** [comment]
Bug confirmed. looking...
