### ISSUE TITLE
Error in GUI after loading a private profile 

### ISSUE THREAD

**Issue by Heddesdorfer** [Beep6581/RawTherapee#6370]
**Short description**
After loading a private profile which is not the standard profile contains a pre-setting for wavelets and then move to another picture and load this profile again, some comboboxes are disabled.

**Steps to reproduce**
1. Create a profile with settings within wavelets
2. Close Rawtherapee und start it again
3. Open a picture and load this profile
4. Open another picture and load this profile again
5. The comboboxes "Hintergrund" and "Verarbeitung" are disabled
6. You have to close Rawtherapee and start it again to use this profile for the second  picture

** Expected behavior**

**Additional information**
Version: 5.8-3049-gd053f0245
Branch: dev
Commit: d053f0245
Commit date: 2021-09-19
Compiler: cc 11.1.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.24.5
Lensfun: V0.3.95.0
Build type: release
Build flags:  -std=c++11 -march=native -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wno-attributes -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON
Build OS: Linux 5.14.2-1-MANJARO x86_64
Build date: Sun, 19 Sep 2021 15:52:36 +0000 UTC
Build epoch: 1632066756
Build UUID: b5f1e306-353d-4902-9be9-3c8577210901

Other useful information:
[RPMakroVor.pp3.txt](https://github.com/Beep6581/RawTherapee/files/7231573/RPMakroVor.pp3.txt)
![Wavelet](https://user-images.githubusercontent.com/91422232/134812372-3461f048-1e6a-4db8-baba-69cef7eef715.png)

**Comment by ghost** [comment]
I'm not able to reproduce this issue.

I tried creating a few wavelet profiles with different initial settings. None show this. Not with and not without restarting RawTherapee in between using it with different RAWs.

I also tried your _RPMakroVor.pp3_ and that doesn't show this issue either. However: Your sidecar and the above screenshot are not at all the same.

The Wavelets module is turned off and settings are different when I load RPMakroVor.pp3:
![RPMakroVor](https://user-images.githubusercontent.com/56407344/134881567-512388da-86f1-40a0-bb88-32401c0d6737.png)

**Comment by Heddesdorfer** [comment]
Well, I tried to reproduce it (it happened three times yesterday) - but now it works ! Although nothing has changed. Seems to be an one-off error. Not the first time in my life as SW-QA (I'm used to reproduce errors before reporting them).
