### ISSUE TITLE
Rawtherapee flatpak to access all user folders (incl /mnt/)

### ISSUE THREAD

**Issue by r47177** [Beep6581/RawTherapee#6372]
Hi,

I've used command "sudo flatpak override com.rawtherapee.RawTherapee --filesystem=host" however inside the app I still can't access /mnt or /media folders which are acessible to me using file browser and other programs.

I am using Elementary OS 6 and RawTherapee 5.8

May you please help?

Thanks.

**Comment by Lawrence37** [comment]
I found a similar question on UNIX Stack Exchange: https://unix.stackexchange.com/questions/605285/how-to-always-run-a-flatpak-application-with-a-filesystem-permission

The command you used is for system-wide installations. For per-user installations, add the `--user` option without sudo:
```
flatpak override --user com.rawtherapee.RawTherapee --filesystem=host
```

Could this be the problem you are facing?

**Comment by r47177** [comment]
That's exactly what happened, working great now! Thanks ;)
