### ISSUE TITLE
Feature request: JPEG XL

### ISSUE THREAD

**Issue by abnormally-distributed** [Beep6581/RawTherapee#6375]
I think it would be nice to have JPEG XL support added for both importing and exporting in RT 5.9

- Supports up to 32 bit float encoding
- Has both lossy and lossless compression modes 
- Supports alpha (transparency) channel
- Is explicitly intended to replace the legacy JPEG format 

For more information: https://jpeg.org/jpegxl/

**Comment by Lawrence37** [comment]
Duplicate of #6273.
