### ISSUE TITLE
Add a average filter for pixel shift to process the moving  parts

### ISSUE THREAD

**Issue by huahuasousou** [Beep6581/RawTherapee#6376]
In the current version5.8, we can use median for moving parts to remove some objects. but some photography don't want to remove the moving object, and they want to have a Motion blur. So maybe we can add an average filter for moving parts. and it can achieve the slow shutter effect that simulates long exposure.

**Comment by heckflosse** [comment]
@huahuasousou 

I created psaverage branch with the requested feature

**Comment by heckflosse** [comment]
@huahuasousou Any interest to test this?

**Comment by huahuasousou** [comment]
> @huahuasousou Any interest to test this?

Hi, I can test this feature

**Comment by huahuasousou** [comment]
> @huahuasousou Any interest to test this?

Hi, I just finished the test, result it's good. you can check it in attachement.
![_DSC8766](https://user-images.githubusercontent.com/35621281/141019085-53e1ea9f-83e4-4bc9-9135-e07f23733c48.jpg)

![_DSC8766_PSMS](https://user-images.githubusercontent.com/35621281/141019070-2e55d07a-65bc-422b-9fca-1450d895f88a.jpg)

**Comment by heckflosse** [comment]
@huahuasousou Thanks for testing 👍
