### ISSUE TITLE
dng OpcodeList2 gainmap support

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#6379]
I started work on dng gainmap support.

Here's a first result, left without gainmap, right with:
![grafik](https://user-images.githubusercontent.com/13733487/140913892-a91296a0-5e12-4cf4-9ead-bfae16d0e221.png)

The implementation is different to the ART implementation (well, at least for now) and runs only once over the rawdata array, while the ART implementation needs to run twice (cache-wise). This is still wip, but a PR will follow soon.

**Comment by heckflosse** [comment]
I created dnggainmap branch. Code is ready to test, but not ready to merge (too verbose, gui needs some changes etc.)

![grafik](https://user-images.githubusercontent.com/13733487/141676826-fc6da508-8429-4ee6-b538-926344c8600b.png)

**Comment by paolodepetrillo** [comment]
Just found an unusual usage of GainMap that wouldn't work with this implementation, or with ART's. Not sure how common this is, I had never seen it in any other files. This one is in OpcodeList3 and is intended to be applied to each color channel after demosaic.

https://discuss.pixls.us/t/looking-for-samples-smartphone-dngs-with-embedded-gainmap/27296/12
