### ISSUE TITLE
Entries missing in Default

### ISSUE THREAD

**Issue by marter001** [Beep6581/RawTherapee#6381]
I am working with:

Version: 5.8-3049-gd053f0245
Branch: dev
Commit: d053f0245
Commit date: 2021-09-19
Compiler: cc 10.3.0
Processor: Skylake
System: Windows

Seems there are some entries missing in the default file: Using the wavelet-tools, these msgs will be shown in History:

HISTORY_MSG_chrwav
HISTORY_MSG_WAVLEVELSIGM
HISTORY_MSG_WAVLABGRID_VALUE

instead of:

wavelets - blur levels - blur chroma  
wavelets - denoise - radius
wavelets - toning - excluded colors
![default_missing](https://user-images.githubusercontent.com/78749513/141478489-6b4504b6-7823-4183-8022-09272ff01c46.jpg)

**Comment by Desmis** [comment]
@marter001 

Thank you for testing....and find these missing history msg.

Fixed with commit a1bbede06


jacques
