### ISSUE TITLE
RawTherapee not loading sidecar pp3 files

### ISSUE THREAD

**Issue by samueldc** [Beep6581/RawTherapee#6392]
Hi, my RawTherapee stopped loading pp3 files. The folder images are loaded, but the saved changes are not. All the pp3 files are there, but no change is showed during processing. If I make a new change, the pp3 is rewritten. But the old pp3 files are not loaded.

**Comment by heckflosse** [comment]
Please provide a raw and pp3 file. Also please post the content of your `AboutThisBuild.txt`.
