### ISSUE TITLE
don't start

### ISSUE THREAD

**Issue by TomaszMyszak** [Beep6581/RawTherapee#6396]
**Short description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

**Comment by TomaszMyszak** [comment]
==========

LD_LIBRARY_PATH: /tmp/tmp.Yq21ZEKZov:/usr/lib::/tmp/.mount_RawThecsBKoo/usr/lib/gdk-pixbuf-2.0/loaders
DIRNAME: /tmp/.mount_RawThecsBKoo/usr/bin
DESKTOPFILE_NAME: rawtherapee.desktop
APP_FULL: RawTherapee
APP: RawTherapee
APP_FULL: RawTherapee
APP: RawTherapee
BIN: /tmp/.mount_RawThecsBKoo/usr/bin/rawtherapee
DESKTOPINTEGRATION: 
HERE!!!
GLib-GIO-Message: 09:45:59.570: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.

(zenity:6695): GLib-GIO-ERROR **: 09:45:59.571: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'
/tmp/.mount_RawThecsBKoo/usr/bin/rawtherapee.wrapper: line 124:  6695 Trace/breakpoint trap   (core dumped) zenity --question --title="$TITLE" --text="$TEXT" --no-wrap
yesno finished
GLib-GIO-Message: 09:45:59.861: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.

(zenity:6700): GLib-GIO-ERROR **: 09:45:59.861: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'
/tmp/.mount_RawThecsBKoo/usr/bin/rawtherapee.wrapper: line 124:  6700 Trace/breakpoint trap   (core dumped) zenity --question --title="$TITLE" --text="$TEXT" --no-wrap
yesno finished
GLib-GIO-Message: 09:46:00.756: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.

(rawtherapee:6672): GLib-GIO-ERROR **: 09:46:00.757: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'
/tmp/.mount_RawThecsBKoo/AppRun: line 146:  6672 Trace/breakpoint trap   (core dumped) LD_PRELOAD="${APPDIR}/usr/lib/exec_wrapper2.so" "${APPDIR}/usr/bin/rawtherapee.wrapper" "$@"


don't work in Ubuntu 21.10

**Comment by Thanatomanic** [comment]
Please provide accurate information on what you've done to obtain your copy of RT and then how you try to run

**Comment by kmoppel** [comment]
With the same error on Ubuntu 22.04 got it to start by setting the `GDK_BACKEND=x11` variable, i.e. `GDK_BACKEND=x11 ./RawTherapee_5.8.AppImage`
