### ISSUE TITLE
Perspective module (camera based) filled with false focal lengt and crop factor data if set after file browser rotate

### ISSUE THREAD

**Issue by epadepa** [Beep6581/RawTherapee#6402]
**Steps to reproduce**
1. Select and image suitable for perspective correction in the file browser and right click select _Processing profile operations > Clear_ 
2. Rotate the image clockwise using the _90 degree icons_ in the file browser view. Rotate the image counterclockwise to get the image back as shot. (the problem was discovered when editing old files from a camera that doesn't have a sensor for orientation so this step in only for triggering the bug with contemporary files)
3. Open the perspective tool and set the "camera based" mode.
4. The various fields are filled out with the wrong data about the camera and the lens. Typically a focal length of 24 and crop factor of 1 regardless of exif data and actual camera and lens. 
 
**Expected behavior**
The focal length and crop factor should match the exif data.

**Additional information**

Note that the bug only manifests if the perspective module is set to "camera based" from simple **after** doing the rotate in the file browser. If you change the perspective module from "simple" to "camera based" in the Editor before doing the rotate the correct focal length and crop factor will remain even after a file browser rotate.

If you rotate using the same 90 degree icons in the Editor tab it works as expected. The bug was  encountered working on old files from a camera without the orientation sensor. My workflow is usually to ctrl-click all mis oriented images and rotate them en mass.

My guess is that RT is doing something clever to avoid processing all actions initiated from the file browser and waits to do this until the file is actually edited in the Editor tab. Unfortunately something happens and it is then initialised incorrectly or incompletely when the combination of rotate and perspective correction "camera based" is applied.

Version: 5.8-3183-g3289e6951
Branch: dev
Commit: 3289e6951
Commit date: 2021-09-07
Compiler: cc 10.3.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.24.5
Lensfun: V0.3.2.0
Build type: release
Build flags: -std=c++11 -Wno-deprecated-declarations -Wno-unused-result -O3 -msse2 -std=c++11 -march=native -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wno-attributes -flto -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags:  -march=native -flto
OpenMP support: ON
MMAP support: ON
Build OS: Linux 5.10.0-8-amd64 x86_64
Build date: Tue, 07 Sep 2021 16:26:30 +0000 UTC
Build epoch: 1631031990
Build UUID:

**Comment by Lawrence37** [comment]
Thanks for reporting.

The focal length and crop factor are populated when the image is opened in the editor and the existing processing profile (if there is one) does not have them. I'm guessing the two parameters are getting set when rotating from the file browser. The default values are 24 and 1. I will fix this when I get the chance.
