### ISSUE TITLE
Color balance for Sony ILCE-7M4 is way off

### ISSUE THREAD

**Issue by Barugon** [Beep6581/RawTherapee#6404]
**Short description**
If I use the camera's color balance then the colors look correct but the values are way off.
![Screenshot from 2022-01-09 16-47-22](https://user-images.githubusercontent.com/16503728/148708189-ba826a28-1451-4dc2-b9e2-649c1b004d37.jpg)

If I switch to daylight color balance then the colors are very wrong.
![Screenshot from 2022-01-09 16-47-34](https://user-images.githubusercontent.com/16503728/148708329-1bdcc439-e929-4b24-a56f-c29d7a655d7e.jpg)

The same thing happened with the Panasonic S5 [here](https://github.com/Beep6581/RawTherapee/issues/5987) but that was resolved.

**Steps to reproduce**
Open a Sony A7IV raw file and switch to any color balance other than "camera".

**Expected behavior**
Correct values for color balance.

**Additional information**
Version: 5.8-3065-g9c5ce0d9b
Branch: dev
Commit: 9c5ce0d9b
Commit date: 2022-01-08
Compiler: clang 13.0.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.24.5
Lensfun: V0.3.2.0
Build type: release
Build flags:  -std=c++11 -march=native -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wno-attributes -flto -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -fopenmp=libomp -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags:  -march=native -flto
OpenMP support: ON
MMAP support: ON
Build OS: Linux 5.15.12-200.fc35.x86_64 x86_64
Build date: Mon, 10 Jan 2022 00:40:35 +0000 UTC
Build epoch: 1641775235
Build UUID: 4c318817-72fe-4db5-9f96-fab6dbd888e8

**Comment by Barugon** [comment]
If I use the color matrix values from the ILCE-7M3 (which are apparently the same as the ILCE-9) then everything looks pretty correct.

**Comment by Entropy512** [comment]
Amazon keeps on moving up my shipping estimate, to the point where the camera MIGHT arrive for this weekend if the trend continues (it did for my A7M3 order).  If so, AND if it's clear sky out (um...  low probability on this one...) I'll shoot the necessary ColorChecker shots to generate a DCP profile.

Otherwise the camera will be arriving early next week and I won't be able to shoot daylight color chart shots until the following weekend.

**Comment by Entropy512** [comment]
Camera is arriving today, but weather and timing mean that if I can get a sunlight ColorChecker shot it'll be a marginal one - better than nothing I guess until I get a good sunny weekend.

**Comment by Barugon** [comment]
I really should invest in a proper test target....

**Comment by Entropy512** [comment]
I have my sunlight shots, need to stop being lazy and find my tungsten bulb for StdA shots.  Later this week maybe?

**Comment by Beep6581** [comment]
> but weather and timing mean that if I can get a sunlight ColorChecker shot it'll be a marginal one

My experiments revealed no practical difference between profiles made on sunny summer days vs overcast winter days.

**Comment by Entropy512** [comment]
I think I remember you mentioning that, but I'm picky enough that I wanted to at least get clear winter - which I do have now.  Just need to find my tungsten bulb and stop being lazy to get StdA.

I haven't seen you in a while, welcome back!

**Comment by Beep6581** [comment]
Indeed the color matrix was way off. @Barugon please try build 34b56a14 or newer ([automated builds](https://github.com/Beep6581/RawTherapee/releases/tag/nightly-github-actions)) and comment whether the issue is fixed.

@Entropy512 we can handle the color profile in a separate issue once you're ready.

**Comment by Barugon** [comment]
> Indeed the color matrix was way off. @Barugon please try build [34b56a1](https://github.com/Beep6581/RawTherapee/commit/34b56a14e48fe5b09b78ae1a12699be5e675d76a) or newer ([automated builds](https://github.com/Beep6581/RawTherapee/releases/tag/nightly-github-actions)) and comment whether the issue is fixed.

Yes, much better. Thank you.

**Comment by Barugon** [comment]
Closing this issue as it's now fixed.
