### ISSUE TITLE
http://rawtherapee.com/ website is down

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#6407]
I noticed that our website is down. Has it been down for long?

I cannot access it via FTP either, but the domain and the server show no issues.

**Comment by Thanatomanic** [comment]
It is not down: https://downforeveryoneorjustme.com/rawtherapee.com

Not sure what is going on on your end...

![image](https://user-images.githubusercontent.com/6567747/149163189-7c21bddd-608c-4716-9fd6-932572006958.png)

Edit: it doesn't matter for me whether I try `rawtherapee.com`, `www.rawtherapee.com` and with either `http` or `https`. Things are looking good.

**Comment by Beep6581** [comment]
Both the website and FTP are down for me not only via the domain but also via IP. Guess it will solve itself...

**Comment by chaimav** [comment]
Works fine for me as well
