### ISSUE TITLE
Running commnad "cmake --build . --target install" fails in the next job: [2/35] Linking CXX executable rtgui\rawtherapee-cli.exe

### ISSUE THREAD

**Issue by Acasmol** [Beep6581/RawTherapee#6412]
**RawTherapee version:** "dev" branch as the date of 2022-01-21
**OS Version**: Windows 10 - 19043.1466

**Issue happen when:** Running the follow command:
 "cmake --build . --target install"

**Output of the command:**

[262/300] Linking CXX executable rtgui\rawtherapee-cli.exe
FAILED: rtgui/rawtherapee-cli.exe
cmd.exe /C "cd . && C:\TDM-GCC-64\bin\c++.exe -std=c++11 -march=native -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wno-attributes -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -O3 -DNDEBUG -march=native rtgui/CMakeFiles/rth-cli.dir/myicon.rc.obj rtgui/CMakeFiles/rth-cli.dir/alignedmalloc.cc.obj rtgui/CMakeFiles/rth-cli.dir/editcallbacks.cc.obj rtgui/CMakeFiles/rth-cli.dir/main-cli.cc.obj rtgui/CMakeFiles/rth-cli.dir/multilangmgr.cc.obj rtgui/CMakeFiles/rth-cli.dir/options.cc.obj rtgui/CMakeFiles/rth-cli.dir/paramsedited.cc.obj rtgui/CMakeFiles/rth-cli.dir/pathutils.cc.obj rtgui/CMakeFiles/rth-cli.dir/threadutils.cc.obj -o rtgui\rawtherapee-cli.exe -Wl,--out-implib,rtgui\librawtherapee-cli.dll.a -Wl,--major-image-version,0,--minor-image-version,0 -LD:/Software/RawTherapee/RawTherapee/rtgui/.   -LD:/Software/RawTherapee/RawTherapee/rtexif   -LC:/msys64/mingw64/bin/../lib rtengine/librtengine.a  -lcairomm-1.0  -lsigc-2.0  -lcairo  -lexpat  -lm  -lwinmm  -lfftw3f  -lgiomm-2.4  -lgio-2.0  -lglibmm-2.4  -lgobject-2.0  -lglib-2.0  -lintl  -lsigc-2.0  -lgio-2.0  -lgobject-2.0  -lglib-2.0  -lintl  -lglib-2.0  -lintl  -lglibmm-2.4  -lgobject-2.0  -lglib-2.0  -lintl  -lsigc-2.0  -lgobject-2.0  -lglib-2.0  -lintl  -lgthread-2.0  -lglib-2.0  -lintl  -liptcdata  C:/msys64/mingw64/lib/libjpeg.dll.a  -llcms2  C:/msys64/mingw64/lib/libpng.dll.a  C:/msys64/mingw64/lib/libz.dll.a  C:/msys64/mingw64/lib/libtiff.dll.a  C:/msys64/mingw64/lib/libz.dll.a  -llensfun  -lrsvg-2  -lm  -lgio-2.0  -lgdk_pixbuf-2.0  -lgobject-2.0  -lglib-2.0  -lintl  -lcairo  rtexif/librtexif.a  -lws2_32 -lshlwapi  -lsigc-2.0  -lm  -lfftw3f  -lgio-2.0  -lglibmm-2.4  -lgobject-2.0  -lglib-2.0  -lintl  -lgthread-2.0  -liptcdata  C:/msys64/mingw64/lib/libjpeg.dll.a  -llcms2  C:/msys64/mingw64/lib/libpng.dll.a  C:/msys64/mingw64/lib/libz.dll.a  C:/msys64/mingw64/lib/libtiff.dll.a  -llensfun  -lrsvg-2  -lgdk_pixbuf-2.0  -lsigc-2.0  -lm  -lfftw3f  -lgio-2.0  -lglibmm-2.4  -lgobject-2.0  -lglib-2.0  -lintl  -lgthread-2.0  -liptcdata  C:/msys64/mingw64/lib/libjpeg.dll.a  -llcms2  C:/msys64/mingw64/lib/libpng.dll.a  C:/msys64/mingw64/lib/libz.dll.a  C:/msys64/mingw64/lib/libtiff.dll.a  -llensfun  -lrsvg-2  -lgdk_pixbuf-2.0  -lcairo  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
C:/msys64/mingw64/bin/../lib/libiptcdata.a(iptc-data.o):(.text+0x195): undefined reference to `__imp___acrt_iob_func'
collect2.exe: error: ld returned 1 exit status
[263/300] Building CXX object rtgui/CMakeFiles/rth.dir/fattaltonemap.cc.obj
[264/300] Building CXX object rtgui/CMakeFiles/rth.dir/extprog.cc.obj
[265/300] Building CXX object rtgui/CMakeFiles/rth.dir/filebrowserentry.cc.obj
[266/300] Building CXX object rtgui/CMakeFiles/rth.dir/editorpanel.cc.obj
[267/300] Building CXX object rtgui/CMakeFiles/rth.dir/filebrowser.cc.obj
ninja: build stopped: subcommand failed.

**Command ran before the last command:**
cmake -G "Ninja" -DLENSFUNDBDIR=C:/msys64/mingw64/var/lib/lensfun-updates/version_1 -DCMAKE_BUILD_TYPE="release" -DPROC_TARGET_NUMBER="2" -DCACHE_NAME_SUFFIX="5-dev" -S D:/Software/RawTherapee/RawTherapee

**Output of the last command:**
-- The C compiler identification is GNU 5.1.0
-- The CXX compiler identification is GNU 5.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/TDM-GCC-64/bin/gcc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/TDM-GCC-64/bin/c++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_BUILD_TYPE: release
-- Found PkgConfig: C:/msys64/mingw64/bin/pkg-config.exe (found version "1.8.0")
-- Checking for module 'gtk+-3.0>=3.22.24'
--   Found gtk+-3.0, version 3.24.31
-- Checking for module 'gtkmm-3.0>=3.22'
--   Found gtkmm-3.0, version 3.24.5
-- Checking for module 'glib-2.0>=2.48'
--   Found glib-2.0, version 2.70.2
-- Checking for module 'glibmm-2.4>=2.48'
--   Found glibmm-2.4, version 2.66.2
-- Checking for module 'cairomm-1.0'
--   Found cairomm-1.0, version 1.14.3
-- Checking for module 'gio-2.0>=2.48'
--   Found gio-2.0, version 2.70.2
-- Checking for module 'giomm-2.4>=2.48'
--   Found giomm-2.4, version 2.66.2
-- Checking for module 'gthread-2.0>=2.48'
--   Found gthread-2.0, version 2.70.2
-- Checking for module 'gobject-2.0>=2.48'
--   Found gobject-2.0, version 2.70.2
-- Checking for module 'sigc++-2.0>=2.3.1'
--   Found sigc++-2.0, version 2.10.7
-- Checking for module 'lensfun>=0.2'
--   Found lensfun, version 0.3.2.0
-- Checking for module 'librsvg-2.0>=2.40'
--   Found librsvg-2.0, version 2.52.5
-- Checking for module 'lcms2>=2.6'
--   Found lcms2, version 2.12
-- Checking for module 'expat>=2.1'
--   Found expat, version 2.4.3
-- Checking for module 'fftw3f'
--   Found fftw3f, version 3.3.10
-- Checking for module 'libiptcdata'
--   Found libiptcdata, version 1.0.4
-- Found TIFF: C:/msys64/mingw64/lib/libtiff.dll.a (found suitable version "4.3.0", minimum required is "4.0.4")
-- Found JPEG: C:/msys64/mingw64/lib/libjpeg.dll.a (found version "80")
-- Found ZLIB: C:/msys64/mingw64/lib/libz.dll.a (found version "1.2.11")
-- Found PNG: C:/msys64/mingw64/lib/libpng.dll.a (found version "1.6.37")
-- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES)
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES)
-- Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND)
-- Performing Test LENSFUN_HAS_LOAD_DIRECTORY
-- Performing Test LENSFUN_HAS_LOAD_DIRECTORY - Success
-- Configuring done
-- Generating done
-- Build files have been written to: D:/Software/RawTherapee/RawTherapee/build

**Issue Summary:**
 Running commnad "cmake --build . --target install" fails in the next job: [2/35] Linking CXX executable rtgui\rawtherapee-cli.exe

![image](https://user-images.githubusercontent.com/17996696/150572780-01066725-1428-4050-bef4-50cab9f9b084.png)

![image](https://user-images.githubusercontent.com/17996696/150573033-1dae11cc-5928-4f98-af6c-69bf4f155a75.png)

**Last command run:**
![image](https://user-images.githubusercontent.com/17996696/150573356-e3e23990-e0d5-4f21-9527-0e61c5d80a6b.png)

**Comment by Thanatomanic** [comment]
Not sure what is going on, I have no problems building and linking RT myself. Two things of note:
1. Why are you not using the gcc/g++ provided by MSYS2/Mingw64? Could this be the root of the linking issues?
2. After configuring for Ninja, it is easier to just run `ninja install` instead of your `cmake` line.

Edit: in fact, I see you're also using a separate Git installation, instead of directly from MSYS2, which is also curious.

**Comment by Acasmol** [comment]
Sorry...

All issues were resolved when I start using  MSYS2 MinGW x64

Thanks!

Colising this issue!
