### ISSUE TITLE
Help tooltip overshadows the image

### ISSUE THREAD

**Issue by iurienistor** [Beep6581/RawTherapee#6415]
How can I turn off this help tooltip which overshadows the image?
If there is no options, I think it would be useful the user to be able to turn off in the application in  UI settings.
![helptooltip](https://user-images.githubusercontent.com/56111777/151516125-c2b5ecbf-4f18-49f8-bd96-47fd45449b1f.png)

**Comment by Thanatomanic** [comment]
Duplicate of #6007
