### ISSUE TITLE
Vertical alignment tool

### ISSUE THREAD

**Issue by ror6ax** [Beep6581/RawTherapee#6422]
I'd like to propose a new tool, same as existing horizontal alignment, only for vertical lines.

As someone shooting a lot of architecture imagery, I often find myself wanting to align the window or a column or a house wall - obviously align them vertically.

Should be a relatively easy thing to implement for a newb like me - if @Beep6581 approves such an undertaking,

**Comment by Thanatomanic** [comment]
Nobody holds you back or needs to approve for you to come up with a pull request for the change. Go for it!

**Comment by Lawrence37** [comment]
Are you referring to the [rotate / straight line tool](http://rawpedia.rawtherapee.com/Lens/Geometry#Rotate), because it works vertically too.

**Comment by Thanatomanic** [comment]
Based on @Lawrence37's comment: yes, this should already be possible in the current development build. So @ror6ax, unless there is something specific you need, I'll close this request.
