### ISSUE TITLE
Where to find automated macOS builds

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#6433]
Hey

What is currently the "official" automated macOS build source and who runs it?
Is it https://keybase.pub/kd6kxr/ run by @Benitoite ?

**Comment by Thanatomanic** [comment]
Yes

**Comment by Benitoite** [comment]
These are automated to the extent the distribution package is generated by one command line.

**Comment by Beep6581** [comment]
@Benitoite is it possible and would you feel like turning it into a github-action (or anything completely automatic and transparent)?

**Comment by Thanatomanic** [comment]
@Beep6581 I believe I already asked a similar thing [here](https://github.com/Beep6581/RawTherapee/issues/6139#issuecomment-1031114035) to which the answer is given a few posts down.

**Comment by Beep6581** [comment]
> @Thanatomanic Right, to work on macOS the app and dmg must go thru a proprietary Apple malware check.  The automation skips that post compilation codesigning and notary transmission.

_Originally posted by @Benitoite in https://github.com/Beep6581/RawTherapee/issues/6139#issuecomment-1031125507_

The oozou blog (link below) says says:

> If you don't notarize your app, then when users download it they will be greeted by a message from Gatekeeper saying that Apple could not check the software for malicious content, and there will be no immediately obvious way for the user to open your app. To open your app, they will need to either 1) right click on the application, which opens a menu with an option to open it anyways, or 2) they will need to explicitly go to their Security settings and allow the app to open. However, nothing in Gatekeeper's message indicates either of these are an option, so most users will just not be able to use your app.

For an automated nightly build intended for testing, that shouldn't be too much of a problem. We can always mention this on the development build download page.

Though it seems that notarization can be automated in a script using `notarytool` and `stapler`:
https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution#3087728
https://oozou.com/blog/scripting-notarization-for-macos-app-distribution-38

**Comment by Benitoite** [comment]
Codesign and Notary are both completely handled in https://github.com/Beep6581/RawTherapee/blob/dev/tools/osx/macosx_bundle.sh as documented in https://rawpedia.rawtherapee.com/MacOS#Compiling

The github-action is already working https://github.com/Beep6581/RawTherapee/blob/dev/.github/workflows/main.yml but of course the notary is turned off because of the privatized Apple credential I use.
