### ISSUE TITLE
strong moire in debayerfunctions: none and mono; crashes while zooming in

### ISSUE THREAD

**Issue by Reiner1959** [Beep6581/RawTherapee#6447]
Latest build of dev version RT shows strong moire if zooming to 50% and 100%
sometimes RT crashes during zooming.

see the screenshots attached:

Version: 5.8-3084-gc45a6105f
Branch: dev
Commit: c45a6105f
Commit date: 2022-03-26
Compiler: cc 11.2.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.24.5
Lensfun: V0.3.2.0
Build type: release
Build flags:  -std=c++11 -fno-tree-loop-vectorize -march=native -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wno-attributes -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON
Build OS: Linux 5.16.0-5-amd64 x86_64
Build date: Sun, 27 Mar 2022 11:28:32 +0000 UTC
Build epoch: 1648380512
Build UUID: 27c4c4cd-8fdd-4f49-b731-48ee4a174275

no debayer choosed:
![grafik](https://user-images.githubusercontent.com/68758094/160280583-7a868dbd-1546-448f-8022-a1c0d9138f4b.png)

mono choosed:
![grafik](https://user-images.githubusercontent.com/68758094/160280623-6c331235-0960-43cc-b473-69a4615fcc50.png)

**Comment by heckflosse** [comment]
We need a raw file to reproduce the issue

**Comment by Reiner1959** [comment]
Where should I send this raw-file to?

trying to attach it here:
/home/reiner/Fotos/Fotos_2022/Strassburg_Maerz_2022/originale/L1000651.DNG

**Comment by Reiner1959** [comment]
Seems not work, it is not supported in github upload function
If you could please provide info where to upload. Thank you

regards 
Reiner

**Comment by heckflosse** [comment]
Upload it to filebin.net and post the link

**Comment by Reiner1959** [comment]
I have just discovered, that this issue is not present if using neutral profile.
Further investigation (disabling RT-modules step by step) shows, that it is caused from the module
distortion correction.

See screenshot:
![grafik](https://user-images.githubusercontent.com/68758094/160285434-37ce339c-76c1-4414-985c-be6294f8e97d.png)

**Comment by Thanatomanic** [comment]
But why are you disabling your demosaicer?

Edit: it does not surprise me at all to see heavy moire if your input consists of a very fine-grained dot pattern due to your individual RGGB pixels.

**Comment by Reiner1959** [comment]
Here is the link to the raw file and sidecard file
https://filebin.net/5vt6v6h0d4gmk0lz

**Comment by Reiner1959** [comment]
> But why are you disabling your demosaicer?
> 
> Edit: it does not surprise me at all to see heavy moire if your input consists of a very fine-grained dot pattern due to your individual RGGB pixels.

I was just experimenting a bit with RT, just to see if i could export the file as a non demosaic tiff
and process the file with other software. (hint: scale down the file later to get an effect like using superpixel of one RGGB)
This would reduce the megapixel count by 4 times of course.

And then I discovered this issue:-(
Module distortion correction seems to be involved in this, depending on the level of correction.

regards 
Reiner

**Comment by Thanatomanic** [comment]
Unfortunately, you want something that is impossible. Demosaicing is one of the first steps in raw processing. Everything else, including distortion correction, comes after that.
Distortion correction is impossible on mosaiced data, because after distorting the pixels, how would you know which pixels to combine into a proper RGB color pixel?

This is not bug.

**Comment by Reiner1959** [comment]
Hi,

Ok, if it is impossible to do, RT should give some hint about it
or shall disable the distortion correction if someone uses mono
or none demosaicing.

I discovered this only by coincidence, and other users might
discover this in the future again. It is not obvious for an user
what other modules could influence with that.


just letting you know, that this issue is also in RT 5.8.
So it it is not a new issue.


best regards
Reiner



Am 27.03.22 um 16:30 schrieb Thanatomanic:

**Comment by Thanatomanic** [comment]
I agree that it would be nicer if some (all?) tools would be disabled if somebody chooses Mono or None. Regardless, nobody should use those demosaicers unless for diagnostic purposes or if they know exactly what they're doing. The manual explains their specific use cases: http://rawpedia.rawtherapee.com/Demosaicing#Demosaicing_Methods
