### ISSUE TITLE
RT ignores part of lensfun database after value in calibration data

### ISSUE THREAD

**Issue by rebio** [Beep6581/RawTherapee#6463]
**Short description**
After a certain variable in the calibration data in the lensfun database, RT stops reading the entire file calibration file

**Steps to reproduce**
1. Open RT
2. Open the Editor
3. Go to the "Lens/Geometry" section "Automated Correction"
4. In the drop down menu for the lensfun data for the lens, check the folder for samyang
5. Search for Samyang lens calibration data that is stored in the **mil**-samyang.xml file

**Observed behavior**
RT seems to open the mil-samyang.xml (not slr-samyang.xml) and go through each lens one by one.
If some part of the file causes problems, the entire rest of the file is dropped

**Expected behavior**
It lists all the lenses.
If there is an error in the calibration data, RT tries to skip that (and only that) part (or skips the lens) and continues extracting the rest of the calibration data for other lenses.

**Bug description**
I spend a good amount of time to see what causes the issue. 
In the mil-samyang.xml file there is the "Samyang 7.5mm f/3.5 UMC Fish-eye MFT" lens. RT can read this lens' data.
Up next is the "Samyang 8mm f/2.8 UMC Fish-eye" lens. This lens is NOT included. Every lens that follows this lens is also not included.
The bug is caused by `<calibration>` -> `<distortion>` -> `real-focal="8.405"`
After `real-focal="8.405"` is removed, the database is read like you would expect. I have no idea what this entry does or if it should be even in there, but RT can not process it as it seems. instead of skipping calibration data for distortion (or maybe the lens) it can not read, it skips the entire file.
This variable also appears in other files (eg. slr-sigma.xml) but there it is used as `<real-focal-length focal="18" real-focal="18.14" />`. A lens that follows this entry appears in RT. I guess RT knows how to handle this variable, but does not in the place where it is in mil-samyang.xml.
I think it wouldn't be a bad thing if RT would just ignore variables that can not be matched to any other calibration data. A little log file would help to see if there are some more problems caused by the calibration data

**Additional information**
- RT version 3075
- Tested on Windows and on Linux. Both are effected

Other useful information:
- The problem originated here: https://github.com/lensfun/lensfun/discussions/1799
- See also: https://github.com/lensfun/lensfun/issues/1800

**Comment by Lawrence37** [comment]
All the lenses are listed for me:
![image](https://user-images.githubusercontent.com/45837045/164948613-9d362b3f-0501-468d-9433-2f5554e3a20c.png)

```
$ grep '<model>' *samyang.xml | sort
mil-samyang.xml:        <model>Samyang 12mm f/2.0 NCS CS</model>
mil-samyang.xml:        <model>Samyang 50mm f/1.4 AS UMC</model>
mil-samyang.xml:        <model>Samyang 7.5mm f/3.5 UMC Fish-eye MFT</model>
mil-samyang.xml:        <model>Samyang 8mm f/2.8 UMC Fish-eye</model>
mil-samyang.xml:        <model>SAMYANG AF 12mm F2.0</model>
mil-samyang.xml:        <model>SAMYANG AF 14mm F2.8</model>
mil-samyang.xml:        <model>SAMYANG AF 18mm F2.8</model>
mil-samyang.xml:        <model>SAMYANG AF 24mm F1.8</model>
mil-samyang.xml:        <model>SAMYANG AF 24mm F2.8</model>
mil-samyang.xml:        <model>Samyang AF 35mm f/2.8</model>
mil-samyang.xml:        <model>SAMYANG AF 45mm F1.8</model>
mil-samyang.xml:        <model>SAMYANG AF 85mm F1.4</model>
slr-samyang.xml:        <model>Samyang 10mm f/2.8 ED AS NCS CS</model>
slr-samyang.xml:        <model>Samyang 12mm f/2.8 Fish-Eye ED AS NCS</model>
slr-samyang.xml:        <model>Samyang 12mm f/3.1 VDSLR ED AS NCS Fish-eye</model>
slr-samyang.xml:        <model>Samyang 135mm f/2 ED UMC</model>
slr-samyang.xml:        <model>Samyang 14mm f/2.8 AE ED AS IF UMC</model>
slr-samyang.xml:        <model>Samyang 14mm f/2.8 AE ED AS IF UMC</model>
slr-samyang.xml:        <model>Samyang 16mm f/2.0 ED AS UMC CS</model>
slr-samyang.xml:        <model>Samyang 20mm f/1.8 ED AS UMC</model>
slr-samyang.xml:        <model>Samyang 35mm f/1.4 AS UMC</model>
slr-samyang.xml:        <model>Samyang 35mm f/1.4 AS UMC</model>
slr-samyang.xml:        <model>Samyang 35mm T1.5 Cine Lens</model>
slr-samyang.xml:        <model>Samyang 500mm f/6.3 MC IF Mirror Lens</model>
slr-samyang.xml:        <model>Samyang 85mm f/1.4 IF UMC Aspherical</model>
slr-samyang.xml:        <model>Samyang 8mm f/3.5 Fish-Eye CS</model>
slr-samyang.xml:        <model>Samyang T-S 24mm f/3.5 ED AS UMC</model>
```

Self-compiled `dev` version 5.8-3088 (5.8 works too). Lensfun version 0.3.3.

**Comment by rebio** [comment]
> Self-compiled `dev` version 5.8-3088 (5.8 works too). Lensfun version 0.3.3.
 
Lensfun 0.3.3 seems to be the not-problem here: The Samyang 8mm f/2.8 UMC Fish-eye lens has an entry with `<real-focal-length focal="8" real-focal="8.405"/>`

The tip of master (mil-samyang.xml in lensfun) says `<distortion model="ptlens" focal="8" a="0.02036" b="-0.08028" c="0.01446" real-focal="8.405"/>` which would cause the problem.
Could you test with this version?

This is how it looks to me with the tip of master: 
![RT mil-samyang at tip master](https://user-images.githubusercontent.com/10911084/164954015-a8211d66-642a-47bf-82ca-8355a15495a2.png)
 
Note that you can see some lenses, but all except one are from slr-samyang.xml. The highlighted. 7.5mm lens is the only one from mil-samyang, that is on the list

**Comment by Thanatomanic** [comment]
@rebio Notwithstanding general issues with handling lensfun, your reports are based on a false assumption. After the 0.3.3 release of lensfun, the database format was updated to "version 2". This is entirely unsupported by RawTherapee and has major issues (see e.g. https://github.com/darktable-org/darktable/issues/2813 and the related bug report upstream).

So, taking the xml's from the lensfun GitHub directly is _not_ possible. The correct update procedure is described here http://rawpedia.rawtherapee.com/Lens/Geometry#Lensfun and boils down to running `lensfun-update-data` and syncing that with the path in your RT `options` file

```
[Lensfun]
DBDirectory= ###
```

Either point that to the folder containing the updated `version_1` database, or copy over the updated files to whatever the folder is now.

I will close this issue for now, unless you find a similar problem with the right database files.
