### ISSUE TITLE
Change layout of some UI controls to improve workflow

### ISSUE THREAD

**Issue by peterfreeth** [Beep6581/RawTherapee#6489]
The workspace layout for RT is not optimised for image editing, and this is especially a problem on large monitors.

Having some buttons top left, some top right, the main controls on the left, some more buttons bottom right, more bottom left is a time consuming problem. For example, in order to copy a profile from one image to another and send that second image to the queue, I need to use the processing controls, then go top right to copy the profile, then top left to select a file tab, then top right to paste the profile, then bottom left to send the image to the queue. In all, this means moving the cursor 155cm. With a trackball, this is a lot of very unnecessary scrolling.

Ideally, all buttons should be in movable blocks like toolbars in GIMP. However, at the very least, buttons should be grouped together when they are part of the same workflow.

An alternative would be to assign keyboard shortcuts to the most commonly used functions, namely copy profile, paste profile, put to queue. It's surprising that these are not already in place.

Version: 5.8
Branch: releases
System: Linux

**Comment by TechXavAL** [comment]
There are already a ton of [keyboard shortcuts](https://rawpedia.rawtherapee.com/Keyboard_Shortcuts), many binded to UI buttons.

Processing profiles are a bit different, as clicking those buttons alone or at the same time as Ctrl key will give different results. Hover over the buttons to get a tooltip.

In spite of this, you can develop your image in the Editor and send it straight away to the Queue by just pressing **Ctrl+b**. And you can copy/paste profiles with the context menu in the File Browser (Ctrl+F2 to go to the File Browser and then right click over an image), and send them all at once to the queue with that same context menu.

An alternative to copy/paste profiles: just do Ctrl+c and Ctrl+v.

**Comment by peterfreeth** [comment]
That's very helpful, thank you.

In that case, some buttons show a keyboard shortcut in a tooltip, others don't so I think that needs to be consistent.

I think it would still be good to have movable toolbars.
