### ISSUE TITLE
Local adjustments "Exposure compensation" final output incorrect, preview OK

### ISSUE THREAD

**Issue by stativ** [Beep6581/RawTherapee#6493]
**Short description**
When using "Exposure compensation" function from the local adjustments, the final output sometimes have completely wrong colors, which seem inverted. The preview is however correct. The problem doesn't appear in all cases. So far it seems to happen mostly when I apply negative compensation to a bright sky.

Attached are the images showing the problem, a RAW file and a pp3 file. Please ignore the weird processing, I used a known broken profile from a different image that I do not want to share.

**Steps to reproduce**
1. Enable local adjustments
2. Add a new local adjustment spot
3. Add "Dynamic Range & Exposure" tool
4. Decrease the exposure.

**RAW file**
https://drive.google.com/file/d/11ZbTZIY190GXrIc0nnlwYkdfzEU9Rc5Z/view?usp=sharing

**PP3 file**
https://drive.google.com/file/d/1vBxXsxnkkYg-ANxmtD7l_nOW9JGjEw15/view?usp=sharing

**Preview is fine**
![rt-preview](https://user-images.githubusercontent.com/226064/171921298-0fb4176f-41de-44be-8b32-13e53e3085d1.jpg)

**Completely weird colors in the final export**
![rt-export](https://user-images.githubusercontent.com/226064/171921320-fdf1023a-a02c-42c0-ab2f-23bc4484fb05.jpg)

**Additional information**
Version: 5.8-3095-g68ec1a5bb
Branch: makepkg
Commit: 68ec1a5bb
Commit date: 2022-05-21
Compiler: cc 12.1.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.24.6
Lensfun: V0.3.3.0
Build type: Release
Build flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -flto=auto -std=c++11 -fno-tree-loop-vectorize  -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wno-attributes -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -flto=auto
OpenMP support: ON
MMAP support: ON
Build OS: Linux 5.17.4-arch1-1 x86_64
Build date: Tue, 31 May 2022 22:19:38 +0000 UTC
Build epoch: 1654035578
Build UUID: f65b8653-1939-4aec-ac55-1ec8a92e979d

**Comment by ghost** [comment]
I can reproduce this with the above provided RAW and sidecar, but I'm not able to reproduce it with another RAW (or this RAW and starting from scratch).

**Comment by stativ** [comment]
Interesting, I have tried it now too also without luck of reproducing it. It must have something to do with the Iocal adjustment setting though.
I have trimmed down the pp3 file to only the Local adjustment. When I apply this file on top of the "Neutral" profile to avoid any clashes with other tools, the bug still persists.

Trimmed file:
https://drive.google.com/file/d/1E01BK580gm8e_YGt4amH78Ns3EmckI3-/view?usp=sharing

**Comment by ghost** [comment]
A few things I noticed while checking out your trimmed sidecar:

* The following is shown in the terminal when exporting this file:

```
Premature end of JPEG file
JPEG datastream contains no image
```

* Any negative Exposure compensation value, even the smallest one (-0.01) will trigger this behaviour
* Vertically increasing/decreasing the rectangle spot increases/decreases the effected area

@stativ : Could this RAW be damaged? Do you have a safety copy or one in the same series by any chance and, if so, does it show this behaviour?

**Comment by stativ** [comment]
No, the RAW is fine for sure. It happens with RAW files from different days, and even with RAW files downloaded from the internet. You can try eg. this sample image from dpreview: https://www.dpreview.com/sample-galleries/9985983572/sony-a7r-iii-sample-photos/7733180033 – the issue occurs when using the previously posted pp3, too.

**Comment by ghost** [comment]
Oh, this is interesting: I just tested a bunch of different camera brands and specifically some Sony types. Except for one series, all of them are OK.

My limited tests show that the only camera types that shows this are **Sony ILCE-7RM** series cameras. Have tested the 7RM2, 7RM3 and 7RM4 and they all show this. The 7SM2 and 7M3 are OK, though.

**Comment by MJacal** [comment]
Just in case, it also happens on Windows 10 with 5.8-3095-g68ec1a5bb, also after some settings changed. On the other side, I was not able to trigger the glitch on a cr2 photo.

**Comment by Lawrence37** [comment]
This is the culprit.
https://github.com/Beep6581/RawTherapee/blob/68ec1a5bb50b496e255a0b843c36345fbeff2468/rtengine/iplocallab.cc#L5892

The cosine function gets stretched for large images. The float math is not precise enough, resulting in a divide by zero. `(1.f - cosx[j]) + (1.f - cosy[i])` will work, but double precision is necessary for even larger spots (width and height greater than ~12867 pixels) when `i` and `j` are small.

**Comment by Desmis** [comment]
@Lawrence37 
You are an amazing person, because finding this "error" of lack of precision in some cases in "float" is really remarkable
:)

jacques

**Comment by stativ** [comment]
@Lawrence37 Awesome that you found it so fast! I tried changing the variables in this computation to double and it indeed works!

**Comment by heckflosse** [comment]
Would it be also possible to change this line instead?
https://github.com/Beep6581/RawTherapee/blob/68ec1a5bb50b496e255a0b843c36345fbeff2468/rtengine/iplocallab.cc#L5846
to 
```
table[i] = 1.0 - std::cos(pi_size * i);
```

and then use
```
data[i * nx + j] *= m2 / (cosx[j] + cosy[i]);
```

This would avoid expensive double precision divisions...
