### ISSUE TITLE
another missing entries in default 

### ISSUE THREAD

**Issue by marter001** [Beep6581/RawTherapee#6504]
seems, i just found another missing entry in RT, but its a really minor issue:

I am working on Version Version: 5.8-3098-g404a584c7
Branch: dev
Commit: 404a584c7
Commit date: 2022-06-12
Compiler: cc 12.1.0
Processor: generic x86
System: Windows
Bit depth: 64 bits

When saving an already existing profile, of course its correct to be asked for confirmation, to overwrite the existing file.
in any language, the buttons offer "Yes" or "No"

I guess, the buttons "Yes" and "No", dont have any entry in default for a translation:

![missing entries in default](https://user-images.githubusercontent.com/78749513/174605610-b3bfd95a-2886-41ce-aa2a-705c48ba997b.jpg)

![missing entries in default_jp](https://user-images.githubusercontent.com/78749513/174605620-fd2b094d-4bf7-44ce-a656-a5c22cbd185a.jpg)

**Comment by Entropy512** [comment]
I'm hoping to finish up my pull request this evening (yeah, I know, I said that a week ago...), I'll take a look at this afterwards.

I'm wondering if button names are somehow coming from the graphics toolkit itself, or something else.

**Comment by Thanatomanic** [comment]
This is reported earlier in https://github.com/Beep6581/RawTherapee/issues/5243
