### ISSUE TITLE
Local Adjustments: []Inverse has no effect on full image spot

### ISSUE THREAD

**Issue by chaimav** [Beep6581/RawTherapee#6506]
Window 10, RawTherapee 5.8-3098 nightly

Issue: []Inverse checkbox incompatible with full image spots.

Recommendation: Disable []Inverse checkbox when full image spot is selected.

Background: I was trying to lighten everything but the sky in an image with the Dynamic Range & Exposure tool. I created a full image spot placed the sky (very easy to set the scope as it is relatively monotone) and tried using the []Inverse checkbox to set the effective scope on the the rest of the image. What I erroneously expected was that Inverse means affects everything out of scope. In reality, it means the same scope, but everything outside the _spot_.

**Comment by Desmis** [comment]
@chaimav 
this is totally normal, because the "inverse" mode applies outside the Spot. As in "full image" it covers the whole image, it is obvious that this has no effect

jacques

**Comment by chaimav** [comment]
'Obvious' is relative. Once I understood what inverse means, I was able to figure it out, my concern was that others may make the same mistake as I originally made. I have no idea how easy or hard it is to do, but to have the checkbox disabled when full image spots are used would be ideal.
Short of that, maybe update the tooltip?

**Comment by Desmis** [comment]
@chaimav 
I don't want to bother anyone, but my health is bad (unfortunately)

Regarding "inverse" and "full Image", solving this through the GUI is too complex for me. If nobody minds I would change the tooltip of "inverse" by adding a line

**If 'Full Image' is selected, 'inverse' has no effect.**

Or do you have another text to propose ?

jacques

**Comment by chaimav** [comment]
How about something more general and explanatory: 
"Inverse will enable this tool for the area outside the spot, while the area within the spot will remain unaffected by the tool"

**Comment by Desmis** [comment]
For me your text is good, no problem, I will pussh this change tomorrow.  Unless there is another proposal

jacques

**Comment by Desmis** [comment]
@chaimav 

Done, push in Dev

Jacques
