### ISSUE TITLE
Local Adjustments: Dynamic Range & Exposure hidden Gamma slider

### ISSUE THREAD

**Issue by chaimav** [Beep6581/RawTherapee#6507]
Windows 10, RawTherapee 5.8-3098 nightly

Toggling the []Inverse checkbox on the Dynamic Range & Exposure tool makes a Gamma slider appear.

Step 1: Add a spot and select Dynamic Range & Exposure tool.
![No gamma](https://user-images.githubusercontent.com/47765782/174877348-0f6c674a-8664-4504-9811-6d1a059463e8.jpg)

Step 2: Check and then uncheck []Inverse
![magic gamma](https://user-images.githubusercontent.com/47765782/174877398-e3c3c4ef-1244-4754-a71d-ac42f8c86de5.jpg)

**Comment by Desmis** [comment]
@chaimav 

Excuse me but I was in hospital...(still my very bad health)

"Gamma" should only appear in advanced mode (not in inverse), in others mode always hide 

I just push a change to DEV which must solve the problem mentioned

:)

Jacques

**Comment by chaimav** [comment]
Thanks for the fix. I hope your health improves.

**Comment by chaimav** [comment]
Confirmed fix works.
