### ISSUE TITLE
Missing language keys cleanup

### ISSUE THREAD

**Issue by Lawrence37** [Beep6581/RawTherapee#6516]
While reviewing #6466 for keys that are still in use, I found these keys which are referenced but not found.

Missing keys
- TP_BWMIX_AUTOCH_TIP: Missing tooltip in the Batch Edit panel: Color tab > Black-and-White > Chanel Mixer > Auto

Invalid (empty) keys
- https://github.com/Beep6581/RawTherapee/blob/0599a5e96d7547f8dc7095f7bf24d00182b05f86/rtgui/locallabtools2.cc#L7443
- https://github.com/Beep6581/RawTherapee/blob/0599a5e96d7547f8dc7095f7bf24d00182b05f86/rtgui/icmpanel.cc#L314-L316

Unused keys (referenced in the code, but never visible)
- HISTORY_MSG_867
- HISTORY_MSG_896
- HISTORY_MSG_976
- TP_LOCALLAB_SAVREST_TOOLTIP
- TP_LOCALLAB_COMPLEXMETHOD_TOOLTIP
- TP_LOCALLAB_GRADWAVFRA
- TP_LOCALLAB_EDGSHARPFRA
- TP_LOCALLAB_LOGCONTQ
- TP_LOCALLAB_LOGJZFRA
- HISTORY_MSG_ICMPREDX
- HISTORY_MSG_ICMPREDY
- HISTORY_MSG_ICMPGREX
- HISTORY_MSG_ICMPGREY
- HISTORY_MSG_ICMPBLUX
- HISTORY_MSG_ICMPBLUY
- HISTORY_MSG_LEVELSHC
- TP_WAVELET_DENEQUAL_TOOLTIP

Miscellaneous
- HISTORY_MSG_1197: https://github.com/Beep6581/RawTherapee/blob/0599a5e96d7547f8dc7095f7bf24d00182b05f86/rtgui/perspective.cc#L99

I obtained the above by inspecting this function.
https://github.com/Beep6581/RawTherapee/blob/0599a5e96d7547f8dc7095f7bf24d00182b05f86/rtgui/multilangmgr.cc#L207-L216

**Comment by Entropy512** [comment]
As a side note, I'm wondering if a post-5.9 task should be moving to something like gettext instead of the homegrown language handling system.  Among other things it would make moving to something like weblate or crowdin easier.

Family is gone now that the holiday in the US is over, will try and get back to #6466 tonight
