### ISSUE TITLE
L*a*b CC curve histogram scaled incorrectly

### ISSUE THREAD

**Issue by rebio** [Beep6581/RawTherapee#6519]
**Short description**
The vertical indicator line is in the wrong spot

**Steps to reproduce**
1. Create an image with the Gradient black to blue to white. Tested with tiff. Not allowed to upload it here.
![blue gradient](https://user-images.githubusercontent.com/10911084/177765534-0ac9d8c3-fc5f-4d8a-8bb5-6ff9094bbb79.jpg)
2. Open image and look at the vertical slider in any of the chromaticity based curve editors

**Observed behavior**
The vertical indicator line only goes from 0 to grid line 9 in the most saturated part.
![CC  curve max saturation](https://user-images.githubusercontent.com/10911084/177766716-9372c64b-161f-4eef-8c73-914b33526cfe.png)

**Expected behavior**
The vertical indicator line goes from 0 to 10 (assuming that the grid is 10% steps, left is 0% aka 0, right is 100% aka 10)
The image shows the most saturated part of the base image with `L*a*b` chroma at +12
![CC  curve max saturation with chroma +12](https://user-images.githubusercontent.com/10911084/177767294-66fed000-fccb-41d7-a25d-bcbf89a05b69.png)

**Additional information**
RawTherapee is on the latest dev build

According to the Navigator the values for saturation, blue channel of RGB as well as the b channel are maxed out. This can not be more saturated unless it displays information outside the colour space. Why would it though? The L curve has not 10% reserved for out areas out of the luminance range.

This is the "chroma drop". Numbers refer to grid lines.
![CC  curve chroma drop](https://user-images.githubusercontent.com/10911084/177767778-995a63bb-5983-44fc-b259-03a69e8a95d6.png)

Image with chroma drop at 9:
![default gradient with chroma drop at 9](https://user-images.githubusercontent.com/10911084/177768127-d4cc5798-b8e5-456f-9fb7-509f4532d066.jpg)

Image with `L*a*b` chroma +12 and chroma drop at 9:
![default gradient with with chroma +12 and chroma drop at 9](https://user-images.githubusercontent.com/10911084/177768220-e9f9d830-8eda-4c6a-9e11-2fb6b1a24864.jpg)

Image with `L*a*b` chroma +2 and chroma drop at 8:
The CC curve of this image is the one above. Even more parts of the image should be effected by the position of the vertical indicator, they are not.
![default gradient with with chroma +2 and chroma drop at 8](https://user-images.githubusercontent.com/10911084/177768480-925daf0c-6a71-4fa7-8b14-86ed03a25f63.jpg)

**Comment by Lawrence37** [comment]
Chroma is not saturation. There's no such thing as 100% chroma in CIELAB, so the choice of maximum chroma in the histogram is somewhat arbitrary.

**Comment by rebio** [comment]
Even if there is no 10/10 chroma, what about that the image with with L*a*b chroma +12 and chroma drop at 9?
The vertical line says the middle part (first image under Additional information) is in the area that should be effected yet it is not (see image under headline Image with `L*a*b` chroma +12 and chroma drop at 9)

**Comment by Lawrence37** [comment]
I see what you mean. Sorry, I misinterpreted the gradient images. The histogram and curve values are not aligned correctly.
