### ISSUE TITLE
Different slider/cursor behaviour on Windows and Linux

### ISSUE THREAD

**Issue by rebio** [Beep6581/RawTherapee#6521]
**Short description**
The same action does different things on Windows and Linux

**Steps to reproduce**
1. Open RawTherapee
2. Open an Image
3. Adjust the image to your linking using any tool slider aka "use the software"

**Observed behavior**
Windows:
- Left click: Slider position jumps to cursor
- Mouse wheel click: Slider position moves slightly toward the cursor position

Linux:
- Left click: Slider position moves slightly toward the cursor position
- Mouse wheel click: Slider position jumps to cursor

**Expected behavior**
Works the same on both OS

**Additional information**
Latest version of RT was used (3101)

**Comment by Benitoite** [comment]
Please give some basic information, for instance the exact version numbers of your operating system, and specific information about expected behavior.
http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports

**Comment by rebio** [comment]
Windows:
Windows 10 with latest updates

Linux:
Operating System: KDE neon 5.25
KDE Plasma Version: 5.25.2
KDE Frameworks Version: 5.95.0
Qt Version: 5.15.5
Kernel Version: 5.13.0-52-generic (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 4800H with Radeon Graphics
Memory: 30.8 GiB of RAM
Graphics Processor: AMD RENOIR
Manufacturer: Micro-Star International Co., Ltd.
Product Name: Bravo 17 A4DDR
System Version: REV:1.0

Expected behavior
Works the same on both OS = Works on Linux and Windows like it does now on Windows or on Linux. Left click and middle click do the same on both OS. No preferred  default

**Comment by Benitoite** [comment]
And do you have any local `settings.ini` file with `gtk-primary-button-warps-slider` on either system set to true or false?

**Comment by rebio** [comment]
I checked 
- /home/USER/.var/app/com.rawtherapee.RawTherapee/
- /var/lib/flatpak/app/com.rawtherapee.RawTherapee/current/active/

and

- /home/USER/.config/RawTherapee5-dev-AppImage/

for the AppImage dev snapshot.

I could not find any  settings.ini file or a gtk-primary-button-warps-slider setting. Since I have never heard of it, it's very unlikely that I changed it.

**Comment by rebio** [comment]
Shift + Click on a slider does the same as middle click on Linux (the slider jumps to the position you clicked on)

**Comment by mikkovedru** [comment]
I am using:
- Linux Mint 20.3 Cinnamon
- the latest build (5.8-3128)

In my Linux system, the behavior is exactly like you describe for Windows (Left click: Slider position jumps to cursor; Mouse wheel click: Slider position moves slightly toward the cursor position).

I can't test it in Windows.

**Comment by rebio** [comment]
As the program works the same on both operating systems (Linux and Windows) now (left-click is _move value here_,  middle-click is _move value one step to here_) I will close the issue.
