### ISSUE TITLE
AppImage: White outlines and layers in UI

### ISSUE THREAD

**Issue by rebio** [Beep6581/RawTherapee#6526]
**Short description**
UI elements in the **AppImage** have a white outline/layer to it

**Steps to reproduce**
1. Open the AppImage
2. Check the UI (eg. Editor)

**Observed behavior**
White outlines layers as shown in the image
![editor slider](https://user-images.githubusercontent.com/10911084/179371417-bfb99b1e-2ff2-4452-8182-ea260dc37cc5.png)
![editor save image](https://user-images.githubusercontent.com/10911084/179371426-0a24f0b8-d7af-4538-b367-dc098790fcc4.png)

**Expected behavior**
Same UI theme as in 5.9 with no white outline

**Additional information**
Issue was observed in KDE neon, but was also observed with a live Ubuntu 22.04

Already noted by Lawrence37 in the 5.9 thread.
> > I prefer builds from an automated source
> 
> The automated builds for Windows and Linux AppImages will also build releases. If you plan on using them, verify the quality first. I have encountered issues such as weird crashes on the Windows version and **white outlines with the default theme on the AppImage**.

I did not find a bug report for this.

My guess that this is a bug and not a style change is based on that the AppImage didn't have that issue in the past. It has changed with some update between April and June around when the new system for automated updates got in place.
The same dev version on Windows (from ZIP) does not show this behaviour

Only the RT and RT legacy profiles are effected. None of the TooWaGrey profiles show this behaviour.

**Comment by Benitoite** [comment]
Do you know which commit caused this change?

**Comment by rebio** [comment]
No. I used the AppImage for some time and after I downloaded a new version and saw the change.

IIRC it was after the night builds broke and were moved from https://github.com/Beep6581/RawTherapee/releases/tag/nightly to https://github.com/Beep6581/RawTherapee/releases/tag/nightly-github-actions

**Comment by Thanatomanic** [comment]
I can also confirm this, running the current nightly AppImage in a VM of Kubuntu 22.04. I happened to have an earlier AppImage available that does not exhibit the issue: `RawTherapee_dev_5.8-2856-g3cb6e88_20210512.AppImage` (so, from some time ago... but I cannot find the specific commit)

I'll see if I can find anything to explain this.

**Comment by Lawrence37** [comment]
@Thanatomanic That AppImage is from the old automated builds. There's something missing from either the new AppImages or the theme CSS.

**Comment by Thanatomanic** [comment]
The CSS files are identical between the two AppImages. The next logical thing would be to assume one of the GTK+ related components has an incompatibility. One thing that I notice is the use of the "GTK plugin for linuxdeploy". Perhaps this messes around with some GTK defaults?

And for reference, building RT myself on Ubuntu 18.04 LTS does not give the white outlines. So it's not directly related to the available packages on 18.04.

**Comment by Thanatomanic** [comment]
I am afraid the patch in #6555 did not solve the issue. At least, not on my VM with Kubuntu 22.04. Edit: this AppImage is freshly run from GitHub Actions a few minutes ago.

![image](https://user-images.githubusercontent.com/6567747/186069697-d62150d2-6a35-4961-8a68-c9d5f5edf74d.png)

**Comment by Lawrence37** [comment]
@Thanatomanic Could you use the GTK inspector (Visual tab) to check what theme is used? If it's greyed out and the tooltip says the theme is explicitly set with GTK_THEME, then I'll need to check why it is still like that. Otherwise, we'll need to look elsewhere, such as fixing the theme CSS.

**Comment by Thanatomanic** [comment]
Very quickly before I need to head off to work:

Starting the AppImage gives me
```
Gtk-Message: 07:01:45.531: Failed to load module "window-decorations-gtk-module"
Gtk-Message: 07:01:45.532: Failed to load module "colorreload-gtk-module"
```

The inspector tells me the following:
![image](https://user-images.githubusercontent.com/6567747/186074118-766ce537-85ad-48e0-b57f-11dfcddc5f7c.png)
