### ISSUE TITLE
Duplicated information in Exif and unable to remove

### ISSUE THREAD

**Issue by wsyxbcl** [Beep6581/RawTherapee#6528]
**Short description**  

When editing RAW file generated by Sony camera, there are duplicated tags in the Exif, which may have nothing to do Rawtherapee. However, Rawtherapee can not remove certain tag, the output file will still contain the tag and you'll find the tag been toggled on when revisiting the editor.

**Steps to reproduce**
For example, if we want to remove the model tag in Exif, 
1. Go to the Metadata tab in editor
2. (Notice that there are  two parts containing duplicated tags) Select the 2 `Model` tags and click `remove`
3. Export the image and you'll find model information still in exif
4. Switch to any other photo and come back you'll find the second `Model` tag is been toggled on again

**Additional information**
```
Version: 5.8-3090-gb989c271d
Branch: dev
Commit: b989c271d
Commit date: 2022-04-18
Compiler: cc 11.2.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.24.5
Lensfun: V0.3.3.0
Build type: release
Build flags:  -std=c++11 -fno-tree-loop-vectorize -march=native -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wno-attributes -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON
Build OS: Linux 5.17.4-arch1-1 x86_64
Build date: Tue, 26 Apr 2022 04:33:13 +0000 UTC
Build epoch: 1650947593
Build UUID: 2ef8d15c-e043-4d39-ae62-91d841141565
```

**Attachment**

Here is a image showing the duplicated tags

![Screenshot from 2022-07-20 21-58-57](https://user-images.githubusercontent.com/13074950/180001075-cc5b1995-94c6-43d7-9d24-b87fae3c93fd.png)

and a raw file for reproduction

[_DSC4431.zip](https://github.com/Beep6581/RawTherapee/files/9150438/_DSC4431.zip)

**Comment by wsyxbcl** [comment]
It seems that the remove function in metadata tab doesn't work at all

**Comment by ChasingShadows** [comment]
Please try again, with the following setting
![image](https://user-images.githubusercontent.com/55600750/185784677-51d393d7-0e72-4bce-bce8-f1e2261ab8f2.png)

**Comment by wsyxbcl** [comment]
> Please try again, with the following setting ![image](https://user-images.githubusercontent.com/55600750/185784677-51d393d7-0e72-4bce-bce8-f1e2261ab8f2.png)

Yes that's correct, I didn't notice the option. Thank you @ChasingShadows.
