### ISSUE TITLE
A change to “Camera Standard” and then back to “Auto-matched” will leave the options greyed out again.

### ISSUE THREAD

**Issue by KarlMagnusLarsson** [Beep6581/RawTherapee#6533]
**Short description**

In current RT dev git repo starting with ‘Color tab’ | ‘Auto-matched profile’ selected having DCP ‘base table’ as an active option and then selecting ‘camera standard’ will leave DCP options grayed out and inactive, even when going back to ‘Auto-matched profile’. This happens despite the fact that the camera has a ‘base table’. Selecting a new picture and going back will make DCP options possible to select again. (My case Canon 5D mk IV camera).

I have bisected this issue described by @nosle  and in this thread (above) and it points to commit `37080e1b5` https://github.com/Beep6581/RawTherapee/commit/37080e1b5d12a4e128d73c7011ef6e97f8df1ec7

The discussion is here: https://discuss.pixls.us/t/input-profile-checkboxes-greyed-out-in-recent-rt/31808

**Steps to reproduce**

1. Open raw file for camera with DCP 'base table' (like Canon 5D mk IV)
2.  ‘Color tab’ |shows 'DCP base table' active and possible to select.
3. Select DCP 'camera standard'
4. Go back and select  ‘Auto-matched profile' 
5. DCP options are grayed out.

**Expected behavior**

The DCP options should go back to what they were before 'camera standard' was selected.

'Auto-matched profile'  selected (default in  ‘Bundled profiles’ → ‘Auto matched curve ISO low’): 
![Screenshot from 2022-07-23 23-11-03](https://user-images.githubusercontent.com/42386052/180624661-0bb70e54-b77f-42bc-b5af-f1d010101863.png)

Selecting 'camera standard' and then back to 'Auto-matched camera profile' will make DCP options grayed out in GUI until selecting another raw file and going back.
![Screenshot from 2022-07-23 23-15-10](https://user-images.githubusercontent.com/42386052/180624667-f9a854db-90a6-4fd6-b0a7-290139593940.png)

**Additional information**

This is what `git bisect` showed:

```
git bisect good

37080e1b5d12a4e128d73c7011ef6e97f8df1ec7 is the first bad commit
commit 37080e1b5d12a4e128d73c7011ef6e97f8df1ec7
Author: Lawrence37 <45837045+Lawrence37@users.noreply.github.com>
Date:   Fri May 13 20:39:31 2022 -0700

    Fix some history messages (#6474)
    
    Use correct key for spot removal history message.
    
    Remove B&W channel mixer auto enabled message when changing the filter
    color.
    
    Replace hard-coded input color profile strings.

 rtgui/blackwhite.cc |  1 -
 rtgui/icmpanel.cc   | 12 ++++++------
 rtgui/spot.cc       |  4 ++--
 3 files changed, 8 insertions(+), 9 deletions(-)
```
The commit before this works: feada4cd0

**Comment by Lawrence37** [comment]
@KarlMagnusLarsson Thanks for bisecting.
