### ISSUE TITLE
Gdk-ERROR **: 09:39:38.735: The program 'rawtherapee' received an X Window System error.

### ISSUE THREAD

**Issue by hsqaihkl** [Beep6581/RawTherapee#6535]
Hi,I run this code in ubuntu 20.04 with vscode and cmake.Follow the Linux guide to manual compile.Bur when I debug it I met this error:

ERROR: Open the file“${DATADIR}/images/node-move-y-hicontrast.svg”failed：no this file or directory
ERROR: Open the file“${DATADIR}/images/rotate-aroundnode-hicontrast.svg”failed：no this file or directory
ERROR: Open the file“${DATADIR}/images/gears.svg”failed：no this file or directory

(rawtherapee:5215): Gdk-ERROR **: 09:39:38.735: The program 'rawtherapee' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadMatch (invalid parameter attributes)'.
  (Details: serial 242 error_code 8 request_code 139 (RENDER) minor_code 27)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)c

**Comment by Lawrence37** [comment]
Did you use the exact steps in RawPedia to compile? If not, what modifications did you use?

**Comment by hsqaihkl** [comment]
I haved modified ,Thanks!
