### ISSUE TITLE
Speed up compilation for release builds with GCC 12.1

### ISSUE THREAD

**Issue by Lawrence37** [Beep6581/RawTherapee#6548]
After upgrading GCC to 12.1, the compile time for release builds increased. `rtengine/procparams.cc` is responsible for a significant percentage of the build time. The difference is quite dramatic and can be seen in the automated Windows builds.

Here's an example using two consecutive `dev` builds.
GCC 11.3: https://github.com/Beep6581/RawTherapee/runs/6540668974
- Release: 12m 54s
- Debug: 11m 39s

GCC 12.1: https://github.com/Beep6581/RawTherapee/runs/6834837161
- Release: 21m 40s
- Debug: 11m 19s

We could probably speed up the build by disabling some optimizations for `rtengine/procparams.cc` or splitting it into multiple files. Thoughts?

**Comment by Thanatomanic** [comment]
I had noticed the long compilation times as well, but have no idea how to improve. Is it feasible to not optimize the compilation of a single file?

**Comment by Lawrence37** [comment]
It looks straightforward to add compiler flags to a single file in CMake (https://stackoverflow.com/a/13639476). The last flag wins in case of any contradicting flags, so adding a `-O0` overrides the `-O3` CMake uses for release builds.

**Comment by Floessie** [comment]
I can't see the translation unit times from the runs given above nor the compile flags, but in my experience LTO gets more and more sophisticated with every GCC version and thus takes longer and longer. Even if that's not the case here, we should maybe think about this:

```patch
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 0a55ca6d5..2a517fe00 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -549,7 +549,7 @@ if(WITH_LTO)
 
     set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -flto")
     set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -flto")
-    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -flto")
+    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -flto=auto")
 endif()
 
 if(WITH_SAN)
```

HTH,
Flössie

**Comment by Thanatomanic** [comment]
In my normal builds I don't use our `WITH_LTO` flag, neither does the Windows job here on GitHub, so that will not be the cause of the slowdown, right?

**Comment by Lawrence37** [comment]
@Floessie The reason why I know `procparams.cc` is taking a long time is because several times, I have encountered a build that seemingly paused. When I checked the running processes, I saw GCC processing that file for quite some time.

**Comment by Floessie** [comment]
@Lawrence37 Thanks for the hint. :+1: 

I dug a bit into the topic and found out, that `-ftree-pta` at `-O2` and `-O3` is the culprit. Compiling `procparams.cc` alone with GCC 12 takes about 10 times longer here at `-O3` and about 14 times longer at `-O2` than GCC 11 at `-O3`. Using `-ftime-report` shows that most of the time is spent with "tree PTA". Adding `-fno-tree-pta` gets the compile times down to normal.

IMHO that's a GCC regression we should report. Anyone up for this? @heckflosse and I have already done this. A novice maybe? :stuck_out_tongue_winking_eye:

How to reproduce
---

1. Do a normal CMake/make build.
2. Wait until `procparams.cc` is processed.
3. Run `ps  aux | less` in another terminal and search for `procparams`.
4. Copy the long line starting with `/usr/bin/c++` and ending with `-c .../rtengine/procparams.cc`
5. In your build directory `cd` to `rtengine`.
6. Paste the line and run it. Now you can modify the flags to your liking.

HTH,
Flössie

**Comment by Lawrence37** [comment]
Thanks @Floessie. I tried adding `set_source_files_properties(procparams.cc PROPERTIES COMPILE_FLAGS -fno-tree-pta)` to `rtengine/CMakeLists.txt` and it compiles much faster now.

**Comment by Floessie** [comment]
@Lawrence37 Would you mind to push your change? I'm building RT on QEMU emulated foreign architectures, and this takes ages with GCC 12...

**Comment by ValZapod** [comment]
> -fno-tree-pta

Does this give any cool acceleration for that file?

**Comment by Lawrence37** [comment]
@Floessie I have pushed the change to https://github.com/Lawrence37/RawTherapee/tree/procparams-compile-flags.

@ValZapod I'm not exactly sure what you are asking, but that flag means it won't enable that specific optimization. Who knows if the long compilation time is a bug. :man_shrugging:

**Comment by Thanatomanic** [comment]
@Lawrence37 I think it would be helpful if you could push this particular change to the dev branch as well. It saves a lot of time, e.g. when bisecting an issue.

**Comment by Lawrence37** [comment]
@Thanatomanic Coincidentally I was working on proper patch for this but didn't have time to finish it until now. I will push the commit to `dev` soon.

**Comment by ValZapod** [comment]
Still, this is a bug in gcc.

**Comment by Thanatomanic** [comment]
@ValZapod Well, it's not generating incorrect results, so I wouldn't call it a bug. It may simply be that gcc tries too hard to optimize for very little benefit. This behavior is much worse in 12.0 for sure... but it's also easy to work around.
