### ISSUE TITLE
Canon EOS 1000D White Point Regression

### ISSUE THREAD

**Issue by Lawrence37** [Beep6581/RawTherapee#6559]
From https://discuss.pixls.us/t/auto-matched-tone-curve-in-rawtherapee-dev-release-5-8-3126-appimage-on-linux-mint/32309

One of the recent commits must have made the white point incorrect. 5.8-3120 was fine, but 5.8-3124 shows the problem. #6505 is a good starting point to check.

I downloaded a picture from the RPU at https://raw.pixls.us/getfile.php/1616/nice/Canon%20-%20EOS%201000D%20-%20RAW%20(3:2).CR2. The neutral photo is 4x-5x darker in the current dev version.
| 5.8-3119 | 5.8-3128 |
|-|-|
| ![image](https://user-images.githubusercontent.com/45837045/186340860-fc6d6d97-513c-4876-a988-4d9b061c9823.png) | ![image](https://user-images.githubusercontent.com/45837045/186341095-bb1347af-5578-40a3-b2d9-aa6b7a736494.png) |

**Comment by Thanatomanic** [comment]
Agreed that #6505 would be the only reasonable cause of this change. It was a proposed fix by @heckflosse in collaboration with @agriggio. We should check whether ART has had some later changes to this code. Otherwise, we should at least revert back the changes until we find a proper solution.

**Comment by Thanatomanic** [comment]
Did a quick check with ART code and could not find differences. ART itself renders the file as 5.8-3128, so also presumably incorrectly.

**Comment by apostel338** [comment]
Do you have an ART newer than 1.15-52? This version seems correct to me.

![grafik](https://user-images.githubusercontent.com/96216629/186354057-eb0b0def-a203-40be-b2c0-071d7573fcf6.png)

**Comment by Lawrence37** [comment]
@apostel338 I see the same problem with ART 1.16.1, although I think ART uses LibRaw now.

**Comment by apostel338** [comment]
With 1.16.1 I still can't reproduce in ART. Out of curiosity I installed Tumbleweed in a VM to see if it's an OS oddity. All my ARTs render the 1000D photos correctly.
