### ISSUE TITLE
choice 'yes' and 'no' untranslated?

### ISSUE THREAD

**Issue by marter001** [Beep6581/RawTherapee#6564]
The  choice of 'yes' and 'no' for overwriting a file is not being translated.

Does this depend of the system (Windows 10, german), is sth missing in default-file, or may be is it hardcoded?

![grafik](https://user-images.githubusercontent.com/78749513/186844486-efa9aa15-3752-4ace-95f2-54710fe64d98.png)

**Comment by Thanatomanic** [comment]
Please see https://github.com/Beep6581/RawTherapee/issues/5243

**Comment by marter001** [comment]
oh, i missed that....

**Comment by Thanatomanic** [comment]
I even think you reported exactly the same before in https://github.com/Beep6581/RawTherapee/issues/6564 😉

**Comment by marter001** [comment]
hmmm.. i am getting old....
