### ISSUE TITLE
macOS 10.15 automated build needs upgrade (to work with GitHub Actions)

### ISSUE THREAD

**Issue by Thanatomanic** [Beep6581/RawTherapee#6566]
@Benitoite Can you take a look at this? I got this just now. It refers to https://github.com/actions/runner-images/issues/5583 for more information.

![image](https://user-images.githubusercontent.com/6567747/186962280-b30352e6-2dfb-4e4b-bfbe-5f70d695c696.png)

**Comment by Benitoite** [comment]
PR #6613 Upped to macos-11 from OSX 10.15
