### ISSUE TITLE
RT crash (SIGABRT) during export on MacOS 12.5.1 arm64 (RT 5.8 dev)

### ISSUE THREAD

**Issue by nomar500** [Beep6581/RawTherapee#6572]
I was exporting files (from raw to jpg) and RT gave up and crashed in the middle of a queue.

The terminal says:

```
Pango:ERROR:../pango/itemize.c:955:itemize_state_process_run: assertion failed: (state->run_end != state->run_start)
Bail out! Pango:ERROR:../pango/itemize.c:955:itemize_state_process_run: assertion failed: (state->run_end != state->run_start)
zsh: abort      build/Release/MacOS/rawtherapee
```

The build is: 
```
Version: 5.8-3133-gdfede0531
Branch: dev
Commit: dfede0531
Commit date: 2022-08-26
Compiler: clang 13.1.6.13160021
Processor: arm
System: Apple
Bit depth: 64 bits
Gtkmm: V3.24.6
Lensfun: V0.3.3.0
Build type: Release
Build flags:  -std=c++11 -mcpu=native -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wno-attributes -mmacosx-version-min=12.5 -flto -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -Xclang -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags:  -mcpu=native -Wl,-headerpad_max_install_names -mtune=generic -framework Foundation -flto
OpenMP support: ON
MMAP support: ON
Build OS: Darwin 21.6.0 arm64
Build date: Fri, 26 Aug 2022 21:00:45 +0000 UTC
Build epoch: 1661547645
Build UUID: 62a6f939-dca0-4457-a038-acdd4a67755c
```

The MacOS problem report is here: https://paste.sh/vx9RN0FY#pW7xBrSzEldZGYZ4v0oCna0R

Is there anything that stands out, that could have stemmed from the compilation?

Thanks.

**Comment by Lawrence37** [comment]
It's hard to tell without detailed crash information from a debug build. The problem could be in one of the libraries or with how RawTherapee is using them.

**Comment by Benitoite** [comment]
Please include AboutThisBuild.txt with your report, so we may judge the compilation effort.

**Comment by nomar500** [comment]
@Benitoite, I have included it in my original post, have I not?
It's in the _text_ of the report, not at the paste.sh link.

**Comment by Benitoite** [comment]
Thanks, I didn't notice it... Is this a one-timer, or do you regularly encounter this with a specific RAW?

**Comment by nomar500** [comment]
This was a one-timer; but then, I haven't been exporting batches recently.
Can't reproduce right now.
