### ISSUE TITLE
Single tiled deflate compressed DNGs not decoded properly

### ISSUE THREAD

**Issue by SimonSegerblomRex** [Beep6581/RawTherapee#6575]
**Short description**

I just tried opening a DNG using deflate compression with only one tile. If fails miserably since `tile_length` is set to INT_MAX before reaching this if statement:
https://github.com/Beep6581/RawTherapee/blob/2ce5b827c5fa39b2b5425303f79f28b78f3df4f4/rtengine/dcraw.cc#L10906

**Steps to reproduce**
1. Open the [attached DNG](https://github.com/Beep6581/RawTherapee/files/9490364/float32deflate.zip) (with the latest commit on dev)
3. Notice how you only get an image containing zeros since (since `tile_offset`, `tile_length`, and `tile_width` are messed up)

This is were things get messed up:
https://github.com/Beep6581/RawTherapee/blob/2ce5b827c5fa39b2b5425303f79f28b78f3df4f4/rtengine/dcraw.cc#L6551-L6554

Followed by:
https://github.com/Beep6581/RawTherapee/blob/2ce5b827c5fa39b2b5425303f79f28b78f3df4f4/rtengine/dcraw.cc#L7065-L7066

**Expected behavior**

The [attached image](https://github.com/Beep6581/RawTherapee/files/9490364/float32deflate.zip) should be decoded properly.

**Additional information**
Version: 5.8-3139-g2ce5b827c
Branch: dev
Commit: 2ce5b827c
Commit date: 2022-08-30
Compiler: cc 10.2.1
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.24.2
Lensfun: V0.3.2.0
Build type: release
Build flags:  -std=c++11 -march=native -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wno-attributes -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON
Build OS: Linux 5.10.0-16-amd64 x86_64
Build date: Mon, 05 Sep 2022 09:39:15 +0000 UTC
Build epoch: 1662370755
Build UUID:

**Comment by ValZapod** [comment]
@Entropy512 Fork ART decodes https://github.com/Beep6581/RawTherapee/files/9490364/float32deflate.zip normally.

**Comment by Beep6581** [comment]
Which cameras and software produce deflate-compressed DNGs?

**Comment by SimonSegerblomRex** [comment]
> Which cameras and software produce deflate-compressed DNGs?

I haven't come across any deflate compressed DNGs in the wild. This issue was just something I noticed when playing with the different options in the DNG specification. `dcraw.cc` is fragile, so we need to be really careful changing anything in there.

**Comment by kmilos** [comment]
> Which cameras and software produce deflate-compressed DNGs?

For example [HDRMerge](https://github.com/jcelaya/hdrmerge) produces 16/24/32-bit float deflate compressed DNGs. Not sure what it does re striping/tiling...

> I haven't come across any deflate compressed DNGs in the wild.

There are HDRMerge samples on https://raw.pixls.us/
