### ISSUE TITLE
MacOS keyboard shortcuts involving numbers are partly broken or shifted

### ISSUE THREAD

**Issue by nomar500** [Beep6581/RawTherapee#6577]
Some keyboard shortcuts appear to be broken on my MacOS (12.5) build of RT (dev branch 5.9)

- In the _File Browser_, pressing the `1` key does nothing, apparently - it should toggle highlight of 1-star images
- Pressing the `2`key does what's expected of the `1` key.
- In the _Editor_, the `1` key does what the `9` key is supposed to do (switch the background colour)
- The `shift+ctrl+number` shortcuts for colour labels don't seem to work either. 
- Note: changing the keyboard layout does not seem to fix this.

Sorry, I don't have a debug build handy :( 

```
Version: 5.8-3139-g2ce5b827c
Branch: dev
Commit: 2ce5b827c
Commit date: 2022-08-30
Compiler: clang 13.1.6.13160021
Processor: arm
System: Apple
Bit depth: 64 bits
Gtkmm: V3.24.6
Lensfun: V0.3.3.0
Build type: Release
Build flags:  -std=c++11 -mcpu=native -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wno-attributes -mmacosx-version-min=12.5 -flto -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -Xclang -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags:  -mcpu=native -Wl,-headerpad_max_install_names -mtune=generic -framework Foundation -flto
OpenMP support: ON
MMAP support: ON
Build OS: Darwin 21.6.0 arm64
Build date: Tue, 30 Aug 2022 19:48:45 +0000 UTC
Build epoch: 1661888925
Build UUID: 720b80b1-d6bc-423f-b33b-1c50b91d10b6
```

**Comment by Thanatomanic** [comment]
Hi, can you also check this thread and see if it overlaps/adds to your report?
https://github.com/Beep6581/RawTherapee/issues/3510

**Comment by nomar500** [comment]
Hi @Thanatomanic 
sorry for not responding earlier. My report indeed only addresses a fraction of what's discussed, there.
