### ISSUE TITLE
shrunken workspace in Mac OS 12.5.1 Monterey

### ISSUE THREAD

**Issue by sunolen** [Beep6581/RawTherapee#6578]
Rawtherapee version 5.8 Mac Universal downloaded from https://discuss.pixls.us/t/direct-download-links-to-the-latest-rawtherapee-development-version/29806. Running on a Macbook Pro with an M1 chip.

The screen looks like this upon opening on my laptop screen:

<img width="1506" alt="Screen Shot 2022-09-12 at 9 50 47 AM" src="https://user-images.githubusercontent.com/113376003/189712678-3c620430-8c86-4c6d-9b84-7ef4ebd9281d.png">

I can't resize the workspace, which is too small to work with. When I adjust the origins file's GUI section by changing the WindowWidth and WindowHeight, it has no effect.

The options file contains this GUI section:
[GUI]
Favorites=
WindowWidth=1487
WindowHeight=824
WindowX=0
WindowY=38
WindowMonitor=0
MeowMonitor=-1
MeowFullScreen=false
MeowMaximized=true
MeowWidth=2560
MeowHeight=1440
MeowX=0
MeowY=0
WindowMaximized=true
DetailWindowWidth=-1
DetailWindowHeight=-1
DirBrowserWidth=260
DirBrowserHeight=350
SortType=0
PreferencesWidth=800
PreferencesHeight=600
SaveAsDialogWidth=920
SaveAsDialogHeight=680
ToolPanelWidth=400
BrowserToolPanelWidth=465
BrowserToolPanelHeight=421
BrowserToolPanelOpened=true
EditorFilmStripOpened=true
BrowserDirPanelOpened=true
HistoryPanelWidth=330
FontFamily=Helvetica Regular
FontSize=10
CPFontFamily=Helvetica Regular
CPFontSize=8
PseudoHiDPISupport=false
LastPreviewScale=5
LastShowAllExif=false
PanAccelFactor=5
RememberZoomAndPan=true
LastCropSize=1
ShowHistory=true
ShowFilePanelState=0
ShowInfo=true
MainNBVertical=true
ShowClippedHighlights=false
ShowClippedShadows=false
FrameColor=0
ProcessingQueueEnbled=false
ToolPanelsExpanded=
ToolPanelsExpandedAutoSave=true
MultiDisplayMode=0
CutOverlayBrush=0;0;0;0.66700000000000004;
NavGuideBrush=1;0;0;1;
HistogramPosition=1
HistogramRed=true
HistogramGreen=true
HistogramBlue=true
HistogramLuma=false
HistogramChroma=false
HistogramRAW=false
HistogramBar=true
HistogramHeight=200
HistogramDrawMode=0
NavigatorRGBUnit=0
NavigatorHSVUnit=0
ShowFilmStripToolBar=false
FileBrowserToolbarSingleRow=false
HideTPVScrollbar=false
HistogramWorking=false
CurveBBoxPosition=1

**Comment by Thanatomanic** [comment]
I've been following the thread on Pixls. There was a report that this was not a bug with RT, but a setting in macOS you needed to change. Or, that you should try the high dpi mode of RT. 
Have you tried both?

Otherwise, ping @Benitoite for some possible insight

**Comment by sunolen** [comment]
Thanks. What setting on mac and where is the high dpi mode switch for RT - in the config file? It's clearly an issue of how RT plays with the hi-res display on my macbook pro.

Right now my workaround is to use RT on my monitor instead of on the laptop display. This is my usual mode, but I was on the road so was using my laptop when I ran into the problem.

**Comment by Lawrence37** [comment]
Preferences > General, then enable pseudo HiDPI mode.
https://rawpedia.rawtherapee.com/Preferences#Appearance

**Comment by Benitoite** [comment]
FAQ added to bottom of [rawpedia](http://rawpedia.rawtherapee.com/MacOS) compilation page.

**Comment by Beep6581** [comment]
Closing as no response from OP.
