### ISSUE TITLE
Possible bug with libpng16-16.dll with msys2

### ISSUE THREAD

**Issue by Desmis** [Beep6581/RawTherapee#6594]
Hello
I am very careful because my computer is very old, overheats and often crashes. I expect the delivery of a new computer in the coming days.
I  update msys2 
$ pacman -Syu

The compilation goes without problem, but when I want to run Rawtherapee I get the following message:

"Le point d'entrée de procédure inflateReset2 est introuvable dans la bibliothèque de liens dynamiques C:\msys64\mingw64\bin\libpng16-16.dll"
When I execute Cmake:
for libpng ==> libpng.dlll.a (found version 1.6.38)

When I download the latest version of nighty-builds, and run, all works well... (version 5.8-3161-g93aac4510)

Is this a Msys2 problem, or related to my computer and is there a way to solve this problem ?

Reminder, I have a very poor command of these things (Msys2, mingw64, etc.) which for me are Chinese...

Thank you

Jacques

**Comment by Thanatomanic** [comment]
Bonsoir Jacques, it might happen that MSYS2 updates introduce incompatible versions. However, I just updated and recompiled RawTherapee and the software starts without problem. So... I am not really sure what happened in your installation.

Are you sure you built RT from an empty build directory?

Perhaps others have some idea what is going on.

**Comment by Desmis** [comment]
@Thanatomanic 

I did 2 things
* with my actual repo : rebuild cmake 
* with a new clone : rebuild all
Same problem...

is there a way to rebuild libpng and all its dependencies ?

Thank you

My new computer (I hope) will be at my home this week ??? 

Jacques

**Comment by Desmis** [comment]
@Thanatomanic 
I just try to rebuild libpng

$ pacman -S mingw-w64-x86_64-libpng
Msys2 says rebuild libpng

Then i rebuild Cmake

And all seems to work fine

Jacques

**Comment by Thanatomanic** [comment]
Glad you were able to work it out! Reinstalling the package was a good thought.
