### ISSUE TITLE
Canon R7 support

### ISSUE THREAD

**Issue by alexforencich** [Beep6581/RawTherapee#6607]
When opening CR3 C-RAW files from my R7, black bars are appearing on the left and top side, along with a pink bar on the very top edge.  I suspect this is due to the entry for the R7 in camconst.json missing the raw_crop item.  

Looking at the CR3 in exiftool reveals some parameters that seem relevant:

    Cropped Image Width             : 6960
    Cropped Image Height            : 4640
    Cropped Image Left              : 0
    Cropped Image Top               : 0
    Sensor Width                    : 7128
    Sensor Height                   : 4732
    Sensor Left Border              : 156
    Sensor Top Border               : 84
    Sensor Right Border             : 7115
    Sensor Bottom Border            : 4723
    Black Mask Left Border          : 0
    Black Mask Top Border           : 0
    Black Mask Right Border         : 0
    Black Mask Bottom Border        : 0

The HIF files from the camera are 6960x4640, so presumably the RAW file should end up being the same size, and the exif data seems to indicate this.  

When opening the CR3 in RawTherapee, there are black bars on the left and top, and the size is reported as 7120 x 4724.  Oddly, this does not seem to correspond to the sensor size entry in the RAW file (7128 x 4732), with a difference of exactly 8 pixels in both X and Y.  

I attempted to adjust the R7 entry in camconst.json by adding a raw_crop entry like so, based on the exif data:

    "raw_crop": [ 156, 84, 6960, 4640 ],

This almost works - restarting rawtherapee and reopening the image results in an image with no black bars, but the image size is still not correct, at 6952 x 4632.  Interestingly, the discrepancy is exactly the same as the reported sensor size (7120 x 4724) vs. the original image size (7128 x 4732), with the image size differing by exactly 8 pixels in both X and Y.  

As a sanity check, I downloaded an R5 raw file (from https://www.dpreview.com/sample-galleries/7757595702/canon-eos-r5-sample-gallery/8277337580) and compared the exif data against rawtherapee and the raw_crop entry for the R5 (128, 96, 8224, 5490).  The image size reported by exiftool and on the gallery is 8192 x 5464, however the image size reported by rawtherapee is 8216 x 5482, which is also 8 pixels less than the size indicated by raw_crop, but does not match the image size fields in the exif data.  

Most likely my understanding of how raw_crop is supposed to be configured is incorrect.  Is the 8 pixel discrepancy coming from the debayering process, perhaps?  And perhaps should the raw_crop setting be adjusted not to produce a size that matches the exif data, but instead the largest possible image based on what the sensor is actually picking up?  In other words, should raw_crop be set by ignoring the exif data and simply inspecting a raw file directly for where the actual boundaries of the image end up?  If so, what's the best process for doing this?

**Comment by Thanatomanic** [comment]
There is no issue I think. Please take a look at the Demosaicing settings in RT to find a slider for a border. Reduce this to zero and voila, you should have maximum size (but could have some border artifacts due to interpolation).

**Comment by alexforencich** [comment]
Ah, I see, the 8 pixel difference is coming from the default border of 4 pixels during demosaicing.  That part makes sense.

Then, what is the accepted method for determining the raw_crop settings for a given camera?  Should I just take the exif parameters and expand the size by 4 pixels all the way around?  Or should I do something based on the actual file data?  The R5 crop settings don't match the reported image size, so I'm assuming they were picked to match whatever part of the sensor was actually illuminated, resulting in a few more pixels around the edge than you would get from the default in-camera processing.

(For reference, if the R5 crop settings were based on the exif data by simply expanding by 4 pixels in each direction, I would expect the first two values to be 140 and 108 as they are 4 less than the reported sensor left and top border values of 144 and 112, but instead they are 128 and 96...so where did the values of 128 and 96 come from?)

**Comment by Thanatomanic** [comment]
The physical sensor size is typically different from the illuminated area. And we try to maximize the image area. So, while I do not know exactly who figured out the R5 values, it should give the maximal area. This is easy to check: lower the crop value and a black border (or garbage data) should appear.

The same process should be done for new sensors. The metadata may give a good starting point, and just keep expanding until you have found the maximum size. A bit tedious to do, but we don't have a faster way atm.

**Comment by alexforencich** [comment]
I see, I suppose I can mess around with that and see if I can come up with some sensible crop settings.  

What about masked_areas setting that a number of cameras have, I think that is supposed to correspond to a masked off (black) region of the sensor, outside of the image area?  Is that just cooked up to correspond to a strip along one edge outside of the raw_crop area, or is that based on anything specific?

**Comment by Thanatomanic** [comment]
Masked area is unexposed and therefore useful to determine the lowest sensor value (black level).

Please also take a look in the introduction of https://github.com/Beep6581/RawTherapee/blob/dev/rtengine/camconst.json for some explanation of the values and format.

**Comment by alexforencich** [comment]
I did look at that, but I was wondering if there was any other documentation or proper procedures for figuring out what the values should be for a specific camera.  For instance, if the crop values are determined from looking at the extents of the image in the raw file, it's generally pretty clear where it goes from "black" to "image", but presumably a margin of some sort would be a good idea - are there any guidelines for things like that?

**Comment by Thanatomanic** [comment]
I'm not sure if something is written on RawPedia, but in general: maximize the raw area, the 'Border' setting takes care to prevent any edge artifacts.

**Comment by alexforencich** [comment]
Makes sense.  What about variations in the actual masked area, sensor-to-sensor?  Are we just assuming that all sensors are going to have the image area masked exactly the same, at least to within a pixel?  Or should extra margin be added to account for that possibility?  

I'll take a closer look at the R5 crop settings and compare those to the raw file I downloaded, and try to do something similar for the R7.  

Also, since it seems like the crop data can be contained in the exif tags, is there anything to be said for having a "camera" setting that crops the image according to those parameters so it exactly matches the camera's internal processing?

**Comment by alexforencich** [comment]
Notes on R5 settings:

I commented out the R5 raw_crop and masked_areas settings in camconst.json.  The original settings were:

    "raw_crop" : [ 128, 96, 8224, 5490 ],
    "masked_areas" : [ 94, 20, 5578, 122 ],

Opening an R5 raw file in rawtherapee resulted in an image that's 8344 x 5578.  Setting the demosaicing border to 0 changed that to 8352 x 5586, which matches the exif data for the sensor size.  Adjusting the crop to exactly the bounds of the image resulted in a crop of left 128, top 96, width 8224, height 5490.  Which corresponds exactly to the raw_crop setting.

For the masked_areas setting, this seems to correspond to a rectangle in the black region on the left of the image that's separated by a few pixels (122 vs 128).  The height is approximately the same as the image height.  I'm not sure if there is any other significance to the selected values; they otherwise seem to be rather randomly selected.  The top is 94 pixels from the top of the sensor, the left is 20 pixels from the left of the sensor, the bottom is 5586-5578 = 8 pixels from the bottom of the sensor, and the left is 128 - 122 = 6 pixels away from the image.  All of the gaps are different, and the height does not match the image height.

I'll extract a similar set of settings from an R7 raw, and I'll also see if I can hunt down an R10 raw.

**Comment by alexforencich** [comment]
Updated entries for the R7 and R10:

    { // Quality C
        "make_model": "Canon EOS R7",
        "dcraw_matrix" : [10424, -3138, -1300, -4221, 11938,  2584,  -547,  1658,  6183],
        "raw_crop": [ 144, 72, 6984, 4660 ],
        "masked_areas" : [ 70, 20, 4724, 138 ]
    },

    { // Quality C
        "make_model": "Canon EOS R10",
        "dcraw_matrix" : [9269, -2012, -1107, -3990, 11762,  2527,  -569,  2093,  4913],
        "raw_crop": [ 144, 40, 6048, 4020 ],
        "masked_areas" : [ 38, 20, 4052, 138 ]
    },

Still not 100% confident about the masked_areas settings.

**Comment by alexforencich** [comment]
Another side note, I noticed that the EOS M3 raw_crop setting appears like it might be incorrect, at least according to the comments:

    "raw_crop": [ 72, 34, 6024, 4022 ], // full size 6096x4056, official crop 84,46,6083,4045

It's moved relative to the "official" crop towards the upper left corner, but it's significantly smaller, which doesn't make any sense to me.

**Comment by alexforencich** [comment]
What else needs to be done to fully support the R7 in RawTherapee?  It seems like there are some specific test shots that should be taken as per http://rawpedia.rawtherapee.com/Adding_Support_for_New_Raw_Formats .  Should I do that and post a link the files here?

**Comment by alexforencich** [comment]
I created a pull request with these additions here: https://github.com/Beep6581/RawTherapee/pull/6608

**Comment by Lawrence37** [comment]
Yes, take the images described in RawPedia and post a link to them here.

For `masked_areas`, the exact number of pixels to discard from the borders is up to you, but `camconst.json` offers some guidance (2-4 pixels on each side):
https://github.com/Beep6581/RawTherapee/blob/11168aa6404b6db18c3b6e67ac12b47740369b6c/rtengine/camconst.json#L83-L85
