### ISSUE TITLE
macOS automated builds fail

### ISSUE THREAD

**Issue by Thanatomanic** [Beep6581/RawTherapee#6610]
@Benitoite Could you please look at what is going on? Please see https://github.com/Beep6581/RawTherapee/actions/runs/3408747558

**Comment by Beep6581** [comment]
Technically I don't think we need to wait with 5.9 for this to be fixed as we should be able to trigger a rebuild of the `releases` branch or of the (future) `5.9` tag once fixed.

**Comment by Benitoite** [comment]
PR #6613 resolves this issue.  Updated the autobuild for macos.
