### ISSUE TITLE
UI Freeze - can't apply processing profile

### ISSUE THREAD

**Issue by finnito** [Beep6581/RawTherapee#6614]
**Short description**
When trying to apply a saved profile to one/many images the UI freezes and won't let me select a profile.

**Steps to reproduce**
1. Highlight a photo
2. Right click or use the Processing Profiles to apply a profile
3. See error in video here [https://youtu.be/FIKmf4Hxi7o](https://youtu.be/FIKmf4Hxi7o)

**Expected behavior**
The UI should let you select and apply a profile.

**Additional information**
RawTherapee 5.8
Macbook Pro 16" 2019
MacOS Ventura 13.0.1
Installed from a binary (not from source)

**Comment by Lawrence37** [comment]
It's unlikely that this is a problem specific to processing profiles. Have you checked if it happens to other menus?

**Comment by Thanatomanic** [comment]
This is caused by an upstream issue https://gitlab.gnome.org/GNOME/gtk/-/issues/5305
We cannot fix it unfortunately.
