### ISSUE TITLE
 Automated macOS build - various issues

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#6618]
```
Error: Failed to load cask: libomp.rb
```

https://github.com/Beep6581/RawTherapee/actions/runs/3559871755/jobs/5979523410#step:4:111

```
tput: unknown terminal "unknown"
```

https://github.com/Beep6581/RawTherapee/actions/runs/3559871755/jobs/5979523410#step:6:32

```
ditto: Cannot get the real path for source '/usr/local/lib/liblensfun.2.dylib'
```

https://github.com/Beep6581/RawTherapee/actions/runs/3559871755/jobs/5979523410#step:6:53

```
ditto: can't get arch info for ''
ditto: Could not parse the Mach-O architectures to copy
```

https://github.com/Beep6581/RawTherapee/actions/runs/3559871755/jobs/5979523410#step:6:56

```
ditto: Cannot get the real path for source '/usr/local/lib/libjpeg.62.dylib'
```

https://github.com/Beep6581/RawTherapee/actions/runs/3559871755/jobs/5979523410#step:6:161

```
cp: RawTherapee.app/Contents/Frameworks/gtk-3.0/3*/immodules/*.dylib: No such file or directory
cp: RawTherapee.app/Contents/Frameworks/gtk-3.0/3*/immodules/*.so: No such file or directory
rm: RawTherapee.app/Contents/Frameworks/gtk-3.0: No such file or directory
```

https://github.com/Beep6581/RawTherapee/actions/runs/3559871755/jobs/5979523410#step:6:174

```
Cannot load module /Users/runner/work/RawTherapee/RawTherapee/build/RawTherapee.app/Contents/Frameworks/im-*: dlopen(/Users/runner/work/RawTherapee/RawTherapee/build/RawTherapee.app/Contents/Frameworks/im-*.so, 10): image not found
/Users/runner/work/RawTherapee/RawTherapee/build/RawTherapee.app/Contents/Frameworks/im-* does not export GTK+ IM module API: dlopen(/Users/runner/work/RawTherapee/RawTherapee/build/RawTherapee.app/Contents/Frameworks/im-*.so, 10): image not found
/Users/runner/work/RawTherapee/RawTherapee/tools/osx/macosx_bundle.sh: line 271: /usr/local/bin/gtk-query-immodules: No such file or directory
```

https://github.com/Beep6581/RawTherapee/actions/runs/3559871755/jobs/5979523410#step:6:184

@Benitoite could you take a look?

**Comment by Beep6581** [comment]
Current macOS build actions run successfully, so closing.

**Comment by Benitoite** [comment]
> ```
> Error: Failed to load cask: libomp.rb
> ```
> 

fixed with https://github.com/Beep6581/RawTherapee/pull/6675/commits/0838d77fb94d4297e911ac975b6348115d93067d

> 
>      
>   
> 
> ```
> tput: unknown terminal "unknown"
> ```
> 

fixed with https://github.com/Beep6581/RawTherapee/pull/6675/commits/c55bc5103fc50bc2499ebc2a7933bbd8eb4b1495

> 
> ```
> ditto: Cannot get the real path for source '/usr/local/lib/liblensfun.2.dylib'
> ```
> 
> 
>      

fixed in https://github.com/Beep6581/RawTherapee/pull/6675/commits/ba11a9355ac76342368ba122b252fe372b328128

> 
> ```
> ditto: can't get arch info for ''
> ditto: Could not parse the Mach-O architectures to copy
> ```
> 
> 

fixed by https://github.com/Beep6581/RawTherapee/pull/6675/commits/fe69ebff6abbb7d5756f909b3d6abf246215cd4c

>      
>   
> 
> 
> ```
> ditto: Cannot get the real path for source '/usr/local/lib/libjpeg.62.dylib'
> ```
> 
> 

fixed in _wip_

> 
> ```
> cp: RawTherapee.app/Contents/Frameworks/gtk-3.0/3*/immodules/*.dylib: No such file or directory
> cp: RawTherapee.app/Contents/Frameworks/gtk-3.0/3*/immodules/*.so: No such file or directory
> rm: RawTherapee.app/Contents/Frameworks/gtk-3.0: No such file or directory
> ```
> 
> 
>      

fixed in _wip_

> 
> ```
> Cannot load module /Users/runner/work/RawTherapee/RawTherapee/build/RawTherapee.app/Contents/Frameworks/im-*: dlopen(/Users/runner/work/RawTherapee/RawTherapee/build/RawTherapee.app/Contents/Frameworks/im-*.so, 10): image not found
> /Users/runner/work/RawTherapee/RawTherapee/build/RawTherapee.app/Contents/Frameworks/im-* does not export GTK+ IM module API: dlopen(/Users/runner/work/RawTherapee/RawTherapee/build/RawTherapee.app/Contents/Frameworks/im-*.so, 10): image not found
> /Users/runner/work/RawTherapee/RawTherapee/tools/osx/macosx_bundle.sh: line 271: /usr/local/bin/gtk-query-immodules: No such file or directory
> ```
> 
> 
>     

wip.

> 
> 
> @Benitoite could you take a look?
