### ISSUE TITLE
Improve support for several Fujifilm camera's

### ISSUE THREAD

**Issue by Thanatomanic** [Beep6581/RawTherapee#6624]
As per request on Pixls. See e.g. https://discuss.pixls.us/t/rawtherapee-5-9-released/33834/24 to encourage copying values from RawSpeed, and https://discuss.pixls.us/t/black-band-on-side-of-pictures-with-fuji-x-t5/33871 with preliminary X-T5 info.

**Comment by kmilos** [comment]
Looking at e.g. X-T4 it seems you do crops differently, so it's probably better to actually determine it your way.

The color matrix comes from the DNG conversion in any case...
