### ISSUE TITLE
Canon R camera exif still not supported

### ISSUE THREAD

**Issue by mickhause** [Beep6581/RawTherapee#6625]
Hello
I just built the 5.9 release on Windows 10 pro, after updated my lensfun database, but Canon R5 / R6 / R7 exif are still unavailable.
Could the feature be included in the next dev version ?
Thanks.

**Comment by Thanatomanic** [comment]
We need proper CR3 metadata support, which is in the pipeline. See https://github.com/Beep6581/RawTherapee/issues/6248
