### ISSUE TITLE
Raw Black Points and Abstract Profile are ignored for the File Browser thumbnails

### ISSUE THREAD

**Issue by teplit** [Beep6581/RawTherapee#6628]
For the thumbnails in the File Browser, RawTherapee 5.9 ignores:
- The Raw Black Points
- The Abstract Profile

Steps to reproduce the problems:
1. Open a RAW file in RawTherapee 5.9.
2. Open the top panel.
3. Change substantially one of the Raw Black Points in the Raw Tab and observe the lack of effect on the image thumbnail in the top panel.
4. Reset the Raw Black Points.
5. In the Color Tab activate a linear profile (Linear g=1) and again observe the lack of effect on the image thumbnail in the top panel.

Tested on two Windows 10 computers.

**Comment by Lawrence37** [comment]
Confirmed. The flat field is not applied either (possibly intentional) and the white point correction doesn't trigger a refresh.
