### ISSUE TITLE
PDAF lines filter crashes with RAWs from Nikon Z 50

### ISSUE THREAD

**Issue by apostel338** [Beep6581/RawTherapee#6630]
**This bug has been fixed in ART some days ago:** https://bitbucket.org/agriggio/art/commits/365a76ed78e36dac7d7797510b750aa92276da03

**Steps to reproduce**

-> Raw-Tab
-> Sensor Matrix
-> Preprocessing
-> Activate *PDAF lines filter*
-> Crash

**Expected behavior**

Not to crash.

**Additional information**

Up-to-date Windows 11, latest automated dev build as of today.

I tried RAWs from about 10 - 12 cameras, including Z fc, other Nikons of the Z series and some Sonys, Canons, but the bug is very picky and only crashes with Z 50 so far.

Screencast:
https://user-images.githubusercontent.com/96216629/205400968-8f6d899f-06a5-4bc8-abc0-f35c306fb0b9.mp4

Sample raw: 
https://share.mailbox.org/ajax/share/0731300e0495c64d7237702495c64b13a6008e2447669246/1/8/Mzg/MzgvNg

BT:
[log.txt](https://github.com/Beep6581/RawTherapee/files/10144784/log.txt)

**Comment by ValZapod** [comment]
Yep, crashes.

**Comment by Lawrence37** [comment]
Resolved with PR #6687.
