### ISSUE TITLE
RawTherapee 5.9 AppImage does not install on Intel Linux and not run at all on ARM Linux

### ISSUE THREAD

**Issue by freebrowser1** [Beep6581/RawTherapee#6632]
```~/Downloads$ ./RawTherapee_5.9.AppImage 
bash: ./RawTherapee_5.9.AppImage: cannot execute binary file: Exec format error
```

**Short description**
RT 5.9 Linux has no installer provided 

**Steps to reproduce**

Run Ubuntu 22.04 and start the downloaded 
1. Open terminal and go to folder where RawTherapee_5.9.AppImage is downloaded.
2. Run :
```chmod u+w ./RawTherapee_5.9.AppImage 
./RawTherapee_5.9.AppImage 
```

3a. Ubuntu 22.04 INTEL : Does work, but no installer provided and dumps some error info before starting.
Run:
```./RawTherapee_5.9.AppImage 
/usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so

(AppRun.wrapped:1976): Gtk-WARNING **: 15:03:42.966: Theme parsing error: gtk.css:1374:85: 'font-feature-settings' is not a valid property name
/usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so
/usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so
/usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so
```
Then it starts and can be used normally despite these error messages but after exit no RT app is installed.

3b. Ubuntu 22.04 ARM64/M1 : Repeat steps 1 and 2.
Then do this: it does not run at all
```~/Downloads$ ./RawTherapee_5.9.AppImage 
bash: ./RawTherapee_5.9.AppImage: cannot execute binary file: Exec format error

**Comment by ulrichk33** [comment]
Same as in 3a here in Debian 11 (bullseye - 5.10.0-19-amd64).
Verison-no of gvfs-libs is 1.46.2-1
Appimage runs fine, it is only about the error messages.

(Apart from the warning at start that the locale (de_DE.UTF-8) is not supported by C library and it will use the fallback.)

**Comment by Lawrence37** [comment]
The AppImage does not need to be installed. The errors and warnings can be ignored if it runs normally. We do not provide AppImages for ARM architectures (yet).

**Comment by albertosaurus** [comment]
An appimage is not an installer. See: https://appimage.org/

**Comment by Beep6581** [comment]
Closing as I don't see any specific issue to resolve (the AppImage was never intended to run on ARM as far as I know).

**Comment by Benitoite** [comment]
See PR #7477 for an arm64 appimage.
