### ISSUE TITLE
cannot link with pangomm-2.50.1

### ISSUE THREAD

**Issue by avpanov** [Beep6581/RawTherapee#6634]
I cannot link rawtherapee-5.9 with pangomm-2.50.1 when compiling from sources on Linux with modern libraries. The error text is:

'''
[ 43%] Linking CXX executable rawtherapee
/usr/bin/ld: CMakeFiles/rth.dir/cropwindow.cc.o: in function `CropWindow::drawStraightenGuide(Cairo::RefPtr<Cairo::Context>)':
/tmp/build/rawtherapee-5.9/rtgui/cropwindow.cc:2552: undefined reference to `Pango::Layout::add_to_cairo_context(Cairo::RefPtr<Cairo::Context> const&)'
/usr/bin/ld: /tmp/build/rawtherapee-5.9/rtgui/cropwindow.cc:2554: undefined reference to `Pango::Layout::add_to_cairo_context(Cairo::RefPtr<Cairo::Context> const&)'
/usr/bin/ld: /tmp/build/rawtherapee-5.9/rtgui/cropwindow.cc:2556: undefined reference to `Pango::Layout::add_to_cairo_context(Cairo::RefPtr<Cairo::Context> const&)'
/usr/bin/ld: /tmp/build/rawtherapee-5.9/rtgui/cropwindow.cc:2558: undefined reference to `Pango::Layout::add_to_cairo_context(Cairo::RefPtr<Cairo::Context> const&)'
/usr/bin/ld: /tmp/build/rawtherapee-5.9/rtgui/cropwindow.cc:2562: undefined reference to `Pango::Layout::add_to_cairo_context(Cairo::RefPtr<Cairo::Context> const&)'
/usr/bin/ld: CMakeFiles/rth.dir/cropwindow.cc.o:/tmp/build/rawtherapee-5.9/rtgui/cropwindow.cc:2478: more undefined references to `Pango::Layout::add_to_cairo_context(Cairo::RefPtr<Cairo::Context> const&)' follow
collect2: error: ld returned 1 exit status
make[2]: *** [rtgui/CMakeFiles/rth.dir/build.make:2628: rtgui/rawtherapee] Error 1
make[1]: *** [CMakeFiles/Makefile2:237: rtgui/CMakeFiles/rth.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

'''

**Comment by Thanatomanic** [comment]
What distro are you using?
Also, did you clear the build folder before configuration and compilation?

**Comment by Thanatomanic** [comment]
This is what happens on my fully updated Fedora 35 system:
```
[roel@fedora35 ~]$ sudo dnf list pango*
Last metadata expiration check: 0:05:09 ago on Tue 06 Dec 2022 09:15:41 AM CET.
Installed Packages
pango.x86_64                                  1.50.4-1.fc35                      @updates
pango-devel.x86_64                            1.50.4-1.fc35                      @updates
pangomm.x86_64                                2.46.2-1.fc35                      @updates
pangomm-devel.x86_64                          2.46.2-1.fc35                      @updates
Available Packages
pango.i686                                    1.50.4-1.fc35                      updates 
pango-devel.i686                              1.50.4-1.fc35                      updates 
pango-tests.x86_64                            1.50.4-1.fc35                      updates 
pangomm.i686                                  2.46.2-1.fc35                      updates 
pangomm-devel.i686                            2.46.2-1.fc35                      updates 
pangomm-doc.noarch                            2.46.2-1.fc35                      updates 
pangomm2.48.i686                              2.50.0-1.fc35                      updates 
pangomm2.48.x86_64                            2.50.0-1.fc35                      updates 
pangomm2.48-devel.i686                        2.50.0-1.fc35                      updates 
pangomm2.48-devel.x86_64                      2.50.0-1.fc35                      updates 
pangomm2.48-doc.noarch                        2.50.0-1.fc35                      updates 
```
It seems it has 2.50.0, not 2.50.1, but at least that compiles perfectly fine. It would be curious if a minor version update would cause linking issues. I'm not even sure if RT actually uses pangomm2.48 instead of the regular pangomm (2.46).

**Comment by avpanov** [comment]
My distro is Slackware-current with manually installed pangomm and other gtkmm libraries. The issue does not depend on clearing the folder.

**Comment by Floessie** [comment]
Please excuse me if I have to be the killjoy here.

Compiling fine and then failing in the linking phase is usually a sign for an improperly installed library. The compiler uses header files that don't fit the library files that are picked up by the linker. This is a problem with @avpanov's installation and should be fixed there.

Although we don't know yet if RT builds fine with pangomm-2.50.1, I'll close this issue. Feel free to reopen it when the problem can be reproduced with a distribution supplied pangomm.

Best,
Flössie

**Comment by avpanov** [comment]
I think I have no problems with pangomm installation. There were rearrangements in pangomm header files after the version of 2.48. Do you plan to stay at pangomm 2.46 for ever?

**Comment by Thanatomanic** [comment]
Probably not for ever, but as long as 2.46 suits our purposes perfectly and it remains widely available in distro's, there is no need to update.
