### ISSUE TITLE
Color Checker 24 shots for making a Sony a7IV camera profile

### ISSUE THREAD

**Issue by stefan-i** [Beep6581/RawTherapee#6636]
Hi,
I have shot a Colorchecker Passport (manufactured 2022) with my Sony a7 Mark IV in Daylight and Tungsten light. I uploaded the files here, you can freely use them based on CC0 (Public domain) licence:

https://gofile.io/d/1hOtHG

The files provided are in the camera's native .ARW format (14 bit, lossless compression) as well as converted to DNG with the latest Adobe DNG converter.  
Thank you for adding a DCP profile in RT.
Kind regards
Stefan

**Comment by Thanatomanic** [comment]
I've downloaded your files. Interestingly the ARW files do not show up in the file browser, even though the extension is allowed. Apparently RT cannot even read them. This also may have to do with the lossless compression, but usually this allowed files to be seen, only not to be read properly.

**Comment by stefan-i** [comment]
I noticed that too. Apparently RT does not support the lossless compression of newer Sony cameras. Lossy and uncompressed Raw files work fine. That is a pity as I find lossless compressed the most useful format. Is there any support planned for RT?

**Comment by Thanatomanic** [comment]
Actually, this camera already has a DCP https://github.com/Beep6581/RawTherapee/pull/6552

**Comment by stefan-i** [comment]
Oops, sorry, I hadn't noticed. Thanks anyway.

**Comment by Entropy512** [comment]
> Is there any support planned for RT?

Probably unlikely before https://github.com/Beep6581/RawTherapee/issues/4462 - at some point I may take a crack at it, but it's pretty low priority for me, I just shoot uncompressed.

**Comment by yeralexey** [comment]
> Hi,
> I have shot a Colorchecker Passport (manufactured 2022) with my Sony a7 Mark IV in Daylight and Tungsten light. I uploaded the files here, you can freely use them based on CC0 (Public domain) licence:
> 
> https://gofile.io/d/1hOtHG
> 
> The files provided are in the camera's native .ARW format (14 bit, lossless compression) as well as converted to DNG with the latest Adobe DNG converter.  
> Thank you for adding a DCP profile in RT.
> Kind regards
> Stefan

Hi. Is there still any place to get these photos? Directory does not exist, they say

**Comment by stefan-i** [comment]
> Hi. Is there still any place to get these photos? Directory does not exist, they say

It probably got removed after all this time. I uploaded again here: https://gofile.io/d/fEVD2W
