### ISSUE TITLE
Exif data not visible in Windows Photo Viewer after export

### ISSUE THREAD

**Issue by kleinm95** [Beep6581/RawTherapee#6637]
The exif-data (like camera model, shutter, ISO, recording date, ...) gets lost when I export the files in RawTherapee. It happens after preprocessing my .dng-files with Topaz Denoise AI. 
At first I thought its a bug in Topaz. 
But when editing the preprocessed files in RawTherapee, I'm able to see the exif-data in the editor. It also works when changing the export as tiff (8bit). But when I set the export as jpeg (8bit), the exif-data is lost.

I tried to attach the files, but they're too big. So i uploaded them to google drive: https://drive.google.com/drive/folders/1B6rZxWs2R93k2-U230RIarY-wat85B5h?usp=sharing

My OS: 
Windows 10 
Version: 21H1

My installed RawTherapee version:

Version: 5.9
Branch: 5.9
Commit: 9b8583988
Commit date: 2022-11-27
Compiler: cc 12.2.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.24.7
Lensfun: V0.3.3.0
Build type: release
Build flags:  -std=c++11 -ffp-contract=off -mtune=generic -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wno-attributes -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags:  -mtune=generic
OpenMP support: ON
MMAP support: ON
Build OS: MINGW64_NT-10.0-20348 3.3.6-341.x86_64 x86_64
Build date: Sun, 27 Nov 2022 18:38:56 +0000 UTC
Build epoch: 1669574336
Build UUID: 9d19d210-c668-4aa2-8af6-2d527fd55d1c

**Comment by gaaned92** [comment]
I downloaded bug.zip and extracted the jpg. It is a photo of a Typhoon. 

All these metadata are included in the jpg

[IMG_0936-DeNoiseAI-raw.txt](https://github.com/Beep6581/RawTherapee/files/10236639/IMG_0936-DeNoiseAI-raw.txt)

**Comment by kleinm95** [comment]
You're right. The metadata is still there, but after checking for myself the exif-structure of the pictures are slightly different. And somehow the Windows Photo Viewer has an issue showing the data after Preprocessing the files. 

If both exports (as jpeg and tiff) would both not work, then I'd say its a bug from Topaz. But the tiff-export works fine.

**Comment by gaaned92** [comment]
I should say the better option is to not use Windows Photo viewer which I think is not color managed.
Instead better use xnviewMP, irfanview, faststone or digikam if you want DAM...

**Comment by Lawrence37** [comment]
I opened the JPEG in multiple applications and they all show the EXIF data. This is likely a bug/deficiency in Windows Photo Viewer, so I'm closing this issue.
