### ISSUE TITLE
Regression? Color shift even though automatic wb is not used.

### ISSUE THREAD

**Issue by Thanatomanic** [Beep6581/RawTherapee#6639]
First reported here: https://discuss.pixls.us/t/broken-compatibility-in-rawtherapee-5-9-greenish-tint/34031/
Raw file: https://discuss.pixls.us/uploads/short-url/yFFZBk6UDEpdd8cVjuq4l4JeHJW.ORF
Custom PP3 to check: [P5020458-test.ORF.pp3.txt](https://github.com/Beep6581/RawTherapee/files/10200395/P5020458-test.ORF.pp3.txt) (remove .txt)

I was able to confirm that a color shift is present when comparing 5.8 and 5.9. This is white balance related and I could trace it back to this commit: https://github.com/Beep6581/RawTherapee/commit/8a972bef9ef8760e8045ebee95f78ec0706d50c5.

To check:
```
git checkout 97b8918
git cherry-pick be67261d0bdeb21ffe15fe968dd5bc16edd407e0
```
The cherry-pick is to ensure RT can be linked to `jpegturbo`. Then build, load image, load pp3, export (either JPEG or TIF, doesn't matter).
If you instead checkout `8a972be` (or any later commit) and compare the image, there is a small, but noticeable color difference.

**Why is this a problem?** Well, looking at the commit, it is related to automatic white balancing. However, there is also a color difference when a manual, custom wb is used. I would not expect that to happen. I have not looked at _why_ this happens, that's the next step.

@Desmis Do you have any ideas?

**Comment by Desmis** [comment]
@Thanatomanic 

 I just looked and there is a bad assignment of the variable "observer 2°" instead of "observer 10°"

I made the change in the branch "observer2".
Maybe this is the cause of the problem.

But not used in this case (automatic), but used in all white balance ?

Jacques

**Comment by Desmis** [comment]
I made another change  - related to wb auto...

Jacques

**Comment by Thanatomanic** [comment]
This seems to have done the trick!

**Comment by Desmis** [comment]
OK 

I create a Pull Request

But it must be said that the debate in colorimetry observer2 or  observer10 has no solution. This is only due to the difference in the cone of vision. It is neither better nor worse. Nevertheless in this specific case if the matrix was developed under certain conditions this may have an impact

Jacques

**Comment by Thanatomanic** [comment]
I understand. However, this issue was raised because we broke backwards compatibility. In my opinion that is a valid point. _If_ there was a way in the GUI to choose the observer, we could circumvent it and have a legacy option available. But that may also be too complicated...

**Comment by Desmis** [comment]
Yoi are right. But I think this change in "option" (or in main) can wait.

I will push the change today.

Thank you

Jacques

**Comment by Thanatomanic** [comment]
Closed by https://github.com/Beep6581/RawTherapee/pull/6640
