### ISSUE TITLE
RawPedia broken design (Template:K)

### ISSUE THREAD

**Issue by rebio** [Beep6581/RawTherapee#6652]
**Short description**
The design of RawPedia seems to be broken

**Steps to reproduce**
1. Visit http://rawpedia.rawtherapee.com/Getting_Started
2. Section _Basics_

**Additional information**
RawPedia had a black design before. I don't know if the new theme is intentional or maybe some update broke it. It seems like "{{k|w}} " is the part that causes the issue ( http://rawpedia.rawtherapee.com/Template:K )

**Comment by ghost** [comment]
Pat David broke RawPedia :-)

Seriously, though: Something did not work as expected after a software upgrade.

There's also the intention to migrate the website, and as the current situation is just the theme that is broken and not the overall functionality it is decided to leave it as is until the migration has taken place.

Read all about it on Pixls: [An update on Rawpedia](https://discuss.pixls.us/t/an-update-on-rawpedia/34168?u=jade_nl)

**Comment by TechXavAL** [comment]
I'm obliged to say that the keyboard shortcuts template has nothing to do with the theme, so aside of the dark theme not working, there are other side effects.

As an example, try to load [the Keyboard Shortcuts page](https://rawpedia.rawtherapee.com/Keyboard_Shortcuts).

Nevertheless, there's no intention to fix that. Patience is the key now, until the new website is ready.
