### ISSUE TITLE
Activating Ciecam introduces color cast in RT 5.9

### ISSUE THREAD

**Issue by stefan-i** [Beep6581/RawTherapee#6656]
Hi
I noticed an unwelcome change in the Ciecam module in 5.9 that was not present in 5.8.

In 5.8 and earlier, just activating Ciecam with all sliders to default values did not change the image (provided "mean luminance Yb%" was set to 18). Now in 5.9, when Ciecam is activated a noticeable color shift occurs. 

As an example, take the image of the color checker here:
https://www.file-upload.net/download-15068738/Sonya7IVDaylightDSC00122.DNG.html

When setting the white balance on the second left grey patch, the RGB values are identical (as they should be):
<img width="387" alt="Clipboard01-NoCiecam" src="https://user-images.githubusercontent.com/13986045/210179271-9bc92e2b-7a92-4ac7-ba13-c4efae07b508.png">

However, just activating the Ciecam module introduces a color cast:
<img width="387" alt="Clipboard02-Ciecam" src="https://user-images.githubusercontent.com/13986045/210179294-dc5a6cf2-01a4-4b8f-9d3e-c4e05a0d4ced.png">

So with Ciecam on, it is no longer possible to set a  neutral white balance by e.g. clicking on a grey patch, as the module introduces a color shift.

The color shift is quite noticeable in real world images (looks like magenta shift). Just look at the asphalt background of the provided Raw file to get an idea.  It does not seem to depend much on the white balance setting of the image: When you set white balance of the image in RT to random values the strength of the shift by activating Ciecam seems to stay roughly the same, so it does not seem to be an effect of the normal color adaptation behavior of Ciecam but an unwanted, fixed shift.

I think that at default values there shouldn't be these kind of color shifts for supposedly neutral patches, so could you please take a look at the cause of this problem? Thank you!

P.S.: I played around a bit in the Ciecam settings, and the shift can mostly (but not entirely) be avoided by changing the following settings from the default values:
<img width="287" alt="Clipboard03-SettingsNeutral2" src="https://user-images.githubusercontent.com/13986045/210179830-027e858e-4936-4d9b-b735-644f509b6e7b.png">
However, this is just a workaround for now and may not work as intended for all images, so it would be preferable to properly fix this issue.

RT versions tested: 

Version: 5.9
Branch: 5.9
Commit: 9b8583988
Commit date: 2022-11-27
Compiler: cc 12.2.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.24.7
Lensfun: V0.3.3.0
Build type: release
Build flags:  -std=c++11 -ffp-contract=off -mtune=generic -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wno-attributes -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags:  -mtune=generic
OpenMP support: ON
MMAP support: ON
Build OS: MINGW64_NT-10.0-20348 3.3.6-341.x86_64 x86_64
Build date: Sun, 27 Nov 2022 18:38:56 +0000 UTC
Build epoch: 1669574336
Build UUID: 9d19d210-c668-4aa2-8af6-2d527fd55d1c

Version: 5.9-7-g1cc3b0eb6
Branch: dev
Commit: 1cc3b0eb6
Commit date: 2022-12-02
Compiler: cc 12.2.0
Processor: znver3
System: Windows
Bit depth: 64 bits
Gtkmm: V3.24.7
Lensfun: V0.3.95-lc
Build type: release
Build flags:    -Wno-aggressive-loop-optimizations -Wno-parentheses -std=c++11 -ffp-contract=off -march=znver3 -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wno-attributes -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -fopenmp -Werror=unknown-pragmas  -DNDEBUG  -O3
Link flags:   -march=znver3  -s  -O3
OpenMP support: ON
MMAP support: ON
Build OS: MINGW64_NT-10.0-19044 3.3.6-341.x86_64 x86_64
Build date: Mon, 05 Dec 2022 12:55:52 +0000 UTC
Build epoch: 1670244952
Build UUID: 60e1bf50-2b90-4e0d-815d-9ad0d3a25617

**Comment by Thanatomanic** [comment]
Regardless of the fact that there may be a difference between 5.8 and 5.9: is this a bug or a feature? I am not sure that using a CAM would always guarantee that neutral colors remain neutral. Edit: And since this is the premise of your report, it is quite important to figure that out.

**Comment by stefan-i** [comment]
As I understand it, one feature of Ciecam is indeed to adapt the colours when shooting far outside the normal D50 range. However, in this case I am pretty sure this has to be a bug as the color checker was shot almost exactly at D50 color temperature and then white balance was even set manually to the neutral grey patch. It does not seem right that it is clearly pushed away from being neutral by activating Ciecam. In addition, the color shift away from neutral seems to be fixed, i.e. it does not depend on the white balance set in the white balance module of RT. What might also be a possibility is that RT's _regular_ White Balance module got somehow broken or misaligned with the white balance module within Ciecam, leading to these color mismatches.
Edit: Might this be related to this issue? https://github.com/Beep6581/RawTherapee/issues/6639

**Comment by Desmis** [comment]
Nothing surprises me...
Indeed I have been asked for 1 to 3 years totally contradictory approaches.
* the modification on cat02preset which ensured symmetry in "automatic symmetric" mode
* the automatic adjustment of the temperature (output) according to the choices of the various menus which has also been deleted (the code still existed, but deactivated)

In reality the solution so that Ciecam does not change the colorimetry at all is the "symmetrical" mode...which has been rendered ineffective after all the modifications requested, otherwise to do it manually.

In symmetric:
* adaptation (chromatic), mean luminance, absolute luminance, surround must be the same for 'scene' and 'viewing'
* temp output is either white-balance or the illuminant choose...

These various choices are almost impossible to select all - according to the various modes - in all cases, after all requested changes.
I propose a compromise solution which by default makes the "automatic symmetric" mode an almost true symmetric mode;

Branch : ciecamsym

jacques

**Comment by stefan-i** [comment]
Dear Jacques
Thank you for taking a look at this issue and working on a solution!

**Comment by Desmis** [comment]
@stefan-i 

If you want, you can test with executable file here
https://github.com/Beep6581/RawTherapee/actions

jacques

**Comment by stefan-i** [comment]
@Desmis 
I tested the new version and it seems to work fine now, no longer any visible color shifts when using the "automatic symmetric" mode. Thanks again!

**Comment by Desmis** [comment]
Thank you
I will merge the PR probably tomorrow

Jacques

**Comment by Desmis** [comment]
merge :)

**Comment by Lawrence37** [comment]
Resolved by PR #6658.
