### ISSUE TITLE
Displaying correct, untranslated languages in preferences

### ISSUE THREAD

**Issue by Lawrence37** [Beep6581/RawTherapee#6657]
As discussed in #6591, the language selection drop-down in preferences can be improved by showing the languages exactly as they would appear in their respective language, e.g. "Español" instead of "Espanol". Currently, the name of the language file is used as the display name (and also for storing the language in `options`). This is not good design because from a user's perspective, there is no relationship between languages and files. @Entropy512 has suggested adding the language names as entries in the language files. The file name to language display name mapping could also be in its own configuration file or in the source code itself.

What are your thoughts on how to define the mapping?

**Comment by TechXavAL** [comment]
If the I18n system is not ported to gettext, then one possibility may be specifying the language name in the first line of the translation file, as already done in the Chinese and Czech files.

So the first line would be **_#00 Language name_** and then everything else below that.
