### ISSUE TITLE
RT crush when using before/after + abstruct Profile

### ISSUE THREAD

**Issue by Foxtailgh** [Beep6581/RawTherapee#6663]
RT crushes when using before/after + abstruct Profile

1. Go to tab - color 
2. Click on  color managment
3. Scroll down to abstruct Profile 
4. Change abstruct Profile to custom and make changes in gamma and slope
5. Click before/after
6. Rt will crush.

RawTherapee 5. 9
Windows 10

**Comment by Thanatomanic** [comment]
See #6638. It is very likely the same issue.

**Comment by matei-georged** [comment]
Hey, 

I tested this on windows with a recent dev build (8047aded3ba4756233be0d4e833e535bdd6293f0). This doesn't seem to be related to #6638 . It's a crash in the GUI, `primListener` at `rtengine/improccoordinator.cc:1865` (`rtengine::ImProcCoordinator::updatePreviewImage`) seems to be a deallocated pointer.  I will to look into it.

**Comment by matei-georged** [comment]
Hey, 

I think I found the problem. I fixed it and MR will be on the way

**Comment by Lawrence37** [comment]
Thanks for the fix @din99dany. Before the merge, the AppImage crashes. After, it no longer crashes.
