### ISSUE TITLE
Profiled Lens correction for Nikon AF-S 24-85mm Lenses: Lens not detected automatically

### ISSUE THREAD

**Issue by twatzl** [Beep6581/RawTherapee#6666]
Hello,

I just picked up a "new" lens for my D610. 

It is this one: https://www.nikon.de/de_DE/product/nikkor-lenses/auto-focus-lenses/fx/zoom/af-s-nikkor-24-85mm-f-3-5-4-5g-ed-vr

Usually I was used to automatic lens correction in RT to be working, but not with this lens.

When I dug further I found profiles for two similar sounding lens names

- Nikon AF-S Nikkor 24-85 mm f/3.5-4.5G ED VR
- Nikon AF-S Zoom-Nikkor 24-85mm f/3.5-4.5G IF-ED

However in the EXIF data my lens is shown as: 
- Lens ID 	 AF-S Zoom-Nikkor 24-85mm f/3.5-4.5G IF-ED VR

Note that this is different to both entries, so obviously it matches none of the two above entries. I suspect both entries are intended for the same lens, but the lens corrections are different. Probably because one of the entries is much more detailed.

It would be cool if we could:
- figure out why there are 2 entries and if one of them is redundant and can be removed
- rename the entry so it gets detected correctly (maybe add aliases)

If needed I can provide example pictures in NEF and JPG format.

Edit:

As a workaround I copied the entry from Nikon AF-S Nikkor 24-85 mm f/3.5-4.5G ED VR and renamed it to AF-S Zoom-Nikkor 24-85mm f/3.5-4.5G IF-ED VR in the srl-nikon.xml and now the automatic detection correctly selects the lens correction profile.

**Comment by Lawrence37** [comment]
There does appear to be two 24-85mm 1:3.5-4.5 lenses, one with VR and an older model without VR. A sample NEF would be helpful in determining how to fix the automatic selection.

**Comment by twatzl** [comment]
Sorry for the late response. Hacking together the profile for me solved the issue. So basically I copied the more sophisticated profile and renamed it so that auto detection works.

I uploaded a raw file to google drive. let me know if you need more.

https://drive.google.com/file/d/1SQMrMUccpyGQLpk5wf1-BxQw3W_P5bBc/view?usp=share_link

**Comment by Lawrence37** [comment]
ExiftTool shows a name different from the Lensfun one. Exiv2 (#5889) may fix this issue.

When you say you used the "more sophisticated profile", does that mean you chose the one with more correction data? The two lenses are different, so make sure it is the correct one (the one with VR).

**Comment by Lawrence37** [comment]
Exiv2 shows the correct lens name.
![image](https://github.com/Beep6581/RawTherapee/assets/45837045/5b4648a0-89da-42c8-85b5-358d626e3d33)
It allows correct automatic selection.
![image](https://github.com/Beep6581/RawTherapee/assets/45837045/722d25ed-74d8-4523-8268-7cd301e40bbb)
