### ISSUE TITLE
LAB values seem to have an offset, when using lockable color picker

### ISSUE THREAD

**Issue by Cmonsta6** [Beep6581/RawTherapee#6685]
**Short description**

Currently having an issue with incorrect LAB lightness values when using the lockable color picker, the values are being reported too low, but not for every measurement I take.

A list of samples; 
**Measured in RT** > **What it actually is** > **Error amount**
Lab 18 > Lab 24 > -6
Lab 30 > Lab 35 > -5
Lab 40 > Lab 47 > -7
Lab 50 > Lab 54 > -4
Lab 58 > Lab 62 > -4
Lab 68 > Lab 70 > -2
Lab 80 > Lab 81 > -1
Lab 89 > Lab 90 > -1
Lab 92 > Lab 92 > 0

So the darker tones are further off than lighter tones, pretty unusual to me. I exported the file to Photoshop, used the 32 bit 0-1 range color picker set to readout LAB, to get the 'what it actually is' values. I also processed the image via Darktable using matching LAB values, imported it to Photoshop, and confirmed that while the two photos look identical, and have identical readouts in photoshop, they are being reported differently in their respective raw converter. 

I rebooted rawtherapee and upgraded from 2.8 to 2.9 but no change in this behavior. It sure seems gamma related...

**Steps to reproduce**

Download my photo: https://mega.nz/file/xUVWjZjZ#h6wCAcIl-Xb_rJtwJ9Kz4hNgGFfMvFL1MjUT9Lvls7I
Download my ICC profile: https://mega.nz/file/MdlEUCBJ#Dj4uzZb782IzV-Mu9J3qoXw0yXtYYwv0o8jJ6Z6XJKw
Download my processing profile: https://mega.nz/file/xJ9QWKwS#DQ_FbTb2UMJsfjsPeYcVXUG4SMv8s2uu0ipWurV38MA
Check the LAB values of the gray ramp in the color chart
Export to Photoshop and check the values with 32 bit 0-1 lab color picker.

**Expected behavior**

_Mostly_ consistent LAB values

**Additional information**

**Comment by Cmonsta6** [comment]
Now I'm seeing the opposite issue, too high of lab values in the dark tones. RGB seems to be consistently correct though so I've been using that in the meantime.

**Comment by Cmonsta6** [comment]
Sorry didn't mean to close this... I don't github often.

**Comment by Lawrence37** [comment]
There's definitely something weird going on here. You can also see the issue in the histogram.
![image](https://user-images.githubusercontent.com/45837045/219907253-ac6caff8-fe10-483e-b82e-916dfead3724.png)
The indicator bar seems correct and I believe it is calculated independently of the histogram.

**Comment by Lawrence37** [comment]
I just found an older issue (#5408) which is a duplicate. Closing this one.
