### ISSUE TITLE
Canon EOS R6 Mark II Raw Crop

### ISSUE THREAD

**Issue by mvrvelous** [Beep6581/RawTherapee#6688]
Hey everyone. Photos have these black bars. Bars are the same on every photo.

![image](https://user-images.githubusercontent.com/4885001/220215492-80cd2917-87f4-4db1-8138-5905bd7497c3.png)

- 5.9
- Windows 10
- Canon R6II (RAW)

I can crop these no problem, but I'd rather have these gone. Thanks in advance!

**Comment by Lawrence37** [comment]
Hi @mvrvelous. Could you please share a sample raw file we can use to fix this issue? If the camera has multiple raw formats like CRAW or crops, share one file for each combination. I know the original R6 has CRAW and 1.6x crop modes which can be found on raw.pixls.us, but no one has uploaded samples for the R6 Mark II yet.

**Comment by mvrvelous** [comment]
Thanks. Will do!

**Comment by rebio** [comment]
Reminds me about this issue: Canon EOS R5 Raw image problems #6438
Edit: The EOS R6 Mark II is already present on https://raw.pixls.us/
