### ISSUE TITLE
Saving gigapixel image to tiff >= 16bit fails

### ISSUE THREAD

**Issue by ghost** [Beep6581/RawTherapee#6690]
I want to save an image with ~55000x27000 Pixel (1522MP). As JPEG 8 Bit works, as TIFF 8 bit works, but starting with 16 bit it fails.

Under Windows, there is no rawtherapee-debug.exe.

**How can i get log-files or debug prints of whats happening?**

RT 5.9
Windows 10 Pro 64bit 22H2

RAM usage is only one third, NVME 328GB left. So resources are free.

Thank you

**Comment by ghost** [comment]
PNG 8 and 16 bit works

**Comment by ghost** [comment]
The gigapixel input file is TIFF 16 bit ~ 8 GB.

The output sizes are:
- JPEG 8 bit ~ 592 MB
- TIFF 8 bit ~ 2.9 GB
- PNG 8 bit ~ 1.8 GB
- PNG 16 bit ~ 6.6 GB

**Comment by ghost** [comment]
Saving fails even without any modul/correction (manipulation)

BTW it fails too even if compressed or not

**Comment by ghost** [comment]
I tried with smaller versions, which works, but why does it fail?

![image](https://user-images.githubusercontent.com/126161988/221299174-394fdf1e-e22e-4b27-84b1-74c4a79ca5b9.png)

This is not a typical out-of-memory.

**Comment by Floessie** [comment]
Maybe we have to teach `libtiff` to write BigTIFF (>4GB) if necessary? Seems like 32 bit (offset) is the culprit here...

**Comment by ghost** [comment]
PLEASE 🙏🏻

**Comment by ghost** [comment]
@Floessie I am surprised that BigTIFF is opened but not written? Hope for a solution. Thank you :-)

In the meantime, I save 16 bit PNG and convert with ImageMagick. I hope that doesn't make any difference afterwards.

**Comment by Floessie** [comment]
@bediicco 
> I am surprised that BigTIFF is opened but not written?

This seems logical to me. When reading LibTIFF knows what it reads. When writing one has to tell whether it should be a classic TIFF or BigTIFF.

@Lawrence37 I had a look at the [docs](http://www.simplesystems.org/libtiff/functions/TIFFOpen.html#options): There is an `8` option for `TIFFOpen()` which we could use. As it's hard to tell the file size before it's written, this should be an option for the save dialog when TIFF is selected. There might still lurk some problems, as `width` and `height` are 31 bits (`signed int`) and there might be a multiplication somewhere. This, too, should be reviewed. Maybe I find some time for that in the weeks coming, maybe you're faster.

HTH,
Flössie

**Comment by Floessie** [comment]
@bediicco Are you able to build RT yourself? If so, please test the [`bigtiff` branch](https://github.com/Beep6581/RawTherapee/tree/bigtiff).

HTH,
Flössie

**Comment by ghost** [comment]
@Floessie oh, ok great! Only in my linux experience but will try asap on windows :)

**Comment by Floessie** [comment]
@Lawrence37 I think using `int` in [`ImageIO::saveTIFF()`](https://github.com/Beep6581/RawTherapee/blob/bigtiff/rtengine/imageio.cc#L1335) is okay. `linewidth` could be a problem for very wide images (something like more than 44.739.243 pixels :sweat_smile:).

Best,
Flössie

**Comment by Floessie** [comment]
@bediicco Then why not try it on Linux? It's easier...

**Comment by ghost** [comment]
@Floessie Can you say if RT generally runs better under Linux? I would install Linux again in parallel. My Panorama software only runs on Windows and Mac, so I currently only work with Windows.

**Comment by Floessie** [comment]
@bediicco I can't tell from personal experience, as I left the Windows camp around 1999. But I heard rumors over at PIXLS that RT on Windows isn't as performant as on Linux. But if that merits the work involving a new setup, I don't know.

**Comment by ghost** [comment]
@Floessie everything is fine, i will both give a try 👍

**Comment by ghost** [comment]
@Floessie ❤️ YOU DID IT 🥇 

![image](https://user-images.githubusercontent.com/126161988/222252539-5db4e0a0-0bba-43bf-8fad-1e37e20be3a1.png)

I tried only one image today but every kind of export.

This is the Windows Build :-)

(actually i will not try linux)

THANK YOU VERY MUCH

**Comment by Beep6581** [comment]
@bediicco which panorama software are you using?

**Comment by ghost** [comment]
@Beep6581 

I have probably tried and tested all available and use these:

https://www.tshsoft.de/de/panostudiopro_index

I have a fully silent Xeon workstation on which PSP3 runs best. A GPU brings me too much noise or is by far to expensive :-)
