### ISSUE TITLE
zoom 100% and stop (Settings)

### ISSUE THREAD

**Issue by ghost** [Beep6581/RawTherapee#6693]
Hey i love this powerful tool 🥇 

I am working in zoomlevels up to 100%, but not more. It is hard to use the mousewheel because it jumps.

Can you please make an option in the Settings like `"minimum maximum zoom"` `[0...]` `[0...100...500]`

Via fields roughly like the HTML < option > element or concrete numbers?

![image](https://user-images.githubusercontent.com/126161988/221690113-1fe506a5-b8d3-4f96-b524-1e7d02fc4fab.png)

This way anyone can set this to its perfect fit.

**Comment by ghost** [comment]
Just to make sure:

Are you aware that you can double click on the image and jump between a fit-to-screen and 100% view?

If another zoom factor is already dialed in (not fit-to-screen or 100%)  this method will first go to a fit-to-screen view.

**Comment by ghost** [comment]
Hi @jade-nl 

No, here i am only scrolling with my mousewheel, what is never perfectly good.

All in all i just want to set `max: 100%`.
But i think that others have similar different wishes so it could be changed to `min: x` `max: y`.

For me an optional `max: 100%` is all i want.

I do not want to / can not use a 1:1 button because i have to zoom up and down permanently to ckeck very large images from wider or closer view and i must see 1:1, but never > 100%.

**Comment by ghost** [comment]
@bediicco 

Until there's a solution that fits your needs using the double click method might be helpful.

The spot you double click on to get a 1:1/100% view is also centered on the screen, something that the z-key shortcut/1:1 key does not do (or only partially).

Anyway, Lawrence already put tags on this one, just have to wait until someone is willing to pick this up and work on it.

**Comment by ghost** [comment]
Thank you:)

**Comment by ghost** [comment]
After some experience i would like to (_only_) have an 100% stop mode like darktable it has - this is so helpfully.

May be, serveral settings [from] - [to] is to complicated. If someone can make this 100% stop setting please close this issue by only making this switch available :)

**Comment by 0v3rt1r3d** [comment]
Hey community! I've a wish to participate in the RawTherapee project as a contributor and decided to choose this ticket to be my good-first issue. I've already made a successfull attempt to implement it.

It looks like on the screenshot for now and works perfectly. @Lawrence37 @Beep6581 @heckflosse @Desmis (mention the most active contributors):
- Do you still think this is a worth-to-have feature?
- If yes, would have time to see my PR?

<img width="1700" alt="Screenshot 2023-10-25 at 23 17 10" src="https://github.com/Beep6581/RawTherapee/assets/21157170/4c140257-0ddd-4c8a-bdc8-6e6e2705f562">
