### ISSUE TITLE
Latest version does not run (libffw3f issue)

### ISSUE THREAD

**Issue by Souzaadauri** [Beep6581/RawTherapee#6701]
Versão 5.9-105-gae315a17 windows
não instala pois não encontra:  libffw3f_omp-3.dll

**Comment by Thanatomanic** [comment]
Please write your messages in English, not Portuguese.

As for the problem: where did you download this version?

**Comment by KirillKryukov** [comment]
I confirm the issue (assuming it's the same one). I downloaded RawTherapee executable installer:
https://github.com/Beep6581/RawTherapee/releases/download/nightly-github-actions/RawTherapee_dev_win64_release.exe

After installing, attempting to run it fails with the message:

> The code execution cannot proceed because
> libfftw3f_omp-3.dll was not found. Reinstalling the program
> may fix this problem.

The installed version seems to be "5.9-105-gae3155a17" (at least this is the directory it created for itself). Please let me know if I can provide any other details that may help fixing it.

**Comment by Souzaadauri** [comment]
The version was downloaded from https://github.com/

**Comment by Souzaadauri** [comment]
I closed it wrong.
Reporting again.
I downloaded the RawTherapee executable installer:
https://github.com/Beep6581/RawTherapee/releases/download/nightly-github-actions/RawTherapee_dev_win64_release.exe
After installation, the attempt to run it fails with the message:
Code execution cannot continue because
libfftw3f_omp-3.dll was not found. The reinstallation of the program
can fix this problem.

**Comment by Lawrence37** [comment]
It should be fixed now. Please try the latest build after it completes. Let me know if there is still an issue.

**Comment by Souzaadauri** [comment]
> Deve ser corrigido agora. Tente a compilação mais recente após a conclusão. Deixe-me saber se ainda há um problema.

Thank you. Problem solved

**Comment by KirillKryukov** [comment]
Today's nightly works. Thanks!
