### ISSUE TITLE
Color Appearance and Lighting >  Viewing Condition > Temperature doesn't update via keyboard

### ISSUE THREAD

**Issue by chaimav** [Beep6581/RawTherapee#6713]
RT Dev 5.9-126, Widows 10.
Color Appearance and Lighting >  Viewing Condition > Temperature doesn't update via keyboard properly. If I manually type a value for temperature and click enter, the value shows in the control, but the image remains unchanged and the history list doesnt show the change. 
![Viewing conditions](https://user-images.githubusercontent.com/47765782/225913203-94c0720b-b13c-4fc3-b978-c9e500cd0b0d.JPG)

Clicking on the -+ buttons will effect a change. They even change it starting at he reference point showing. This is after I click on the - once.
![Viewing conditions click once](https://user-images.githubusercontent.com/47765782/225914222-b8d16842-20de-4523-85cd-b07bdab8c965.JPG)

**Comment by Desmis** [comment]
@chaimav 
I will create a PR that will solve (I hope) this problem and improve (a little) the GUI (batch...).. In colorappearance GUI is complex
 

Thank you

Jacques

**Comment by Desmis** [comment]
https://github.com/Beep6581/RawTherapee/pull/6717
