### ISSUE TITLE
I update Msys2 - pacman -Syu - and after lib fftw  undefine reference

### ISSUE THREAD

**Issue by Desmis** [Beep6581/RawTherapee#6714]
@Lawrence37 @Thanatomanic 

I just **updated Msys2** (today 17), redid Cmake, launched Mingw64 
cmake --build . --target install
**And compilation failed - with message concerning fftw**

What did I do that I shouldn't do?
 Is there a "lib" missing on my computer? 
How do I go back?

Thank you

Jacques

I attach a screenshot below:

$ cmake --build . --target install
[1/4] Creating AboutThisBuild.txt and other version-dependent files
-- git command found: C:/msys64/usr/bin/git.exe
-- Git checkout information:
--     Commit description:    5.9-174-gc246d5b5d
--     Branch:                whitebalanceopt
--     Commit:                c246d5b5d
--     Commit date:           2023-03-15
--     Commits since tag:     174
--     Commits since branch:  174
--     Version (unreliable):  5.9.174
-- Build information:
--     Build OS:              MINGW64_NT-10.0-22624 3.4.6.x86_64 x86_64
--     Build date:            Fri, 17 Mar 2023 15:57:20 +0000 UTC
--     Epoch:                 1679068640
--     UUID:                  1d28f069-b781-45c2-84fa-b4b0bfb2424d
-- CACHE_NAME_SUFFIX is "5-dev"
[2/4] Linking CXX executable rtgui\rawtherapee-cli.exe
FAILED: rtgui/rawtherapee-cli.exe
cmd.exe /C "cd . && C:\msys64\mingw64\bin\c++.exe -std=c++11 -ffp-contract=off -march=native -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wno-attributes -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG -march=native rtgui/CMakeFiles/rth-cli.dir/myicon.rc.obj rtgui/CMakeFiles/rth-cli.dir/alignedmalloc.cc.obj rtgui/CMakeFiles/rth-cli.dir/editcallbacks.cc.obj rtgui/CMakeFiles/rth-cli.dir/main-cli.cc.obj rtgui/CMakeFiles/rth-cli.dir/multilangmgr.cc.obj rtgui/CMakeFiles/rth-cli.dir/options.cc.obj rtgui/CMakeFiles/rth-cli.dir/paramsedited.cc.obj rtgui/CMakeFiles/rth-cli.dir/pathutils.cc.obj rtgui/CMakeFiles/rth-cli.dir/threadutils.cc.obj -o rtgui\rawtherapee-cli.exe -Wl,--out-implib,rtgui\librawtherapee-cli.dll.a -Wl,--major-image-version,0,--minor-image-version,0 -LE:/code/repo-rt/rtgui/.   -LE:/code/repo-rt/rtexif rtengine/librtengine.a  -lcairomm-1.0  -lsigc-2.0  -lcairo  -lexpat  -lwinmm  -latomic  -lfftw3f  -lgiomm-2.4  -lgio-2.0  -lglibmm-2.4  -lgobject-2.0  -lglib-2.0  -lintl  -lsigc-2.0  -lgio-2.0  -lgobject-2.0  -lglib-2.0  -lintl  -lglib-2.0  -lintl  -lglibmm-2.4  -lgobject-2.0  -lglib-2.0  -lintl  -lsigc-2.0  -lgobject-2.0  -lglib-2.0  -lintl  -lgthread-2.0  -lglib-2.0  -lintl  -liptcdata  C:/msys64/mingw64/lib/libjpeg.dll.a  -llcms2  C:/msys64/mingw64/lib/libpng.dll.a  C:/msys64/mingw64/lib/libz.dll.a  C:/msys64/mingw64/lib/libtiff.dll.a  C:/msys64/mingw64/lib/libz.dll.a  -llensfun  -lrsvg-2  -lm  -lgio-2.0  -lgdk_pixbuf-2.0  -lgobject-2.0  -lglib-2.0  -lintl  -lcairo  rtexif/librtexif.a  -lws2_32 -lshlwapi  C:/msys64/mingw64/lib/libgomp.dll.a  C:/msys64/mingw64/lib/libmingwthrd.a  -lfftw3f  -lsigc-2.0  -lgio-2.0  -lglibmm-2.4  -lgobject-2.0  -lglib-2.0  -lintl  -lgthread-2.0  -liptcdata  C:/msys64/mingw64/lib/libjpeg.dll.a  -llcms2  C:/msys64/mingw64/lib/libpng.dll.a  C:/msys64/mingw64/lib/libz.dll.a  C:/msys64/mingw64/lib/libtiff.dll.a  -llensfun  -lrsvg-2  -lm  -lgdk_pixbuf-2.0  -lsigc-2.0  -lgio-2.0  -lglibmm-2.4  -lgobject-2.0  -lglib-2.0  -lintl  -lgthread-2.0  -liptcdata  C:/msys64/mingw64/lib/libjpeg.dll.a  -llcms2  C:/msys64/mingw64/lib/libpng.dll.a  C:/msys64/mingw64/lib/libz.dll.a  C:/msys64/mingw64/lib/libtiff.dll.a  -llensfun  -lrsvg-2  -lm  -lgdk_pixbuf-2.0  -lcairo  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: rtengine/librtengine.a(init.cc.obj):init.cc:(.text+0x119): undefined reference to `fftwf_cleanup_threads'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: rtengine/librtengine.a(tmo_fattal02.cc.obj):tmo_fattal02.c:(.text+0x8cbf): undefined reference to `fftwf_init_threads'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: rtengine/librtengine.a(tmo_fattal02.cc.obj):tmo_fattal02.c:(.text+0x8ccb): undefined reference to `fftwf_plan_with_nthreads'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: rtengine/librtengine.a(iplocallab.cc.obj):iplocallab.cc:(.text+0x5bed9): undefined reference to `fftwf_cleanup_threads'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: rtengine/librtengine.a(iplocallab.cc.obj):iplocallab.cc:(.text+0x5bef1): undefined reference to `fftwf_init_threads'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: rtengine/librtengine.a(iplocallab.cc.obj):iplocallab.cc:(.text+0x5befd): undefined reference to `fftwf_plan_with_nthreads'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: rtengine/librtengine.a(iplocallab.cc.obj):iplocallab.cc:(.text+0x5ce61): undefined reference to `fftwf_init_threads'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: rtengine/librtengine.a(iplocallab.cc.obj):iplocallab.cc:(.text+0x5ce6d): undefined reference to `fftwf_plan_with_nthreads'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: rtengine/librtengine.a(iplocallab.cc.obj):iplocallab.cc:(.text+0x5e551): undefined reference to `fftwf_init_threads'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: rtengine/librtengine.a(iplocallab.cc.obj):iplocallab.cc:(.text+0x5e55d): undefined reference to `fftwf_plan_with_nthreads'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: rtengine/librtengine.a(iplocallab.cc.obj):iplocallab.cc:(.text+0x5e571): undefined reference to `fftwf_cleanup_threads'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: rtengine/librtengine.a(iplocallab.cc.obj):iplocallab.cc:(.text+0x5e7e1): undefined reference to `fftwf_init_threads'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: rtengine/librtengine.a(iplocallab.cc.obj):iplocallab.cc:(.text+0x5e7ed): undefined reference to `fftwf_plan_with_nthreads'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: rtengine/librtengine.a(iplocallab.cc.obj):iplocallab.cc:(.text+0x5ce58): undefined reference to `fftwf_cleanup_threads'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: rtengine/librtengine.a(iplocallab.cc.obj):iplocallab.cc:(.text+0x5e7d6): undefined reference to `fftwf_cleanup_threads'
collect2.exe: error: ld returned 1 exit status
[3/4] Linking CXX executable rtgui\rawtherapee.exe
FAILED: rtgui/rawtherapee.exe
cmd.exe /C "cd . && C:\msys64\mingw64\bin\c++.exe -std=c++11 -ffp-contract=off -march=native -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wno-attributes -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG -march=native   -mwindows @CMakeFiles\rth.rsp -o rtgui\rawtherapee.exe -Wl,--out-implib,rtgui\librawtherapee.dll.a -Wl,--major-image-version,0,--minor-image-version,0  && cd ."
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: rtengine/librtengine.a(init.cc.obj):init.cc:(.text+0x119): undefined reference to `fftwf_cleanup_threads'

**Comment by kmilos** [comment]
`pacman -S mingw-w64-x86_64-fftw`

**Comment by Desmis** [comment]
@kmilos 

I have tried, 2 times
jdesm@PCSPECIALIST01 MSYS ~
$ pacman -S mingw-w64-x86_64-fftw
warning: mingw-w64-x86_64-fftw-3.3.10-5 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) mingw-w64-x86_64-fftw-3.3.10-5

Total Installed Size:  35.61 MiB
Net Upgrade Size:       0.00 MiB

:: Proceed with installation? [Y/n] Y
(1/1) checking keys in keyring                               [###############################] 100%
(1/1) checking package integrity                             [###############################] 100%
(1/1) loading package files                                  [###############################] 100%
(1/1) checking for file conflicts                            [###############################] 100%
(1/1) checking available disk space                          [###############################] 100%
:: Processing package changes...
(1/1) reinstalling mingw-w64-x86_64-fftw                     [###############################] 100%

But always same message
Thank you
Jacques

**Comment by kmilos** [comment]
Maybe start from scratch w/ a clean build directory then.

**Comment by Desmis** [comment]
@kmilos 

Thank you
I just create a new clone, and all works well... (I hope)

Jacques

**Comment by kmilos** [comment]
Np. It's usually not advisable to build inside the source tree itself, you should use a build folder.
