### ISSUE TITLE
Support for Sony A7R V lossless compressed RAW files

### ISSUE THREAD

**Issue by anxix** [Beep6581/RawTherapee#6726]
The current official release (5.9) doesn't support the lossless compressed RAW files generated by Sony A7R V cameras (SONY ILCE-7RM5). The camera supports these in three different resolutions:

Large: 61MP (9504×6336 pixels)
Medium: 26M (6240×4160 pixels)
Small: 15M (4752×3168 pixels)

RawTherapee cannot read these at all. https://raw.pixls.us/ contains sample images in these formats.

These files are significantly smaller than the uncompressed option, and allow selecting different resolutions as well, which is quite convenient. I have found no solutions capable of handling these files on Linux, though Lightroom for example does support them on Android.

**Comment by Benitoite** [comment]
Here I am testing https://raw.pixls.us/getfile.php/6235/nice/Sony%20-%20ILCE-7RM5%20-%2014bit%20compressed%20(3:2).ARW with the `metadata-exiv2` branch.  Seems to decode and adjust raw parameters ok.


![Screenshot 2023-03-24 at 4 52 10 PM](https://user-images.githubusercontent.com/17919239/227663662-6a390a8c-b881-49c7-9099-05e90a4c71da.png)
![Screenshot 2023-03-24 at 4 54 22 PM](https://user-images.githubusercontent.com/17919239/227663760-296cc046-de91-41f8-90fc-2523b4fa91bb.png)

**Comment by anxix** [comment]
That one works in the official 5.9 release as well. I think that's probably lossy compressed rather than lossless compressed, which is a different storage option. 
I uploaded yesterday a full new set to the website with various compression and aspect ratio options, but for some reason they don't show up (maybe there's some review process before they get listed?). Instead here are links to another online storage:

Large lossless compressed: https://drive.proton.me/urls/17CEH1EZ14#AyOMq8ZrQ1Q2
Medium lossless compressed: https://drive.proton.me/urls/NH1QW8TPXC#jHGdKnLlod8v
Small lossless compressed: https://drive.proton.me/urls/QN4EC4TJVR#JD0da8aoF2uV

These don't open in 5.9.

**Comment by anxix** [comment]
Ah, I see, the file names on raw.pixls.us are confusing - the lossless compressed files are not named compressed at all. For example https://raw.pixls.us/getfile.php/6238/nice/Sony%20-%20ILCE-7RM5%20-%204:3.ARW I think might be lossless compressed small and it doesn't open. 

Another thing I noticed is that the aspect ratio setting for the supported files is ignored by RT, but I'm not sure it's generally intended behaviour. The full 3:2 information is of course in the RAW, but I'd maybe expect the crop configured in the camera to be preselected? But this is minor and maybe intentional in RT.

**Comment by Benitoite** [comment]
I cannot open those either.. Large (85MB), Small (42MB) etc.

**Comment by kmilos** [comment]
> Another thing I noticed is that the aspect ratio setting for the supported files is ignored by RT, but I'm not sure it's generally intended behaviour. The full 3:2 information is of course in the RAW, but I'd maybe expect the crop configured in the camera to be preselected? But this is minor and maybe intentional in RT.

See also https://github.com/darktable-org/darktable/issues/8523#issuecomment-841130816 and https://github.com/darktable-org/darktable/issues/8523#issuecomment-885688715

Also, the ARW lossless "small" (and "medium" if not from APS-C crop) are actually completely different beast from lossless FF or APS-C, as they are not raw (Bayer CFA) at all, but similar to demosaiced Canon sRaw it would seem...

**Comment by Lawrence37** [comment]
Related to #6226.

> Another thing I noticed is that the aspect ratio setting for the supported files is ignored by RT, but I'm not sure it's generally intended behaviour.

Yes, it's intended. To automatically crop the image according to the settings, there would need to be a "Camera" option in the crop tool.

**Comment by tankist02** [comment]
I have Sony A7IV and RT 5.9 dev cannot open lossless compressed L files from it. The size difference between these and uncompressed is huge, e.g. 41 vs 68 MB. It would be really helpful to be able to use the lossless compression format. For comparison Darktable 4.7 dev has no problems with such images. I tried the metadata-exiv2 branch, but it also was not able to load the images. I'm familiar with Linux and C++ programming, can I help in any way?

**Comment by Lawrence37** [comment]
Hi @tankist02, thanks for your interest. The easiest way to add support would be to port the RawSpeed (I think that's what darktable uses for these images) implementation to RawTherapee's custom dcraw decoder. The first steps are of course to locate and understand the relevant RawSpeed code. If you are able to help with this, it will get the ball rolling.

FYI the current development version has everything the `metadata-exiv2` one has.

**Comment by kmilos** [comment]
The codec is actually just good old ljpeg92 (i.e. same as DNG/Canon CR2 compression, so it should be present somewhere in dcraw already), just that channels/MCUs are arranged somewhat differently (for that you can refer to RawSpeed).

**Comment by tankist02** [comment]
Hi @Lawrence37, I took a look at DCraw stuff in RT and LibRaw with RawSpeed in DT. Wow, a lot of code which is totally unfamiliar to me. I saw that Canon CR3 support was "stolen" from LibRaw as separate functions in dcraw.h in RT. Do you have something similar in mind for Sony A7IV?

**Comment by Lawrence37** [comment]
We can borrow from RawSpeed. There are a couple of snippets from RawSpeed and LibRaw in `dcraw.cc` you can refer to. Whether a separate function(s) is needed depends on how much new code is required. Just follow reasonable coding practices.

**Comment by tankist02** [comment]
> We can borrow from RawSpeed. There are a couple of snippets from RawSpeed and LibRaw in `dcraw.cc` you can refer to.

@Lawrence37 Do you refer to Canon CR3 related code or something else? How do I find these snippets?

**Comment by Lawrence37** [comment]
There are comments indicating if the code is taken from LibRaw. Example here: https://github.com/Beep6581/RawTherapee/blob/31bf942d9294bbb8bd174cd4cc77ec7c87833b91/rtengine/dcraw.cc#L6828

**Comment by Billy-** [comment]
Hi, apologies for the noise, I have just installed RT 5.10 and not able to import my ARW lossless compressed RAW files from my Sony A7IV, I see this issue is closed but I am assuming that while the issue is fixed, there is not yet a release containing the fix, would that be correct? Could anyone advise if/how I could make it work (build from source?), or if known, when a release containing the fix will come? Thank you

**Comment by tgrushka** [comment]
Same here, @Billy-  -- I found this issue: #7140 but it does not give any indication of how we can access the feature.

**Comment by tankist02** [comment]
I build RT from source code and I can open lossless compressed files from A7IV

**Comment by Lawrence37** [comment]
@Billy- Questions like yours are best asked on the official forum at https://discuss.pixls.us/c/software/rawtherapee/14. The short answer is you can look in RawPedia to find how you can [download a development build](https://rawpedia.rawtherapee.com/Download) or build from source.
