### ISSUE TITLE
Zooming to 100% crashes RawTherapee.

### ISSUE THREAD

**Issue by ghost** [Beep6581/RawTherapee#6738]
**Short description**

I ran into an image that will crash RawTherapee when zooming to 100%.
If zooming in to 100% doesn't crash it set WB to Temperature correlation when zoomed in to 100%.

Either of those (first one 90% of the time) crashes RT.

This seems to be related to the https://github.com/Beep6581/RawTherapee/pull/5889 (Adopt Exiv2 for metadata handling). If I build without that one merged I don't encounter a crash.

I did try to catch a coredump by building with *relwithdebinfo* instead of *release* but, as has happened before, RT does not crash when I do that. So I'm not sure if this one will actually be of any help: [backtrace.txt](https://github.com/Beep6581/RawTherapee/files/11150890/backtrace.txt)

If I understand my bisect correctly then this one seems to be the culprit:

```
.
.
.
.
[stasis] jade ~/.local/git/RawTherapee $ git bisect good
Bisecting: 0 revisions left to test after this (roughly 0 steps)
[3833c6e6347ad200b3053df4f323cb72c5ece16e] Merge branch 'dev' into metadata-exiv2
[stasis] jade ~/.local/git/RawTherapee $ git bisect bad
3833c6e6347ad200b3053df4f323cb72c5ece16e is the first bad commit
```

https://github.com/Beep6581/RawTherapee/pull/5889/commits/3833c6e6347ad200b3053df4f323cb72c5ece16e

Pinging @Lawrence37

---

I'm not able to test all the RAWs I have, but I did try this on about 30 or so different RAWs, initially limited to high ISO Nikon Z62 RAWs. No luck in finding any other RAWs thus far that show this behaviour.

**Steps to reproduce**

There's a 25Mb limit to what I can upload to GitHub, so: [WeTransfer link](https://we.tl/t-FWgmDjtkUo) (30Mb, valid until 11 April)

1. Build latest dev branch with https://github.com/Beep6581/RawTherapee/pull/5889  merged (and nothing else/extra),
2. Load the provided NEF,
3. Double click to zoom to 100% _or_ set WB to Temperature correlation when at 1:1,
4. RT crashes.

**Expected behavior**
RawTherapee not to crash when zooming in.

**Additional information**
* RawTherapee version : 5.9-247-gb356c2168 (latest dev branch + merged branch)

**Platform**

* OS                : Linux (kernel 5.9.15-1 x86_64 amd64)
* Distro            : Debian Buster (rel. 10.13)
* Graphics driver   : nvidia (460.39)

**Build info**

* Compiler      : gcc 8.3.0
* Cmake         : 3.18.4
* Glib          : 2.58.3-2
* Gtk+          : 3.24.5-1
* Exiv2         : 1.0.0.9
* Lensfun       : 0.3.2-4

**Build using:**

  cmake \
      -DBUNDLE_BASE_INSTALL_DIR="${localTrgtDir}" \
      -DBUILD_BUNDLE="ON" \
      -DCACHE_NAME_SUFFIX="5-dev" \
      -DCMAKE_BUILD_TYPE="release"  \
      -DBUILD_SHARED="OFF" \
      -DOPTION_OMP="ON" \
      -DPROC_TARGET_NUMBER="2" \
      -DWITH_BENCHMARK="OFF" \
      -DWITH_LTO="OFF" \
      -DWITH_PROF="OFF" \
      -DWITH_SAN="OFF" \
      -DWITH_SYSTEM_KLT="OFF" \
      -DCMAKE_C_FLAGS="-Wno-maybe-uninitialized -O3" \
      -DCMAKE_CXX_FLAGS="-Wno-maybe-uninitialized -O3" \
      .. || exit 249

**Build flags:**

    -DNDEBUG
    -O3
    -Wall
    -Wcast-qual
    -Werror=delete-incomplete
    -Werror=unknown-pragmas
    -Werror=unused-label
    -Wno-attributes
    -Wno-deprecated-declarations
    -Wno-maybe-uninitialized
    -Wno-unused-result
    -Wuninitialized
    -Wunused-macros
    -fno-math-errno
    -fopenmp
    -ftree-vectorize
    -march=native
    -std=c++11

**Comment by Floessie** [comment]
Cannot reproduce in a QEMU Debian Buster AMD64 VM, sorry. :frowning_face:

**Comment by Floessie** [comment]
It might be beneficial to locally merge `dev` into `metadata-exiv2` and to bisect on that branch.

**Comment by ghost** [comment]
@Floessie : Thanks for having a look and doing some testing on this one!

> [...]locally merge dev into metadata-exiv2 and bisect [...]

I'll give that a try later on and see what it spits out.

---

I've been trying to reproduce this one using other RAWs and am unable to do so. I've tested 50 randomly selected Nikon Z6ii RAWs I shot (the above RAW is one of my own) and another 50 random RAWs from my collection of RAWs from other cameras.

This one might be a fringe/edge case, so I'll keep this issue open until I've done some other tests and will close it afterwards if I find nothing substantial to report.

**Comment by ghost** [comment]
OK, I found the problem after systematically going through all the steps starting with a fully clean start.

Turns out that the following is a way to trigger it:

1. select the RAW in file browser, then *Processing profile operations -> clear*
2. load RAW and set a *neutral* profile
3. set *demosaicing: LMMSE  4  1  4*
4. turn on *Impulse Noise Reduction* value *50*
5. load [iso.12800.pp3.txt](https://github.com/Beep6581/RawTherapee/files/11160582/iso.12800.pp3.txt)
6. zoom to 100%

Steps 3, 4 and 5 are part of one of the dynamic rules that I have in place to give me a good starting point for different noise levels.

Now that I know what causes this I'm also able to reproduce this with some(!) other Nikon Z6ii RAWs. For those that are hit: RT doesn't always crash, though. If it does not crash the screen turns black when at 100% zoom or larger and shows the image when below 100%.

I'm only able to reproduce this with 3 images, Al from my own camera and all high ISO ones. Even now that I know what to look for I'm not able to reproduce this with any other camera (even "foreign" high ISO Nikon Z6ii's). Maybe my specific camera settings are also part of this issue.

I'm also not at all sure any longer that this issue is related to #5889 in any way! Not sure why the bisect from yesterday showed that it was (maybe the way things are merged?). I basically don't have a clue when this was introduced to be honest. 

Anyway, I'm going to close this one as it might not be worth it looking into this fringe issue, you developers have better things to do....
