### ISSUE TITLE
Unicode problem

### ISSUE THREAD

**Issue by distrair** [Beep6581/RawTherapee#6740]
**Short description**
The unicode after installation is wrong

**Steps to reproduce**
1. Just install the program for the first time 

**Expected behavior**
I can read everything

**Additional information**
- Version of RawTherapee: 5.9
- Version of operating system: Windows 11 22621.1485

Other useful information:
![image](https://user-images.githubusercontent.com/78724291/230192699-82ebebd8-16da-426a-a578-b7779d6ab758.png)

**Comment by Lawrence37** [comment]
What happens if you change the font (second row from the bottom of your screenshot on the left, the one called ``L `hmenns`` in the ``@ood`q`nbd`` section)?

**Comment by distrair** [comment]
Oh, now it looks normal, thanks!
