### ISSUE TITLE
lcp distortion correction over corrects

### ISSUE THREAD

**Issue by epadepa** [Beep6581/RawTherapee#6745]
**Short description**
Applying distortion correction from a  lcp file over corrects the image compared to Adobe Lightroom and sooc jpegs.

**Steps to reproduce**
1. Open raw file of photo taken with lens  that has visible barrel or pincushion distortion
2. Set neutral profile
3. Apply matching lcp file in the Lens/Geometry > Profiled lens correction module
4. Export jpeg
5. Compare with Adobe Lightroom exported file using the same lcp file or sooc jpeg
6. Rawtherapee exported file will show over correction

**Expected behavior**
Files exported with RT and LR should be equally corrected. When the lcp is brand approved it should also be similar to sooc jpeg.

**Additional information**
I have limited access to LR for comparisons but noticed obvious over correction of the HD Pentax-D FA 21mm LTD lens and followed up with tests using samples from dpreview with matching lcp files from the Adobe set. 

It seems the distortion correction isn't correctly implemented.

**Comment by epadepa** [comment]
Visual example using Adobe provided lcp file. (animated GIF) The difference is drastic but unfortunately the example underplays it somewhat. In reality the RT image is unusable due to extreme over correction.

![DFA21-lcp-animation](https://user-images.githubusercontent.com/25066131/231758297-3315cad8-48e3-4812-8dba-bc0ea23e3988.gif)

**Comment by Lawrence37** [comment]
I suspect this is the same as #2527. RawTherapee does apply the distortion correction correctly when distance is not a factor (tested with my own images and LCP files split from the original based on focus distance).
