### ISSUE TITLE
Support Smartphone OPPO Find X3 Pro Camera

### ISSUE THREAD

**Issue by Jexor89** [Beep6581/RawTherapee#6747]
Hi,

I can't open dng photos from my Smartphone so i uploaded photos from OPPO Find X3 Pro in dng format. I hope these photos are enough for getting support.

https://filebin.net/u8d5kimbof7g2y3k

**Comment by SimonSegerblomRex** [comment]
I think you should change the milestone to 5.10 @Lawrence37. The files decode properly on 5.8, this is just an issue with a regression in 5.9 fixed by #6739.

**Comment by Lawrence37** [comment]
Thanks for investigating @SimonSegerblomRex. That means this is technically a duplicate of #6682.
