### ISSUE TITLE
File Browser Places cluttered by devices and mounts

### ISSUE THREAD

**Issue by Jens1122** [Beep6581/RawTherapee#6750]
OpenSuSE Tumbleweed:
In RT 5.9 (also older versions) File Browser, the Favorites are filled with undeletable folders (which are partially associated with mountpoints). (See attached image)
In RT 5.9-dev (5.9-146-g3d67ca450) the situation becomes even worse. (See attached image)

This makes navigation ugly, there is also no way to move the added 'real' favorites above these entries.
![RT5 9](https://user-images.githubusercontent.com/124442783/233572313-567976a7-ab1c-4288-9caf-c4b9d1be6c78.png)
![RT5 9-dev](https://user-images.githubusercontent.com/124442783/233572341-f0f4fb7c-3427-48b1-b57b-75577a3f5bb6.png)

**Comment by Lawrence37** [comment]
The simplest solution would be to move the user-selected locations to the top. Another option is to make the sections collapsible.

Slightly unrelated: The section dividers are not visible with the default and legacy themes. This needs to be fixed for the default theme at least.

**Comment by Jens1122** [comment]
A more simple solution would be to get rid of the pre-defined mountpoints and add / delete them like any other favorites by the user if necessary.

**Comment by paulmatthijsse** [comment]
Hello, just for info. Some time ago I asked @agriggio, the maker of ART, to change this behavior and he did that. Since then, newly added 'Favs' are placed on top of that list. @Lawrence37, perhaps you can copy that code.

**Comment by Jens1122** [comment]
Any update? Current dev appimage still shows the issue.

**Comment by Lawrence37** [comment]
I don't know if anyone is working on this, but generally you will see some indication of any progress like a comment or a linked pull request. Keep in mind there are only a few people dedicating a small portion of their time to this project and there are over 900 open issues with various levels of urgency. This is, however, a good first issue to tackle for any potential new contributor who might be reading this comment 😉.

**Comment by Jens1122** [comment]
Thanks - big improvement. Just checked with dev AppImage.
Also most of the duplicates of mounted devices in the Favorites are
gone, except my home directory (entry jens in attachment).

Greetings, Jens
![Screenshot_20230809_151620](https://github.com/Beep6581/RawTherapee/assets/124442783/de263c15-bc4f-4160-a73b-e3dce340b3d7)

**Comment by hujuice** [comment]
Same point of view, here.
I love RawTherapee, but there is a strange corner upper-left in the file browser.
![image](https://github.com/Beep6581/RawTherapee/assets/761786/891ffd6c-a307-4653-8f47-4af89305b4bc)

Favorites was enough.

Best,
HUjuice

**Comment by Lawrence37** [comment]
@hujuice As of 5.10, the manually added places appear at the top of the list. Is that not enough?

**Comment by hujuice** [comment]
> @hujuice As of 5.10, the manually added places appear at the top of the list. Is that not enough?

Oh, yes. Sorry, I didn't read carefully. In my package manager I still have 5.9.
Thank you!

**Comment by hujuice** [comment]
I know it's very minor, but I prefer to add a new comment.
RawTherapee 5.10 just came in my package manager and now I have my favorites on top. Nice!
I really don't understand, anyway, the reason to have this list of non accessible (of course!) devices.
What I have there is:
- my home
- Pictures (my photos are not there)
- 6 LVM entries (I have 8), listed by size, not by name
- 4 of my hard disk names (I have 5)
- my SD card reader, even if empty
I'm sure there is a workflow producing this list, but why to not get rid of it and leave favorites only?

![image](https://github.com/Beep6581/RawTherapee/assets/761786/abfe00e4-8ee2-42bd-8788-114ad2c502bf)

I'm sorry for this comment, I really appreciate RawTherapee.

Regards,
Sergio
