### ISSUE TITLE
Wavelet Settings, a quirk in Level Selection

### ISSUE THREAD

**Issue by RolfGe** [Beep6581/RawTherapee#6752]
If you are filing a bug report, please first read the guide How to Write Useful Bug Reports:
http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports
You must provide the required information in order for your bug report to be valid.
Delete this text before posting.

**Comment by RolfGe** [comment]
**Short description**

Under Advanced > Wavelet levels > Wavelet Settings the options to select a particular level do no longer work.

**Steps to reproduce**
Hmm, reproduction is impossible, because it worked ONCE following the procedure [https://discuss.pixls.us/t/wavelet-noise-suppression-effect-not-visible-in-saved-jpeg/36423](url) answer 2. I've followed the steps mentioned there sucessfully for one file. For subsequent files it was no longer possible. 
When I select for Process > One Level and try to select from the List Level 1, level 5 is selected. I can select higher levels. System behaves like I had selected "Finer detail levels, including this level".

**Expected behavior**

Should work as described

**Additional information**
```
RawTherapee Version: 5.9
Branch: 5.9
Commit: 9b8583988
Commit date: 2022-11-27
Compiler: cc 12.2.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.24.7
Lensfun: V0.3.3.0
Build type: release
Build flags:  -std=c++11 -ffp-contract=off -mtune=generic -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wno-attributes -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags:  -mtune=generic
OpenMP support: ON
MMAP support: ON
Build OS: MINGW64_NT-10.0-20348 3.3.6-341.x86_64 x86_64
Build date: Sun, 27 Nov 2022 18:38:56 +0000 UTC
Build epoch: 1669574336
Build UUID: 9d19d210-c668-4aa2-8af6-2d527fd55d1c
```
on
```
Hostname:                                      DESKTOP-xxxxxxxxxxxxxxx
Betriebssystemname:                            Microsoft Windows 11 Home
Betriebssystemversion:                         10.0.22621 Nicht zutreffend Build 22621
Betriebssystemhersteller:                      Microsoft Corporation
Betriebssystemkonfiguration:                   Eigenständige Arbeitsstation
Betriebssystem-Buildtyp:                       Multiprocessor Free
Registrierter Benutzer:                        rolfxxxxxxxxxxxxxx
Registrierte Organisation:
Produkt-ID:                                    00326-00855-29568-AAOEM
Ursprüngliches Installationsdatum:             26.01.2023, 11:49:00
Systemstartzeit:                               26.04.2023, 10:08:52
Systemtyp:                                     x64-based PC
Prozessor(en):                                 1 Prozessor(en) installiert.
                                               [01]: Intel64 Family 6 Model 158 Stepping 13 GenuineIntel ~3696 MHz
BIOS-Version:                                  American Megatrends Inc. 3202, 10.07.2021
Windows-Verzeichnis:                           C:\WINDOWS
System-Verzeichnis:                            C:\WINDOWS\system32
Startgerät:                                    \Device\HarddiskVolume5
Systemgebietsschema:                           de;Deutsch (Deutschland)
Eingabegebietsschema:                          de;Deutsch (Deutschland)
Zeitzone:                                      (UTC+01:00) Amsterdam, Berlin, Bern, Rom, Stockholm, Wien
```
![Screenshot 2023-04-26 174230](https://user-images.githubusercontent.com/131891836/234632838-b3e4bdf3-36a1-4aa0-92c5-908a2c51eb70.png)

Picture File and Profile are available for download at [https://c.1und1.de/@520184488337087421/jev09p49SsGW9gPZu79pbQ](url)

**Comment by ghost** [comment]
This is not a bug.

You also use the *Sharp-mask and Clarity* tool that is present in the wavelets module. You wan to read this RawPedia section: [Sharp-mask and Clarity module](https://rawpedia.rawtherapee.com/Wavelet_Levels#Sharp-mask_and_Clarity_module).

In short: The moment you turn on *Sharp-mask and Clarity* you get, depending on what was chosen: *Clarity* the upper levels or *Sharp-mask*  the lower levels. The background and process settings are also hard set when using this tool.

This does influence the other wavelet tools as well. So you need to first dial in for example denoise and then use sharp-mask and clarity (not sure if those 2 go together very well, but that's a different topic).

**Comment by RolfGe** [comment]
Thanks for the information. It's always difficult when so many cross influences exist.
