### ISSUE TITLE
Image pixelated when dragging.

### ISSUE THREAD

**Issue by sun-jiao** [Beep6581/RawTherapee#6763]
**Short description**
Image pixelated when dragging.

**Steps to reproduce**
1. Open an image
2. Drag it.

**Expected behavior**
I think it should not be pixelated.

**Additional information**
![image](https://github.com/Beep6581/RawTherapee/assets/14086980/bca19fe9-1e94-4bb0-b7e8-f298e4875db9)

**Comment by radumitrescu** [comment]
I think it's supposed to happen, always was the case and I never thought this was an issue.

**Comment by Lawrence37** [comment]
Like @radumitrescu says, the pixelation is expected. Only the visible portion of the preview is rendered for speed. When you drag the preview, it shows the low resolution preview so the other parts of the image are visible.

FYI there is a feature request to preserve the full resolution preview while dragging (#956).
