### ISSUE TITLE
Panasonic	DC-S5M2 Camera Support

### ISSUE THREAD

**Issue by WarlockFish** [Beep6581/RawTherapee#6771]
I have uploaded rw2 file  by the DC-S5M2 camera to [raw.pixls.us](https://raw.pixls.us/)

Panasonic Lumix S5 Mark II is a brand new camera and it seems the format has changed.

**Comment by kmilos** [comment]
> it seems the format has changed

Yes, the v8 codec was introduced w/ the [GH6](https://github.com/Beep6581/RawTherapee/issues/6469).

**Comment by esby** [comment]
Libraw seems to support the new rw2 format , now the corresponding code will be published in their "next support schedule", I don't know exactly when this will be, I'd assume this might take a while. In the meantime, you can use Adobe Dng Converter with wine.

[Source of the information](https://www.libraw.org/node/2710)

**Comment by Lawrence37** [comment]
According to LibRaw's main web page, major releases happen every 1.5 to 2 years. The latest major release, 0.21, was announced in mid-December. It's only been half a year. The good news is that they also release public snapshots every 7 to 9 months. These snapshots contain new camera support, though it's not clear if they artificially limit which cameras are included. We'll find out which cameras are available in a few months.

I'm not well-versed in law, but I believe the license requires the source code to be distributed along with the program. RawDigger, one of LibRaw's products, already decodes this camera. I think anyone with the latest beta RawDigger has access to the code that understands the DS-S5m2 raws.

**Comment by WarlockFish** [comment]
I discovered the project  https://libopenraw.freedesktop.org/   the version of 0.35 is support for Panasonic S5M2*.  Is the libopenraw source code  suitable for assistance with this project ？ I don't know this codec  knowledge

**Comment by Lawrence37** [comment]
I'll have to chech how compatible the code is, but at least it will tell us how to decode the files. libopenraw's license is compatible with GPLv3, so that's good.

**Comment by kmilos** [comment]
> I'm not well-versed in law, but I believe the license requires the source code to be distributed along with the program. RawDigger, one of LibRaw's products, already decodes this camera. I think anyone with the latest beta RawDigger has access to the code that understands the DS-S5m2 raws.

Not necessarily, LibRaw has a dual licence choice, so RawDigger might be distributed under different terms. In any case, as you said, we'll just have to wait those couple of months for it to be published...

**Comment by kmilos** [comment]
> at least it will tell us how to decode the files

[I don't really see libopenraw added support for the actual v8 codec](https://github.com/hfiguiere/libopenraw/commits/master), just support to identify the camera?

**Comment by Lawrence37** [comment]
I'm making the assumption that RawDigger uses LibRaw. The LibRaw part is covered by LGPLv2 and/or CDDL which both require the distribution or availability of the source code.

**Comment by sgotti** [comment]
New libraw snapshot is out! Since I own this camera I'll port this to Rawtherapee dcraw ASAP...
