### ISSUE TITLE
Crash when choosing the HSVeq adj.point tool during image processing

### ISSUE THREAD

**Issue by egrochka** [Beep6581/RawTherapee#6772]
RT 5.9 on Linux (Debian 12) crashes when choosing the adjustment point selector tool in the HSV equalizer if the image is not yet done processing from any previous interactions. The crash is more likely to occur when the image is heavily processed (a lot of stuff is applied, see the left column). I don't think that the issue is related to any specific processing option and will just occur when many settings are applied at once.

A video of the crash
https://github.com/Beep6581/RawTherapee/assets/98033774/280f37ef-928c-4d3e-bfb7-f95d2834c933

A pp3 file
[test2.pp3.txt](https://github.com/Beep6581/RawTherapee/files/11772677/test2.pp3.txt)

**Comment by Lawrence37** [comment]
This sounds like #6520. Your hint about the image processing in progress allowed me to finally reproduce the issue and find the cause. The crash is happening at the same place according to the debug report shared by @rebio, so these do appear to be the same. A fix is coming right up.
