### ISSUE TITLE
JXL support

### ISSUE THREAD

**Issue by jurandfantom** [Beep6581/RawTherapee#6773]
Hi there, I saw that similar request were made 3 times, but because topic ale lock im forced to make new one instead add my 3cents up there.

Apple recently announced their support for that format ( https://blog.desdelinux.net/apple-ya-admite-el-formato-jpeg-xl-en-safari-y-ademas-presento-un-port-de-wine/ ) with make more and more people to talk about it. Of course major player (Adobe) is still not supporting JXL, but I would suggest to place JXL support as at least low level feature (compare to not being considered at all). 
Darktable is supporting that format (8, 10, 12, 16 and 32 bit) so its possible to push it indeed. 

Other thing is, this is chance to at last push superior format into masses - all because of work from small but multiple communities that make people aware and willing to ask bigger players "hey why your product don't support that ? " List of softwares that would need implement support is long, but everything starts from processed RAW picture :)

Thank you for your work - happy to see open source projects Like RT, DarkT, Blender doing such great job in terms of promoting community driven solutions.

**Comment by Lawrence37** [comment]
#6273 is still open.

**Comment by kmilos** [comment]
> (Adobe) is still not supporting JXL

They do, in some way: https://helpx.adobe.com/camera-raw/using/hdr-output.html
