### ISSUE TITLE
Canon EOS R5 white level files

### ISSUE THREAD

**Issue by johnrmoyer** [Beep6581/RawTherapee#6783]
I put white level files for Canon EOS R5 on my web server today. Those with long exposure noise reduction did not compress very well. Please let me know if they are not suitable.

https://www.rsok.com/~jrm/raw/Canon_EOS_R5_white_level.zip 

<pre>
Archive:  Canon_EOS_R5_white_level.zip
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
 4557960  Defl:N  3406199  25% 2023-06-29 07:28 994249ae  Canon_Canon EOS R5_Off_5.6_10000.cr3
 3270824  Defl:N  2137129  35% 2023-06-29 07:28 f29f1383  Canon_Canon EOS R5_Off_5.6_1000.cr3
57036760  Defl:N 55908288   2% 2023-06-29 07:27 d4c15088  Canon_Canon EOS R5_Off_5.6_100.cr3
 3415032  Defl:N  2281072  33% 2023-06-29 07:28 ac9566cb  Canon_Canon EOS R5_Off_5.6_1250.cr3
59060696  Defl:N 57939380   2% 2023-06-29 07:27 bafb753c  Canon_Canon EOS R5_Off_5.6_125.cr3
 4698976  Defl:N  3543066  25% 2023-06-29 07:28 a2e66823  Canon_Canon EOS R5_Off_5.6_12800.cr3
 4830320  Defl:N  3671141  24% 2023-06-29 07:28 d2ff24f7  Canon_Canon EOS R5_Off_5.6_16000.cr3
 3491944  Defl:N  2358349  33% 2023-06-29 07:28 016d5434  Canon_Canon EOS R5_Off_5.6_1600.cr3
31242872  Defl:N 26890505  14% 2023-06-29 07:28 485c6334  Canon_Canon EOS R5_Off_5.6_160.cr3
 4965760  Defl:N  3802563  23% 2023-06-29 07:28 acb7d4ae  Canon_Canon EOS R5_Off_5.6_20000.cr3
 3625728  Defl:N  2491028  31% 2023-06-29 07:28 a9236c74  Canon_Canon EOS R5_Off_5.6_2000.cr3
 2875224  Defl:N  1736087  40% 2023-06-29 07:28 c31c3acb  Canon_Canon EOS R5_Off_5.6_200.cr3
 3787992  Defl:N  2654971  30% 2023-06-29 07:28 9b2f064e  Canon_Canon EOS R5_Off_5.6_2500.cr3
 3030720  Defl:N  1894797  38% 2023-06-29 07:28 b1b1d9da  Canon_Canon EOS R5_Off_5.6_250.cr3
 5103976  Defl:N  3937252  23% 2023-06-29 07:28 8dacfceb  Canon_Canon EOS R5_Off_5.6_25600.cr3
 5232400  Defl:N  4061878  22% 2023-06-29 07:28 4962244e  Canon_Canon EOS R5_Off_5.6_32000.cr3
 3892616  Defl:N  2758328  29% 2023-06-29 07:28 f4606e75  Canon_Canon EOS R5_Off_5.6_3200.cr3
 3190000  Defl:N  2053843  36% 2023-06-29 07:28 e08be665  Canon_Canon EOS R5_Off_5.6_320.cr3
 5357920  Defl:N  4185168  22% 2023-06-29 07:28 e48d87a5  Canon_Canon EOS R5_Off_5.6_40000.cr3
 4025880  Defl:N  2889228  28% 2023-06-29 07:28 0c7cb827  Canon_Canon EOS R5_Off_5.6_4000.cr3
 2622264  Defl:N  1471997  44% 2023-06-29 07:28 e09bfecd  Canon_Canon EOS R5_Off_5.6_400.cr3
 4208104  Defl:N  3066204  27% 2023-06-29 07:28 7da552e9  Canon_Canon EOS R5_Off_5.6_5000.cr3
 2784120  Defl:N  1642143  41% 2023-06-29 07:28 c614f3dd  Canon_Canon EOS R5_Off_5.6_500.cr3
 5474912  Defl:N  4299141  22% 2023-06-29 07:28 2fa98b96  Canon_Canon EOS R5_Off_5.6_51200.cr3
 4285744  Defl:N  3141107  27% 2023-06-29 07:28 8d092776  Canon_Canon EOS R5_Off_5.6_6400.cr3
 2965936  Defl:N  1823436  39% 2023-06-29 07:28 4414fcd0  Canon_Canon EOS R5_Off_5.6_640.cr3
 5764088  Defl:N  4583522  21% 2023-06-29 07:28 753ca8c5  Canon_Canon EOS R5_Off_5.6_65535.cr3
 4420384  Defl:N  3271304  26% 2023-06-29 07:28 96c6c04f  Canon_Canon EOS R5_Off_5.6_8000.cr3
 3129096  Defl:N  1994397  36% 2023-06-29 07:28 d6937411  Canon_Canon EOS R5_Off_5.6_800.cr3
72807128  Defl:N 71286877   2% 2023-06-29 07:29 89157585  Canon_Canon EOS R5_On_5.6_100.cr3
77356584  Defl:N 75614450   2% 2023-06-29 07:29 f3704ed3  Canon_Canon EOS R5_On_5.6_125.cr3
62455136  Defl:N 57871865   7% 2023-06-29 07:28 c02c3f87  Canon_Canon EOS R5_On_5.6_160.cr3
45769536  Defl:N 43233634   6% 2023-06-29 07:28 0687f6e2  Canon_Canon EOS R5_On_5.6_200.cr3
49648544  Defl:N 47107090   5% 2023-06-29 07:28 d02e4eb9  Canon_Canon EOS R5_On_5.6_250.cr3
53439480  Defl:N 50920791   5% 2023-06-29 07:28 fe0a3ffb  Canon_Canon EOS R5_On_5.6_320.cr3
39587032  Defl:N 37055713   6% 2023-06-29 07:28 08f7facd  Canon_Canon EOS R5_On_5.6_400.cr3
43740568  Defl:N 41051756   6% 2023-06-29 07:28 e7ebdd38  Canon_Canon EOS R5_On_5.6_500.cr3
47697480  Defl:N 45139427   5% 2023-06-29 07:29 f8a1f765  Canon_Canon EOS R5_On_5.6_640.cr3
52609464  Defl:N 49975256   5% 2023-06-29 07:29 2013d62b  Canon_Canon EOS R5_On_5.6_800.cr3
--------          -------  ---                            -------
797459200         735150382   8%                            39 files

</pre>

**Comment by Lawrence37** [comment]
Thanks for the images. Are these dual-pixel shots? I see two frames and strangely for some images, the white and black levels appear to be different for frame 2. Could you also supply one image shot with the aperture wide open to verify the camera doesn't do any scaling based on aperture?

**Comment by johnrmoyer** [comment]
They are all dual pixel. I would expect them all to have two frames unless dual pixel is disabled at some ISOs.

So far as I can remember, the ones with Long Exposure Noise Reduction "on" save a black frame and I might expect the black frame to be different, but I do not know what the camera actually saves. Maybe dual pixel is not saved with LENR?

I might have misinterpreted: "If your camera has several raw modes, use the full one, uncropped, lossless compression if possible." The camera dual pixel processing seems a little mysterious to me even after reading patents and reading papers presented at conferences by Canon engineers. I expect the first frame to be what the camera would have saved if dual pixel had been disabled and the second frame is intended for the Canon DPP program processing. Some have reported using the second frame for highlight recovery because it is clipped differently, if I understood what they wrote. 

Do you need some that are not dual pixel?

Camera temperature also increased from 39 C to 40 C while shooting and that will have increased noise in later shots. 

I speculate that the camera might do something different with wide angle lenses because the angle will cause the light to hit more than one photosite and change the colors.

I will try to do wide open today.

**Comment by johnrmoyer** [comment]
https://www.rsok.com/~jrm/raw/Canon_EOS_R5_white_level2.zip contains one image file. 
<pre>
unzip -v Canon_EOS_R5_white_level2.zip
Archive:  Canon_EOS_R5_white_level2.zip
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
57827264  Defl:N 56700790   2% 2023-07-01 08:03 16e877b5  Canon_Canon EOS R5_Off_1.8_100.cr3
--------          -------  ---                            -------
57827264         56700790   2%                            1 file
</pre>

**Comment by Lawrence37** [comment]
I believe the two frames for dual-pixel images are for the left and right halves of the pixels. In the demosaicing options, you can select frame 1, 2, or SN mode. I don't know what effect dual-pixel has on measuring the white levels, but typically we use "normal" images, i.e. no crop, dual-pixel off, lossless compression, dynamic range settings off, etc. LENR is applied to the data before it is saved to the raw file. There's no black frame in the file.

**Comment by johnrmoyer** [comment]
Thanks for the information!

Should I do the images over without DPRAW?

**Comment by Lawrence37** [comment]
Yes, those images are useful to verify white levels between dual-pixel and non-dual-pixel shots.

**Comment by johnrmoyer** [comment]
No DPRAW

https://www.rsok.com/~jrm/raw/Canon_EOS_R5_white_level3.zip 

<pre>
unzip -v Canon_EOS_R5_white_level3.zip
Archive:  Canon_EOS_R5_white_level3.zip
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
 1814614  Defl:N   686082  62% 2023-07-01 18:59 55afcb29  Canon_Canon EOS R5_Auto_1.8_100.cr3
 2097238  Defl:N   977255  53% 2023-07-01 18:59 3e5cc856  Canon_Canon EOS R5_Auto_1.8_250.cr3
 2175062  Defl:N  1055320  52% 2023-07-01 18:59 108e4dbb  Canon_Canon EOS R5_Auto_1.8_320.cr3
 2150998  Defl:N  1031295  52% 2023-07-01 18:59 c56bd915  Canon_Canon EOS R5_Auto_1.8_800.cr3
 2870358  Defl:N  1737871  40% 2023-07-01 18:59 7bb389e7  Canon_Canon EOS R5_Off_5.6_10000.cr3
 2191446  Defl:N  1072064  51% 2023-07-01 18:58 237cb119  Canon_Canon EOS R5_Off_5.6_1000.cr3
 1782358  Defl:N   653284  63% 2023-07-01 18:57 48301642  Canon_Canon EOS R5_Off_5.6_100.cr3
 2264662  Defl:N  1144648  50% 2023-07-01 18:58 b1731f8d  Canon_Canon EOS R5_Off_5.6_1250.cr3
 1859670  Defl:N   733604  61% 2023-07-01 18:57 0f19f441  Canon_Canon EOS R5_Off_5.6_125.cr3
 2941526  Defl:N  1806787  39% 2023-07-01 18:59 9fdf8faa  Canon_Canon EOS R5_Off_5.6_12800.cr3
 3008598  Defl:N  1871771  38% 2023-07-01 18:59 d9bd5e9e  Canon_Canon EOS R5_Off_5.6_16000.cr3
 2304086  Defl:N  1184183  49% 2023-07-01 18:58 fe32d2b7  Canon_Canon EOS R5_Off_5.6_1600.cr3
 1954390  Defl:N   829458  58% 2023-07-01 18:57 085730c5  Canon_Canon EOS R5_Off_5.6_160.cr3
 3076694  Defl:N  1937427  37% 2023-07-01 18:59 617754e8  Canon_Canon EOS R5_Off_5.6_20000.cr3
 2370646  Defl:N  1250159  47% 2023-07-01 18:59 9623cf85  Canon_Canon EOS R5_Off_5.6_2000.cr3
 1992790  Defl:N   871155  56% 2023-07-01 18:58 66552c26  Canon_Canon EOS R5_Off_5.6_200.cr3
 2457174  Defl:N  1337991  46% 2023-07-01 18:59 5511f947  Canon_Canon EOS R5_Off_5.6_2500.cr3
 2070102  Defl:N   949190  54% 2023-07-01 18:58 c268b4c1  Canon_Canon EOS R5_Off_5.6_250.cr3
 3145302  Defl:N  2003588  36% 2023-07-01 18:59 9ff79197  Canon_Canon EOS R5_Off_5.6_25600.cr3
 3208278  Defl:N  2065614  36% 2023-07-01 18:59 968460f2  Canon_Canon EOS R5_Off_5.6_32000.cr3
 2510934  Defl:N  1390816  45% 2023-07-01 18:59 29bda311  Canon_Canon EOS R5_Off_5.6_3200.cr3
 2148950  Defl:N  1029026  52% 2023-07-01 18:58 53a67f59  Canon_Canon EOS R5_Off_5.6_320.cr3
 3270742  Defl:N  2125876  35% 2023-07-01 18:59 1b4988f1  Canon_Canon EOS R5_Off_5.6_40000.cr3
 2577494  Defl:N  1456156  44% 2023-07-01 18:59 a908ecef  Canon_Canon EOS R5_Off_5.6_4000.cr3
 1867350  Defl:N   739329  60% 2023-07-01 18:58 65a76ab5  Canon_Canon EOS R5_Off_5.6_400.cr3
 2678358  Defl:N  1552853  42% 2023-07-01 18:59 685f97ef  Canon_Canon EOS R5_Off_5.6_5000.cr3
 1947222  Defl:N   823550  58% 2023-07-01 18:58 b6501388  Canon_Canon EOS R5_Off_5.6_500.cr3
 3330134  Defl:N  2183080  34% 2023-07-01 18:59 9f6f146e  Canon_Canon EOS R5_Off_5.6_51200.cr3
 2732630  Defl:N  1604921  41% 2023-07-01 18:59 06441d4e  Canon_Canon EOS R5_Off_5.6_6400.cr3
 2039382  Defl:N   915235  55% 2023-07-01 18:58 bbc3776f  Canon_Canon EOS R5_Off_5.6_640.cr3
 3474006  Defl:N  2324895  33% 2023-07-01 18:59 4c1f9198  Canon_Canon EOS R5_Off_5.6_65535.cr3
 2800214  Defl:N  1670198  40% 2023-07-01 18:59 cbe11734  Canon_Canon EOS R5_Off_5.6_8000.cr3
 2121302  Defl:N  1001401  53% 2023-07-01 18:58 8205ec25  Canon_Canon EOS R5_Off_5.6_800.cr3
17514070  Defl:N 15987079   9% 2023-07-01 18:59 dde39a63  Canon_Canon EOS R5_On_5.6_100.cr3
20163158  Defl:N 18418595   9% 2023-07-01 18:59 0b553075  Canon_Canon EOS R5_On_5.6_125.cr3
22579286  Defl:N 20818898   8% 2023-07-01 18:59 0d1231fc  Canon_Canon EOS R5_On_5.6_160.cr3
23866966  Defl:N 22054340   8% 2023-07-01 18:59 5a0b1fca  Canon_Canon EOS R5_On_5.6_200.cr3
25804886  Defl:N 23982954   7% 2023-07-01 18:59 bafb7374  Canon_Canon EOS R5_On_5.6_250.cr3
27742294  Defl:N 25916108   7% 2023-07-01 18:59 35ec6780  Canon_Canon EOS R5_On_5.6_320.cr3
20797526  Defl:N 18949821   9% 2023-07-01 18:59 1d9ab551  Canon_Canon EOS R5_On_5.6_400.cr3
22921302  Defl:N 21024047   8% 2023-07-01 18:59 eabfee14  Canon_Canon EOS R5_On_5.6_500.cr3
24893526  Defl:N 23070891   7% 2023-07-01 18:59 05cc5487  Canon_Canon EOS R5_On_5.6_640.cr3
27473494  Defl:N 25600868   7% 2023-07-01 18:59 091b5edd  Canon_Canon EOS R5_On_5.6_800.cr3
--------          -------  ---                            -------
314991218         259839683  18%                            43 files
</pre>

**Comment by Lawrence37** [comment]
I've recorded the percentiles for each subframe of every dual pixel image you provided. The raw data is in the file.
[percentiles.txt](https://github.com/Beep6581/RawTherapee/files/11927727/white_levels.txt)

The data is not very interesting. For the most part, the typical white level is 16382 which is the current value in `camconst.json`. Without LENR, almost all pixels are 16382, which explains why the files are so small. LENR images have some variation due to black frame subtraction. For images shot at ISO <200, the second frames have lower white levels, starting at ~10000 for ISO 100 and gradually increasing to 16382 at ISO 200. The f/1.8 ISO 100 image shows some scaling for the second frame with a white level around 11000. Interestingly, the white level in the metadata is 12735 (normal) and 14008 (specular) for the ISO 100 shots. It's quite conservative, but still not low enough for the second frame. 

I'll check the non dual-pixel images to confirm the white levels here.

**Comment by Lawrence37** [comment]
Non dual-pixel white levels are all 16382. The only change needed is reducing the current value in `camconst.json` to account for the slight variation due to LENR. In the rare case someone wants to use the second dual-pixel frame, they can use the white-point correction in the raw tab.

**Comment by johnrmoyer** [comment]
Thanks!

**Comment by Lawrence37** [comment]
I opened a pull request for this. Thanks for providing the white frames @johnrmoyer!
