### ISSUE TITLE
dragging whilst zoomed moves too quickly

### ISSUE THREAD

**Issue by uhthomas** [Beep6581/RawTherapee#6784]
**Short description**

Dragging whilst zoomed in on a file will move the image way too much. When zoomed out, it's fine. The image follows the mouse cursor to the pixel. When zoomed in, the mouse cursor and the image are not in sync and the image flies everywhere. I was hoping the video would be more helpful, but it doesn't have the mouse cursor. I hope it shows what I'm describing though.

[Screencast from 2023-07-01 22-24-10.webm](https://github.com/Beep6581/RawTherapee/assets/9749173/1162acb2-4c8f-40a1-97a1-c2c147596ccd)

**Steps to reproduce**

See above.

**Expected behavior**

The image should follow the mouse cursor exactly.

**Additional information**

```sh
❯ paru -Q rawtherapee
rawtherapee 1:5.9-2
```

Other useful information:

I am using a scaled screen resolution. Maybe this is messing up some calculations?

**Comment by Lawrence37** [comment]
It's expected behavior. See http://rawpedia.rawtherapee.com/Preferences#Pan_Rate_Amplification to change it.
