### ISSUE TITLE
Website Down

### ISSUE THREAD

**Issue by patdavid** [Beep6581/RawTherapee#6792]
Hi all!

Just an FYI that we (pixls) have had some disk issues on our primary servers.  We are in the process of tracking down the issue and fixing things on our end, but I wanted to let y'all know that there may be a need to update DNS entries to point to a new IP.  Until we get this sorted out the primary website will be down.

Rawpedia should still run fine (it's hosted on a different machine).

Sorry for the downtime - we are working diligently to get things back up and running asap!

**Comment by shlomiv** [comment]
Wow, any news on this?
