### ISSUE TITLE
White balance seems broken on converted film negatives

### ISSUE THREAD

**Issue by AKADAP** [Beep6581/RawTherapee#6804]
**Steps to reproduce**
Open a RAW image of a film negative
![Screenshot from 2023-07-29 15-36-18](https://github.com/Beep6581/RawTherapee/assets/31718396/011a6d29-4a36-4a52-a4d7-3b95c0b54cf4)
Convert to positive
![Screenshot from 2023-07-29 15-39-05](https://github.com/Beep6581/RawTherapee/assets/31718396/563c13dd-e289-4814-9dbb-d922b09b9f16)
Attempt to adjust white balance by picking a point that should be a shade of grey
![Screenshot from 2023-07-29 15-40-29](https://github.com/Beep6581/RawTherapee/assets/31718396/8231429c-fb49-4824-bda2-0055b66336d3)
In this case, I chose the breast of a seagull. It may not be pure white, but it is not far enough off to get the results I got.
On a side note, all of the sliders for white balance seem to work reverse of the way they are marked.

**Expected behavior**
I expect the white balance to get better, not worse.

**Additional information**
- Version of RawTherapee
Version: 5.9
Branch: 5.9
Commit: 9b8583988
Commit date: 2022-11-27
Compiler: cc 7.5.0
Processor: generic x86
System: Linux
Bit depth: 64 bits
Gtkmm: V3.22.2
Lensfun: V0.3.2.0
Build type: release
Build flags:  -std=c++11 -mtune=generic -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wno-attributes -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags:  -mtune=generic
OpenMP support: ON
MMAP support: ON
Build OS: Linux 5.4.0-1094-azure x86_64
Build date: Sun, 27 Nov 2022 18:34:15 +0000 UTC
Build epoch: 1669574055
Build UUID: 2de227cc-698a-4f4c-87e5-0651b0fd79f7

- Version of your operating system
System:
  Kernel: 5.19.0-50-generic x86_64 bits: 64 compiler: N/A Desktop: Cinnamon 5.8.4 tk: GTK 3.24.33
    wm: muffin dm: LightDM Distro: Linux Mint 21.2 Victoria base: Ubuntu 22.04 jammy
Machine:
  Type: Desktop Mobo: ASRock model: X570 Creator serial: <superuser required>
    UEFI: American Megatrends v: P3.90 date: 10/19/2022
Battery:
  ID-1: hidpp_battery_0 charge: 96% condition: N/A volts: 4.1 min: N/A
    model: Logitech G903 Wired/Wireless Gaming Mouse serial: <filter> status: Charging
CPU:
  Info: 12-core model: AMD Ryzen 9 3900X bits: 64 type: MT MCP arch: Zen 2 rev: 0 cache:
    L1: 768 KiB L2: 6 MiB L3: 64 MiB
  Speed (MHz): avg: 2377 high: 4060 min/max: 2200/4672 boost: enabled cores: 1: 2200 2: 2200
    3: 3188 4: 2200 5: 2200 6: 2200 7: 2200 8: 2195 9: 2195 10: 2200 11: 2200 12: 2200 13: 2200
    14: 2200 15: 3800 16: 2200 17: 2033 18: 4060 19: 2200 20: 2200 21: 2200 22: 2200 23: 2200
    24: 2200 bogomips: 182072
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
Graphics:
  Device-1: NVIDIA GM200 [GeForce GTX 980 Ti] vendor: Micro-Star MSI driver: nvidia v: 525.125.06
    pcie: speed: 2.5 GT/s lanes: 16 ports: active: none off: DP-3,HDMI-A-1 empty: DP-1,DP-2,DVI-I-1
    bus-ID: 33:00.0 chip-ID: 10de:17c8
  Device-2: Logitech BRIO Ultra HD Webcam type: USB
    driver: hid-generic,snd-usb-audio,usbhid,uvcvideo bus-ID: 8-3:2 chip-ID: 046d:085e
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: nvidia
    unloaded: fbdev,modesetting,nouveau,vesa gpu: nvidia display-ID: :0 screens: 1
  Screen-1: 0 s-res: 6400x2160 s-dpi: 100
  Monitor-1: DP-4 pos: bottom-r res: 2560x1600 dpi: 101 diag: 756mm (29.7")
  Monitor-2: HDMI-0 pos: primary,top-left res: 3840x2160 dpi: 68 diag: 1651mm (65")
  OpenGL: renderer: NVIDIA GeForce GTX 980 Ti/PCIe/SSE2 v: 4.6.0 NVIDIA 525.125.06
    direct render: Yes
Audio:
  Device-1: NVIDIA GM200 High Definition Audio vendor: Micro-Star MSI driver: snd_hda_intel
    v: kernel pcie: speed: 8 GT/s lanes: 16 bus-ID: 33:00.1 chip-ID: 10de:0fb0
  Device-2: AMD Starship/Matisse HD Audio vendor: ASRock driver: snd_hda_intel v: kernel pcie:
    speed: 16 GT/s lanes: 16 bus-ID: 35:00.4 chip-ID: 1022:1487
  Device-3: C-Media KT01 type: USB driver: hid-generic,snd-usb-audio,usbhid bus-ID: 7-4:4
    chip-ID: 0d8c:0134
  Device-4: Logitech BRIO Ultra HD Webcam type: USB
    driver: hid-generic,snd-usb-audio,usbhid,uvcvideo bus-ID: 8-3:2 chip-ID: 046d:085e
  Sound Server-1: ALSA v: k5.19.0-50-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Intel I211 Gigabit Network vendor: ASRock driver: igb v: kernel pcie: speed: 2.5 GT/s
    lanes: 1 port: b000 bus-ID: 28:00.0 chip-ID: 8086:1539
  IF: enp40s0 state: up speed: 1000 Mbps duplex: full mac: <filter>
  Device-2: Intel Wi-Fi 6 AX200 driver: iwlwifi v: kernel pcie: speed: 5 GT/s lanes: 1
    bus-ID: 29:00.0 chip-ID: 8086:2723
  IF: wlp41s0 state: down mac: <filter>
  Device-3: Aquantia AQC107 NBase-T/IEEE 802.3bz Ethernet [AQtion] vendor: ASRock
    driver: atlantic v: kernel pcie: speed: 8 GT/s lanes: 2 port: N/A bus-ID: 2e:00.0
    chip-ID: 1d6a:07b1
  IF: enp46s0 state: down mac: <filter>
Bluetooth:
  Device-1: Intel AX200 Bluetooth type: USB driver: btusb v: 0.8 bus-ID: 5-6:2 chip-ID: 8087:0029
  Report: hciconfig ID: hci0 rfk-id: 0 state: up address: <filter> bt-v: 3.0 lmp-v: 5.2
    sub-v: 237e
RAID:
  Device-1: md1 type: mdraid level: mirror status: active size: 9.1 TiB
  Info: report: 2/2 UU blocks: 9766304768 chunk-size: N/A super-blocks: 1.2
  Components: Online: 0: sdb 1: sda
  Device-2: bpool type: zfs status: ONLINE level: mirror-0 raw: size: 1.88 GiB free: 1.2 GiB
    zfs-fs: size: 1.75 GiB free: 1.07 GiB
  Components: Online: N/A
  Device-3: rpool type: zfs status: ONLINE level: mirror-0 raw: size: 1.81 TiB free: 1.36 TiB
    zfs-fs: size: 1.76 TiB free: 1.3 TiB
  Components: Online: N/A
Drives:
  Local Storage: total: raw: 23.19 TiB usable: 15.86 TiB used: 4.13 TiB (26.1%)
  ID-1: /dev/nvme0n1 vendor: Gigabyte model: GP-ASM2NE6200TTTD size: 1.82 TiB speed: 63.2 Gb/s
    lanes: 4 serial: <filter> temp: 53.9 C
  ID-2: /dev/nvme1n1 vendor: Gigabyte model: GP-ASM2NE6200TTTD size: 1.82 TiB speed: 63.2 Gb/s
    lanes: 4 serial: <filter> temp: 54.9 C
  ID-3: /dev/sda vendor: Western Digital model: WD100EFAX-68LHPN0 size: 9.1 TiB speed: 6.0 Gb/s
    serial: <filter>
  ID-4: /dev/sdb vendor: Western Digital model: WD100EFAX-68LHPN0 size: 9.1 TiB speed: 6.0 Gb/s
    serial: <filter>
  ID-5: /dev/sdc vendor: Western Digital model: WD15EADS-00P8B0 size: 1.36 TiB speed: 3.0 Gb/s
    serial: <filter>
Partition:
  ID-1: / size: 1.31 TiB used: 8.85 GiB (0.7%) fs: zfs logical: rpool/ROOT/ubuntu_f2mgxr
  ID-2: /boot size: 1.75 GiB used: 692.9 MiB (38.7%) fs: zfs logical: bpool/BOOT/ubuntu_f2mgxr
  ID-3: /boot/efi size: 511 MiB used: 14.3 MiB (2.8%) fs: vfat dev: /dev/nvme0n1p1
  ID-4: /var/log size: 1.3 TiB used: 795.9 MiB (0.1%) fs: zfs
    logical: rpool/ROOT/ubuntu_f2mgxr/var/log
Swap:
  ID-1: swap-1 type: partition size: 2 GiB used: 0 KiB (0.0%) priority: -2 dev: /dev/nvme1n1p2
Sensors:
  System Temperatures: cpu: N/A mobo: N/A gpu: nvidia temp: 61 C
  Fan Speeds (RPM): N/A gpu: nvidia fan: 0%
Repos:
  Packages: 3018 apt: 3000 flatpak: 18
  No active apt repos in: /etc/apt/sources.list
  Active apt repos in: /etc/apt/sources.list.d/google.list
    1: deb [arch=amd64] http: //dl.google.com/linux/earth/deb/ stable main
  Active apt repos in: /etc/apt/sources.list.d/kdenlive-kdenlive-stable-jammy.list
    1: deb [arch=amd64 signed-by=/etc/apt/keyrings/kdenlive-kdenlive-stable-jammy.gpg] https: //ppa.launchpadcontent.net/kdenlive/kdenlive-stable/ubuntu jammy main
  Active apt repos in: /etc/apt/sources.list.d/mythbuntu-33-jammy.list
    1: deb [arch=amd64 signed-by=/etc/apt/keyrings/mythbuntu-33-jammy.gpg] https: //ppa.launchpadcontent.net/mythbuntu/33/ubuntu jammy main
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb https: //mirrors.ocf.berkeley.edu/linuxmint-packages victoria main upstream import backport
    2: deb http: //mirror.us-sc.kamatera.com/ubuntu jammy main restricted universe multiverse
    3: deb http: //mirror.us-sc.kamatera.com/ubuntu jammy-updates main restricted universe multiverse
    4: deb http: //mirror.us-sc.kamatera.com/ubuntu jammy-backports main restricted universe multiverse
    5: deb http: //security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
  Active apt repos in: /etc/apt/sources.list.d/skype-stable.list
    1: deb [arch=amd64] https: //repo.skype.com/deb stable main
  Active apt repos in: /etc/apt/sources.list.d/ubuntuhandbook1-audacity-jammy.list
    1: deb [arch=amd64 signed-by=/etc/apt/keyrings/ubuntuhandbook1-audacity-jammy.gpg] https: //ppa.launchpadcontent.net/ubuntuhandbook1/audacity/ubuntu jammy main
Info:
  Processes: 702 Uptime: 5h 28m Memory: 62.71 GiB used: 13.51 GiB (21.5%) Init: systemd v: 249
  runlevel: 5 Compilers: gcc: 11.3.0 alt: 11/12 Client: Cinnamon v: 5.8.4 inxi: 3.3.13

**Comment by Lawrence37** [comment]
As of version 5.9, the Film Negative tool behaves differently and the documentation on RawPedia is outdated. The White Balance tool should be used to balance the color of the backlight. White balance of the film image should be set within Film Negative itself.
