### ISSUE TITLE
Failure to compile with Clang under MSYS2

### ISSUE THREAD

**Issue by ss23** [Beep6581/RawTherapee#6821]
**Short description**
The `dev` branch builds but fails to link when compiled with Clang under MSYS2. The error is caused by the `-latomic` linker flag:
```
cmd.exe /C "cd . && C:\msys64\clang64\bin\c++.exe -std=c++11 -march=native -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wno-attributes -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -fopenmp=libomp -Werror=unknown-pragmas -O3 -DNDEBUG -march=native rtgui/CMakeFiles/rth-cli.dir/myicon.rc.obj r
tgui/CMakeFiles/rth-cli.dir/alignedmalloc.cc.obj rtgui/CMakeFiles/rth-cli.dir/editcallbacks.cc.obj rtgui/CMakeFiles/rth-cli.dir/main-cli.cc.obj rtgui/CMakeFiles/rth-cli.dir/multilangmgr.cc.obj rtgui/CMakeFiles/rth-cli.dir/options.cc.obj rtgui/CMakeFiles/rth-cli.dir/paramsedited.cc.obj rtgui/CMakeFiles/rth-cli.dir/pathutils.cc.obj rtgui/CMakeFiles/rth-cli.dir/th
readutils.cc.obj -o rtgui\rawtherapee-cli.exe -Wl,--out-implib,rtgui\librawtherapee-cli.dll.a -Wl,--major-image-version,0,--minor-image-version,0 -LC:/msys64/home/ss23/RawTherapee/rtgui/. rtengine/librtengine.a  -lcairomm-1.0  -lsigc-2.0  -lcairo  -lexpat  -lwinmm  -latomic  -lfftw3f  C:/msys64/clang64/lib/libfftw3f_omp.dll.a  -lgiomm-2.4  -lgio-2.0  -lglibmm-2
.4  -lglib-2.0  -lintl  -lgobject-2.0  -lsigc-2.0  -lgio-2.0  -lgobject-2.0  -lglib-2.0  -lintl  -lglib-2.0  -lintl  -lglibmm-2.4  -lgobject-2.0  -lsigc-2.0  -lglib-2.0  -lintl  -lgobject-2.0  -lglib-2.0  -lintl  -lgthread-2.0  -lglib-2.0  -lintl  -liptcdata  C:/msys64/clang64/lib/libjpeg.dll.a  -llcms2  -llcms2_fast_float  C:/msys64/clang64/lib/libpng.dll.a  C
:/msys64/clang64/lib/libz.dll.a  C:/msys64/clang64/lib/libtiff.dll.a  C:/msys64/clang64/lib/libz.dll.a  -llensfun  -lrsvg-2  -lm  -lgio-2.0  -lgdk_pixbuf-2.0  -lcairo  -lglib-2.0  -lintl  -lgobject-2.0  -lws2_32 -lshlwapi  C:/msys64/clang64/lib/libexiv2.dll.a  C:/msys64/clang64/lib/libomp.dll.a  -lfftw3f  C:/msys64/clang64/lib/libfftw3f_omp.dll.a  -lsigc-2.0  -
lcairo  -lgio-2.0  -lglibmm-2.4  -lglib-2.0  -lintl  -lgobject-2.0  -lgthread-2.0  -liptcdata  C:/msys64/clang64/lib/libjpeg.dll.a  -llcms2  -llcms2_fast_float  C:/msys64/clang64/lib/libpng.dll.a  C:/msys64/clang64/lib/libz.dll.a  C:/msys64/clang64/lib/libtiff.dll.a  -llensfun  -lrsvg-2  -lm  -lgdk_pixbuf-2.0  -lsigc-2.0  -lcairo  -lgio-2.0  -lglibmm-2.4  -lgli
b-2.0  -lintl  -lgobject-2.0  -lgthread-2.0  -liptcdata  C:/msys64/clang64/lib/libjpeg.dll.a  -llcms2  -llcms2_fast_float  C:/msys64/clang64/lib/libpng.dll.a  C:/msys64/clang64/lib/libz.dll.a  C:/msys64/clang64/lib/libtiff.dll.a  -llensfun  -lrsvg-2  -lm  -lgdk_pixbuf-2.0  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -la
dvapi32 && cd ."
lld: error: unable to find library -latomic
c++: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Steps to reproduce**
1. Build the project under the Clang profile of MSYS2
2. Observe linking fails

**Additional information**
The fix for this is simple -- do not include the `atomic` library flag to the linker when compiling under MSYS2 with Clang. The relevant line of code is in https://github.com/Beep6581/RawTherapee/blob/9ae8c79c3a6133b8b37a89a6a2fa2c403e834b8d/rtgui/CMakeLists.txt#L254.
Unfortunately, I don't understand what specific platforms this applies to (clearly FreeBSD and Apple platforms, but others maybe?). Someone with more experience may be able to simplify this condition to fix all platforms at once (e.g. should this just be set based on whether the platform uses Clang, rather than platform specific? FreeBSD and Apple default to Clang, but surely compiling with GCC requires the `-latomic` flag regardless of platform?)

**Comment by ss23** [comment]
Also, I can confirm that once this is changed, the project builds successfully and runs without problems (though I haven't tested extensively).

**Comment by Benitoite** [comment]
The FreeBSD Linux kernel and it’s derivative Darwin macOS kernel provide functionally atomic-looking lock spaces on their own.

mingw64 provides libatomic for gcc.

**Comment by kmilos** [comment]
> mingw64 provides libatomic for gcc

And for Clang it is built into libc++, so there is no need for standalone libatomic linkage.

**Comment by Benitoite** [comment]
This will test in cmake if either clang or AppleClang, which is the default macOS compiler.
```
if (CMAKE_CXX_COMPILER_ID MATCHES "Clang")
  # using regular Clang or AppleClang
endif()
```

Looking at the commit history this is the third we've caught this bug.  Starting with Clang 6 on an Apple, then with Clang on FreeBSD, and now Clang on Windows.
<s>` if(OPENMP_FOUND AND NOT APPLE AND NOT ${CMAKE_SYSTEM_NAME} STREQUAL "FreeBSD" AND NOT MATCHES "Clang")`</s>
But for GCC on everything needing to use `-latomic`
` if(OPENMP_FOUND AND NOT MATCHES "Clang")`
builds ok in macOS. both default AppleClang and gcc AppleClang alias wrapper at /usr/bin/gcc

**Comment by Floessie** [comment]
As the need for `-latomic` is hard to determine statically, it's often a good idea to catch this with a compile test in CMake. I was recently hit by a missing `-latomic` at work when compiling for RISC-V, which has no support for atomic 8 bit operations, so `-latomic` was necessary there.

Here is a compile test similar to those you can easily find on the internet adapted to the source's needs concerning atomicity (`bool`, `int`, and `unsigned int` in this case, RT might need other types):

```cmake
include(CheckCXXSourceCompiles)

set(ATOMIC_CXX_TEST_SOURCE
"
#include <atomic>
int main() {
	std::atomic<bool> b(false);
	std::atomic<int> i(0);
	std::atomic<unsigned int> ui(0);
	b.exchange(true);
	++i;
	return ++ui;
}
")

set(SAFE_CMAKE_REQUIRED_LIBRARIES "${CMAKE_REQUIRED_LIBRARIES}")
list(REMOVE_ITEM CMAKE_REQUIRED_LIBRARIES "atomic")

check_cxx_source_compiles("${ATOMIC_CXX_TEST_SOURCE}" HAVE_CXX_ATOMICS_WITHOUT_LIB)

if(NOT HAVE_CXX_ATOMICS_WITHOUT_LIB)
	list(APPEND CMAKE_REQUIRED_LIBRARIES "atomic")
	check_cxx_source_compiles("${ATOMIC_CXX_TEST_SOURCE}" HAVE_CXX_ATOMICS_WITH_LIB)
	if (NOT HAVE_CXX_ATOMICS_WITH_LIB)
		message(FATAL_ERROR "libatomic support needed for std::atomic<> but not found.")
	endif()
	set(ATOMIC_LIBRARIES "atomic")
	set(ATOMIC_FOUND ON)
endif()

set(CMAKE_REQUIRED_LIBRARIES "${SAFE_CMAKE_REQUIRED_LIBRARIES}")
unset(SAFE_CMAKE_REQUIRED_LIBRARIES)

mark_as_advanced(ATOMIC_LIBRARIES)
mark_as_advanced(ATOMIC_FOUND)
```

Save this as a CMake module (`FindATOMIC.cmake`), which can be used like this:

```cmake
find_package(ATOMIC)

if(ATOMIC_FOUND)
	target_link_libraries(executable ${ATOMIC_LIBRARIES})
endif()
```

HTH,
Flössie

**Comment by Benitoite** [comment]
@Floessie Yes this seems to work for the macos x86_64 gnu gcc-13/g++-13 builds. I think in a PR we could see how the CI goes...

**Comment by Benitoite** [comment]
I guess it would be ok to just comment this line out then, with the @Floessie module?

https://github.com/Beep6581/RawTherapee/blob/9ae8c79c3a6133b8b37a89a6a2fa2c403e834b8d/rtgui/CMakeLists.txt#L254

**Comment by Benitoite** [comment]
@ss23 `dev` should be linking for you now?

**Comment by barracuda156** [comment]
@Floessie Not sure which platform may need a check for 4-byte atomics support, but what _is_ needed, assuming RT uses such, is a check for 8-byte atomics. That is not guaranteed to be supported and will need `libatomic` linking on some 32-bit platforms.

P. S. By the way, there is nothing special about Apple here: macOS will not support atomics in hardware where it is not supported in hardware, so it may also need linking to `libatomic`.
