### ISSUE TITLE
Compile script started failing (Linux)

### ISSUE THREAD

**Issue by pi99y** [Beep6581/RawTherapee#6823]
Hi,
I use the automated script to compile the dev builds for Linux as described here https://rawpedia.rawtherapee.com/Linux#The_Automatic_Way This still worked just a few weeks ago but started failing in the last days.

```
Program name: rawtherapee
Build type: release
Build without updating: false

-- CMAKE_BUILD_TYPE: release
-- Checking for module 'exiv2>=0.24'
--   No package 'exiv2' found
CMake Error at /usr/share/cmake-3.18/Modules/FindPkgConfig.cmake:545 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.18/Modules/FindPkgConfig.cmake:733 (_pkg_check_modules_internal)
  CMakeLists.txt:502 (pkg_check_modules)


-- Configuring incomplete, errors occurred!
```
exiv2 0.27.3 IS installed on my system.
I'm using Devuan (5.10.0-23-amd64 #1 SMP Debian 5.10.179-3 (2023-07-27) x86_64 GNU/Linux)

Can someone please look into it? Thank you.

**Comment by Hombre57** [comment]
Hi @pi99y , have you installed the `exiv2-devel` package ?

**Comment by pi99y** [comment]
Hi @Hombre57 ! Thank you for the quick response.
I couldn't find the one you suggested, but after installing **libexiv2-dev** the compile script works again!

... is this a recent requirement, because it used to work without it. 
Perhaps https://rawpedia.rawtherapee.com/Linux#Debian/Ubuntu/Mint/elementary_OS should be updated.

Thank you!

**Comment by Hombre57** [comment]
@pi99y  Yes, the exiv2 branch has been merged to dev last week, so it's a new requirement. Someone should update the build instruction  ( @Beep6581 , if you have some time ?)

Btw, exiv2 must be compiled [with the BMFF option](https://github.com/Exiv2/exiv2#support-for-bmff-files-eg-cr3-heif-heic-avif-and-jpeg-xl) to handle CR3 Canon files.

I guess we can close this issue.
