### ISSUE TITLE
Automatic distortion correction crashes.

### ISSUE THREAD

**Issue by apostel338** [Beep6581/RawTherapee#6840]
**Short description**

Automatic distortion correction crashes.

**Steps to reproduce**

-> go to _Transform_ tab
-> _Distortion Correction_
-> hit _Automatic_
-> crash

**Expected behavior**

:-)

**Additional information**

I use the nightly AppImages from Releases/nightly-github-actions.

Testing the builds from the _Actions_ page, the first AppImage that crashes seems to be

RawTherapee_dev_5.9-438-gec12c170a_release
Merge pull request #6806 from Lawrence37/browser-preview-applied-pparams #864

The once before I've tested seem fine.

**Other useful information**

[bt.txt](https://github.com/Beep6581/RawTherapee/files/12557340/bt.txt)

**System**

Operating System: openSUSE Tumbleweed 20230902
KDE Plasma Version: 5.27.7
KDE Frameworks Version: 5.109.0
Qt Version: 5.15.10
Kernel Version: 6.4.12-1-default (64-bit)
Graphics Platform: X11
Processors: 12 × 12th Gen Intel® Core™ i5-12500T
Memory: 15.3 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics 770

**Comment by Lawrence37** [comment]
Thanks for reporting. It should be fixed now.
