### ISSUE TITLE
Color Toning shows maximum of 3 layers on first load

### ISSUE THREAD

**Issue by wilchak** [Beep6581/RawTherapee#6844]
When you first load an image for editing, and its associated profile (previously saved OR just the configured default) has more than 3 layers in the Color Toning module, the Color Toning module will only show the top 3 layers, hiding the other ones. The only way to get it to show the full list of layers is to change steps in the History module. Going backwards to any previous step (doesn't matter which step, and you only need to do it once) will suddenly cause the Color Toning module to show all the layers. The Color Toning module then works normally for the duration of the image being open.

This behavior happens every time, and with all images. It should be easy to reproduce.

I am presently using a Windows build of 5.9-151-g677aaf2ec. This has been going on for a while so unfortunately I cannot remember or pinpoint when exactly the bug was introduced, but I don't think it was in the 5.8 series. I apologize for not filing this bug report sooner.

I can supply a PP3 if you are unable to reproduce.

Here are some screenshots that I think illustrate the issue.

![1](https://github.com/Beep6581/RawTherapee/assets/2185789/0ae6b40a-3b3a-4ff0-8d81-1556d6602570)
![2](https://github.com/Beep6581/RawTherapee/assets/2185789/8013e28b-0a79-41b4-a267-76a4a85dc096)
![3](https://github.com/Beep6581/RawTherapee/assets/2185789/816c1ae0-9ad3-4351-8157-d99e6f373964)

**Comment by Lawrence37** [comment]
This is a visual bug introduced by the favorites preferences update (#6383). What's happening is the tools are not getting attached to the editor panel until the tab it belongs to is activated. The tools don't know their dimensions until that happens and therefore the Color Toning corrections list doesn't resize initially. For some reason, attaching the tool to the editor panel does not trigger a resize, so it has to be done explicitly. The following patch fixes the issue:
```diff
diff --git a/rtgui/toolpanelcoord.cc b/rtgui/toolpanelcoord.cc
index 77ac26d57..c957f605a 100644
--- a/rtgui/toolpanelcoord.cc
+++ b/rtgui/toolpanelcoord.cc
@@ -856,10 +856,15 @@ ToolPanelCoordinator::updateToolPanel(
         }
         FoldableToolPanel *tool_panel =
             getFoldableToolPanel(*new_tool_trees_iter);
-        if (tool_panel->getParent()) {
+        const bool reparent = tool_panel->getParent();
+        if (reparent) {
             tool_panel->getParent()->remove(*tool_panel->getExpander());
         }
         addPanel(panelBox, tool_panel, level);
+        if (!reparent) {
+            // If attaching for the first time, update the widget sizes.
+            tool_panel->getExpander()->check_resize();
+        }
     }

     // Update the child tools.
```
