### ISSUE TITLE
Local Adjustments not working

### ISSUE THREAD

**Issue by MarkKocherovsky** [Beep6581/RawTherapee#6848]
**Short description**
For local adjustments, showing the Delta E does not seem to work

**Steps to reproduce**
1. Create a new local adjustment
2. Add a tool to the spot
3. Begin experiments with adjustments
4. See that no changes are made

Ubuntu 22.04
Version: 5.9-452-gc380044a2
Branch: dev
Commit: c380044a2
Commit date: 2023-09-11
Compiler: cc 13.1.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.24.5
Lensfun: V0.3.2.0
Build type: release
Build flags:  -std=c++11 -ffp-contract=off -march=native -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wno-attributes -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON
Build OS: Linux 6.2.0-32-generic x86_64
Build date: Thu, 14 Sep 2023 15:23:03 +0000 UTC
Build epoch: 1694704983
Build UUID: 87c0e0e7-bbf0-4a88-9cc2-297c5314615b

![image](https://github.com/Beep6581/RawTherapee/assets/67556945/efddd6b6-47f7-43f3-bc0e-c1b0070fe3bd)

**Comment by Lawrence37** [comment]
Cannot reproduce here. Do you have Local Adjustments enabled? If so, please save and upload the pp3.
![image](https://github.com/Beep6581/RawTherapee/assets/45837045/f39ab831-020e-439c-a9dc-f758826265fa)

**Comment by MarkKocherovsky** [comment]
...I did not know it had to be specially enabled. That's embarrassing.
