### ISSUE TITLE
Compile script started failing again (Linux)

### ISSUE THREAD

**Issue by pi99y** [Beep6581/RawTherapee#6862]
Hi,
the automated script to compile the dev builds for Linux as described here https://rawpedia.rawtherapee.com/Linux#The_Automatic_Way started failing again, apparently related to lensfun...

```
Program name: rawtherapee
Build type: release
Build without updating: false

-- CMAKE_BUILD_TYPE: release
-- searching for library exiv2
--   result: /usr/lib/x86_64-linux-gnu/libexiv2.so
CMake Error at cmake/modules/FindATOMIC.cmake:17 (list):
  list sub-command REMOVE_ITEM requires list to be present.
Call Stack (most recent call first):
  CMakeLists.txt:569 (find_package)

-- searching for library lensfun
--   result: /usr/lib/x86_64-linux-gnu/liblensfun.so
-- Configuring incomplete, errors occurred!
```

I have 
```
liblensfun-data-v1/bionic,bionic,now 0.3.2-4 all [installed,automatic]
liblensfun-dev/bionic,now 0.3.2-4 amd64 [installed]
liblensfun1/bionic,now 0.3.2-4 amd64 [installed,automatic]
```
```
libexiv2-14/now 0.25-3.1ubuntu0.18.04.11 amd64 [installed,local
libexiv2-dev/now 0.25-3.1ubuntu0.18.04.11 amd64 [installed,local]
```
installed and have tested this on Ubuntu 18.04.6 LTS.

Can you please help me find what is missing.
Thanks.

**Comment by Lawrence37** [comment]
>```
>CMake Error at cmake/modules/FindATOMIC.cmake:17 (list):
>  list sub-command REMOVE_ITEM requires list to be present.
>```

Line 17 is
```list(REMOVE_ITEM CMAKE_REQUIRED_LIBRARIES "atomic")```

Maybe `CMAKE_REQUIRED_LIBRARIES` is undefined here? It doesn't make much sense to me because it looks like a CMake variable but I can't find any documentation for it.

**Comment by pi99y** [comment]
if it helps, these are the installed packages on my OS (where the compile script fails) that include word "atomic" 
```
libatomic-ops-dev/bionic,now 7.6.2-1 amd64 [installed]
libatomic1/now 8.4.0-1ubuntu1~18.04 amd64 [installed,local]
libatomic1-alpha-cross/bionic,bionic,now 8-20180414-1ubuntu2cross1 all [installed]
libatomicparsley0/bionic,now 2.1.5-6 amd64 [installed,automatic]
```

**Comment by Beep6581** [comment]
Ubuntu 18.04 LTS support ended on 2023-06. Re-open if this is still a problem in current versions.
