### ISSUE TITLE
Whitebalance / Temperature correlation (itcwb) set in batch edit exports wrong wb until file is opened in editor

### ISSUE THREAD

**Issue by epadepa** [Beep6581/RawTherapee#6867]
**Steps to reproduce**
1. Select unedited (or apply Neutral profile) image with the File Browser
2. Activate `Batch Edit` tab and set `Whitebalance` to `Temperature correlation` (note thumbnail colours)
3. Click `Put to queue` icon
4. Open the same file in Editor
5. `Put to queue` or `Save Current Image`
6. Compare the two images and note very different WB. Often the image is completely pink or otherwise off sometimes it's less noticeable.

Alternatively have a dynamic profile set the wb to Temperature correlation and export from File Browser.

**Expected behavior**
Images exported from File Browser should look like those exported from the Editor when no changes have been made. This should be the case even when the file hasn't been opened in the editor tab. 

A file with a dynamic profile set to use Temperature Correlation or the same set from batch mode should export a file where the full Temperature Correlation has been applied regardless of whether the file has been opened in the Editor.

**Additional information**
```
Version: 5.9-452-g88b0a5e45
Branch: 5.10
Commit: 88b0a5e45
Commit date: 2023-10-12
Compiler: cc 13.2.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.24.8
Lensfun: V0.3.4.0
Build type: release
Build flags: -std=c++11 -Wno-deprecated-declarations -Wno-unused-result -O3 -msse2 -std=c++11 -ffp-contract=off -march=native -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wno-attributes -flto -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags:  -march=native -flto
OpenMP support: ON
MMAP support: ON
Build OS: Linux 6.3.0-1-amd64 x86_64
Build date: Tue, 17 Oct 2023 17:06:06 +0000 UTC
Build epoch: 1697562366
Build UUID:
```

Other useful information:
It seems as if  ITCWB isn't initialized until the file is opened in the editor. Only some first step of setting a really off WB happens. The main issue with this that dynamic profiles become less useful. You have to "fully" edit all images and can't do quick exports with personal profiles.

**Comment by Desmis** [comment]
I will have a look.
But not now, I'm not at home for another fortnight

**Comment by Desmis** [comment]
@epadepa 

I think this change should solve the problem
jacques

**Comment by epadepa** [comment]
@Desmis It now works for me! Tested batch and dynamic profile on a number of photos.
