### ISSUE TITLE
local spot: history-entries in default-file

### ISSUE THREAD

**Issue by marter001** [Beep6581/RawTherapee#6870]
The following history-entries in the default file of RawTherapee_dev_5.9-459-g46e5a63b6_win64_release are not used any more:
HISTORY_MSG_498;--unused--
HISTORY_MSG_499;--unused—

in former versions they were:
HISTORY_MSG_498;Local Spot name
HISTORY_MSG_499;Local Spot visibility

Now, when working on local spots, the messages in GUI are shown like this:

![history_msg_498](https://github.com/Beep6581/RawTherapee/assets/78749513/e81d8499-083f-472b-9b1b-f431e49f8f4a)

**Comment by Lawrence37** [comment]
Good catch @marter001. It was removed in commit 2197a9b. @Beep6581, did you intend to remove the history messages altogether or was it a mistake?

**Comment by Lawrence37** [comment]
Fixed by 6ce4e69b7a97f98632476dda20619ef56f966013.

**Comment by marter001** [comment]
hmmm in 5.10-208 the same occurs again....
