### ISSUE TITLE
What was the bright idea which led to this line of code?

### ISSUE THREAD

**Issue by pbaykalov** [Beep6581/RawTherapee#6874]
https://github.com/Beep6581/RawTherapee/blob/dev/rtengine/hilite_recon.cc#L1147

Can anybody please explain why the regions with Y>whitept somehow should be brightened non-linearly?

**Comment by Lawrence37** [comment]
I don't know the algorithm, but I believe that block doesn't brighten, but actually clips the luminance at the white level.
