### ISSUE TITLE
Lensfun's vignetting correction does not work with CR2 files

### ISSUE THREAD

**Issue by MJacal** [Beep6581/RawTherapee#6879]
While the necessary data are present in the lens profile, activating vignetting correction does nothing. Devignetting works in darktable and ART (1.20.1 or later).

Steps to reproduce: all CR2 files with corresponding lens profile, that I have tried, are affected.

The issue looks to be introduced, when the exiv2 branch has been merged into dev.

I have noticed this glitch in ART some time ago, but it was fixed in the meantime; first version, that let me devignette CR2 photos, was `ART_master_1.20-16-g9565d00c0_W64_Skylake_230710`.

Last RT version without the problem, that I have been and still am using, is `RawTherapee_dev_5.9-198-g1d9225dfc_W64_Skylake_230630`.

Two PlayRaw samples can be found here:

https://discuss.pixls.us/t/loch-ard-boat-shed/32842

https://discuss.pixls.us/t/maman-et-son-chiot/34177

Windows 10/11: `RT_dev_5.9-198-g1d9225dfc` vs `RT_dev_5.9-461-g0e835e8c0`
Ubuntu Studio 23.10 virtual machine: `RT 5.9-1 build1` vs `5.9-461-g0e835e8c0` (appimage)

**Comment by Lawrence37** [comment]
Thanks for reporting. Starting with your hint that this issue existed in ART, I managed to pull the relevant fix and created a pull request for it.

**Comment by MJacal** [comment]
This certainly looks to be fixed in 5.10-rc1, works fine now.
(I only have Windows at hand.)
