### ISSUE TITLE
Reset button on Whitebalance without function?

### ISSUE THREAD

**Issue by marter001** [Beep6581/RawTherapee#6888]
RT 5.9-463
beside the drop down for Whitebalance you can find a reset button.  
Seems it is without any function, isn't it? And even it would work, to which settings it should reset? May be to "Camera"?

![grafik](https://github.com/Beep6581/RawTherapee/assets/78749513/f973ebf8-6abe-4bfd-9381-e0a77714bc7d)

What am i overlooking?

**Comment by Lawrence37** [comment]
When I click it, it resets to "Camera" on 5.9 and the latest `dev`.

**Comment by marter001** [comment]
ok, after playing around, this occured after choosing a different language in the settings and restart RT.

btw: i am on Windows 10

**Comment by Lawrence37** [comment]
I was able to reproduce it with your hint. The reset button is fixed with commit 330f998.
