### ISSUE TITLE
Update the Flatpak package in Flathub? (also thinking Steam Deck)

### ISSUE THREAD

**Issue by vrement** [Beep6581/RawTherapee#6893]
it is a bit behind https://flathub.org/apps/com.rawtherapee.RawTherapee 

I have never managed to get AppImage package to install or open or anything for that matter for some reason when i try to launch it. Flatpak opens up an easy usage on Steam Deck too! 

So please?

**Comment by Lawrence37** [comment]
Hi @vrement,

The RawTherapee team does not maintain an official Flatpak. You'll need to contact the people who are supplying the Flatpak (probably here: https://github.com/flathub/com.rawtherapee.RawTherapee). Anyway, it looks like they already have the latest version which is 5.9. 5.10 is around the corner but not officially released yet.

You may also want to open a separate issue for the AppImage problem and supply the details. There is an official AppImage of the development version in case you want to try the bleeding edge.
