### ISSUE TITLE
Tumbleweed Latest update wipes .pp3's and crop doesn't work...

### ISSUE THREAD

**Issue by OldNick** [Beep6581/RawTherapee#6897]
I'm in Tumbleweed and using the graphics repository, so I get nightly updates... all has been going quite well until now.

I discover that the .pp3 s have been wiped of information - leaving the file date-stamped from when I used it (at least the wavelet  and the *L*a*b adjustments info) and the crop function is not working... Probably other things too, but I'm too angry and disgusted to inquire further.

This is oven-level uncool.

**Comment by ghost** [comment]
Hello OldNick,

I feel sorry for your experience with RawTherapee. Maybe you would like to give us a few more information like version number inside the about dialog? There is also some kind of commit reference. I am also on tumbelweed and my information look like the following screenshot.

<img width="382" alt="grafik" src="https://github.com/Beep6581/RawTherapee/assets/201798/baf8029a-395c-4d7e-a2ab-2b07374f06dc">

**Edit**: Maybe also the last version it worked - if you remember. Thanks :-).

Thanks for your report and help.
Greetings CerebrosuS

**Comment by Lawrence37** [comment]
Hi @OldNick,

If I understand you correctly, the PP3s have been renamed to include the last-modified time, and some of the file contents like the wavelet and L\*a\*b\* adjustments are gone? If that's wrong, please clarify and share some example PP3s. Which PP3s are affected, the ones automatically saved upon editing, or those you manually saved?

RawTherapee does not add dates/times to the PP3 file names. Some other program has touched your files. My guess is some kind of backup software has restored outdated versions of the files. If your processing profile saving preferences instruct RawTherapee to save to the cache, it is possible to recover the most recent edit. Go into preferences and change the processing profile loading priority to the cache. RawTherapee will read the PP3s in the cache when you open the image in the editor. Then you can save the edit in a new PP3. If RawTherapee is not set to save to the cache, unfortunately you're out of luck unless you have a backup or snapshot somewhere.

For other issues, please file separate bug reports for each distinct issue and supply the necessary information. The crop tool works as expected for me, both in version 5.9 and the development version.

**Comment by OldNick** [comment]
I honestly don't what happened, what I know is that, in some way the .pp3's were not being taken into account... I'd also lost the icons that tell you if the image has been processed - I'm not sure where that information is stored. 
Yesterdays update righted the ship and everything appears to be normal again - Wavelets are back etc. and the "image processed" icons are back.

Also changed configuration to save pp3's to cache.

**Comment by Lawrence37** [comment]
Glad to hear things are back to normal. PP3s are applied by taking the one in the cache or the one in the image's directory with the same file name. If the PP3s were renamed, that explains why the edits didn't show.

Closing this issue as the problem cannot be solved on the RawTherapee side.
