### ISSUE TITLE
Temperature Correlation bias sliders have no effect on JPGs

### ISSUE THREAD

**Issue by chaimav** [Beep6581/RawTherapee#6902]
Currently using Dev Version: 5.9-472, Windows 10.
The 'AWB temperature bias' and 'Green refinement' sliders have no effect on jpg images but are still enabled.

(As a side point, the capillarization of the the title "**A**uto **T**emperature **c**orrelation **Setting**" is inconsistent. Recommend only 'Auto' be capitalized)

@Desmis

**Comment by Desmis** [comment]
@chaimav 

This problem has already been reported to me (this is not an excuse), but as you know I am not at all a GUI specialist.

I'll see what I can do (workaround the problem...).
The second part on the labels of "Preferences" is easy to do

**Comment by Desmis** [comment]
@chaimav 

I tinkered with something that seems to work
Branch : wbrefinement

PR https://github.com/Beep6581/RawTherapee/pull/6903

Pre-dev builds in progress
https://github.com/Beep6581/RawTherapee/releases/tag/pre-dev-github-actions

But there is probably a way to do it differently :)


Jacques

**Comment by chaimav** [comment]
@Desmis I tried the fix and it seems to work as intended. 
Thanks
