### ISSUE TITLE
Crash on launch - first installation

### ISSUE THREAD

**Issue by jvk2** [Beep6581/RawTherapee#6905]
**Short description**
I've just installed RawTherapee for the first time from the .dmg
It crashes on launch with:
Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: /Applications/RawTherapee.app/Contents/Frameworks/libomp.dylib
Referenced from: <EF39BBF0-8356-3E01-A569-E00C6D4FF14E> /Users/USER/*/RawTherapee.app/Contents/MacOS/rawtherapee
Reason: tried: '/Applications/RawTherapee.app/Contents/Frameworks/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/RawTherapee.app/Contents/Frameworks/libomp.dylib' (no such file), '/Applications/RawTherapee.app/Contents/Frameworks/libomp.dylib' (no such file), '/usr/lib/libomp.dylib' (no such file, not in dyld cache)
(terminated at launch; ignore backtrace)

**Comment by jvk2** [comment]
Sorry I've just worked it out - the program must be placed in the system apps folder, not with the licence and webloc files in a folder as is my wont.

**Comment by Lawrence37** [comment]
For record keeping purposes, I'm tagging this issue as a duplicate of #6580.
