### ISSUE TITLE
Panasonic DC-S5M2X Camera Support

### ISSUE THREAD

**Issue by pasi1** [Beep6581/RawTherapee#6909]
If you are filing a bug report, please first read the guide How to Write Useful Bug Reports:
http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports
You must provide the required information in order for your bug report to be valid.
Delete this text before posting.

**Comment by pasi1** [comment]
just black picture. its good, xnview shows it properly.
Ubuntu 22.04
rawtherapee 5.8

**Comment by Lawrence37** [comment]
I guessing it uses the same new file format as the DC-S5M2 (see #6771). LibRaw has not released a new major version or a snapshot and it looks like RawSpeed hasn't added support for the format.

@pasi1 This is unrelated, but 5.8 is a very old version. 5.9 is the current release and is about 1 year old itself. Just an FYI in case you are unaware and want to use the latest features.

**Comment by sgotti** [comment]
New libraw snapshot is out! Since I own this camera I'll port this to Rawtherapee dcraw ASAP...
