### ISSUE TITLE
multiple pp3-files

### ISSUE THREAD

**Issue by marter001** [Beep6581/RawTherapee#6910]
hi,

sometimes i cannot decide between several totally different edits and want to keep them all. Thats not a problem by saving several pp3-files.

But:
Coming back to one pic after some time, i can see from the filmstrip, that there is an edit available but i dont remeber if i did several edits on this specific pic. This i only can find out by "open profile" or a file manager.

![one_edit](https://github.com/Beep6581/RawTherapee/assets/78749513/49715c0e-4695-4c65-9fe5-df5baf9bf08c)

If there were a hint on this film-strip, showing that several relating pp3-files are beside this pic this would be a great help (at least to me)
as an example: 
![two_edits](https://github.com/Beep6581/RawTherapee/assets/78749513/4db4e18f-ba69-4da6-b7d5-d2669705fbe7)

May be it could also be possible to save the snapshots-pp3-files? I know, calling the snapshot, run "save profile" will do the trick. but then coming back to the former edit and continue from there, can cause mistakes and seems labourious, isn't it?

What do you think?

Greetings
Martin

**Comment by Lawrence37** [comment]
Would persistent snapshots (#2624) accomplish what you want?

**Comment by marter001** [comment]
oh, yes, i should get used to the search function. The discussion there includes a lot of ideas, and now i understand the difficulties why this feature is not yet available.

**Comment by Lawrence37** [comment]
Ok, closing this as a duplicate.
