### ISSUE TITLE
Export via Que gives different white balance

### ISSUE THREAD

**Issue by chaimav** [Beep6581/RawTherapee#6911]
Using the latest version, Dev 5.9-474 I get a white balance that is is different than displayed if I export via the que on this image and pp3. Exporting via the save function gives the correct output.
RAW file: https://drive.google.com/file/d/1fOpHDtlEbLccLF3JifZUify-wp8duZxc/view?usp=drive_link
save output pp3: https://drive.google.com/file/d/1oVw0HVQkU1ATMsD1iVk9U7-lV64vzPVc/view?usp=drive_link
que output pp3: https://drive.google.com/file/d/1FEQu-kOJfxn7N_RaSbmiJbK-W-oQScy3/view?usp=drive_link
![DSCF9184-save](https://github.com/Beep6581/RawTherapee/assets/47765782/22655448-67c4-42b3-9912-ae1beee87a7b)
![DSCF9184-1](https://github.com/Beep6581/RawTherapee/assets/47765782/cfc23e2c-9813-4bfc-aee3-fbb12df80027)
![save vs que](https://github.com/Beep6581/RawTherapee/assets/47765782/32d14808-f6f1-419f-9145-3e0a377b8bf5)

**Comment by Lawrence37** [comment]
Your links ask for a login. Do you have links that don't require a Google account?

**Comment by chaimav** [comment]
> Your links ask for a login. Do you have links that don't require a Google account?

Sorry about that, I forgot to change the permission. Should be good now. (I wish Github would allow more filetypes)

**Comment by Lawrence37** [comment]
Thank @chaimav, the links work now. @Desmis It looks like a problem temperature correlation AWB. There's no difference in output when I tried RGB grey and a custom white balance. Only temperature correlation is affected.

**Comment by Desmis** [comment]
@chaimav @Lawrence37 
I just tested as you suggested...

The least we can say is that it’s curious.

To make "fine" comparisons I chose the outputs in TIf and compared with Photoshop (difference layers)
With you RAF file I obtain a significant difference, visible to the eye


With 3 NEF or ORF  files about 2600K to 5000K, no differences or very, very small, not visible...
With 2 others RAF files one about 5000K, the other about 3800K  (not XT-20), no differences...or very, very small, no visible...

I will continue the investigations.... but curious.
When I use your pp3 on other files, problem appears...curious
I notices that this happens with the use of "bias"

Happy new year.

Jacques

**Comment by Desmis** [comment]
@chaimav @Lawrence37 

I think I found the culprit. 
I will create a PR this afternoon... Small change

After thinking, I'm going to make this change in the current PR relating to Temperature correlation, 

Jacques

**Comment by chaimav** [comment]
I'm not sue if the fix was supposed to be included or not, but I tried this again with dev build -504 and the bug is still present.

**Comment by Desmis** [comment]
@chaimav 

This should be fixed (I hope) by the current PR

**Comment by chaimav** [comment]
When will it be merged into the dev branch?

**Comment by Desmis** [comment]
I think, very soon (I hope).
But, you should not anticipate the updates too much, which are mandatory if you want to ensure the overall reliability of the system.

jacques

**Comment by Desmis** [comment]
@chaimav 

PR merge

Jacques

**Comment by chaimav** [comment]
I tested -506 and can confirm it works as intended. Thanks!
