### ISSUE TITLE
macos 14.2 sonoma and RT build 5.9 crash just after opening

### ISSUE THREAD

**Issue by sunolen** [Beep6581/RawTherapee#6912]
I have searched for this issue but could not find anything related. I have redownloaded the software, restarted my mac, but still have the problem. It opens fine, but after a few seconds it closes and I get an "closed unexpectedly" message. Here is the first part of the report:

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               rawtherapee-bin [1123]
Path:                  /Applications/RawTherapee.app/Contents/MacOS/bin/rawtherapee-bin
Identifier:            rawtherapee-bin
Version:               ???
Code Type:             X86-64 (Translated)
Parent Process:        launchd [1]
User ID:               503

Date/Time:             2023-12-30 15:48:56.7313 -0800
OS Version:            macOS 14.2.1 (23C71)
Report Version:        12
Anonymous UUID:        FF93FE46-C47E-A9E4-BE88-F18C1ED92166

Time Awake Since Boot: 610 seconds

System Integrity Protection: enabled

Notes:
PC register does not match crashing frame (0x0 vs 0x7FF8A3992A78)

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 6 Abort trap: 6
Terminating Process:   rawtherapee-bin [1123]

Error Formulating Crash Report:
PC register does not match crashing frame (0x0 vs 0x7FF8A3992A78)

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread

**Comment by Lawrence37** [comment]
I think RawTherapee is compatible with macOS Sonoma because someone successfully ran it (see #6880). @Benitoite can confirm. Have you tried [How to fix crashes on startup](http://rawpedia.rawtherapee.com/How_to_fix_crashes_on_startup)?

**Comment by Benitoite** [comment]
Current `5.10-release` builds available in https://r42.us/rt5 will work, 5.9 release will probably not because it was composed for a now very obsolete OS version.

**Comment by sunolen** [comment]
The new build works, problem solved. Thanks!
