### ISSUE TITLE
Adding dynamic compression to the workflow crashes RT

### ISSUE THREAD

**Issue by rebio** [Beep6581/RawTherapee#6916]
'*Short description**
When I add dynamic compression for the process, RT crashes as it develops the image in the queue. The image stays in the queue when RT crashes.

**Steps to reproduce**
There is no consistent way of reproducing the bug since it seems to be image file specific.

**Expected behavior**
No crash

**Additional information**
RawTherapee version:
- Version: 5.9-474-g255a0c708
- Branch: dev
- Commit: 255a0c708

OS info:
- Windows 10
- Version:	22H2
- Build: 19045.3803

Other useful information:
I already noticed before that RT crashed somewhat reproducable when I activated dynamic compression. 'somewhat reproducable' means that it would sometimes crash, sometimes it wouldn't (so not step by step instructions to crash RT), but if RT crashes dynamic compression was always enabled.

The file I worked on was a dng that was created with Topaz Denoise AI from a Canon R5 CR3 file. Since the file has ~250MB I can not upload it here. The CR3 file of the same image does not crash RT.
Some other dng files also crash RT, but many of them don't.

Saving the file with Ctrl + S on the Editor does also crash RT.

Since I noticed that the bug does not seem to exist as much in landscape images but more in upright images, I flipped the image 90° and this worked. I have no idea why this would work, but it did.

pp3-file: [one to crash them all.txt](https://github.com/Beep6581/RawTherapee/files/13823197/one.to.crash.them.all.txt) (it's a pp3 file, you just have to rename it)

**Comment by Lawrence37** [comment]
When you say it is not always reproducible, is it just because some files don't crash, or is it because for the files that do crash, they sometimes don't crash even with the same edit?

**Comment by rebio** [comment]
In this case for this dng file RT crashes reproducably with the same pp3 file.
Other files may or may not crash.

After some more testing for the crashes while editing a file, I get the crashes most of the time when I zoom the image.
So 1) Adjust the image (except dynamic compression) 2) activate dynamic compression 3) zoom 4) crash (not always, but it seels to do it more often than not). The crash happens when I get to ~50%.
And yet again: Portrait mode = crash. Same image + same settings in landscape mode = no crash

I can put this one step further:
1) Activate dynamic compression in full view ("F")
2) Adjust image
3) Turn dynamic compression off
4) Zoom in (RT will not crash because dynamic compression is deactivated)
5) Remain at the zoom level and jump to position 2) with your history. ("L"-tab on the left)

**Comment by Lawrence37** [comment]
Do you have a debug build which you can use to generate a crash report? Or, you can see if filebin.net accepts the DNG.

**Comment by rebio** [comment]
> Do you have a debug build which you can use to generate a crash report? Or, you can see if filebin.net accepts the DNG.

I had it in the past, but I think I have to update it since it was pre 5.9 as far as I remember. However, this will take a few days.

**Comment by rebio** [comment]
As I can no longer reproduce the bug even with the files I used following my description, I close this issue.
If the problem comes back again, I'll reopen the report.
