### ISSUE TITLE
Text Entered into IPTC "Description" Field Actually Goes into "Caption- Abstract" Field, instead of "Description" when jpg Posted to Flickr

### ISSUE THREAD

**Issue by mjohnlinden** [Beep6581/RawTherapee#6925]
RawTherapee 5.9
64-bit Windows 10 Home OS Build 19045.3930

I normally enter subject matter text into the IPTC "Description" field when using raw editors because that text will be shown in a "Description" box under the images title when the jpg is posted to Flickr. Every RAW editor I've ever used has worked that way. However, that "Description" text does not show up in the "Description" box on Flickr when I upload jpg's created by RawTherapee. Rather, at least according to Flickr's "Show EXIF" button, RawTherapee's "Description" field data is going into the "Caption- Abstract" field instead of the "Description" field. Additionally, I have not been able to identify any of RawTherapee's IPTC fields that ultimately map to Flickr's "Description" field.

*I should note that other RawTherapee IPTC fields do appear to map correctly on Flickr. For instance, text entered into the IPTC "Title" field in RawTherapee does correctly map into the "Title" box and into the "Show EXIF" "Title" field on Flickr.

How to reproduce (desired/correct operation):
1) Generate a jpg with text in the "Description" field using another raw editor (Nikon NX Studio, PhotoLab, etc.)
2) Upload the jpg to Flickr
3) Note that text entered into the "Description" field is displayed in Flickr's "Description" box just below the image's "Title" (if any)
4) Click on Flickr's "Show EXIF" button and note that the text in question is shown in the "Description" field

How to reproduce (undesired/incorrect operation):
1) Generate a jpg with text in the "Description" field using RawTherapee 5.9
2) Upload the jpg to Flickr
3) Note that text entered into the "Description" field is NOT displayed in Flickr's "Description" box just below the image's "Title" (if any)
4) Click on Flickr's "Show EXIF" button and note that the text in question is shown in the "Caption- Abstract" field, but not in the "Description" field

**Comment by Lawrence37** [comment]
Could you please provide a sample JPEG for which Flickr shows the description and also note what text is in the description field?

**Comment by mjohnlinden** [comment]
Wow! You folks are on top of this stuff! I didn’t expect someone to be looking into this so quickly.

  I’ve attached a jpg that was generated by PhotoLab 7 in which the jpg description text shows up as description text on Flickr. The “Description” text is as follows: “A warm late Fall day on the Virgil Gilman Trail. IL.”

  Thanks! -Michael
![DSC08184_DxO](https://github.com/Beep6581/RawTherapee/assets/156380572/b89e9b8e-c9ff-4a60-b25d-4e599a9a444c)

**Comment by Lawrence37** [comment]
Thanks for supplying the sample. It looks like it does not have any IPTC metadata at all. The description instead appears in the EXIF ImageDescription tag and also in the XMP Dublin Core's Description tag:
```
$ exiv2 -pa 296519289-b89e9b8e-c9ff-4a60-b25d-4e599a9a444c.jpg | grep "A warm late Fall day"
Exif.Image.ImageDescription                  Ascii      53  A warm late Fall day on the Virgil Gilman Trail. IL.
Xmp.dc.description                           LangAlt     1  lang="x-default" A warm late Fall day on the Virgil Gilman Trail. IL.
```

The [IPTC specification](https://iptc.org/std/photometadata/specification/iptc-pmd-techreference_2021.1.json) seems to have one description field which is indeed called Caption/Abstract:
```json
        "description": {
            "name": "Description",
            "ipmdschema": "IptcCore",
            "sortorder": "tp260",
            "ugtopic": "gimgcont",
            "specidx": "#description",
            "datatype": "struct",
            "dataformat": "AltLang",
            "propoccurrence": "single",
            "isrequired": "0",
            "IIMid": "2:120",
            "IIMname": "Caption/Abstract",
            "IIMmaxbytes": 2000,
            "XMPid": "dc:description",
            "EXIFid": "270",
            "SCHEMAid": "https://schema.org/caption",
            "etXMP": "XMP-dc:Description",
            "etIIM": "IPTC:Caption-Abstract",
            "etEXIF": "IFD0:ImageDescription"
        },
```
To me, RawTherapee's handling of the IPTC description is correct.

Fortunately for you, the EXIF ImageDescription is available in RawTherapee.
![image](https://github.com/Beep6581/RawTherapee/assets/45837045/4cfc24b6-fbf0-458a-8708-b4e608738224)
Does it show up in Flickr's description if you add/edit this field?

**Comment by mjohnlinden** [comment]
Hi Lawrence:
Yes, that field works for Flickr. Sorry, as this appears to have been a misunderstanding on my part regarding Exif and IPTC. I saw the Exif data, but thought it was read-only and that it wasn't relevant to what I was trying to do.  :^(

Thanks much! -Michael

**Comment by Lawrence37** [comment]
Glad to hear it works!
