### ISSUE TITLE
Sony ILCA-99M2 White Frames

### ISSUE THREAD

**Issue by UF-rss36** [Beep6581/RawTherapee#6933]
Hello,
I did upload all files:
https://filebin.net/0zdus8jbqat4c0rn

What is the next step?
UF_rss36
Thank you

Sorry for my bad english

**Comment by Lawrence37** [comment]
Thanks for the files. We will handle the rest.

**Comment by Lawrence37** [comment]
The white level across all ISOs is consistent, with minor variation due to LENR. The existing white level in `camconst.json` is sufficient so no changes are necessary.
