### ISSUE TITLE
RT still crashes / locks up after processing queue

### ISSUE THREAD

**Issue by peterfreeth** [Beep6581/RawTherapee#6946]
While processing a queue of more than about 50 images, the application locks up. The interface is completely unresponsive, moving the window leaves a trail of window fragments. The queue is still being processed in the background but the UI is unusable. After the queue has been processed, it seems the only solution is the kill the program and restart.

This doesn't happen when only a small number of images (e.g. 20) are in the queue.

** Edit - after repeated use it displays this behaviour after processing a single image

This has happened since version 5.8, I download dev versions in the hope that it has been fixed. It's the same with repo or appimage versions.

Old bug reports claim to have fixed this.

**Steps to reproduce**

Put 50 images in the queue
Start the queue
Wait

**Expected behavior**

The UI will remain usable while and after the queue is processed

**Additional information**

- Version of RawTherapee

Version: 5.9-474-g255a0c708

- Version of your operating system

Ubuntu 23.10

**Comment by Lawrence37** [comment]
Reading some of the older bug reports, I see that the GUI sometimes becomes unresponsive due to a deadlock while refreshing the file browser. Are you saving images to the folder you have open in the file browser?

**Comment by peterfreeth** [comment]
That's an excellent question. Unfortunately the answer is no, the queue outputs both jpg and pp3 files into a subfolder of the cwd, 'edits'. You do make me wonder though if the simple appearance of a single sub folder is enough to cause this. I will investigate and post my findings here.

**Comment by peterfreeth** [comment]
I tested the theory by first creating an edits folder, rather than allowing RT to create it, thus changing the structure of its own current directory. This time, I queued and processed images as I went along, 42 in total, processing the queue whilst also editing images so that there was never more than one image in the queue. At the end, there were 2 images in the queue, the UI became unresponsive whilst processing those 2 images and I had to close and restart RT. I do get the deadlock if I am still transferring raw files while also opening that folder in RT's browser, but that's not what's happening here.

**Comment by Lawrence37** [comment]
Interesting. Either there is a cumulative effect or it's random. I recently processed 48 images in the queue with v5.9, but no issues. I will try with more.

**Comment by peterfreeth** [comment]
I can't find a predictable pattern, but we also know that computers don't do random! It's locked up with just 2 images, other times it processes without complaint. I don't know how to produce better diagnostic information.

**Comment by peterfreeth** [comment]
In fact, today it is locking up with nothing in the queue. When processing images, one at a time in single editor mode, after editing a few images I get the same non responsive UI and bits of window edges left behind when I move or resize the window.

Is there a way to get more debug output?

**Comment by Floessie** [comment]
> I can't find a predictable pattern, but we also know that computers don't do random!

[Really?](https://en.wikipedia.org/wiki/RDRAND)

Joking aside, if more than one thread of execution is involved, and that is definitely the case here, everything is random when not properly designed.

Are you familiar with GDB? If so, you can attach to the stalled process and list all threads. It might be possible to pin down the deadlock with this information even on a release build. We have some info on the topic [here](https://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports#When_RawTherapee_crashes_-_An_introduction_to_stack_backtraces), albeit only for running RT under GDB not GDB attaching to the already running RT. But this can be easily found on the web.

HTH,
Flössie

**Comment by peterfreeth** [comment]
Thank you for that advice. I followed the instructions but there's nothing in the debug data that seems to coincide with the UI becoming unresponsive.

For each image processed, I see a long list of threads coming and going then finally some EXIF warnings. The queue processing will continue normally while the UI has failed.

I have attempted to add two screenshots of what happens to the UI. You can't see much, basically if I minimise the window then I get a border that trails behind the window if I move it and if I maximise the window, empty space. Everything in the UI is unresponsive apart from the window controls.

![Screenshot from 2024-02-29 18-36-22](https://github.com/Beep6581/RawTherapee/assets/34449127/4f3dffb8-b3a5-4486-a6f4-477e8c59379e)

![Screenshot from 2024-02-29 18-36-38](https://github.com/Beep6581/RawTherapee/assets/34449127/7923dac7-14a2-44a3-b3b8-8043ddf8e819)


[New Thread 0x7fffda7fc6c0 (LWP 618213)]
[New Thread 0x7fff80ff96c0 (LWP 618214)]
[New Thread 0x7fff83fff6c0 (LWP 618215)]
[New Thread 0x7fff81ffb6c0 (LWP 618216)]
[New Thread 0x7fffd9ffb6c0 (LWP 618217)]
[New Thread 0x7fffd97fa6c0 (LWP 618218)]
[New Thread 0x7fff90ff96c0 (LWP 618219)]
[New Thread 0x7fff837fe6c0 (LWP 618220)]
[New Thread 0x7fff827fc6c0 (LWP 618221)]
[New Thread 0x7fff817fa6c0 (LWP 618222)]
[New Thread 0x7fff5bfff6c0 (LWP 618223)]
[Thread 0x7fff817fa6c0 (LWP 618222) exited]
[Thread 0x7fff827fc6c0 (LWP 618221) exited]
[Thread 0x7fff837fe6c0 (LWP 618220) exited]
[Thread 0x7fff90ff96c0 (LWP 618219) exited]
[Thread 0x7fffd97fa6c0 (LWP 618218) exited]
[Thread 0x7fffd9ffb6c0 (LWP 618217) exited]
[Thread 0x7fff81ffb6c0 (LWP 618216) exited]
[Thread 0x7fff80ff96c0 (LWP 618214) exited]
[Thread 0x7fff5bfff6c0 (LWP 618223) exited]
[Thread 0x7fff83fff6c0 (LWP 618215) exited]
[Thread 0x7fffda7fc6c0 (LWP 618213) exited]
Warning: Exif tag Exif.PentaxDng.PreviewLength not encoded
Warning: Exif tag Exif.PentaxDng.PreviewOffset not encoded
Warning: Exif tag Exif.PentaxDng.PreviewResolution not encoded
Warning: Exif tag Exif.PentaxDng.0x0405 not encoded
Warning: Exif tag Exif.PentaxDng.0x0406 not encoded
Warning: Exif tag Exif.PentaxDng.0x0407 not encoded
Warning: Exif tag Exif.PentaxDng.0x040d not encoded
MSR took 336 ms

**Comment by Floessie** [comment]
As it doesn't crash but deadlocks you need to interrupt the process (usually <kbd>Ctrl</kbd>+<kbd>C</kbd>) and do the backtrace in the interrupted state. With a bit of luck this will give us a hint where the main thread hangs. If not, we need you to do a debug build and reproduce the hang there.

HTH,
Flössie

**Comment by peterfreeth** [comment]
It seems that this is now working properly in Ubuntu 24.04, unfortunately I don't know why.
