### ISSUE TITLE
Rawtherapee does not open

### ISSUE THREAD

**Issue by Korrydwenn** [Beep6581/RawTherapee#6954]
Hello, 

I can't open Rawtherapee.

![Capture d’écran 2024-02-18 à 06 35 23](https://github.com/Beep6581/RawTherapee/assets/107409084/742821bb-3f0f-4f9a-87b2-e42d04c3312e)

Many thanks for your help,

Elisabeth

**Comment by Benitoite** [comment]
We would need to see the report in order to help.

**Comment by Korrydwenn** [comment]
Hello Richard, 

Great you answer so quick!!!

I posted the screen print, here it is again: 




Something is very strange: when I put the icon in the Applications file, it becomes grey, showing a hard disk.

Kind regards
Elisabeth

**Comment by Lawrence37** [comment]
@Korrydwenn Your screenshot disappeared by using reply with email. Try replying directly on GitHub. If there is a crash report, please share it here. This comment has an example of what the report looks like: https://github.com/Beep6581/RawTherapee/issues/6912#issue-2060887058

**Comment by Benitoite** [comment]
I believe this is going to duplicate #6957

**Comment by Korrydwenn** [comment]
Hello, the screenshot is on my first mail : I add it again here below. I understand I was too quick since I can't open Rawtherapee, because I can't install it in fact. When I wan't to put the installation icon in the application files, it becomes grey, just showing hard disk.

Many thanks_
Elisabeth


[Capture d’écran 2024-02-19 à 06 38 12](https://github.com/Beep6581/RawTherapee/assets/107409084/e601283b-14cc-4e9d-a277-ff83adaa782a)

**Comment by Lawrence37** [comment]
If I'm not mistaken, if you click the blue button, it will show the crash report. Please copy the report and share it here.

**Comment by Korrydwenn** [comment]
I clicked the bue button but it doesn't do anything: it is supposed to send an message to Apple. There is no crash report.

**Comment by Korrydwenn** [comment]
This time I got a report:
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               rawtherapee [94531]
Path:                  /Applications/RawTherapee.app/Contents/MacOS/rawtherapee
Identifier:            com.rawtherapee.RawTherapee
Version:               5.10.0 (5.10.0)
Code Type:             X86-64 (Translated)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-02-21 16:10:11.7310 +0400
OS Version:            macOS 13.0 (22A380)
Report Version:        12
Anonymous UUID:        0740F970-6DF7-93C3-BCF7-BF545FCE07C3


Time Awake Since Boot: 9000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: /Applications/RawTherapee.app/Contents/Frameworks/libgomp.1.dylib
Referenced from: <8E42802E-10AD-3FF3-98CE-90C80388AEF3> /Applications/RawTherapee.app/Contents/Frameworks/libfftw3f_omp.3.dylib
Reason: tried: '/Applications/RawTherapee.app/Contents/Frameworks/libgomp.1.dylib' (code signature in <27DF851D-10AA-3150-9FA2-AD080D41BDC8> '/Applications/RawTherapee.app/Contents/Frameworks/libgomp.1.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '/System/Volumes/Preboot/Cryptexes/OS/Applications/RawTherapee.app/Contents/Frameworks/libgomp.1.dylib' (no such file), '/Applications/RawTherapee.app/Contents/Frameworks/libgomp.1.dylib' (code signature in <27DF851D-10AA-3150-9FA2-AD080D41BDC8> '/Applications/RawTherapee.app/Contents/Frameworks/libgomp.1.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '/usr/lib/libgomp.1.dylib' (no such file, no
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   Rosetta Runtime Routines	       0x104d189a8 ???
1   <translation info unavailable>	       0x104dbc7cc ???
2   dyld                          	       0x2040329c7 abort_with_payload_wrapper_internal + 82
3   dyld                          	       0x2040329f9 abort_with_payload + 9
4   dyld                          	       0x203fba1e1 dyld4::halt(char const*) + 375
5   dyld                          	       0x203fb7660 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 4502
6   dyld                          	       0x203fb6281 start + 2289

Thread 1:: com.apple.rosetta.exceptionserver
0   runtime                       	    0x7ff7ffe09750 0x7ff7ffe05000 + 18256
1   runtime                       	    0x7ff7ffe1566c 0x7ff7ffe05000 + 67180
2   runtime                       	    0x7ff7ffe1706c 0x7ff7ffe05000 + 73836


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000001   x2: 0x000000030afa9a30   x3: 0x000000000000009e
    x4: 0x000000030afa9630   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000002018dd6000
    x8: 0x000000030afa9630   x9: 0x0000000000000000  x10: 0x000000000000009e  x11: 0x000000030afa9630
   x12: 0x000000000000009e  x13: 0x000000030afa9a30  x14: 0x0000000000000001  x15: 0x0000000000000006
   x16: 0x0000000000000209  x17: 0x0000000000000000  x18: 0x800000010cd7db80  x19: 0x0000000104d0e000
   x20: 0x00000000000007ff  x21: 0x000000010cd82fa0  x22: 0xffffffffffffffff  x23: 0x0000000104d1897c
   x24: 0x00000002040329c7  x25: 0x0000000104d18248  x26: 0x0000000104dba438  x27: 0x0000000000000000
   x28: 0x000000020401983a   fp: 0x000000002c000000   lr: 0x0000000104dbc7cc
    sp: 0x000000010cd7db80   pc: 0x0000000104d189a8 cpsr: 0x80001000
   far: 0x0000000104dbc000  esr: 0x56000080  Address size fault

Binary Images:
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
       0x203fb0000 -        0x204047fff dyld (*) <0f050705-2258-3d40-b7bc-f3b35a44bbea> /usr/lib/dyld
    0x7ff7ffe05000 -     0x7ff7ffe34fff runtime (*) <6f797d84-b330-3656-9a0d-7b3dbd3f8a07> /usr/libexec/rosetta/runtime

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=430.1M resident=0K(0%) swapped_out_or_unallocated=430.1M(100%)
Writable regions: Total=157.7M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=157.7M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Rosetta Arena                     4096K        2 
Rosetta Generic                    944K      233 
Rosetta IndirectBranch              32K        1 
Rosetta JIT                      128.0M        1 
Rosetta Return Stack                20K        2 
Rosetta Thread Context              20K        2 
Stack                             8176K        1 
Stack Guard                       56.0M        1 
VM_ALLOCATE                       15.3M        7 
VM_ALLOCATE (reserved)             688K       58         reserved VM address space (unallocated)
__DATA                            15.4M      335 
__DATA_CONST                      16.8M      228 
__DATA_DIRTY                       632K       95 
__FONT_DATA                        2352        1 
__LINKEDIT                       180.1M       66 
__OBJC_RO                         65.1M        1 
__OBJC_RW                         1980K        1 
__TEXT                           250.1M      352 
dyld private memory                512K        2 
mapped file                        4.1G     1410 
===========                     =======  ======= 
TOTAL                              4.8G     2799 
TOTAL, minus reserved VM space     4.8G     2799 



-----------
Full Report
-----------

{"app_name":"rawtherapee","timestamp":"2024-02-21 16:10:12.00 +0400","app_version":"5.10.0","slice_uuid":"a129f46a-5d01-3124-be3e-2e169b97ae23","build_version":"5.10.0","platform":1,"bundleID":"com.rawtherapee.RawTherapee","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.0 (22A380)","roots_installed":0,"name":"rawtherapee","incident_id":"4BE83B0E-A55C-4F99-A8F2-365160253128"}
{
  "uptime" : 9000,
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro18,2",
  "coalitionID" : 1836,
  "osVersion" : {
    "train" : "macOS 13.0",
    "build" : "22A380",
    "releaseType" : "User"
  },
  "captureTime" : "2024-02-21 16:10:11.7310 +0400",
  "incident" : "4BE83B0E-A55C-4F99-A8F2-365160253128",
  "pid" : 94531,
  "translated" : true,
  "cpuType" : "X86-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2024-02-21 16:10:11.6668 +0400",
  "procStartAbsTime" : 217949352168,
  "procExitAbsTime" : 217950878399,
  "procName" : "rawtherapee",
  "procPath" : "\/Applications\/RawTherapee.app\/Contents\/MacOS\/rawtherapee",
  "bundleInfo" : {"CFBundleShortVersionString":"5.10.0","CFBundleVersion":"5.10.0","CFBundleIdentifier":"com.rawtherapee.RawTherapee"},
  "storeInfo" : {"deviceIdentifierForVendor":"19BB53E9-1512-5370-BA76-E9A18F37C43F","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.rawtherapee.RawTherapee",
  "crashReporterKey" : "0740F970-6DF7-93C3-BCF7-BF545FCE07C3",
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: \/Applications\/RawTherapee.app\/Contents\/Frameworks\/libgomp.1.dylib","Referenced from: <8E42802E-10AD-3FF3-98CE-90C80388AEF3> \/Applications\/RawTherapee.app\/Contents\/Frameworks\/libfftw3f_omp.3.dylib","Reason: tried: '\/Applications\/RawTherapee.app\/Contents\/Frameworks\/libgomp.1.dylib' (code signature in <27DF851D-10AA-3150-9FA2-AD080D41BDC8> '\/Applications\/RawTherapee.app\/Contents\/Frameworks\/libgomp.1.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '\/System\/Volumes\/Preboot\/Cryptexes\/OS\/Applications\/RawTherapee.app\/Contents\/Frameworks\/libgomp.1.dylib' (no such file), '\/Applications\/RawTherapee.app\/Contents\/Frameworks\/libgomp.1.dylib' (code signature in <27DF851D-10AA-3150-9FA2-AD080D41BDC8> '\/Applications\/RawTherapee.app\/Contents\/Frameworks\/libgomp.1.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '\/usr\/lib\/libgomp.1.dylib' (no such file, no"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":256841,"threadState":{"x":[{"value":6},{"value":1},{"value":13069097520},{"value":158},{"value":13069096496},{"value":0},{"value":0},{"value":137856114688},{"value":13069096496},{"value":0},{"value":158},{"value":13069096496},{"value":158},{"value":13069097520},{"value":1},{"value":6},{"value":521},{"value":0},{"value":9223372041365216128},{"value":4375764992},{"value":2047},{"value":4510461856},{"value":18446744073709551615},{"value":4375808380},{"value":8657250759,"symbolLocation":82,"symbol":"abort_with_payload_wrapper_internal"},{"value":4375806536},{"value":4376470584},{"value":0},{"value":8657147962,"symbolLocation":10,"symbol":"__abort_with_payload"}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4376479692},"cpsr":{"value":2147487744},"fp":{"value":738197504},"sp":{"value":4510440320},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":4375808424,"matchesCrashFrame":1},"far":{"value":4376477696}},"frames":[{"imageOffset":4375808424,"region":"Rosetta Runtime Routines","symbolLocation":10664,"imageIndex":0},{"imageOffset":4376479692,"region":"<translation info unavailable>","imageIndex":0},{"imageOffset":534983,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":82,"imageIndex":1},{"imageOffset":535033,"symbol":"abort_with_payload","symbolLocation":9,"imageIndex":1},{"imageOffset":41441,"symbol":"dyld4::halt(char const*)","symbolLocation":375,"imageIndex":1},{"imageOffset":30304,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":4502,"imageIndex":1},{"imageOffset":25217,"symbol":"start","symbolLocation":2289,"imageIndex":1}]},{"id":256849,"name":"com.apple.rosetta.exceptionserver","frames":[{"imageOffset":18256,"imageIndex":2},{"imageOffset":67180,"imageIndex":2},{"imageOffset":73836,"imageIndex":2}]}],
  "usedImages" : [
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 8656715776,
    "size" : 622592,
    "uuid" : "0f050705-2258-3d40-b7bc-f3b35a44bbea",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 140703126540288,
    "size" : 196608,
    "uuid" : "6f797d84-b330-3656-9a0d-7b3dbd3f8a07",
    "path" : "\/usr\/libexec\/rosetta\/runtime",
    "name" : "runtime"
  }
],
  "sharedCache" : {
  "base" : 140703329107968,
  "size" : 21474836480,
  "uuid" : "ee01862f-fb72-33bf-954c-a23866e17da6"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=430.1M resident=0K(0%) swapped_out_or_unallocated=430.1M(100%)\nWritable regions: Total=157.7M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=157.7M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nRosetta Arena                     4096K        2 \nRosetta Generic                    944K      233 \nRosetta IndirectBranch              32K        1 \nRosetta JIT                      128.0M        1 \nRosetta Return Stack                20K        2 \nRosetta Thread Context              20K        2 \nStack                             8176K        1 \nStack Guard                       56.0M        1 \nVM_ALLOCATE                       15.3M        7 \nVM_ALLOCATE (reserved)             688K       58         reserved VM address space (unallocated)\n__DATA                            15.4M      335 \n__DATA_CONST                      16.8M      228 \n__DATA_DIRTY                       632K       95 \n__FONT_DATA                        2352        1 \n__LINKEDIT                       180.1M       66 \n__OBJC_RO                         65.1M        1 \n__OBJC_RW                         1980K        1 \n__TEXT                           250.1M      352 \ndyld private memory                512K        2 \nmapped file                        4.1G     1410 \n===========                     =======  ======= \nTOTAL                              4.8G     2799 \nTOTAL, minus reserved VM space     4.8G     2799 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "63a0a6cfd1cdb67d083006d0",
      "factorPackIds" : {

      },
      "deploymentId" : 240000003
    },
    {
      "rolloutId" : "5ffde50ce2aacd000d47a95f",
      "factorPackIds" : {

      },
      "deploymentId" : 240000364
    }
  ],
  "experiments" : [

  ]
}
}

Model: MacBookPro18,2, BootROM 8419.41.10, proc 10:8:2 processors, 64 GB, SMC 
Graphics: Apple M1 Max, Apple M1 Max, Built-In
Display: ASUS VP278, 1920 x 1080 (1080p FHD - Full High Definition), Main, MirrorOff, Online
Memory Module: LPDDR5, Hynix
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4387), wl0: Sep  3 2022 02:35:52 version 20.10.965.9.8.7.129 FWID 01-b0e84a9b
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: USB 10/100/1000 LAN, Ethernet, en6
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB3.1 Hub
USB Device: USB 10/100/1000 LAN
USB Device: USB 2.0 Hub
USB Device: USB2.1 Hub
USB Device: USB OPTICAL MOUSE
USB Device: USB Backlit Keyboard
USB Device: USB C Video Adaptor
USB Device: USB31Bus
USB Device: Mobile Drive
Thunderbolt Bus: Laptop, Apple Inc.
Thunderbolt Bus: Laptop, Apple Inc.
Thunderbolt Bus: Laptop, Apple Inc.

**Comment by Lawrence37** [comment]
Thanks @Korrydwenn. It's the same issue as #6957. Closing this one as a duplicate because the other one has the crash details in the original post.

**Comment by Korrydwenn** [comment]
Thanks Lawrence!
