### ISSUE TITLE
Icon of hand-tool toggles when using local adjustments

### ISSUE THREAD

**Issue by marter001** [Beep6581/RawTherapee#6955]

**Comment by marter001** [comment]
The icon of the hand tool in favorites is showing a hand as it should.
Only when activating the local adjustments there appears another icon and the tooltip still is "hand-tool". 

![toggle](https://github.com/Beep6581/RawTherapee/assets/78749513/4d68c31a-c263-44dd-a350-53e1b6fae888)

expected behaviour: no changes of the icon

RT 5.10-63

**Comment by Pandagrapher** [comment]
@marter001 
In fact, the icon behavior is correct: "hand-tool" indicates that an edit widget is displayed on picture. For other tools such as spot correction, a button shall be clicked on tool to show the edit widgets. With local adjustments, as all the tool deals with edit widgets, this is automatically done when switching to or from the local adjustments tab.
