### ISSUE TITLE
Enhancing usability of 'edit current image in external editor' invocation icons/buttons

### ISSUE THREAD

**Issue by LateJunction** [Beep6581/RawTherapee#6968]
<!-- READ THIS FIRST

I spent some hours trying to invoke an external editor from RT (version doesn't matter, but it is 5.10 Windows build of 24 Feb 24). I was about to submit a detail request for help to Pixls.us when I realised, completely by accident, that I was not actually requesting the invocation of the external editor I had chosen. I was clicking only on the 'down arrow' part of what I thought was a single icon, combining a 'down arrow' and a 'paint palette'. I should have been clicking on what appears to be a separate 'paint palette' icon to the left of the 'down arrow' icon. The chosen external editor is then invoked to expectation.

My suggested improvement is to provide a pixel or three separation between these two icons. There appears to be enough real-estate here, either to the  left of the 'floppy disk' icon or to the left of the box which. on my system, says 'Ready'.

This separation would make it clear (which my reading of Rawpedia didn't) that one has to first choose/set  the external editor to be invoked (if there is more than one), using the down arrow, and then invoke it using the paint palette.

As to How to implement this suggestion, it would be presumptuous in the extreme with somebody with my (lack of) skill level to make any comment on this.

**Comment by Lawrence37** [comment]
Please elaborate on your proposal. It's not clear from the title what the current implementation is lacking and what the desired features are.

**Comment by LateJunction** [comment]
I didn't try to make the title provide the information you have requested - there is not enough space for that. I worded the title to engage the attention of the reader. The remainder of my submission is, however, clearly not sufficient, in detail or understand-ability. I trust what follows addresses this weakness:

In the latest version of RT available to me (v5.10; commit 8abd5439d) there are three clickable 'buttons' at the foot of the screen, in the bottom left corner, which are immediately to the right of the '+' and '-' icons associated with and immediately below the Snapshots. These three clickable buttons are, reading left to right,  a 'floppy disk', then a pair of toothed gears and, right-most, a clickable area that contains two icons - a 'paint palette' to the left and a 'down arrow' to the right. 

The first two of the three clickable buttons just listed are square in shape, are not outlined and each contains a single icon. The third  clickable area is rectangular, outlined by a single pixel wide black line and contains two icons. This is what leads to a potential usability issue. Although it is just one clickable area or button, this area has two distinctly different actions. The icon to the right - the down arrow - using approximately 30% of the outlined area, has the function of selecting from a (potential) list of external editors and other applications that have been defined in the preferences dialog. The icon to the left - the paint palette -  using approximately 70% of the outlined area, has the action of invoking the selected external application and passing the current image to it. 

These two parts of the rectangular area are back-lit independently on mouse-over. This effect, which essentially tells the user which part is being selected, is not distinct (just as it is not on the 'floppy disk' and 'gear' icons to the left), especially for those with a low resolution monitor and/or less then acute eyesight. The back lighting is also masked by the brightness of the mouse pointer I have selected, for eyesight reasons, on my system. These users might think that, having selected the external application, one only has to click somewhere on this rectangular, outlined, clickable area in general to invoke that external application. 

This caused me to spend quite a few hours trying to understand why neither Photoshop nor GIMP were being invoked from my windows version of RT, even though the command definitions  within RT preferences were valid and effective when issued in a command line outside RT. The reason for the external app not being invoked was because RT interpreted my mouse action as being on the 'down arrow' rather than on the 'paint palette', while I saw the mouse action as being on this one rectangular area.

This usability issue would not arise if this rectangular area was split into two distinctly separate clickable areas, possibly each with a single pixel wide black outline, or a 1 or 2 pixel wide space between them. There is enough real-estate here the make such a re-arrangement. Perhaps the 'backlit' effect could also be made a little brighter so as to clearly show which part of the functionality ( 'select' or 'invoke') is being used.

**Comment by Lawrence37** [comment]
Since you did not provide a description in the original post, I only had the title to work with. For future reference, you *can* write text in the description, just like on Pixls. You can also edit it if you accidentally hit the submit button too early.

The problem you describe is a theme issue. The drop-down button is used throughout RawTherapee. I had a similar confusion when I started using RawTherapee. I couldn't figure out how to use the curves because I was clicking the icon instead of the arrow. The documentation didn't say how to use it, but the [documentation for the external editor button](http://rawpedia.rawtherapee.com/Edit_Current_Image_in_External_Editor) does make the distinction. I think the TooWa* themes have a line separating the icon from the arrow.
