### ISSUE TITLE
Update white balance observer tooltip

### ISSUE THREAD

**Issue by Lawrence37** [Beep6581/RawTherapee#6970]
The tool-tip says the default observer is 10 degrees, but it is actually 2. The rest of the tool-tip should be reviewed for accuracy (is 10 degrees still the better option in most cases?). Here's the current tooltip:

> The color management in Rawtherapee (White balance, channel multipliers, highlight recovery,...) uses the spectral data of the illuminants and colors. Observer is an important parameter of this management which takes into account the angle of perception of the eye. In 1931 it was fixed at 2° (privileges the use of the cones). In 1964 it was fixed at 10° (privileges the use of the cones, but partially takes into account the rods).
To avoid a (rare) drift of the colors due to the choice Observer 10° - probably due to the conversion matrix - Observer 2° must be selected.
In a majority of cases Observer 10° (default) will be a more relevant choice.

**Comment by Desmis** [comment]
@Lawrence37 
As you say elsewhere, developing documentation (website, rawpedia, video, etc.) is a long process, which requires many conditions.

The corollary problem, also complex, is the evolution of this documentation through that of the software functionalities.

This “Observer” case is just one example among others.
Here is what I propose. Of course, you can change, my english is so bad.

**No changes for the first part:**
"The color management in Rawtherapee (White balance, channel multipliers, highlight recovery,...) uses the spectral data of the illuminants and colors. Observer is an important parameter of this management which takes into account the angle of perception of the eye. In 1931 it was fixed at 2° (privileges the use of the cones). In 1964 it was fixed at 10° (privileges the use of the cones, but partially takes into account the rods)."

**And for the second:**
In a majority of cases Observer 2° (default) will be the best choice.
To avoid a (rare) drift of the colors due to the choice Observer 2° - probably due to the conversion matrix - Observer 10° must be selected.

Jacques

**Comment by Desmis** [comment]
If you are OK, I will change the tooltip tomorrow, directly in dev (without PR, if you agree).

Jacques

**Comment by alice-mm** [comment]
Hi and thanks for taking care of this!
I suggested an alternate version (for the last part) here:
https://discuss.pixls.us/t/questions-how-to-choose-a-dcp-profile-if-at-all/42404/10?u=alicem

**Comment by Desmis** [comment]
@alice-mm 

For me it's OK

_In the rare occurrence where a drift of the colors is noticed with “Observer 2°” – generally due to the conversion matrix –, “Observer 10°” must be selected instead._

But I am not at all english...
Thank you.

Jacques

**Comment by alice-mm** [comment]
I’m French so I’ll let @Lawrence37 be the judge. xD

**Comment by Desmis** [comment]
@alice-mm 
In french :)

Sympathique qu'il y ait des français(e) qui participent.
N'hésites pas à me contacter pour n'importe quel sujet (si je le maîtrise bien sûr)

Jacques

**Comment by Lawrence37** [comment]
Well, I'm embarrassed. I know the distinction between hyphens and dashes, but I had to look up the difference between an en dash (short dash) and an em dash (long dash). The em dash (—) is correct here. To make it more concise, I suggest
> In the rare case of a color drift with "Observer 2°" — generally due to the conversion matrix — “Observer 10°” must be selected.

I have one question for Jacques. The original tool-tip reads "probably due to the conversion matrix" while Alice's is "generally due to the conversion matrix". "probably" and "generally" have different meanings. "probably" implies we don't know the cause, but we suspect it has something to do with the conversion matrix. "generally" means most color drifts that have been observed are caused by the conversion matrix. Essentially, the difference between the words is whether we know the conversion matrix causes color drifts. Which one is right?

**Comment by Desmis** [comment]
@Lawrence37 

For me it's "probably", because **we don't know what "Adobe" does** ( or else we would have to send the CIA or the FSB...)

I will take your last text, with :
In the rare case of a color drift with "Observer 2°" — **probably** due to the conversion matrix — “Observer 10°” must be selected.

And to be sure, I will create a PR.

Jacques

**Comment by Lawrence37** [comment]
Sounds good.

**Comment by Desmis** [comment]
@Lawrence37 
@alice-mm 

I just create a Pull-Request with this (small, but important) change

Jacques

**Comment by alice-mm** [comment]
> Well, I'm embarrassed. I know the distinction between hyphens and dashes, but I had to look up the difference between an en dash (short dash) and an em dash (long dash). The em dash (—) is correct here.

Haha sorry for launching you on that topic. Hum yeah they’re sometimes used interchangeably for this, but ultimately the em may be better yeah. Note, however, that it has no spaces on the side, generally, unlike the en. (While in French we use spaces regardless of en or em. 🙃) Wikipedia gives examples such as: `The food—which was delicious—reminded me of home.`

>  "probably" implies we don't know the cause

Sorry about this! I indeed wrongly assumed that we kinda knew what was happening.

**Comment by Desmis** [comment]
in French

D'où ma remarque sur la CIA ou le FSB...
La colorimétrie est quelque chose d'incroyablement complexe, par elle même. Mais en plus il y a des inconnues. 
Que font réellement dans leur traitement du capteur, chaque constructeur (Canon, Nikon, Sony,...), ils ne livrent que ce qu'ils veulent. Comment Adobe "décrypte" les Raw des constructeurs , ont-ils les "secrets" ou non...?

Bref, pas simple.
Si tu es intéressé, c'est un peu complexe... je peux expliquer - ce que j'ai fait (le plus complexe et de loin - l'algorithme WBauto Temperature correlation" ) - ou du moins ce que je crois comprendre.

Jacques

**Comment by alice-mm** [comment]
> Bref, pas simple. Si tu es intéressé, c'est un peu complexe... je peux expliquer - ce que j'ai fait (le plus complexe et de loin - l'algorithme WBauto Temperature correlation" ) - ou du moins ce que je crois comprendre.

Je crois que c’est bien au-dessus de mon niveau. xD

By the way, do such changes automatically get reflected on files such as `rtdata/languages/Francais`? There seems to be a diff-script thingy that gets run before releases.
Maybe one day I’ll try to help a little on French translation. I never realized there was one, as I use the English version. 😆
Oh yeah OK there are `!`-s indicating whether an entry has been translated or not. I suppose that’s how the diff script can do its magic.

**Comment by Desmis** [comment]
In french

En fait, rien n'est simple, y compris pour la documentation.
Je suis français, vieux...(très), parlant mal anglais (mes petits fils parlent beaucoup mieux que moi)...et aucune formation d'informatique (je suis autodidacte...), donc, code brouillon, etc.

Depuis que je coopère avec Wayne @Wayne_Sutton50  ou @Wayne_Sutton qui est anglophone de naissance et habite en France depuis longtemps, pour moi, tout va bien...Notre coopération se passe au mieux... Seul problème en termes de convivialité, nous sommes à 1000km de distance.

Non seulement il traduit, mais il essaye, critique, souhaite des modifications - souvent de GUI - le plus souvent sur la compréhension de ce que cela fait... 

Ce qui amène que la version 'anglaise' est mieux (c'est presque un comble) que la française, que ce soit pour la documentation, mais aussi les Labels et Tooltips. C'est un travail considérable, on y passe beaucoup de temps. L'inconvénient c'est que Rawpedia (le support) est antique... Il y a un projet d'amélioration (je ne comprends pas tout ce qui est prévu).
Mais en attendant, si je fais, ou un autre développeur (je n'aime pas ce terme), une modification logicielle (algorithmes, GUI,...) il faudrait en théorie revoir la documentation. Jette un oeil à "Local Adjustments" dans Rawpedia... tu verras..Le travail est colossal. 

En tous cas, je retiens ta proposition, si tu souhaites coopérer comme Wayne (traduire, tester, critiquer...), cela présente tout un tas d'avantages (à part le temps à y passer), tout le monde est gagnant.
Contactes moi, le cas échéant.

Mais cette proposition tient aussi pour les autres participants, traduire de anglais à Français ou l'inverse... Et toutes les langues...Japonais, allemand, néerlandais..
Détail qui n'en est pas un: il faut avoir accès à Rawpedia... donc être autorisé..Moi je l'ai cet accès , mais qui autorise ??
L'idéal dans un monde parfait, c'est que la doc, les tooltips, soient accesibles via une Pull-request... 

Merci.

Bon week-end.

Jacques
