### ISSUE TITLE
Translation of rawtherapee into Italian

### ISSUE THREAD

**Issue by capejeaspaje** [Beep6581/RawTherapee#6971]
I translated RawTherapee 5.9 into Italian. When version 5.10 was released I checked my translation with the default version inserted into the "languages" directory and made the appropriate changes. I think I did a decent job.
If you want to insert the file into RawTherapee 5.10 I would be happy

[Italiano.txt](https://github.com/Beep6581/RawTherapee/files/14480653/Italiano.txt)

**Comment by Lawrence37** [comment]
Thanks @capejeaspaje! I will add your translations to the code.

**Comment by Lawrence37** [comment]
I created a pull request with your translations. There were some trailing spaces that I removed. I also added to the history at the top of the file. Is your name in [AUTHORS.txt](https://github.com/Beep6581/RawTherapee/blob/dev/AUTHORS.txt)?

**Comment by Lawrence37** [comment]
I've added your translations to `dev`. Let me know if your name is not in AUTHORS.txt.
