### ISSUE TITLE
B&W not working

### ISSUE THREAD

**Issue by paulmatthijsse** [Beep6581/RawTherapee#6978]
Unless I'm very stupid or oversee something, the black&white filter in the Color tab doesn't produce a b&w image, it just stays in color. (And yes, the filter IS activated). With today's version of RT from Github. 

Version: 5.10-149-g103bc9fa1
Branch: dev
Commit: 103bc9fa1
Commit date: 2024-03-07
Compiler: cc 13.2.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.24.8
Lensfun: V0.3.2.0
Build type: Release
Build flags:  -std=c++11 -ffp-contract=off  -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wno-attributes -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags:   
OpenMP support: ON
MMAP support: ON
Build OS: Linux 6.5.0-25-generic x86_64
Build date: Fri, 08 Mar 2024 13:06:04 +0000 UTC

**Comment by paulmatthijsse** [comment]
I am very stupid. Issue can be closed.

**Comment by Lawrence37** [comment]
Just curious, what was the problem? Maybe the UX could be better.

**Comment by paulmatthijsse** [comment]
Hello, the problem was as described above, the b&w function did not turn the color image into b&w. I was playing with color correlation and other wb settings, and the b&w module did not respond at all. I guess I could have solved that by exiting RT and restarting. Yesterday I tried to reproduce the issue but in vain...
