### ISSUE TITLE
Possible Big Sur incompatibility?

### ISSUE THREAD

**Issue by azerty68123** [Beep6581/RawTherapee#6985]
## Short description
The release notes for 5.10 claim compatibility from [Big Sur 11.7 or newer](http://rawtherapee.com/downloads/5.10/#macos-installation-instructions), but I'm getting an error on start up that suggests it may not be compatible with my current OS (11.7.10 on Intel x64):

> RawTherapee.app cannot be opened because of a problem.
> Check with the developer to make sure RawTherapee.app works with this version of macOS. You may need to reinstall the application. Be sure to install any available updates for the application and macOS.

## Steps to reproduce
1. Download and install latest RT universal binary for MacOS
2. Attempt to open the RT app
3. Error appears

I also checked the OS security settings in case the app was blocked due to Apple's notification system, but could only see stuff relating to the RT cli.

## Expected behavior
Either change the documented support level or change the compile options?

## Additional information
- Version of RawTherapee = 5.10
- Version of your operating system = MacOS 11.7.10 (Intel x64)

To be honest, I was only trying out RT so am not super invested, just thought I'd note this glitch.

**Comment by Benitoite** [comment]
There is a working update, it should be on the website soon.  In the meantime you can get a copy at https://r42.us/rt5

**Comment by azerty68123** [comment]
That's working for me @Benitoite, thanks very much.
