### ISSUE TITLE
Flat field is not applied

### ISSUE THREAD

**Issue by timsurber** [Beep6581/RawTherapee#6986]
**Short description**
Applying a flat field correction to some RAW files has no effect.

**Steps to reproduce**
1 Open supplied RAW-File
2 Ensure no lens profile is applied
3 Apply supplied flat field
4 Observe vignetting correction: nothing happens

**Expected behavior**
The flat field is applied and the vignetting is corrected.

**Additional information**
- RawTherapee 5.10 on Windows 11
- https://discuss.pixls.us/t/bizarre-flat-field-effect-rawtherapee-5-9-5-8/33992/5 I think it is maybe this bug

[flat.zip](https://github.com/Beep6581/RawTherapee/files/14564366/flat.zip)
[raw_file.zip](https://github.com/Beep6581/RawTherapee/files/14564369/raw_file.zip)

**Comment by timsu100** [comment]
It works correct on ART.

**Comment by timsurber** [comment]
It works correct on ART.
