### ISSUE TITLE
Demosaiced DNGs fail to load since commit 831a9bbd

### ISSUE THREAD

**Issue by Entropy512** [Beep6581/RawTherapee#6996]
I have some demosaiced (aka Linear RAW) DNGs created by a rather oddball camera (I don't own it, but have put some effort into reverse engineering/supporting it).

One example is at https://filebin.net/a8zb1jja5rwb8dk5

These cause the asserts from 831a9bbd to fail because rawdata.getWidth() returns a width that is three times the image width since it has three samples per pixel

Is the value of DNG samplesPerPixel readily available where these asserts are?

Alternatively, maybe asserting (rawData.getWidth() % W) == 0 would work here, under the assumption that getWidth() won't ever be exactly zero if getHeight is nonzero?

**Comment by Lawrence37** [comment]
`copyOriginalPixels` is where `rawData` gets resized. If `ri->getSensorType() == ST_BAYER || ri->getSensorType() == ST_FUJI_XTRANS || ri->get_colors() == 1`, then its height and width are `H` and `W`. Otherwise, they are `H` and `3 * W`.
