### ISSUE TITLE
Automatic lens correction via lensfun does not work with Leica-SL2-S and Sigma L-mount lenses, manual selection works

### ISSUE THREAD

**Issue by Reiner1959** [Beep6581/RawTherapee#7008]
As the title says, automatic lens correction is not working.
Maybe the reason is the missing lens make vendor. As you can see in the screenshot
there is the camera vendor listed under info but no lens maker vendor:

LEICA CAMERA AG LEICA SL2-S + 28 - 70mm F2.8 DG DN | Contemporary 021

But the lens maker is in the exif data:
(see screenshot, right side)
 
Lens Make   SIGMA

I think the complete info string should be:
LEICA CAMERA AG LEICA SL2-S + SIGMA 28 - 70mm F2.8 DG DN | Contemporary 021

Systeminfo:
Rawtherapee 5.10
Debian testing
amd64

best regards
Reiner
![Bildschirmfoto vom 2024-03-24 12-29-43](https://github.com/Beep6581/RawTherapee/assets/68758094/b64dc159-940f-491b-9b68-537d46c242df)

**Comment by Lawrence37** [comment]
Can you provide a sample image?

**Comment by Reiner1959** [comment]
of course the sample image, from above

A sample image can be found under this link:
https://file.io/VxxkVc3vGMdW
Attention: this file will be automatically deleted after download

If you have a better filesharing resource, please tell :-)

Best regards
Reiner

**Comment by Reiner1959** [comment]
And here on fastupload.io

https://fastupload.io/sPWgMkmrOTwcPIM/file

**Comment by Lawrence37** [comment]
Thanks, I've downloaded the file. We typically recommend using filebin.net to share files that are too big to attach here directly.

**Comment by Lawrence37** [comment]
Even with the lens make, Lensfun fails to find the lens. It does work if the lens name does not contain spaces around the dash, i.e. `28-70mm F2.8 DG DN | Contemporary 021` instead of `28 - 70mm F2.8 DG DN | Contemporary 021`. I have created a pull request that adds an additional round of lens matching with the spaces around dashes removed.
