### ISSUE TITLE
RawTherapee_dev_5.10-177-g61019d0dc_win64_release won't save state for ToolPanelsExpanded

### ISSUE THREAD

**Issue by HGZauner** [Beep6581/RawTherapee#7012]
The latest RawTherapee dev does not save the expanded/collapsed state for the tool panels.
In the options file these values are always set to 0 when closing the program:
```
ToolPanelsExpanded=0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;
ToolPanelsExpandedAutoSave=true

```

**Comment by sgotti** [comment]
This is probably caused by #6769. The settings files is reset due to parsing errors. It should be fixed by #7009  

@Lawrence37 I also found my settings files reset to default values, which is annoying. Probably this should be fixed/improved.
