### ISSUE TITLE
Dev Appimage not storing RT setting (those that need a restart)

### ISSUE THREAD

**Issue by pi99y** [Beep6581/RawTherapee#7014]
I'm using "dev_release.AppImage" Version: 5.10-177-g61019d0dc Commit: 61019d0dc Commit date: 2024-03-24 on Debian and the settings like monitor color profile, HaldClut directory (those that need a restart to apply) don't hold. When I restart RT they any not set anymore. Some settings like the Appearance are remembered. 

The Stable Appimage Version: 5.10 Commit: 8adb5439d Commit date: 2024-02-15 works fine.

Thanks.

**Comment by sgotti** [comment]
Should be fixed by #7009 merged 12 hours ago. So try a newer app image (the one with the fix is this https://github.com/Beep6581/RawTherapee/actions/runs/8477213389).

**Comment by pi99y** [comment]
Great! @sgotti you're right, looks like the last build fixed this. Thank you.
