### ISSUE TITLE
Panasonic DMC-FX150

### ISSUE THREAD

**Issue by abpolly** [Beep6581/RawTherapee#7021]
Panasonic DMC-FX150 - submitted two samples.
Thank you

**Comment by Lawrence37** [comment]
Thanks for submitting samples, @abpolly! Where have you submitted them? To raw.pixls.us? I see one image has been approved and added.

**Comment by abpolly** [comment]
uploaded new samples today to raw.pixls.us, file name:
Panasonic-DMC-FX150-ratios_4-3_3-2_16-9.zip
just in case, link to download:
https://drive.google.com/file/d/1samj8PxLi5-p3d1GJYEys1pU13JVi1LW/view?usp=drive_link

**Comment by Lawrence37** [comment]
The file on raw.pixls.us opens without problems. The colors and raw crop are correct. The black and white levels are good as far as I can tell.

@abpolly The Google drive link is not allowing me access to the files.

**Comment by abpolly** [comment]
Corrected sharing for the link on Google drive, download should work now.
Thanks

**Comment by Lawrence37** [comment]
Thanks. The 16:9 images have garbage pixels on the bottom and right sides which are hidden with the default 4 pixel demosaic border. This will need to be fixed. Everything else looks fine.
