### ISSUE TITLE
cannot disable black & white

### ISSUE THREAD

**Issue by acamari** [Beep6581/RawTherapee#7025]
Disabling Black & White keeps the image in Black & white, even when viewing tiff via ctrl-e or when image is processed (jpg) ctrl-b.

To reproduce:

```
$ rawtherapee la_segunda_venida.jpg
```
Just as image opens it shows on black&white even though the black&white option is 'powered off' (see image)

```
acamari@maetel-ubuntu:~$ uname -a
Linux maetel-ubuntu 6.2.0-39-generic #40~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov 16 10:53:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
acamari@maetel-ubuntu:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
```

About/version:
```
Version: 5.10
Branch: 5.10
Commit: 8adb5439d
Commit date: 2024-02-15
Compiler: cc 9.4.0
Processor: generic x86
System: Linux
Bit depth: 64 bits
Gtkmm: V3.24.2
Lensfun: V0.3.2.0
Build type: release
Build flags:  -std=c++11 -mtune=generic -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wno-attributes -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags:  -mtune=generic
OpenMP support: ON
MMAP support: ON
Build OS: Linux 5.15.0-1054-azure x86_64
Build date: Fri, 16 Feb 2024 05:18:01 +0000 UTC
Build epoch: 1708060681
Build UUID: fd65a10b-7483-40e7-8afd-fd9c2e5cff2a
```

license: CC BY-NC-SA
![la_segunda_venida.jpg](https://github.com/Beep6581/RawTherapee/assets/716556/05d3303e-81aa-45d7-b293-5fb575b0d1c0)

pp3 renamed to pp3.txt so github allows it
[la_segunda_venida.jpg.pp3.txt](https://github.com/Beep6581/RawTherapee/files/14832548/la_segunda_venida.jpg.pp3.txt)

screenshot of error of editor (shows image in bw but option disabled):
![bw](https://github.com/Beep6581/RawTherapee/assets/716556/2db2592c-01a6-4adb-bd96-63a529feaa5e)

**Comment by TechXavAL** [comment]
May you try to disable the Film simulation tool?

**Comment by marter001** [comment]
cannot reproduce here under Win10, but: your pp3-file shows a film-simulation, which i dont have. Could be, that your simulation does excact this - simulate bw?

**Comment by acamari** [comment]
Hahah, you're right, I'm using Kodak TRI-X 400 2 from the rt film simulation zip (http://rawtherapee.com/shared/HaldCLUT.zip).

Sorry, first time using film simulation, for some reason I believed it only altered "somehow" lightness levels of the image but that I still required to use the B&W module.

Thanks for looking into this, I'm closing this issue
