### ISSUE TITLE
lost GPS coordinates in exported JPG

### ISSUE THREAD

**Issue by moonraver** [Beep6581/RawTherapee#7027]
Ubuntu 23.10
RawTherapee 5.10 installed from Flatpak

I edit RAW files with GPS coordinates included. When I save edited image as JPG, GPS coordinates are lost.

Thank you.

**Comment by Lawrence37** [comment]
Have you checked if the GPS data is selected in the EXIF section of the metadata tab?

**Comment by moonraver** [comment]
You are right. I didn't check this. It was unchecked.
Thank you
