### ISSUE TITLE
XMP Metadata Synchronization not Writing XMP Sidecars

### ISSUE THREAD

**Issue by Calandracas606** [Beep6581/RawTherapee#7036]
**Short description**

XMP metadata synchronization is not writing to XMP sidecars when settings are changed.

**Steps to reproduce**
1. Go to settings > Image Processing
2. Metadata Synchronization with XMP Sidecars: Bidirectional
3. XMP-Sidecar style: darktable-like
4. Go to file browser
5. Apply a "star" rating to an image
6. Look in the folder where the image is stored. Notice how a .pp3 file has been written, but a .xmp has not

**Expected behavior**

An XMP sidecar file has been written containing the `xmp:Rating` tag.

**Additional information**
- Version of RawTherapee: 5.10
- Version of your operating system: Void Linux - `Void 6.6.25_1 x86_64 GenuineIntel uptodate rrrdFFFFFFFFFFF`
- `AboutThisBuild.txt`
```
Version: 5.10
Branch: 5.10
Commit: 8adb5439d
Commit date: 2024-02-15
Compiler: cc 13.2.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.24.8
Lensfun: V0.3.4.0
Build type: None
Build flags: -DNDEBUG -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2  -O3 -g -ffile-prefix-map=/builddir/rawtherapee-5.10/build=. -std=c++11 -ffp-contract=off  -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wno-attributes -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -fopenmp -Werror=unknown-pragmas  -ftree-vectorize
Link flags: -Wl,-z,relro -Wl,-z,now -Wl,--as-needed
OpenMP support: ON
MMAP support: ON
Build OS: 
Build date:  UTC
Build epoch: 
Build UUID: 
```

![image](https://github.com/Beep6581/RawTherapee/assets/40183138/06ca1302-594f-4e9b-b5b0-f77f98043adf)

**Comment by Lawrence37** [comment]
At the moment, XMP synchronization only applies to the metadata shown in the metadata tab in the editor. #6988 adds file browser ratings and color tags.
