### ISSUE TITLE
File operations rename not working after file opened for editing. Development branch.

### ISSUE THREAD

**Issue by kaesa** [Beep6581/RawTherapee#7045]
**Short description**
In file browser view, Mouse right click menu->File operations->Rename stops working after Canon EOS R10 generated CR3 raw file has been opened for editing. Nothing else seems to be wrong, only apparent problem is that the file renaming doesn't work for a file that has been opened for editing. Issue exists both in editor view and in file browser view. Files can be renamed before opening for editing and again after restarting the RawTherapee.

- Issue does not occur with DNG files generated from the EOS R10 CR3 files. 
- Issue does not occur with Sony A7II ARW files or with Canon 2000D CR2 files.
- Issue did not exists with 5.10 release version, it started after building with latest commits.
- You can still rename any other files including other CR3 files, but not those CR3 files that have been opened for editing.
- Renaming the files outside of RawTherapee, using Dolphin File Manager is also not possible until RawTherapee is closed. With the other filetypes, there doesn't seem to be any restrictions.

**Steps to reproduce**
1. Open RawTherapee and browse into a folder with a CR3 file from Canon EOS R10.
2. Double click file for editing it.
3. Using the mouse right click menu, try to rename file from the top panel or go back to the file browser view to attempt renaming.
4. Nothing happens after selecting OK.

**Expected behavior**
File should get renamed.

**Additional information**
<details><summary>About the system and the build:</summary>
<p>

Version: 5.10-179-g11240bc97
Branch: dev
Commit: 11240bc97
Commit date: 2024-03-28
Compiler: cc 13.2.1
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.24.8
Lensfun: V0.3.4.0
Build type: Release
Build flags:  -std=c++11 -ffp-contract=off  -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wno-attributes -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags:   
OpenMP support: ON
MMAP support: ON
Build OS: Linux 5.15.150-1-MANJARO x86_64
Build date: Wed, 10 Apr 2024 16:43:37 +0000 UTC
Build epoch: 1712767417
Build UUID: be55565b-c08a-4c2d-bc7d-f0dddb404715

</p>
</details>

**Comment by Lawrence37** [comment]
Cannot reproduce with commit 73fb89147c1910b6d4e95aac8171ed4fa3602b3a on Linux. Renaming a R10 CR3 file after opening it in the editor still works.

**Comment by kaesa** [comment]
I did a clean rebuild and tested with a fresh user account on an up to date Manjaro.
<details><summary>From uname -a</summary>
<p>

5.15.154-1-MANJARO #1 SMP PREEMPT Wed Apr 10 19:10:26 UTC 2024 x86_64 GNU/Linux

</p>
</details> 

I can still reproduce the issue. If I try to rename the file with mv on command line, I get "Text file busy" -error.

<details><summary>New build info</summary>
<p>

Version: 5.10-188-g46531c7ec
Branch: dev
Commit: 46531c7ec
Commit date: 2024-04-17
Compiler: cc 13.2.1
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.24.8
Lensfun: V0.3.4.0
Build type: Release
Build flags:  -std=c++11 -ffp-contract=off  -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wno-attributes -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags:   
OpenMP support: ON
MMAP support: ON
Build OS: Linux 5.15.154-1-MANJARO x86_64
Build date: Fri, 19 Apr 2024 06:26:16 +0000 UTC
Build epoch: 1713507976
Build UUID: 0c3ae78b-ee01-4704-9d85-30d2bffd09e0


</p>
</details> 

EDIT:
Just in case there is something specific about the files I have, I have prepared a black frame (shot with lens cap on) which does trigger the issue for me.
[https://filebin.net/ehonheswuhaairql](url)

**Comment by Lawrence37** [comment]
I cannot reproduce with the provided file. Are your images saved somewhere other than your main storage drive? Are you able to reproduce with a debug build?

**Comment by kaesa** [comment]
All images are on the same drive, which is an SMB mount. Please note, that I have DNG files made from the same CR3 files in the same folder as well as files from other cameras and they will not trigger the issue. It is somehow related to this specific file type. I will test the debug build.

**Comment by kaesa** [comment]
I can reproduce the issue with the debug build. I have narrowed down the exact commit that breaks it for me is #6962. I certainly don't understand the commit details, but I suspect it could be that something in the handling of the embedded DCP is the difference between these files which trigger the issue and the other files which don't trigger the issue.

Is there something I can do with the debug build to get more information about the execution, given that the program doesn't crash?

**Comment by sgotti** [comment]
@Lawrence37 it could be possible that a file without an embedded dcp could trigger a file descriptor leak in this point

https://github.com/Beep6581/RawTherapee/blob/46531c7eca7fd2b5a504ed13c792b6eec0f2b9b2/rtengine/dcp.cc#L1134-L1138

There's probably a missing `fclose(file);` before the return.

**Comment by kaesa** [comment]
Given the clues. I tested and indeed, I can't reproduce the issue if I copy the triggering file to my home folder. So it seems that with the way the SMB shares have been tied to the system, it makes the files more prone to getting locked.

**Comment by kaesa** [comment]
I confirm. Adding
```c++
fclose(file);
``` 
to the proposed location fixed the issue.

**Comment by Lawrence37** [comment]
@sgotti Yes, the file does need to be closed.

@kaesa Thanks for confirming! For future reference, you can press `Control` + `c` in the debugger. This will pause the program and allow you to proceed with step 5 in https://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports#Step_by_step
