### ISSUE TITLE
A gamma shift issue/color change after saving to jpg

### ISSUE THREAD

**Issue by estaf1001** [Beep6581/RawTherapee#7057]
It's one
This topic is similar to a topic created back in 2018 by another person https://github.com/Beep6581/RawTherapee/issues/5052

I tried to take into account the fact that on def. The tool is marked 1:1 (you need to look at the picture at 1:1 scaling).

The software I use when viewing photos:
Fastone viewer v 7.7 (with cms support/default color profile is on).
RT v 5.10.
Adobe Photoshop v 25.7 (there I also use the monitor system profile).
Adobe camera raw.
3DLUT Creator.
windows 10 21h2. The profile was created using the argyll and colorizer i1display pro.

Problem:
The display in the viewports of rt and fastone/ps ones  is different.
The display in the viewports of the Adobe camera raw app and fastone/ps ones is the same.
The display in the viewports of the 3DLUT Creator app and fastone/ps is the same.
Differences in scale and shades.

I observe several points of difference.
If we compare the display of pictures in rt with the display in other programs, then in the first one I am satisfied with everything. Exactly what I was trying to achieve.
When saving the picture to jpg one, the image becomes less contrasty, and some colors become warmer in temperature (but only if you look at the windows of these different programs visually, without creating screenshots). If I take a screenshot of two windows, I won’t see the difference in shades. I will see the difference only in the contrast.
There is a nuance. This state of affairs will be true only for raw files (I're talking about raw files of the same camera), for which if we transfer the workspace from prophoto to srgb (This is not about the output profile, but about changing one profile to another specifically for the workspace), we will see the difference within rawtherapee app itself. For the "remaining" images we will not see a difference. That is, most likely it all depends on the content in the file. There are many colorful flowers and we “sailed”.

![Screenshot_1](https://github.com/Beep6581/RawTherapee/assets/86945829/ad28cfca-6bcf-42b7-b817-832e7a47fc45)

raw one with pp3 preset https://filebin.net/ic4ygp4yw34blesv/_MG_6884.zip

Have you forgotten anything?...that’s it.

Yes. The program has a system profile.
![Screenshot_2](https://github.com/Beep6581/RawTherapee/assets/86945829/454e1d9b-ba80-4d5a-945a-6a4ec3145913)

And:
![Screenshot_3](https://github.com/Beep6581/RawTherapee/assets/86945829/f57d374a-85c7-4383-8bec-f6b938412673)

**Comment by Lawrence37** [comment]
I don't see any differences between the colors or contrast between the two images in your screenshot. If you load the saved jpg in RawTherapee, does it look the same as the raw?

Difference between the two images:
![image](https://github.com/Beep6581/RawTherapee/assets/45837045/bcd50b6f-b553-407d-9afc-f46d21461f87)

GIF comparing the two images. They are identical, ignoring the GIF compression:
![screenshots](https://github.com/Beep6581/RawTherapee/assets/45837045/563dc4f1-5ffc-4f5a-8d38-8750d446d450)

**Comment by estaf1001** [comment]
My mistake. I can't set default color profile in app settings. Color management> monitor>default color profile. I didn't indicate my monitor profile there. Now I installed it and everything is back to normal.

**Comment by estaf1001** [comment]
Honestly, I gave up on the program. I give up. I have no idea what can be done to make it work.
![Screenshot_1](https://github.com/Beep6581/RawTherapee/assets/86945829/c8c9ac2f-b72c-43f2-9c26-248621f87662)

**Comment by Lawrence37** [comment]
Glad it's working for you now.
