### ISSUE TITLE
JPG Export best-quality really chroma subsampling 4:4:4 ?

### ISSUE THREAD

**Issue by hubertmeier** [Beep6581/RawTherapee#7062]
This is more a question: 

My favourite Image Viewer / Organizer shows following info for the chroma subsampling

**Sub-sampling	2x2,1x1,1x1**	

Is this **the same like chroma 4:4:4** ? I didn't found any other program which could show this. The export in RT is set

JPG / 8bit / best quality / quality 91

Thank you

**Comment by Lawrence37** [comment]
Yes, best quality uses 4:4:4 subsampling. Exiftool show
`Y Cb Cr Sub Sampling            : YCbCr4:4:4 (1 1)`
