### ISSUE TITLE
Sony ILCE-6700 has invalid pixels on the right border

### ISSUE THREAD

**Issue by che0** [Beep6581/RawTherapee#7075]
Currently, ARW files from Sony ILCE-6700 map to 6264x4160 image, which has rightmost 26 pixels without any meaningful data. The effect is visible on [this converted photo](https://flic.kr/p/2pPoKVe) (Flickr link), as well as on compressed raw sample from raw.pixls.us when processed by RawTherapee 5.10.

The following camconst.json fragment fixed it for me:

```json
    { // Quality C
        "make_model": "Sony ILCE-6700",
        "raw_crop": [ 20, 12, 6200, 4136 ] // columns after 6238 are b0rked; this crops the rest so that resulting image is 6192x4128, i.e. the same as camera JPEG
    },
```

**Comment by sgotti** [comment]
Created PR #7076 with also the dcraw matrix. The raw crop used in that PR is the one provided by also other tools and looks saner.
