### ISSUE TITLE
Chinese (Simplified) translation (intended for) Rawtherapee 5.8 (or 5.9?)

### ISSUE THREAD

**Issue by syyrmb** [Beep6581/RawTherapee#7077]
[Chinese (Simplified).txt](https://github.com/Beep6581/RawTherapee/files/15365421/Chinese.Simplified.txt)

My age-old translation that I had been working on. Mainly made things easier to understand.

I believe I overwrote some of my earlier work due to updating from 5.8 to 5.9. Also I switched to a new PC, that made things a lot more complicated so I haven't been bothered to work on this file for a long time. Hopefully it can be convert to something that can be used for RT 5.10.

**Comment by Lawrence37** [comment]
Thank you @syyrmb! I created pull request #7078 with your updated translations.
