### ISSUE TITLE
MAIN_TOOLTIP_PREVIEWSHARPMASK isn't correct any longer

### ISSUE THREAD

**Issue by marter001** [Beep6581/RawTherapee#7087]
MAIN_TOOLTIP_PREVIEWSHARPMASK;Preview the <b>sharpening contrast mask</b>.\nShortcut: <b>p</b>\n\nOnly works when sharpening is enabled and zoom >= 100%.

When capture sharpening in RAW-tab is acitvated, this function also works with zoom < 100% 

I propose a tooltip like:
Preview the <b>sharpening contrast mask</b>.\nShortcut: <b>p</b>\n\nIf capture-sharpening is not activated, this only works when sharpening is enabled and zoom >= 100%.

**Comment by Lawrence37** [comment]
Thanks for bringing this up @marter001. What do you think about this to replace the last sentence?
> Only works when sharpening is enabled and zoom >= 100%, or when capture sharpening is enabled.

**Comment by marter001** [comment]
@Lawrence37 sorry no native english speaker here, and now, when i read your version, it sounds much better to me.
