### ISSUE TITLE
Which icc output profile of RawTherapee has widest gamuth, richest color space in 16bit?

### ISSUE THREAD

**Issue by zelenooki87** [Beep6581/RawTherapee#7088]
From all of these? screenshot
Is it "safe to use" them with Adobe Photoshop?
Thanks
![Skrinšot-0002](https://github.com/Beep6581/RawTherapee/assets/75204635/5654d25e-db45-4bd1-91b0-d94938605a00)

**Comment by kmilos** [comment]
https://discuss.pixls.us/c/software/rawtherapee/14

**Comment by Lawrence37** [comment]
ACES AP0 has the largest gamut. I'm not sure what you mean by "richest". Photoshop should be able to use these profiles. You should ask on the forum (linked by @kmilos) to get a better understanding of which to use.
