### ISSUE TITLE
The program fault unexpectedly

### ISSUE THREAD

**Issue by estaf1001** [Beep6581/RawTherapee#7101]
If you try to minimize its window while a program is open, or switch to another application, the program unexpectedly “disappears”. As if this program had not been launched.

1. Open RT and work
2. Click on any tool that allows you to minimize the program window, or switch from it to any other application - Google Chrome, calculator, notepad, etc. Also, if you try to switch to the rawtherapee program window from another program, the program “disappears”
3. We see that its icon on the taskbar informs us that the program is not running.
4. In the task manager, in the list of processes, the program disappears in the same way.

- Version of RawTherapee: 5.10
- Version of operating system: windows 10 21h2 ltsc, windows 10 22h2 professional.
- Hardware: i7-12700K/rtx4070 12GB/32GB ram/1 

The problem occurs when opening any raw file.
The problem occurs even if you reinstall the operating system from scratch.
RAM tested using memtest 86+ program.

There are no problems with any other programs on the computer. No problem.
Installed other programs:
Davinci Resolution (not a studio);
Adobe Photoshop, Lightroom, acr, Adobe Bridge (photo subscription);
xvid4psp encoder;
3dlut creator.

log one by gdb
[log.txt](https://github.com/user-attachments/files/15838429/log.txt)

**Comment by estaf1001** [comment]
My hwinfo
[hwinfo.LOG](https://github.com/user-attachments/files/15838610/hwinfo.LOG)

**Comment by Benitoite** [comment]
As the gdb session ended were you able to get a backtrace?

**Comment by Lawrence37** [comment]
Since you have gdb, following these instructions closely will yield helpful information:
https://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports#Step_by_step
All steps are important, but please double check you have performed step 6, because that information is missing from the gdb log you provided.

**Comment by estaf1001** [comment]
> As the gdb session ended were you able to get a backtrace?

Isn’t the created log file the same?
I did it according to those instructions. I’m not good at English, but I understood that everything was recorded in the log.

**Comment by Lawrence37** [comment]
As I mentioned in my previous comment, the log you provided is missing the most important information. In particular, the information from step 6 is not there. Please go through the procedure and make sure you follow **every** step.

**Comment by estaf1001** [comment]
ok. I do everything according to the instructions
download the debug version of rt
download gdb from the link in the instructions.
Then they ask me to run gdb with the binary.
I run
gdb rawtherapee.exe
I see a bunch of messages, like in the file I sent you.
Then the instructions ask me to:
"We want a detailed stack backtrace, and to make sending it to us easier in the next three commands you will tell GDB to save it to a text file called log.txt (or anything, the name doesn't matter). Type:
set pagination off
set logging file log.txt
set logging on
Now to have GDB show info on all threads and print the actual stack backtrace, type:
info threads
thread apply all bt full
You should see a screen full of text, numbers, code and magical spells. These were automatically saved to the log.txt file."
I did everything as asked in that text. I saved the sequence.
I open that log file and see the message there:
"no threads".

**Comment by Lawrence37** [comment]
Please upload the file here.

**Comment by estaf1001** [comment]
[log.txt](https://github.com/user-attachments/files/15905866/log.txt)

**Comment by Lawrence37** [comment]
Thanks. The program exited purposefully, but obviously not in the normal way. I don't think this is an issue coming from RawTherapee itself, but here is what you can try to confirm and get clues on what told RawTherapee to close. Repeat the steps to get the log, but between steps 2 and 3, run this command:
```
catch syscall exit_group
```
This will tell gdb to halt the program when it is about to close and it will make step 6 provide more useful information.

**Comment by Lawrence37** [comment]
Closing as an external issue.

**Comment by Lawrence37** [comment]
Instead of `catch syscall exit_group`, you can use
```
b exit
```
```
b _exit
```
and
```
b _Exit
```
You may encounter this message: `Make breakpoint pending on future shared library load? (y or [n])`
Just press enter if you see it.

**Comment by estaf1001** [comment]
> Instead of `catch syscall exit_group`, you can use
> 
> ```
> b exit
> ```
> 
> ```
> b _exit
> ```
> 
> and
> 
> ```
> b _Exit
> ```
> 
> You may encounter this message: `Make breakpoint pending on future shared library load? (y or [n])` Just press enter if you see it.

(gdb) b exit
Breakpoint 1 at 0x140b196b0
(gdb) r
..
-Type <RET> for more, q to quit, c to continue without paging--
####At this point I was pressing Enter####
[Inferior 1 (process 23548) exited with code 03]

As for me, the information content is practically zero.
Why, if the program is downloaded as a debug version, nothing meaningful is added to the log file, it’s not clear, I don’t know.

############
Please move topics to "open" status.

**Comment by Lawrence37** [comment]
Did it show the `Make breakpoint pending` message? If so, for which one(s)?

There aren't many logs because most likely some other program or Windows forced closed RawTherapee. If that's the case, there is nothing RawTherapee can do to solve the issue you are facing.

**Comment by estaf1001** [comment]
>Did it show the Make breakpoint pending message? If so, for which one(s)?
![Screenshot_1](https://github.com/user-attachments/assets/7f449c04-c2fb-4b82-bc0c-33918f2fafae)

So how do I find out which external action the program closed?
I can install an operating system from scratch and get the same minimal problem out of the blue.

Maybe the problem is related to the GTK Shell?

**Comment by Lawrence37** [comment]
If the message shows, it will come immediately after issuing the `b exit`, `b _exit`, and/or `b _Exit` command. I see in your previous comment that the first one did not show the message, but what about _exit and _Exit? Your screenshot only shows the messages after running RawTherapee.

I will answer your other questions after you tell me if you got the message with the other commands. They may provide clues.

**Comment by estaf1001** [comment]
(gdb) b _exit
Function "_exit" not defined.
Make breakpoint pending on future shared library load? (y or [n]) y
Breakpoint 3 (_exit) pending.
(gdb) r
..
[Thread 25788.0x49ac exited with code 3]
[Thread 25788.0x34ec exited with code 3]
[Thread 25788.0x4dd4 exited with code 3]
[Thread 25788.0x57ec exited with code 3]
[Thread 25788.0x6bc exited with code 3]
[Thread 25788.0x3138 exited with code 3]
--Type <RET> for more, q to quit, c to continue without paging--
[Inferior 1 (process 25788) exited with code 03]
(gdb)

(gdb) b _Exit
Function "_Exit" not defined.
Make breakpoint pending on future shared library load? (y or [n]) y
Breakpoint 4 (_Exit) pending.
(gdb) r
..
[Thread 12244.0x4078 exited with code 3]
[Thread 12244.0x5d78 exited with code 3]
[Thread 12244.0x6c34 exited with code 3]
[Thread 12244.0x2568 exited with code 3]
[Thread 12244.0x5948 exited with code 3]
--Type <RET> for more, q to quit, c to continue without paging--
[Inferior 1 (process 12244) exited with code 03]
(gdb)

**Comment by estaf1001** [comment]
(gdb) b _exit
Function "_exit" not defined.
Make breakpoint pending on future shared library load? (y or [n]) n
(gdb) r
..
[Thread 8372.0x48e0 exited with code 3]
[Thread 8372.0x3c78 exited with code 3]
[Thread 8372.0x3d7c exited with code 3]
[Thread 8372.0x3374 exited with code 3]
[Thread 8372.0x692c exited with code 3]
--Type <RET> for more, q to quit, c to continue without paging--
[Inferior 1 (process 8372) exited with code 03]
(gdb)

(gdb) b _Exit
Function "_Exit" not defined.
Make breakpoint pending on future shared library load? (y or [n]) n
(gdb) r
..
[Thread 22620.0x1630 exited with code 3]
[Thread 22620.0x2524 exited with code 3]
[Thread 22620.0x60dc exited with code 3]
[Thread 22620.0x3058 exited with code 3]
--Type <RET> for more, q to quit, c to continue without paging--
[Inferior 1 (process 22620) exited with code 03]
(gdb)

**Comment by Lawrence37** [comment]
As this is outside RawTherapee's control and Windows is not my main OS, I won't be able to provide much more help. All I can do is recommend searching for how to diagnose sudden closures on Windows, or ask on a Windows-specific forum. For example, I did some googling and found these:
https://techcommunity.microsoft.com/t5/ask-the-performance-team/what-killed-my-process/ba-p/375329
https://answers.microsoft.com/en-us/windows/forum/all/apps-are-being-closed-when-minimized/478bf093-595a-4833-9212-d346dbc59433?page=1

**Comment by Lawrence37** [comment]
Also, what do you mean by the GTK Shell? There is no such thing.

**Comment by estaf1001** [comment]
By the way, the debug version of the program crashes not when minimized, but when switching from the browser to photo editing (developing) mode. That is, it doesn’t even come to the point of folding.

It’s unlikely that anyone on the Microsoft website will help me with this problem. All their advice is to check system files, or reinstall the system.

But I understand you. Unfortunately, you will have to return to Adobe Camera Rav.
Sincerely. Thank you.

**Comment by estaf1001** [comment]
> Also, what do you mean by the GTK Shell? There is no such thing.

Reinstalling OS completely from scratch. Breathless. No drivers and no network.
Same song with rawtherapee. I was just thinking - here it is! In general, everything is from scratch - now I’ll catch the problem. The network was turned off all this time - the cord was pulled out. No - the same song.
ok. I install this windows under a virtual machine. I launch the program - no problem!!!
That is. The idea was to somehow step by step in order to catch the culprit, but already at the first stage (if not under vm) we have a problem.

**Comment by estaf1001** [comment]
with GFLAGS.EXE

eventlog:
The process 'D:\Users\iron\Desktop\RawTherapee_5.10_win64_debug\rawtherapee.exe' terminated with exit code 3. The creation time for the terminating process was 0x01dad60e8b7489b7.

event id: 3000

The crash occurs when I switch between the program browser and the editor.
