### ISSUE TITLE
Default Local Adjustments Scope from 5.10 not used in dev

### ISSUE THREAD

**Issue by Lawrence37** [Beep6581/RawTherapee#7102]
**Short description**
When applying a pp3 from 5.10 with the Local Adjustments color tools Scope set to the default value of 30, the scopes of the individual tools are not set to 30.

**Steps to reproduce**
1. In 5.10, start with the Neutral profile.
2. Create a Local Adjustments spot and add the Color & Light tool.
3. Save the pp3.
4. In dev, apply the pp3. Observe the Color & Light tool's Scope is set to 15.

**Additional information**
The scope is properly set if it was saved with a value other than 30. Applying pp3s from dev works as expected. The issue only happens when applying a pp3 with the "Scope (color tools)" set to 30.

**Comment by Desmis** [comment]
@Lawrence37 

I will have a look

Jacques
