### ISSUE TITLE
Some jpeg files are treated as raw files

### ISSUE THREAD

**Issue by Lawrence37** [Beep6581/RawTherapee#7103]
**Steps to reproduce**
1. Apply the Neutral profile to https://raw.pixls.us/getfile.php/3648/nice/Nikon%20-%20Z%2050%20-%2012bit%20compressed%20(3:2).NEF and save a jpeg.
2. View the jpeg in the file browser. The thumbnail does not render correctly.
3. Open the jpeg in the editor. Notice the file is treated as a raw file.

**Additional information**
Possibly introduced in #6367 because it changed how files are decoded. It attempts to load images as raw files first, then tries other formats upon failure.

**Comment by xiota** [comment]
I wonder why JPG isn't rejected as raw.  I have a potential fix.  Tries to load imagio before raw.

Is it okay to add to #7096 or should it be a separate PR?

**Comment by Lawrence37** [comment]
A separate PR is better.
