### ISSUE TITLE
Add  panel with hue colors, luminance and saturation

### ISSUE THREAD

**Issue by ghost** [Beep6581/RawTherapee#7108]
I want to implement a color scheme of eight colors. And this:
red
orange
yellow
green
aqua
blue
purple
magenta

Implement the above using the HSL color model.

These colors span the entire color spectrum and offer a range of targeted settings to create all sorts of interesting effects.

Descriptions:

Hue moves the color you choose across the spectrum. This limits your choices to color boundaries (for example, when red can become orange).

The Saturation option lets you change the color intensity from monochromatic to extremely sharp. This is a great way to brighten colors or remove them altogether.

If we reduce the saturation to maximum, we will see that the red color almost completely disappears. This cool effect allows us to get creative with our photo editing.

Brightness changes the brightness of a color. This is similar to a tone adjustment, but only applies to the color you select. Similar to adjusting the tone, changing the brightness of a color will change its hue.

By editing the red to maximum brightness, we can see much more detail in the areas that were red.

How it works:
Tint: Adjusts the actual color of the photo.
Saturation: Increases or decreases the intensity of colors. Photos often appear more vibrant than the actual landscape because the colors in the photo are more saturated.
Brightness: Adjust the brightness of colors.

There are 100 steps for each color. Color range from -100 to 100.
Explanation: -100 dark areas of color, 0 - initial position, 100 light areas of color.

This depends on the image itself and affects saturation, hue and brightness.

Why did you choose this?

This is a subtle color correction tool that allows you to subtly change the colors of an image. Red colors can be finely adjusted including:
red
orange
yellow
green
aqua
blue
purple
magenta

And so with each color you can get something beautiful.

**Comment by Lawrence37** [comment]
Are you aware of the HSV Equalizer in the Color tab?

**Comment by ghost** [comment]
No

**Comment by Lawrence37** [comment]
It's pretty much exactly what you want. By default, there are 6 colors, but you can add more and put it in your default processing profile(s).
