### ISSUE TITLE
Selective Editing feather gradient from 5.10 not applied

### ISSUE THREAD

**Issue by Lawrence37** [Beep6581/RawTherapee#7113]
**Short description**
First noted here: https://github.com/Beep6581/RawTherapee/issues/7079#issuecomment-2170945774

When applying a pp3 from 5.10, the gradient feather does not get applied. Instead, the default value of 25 is used.

**Steps to reproduce**
1. Apply the attached pp3, or generate one with 5.10 by adding a new Local Adjustments spot with the feather gradient changed (to 77 for example), Color & Light tool added, and gradient strength set to a non-zero number.
2. Observe the feather gradient value in the Color & Light tool. It is 25, which is wrong.

[feather.pp3.txt](https://github.com/user-attachments/files/15948456/feather.pp3.txt)

**Comment by Desmis** [comment]
@Lawrence37 

Clearly I am unforgivable. I clearly saw and took into account your remark on the value 25 which is kept, but not corrected (probably the age).
I will reopen a PR

Jacques
