### ISSUE TITLE
Cannon EOS R6 Mark II - RAW colors off

### ISSUE THREAD

**Issue by JimmyS83** [Beep6581/RawTherapee#7117]
Hello,

RawTherapee 5.10, win11.
White Balance: Camera (from shot)

I am having big trouble with color balance. Get used to Samsung NX before, where **RAW** (SRW format) **and camera produced JPG was really close right off the bat in Rawtherapee (in terms of colors)**, so work with RAW was non problematic. Input profile used for Samsung NX: Standard.

But with CR3 from Cannon EOS R6 Mark II (for this example with standard 50mm / 1.8 STM Lens), with Standard input profile, I have yellowish colors. 
[photo removed]
[photo removed]

7C9A0095.JPG - [photo removed]
7C9A0095.CR3 - [photo removed]

I even tried profiles from Adobe DNG converters, which affect coloring, but non of the profiles looks as it should, but any of them have correct colors; well, colors matched cameras JPG (which has often best result in white balance matching).

EOS R6 m2 Adobe DCP's - https://fastupload.io/dc1a3ccd34001038

**Comment by JimmyS83** [comment]
I could try to work on some custom color profile, I should have color plate somewhere, but I believe that R6 Mark II is wide spreaded and used camera, so I believe this is just some bug or mismatch in the (draw) code?

**Comment by sgotti** [comment]
@JimmyS83 I don't see any issue here: it's just this: http://rawpedia.rawtherapee.com/Editor#Eek.21_My_Raw_Photo_Looks_Different_than_the_Camera_JPEG

Your jpeg image is the OutOfCamera jpeg already developed, with added contrast, color grading etc... 

If you use the Adobe DCP with all Tone Curve/Base table/LookTable options enabled you obtain an already good starting image with good colors that you can tweak as you like.

If you use the default matrix you have to define a tone curve (also read rawpedia) and the image is workable but requires more work since it just uses a basic matrix done for a d65 illuminant.

**Comment by JimmyS83** [comment]
> @JimmyS83 I don't see any issue here: it's just this: http://rawpedia.rawtherapee.com/Editor#Eek.21_My_Raw_Photo_Looks_Different_than_the_Camera_JPEG
> 
> Your jpeg image is the OutOfCamera jpeg already developed, with added contrast, color grading etc...
> 
> If you use the Adobe DCP with all Tone Curve/Base table/LookTable options enabled you obtain an already good starting image with good colors that you can tweak as you like.
> 
> If you use the default matrix you have to define a tone curve (also read rawpedia) and the image is workable but requires more work since it just uses a basic matrix done for a d65 illuminant.

Thank you for your response!

Yes, I am aware that RAW is unprocessed, but what is puzzling for me, when I use vanilla SRW from samsung, colors are really the same, with just default matrix.

_If you use the Adobe DCP with all_
Hmm, you mean this one?: `Canon EOS R6 Mark II Adobe Standard.dcp` (So far I was unable to obtain any other R6 m2 profiles except this from Adobe DN convertor. You can see other like 
![image](https://github.com/Beep6581/RawTherapee/assets/7437057/1ebeebf0-6ecd-4916-b9e7-148062e46280)
but when I use them, the colors are completelly off)


)? I am not sure, if some profiles are included or not within RT for this camera, I noticed just some crop settings added to json but didnt dig deeper.

_options enabled you obtain an already good starting image with good colors_
By enabling you mean just turn ON some processing panels? What about values, they are loaded from the RAW and setuped, just processing is turned OFF by default? Because for me it seems, that values are left on defaults. I tried to find BaseTable/LookTable, not sure what tools they are, regarding Tone Curve in Exposure I didnt see ON/OFF button basically. 

I will try to study more RAW pages in RT docs, but if you could point me what options should be enabled, after loading Adobe DCP (Adobe DCP with all Tone Curve/Base table/LookTable options enabled) it would be appretiated very much. I am feeling that I am not able to get these from the RAW, especially _with all_:

"_but usually this includes a custom tone curve, saturation boost, sharpening and noise reduction_"  ([Eek! My Raw Photo Looks Different than the Camera JPEG](https://rawpedia.rawtherapee.com/Editor#Eek.21_My_Raw_Photo_Looks_Different_than_the_Camera_JPEG))
After open CR3 file included here, I didnt see any Custom Tone curve option, or any Custom in Processing Profiles, so I feel like option two you describing, image is workable, but I must find quite a lot parameters, which should be already known and passed by camera.


The contrast/exposure/sharpening/denoise, this is all OK, I could manage it, as I see minor difference between vanilla RAW and camera JPG, and see the effects of tools to make JPG from RAW as I want, and as close to camera JPG if I want. But the colors is something which I wouldnt be able to figure out for these CR3 RAWs yet, and I feeling like the starting point is already wrong.. Happy to proove myself wrong, I just didnt find what color options (especially Processing Profile and Color Management-Input profile) should get me to correct starting point, which have correct coloring/curves from camera, from where the adjustmens would be more subtle and not feeling completelly groundbreaking :)

**Comment by sgotti** [comment]
@JimmyS83 We are going in a direction where probably a forum like https://discuss.pixls.us/ will be better for this beginner questions. 

> If you use the Adobe DCP with all Tone Curve/Base table/LookTable options enabled you obtain an already good starting image with good colors that you can tweak as you like.

From the neutral profile and with ONLY this (see the Tone Curve/Base table/LookTable enabled)

![image](https://github.com/Beep6581/RawTherapee/assets/1690273/568a9e41-e903-45f6-9287-faf34305d506)

you get this
~~removed image~~

That has right colors, then you should read the doc, tune exposure, enable highlight reconstruction (see the burned out window), denoise, tweak shadows/highlight with Tone Equalizer or Shadows/Highlights, add local contrast, color grade etc..

For all the other questions the suggested forum will be better (as I don't have time to answer on all of them) since this isn't a RawTherapee issue.

**Comment by JimmyS83** [comment]
Ah, DCP options, right, now I understand! Thanks! I mismatched _Curve_ term with 
![image](https://github.com/Beep6581/RawTherapee/assets/7437057/22032300-5b1d-4219-ad0a-0a5629d61afd)
from Exposure, where there are _Standard_ wording multiple times.. So now I now this "`Auto-Matched Tone Curve`" shouldnt be applied as it will rewrite Curve loaded from Adobe DCP's. And importantly, I should have chosen Neutral profile first, then load Camera's to have base. So the "reddish" look from camera JPG is postprocessing, not the wrong standard values.

I am still puzzled how it could work SO GOOD with Samsung NX camera - Maybe `auto-matched curve profile` using JPG inside Samsung's SRW, and in this CR3 it cant find JPG as efficiently as in Samsung case?

Regarding RT development, is there any chance or could I help with something, so the DCP's for this camera would be available from RT itself? I mean working automatically for example with
![image](https://github.com/Beep6581/RawTherapee/assets/7437057/b131e14f-2076-4c12-9ac8-c9819dc7d4c2), because clearly, standard profile didnt work well for this kind of camera?

I think custom DCP would work with correct naming, and placing file(s) to the folder, but I think it would be great, if that would be available for all users when they install/update RT. That could help many users with this camera, saving time to extract custom DCP from Adobe DNG or creating their own?  As I considering as [FEATURE], I post this reply here instead creating new thread in forum, hopefully its OK.

**Comment by sgotti** [comment]
> Regarding RT development, is there any chance or could I help with something, so the DCP's for this camera would be available from RT itself?

You can create and submit a well shaped DCP, much better if dual illuminant.

Everything is documented here: http://rawpedia.rawtherapee.com/How_to_create_DCP_color_profiles .

You have to create valid target images taken under the right conditions and then generate a DCP profile using dcamprof (it uses dcamprof Neutral tone reproduction operator to provide scene referred DCP profiles). You can also just provide the raw files and someone could create the DCP if you are unfamiliar with the command line.

Obliviously RawTherapee cannot distribute DCP profiles from Adobe.


> I am still puzzled how it could work SO GOOD with Samsung NX camera - Maybe auto-matched curve profile using JPG inside Samsung's SRW, and in this CR3 it cant find JPG as efficiently as in Samsung case?

This will require a deep analisys of the nx jpeg output, the matrix/dcp profile used etc... But I don't have time to do this. You could try it by yourself. But expecting the default rendering of the raw to be like the jpeg is a wrong expectation.

I think you can close this issue and open new ones or ask on the forum.

**Comment by JimmyS83** [comment]
Will do. I will try my best, if someone wouldnt be faster (I see that EOS R6 is already there).

The NX isnt need review/digging at all, it was just as mention to compare (to more understand, why I was surprized when I started using Canon HW)

**Comment by JimmyS83** [comment]
> > Regarding RT development, is there any chance or could I help with something, so the DCP's for this camera would be available from RT itself?
> 
> You can create and submit a well shaped DCP, much better if dual illuminant.
> 
> Everything is documented here: http://rawpedia.rawtherapee.com/How_to_create_DCP_color_profiles .
> 
> You have to create valid target images taken under the right conditions and then generate a DCP profile using dcamprof (it uses dcamprof Neutral tone reproduction operator to provide scene referred DCP profiles). You can also just provide the raw files and someone could create the DCP if you are unfamiliar with the command line.
> 
> Obviouly RawTherapee cannot distribute DCP profiles from Adobe.
> 
> > I am still puzzled how it could work SO GOOD with Samsung NX camera - Maybe auto-matched curve profile using JPG inside Samsung's SRW, and in this CR3 it cant find JPG as efficiently as in Samsung case?
> 
> This will require a deep analasys of the nx jpeg output, the matrix/dcp profile used etc... But I don't have time to do this. You could try it by yourself. But expecting the default rendering of the raw to be like the jpeg is a wrong expectation.
> 
> I think you can close this issue and open new ones or ask on the forum.

Will do. I will try my best, if someone wouldnt be faster, or with better equipment/photos (I see that EOS R6 is already in RT).

The NX doesnt need review/digging at all, it was just as mention to compare experience (to more understand, why I was surprized when I started using Canon HW)
