### ISSUE TITLE
Dynmamic range and exposure spot crashes a particular edit

### ISSUE THREAD

**Issue by chaimav** [Beep6581/RawTherapee#7121]
Using RawTherapee Dev 5.10-298 and editing the RAF image in this thread https://discuss.pixls.us/t/between-you-me-and-the-lamp-post/44334 
This pp3 in this post https://discuss.pixls.us/t/between-you-me-and-the-lamp-post/44334/28?u=chaimav crashes RT. Spot is named appropriately

![crash](https://github.com/Beep6581/RawTherapee/assets/47765782/456ffc97-0fd0-4557-929c-6f70112dfa47)

**Comment by Desmis** [comment]
@chaimav 

I confirm the bug, I'm looking, it might take a long time

Jacques

**Comment by chaimav** [comment]
If I get some free time, I plan on going through the rest of the PP3 and turning off things one at at time to see what the conflict is. The problem is, I need to re-open RT every time it crashes...

**Comment by Desmis** [comment]
I made a modification which should improve operation in the case where several Spots are used at the same time with "Dehaze" and "Dynamic Range & Exposure" > Exposure.

Exposure (in Selective Editing) has a capricious behavior, which meant that I added a Laplacian to it to reduce the fluctuations.

On many images, combining "Dehaze" and "Exposure DR" does not pose a problem. But with this image and numerous instances of "Dehaze" the Laplacian brings RGB values ​​out of bounds. Hence the crash.

I deactivated the Laplacian as soon as the user creates a Spot with Dehaze.
In addition, I took advantage, given the complexity of the "Contrast attenuator" tool, to reserve it for Advanced mode. Which simplifies the interface in basic mode.

As a reminder, I do not recommend using "Exposure (SE)". There are many other tools that are generally more efficient for processing images. But of course you can use it
https://rawpedia.rawtherapee.com/Local_Adjustments#Five_ways_to_change_the_exposure_and_lift_the_shadows

See also the latest advances regarding "Abstract Profile" (main) and  "Selective Editing - Cam16 - Source Data Adjustements".

Branch drexpos

I created a PR with executables - drexpos
https://github.com/Beep6581/RawTherapee/releases/tag/pre-dev-github-actions

**Comment by chaimav** [comment]
Thanks 👍. I have to admit that most of what you wrote went over my head (my understanding not your writing), but I am looking forward to testing the PR.

**Comment by chaimav** [comment]
I can confirm it no longer crashes.

**Comment by Desmis** [comment]
@chaimav 

I modified the way of controlling the Laplacian.
The previous change removed its use. Now I maintain the use but I control the RGB values. This seems much more relevant to me.

Can you check, the executables are being developed - drexpos
https://github.com/Beep6581/RawTherapee/releases/tag/pre-dev-github-actions

Jacques

**Comment by chaimav** [comment]
I can confirm that the new version does not crash. The biggest behavioral difference between the two is the transition from the clouds to the sky. Look at the upper left corner. I can't say if one is better or not, as the parameters can probably tweaked on either to achieve the desired effect. 

![DSCF9835-319](https://github.com/Beep6581/RawTherapee/assets/47765782/0ef110d8-e74a-40ef-9bab-1b027638eb91)
New build

![DSCF9835-311](https://github.com/Beep6581/RawTherapee/assets/47765782/de804e0d-8e3f-4f65-a296-70dc7b515a04)
Old build

**Comment by Desmis** [comment]
The only difference is:
The new version (build)  takes into account a Laplacian to ensure “smoother” transitions. This is what is in the basic "Dev" version, and which I removed to test if that was what was causing the problem.

The new version is like "dev" before, but now doesn't (hopefully) cause any more crashes.

Thank you for testing.

Jacques
