### ISSUE TITLE
The program fault unexpectedly

### ISSUE THREAD

**Issue by estaf1001** [Beep6581/RawTherapee#7127]
(Since the previous thread https://github.com/Beep6581/RawTherapee/issues/7101 in which I described this problem was closed (due to work, I did not have time to respond in time so that it would not be closed), I am creating a new post.)

If you try to minimize its window while a program is open, or switch to another application, the program unexpectedly “disappears”. As if this program had not been launched.

Open RT and work
Click on any tool that allows you to minimize the program window, or switch from it to any other application - Google Chrome, calculator, notepad, etc. Also, if you try to switch to the rawtherapee program window from another program, the program “disappears”
We see that its icon on the taskbar informs us that the program is not running.
In the task manager, in the list of processes, the program disappears in the same way.
Version of RawTherapee: 5.10
Version of operating system: windows 10 21h2 ltsc, windows 10 22h2 professional.
Hardware: i7-12700K/rtx4070 12GB/32GB ram/1
The problem occurs when opening any raw file.
The problem occurs even if you reinstall the operating system from scratch.
RAM tested using memtest 86+ program.

There are no problems with any other programs on the computer. No problem.
Installed other programs:
Davinci Resolution (not a studio);
Adobe Photoshop, Lightroom, acr, Adobe Bridge (photo subscription);
xvid4psp encoder;
3dlut creator.

log one by gdb
https://github.com/user-attachments/files/15838429/log.txt

I will be guided by user Lawrence37's post https://github.com/Beep6581/RawTherapee/issues/7101#issuecomment-2184160634

"Thanks. The program exited purposefully, but obviously not in the normal way. I don't think this is an issue coming from RawTherapee itself, but here is what you can try to confirm and get clues on what told RawTherapee to close. Repeat the steps to get the log, but between steps 2 and 3, run this command:

catch syscall exit_group

This will tell gdb to halt the program when it is about to close and it will make step 6 provide more useful information."

Result

"C:\Users\iron>cd /d D:\Users\iron\Desktop\RawTherapee_5.10_win64_debug

D:\Users\iron\Desktop\RawTherapee_5.10_win64_debug>gdb rawtherapee.exe
D:\Users\iron\Desktop\RawTherapee_5.10_win64_debug\gdb.exe: warning: Couldn't determine a path for the index cache directory.
GNU gdb (GDB) 10.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-w64-mingw32".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from rawtherapee.exe...
**(gdb) catch syscall exit_group
The feature 'catch syscall' is not supported on this architecture yet**.
(gdb)"

**Comment by Lawrence37** [comment]
No need to open a new issue. You can still comment on the old one. It's preferable to comment there to avoid fragmenting the conversation.
