### ISSUE TITLE
New icon for Selective Editing

### ISSUE THREAD

**Issue by Lawrence37** [Beep6581/RawTherapee#7129]
The current icon for the Selective Editing tab is the open hand: ![hand-open](https://raw.githubusercontent.com/Beep6581/RawTherapee/64dce38c3335a095348690cbd9e363e017d44140/rtdata/icons/rawtherapee/scalable/apps/hand-open.svg)
To avoid confusion, the toolbar icon for the hand tool was changed to the high contrast version: ![hand-open-hicontrast](https://raw.githubusercontent.com/Beep6581/RawTherapee/64dce38c3335a095348690cbd9e363e017d44140/rtdata/icons/rawtherapee/scalable/apps/hand-open-hicontrast.svg)

The problem is that the high contrast icon doesn't fit in with the other icons. I propose restoring the hand tool icon and giving the Selective Editing tab a new icon. The RT spot is an important aspect of Selective Editing, so my idea for an icon is an RT spot:
![rt-spot](https://github.com/user-attachments/assets/a9e041d6-cfde-4ec0-a68e-56e862b02319)

**Comment by Benitoite** [comment]
Good idea as the hand icon is usually used for a canvas panning tool.

**Comment by Desmis** [comment]
Good idea 

Jacques

**Comment by rebio** [comment]
I assume with "Selective Editing" you mean _Local Adjustments_.
If so: I think it's a good idea as I never associated a hand with a tool with which you apply changes to only a part of the image. 

I thought about these ones:
The icons would all represent the image (square) and partially adjusted areas (square and circle with dashed line).
(These images are just a quick drawing with GIMP that I could also turn into SVG files with Inkscape)
1. Two effected areas
![RT - local adjustments - icon idea 01](https://github.com/user-attachments/assets/582b8e76-c752-4638-95be-ccfac2723feb)
2. Effected area with console for adjustments. One version is with circular control elements, the other one is with with rectangle control elements.
![RT - local adjustments - icon idea 02a](https://github.com/user-attachments/assets/17e8e7a5-aae7-4df1-8165-e0b31b234692)
![RT - local adjustments - icon idea 02b](https://github.com/user-attachments/assets/f619b87f-f96f-4be7-9e39-348aeabe212c)
3. Effected area worked on with a wrench
![RT - local adjustments - icon idea 03](https://github.com/user-attachments/assets/a2620e22-1dec-4a3d-bde0-07f707e9b605)
4. Effected area combined with a gear
![RT - local adjustments - icon idea 04](https://github.com/user-attachments/assets/bde398d3-d670-40b5-a2e0-8d58268e7dfd)
5. Effected area combined with a nob to control it
![RT - local adjustments - icon idea 05](https://github.com/user-attachments/assets/d7e00cbf-4b67-4e1e-8950-1097ba81885b)

I just combined a few idea I found on Google that look far better in their original versions (eg. [this one](https://www.shutterstock.com/de/image-vector/settings-icon-set-containing-options-configuration-2254713121) and [this one](https://www.shutterstock.com/es/image-vector/vector-isolated-settings-icons-set-162599585)).

**Comment by Lawrence37** [comment]
Thanks for the suggestions @rebio. Keep in mind the icon is very small: only 24x24 pixels on standard DPI screens. Fine details such as dashed lines may not show up well. In my suggestion, the ellipse and circle are only 1 pixel thick. The control points are 3 pixels in diameter. That's very small!

**Comment by Benitoite** [comment]
A dashed rectangular area selection tool icon would be nice if there were such a tool but there is no such functionality in RT.  The ![rt-spot](https://private-user-images.githubusercontent.com/45837045/348575225-a9e041d6-cfde-4ec0-a68e-56e862b02319.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExODA1ODgsIm5iZiI6MTcyMTE4MDI4OCwicGF0aCI6Ii80NTgzNzA0NS8zNDg1NzUyMjUtYTllMDQxZDYtY2ZkZS00ZWMwLWE2OGUtNTZlODYyYjAyMzE5LnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDAxMzgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxZmFmYTFjNjU1MjZiZDFhYThjYmIwZDZiMmRjZGFlNjZmMDA1ZDE2ZjU5N2VjYmQ4OTg1NWVhNGY0NzljZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2ggf8ohzaE3c1H3khZDuIc0b33ufeZuc87Di1Gao-JY) local spot icon works better for me because it actually resembles the interface.

**Comment by Desmis** [comment]
At the time (many years ago) I (with Pierre Cabera) looked for another icon among the existing ones. This one suited well.
But I don't know how to create png/svg files. Considering the size it has to be simple.

**Comment by marter001** [comment]
how about a kind of asterisk?

**Comment by rebio** [comment]
> Keep in mind the icon is very small: only 24x24 pixels on standard DPI screens. Fine details such as dashed lines may not show up well.

@Lawrence37  I know. I made the files bigger on purpose to a) be easier to draw and b) easier to see what should be in the file. I just created several ideas without caring about if they would look good as small icons (more to get ideas rolling and not straight up limiting improvable first drafts and creativity)

> ![rt-spot](https://private-user-images.githubusercontent.com/45837045/348575225-a9e041d6-cfde-4ec0-a68e-56e862b02319.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExODA1ODgsIm5iZiI6MTcyMTE4MDI4OCwicGF0aCI6Ii80NTgzNzA0NS8zNDg1NzUyMjUtYTllMDQxZDYtY2ZkZS00ZWMwLWE2OGUtNTZlODYyYjAyMzE5LnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDAxMzgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxZmFmYTFjNjU1MjZiZDFhYThjYmIwZDZiMmRjZGFlNjZmMDA1ZDE2ZjU5N2VjYmQ4OTg1NWVhNGY0NzljZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2ggf8ohzaE3c1H3khZDuIc0b33ufeZuc87Di1Gao-JY)

@Benitoite This file does not seem to exist or to be empty. When I look at this file I only see an svg file with 0 Byte. (Or do I just have not enough (user) rights to see it?)

**Comment by Benitoite** [comment]
@rebio sorry I was trying to second the one by @Lawrence37 :
![IMG_2447](https://github.com/user-attachments/assets/eef61efb-80f1-4c17-8f0b-a66b674f6d35)

**Comment by marter001** [comment]
the RT-spot looks very nice, but it also looks very close to the icon of "advanced-tab" when reduced to 24px
proposing a different shape:
![grafik](https://github.com/user-attachments/assets/95e26f91-5d51-4fdf-8397-c915b524f194)

**Comment by Benitoite** [comment]
hmmm, if asterisk, I'd like to see more of a Polaris design, to have some representation of the interface function.
<img src="https://github.com/user-attachments/assets/ff74a9ec-403a-424c-94f1-adf829397d91" width=24>

**Comment by marter001** [comment]
@Benitoite, this really looks good!

Inverted it fits perfectly:
![grafik](https://github.com/user-attachments/assets/ddb565ff-c069-4e41-876d-048d78a29851)

**Comment by Benitoite** [comment]
mock-up: <img src="https://github.com/user-attachments/assets/02a2bf7a-3be5-4157-857d-855ef24a44b2" width=500>

**Comment by Benitoite** [comment]
drop-in replacement of `hand-open.svg`
![Screen Shot 2024-07-20 at 1 33 08 AM](https://github.com/user-attachments/assets/3f52acf4-045e-41b3-bfac-04a3b7df9fa8)
![Screen Shot 2024-07-20 at 1 58 24 AM](https://github.com/user-attachments/assets/9e0ad9ba-d98a-4579-984e-fc9f45b8b2db)

with the icon:
https://gist.github.com/Benitoite/acdbb3873ee3daccac04edecf77c6c48#file-polaris-optimizd-svg

**Comment by Lawrence37** [comment]
@marter001 If the RT spot looks too similar to the atom, then I can change it to the rectangle shape. What does the asterisk represent?

Here's a comparison using the lightest background color (TooWaGrey - Average Surround theme) at standard DPI and HiDPI (2x).
|24x24|48x48|
|-|-|
|![rt-spot-ellipse-24x24](https://github.com/user-attachments/assets/96530fcb-c19f-4518-b0fc-2d209266e9cf)|![rt-spot-ellipse-48x48](https://github.com/user-attachments/assets/f2d4c699-fa00-4d2c-adf8-f5348e589663)|
|![rt-spot-rectangle-24x24](https://github.com/user-attachments/assets/dc5115fe-8055-460d-9051-857d7a5764cf)|![rt-spot-rectangle-48x48](https://github.com/user-attachments/assets/c4fc588a-0ba7-4d58-844d-958c62fe1332)|
|![polaris-optimized-24x24](https://github.com/user-attachments/assets/bae43c2f-e910-4fcf-a835-248c4d76ef64)|![polaris-optimized-48x48](https://github.com/user-attachments/assets/4c3fef9a-5b20-46e8-a8b1-d7b75efd57c5)|

**Comment by marter001** [comment]
@Lawrence37 your examples 2 and 3 look very good! I am not insisting in an asterisk, my proposal was targeting a total different shape than the existing tab icons. 
The polaris version, you and @Benitoite created, reminds me of an enlightening spot with transition masking, so, me personally would prefer it against a square RTspot. 
Anyway, its only my humble opinion and i am also fine with the RTspot, you proposed.

**Comment by Lawrence37** [comment]
The Polaris symbol is based on your suggestion for an asterisk. The reason I asked was to understand how the icon relates to selective editing. It should be intuitive to the user or be easy to learn the association between the icon and the tab. If I were a user who didn't read this thread, I don't think I would have noticed the similarities between the Polaris symbol and the RT spot and transition.

**Comment by Benitoite** [comment]
This is outside the box, but I'd personally recommend switching the advanced tab's "atom" icon with a tiny bessel curve, to represent wavelets.  Maybe that would allow for the eliptical spot icon.

<img src="https://gist.githubusercontent.com/Benitoite/acdbb3873ee3daccac04edecf77c6c48/raw/8dac2f407954378b971557e0cf3c32822e12be1f/bessel.svg" width=24>

**Comment by Benitoite** [comment]
<img src="https://gist.githubusercontent.com/Benitoite/acdbb3873ee3daccac04edecf77c6c48/raw/8dac2f407954378b971557e0cf3c32822e12be1f/bessel.svg" width=24>

**Comment by marter001** [comment]
@Lawrence37 youre right, not having read this thread can lead to totally different view on an icon: me personally would recognize the RTspot-Icon as a possibility to create some "frames" to the pic.

Now @Benitoite presents a new idea which i like very much: the atom for advanced was good, but selective editing also is kind of advanced.  
BTW:  @Desmis whats your preference to the icon for selective editing?
