### ISSUE TITLE
Cannot interact with UI (Linux)

### ISSUE THREAD

**Issue by 2-3-5-41** [Beep6581/RawTherapee#7136]
**Short description**
After installing through Flatpak, Appimage, and Package Manager on Arch, RawTherapee opens as expected, but I can not interact with any UI element, including the close button. This is similar to a frozen or crash on start app, but it's not closing unless I force close it through system monitor.

**Steps to reproduce**
1. Install Arch Linux
2. Install KDE Plasma (Wayland) / Gnome (Wayland)
3. Install RawTherapee
4. Fail to interact with app, including ability to close.

**Expected behavior**
I'm expecting to be able to do as what's described by users and the wiki.

**Additional information**
- RawTherapee 5.10
- Arch Linux LTS 6.6.40-1-lts

Not built from source, installed through Flatpak, Appimage, and package manager, all three attempts resulted in same behavior, and to clarify, it's not crashing, it's just behaving as if it's frozen but no "not responding" message is displayed from my desktop environment.

**Comment by rebio** [comment]
I can not reproduce this bug on my KDEneon machine with KDE Plasma 6.1.2 running under Wayland.
I installed RT 5.10 via Flathub and it works fine for me - so it might be Arch specific.

@2-3-5-41 Did you also try the [nightly Appimage](https://github.com/Beep6581/RawTherapee/releases/tag/nightly-github-actions)?

**Comment by 2-3-5-41** [comment]
Turns out I just needed to let my computers sit overnight with the app installed and try again in the morning, because now it's working.

Extremely odd, but it's nothing new to me at this point with bugs and technical issues.

**Comment by kaesa** [comment]
Sounds similar to this issue (#7064). If you rename the .config/RawTherapee maybe you can reproduce the issue.
