### ISSUE TITLE
DEV branch: Applying a partial processing profiles resets all other settings and clear automatched tone curve

### ISSUE THREAD

**Issue by kaesa** [Beep6581/RawTherapee#7138]
**Short description**

Creating a partial processing profile, for example only crop. Then applying the profile to another picture with existing edits. All existing edits reset and also, the auto matched tone curve is cleared. I have not tested to see if it matters what settings are saved into a partial profile. The issue exists at least with crop data and user comments/copyrights in EXIF data.

**Steps to reproduce**

1. Create a custom crop in a RAW image.
2. Save the crop by pressing CTRL while selecting the save icon from processing profiles.
3. Check only the checkbox for crop.
4. Open another RAW or DNG file.
5. Load the partial processing profile.

**Expected behavior**

Only the crop should be applied.

**Additional information**

<details><summary>Details</summary>
<p>

Version: 5.10-313-g64dce38c3
Branch: dev
Commit: 64dce38c3
Commit date: 2024-07-06
Compiler: cc 14.1.1
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: 3.24.8
Lensfun: 0.3.4.0
libjxl: 0.10.2
Build type: Release
Build flags:  -std=c++11 -ffp-contract=off  -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wno-attributes -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags:   
OpenMP support: ON
MMAP support: ON
Build OS: Linux 5.15.161-1-MANJARO x86_64
Build date: Sat, 13 Jul 2024 16:16:35 +0000 UTC
Build epoch: 1720887395
Build UUID: 673c0450-6af3-424a-8344-70783a2479c2

</p>
</details>

**Comment by Lawrence37** [comment]
Cannot reproduce on `dev`. Did you make sure the processing profile fill mode is set to preserve instead of fill?
https://rawpedia.rawtherapee.com/Sidecar_Files_-_Processing_Profiles#Partial_Processing_Profiles_and_Fill_Modes

**Comment by kaesa** [comment]
That was the problem. I'm sorry for creating this false report. Somehow I completely missed that feature even when checking the wiki before writing this.
