### ISSUE TITLE
Add support for Canon CR3 Raw Burst picture selection and extraction

### ISSUE THREAD

**Issue by Weltherrscher** [Beep6581/RawTherapee#7143]
Some newer Canon EOS cameras with DIGIC X can use a feature named "RAW Burst Mode".
It basically means that the cam already starts taking pictures while the trigger is half pushed.
They are stored in the CR3 file like some sort of RAW video sequence (picture roll).
Right now, only Canons DPP software and the cam itself can change the "starting" picture and extract the other pictures from the sequence.
Known Cams to support this feature are: R1, R3, R5m2, R6m2, R7, R8, R10...

Currently, RAW Therapee doesnt show these files in the file browser.

My feature request is therefore:
- please add support for these files (i can supply demo files from a Canon R6 Mark II)
- add support for changing the 1st picture
- add support for extracting other RAW pictures from the sequence

**Comment by Lawrence37** [comment]
>i can supply demo files from a Canon R6 Mark II

Please do. You can use filebin.net to share the files if you don't have another way to upload them.

**Comment by Weltherrscher** [comment]
I shot 2 little sequences:
1st one is 40 pics (about 600 MB)
2nd one is smaller with 17 pics (about 250 MB)

sequence 1
IMG_0686.CR3 -> picture roll (40 pictures, trigger picture is 16)
IMG_0687.CR3 -> 16 (trigger pic)
IMG_0688.CR3 -> 25 (in camera extracted pic after pushing trigger fully down)
IMG_0687.CR3 -> 10 (in camera extracted pic from pre shot while pushing trigger only half down)
IMG_0686_12.CR3 -> 12 (DPP extracted pic from pre shot)
IMG_0686_16.CR3 -> 16 (DPP extracted trigger pic)
IMG_0686_20.CR3 -> 20 (DPP extracted pic after trigger)

sequence 2
IMG_0692.CR3 -> picture roll (17 pictures, trigger picture is 06)
IMG_0693.CR3 -> 06 (trigger pic)
IMG_0694.CR3 -> 01 (in camera extracted pic from pre shot while pushing trigger only half down)
IMG_0695.CR3 -> 07 (in camera extracted pic after pushing trigger fully down)
IMG_0692_01.CR3 -> 01 (DPP extracted pic from pre shot)
IMG_0692_06.CR3 -> 06 (DPP extracted trigger pic)
IMG_0692_07.CR3 -> 07 (DPP extracted pic after trigger)

Files are at:
https://nitroflare.com/folder/2026231/L11JBVyBCdXJzdCBkZW1vIGZpbGVz

**Comment by Lawrence37** [comment]
Here's a preliminary patch that enables selection of any sub-image when using LibRaw. 5.11 only allows frames 2-7 to be selected with LibRaw. Decoding will have to be added to dcraw to make it work without LibRaw. The frame limit was there to fix a bug with Hasselblad pixelshift images (see #5433).

```diff
diff --git a/rtengine/rawimagesource.cc b/rtengine/rawimagesource.cc
index ab2ee58e6..310e70f00 100644
--- a/rtengine/rawimagesource.cc
+++ b/rtengine/rawimagesource.cc
@@ -505,13 +505,15 @@ RawImageSource::~RawImageSource()
     delete greenCache;
     delete blueCache;
 
-    for (size_t i = 0; i < numFrames; ++i) {
+    for (size_t i = 0; i < riFrames.size(); ++i) {
         delete riFrames[i];
     }
+    riFrames.resize(0);
 
-    for (size_t i = 0; i + 1 < numFrames; ++i) {
+    for (size_t i = 0; i < rawDataBuffer.size(); ++i) {
         delete rawDataBuffer[i];
     }
+    rawDataBuffer.resize(0);
 
     if (camProfile) {
         cmsCloseProfile(camProfile);
@@ -1219,11 +1221,13 @@ int RawImageSource::load(const Glib::ustring &fname, bool firstFrameOnly)
         return errCode;
     }
 
-    numFrames = firstFrameOnly ? (numFrames < 7 ? 1 : ri->getFrameCount()) : ri->getFrameCount();
+    bool isHasselblad = ri->get_maker() == "Hasselblad";
+
+    numFrames = firstFrameOnly ? (numFrames < 7 && !isHasselblad ? 1 : ri->getFrameCount()) : ri->getFrameCount();
 
     errCode = 0;
 
-    if (numFrames >= 7) {
+    if (numFrames >= 7 && isHasselblad) {
         // special case to avoid crash when loading Hasselblad H6D-100cMS pixelshift files
         // limit to 6 frames and skip first frame, as first frame is not bayer
         if (firstFrameOnly) {
@@ -1237,6 +1241,7 @@ int RawImageSource::load(const Glib::ustring &fname, bool firstFrameOnly)
 #endif
         {
             int errCodeThr = 0;
+            riFrames.resize(numFrames);
 #ifdef _OPENMP
             #pragma omp for nowait
 #endif
@@ -1264,6 +1269,7 @@ int RawImageSource::load(const Glib::ustring &fname, bool firstFrameOnly)
 #endif
         {
             int errCodeThr = 0;
+            riFrames.resize(numFrames);
 #ifdef _OPENMP
             #pragma omp for nowait
 #endif
@@ -1287,9 +1293,12 @@ int RawImageSource::load(const Glib::ustring &fname, bool firstFrameOnly)
             }
         }
     } else {
+        riFrames.resize(1);
         riFrames[0] = ri;
         errCode = riFrames[0]->loadRaw(true, 0, true, plistener, 0.8);
     }
+    rawDataFrames.resize(riFrames.size());
+    rawDataBuffer.resize(riFrames.size() - 1);
 
     if (!errCode) {
         for (unsigned int i = 0; i < numFrames; ++i) {
diff --git a/rtengine/rawimagesource.h b/rtengine/rawimagesource.h
index 7296b830f..2457d622a 100644
--- a/rtengine/rawimagesource.h
+++ b/rtengine/rawimagesource.h
@@ -21,6 +21,7 @@
 #include <array>
 #include <iostream>
 #include <memory>
+#include <vector>
 
 #include "array2D.h"
 #include "colortemp.h"
@@ -78,13 +79,13 @@ protected:
     bool rgbSourceModified;
 
     RawImage* ri;  // Copy of raw pixels, NOT corrected for initial gain, blackpoint etc.
-    RawImage* riFrames[6] = {nullptr};
+    std::vector<RawImage *> riFrames;
     unsigned int currFrame = 0;
     unsigned int numFrames = 0;
     int flatFieldAutoClipValue = 0;
     array2D<float> rawData;  // holds preprocessed pixel values, rowData[i][j] corresponds to the ith row and jth column
-    array2D<float> *rawDataFrames[6] = {nullptr};
-    array2D<float> *rawDataBuffer[5] = {nullptr};
+    std::vector<array2D<float> *> rawDataFrames;
+    std::vector<array2D<float> *> rawDataBuffer;
 
     // the interpolated green plane:
     array2D<float> green;
@@ -203,10 +204,10 @@ public:
     static void init ();
     static void cleanup ();
     void setCurrentFrame(unsigned int frameNum) override {
-        if (numFrames == 2 && frameNum == 2) { // special case for averaging of two frames
+        if (numFrames == 2 && frameNum == 2 && riFrames.size() >= 1) { // special case for averaging of two frames
             currFrame = frameNum;
             ri = riFrames[0];
-        } else  {
+        } else if (riFrames.size() > std::min(numFrames - 1, frameNum)) {
             currFrame = std::min(numFrames - 1, frameNum);
             ri = riFrames[currFrame];
         }
diff --git a/rtgui/bayerprocess.cc b/rtgui/bayerprocess.cc
index 5ef3a777c..f89e11510 100644
--- a/rtgui/bayerprocess.cc
+++ b/rtgui/bayerprocess.cc
@@ -745,7 +745,7 @@ void BayerProcess::FrameCountChanged(int n, int frameNum)
 
             imageNumber->remove_all();
             imageNumber->append("1");
-            for (int i = 2; i <= std::min(n, 6); ++i) {
+            for (int i = 2; i <= n; ++i) {
                 std::ostringstream entry;
                 entry << i;
                 imageNumber->append(entry.str());
```
Screenshot showing the sub-image selection for image IMG_0692.CR3:
![image](https://github.com/user-attachments/assets/c8d08ebf-4cc5-4dd2-9d51-1d80290a0075)

**Comment by Weltherrscher** [comment]
Indeed i missed the 5.11 Release because i were on holidays...
Since that, the film rolls are detected.
I patched and compiled the 5.11 Release myself and now it works flawlessly with all pictures in the roll. =)
(altough i had to manually change the bayerprocess.cc, since the patch failed, but this could be at my end...)
Well done, thank you!

How to extract the RAW pictures from the roll?

**Comment by Lawrence37** [comment]
If by "extract" you mean creating cr3s with individual sub-images, I think it will require much more work. The sub-images are probably not stored as individual cr3s, which means RawTherapee would need to create a new cr3 file and embed the sub-image in it, along with making sure the metadata is correct. RawTherapee won't be able to create cr3s in the near future, if ever.

**Comment by Weltherrscher** [comment]
Ok, understood.
For the workflow it isn't necessarily needed to have a CR3 as intermediate. I personally can work with the 16bit png or 16bit tif.
But it would be nice to have some sort of slider inside RawTherapee to quickly jump between the subpics to compare and select the best focused subpic.

But thats another feature request. =)
