### ISSUE TITLE
Fuji S3: lost highlights

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#715]
Originally reported on Google Code with ID 726

```
Dev-3.1m5.13

RT is not able to recover vast amount of highlight data in FUJI S3 RAF files.
```

Reported by `michaelezra000` on 2011-06-07 03:49:17

**Comment by Thanatomanic** [comment]
No longer relevant as far as I can tell. The only S3 sample raw with overexposure I can find looks as good as you may expect using the available HR methods of RT.
