### ISSUE TITLE
Selective Editing - Dynamic Range & Exposure crash

### ISSUE THREAD

**Issue by Benitoite** [Beep6581/RawTherapee#7151]
@Desmis, et al.:
I am able to crash RawTherapee with this sequence of edits:

**Steps to reproduce**
1. Download and open this jpeg with RawTherapee-`dev`: <img src="https://github.com/user-attachments/assets/24002b10-37b2-4f77-b890-38117294aba7" width=100 align=middle>
2. Activate Selective Editing
3. Add a spot
4. Add the Dynamic Range & Exposure tool to the spot
5. Raise the Dynamic Range Compensation slightly
6. Expand the Exposure Tools
7. Raise the Black slider to the highest setting
8. Lower the Dynamic Range Compensation all the way down.
9. Program crashes:
```
Crashed Thread:        30

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x00007f83c0210000
Exception Codes:       0x0000000000000001, 0x00007f83c0210000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [81800]
```
```
Thread 30 Crashed:
0   rawtherapee                   	       0x10147aa21 .omp_outlined..31.17778 + 9089
1   libomp.dylib                  	       0x101ef3d83 __kmp_invoke_microtask + 147
2   libomp.dylib                  	       0x101ea6bbd __kmp_invoke_task_func + 367
3   libomp.dylib                  	       0x101ea5aa9 __kmp_launch_thread + 383
4   libomp.dylib                  	       0x101edb0b6 __kmp_launch_worker(void*) + 278
5   libsystem_pthread.dylib       	    0x7ff80cb024e1 _pthread_start + 125
6   libsystem_pthread.dylib       	    0x7ff80cafdf6b thread_start + 15
```

**Expected behavior**
n/a

**Additional information**
RawTherapee current `dev` macOS 12.5.7 *Monterey* x86_64
Downgrading libomp 18 -> 11 produces same crash
Threads number in Preferences>Performance has no effect

**Comment by Desmis** [comment]
@Benitoite 

Effectively it crash...
It's the same problem as #7121 

I think I have fixed this crash with the PR #7122 
I added another control, on Dynamic Range and black

Executables ( in progress)

https://github.com/Beep6581/RawTherapee/releases/tag/pre-dev-github-actions

I hope it's good.

Jacques

**Comment by Desmis** [comment]
I just change a new version 
commit 80141cf

**Comment by Benitoite** [comment]
Thanks, I didn't realize this was related.  #7122 is working for me, appreciate you having a look at this!
