### ISSUE TITLE
Updated Dutch translation v3

### ISSUE THREAD

**Issue by paulmatthijsse** [Beep6581/RawTherapee#7156]
For RawTherapee 5.11.
[Nederlands.txt](https://github.com/user-attachments/files/16400726/Nederlands.txt)

**Comment by Benitoite** [comment]
If this issue supersedes the other two versions, you may want to close those, offering any further updates to only this one issue.

**Comment by Lawrence37** [comment]
Thanks @paulmatthijsse! I opened a pull request with your translations. If I'm seeing correctly, this has all the updates from the previous two versions you provided, correct? I will close those issues.

**Comment by paulmatthijsse** [comment]
Hello @Benitoite and @Lawrence37,

Sorry to bother you with my ignorance.

Yes those translations v2 and v3 are incremental updates to v1. 
I am planning to upload more updates over the coming months. 
Is the following the right procedure? 
I edit my latest issue v3, delete the file Netherlands.txt and add a new text file, which is v4, then v5, etc.?

Thanks.

**Comment by Benitoite** [comment]
The Pull Request #7158 contains your latest update and is now "staged" for integration into the code base.  Once that happens this issue will close automatically and you may raise a new issue with further updates.   

If you need to update the version currently in the Pull Request, and it is still open, you can request that either in this still-open issue or on the still-open Pull Request itself. 

Also as 5.11 will come out soon™️, the Pull Request will be merged sooner than later.

**Comment by paulmatthijsse** [comment]
Thanks Richard, that's clear.

**Comment by Lawrence37** [comment]
If you have new translations this or next week, I suggest uploading them here so they can be included in 5.11. We are most concerned about translations for releases, so for 5.12/6.0 and beyond, it is ok to upload large translations instead of multiple incremental updates.

**Comment by paulmatthijsse** [comment]
Thanks Lawrence. The Dutch translations I sent are about the interface (tools, sliders, Preferences, etc.). 

But I started to translate all Jacques' tooltips in Dutch as well, also in order to better understand what this CieCAM thing is about. This will certainly not be ready in one or two weeks, so I'll attach a major update later. 

Kind regards,
Paul.
