### ISSUE TITLE
Dev branch: Geometric distortion correction not avaiilable with Sony A7II in combination with Sigma 150-600 Contemporary for Canon EF mount.

### ISSUE THREAD

**Issue by kaesa** [Beep6581/RawTherapee#7171]
**Short description**

Geometric distortion correction not available with Sony A7II in combination with Sigma 150-600 Contemporary for Canon EF mount. Lens is adapted using Sigma MC-11.

**Steps to reproduce**

1. Open the example file with RawTherapee
2. Select the correct lens profile manually. Sigma 150-600 DG OS HSM Contemporary.
3. Observe that the Geometric corrections remain grayed.
4. You may further test, selecting None will not impact the image.

**Expected behavior**

Geometric corrections should be available. They are available for Canon EOS R10 camera. They are available in Darktable, though I don't know what Darktable thinks the lens is as they don't show any details.

**Additional information**

<details><summary>Details</summary>
<p>

Version: 5.10-370-gcc0e94165
Branch: dev
Commit: cc0e94165
Commit date: 2024-07-28
Compiler: cc 14.1.1
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: 3.24.8
Lensfun: 0.3.4.0
libjxl: 0.10.2
Build type: Release
Build flags:  -std=c++11 -ffp-contract=off  -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wno-attributes -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags:   
OpenMP support: ON
MMAP support: ON
Build OS: Linux 5.15.162-1-MANJARO x86_64
Build date: Sun, 28 Jul 2024 09:52:36 +0000 UTC
Build epoch: 1722160356
Build UUID: 6ee6b6e2-c9bb-4357-95c4-0354b572da69

</p>
</details> 

Example file at
https://filebin.net/fzzyqjfxp2tllp29

**Comment by kaesa** [comment]
I figured Darktable uses embedded metadata. Their lensfun implementation seems weaker than in RT and doesn't show the lens at all. However, the lens data is available for canon cameras.

**Comment by Benitoite** [comment]
Similar to lensfun issue 1003 https://github.com/lensfun/lensfun/issues/1003

**Comment by kaesa** [comment]
That issue is about detecting the lens. The report has already assumed the lens is manually chosen. Do you mean that the geometric corrections checkbox is not available because the database lacks an entry for the converter?

**Comment by Benitoite** [comment]
The compatibility between the Sigma 150-600 C and the Sony E mount is not known by the database. In lensfun#1003 they recommend using `lensfun-add-adapter` to enable the connection between the body and lens requiring adaptation.

https://github.com/lensfun/lensfun/blob/ebfbe426c9a012ae6c626ee371c7ee404f8e4b13/data/db/slr-sigma.xml#L3473

**Comment by kaesa** [comment]
Thank you. That indeed allowed the geometric corrections to be applied. I wonder why it worked out of the box with EOS R10 though.

I think the program should still consider falling back to the "from file metadata" option, which applied geometric corrections correctly, if the "Automatically selected" fails. Or another graceful way to handle the condition, which I suspect is not very uncommon.

**Comment by Benitoite** [comment]
Regarding the lens on an R10, lensfun knows about the adaptability between Canon EF and RF mounts, 

https://github.com/lensfun/lensfun/blob/d38928e988946f4d97c2bee05980534eae2a1a26/data/db/mil-canon.xml#L18

and the lens has been measured at the same crop factor 1.613.

https://github.com/lensfun/lensfun/blob/d38928e988946f4d97c2bee05980534eae2a1a26/data/db/slr-sigma.xml#L3640

**Comment by kaesa** [comment]
Closing this report as the corrections work after either manually choosing embedded data or after selecting the lens manually and using the lensfun-add-adapter utility.
