### ISSUE TITLE
Dev branch: Lens not automatically detected. Sony A7II with Tamron 24mm f2.8 Di III OSD M1:2 for Sony FE

### ISSUE THREAD

**Issue by kaesa** [Beep6581/RawTherapee#7172]
**Short description**

Lens Tamron 24mm f2.8 Di III OSD M1:2 for Sony FE is not automatically selected with Sony A7II

**Steps to reproduce**

1. Open the supplied example file.
2. Observe the lens is not detected
3. Select the lens manually (Tamron E 24mm F2.8)

**Expected behavior**

The lens should be automatically selected. Alternatively, the corrections should be read from the file metadata.

**Additional information**

<details><summary>Details</summary>
<p>

Version: 5.10-370-gcc0e94165
Branch: dev
Commit: cc0e94165
Commit date: 2024-07-28
Compiler: cc 14.1.1
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: 3.24.8
Lensfun: 0.3.4.0
libjxl: 0.10.2
Build type: Release
Build flags:  -std=c++11 -ffp-contract=off  -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wno-attributes -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags:   
OpenMP support: ON
MMAP support: ON
Build OS: Linux 5.15.162-1-MANJARO x86_64
Build date: Sun, 28 Jul 2024 09:52:36 +0000 UTC
Build epoch: 1722160356
Build UUID: 6ee6b6e2-c9bb-4357-95c4-0354b572da69

</p>
</details> 

Example file at:
https://filebin.net/fzzyqjfxp2tllp29

**Comment by Benitoite** [comment]
FYI:

1. `Tamron E 24mm F2.8` is an APS-C lens.
2. Your lens was detected as:
![IMG_2566](https://github.com/user-attachments/assets/0dc8782c-9498-4697-9ffd-6e7aa38f78c4)
3. model F051 is not currently a part of the [tamron lensfun database](https://github.com/lensfun/lensfun/blob/release_0.3.x/data/db/mil-tamron.xml) timestamped `1645386247`. (Sunday, February 20, 2022 7:44:07 PM GMT)
4. The Tamron 24mm f2.8 Di III OSD M1:2 is for Sony *E* mount.

**Comment by kaesa** [comment]
The Tamron 24mm f2.8 Di III OSD M1:2 is for full frame Sony E mount. Tamron does not have a separate lens for crops sensor.

However, do you think the program should fallback to the embedded data when the automatic method fails or do you think this issue is entirely third party problem?

**Comment by Benitoite** [comment]
Talking database here, the entry called `Tamron E 24mm F2.8` was measured on an APS-C body. 
https://github.com/lensfun/lensfun/blob/ebfbe426c9a012ae6c626ee371c7ee404f8e4b13/data/db/mil-tamron.xml#L494

Not sure which program falls back to embedded data, but the full frame and APS-C geometries are not compatible.

**Comment by kaesa** [comment]
Ok I understand.

- The Darktable uses the embedded, applies the corrections and does not allow selecting the lens.
- The RawTherapee goes by default to the automatic, but doesn't select the lens. The lens can be selected manually and the corrections that will get applied, match visually to the embedded option.

**Comment by Benitoite** [comment]
The lens in question hasn't been measured on a full frame body.  I'm not sure there is a meaningful result in applying the lens as measured in APS-C?

**Comment by kaesa** [comment]
Getting straight lines is meaningful even if the corrections are not correct. I understand what you're saying though.

I don't know what the embedded data refers to. If that data is also wrong, there is indeed a problem for corrections.

**Comment by sgotti** [comment]
> * The Darktable uses the embedded, applies the corrections and does not allow selecting the lens.

@kaesa Also rawtherapee dev (use the latest git version, now at commit 79279bc42c7a85aaa463e51d6950e9bee3a19eae, not the one you have reported) handles sony embedded metadata correction (to be used instead of lensfun data).

![image](https://github.com/user-attachments/assets/08e8e021-4199-49be-8df4-c0dff58cfbbe)

![image](https://github.com/user-attachments/assets/f73ea8f9-fcf4-4184-8157-97ba43eaf6bb)

**Comment by Benitoite** [comment]
@kaesa I tried the body/lens combo with [the jpeg capture from LensTip](https://www.lenstip.com/586.6-Lens_review-Tamron_24_mm_f_2.8_Di_III_OSD_M_1:2_Distortion.html)
The orthorectilinearity looked a-ok, maybe off by a tenth of a percent, but not enough to be noticible.

**Comment by kaesa** [comment]
There was some uncleanliness with the build. I did full clean and rebuild and it is now in:
<details><summary>Details</summary>
<p>

Version: 5.10-382-g79279bc42
Branch: dev
Commit: 79279bc42
Commit date: 2024-08-04
Compiler: cc 14.1.1
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: 3.24.9
Lensfun: 0.3.4.0
libjxl: 0.10.3
Build type: Release
Build flags:  -std=c++11 -ffp-contract=off  -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wno-attributes -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags:
OpenMP support: ON
MMAP support: ON
Build OS: Linux 5.15.163-1-MANJARO x86_64
Build date: Tue, 06 Aug 2024 08:06:37 +0000 UTC
Build epoch: 1722931597
Build UUID: b3f1e6e9-a564-469a-b176-e7f7e0c71ba0


</p>
</details>

I deleted the pp3 files and the .cache/RawTherapee directory. It is still defaulting to "Automatically selected". Is this the design or there is something still messed in my build/installation?

I tried opening the file in verbose mode. Here is the text output:
<redacted>

**Comment by sgotti** [comment]
> There was some uncleanliness with the build. I did full clean and rebuild and it is now in:
> Details
> 
> I deleted the pp3 files and the .cache/RawTherapee directory. It is still defaulting to "Automatically selected". Is this the design or there is something still messed in my build/installation?
> 
> I tried opening the file in verbose mode. Here is the text output: [verbose.txt](https://github.com/user-attachments/files/16507850/verbose.txt)

@kaesa  Is your message directed to me or @Benitoite or a generic information?

Sorry but you are too cryptic and I cannot understand what is your question without more context and details.

**Comment by kaesa** [comment]
@sgotti It was directed at you. My question is. Are the embedded corrections intended to be used by default or is it intended that the user selects the option manually?

Sorry for not writing clearly.

**Comment by sgotti** [comment]
> It was directed at you. My question is. Are the embedded corrections intended to be used by default or is it intended that the user selects the option manually?

> it is still defaulting to "Automatically selected"

@kaesa 

1. As far as I know in rawtherapee by default no correction is enabled (`Profiled Lens Correction` -> `Lens Profile` -> `None` is selected). If you have one kind of correction enabled by default for new images you probably have a Dynamic Profile Rule that applies a profile with `Automatically Selected` set.

2. I don't understand if, with the latest build, you have "From file metadata" available and working if enabled.

**Comment by kaesa** [comment]
@sgotti

1. Ok I understand. I thought the "Automatically selected" is a program default operation because I don't remember ever applying any settings for this thing.

2.  Yes. It is working correctly.

What I assumed was that if there are good corrections, those would be applied by default. This is not the design so I will close this and the other report.

About the dynamic profile rules though, I don't know where to find it because I have tested with brand new .config/RawTherapee and .cache/RawTherapee as well as deleting all the pp3 files next to the files. It still always opened with "Automatically selected" option enabled.

**Comment by sgotti** [comment]
> About the dynamic profile rules though, I don't know where to find it

@kaesa 

* Open settings
* Go to the tab called "Dynamic Profile Rules". You'll find a table. If empty then you don't have any dynamic profile rule set.

**Comment by kaesa** [comment]
@sgotti

Thank you. It is empty.
