### ISSUE TITLE
tone mapping doesn't react, when extras -  color model appearance is set to CAT02, but deactivated.

### ISSUE THREAD

**Issue by marter001** [Beep6581/RawTherapee#7177]
RT 5.10-dev-384, Windows 10

How to recreate this issue:

start with a neutral profile 
goto tab extras-color appearance
set model to CAT02
deactivate color appearance
goto tab exposure - tone mapping
activate tone mapping set intensity to 2.00 - nothing happens

goto tab extras-color appearance
set model to CAT16
deactivate color appearance
goto tab exposure - tone mapping
activate tone mapping set intensity to 2.00 - tone mapping is applied

Expected behaviour: tone mapping should be applied anyway.
If color appeareance is deactivated, its settings should not influence other functions.

**Comment by Desmis** [comment]
@marter001 
I will have a look soon

Jacques

**Comment by Desmis** [comment]
@marter001 

I think I've found a palliative in the branch "cam02_activ"

Jacques
