### ISSUE TITLE
Results on Red and Blue channel swap differ from most other editors

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#718]
Originally reported on Google Code with ID 729

```
What is the problem?
In infrared photography, when shooting with a 700nm filter you get bluish grey foliage
and reddish brown sky after doing a white balance eye dropper tool in foliage.
After that we do a red and blue channel swap in channel mixer, to give us bluish sky
and reddish white foliage. However, in RAW Therapee, it gives a greenish sky. So channel
swapping just red and blue channels is actually resulting in different results, than
the results you would get if you used GIMP or any other editor like photshop.
What steps will reproduce the problem?
1. Open an IR RAW file
2. Select white balance on foliage
3. Swap red and blue channels

If you see my attached files, after channel swap the sky is greenish.
Gimp gives totally different result, with bluish sky instead of greenish.
I suspect channel swap is leading to some hue adjustment
To replicate, maybe you could paint a custom blue and red canvas, and see if swapping
red and blue channels shifts hue or not?
Click on the Preferences icon (top-right corner) > About > Version, and
paste all that here.
Branch: default
Version: Dev-3.1m5.8
Changeset: 72fbb5342ebf
Compiler: GCC 4.5.2
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V2.22.0
Build type: RELEASE
Build flags:  -mtune=generic -O2 -DNDEBUG
Link flags:  -mtune=generic -mwindows
OpenMP support: ON
MMAP support: ON
Rawzor support: OFF

Operating system and architecture (e.g. winXP-32, ubuntu-10.10-64):


All files over 50kB excluding patches should be referred to with
links, please do not use this site's "Attach a file" feature because space
is limited. Use http://imgur.com/ for images and http://min.us/ for other
files.

```

Reported by `tanveer1979` on 2011-06-07 18:54:44

**Comment by LAK132** [comment]
Channel swapping still seems to be weird in 5.9. In `preview red channel` mode, adjusting green-in-green or blue-in-blue in the channel mixer will affect the visible output of the red channel (same effect happens regardless of which combination of channels are being previewed/edited). 

`Preview red channel` mode examples (note how the preview gets darker):
![image](https://github.com/Beep6581/RawTherapee/assets/1386467/dec4491f-78d0-4d78-9778-291e9d56013a)
![image](https://github.com/Beep6581/RawTherapee/assets/1386467/d407a6ad-b049-4a0a-9df8-51eaef98cd82)
![image](https://github.com/Beep6581/RawTherapee/assets/1386467/4b18ab6e-4e6e-4b7f-afd6-78ef985eeda8)
![image](https://github.com/Beep6581/RawTherapee/assets/1386467/fdef4e12-3988-440f-be42-164fe95a71a1)

**Comment by Lawrence37** [comment]
@LAK132 The Channel Mixer operates on the working profile whereas the channel preview uses the display profile.

**Comment by LAK132** [comment]
Setting the working, output and display profiles all to sRGB or all to Adobe RGB makes no difference

Edit: but maybe that's just colour space clipping, will investigate further
