### ISSUE TITLE
RT 5.11 AppImage outputs errors in terminal on Linux Mint 22

### ISSUE THREAD

**Issue by ghost** [Beep6581/RawTherapee#7191]
On my Mint 22 PC, I downloaded the `RawTherapee_5.11_release.AppImage` and made it executable. When I ran it from a terminal it output a message about failing to load module "xapp-gtk3-module", plus several 'undefined symbol' errors.

```
richardt@Pavilion:~/Applications/rawtherapee_5.11 $ ll
total 124248
-rw-rw-r-- 1 richardt richardt 127222976 Sep  1 07:32 RawTherapee_5.11_release.AppImage
richardt@Pavilion:~/Applications/rawtherapee_5.11 $ 
richardt@Pavilion:~/Applications/rawtherapee_5.11 $ chmod 774 RawTherapee_5.11_release.AppImage 
richardt@Pavilion:~/Applications/rawtherapee_5.11 $ ll
total 124248
-rwxrwxr-- 1 richardt richardt 127222976 Sep  1 07:32 RawTherapee_5.11_release.AppImage
richardt@Pavilion:~/Applications/rawtherapee_5.11 $ ./RawTherapee_5.11_release.AppImage 
Gtk-Message: 08:20:34.376: Failed to load module "xapp-gtk3-module"
/usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so: undefined symbol: g_assertion_message_cmpint
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
/usr/lib/x86_64-linux-gnu/libproxy/libpxbackend-1.0.so: undefined symbol: g_strv_builder_unref
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiolibproxy.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgiognomeproxy.so: undefined symbol: g_uri_is_valid
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiognomeproxy.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so: undefined symbol: g_source_set_static_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so
/usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so: undefined symbol: g_task_set_static_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so
/usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so: undefined symbol: g_task_set_static_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so
richardt@Pavilion:~/Applications/rawtherapee_5.11 $ 
```

However, the main window did appear and displayed the File Browser and Editor OK under limited testing. 

What functionality will these errors affect?

Note: I have been successfully building the latest dev branch on Mint 22 for several weeks and it doesn't output any error messages in the terminal.

**Comment by ghost** [comment]
The `Failed to load module "xapp-gtk3-module"` message also occurs when I click on the Help button on the main window. However the RawPedia main page does then get displayed in my web browser.

I also get the following warning a couple of seconds after opening a photo in the editor for the first time since starting the app:

```
** (AppRun.wrapped:38425): WARNING **: 13:25:54.724: atk-bridge: get_device_events_reply: unknown signature
```

This warning doesn't appear when I do the same thing in the dev build.

**Comment by Lawrence37** [comment]
xapp seems like a Mint thing, so it probably has no effect on RawTherapee functionality. The undefined symbol errors can be ignored because the program starts up. Not sure about the unknown signature, but it is just a warning. Running a self-built version will not have these messages because it is built specifically for your system.

**Comment by ghost** [comment]
Thanks for your reassuring reply. I did a lot more testing after I raised this issue and didn't find any problems viewing and editing photos from different cameras. I am happy to close this now.
