### ISSUE TITLE
[Feature] Adjust sliders using scroll wheel

### ISSUE THREAD

**Issue by MinePro120** [Beep6581/RawTherapee#7193]
Hello. I find myself cycling through my LUTs in the film simulation tool quite often. It would be way easier if I could do this cycling by using the scroll wheel, while the cursor hovers over the LUT drop-down menu. The same could be applied to any slider for that matter. This is the approach GIMP uses. Inkscape on the other hand seems to enable the scrollwheel to change a slider, only when the numeric value on the side of the slider is clicked (and hovered). Either way, especially for LUTs in a folder, I think it would be quite useful.

**Comment by rgcmce** [comment]
For a slider, place the cursor over the slider, press shift and use the scroll wheel.  Or am I not understanding the request?

**Comment by Lawrence37** [comment]
To cycle through LUTs, you can use the up and down keys.

**Comment by MinePro120** [comment]
I didn't know shift was required, that's exactly what I wanted. Works for LUTs as well.
