### ISSUE TITLE
Profile picker GUI glitch in Windows

### ISSUE THREAD

**Issue by Krzysiu** [Beep6581/RawTherapee#7194]
**Short description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

Hey! I'm about to report low profile, not really important glitch. When I'm opening profile picker (the dropdown list in top-right corner) it's weirdly scrolled down like this:
![obraz](https://github.com/user-attachments/assets/724cb814-9f55-4b2e-822e-7bb7127f99da)
The space below is just empty, no invisible menu items (at least it can't be selected).

But when I scroll it up, scroll arrows disappear, so I see all profiles at once (this is also the expected behavior).
![obraz](https://github.com/user-attachments/assets/5a617e86-3ca0-4095-870e-026f345d229a)

On Linux Mint, it's fine:
![obraz](https://github.com/user-attachments/assets/4415f4fb-a01d-483a-a993-53f055d1426b)

After seeing that, I got the idea it might be because relatively large font, but changing it from 11 to 9, does nothing. Changing theme also doesn't help.

Because that to use profiles from the top I need to scroll every time I open this widget. When I choose the profile (or close it by clicking elsewhere) and click again, it's scrolled down again. 

You may notice I got bundled profiles hidden, but it happens with or without that. Maximizing window doesn't affect this glitch.

Technical info:
* RT 5.11 (last stable build from the website, but it happens probably since switching to new GTK, so long time ago).
* Windows 10 19045.4842 Windows Feature Experience Pack 1000.19060.1000.0
* 1920x1080, standard DPI/scaling (i.e. 100%)

**Comment by Lawrence37** [comment]
I think this is just the way GTK behaves. The menu opens with the currently-selected option over where the button is so that the mouse cursor is over the current selection. If the selected option is very low or high on the list, then there could be empty space because the list must be scrolled very far.

**Comment by Krzysiu** [comment]
Yeah (precisely "This is fundamentally an accessibility feature"[1]), but even if, there could be some workaround.

[1] https://gitlab.gnome.org/GNOME/gtk/-/issues/270

**Comment by pyrareae** [comment]
To be honest this would be worth adding some kind tree view panel in the ui as an alternative/replacement to this stock gtk dropdown element. This drop down behavior is honestly really obnoxious when trying out multiple presets and it would be nice to be able to have a list that could be left open.

For example this is how Lightroom displays presets. Which to me is seems to be a better UX.
![image](https://github.com/user-attachments/assets/697eaef3-c608-4edc-8913-cc5c06aa738f)

**Comment by Lawrence37** [comment]
@pyrareae Please keep it to one topic per issue. Open a new issue if one does not already exist. For your request, there is already #3043.

**Comment by pyrareae** [comment]
Oh wow, I was looking through the issue and didn't even see that one

**Comment by Lawrence37** [comment]
The GTK folks don't want to change the behavior, and it would be unwise to try to work around it (potential bugs, maintenance issues, etc.). I am closing this until something new comes up.
