### ISSUE TITLE
Add support for simplest debayer algorythm (Superpixel)

### ISSUE THREAD

**Issue by 4uma96** [Beep6581/RawTherapee#7198]
Superpixel mean just write 4 RGGB subpixels in 1 RGB pixel.
No interpolation, no artifacts, low resolution, nature look, don`t need sharp. 
Demosaic for oversample images.

Why it make sense?
Modern matrix has 48,..200 megapixels, but in quad- nona- tetra- etc bayer. (matrix for binning use)
In that case vendors use Remosaic for return their RRRRGGGGGGGGBBBB to RGGB RGGB RGGB RGGB.
In quadbayer result is some synthetic, but not bad at this point.

When we try to interpolate it usual debayer methods, debayer over remosaic got really terrible results.
Results than has`t sense. It very synthetic look.

If we make superpixel over remosaic, like 48 in 12, it look significant better than usual debayer 12 mp.
(can make example if need)
And it very simple algorythm, so, i hope it will not be difficult to implement it.

**Comment by kmilos** [comment]
What raw file has this output?

**Comment by 4uma96** [comment]
> What raw file has this output?

Ow, raw quadbayer, if i understand correctly? RRRRGGGGGGGGBBBB?
It is difficult to find it, only by modifying the smartphone libraries.

And it's not important, because Superpixel debayer is about usual RGGB sequence.

**Comment by Lawrence37** [comment]
An example would be helpful. I don't quite understand what the algorithm is or what it does. Is the algorithm for n-bayer (n- is quad, nona, etc.) color filter arrays only?

**Comment by 4uma96** [comment]
> An example would be helpful. I don't quite understand what the algorithm is or what it does. Is the algorithm for n-bayer (n- is quad, nona, etc.) color filter arrays only?

[Find some descriptoin.](https://telescope.live/blog/pixinsight-debayer-demosaicing-process-explained)
![TLStory Superpixel](https://github.com/user-attachments/assets/7d693bca-59b4-49b8-a388-8001ac1978f9)

It useful for standart bayer and quadbayer.
![SuperStandart](https://github.com/user-attachments/assets/631b2b95-cda1-4131-b7a0-8bd46036d0d4) ![SuperQuad](https://github.com/user-attachments/assets/472928d3-5920-4476-9ce1-d7d2a94f26e3)

(I ask only for standart bayer)

**Comment by Lawrence37** [comment]
Thanks for the explanation. This enhancement request has been made in #5536. The discussion stopped with an unanswered question of what real-world advantages the proposed demosaic method has over the existing methods. Closing this issue as a duplicate.
