### ISSUE TITLE
Join / merge selective editing regions

### ISSUE THREAD

**Issue by Krzysiu** [Beep6581/RawTherapee#7201]
Sorry if that was already proposed, I did my best to search for it. 

My proposition is to be able to merge multiple regions 
![obraz](https://github.com/user-attachments/assets/4c1cf611-4554-467d-85e7-86c90b1ccf7e)
As you can see, it has three, overlapping regions. As they add exposure, they are adding each other, causing white "highlights" with draker regions.
![obraz](https://github.com/user-attachments/assets/35b21c49-382e-4779-b1a2-f8708b432f5a)
This one has less shadowy parts, but the white blobs are even more visible.

One more example, without lines, which shows IMO more clearly what's the problem:
![obraz](https://github.com/user-attachments/assets/6bee8208-f845-408e-8f16-f612a9d4b25f)

I think this tool is too great to be constrained by two shapes.

What I propose is that (one of these, sorted from seemingly simplest to the most robust):
1) **regions could be merged into one** by simple text box with group name - shapes in single group woks as single region ||
2) ability to create shape from beizer curves ||
3) shapes could be imported SVG shape ||
4) the same, but with changed logic - two level tree, where there's effect as 1st level and it can contain many 2nd level regions (see picture below) 

![obraz](https://github.com/user-attachments/assets/15e61de3-5bd4-4c03-8fd0-a191d0c4a90e)

**Comment by Lawrence37** [comment]
> ability to create shape from beizer curves

See #5409.

**Comment by Lawrence37** [comment]
Closing as a duplicate.
