### ISSUE TITLE
Crash while computing minimum raw value of Canon Dual Pixel image

### ISSUE THREAD

**Issue by Lawrence37** [Beep6581/RawTherapee#7213]
Attempting to load a Canon Dual Pixel raw image results in a crash in `dev`.

This happens during the computation of the minimum raw value, which is used for raw de-haze. In this line, `rawData` is empty, so attempting to get the pixel value fails.
https://github.com/Beep6581/RawTherapee/blob/00360a6dbb060587a300d809594c756069fda75b/rtengine/rawimagesource.cc#L8545

I used an image obtained from raw.pixls.us. The web page is down, and I can't upload the image because I don't remember the license for this particular file.

**Comment by Weltherrscher** [comment]
I could provide some examples. Give the sun some time to settle, then i shoot 2..3 pictures.
//Edit:
![image](https://github.com/user-attachments/assets/22dda43f-a7c4-4f48-bc24-8cd369d2fc62)
No Crash on my end.
Compiled the latest git.

**Comment by Lawrence37** [comment]
After some more testing, this happens due to the handling of the selected sub-image number. Select SN mode for the sub-image, then reload the image in the editor. The crash does not happen if sub-image 1 or 2 is selected. I also tried with pixel shift images. They crash unless sub-image 1 is selected. Canon burst images work fine though.

**Comment by Weltherrscher** [comment]
Indeed, that way it crashes.
That's a bad crash, after setting SN mode it is impossible to open DP-Raws again until the corresponding pp3 is deleted.

**Comment by Lawrence37** [comment]
It's possible to use the batch edit tab to change the sub-image to 1 or 2. The image can then be opened in the editor without deleting the processing profile.
