### ISSUE TITLE
Green color cast in shadows on Canon images using electronic shutter

### ISSUE THREAD

**Issue by kedga** [Beep6581/RawTherapee#7214]
**Short description**
Shadows in raw images taken with Canon R8 in electronic shutter mode exhibits a strong green color cast. Especially noticeable if the image is taken at a low ISO (like 100) and has been brightened in RawTherapee (using exposure compensation for example). But also visible in shadow areas in some unbrightened images. RawTherapee is the only raw image processor that I have tested that exhibits this behavior.

**Steps to reproduce**
Take 2 identical (ideally somewhat underexposed) images, one using electronic shutter and the other using mechanical shutter, bring into RawTherapee and brighten them.

**Expected behavior**
The image taken using electronic shutter is expected to have considerably more noise in the shadows, but the overall color tone should not be different from the image taken using mechanical shutter.

**Additional information**
I'm using windows 10, RawTherapee 5.10

Comparison with Capture One (but could be any other raw processing software; they all seem to handle this fine):
![C1 vs RT electronic shutter](https://github.com/user-attachments/assets/93d860d7-ad8c-4988-8178-78ddafc1832f)

Raw images that can be used for reproducing/testing the issue: https://filebin.net/iyrmuf6iem9sup0p

**Comment by Lawrence37** [comment]
Reproducible with the dcraw decoder. Loads fine with LibRaw enabled.

**Comment by Lawrence37** [comment]
The black level is incorrectly read as 517 instead of 512. Setting all the raw black points to -5 removes the color cast, confirming the bad black level is causing the issue.

**Comment by Lawrence37** [comment]
@kedga Does it happen in crop mode too? If it does, can you provide a sample file so I can fix it for the crop mode too?

**Comment by kedga** [comment]
@Lawrence37 From what I can tell it doesn't seem to happen in crop mode

**Comment by Lawrence37** [comment]
Thanks for verifying! #7249 will fix the issue.
