### ISSUE TITLE
Minor Bug/Typo in xtrans_demosaicing?

### ISSUE THREAD

**Issue by Jaysmito101** [Beep6581/RawTherapee#7222]
**Short description**
Recently while going through the source of the xtrans_demosaicing (https://github.com/Beep6581/RawTherapee/blob/dev/rtengine/libraw/src/demosaic/xtrans_demosaic.cpp) I noticed something I think might be a bug,

On line 85
https://github.com/Beep6581/RawTherapee/blob/00360a6dbb060587a300d809594c756069fda75b/rtengine/libraw/src/demosaic/xtrans_demosaic.cpp#L85
It has :
```
int v = orth[d] * patt[g][c * 2] + orth[d + 1] * patt[g][c * 2 + 1];
int h = orth[d + 2] * patt[g][c * 2] + orth[d + 3] * patt[g][c * 2 + 1];
minv = MIN(v, minv);
maxv = MAX(v, maxv);
minh = MIN(v, minh);
maxh = MAX(v, maxh);
```     
Which I think is a minor bug/typo. Can somebody please confirm.

What I propose is (https://github.com/Beep6581/RawTherapee/compare/dev...Jaysmito101:RawTherapee:dev) :
```
int v = orth[d] * patt[g][c * 2] + orth[d + 1] * patt[g][c * 2 + 1];
int h = orth[d + 2] * patt[g][c * 2] + orth[d + 3] * patt[g][c * 2 + 1];
minv = MIN(v, minv);
maxv = MAX(v, maxv);
minh = MIN(h, minh);
maxh = MAX(h, maxh);
```     

What I understand is this could easily be overlooked as the values are only used 
https://github.com/Beep6581/RawTherapee/blob/00360a6dbb060587a300d809594c756069fda75b/rtengine/libraw/src/demosaic/xtrans_demosaic.cpp#L98
where it seems to be a very rare case for this to actually cause a problem, but might have some edge cases.

Disclaimer: At the time of writing this I do not understand the algorithm fully yet, so I might be wrong about something.

Relevant thread: https://github.com/LibRaw/LibRaw/issues/673

**Comment by Lawrence37** [comment]
RawTherapee doesn't use any of LibRaw's demosaicing routines, so we'll let LibRaw handle it however they want.
