### ISSUE TITLE
[Feature request] Crop/resize to a specific focal length/sensor size

### ISSUE THREAD

**Issue by makerbeleg** [Beep6581/RawTherapee#7234]
User inputs current focal length (taken from exif by default)
Current sensor size (full frame, aps-c, medium formats etc, custom (field to enter sensor dimensions))
Target focal length (by default same as current)
Target sensor size (full frame, aps-c, medium formats, custom (field to enter sensor dimensions), or crop factor (1 by default)). By default same as current.

As result crop to a specific format (with ability to move cropped space around the frame) or resize (if crop factor less than 1) with empty space filling with neutral color.

**Comment by Lawrence37** [comment]
Thanks for sharing your idea. May I ask what the use cases are? It seems fairly niche. I can see a subset of the functionality could be used to crop images where the lens was designed for sensors smaller than the camera that took the picture (such as using APS-C lenses on full-frame cameras). I don't know when it would be useful to consider the focal length or allow expansion of the image size.

**Comment by makerbeleg** [comment]
To simulate look of certain lens on certain format and also to see how scene would look with different lenses and different formats.

E.g. I took picture on 24mm (or even phone, before bringing actual camera) and would like to see how certain details would look with my 105 or 200mm lens. Or, in case of resize, how picture would look fov wise with my 24mm lens but taken on 50mm.

And, in case of film, how picture taken on 35mm camera would look on 6 x 6 or 6 x 9 medium format camera, or even more extreme 6 x 17, with different lenses.

Also I see this more like a separate tool rather than enhancement of a crop.

**Comment by Lawrence37** [comment]
Such a feature is not related to image editing and does not facilitate image editing. Unfortunately, it is outside the scope of RawTherapee.
