### ISSUE TITLE
Weird behaviour of the Channel Mixer tool

### ISSUE THREAD

**Issue by teplit** [Beep6581/RawTherapee#7238]
When the red, green and blue channels are set to 10 in the following way via the Channel Mixer tool, nothing happens:
Red channel ->     (10,   0,   0)
Green channel -> (   0, 10,   0)
Blue channel ->    (   0,   0, 10)

Here (a, b, c) means that the red component is a, the green component is b and the blue component is c.
With other values close to ten, like 9 or 11, the image becomes dark as expected.

Tested with RawTherapee 5.10 on Windows 11 (24H2).

**Comment by Lawrence37** [comment]
Thank you for reporting the issue! It will be fixed with #7239.
