### ISSUE TITLE
Magenta cast on photos with iso 128000 or higher.

### ISSUE THREAD

**Issue by makerbeleg** [Beep6581/RawTherapee#7252]
**Short description**
Magenta cast on photos when shot on iso 128000 or higher on Sony.

**Expected behavior**
Similar color balance to photos shot on iso 102400 or lower

**Additional information**
Not related to tint value in color balance.
This behavior I had at least since 5.9.
![2024-11-14-221159_1920x1080_scrot](https://github.com/user-attachments/assets/83a6ea51-4dab-434f-82f6-830bc915b177)
![2024-11-14-221203_1920x1080_scrot](https://github.com/user-attachments/assets/0824b409-cac2-4b2d-b914-a8e236e12bae)

default pp profile [default.pp3.txt](https://github.com/user-attachments/files/17756647/default.pp3.txt)

iso102400 https://drive.google.com/file/d/1xmzHSddzO72E3xsShitqnpuwH7_EuoVs/view?usp=sharing
iso128000 https://drive.google.com/file/d/1_E10wbgv-6GJ1eDy-AwScK3vVOoqCpkp/view?usp=sharing

**Comment by Lawrence37** [comment]
The black level at ISO 128000 is 1024 instead of 512 which is what RawTherapee uses for all ISOs. Could you also provide sample images for every ISO above 128000 so I can confirm the black levels?

**Comment by makerbeleg** [comment]
iso 80000 - 204800
https://drive.google.com/file/d/18aT-hSq0dRnvM812MK94kkv0O0rF-Gzs/view?usp=sharing

**Comment by Lawrence37** [comment]
Thanks! It looks like the black level is 1024 for all ISO 128000 and higher.
