### ISSUE TITLE
traduction incomplète en français

### ISSUE THREAD

**Issue by rtuo47** [Beep6581/RawTherapee#7262]
**Short description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

**Comment by rtuo47** [comment]
Bonjour,
J'ai installé RawTherapee 5.11 en français. 
Constat 90 % des libellés et aides sont en français mais 10 % sont toujours en anglais !
Par exemple : menu Exposition  Ombres/ hautes lumières puis Tone Egalizer dont tout le contenu est en anglais.
Il y a d'autres  menus avec le même problème, ainsi qu'une partie des préférences.
Après désinstallation puis un nouveau téléchargement le problème persiste.
A quand la correction du bug ou une nouvelle version de la traduction en français ?
Merci.

**Comment by Lawrence37** [comment]
The French translation is incomplete. If a translation is missing, English is used. There is no timeline for adding the missing translations since RawTherapee is developed by volunteers.
