### ISSUE TITLE
Preview not applying transition value in selective editing

### ISSUE THREAD

**Issue by graphikeye** [Beep6581/RawTherapee#7270]
**Short description**
When changing the transition value in selective editing the AE Preview does not update accordingly

**Steps to reproduce**
1. Open new image
2. Add selective editing spot ellipse
3. Add tool "Color & Light"
4. Enable AE Preview
![rawtherapee_Gnc8Q7OnFz](https://github.com/user-attachments/assets/11834905-8373-419d-8eba-7878a7d34839)
![rawtherapee_KkBmTmSwqY](https://github.com/user-attachments/assets/4b2d5323-8989-4a6d-904a-cb80b9e5d660)

5. Change transition value

The transition value is working, it's just the preview isn't reflecting it.

**Comment by Lawrence37** [comment]
@Desmis can confirm, but I do believe the deltaE (ΔE) preview button is intended to show only the deltaE selection, which is affected by the scope and shape detection values, but not the transition gradient. There doesn't seem to be a way to show the combined effect of the deltaE, advanced mask, and transition gradient.

**Comment by Desmis** [comment]
@graphikeye  @Lawrence37 

The DeltaE preview only shows, as its name suggests, the incidence of deltaE.
If you want to see the action of the transitions, you must be in "Standard" or "Advanced" mode and use "Mask and modifications" as below.


![image](https://github.com/user-attachments/assets/d56b4c65-6382-4fee-8a3e-fc9d4e75c2ed)

**Comment by graphikeye** [comment]
This makes sense. I understand how the tool works now. Thanks.
