### ISSUE TITLE
Automatic lens correction with Fujifilm X-T200

### ISSUE THREAD

**Issue by fischer-felix** [Beep6581/RawTherapee#7272]
As the title says, the Fujifilm X-T200 is not available to select in the Profiled Lens Correction menu.

I have been using the profile for the X-T30 and X-T100 instead, which produced good results, so maybe this could be linked somehow.

Sadly I was not able to figure out how to add this myself, however if anyone could give me some pointers, I am more than happy to assist in any way I can.

Running RawTherapee 5.11 on Arch Linux

**Comment by Lawrence37** [comment]
Lensfun does not have the X-T200 yet. The only important data about the camera is the crop factor, so choosing any camera with the same crop factor will result in the right corrections.
